### ISSUE TITLE
[Routing] SSL Feature Request

### ISSUE THREAD

**Issue by trsteel88** [symfony/symfony#10092]
I have a multi tenancy website where some domains have SSL enabled and others don't.

I basically want to be able to set schemes: [https] on all of my routes. However, if I do that, they all automatically redirect. I really need a way to only set the schemes to ssl on specific hosts.

Is there a simple solution to this that I am missing?

**Comment by Tobion** [comment]
Closing as you can use the expression for that. You need to check the host and the scheme inside the expression. This means you cannot use the `schemes` option directly but have to do it manually. So redirecting and scheme recognition on URL generating will not be automatically supported.
Otherwise you need to find some other workaround, like I proposed, to group routes and set the schemes on them explicitly.
Also this issue is to vague, neither bug, nor concrete feature request that can be implemented.
