### ISSUE TITLE
[3.0] [Form] IntegerType accepts floats - a bit misleading

### ISSUE THREAD

**Issue by jameshalsall** [symfony/symfony#10240]
The [`IntegerType`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/IntegerType.php) supports floats, but as the name suggests it should only accept integers, i.e. whole numbers.

The [`NumberType`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/NumberType.php) supports floats, locale specific numeric strings (e.g. "40,000") etc. 

I propose a change to these 2 types:
- `IntegerType`: should be used for whole integers as the name suggests
- `NumberType`: should be used for floats (rendering as an `input[type="number"]`), and have a new option (`support_locale_strings` or something similar) so that it renders as `input[type="text"]` and has the relevant attached `NumberToLocalizedStringTransformer`.

This is obviously a BC break so marked it for 3.0.

**Comment by thomas-koch-comsolit** [comment]
The symfony form number type should also have a "step" option that would than be mapped to the html5 input type="number" step option. Than it would e.g. be possible to have float numbers that would only be a full number or a .5 number with step=".5"

**Comment by AxxiD** [comment]
**Another year has passed and still nothing has happend here.**

I can confirm that `NumberType` renders to `<input type="text" ... >` and not as expected to `<input type="number" ... >` in version 3.0.6.

At this point this might be worth noting: [/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L135](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L135)
The comment was added in 4c0d53a back in 2011. Since then things have changed and I'd say the statement is wrong. The `type="number"` definitely can handle floats. It also has this neat attribute called 'step' as mentioned by @ghost almost a year ago.

I'd love to see this corrected in the next version because especially on smartphones it's more convenient to have it as `type="number"` instead of plain text.

**Comment by stof** [comment]
@ghost ``step`` can already be added through ``attr``

**Comment by AxxiD** [comment]
@stof yes sure. But if NumberType would render into `type="number"` then it'd be nice to have a default value like `step="any"`.

**Comment by jameshalsall** [comment]
I think the field types have moved on slightly since this was opened, but now there is the issue of `IntegerType` supporting non-integer values when it would make more sense to have this support in a `NumberType` instead (with the localised string support like I mentioned in my original comment).

I doubt this will ever be changed now as it would break BC

**Comment by barryvdh** [comment]
Isn't it an option to add a `widget` option for the NumberType (similar to DateType), with a default of `text`, but add an option for `number`. That could be without BC breaks, right?

**Comment by phavlik** [comment]
Just came across this issue. It really doesn't make any sense to me that `IntegerType` allows decimal numbers and there is no flag to disable it. Who thinks that `1.23` is integer?
