### ISSUE TITLE
[Form] Entity type with empty_value never gets to validation

### ISSUE THREAD

**Issue by WishCow** [symfony/symfony#10477]
I have an entity called "Message", which belongs to an entity called "Group". I modeled this relation in my form with:

```php
        $builder->add('group', 'entity', [
                'label' => 'select class',
                'empty_value' => 'Choose a group',
                'empty_data' => null,
                'class' => 'Bundle:Group',
                'property' => 'name',
                'mapped' => false,
```
And in the validation:
```yaml
Bundle\Entity\Message:
    properties:
        group:
            - Type:
                type: Bundle\Entity\Group
            - NotBlank: ~ # probably redundant
```
If the user submits the form, leaving the empty value (Choose a group) in the select box, the form never gets to validate the entity, because it will fail with a fatal error on the setter:

Catchable Fatal Error: Argument 1 passed to Bundle\Entity\Message::setGroup must be an instance of Bundle\Entity\Group, null given

If I understand correctly, this happens because the validation happens after the data is bound to the entity, and not before. 

I found two workarounds:

1. Set mapped: false on the field, and handle the setting with an event listener
2. Allow nulls in the setter

However, there is another place where this error comes up. The "Message" entity requires a "Group" in its constructor. You can provide a closure in "empty_data" to create the entity, but the Group will also be missing there, which will produce another fatal error there. This makes me believe that this is something that I should validate *before* binding to the model, but that will mean that the user will only be able to see some errors first, and after correcting them, see the others, which is also not optimal.

Is there a recommendation for this? Validate the field with javascript perhaps, and let it fail at $em->flush() time (column cannot be null)?

**Comment by Tobion** [comment]
This use-case is explained in https://webmozart.io/blog/2015/09/09/value-objects-in-symfony-forms/

**Comment by WishCow** [comment]
Can you elaborate?

**Comment by HeahDude** [comment]
@WishCow when you submit a choice field with no value select, 'empty_data' overrides the submitted data, in that case null.

You may want to set it as : `'empty_data' => new \Bundle\Group()`

But this wouldn't be work because `EntityType` only use "managed" entities and would throw an exception.

The workaround is :
```php
$defaultGroup = new \Bundle\Group();
$entityManager->persist($defaultGroup);
// or $defaultGroup->setId('some_unused_id') be careful as it could override an existing entity
$builder->add('group', 'entity', [
                'label' => 'select class',
                'empty_value' => 'Choose a group',
                'empty_data' => $defaultGroup,
                'class' => 'Bundle:Group',
                'property' => 'name',
                'mapped' => false,
]);
```

**Comment by WishCow** [comment]
I see, thank you.

**Comment by ianfp** [comment]
Can I re-open this issue? I have a required `EntityType` form field, and the corresponding setter (accordingly) does not allow null values. The field has a `placeholder` because I want to force the user to think about which selection to make, rather than giving him the opportunity to just go with the default. The user must select an existing entity, so the discussion above about instantiating a new instance doesn't apply.

The problem is that if the user's browser doesn't support HTML5 validation (cough, cough, Safari), the user can leave the select input blank, and I get the same Fatal Error that @WishCow describes.

I tried adding a constraint directly via the form builder using the `constraints` option, but that doesn't solve the problem. I realize that the setter could allow nulls, but that feels wrong -- that would suggest to future maintainers that nulls are allowed, which isn't true.

**Comment by HeahDude** [comment]
Hi @ianfp which version of symfony are you using?

**Comment by ianfp** [comment]
Sorry, @HeahDude, I meant to include that. I'm using 2.8.7.

**Comment by HeahDude** [comment]
What did you use as `constraints`?

**Comment by ianfp** [comment]
```php
$builder->add('source', EntityType::class, [
    'class' => MyEntityClass::class,
    'query_builder' => // some query
    'placeholder' => '-- choose --',
    'constraints' => new Assert\NotNull(),
]);
```

**Comment by HeahDude** [comment]
@ianfp Ok, could you please try to add `'choice_value' => 'id'` as an option? I'll investigate further in the meanwhile. Thanks!

**Comment by ianfp** [comment]
@HeahDude, I tried your suggestion but the result was the same.

**Comment by HeahDude** [comment]
The simplest way is indeed to allow `null` on the setter so it can reach the validation step.

You can also provide a new instance as empty data which would not be valid or use a caller.

**Comment by empiricalx** [comment]
I want to make an observation and a constructive criticism of this framework. When a framework make a tasks as simple as populating a select/option (dropdown) with data and to set the preselected value more difficult than doing it using just php (without the assistance of the framework) it defy the purpose of the framework.  How can't the EntityType doesn't have a selectedValue attribute?, how damn hard is to add that to it? Why do I need to write so much code for something so simple? 

making the EntityType to populate with the mapped ORM was very straight forward, setting the preselected value in the case of an update a nightmare! the 'data' attribute doesn't work.
