### ISSUE TITLE
non-catchable pattern in requirements

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#10548]
From #10350 (which contains a unit test to demonstrate the issue)

If you have a non-catchable pattern in requirements like f.e. a positive lookahead (.+(?=/foo/)), the generator will not accept the parameter as the parameter itself cannot fulfil the requirement, but only matches in the context of the entire path.

I'm not sure how/if you would like to fix this, this only adds a failing test case. One way might be to generate the URL and run the matcher against the entire URL.

/cc @Tobion

**Comment by fabpot** [comment]
Closing this old issue.

**Comment by schmittjoh** [comment]
Just a quick follow up on this. An alternative to rewriting the validation could be to take the `strictRequirements` setting and allow this to be changed on a per-route basis instead of a switch on the framework level. 

Typically, there are only a few routes where you need these lookaheads. The use-case here was branch names and paths which are part of the URL on some routes on Scrutinizer. Both, the branch name and the path can contain ``/`` hence the lookahead to decide where the branch name ends and the path starts.

**Comment by stof** [comment]
or even detecting automatically the usage of a lookahead in the requirement, to disable the strict check automatically in such case (avoiding the need for extra per-route configuration)
