### ISSUE TITLE
Rewrite the Filesystem component

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#10547]
The Filesystem component is just about one class that abstracts some filesystem operations. This class comes from symfony1 and never got the love it would have need.

What we need is a component that abstract the filesystem a bit more so that we don't rely on a "real" filesystem (see #9238 for instance) which would also allow for easier mocking (see #10539 for instance).

As always, we have two options here: replace what we already have with something that already exists in the community or replace it with something we build.

The only concerns I have are overhead/performance.

**Comment by JHGitty** [comment]
I would love to see a component in the Symfony Community like FlySystem with a great abstraction for different platforms. FlySystem is great but I think we would do it more "in the Symfony way".

**Comment by pilotftzi** [comment]
@JHGitty +1

**Comment by SenseException** [comment]
Besides using something like Flysystem or not:

Do we keep the API of `Filesystem` using an interface while the class itself is going to use adapters or something like that? In that case we'll have BC break.

Using a new implementation for filesystem handlings would result in a deprecation for the component, resulting in a new one.

Going with an interface only the `Filesystem` class may be deprecated and untouched, except adding that interface, while userland has to change their type hints for using the new interface. The new implementation would also use that interface.

There's also the possibility to split up functionality into separate classes like for changes of file information, file contents and file location (delete, move, etc.). This may be only considered if `Filesystem` is going to be completely different.

Thinking about the Symfony framework and not only the component: We have to think about the filesystem service name. Will the new filesystem component get its own service or replace the new one? Maybe a configuration had to be added for using something different than the current `Filesystem` class.

Please feel free to post your thoughts on this. Maybe my suggestions are much more than we want to accomplish with this issue (Yagni), because we're not only going to change Symfony stuff with this.
