### ISSUE TITLE
[5.0][HttpFoundation] The session must not be a service

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#10557]
The session is a data object, and so, like the request, must not be in the container.

**Comment by JHGitty** [comment]
I like to change values in the session in my own service. Should I always pass the current request as parameter? Or should I only pass the session (``SessionInterface``)? As I understand I should not get ``session`` from the container anymore.

**Comment by yjv** [comment]
@GHGitty im thinking you should probably pass the request_stack service,  call getCurrentRequest()->getSession()

**Comment by aeos** [comment]
I am trying to find the best way to implement my chosen design pattern, and this discussion is the most relevant. I don't use DAO, or any of the ORM features in symfony. Instead I create services with method calls that accept, and return, basic data types. Through DI, I inject the storage mechanism (often Doctrine DBAL). The service is responsible for retrieving and formatting data. This allows me to swap the storage mechanism by modifying the service, and the consumer doesn't need to be updated (pretty common approach I think). 

Now two of the storage mechanisms I would like to use are the session, and cookies. If I pass the request_stack into the service, obviously I can read/write to both the session and cookies. But I feel that this discussion looks down on that approach. How else can I allow my service to use the session/cookie as a data store?

**Comment by nicolas-grekas** [comment]
What about adding `RequestStack::getSession()` to fix this issue?

**Comment by lyrixx** [comment]
@nicolas-grekas Initially, I thought about `SessionStorage::getSession()`, but the `RequestStack` is a very good idea :+1:

**Comment by linaori** [comment]
The Session is bound to your HTTP layer, so whenever you need it somewhere, you can _always_ pass it as method argument if you really need to modify the session contents in another layer. If you _really, really_ want to modify the session in listeners that do not have a direct access to the request, you can always retrieve it from the current request via the request stack.

If the events do not contain the request object while being part of the request lifecycle, perhaps they can be added. As far as I can see, the Kernel events have a request object and thus a session though: https://symfony.com/doc/current/reference/events.html#kernel-events (given the session is set).

`RequestStack::getSession()` will not solve anything other than being it being a shortcut for `getCurrentRequest()->getSession()`.

**Comment by nicolas-grekas** [comment]
We should then ensure subrequests have the session, or tell about `getMasterRequest()->getSession()` instead. Any blocker to deprecate the session service then? PR welcome if not.

**Comment by linaori** [comment]
Considering there are enough work-arounds, it seems that that it can be deprecated as service. Worst case scenario, provide an alternative solution to show how to register the Session as service using a factory in the DIC.

**Comment by lyrixx** [comment]
> `RequestStack::getSession()` will not solve anything other than being it being a shortcut for `getCurrentRequest()->getSession()`.

Yes, it's a shortcut, but a convenient one. That's why I'm in favor to add it to the request stack

**Comment by fabpot** [comment]
I like the `RequestStack::getSession()` shortcut as well.

**Comment by derrabus** [comment]
If we remove the service, can we make it so that controller actions that type-hint for `SessionInterface` still receive the session?

**Comment by linaori** [comment]
@derrabus What do you mean exactly? The `SessionInterface` will not be removed

**Comment by derrabus** [comment]
@linaori No, but the `SessionInterface` service will. I wasn't sure if controllers type-hinting for the interface depend on autowiring via `controller.service_arguments` to receive the session, but this is apparently not the case thanks to `Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver`. So, those controllers will continue to work without the session service. 👍

**Comment by wouterj** [comment]
So, I started working on this as I thought "it should not be that hard". But discovered the `\Symfony\Component\HttpKernel\EventListener\AbstractSessionListener` class, which does exactly the opposite of what is discussed here: if a session service is initialized, it makes sure it's set on the master request.

So that means we deprecate the `session` service in favor of `masterRequest#getSession()`, but `masterRequest#getSession()` depends heavily on the `session` service. I no longer understand what I should be doing and how we can keep BC with "initializing the session service".

**Comment by derrabus** [comment]
@wouterj Either way, the session needs to be initialized somehow. At the moment, the container does this and the objective (as I understand it) would be to move that initialization somewhere else. That listener could be the place we're looking for.

Since the `session` service needs to be kept in Symfony 4 in order not to break BC, that listener will probably be kept as-is for now. All other services provided by the framework that depend on the session should instead depend on the request stack.

In Symfony 5, the `session` service is removed and the listener will be responsible for constructing the session object before injecting it into the current request.

Does that make sense?

**Comment by Pierstoval** [comment]
First thing to me is to split the `Session` object and remove its dependency to the session storage, and refactor the storage so it can do `$storage->save($session)`.

This would enforce the session to be created by either the storage, or a new factory that may need the storage itself, to create the session object, fetch data from the storage, populate the session with storage data, return the session.
The SessionListener may use such factory, for BC, and put the session in the Request object as usual.

BC and migration path would be achieved with new contracts, making the "old" session a `SessionStorageInterface` and injecting the storage with DI, making the session a decorator of the storage (just like it currently is, but by changing the contract). Or even farther: making the current `session` service a new class that would just make the calls to the factory, using request stack to populate the session in the current request, etc.

WDYT?

**Comment by stof** [comment]
The first thing here would be to propose solutions about how this split would look like actually. As said previously, this is not easy, due to the fact that we wrap the PHP session handling, and so we are limited by what it allows.

**Comment by warslett** [comment]
> Either way, the session needs to be initialized somehow. At the moment, the container does this and the objective (as I understand it) would be to move that initialization somewhere else. That listener could be the place we're looking for.
>
>Since the session service needs to be kept in Symfony 4 in order not to break BC, that listener will probably be kept as-is for now. All other services provided by the framework that depend on the session should instead depend on the request stack.

RequestStack could be used as a factory and getSession the factory method to protect BC breaks while the session service is deprecated but not removed same as we did #36063.

The Session could be instantiated in the SessionListener when the master request is received and onKernelRequest is triggered as @derrabus suggests. The problem I can see with this is if a service which injects the session is instantiated by the service container before that onKernelRequest event maybe in another event handler for example. In this situation getMasterRequest will be null so it won't be possible to get the Session from it.

Another approach might be to remove this behaviour from the SessionListener and instead make the RequestStack the owner of the session and set it's session object on each request that is pushed to it. That way we can rely on the Session being available to the service container at any point in the process including to all KernelEvents.

```
/**
 * @var Request[]
 */
private $requests = [];

/**
 * @var SessionFactoryInterface
 */
private $sessionFactory;

/**
 * @var SessionInterface
 */
private $session;

/**
 * @param SessionFactoryInterface $sessionFactory
 */
public function __construct(SessionFactoryInterface $sessionFactory)
{
    $this->sessionFactory = $sessionFactory;
}

/**
 * Pushes a Request on the stack.
 *
 * This method should generally not be called directly as the stack
 * management should be taken care of by the application itself.
 */
public function push(Request $request)
{
    $request->setSession($this->getSession());
    $this->requests[] = $request;
}

...

/**
 * @return SessionInterface
 */
public function getSession(): SessionInterface
{
    if (null === $this->session) {
        $this->session = $this->sessionFactory->createSession();
    }

    return $this->session;
}
```

We also have to consider applications that might have overwritten the definition of the session service with their own definition. We could maybe add a compiler pass that detects if the session service definition is overwritten (by checking whether it is using RequestStack as a factory) and if so replaces the definition for SessionFactoryInterface with one that uses an implementation that delegates to the service container.

That implementation could be deprecated from the start so that any applications that are overriding the default session service will get deprecation notices. Any application can override the default instantiation of the session, use their own class, register their own bags etc. by implementing their own SessionFactoryInterface.
