### ISSUE TITLE
console config:debug framework

### ISSUE THREAD

**Issue by coviex** [symfony/symfony#11089]
This recipe http://symfony.com/doc/current/cookbook/configuration/pdo_session_storage.html results in

    [Symfony\Component\DependencyInjection\Exception\RuntimeException]
    A string value must be composed of strings and/or numbers, but found parameter "database_port" of type NULL inside string value "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%".

after

    ./app/console config:debug framework

on

    parameters:
        database_driver: pdo_mysql
        database_host: localhost
        database_port: null
        database_name: example
        database_dbname: example
        database_user: root
        database_password: root

and 

    PHP 5.5.12-pl0-gentoo

**Comment by fabpot** [comment]
Not sure what this is all about, any bugs?

**Comment by javiereguiluz** [comment]
Closing it because of the lack of feedback.

**Comment by richard-keller** [comment]
The Symfony docs suggest using the following configuration for PDO session storage:

```
session.handler.pdo:
    class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    public:    false
    arguments:
        - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
        - { db_username: '%database_user%', db_password: '%database_password%' }
```

The problem here is that when the `database_port` variable hasn't been explicitly set in `parameters.yml` (or if it's been set to `null`) then Symfony throws the runtime exception that @coviex ran into.

There are 2 possible solutions:

**Option 1:**
Explicitly set a numeric value for the `port` variable in `parameters.yml`

**Option 2:**
Change the PDO session configuration to remove the reference to the database port, like this:

```
session.handler.pdo:
    class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    public:    false
    arguments:
        - 'mysql:host=%database_host%;dbname=%database_name%'
        - { db_username: '%database_user%', db_password: '%database_password%' }
```

It would be great if this could be added to the Symfony docs, because many people won't explicitly set a database port, and the error message that Symfony spits out is not very useful.

**Comment by xabbuh** [comment]
@richard-keller Please open an issue in the [symfony-docs](https://github.com/symfony/symfony-docs/) repo so that it doesn't get lost.

**Comment by crmpicco** [comment]
As @richard-keller said, explicitly set a `port` in `parameters.yml`:
```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: 5432
```

This worked for me.
