### ISSUE TITLE
[Finder][Feature] depth ordering

### ISSUE THREAD

**Issue by claudebossy** [symfony/symfony#11289]
Hello,

I'm not currently assuming that the finder returns results order by ascending depth.
I'd like to have a way to be sure the results are ordered that way.
I think that guessing that the algorithm is doing it that way and will stay forever like that is too risky.
So right now I do a sort on the full path name and I count the number of `"/"`.
So it'd be nice to have a way to explicitly specify that the results are ordered in a ascending depth way. Like a `sortByDepth` method maybe.

Best.
Claude

**Comment by javiereguiluz** [comment]
Closing it because this feature looks unnecessary. The Finder component uses the PHP's built-in iterators and is well-tested, so it won't change the default behavior in newer Symfony versions. (And if we break this by mistake, we'll get lots of bug reports and we'll fix it right away).

In any case, if you still want to be sure about the result sorting, you can keep applying the solution you mentioned about counting directory separators. Thanks!
