### ISSUE TITLE
[DX] Expanded, single-value 'entity' fields need a default value

### ISSUE THREAD

**Issue by zebba** [symfony/symfony#11740]
If you add an 'entity' field to your FormType and decide to render the field as radio buttons  none of the radio boxes is pre-selected.

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
        ->add('test', 'entity', array(
            'class' => 'Acme\BlogBundle\Category',
            'multiple' => false,
            'expanded' => true
    ));
```
Passing 'empty_value' renders an additional field. So far I can only imagine passing an entity through the form options from the controller to determine a default value. It would be more intuitive if the internal pointer uses the first result from the EntityManager-generated list as a default (marks it as checked) or could be overriden with 'data' allowing a Closure to find one of the internal choice_list entries.

**Comment by HeahDude** [comment]
I don't agree as it would usually be expected that "selected" values match the default data, otherwise it would be weird IMO.

However you're right, you cannot dynamically set the data in `EntityType` since loading choices is made internally.

For this use case you should load your entities first and pass them through the `choices` option of `ChoiceType` instead, while you would get the opportunity to set default data as you need.

**Comment by HeahDude** [comment]
Here's a possible workaround for symfony 2.7 :

```php
<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Exception\InvalidConfigurationException;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DynamicEntityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $class = $options['class'];
        $dynamicData = $options['dynamic_data'];
        $requireArray = $options['expanded'] || $options['multiple'];

        if ($dynamicData && is_callable($dynamicData)) {
            $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($class, $dynamicData, $requireArray) {
                $data = call_user_func($dynamicData, $event->getForm()->getConfig()->getOption('choice_list')->getChoices());

                if (null !== $data && !is_array($data) && false === $data instanceof $data) {
                    throw new InvalidConfigurationException(sprintf('The callable option "dynamic_data" should return either "null", an array of %$1s, or an instance of %$1s but got %s.', $class, gettype($data)));
                }

                if (!is_array($data)) {
                    $requireArray ? $event->setData(array($data)) : $event->setData($data);

                    return;
                }

                if (!$requireArray) {
                    throw new InvalidConfigurationException('The callable option "dynamic_data" should return a single instance entity or "null" but got an array.');
                }

                foreach ($data as $entity) {
                    if (null !== $entity && false === $entity instanceof $class) {
                        throw new InvalidConfigurationException(sprintf('The callable option "dynamic_data" should return an array of %s or "null" but got an array containing %s', $class, gettype($entity)));
                    }
                }

                $event->setData($data);
            });
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $dynamicDataNormalizer = function (Options $options, $dynamicData) {
            if (null === $dynamicData) {
                $class = $options['class'];
                return function ($data) use ($class) {
                    if (is_array($data) && !empty($data)) {
                        return $data[0];
                    }

                    return new $class;
                };
            }

            return $dynamicData;
        };

        $resolver->setDefault('dynamic_data', null);

        $resolver->setNormalizer('dynamic_data', $dynamicDataNormalizer);

        $resolver->setAllowedTypes('dynamic_data', array('null', 'callable'));
    }

    public function getParent()
    {
        return 'entity';
    }

    public function getName()
    {
        return 'dynamic_entity';
    }
}
```

**Comment by xabbuh** [comment]
Closing here as I don't see what we can do here in the core and @HeahDude provided a way to achieve this in userland code.

**Comment by HeahDude** [comment]
@xabbuh the `dynamic_data` option could be easily added in `EntityType`, and would avoid this workaround.

This label DX is explicit, using an `EntityType` means that you want to delegate the loading, otherwise one should use the `ChoiceType` with the `choices` option instead.

But using the `EntityType` you cannot easily "pre set" data as they are not already loaded.
I find it more "dev friendly" to use an option than to write a form event listener and create a form type to extending an existing one to add it.

I see two possible solutions as @zebba suggested :
- override the `data` option to accept a callable for `EntityType` as we cannot use it as it is anyway,
- or add an option like the above `dynamic_data` being a callable or null by default.

In my example I used a default behaviour in the `dynamicDataNormalizer` to suit @zebba wish to pre select the first entity, but I think it would be nice to allow two key string for this option, like "first" and "last", knowing that the default order is by ID's but can be set with a custom `query_builder` option.

May be this issue could be reopened.

What do you think ?
