### ISSUE TITLE
[DX] improve file loader errors for router

### ISSUE THREAD

**Issue by lmammino** [symfony/symfony#11958]
I had this error today after pulling out the commit of a colleague (he just had created a new bundle):

```
Cannot load resource "@AcmeDemoBundle/Controller/". Make sure the "AcmeDemoBundle" bundle is correctly registered and loaded in the application kernel class.
```

The bundle was correctly created and registered. The problem was that he hadn't written any controller (and deleted the default one). So the `Controller` folder remained empty and wasn't committed.

I struggled out for a while before having been able to find the problem. 
I think the error message is wrong here. We might improve it and just state the the "/Controller" folder was missing in the bundle. Didn't had a look at the code yet but I think it can be easy to add this check and improve the error message.

What do you think?

**Comment by fabpot** [comment]
Anyone willing to work on this one? Or let's close it.

**Comment by Neophy7e** [comment]
@fabpot just submitted a pull request :-)

**Comment by sstok** [comment]
#13969 is closed because implementing this properly would require a bundle location resolver.
And that in turn will require to much BC breakage.

I can think of only way to improve the DX, update the exception message.

`'Make sure the "%s" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure that directory "%s" exists in the bundle.'`

The directory name is easily extractable, the full path is not.
But will help with newcomers with looking further :)

**Comment by lmammino** [comment]
I think @sstok proposal is good enough to solve the issue right now :wink:

**Comment by cordoval** [comment]
ping @javiereguiluz is this the wrong PR, or any chance, maybe i should just close it?
