### ISSUE TITLE
[VarDumper] Add stacktrace information

### ISSUE THREAD

**Issue by italolelis** [symfony/symfony#12073]
Hi,

What about adding a stack trace information when dumping?

I think it may help to see which were the steps to get there.

**Comment by javiereguiluz** [comment]
Closing it because adding the stack trace to each `dump()` call looks like "too much". Besides, the dumps already show the file path and line number in which they were called.

If @nicolas-grekas, the maintainer of VarDumper, disagrees with this, he will reopen the issue and provide more details. Thanks!

**Comment by nicolas-grekas** [comment]
the return value is a plain php array, there's no way to know that its special
but you can `dump(new Exception());`

**Comment by flip111** [comment]
@nicolas-grekas that works but it floods my console with text, any way to trim long arguments?

**Comment by nicolas-grekas** [comment]
`echo new \Exception();` :)
