### ISSUE TITLE
Extra quotes when using {{ value }} in Email constraint message

### ISSUE THREAD

**Issue by arnaugm** [symfony/symfony#12101]
I used to have the constraint message:

```twig
The email "{{ value }}" is not valid
```

in an Email constraint inside a Form Type class, which gave me an error message like

```
The email "username@example.com" is not valid
```
After updating Symfony from 2.3.6 to 2.3.20, the displayed message looks like this
```
The email ""username@example.com"" is not valid
```
with doubled quotes.

Is this intended or is a mistake? I would say that the old version was better in case you don't want to put quotes in your message.

**Comment by javiereguiluz** [comment]
Closing it as "won't fix". Even if this was an unexpected change and some people don't like it, 17 minor Symfony versions have been released since this change, so it's too late to revert it. Moreover, the fix for our own apps is easy although a bit cumbersome: just remove the extra quotes in every custom validation message.

@lenardpalko thanks for sending a PR trying to solve this!
