### ISSUE TITLE
[Routing] configure trailing slash on imported routes

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#12141]
There is currently a known limitation when using route imports that makes it impossible to to have a root route `/` be imported under a prefix without a trailing slash. See #4322 and silexphp/Silex#149

I propose to solve this problem in a generic way by offering an option when importing routes to remove or add trailing slashes (which defaults to null, meaning not modifying anything):

```
AcmeBusinessBundle_client:
    resource: "@AcmeBusinessBundle/Resources/config/routing/client.yml"
    prefix:   /clients
    trailing_slashes: true|false|null
```

This way, the users can unify the path on import the way they want.

So for example

```
acme_business_client_list:
    path:  /
    defaults: { _controller: AcmeBusinessBundle:Client:list }
```

imported with `trailing_slashes: false` under `prefix: /clients` will result in path `/clients` instead of `/clients/`. 

The other case with `trailing_slashes: true` is helpful when you import third party routes without trailing slash but you decided that you app should use training slashes everywhere consistently.

**Comment by Tobion** [comment]
@sebastianblum it makes no sense to configure the trailing slash on the route instead of on the import.

```
route:
    path: /
    trailing_slash: false
```

makes no sense if the route in not imported under a prefix. Also it does not allow the overwrite the trailing slash of third party routes.

**Comment by dejayc** [comment]
There's another special case that we could try to find a common solution for.  Some people want to specify that a route is valid regardless of whether there is a trailing slash.  Consider the following:

    test_route:
        path: /test

This route only matches `/test`, and not `/test/`.  Here's the common way to solve the problem:

    test_route:
        path: /test{ts}
    requirements:
        ts: /?

This is a hacky workaround, which then complicates any optional, trailing pattern matching.  Some people say, "Why not just put this logic in the web server config, so that the web server can /issue redirects/map multiple paths to the same controller/?"  But if you only want certain paths to exhibit this behavior, then duplicating multiple paths in the web server config is not an ideal separation of concerns.

**Comment by dirkluijk** [comment]
I don't like the proposed solution very much, but I am dealing with the same problem. When importing (mounting) a collection of routes, I can't get rid of the trailing slash, even when ``path`` is ``""``.

Not a world problem, but an elegant solution would be nice!

**Comment by iltar** [comment]
I would like to add 1 possible issue. The security component also triggers on redirect from without to with trailing slash. That means that if you security is configured to listen `/login/check_login` but your route is `/login/check_login/`, it will actually trigger on the `/login/check_login` with the redirect controller and fail.

**Comment by Tobion** [comment]
@dirkluijk what do you not like?
@iltar what "fails"? If your security is "^/login/check_login" then it's obvious that it also matches with any suffix.

**Comment by iltar** [comment]
@Tobion Except that you do not expect it to also trigger on an internal framework redirect. It makes sense, but it's not obvious for those cases. It took me quite a few hours to figure out why a certain route with login failed. 

I expected symfony to redirect with a trailing slash _before_ the security hooks in.

**Comment by dirkluijk** [comment]
@Tobion Well, in my opinion it should work without further configuration. It just doesn't make sense to me.

This is my code in my Silex app:
```php
$controllers
    ->get('', 'serius_catalog.controller.catalog:indexAction')
    ->bind('serius_catalog_index');

$controllers->get('/product/{productId}/{slug}', 'serius_catalog.controller.catalog:productAction')
    ->bind('serius_catalog_product');

return $controllers;
```
```php
$app->mount('/catalog', new MyCatalogServiceProvider());
```
This should result in ```/catalog```, and not ```/catalog/```.

**Comment by Tobion** [comment]
Then we would need to distinguish between "" and "/" until we have the final "mounted" routes. But according to RFC `'' == '/'`. Image `MyCatalogServiceProvider` comes from a library. Then it would decide if it's `/catalog` or `/catalog/`.

**Comment by nickshanks** [comment]
Hi. I've just ran into bug #4322 as well. I have a bundle prefix of /foo and wanted to specify a resource in the bundle's routing file at `/foo`, not at `/foo/`, but was unable to. I suggest also supporting `~` (YAML's null value) as an equivalent to `""` for the path. I am not keen on the trailing_slash suggestions posted—just allow an empty string to be concatenated to the prefix, to refer to a route at the prefix path.

@Tobion You say " But according to RFC path '' == '/'. "  — yes, but that only applies to the root of a server. We're talking about deeper down in the hierarchy here. "/foo" + "" == "/foo"


Here's what I wrote before finding this bug:

in ./app/config/routing.yml:

``` yaml
my_bundle:
    resource: "@MyBundle/Resources/routing.yml"
    prefix: /path/to/where/bundle/starts
```

in ./src/MyBundle/Resources/routing.yml:

``` yaml
my_bundle_index:
    path: ~
```

Expected path of "my_bundle_index" would be `/path/to/where/bundle/starts`

**Comment by Tobion** [comment]
The thing is you know that you import `my_bundle_index` under a prefix, which is why you can use a  `null` path. But for bundles providing routes it doesn't make sense to have a `null` path since they cannot assume how it's going to be used. So we have to treat each routing file as it could also be used standalone, which is why I said `'' == '/'`.

**Comment by nickshanks** [comment]
Well that's simple to solve logically—in fact I can think of two obvious solutions. 1) Any bundle that has a empty route path, throws an exception when loaded if it's not loaded under a prefix. It's a condition of use of such bundles that they be imported under a prefix. Or 2) once all paths are loaded, any full path which resolves to an empty string is upgraded to "/" and treated as if it were specified as such in config.

**Comment by Tobion** [comment]
Again, this still doesn't provide a way of the route user to configure trailing slashes. To me, the one that uses the routes should be in control of how the routes look like (trailing slash or not). Thus my proposal. But your proposal only gives control for the one who defined the routes.

**Comment by nickshanks** [comment]
I'm not quite sure what you mean by "the one who uses the routes" and "the one who defines the routes". At the moment, we can't choose "no slash" because the root of a bundle always has a slash added to it. Instead, we are forced to put some of the prefix in the bundle, which puts some of the path in a place it doesn't belong:

``` yaml
my_bundle:
    resource: "@MyBundle/Resources/routing.yml"
    prefix: /path/to/where/bundle
```

``` yaml
my_bundle_index:
    path: /starts
my_bundle_page1:
    path: /starts/page
my_bundle_page2:
    path: /starts/another-page
```

**Comment by sebastianblum** [comment]
In the discussion, we have the pro and cons with "the one who uses the routes" and "the one who defines the routes".

The main problem is in my opinion, that the path of the homepage is the slash

    my_bundle:
        prefix: /folder
    index:
        path: /

If we define instead of path: / something like path: ~ or a different character, then we can say
* path: ~ is the same as / without a prefix
* path: ~ is like an empty string with a prefix
Because we introduce a new character, we have not problems with backwards compatibility.

maybe this could a solution for the trailing slash

**Comment by Ronnie-J** [comment]
So where are we on this?

**Comment by NothingWeAre** [comment]
I agree with @sebastianblum solution.
And this issue is rather unnerving when i'm trying to create REST API. 
Fo example dealing with list retrival 
/orders rediretcs to /orders/
so i have to define routes fo orders retrival in root route file to avoid such behavior.

**Comment by FinesseRus** [comment]
Symfony Routing is so smart that automatically changes such path `dir` to `/dir`. Internet users are used to treat URL with ending slashes and without as the same URL. So why not to teach Routing automatically change `/dir/` to `/dir` and treat them as the same paths?

**Comment by giosh94mhz** [comment]
@FinesseRus because they are not the same path. The fact that most webserver threated with-/ and without-/ is the source of the problem. Currently, Symfony is smart enough that if you use a prefix it imply that a prefix act like a webserver directory, but the whole discussion here is to provide a way for implementing the "prefix is not a directory". (if I understand correctly, of course)

**Comment by ThisIsAreku** [comment]
It's been more than 2 years now. I'm in favor of @sebastianblum solution, it seems more natural in the context of REST.

**Comment by yellow1912** [comment]
Where are we on this issue? I have the same problem with the traling slash when using prefix.

**Comment by mdeboer** [comment]
With @sebastianblum on this one, nice and clean solution. Currently using the following workaround but his solution would make it much cleaner. Fortunately when working building a REST API you only need this for your index path(s).

```yaml
my_route:
  path: /{ts}
  defaults: { _controller: AppBundle:Default:index, ts: null }
  requirements:
    ts: /?
```

**Comment by tomsykes** [comment]
Is this not a question of the order in which things are done?

I understand that we can't have an empty route - and so an empty route is normalised to "/" in order to prevent that.

At the moment, a route is normalised before the prefix is added. So an empty route becomes "/" and adding a prefix makes it "/prefix/"

Shouldn't the normalisation be done after any prefixing, so that "/prefix" can be left as is, but if a route is still empty even after a prefix has been added, then it can be normalised to "/"?

**Comment by andyexeter** [comment]
Any movement on this? It's been three years since this thread was created and the issue still remains.

**Comment by mdeboer** [comment]
I hope this gets fixed in 3.4/4.0 otherwise I'll need to find some time and look into it myself. My workaround works but it's ugly as hell.

**Comment by yellow1912** [comment]
I sure hope it gets fixed, there are many cases we don't want Symfony to automatically apply the slash

For example, I have something like this

```
_frontend:
    prefix: /{_locale}
    resource: frontend.yml
    defaults:
        _locale: '%kernel.default_locale%'
    requirements:
        _locale: ^[a-z]{2}([-_]{1}[A-z]+)?$
```

Then my homepage route is:
```
core.frontend.home.index:
    path: /.{_format}
    methods: [GET]
    defaults:
        _controller: theme.frontend.controller.page:showAction
        _format: html
    requirements:
        _format: (html|partial|json)
```
I want the localized url to be site.com/en, not site.com/en/, but because Symfony appends the slash it is forced to site.com/en/

**Comment by iltar** [comment]
What would be the reason to not want with a trailing slash in that scenario? If anything, _with_ trailing slash, both urls will work (with a 301 to with slash).

**Comment by mdeboer** [comment]
@iltar because without a slash currently no 301 redirect is being made, instead a 404 is returned. See my comment above to see what "hack" is needed to make things work as they're supposed to.

**Comment by dejayc** [comment]
Haha, I'm glad I gave up on Symfony 3 years ago when I first encountered this issue.  Seriously!

**Comment by nicolas-grekas** [comment]
@dejayc we where waiting for a PR of yours, what did you do for 3 years? Since it's now pretty obvious we shouldn't have, here is one: #26284, implementing @sebastianblum's proposal (sorry couldn't resist :) )

**Comment by dejayc** [comment]
> Mind staying on topic please?

I'd love to try, but I'm afraid I might be dead by the time this topic resolves itself.

**Comment by nicolas-grekas** [comment]
@dejayc if you don't mind and don't care, please unsubscribe from the issue.

**Comment by arteniioleg** [comment]
Similar issue with `@Route`

```
/admin/actions/ <---
/admin/actions/add
/admin/actions/{id}
```

Fortunately `@Route` allows empty `path=""` so the fix is

```php
/**
 * @Route(path="/admin/actions")
 */
class AdminActionsController extends Controller
{
    /**
     * @Route(path="", name="admin_actions")
     */
    public function indexAction(Request $request);

    /**
     * @Route(path="/add", name="admin_action_add")
     */
    public function addAction(Request $request);

    /**
     * @Route(path="/{id}", name="admin_action_edit")
     */
    public function editAction(Request $request, string $id);
}
```

_Symfony 4.0_

**Comment by mdeboer** [comment]
@fabpot Thank you so much, that's amazing. Can't wait for 4.1! 👍
