### ISSUE TITLE
provide a clock service

### ISSUE THREAD

**Issue by thkoch2001** [symfony/symfony#12178]
Unit-Testing anything related to time is hard if the code under test directly accesses the system time. Therefor I always use a clock service wrapping a DateTime instance that represents "now".
Another nice property is, that "now" remains the same during one request.

It would of course be nicer to rely on ImmutableDateTime but this is only in PHP 5.5 AFAIK.

The clock also contains some helper functions:
```php
class Clock {

    private $now;

    public function __construct(\DateTime $now) {
        $this->now = $now;
    }

    /**
     * Time representation usable as (part of) a file name, e.g.: 2014-05-23_13-45-23
     */
    public function getFileName() {
        return $this->now->format('Y-m-d_H-i-s');
    }

    public function getDateTime() {
        return $this->now;
    }

    public function getSeconds() {
        return (int)$this->now->format('U');
    }

    /** How many seconds passed since $past
    */
    public function getSecondsSince(\DateTime $past) {
        return $this->getSeconds() - (int)$past->format('U');
    }

    /** Have $seconds already elapsed since $past?
    */
    public function hasElapsed($seconds, \DateTime $since) {
        return $this->getSecondsSince($since) > $seconds;
    }

    /** Is $expiryDate in the past? */
    public function isExpired(\DateTime $expiryDate) {
        return $this->now > $expiryDate;
    }

    /**
     * Create new DateTime object with the timezone of this clock
     *
     * @param String $time
     */
    public function createDateTime($time) {
        return (new \DateTime($time, $this->now->getTimezone()))->setTimezone($this->now->getTimezone());
    }
}
```

**Comment by zebba** [comment]
Introducing a Clock service will not solve all of the possible use-cases: you will not be able to use this in LifecycleCallbacks for example. Therefore introducing the service might help a few, but most of the developers will not have a real benefit from this.

Also, time is always a relative thing on the internet, isn't it? Even if you only serve a single timezone by default determining what theme (Day/night) to use isn't determined by the timezone of the server, is it? It feels more natural for the visitor if his current timezone (which could be on the other side of the world) is taken into account. If you need to work with multiple timezones you can only work with converting to UTC anyway. And even in this case you will always run into problems when you encounter Daylight saving time because there is no way you can safely determine the correct UTC time from a local time around the times of the switching.

On unit-tests you should be able to mock data if you need to. Functional testing any possible controller result is obviously not suitable so use unit tests with mocking instead.

**Comment by fabpot** [comment]
Closing as reading from the comments, nobody is really excited about this.
