### ISSUE TITLE
Ajax debug toolbar display only request starting with "/"

### ISSUE THREAD

**Issue by arno14** [symfony/symfony#12221]
I am just testing the new ajax debug toolbar and my request are not visible in the profiler.
It works if the url are relatives and not absolute.
"http://localhost/sf_test/app_dev.php/demo/test" is not handled, but "/sf_test/app_dev.php/demo/test" works.

That seems normal regarding this code:

```
/* prevent logging AJAX calls to static and inline files, like templates */
if (url.substr(0, 1) === '/' && !url.match(new RegExp("{{ excluded_ajax_paths }}"))) {
```
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L181

excluded path does not work also:
 "http://localhost/sf_test/app_dev.php/_wdt" does not match regexp "^/_wdt".

Did I miss something ?

tested on Firefox and Chrome (Ubuntu)

**Comment by bobvandevijver** [comment]
I am experiencing the same issue: simply removing the first part (`url.substr(0, 1) === '/'`) solves the problem. 

In my opinion, I do not care whether external ajax requests are given in this overview. I think it is more important to see all my own AJAX requests, instead of missing them because of this. I can also imagine that we want to filter the external URL's, but I would do that somewhat else. Possible solutions:
- Search field to search in the captured ajax request
- Filter the requests (after capture) by default on the domain of the current window. 
- Together with the previous point, it can be considered to add a checkbox to enable and disable that filtering.

Simply changing the AJAX urls is not an option for me, as they are not generated directly with Symfony within a template, but from an exposed routing export, as sometimes variables still need to be filled in. 

@fabpot: If wanted, I can create an PR for the 2.6 branch. Could you elaborate on the best solution?

**Comment by sormy** [comment]
I am experiencing the same issue
