### ISSUE TITLE
security.interactive_login event marked as not called

### ISSUE THREAD

**Issue by ZCJ** [symfony/symfony#12276]
When I login into my sf application, I have some code executed on the security.interactive_login event listener and it works, however in the toolbar, under the events not called section, I can see the "security.interactive_login" marked as a not called listener. Is that normal? I am using 2.3.20

![screen shot 2014-10-21 at 9 37 07 am](https://cloud.githubusercontent.com/assets/1475845/4720286/024869d2-5930-11e4-80f4-4f17946c1f9c.png)

**Comment by skylord123** [comment]
@ZCJ I know this is old..

From what I have found out it looks like the `security.interactive_login` is called from the `login_check` path when logging in. Then it redirects to whatever the login page is after that.

One way to test this is to put a `die();` call inside your listener. This will prevent it from redirecting and show you it is being called from the `login_check` path.

**Comment by javiereguiluz** [comment]
Closing this old issue because of the lack of activity and because it's probably caused by what @skylord123 explained. By the way, instead of `die()` a better way to work with redirections in the `dev` environment is to set this option to true:

```
# app/config/config_dev.yml
web_profiler:
    intercept_redirects: true
```

When using a modern Symfony version, it's even easier because the debug toolbar shows if the page was the result of a redirection and you can see the profiler of the original request that made the redirection.
