### ISSUE TITLE
[DX] Provide access to $token in classes that extend AbstractVoter

### ISSUE THREAD

**Issue by richard-keller** [symfony/symfony#12360]
Since `$token` is already passed to the `vote()` function of AbstractVoter, it would be great if `$token` could be defined in the AbstractVoter class as a protected variable, thus enabling classes that extend it to gain access to the token in the `isGranted()` function.

Currently the Symfony Best Practises book suggests creating Voters and invoking the `getRoles()` function on the User object. However, this will not work in the case of role hierarchies, since `getRoles()` will not return the full hierarchy. To get the full hierarchy, we need access to the `$token` object, and from there we can then work out the full role hierarchy in the `isGranted` function.

Of course, we would also need to inject the container into the voter in order to get access to the full list of roles, but that's easy enough to do from the developer's perspective.

The result of this would be the ability to perform access control based on a combination of the user's role and some property on the object which is being voted on. For example, all ROLE_ADMIN users are allowed to view all objects, but ROLE_USER users are only allowed to view objects whose $office attribute matches the office that the user is assigned to.

Of course, even better would be to provide the full role hierarchy for the user in classes that extend AbstractVoter, but that might be taking it a step too far, since not all devs will be interested in the full role hierarchy.

An implementation of such a voter would be as follows:

```php
<?php

namespace Acme\FooBundle\Security;

use Symfony\Component\Security\Core\Authorization\Voter\AbstractVoter;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Role\RoleHierarchy;
use Symfony\Component\DependencyInjection\ContainerInterface;

abstract class CustomVoter extends AbstractVoter
{
    const CREATE    = 'create';
    const READ      = 'read';
    const UPDATE    = 'update';
    const DELETE    = 'delete';

    private $roleHierarchy;

    function __construct(ContainerInterface $container)
    {
        $hierarchy = $container->getParameter('security.role_hierarchy.roles');
        $this->roleHierarchy = new RoleHierarchy($hierarchy);
    }

    protected function getSupportedAttributes()
    {
        return array(self::CREATE, self::READ, self::UPDATE, self::DELETE);
    }

    protected function isGranted($attribute, $object, $user = null)
    {
        $reachableRoles = $this->roleHierarchy->getReachableRoles($this->roles);
        $roles = array();
        foreach ($reachableRoles as $reachableRole)
        {
            $roles[] = $reachableRole->getRole();
        }

        if (!$user instanceof UserInterface)
        {
            return false;
        }

        if ($attribute == self::READ)
        {
            # Users are allowed to view their own objects
            if (in_array('ROLE_USER', $roles) && $user->getOffice() == $object->getOffice())
            {
                return true;
            }

            # Administrators are allowed to view all objects for all offices.
            if (in_array('ROLE_ADMIN', $roles))
            {
                return true;
            }

        }

        # Return false for everything else
        return false;
    }
}
```

**Comment by javiereguiluz** [comment]
What's the status of this PR? It seems a legit change because right now we're in a "circular mess" of users, tokens, roles and role hierarchies.

**Comment by weaverryan** [comment]
Quickly, there are a few problems with the `AbstractVoter` that we should solve. I don't mean to add more to this, but we should fix them all at once, and add any deprecations we need (for 2.8):

1) It doesn't work unless you pass an object: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Authorization/Voter/AbstractVoter.php#L61. There is an issue about this somewhere, and it's not the end of the world, since you can always implement `VoterInterface` directly, and using objects is the biggest use-case. But, we should consider renaming this class to `AbstractObjectVoter` (which would also allow us to make some of the changes below, while leaving `AbstractVoter` for BC

2) You don't have access to the "token". We originally did this to avoid having 4 args to `isGranted()` . Perhaps we could create/pass a small model object - `UserDetails` with `getUser()` and `getToken` methods.

3) And the change I'm MOST interested in: a common use-case is needing to ask `isGranted('ROLE_ADMIN'` from within a voter (maybe I can edit a `Post` if I'm the author OR if `ROLE_ADMIN`). The problem is that injecting the `security.authorization_checker` or `security.access.decision_manager` causes a circular reference exception. What if we created a new interface - `AccessDecisionManagerAwareInterface` (better name), and if a voter implements this, the `AccessDecisionManager` calls `setAccessDecisionManager` and passes itself before calling `vote()`, This could be stored on a property and used easily to do `$this->decisionManager->decide($token, array('ROLE_ADMIN'))`.

Anyone see any problem - especially with (3)? If we created a new `AbstractObjectVoter`, we could probably do (2) without affecting BC on `AbstractVoter`.

Thanks!

**Comment by gharlan** [comment]
> 3) And the change I'm MOST interested in: a common use-case is needing to ask isGranted('ROLE_ADMIN' from within a voter

+1

**Comment by weaverryan** [comment]
I've just added (3) in #14550. Please review and let me know if you like it and see any issues.

Thanks!

**Comment by gharlan** [comment]
What is the state of this issue? Am I correct that with #14733 it is possible to use `AccessDecisionManager` when implementing `VoterInterface` directly, but not when extending `AbstractVoter` because you do not have access to the token there?
