### ISSUE TITLE
[Session] SessionInterface should have a destroy() method. Currently there is no way to simply destroy a session

### ISSUE THREAD

**Issue by drscre** [symfony/symfony#12375]
SessionInterface::invalidate() method starts a new session after invalidating the current one.

When PdoSessionHandler is used, this creates unnecessary db entries.

In my case sessions have long gc_maxlifetime (because they are used by mobile clients), so there is no way to close a session without generating implicit redundant db rows which stays there for a long time.

**Comment by dbu** [comment]
+1, session needs a bunch of improvements. lets do the necessary BC breaks in symfony 3.0! (add to #11742?)

note that [session_destroy](http://php.net/manual/en/function.session-destroy.php) does not remove the session cookie, only remove all data. but for caching, what we really need is to get rid even of the session cookie. maybe we could call the method `remove()` instead of destroy to avoid confusion.

and lets not mix this issue with the topic of fixing session behaviour to avoid accidental sessions. that is the topic of #6036 and there is #6388 which has been waiting for feedback for a long time.

i hope that #12325 can be pushed forward to clean up session handling in symfony in general.

**Comment by dbu** [comment]
btw, the workaround i currently use is `$response->headers->clearCookie($request->getSession()->getName());`

**Comment by geoffrey-brier** [comment]
@dbu says it all, it's a real problem for caching.
If anyone is willing to write an RFC, I'd gladly write a PR :)
/cc @Tobion

**Comment by andypost** [comment]
What it means "write rfc"?

**Comment by geoffrey-brier** [comment]
@andypost something like that : https://github.com/symfony/symfony/issues/12325

**Comment by geoffrey-brier** [comment]
Oh, juste stumbled upon http://symfony.com/doc/current/reference/configuration/security.html#logout-configuration and the `delete_cookies` node which fits my use case.

**Comment by alterphp** [comment]
@geoffrey-brier Do you finally use `delete_cookies` security logout option ? I can not make it work, or I need to inject if in a logout success handler...

**Comment by geoffrey-brier** [comment]
@alterphp TBH I didn't implement something as only admin can log in, the impact was not that important.

But from what I remember, the delete_cookies would be too complicated to implement as I had a bunch of cookies and I figured that the easiest to do would be to manually clear **_ALL_** cookies in a logout success handler.

**Comment by alterphp** [comment]
@geoffrey-brier Thanks. I use a logout success handler too, as I can't make `delete_cookies` options do the job.
