### ISSUE TITLE
Namespaced Twig Paths cache warmup

### ISSUE THREAD

**Issue by cmodijk** [symfony/symfony#12507]
If you run cache:warmup the twig templates that are in the bundles directory get into the cache folder but not if u use a custom namespace path for twig. I don't know if Symfony renders the cache on first call/open of a custom path template. 

http://symfony.com/doc/current/cookbook/templating/namespaced_paths.html

**Comment by fabpot** [comment]
Do you add templates that are outside of bundles or `app/Resources/views`? If yes, then indeed, they are not taken care of by the `cache:warmup` command. The `TemplateCacheCacheWarmer` class in the Twig bundle relies on the `TemplateFinder` class from FrameworkBundle where we only looks for files in bundles and in the main `app/Resources/views` directory. We could change the logic, but I want to be sure how you store your templates first.

**Comment by cmodijk** [comment]
Yes it's outside of the bundles and `app/Resources/views` directory

**Comment by ShonM** [comment]
A good example for this issue is http://symfony.com/doc/current/cookbook/controller/error_pages.html#overriding-or-adding-templates

If for example you have web servers without node.js, and you use Assetic with less and node but a read-only cache directory, you'll have issues where the web server can't find node. An "easy fix" is to create templates in a bundle and extend from those in `app/`, which triggers their warming.

Additionally, when a template has an exception during compilation it's [straight up ignored](https://github.com/symfony/TwigBundle/blob/master/CacheWarmer/TemplateCacheCacheWarmer.php#L64), so if you have anything like the above issue this could be contributing to that as well.

**Comment by yethee** [comment]
We have the custom templates for error pages in `app/Resources/TwigBundle/views/Exception` directory. Should we manually add path to app config, to allow put them (templates) to cache when running `cache:clear`? Like this:

```yaml
twig:
  paths:
    "%kernel.root_dir%/Resources/TwigBundle/views": "TwigBundle"
```

**Comment by kbond** [comment]
@yethee Because you are overriding the TwigBundle templates, you don't need to set the path at all. Symfony takes care of that automatically and will cache them.

**Comment by yethee** [comment]
New templates, defined into `app/Resources/TwigBundle/views/Exception`, will not be found by `Symfony\Bundle\FrameworkBundle\CacheWarmer\TemplateFinder`. If they are not exist into resources of the bundle.

For example, a file `app/Resources/TwigBundle/views/Exception/error404.html.twig` will be skipped, because a file `TwigBundle/Resources/views/Exception/error404.html.twig` does not exist.

For overridden templates the cache warmer working correctly.

**Comment by kbond** [comment]
@yethee interesting, looks like you're right. I didn't realize that. I am unsure if what you propose would work.. The bundle templates would be found (https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheCacheWarmer.php#L61), then the path templates would be found (https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheCacheWarmer.php#L63). There would be some duplicates but I don't think this would cause a problem.

Have you tried your solution?

**Comment by yethee** [comment]
> Have you tried your solution?

I tried to add path to the config. This is not working as expected, because `ExceptionController` generates template reference in format **bundle:directory:filename**, but the cache warmer uses namespace notation. We have two file in cache for same template after warming cache and first rendering page for an error.

```php
/* @TwigBundle/Exception/error404.html.twig */
class __TwigTemplate_82ea5942c2e29b07b739ac9f0a1148105ea4d52364ebbccd725f58a4849f9066 extends Twig_Template
{
```
And
```php
/* TwigBundle:Exception:error404.html.twig */
class __TwigTemplate_e7ffa9c5c454b12590b7e797c053e049a45a30d3b2385c109cc40ecb3871111c extends Twig_Template
{
```

**Comment by kbond** [comment]
I would open an issue.

**Comment by yethee** [comment]
I created PR #15846, it fixes issue.
