### ISSUE TITLE
[2.6] Var dumper result is not shown in toolbar on not smaller screens

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#12582]
Since the toolbar is so full of stuff, the icons start to fall of the screen, starting with the var dumper. This makes it pretty hard to use it.

**Comment by stof** [comment]
This is not only about the VarDumper. Changing the order of icons to put the VarDumper earlier wil not fix the issue. It will simply change the collector being impacted.

The issue is in the design of the toolbar, which has a fixed height allowing to render a single line of items but still allows items to move on a next line when they are too big. This requires reworking a bit the toolbar design and media queries.
