### ISSUE TITLE
The MimeTypeGuesser::guess() exception message is misleading

### ISSUE THREAD

**Issue by dawehner** [symfony/symfony#12857]
Some users in Drupal had the following exception message:

````
'Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)'
````

Sadly this is not the entire truth, there are two of them by default.
````
        if (FileBinaryMimeTypeGuesser::isSupported()) {
            $this->register(new FileBinaryMimeTypeGuesser());
        }

        if (FileinfoMimeTypeGuesser::isSupported()) {
            $this->register(new FileinfoMimeTypeGuesser());
        }
````

The actual error message should take into account both.

**Comment by Garethp** [comment]
It appears the main cause of this error would be if the server is running on Windows and doesn't have fileinfo extension, because the FileBinaryGuesser uses the shell command "file" which doesn't exist natively on Windows. Should the MimeTypeGuesser, when throwing the exception, check if the server is a Windows server, and respond accordingly?

**Comment by 161710101** [comment]
![image](https://user-images.githubusercontent.com/33051606/52549471-de409780-2e05-11e9-8143-56b353dd44f0.png)

**Comment by xabbuh** [comment]
@161710101 I have no idea what you screenshot is about to tell us, but if you think that you found a bug, please open a new issue and give us some instructions on how to reproduce it.
