### ISSUE TITLE
[RFC][3.0] Drop PHP templates support

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#12897]
When Symfony2 was launched in the summer of 2011, Twig was a relatively new project and thus, Symfony decided to support both Twig and PHP templates. Now it's clear that Twig is the way to go when developing Symfony applications and it's getting better and better with each new version.

That's why **I'd like to propose to drop PHP templates support entirely for Symfony 3.0**.

Pros:

  * Much less code to maintain, specially on heavy components such as forms.
  * Much less documentation to write or maintain. We could use those resources to create new docs or improve the existing ones.
  * Ideally, if we only define one default templating format, we could also optimize Symfony performance and configuration .

Cons:

  * The tiny fraction of developers still using PHP templates will have to configure *something* or install *something* to be able to use PHP templates.

**Comment by dosten** [comment]
Any news on this?

**Comment by webmozart** [comment]
> I don't see how removing PHP templating would give us minutes of free time working on something else.

The removal of *any* feature makes maintenance easier. We're not just talking about fixing bugs. The more features we have, the harder it gets to add new ones, because you have to make sure that *all* the old features still work. More so, duplicate templating engines encourage inconsistencies, because people tend to fix bugs for Twig but forget to fix them for PHP (this is hardly happening the other way round, actually).

I'm :+1: for dropping PHP templating support in core.

**Comment by xabbuh** [comment]
I am :+1: too for dropping support for it in the core.

If there were some people who want to maintain it as a separate community package, this would be great too.

@javiereguiluz What do you think about publishing an article on symfony.com asking for community feedback?

**Comment by javiereguiluz** [comment]
@xabbuh I don't like those kind of surveys because they are biased towards the opinion of the more advanced developers.

**Comment by Green-Cat** [comment]
:+1:  For dropping php templating support.

**Comment by dunglas** [comment]
:+1:

**Comment by xabbuh** [comment]
@javiereguiluz That's true, though developers commenting on GitHub will probably be even more experienced than the ones commenting on symfony.com.

**Comment by dosten** [comment]
If all agree with this, i have a WIP branch with the drop of the Templating component.

**Comment by fabpot** [comment]
@dosten Thanks for volunteering. Most of the work has been done in 2.7, so dropping support for the Templating component and the PHP templating engine should be relatively easy in 2.8. Yes, I said 2.8 as the component and everything we want to drop should be extracted into a component/bundle to continue supporting it in the future. Then, if someone want to still maintain it, that's at least an option.

**Comment by dosten** [comment]
The templating component will be still maintained under the Symfony org? The steps to follow IMO should be:

- Remove the READ-ONLY flag from symfony/Templating
- Drop `src/Symfony/Templating` from symfony/symfony
- Maybe some minor things

As a first step what do you think?

**Comment by stof** [comment]
@dosten we would then need to move the configuration of the Templating component into a separate bundle than FrameworkBundle though

**Comment by dosten** [comment]
@stof yes, of course. I've checked all the places where we depend on the Templating component.

- TwigBridge (only TwigEngine)
- FrameworkBundle
- SecurityBundle (LogoutUrl and Security helpers)
- TwigBundle 
- Form (only TemplatingExtension)
- HttpKernel (only HIncludeFragmentRenderer)

If we create a TemplatingBundle we can (IMO) move into it all the code related from FrameworkBundle, SecurityBundle, Form, maybe HttpKernel.

**Comment by fabpot** [comment]
Yes, the idea is to decouple the sub-tree split from the main repo to make it read/write and to create a new bundle.

**Comment by WouterJ** [comment]
Why do we remove the complete Templating component and not just PHP templating, as suggested by the start post of this issue?

Removing the templating component means **removing a templating abstraction layer** and one of the big Symfony extension points. This means that by default, Symfony will **no longer support anything else than Twig**.

Removing PHP templating from core just means Symfony advocates Twig templates even more, but makes it still possible to use other templating engines (e.g. Smarty, Blades, Plates).

Just extracting Templating from `symfony/symfony` into a seperate repository (`symfony/templating`) doesn't make maintainance easier, as the core team will still need to care about the Templating component. It will make it even harder, as one now has to create 2 PRs (one for `symfony/symfony` and one for `symfony/templating`).

Extracting Templating from `symfony/*` into `some-sf-community-vendor/templating` means PHP templating dies. At the moment, as PHP templating is supported by the core, 3rd party bundles have to provide templating helpers as well (see KnpMenuBundle, CmfCoreBundle, SonataBlockBundle, etc.). Moving PHP templating to a community maintained bundle/component means these bundles will no longer maintain/will remove their templating helpers. This means the community maintained bundle will have to maintain all PHP templating helpers in the community world, which will be a nightmare...

These are just my final 2 cents on this question and why I don't see how Symfony benefits from removing the Templating component (especially when we're not talking about just removing the PhpEngine). Of course, when Symfony wants PHP templates to no longer be used, extracting PhpEngine to a community based bundle is still a possibility.

**Comment by fabpot** [comment]
Indeed, the goal is to remove the Symfony Templating component, not just PHP support. The reality is that **almost** everyone use Twig and that PHP (and of course any other templating engine) is not that well supported today. The big "problem" with the current architecture is that there is a huge performance penalty caused by the templating component layer for no obvious benefit to 90% of the community.

This is better as of 2.7 as I have decoupled Twig support completely from the Templating component and as such, you can use Twig alone without the overhead. The natural next step is to move this extra layer outside the framework. That let other people who do not want to use Twig to be able to do so. But, and that is important: we will need someone/a team to volunteer so that this layer is actually maintained. If not, it means that nobody cares that much as as the code is anyway not maintained anymore, it will die.

**Comment by dosten** [comment]
@fabpot I understand your concerns, I've started some work around this (#15028). As of actually anybody is taking care about the Templating component, I can maintain it as a standalone component.

**Comment by sanjoydesk** [comment]
Removing PHP template support from symfony 3.0 will force developers to use/learn twig templates. But as performance is the concern, I am :+1:  for doping PHP template support from Symfony3.0. 

Would be good if any bridge or service providers to use PHP template component for view, this way developers who are not familiar with twig or want to use Php only will not be upset. So not by default by still developers can make use of PHP template component as their wish.

**Comment by stof** [comment]
> At the moment, as PHP templating is supported by the core, 3rd party bundles have to provide templating helpers as well

The reality is that most bundles don't provide such helpers (most bundles providing one are the ones written in the early days of Symfony when it was not yet clear that Twig would be the winner). And among bundles providing one, some of them are not providing a working one, because nobody actually use the PHP templating engine among the developers of these bundles and so nobody notice about broken things. See https://github.com/KnpLabs/KnpMarkdownBundle/pull/70 for instance which means that the PHP helper is unusable since at least 2 years.

**Comment by mickaelandrieu** [comment]
> The removal of any feature makes maintenance easier. We're not just talking about fixing bugs. The more features we have, the harder it gets to add new ones, because you have to make sure that all the old features still work.

Agree, we should remove a lot of features in Symfony that are not very useful. *Symfony commands, I talk to you here.* Can we open a meta issue where we can discuss about what we should keep and what we should remove ?

**Comment by sstok** [comment]
@mickaelandrieu Symfony commands?

**Comment by mickaelandrieu** [comment]
@sstok not all, but most of provided commands are not used. I'm sad that we can't have statistics on this point. But 71 commands ? realy ? I use at least 10/12 commands when I work with Symfony framework, I'm pretty sure I'm not an exception. Open source softwares tend to grow, we should start on a lighter and more decoupled Symfony 3 as it is *still* possible.

**Comment by lyrixx** [comment]
I reviewed all commands that are present in fresh projet, I almost use every command expects translation and swiftmailer one. 

But anyway, it off topic.

**Comment by periklis** [comment]
@fabpot Would you mind to explain in short the internals of the templating component, which result to the performance penalty?

**Comment by javiereguiluz** [comment]
For what it's worth, [Drupal recently announced](https://groups.drupal.org/node/482888) that they are dropping PHP support entirely and they'll will just use Twig templates.

**Comment by javiereguiluz** [comment]
I'm closing this issue because it's just a "RFC". The requested change is actually happening and Symfony 3.0 will drop PHP support by default. Thank you all for the discussion.

**Comment by dragoonis** [comment]
@fabpot,

in PPI Framework we're using Symfony2 `DelegatingEngine`, `EngineInterface` and also providing users with the ability to use PHP, Twig, Smarty, Mustache built using Templating component as they're all implementing `EngineInterface`

If you don't want to bundle `PhpEngine` with Symfony3 core then that's fine as long as you continue to maintain PhpEngine along with TwigEngine as they are both equally as valuable as each other.

The majority of the people using PPI, coming from a Zend Framework, CodeIgniter ..etc background are used to straight up PHP and thus they enjoy using Symfony's PhpEngine here versus something like Twig or Smarty.

Can you please consider maintaining PhpEngine as it's still a powerful templating engine in itself and a solid alternative to people rolling their own plain old php engines. 

With open source it's difficult to gauge who's using what so based on the unknowns of this I don't think dropping it would be a positive move forward for Symfony3. Making it optional however is totally cool since it's still actually available and maintained.

Thanks for hearing me out.
Paul

**Comment by fabpot** [comment]
@dragoonis The Templating component won't be removed in Symfony 3.0 as we are not reading for that yet anyway. Hearing some use cases is indeed great as it allows us to make better decisions. Thanks for your input.

**Comment by dragoonis** [comment]
@fabpot welcome. feel free to ping me on any other symfony github discussions, happy to give input/insight on things.

**Comment by liubinas** [comment]
> find ./src -name *.html.php | xargs wc -l
....
49299 total

Yes, that's 50 KLOC in PHP templates. And that's just one project. Learning Twig is fun, but what should I do with this? Rewrite?

I don't think that Symfony will get any stronger by dropping support in the core for PHP as a templating language. Essentially, you're dropping support for the language you're trying to promote, which doesn't make any sense. Dropping it from the core and docs would put it into the grey area among other "hack-it-yourself" sad templating ways.

Although I understand that supporting something that is not used around can be trying :) but I'm pretty sure that PHP as a templating language will still be around when Twig is superseded by some newer/faster/cooler engine in the future.

**Comment by Venzon** [comment]
We also use php templates in large application and will need to keep php templates till end

**Comment by jakzal** [comment]
@Venzon @liubinas we only plan to extract it out of the core framework. You will still be able to use it as a third party component. Perhaps, if you use it so heavily you'd be also able to maintain it and take active part in the deciding which direction it takes. Anyway, as fabpot mentioned we won't make it for Symfony 3.0.
