### ISSUE TITLE
[DependencyInjection] ExpressionLanguage providers are not merged

### ISSUE THREAD

**Issue by xphere** [symfony/symfony#13267]
I have a use case to define a `ExpressionLanguage` function in the main container to be used by third party bundles, but can't find a way to do that.

First I tried to add the `ExpressionLanguageProvider` in the `load` method of a `Extension`, but this works with a separate `ContainerBuilder` instance and then the `MergeExtensionConfigurationPass` isn't merging `ExpressionLanguageProvider`s to the main container.

Then I tried to add the `ExpressionLanguageProvider` in the `build` method of my `Bundle` (which receives the main container), but the third-party bundle is also working with a separate one, so it doesn't have the providers from the parent.

I don't know if there's a rationale to disallow this use case. I can see a problem where the first way can fail, so I would find the second as the best approach. /cc @mmoreram

**Comment by stof** [comment]
They should be registered in the build() method of your bundle, not in the extension.
Extensions are getting a temporary ContainerBuilder in their load method, and no service should be retrieved there given that the container is incomplete (which means that no expression will need to be evaluated there by the container, and so it does not need the have the providers)

And I don't understand what you mean about ``the third-party bundle is also working with a separate one, so it doesn't have the providers from the parent.``.

**Comment by stof** [comment]
and the expression providers registered in the ContainerBuilder itself are for the DI expressions. If another bundle is using the ExpressionLanguage for its own use case, it will use a separate ExpressionLanguage instance (available functions will be different in the different context), and in such case, the right solution will be that this bundle registers a compiler pass to let you register your provider through a tag. This is how FrameworkBundle does it for the Security and Routing expressions: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/AddExpressionLanguageProvidersPass.php

the reason why the DI component does it differently is because building the container cannot rely on services defined inside the container.

**Comment by xphere** [comment]
Thanks, as said above I tried the `build` method approach, but it does not work, because my use case is precisely to register our own DI expression for third-parties to use, and their `Extension` will receive a brand new `ContainerBuilder` with no `ExpressionLanguageProvider`s as [MergeExtensionConfigurationPass.php#L46-L48](https://github.com/symfony/symfony/blob/83c15db887fd1f614716ea2de5853ac84054d604/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php#L46-L48).

It would be useful if the parent `ExpressionLanguageProvider`s can be passed into the new containers, so other extensions can rely on those functions to exist in configuration time.

**Comment by stof** [comment]
@xphere but DI expressions will not be evaluated by third party bundles, meaning they don't need your providers (the ContainerBuilder needs them when compiling the expression)

**Comment by stof** [comment]
and if they are evaluating DI expressions at this time, they are wrong. It is the same than calling ``$container->get()`` at this point: it is likely to break, because it is way too early in the container building process (even compiler passes are not allowed to call it safely, and they run later)

**Comment by mmoreram** [comment]
@stof So... fast question. I want to create something like `parameter()` or `service()` in my project using ExpressionLanguage. Is it possible?

Thanks.

**Comment by xphere** [comment]
So, there is no **safe** way to extend the DI ExpressionLanguage?

**Comment by stof** [comment]
@xphere There is (in Symfony 2.6.2+ because 2.6.0 and 2.6.1 are buggy): registering your providers in the build() method of the bundle.

what is not safe is for a bundle to try to **evaluate** expressions in its own DI extension (it can define expressions as much as it wants). and this will never be made safe because it is simply impossible (it supposes using a fully working container at a point where the container is not yet defined fully)

**Comment by xphere** [comment]
Ok, thanks, we're working with latest tag, so 2.6.1 here and maybe that's the problem.

We only need our bundle to define a function and our customers to use it in configuration of their bundles, so no evaluation will be done until the `Container` is ready, am I right?

**Comment by stof** [comment]
yeah, the bundle will not evaluate it. So you issue is the bug which has been fixed in the 2.6 branch and will be part of 2.6.2

**Comment by xphere** [comment]
Just updated to 2.7@dev for testing and it works. Thanks!

**Comment by mmoreram** [comment]
@stof lol! Thanks! :D We really appreciate your help! :D

btw, any idea when 2.6.2 will be released?

**Comment by xabbuh** [comment]
@xphere You should better switch to `2.6@dev` as Symfony 2.7 is still in development and is more likely to break. Once `2.6.2` is released, you can then just remove the `@dev` stability flag.
