### ISSUE TITLE
[Security] refreshUser() doesn't call eraseCredentials()

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#13287]
When checking back some code I wrote, I noticed that I didn't implement `eraseCredentials()` properly. My user always had a Password and Salt. I started to investigate and hit the following issues:

 - A user is always initiated with a password/salt present. 
 - With a refresh, `eraseCredentials()` is never called.

As far as I can tell, a refresh _always_ refreshes the user and is triggered _every_ master request. According to the existing documentation and implementations in the core and FOSUserBundle, the whole user object is returned. This means it also populates the password and salt fields. I can simply fix this by calling `eraseCredentials()` manually in my `refreshUser()`, but I expect the security component to do that for me. What is the desired flow here? Is this done intentionally or a "feature" long forgotten?

The best location to call `$token->eraseCredentials();` would probably be here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L163-L165

**Comment by jaytaph** [comment]
I would agree with this, but i would explicitly call `eraseCredentials()` on the user entity (provided it implements `UserInterface`). But, I would like to see this happen too in the authentication provider as well.

The reason for this, is that right now, only the `eraseCredentials()` of the token is called, and it may or may not, depending on the token, will call the users' `eraseCredentials()` method. 

By calling in the authentication provider manager the `$token->eraseCredentials()` and the `$token->getUser()->eraseCredentials()` explicitly, you are always sure that no matter what kind of token is used with the given user, any sensitive information is explicitly removed. Which is something you would assume when implementing `eraseCredentials()` inside a user (maybe even regardless of the `erase_credentials` configuration setting, but that would be a big BC break).

This also makes the `RefreshUser()` clearer: since it only changes the user, and not the token itself, it doesn't need to do anything with the token, not even clearing it. In that case, it only need to call the `$token->getUser()->eraseCredentials()`.  Clearing the token again would be pointless: either it's already cleared by the authenticator, or it's cleared because it was stored as such in the session. It's only the user-entity you are interested in clearing.

Also, erasing of credentials is a configurable option. The contextListener should have this parameter injected as well.

**Comment by iltar** [comment]
@weaverryan while we are working on relevant things here, what do you think about this?

**Comment by weaverryan** [comment]
@iltar From what I can see, I actually disagree. The point of `eraseCredentials` (which is originally on the `TokenInterface`) is to erase the plan text password from the unauthenticated token (remember, you always have an unauthenticated token that's passed to the auth manager, then an authenticated token after that). Having the encoded password and salt on the User object isn't sensitive. I mean it is - e.g. don't print it out on the screen - but it's not sensitive in the sense that the plain text password is sensitive.

So from what I see - it works as designed currently.

**Comment by iltar** [comment]
I actually didn't even think of the fact that there was supposed to be a
pre authentication token and user up until your guard PR. My user object is
used for both the pre and post, thus has a password filled in for both
cases.

**Comment by xabbuh** [comment]
@iltar This would only be an issue if you stored plaintext passwords in your user storage, wouldn't it? Or put it in other words: How do you get plaintext credentials in your user object on subsequent requests if not retrieving them from your storage?

**Comment by iltar** [comment]
I don't have plain text passwords in there, only the encrypted password which is in the database. But because of the way the custom UserObject is created and used in both locations, it's also present in the user which gets saved into the session and again put back in there during a refresh.

**Comment by xabbuh** [comment]
Maybe I misunderstand your issue, but shouldn't the plaintext credentials be erased during the initial authentication when `eraseCredentials()` is called? So they would never make it into the session and the whole issue would vanish.

**Comment by iltar** [comment]
@xabbuh the credentials of the token are used. The User has a method `getPassword()` that returns the password stored in the user. Either way, it's confusing when you should or should not use which token with what values...

**Comment by weaverryan** [comment]
I agree that it's confusing (hence why I hope we can abstract it away for most users - e.g. Guard), but afaik, I don't think this is a valid bug. Or said differently, I don't think there's anything to do with this issue. @iltar close it? Or do you have some further suggestion?

**Comment by iltar** [comment]
@weaverryan I think it's for the best if we keep it like this and see what Guard will bring us. Maybe this can inspire the other flows to support the same token system. It's weird to have a UsernamePasswordToken on a refresh, because it shouldn't contain a password as the user is already authenticated.

I'll close this and open a new issue if something pops up.
