### ISSUE TITLE
Can't access to parameters array anymore

### ISSUE THREAD

**Issue by fcharrier** [symfony/symfony#13304]
Hi,

I just updated Symfony to 2.3.24 version, and I get errors about this code:
$user_parameters = $this->container->parameters['nexus']['user'];

It seems that I need to rewrite it:
$user_parameters = $this->container->getParameter('nexus')['user'];

Is it normal? Intended? I had a look on differences between 2.3.23 and 2.3.24, but can't find any reference to this problem (http://symfony.com/blog/symfony-2-3-4-released).

Thanks,
Fred

**Comment by stof** [comment]
the fact that the parameters property was public in the dumped container was a bug in 2.3.23 (the property declaration was missing by mistake). This has never been a supported API, and it was not reliable because getting another container (dumped in a different way or not dumped at all) would have used a private property already.
And the documentation has always used the method.

The only properties which are part of the Symfony API for which we provide BC are the properties which are explicitly defined as public (we only use this in the Request object IIRC), not properties created dynamically by PHP when the declarations are missing.

**Comment by fcharrier** [comment]
Thank you so much for your response
