### ISSUE TITLE
Allow dash in route placeholders

### ISSUE THREAD

**Issue by garwat82** [symfony/symfony#13400]
I'm using a component library that uses dashes ("-") in parameter name. The current implementation of Symfony routes doesn't allow dashes in placeholders like /detail/{d-product-id}.

I've tried to make a patch that changes this behavior by modifying the regex to "{[\w-]+}" which worked fine for generating URLs. The other way round to extract the parameter values and assign them to the placeholder (d-product-id) seems much more complicated as the RouteCompiler class uses named regex placeholders (P<name>(...)) and "name" must only consist of word characters. Also, if values should be injected as parameters in actions, dashes are not allowed.

Is there a possibility to get an implementation that accepts dashes in placeholders?

**Comment by Tobion** [comment]
Not possible as you found out yourself. Neither php variables allow dashes nor do named regex placeholders. And magic like changing dashes to camelCase on-the-fly are not viable.

**Comment by stof** [comment]
I suggest that you handle this in your integration layer between your component and the routing component (converting dashes to underscores when calling generating urls and converting underscores to dashes after matching for instance). I don't think this should be done magically in Symfony (where it would cause more harm than good), but it is totally fine in an integration layer between both libraries

**Comment by Kern046** [comment]
Hello there.

I rather comment an old closed issue instead of creating a new one for the moment.

I just had the same problem with the dashes in route parameters, as told in this [stackoverflow topic](http://stackoverflow.com/questions/38528566/symfony-route-is-found-but-not-matched).

I'm not writing this to ask to allow dashes in placeholders, but the described behaviour in my message slowed me down, because the ``bin/console debug:router`` showed me the route without problems, whereas the ``bin/console router:match`` with my route pattern failed.

Perhaps it would be useful to checkout the route pattern with an option for the ```debug:router``` command, or a piece of documentation about the placeholder format (I didn't find it if it's already written). Why not a new command like ```doctrine:mapping:info``` for the Routing component ?

This is just a suggestion, if it seems useless I'm open to hear it :) !

If not, tell me if it's better to open a new issue, this is my first one for the Symfony framework !
