### ISSUE TITLE
PdoSessionHandler Lock wait timeout exceeded

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#13411]
After upgrading to 2.6.3 and switching to the new PdoSessionHandler schema I have been getting these errors in my log sporadically:

```
[2015-01-12 13:28:59] request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction" at /../vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php line 513 {"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction at /../vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php:513)"} []
```

It doesn't appear to be affecting the end users. Seems like it is happening silently.

I followed the updated cookbook article: http://symfony.com/doc/current/cookbook/configuration/pdo_session_storage.html

The `sessions` table is in the same [database as my app](http://symfony.com/doc/current/cookbook/configuration/pdo_session_storage.html#sharing-your-database-connection-information). Could that be causing the problem? Reading the comments for `PdoSessionHandler::LOCK_TRANSACTIONAL` this should not use the same connection but this wouldn't be the case, would it?

I am using MySQL.

**Comment by Tobion** [comment]
The database doesn't matter. So are you using the same connection for sessions and your app?

**Comment by kbond** [comment]
I don't think so although I am a little unclear as to what exactly that means... My app is a standard Symfony app with database connections using doctrine.

I created a `PDO` instance (as shown in the cookbook article) just for use with the PdoSessionHandler. That would be a separate connection, correct?

**Comment by Tobion** [comment]
It means that one session read blocked for over 50 seconds (assuming you have the default value for http://dev.mysql.com/doc/refman/5.0/en/innodb-parameters.html#sysvar_innodb_lock_wait_timeout). I could imagine that a crawler of a search engine generated many parallel request and sessions are used for them, this could cause lock contention (assuming search crawlers send cookie headers, which I don't know).

Or you interfere with the session connection causing more locks than necessary, which as documented should not be done.

**Comment by kbond** [comment]
> you interfere with the session connection

Do you mean using something like `$this->get('session')->set('foo', 'bar')` within your controller?

**Comment by Tobion** [comment]
Now the question would be how often does this error happen? Like in percent of the request.

**Comment by kbond** [comment]
Super low % - like 0.1% of requests or less.

**Comment by kbond** [comment]
> But I would suggest you only pass the dns and the credentials as options to the constructor and let the PdoSessionHandler lazy connect to the db itself

Ok, should I make a PR for the cookbook to do that?

**Comment by Tobion** [comment]
I optimized the database access so that deadlocks should not occur. But we cannot do anything against lock timeouts as this solely depends on the load and the DB configuration.

From my answer in http://stackoverflow.com/questions/9693164/how-to-handle-lock-wait-timeout-errors-in-php-database-based-sessions-using-se/29103037#29103037

> From my research there are basically three options to deal with this:

> 1. Catch the error and retry the transaction in the hope that the lock is released by then. When using Doctrine, have a look at https://github.com/doctrine/dbal/pull/718 for some implementation ideas and discussions.
2. Increase the timeout, e.g. innodb_lock_wait_timeout which might help depending on the database load.
3. Ignore the deadlock or timeout by catching the exception and informing the user that he has to refresh the page for example to get his session back. Usually the lock timeout occurs when the same session is requested many times in parallel, i.e. many parallel requests of the same user. This is a non-standard user behavior and more likely to be caused by scripts or performance testing. So ignoring the error on your side and just displaying an error for the user might be a reasonable approach.


@symfony/deciders I'd say we should go with 3). The lock timeout is 50 seconds by default in innodb. No user would wait this long on a request and thus 1) with retrying makes no sense here.
But I don't easily see how we would implement that. We should not just catch the exception and continue program execution as if no session data was available. That could lead to race conditions again. So raising an exception is the correct thing IMO. But this exception should not be logged as "error" but more like a "warning" and we might want to show a better error page than the standard "An Error Occurred: Internal Sever Error". We could also wrapp the lock wait timeout exception in our custom exception that explains why it happens and devs can usually ignore it.

**Comment by kbond** [comment]
I should note, after upgrading to 2.6.4 and using the updated PDO session config from the cookbook article, I have seen a drastic drop in these errors (down from a couple a day to maybe once every two weeks). Our site sees about 3000 unique sessions a day.

**Comment by kbond** [comment]
I am on 2.7.5 and haven't seen this error in a long time now... Closing.

**Comment by Romain** [comment]
Hi,

Sorry to reopen this, but I'm using Symfony 2.8.13, and I face the same issue.
This error has been occurring for the previous versions of Symfony 2.8, and I can't manage to fix it.

Here is the exact error message:
> request.CRITICAL: Uncaught PHP Exception PDOException: “SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction” at /path/to/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php line 509

It's a bit annoying to have an error occuring from time to time that I can't fix.
Does anyone have a clue of what could be done to stop this?

Thanks for your help.
Romain

**Comment by dmeziere** [comment]
Hello, I recently switched the sessions from Redis to MariaDB under Symfony 6.0.8 and I am facing these errors from then :

`request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction"`
