### ISSUE TITLE
Bootstrap form theme - variable "widget" does not exist

### ISSUE THREAD

**Issue by nicolaskern** [symfony/symfony#13417]
Hi,

We encountered a problem documented in this comment : https://gist.github.com/cowlby/1294186#comment-1362520

```Variable "widget" does not exist in bootstrap_3_layout.html.twig at line 169```

As I said in my answer to this comment, a quick temporary fix was to replace the line 169 with :
```{{ widget|default('')|raw }}```

This problem can be reproduced with the following configuration and the use of the bundle https://github.com/J-Mose/CommandSchedulerBundle
```
twig:
    form:
        resources: ['bootstrap_3_layout.html.twig' ]
```

Is this a known problem ?

Thanks,
Nicolas

**Comment by fabpot** [comment]
ping @lyrixx

**Comment by lyrixx** [comment]
Hi.

The `bootstrap_3_layout.html.twig` works as expected.

But the [CommandSchedulerBundle template](https://github.com/J-Mose/CommandSchedulerBundle/blob/c77138060718603ba74451430cc2b3e80cba925b/Resources/views/Detail/index.html.twig#L21-L24) re-implements on its own the bootstrap layout. So when a user tries to combine the symfony bootstrap template (like this issue) and CommandSchedulerBundle it does not work because symfony has already rendered the widget **and** the label. To fully understand what happens, one should read [that](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig#L118) then [that](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig#L169). So as you can read, and because bootstrap needs a really custom / weird DOM, I had to "hack" the form templating layer. 

There is at least 2 options to fix that:

* Update the CommandSchedulerBundle to use the native/symfony bootstrap, but it would require symfony 2.6+ ..., or doing some check to use one template or another one
* **or** add a safeguard in symfony (the same as describe in this issue). but  i will create another issue: the label will be render twice. (one by symfony by calling ` {{ form_widget( scheduledCommandForm.executeImmediately ) }}` and another one by calling `{{ form_label( scheduledCommandForm.executeImmediately ) }`)

Actually, I don't like theses options.

**BUT**: There is a last option ;), updating the CommandSchedulerBundle to ensure the label is not already => [PR](https://github.com/J-Mose/CommandSchedulerBundle/pull/2)

**Comment by nicolaskern** [comment]
Thanks for your investigation.
This seems to be quite a hard one.

I have seen your cancelled PR, what can I do to help you?

Thanks,
Nicolas

**Comment by weaverryan** [comment]
@lyrixx Actually, there is a simple bug here, and I can give you a small amount of code to replicate it.

### Controller

```php
class DefaultController extends Controller
{
    /**
     * @Route("/app/example", name="homepage")
     */
    public function indexAction()
    {
        $form = $this->createFormBuilder()
            ->add('agreeTerms', 'checkbox')
            ->getForm();

        return $this->render('default/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}
```

### Template

```php
{% form_theme form 'bootstrap_3_layout.html.twig' %}

{{ form_label(form.agreeTerms) }}
```

This produces the error:

>
Variable "widget" does not exist in bootstrap_3_layout.html.twig at line 169

I think the issue is that the label for a checkbox is not meant to be rendered directly - you're supposed to only call `form_widget(form.agreeTerms)`, and *it* renders the label. But if you don't know that, you will try to render it directly, and receive this error. I think we should probably check to see if the `widget` is defined, and *just* render the label if it is not.

Does this help?

**Comment by lyrixx** [comment]
@weaverryan yes. I detect the same issue/cause. I'm not sure it help, because if you use:

```twig
{{ form_label(form.agreeTerms) }}
{{ form_widget(form.agreeTerms) }}
```

in this case the label will be rendered twice.

So I don't know what do to do...
May be we can display **nothing** if the widget var is undefined or empty? and if symfony is in a debug env, display a message to the developer...

**Comment by weaverryan** [comment]
@lyrixx Hey!

Yes, if we followed my proposal, then you would have *two* labels. We have 2 options:

1) Keep this current behavior where `form_widget` renders the label. Was this necessary because of the Bootstrap markup? If we keep this, then we would need to document it. Then, on a PR, we can discuss what to do - i.e. to hide the label entirely or throw an exception. I'm not sure.

2) Remove this special behavior (not sure if this is possible with the Bootstrap markup) so that form_label renders the label and form_widget does not (like normal). Obviously, this would be a BC break and would need to happen in 2.7 at least.

Thanks!

2)

**Comment by lyrixx** [comment]
> 1) Keep this current behavior where form_widget renders the label. Was this necessary because of the Bootstrap markup? If we keep this, then we would need to document it. Then, on a PR, we can discuss what to do - i.e. to hide the label entirely or throw an exception. I'm not sure.

Yes, bootstrap work like that. Look at the [checkbox example](http://getbootstrap.com/css/#forms-horizontal)

**Comment by weaverryan** [comment]
I think we should:

1) make `form_label` print the label (so get rid of the error)
2) keep `form_widget` as it is now, but add a variable that can be changed (if it's not there already) to *not* render the label
3) document this!

**Comment by lyrixx** [comment]
Good idea. Will do that

**Comment by javiereguiluz** [comment]
@lyrixx @weaverryan I'm not sure if that's a good idea. Don't you think that the most common scenario is to not show the regular standalone `<label>` and show instead the `<label>` inside the widget with the `form_widget` function.

In EasyAdminBundle we hide the regular `<label>` using CSS styles and then we show the full widget:

![label-checkbox](https://cloud.githubusercontent.com/assets/73419/5871801/2407f946-a2e3-11e4-839d-41c230995f34.png)

**Comment by weaverryan** [comment]
@javiereguiluz I hadn't seen the EasyAdminBundle :). Looking forward to trying it!

**Comment by karousn** [comment]
i have the same issue when i try to override date or datetime
my twig config :
```
form_themes:
    - 'bootstrap_3_layout.html.twig'
```
my twig file :
```
{% form_theme form _self %}
{%- block date_widget -%}
    {%- if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        <div {{ block('widget_container_attributes') }}>
            {{- date_pattern|replace({
                '{{ year }}':  form_widget(form.year),
                '{{ month }}': form_widget(form.month),
                '{{ day }}':   form_widget(form.day),
            })|raw -}}
        </div>
    {%- endif -%}
{%- endblock date_widget -%}
```
Message error : **Variable "widget" does not exist in default/filter.html.twig at line 3**

**Comment by karousn** [comment]
when i dump the form in the block date_widget i got my global form object instead of my date form

ps : no feedback until now (for a 12 days ago )!

**Comment by xabbuh** [comment]
@karousn We are all doing Symfony stuff in our spare time. So please be patience when asking for help. Added to this, I suggest that you open a new issue instead of commenting on one that was already resolved. You should then also provide some more details about how to reproduce your issue. The best is to fork the Symfony Standard Edition and make the minimum set of changes that are necessary to reproduce your issue.
