### ISSUE TITLE
[DI] Backward compatible bundles with old factory config

### ISSUE THREAD

**Issue by danez** [symfony/symfony#13436]
If a bundle contains the old way to specify a factory-class/-method/-service, what is the proposed way to have your Bundle backwards compatible, but also working with 2.7?

In the example of https://github.com/doctrine/DoctrineBundle/blob/master/Resources/config/dbal.xml#L46 the bundle will throw an E_DEPRECATED if used with symfony 2.7 as it uses factory-service and factory-method and not the new factory-tag. (see https://travis-ci.org/chili-labs/AclBundle/jobs/47301386)

The only thing that I can think of is dropping support for older symfony versions in your bundle and adding a minimum requirement to ~2.6 (suggested here doctrine/DoctrineBundle#367), or having different bundle versions, one for < 2.6 and one for >= 2.6.
Imho both ideas are not really good, as you either stop supporting old symfony versions or need to maintain multiple versions of your bundle.

Does the code need to throw deprecated warnings?

**Comment by iltar** [comment]
Yes, the code needs to throw it. If you've configured your php correctly, you will only see them in the development toolbar.

**Comment by xabbuh** [comment]
@danez You could ship the service definition configuration in two versions and load the appropriate one depending on the version of the DependencyInjection component the user has installed if you don't want to maintain two different versions of your bundle.

**Comment by danez** [comment]
Maintaining different configs for different symfony versions, just to avoid deprecation warnings is still a hassle. Just for the sake of having all the deprecations visible - which is actually not a bad idea - a lot of symfony users will see a lot of this unfixable warnings, as bundles probably won't fix it due to compatibility with older versions. As an symfony-standard project developer, this would make me nervous and think that the bundles are bad maintained, which in fact may not be the case. That's just my general worries about throwing this notices. Or is the plan to get 3rd-party-bundles to drop support for older symfony versions as 2.7 will be an LTS?

**Comment by nicolas-grekas** [comment]
@danez You ask about backward compatibility. But did you think about forward compatibility?
Lets consider this: if you manage to do what @xabbuh invites you to do, you'll have a bundle that is free from deprecation notices and embeds a BC layer for 2.3 components. If it were only for BC that would have little interest on its own: by using the non deprecated 2.7 way you also gain 3.0 forward compatibity! That's the plan and the reason why Sf 2.7 triggers these deprecations: help the ecosystem move forward. I hope that will give you (and the ecosystem) enough incentive to adapt the code.

**Comment by derrabus** [comment]
If @xabbuh's solution is the way to go, maybe it should be added to the documentation or the best practices? I think, this might be a common problem for bundle developers.

**Comment by WouterJ** [comment]
@nicolas-grekas in that case, we should change the BC promise to say that "the last minor version of a major version is by no means BC".

**Comment by nicolas-grekas** [comment]
@WouterJ triggering a deprecation is not a BC break. What is a BC break is defined here: http://symfony.com/bc
Symfony 2.7 will not require anyone to *change* their code. The only thing that *may* be required is changing the error reporting level.

**Comment by stof** [comment]
Thus, Symfony already avoids triggering error exceptions for deprecations. It only logs them

**Comment by WouterJ** [comment]
@nicolas-grekas let's look at it this way:

* When you're using Symfony, you don't want a yellow/red icon in your toolbar saying that there were errors
* When that happends, you are going to report an issue to the bundle that caused it
* There is a 90% change the bundle can't do anything or the bundle will drop 2.3 (which is an LTS) support.
* This means the bundle owner has to say "I know my bundle causes errors in the 2.7 LTS (!), you have to deal with it."

Since we're both know the hassle of maintaining open source projects, we both know that saying that last item is the worst thing possible as a project owner.

Btw, this also makes me wonder if we shouldn't release a 2.8 after 2.7 which does include these deprecation messages and let 2.7 just be a normal LTS release.

**Comment by nicolas-grekas** [comment]
The process you're describing here can stand in one sentence, both  from app dev pov and from bundle dev pov: "I do ignore deprecation notices".

If you really do, then you'd better change the error reporting level. But I hope you're not because we know what the deprecations say: "Ignore me and you'll be stuck alone in the past very soon".

You'd better fix your code. I know it's a pain, we've updated the entire Symfony code base recently. But if you don't, it's perfectly fine. error_reporting is here for you.

**Comment by WouterJ** [comment]
Okay, then we do the process that Symfony wants me to do:

* Let's add "Legacy" classes and change the "normal" classes to use the new way
* Detect support for features/symfony versions and choose whether to use the "Legacy" or "normal" classes.
* Hmm, didn't BC mean Backwards Compability, meaning "You don't have to do anything with code working on 2.3 to make it work without a problem in 2.7". Now I have to put a couple of hours into rewriting my code to make my 2.3 bundle work as it should in 2.7.

**Comment by xabbuh** [comment]
@WouterJ Well, I don't consider changing the `error_reporting` level to be a huge effort. The real effort you have to do is spending time to make your libs forward compatible with Symfony 3.0.

**Comment by WouterJ** [comment]
@xabbuh so you believe that the CMF project is not going to recieve any issue about it causing deprecated errors? I think we get at least a single issue for each line of code that's causing such an error.

**Comment by danez** [comment]
My concern is also, that  a lot of people will report bugs on this deprecation-notices, and maintainers will either ignore that or find weird solutions, just to circumvent the notices but still support 2.3 LTS.

The best-ish solution that comes into my mind right now - in the case symfony 2.7 is going to be released like it is right now - is having a new major version of your bundle for 2.7+, which fixes the deprecations and is hopefully forward compatible. (Probably there will be still changes from 2.7 to 3.0, after 2.7 is released). But that will also lead to new features in the bundle to maybe only show up in the newest version.

I really like the solution from @WouterJ with having a 2.7 version that's not throwing deprecations, and with the release of 3.0 also a 2.8 version that supports all the 3.0 apis, but also the old ones, with deprecation warnings.

**Comment by xabbuh** [comment]
> @xabbuh so you believe that the CMF project is not going to recieve any issue about it causing deprecated errors? I think we get at least a single issue for each line of code that's causing such an error.

Of course, I don't believe that. :) But 2.7 is far from stable yet. What I mean is that there is time to decide about the right strategy for everyone to decide how they want to support Symfony 2.7.

> btw, to be clear: I would love to make all CMF bundles forward compatible. But not at the cost of dropping Sf 2.3 support of the CMF. Also I don't think we're going to write a layer system like the Validation component for each single bundle (and each single class that is not yet forward compatible) as it takes much time for just a few months (as for 3.0, this whole system and legacy stuff is going to be removed).

Honestly, I don't know the Symfony CMF codebase in much depth. But is there really that much deprecated code being used? I know that a lot of deprecation notices have been triggered initially by Symfony itself since the core itself used a lot of deprecated functions which might have led to a misperception of the impact of these changes.

**Comment by danez** [comment]
It seems like @fabpot is working around this problem in this way: https://github.com/fabpot/AsseticBundle/commit/5be3b6fff6b5ac9078d09dfde4250d1853ea2988

**Comment by fabpot** [comment]
and doctrine/DoctrineBundle#381

**Comment by fabpot** [comment]
FWIW, Symfony itself does not use deprecated features anymore in 2.7 and so it should be notice-free.

**Comment by fabpot** [comment]
Closing as DoctrineBundle is now fixed and there is a way for other bundles to keep compatibility wih all versions of Symfony as I demonstrated in DoctrineBundle and AsseticBundle.
