### ISSUE TITLE
[Form] Use 'search' term to named a form

### ISSUE THREAD

**Issue by nlemahieu** [symfony/symfony#13485]
When i create a form named search, the framework doesn't throw an exception to tell that this form type is already registered. Instead, when i put my form in my view i have a new search field which is not describe in my class.

**Example:**

***Implementation***
```
class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('search', 'search', [
            'label' => 'Your search'
        ])
        ->add('Search', 'button');
    }

    public function getName()
    {
        return 'search';
    }
}
``` 

***Result***
```
<form method="get" action="/app_dev.php/backend">
    <input type="search" id="search" name="search" required="required">
    <div>
        <label for="search_search" class="required">Your search</label>
        <input type="search" id="search_search" name="search[search]" required="required">
    </div>
    <div>
        <button type="button" id="search_Search" name="search[Search]">Search</button>
    </div>
</form>
```

We can see in the result that there is 2 fields for searching while i have implement one.

**Comment by stof** [comment]
Allowing to reuse the name is a feature: it allows to overwrite existing fields.

However, overwriting a non-compound field with a compound one can create a very weird behavior.
Here you first get the non-compound rendering for the root form (because it reuses the rendering of the core ``search`` field) and then ``form_rest`` is rendering the child fields because they were not rendered previously.

Note that this is the reason why the Symfony best practices have been updated to recommend naming your app-specific form types with a ``app_`` prefix, which ensures it will never conflict with a core type by mistakes (or with a type from a bundle following the best practices for shared bundles).

Sorry for the delay for the answer. For such support requests, asking on the mailing-list may be faster as there are more people answering there than people monitoring all incoming Github issues regularly (and I am late on this task myself)
