### ISSUE TITLE
[Validator] validation for ill-formed byte sequences 

### ISSUE THREAD

**Issue by masakielastic** [symfony/symfony#13492]
`mb_strlen` doesn't validate ill-formed byte sequences. Non-Shortest Form UTF-8 can be converted to dangerous characters such as `<`, `>`, `/`, `\` in old systems (NET 2.0	.NET 3.0). See Unicode Security Guide for the details ([Canonicalization of Non-Shortest Form UTF-8](http://websec.github.io/unicode-security-guide/character-transformations/#canonicalization)). 

```php
$str = "a\x80bc";

var_dump(
  4 === mb_strlen($str, 'UTF-8')
);
```

```php
$str = "a\x80bc";

var_dump(
    false === mb_check_encoding($str, 'UTF-8'),
    '' === htmlspecialchars($str, ENT_COMPAT, 'UTF-8'),
    false === preg_match_all('/./u', $str)
);
```
The validity of string can be checked by the following functions.

```
var_dump(
    false === mb_check_encoding($str, 'UTF-8'),
    '' === htmlspecialchars($str, ENT_COMPAT, 'UTF-8'),
    false === preg_match_all('/./u', $str),
    NULL === grapheme_strlen($str)
);
```

The frameworks should not depend heavily on databases since some of data types (for example, MYSQL's `binary` type) have no ability to validating ill-formed byte sequences.

**Comment by sstok** [comment]
Interesting, but what is you're actual proposal/bug or question?

**Comment by nicolas-grekas** [comment]
I would broaden the problem to charset validation. For example, what is the expected behavior of LengthValidator when the input string does not match the given charset? With the current implementation, the counted `$length` will end up to be `false` or `null`, which will compare being `>= 0`. That means that a string of arbitrary length but with a charset mismatch will be accepted if zero length strings are accepted.
Ping @Tobion do we need a CharsetValidator?

**Comment by Tobion** [comment]
I fear that one would need to apply a CharsetValidator to every string field if the user can pass a string of arbitrary charset. This makes to kinda cumbersome.
I don't know if there is an actual problem with Non-Shortest UTF-8 string in symfony or twig itself, e.g. failing escaping in twig.
@nicolas-grekas maybe we should just check that `null !== grapheme_strlen` inside the validator.

**Comment by nicolas-grekas** [comment]
See #13528
