### ISSUE TITLE
Translator get fallback catalogue only in transChoice()

### ISSUE THREAD

**Issue by pk16011990** [symfony/symfony#13499]
In `Symfony\Component\Translation\Translator` only method `transChoice()` load fallback catalogue, but method `trans()` doesn't. 

Exactly:
```
$catalogue = $this->catalogues[$locale];
while (!$catalogue->defines($id, $domain)) {
      if ($cat = $catalogue->getFallbackCatalogue()) {
           $catalogue = $cat;
           $locale = $catalogue->getLocale();
      } else {
           break;
      }
}
```

**Comment by stof** [comment]
The method ``trans`` relies on the fact that ``$catalogue->get()`` already deals with checking the fallback catalogue. ``transchoice`` cannot rely on that and needs to deal with the fallback catalogue on its own because it needs to know the locale of the catalogue defining the message to be able to apply the right pluralization rules

**Comment by pk16011990** [comment]
Thank you for explanation. I understand
