### ISSUE TITLE
[Console] Difficulties with PWD when running console apps in Docker container

### ISSUE THREAD

**Issue by advancingu** [symfony/symfony#13508]
I am trying to run ``app/console`` commands from within a Docker container in my development environment and am having difficulties with the way the working directory is used.

For example, running ``/var/www/symfony/app/console assets:install`` as a Docker ``run`` command, the shell's PWD will be ``/`` once the command is executed in the container. This will cause the asset installer to fail as it looks for the ``web`` folder relative to PWD ( see https://github.com/symfony/symfony/blob/eabc9b89010c8287e969f55ddea1c48ff4021625/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php#L73 ).

Of course I could run ``assets:install`` outside the container as my project is only mounted into the container as a volume, however there are other commands (e.g. ``sylius:install``) that require a working database connection which will only be available from inside the container.

Is there any way ``app/console`` could be improved to recognize the project it is running in from its own location?

Right now I am working around it with a small wrapper shell script I put into the ``app`` folder:

    #!/bin/bash

    cd "$( dirname "${BASH_SOURCE[0]}" )"
    cd ..
    app/console "$@"

**Comment by cordoval** [comment]
this problem then is independent of docker. Since on my own project i run the app/console using the absolute path and it fails the same. I think the app/console commands had always been thought to be run from the same folder of the project. In any case you could just do:

```bash
full_path/app/console full_path/web
```
since the first argument is the target web folder for that command.

I tested it and it works. For any other case it will really just depend on the command you are running mostly and for that you have full control on what you write in your command.

**Comment by advancingu** [comment]
This however only works when manually calling ``assets:install``. For example, running ``sylius:install`` will internally call ``assets:install`` but will not allow you to specify the target ``web`` folder, therefore failing the command. The only way to make it work is to execute ``app/console`` from the project directory.

**Comment by cordoval** [comment]
correct and that is how sylius is meant to be run. Docker should call a script rather than a direct symfony command. Calling commands like that on a RUN docker line is not a good practice imo.

**Comment by advancingu** [comment]
I would agree with you about bad practice if we were talking about running these commands inside a regular Docker container, however as I indicated, this is a dev environment and the Symfony project files are runtime-mounted into a volume container. This means none of the Symfony files are persisted inside a container. The container only provides the runtime environment such as DB connection, PHP, etc.. I don't even have a full PHP installed on the host, that's why I need to run these commands inside the container.

To get back on topic, what I'm asking for is if ``app/console`` could be improved to discover the project directory by itself.

For example, a ``--working-dir`` option or similar would make things much easier.

**Comment by cordoval** [comment]
the Process class has that type of abstraction for cwd, however that starts a proc_ process indeed using the cwd passed. In the case of app/console the php process you are starting is indeed in / because you are providing the entire path. SensioDistribution bundle script handler for composer also expects this (running the app/console or bin/console from the project root directory), however if we are looking for options then adding this:

```php
// src/Symfony/Bundle/FrameworkBundle/Console/Application.php
$this->getDefinition()->addOption(new InputOption('--working-dir', null, InputOption::VALUE_REQUIRED, 'Current working directory.', getcwd()));
```
and a change like:

```
// app/console
$cwd = dirname(dirname($input->getParameterOption(array('--working-dir', '-w'), getcwd())));
chdir($cwd);
```
would just do what you want.

**Comment by advancingu** [comment]
For reference, I've just uploaded my Docker setup to https://github.com/advancingu/SfDocker

**Comment by hacfi** [comment]
Maybe @denderello or @seiffert can point us in the right direction here.

**Comment by hacfi** [comment]
@seiffert solves it the following way:
https://github.com/seiffert/symfony-swarm/blob/master/php-fpm/symfony/Dockerfile

**Comment by advancingu** [comment]
Good point, thanks. I hadn't seen Docker's ``WORKDIR`` and it solves my problem well enough.

Closing this issue for now since there doesn't seem to be much need for this feature elsewhere.
