### ISSUE TITLE
PdoSessionHandler is not able to use different transaction isolation level

### ISSUE THREAD

**Issue by kl3ryk** [symfony/symfony#13592]
PdoSessionHandler should allow customizing transaction level (https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L443). 

IMO there should be something like this:
```php
$transactionIsolationLevel = $conn->getTransactionIsolation();
$transactionIsolationLevelSql = $conn->getDatabasePlatform()->getSetTransactionIsolationSQL($transactionIsolationLevel);
// execute $transactionIsolationLevelSql 
```

**Comment by Tobion** [comment]
For what reason?

**Comment by kl3ryk** [comment]
On our server there is `binlog_format=STATEMENT` and because of that there is an error:
```
SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.
```

And this hardcoded sql `SET TRANSACTION ISOLATION LEVEL READ COMMITTED` can be used only with `binlog_format=RAW` or `binlog_format=MIXED`

**Comment by Tobion** [comment]
1. using a different transaction level doesn't work reliably, which is why this code is there
2. binlog_format=STATEMENT is not good for session data. so binlog_format=ROW is a better fit. you can even change the binlog_format per connection at runtime.

> A session that makes many small changes to the database might want to use row-based logging.
A session that performs updates that match many rows in the WHERE clause might want to use statement-based logging because it will be more efficient to log a few statements than many rows.

**Comment by kl3ryk** [comment]
1. I don't want to use any specific isolation level.
2. I know - it will be changed on our servers.

What I need - is to run my code on any `binlog_format` configuration.

I found that this is not only `PdoSessionHandler` issue. After vendors update this error is thrown on any insert.

On the same machine i have two versions of my code - with updated vendors and without. One of them have those errors and another one has not. I will compare what has changed.

**Comment by kl3ryk** [comment]
Ok I have compared everything and now I'm sure that `PdoSessionHandler` is causing problems. After session is initialized and `ISOLATION LEVEL` is set, all queries are executed with this isolation level.

So if you are using `PdoSessionHandler` and `binlog_format=STATEMENT` you will never be able to work with it because `PdoSessionHandler` have hardcoded `ISOLATION LEVEL` initialization.

**Comment by Tobion** [comment]
As I said, don't use `binlog_format=STATEMENT` because it's not good for single row operations. You could maybe make a PR to add `SET SESSION binlog_format = 'ROW';` before starting the transaction.

Also you could change the lock_mode to `PdoSessionHandler::LOCK_ADVISORY`. This will not require a transaction and thus also not change the isolation level.

**Comment by Tobion** [comment]
We want to prevent gap locks which is why we have to use READ COMMITTED transaction isolation. See http://www.percona.com/blog/2012/03/27/innodbs-gap-locks/ 

To add the SQL in the class would require the SUPER priviledge: "To change the global binlog_format value, you must have the SUPER privilege. This is also true for the session value as of MySQL 5.1.29."
So I think it's not a good idea either. And as an option it would be the same as if the user used the better binlog_format for sessions in the first place as he would need to know about it.

So closing.

**Comment by kl3ryk** [comment]
@Tobion thanks for explanation

**Comment by vide** [comment]
So @Tobion are you implying that one should have a *whole dedicated* mysqld cluster (master+slave) just for one, single sessions table?!? Or change the replication format of a whole mysqld cluster to support Symfony session management?
Both options seem a little bit overkill to me to say the least...

**Comment by Tobion** [comment]
Feel free to make a PR if you have a solution.

**Comment by kl3ryk** [comment]
@vide I have changed bin log format and it solved the problem. But it was environment where I had direct access to it's configuration. But there are still some problems with projects where I can't change the database configuration (eg. most of hosting operators).

Still if you are using `PdoSessionHandler` and hosting with `binlog_format=STATEMENT` you will never be able to work with it because `PdoSessionHandler` have hardcoded ISOLATION LEVEL initialization.

The only one possible solution for now is to use `PdoSessionHandler::LOCK_ADVISORY` as @Tobion said previously.

I try to find some time to solve this problem for this particular case and make a PR with proposal of solution.

**Comment by vide** [comment]
@kl3ryk  thanks for you reply @Tobion Sorry, I missed the bit about LOCK_ADVISORY so I think I will tell the developers to try this solution (I'm a sysadmin maintaining the mysqld cluster affected by this).
