### ISSUE TITLE
[HttpKernel] Why are StreamedResponse's sent by a kernel.response listener?

### ISSUE THREAD

**Issue by gerryvdm** [symfony/symfony#13591]
I was wondering what the exact use of the StreamedResponseListener in the HttpKernel is, since responses are typically sent to the browser anyway by invoking Response::send() in the front controller.

Maybe this event subscriber can be eliminated? Or what are the use-cases?

**Comment by ogizanagi** [comment]
Might be wrong, or incomplete, but I think this is to avoid triggering some response listeners like the [FragmentListener](https://github.com/symfony/HttpKernel/blob/master/EventListener/FragmentListener.php), esi, profiler, ... before sending the Response to the client : 

```php
class StreamedResponseListener implements EventSubscriberInterface
{
    static public function getSubscribedEvents()
    {
        return array(
            KernelEvents::RESPONSE => array('onKernelResponse', -1024), //The priority is set to 1024
        );
    }
}
```

As you can see, the priority is set to `-1024`, and the Response is sent inside the Listener. Which means that any other listener will not have any effect if its priority is over `-1024`.
So no, it could not be removed.

**Comment by gerryvdm** [comment]
Not sure I understand @ogizanagi, every kernel.response listener with a priority > -1024 (I assume most if not all) is executed before the StreamedResponseListener.

**Comment by ogizanagi** [comment]
Right. My assumptions were biased as I inverted the priority. Forgot what I said :)

**Comment by stof** [comment]
The response is send by the listener so that the callback is triggered before leaving the request scope, i.e. before leaving the ``Kernel::handle()`` call.

**Comment by javiereguiluz** [comment]
I think it's safe to close the issue. @gerryvdm's question is answered in https://github.com/symfony/symfony/pull/2935#discussion_r310919 and it seems like there's nothing else to do.

**Comment by TomaszGasior** [comment]
@stof 

>The response is send by the listener so that the callback is triggered before leaving the request scope, i.e. before leaving the Kernel::handle() call.

Could you please tell me why is this important at all? Why is that important to trigger callback in Kernel::handle() instead of in send() method in front controller? What's the difference at all? StreamedResponse works exactly the same without this listener and the listener breaks compatibility with tests.

Here, in 2020, I tried to write tests for request which returns streamed response with PDF document. Wich StreamedResponseListener my terminal is polluted with binary contents. With StreamedResponseListener disabled **response of the web applications works exactly the same**.

The existence of StreamedResponseListener causes two negative things for tests:
- Output of reponse pollutes terminal.
- You can't get content of response from test.

This code, designed for StreamedResponse completely does not work because of the listener: https://github.com/symfony/http-kernel/blob/81d42148474e1852a333ed7a732f2a014af75430/Client.php#L194 . So basically what's the difference? Can't we disable StreamedResponseListener, at least for tests?
