### ISSUE TITLE
Twig render problem with form use name "time" in FormType

### ISSUE THREAD

**Issue by andrewsmm** [symfony/symfony#13590]
I use twig in Symfony 2.6.5. I created a FormType and set in public function getName(){ return "time" }
and get next error when render form(form):
Variable "widget" does not exist in form_div_layout.html.twig at line 123

```
{% block time_widget -%}
    {% if widget == 'single_text' %}
        {{- block('form_widget_simple') -}}
    {% else -%}
        {% set vars = widget == 'text' ? { 'attr': { 'size': 1 }} : {} %}
        <div {{ block('widget_container_attributes') }}>
            {{ form_widget(form.hour, vars) }}{% if with_minutes %}:{{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %}:{{ form_widget(form.second, vars) }}{% endif %}
        </div>
    {%- endif %}
{%- endblock time_widget %}
```

If i use any other name this problem resolve.

**Comment by jakzal** [comment]
This happens because the `time` name is already taken by the `TimeType`. As mentioned in [the documentation](http://symfony.com/doc/current/book/forms.html#creating-form-classes): 

> note that the getName() method should return a unique identifier for this form "type"

In other words, choose a different name for your form. Using a prefix for your form names will make it less likely you'll get a name clash.

**Comment by andrewsmm** [comment]
Thanks
