### ISSUE TITLE
[form] Delete_empty issue

### ISSUE THREAD

**Issue by Looted** [symfony/symfony#13601]
I have a one-to-many relation, where child is the owning side. I embed the childs form in the parents form as a collection type field. That way I can dynamically add new children, change their content and remove them (with the oprhanRemoval set to true on parent entity annotations). When I leave the child form empty however, this happens:

```
An exception occurred while executing 'INSERT INTO child
(content, completed, parent_id, created_by) VALUES (?, ?, ?, ?)'
with params [null, null, null,  null]: Column 'content' cannot be null
```

The request with the parent entity has:

```
  children => [
        0 => [
         content => 
        ]
  ],
```

Delete_empty and allow_delete is of course set to true. There is no required set. Any idea why doctrine tries to perform an insert instead of deleting the empty entity?

**Comment by Looted** [comment]
I've managed to fix this issue. I was adding the empty child in the createForm method. The logic went as follows:

####Edit action

    $parent = $em->getRepository('AppBundle:parent')->find($id);
    $editForm->createEditForm($parent)

####Create edit form method

    public function createEditForm(Parent $parent){
        $child = new Child();
        $parent->setChild($child);
        $form = $this->createForm(...)

The child needed to be added in the edit action, before creating the form (so the entity passed to form already had the empty entity). Is this intended behavior? If yes, then please close the issue.

**Comment by jakzal** [comment]
Please ask support questions on the mailing list. Thanks.

**Comment by Looted** [comment]
I may have worded it badly - the issue was delete_empty not behaving like it should (based on documentation).

**Comment by jakzal** [comment]
Sorry.

It would be easier to debug your issue if you forked Symfony Standard Edition and recreated the issue on a new branch.

**Comment by Koc** [comment]
Relates to #13940.

It would be useful add option like `entry_is_empty_callback` to `CollectionType` with will recieve child model data and return bool (`true` for empty objects).

```php
class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add(
                'productAttributeValues',
                'collection',
                array(
                    'required' => false,
                    'entry_type' => ProductAttributeValueType::class,
                    'entry_options' => array(
                        'category_id' => $product->getCategory() ? $product->getCategory()->getId() : null,
                    ),
                    'entry_is_empty_callback' => function (ProductAttributeValue $productAttributeValue = null) {
                        return null === $productAttributeValue->getAttributeValue();
                    },
                    'allow_add' => true,
                    'allow_delete' => true,
                    'delete_empty' => true,
                    'by_reference' => false,
                )
            );
```

WDYT @Looted , @nino-s , @webmozart ?

**Comment by murilolobato** [comment]
@Looted , delete_empty work for your case. You may have just not configured it correctly. I'll try to explain because it is a little confuse in the docs. I've already opened a issue in the docs, to try to make it more clear, here: https://github.com/symfony/symfony-docs/issues/7630

If you have a collection of another form type, the following will happen:
- If your embedded form has `data_class` defined, and the collection is passing `entry_options => ['required' => false]`, and `delete_empty` is true, it will work  as you desire. Empty collection items will be removed when you submit the form. Configuration e.g.:

        // OrderType.php
        ...
        ->add('items', CollectionType::class, [
            'entry_type' => ItemType::class,
            'allow_add' => true,
            'allow_delete' => true,
            'delete_empty' => true,
            'by_reference' => false,
            'constraints' => [
                new Assert\Valid(),
                new Assert\Count(['min' => 1]),
            ]
        ]) 
        ...

- If your embedded form has `data_class` defined, and you don't pass the correct `entry_options`, even if you set `delete_empty` to true, it will not work. Empty collection items will be validated in the interface, and will not be removed.

The reason for this is in the FormType documentation, because when we create the `ItemType` in this case, ItemType is a instance of FormType, so to understand it we have to recur to FormType doc, more specifically the empty_data section, here http://symfony.com/doc/2.8/reference/forms/types/form.html#empty-data .

So, I think that for this specific case you are reporting, there is no need for the proposed `entry_is_empty_callback` option.
