### ISSUE TITLE
[Debug] Wrong exception handler passed to setExceptionHandler method

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#13707]
Hi all!
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Debug/ErrorHandler.php#L143
```php
$handler->setExceptionHandler(set_exception_handler(array($handler, 'handleException')));
```
`set_exception_handler` returns _previous_ exception handler. Seems  that this is not expected behaviour, because previous exception handler is `null`.

**Comment by nicolas-grekas** [comment]
This is expected behaviour: we only want to wrap the existing exception handler. If there is no existing one, it's fine. Null is cirrectly handled [here](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Debug/ErrorHandler.php#L233) and [here](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Debug/ErrorHandler.php#L469).

**Comment by Strate** [comment]
Okay
