### ISSUE TITLE
Deprecated TableHelper is being used by Application

### ISSUE THREAD

**Issue by antonioribeiro** [symfony/symfony#13732]
I was getting this error

    exception 'ErrorException' with message '"Symfony\Component\Console\Helper\TableHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\Table" instead.' in /var/www/tests/l5/vendor/symfony/console/Symfony/Component/Console/Helper/HelperSet.php:86

And found the file being used in:

    vendor/symfony/console/Symfony/Component/Console/Application.php:use Symfony\Component\Console\Helper\TableHelper;

**Comment by WouterJ** [comment]
Please update your Symfony version. This error is no longer triggered by Symfony core.

**Comment by cordoval** [comment]
nonetheless it should be changed right @WouterJ ? would you take a PR or there is a PR already for this?

**Comment by stof** [comment]
The Application indeed registers the deprecated helper because of the BC constraints. However, we will trigger the warning only when you retrieve the deprecated helper, not when instantiating them.

We cannot stop registering them. Deprecated features must continue to work (with deprecation warnings being thrown, which does not trigger exceptions in Symfony because of our error reporting config, but would indeed trigger exceptions by default in PHPUnit)

**Comment by cordoval** [comment]
will 2.7 still do this? or 3.0 will remove them?

**Comment by WouterJ** [comment]
Btw, as this issue is already fixed, it should be closed, right?

The TableHelper will trigger the error only when `$triggerDeprecation` (constructor argument) is set to `true` (default value). When registering it in the HelperSet, it instantiates it with `false`, meaning that it is no longer a problem.

**Comment by antonioribeiro** [comment]
I'm having this on

    symfony/console  2.7.x-dev 289113e  Symfony Console Component

**Comment by WouterJ** [comment]
Btw, we should improve the error triggering as it is not triggered when using it...

**Comment by antonioribeiro** [comment]
Unfortunatelly this is not being used by me, but Laravel and http://psysh.org/.

**Comment by cordoval** [comment]
oh, interesting, then perhaps you should try to use something more stable? 2.7.x-dev is bleeding edge. I use it also for some projects but it is my responsibility to solve any issues.

**Comment by WouterJ** [comment]
Hmm, it's strange you get that error with 289113e, @antonioribeiro.

Here it is registered (note the `false`)
: https://github.com/symfony/Console/blob/289113e60aad754d35b50347f66ecd3a4d96d03c/Application.php#L959
And here you can see that it should not trigger in that case: https://github.com/symfony/Console/blob/289113e/Helper/TableHelper.php#L37-41

Also, I would indeed suggest to use 2.6. 2.7 is still in early dev...

**Comment by stof** [comment]
@WouterJ we should be triggering the message when getting the helper from the application.

@cordoval It has already been removed in the 3.0 branch

**Comment by stof** [comment]
@antonioribeiro the deprecation notice was expected because Psysh is using the deprecated feature. Note that Psysh added a commit to hide it in https://github.com/bobthecow/psysh/commit/7e3349762ffd6c1598037802b99e8c78e765ae71 so check which version you are using

**Comment by antonioribeiro** [comment]
On Laravel It's not being fired by TableHelper itself, but https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Console/Helper/HelperSet.php#L86

**Comment by WouterJ** [comment]
That means it's used by some library, which is Psysh in this case. See @stof's comment above yours.
