### ISSUE TITLE
ESI: Response with content although FragmentListener throws AccessDeniedHttpException

### ISSUE THREAD

**Issue by IceShack** [symfony/symfony#13773]
Hi,

We added som ESI calls into our app and wanted to check if they aren't callable from the Browser.
So in dev mode we looked up the URL for a fragment and opened the link in a browser.
We expected to see a 403 response without any content, but got the 403 status with the correct content.

I can reproduce the error in a newly created project.

Example Response (http://127.0.0.1:8000/_fragment?_path=_format%3Dhtml%26_locale%3Dde%26_controller%3DAppBundle%253ADefault%253Afragment):

    HTTP/1.1 403 Forbidden
    Host: 127.0.0.1:8000
    Connection: close
    X-Powered-By: PHP/5.5.9-1ubuntu4.6
    Cache-Control: private
    Date: Tue, 24 Feb 2015 09:08:13 GMT
    X-Debug-Token: 7ae2aa
    X-Debug-Token-Link: /_profiler/7ae2aa
    Content-Type: text/html; charset=UTF-8
    X-Symfony-Cache: GET /_fragment?_path=_format%3Dhtml%26_locale%3Dde%26_controller%3DAppBundle%253ADefault%253Afragment: miss
    
    Fragment!!!!

**Comment by fabpot** [comment]
You're responsible for protecting the fragments yourself. If done, http://symfony.com/blog/cve-2015-4050-esi-unauthorized-access might have fixed your issue.

**Comment by jakzal** [comment]
@IceShack what's the Symfony version do you use?

**Comment by stof** [comment]
ESI calls are callable from the browser in Symfony btw (because determining whether the query started in the browser or in Varnish itself is not possible unless you manipulate the Varnish config to add extra headers when starting a ESI request, but not when forwarding the same request done by the browser). This is why the fragment listener requires the usage of signed URLs

**Comment by IceShack** [comment]
@fabpot, I just checked and that fixed my issue. thx
