### ISSUE TITLE
Body empty when using multipart request 

### ISSUE THREAD

**Issue by roelveldhuizen** [symfony/symfony#13846]
In the code bellow I expect the $request->getContents() to get the body content of the HTTP request. When sending non multipart request this works as expected though when using multipart requests the $body variable remains empty.

```
public function postDebugAction(Request $request) {
    $body = $request->getContent();

    if (empty($body)) {
        throw new \Exception('Body empty.');
    }


    return $this->view(array(), 201);
}
```

According to my PHPUnit test this was working though when using Postman and Advanced Rest Client to simulate the request the body seems to be empty again. I double checked this to run both the simulate requests as PHPUnit with the debugger. Result is that, indeed, the body is empty when simulated via a Rest client and not empty when ran through PHPUnit.

POST url:
```
http://localhost/EntisServer/web/app_dev.php/api2/debug
```
Headers:
```
Authorization: Bearer ZGYzYjY1YzY4MGY3YWM3OTFhYTI4Njk3ZmI0NmNmOWZmMjg5MDFkYzJmOWZkOWE4ZTkyYTRmMGM4NTE1MWM0Nw
Content-Type: multipart/form-data; boundary=-----XXXXX
```

Content:
```
-----XXXXX
Content-Disposition: form-data; name="json"
Content-Type: application/json; charset=utf-8

{
    "blabla": 11
}

-----XXXXX
Content-Disposition: form-data; name="q_3101"; filename="image.jpg"
Content-Type: image/jpeg

contents of a file...

-----XXXXX--
```

**Comment by roelveldhuizen** [comment]
I've added breakpoints to app_dev.php and app.php. When debugging the code from by sending a request from Postman, the breakpoint will hit one of those breakpoints. However, debugging from the PHPUnit test none of those breakpoints will be hit. 

What is the difference between the entry point when using PHPUnit or another tool? Why is there a difference at all?

**Comment by roelveldhuizen** [comment]
Oddly, the PUT seems to work though; the POST remains empty. 
Regarding my previous comment I already found out the difference. The client used in PHPUnit creates the Request object directly and does not do an actual HTTP call.

**Comment by roelveldhuizen** [comment]
The ``` file_get_contents('php://input'); ```in the getContents() of bootstrap.php.cache return null  for some reason.

Whole getContents code:
```
public function getContent($asResource = false)
{
if (false === $this->content || (true === $asResource && null !== $this->content)) {
throw new \LogicException('getContent() can only be called once when using the resource return type.');
}
if (true === $asResource) {
$this->content = false;
return fopen('php://input','rb');
}
if (null === $this->content) {
$this->content = file_get_contents('php://input');
}
return $this->content;
}
```

**Comment by unkind** [comment]
http://php.net/manual/en/wrappers.php.php#wrappers.php.input

**Comment by roelveldhuizen** [comment]
@unkind I would expect that the content would not be availble for all multipart/form-data request though, this seems only true for POST requests. Is this correct? And is there a workaround? 

```
php://input is a read-only stream that allows you to read raw data from the request body. In the case of POST requests, it is preferable to use php://input instead of $HTTP_RAW_POST_DATA as it does not depend on special php.ini directives. Moreover, for those cases where $HTTP_RAW_POST_DATA is not populated by default, it is a potentially less memory intensive alternative to activating always_populate_raw_post_data. php://input is not available with enctype="multipart/form-data".
```

**Comment by unkind** [comment]
This topic isn't Symfony related. PHP works like that, it is correct behaviour.

**Comment by jakzal** [comment]
This is indeed how PHP works. There seems to be [no sane way](http://stackoverflow.com/questions/20148612/php-input-is-empty-on-post-request) to retrieve the content with POST multipart/form-data requests.

**Comment by DazDotOne** [comment]
As mentioned, this isn't a symfony (or laravel, or any other framework) issue, it's a limitation of PHP.

After trawling through a good few RFCs for php core, the core development team seem somewhat resistant to implementing anything to do with modernising the handling of HTTP requests. The issue was first reported in 2011, it doesn't look any closer to having a native  solution.

That said, I managed to find [this PECL extension](https://pecl.php.net/package/apfd). I'm not really very familiar with pecl, and couldn't seem to get it working using pear. but I'm using CentOS and Remi PHP which has a yum package.

I ran `yum install php-pecl-apfd` and it literally fixed the issue straight away (well I had to restart my docker containers but that was a given).

That is, `request->all()` and `files->get()` started working again with PATCH and PUT requests using `multipart/form-data`.

Ergo, I managed to get my api playing nicely with my front-end without adding any quirks (that would need to be relayed to anybody developing front-end solutions) or breaking RESTful conventions.

I believe there are other packages in various flavours of linux and I'm sure anybody with more knowledge of pear/pecl/general php extensions could get it running on windows or mac with no issue.
