### ISSUE TITLE
[Security] Change of username / password does not cause logout

### ISSUE THREAD

**Issue by ptrm04** [symfony/symfony#13870]
Steps to reproduce:

1. Follow http://symfony.com/doc/current/cookbook/security/entity_provider.html with the AcmeDemoBundle
2. Load a fixture for the user http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html
3. Login
4. Change the username or password hash behind the scenes in the database
5. Reload the page - the user should be logged out at this point but is not - according to the cookbook article. The user remains logged in and if you changed the username, the updated username comes up in the profiler.

Using Symfony 2.6.4, PHP 5.4.35

Could anyone else please try it and let me know if you experience the same? Thanks.

**Comment by timglabisch** [comment]
the user is "refreshed" by the id.
https://github.com/symfony/symfony/blob/d94d837e9ea75d76eeb0a43e0535a5e7a7a01542/src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php#L95

i dont think this is a bug.

**Comment by iltar** [comment]
I think you should implement the `EquatableInterface`.

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L250-L252
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/User/EquatableInterface.php

**Comment by ptrm04** [comment]
Thanks for your replies, if you could please try it on your dev machine projects, you should be able to see it in action. Either by following the steps I have listed or just do 4 & 5 for your existing projects (given you serialize username / password in the User entity, which should be for security and the checks as mentioned as part of this issue)

@timglabisch it reloads the user just fine by the id as in the cookbook article, then it uses the reloaded user to check against what has been serialized in the session, i.e. username, password etc. In `AbstractToken` you can see that `$this->user` contains only the values for what has been previously serialized, and `$user` is the "refreshed" hydrated user object

@iltar there should be no need for the `EquatableInterface` as it is to be used to check your custom checks, username / password is handled out of the box
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L254-L256
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L262-L264

**Comment by iltar** [comment]
@ptrm04 Does it even hit that code? I've not used that guide as an example before so I can't tell.

**Comment by ptrm04** [comment]
@iltar Indeed it does, I have run through it with xdebug so many times trying to figure this one out.

**Comment by iltar** [comment]
@ptrm04 and if you check `$this->user` and `$user` in the `hasUserChanged()` method, are they different objects? Did the values change accordingly? Did the refresh take place too soon and has filled in the new values already?

**Comment by ptrm04** [comment]
@iltar the objects are different, meaning the username or password change is detected, in case of username https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L262-L264

**Comment by ptrm04** [comment]
Tried with PHP 5.3.27, same story, user remains logged in even though the change of username / password got detected. What's missing?

**Comment by tetranz** [comment]
I'm experiencing the same thing. Before I saw this issue I described the problem and asked a question on Stackoverflow.

http://stackoverflow.com/questions/29201019/symfony-2-6-5-custom-userprovider-user-not-logged-out-when-user-isequalto-ret

**Comment by ptrm04** [comment]
@tetranz thanks for confirming this, I did see a few questions on SO asking about the same issue.

**Comment by tetranz** [comment]
I did some more digging tonight. It seems to be related to using a login form. It works correctly with http_basic.

To eliminate any of my code, I started with the Symfony demo app. I then followed [this](http://symfony.com/doc/current/cookbook/security/entity_provider.html), including http_basic, to change from the memory user provider to the built-in entity provider.  That worked correctly. Then I changed to the login form form and then I get the problem.

I changed my own application to http_basic and then that work correctly. Of course, I want a nice form.

**Comment by tetranz** [comment]
After some more testing, I somewhat take back what I said above.  http_basic prompts me to login again when I change the username or password in the database but it doesn't do it if I change other field. My user has an email field, I implemented EquatableInterface and serialized email but it does not prompt me to login again if I change email.

Since http_basic sends the credentials in every request, I'm not sure if it really is "working" for username and password or something a little different is really happening. I verified that EntityUserProvider::refreshUser and User:isEqual are being called on every request.

**Comment by ptrm04** [comment]
@tetranz there is definitely something ongoing - wish I had more time to dive into it, this could affect quite a number of developers. If we could get someone who has tried the steps above and can confirm that he/she is not affected by it we could then take it forward if that was the case. I have tried it on different hosting environments and it all behaves the same. Symfony config checker says you are "good to go" and gives a thumbs up for the hosting environment.

**Comment by dpistole** [comment]
Similar issue here I think. I have a customer user provider implemented, with a refreshUser function that uses loadUserByUsername.

If I log in, and then go behind the scenes and swap the usernames for me and another user, when I go to a new page I get to see the other users data instead of mine, as if it does not check the password but just loads the userdata based on the username.

If I go behind the scenes and change the password for my user and refresh, the page loads fine, without checking the password in my token against the password on my user. My user class is serializing the id, username, password, salt, and isActive fields. I've looked at the session data on my server and the serialized data is there OK.

This all started for me because user A was logged in, and then all of the sudden ended up logged in as user B (and could view semi sensitive information). It turned out that someone had removed the username on User B. I think User A was logged in, it somehow ran refreshUser with an empty string (still havnt been able to reproduce this piece), and then found User B and loaded his data.

My understanding was that as long as I am serializing the username, password, etc. then it should detect these changes when it tries to compare the token to the user found by username. If the token data does not match it should force a logout/login.

**Comment by iltar** [comment]
Even thought that's a case that is unlikely to happen, I do agree that this is a pretty bad vulnerability if configured incorrectly. I have just tried to reproduce this and failed to do so.

_Why does this work for me?_
My username (username) is nothing more than an Alias for my actual user identifier (client_id). When the client logs in, the alias is used to find the username. This alias will find the correct user. However, instead of storing the actual username, I stored the client_id in the user as username (`getUsername()` should've been `getIdentifier()`. Because I store the client identifier and not the username (aliases can change), it works like intended for me as the `refreshUser` will look up the client authentication by id instead of username.

**Comment by stof** [comment]
@dpistole and this is precisely why the EntityUserProvider is reloading by primary key to avoid issues with people using a mutable identifier. The UserInterface defines the username as being an identifier of the user. Mutable identifiers always cause pain.
@iltar you might suffer from issues if you use the ACL system though, as it uses the username as identifier.

@dpistole are you using an access control rules on your controller or no ? The check in the token means that any isGranted check will be rejected later, and so access control rules will block access (and the ExceptionListener of the firewall will prompt to authenticate again when seeing an AccessDeniedException because of that too)

**Comment by dpistole** [comment]
@stof that makes sense, thanks for the information. I had followed the cookbook writeup on creating a custom user provider, maybe I can update that doc. I will update my refresh user to lookup by id which does not have the potential to be blank/deleted/changed.

@stof my access control rules are configured in security.yml not on the controller (if i am understanding the question correctly). I don't quite follow what you're saying about the check in token, apologies for my confusion, still relatively new to the framework.

**Comment by tetranz** [comment]
I think the issue of mutable user identifiers is a side issue to the original raised by @ptrm04 and confirmed by myself. That is, the part of [this documentation](http://symfony.com/doc/current/cookbook/security/entity_provider.html#understanding-serialize-and-how-a-user-is-saved-in-the-session) which says:

"For example, if the username on the 2 User objects doesn't match for some reason, then the user **will be logged out** for security reasons."

I interpret that to mean that if your user class implements EquatableInterface and isEqualTo() returns false for any reason then the user will be logged out.

That does not work for me. I have not heard anyone confirm that it works for them.

It seems that you should be able to have a logged in user happily clicking away. You then change the password or something directly in the database and the user should be logged out on the next request provided that a password change causes isEqualTo() to return false.

Can anyone actually report seeing this happen?

**Comment by tetranz** [comment]
I've had another look and this and it's now clear to me that the cause of the "problem" that @ptrm04 and I are referring to is a documentation problem rather than a bug in the code.

I think it works as designed but the user is not "logged out" when isEqualTo() returns false as the documentation says. What really happens is that the authentication token is invalidated. A new token is created the next time AuthorizationCheckerInterface::isGranted() is called.

I can see this working correctly in my application in the dev environment. The debug toolbar shows me logged in and authenticated. If I change something like the password directly in the database and refresh, I'm still logged in but the toolbar no longer shows me as authenticated.  Then if I click on a page which uses AuthorizationCheckerInterface::isGranted() either directly or indirectly by using Symfony ROLE_ access control, I am re-authenticated. If my roles have changed such that I no longer have access to the page I'm trying to access, I'll get an access denied error.

**Comment by fabpot** [comment]
@tetranz Thank you so much for digging into the details here. Does that mean we can close this one? Can you open an issue on the documentation repository (symfony/symfony-docs) with a reference to this ticket as well to fix the docs?

**Comment by tetranz** [comment]
Yes I think we can close this. I'll create an issue for the docs.

Thanks

**Comment by fabpot** [comment]
Thank you @tetranz

**Comment by ptrm04** [comment]
@tetranz thanks for looking into this - as this is a core security component - i'd strongly suggest against rushing with closing this off and try to fully understand all scenarios, as the fix for the docs you suggested will make them shift towards a subset - to answer one of your previous posts - I can confirm that it does behave as currently described in the docs *only* when you change the value returned from isEnabled() (from true to false) - the user will get *logged out immediately*, so the fix you'd be suggesting for the documentation only applies to a subset of scenarios.

**Comment by ptrm04** [comment]
It appears that back in 2013 there were instances on SO (http://stackoverflow.com/questions/18148647/symfony-authentication-issue-after-username-change) of people saying that when they edited their user account i.e. username they would get logged out so it seems like at that time this would be Symfony 2.2/2.3 (http://symfony.com/doc/current/_images/release-process.jpg) and the behaviour was just as described in the docs. In that SO question the solution was to re-authenticate programmatically immediately after the username update so that the log out does not happen.

Looks like something in this aspect of the core security has changed between Symfony 2.2/2.3 and 2.7/or latest.

Also, let's think of the purpose of this behavior as currently described in the docs - very useful if you have multiple sessions active let's say machine A and machine B. If your session cookie gets compromised on machine A, the attacker will have control over your account. You notice that there is unusual activity and change the password on machine B. Now if this behaved as described currently in the docs, the attacker on machine A would be instantly logged off as the password would have changed. This does sounds great.

Otherwise, it still does not invalidate your session on the compromised session id on machine A. if it just sets you as "Authenticated: No" and changes to "Yes" once you hit a page that requires a role - highly unlikely your roles would have changed or you would lose your standard ROLE_USER (or whatever you call it) if you just reset your password.

Also, this does not require EquatableInterface as indicated in other comments, this applies to all checks in https://github.com/symfony/symfony/blob/3.0/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L244-L2287

What is really interesting, changing the value stored for "enabled" to false behind the scenes (checked in https://github.com/symfony/symfony/blob/3.0/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L279-L281) field will get you logged out, *please try it out*.

However, checks for getPassword / getUsername will not.

**Comment by xenmayer** [comment]
Today I encountered a similar problem with http_basic. When I change login or password in db user does not logout. I found seasy solution for my controller:

`$this->get('security.token_storage')->setToken(null);`

Symfony 2.8

**Comment by ptrm04** [comment]
@xenmayer this will only log you out for the *current* session, other sessions you might have on other computers will remain active.

**Comment by iceuponfire** [comment]
First of all sorry about my english. Well i think i encounter the same issue, i followed the documentation security/entity_provider.html and when i change the password in the database user aren't disconnected altought hasUserChanged return true. In my opinon it's a serious problem considering you would change the password if an account is compromise and then disconnect all the session related.

Is there any solution or best practice to avoid that case?

**Comment by ptrm04** [comment]
Indeed it is a serious problem @iceuponfire but it would probably take someone in the calibre of @fabpot to resolve who knows symfony inside out.
