### ISSUE TITLE
[Validator] File maxSize does not work properly?

### ISSUE THREAD

**Issue by ardi-n** [symfony/symfony#13891]
I think it is related to recent change in logic that allows to specify binary format in maxSize.

I'm using Symfony 2.6.4.

I've got an image assertion which worked previously. 
    
    mimeTypes="image/gif",
    maxSize="30M"

Now it produces an error:

> "The file is too large (23707.88 kB). Allowed maximum size is 0.03 kB."

**Comment by xabbuh** [comment]
Does it work with *30MB* instead of only *30M*?

**Comment by ardi-n** [comment]
I've got a ConstraintDefinitionException:
> "30MB" is not a valid maximum size

**Comment by xabbuh** [comment]
How do you configure you constraints? Do you use the full-stack framework or just the Validator component? Could you provide some steps to reproduce your issue?

**Comment by jakzal** [comment]
Also, what's `upload_max_filesize` set to in your `php.ini`?

**Comment by ardi-n** [comment]
Hi,

I use full-stack framework. Constraints are set on a model class with annotations.

It's a simple scenario where a file is uploaded through an html form.

php.ini settings are correct, size for upload and post big enough.

When maxSize is set to `30000000` validation works correctly.

**Comment by xabbuh** [comment]
@ardi-n I was not able not reproduce your issue. Would you mind forking the Symfony Standard Edition and make the changes needed to reproduce it?

**Comment by ardi-n** [comment]
I wasn't too with a simple deployment. Have to work on it more.

**Comment by webmozart** [comment]
Closed due to lack of feedback. Please reopen if you can reproduce this issue on a fork of the Symfony Standard Edition.

**Comment by Falc** [comment]
Try this to reproduce it: https://github.com/Falc/symfony-standard/tree/error-maxsize

```
git clone -b error-maxsize --single-branch git@github.com:Falc/symfony-standard.git
cd symfony-standard
composer install
app/console server:run
```

Open 127.0.0.1:8000 in your browser and you will see what happens when setting the maxSize option in a File constraint in these ways:

1. Setting as option in the constructor.
2. $constraint->maxSize = '1000000'.
3. $constraint->maxSize = '1M'.

Approaches 1 and 2 work with `"symfony/validator": ">= 2.5.0"`
Approach 3 works with `"symfony/validator": "2.5.*"` but fails with `"symfony/validator": "2.6.*"`

Change the `symfony/validator` version to `2.5.*` and reload. No errors.

It seems that in `v2.5` the conversion to bytes is done in `validate()` ([source](https://github.com/symfony/symfony/blob/v2.5.11/src/Symfony/Component/Validator/Constraints/FileValidator.php#L142)).

In `v2.6` it is done in the constrain constructor ([source](https://github.com/symfony/symfony/blob/v2.6.6/src/Symfony/Component/Validator/Constraints/File.php#L72)) but not in `validate()` ([source](https://github.com/symfony/symfony/blob/v2.6.0/src/Symfony/Component/Validator/Constraints/FileValidator.php#L154)). That means that setting the property manually to a value other than bytes will cause the issue.

**Comment by rayrigam** [comment]
After upgrading from Symfony 2.5 to Symfony 2.7, I have the same issue as mentioned by @Falc . Using `$constraint->maxSize = '1M'` mistakenly results in a max size of 1 byte.
The following error is thrown:
>> The file is too large (xxxxx bytes). Allowed maximum size is 1 byte.

In order for it to work on Symfony 2.7 one must define the value in bytes:
`$constraint->maxSize = '1000000'`

**Comment by xabbuh** [comment]
@ardi-n @Falc @rayrigam Can you please check if the changes in #15115 solve your issue?

**Comment by xepozz** [comment]
And now it fails on https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Component/Validator/Constraints/FileValidator.php#L56, and I see just `The file is too large. Allowed maximum size is {{ limit }} {{ suffix }}.`.
Would be nice to suggest user to check `.ini` config.

**Comment by xepozz** [comment]
@fabpot wdyt?

**Comment by xabbuh** [comment]
Please open a new issue if you think that you discovered a bug.

**Comment by xepozz** [comment]
Why?

**Comment by xabbuh** [comment]
Comments on a closed issue are likely to get lost. Alternatively you can also open a PR with the improvement that you have in mind.
