### ISSUE TITLE
100% CPU load and mem usage with render and unexisting service access

### ISSUE THREAD

**Issue by valeriangalliat** [symfony/symfony#13916]
I ran into this problem while I had a typo in a service class name; when trying to load a page that renders another action accessing this service, the CPU load and mem usage of my computer started to increase until saturation.

I [could reproduce this](https://github.com/valeriangalliat/symfony-bug/commit/70d6a92fa13e1b5e1b9eb42823eb8e1d029f7a92) on a fresh Symfony 2.7 installation with very few lines of code.

I'm using the built-in development server `app/console server:run` (this bug doesn't happen with Apache); here's the verbose output:

```
Server running on http://127.0.0.1:8000

Quit the server with CONTROL-C.
  RUN  '/usr/bin/php5' '-S' '127.0.0.1:8000' '/home/hap/public_html/symfo/test2/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php'
  RES  137 Command did not run successfully
Built-in server terminated unexpectedly
```

Here's a capture of `htop` while loading `/app/example`:

![100% CPU load and high mem usage](http://image.noelshack.com/fichiers/2015/11/1426236873-2015-03-13-095429-949x103-scrot.png)

I'm running Debian Wheezy, x86_64, and PHP is 5.4.36.

Is there anything I can do to help targeting more precisely this bug?

**Comment by cordoval** [comment]
@valeriangalliat 

```bash
[Fri Apr  3 01:27:35 2015] PHP Fatal error:  Class 'AppBundle\Troll' not found in /Users/cordoval/Sites/symfony-standard/app/cache/dev/appDevDebugProjectContainer.php on line 2934
[Fri Apr  3 01:27:35 2015] ::1:56798 [500]: /app_dev.php/app/example - Class 'AppBundle\Troll' not found in /Users/cordoval/Sites/symfony-standard/app/cache/dev/appDevDebugProjectContainer.php on line 2934
[Fri Apr  3 01:27:35 2015] ::1:56799 [200]: /bundles/framework/css/structure.css
[Fri Apr  3 01:27:35 2015] ::1:56800 [200]: /bundles/framework/css/body.css
[Fri Apr  3 01:27:35 2015] ::1:56801 [200]: /bundles/framework/css/exception.css
[Fri Apr  3 01:27:35 2015] PHP Deprecated:  The Symfony\Component\Security\Core\SecurityContextInterface interface is deprecated since version 2.6 and will be removed in 3.0. in /Users/cordoval/Sites/symfony-standard/app/cache/dev/classes.php on line 2565
[Fri Apr  3 01:27:35 2015] PHP Deprecated:  The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead. in /Users/cordoval/Sites/symfony-standard/app/cache/dev/classes.php on line 2577
[Fri Apr  3 01:27:39 2015] PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 32 bytes) in /Users/cordoval/Sites/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/DataCollector.php on line 40
[Fri Apr  3 01:27:39 2015] ::1:56802 [500]: /app_dev.php/_wdt/13c56b - Allowed memory size of 2147483648 bytes exhausted (tried to allocate 32 bytes) in /Users/cordoval/Sites/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/DataCollector.php on line 40
```

i also get an error on the page showing the first error which is your class Troll does not exist or is missing an use statement. The memory leaks after that error has happened. I believe the ClassNotFoundFatalErrorHandler starts the leak since it builds up a huge array of classes of all the autoloaders. Then after that comes the datacollector which is going to use the memory that finally exhausts it. Did you try to investigate where the leak happens and what can be done about it @valeriangalliat ? :older_man:

**Comment by valeriangalliat** [comment]
Thanks for your answer @cordoval. I didn't took the time to investigate further with this bug yet. However I just tried again with the exact same project I captured the first screenshot with (vendors were not updated, code was not changed) but I cannot reproduce anymore.

Since the last time I just upgraded PHP to 5.4.39. I tried to compile 5.4.36 again but I still can't reproduce. Really odd.

**Comment by jakzal** [comment]
Feel free to reopen if you manage to reproduce this problem again.

**Comment by hoang-danny05** [comment]
So I think I managed to reproduce this error with Symfony 7.4. Investigating this issue for me is hard because the system becomes inoperable after 10s, so I only can catch a glimpse of memory being absolutely consumed by the system before I have to restart. (PHP v8.3)

What I have is a service in `App\Service` that uses the HttpClientInterface service from Symfony. Having a function that doesn't interact with the service works perfectly. However, as soon as you access the `$client`, all hell breaks loose.
```php
<?php
use Symfony\Component\HttpClient\HttpClientInterface;

class ApiProxy
{
    // use Symfony's services
    public function __construct(
        private HttpClientInterface $client,
    )
    {
    }

    
    public function verifyToken(string $token)  {
        $url    = $this->api_base(API::Extraction) . '/verify-token'; // this works!
        return $this->client;
  }
```

**Additional Context**
I happen to have this containerized in a php-apache:8.3 container and I see CPU spiking up to 100%. Something very odd that I notice is that the memory used of the entire system is consumed after I trigger this error. The odd part is that shutting the containers down with `CTRL+C` (i use docker compose) does NOT clear up the error. I think this is causing some sort of memory leak that escapes docker?

**Edit**

Okay, I just realized that I was using a non-interface object as an interface, and feel super silly for it. However, I still think that this issue is kinda relevant. An error should be thrown if a service is not recognized, instead of flooding the user's computer.
