### ISSUE TITLE
Require PHPUnit as a dev dependency

### ISSUE THREAD

**Issue by mnapoli** [symfony/symfony#13934]
Yes I know this has been discussed already :) but I'd like to start the discussion again with a nice summary of the arguments that were expressed:

> @fabpot in #5748: For me, PHPunit is a tool and I'm not comfortable (yet) about adding this tool dep into the composer file.

PHPUnit is not just a tool, it's also a framework: we use PHPUnit classes to write the tests. So it's not just about downloading and running a phar, it's also about installing the code so that we can use it like any framework/library.

As a more concrete example, PHPUnit 4.5 has added [important new features](https://thephp.cc/news/2015/02/phpunit-4-5-and-prophecy) to the test framework and only by requiring it in Composer can you make sure people install the latest version.

> @stof in #12136: Adding phpunit as a dev requirement means that each Travis build has to install 15 more composer packages (phpunit is not a small dependency)

@pborreli mentions this in #5748: "indeed, build takes 1 second more approx, which is not much"

Another reason I've read:

> When working with VMs the global include path is not accessible on the host machine

For me autocompletion & co is completely broken because the IDE can't find the PHPUnit *framework* classes. It's much harder to work with tests. And by adding the global tools (i.e. global composer install) to PhpStorm I now have a lot of duplicated classes, which trips the IDE even more.

So hopefully we can open this discussion again and add PHPUnit to `require-dev` in `composer.json` :)?

**Comment by merk** [comment]
Something that might have changed slightly since the last discussion is the possibility of using travis's cache: http://docs.travis-ci.com/user/caching/

**Comment by sstok** [comment]
@merk That will not work as Symfony needs sudo for installing parallel
https://github.com/symfony/symfony/blob/2.7/.travis.yml#L28

And caching currently only works when sudo is disabled.

**Comment by unkind** [comment]
> So it's not just about downloading and running a phar <...>
> For me autocompletion & co is completely broken because the IDE can't find the PHPUnit framework classes

PhpStorm indexes code from phars, maybe your `phpunit.phar` is outside of a project?

**Comment by mnapoli** [comment]
@unkind then that shows that PHPUnit's code is required for tests to work, which, like any other library, should be installed as a dev dependency.

**Comment by zomberg** [comment]
+1 for add PHPUnit to require-dev in composer.json.

I have global installation of PHPUnit in /usr/local/bin, but for IDE autocompletion I must store phpunit.phar in project. It is really annoing.

**Comment by stof** [comment]
> That will not work as Symfony needs sudo for installing parallel

@sstok Travis allows to install a bunch of APT packages on the new infrastructure through a dedicated addon, and parallel is in the whitelist (because I requested it).
The actual issue is the other place where we use sudo: https://github.com/symfony/symfony/blob/17ad6fd90c69a0ff35589b5ad3fc9c4e660f7631/.travis.yml#L36

**Comment by dunglas** [comment]
To speed up the Travis build while having phpunit in `require-dev` we can still add something like that in `.travis.yml`:

```yaml
before_install:
    - sed '/phpunit\/phpunit/d' composer.json > composer.json
```

**Comment by webmozart** [comment]
I'm actually +1 for this proposal. Currently, whenever the tests use features from a new PHPUnit version, the tests on developer machines fail for initially unknown reasons. By requiring PHPUnit in composer.json we can document the actual minimum version of the framework, while fixing the above mentioned autocompletion issues at the same time.

**Comment by nicolas-grekas** [comment]
It would be great to be able to tell phpunit which version is required to run the tests in the phpunit.xml file!

**Comment by mnapoli** [comment]
@nicolas-grekas while that is a solution, I don't believe it is the right one. To me a tool is a tool and shouldn't be installed with Composer when we just run it as a tool (e.g. phpmd, phpcs, …).

But PHPUnit is also a testing framework, we need the classes to write the tests. The test runner is the tool, but you need the framework to write PHPUnit tests, with all the problems that apply to any other libraries (autoloading, versioning, discoverability by IDE, etc.).

**Comment by derrabus** [comment]
PHPUnit itself depends on Symfony's YAML component. Would this be a problem when requiring PHPUnit as a dev dependency?

**Comment by Tobion** [comment]
@derrabus no since phpunit would only be a DEV dependency, so there is no recursion

**Comment by derrabus** [comment]
I'm not worried about recursion. It just freaks me out that the code under test would also be part of the test runner, although not an essential one.

Don't get me wrong. Apart from that, I'm absolutely :+1: for adding phpunit as a dev dependency.

**Comment by MacDada** [comment]
+1

Apart from what's been said (with which I agree: IDE completion + versioning), running tests is required before contributing. That means that every **dev**eloper should do that. That means that the tool is required in **dev** environment. That means it fits perfectly for `require-`**`dev`** in `composer.json`.

**Comment by jameshalsall** [comment]
@fabpot can we look at adding this to the `composer.json`? Currently contributing back to symfony means modifying the `composer.json` manually in order to run the test suite (I don't like having a global phpunit on my machine, and if I did it would be the latest version which may not necessarily be the version used on the project).

**Comment by nicolas-grekas** [comment]
This would be a mistake. In fact, I tried on travis while working on PHP7 and Symfony 3.0 and it's just plain broken. Why? I won't argue about this being broken in theory (because it is). But because here, theory meets practice: phpunit uses symfony/yaml. Which means we can't test lastests Symfony Yaml with phpunit.
Well, we have now a proper workaround in the test suite on Travis: [we build a custom phpunit without any dep on any symfony component](https://github.com/symfony/symfony/blob/2.8/.travis.yml#L40) (and we do not use the features that would require them).

If someone manages to open a **green** PR with phpunit as a composer dep, they we might reconsider.
Until it happens, I'm closing the issue.

**Comment by nicolas-grekas** [comment]
By **green**, I mean green *and able to test latests symfony/yaml* of course.

**Comment by derrabus** [comment]
But if the PHPUnit code that uses the YAML component is not triggered by Symfony's test suite, isn't that custom PHPUnit build, that the travis script assembles, exactly what you get, if you add PHPUnit to the dev dependencies? Instead of pulling Symfony YAML from github, composer should recognize the dependency as fullfilled by Symfony's codebase.

I don't want to argue about this being broken. I just want to understand the problem.

**Comment by nicolas-grekas** [comment]
This can work is practice for the main symfony/symfony tests, but we also test component by component. This is where things break again:
if you test component by component with the phpunit build on top of symfony/symfony, you'll break.
And no please, nobody suggested adding phpunit as a dev dev to each and every component.

**Comment by derrabus** [comment]
Well, adding PHPUnit to each component is what you consequently would have to do, if you wanted to pull PHPUnit from composer. Otherwise you would be testing with the wrong dependencies.

I begin to understand, why you don't want this. :sunglasses:
