### ISSUE TITLE
[Session][3.0] PdoSessionHandler: precalculate expiry timestamp

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#13955]
Based on #13858 we should make the following BC break in 3.0 to speed up garbage collection in PdoSessionHandler.
1. rename sess_lifetime column to sess_exipiry
2. save time + lifetime in sess_exipiry
3. probably add an index on sess_exipiry
4. change gc() to delete by sess_exipiry

**Comment by robertfausk** [comment]
+1 for that. PdoSessionHandler as of symfony 2.7 is not usable on large production websites with default php session garbage collector.

**Comment by rodinia814** [comment]
This was delayed until 4.0?  I'm having the same problem as the poster of #15020.  It's causing significant production issues.

**Comment by digilist** [comment]
Why not introduce a new Session Handler that can be used as an alternative to PdoSessionHandler? Anyone who is aware of this problem can switch the handler and everybody else stays with the current solution. This would not introduce any BC.

**Comment by bcremer** [comment]
Our clients have the same issue since we introduced `PdoSessionHandler` recently so I implemented this changes in a plugin: https://github.com/bcremer/SwagSessionHandler/blob/master/PdoSessionHandler.php

I would like to open a Pull Request to Symfony/Symfony with the updated `PdoSessionHandler`, any objections how to proceed?  In https://github.com/symfony/symfony/pull/14625 the same failed because of deprecation issues.

**Comment by nicolas-grekas** [comment]
Just wondering: did you consider a chunked-delete strategy, as described eg in https://sqlperformance.com/2013/03/io-subsystem/chunk-deletes?
This will still require a full scan, but maybe this is not an issue on large installs if this is done lazily in chunks? Especially compared to adding an index (which is the goal here if I read correctly) - which can create a big space overhead (since we're talking about large installs?)

**Comment by bcremer** [comment]
To be honest I don't know if the added complexity for chunked deletes is worth it.
We could add a configurable LIMIT clause here <https://github.com/symfony/symfony/pull/21423/files#diff-5b96aee9c7c07a0e18d1fd32f7a3028eR429> so one could descrease the limit and increase the `gc_probability` to archive something similarly.
