### ISSUE TITLE
[SecurityBundle] UserPasswordEncoderCommand concerns

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony#13988]
As I just tried it now, I've some concerns about the newly introduced command to encode user password (#12818).

# Arguments order

The command currently looks like : 

```
security:encode-password [password] [user-class] [salt]
```

All arguments are optional, for the interactive command purpose (The command will ask the user for missing arguments in a very user-friendly way).
But, as they are arguments, we should provide each of them in the proper order. That means we cannot provide a salt without defining the optional `user-class`.

Why not using options instead of arguments for both `user-class` & `salt` ?

# Empty salt

Currently, the only way to generate a password with an empty salt (for `in_memory` users and bcrypt for example) is by executing the following trick:
```
security:encode-password p@ssw0rd --no-interaction.
```

Indeed, with interaction, if no salt or an empty salt is provided (`security:encode-password p@ssw0rd 'Symfony\Component\Security\Core\User\User' ''`), we'll be asked for a salt. Then again, if we provide an empty salt (press enter), a salt is automatically generated.

**Solutions (one of those):**
- a new `--empty-salt` option
- ask confirmation about providing or generating a salt
- do not ask for salt if an empty salt is provided (`security:encode-password p@ssw0rd 'Symfony\Component\Security\Core\User\User' ''`)

# Symfony Core User should be the default user-class

As @jeremyFreeAgent said:
> Since we configure Symfony\Component\Security\Core\User\User in the setAutocompleterValues and set the $value to Symfony\Component\Security\Core\User\User if null, I guess we can configure the default value of the user-class.

Indeed, why not providing the `Symfony\Component\Security\Core\User\User` as the default value of the `user-class` option/argument ?
Asking it explicitly to the user is only useful for new symfony's users. Once understood, I think most users will provide it directly, or expect the default `Symfony\Component\Security\Core\User\User` value.

# Non interactive salt generation

I see 2 "issues" here:
- We cannot ask for a generated salt with non-interactive usage
- Anyway, the salt isn't in the Table summarizing the generation.

**Solution**
- add a `--generate-salt` option in order to generate the salt instead of providing it
- add the generated salt to the Table output

=========

What do you think ?

ping @saro0h

**Comment by javiereguiluz** [comment]
@ogizanagi :+1: I think your ideas make a lot of sense and they could easily improve this new command.

**Comment by inanimatt** [comment]
Beat me to it, and in a much more complete way <3

**Comment by saro0h** [comment]
OK I'm on it.

**Comment by saro0h** [comment]
Tell me if this what you meant:

Arguments order
=============

## Option --user-class
![capture d ecran 2015-03-22 a 15 31 11](https://cloud.githubusercontent.com/assets/667519/6769775/7f96c308-d0a8-11e4-8ab5-5f90bb0143a6.png)

## Option --salt
![capture d ecran 2015-03-22 a 15 32 59](https://cloud.githubusercontent.com/assets/667519/6769783/c08d7604-d0a8-11e4-95f6-234acb3ffb76.png)

Empty salt
========
![capture d ecran 2015-03-22 a 15 21 25](https://cloud.githubusercontent.com/assets/667519/6769725/24288912-d0a7-11e4-9abc-4a8fa387c7d4.png)

Symfony Core User should be the default user-class
=======================================
Done.

Non interactive salt generation
=======================
![capture d ecran 2015-03-22 a 15 20 32](https://cloud.githubusercontent.com/assets/667519/6769721/0e710a36-d0a7-11e4-9b34-08b3fde65080.png)

Do I forget something?

**Comment by inanimatt** [comment]
This looks good to me - @ogizanagi ? 
One thing: I do wonder if you should need to specify `--generate-salt`… I haven't thought this through very deeply, but it seems to me that this should be the default behaviour unless you override it with `--salt` or `--empty-salt`. So then the least-effort command would be `app/console security:encode-password myPassword`, which would generate a salt and pick the default user class, right?

**Comment by saro0h** [comment]
About the ``--generate-salt`` and ``--empty-salt``, it coulld be kinda redundant yes. I added a check to make sure that both can't be provided at the same time.

Should I remove this ``--generate-salt`` option as it is the default behaviour? (see below)
![capture d ecran 2015-03-22 a 16 01 00](https://cloud.githubusercontent.com/assets/667519/6769875/ad0f1e12-d0ac-11e4-83fe-5df37af5cf34.png)

**Comment by ogizanagi** [comment]
#### Arguments order
:+1: 

#### Empty salt
I suggested the `--empty-salt` option, but in fact I don't know what should be the best. That's why I opened this issue.
BTW, the `--empty-salt` option meant to me "Do not ask me for a salt nor generate one, I don't want any."
Maybe the command should ask for the salt generation this way:

- No salt provided:
```bash
security:encode-password password

Symfony Password Encoder Utility
[...]
No salt was provided. Would you like to provide or generate a salt ? [y/N] y
Provide a salt (press <enter> to generate one):
The salt has been generated: salt
Make sure that your salt storage field fits this salt length: 128 chars
[...]
```

- Empty salt provided:
```bash
security:encode-password password --salt=""
#do not ask for salt, which is equivalent to:
security:encode-password password --empty-salt
```

- Non-interactive usage:
```bash
security:encode-password password --no-interaction
#salt is ""
```

#### Non interactive salt generation

:+1: Don't forget the salt in the Table output. I think it's better to have it in there for non interactive usage.

**Comment by saro0h** [comment]
I think that it would be more intuitive for the user to have actually the very simple version (with no question asked) when typing ``security:encode-password password``.

----------------------
I agree for the 
```sh
security:encode-password password --salt=""
#do not ask for salt, which is equivalent to:
security:encode-password password --empty-salt
```
Let me change that right away.
----------------------
For the non interactive usage => no need to add the ``--no-interactive`` as I really think we should provide a really short version, which is ``security:encode-password password``.

----------------------
About the display of the salt, I can display it if there was generation + no interaction with the user.

**Comment by saro0h** [comment]
Oh actually, about the display of the salt, I already display it in the recapitulative text, no need to do it again in the table.

**Comment by ogizanagi** [comment]
@saro0h : 
> Oh actually, about the display of the salt, I already display it in the recapitulative text, no need to do it again in the table.

I know. It was mainly essential for the `--generate-salt` option. 
But in fact I think it will be clearer for the user to have a full summary of what the command generated in the table.

**Comment by inanimatt** [comment]
One thing that's bothering me (at the risk of invoking @ircmaxell) … with the bcrypt encoder (which uses `password_hash($pw, PASSWORD_BCRYPT)`, my understanding is that it's really best to not provide a salt at all unless you have a good reason to, because a good one will be generated if none is provided. 

But the other built-in encoders (`MessageDigestPasswordEncoder`, `Pbkdf2PasswordEncoder`) both require a salt to be passed in and won't (as far as I can tell) generate one if none is given, and of course people might be using a custom encoder.

So perhaps the correct default behaviour is (unfortunately a bit clunky): if the encoder is `BCryptPasswordEncoder` _and_ a salt isn't provided _and_ `--empty-salt` isn't provided (which would be an awful idea if it even works :smile:) _then_ let the encoder create the salt automatically, otherwise generate one.

Generating salts is tricky, and doing the right thing is trickier still, especially on a Sunday afternoon :grinning:   -- for example, bcrypt's salt length is 22 chars (128 bits base64 encoded), so if you feed it hex then you're not getting nearly as much entropy as you could be.

**Comment by ogizanagi** [comment]
@inanimatt : if an empty salt or the `--empty-salt` option is provided, the BCryptPasswordEncoder will generate a salt itself anyway (https://github.com/symfony/symfony/blob/7c026bb33e8ca96b285402f7fe7ae27a04a74ea9/src/Symfony/Component/Security/Core/Encoder/BCryptPasswordEncoder.php#L77)

We should only care not generating a salt at all for bcrypt encoders.

**Comment by inanimatt** [comment]
@ogizanagi oh yes, that's the encoder's behaviour 100% agreed, but I think _this command_ will try to provide a generated salt, which would override that behaviour; and worse, it'd be a lower quality salt than the one bcrypt would generate itself. That's what I'm trying to address here - we shouldn't be generating weaker hashes by default :)

**Comment by saro0h** [comment]
Too complicated… If the user uses a custom encoder that needs a salt? The hardcoded if won't be efficient anymore.

Let's just keep it really simple:
Case 1: The user  types: ``security:encode-password password``
    The user gets his/her password encoded with a generated salt and the ``Symfony\Component\Security\Core\User\User`` encoder configured encoder.

Case 2:  The user types: ``security:encode-password password --salt="mysalt"`
     The user gets his/her password encoded with the salt he/she chose with the ``Symfony\Component\Security\Core\User\User`` configured encoder.

Case 3:  The user types: ``security:encode-password password --salt="mysalt"`
     The user gets his/her password encoded with the salt he/she chose with the class he/she chose configured encoder.

No choice here => We generate a salt no matter what => No problem anymore.

**Comment by saro0h** [comment]
So let's not add the ``empty-salt`` and ``generate-salt`` options.

**Comment by ogizanagi** [comment]
@saro0h : I agree to keep things simple. 
Your suggestion fits what I thought while opening this issue. Except I had some concerns about entirely getting rid of the questions for new symfony users (I thought your interactive command was a good thing for them and intended to, but heavy for more experienced users).

Maybe just add an advice in the command documentation and particular encoders for which it is not recommended to generate a salt.

**Comment by saro0h** [comment]
@ogizanagi I don't want to get rid of the interactive part too;

I suggest to a ``--interactive`` option to ask all of what he/she did not provided.

I'll add the recommendation in there.

**Comment by ogizanagi** [comment]
@saro0h : Well, that was the point of using the global `no-interaction` option.
The `interactive` way should be the default one, don't you think ? Adding an option for this seems a bit strange to me.  :confused:

**Comment by saro0h** [comment]
All right, all right :)

**Comment by inanimatt** [comment]
@saro0h I definitely want it to be that simple too! :smile: 

But forcing our own salt on the bcrypt encoder seems like a bad idea. I'm nearly certain that `hash('sha512', $container->get('security.secure_random')->nextBytes(30));` is a lot weaker than the salt that `password_hash` would generate itself (22 chars of base64 has a lot more entropy than 22 chars of base16, right?) and pretty much all the advice I can find online says "let `password_hash` generate the salt for you". 

Like I said, it's tricky! The best kind of salt that each encoder (built in or custom) wants is probably different, and there's no way for us to know what the encoder needs at runtime. It's something that'd be best fixed in the encoder interface, I suspect. e.g. force all encoders to handle generating a salt if none is provided, since the encoder itself would know what's best for it and what kind of input it allows/needs. But that's for another PR! 

In the meantime I really think the least-worst thing to do here is check if the encoder is `BCryptPasswordEncoder` and if it is, let it generate the salt. For the other encoders which won't generate their own… then I guess we have to generate one, maybe with base64 instead of base16, if they'll take it.

**Comment by ogizanagi** [comment]
@inanimatt : Then, the best would certainly be not generating a salt as the default behavior when no salt is provided...and reintroduce the `generated-salt` option... Way much simple.

**Comment by inanimatt** [comment]
@ogizanagi … but then all the other encoders would fail, wouldn't they? :)

**Comment by saro0h** [comment]
Let's provide the salt all the time.
This command was actually built to easily use bcrypt encoded password for ``memory`` provider, the one we should use only for dev purpose. So the weakness of the salt does not really matter at this point I guess.

**Comment by ogizanagi** [comment]
@inanimatt : Why ? Is an empty salt a matter for some encoders ? The interactive way could ask him if it is really wanted anyway.
When using non-interactive, I think the user knows what is doing.

**Comment by ogizanagi** [comment]
@saro0h : Let's do it as you suggested. Thank you for having considered all of our *tergiversations* :smile: 

Eventually, we could discuss about this later in another dedicated issue.

**Comment by saro0h** [comment]
Sure :smiley:

**Comment by inanimatt** [comment]
@ogizanagi Yep, of the built-in encoders, both `MessageDigestPasswordEncoder` and `Pbkdf2PasswordEncoder` require a salt to be present, and neither check if it's valid/present, or generate one if none is given. `BCryptPasswordEncoder` is the odd-one-out.

I'm sorry to be so pushy/insistent/annoying about this. I'll stop after this comment. The [PHP manual](http://php.net/password_hash):

> "**Caution**: It is strongly recommended that you do not generate your own salt for this function. It will create a secure salt automatically for you if you do not specify one."

If we _have_ to generate a salt no matter what (which is definitely the simplest and easiest way forward - and, I think… okay. It's an okay thing to do), please replace the current `sha512` hash of bytes from the `security.secure_random` service) with the method used by @ircmaxell in their [password_compat library](https://github.com/ircmaxell/password_compat/blob/master/lib/password.php#L102):  e.g. `base64_encode($container->get('security.secure_random')->nextBytes(16))` who knows this kind of stuff a lot better than I do. Why? Well it's not a small difference:

hex sha512 of random bytes truncated to 22 chars → 22^16 (3011361496339065143296)
16 random bytes base64 encoded (22 chars) → 256^16 (340282366920938463463374607431768211456)

**Comment by ogizanagi** [comment]
@inanimatt : Those encoders will not fail at all with an empty salt. The salt will be empty, that's all. And it might be desired for in_memory users where salt is always empty (unless for bcrypt where the salt is in the hash).
That's why I finally maintain my first opinion: 
- providing an empty salt should be allowed, so the `salt` option shouldn't be required.
- we must not generated an salt unless the user desired it
- the interactive command should ask the user if the fact he didn't provided an empty salt is desired (askConfirmation question), or generate/ask him one.
- the non-interactive command should allow to generate a basic salt as @saro0h implemented with the `generate-salt` option. The command documentation and the salt generation will warn the user that the generated salt isn't the most suitable one for security reasons.

What do you think ?

**Comment by inanimatt** [comment]
I wanted to stop after that last comment, honest I did.

@ogizanagi what do you mean will not fail? They won't throw an exception, but you also won't get a secure password hash :smile: Anyway:

1. You don't need a convenience CLI command to encode a plaintext password when you could just type it straight into `security.yml`, right? Maybe there's a better example where it's necessary. Right now I don't see it. So  `--empty-salt` is kind of pointless.

2. Users shouldn't _ever_ have to provide a salt. It's a pointless burden, and computers can do it _much_ better than people can. There might be special cases, but then… don't use the convenience command, right? :smile:  So `--generate-salt` shouldn't be an option, it should just happen. 

3. (&4). The salt generated by the command right now is like… 112,999,507,808,883,889 times weaker than base64ing secure_random when given to bcrypt. That's like … the difference between a single cell and a solar system or something :D. And it's a one-line fix so… let's do that? As far as I can tell it won't break or change anything, it just makes better salts.

So… the easiest thing to do is kill empty-salt and always generate a salt, and the salt should be decent. I think we can all agree on that. All that's left is whether or not we treat the bcrypt encoder specially (i.e. detect it and delegate the generation of a salt to its built-in method).

I think yes, because it's a special case. It's the only encoder that generates its own salts, and it generates better ones than we can, so let's trust it and the experts that tell us to use it. You can disagree with me on this and I won't cry, though, as long as the generated salt is better.

**Comment by ogizanagi** [comment]
@inanimatt : I'm not talking about plaintext encoder... in_memory user's could also be used with other encoders. So, no, the `empty-salt` isn't pointless if we keep the salt generation as the default behavior.
To summarize:
- I agree with you about the generated salt not being optimal, and yes, I think we should provide a more decent salt. In fact, I didn't mentioned your suggestion to fix that in my previous comment and talked about warnings because I think it belongs to another issue.
- Do not make exception in the code for specific encoders.

**Comment by inanimatt** [comment]
Thanks for putting up with me. I'm almost done.

I'll make another issue to improve the generated salt. Seems like a lot of fuss, but… okay :)

I agree that you can use both bcrypt and plaintext on the in_memory provider. The other encoders (sha512 and pbkdf2) make broken, insecure hashes without salts. I'm not sure we should be encouraging that.

I'm also not sure why we shouldn't treat the bcrypt encoder differently. You could make an OO argument that the command shouldn't know the implementation of the specific encoder class, but nothing's perfect and I think following best practice security advice is more important than being pure SOLID, especially when this is just a utility command, not a deep part of the framework library itself.

**Comment by ogizanagi** [comment]
> I'm also not sure why we shouldn't treat the bcrypt encoder differently. You could make an OO argument that the command shouldn't know the implementation of the specific encoder class, but nothing's perfect and I think following best practice security advice is more important than being pure SOLID, especially when this is just a utility command, not a deep part of the framework library itself.

You're right about this. But it will not solve the issue for custom encoders (some of them might have built-in salts too).
Making an exception for the `BCryptPasswordEncoder` could make sense, as it's one of the encoders shipped with Symfony, but it really doesn't belong to me to state if this is something acceptable for a "Symfony's core element", even just a utility command.

**Comment by ircmaxell** [comment]
Question: why do you accept a salt on the command line in the first place? That seems like a problem to me. Instead, you should **always** generate it.

In fact, I'd raise the question of why encoders even accept a salt in the first place. They are a high-level abstraction, and as such should be generating salts automatically, not requiring one as input.

**Comment by inanimatt** [comment]
@ircmaxell Trying to be pragmatic, what I'm proposing is that the command never asks the user for a salt - it'll generate one if it needs to, and delegate to the encoder if it can (bcrypt). I'm not sure we can change the encoder interface without breaking B/C (maybe we can submit a PR for 3.0 - but that's a tangent).

I think there's some confusion in the thread because @saro0h and @ogizanagi [want](https://github.com/symfony/symfony/issues/13988#issuecomment-84645031) (fairly reasonably, I think) the command to support the `in_memory` user provider for development. That provider loads users from the `security.yml` config file into a stub user class that doesn't handle salts IIRC. That should be totally fine for bcrypt since the salt is part of the hash and doesn't need to be stored separately, and it's fine for plaintext (which doesn't need this command at all), but it means if you tried it with any other encoder, it'd fail unless you make weak-ass unsalted hashes.

My opinion is … don't do that :stuck_out_tongue_winking_eye:. It's something better fixed with help-text or a notice, something like: "Note: the `in_memory` provider only supports bcrypt and plaintext hashes".

**Comment by ircmaxell** [comment]
@inanimatt that's fair. I need to blog about this concept anyway, so thanks for giving me some context and framing. And no, it won't be a "look at this, doing it wrong" style post ;-).

**Comment by ogizanagi** [comment]
> why do you accept a salt on the command line in the first place? That seems like a problem to me. Instead, you should always generate it.

Unless you're trying to change a password hash keeping the existing salt for any reason... yeah, the `salt` option is arguable... You're right, I really think we should get rid of it.

> Trying to be pragmatic, what I'm proposing is that the command never asks the user for a salt - it'll generate one if it needs to, and delegate to the encoder if it can (bcrypt). I'm not sure we can change the encoder interface without breaking B/C (maybe we can submit a PR for 3.0 - but that's a tangent).

@inanimatt : Ok, what do you think about : 
- getting rid of the `salt` option
- generating a salt everytime
- allowing an option to let the encoder generate the salt (provides an empty salt to the encoder replacing the `empty-salt` option) ? Of course there is no check if the encoder is able to generate one or not, the user must know what he's doing using this option. The option doc should warn the user.<br/>How should we name this option ?

Then, we could suggest a change about the encoder interface for 3.0.

**Comment by ircmaxell** [comment]
@ogizanagi 

> Unless you're trying to change a password hash while keeping the existing salt for any reason... yeah, the salt option is arguable... You're right, I really think we should get rid of it.

Even the use-case for keeping an existing salt sounds really suspect (as in, the dev is doing something they shouldn't be).

But yeah, it sounds like we're all on the same page here :-)

**Comment by inanimatt** [comment]
@ogizanagi - yep, kill the salt option. But then…

I think the common case is "someone wants a bcrypt hash to put into `security.yml`/database" - so the default for the command should cater to that. What you suggest (putting words in your mouth, apologies if not true) is something like `app/console security:encoder-password --empty-salt` and to quote you, "the user must know what he's doing using this option", which combines to make something unpalatable to me on DX grounds. I think the default behaviour should be safe and useful… otherwise what's the point, right? Here's what I think the bare (un-optioned) behaviour should do:

* Get the list of configured encoders (from `security.yml` if it has to, but there's probably a better way)
* If there's only one (the common case), pick it, otherwise offer an interactive choice from the configured encoders - a CLI option (like `--user-class="…"`) would override this.
* If the encoder is an instance of the BCryptPasswordEncoder, either prompt for a password or take it from the CLI argument then encode the password without generating a salt (i.e. let the BCryptPasswordEncoder generate the salt)
* Otherwise generate a salt and give it to the specified password encoder. For custom encoders which require no salt (or the weird rare case when someone uses the plaintext encoder but doesn't just enter it into `security.yml` themselves), you could pass `--empty-salt` if you needed to override this default behaviour.

In other words, treat the symfony manual's recommendation as the default case and do the best thing, but add CLI options to override this when people have the knowledge and need to do something different.

I know this leaks knowledge of the encoder outside of the class and that's not ideal from an OO design perspective, but I think that's the hand we've been dealt and it's more important to give a good hash than it is to write pure OO. The "proper" way to fix it is to submit a PR later to make encoders handle the generation of their own salts - it's wrong that this needs to be passed in from outside. Some encoders might be binary/null-safe and thus get greater entropy, while others might accept base64, or only hex, or throw an exception if the salt is too long… we don't know, we can't know, and we _shouldn't_ know - only the encoder can know what the parameters of a good salt are, so the interface is wrong and that's outside the purview of this issue.

What do you think? I'm aware that when I say "pragmatic" I mean "I'm wrong, but for the right reasons" :smile: My opinion is that from a DX perspective (which is really the only reason the command exists at all) we should Do The Right Thing™ even if it means more code with some special treatment. That's what I think this suggestion is.

**Comment by ogizanagi** [comment]
@inanimatt : There is currently no way to retrieve configured encoders. :/ It will need the `SecurityExtension` to expose the `$config['encoders']` as a parameter in the container, or the `EncoderFactory` to provide access to the `$encoders` property.

As I said before, I agree with you. I'm only asking now for a straightforward solution as we don't have any opinion on this from core team members and there is more chances to have a working PR being merged quickly (wasn't your PR #14018 merge faster thanks to a dedicated PR ?)  allowing to generate a decent salt with a single new option and removing the `salt` one, than keeping repeating the same things. 

We could then structure our thoughts and expose the real issue you raised to core members instead of providing an almost 40 comments thread as a witness. :smiley: 

We agree on the `salt` option removal. We agree that the `empty-salt` or whatever would be named this option will be useful anyway. Let's do it. Agreed ? ^^

**Comment by inanimatt** [comment]
Yeah I dunno, I kinda give up. All I can think of as a straightforward solution is… if the encoderfactory gives back an instance of bcryptpasswordencoder, then don't generate a salt (because we know it'll make a better one), otherwise generate a salt unless `--empty-salt` is passed. It'll do for now, especially since the generated salt is better now that #14018 got merged. Maybe someone who knows what they're doing better than I do can improve it properly later.

**Comment by ircmaxell** [comment]
I think the problem is that the `PasswordEncoder` API is flawed. That's why you're seeing these issues. Perhaps a new API is needed:

    PasswordEncoderV2 {
        public function encodePassword(string $password): string;
        public function isPasswordValid(string $encoded, string $password): bool;
    }

I realize that this is beyond the scope of this discussion, but it's an important point of feedback.
