### ISSUE TITLE
in 2.6.5 , can we change the AppBundle name ? 

### ISSUE THREAD

**Issue by Sshuichi** [symfony/symfony#14008]
it's not representative and created by default. 
Can we change the name ?

**Comment by javiereguiluz** [comment]
@Sshuichi you can choose any name for your Symfony application bundles. And you can create several bundles if that's what you need.

`AppBundle` is just the default pregenerated bundle available when you install Symfony or when use the Symfony Standard Edition. We think it's a good name because it's generic and very concise. We use it in the examples of the entire Symfony documentation, so we can't really change it.

But again, the important thing to remember is that you don't have to use AppBundle in your Symfony applications. Use any number of bundles and select their names freely.

**Comment by Sshuichi** [comment]
All right,  so it's named that way for documentation purposes :) 
Can you point me the docs where you create a new bundle on 2.6.5 ? 
I think that `php app/console generate:bundle` is only for 2.4

**Comment by WouterJ** [comment]
@Sshuichi the generate:bundle command works on every symfony version (it's part of the SensioGenratorBundle automatically included in the STandard Edition).

You can create a bundle by using that command, or just create a bundle class and register it. This is described in ["Creating Pages in Symfony"](http://symfony.com/doc/current/book/page_creation.html#before-you-begin-create-the-bundle)

**Comment by Sshuichi** [comment]
All right, thanks folks !
