### ISSUE TITLE
[DX] [3.0] Remove 'secret' config parameter and 'kernel.secret' container parameter

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#14026]
Rationale
-------------

The `secret` parameter is one of Symfony's most misunderstood configuration parameters. In the documentation you can read [its explanation](http://symfony.com/doc/current/reference/configuration/framework.html#secret):

> This is a string that should be unique to your application. In practice, it's used for generating the CSRF tokens, but it could be used in any other context where having a unique string is useful. It becomes the service container parameter named kernel.secret.

However:

  * It seems that `secret` is no longer used to generate CSRF tokens.
  * We have never explained how to generate and maintain this configuration option: how long should it be? which kind of characters should contain? should I change it frequently? should I custody it as if it were a password? what would happen if some malicious user gets my secret?

I've tried to look for uses of the `secret` configuration parameter and I've found almost nothing.

First use: in the FrameworkBundle DI extension you can find the following:

```php
if (isset($config['secret'])) {
    $container->setParameter('kernel.secret', $config['secret']);
}
```

Second use: in the same FrameworkBundle there is one service that uses it:

```xml
<service id="uri_signer" class="%uri_signer.class%">
    <argument>%kernel.secret%</argument>
</service>
```

The alternatives
----------------------

If you agree that this configuration parameter is no longer useful, we could deprecate this option in 2.7 and remove it entirely in 3.0.

If you still think that this option could be of some value, we could remove the `secret` configuration option and generate the `kernel.secret` parameter automatically by creating a random string in the FramewokBundle DI extension.

**Comment by stof** [comment]
The RememberMe feature needs a secret IIRC, and it defaults to kernel.secret.

The difficult part with generating a random one is that it cannot be generated all the time: all your servers need to have the same value (otherwise signed URLs and remember me cookies will be invalid if you reach the other server behind the load balancer) and also stay the same when deploying a new version of the code (same reason).

**Comment by sstok** [comment]
@stof Should be rename it instead? Because "secret" is a bit ambiguous.

Give the uri-signer its own dedicated config key "framework.uri_signer.secret_key" or "framework.fragments.signer_key".

**Comment by javiereguiluz** [comment]
I'm closing this issue because, after reading @stof's compelling reasons, I don't think it makes sense.

@sstok I agree with you that the name could be better ... but changing it would slightly improve the situation but it would introduce yet another BC break in 3.0. I think we should maintain the option name, but improve its documentation. I'm going to submit a PR to the doc repository soon.

**Comment by Tobion** [comment]
How about we move the secret to `secret.yml` and add a composer listener that generates a random string as secret when there is not secret.yml and then caches writes it itso the file.
The path to `secret.yml` could also be configurable with a composer option.

This way, people don't need to manually generate a random string but it still stays the same across servers and versions.

**Comment by javiereguiluz** [comment]
@Tobion your proposal looks good to me. But I don't think we need to add this feature to Symfony itself, because the new Symfony Installer already takes care of this (see https://github.com/symfony/symfony-installer/blob/master/src/Symfony/Installer/NewCommand.php#L477).

**Comment by sstok** [comment]
@javiereguiluz How about a console command for those who don't use the installer or need to generate a new string?

**Comment by jrobeson** [comment]
yeah, i'd like to have that too.  i do know rails also has this command "rails secret"

**Comment by Pierstoval** [comment]
I think that this kind of command does not have its own place in the installer, but in the framework.
 
Anyway I think that more documentation is enough to teach how to really use the `secret` parameter.

**Comment by javiereguiluz** [comment]
@sstok I don't really have a strong opinion about that. No doubt it would be useful, but given the tiny logic involved in it, is it really worth it to include it in Symfony?

**Comment by sstok** [comment]
It maybe tiny logic, but it is important to always have a good secret.
As the web-configure and installer are the only two places where you can get one now its harder to generate a secure one.

Now I only need a good command name, `config:generate-secure [--no-update]`?

**Comment by Pierstoval** [comment]
@sstok This sounds a good deal, but only in the symfony framework, not in the installer :) 
 
But it does not solve the problem of "where to put it", because generating the secret implies to know where it's located, and if someone changes the default behavior in the standard edition, the command must find the secret parameter and change it where it's set.

**Comment by sstok** [comment]
The `--no-update` was just an idea ;) basically you need a command to generate a secret.
Updating is secondary.

**Comment by ClementNotin** [comment]
I'm reopening this issue, because as @javiereguiluz explained at the beginning, the secret is not used anymore for CSRF tokens but this statement is still written in the current documentation https://symfony.com/doc/current/reference/configuration/framework.html#secret
This is confusing and I would recommend to clarify this by removing the statement or describing that it was valid until a certain version.
My understanding is that the CSRF token provider that used this parameter has been deprecated since v2.4 and removed in v3.0 according to https://github.com/symfony/symfony/blob/2.4/src/Symfony/Component/Form/Extension/Csrf/CsrfProvider/DefaultCsrfProvider.php#L22 or http://api.symfony.com/2.3/Symfony/Component/Form/Extension/Csrf/CsrfProvider/SessionCsrfProvider.html#method___construct
