### ISSUE TITLE
(RFC) [Twig Bridge] LintCommand move to Twig

### ISSUE THREAD

**Issue by SpacePossum** [symfony/symfony#14056]
Would it be possible to move the Twig lint logic from Symfony to Twig itself?
It would make it easier to use the lint command in a CI setup in non-symfony Twig projects (like Silex based, etc.)

**Comment by stof** [comment]
For reference for future readers interested in this issue, most of the logic is actually in Twig already.

The linting logic is only https://github.com/symfony/symfony/blob/37c137acddbbfea1c46777a62f5ce02a8d447c76/src/Symfony/Bridge/Twig/Command/LintCommand.php#L141-157 (everything else deals with finding files and outputing the result to the user, which is not something Twig should deal with).

This could even be simpler by using ``$twig->compileSource()`` to handle the tokenization, the parsing and the compilation (I'm not sure it was available in Twig at the time the LintCommand was implemented in Symfony).

And this logic is a bit complex because the command deals with file names and does not know the name of templates. In case you know the name of templates to be linted (and you cleared the cache of compiled templates in case you don't run Twig in auto_reload mode), this is all you need:

```php
try {
    $twig->loadTemplate($templateName);
} catch (Twig_Error_Loader $e) {
    // Template name is invalid. fix your linting input
} catch (Twig_Error $e) {
    // Template is invalid
}
```

**Comment by SpacePossum** [comment]
@stof Thanks for explanation :+1: Good pointers to get started :)

(I realised there was enough in Twig itself already so closed I the issue)
