### ISSUE TITLE
Improve RecursiveContextualValidator debugging

### ISSUE THREAD

**Issue by dawehner** [symfony/symfony#14108]
... Let's say the least, having to debug problems in RecursiveContextualValidator is hard
Drupal is struggling with it already with more than one week fulltime work.

One general suggestion would be to make the methods protected, which would allow to
add some decorator which adds helpful debug output, so we know which method is executed how often
and at which level of the tree

**Comment by stof** [comment]
We won't make method protected, unless we have a strong use case for them to become extension point (and we recognize that inheritance is the right extension point for this use-case). Anything protected needs to be taken into account for BC when refactoring the code, as they are extension points subject to being used by other code. On the other hand, we can do what we want with our private code.
If everything was protected in Symfony, we would not be able to provide our BC guarantee while keeping all framework evolutions we are doing (and the places were we are using inheritance to provide extensions have already caused us pain when wanting to refactor the code because of the need to preserve BC...)

**Comment by jakzal** [comment]
@dawehner any feedback on stof's comment?

**Comment by dawehner** [comment]
To be honest at that point I don't care anymore given that we worked on our own implementation of the RecursiveContextualValidator bound to our domain

**Comment by dawehner** [comment]
Thanks for taking the time to try to help about it

**Comment by jakzal** [comment]
Fair enough :)
