### ISSUE TITLE
Define documentation standards for service tags

### ISSUE THREAD

**Issue by cilefen** [symfony/symfony#14149]
I am working on this [Drupal 8 issue for documenting service tags](https://www.drupal.org/node/2264047). Right now it looks as though we may implement a `@service_tag` doc tag. 

It would be good to match implementations if Symfony would want to document service tags. Has there been any interest among the Symfony developers in documenting service tags?

**Comment by jakzal** [comment]
We've recently added the `@Event` annotation (see #12299).

I'm not sure how much value would this bring to Symfony. However, to be consistent with `@Event` and doctrine's `@Annotation` I propose you use `@ServiceTag` for Drupal.

**Comment by xabbuh** [comment]
One problem I see with this is that the interface being used when processing the tag, might not be aware of the tag at all (for example, because the interface in one of the component, but the compiler is in a bundle). How would we deal with this?

**Comment by jakzal** [comment]
Note I'm not a fan of introducing it in Symfony, I merely suggested some consistency in naming.

I don't like this way of documenting tags at all. Having this implementation detail in an interface feels a bit wrong to me as it couples the interface to a service container. An interface, or its implementation, can be successfully used without a DI container. It just seems to be a wrong place for this. 

Perhaps a command listing tags, or another way of documenting them in a context of the container would be better.

**Comment by cilefen** [comment]
@xabbuh I agree—the issue over where to document them is difficult.

**Comment by xabbuh** [comment]
The only place where this basically makes sense is the compiler pass that is processing the particular tag. Though I'm not sure if anyone would really find their description in the API docs (again you would have to know which class processes the tag to find the description).

> Perhaps a command listing tags, or another way of documenting them in a context of the container would be better.

That would probably be the best solution. We just need to find a way to expose some explanation with a tag.

**Comment by jhodgdon-drp** [comment]
Hi there, I'm the Documentation maintainer for Drupal core... A few thoughts on why we're thinking along the directions we're currently thinking:

a) We use a custom docs parser in the Drupal project to make our API documentation site (https://api.drupal.org). It was originally modeled on (or implementing?) Doxygen, but has since evolved. So... basically we can add tags and I (the maintainer of the docs parser) can make our docs site recognize them, list them, and do whatever else we want to do with them. I did that recently with the @Event tag from Symfony, for instance -- made them automatically list in Drupal on this page:
https://api.drupal.org/api/drupal/core!modules!system!core.api.php/group/events/8

So, whatever we adopt, as long as it starts with @, should be fine. 

b) Generally the tags we use in docs, like @author, @param, @return, are lower-case. That's why the suggestion was @service_tag. But, as I said in (a) I'm not set on this.

c) The reason we are thinking that the Interface is the best place to document the tags is that presumably, someone who is implementing a service would need to read the interface to learn about what methods the service class needs. So, they're already looking at that interface; it seems sensible to also include there the docs on what tags they can or need to put in their services.yml file for that same service.  One-stop documentation shopping.

Also, for the code/docs maintainers, having the docs all in one place is useful, again one-stop shopping.

To my mind, the closer we can keep the code and docs, and the fewer places people have to look to find docs, the more likely it is that the docs will actually get updated when the code changes, and that a consumer of docs (service developer in this case) will discover them.

d) "Find a way to expose some explanation with a tag" -- indeed. Our custom docs parser lets us fairly easily add a new tag-with-documentation fairly easily; not sure about Symfony. [For "us" in the previous sentence, read "me".]

Anyway... Obviously it would be great for everyone (I think) if Symfony adopted a way to document these that makes sense, and then we'll adopt the same thing in Drupal-land and I'll adapt the API docs parser we use, and life will be good.

**Comment by fabpot** [comment]
Closing as there is no traction on this from Symfony core team.
