### ISSUE TITLE
[Form] unintended validation BC break by #14050

### ISSUE THREAD

**Issue by craue** [symfony/symfony#14165]
#14050 seems to inadvertently affect validation. When submitting an empty required choice field, there's now a message "This value is not valid." which wasn't there before. See https://github.com/symfony/symfony/pull/14050#issuecomment-88445279.

**Comment by webmozart** [comment]
Could you please post some code to reproduce this issue? Preferably a clone of symfony-standard?

**Comment by craue** [comment]
@webmozart: Done in https://github.com/craue/symfony-standard/tree/2.7-symfony-issue-14165.

Pre-PR (using `"symfony/symfony": "2.7.x-dev#ef886548a0b6d1467876a60ef8f2c0f1e5a3ac3c"`) the error message is "This value should not be blank.", caused by the `NotBlank` annotation in the entity.

Post-PR (using `"symfony/symfony": "2.7.x-dev#776796435e9f09cdb1b3afd71df2bff9b89d0c36"`) it's "This value is not valid.", making validation fail at some other point.

**Comment by webmozart** [comment]
Thanks, I can confirm this. The reason is that `ChoiceToValueTransformer::reverseTransform()` originally returned `null` if either an empty string or `null` were passed, but without asking the choice list first. That was buggy in the case that you mapped the empty string to a custom choice, so I removed that check.

We need to find some other solution to allow empty strings if (i) the placeholder is enabled and (ii) the choice list does not already contain a choice with an empty string as value.

**Comment by samvaughton** [comment]
I'm also getting this. For an entity form type that is not required by default it will cause a SQL error due to an empty string `""` being passed in the `WHERE IN (?)` clause.

If the `empty_data` is `0` then the query runs how it should but displays the "This value is not valid" message since no entity exists with id `0`.

This stops any form from having optional entity form types.

**Comment by ngodfraind** [comment]
Any idea for a workaround ?

**Comment by adam187** [comment]
@ngodfraind https://github.com/symfony/symfony/pull/14465

**Comment by ngodfraind** [comment]
Thanks

**Comment by craue** [comment]
It's fixed by #14465. Thank you, @webmozart.
