### ISSUE TITLE
DomCrawler incorrect results for text extraction

### ISSUE THREAD

**Issue by sparrowek** [symfony/symfony#14249]
When using extract with '_text' I only got leading text for any node.
The text() function returns "test1test2test4test5test6test7test3" but extract() does not return 'test5' nor 'test7'

```php
$response = '<html><body>test1<p>test2<div>test4</div>test5<div>test6</div>test7</p>test3</body></html>';
$crawler = new Crawler($response);
$text1 = $crawler->filter('body')->text();
var_dump($text1);
$text2 = $crawler->filter('body *')->extract(array('_text'));
var_dump($text2);
```

**Comment by jakzal** [comment]
Firstly, your two calls are not equivalent. You filter by `body` first and by `body *` second. First call returns a collection with a single node, while the second call returns multiple nodes. If you filter by `body` you'll get the same string in both cases.

**Comment by jakzal** [comment]
Secondly, `text()` and `extract()` behaviour is a bit different. 

**text()**

`text()` works on [a single node](https://github.com/symfony/symfony/blob/95b6c564960e185f77a5f2f74916ff8a23b6d80f/src/Symfony/Component/DomCrawler/Crawler.php#L567) (the first found). If `filter()` returns more than a single node, `text()` will only use the first one.

Take `$crawler->filter('body')->text()` as an example:
*  `$crawler->filter('body')`will return a Crawler decorating a single `body` node
* `->text()` will take the first (and only) node and return its text (`test1test2test4test5test6test7test3`)

Looking at `$crawler->filter('body *')->text()`:
*  `$crawler->filter('body *')`will return a Crawler decorating all children of body - three `p` nodes.
* `->text()` will take the first node and return its text (`test2`)

**extract()**

`extract()` on the other hand [works on a collection of nodes](https://github.com/symfony/symfony/blob/95b6c564960e185f77a5f2f74916ff8a23b6d80f/src/Symfony/Component/DomCrawler/Crawler.php#L612).

Looking at `$crawler->filter('body')->extract(['_text'])`:
*  `$crawler->filter('body')`will return a Crawler decorating a single `body` node
* `->extract(['_text'])` will iterate over all the nodes (there's only one) and return their text (`[test1test2test4test5test6test7test3]`)

Looking at `$crawler->filter('body *')->extract(['_text'])`:
*  `$crawler->filter('body *')`will return a Crawler decorating all children of body - three `p` nodes
* `->extract(['_text'])` will iterate over all the nodes (three `p` nodes) and return their text (`['test2', 'test4', 'test6']`).

**Comment by jakzal** [comment]
In other words, everything works as expected. Hopefully I managed to clarify this for you.

**Comment by sparrowek** [comment]
I am still a bit confused - the body has one p and two div's (contained in the p). The text that is inside the p is text2, text5 and text7. Is there a way to extract all of it?

**Comment by jakzal** [comment]
I'll have a look again tomorrow.

**Comment by jakzal** [comment]
Like I said earlier both methods work as expected. Both `$crawler->filter('body')->text();` and `$crawler->filter('body')->extract(array('_text'));` do return full text inside the body tag (`test1test2test4test5test6test7test3`).

If you need a list of text nodes, instead of a single value you'll need to use XPath. Selecting text nodes is not possible with CSS selectors. It's a limitation of CSS selectors in general, not just this library. 

Example:

```php
$crawler->filterXPath('//body//text()')->extract(array('_text'));
```

Note that we don't use github for support questions. Feel free to reopen this issue if you think there's a bug.

**Comment by jakzal** [comment]
I did find one bug though.

In my last example the `filterXPath()` method should return 7 elements. It returns 6 (last two are merged). I'll create a bug report for this.

**Comment by jakzal** [comment]
Ok, there's no bug after all ;)

Try this to see how PHP loads your html document:

```php
$response = '<html><body>test1<p>test2<div>test4</div>test5<div>test6</div>test7</p>test3</body></html>';
$crawler = new \Symfony\Component\DomCrawler\Crawler($crawler);
echo $crawler->html();
```

It outputs:
```
<body>test1<p>test2</p>
<div>test4</div>test5<div>test6</div>test7test3</body>
```

This is because we use the [DOM](http://php.net/manual/en/book.dom.php) library internally to load documents. It is a library for handling XML documents. Since your html example is not a valid XML, looks like DOM tries to convert it to a valid document.

Crawler silences warnings while loading html documents. If you try to use DOM directly:

```php
$doc = new DOMDocument;
$doc->loadHTML('<html><body>test1<p>test2<div>test4</div>test5<div>test6</div>test7</p>test3</body></html>');
```

you'll get the following warning:

```
PHP Warning:  DOMDocument::loadHTML(): Unexpected end tag : p in Entity
```
