### ISSUE TITLE
[Process] "Process->run()" high CPU usage on Windows

### ISSUE THREAD

**Issue by klemenb** [symfony/symfony#14252]
I've been debugging an issue with Laravel's queue listener on Windows and there appears to be a problem with Symfony's Process component that causes an excessive amount of temporary file reads during a simple `Process->run()` execution.

It can be observed by running the below snippet of code and monitoring your CPU usage.
```php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Process\Process;

$process = new Process('notepad');
$process->run();
```
The problem apparently stems from the combination of `Process->wait()`'s do-while loop for checking the current state of the process and the `WindowsPipes->readAndWrite()` implementation.

I've compared 1 second long runs (using `php -r "sleep(1);"` as the child process) on Linux and Windows and you can find the corresponding **Xdebug profiler outputs** here: http://1drv.ms/1O2MHaf (2000+ `readAndWrite()` calls on Windows, 10 on Linux)

A simple (and "dirty"?) solution would be to add`usleep()` inside the do-while loop but I am not sure what the wider implications would be. The elegant solution would probably be to bring `WindowsPipes` behavior closer to the `UnixPipes`, but I guess that core PHP issues don't really allow that.

**Comment by javiereguiluz** [comment]
I'm closing this because, as you said, this is due to internal PHP limitations. `Symfony\Component\Process\Pipes\WindowsPipes` uses a lot of workarounds for PHP bugs. Some of them, like https://bugs.php.net/bug.php?id=51800, has been fixed in recent versions of PHP. But as you can read in the PHP bug tracker, the "fix" has introduced new bugs.

If @romainneutron, the maintainer of Process component, or any other person from the community, comes up with a different approach to solve this, we can reopen the issue.
