### ISSUE TITLE
Trigger a E_USER_DEPRECATED when I used a deprecated service

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#14307]
My current problem is the following:
I upgrade a legacy application to 2.8. And I've now a `E_USER_DEPRECATED`: `Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfProviderAdapter class is deprecated since version 2.4`. 
I search a lot and found that the problem was the parameter `csrf_provider` in `security.yml` who's defined to the service `form.csrf_provider`. Finally this service use the deprecated class `CsrfTokenManagerAdapter` which let `FormTypeCsrfExtension` to instanciate a `CsrfProviderAdapter`... ouch.. hard to debug and find the source of the deprecation.

An idea to help is such case, is to trigger the `E_USER_DEPRECATED` earlier.
We (@nicolas-grekas and me) thinks that it could be ncie to trigger the error when the service is  retreived from the container: A solution => When the container is compiled, we can Reflect the class defined in the service, and, automaticly add a trigger_error if the `@deprecated` annotation is found.

**Comment by nicolas-grekas** [comment]
Rethinking about this, it would even be simpler and more reliable to just have a "deprecated" tag in the deprecated services definition. In debug mode, this should trigger deprecation notices.

**Comment by cordoval** [comment]
@nicolas-grekas is there a way to avoid notices even in debug mode? sometimes even we are doing the right thing, e.g. using twig.form_themes: [...] instead of say twig.form.resources but because there is a setter $container->setParameter('twig.form.resources', $config['form_themes']); even on 2.8 https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L58 we get the notice for no reason. 

Should I send a PR to fix this or what is the purpose of this. Thanks in advance for the explanation. :older_man:

**Comment by nicolas-grekas** [comment]
@cordoval see #14305. And yes, this needs a bug fix on 2.7

**Comment by WouterJ** [comment]
Checking for a `@deprecated` annotation on the class is not always enough (a service can also be renamed). So I'm +1 for a deprecated tag (which can be provided by the DebugBundle).

**Comment by hhamon** [comment]
A `deprecated` tag seems to be a smart solution.
