### ISSUE TITLE
Fix FileLoaderImportCircularReferenceException errors

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#14342]
Symfony 2.6.5 version changed the way errors are displayed in the browser. Lately a lot of users are complaining about this new behavior: #14337, #14199, #1396, #14111, #14073.

Symfony 2.7 beta tried to solve this problem, but the result is not completely satisfactory.

To better understand the problem, check out the different error messages that you get when your controller uses the `@Security` annotation without importing its associated class.

### Symfony 2.6.4

The error message is perfect.

![2_6_4_web](https://cloud.githubusercontent.com/assets/73419/7124728/a9ecdc2a-e22b-11e4-8626-9a0d10456c5b.png)

### Symfony 2.6.5 and 2.6.6

The error message is awful.

![2_6_6_web](https://cloud.githubusercontent.com/assets/73419/7124730/bab1730e-e22b-11e4-96eb-8915b5c14d43.png)

### Symfony 2.7

You see 4 error messages instead of just 1. The good error is displayed at the bottom and the awful error is displayed first.

![2_7_dev_web](https://cloud.githubusercontent.com/assets/73419/7124736/c5213234-e22b-11e4-81c1-21f4b390833d.png)

This behavior only happens in the browser. If you use Symfony 2.6.5 or 2.6.6 in the console, you get perfect error messages:

![2_6_4_cli](https://cloud.githubusercontent.com/assets/73419/7124764/f5529218-e22b-11e4-87bd-defe2dacab34.png)

In my opinion this is a **critical issue** that should be fixed both for 2.6 and 2.7.

**Comment by Green-Cat** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
Let's close all duplicates :) The issue also exists in 2.3. Here is the situation:

#14073 fixes error reporting and makes this error understandable. Still, it does not fix the root of this very issue, which is:
- the routes are loaded but this fails with an exception because the route definition has an issue
- this exception is handled by the HttpKernel and re-injected for rendering to the exception controller route
- but this also fails because for the same reason, the routes can not be loaded.

The root issue is that the router is not able to partially load the routes that are required for displaying the exception page.

**Comment by nicolas-grekas** [comment]
The perfect error message we want is not the one we had in 2.6.4.
Here it is :-) (patch pending)

![x](https://cloud.githubusercontent.com/assets/243674/7132566/bd0b04da-e28a-11e4-9eab-47632c6da3c3.png)

**Comment by javiereguiluz** [comment]
@nicolas-grekas you are awesome! Thanks a lot for making Symfony errors great again :)

**Comment by nicolas-grekas** [comment]
See #14345 and #14346
