### ISSUE TITLE
 [Validator] 2.5 API lacks a way of preprocessing validated values

### ISSUE THREAD

**Issue by fago** [symfony/symfony#14396]
We ran into an issue while porting the Drupal symfony validator integration to 2.5 API compatibility at https://www.drupal.org/node/2343035. With the 2.4 API it was possible to preprocess every value that is being validated before it is passed on to validators. Unfortunately in 2.5 that's not possible any more.

In Drupal, the validation metadata comes with the objects we want to validate. Those objects wrap the values in its regular representation (at least most of the times). For being able to extract the metadata from the object, we need to pass the (Typed data) objects to the symfony validator, such that the metadata classes are able to extract the constraints. However, with the current API there is no posibility to preprocess the validated value for the root node of the validation tree. (It's possible for properties via getPropertyValue() only).

Thus, in order for being able to upgrade to Symfony 2.5 API we'll need to add a way to do that. I'd propose adding a PreprocessingMetadataInterface which allows excatly for that. It's a bit similar to object initializers, but those don't work for us as we need the $value to be passed by reference in order to be able to replace the object.

If the approach makes sense to you, I can work on adding test coverage also.

**Comment by stof** [comment]
What do you mean by preprocing values ?

**Comment by fago** [comment]
Please see the PR or https://www.drupal.org/node/2343035#comment-9840605 for a working patch implementing the interface. 
So what we are doing there (in most cases) is to assign $typed_data->getValue() to $value - where $typed_data was the previous $value.

**Comment by stof** [comment]
I'm not asking for how it would be implementing. I'm asking about the feature itself and and its goal.

**Comment by fago** [comment]
I think I described that in the initial post, not? If there is something unclear there, I'm happy to provide more context. 
Well, the general goal is being able to use Symfony validator 2.5 API in Drupal, instead of having to use the 2.4 BC layer as this will prevent us from upgrading to Symfony 3.

**Comment by stof** [comment]
@fago why not writing a validation constraint for the TypedData implementatio itself rather than writing a special metadata system unwrapping the typed data and then accessing the typed data again from inside the validator to run more constraints on them ?
This would avoid to introduce the extra feature. Note that I haven't tried this approach. I only looked at the code quickly.

@webmozart what do you think about this ?

**Comment by fago** [comment]
I already tried a special constraint wrapping others in order to preprocess things. But I ran into the problem, that when you invoke the validator with the constraints directly, it does not cascade any more (it just uses some generic metdadata class also).  See https://www.drupal.org/node/2343035#comment-9826007

Also, it has issues for constraints which need to be able to use the TypedData object. So actually, we have both uses cases: Regularly, you get the internal value while some more generic validators can choose to work based upon the TypedData object by fetching it from the metadata.

**Comment by webmozart** [comment]
Given the already heavy implementation of the validator, I don't think we should add extra logic for rare use cases.

I talked to @fago in person and the solution seems to be to add custom implementations of ValidatorInterface and ContextualValidatorInterface, since they have a very different object graph than we do anyway. As such, I will close this issue.
