### ISSUE TITLE
BCryptPasswordEncoder only for PHP >= 5.5.0

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#14511]
In the Security Component in ```Security/Core/Encoder/BCryptPasswordEncoder.php``` there is a comment for the ```encodePassword()``` function:

```
     * It doesn't work with PHP versions lower than 5.3.7, since
     * the password compat library uses CRYPT_BLOWFISH hash type with
     * the "$2y$" salt prefix (which is not available in the early PHP versions).
```

I think somebody should change this into PHP 5.5.0 because the used ```password_hash()``` function is only available since PHP 5.5.0. http://php.net/manual/en/function.password-hash.php

**Comment by jrobeson** [comment]
@JHGitty: we use ircmaxell's password compat lib to avoid requiring php 5.5.0

**Comment by stof** [comment]
@JHGitty This encoder works for PHP 5.3.7+ thanks to the password compat library. There is indeed no support for PHP 5.3.6 and below, but these versions of PHP are totally broken and insecure anyway (you cannot use annotations properly for instance because of a Reflection returning a random docComment for any class/method which does not have one, thus using annotations of a different class). And for Symfony 2.7, we bumped the minimum requirement to 5.3.9 anyway because bugs in early PHP versions were too annoying to continue supporting them (lots of such bugs don't have any workarounds)

**Comment by Tobion** [comment]
I think we should remove the comment in version where we require higher php anyway to avoid confusion.

**Comment by JHGitty** [comment]
Ah, now I understand that there is "password_compat" for support for 5.3.7 - 5.5.0. Sorry for this mistake.

Yes, this should be removed for Symfony3 if the minimum requirement is PHP 5.5.

@stof I think it was a great idea to increase the minimum requirement to 5.3.9.
