### ISSUE TITLE
Workaround for fixed ProcessUtils bug no longer needed?

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#14534]
https://github.com/symfony/symfony/blob/42e3ecbe783ea10b73dd8868583698d4d401d083/src/Symfony/Component/Process/ProcessUtils.php#L43

https://bugs.php.net/bug.php?id=43784

**Comment by iltar** [comment]
Which php versions are affected? 2015-01-09 01:04 UTC is the date it got closed but I don't see which php versions got patched. If it's still broken in a version that's supported by Symfony, it can't be removed. I think this would be a nice case for a php-version-check-if-statement in that case.

**Comment by flip111** [comment]
Well the guy who reported it fixed also doesn't know in which version it was fixed. So if this is important to know someone will have to test all the minor versions to pinpoint the correct one. Possibly something from the sourcecode could be deduced.

**Comment by iltar** [comment]
Maybe it's noted in the changelog somewhere.

**Comment by bate** [comment]
I looks like this bug was fixed somewhere between:
2008-01-08 and 2008-08-17 which maps to version 

ref: https://github.com/php/php-src/commits/master/ext/standard/exec.c?page=2
PHP > 5.2.5 && < 5.2.8

I checked 5.2.6 and it was not affected anymore.

http://3v4l.org/RQOqq reported also no old affected version.

Due some other reported issues with windows and escapeshellarg (https://bugs.php.net/bug.php?id=43261) i would remove the code with the next major version of the framework ;)

**Comment by nicolas-grekas** [comment]
Lets' not play with something that work well
