### ISSUE TITLE
Workaround for fixed SplCaster bug no longer needed?

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#14536]
https://github.com/symfony/symfony/blob/b1e2dedf9ed103d4498f7ab0302f12f4589f15f7/src/Symfony/Component/VarDumper/Caster/SplCaster.php#L87

https://bugs.php.net/bug.php?id=65967

**Comment by iltar** [comment]
Why would it not be needed anymore? As long as Symfony supports the php versions that contain this bug, it should be there in my opinion. The fix could be put in an if-statement to avoid running it in higher php versions, but I'm not sure if this would be a gain.

If it's fixed, I do think that a comment should be added in which versions it's fixed with optionally a todo :+1:

**Comment by flip111** [comment]
The fixed version should not be that difficult to figure out as the solution points to a particular commit. I'm just not sure myself how to get the php version from the commit though. http://git.php.net/?p=php-src.git;a=commit;h=950d3d6e9b94b75b266c67bf9e3a85ae9c31905d

**Comment by stof** [comment]
the fix was part of PHP 5.5.24 and 5.6.8. So the workaround definetely cannot be removed.

**Comment by flip111** [comment]
@stof what about a version check to those two versions?
