### ISSUE TITLE
Issue in DomCrawler concerning HTML inside script tag

### ISSUE THREAD

**Issue by estshy** [symfony/symfony#14542]
Let's assume following markup

	<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title></title>
	</head>
	<body>
		<script type="text/javascript">
			var content = '<!DOCTYPE html><html><head></head><body></body></html>'
		</script>
               <div id="test"></div>
	</body>
	</html>

It's taken from youtube source code (search results page). With such structure DomCrawler crashes. Div `#test` is unavailable using `filter` or `filterXpath` methods.

**Comment by dosten** [comment]
You can test with this script:
```php
<?php 

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\DomCrawler\Crawler;

$html = <<<'HTML'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <script type="text/javascript">
    var content = '<!DOCTYPE html><html><head></head><body></body></html>'
    </script>
    <div id="test">test</div>
</body>
</html>
HTML;

$crawler = new Crawler($html);

echo $crawler->filterXpath("descendant-or-self::*[@id = 'test']")->text() . PHP_EOL;
```

Seems to be a DOMDocument problem in `loadHTML`

**Comment by jakzal** [comment]
This is an issue with DOMDocument indeed. 

When you try to load mentioned html with DOMDocument:

```php
$doc = new \DOMDocument();
$doc->loadHTML($html);
```

you'll get warnings back:

```
PHP Warning:  DOMDocument::loadHTML(): Unexpected end tag : head in Entity, line: 9 in /Users/jakubz/Projects/symfony/dom-script.php on line 24
PHP Warning:  DOMDocument::loadHTML(): Unexpected end tag : script in Entity, line: 10 in /Users/jakubz/Projects/symfony/dom-script.php on line 24
PHP Warning:  DOMDocument::loadHTML(): Unexpected end tag : body in Entity, line: 12 in /Users/jakubz/Projects/symfony/dom-script.php on line 24
```

Looks like this issue is already known: https://bugs.php.net/bug.php?id=52012. Someone suggested that's actually due to libxml2 handling of HTML and not PHP.

It might also be related to a common practice of [splitting the tags in JS](http://stackoverflow.com/questions/236073/why-split-the-script-tag-when-writing-it-with-document-write/236106#236106), which google often follows as well (for example in the analytics code). Something like the following would work:

```
    <script type="text/javascript">
    var content = '<!DOCTYPE html'+'><'+'html><'+'head><'+'/head><'+'body><'+'/body><'+'/html>'
    </script>
```

Closing, as it's not an issue with the DomCrawler.
