### ISSUE TITLE
[PHPUnit] PHP Fatal error:  Cannot redeclare class Symfony\Component\Debug\Tests\Fixtures\RequiredTwice

### ISSUE THREAD

**Issue by karolhor** [symfony/symfony#14573]
Hi. When I fire phpunit with all test suit, I've got error in 
```
ClassNotFoundFatalErrorHandlerTest::testCannotRedeclareClass()
```

I cloned symfony/symfony repo and  I haven't made any changes to the code. I also followed documentation for contributing & PHPUnit tests.

I check this with PHPUnit version 4.5.0 and 4.6.6.
My PHP version is 5.4.26, and OSX 10.10.3

I created a gist with my output: https://gist.github.com/karolhor/b2a767420ee7541dcbc2

**Comment by xelaris** [comment]
I can confirm. Running the tests of the Debug component is enough to repoduce. It don't let tests fail on travis because the related test is skipped on case-sensitive filesystems. The issue seems to be related to https://github.com/symfony/symfony/commit/d90891a#diff-49579792cd5fcfe2ddd72064b1e7f416R36. See PR #14588 for a solution.

**Comment by karolhor** [comment]
thanks :) I'm waiting for merge
