### ISSUE TITLE
[Security] AbstractAuthenticationListener should dispatch the login failure event instead of invoking onFailure() directly

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony#14685]
At the moment it invokes the `onFailure` directly, but according to the whole idea of kernel event system it should dispatch the `AuthenticationEvents::AUTHENTICATION_FAILURE` (or some other) event instead.

Then it would be possible to add custom handlers for the authentication events.

Example of event that you cannot handle with the current implementation: CSRF token mismatch.

References:
- https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php#L160

**Comment by iltar** [comment]
I think that the main challenge here, is that the `AuthenticationFailureEvent` doesn't support setting content... But I agree on the whole success/failure handling. It does make it very easy to set a specific handler per authenticator.

**Comment by mTorres** [comment]
AFAIK, you don't need to dispatch an event in order to hook on the AuthenticationFailuire. The failure handler is a *Symfony\Component\Security\Http\Authentication\AuthenticationFailureHandlerInterface* so you just need to implement your own.

The success and failure handlers are passed to the constructor of the AbstractAuthenticationListener, so with current implementation you should be able to hook your code to the authentication flow.

**Comment by zerkms** [comment]
@mTorres not everything: you cannot handle wrong CSRF token exception thrown at https://github.com/symfony/symfony/blob/2.7/src%2FSymfony%2FComponent%2FSecurity%2FHttp%2FFirewall%2FSimpleFormAuthenticationListener.php#L107

**Comment by zerkms** [comment]
@mTorres there is a problem with that - you can only have one of them. If you want to have the default handler and just process the failure additionally (like add something to log) you're still out of luck.

**Comment by mTorres** [comment]
Well, you can always create your on failure handler that dispatches an event, but I really see your point. Let's wait if the core developers think that this event should be fired on core instead of creating custom events. I'm +1 on this as we already have the *security.interactive_login* and the *security.switch_user*

**Comment by wouterj** [comment]
I think this can be closed. The experimental security system has a `LoginFailureEvent` that is dispatched whenever there is an authentication failure and can be used to set a custom response or execute custom logic on failure.
