### ISSUE TITLE
[Console] Generating urls in command in dev environment

### ISSUE THREAD

**Issue by kminh** [symfony/symfony#14691]
Hi,

According to http://symfony.com/doc/current/cookbook/console/sending_emails.html we need to manually specify host/scheme/path. However, do I have to do this for the dev environment?

```php
        $env = $container->get('kernel')->getEnvironment();
        $context = $container->get('router')->getContext();
        $context->setBaseUrl($env != 'prod' ? '/app_' . $env . '.php' : '/'); 
```

Because when I try generating urls without setting the base url, all generated urls are missing the `app_dev.php` path.

Any insight is appreciated.

**Comment by Tobion** [comment]
Yes you need to set the app_dev.php base url in dev mode if you want it to be included.

**Comment by kminh** [comment]
Thanks for your reply.

Is there a reason why it is not included by default? I imagine the `setBaseUrl` is for other use cases.

**Comment by Tobion** [comment]
In console environment you do not have a HTTP request to get the base url from, which is why you have to call setBaseUrl manually. And since the routing context does not know anything about the "dev" environment, it also cannot add the base url automatically. Furthermore people might use a different dev base url than `app_dev.php` which they might have changed.
