### ISSUE TITLE
[2.7][BC Break][Assets] version argument in twig asset() function is broken

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#14692]
I couldn't find any related upgrade notes on this one. Any suggestions on how to continue here?

```twig
{{ asset('/bundles/mybundle/js/webshop.js', version=md5_timestamp) }}
```

This gives me the following error: 
```
An exception has been thrown during the rendering of a template ("Property Symfony\Component\Asset\PathPackage::$versionStrategy does not exist")
```

**Comment by dosten** [comment]
The problem is here https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Twig/Extension/AssetExtension.php#L102
Changing the private property `$versionStrategy` of `Symfony\Component\Asset\Package` to protected solves the issue i guess. but it's not the best solution i think, why we should overwrite the VersionStrategy in AssetExtension? cc/ @fabpot

**Comment by stof** [comment]
@dosten changing the visibility of the property to protected is the bad way to fix it. WE should get the ReflectionProperty for the right class instead.

**Comment by dosten** [comment]
@stof agree, something like this should work
```php
$ref = new \ReflectionClass($package);
$v = $ref->getParentClass()->getProperty('versionStrategy');
$v->setAccessible(true);
$currentVersionStrategy = $v->getValue($package);
```

**Comment by aitboudad** [comment]
[Access a private property (via Reflection)](http://symfony.com/doc/current/contributing/code/bc.html) is not allowed and It's a BC break, isn't it ?

**Comment by dosten** [comment]
I think that we don't guarantee BC if someone else access a private property (via Reflection), in this case the access is from the Symfony code.

**Comment by xabbuh** [comment]
see #14708
