### ISSUE TITLE
[2.7][BC Break][FrameworkBundle] Templating services no longer exists by default.

### ISSUE THREAD

**Issue by aitboudad** [symfony/symfony#14719]
```batch
The service "lexik_mailer.message_renderer" has a dependency on a non-existent service "templating.globals".
```

**Comment by iltar** [comment]
It seems like the service is defined in a file that's only loaded if the php engine is enabled:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/Resources/config/templating_php.xml#L88-L90

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L543-L544

**Comment by jakzal** [comment]
`templating.globals` is meant to provide global variables to PHP templates. Seems a bit of misuse on LexikMailerBundle's side. Is it possible to fix it there?

**Comment by iltar** [comment]
Even though I agree with @jakzal, it's a BC break because of how the php templating was extracted. 

Maybe something can be done with service aliasing, this could provide a better error to the end-developer:
```
// default engine: twig
templating.twig.globals
templating.php.globals
templating.globals -> templating.twig.globals

// default engine: php
templating.twig.globals
templating.php.globals
templating.globals -> templating.php.globals

// default engine: twig
templating.php.globals
templating.globals -> error twig templating not registered

// default engine: php
templating.twig.globals
templating.globals -> error php templating not registered
```

**Comment by jakzal** [comment]
It is documented in the `GlobalVariables` class that it is meant to be used with PHP templates:

>  GlobalVariables is the entry point for Symfony global variables in PHP templates.

Not sure if we should be BC to a misuse. However, since there's at least one bundle that used this service, perhaps it wasn't documented well enough.

Given we're planning to drop or extract php templating (see #12897), and we currently have no alternative for `GlobalVariables`, there's no upgrade path we can provide for 3.0.

That's why I asked if it's possible to fix downstream, as it might be easier in there :)

@iltar there's no `templating.twig.globals`. Globals are [supported by twig](http://twig.sensiolabs.org/doc/advanced.html#globals) natively.

**Comment by xabbuh** [comment]
related to #14790

By the way, we moved the `templating.helper.assets` service back to `templating.xml` in #13871.
