### ISSUE TITLE
[profiler][request toolbar] keep only action name in the toolbar icon.

### ISSUE THREAD

**Issue by aitboudad** [symfony/symfony#14744]
Before:

![selection_009](https://cloud.githubusercontent.com/assets/1753742/7789838/243e0b72-025f-11e5-8a63-df2a781902f1.jpg)

After:

![selection_010](https://cloud.githubusercontent.com/assets/1753742/7789845/43b8719a-025f-11e5-87f4-c488fe55497a.jpg)

**Comment by inso** [comment]
Action name is not unique, why not just keep route name?

**Comment by angusty** [comment]
why?

**Comment by fabpot** [comment]
I like the fact that you can quickly identify the executed request. :-1: from me.

**Comment by aitboudad** [comment]
The toolbar icon should contains a little information and as you see in the screenshot it take 30% of the toolbar width which is wrong to me.
Is there another way to reduce the width of the request toolbar ?

**Comment by iltar** [comment]
I agree with both cases to be honest, working on 1440x900, with 2.7 I have a double rowed bar because it simply doesn't fit on there anymore, even with 2.6 I get this if the action names are very long. I use this feature to quickly trace back my current page to a certain controller and action.

What about showing `MyController :: myAction` and the route name when you hover over it? I know even this can be long, but 1/3 shorter on the average case. Another option would be to strip Controller and Action off, as they _always_ contain those values anyway, but this might be confusing: `My :: my`

**Comment by phansys** [comment]
I like the @iltar's proposal.
The ```My :: my``` syntax shouldn't be confusing, indeed its similar which you use in ```some_route.defaults._controller``` in ```routing.yml``` by instance (just missing the bundle name part).
IMO, it would be nice to show also the request method on hover.

**Comment by ogizanagi** [comment]
:+1: about @iltar suggestion

**Comment by tgabi333** [comment]
I would keep only the routing name, shows the controller and action on hover

**Comment by flip111** [comment]
When displaying the method name the "Action" part of "changePasswordAction" can be removed.

**Comment by stof** [comment]
I agree that we should find a shorter display for them to avoid taking 1/3 of the toolbar width just for this item (which causes issues when you have more items)

**Comment by xabbuh** [comment]
Stripping off `Controller` and `Action` sounds indeed like a good idea to me. What about also remove the route name here? You can see it when hovering the controller name and I assume most of the time you are more interested in finding the controller than the route name.

**Comment by iltar** [comment]
What about just showing the status, amount of requests + subrequests used in the bar and the rest when hovering?

**Comment by stevenmusumeche** [comment]
:+1:  to @iltar's suggestion
