### ISSUE TITLE
[Twig] Default Bootstrap config hides SonataUserBundle labels in AdminBundle

### ISSUE THREAD

**Issue by maalicki** [symfony/symfony#14760]
Hi,

If I use this configuration

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
          resources: ['bootstrap_3_layout.html.twig']
#        resources: ['bootstrap_3_horizontal_layout.html.twig]

with SonataAdminBundle & SonataUserBundle it disables some checkbox labels in admin panel.
Here is an example:
https://github.com/sonata-project/SonataAdminBundle/issues/3003

**Comment by jakzal** [comment]
@maalicki checkboxes render fine with both bootstrap layouts in a standard edition project. I can see on your screenshots that only one section of checkboxes doesn't have labels. Since sonata overrides some of the form blocks it might actually be sonata's issue. 

Would you be able to provide an isolated example of how to reproduce this issue with vanilla standard edition project (with no sonata)? Or at least indicate what's different with the status section from your screenshots.

**Comment by maalicki** [comment]
@jakzal it might be hard to provide example...
Also earlier I've reported it to Sonata but them told me to publish my issue here..
https://github.com/sonata-project/SonataAdminBundle/issues/3003

To reproduce this problem You can use my repo where I've noticed this problem
https://github.com/maalicki/SF2-ProductBundle
Just uncomment line 37 in file SF2-ProductBundle/app/config/config.yml

**Comment by WouterJ** [comment]
Might be related to https://github.com/symfony/symfony/pull/13501?

**Comment by stof** [comment]
@maalicki which Symfony version are you using ?

**Comment by jvasseur** [comment]
I got hit by this issue and it's a bit more complex.

The thing is, sonata tries to reset the the form theme by including the standard div layout. But if you have your app configured to use the boostrap one, the form component uses the checkbox row from the bootstrap layout with the checkbox widget from the div layout leading to a missing label.

This append because of how the form component inheritance system work (search for more specific blocks in all themes the search for more generic blocks).

I think a solution here would be to give a better way for bundles like sonata to reset the form theming, this could be an option to mark a form to ignore global themes.

**Comment by maalicki** [comment]
@stof 2.6.*

**Comment by stof** [comment]
@maalicki this does not tell me which version you are using. This constraint covers all 2.6 versions

**Comment by maalicki** [comment]
@stof I was using 2.6.6

**Comment by xabbuh** [comment]
@maalicki Do you experience the same with Symfony 2.6.11? By the way, please note that Symfony 2.6 reached end of maintenance by the end of July.

**Comment by maalicki** [comment]
@xabbuh I have not tested it on 2.6.11
I leave that project behind ;)

**Comment by xabbuh** [comment]
If I understand you correctly, we can close here then. Please feel free to provide more information if you disagree.

**Comment by maalicki** [comment]
As @WouterJ said, it might be related to issue   #13501 so I think @xabbuh  that it is ok to close this issue.
