### ISSUE TITLE
Excessive Initialization time on 2.6.8 in dev environment

### ISSUE THREAD

**Issue by jfx** [symfony/symfony#14768]
On Previous versions of symfony (lower than 2.6.8) the response time of a page was about 800 ms in dev environment. With the upgrade in 2.6.8 the response time was more than 4s with high usage of CPU. In production environment, I didn't notice any response time change between 2.6.7 and 2.6.8.
The timeline of the toolbar shows an Initialization time from 300ms for 2.6.7 to 3800ms for 2.6.8.
Environment : 
Linux Ubuntu 15.04
PHP 5.5.9

**Comment by ewgRa** [comment]
I install fresh Symfony 2.6.8. Total time 59 ms for dev env and home page of demo.

Maybe cache? In dev env there is many checks about changes in configs and so on. When you change something - it need time to recreate configs, compile twig cache and so on. Try reload page twice.

Also it can be specific Bundle, or third-party soft or something like this. Try install fresh symfony and than step by step add your bundles and software that you use.

**Comment by chbruyand** [comment]
Hello,

This seems to be introduced in pull request #14262.

Regards.

**Comment by wildpine** [comment]
Hi,

I also noticed this performance issue after udpdate to 2.6.8. In my application, after some tests I've found that using assetic controller is causing a big loss of performance.

In prod environment application works without problems because assetic controller is turned off, but in dev environment response time jumped from about 2000ms to over 9000ms and CPU usage is up to 100%. After turning off a controller it goes back to ~2000ms.

I've checked and the most time and resources are taken by container compilation and request matching (where routes collection are loaded and saved to cache), which are made for every request, also those for assets. Maybe this is specific for my application but in 2.6.7 version there was no such problems.

**Comment by Padam87** [comment]
#14771

**Comment by whisller** [comment]
Sadly I've noticed this problem on our projects as well. Needed to downgrade to `2.6.7`.

**Comment by kniziol** [comment]
Same problem here. Only downgrade to ```2.6.7``` resolves the problem...

**Comment by jfx** [comment]
Hi,
With 2.6.9 the performance regression seems to be solved.
Thanks for your quick solution.
