### ISSUE TITLE
[DX] [OptionsResolver] Access private members

### ISSUE THREAD

**Issue by lucascherifi** [symfony/symfony#14923]
I would like to retrieve the OptionsResolver state (its definition) In order to build a full synopsis when throwing Exceptions (for better DX).

I want to know if there is a reason for the members ($defined, $defaults, $required, $resolved, $normalizers, $allowedValues, $allowedTypes...) to be private or could they be protected insteadn so it lets me extends these.

Thanks !

**Comment by jakzal** [comment]
We define all members as private until a valid use case is found that requires higher visibility.

What's that you're trying to accomplish exactly?

**Comment by stof** [comment]
Anything protected means it is covered by a BC policy. This is why we make everything private in Symfony until we decide we need a proper extension point (and then we decide whether making things protected is the right extension point).

And making this options protected is not an option IMO, as we have some invariants between the properties and making them protected would mean we cannot rely on them anymore (as we don't control all the code accessing them), forcing us to add checks in many places to account for cases where we cannot rely on invariants anymore.

the OptionsResolver already has a bunch of public getters to access some of its state:

- ``getRequiredOptions``
- ``getDefinedOptions``
- ``getMissingOptions`` (all options without a default value; the resolution clones the instance and adds passed values in the default values btw)

Allowed values and allowed types are indeed not exposed currently. Exposing normalizers would probably not help you (they are just callables) and exposing the default values would not help you much because of lazy defaults (and btw, allowed values can also be callables).
And regarding ``$resolved``, it is only used on cloned instances during the resolution, so you would probably never have an instance of the OptionsResolver with this field populated in your own code (as the cloned instance is only passed to lazy defaults and normalizers during the resolution but not anything else).

So please describe exactly what you are missing for your use case so that we can look at a way to give the needed info (if possible). We won't turn everything protected.

**Comment by lucascherifi** [comment]
@jakzal : I would like to be able to get a "synopsis" (usage definition) of an OptionsResolver. We use this component in order to improve usage of our front end developers of our project twig "extendable templates" (extended by our front end developers). We have some "extendable templates" with many options. The OptionsResolver is for us a good way to let them use our extendable templates easily, and I would like to developed an twig extension to view available options of an "extendable template", in other way a better Exception message when options are not correctly used.

**Comment by phansys** [comment]
An use case would be the proposal made in #14892 by @xabbuh, but I don't know if it is valid enough.

**Comment by xabbuh** [comment]
@phansys Not really, the issue in #14892 was that the given `OptionsResolverInterface` implementation did not extend the `OptionsResolver` class.

**Comment by phansys** [comment]
But maybe making the properties of ```OptionsResolver``` protected, you could reimplement all required methods in ```LegacyOptionsResolverAdapter```.

**Comment by xabbuh** [comment]
Unfortunately, that's not possible because I cannot access the state of the passed `OptionsResolverInterface` implementation.

**Comment by Tobion** [comment]
Making the private properties protected is not an option as stof explained. When you have a concrete idea of what information is missing as public method, feel free to make a PR. But remember many things, like validation, can be a callable, which is too generic to really generate a synopsis. So I'm closing this one as the current proposal is not doable.

**Comment by Gummibeer** [comment]
Wouldn't it be a solution to implement proper getter methods for all properties? This won't be breaking, it doesn't effect the reliability of the properties itself but will allow all extending classes to access these properties and if needed set them again via the setters.

My **use case** for this is that I want to add, often requested, multidimensional options support via `dot.notation` and allow asterisk placeholders `dot.*.notation`. But to be able to resolve these asterisks to the real array keys I have to adjust the keys during `resolve()`. Everything works fine except the point that I can't get all the other properties (allowed values/types, normalizers, defaults, lazy).
With getters for all these properties it would be possible to get them for logging, adjust them by using the setters (reliability) and so on.
