### ISSUE TITLE
setRedrawFrequency causes ProgressHelper to only display after completion

### ISSUE THREAD

**Issue by stevenmusumeche** [symfony/symfony#14936]
I have a console command that iterates over many tasks. I am using the ProgressHelper to display a progress bar.  If I do not set `setRedrawFrequency`, it works fine.  However, if I set this number to anything, the progress bar is not displayed until after the entire process is finished.

This works:

````
$progress = new ProgressBar($output, 50000);
$progress->start();
$i = 0;
while ($i++ < 50000) {
    $progress->advance();
}
$progress->finish();
```

This causes the progress bar to not be displayed in `finish()` is called:

````
$progress = new ProgressBar($output, 50000);
$progress->setRedrawFrequency(100);
$progress->start();
$i = 0;
while ($i++ < 50000) {
    $progress->advance();
}
$progress->finish();
```

**Comment by javiereguiluz** [comment]
@stevenmusumeche thanks for reporting this issue! In order to help you solve the problem, we may need more information about your installation (e.g. Symfony version) and ideally, some reproducible code for the entire command.

In case you find it useful, the Symfony Installer uses the setRedrawFrequency() in a command without problems. See: https://github.com/symfony/symfony-installer/blob/master/src/Symfony/Installer/DownloadCommand.php#L107

**Comment by stevenmusumeche** [comment]
I am using Symfony version 2.6.9. I am running this on a local Vagrant VM which runs CentOS 6.5. After further testing, it seems the process was competing very quickly (even over 50,000 entries) so it appeared to just complete without any progress.  By removing the setRedrawFrequency command, it introduced enough load to slow down the progress enough to take multiple seconds.

**Comment by stof** [comment]
if you don't do anything in the loop except advancing the progress bar, things will indeed be too fast to see them
