### ISSUE TITLE
Win Server 2008 R2, IIS7, not working, no output

### ISSUE THREAD

**Issue by KuenzelIT** [symfony/symfony#15006]
Hey,

I'm trying to get a backup package for Laravel working on a Windows Server 2008 R2 with IIS7 (yes it has to be Windows :) ).
I'm executing the following script and dont get any output, error or any reaction.
```
$command = 'C:\MysqlDump\mysqldump --user="user" --password="password" --host="localhost" --port="3306" "db" > "C:\test\mysql.sql"';
$process = new Process($command);
$process->setTimeout(999999999);
$process->run();
		
print_r($process->getErrorOutput());
print_r($process->getOutput());
```
The IUSR account of IIS has full permissions on mysqldump and the target folder. And replacing the process with "exec()" is working. But this is the second package with such a problem and I don't want to do this workaround everywhere.

I don't have any problems on my development machine with Windows 7 and xampp.

Does anyone have an idea what could go wrong here?

Thank you!

**Comment by ewgRa** [comment]
If there is just nothing, there is can be fatal error and display_errors is off and no error_reporting. Check logs, find exactly at which one line your script crash, maybe it is class loading and so on.

Ask help in symfony maillist, it is better place for such questions.

**Comment by KuenzelIT** [comment]
I didn't explain it right: everything is working fine, the script runs completely. The command just doesn't get executed and there's no output.

**Comment by ewgRa** [comment]
According to WindowsPipes it is also create some files in temp_dir, like tempnam(sys_get_temp_dir(), 'sf_proc_stdout'). Maybe there is no rights for this.

Also another possibility, check Process.php start method near:
"if ('\\' === DIRECTORY_SEPARATOR && $this->enhanceWindowsCompatibility) {"
Your command line will be not as you expect if this is true for you. It will run $commandline = 'cmd /V:ON /E:ON /C "('.$commandline.')' . Just debug what is really Process run as commandLine.

> the script runs completely
Just to be sure. How you check this? Did you have "echo 'Finish';" at the end of the script and you have 'Finish' in output? Because there is can be exception and you suppress it somehow in your code or by your server settings.

I think better place to ask your question at symfony maillist.

**Comment by KuenzelIT** [comment]
You're right, the windows compatibility enhancement is the problem.

The complete command is:
```
cmd /V:ON /E:ON /C "(C:\MysqlDump\mysqldump --user="user" --password="password" --host="localhost" --port="3306" "db" > "C:\test/mysql.sql") 1>"C:\Windows\Temp\sf_E1C2.tmp" 2>"C:\Windows\Temp\sf_E1C3.tmp""
```
The problem is the missing permissions for the temp directory. So there are multiple solutions:

1) Giving the AppPool permissions for "C:\Windows\temp" directory. It seems like you need to take ownership first though, else you can't really change the permissions.

2) Another possiblity is to set the temp directory in php.ini to some other value and giving the AppPool permissions for that directory.
```
sys_temp_dir = "C:\someothertempdir"
```


3) Or just deactivate the Windows compatibility enhancement with 
```
$process->setEnhanceWindowsCompatibility(false)
```

Thank you so much for pointing me in the right direction! It took me quite some hours to figure this out.
