### ISSUE TITLE
[Intl] Date tests broken without intl extension, IntlDateFormatter

### ISSUE THREAD

**Issue by ewgRa** [symfony/symfony#15049]
When intl extension not installed, many tests that use IntlDateFormatter is broken. For example:

```
1) Symfony\Component\Validator\Tests\Constraints\RangeValidatorTest::testInvalidDatesCombinedMin with data set #0 (DateTime Object (...), 'Mar 20, 2013, 12:00 AM')
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 Symfony\Component\Validator\ConstraintViolation Object (
     'message' => null
     'messageTemplate' => 'myMinMessage'
     'parameters' => Array (
-        '{{ value }}' => 'Mar 20, 2013, 12:00 AM'
-        '{{ limit }}' => 'Mar 10, 2014, 12:00 AM'
+        '{{ value }}' => 'Mar 20, 2013 12:00 AM'
+        '{{ limit }}' => 'Mar 10, 2014 12:00 AM'
     )
     'plural' => null
     'root' => 'root'
     'propertyPath' => 'property.path'
     'invalidValue' => 'InvalidValue'
     'constraint' => Symfony\Component\Validator\Constraints\NotNull Object (...)
     'code' => 3
     'cause' => null
 )

```

When I install intl extension with ICU 52.1 and change getIcuStubVersion to my ICU version - tests passed without failures.

I write PR #15045 that fix it in my machine, but seems it broke tests that run on travis and I can't find reason why on travis native IntDateFormatter return no comma after year, but later in tests start returning with comma.

**Comment by iltar** [comment]
This is exactly the error I got running tests locally. There are around 70 failing tests because of this.

**Comment by ewgRa** [comment]
@iltar Can you test my PR? Is it testEqualWithNative fail for you when intl extension installed?
Which one ICU version you have?


Many developers haven't intl extension and when they run tests such many broken tests will be confuse them.

**Comment by iltar** [comment]
@ewgRa Sadly not within the upcoming week as I have a week off work and I cannot access my workstation from home.

**Comment by stof** [comment]
This is the reason why we have many tests being skipped when the ICU data of the Intl extension does not match the stub version data, because we write tests for the icu version implemented by the stub. However, it looks like these tests are missing the ``IntlTestHelper::requireIntl($this)`` call to ensure we have the ICU data at the version at which tests are written (and they should be written at the version implemented in stubs, which is not the case either).
the fix would be to add the missing check in these tests and update them for the ICU 51 data (you can disable intl and run tests against the stub implementation for that)
