### ISSUE TITLE
Organising translations in locale directories

### ISSUE THREAD

**Issue by ZeeCoder** [symfony/symfony#15059]
(I'm not sure I'm opening this issue at the right place, and if I'm not, please advise. :))

By default all the translation files have to be stored in `app/Resources/translations` named according to this convention: "\<domain\>.\<locale\>.\<loader\>"

But what I need is to collect translation files from locale folders, so for example, there would be an `en` folder inside `app/Resources/translations` where I would store translation files named "\<domain\>.yml".

I've read the docs, searched the net but found nothing useful.

Can it be done through listeners, or something like that?

**Comment by ewgRa** [comment]
Check http://symfony.com/doc/current/reference/dic_tags.html#translation-loader

Also better to ask such question at http://symfony.com/mailing-lists

**Comment by ZeeCoder** [comment]
Thanks, I will ask there next time. :)

I read that part of the docs, but a ` translation.loader` is just another file loader for a custom file extension, isn't it?
I don't want to add a new loader, since I'm using YML files, which have a default loader already.

I just want to store the files differently.

Or am I not getting something?

**Comment by jvasseur** [comment]
@ewgRa This doesn't solve the problem, loaders are here to allow loading different resource types and doesn't change how Symfony finds translation files.

Searching for translation files is done in the FrameworkBundle DI extension (https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L707) and isn't easily customizable.

@ZeeCoder you could try creating a compiler pass that mimic how the FrameworkExtension work but with your custom logic.

**Comment by ZeeCoder** [comment]
Thanks for your answer @jvasseur!
What do you mean by "compiler pass", I have no idea how to implement something like that. O.o

**Comment by ewgRa** [comment]
@jvasseur you are right. Also as I understand in this case will be broken debug:translation command, because in TranslationLoader also have finds code.

@ZeeCoder why you want to customize it in this way? There is no any pros, only cons.

> What do you mean by "compiler pass"

You can start here http://symfony.com/doc/current/cookbook/bundles/override.html#services-configuration and then go here http://symfony.com/doc/current/cookbook/service_container/compiler_passes.html

**Comment by ZeeCoder** [comment]
I have a workflow which includes [OneSky](https://www.oneskyapp.com).
I have wrote a command, which syncs down every translation file through it's API.
Now if I remember correctly, the API is not all that flexible, and I couldn't set it up so that the filenames would follow the Symfony pattern.

Since I originally used this little command in Silex apps - where I had bigger freedom regarding the translator service for obvious reasons -  it didn't even occur to me, that I wouldn't be able to tweak a Symfony app to handle this kind of situation.

*Also:* organising the translation files this way is not all that uncommon.
Imho it just "feels right" to have all the translation files under directories named after the locales, instead of just having every single domain file for every supported language in the same directory.

But putting that aside, I also prefer handling the files this way, since with this, I can download my translation files to a tmp directory and run a diff command between my local translation files, and the ones downloaded from OneSky, where translators could actively work on the project.

**Comment by ewgRa** [comment]
If we talking about support this easy on Symfony level, possible solution is at FrameworkExtension instead of 
```
list($domain, $locale, $format) = explode('.', $file->getBasename(), 3);
```
add something like translator.file_match_regexp option with named patterns locale, format, domain.
And Symfony will be support such functionality. Another question how hard to support such flexible way to keep translation files.

**Comment by ZeeCoder** [comment]
Where and how should I do that exactly?
I'm not familiar with the Symfony source code at such a low level I'm afraid.

**Comment by ewgRa** [comment]
Than for you compiler pass is better way. Try it as @jvasseur suggest.

**Comment by ZeeCoder** [comment]
For the time being I rewrote the synchronizing command, since that seemed far easier to achieve.

It's still not a good solution for me, but it's something I can roll with for now.

I appreciate the help nonetheless, thanks @ewgRa, @jvasseur. :)

**Comment by nalakapws** [comment]
Please add support for this feature.

**Comment by Flinsch** [comment]
**edit**: I mistakenly thought it could work this way (see below). I'll leave it here for documentation purposes. But as @stof correctly pointed out, this isn't a real solution.

---

In one of our projects we have around 90 domains that we wanted to have organized by locale in order to improve the overview a little. As a workaround (which can also be viewed as regular feature usage) we did it like this:
```
# config/packages/translation.yaml
framework:
    # ...
    translator:
        default_path: '%kernel.project_dir%/translations/%locale%'
        # ...
```
So we just set the (default) translation files path to include the locale. This is a bit redundant because the files themselves already carry this information, but it fulfills our requirement. For us, it works like a charm.

**Comment by stof** [comment]
@Flinsch this will only load translations for your default locale and not for other locales, which probably defeats the goal of translating (as you will effectively behave as if other locales are not available)

**Comment by Flinsch** [comment]
@stof Oh, really? I wasn't aware of that. Damn, then we'll also need another approach soon. Thank you very much for your hint. :(

**Comment by stof** [comment]
Well, what you're doing is `default_path: '%kernel.project_dir%/translations/en' (assuming the your `locale` DI parameter has the value `en`).
The DI parameter cannot contain the current locale, unless you redefine it and clear the cache for each request...

**Comment by Flinsch** [comment]
Yes, that makes sense to me now too. Sorry for the then quite pointless "contribution". That would be (another) example of how _not_ to do it then.

**Comment by Flinsch** [comment]
Just to close the loop with regard to my previous "solution", which could not work at all, this is how we have now solved it:
```
# config/packages/translation.yaml
framework:
    # ...
    translator:
        paths:
          - '%kernel.project_dir%/translations/de'
          - '%kernel.project_dir%/translations/en'
        # ...
```
Actually that easy. This feature seems to have been around for a while (though not yet in 2015, but soon after). I don't know to what extent this would still contribute to this thread or even the initial issue, and I'm sorry if I've got something up again that might be totally obvious by now. But we weren't even aware of this feature which has now achieved the desired effect for us, without any workarounds. I'm a little ashamed because "default path" already indicates that there might be further paths that are not the default ones. However, maybe it will help others as well. Peace out.

**Comment by stof** [comment]
@Flinsch In your case, you still need to name the files `messages.en.yaml` and `messages.de.yaml`. And nothing forbids you to put the `.de.yaml` file inside the `translations/en` folder. The locale of the file is still controlled by the file name rather than the folder name. you could name you folders `translations/foo` and `translations/bar` if you want.

**Comment by Flinsch** [comment]
@stof Yes, I know. For us it was primarily a matter of keeping the files of different locales in separate subdirectories in order to organize them at least a little. That the subdirectories then are called, for example, "de" and the files again, for example, "messages.de.yaml" is redundant in terms of the coding of the locale, that's true, and an inattentive developer could create inconsistent directory-file name constellations, that's true, too. But that doesn't bother us. We are now super satisfied with our "new" solution. Nevertheless, thank you very much for pointing out.

**Comment by Justinas-Jurciukonis** [comment]
We had similar problem. I have written compiler pass that dynamically gathers files and injects resources into default translator. All of our files are named `/messages/{locale}/general.json`

```yaml
# config/packages/translation.yaml
framework:
    default_locale: en
    translator:
        default_path: '%app.translation_dir%'
```


```php
<?php

declare(strict_types=1);

namespace App\DependencyInjection\CompilerPass;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Translation\MessageCatalogueInterface;

class TranslationCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $translator = $container->findDefinition('translator.default');
        $translationsDir = $container->getParameterBag()->resolveValue('%app.translation_dir%');

        $finder = Finder::create()
            ->files()
            ->in($translationsDir)
            ->name('general.*');

        foreach ($finder as $file) {
            $translator->addMethodCall(
                'addResource',
                [
                    $file->getExtension(),
                    $file->getRealPath(),
                    basename($file->getPath()),
                    'messages' . MessageCatalogueInterface::INTL_DOMAIN_SUFFIX,
                ]
            );
        }
    }
}
```
