### ISSUE TITLE
[Translation] Translation can truncate messages for constraints

### ISSUE THREAD

**Issue by ahuemmer** [symfony/symfony#15075]
Using a `Length` constraint with a colon (`:`) in one of the messages (`minMessage`, `maxMessage` or `exactMessage`), it seems that everything in front of the colon is truncated during processing:

```PHP
class MyType extends AbstractType {
	public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('text1', 'text', array('constraints' => new Assert\Length(array(
                    'min' => '4',
                    'max' => '100',
                    'minMessage' => 'Error: Text too short.',
                    'maxMessage' => 'Error: Text too long. Allowed length: 100 chars.',
                ))));
	}
}
```

The `Error:` will disappear if the constraint message is shown. Notice that only the first colon is truncated, so the `maxMessage` would still show the part after `Error:` though there's a second one in it.

I tracked this down to the `chose` method of the `Symfony\Component\Translation\MessageSelector` class, where a regex is evaluated removing the part before the first colon.

Yet, I didn't find an elegant way (or a hint in the documentation) to work around this issue.

**Comment by aitboudad** [comment]
Hi @ahuemmer  thank you for reporting this issue, 
I think it's an expected behavior, the message pluralization in translator  allow to optionally "tag" each message (The tags any descriptive string that ends with a colon (:)) for making the translations more clear.

For more details see: http://symfony.com/doc/current/components/translation/usage.html#pluralization
To make work your example just add an interval pluralization at the beginning of the message:

```
[1, +Inf[ Error: There are no apple
```

**Comment by iget-master** [comment]
Though this behavior is expected, it should have an oficial way to escape it!

Maybe allow to escape the `:` character someway!

My workarround is prefix this kind of messages with an tag, but isn't clean enough!

**Comment by vlakoff** [comment]
Agree with this. I can't think of a really great solution, but some way should be offered to let use a message like `lorem: ipsum`.
