### ISSUE TITLE
.htaccess file turns POST request into GET request

### ISSUE THREAD

**Issue by thornycrackers** [symfony/symfony#15229]
I'll provide a link to my Stack Overflow question if anyone is interested in more details. To sum it up I'm using postman to send POST requests to **app.php/myroute/login** which are converted into GET requests. If I post to just **/myroute/login** everything works fine. I post to the original url but move the .htaccess file and xdebug shows the method as being post. I don't think many people will access the application through app.php so I would say this is very low priority but it gave me a bit of trouble, I was accessing through app_dev.php and decided to remove _dev which lead me to this. People may come across this though in the future so I figured it would be good to submit it.

[My Stack Overflow question](http://stackoverflow.com/questions/31280841/symfony2-app-php-receiving-post-request-as-get-app-dev-php-works-fine/31281297#31281297)

**Comment by Tobion** [comment]
The htaccess https://github.com/symfony/symfony-standard/blob/2.8/web/.htaccess#L48 redirects requests from /app.php/* to the path without app.php because app.php in the path should not be accessible to remove duplicate content sites. It's true that this is also done for POST, which will of course results in a redirect with GET.

The only alternative we had would be to return an error response for methods != GET to app.php. Or not do the redirect for methods != GET. Feel free to make a PR. But the correct repository for this thing is https://github.com/symfony/symfony-standard so I'm closing.
