### ISSUE TITLE
Use random_bytes() in Symfony

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#15239]
As of PHP 7.0, `random_bytes` "generates cryptographically secure pseudo-random bytes". We are doing something similar in `Symfony\Core\Component\Security\Util\SecureRandom::nextBytes()` as we should probably use the build-in function for PHP7.

Also, @paragonie-scott maintains paragonie/random_compat, a compat lib for PHP 5.x, which we can use for non-PHP7 installations.

ping @symfony/deciders

**Comment by dunglas** [comment]
:+1:

**Comment by weaverryan** [comment]
So for 5.x users, they would probably get an exception to install the `paragonie/random_compat` library?

What does this affect? At a quick check, looks like `UserPasswordEncoderCommand`, `UriSafeTokenGenerator` and `PersistentTokenBasedRememberMeServices`, which don't seem that huge of a deal (though I'm not sure exactly where `UriSafeTokenGenerator` is used - if it's in forms, that would mean this is a requirement for a lot more users.

But I like the idea - I was just looking at an old issue the other day talking about properly falling back in in `nextBytes()` in some edge case, etc etc. It would be better to not deal with those things.

**Comment by fabpot** [comment]
We did a similar thing with `ircmaxell/password-compat` in the past.

**Comment by weaverryan** [comment]
Good point - and I at least personally never head any complications/complaints about this. :+1:

**Comment by phansys** [comment]
I think these libraries should only check if the environment has the native support for those functions and just bypass the task if that is the situation, in the same way that [```ircmaxell/password-compat```](https://github.com/ircmaxell/password_compat/blob/master/lib/password.php#L12) does. Otherwise, if we mark this as a conflict, the usage of these dependencies could be very problematic in envs with different capabilities.

**Comment by xabbuh** [comment]
Switching to this library when it has proven to be good (however we judge that) sounds like a good idea to. Though this means that we will either have to add it as a dependency or that we will need to be clear about the new dependency for PHP 5.x users when they update their Symfony version.

**Comment by weaverryan** [comment]
@xabbuh agreed - it wouldn't be a hard dep, and we could deprecate the use of the old functionality (before having a version where it requires you to have that lib installed). Anyways, those sound like implementation details, so I think we're still seeing mostly +1's for this being available for someone to do.

**Comment by xabbuh** [comment]
@weaverryan Well, we need to decide how we actually do the change, don't we? When using these functions in core code, we would need to depend on the third-party library. And we could only deprecate some functions if we provided alternatives (which we use in our own code so in turn we must use the new library again, right?).

**Comment by weaverryan** [comment]
@xabbuh The alternatives that we use during deprecation would simple be to use the existing code we have inside `nextBytes()`, right? So, look for the PHP7 function, else look for the presence of the 3rd library and use its code, else use the code we have now (but throw a deprecation warning).

**Comment by xabbuh** [comment]
@weaverryan Yeah, of course you're right. Actually looking for the PHP7/for the presence of the library would even be done in the same step (calling `function_exists()` I assume).

**Comment by paragonie-scott** [comment]
The random_compat does the function_exists() checks internally. If
random_bytes() and random_int() exist (i.e. PHP 7), the lib will not
attempt to redefine them. So naively loading it should be safe on any
functioning platform.

random_compat will select the most optimal backend available for the
current platform. Priority is given to reliably secure CSPRNGs:
/dev/arandom, /dev/urandom, mcrypt, CAPICOM, then openssl.

Additionally, this selection is done once per page lad rather than once per
function call.

I think given the level of engagement we've managed to achieve from the
community at large, a stable v1.0.0 might be ready as soon as next Monday.
(Seriously. There are some amazing people in the PHP community.)

After that point, I'll be sure to let everyone know so you can, at the
time, make a very informed decision about what the library does.

If you know any security folks whom I haven't already publicly asked to
critique random_compat, please do send them my way.

**Comment by weaverryan** [comment]
@paragonie-scott thanks for chiming in - very helpful! You've done much of the work for us then :).

So again, I think this has a :+1: for someone to get a pull request going at least. I don't want to have too much conversation here and cloud that this is actionable.

Cheers!

**Comment by jpauli** [comment]
One could also detect and use openssl_random_pseudo_bytes() if available.
Many PHP installations are bound to OpenSSL, if not, PHP can't open https:// URLs for example, so many PHP installations provide OpenSSL nowadays.

**Comment by xabbuh** [comment]
@jpauli If I don't misunderstand @ircmaxell, [he strongly argues against doing that](https://twitter.com/ircmaxell/status/618865310549057536):

> Dear programming language maintainers, please do not rely on openssl for random numbers. Use the OS, that's what it's designed for.

**Comment by paragonie-scott** [comment]
Update: v1.0.0 is now available for use.

https://github.com/paragonie/random_compat/releases/tag/v1.0.0
