### ISSUE TITLE
[Question] [Translator] Why not add to explicit rules list?

### ISSUE THREAD

**Issue by shehi** [symfony/symfony#15315]
The following line in the code:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/MessageSelector.php#L63

adds translation bits such as: 

```$bit = "guest: Welcome|registered: Welcome, :name!";```

to standard rules. Why not capture the leading ```guest:``` part and add that bit to explicit rules? That way, one could easily add text-based modifiers for, let's say gender-specific translation or any other type of translation string.

**Comment by adamziel** [comment]
These are "tags" and are described in here:

http://symfony.com/doc/current/components/translation/usage.html#pluralization

    The tags are really only hints for translators and don't affect the logic used to
    determine which plural form to use. The tags can be any descriptive string that
    ends with a colon (:). The tags also do not need to be the same in the original
    message as in the translated one.

You probably thought of it as "context" used in other gettext-based translation frameworks e.g one in django:
https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#contextual-markers
https://www.gnu.org/software/gettext/manual/html_node/Contexts.html

This is more complicated than it seems, for example this would be a major BC break. Okay, but there could be a different syntax. Sure, but now you need to change all the `@api` classes in order to add a "context" argument. And twig filters/functions. And there are probably many other dependencies.

Now, there is a different approach. Instead of translating words, you may translate keywords as described in here:
http://symfony.com/doc/current/components/translation/usage.html#creating-translations

this way your "context" is the message key. You simply write:

```yml
guest:
    welcome: "Welcome"
registered:
    welcome: "Welcome, :name!"
```

and translate `guest.welcome` or `registered.welcome`

**Comment by shehi** [comment]
Yea, I know there would be BC implications since it's a grand change to API and lib. And your approach indeed sounds reasonable. Instead of chasing different types of modifiers and later passing them as arguments to ```transChoice()```, why don't I just create different nested keyword-based translations? The result will be the same: for the former case the second argument determining the modifier will differ, for the latter case the translation keyword will differ.

Sometimes it's hard to think simple. "Simplicity is the ultimate sophistication" :) Thanks.

**Comment by jakzal** [comment]
@shehi do you think we can close this issue?

**Comment by shehi** [comment]
Yes, yes, of course. Thanks for asking @jakzal :)
