### ISSUE TITLE
[DX] WDT to long 

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony#15348]
Hi all,

It could be very pleasant if this item in the WebDebugToolbar was much smaller, so the bar will be rendered in one line.

![wdt_to_long](https://cloud.githubusercontent.com/assets/1358361/8850210/747f076a-3146-11e5-9cba-9a1972163fc6.jpg)

FYI I am on 13' display

Thank you,

**Comment by javiereguiluz** [comment]
You are right!

In [the new toolbar](https://github.com/symfony/symfony/pull/15160) that will (hopefully) be included in 2.8 and 3.0, most of these space problems will be solved. For the existing toolbar, I doubt we'll make any change because it's a lot of work and we already updated the toolbar for newer versions.

**Comment by javiereguiluz** [comment]
Since the new toolbar has been merged, this issue can be closed as "fixed".

**Comment by 94noni** [comment]
Yes indeed 
Btw the new toolbar rox !

-- 
Antoine Makdessi
Envoyé de mon iPhone
