### ISSUE TITLE
[DX] Summarize form errors for debugging

### ISSUE THREAD

**Issue by alex-ception** [symfony/symfony#15349]
I'm currently debugging a form (including other forms), I consider the getErrors method counter intuitive when debugging a form. Sometimes it could be really useful to have all error of the form (and children form) as a string (or something less complex than now).

It could be really productive to have them with a method called getErrorsAsString (following the convention of getTraceAsString of Exceptions) returning errors as string, or something more generic and versatile with an array of key, value (keys being fields, and values being errors) with a method named getErrorsAsArray ?

It could not only be useful for debugging, but in others cases such as API oriented projects, but in my case I was on an HTML form.

Useful, in my opinion, but maybe I'm forgetting something though, an undiscovered method maybe ?

**Comment by stof** [comment]
There is a deprecated function ``getErrorsAsString`` https://github.com/symfony/symfony/blob/49959000fc1cbec68a34f69bc5521cf74a5737ff/src/Symfony/Component/Form/Form.php#L849

and ``getErrors`` allows to get all errors of the form by changing the values of arguments (which is exactly what the deprecated ``getErrorsAsString`` method does btw).

For API-oriented projects, you would not want to return them as a string anyway, but as a structured format to be usable, which is also possible thanks to ``getErrors`` giving you all info.

And btw, for debugging purposes, you can also use the form panel of the webprofiler.

I'm closing this issue as the feature is already available since 2.5
