### ISSUE TITLE
File input should not use html5 required tag

### ISSUE THREAD

**Issue by pinoniq** [symfony/symfony#15344]
version: 2.7.1

I have a Form that adds a required image:

    $builder->add('picture', 'file', array(
            'required' => true,
    ));

The problem is that this get's rendered as

    <input type="file" required="required" />

When we now use this form to edit an existing entity that allready has a file. We are unable to submit the form because of the `required="required"` tag, unless we upload a new file

P.S. Bug doesn't appear IE8 however ^^

**Comment by Ascarius** [comment]
That's actually the only purpose of the `required` option.

Note that this option will not result in server-side validation : [See "The required option"](http://symfony.com/doc/current/book/forms.html#field-type-options)

You should probably use validation groups and `NotNull` constraint instead of `required`.

**Comment by xabbuh** [comment]
As @Ascarius said that's expected behaviour. So I'm going to close here. Thanks anyway for reporting the issue @pinoniq even if it turned out to not to be one. ;)

**Comment by pinoniq** [comment]
Required itself behaves as expected. but if the only impact is frontend. It should simply not have it's own value but just be part of attr array. no? Kind of confuses imho.
