### ISSUE TITLE
[RFC] Tweak container optimizations in debug mode

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#15405]
### Context

Most of our performance efforts are dedicated to improve Symfony performance on production. However, as developers, we spend most of our time executing Symfony on `dev` environment. If we could make Symfony fast in this environment too, we'd improve the perceived performance of Symfony.

### Proposal

I was playing with the container and I realized that in the `dev` environment Symfony performs a lot of optimizations:

```
# app/cache/dev/appDevDebugProjectContainerCompiler.log
Removed service "doctrine.dbal.connection.event_manager"; reason: abstract
Removed service "doctrine.orm.security.user.provider"; reason: abstract
Removed service "templating.loader.cache"; reason: unused
Removed service "annotations.cached_reader"; reason: unused
# ...
```

I think that some of those optimizations only make sense in production. Removing unused services? Why? Give me the *damn* container as soon as possible and don't overoptimize it!!

So I did a quick test disabling some compiler passes:

```php
// Symfony\Component\DependencyInjection\Compiler\PassConfig
        $this->removingPasses = array(
            // new RemovePrivateAliasesPass(),
            new RemoveAbstractDefinitionsPass(),
            new ReplaceAliasByActualDefinitionPass(),
            new RepeatedPass(array(
                new AnalyzeServiceReferencesPass(),
                // new InlineServiceDefinitionsPass(),
                // new AnalyzeServiceReferencesPass(),
                new RemoveUnusedDefinitionsPass(),
            )),
            // new CheckExceptionOnInvalidReferenceBehaviorPass(),
        );
```

I'm sure that we could remove more passes but I got some errors if I disabled more passes.

### Results

For the tests I used the 0.4.0 version of the Symfony Demo application and the Blackfire Profiler to analyze the `/en/blog/posts/morbi-tempus-commodo-mattis` page.

-----

**First test**: in this scenario, I execute `rm -fr app/cache/*`, load the page in the browser to regenerate the cache and profile the application in `dev` **without** making any change in any file.

The performance improvement is negligible, but nonetheless the application saved some function calls:

![test_1](https://cloud.githubusercontent.com/assets/73419/8968542/366888aa-363e-11e5-8c95-e7d05e56b72e.png)

-----

**Second test**: in this scenario, I execute `rm -fr app/cache*`, load the page in the browser to regenerate the cache and then I make one single change in the `app/config/services.yml` file.

In this case, the performance improvement is very noticeable (-27% Wall Time, +10% Memory) and the function calls saved are significant:

![test_2_functions](https://cloud.githubusercontent.com/assets/73419/8968645/da595930-363e-11e5-9097-83c1e58f914a.png)

And the call graph clearly shows the nodes where the improvement was achieved:

![test_2_call_graph](https://cloud.githubusercontent.com/assets/73419/8968656/e887410c-363e-11e5-85e9-a92810cb4c18.png)

The improvement is so significant that I repeated the test several times and I always got the same result. However, it may be possible that I made some error that invalidates the results.
 
### Request for Comments

All the above is just a quick-and-dirty test to prove an hypothesis: disabling some optimizations will increase Symfony performance in `dev` environment.

I'd like to ask to the Symfony community: is this a plausible idea to improve Symfony performance? Do you think it's absurd? What side-effects will be introduced for disabling these optimizations? Can we apply this idea to other components too? (Twig for example also optimizes template compilation)

**Comment by fabpot** [comment]
Improving performance is always a good idea, but I'm going to highlight one side-effect: the divergence between debug and non-debug environments. In Symfony2, we've tried to keep all environments as close as possible to avoid problems that you have in prod but not in dev because of the differences between the two. And what you've done here falls exactly in this category: yes, doing less things in dev make things faster but it makes the container different than the one in prod which means potentially a different behavior with bugs that can only be detected in prod.

So, I'm all in favor of trying to optimize performance both in prod and dev, but we need to be very careful about the consistency of both envs.

**Comment by stof** [comment]
and here is the case where disabling this optimization can hide bugs: if you have a private service which gets inlined and removed in prod and you get it dynamically (through ``Container::get``) by mistake, it would now work in dev and break only the day you deploy to prod.

And there is another side effect. Inlined service definitions allow for circular references in some cases which would not work anymore in case you don't inline the services.

And removing the ``CheckExceptionOnInvalidReferenceBehaviorPass`` means that you won't be notified anymore when you make a mistake in your service definition, referencing a non-existent service (typo in the id), so it actually hurts debugging too. This compiler pass is precisely about failing fast for invalid configurations rather than failing at runtime when retrieving the impacted service (which may happen only in some particular requests)

**Comment by javiereguiluz** [comment]
OK. Closing this proposal because the explained side-effects overcome any potential performance gain.

**Comment by stof** [comment]
@javiereguiluz it may be worth profiling the way these optimizations are applied to optimize them though.
for instance, saving 942.3 calls to ``strtolower`` here (btw, please explain me how this number could be a float) means we could probably optimize the way we lowercase ids to make sure we don't make unnecessary calls in the ContainerBuilder. Symfony 2.7 optimized the ``Container::get`` method to optimize the runtime usage on this point, but we might have some places where the container building methods could be optimized.
