### ISSUE TITLE
DOMCrawler plain text

### ISSUE THREAD

**Issue by gagvirus** [symfony/symfony#15504]
I am using Symfony's DomCrawler to fetch an information from website.
In one of the pages there is a text including non-html-encoded attributes like following :

`<a href="some-url.html">Lorem ipsum <<dolor sit>> amet </a>`
And when I try to crawl the text from the a tag using the filterXPath method I get Lorem ipsum <, because as I suppose it behaves to symbols like broken html tags and simply ignores them.

Also, when i try to use `$node->filterXPath('my-xpath/a')->html()`, I also get broken html like following example :

`<a href="some-url.html">Lorem ipsum &gt;</a>`
So, my question is if there is any way to get the "plain" text out of the node ?

**Comment by stof** [comment]
The loading of the DOM is handled by PHP itself. It is not implemented in Symfony.

I guess that libxml does not like your "non encoded node". But anyway, you should report it to the website (or fix it if it is your own) because it is indeed invalid HTML, so the parser failing to read it is not totally unexpected.
On a side node, this could even indicate a CSS issue depending of where this non-encoded content is coming from.

**Comment by jakzal** [comment]
The issue indeed lies in the way PHP handles the documents:

```php
libxml_use_internal_errors(true);
libxml_disable_entity_loader(true);

$doc = new \DOMDocument();
$doc->loadHTML('<a href="some-url.html">Lorem ipsum <<dolor sit>> amet </a>');
echo $doc->saveHTML();
```

Output:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><a href="some-url.html">Lorem ipsum &gt; amet </a></body></html>
```

Note that PHP will emit a warning by default, but Crawler will silence them. This is sensible as most of html out there is invalid. 

There's not much we can do about it. We could introduce a strict mode that would throw exceptions on invalid content, but I think it would be of little value given that it's very easy to produce an invalid html.

**Comment by gagvirus** [comment]
Thanks @stof @jakzal
