### ISSUE TITLE
Installation documentation needs to be fixed

### ISSUE THREAD

**Issue by JVerstry** [symfony/symfony#15559]
Hi, while going through the installation documentation (https://symfony.com/doc/current/book/installation.html) to create a symfony application, I ran into an issue I have reported on stackoverflow (http://stackoverflow.com/questions/32027702/symfony-error-no-route-found-for-get-app-example).

It needs a small fix at the bottom of the page. The  http://localhost:8000/app/example link should be replaced with  http://localhost:8000/.

**Comment by javiereguiluz** [comment]
@JVerstry thakns for reporting this issue! You are right and we're going to fix it very soon. However, since this is a documentation issue, could you please close this issue and open a new one in https://github.com/symfony/symfony-docs ? Sorry for the trouble, but `symfony-docs` is the repository where we track everything related to Symfony documentation. Thanks!
