### ISSUE TITLE
[Form][2.7] Incorrect/invalid select tag is generated if choices have duplicate content

### ISSUE THREAD

**Issue by CriticalFix** [symfony/symfony#15606]
Incorrect/invalid select tag is generated if choices have duplicate content ('Category 4').
```php
$f = $this->formFactory->createNamedBuilder('category', 'form')
    ->add('parent_category', 'choice', array(
        'label'   => 'Name',
        'choices' => array(
            '1' => 'Category 1',
            '2' => 'Category 4',
            '3' => 'Category 3',
            '4' => 'Category 4',
            '5' => 'Category 5'
        )
    ))
    ->add('save', 'submit', array(
        'label' => 'Save'
    ))
    ->getForm();
```

```html
<select>
    <option value="1" >Category 1</option>
    <option value="4" >Category 4</option>
    <option value="3" >Category 3</option>
    <option value="5" >Category 5</option>
</select>
```
Where is option with value="2"?

**Comment by malarzm** [comment]
For the record this is also happening when using expanded choice list

**Comment by georaldc** [comment]
Might have something to do with the Symfony\Component\Form\ChoiceList\ArrayChoiceList::flatten() method, where the choice labels themselves are used as keys for the $structuredValues array (thus preventing duplicates).

Happens in Symfony 2.8 as well

**Comment by YetiCGN** [comment]
+1

This is preventing upgrading to 2.7 on an app of ours. I have suspected duplicate content being the culprit, this is BC breaking in any case!

I have created a minimal test case fwiw: https://github.com/YetiCGN/symfony-issue-15606-testcase

**Comment by YetiCGN** [comment]
> Might have something to do with the Symfony\Component\Form\ChoiceList\ArrayKeyChoiceList::flatten() method, where the choice labels themselves are used as keys for the $structuredValues array (thus preventing duplicates).

I have covered that part with a test, it succeeds. This happens somehow in createView, I suspect a ViewTransformer. Creating a test case for that right now.

**Comment by Tobion** [comment]
Related to #15061

**Comment by YetiCGN** [comment]
Here is what I've learned so far:

1. The group_by default, calling `self::flipRecursive($options['choices'])` uses values as keys, so duplicates are removed. Setting group_by to `array_keys($choices)` solves this part.
2. The [DefaultChoiceListFactory](https://github.com/symfony/form/blob/master/ChoiceList/Factory/DefaultChoiceListFactory.php#L155) uses values as keys, so duplicates are removed.
3. Currently the only solution for me is to workaround by detecting duplicates and adding spaces programmatically. We need categories with the same name as the ChoiceType used displays hierarchical categories and although they have the same name, the database ID is different and their differentiation is done by context, i.e. after which parent category it is listed. So there is a use case for NOT filtering out duplicate choice values.
4. The SimpleChoiceList is still available, which was used in 2.3 and does not show this bug, but I don't know how to force it from the FormBuilder. In any case, going forward to 3.0 we would like to use duplicate values for ChoiceType choices, regardless. ;)
5. It would be BC-breaking from 2.7.5 to 2.7.x (once it's solved) for people relying on duplicates being removed, but I think the BC break from 2.3 or 2.6 is bigger. They should filter duplicates before passing to a ChoiceType anyway, so if they suddenly appear then the user code should be fixed. ;)

**Comment by YetiCGN** [comment]
Actually, the real issue seems to be contained in the ChoiceType:
An ArrayKeyChoiceList is used by the factory, because the ChoiceType says so. If an ArrayChoiceList is used, everything is fine. The corresponding code is in [ChoiceType.php line 281](https://github.com/symfony/form/blob/master/Extension/Core/Type/ChoiceType.php#L281).

Only if the option `choices_as_values` is set will it use the ArrayChoiceList by calling `createListFromChoices` instead of `createListFromFlippedChoices`. 

This is hard to fix, because we would need a new option that is immediately deprecated but also active by default to solve this. Or the ChoiceType should fall back to the deprecated SimpleChoiceList when called with a `choices` option and for 3.0 we would need a differently named array key.

@webmozart What are your thoughts on this?

**Comment by jaugustin** [comment]
We have the same BC break in our application migrated from 2.3.x => 2.7.2 

There is a lot of use case where you can't delete duplicate based on label

**Comment by malarzm** [comment]
Since there's still no fix here's how we tackled the problem (ugly, yes, but works): in affected forms we append label with object's id like 'UNIQUE:Id' and later strip / UNIQUE:.+$/ from label before rendering it (prefix is at your discretion, we use MongoId so it's quite easy to not strip "real" part of label and we're even omitting prefix). So in general append something unique to label and strip it in Twig later :baby:

**Comment by ewgRa** [comment]
Same for me.

We use choices like this

        30   => 'Bundle incl. %s products for <strong>%s</strong>',
        20   => 'Bundle incl. %s products for <strong>%s</strong>',

and now it is broken.

I think it can be fixed in DefaultChoiceListFactory::addChoiceViewsGroupedBy. Instead of call it with $list->getStructuredValues() it must be called with $list->getOriginalValues()
and also in addChoiceViewsGroupedBy value can't be array also as I don't see reason why this private method is static.

I will prepare PR, will see if it will be work.

**Comment by ewgRa** [comment]
Pull request done.

**Comment by Jean85** [comment]
+1
I'm having the same bug, in 2.7.5.

**Comment by peelandsee** [comment]
same problem here,
BC break upgrading from 2.3.
thanks for reporting.

**Comment by webmozart** [comment]
This is fixed in the referenced PR. Does the fix work for you?
