### ISSUE TITLE
RBAC

### ISSUE THREAD

**Issue by sashaaro** [symfony/symfony#15705]
Hi! Why didn't you include familiar RBAC(Role based access control) in security component along with ACL like Zend 2, Yii. Something like https://github.com/Sylius/Rbac . However possible to reach it through Voters?? Thank you, I sorry for my poor English

**Comment by jakzal** [comment]
Since this feature already exists as a 3rd party bundle, there's no need to include it in the core framework. Note that we've actually extracted the ACL part to its own component. In most cases voters do the job very well and there's no need for ACL. Therefore it's better to focus development efforts on other parts of the framework. See #14718 and #15013 for more details.
