### ISSUE TITLE
Security login redirect to fragment (using ESI for example)

### ISSUE THREAD

**Issue by nyroDev** [symfony/symfony#15712]
The login page use a global layout, which includes fragment using ESI (or SSI).
When the login success, the redirect is made to the internal fragment URI.

After a little search on it, my guess is because the fragment URI is catched in 
**Symfony\Component\Security\Http\Firewall\ExceptionListener**
as normal URL, and is then saved in session on the *setTargetPath* function here:

        if ($request->hasSession() && $request->isMethodSafe() && !$request->isXmlHttpRequest()) {
            $request->getSession()->set('_security.'.$this->providerKey.'.target_path', $request->getUri());
        }

Adding a test to check if the URI is a fragment might do the trick, but I may missing some points here.

**Comment by jakzal** [comment]
In order for this to happen the exception listener would need to be called for the framgment URL. Since your fragment URL is embedded on a login page which doesn't require users to be authenticated, I don't see how this could happen.

Could you please provide a fork of standard edition with this issue reproduced on a new branch?

**Comment by xabbuh** [comment]
ping @nyroDev :)

**Comment by xabbuh** [comment]
closing due to the lack of feedback

@nyroDev Please feel free to comment if you can provide more information and we can consider to reopen then.
