### ISSUE TITLE
[Form] Check if DataTransformer is added twice

### ISSUE THREAD

**Issue by Rvanlaak** [symfony/symfony#15752]
The `getParent` function of `FormType` nicely takes care of inheritance. When a custom type is both using `getParent` and extends another type, this could mess up the `DataTransformer`.

In case a type is extended, of which the parent does add a `DataTransformer` in the `buildForm` method, and the child did not implement `buildForm` itself but has implemented `getParent`, the `DataTransformer` is added twice. This will result into an error on submit, because the second time the transformer is executed on the already transformed value.

```php

class ChildType extends BaseType
{
    // ... rest of implementation is omitted, but implementation lacks `buildForm`

    public function getParent()
    {
        return 'parent_type';
    }
}


class BaseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer($this->injectedModelTransformer);
    }

    public function getName()
    {
        return 'base_type';
     }
}

```
This can be solved in two ways, by omitting `ChildType::getParent` or by implementing an empty `ChildType::buildForm`.

What I'd like to propose is to add a "already was added" check on `addModelTransformer` and `addViewTransformer`. The same transformer should never be added twice right?

A condition of this check could be to first determine if `buildForm` is implemented in the case that `getParent` and `getName` are implemented (this excludes the `AbstractType`). `FormTypeInterface` does enforces `getName`, but in this case that function already was implemented in the `BaseType`.

**Comment by jaytaph** [comment]
Omitting the `ChildType::getParent()` would not only affect the build process, but also the render process (`buildView()` and `finishView()`, as well as any inherited options). This may cause problems if you are depending on different block names inside your template views. Plus, there is also another extension point, namely the form type extensions, which could also "mess" things up I reckon.

Checking the transformers will be difficult though. There are some more generic transformers available, like the  `ReversedTransformer()`, which could be added twice (although not likely). 

I'd suggest in this case to implement an empty `buildForm()`. Because the form types itself uses its own inheritance model (with `getParent()`), i'd would say trying to minimize usage through the OO would be recommended. (The `AbstractType` class that most form types extend, is nothing more than some simple boilerplate and doesn't contain any real logic).

**Comment by Rvanlaak** [comment]
Agree with you on implementing an empty `buildForm()` but my point was that a parent type could also implement it. So then the parent's method is executed twice.

Lets take the Sylius [`CouponToCodeType`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PromotionBundle/Form/Type/CouponToCodeType.php) as example, which does call `addModelTransformer` in `buildForm`.

In case you extend it as I've explained above in the `ChildType`, and do not exactly know what's going on, this will lead to some weird behaviour with the transformers.

Do there really are transformers you want to have added twice?

**Comment by jaytaph** [comment]
I think the issue is not so much directly with transformers, but with having multiple calls to the same method. The issue also arise for other calls like the `buildView()` etc,  and it does not only occur with data transformers: what about `buildForm()` methods adding other fields, or event handlers etc. 

Solving this will be very hard to do, it's not a simple "set a flag if a method is called and skip when the flag is set later on". But I'm sure others will have better and/or smarter idea's on how to maybe solve this. I would suggest that not mixing both inheritance systems would be the best strategy here.

**Comment by stof** [comment]
@Rvanlaak the question is why you are using PHP inheritance between your form types.

**Comment by Rvanlaak** [comment]
The inheritance was a result of [the Sylius docs](http://docs.sylius.org/en/latest/bundles/general/overriding_forms.html), and adding the `getParent` function was something I shouldn't have done. But debugging it let me think about the "double" inheritance system, and how it could be confusing for this scenario. 

It indeed isn't specific for the transformers @jaytaph , but debating the entire form inheritance system seemed a bit to much. So, if this could be prevented for future developers that would be nice. Maybe this issue better can be seen as a DX issue.

**Comment by stof** [comment]
@Rvanlaak preventing double registration of transformers won't be done IMO. It would add overhead just to detect a case which can happen only for invalid usage of the component, and would still not detect this invalid usage.

I think the Symlius doc should be updated to advice using the form hierarchy rather than PHP inheritance though. It is a much better way to extend things (PHP inheritance is generally the worse extension point btw)

**Comment by xabbuh** [comment]
I think we should close here and rather add something to the docs explaining why you should avoid to use PHP inheritance for form types.
