### ISSUE TITLE
Upgrade php 5.6.13 and Symfony 2.1.7

### ISSUE THREAD

**Issue by xuanhau** [symfony/symfony#15780]
Dear all,
I have proplem, my current project using php 5.5.12 and symfony 2.1.7 but when i upgrade to php 5.6.13 then project not working. please help me resolve this proplem! 
Error content:
public function __construct($dsn, $user = null, $password = null, array $options = null) 
    { 
        parent::__construct($dsn, $user, $password, $options); 
        $this->setAttribute(PDO::ATTR_STATEMENT_CLASS, array('Doctrine\DBAL\Driver\PDOStatement', array())); 
        $this->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION); 
    } 
Thanks!

**Comment by javiereguiluz** [comment]
@xuanhau this GitHub repository is only used to report Symfony bugs. At this point we don't know if your issue is indeed a Symfony bug, so you should use first any of the official Symfony support alternatives: Stack Overflow or IRC, as explained in [symfony.com/support](http://symfony.com/support) Thanks!
