### ISSUE TITLE
SymfonyStyleTest is failing when being run from a small-width terminal

### ISSUE THREAD

**Issue by stof** [symfony/symfony#15909]
The test should force the terminal width in the application to ensure a consistent output for expectations.
This concerns Symfony 2.7+

**Comment by 1ed** [comment]
This can not be fixed right now because [SymfonyStyle.php#L371](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Style/SymfonyStyle.php#L371).

What do you think about rename that method to `getDefaultTerminalWidth()` and add public `getTerminalWidth()` and `setTerminalWidth($width)` methods and `getTerminalWidth()` should fall back to `getDefaultTerminalWidth()`? I can work on it if sounds good.
