### ISSUE TITLE
What is the right way to deprecate protected or even public methods?

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony#15902]
As the title reads – there are some `protected` methods in the `Translator` class. What does a change have to look like to comply with the BC promise?

Obviously, triggering E_DEPRECATION notices does not work in this case, right?

**Comment by xabbuh** [comment]
Not sure I understand your problem. Why can't you trigger a deprecation warning inside the method (of course you need to ensure that this method is not called anymore from our internal code)?

**Comment by mpdude** [comment]
As long as it is only deprecated, I need to keep calling it to make sure the override code still runs.

**Comment by mpdude** [comment]
Also, it might be overridden without calling the base implementation. In that case, the deprecation warning will not be shown.

**Comment by stof** [comment]
@mpdude the case where the deprecation should be triggered is not when the method is called, but when a child method is called (we need to warn them when they overwrite the method to extend the logic). This implies using Reflection to detect whether the method is overwritten or no. This means that the deprecation must be triggered by the code calling the protected method (see how we did it in the Form component to ask people to overwrite ``configureOptions`` rather than ``setDefaultOptions``. The logic is the same except that the calling place is in another class because these are public methods)

**Comment by mpdude** [comment]
For future reference, the change @stof probably refers to is https://github.com/symfony/symfony/commit/3d43caef88db7226986d43ec98313cb3b5ee600c#diff-3b9d1458321cff8f2d472f20fe02d42d.

Thanks!

**Comment by stof** [comment]
yes it is. The way to handle protected methods is the same.

**Comment by mpdude** [comment]
Following up on this.

In case of the `Translator`, there are even some `public` methods and the entire class is `@api`. 

Is there any chance of deprecating the public methods? I mean, the reflection-based approach pointed out above does not work if the caller is not part Symfony itself and if a public method has been overriden by users.

**Comment by stof** [comment]
@mpdude the Reflection-based approach is for cases where we want to deprecate extension point for child classes.
In case of public methods, we should have triggers in the method itself for code calling it (this is what we do everywhere). And yes, if you write code against your own implementation only, you may not get the warning. But the method will not disappear from your own class either when migrating. So it is not a huge issue.
