### ISSUE TITLE
FrameworkBundle translator tests are failing for deps=high

### ISSUE THREAD

**Issue by stof** [symfony/symfony#15935]
See https://travis-ci.org/symfony/symfony/jobs/82334660#L2124

this should be considered a critical issue. We need to bring our testsuite back to green to be meaningful (2.7.5 and 2.3.3 were released with red builds btw)

/cc @aitboudad

**Comment by aitboudad** [comment]
This due to #15738 /cc @mpdude

**Comment by mpdude** [comment]
The entire test in question has been [removed in 2.8](https://github.com/symfony/symfony/pull/15738/files#diff-990df0e8238847f8ae54e8227f295c22L107). Honestly, I did not see what it was trying to test for (that has not been covered elsewhere).

If you want to keep it, the problem is that at the end of the test,

```php
    // refresh cache when resources is changed in debug mode.
        $translator = $this->getTranslator($loader, array('cache_dir' => $this->tmpDir, 'debug' => true), 'yml');
        $translator->setLocale('fr');
```

After the cache has been warmed (in the same test, above), this now switches `debug` from `false` to `true` and expects the cache to become stale. Somehow that might have worked in the past, but in fact, the resource used (a YAML translation fixture) has not changed and so the cache is still considered fresh.

**Comment by mpdude** [comment]
PR to remove the test is in #15943 /cc @stof

**Comment by aitboudad** [comment]
@mpdude I think it shouldn't considered fresh because the resource used has been removed in the end of the test

**Comment by mpdude** [comment]
You mean the `'resource_files' => $resourceFiles` part is missing? 

Then, you're loading a different set of resources so you need to use a different cache file. But that would also be pointless, because you'd warm the cache for a cache location A, assert that it works and then create a Translator with a different cache location B and make sure that there is no cached data there. IMO that does not add value.

**Comment by aitboudad** [comment]
@mpdude I'm not talking about the test itself if it's useless or not, but only we should be sure that #15943 doesn't break something

**Comment by mpdude** [comment]
The test in question was removed on 2.8 along with the changes from #15738.

On 2.7, the test is still there but fails due to `symfony/config` being installed as `2.8` (`deps=high`). So, let's remove the test on 2.7 as well (#15943).
