### ISSUE TITLE
[Console] Styles do not respect stderr

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#15986]
The problem is that Styles like the SymfonyStyle do not use stderr when appropriate.
Errors and diagnostic and interactive messages that are not meant as actual ouput of the command should go to stderr. For background info see http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

For this we merged #15795 to help people use the right one by default. But this will not take effect when using the styles currently, e.g. when using `askQuestion` in https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Style/SymfonyStyle.php#L330

**Comment by SpacePossum** [comment]
>The problem is that Styles like the SymfonyStyle do not use stderr when appropriate.

Is it by design that a `formatter` chooses a stream, i.e. does more than formatting?
For example, how would you write an error through a formatter to stdout?
Binding a formatter two both streams (through `ConsoleOutput::setFormatter`) at the same time is pretty confusing, if the formatters are going to switch between streams as well it will become even more confusing where output ends up IMHO.
