### ISSUE TITLE
Adding HTTP_HOST in Symfony\Bundle\FrameworkBundle\Client for insulated requests

### ISSUE THREAD

**Issue by bjoernfal** [symfony/symfony#15998]
I am using insulated requests for my unit testing, but the SERVER variable did not come through:

```php
    $this->client = $this->createClient(array(), array("HTTP_HOST" => "my.local.host"));
    $this->client->followRedirects(false);
    $this->client->insulate(true);
```

I found out that I can fix this issue in Symfony\Bundle\FrameworkBundle\Client::getScript() by adding

```php
    \$_SERVER["HTTP_HOST"] = "{$this->getServerParameter("HTTP_HOST")}";
```

in the code.Maybe it can be done better!

**Comment by dolbertz** [comment]
I wrote the following TestCase on Symfony 3.0.3 and PHP 5.6.19:
```
namespace Tests\AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class SimpleControllerTest extends WebTestCase
{
    public function testSomething()
    {
        $client = static::createClient(array(), array('HTTP_HOST' => 'my.local.host', 'X-TEST' => 'test'));
        $client->followRedirects(false);
        $client->insulate(true);

        echo $client->getServerParameter('HTTP_HOST') . "\n";
        var_dump($_SERVER['HTTP_HOST']);
        var_dump($_SERVER['X-TEST']);
    }
}

$test = new SimpleControllerTest();
$test->testSomething();
```

Executing the test via `phpunit tests/AppBundle/Controller/SimpleControllerTest.php`results in
```
my.local.host
Undefined index: HTTP_HOST
```
`$_SERVER` has some other keys like `HOME` but neither `HTTP_HOST` nor `X-TEST` are available. Browsing through the code of `Symfony\Bundle\FrameworkBundle\Client` I found no use of `$_SERVER` at all. All the tests for this class suggest, that it only uses its own server parameters.

I'm not sure if manipulating `$_SERVER` is a desired behaviour. The code that is too be tested should use the Request object instead of `$_SERVER`, I assume.

BTW: The line `$this->client->insulate(true);` is not relevant for the result of this test.

Status: Reviewed

**Comment by xabbuh** [comment]
Actually I am not sure if I understand the issue. @bjoernfal can you give a concrete example of what you are trying to do and what happens instead of what you expected?

**Comment by bjoernfal** [comment]
Sure!

I'm implementing functional tests with HTTP requests, so I am using the createClient method to create a WebTestCase Client. My Bundle uses $_SERVER["HTTP_HOST"] to identify a request, so it has to be set when conducting the tests (otherwise I get the "unidentified index" error). I rewrote my tests to use non-insulated tests (other than I stated before), but that seems to make no difference in this case.

As stated on http://symfony.com/doc/current/book/testing.html#testing-configuration I used this code to create a client and set HTTP_HOST:

```
$client = static::createClient(array(), array(
    'HTTP_HOST'       => 'en.example.com',
    'HTTP_USER_AGENT' => 'MySuperBrowser/1.0',
));
```

But $_SERVER["HTTP_HOST"] is still not set after I send a request with this client. So currently I'm setting the variable in my tests directly, which seems to be a good workaround.

Btw, I do not set any other PHP variables in my phpunit.xml than KERNEL_DIR (i used to set HTTP_HOST there as well).

**Comment by jakzal** [comment]
The browserkit client doesn't modify the global state (namely it doesn't modify the `$_SERVER` global). Otherwise you'd have tests influencing each other, while they should be independent. In Symfony, you shouldn't access global variables either, but use the Request class instead. This way you can run your tests in isolation without side effects.

I'm going to close this as there's nothing to fix in Symfony.
