### ISSUE TITLE
JsonResponse, exception if json_encode() fails

### ISSUE THREAD

**Issue by Richard87** [symfony/symfony#16224]
This is my first issue report, so please let me know if this is not appropiate, or if another channel would be better.

If json_encode() fails in JsonResponse (in my case, due to a bug with substr and utf8) it fails withoug any notification or log event.

I suggest it should throw a UnexpectedValueException if return from json_encode === false with error number.

``` PHP
    public function setData($data = array())
    {
        // Encode <, >, ', &, and " for RFC4627-compliant JSON, which may also be embedded into HTML.
        $data = json_encode($data, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT);
        if ($data === FALSE) {
            throw new \InvalidArgumentException("json_encode() FAILED", json_last_error());
        }
        $this->data = $data;

        return $this->update();
    }
```

Best regards,
Richard Hagen

**Comment by Richard87** [comment]
After a little more testing, it seems that in some coincidences json_encoding would return null instead of value when facing this specific issue, set json_last_error to 5, but still produce the rest of the json... So implementing this might brake a lot of random things, that works (but slightly buggy today)...

**Comment by javiereguiluz** [comment]
I'm sorry but I must close this issue because of the lack of feedback from the community. We didn't receive any issue report related to this either, so maybe this is a very edgy case.

In any case, if checking the JSON validity is critical for your app, you can do that beforehand and then use the new `return JsonResponse::fromJsonString($jsonContents);` shortcut?

If you disagree with our response, please reopen this issue. Thanks!
