### ISSUE TITLE
[Yaml] YAMLDumper does not support writing using folded/literal style

### ISSUE THREAD

**Issue by deanc** [symfony/symfony#16236]
http://yaml.org/spec/1.2/spec.html#id2760844

Specifically, there is no way to output this:

```yaml
>
 Sammy Sosa completed another
 fine season with great stats.

   63 Home Runs
   0.288 Batting Average

 What a year!
```

The main reason I find that this is odd, is if you use the `YamlLoader` and do zero processing on the data, and then immediately dump it back out again - it changes the file. I would expect the API's to be compatible (even if it requires configuration).

**Comment by stof** [comment]
indeed it does not. this is because there is several Yaml representations of the same datastructure in Yaml, and the dumper chooses one of them (the easiest one to implement btw).

How would you imagine an API allowing to choose the representation used for each value when dumping ? I don't see any easy to use interface for that.

**Comment by deanc** [comment]
Yep, I understand that what it outputs is perfectly valid but it would be nice to have a choice on that output. The API right now for dump is:

`public string dump(mixed $input, int $inline, int $indent, bool $exceptionOnInvalidType = false, bool $objectSupport = false)`

An extra option could be added `preserveLiterals` which would expand strings with new lines using the literal style.
