### ISSUE TITLE
Found a Yahoo comment and copyrith mention within the debug component

### ISSUE THREAD

**Issue by egosselin1** [symfony/symfony#16241]
While I was writing some functional tests, I stumbled upon an error wrapped in yahoo html code, example in the decorator method here : https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Debug/ExceptionHandler.php. Although I know that it is not really an issue, I thought it might be helpful to report it.

**Comment by Tobion** [comment]
So what is the problem?

**Comment by javiereguiluz** [comment]
@egosselin1 to give a consistent look across browsers, we need some styles to neutralize the default CSS styles applied by each of those browsers. The mentioned code provided by Yahoo was one of the most popular styles to neutralize browsers. That's why we use it. Do you think we should switch to another "neutralizer library"?

**Comment by egosselin1** [comment]
Nevermind, it just looked like a copy-paste mistake, that's why I reported it.
