### ISSUE TITLE
Use Process component for remote servers

### ISSUE THREAD

**Issue by ComyoPS** [symfony/symfony#16245]
I want to run a process on a remote server over SSH and I love the Process component.
Is there any way or plan to run a process on remote servers (for example over SSH)?

**Comment by stof** [comment]
there is no plan for it, because it would be a totally different component. the Process component is just a wrapper around PHP functions related to run a subprocess, to give a nicer API and handle cross-platform consistency (``proc_open`` and related functions have many edge cases where they are not fully consistent cross-platform).

**Comment by sstok** [comment]
Do you need execute this part of a deployment (or such) were the commands are not fully predictable or do you simple need something to perform operations on a remote server?

**Comment by ComyoPS** [comment]
@sstok Basically I like to deploy my code. But I use ``git`` for deployment, that because I only need to perform operations on a remote server. Example: ``git pull``

**Comment by beni0888** [comment]
So, what about this feature? Do you think it is ok to start working on it? Or have it to be accepted before?

**Comment by stof** [comment]
@beni0888 executing commands on a remote server is a totally different feature that starting subprocesses. So it does not belong to the Process component but to another library

**Comment by beni0888** [comment]
:+1:
