### ISSUE TITLE
[Form] [2.8] Naming forms works only in some cases; passing extra params to a form

### ISSUE THREAD

**Issue by petforsberg** [symfony/symfony#16296]
**1.**

There's a new way to naming forms with help of getBlockPrefix() method, according to the upgrade info https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md.

The problem is it works only when Forms are **instantiated** e.g.:

     new MyFormType()

But not by a **class** name, e.g.:

     'AppBundle/MyFormType'

In the second case, I get the form name like 'my_form' regardless whatever I put into the getBlockPrefix() or getName() methods. But when I pass to the Form Factory **an instance** of my form type (e.g. new MyFormType() as shown above ), the generated form has the proper block prefix - the one I set, e.g. 'profile' in the example from the upgrade text file:

	class UserProfileType extends AbstractType
	{
	   public function getBlockPrefix()
	   {
		   return 'profile';
	   }
	}

**2.**

It seems that when one tries to create a form in a new way (with a class), it seems there's no any possibility to pass any parameters to its constructor.
Maybe introducing some extra array param to the Form Factory when creating a form from a class would resolve the issue?

**Comment by craue** [comment]
The first part is probably related to #15760.

**Comment by petforsberg** [comment]
Yes it is, thx for your comment.

And it *is* a bug in my opinion, because otherwise introducing getBlockPrefix() makes no sense.

**Comment by stof** [comment]
If you want to pass dependencies in your form type, you should register the type in the form registry *before* using it to create a form with it.
This is already the recommendation in previous versions btw.
Passing a new type instance when creating a form forces the registry to replace the existing instance with the new one, which means extra work (especially if the same type is used several times, for instance because of a collection) and can lead to weird bugs in case you register the form type several times with different dependencies (because ``buildView`` will be called with the last registered instance, even if a different one was used for ``buildForm`` previously).

The only new thing in the 2.8 way to reference types is that registering a type before referencing it is now optional (assuming there is no dependency). As names are the class names now, the registry can implicitly register the form type when using it the first time (instantiating it with no argument)

> introducing getBlockPrefix() makes no sense

It is still used for the form theming, which is its primary usage.
Controlling the name of the root form is **not** the primary goal of the form type name or the block prefix (the form type name is only used as a default value when you don't give a name for your root form)

**Comment by petforsberg** [comment]
Ok then, so one point has been explained quite clearly.

And for the  maybe I'll introduce my **use case**, the situation and requested features or "bug fixes" might be clearer.

In my CMS-like app there might be different types of "editors" - from the most simple one like a textarea-based, to some complex things, like JavaScript mini-platforms used as rich WYSIWYG editors.

According to the SF app assumed architecture, all of these editors (in SF as form types) should be easily used either in the standalone version, or "attached" (added) as a part of another, more complex Form Type. The extra complexity is that the same "editor" FormType could be used **multiple times at the same page**.

What's more, in the CMS world a user should be able to configure as many things as possible, including the type of editor - so there will be multiple editors (form types) in my SF app available. Therefore I need to figure out which editor (form type) to attach to a page or as a part of another form type in the fly, it can't be set statically. Actually, this idea of having dettached editors is present in a Symfony's CMF bundles, so it's really nothing new here.

I'd like to follow this "flexibility and ability to configure" way with my app.

The thing is now I'd like to have different names for all editor forms, without abandoning the flexibility Symfony used to give as before. :)

> It is still used for the form theming, which is its primary usage.
> Controlling the name of the root form is not the primary goal of the form type name or the block prefix (the form type name is only used as a default value when you don't give a name for your root form)

Still, it's a really nice feature. It would be really really nice if it was possible to name forms, just as it was before 2.8, instead of taking away existing features from Symfony.
;)

**Comment by stof** [comment]
> Still, it's a really nice feature. It would be really really nice if it was possible to name forms, just as it was before 2.8, instead of taking away existing features from Symfony.

Naming forms explicitly is still possible, with the same API than in 2.7. What has changed for now (and is reported in #15760) is that the default name has changed when you **don't** name the form explicitly.

**Comment by petforsberg** [comment]
Ok. So to be clear, for the moment, should we instantiate all our forms in order to have demanded block prefixes (names)?

**Comment by stof** [comment]
@petforsberg no you should not. Passing type instances is deprecated.
If you really care about the name of the root form (and in many cases, we don't actually care to be honest), you should use the dedicated API of the FormFactory to create a named form instead of creating a form without giving a name.

**Comment by petforsberg** [comment]
Ok thx, now it's clear what you meant.

**Comment by fracsi** [comment]
I agree with @petforsberg 
We decided to update our project to 2.8. We thought that `block_prefix` will behave like the `name` previously in theming. A lot of our JS code broke because the naming convention has changed.

**Comment by Taluu** [comment]
Sorry for making this up (as this issue is still open and concern this though), but I think there's a slight problem with allowing only FQCN as the type on factories... What if your formtype has a dependency not on a service but on a value object ? e.g, I have a formtype which works on an entity, which depends on the parent entity. 

I cannot declare this form type as a service (And thus inject my entity), because said entity is retrieved during the code execution (and cannot be retrieved while the container is built). I don't want to make multiple formtypes just for the states of the parent entity (this is a waste of time and a waste of maintainance time too IMO). So for now, I have to extend the factory to be able to use the type instance directly ? :{

**Comment by HeahDude** [comment]
This one can be closed as fixed by #16758 IMO.
