### ISSUE TITLE
Form validation read_only  or disabled should make form invalid if the field is edited

### ISSUE THREAD

**Issue by m-amr** [symfony/symfony#16337]
I wan't to disable editing some fields of the entity
at the front-end it don't by using read_only or disable the input.

but  i am using an Rest APIs to edit item data and i have a formType to validate the data
but when i set field as read_only=true or disabled=true

expect result when change a read_only field
is the form to be invalid because it is editing in a read_only or disabled field 
but this doesn't happened.

**Comment by Tobion** [comment]
ready_only doesn't mean it cannot be edited according to html spec (which is why we deprecated the option).
disabled will ignore any value that is submitted for this field. So there is not point in validating it has not been changed.

**Comment by m-amr** [comment]
@Tobion  .. what about creating an options called 
is_editable by default equal true
but developer can set it to be false if he want form to be invalid be this field change ?

**Comment by Tobion** [comment]
I don't think it belongs in core as it will create alot of confusion and edge cases. For example what happens when disabled=true and is_editable=true. Or disabled=false and is_editable=false. But you can always write your own form extension that provides this functionality and release it as a standalone library.
