### ISSUE TITLE
empty composer.json after installing with symfony command

### ISSUE THREAD

**Issue by senenh** [symfony/symfony#16354]
When creating a new project on Windows 10, PHP 5.5 with:

php symfony new my_project_name

It creates the project with the file composer.json empty.
That doesn't happen with 

php symfony new demo

or creating it with composer.

**Comment by WouterJ** [comment]
Thank you for submitting the bug! However, this is a bug report for the Symfony Installer and should be submitted to https://github.com/symfony/symfony-installer instead. As you can see, the bug is already submitted by someone else: https://github.com/symfony/symfony-installer/issues/190

*Please close this issue.*

**Comment by senenh** [comment]
Got it. Thank you!
