### ISSUE TITLE
[RFC][Guard] Integrate into Security\Http

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony#16470]
While guard is a really great new feature of the Security component, the decision to make it a sub-component seems a bit strange. I propose to remove the Guard sub-component and merge it into the Security\Http sub-component.

Here is why:

 * Guard fully depends on Security\Http (HttpFoundation). You can't use Guard without Http, as all its logic in inside a firewall listener. This is unlike the other sub-components (e.g. Core can be used in the console, Csrf in a standalone form).
 * Guard is by far the best solution for custom authenticators when using the HTTP Security system. In 3.1, the plan will probably be to deprecate the `Simple*` implementations in favor of Guard. This means that it doesn't make sense to use Security\Http without Security\Guard (so in both ways, the sub-components will rely on eachother).
 * Having Guard in Security\Http simplifies the migration when deprecating the `Simple*` implementations in Symfony 3.1

/cc @iltar @weaverryan

**Comment by iltar** [comment]
My main concern with deprecating `Simple*`, we don't have a proper CLI authentication method yet and this is impossible with Guard as I see it, as it depends heavily on the Request. It would make it a lot easier if we could get some kind of interface in there which we can extend to get the parameters from the bag to authenticate against. This way our CLI and HTTP could both implement a different variant and still use the same code to authenticate with.

_Just throwing some ideas out here, not sure if it's even doable like that. Maybe a whole new authenticator system for the CLI has to be build?_

**Comment by weaverryan** [comment]
Your arguments for putting it into Security\Http are sound. I originally put it in its own component for simplicity: all the classes are put into one spot, instead of being spread through the Http and Core components. It's a nice example of how custom authentication system libraries should be built. This is indeed different than existing things, like Simple*, that are spread across Http and Core. Oppositely, you could make the argument that Http should just include the core Http authentication logic, and that all authentication systems (form login, LDAP, etc) could be their own components, making Http and Core smaller and more focused (I'm not saying we should do this - I don't see the point).

I don't feel highly motivated to change this. The only advantage I see is that projects that currently require `symfony/security-http` that want to use guard will need to also require `symfony/security-guard`.

**Comment by sstok** [comment]
An authenticator system for the CLI? How cool this would sound, are there actual Symfony applications out there that use this concept?

**Comment by WouterJ** [comment]
@sstok you can see https://gist.github.com/WouterJ/03ef6e02d4f3fa639bbe for a very basic example of using Security in the CLI. And I'm currently working on a ConsoleSecurity Bridge/Bundle.

**Comment by iltar** [comment]
@sstok my company internally has this. It uses the question helper to ask for username and password and authenticates against our ldap server. Additionally a token can be provided as argument to the command to authenticate against (but this is possible due to SSO).

So yes, it's available and we need it. Currently we use a `Simple*` variant for this which we will have to rewrite for 4.0.

**Comment by fabpot** [comment]
It's up to you guys but we need to decide NOW as I'm about to release the first 2.8 beta, after it will be too late. ping @symfony/deciders

**Comment by weaverryan** [comment]
:thumbsdown: primarily because I don't see any problems it will solve. I'd vote to not change to a component if the situation were opposite.
