### ISSUE TITLE
[Yaml] Escaper escapeWithDoubleQuotes prints single quotes and double quotes

### ISSUE THREAD

**Issue by nunohorta** [symfony/symfony#16483]
Example:

`$config["server"]   = $escaper->escapeWithDoubleQuotes("localhost");`
`$dumper = new Dumper();`
`$yaml = $dumper->dump($config, 2);`
`file_put_contents($configFile, $yaml);`

this is showing up on the file:

`server: '"localhost"'`

Why is it printing the single quotes? I need to print something like:
`server: "localhost"`

**Comment by xabbuh** [comment]
You should not escape the values yourself. Otherwise the string contains double quotes and the dumper needs to use single quotes so that the double quotes will actually be dumped.

Anyway, there is no reason to quote anything at all here. Just use something like this:

```php
use Symfony\Component\Yaml\Yaml;

$data = array(
    'server' => 'localhost',
);

print_r(Yaml::dump($data));
```

The dumped YAML will look like this:

```
server: localhost
```

Of course, there are no double quotes, but that's absolutely fine as YAML does not need quotes if there are no special characters being used in the string being dumped.
