### ISSUE TITLE
phpunit is not properly installed on first run of ./phpunit

### ISSUE THREAD

**Issue by emil-nasso** [symfony/symfony#16488]
I'll create a new issue for this, as i now feel like this is a bug.

phpunit is not properly installed when i run the `./phpunit` file in the symfony repo root directory.

I'm running OS X 10.11.1, with php version 5.5.30 and the zsh shell.

First, i cloned the symfony repository `git clone git@github.com:symfony/symfony.git` and ran `composer update`

The `.phpunit` directory doesn't exist yet. To my understanding, phpunit is installed when you run the `phpunit` script in the root directory of the symfony repo. When i run that script i get this error:

```bash
[emil:~/Development/symfony](2.8) $ ./phpunit

exec /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/composer/1.0.0-alpha10/libexec/composer.phar "$@"
exec /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/composer/1.0.0-alpha10/libexec/composer.phar "$@"
exec /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/composer/1.0.0-alpha10/libexec/composer.phar "$@"
Warning: require(/Users/emil/Development/symfony/.phpunit/phpunit-4.8/vendor/autoload.php): failed to open stream: No such file or directory in /Users/emil/Development/symfony/.phpunit/phpunit-4.8/phpunit on line 4

Fatal error: require(): Failed opening required '/Users/emil/Development/symfony/.phpunit/phpunit-4.8/vendor/autoload.php' (include_path='.:') in /Users/emil/Development/symfony/.phpunit/phpunit-4.8/phpunit on line 4
PHP Warning:  require(/Users/emil/Development/symfony/.phpunit/phpunit-4.8/vendor/autoload.php): failed to open stream: No such file or directory in /Users/emil/Development/symfony/.phpunit/phpunit-4.8/phpunit on line 4
PHP Fatal error:  require(): Failed opening required '/Users/emil/Development/symfony/.phpunit/phpunit-4.8/vendor/autoload.php' (include_path='.:') in /Users/emil/Development/symfony/.phpunit/phpunit-4.8/phpunit on line 4
KO ./phpunit
```

It looks like something goes wrong during installation. Some commands seems to be printed instead of executed. There is no  `vendor` directory in `.phpunit/phpunit-4.8`.

I got everything up and running thanks to @WouterJ 's help on irc.

I ran the following commands inside the `.phpunit/phpunit-4.8` directory:

```bash
composer remove --no-update symfony/yaml
composer require --dev --no-update symfony/phpunit-bridge ">=2.8@dev"
composer install --prefer-source --no-progress --ansi
```

That seems to have fixed the broken phpunit installation/initialization.

**Comment by nicolas-grekas** [comment]
So, something is wrong with composer. From the output get, I suspect you have a shell wrapper for it and this does't play well with out phpunit script.
The script tries to use the same php binary for composer than the one that is used for running the phpunit wrapper.
For this, it first tries to find the composer phar here:
https://github.com/symfony/symfony/blob/2.8/phpunit#L15
then it runs the current php on it.
But since your composer is a shell wrapper, this doesn't for and instead you get the shell script source on the output (thus the "exec" lines).
If you have any idea how we can enhance the situation, please open a PR. I'll think about it...
Meanwhile, you can put composer.phar in the same dir that our phpunit and it should work.

**Comment by emil-nasso** [comment]
@nicolas-grekas Ah, yeah. That is probably it. I have installed composer with homebrew. I like to install everything with homebrew, if possible. :) Can confirm that composer was a bash-wrapper.

I have an idea for a solution. Will read up on how to create a pull-request. :)
