### ISSUE TITLE
Safer installation instructions for Symfony

### ISSUE THREAD

**Issue by pwaring** [symfony/symfony#16538]
Both the documentation and the Symfony website advise installing Symfony on Linux/Mac using the following command:

```
sudo curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony
```

This is unsafe for three reasons:

 1. The file is downloaded over an insecure protocol, so the user has no way of knowing whether they are really downloading from symfony.com.
 1. The installer is a binary file, so the user has no way of verifying what it does before running it.
 1. The installer is run as root, so if it is malicious it could do anything with key system files.

Please can safer installation instructions be used - we shouldn't be encouraging developers to blindly download binaries over an insecure protocol and run them as root. I'm not sure why Composer is not the default mechanism, since it's common across hundreds of PHP projects.

**Comment by stof** [comment]
you are not running the installer as root here, you are running curl as root (which is necessary only to be able to write to ``/usr/local/bin/``, as it is generally owned by root, but you can avoid sudo if you place it in a folder which is in your PATH but owned by yourself)

Regarding the protocol, the installer is now available on HTTPS. @javiereguiluz I suggest updating the URL

Regarding verifying the file, it is a PHAR archive. So you can inspect it if you want.

Using composer to bootstrap a new project has many drawbacks compared to using the installer:
- it is much slower (the installer downloads an archive will all vendors included instead of forcing you to download all vendors separately)
- the installer does much more than installing composer dependencies. It also performs the initial setup of the project (changing the name in the composer.json to avoid having your own project named as ``symfony/framework-standard-edition`` for instance, generating a random secret, removing the standard edition readme and license as they should not be the readme and license of your own project, etc...) Trying to use a composer hook to do the same when running ``create-project`` has been tried in the past, and it was a huge pain (as it must also be removed from your project to avoid running it again when using ``create-project``)
- it checks the system requirements to run Symfony
- it allows a much better experience for newcomers, by giving them nice feedback about what is happening during the creation of the project (the Composer output is not user-friendly at all for that, given that Composer's job is not to bootstrap project skeletons)

**Comment by pwaring** [comment]
"you are not running the installer as root here, you are running curl as root"

Sure, and that's fine until someone writes remote exploits for cURL (which has happened several times). It would be safer to download the file somewhere writeable by the user (`$HOME` or `/tmp` perhaps)  and then use `sudo` on the `mv` command.

**Comment by javiereguiluz** [comment]
@pwaring thanks for rising your concerns about the security of Symfony installation.

Shortly after your pull request, we changed the instructions to always use HTTPS. That was a no-brainer decision. For the rest of instructions, we prefer to maintain them as they are. If an experienced developer wants to improve the installation process, is trivial to do it for him/her (just remove the `sudo` command, download the package somewhere else, inspect its contents before running it, etc.)

Therefore, I'm closing this as fixed. @pwaring thanks again for your comments!
