### ISSUE TITLE
Route alias / @RedirectRoute

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony#16569]
Currently there is a ``@Route`` annotation. But how could I easily add routes which are redirected to the main route to prevent duplicate content (Search Engine Optimization, redirect old routes, ..)?

I think something like ``@RedirectRoute("/test", "/target", 301)`` would be nice.

**Comment by Tobion** [comment]
Just add the route and configure the redirect controller for it.

**Comment by JHGitty** [comment]
@Tobion That's a solution but a short annotation would result in clean code, IMO.

**Comment by javiereguiluz** [comment]
@JHGitty we are very relunctant to add new annotations. At first sight this `@RedirectRoute()` annotation is perfect for your use case. However, on a second thought, it complicates the framework because it makes you learn another annotation and it adds another way to solve a problem that can already solved in lots of different ways.

An alternative solution to your use case could be to define a `app/config/routing_seo.yml` file and import it from the other routing files. In that SEO file, you could define the redirections as [explained here](http://symfony.com/doc/current/cookbook/routing/redirect_in_config.html#redirecting-using-a-path).

**Comment by JHGitty** [comment]
@javiereguiluz Great idea! :+1:
