### ISSUE TITLE
Add nativ tool to test project

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#16625]
Hello !

Currently, there is no way out-of-the-box to test its entire project; best practices advise to develop [smoke tests](http://symfony.com/doc/current/best_practices/tests.html#functional-tests). I think it would be pratical to dispose a nativ tool that do this.

I made a small (and very incomplete) POC in a fork of  [symonfy-demo](https://github.com/maidmaid/symfony-demo/blob/profile/src/AppBundle/Command/ProfileCommand.php) demonstrating my idea : 

[![asciicast](https://asciinema.org/a/a4mgpy2zpogrelo0zilq6o1px.png)](https://asciinema.org/a/a4mgpy2zpogrelo0zilq6o1px)

This command tries to build each route of project  (this does not always work when the route is complex) and call them with each roles user defined in project. This returns HTTP code, some classical stats of profiler and debugging token.

Add to Symfony a native tool that tests *basically* the entire project is :+1: in my opinion. What is your opinion ?

**Comment by Nek-** [comment]
Hello,

I'm not sure to get your point. What do you test ? Because a 403 could be an error. Just as a 302 if it's not expected. You need to define a configuration of data to send for each route, and data to store in the database (to have `/url/{id}` working). Eventually session cookies...

Another point is that there is no real complete list of `roles` anywhere in an application (because in some cases the role is just reading on a data).

I don't understand in what way it *test* things. Can  you be more explicit ?

**Comment by maidmaid** [comment]
Indeed, you are right @Nek-, this command does not really *test* things, but it can check the return code for each route of your project, what I personally find convenient. With this command, if I develop something and I did not create any tests, I could quickly check my development did not break anything elsewhere.

**Comment by fabpot** [comment]
That's definitely not something that should be part of core Symfony as this is something that can easily be built outside core, something that can be done in many different ways depending on your goals, but also because similar tools already exists (codeception, behat, goutte, ...).
