### ISSUE TITLE
composer diagnose throws warning for new project's composer.json created by symfony installer

### ISSUE THREAD

**Issue by cfhay** [symfony/symfony#16678]
Using composer 1.0-dev (2b14f0a047dd4f3545ec82381f65c36ea93a4c81) 2015-11-25 17:13:09

Using symfony installer 1.3.3

```
$ symfony new test 2.7

 Downloading Symfony...

    5.17 MB/5.17 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

 ✔  Symfony 2.7.7 was successfully installed. Now you can:

    * Change your current directory to /usr/local/symfony/2.7/test


    * Configure your application in app/config/parameters.yml file.

    * Run your application:
        1. Execute the php app/console server:run command.
        2. Browse to the http://localhost:8000 URL.

    * Read the documentation at http://symfony.com/doc
```

```
$ composer diagnose
Checking composer.json: FAIL
description : The property description is required
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking composer version: OK
```

**Comment by javiereguiluz** [comment]
We removed the `description` from the composer.json file because according to [this comment](https://github.com/symfony/symfony-installer/issues/73#issuecomment-66322425) it's optional. And according to the Composer documentation, it's only mandatory for packages published as third-party packages. Reference: https://getcomposer.org/doc/04-schema.md#description

So I guess the `composer disagnose` command is a bit misleading in this case.

**Comment by javiereguiluz** [comment]
I've reported this issue in Composer repository (https://github.com/composer/composer/issues/4652). We can close this issue and we'll update the Symfony Installer according to Composer's authors comments. Thanks.
