### ISSUE TITLE
Versioning inconsistency in symfony/config 2.80

### ISSUE THREAD

**Issue by katzefudder** [symfony/symfony#16807]
**symfony/config** in v. 2.8.0 requires PHP 5.3.9 (">=5.3.9") as a minimum, it also requires **symfony/filesystem** in "~2.3|~3.0.0". 
filesystem in ~3.0.0 requires PHP >=5.5.9 so it breaks the minimum requirements of **symfony/config** in v. 2.8.0

**Comment by stof** [comment]
@katzefudder it does not break anything. The symfony/config code works with symfony/filesystem 3.0. and it is possible to resolve the ``~2.3|~3.0.0`` requirement to versions supporting 5.3.9 (but you will have to select a 2.x version then to fulfil the dependency). Try running composer on PHP 5.3 and you will see that it manages to resolve the dependencies.
There would be a bug only if none of the matching versions were supporting PHP 5.3.9.

Note that if you run a different PHP version locally and in prod, you can force composer to consider the prod PHP version rather than your local PHP version during the package resolution (forcing it to find deps compatible with PHP 5.3 for instance): https://getcomposer.org/doc/06-config.md#platform
