### ISSUE TITLE
When updating to version 2.8.0, more than 50% of tests are broken.

### ISSUE THREAD

**Issue by mmoreram** [symfony/symfony#16840]
The Exception thrown is:

Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a synthetic service ("kernel"). The DIC does not know how to construct this service.

I don't really know if this is a practice we've used in our project and is something forbidden (but acceptable till now) or that, this issue is really solved but not tagged yet, or if this is not really tested.

Is anyone having the same issues?
Any feedback will be really appreciated :)

**Comment by javiereguiluz** [comment]
Could you please share the smallest possible snippet of code that reproduces this issue? Otherwise it's really hard to find the root cause of this issue. Thanks!

**Comment by nicolas-grekas** [comment]
Hackday today ?

**Comment by mmoreram** [comment]
Sure!
El dia 5 des. 2015 9:29 a. m., "Nicolas Grekas" <notifications@github.com>
va escriure:

**Comment by mmoreram** [comment]
We've been reviewing the case of that issue and seems that in our case, we're using a weird usage of static property `static::$kernel`from Symfony's WebTestCase.
We can block the issue (i'd prefer not to close it until we've resolved the issue in our part.

I will add some description about the real problem and how we solved :)

**Comment by mmoreram** [comment]
Fixed:

Basically, in our case we were using symfony's WebTestCase static::$kernel only some times. That made store value inconsistent sometimes.
We're not using this class anymore, and everything work as expected :)

Thanks @nicolas-grekas and @stof for your help :)

**Comment by rufinus** [comment]
i have the same problem - as soon as i request twig_env from the container this runtime exception is thrown.
see http://stackoverflow.com/questions/34372446/twig-environment-in-service-class-leads-to-dic-runtimeextension-only-when-unitte

**Comment by xabbuh** [comment]
@rufinus I answered on StackOverflow.

For anyone else interested in the problem: When using the `KernelTestCase` class as a best class for your functional tests (either directly or by extending the `WebTestCase` class), you shouldn't boot the kernel in the constructor, but rather use the `setUp()` method for this. Otherwise, your tests won't run with a properly booted kernel as booting would only happens once while after each test the kernel is shut down in the `tearDown()` method.

**Comment by rufinus** [comment]
@xabbuh thanks. this indeed fixes the problem.

**Comment by juhah** [comment]
I had this same problem even when I boot the kernel in the `setUp()` method. I'll leave a note here since this page comes up first in search results.

My specific problem was that I create two client instances which leads to two `createClient()` calls which calls again the `bootKernel()` method. So now instead of extending `WebTestCase`, I extend `KernelTestCase`, boot the kernel once in `setUp()` and then the create the two client instances.

**Comment by crmpicco** [comment]
Essentially, remove any calls to `self::bootKernel();` in your tests. See http://stackoverflow.com/a/34469555/691505
