### ISSUE TITLE
[Form] Unable to reset password when not required and always_empty = true

### ISSUE THREAD

**Issue by nykopol** [symfony/symfony#16874]
I have a password field on which i don't want to populate the value (always-empty => true). But this password is also not required (required => false). 

This work well until i want to reset an existing password. This is impossible as no value is interpreted as "keep the existing value".

I'm not sure about how to deal with this issue. I think that there is two solutions : 
- Add a few lines in the docs about this limitation
- Throw an exception (maybe not the best solution...)

Or a third alternative ??

**Comment by backbone87** [comment]
I dont think this is possible. The use-case you describe has a logical error. There is no way to 
distinguish between  "I dont want to update my password" and "I want to reset my password", because both use an empty password field. You need a separate checkbox for "Do you want to change the password?". Imho it is best to handle passwords words on standalone forms that is exclusively setup to handle password changes. In this case you dont need a checkbox, because the desire to change the password is expressed throu using this exclusive form.

**Comment by xabbuh** [comment]
I agree with @backbone87. There's nothing we can do in Symfony about this.

**Comment by nykopol** [comment]
I understand that there is no way to distinguish "don't update" and "reset" with the same value. But at least, this limitation should be pointed out in the documentation.

**Comment by backbone87** [comment]
Its no limitation tied to symfony, its a limitation tied to your implementation of the use-case.

**Comment by jakzal** [comment]
@nykopol if you feel something needs to be documented, please open a new issue (or better a PR) in symfony/symfony-docs.
