### ISSUE TITLE
[FrameworkBundle] config:debug command and yaml inline level

### ISSUE THREAD

**Issue by rpg600** [symfony/symfony#16882]
Hello, actually when we dump the configuration for an extension with the `debug:config` command it becomes hard to read when there is more than 3 level of indentation because the yaml switch to the inlined mode.

See https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/ConfigDebugCommand.php#L88

So my question is : is there any reason to keep the yaml inlined ?
I propose to add an option for the inline level or just set the inline level to a big number.

**Comment by zanderbaldwin** [comment]
Agreed. Increasing the level of indentation will bring the `debug:config` command closer to the same format of the `config:dump-reference` command, both of which are used for debugging bundle config during development.

Because the `config:dump-reference` command uses [`YamlReferenceDumper`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Definition/Dumper/YamlReferenceDumper.php) unlimited levels of indentation occur - this isn't possible using [`Yaml::dump()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Yaml/Yaml.php#L65) (used in `debug:config`).

Setting the indentation level to a high number won't cause any BC breaks (that I know of).

**Comment by javiereguiluz** [comment]
Closing it as fixed by #17538.
