### ISSUE TITLE
Inject nested parameters into service

### ISSUE THREAD

**Issue by zajca** [symfony/symfony#16924]
When I make parameters nested like this:
```
parameters:
  myParameters:
    parameter: 'xxx'
...
```
I can use this:
```
service
    myService:
      class: MyService
      arguments:    ['%myParameters%']
```
and access ```myParameters['parameter']```

But when I do directly:
```
...
arguments: ['%myParameters.parameter%']
```

I get:
The service "myService" has a dependency on a non-existent parameter "myParameters.parameter".

this works only if parameters are like this:
```
parameters:
  myParameters.parameter: 'xxx'
...
```

Is this only not supported or it's somewhere my fault?

I personally prefer more nested approach then repeating all parent parameters, then one can tend to shorting parameters names :)

**Comment by stof** [comment]
There is nothing like a nested parameters in Symfony. What you have is a parameter containing an array.

``$a['myParameters.parameter']`` and ``$a['myParameters']['parameter']`` are indeed not the same in PHP, which is why you get this error.

If you really want to access an element inside an array, you could use an expression to read the value from the parameter array.

**Comment by zajca** [comment]
Thanks for clarifying.

this is working:
```
parameter('myParameters')[parameter ]
```

**Comment by mrself** [comment]
@zajca `parameter` does not work for me. Verison: `3.2`.
