### ISSUE TITLE
[Console] router:match and expression language's condition breaks when using request variable

### ISSUE THREAD

**Issue by ymarillet** [symfony/symfony#16968]
Hi there

Having a route defined like this

``` php
class MyController extends Controller
{
    /**
     * @Route(
     *     "/mycontroller/{type}",
     *     name="my_route",
     *     condition="service('myservice').isKnownType(request.get('type'))"
     * )
     */
    public function testAction($type)
    {
        //do something here
    }
}
```

Makes the router:match to go crazy because the Request object is unknown to the command line

``` console
app/console router:matches /mycontroller/supertype
```

[RuntimeException]
  Unable to get a property on a non-object.

I believe that a request object should be created here. This is also a very simple example that could have a workaround, but this is not a discussion about that.

Note: the service function used in the expression language is an implementation of a custom expression language function, which is just returning a defined service
![ya rly](https://i.imgur.com/ttASWYC.gif)

**Comment by paradajozsef** [comment]
I confirm this in 2.7, 2.8 and 3.0.  Strace is like:

1. RouterMatcherCommand [gets traces](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/Command/RouterMatchCommand.php#L92) from TraceableUrlMatcher
2. TraceableUrlMatcher [matches pathinfo](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Matcher/TraceableUrlMatcher.php#L36)
3. match() tries to [match pathinfo by route collection](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Matcher/UrlMatcher.php#L92)
4. TraceableUrlMatcher::matchCollection() [passes request to expression language](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Matcher/TraceableUrlMatcher.php#L98)
5. But ```$request``` property in ```UrlMatcher``` is set [only in UrlMatcher::matchRequest()](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Matcher/UrlMatcher.php#L106)

I think ```$request``` should be passed because it makes kind of useless the router:match command if there is at least one route condition with request.

Status: Reviewed

**Comment by ro0NL** [comment]
@ymarillet what do you think of the idea to mock request on CLI? Ie. #21043 

Otherwise this probably relates to #21027

**Comment by tburschka** [comment]
It's not a console only bug. I'm having the same issue on a regular request.

**Comment by ro0NL** [comment]
Could you try #22636 :)
