### ISSUE TITLE
Web Profiler - DB icon doesn't appear when no query executed

### ISSUE THREAD

**Issue by unexge** [symfony/symfony#16976]
i have Symfony 3.0 and new toolbar. but if no query was executed DB icon doesn't appear

it seems like this:
![screen shot 2015-12-11 at 21 42 48](https://cloud.githubusercontent.com/assets/16212576/11754026/5f938748-a051-11e5-975c-80cd3f882b80.png)

**Comment by ogizanagi** [comment]
Hi @unexge ! Actually, it isn't a bug, it's a feature :smile: 
Since the new profiler/toolbar theme in Symfony 2.8+, when a data collector has nothing to show...well, it shows nothing in the toolbar! Thus we can get some space.

But there is indeed a bug in the fact the toolbar item wasn't entirely hidden.
However, it belongs to the [`doctrine/DoctrineBundle`](https://github.com/doctrine/DoctrineBundle) repository. You'll find above a PR fixing it.

**Comment by unexge** [comment]
Haha, nice feature :smile: 
Thanks for the PR.

**Comment by javiereguiluz** [comment]
@unexge just a minor comment: the panel will be displayed when some query is executed ... but also when there is some error in any entity configuration. So you'll never miss anything important related to Doctrine.

**Comment by unexge** [comment]
@javiereguiluz really nice. I liked the new toolbar and profiler, thanks for hard work :+1:
