### ISSUE TITLE
BCryptPasswordEncoder's encodePassword throws BadCredentialsException

### ISSUE THREAD

**Issue by chinmayshah24** [symfony/symfony#17039]
Is it correct to throw an `AuthenticationException`? It is thrown when the password to encode is too long.

Case: The user is trying to register a new username/password and the service is trying to encode the password for the user.

If the password is too long, the service will get an (unexpected) "AuthenticationException". Should it not be something like an InvalidArgumentException ?

**Comment by javiereguiluz** [comment]
I'm closing this because of the lack of feedback.

I'd say that at the end it's a matter of personal preference: throwing `BadCredentialsException` is not wrong and it's more specific than `InvalidArgumentException`. Likewise, throwing `InvalidArgumentException` would be correct too, but maybe too generic.

If none of the alternatives is much better than the other, it's better to maintain backwards compatibility and not change it.
