### ISSUE TITLE
[RFC] Add support for Websockets and real-time applications

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17051]
### Context

The next **RubyOnRails** version will include support for websockets ([read about it](http://nithinbekal.com/posts/rails-action-cable/) or [see the pull request](https://github.com/rails/rails/pull/22586)).

The next **Django** version will include support for websockets ([read docs](http://channels.readthedocs.org/en/latest/)).

The next **Spring Framework** version will include support for websockets ([see code](https://github.com/spring-projects/spring-reactive/))

### Question

  * What's the position of Symfony on this websocket/real-time apps trend?

**Comment by dupuchba** [comment]
- On one side I am not sure if it's the role of a HTTP centric framework like Symfony to bring Websockets to it's core
- On the other side it's becoming a "must have" on most web/native applications.

Great question @javiereguiluz , I personally don't have answers ^_^

**Comment by stof** [comment]
Well, all these language are running the webserver themselves, which is a requirement to do websockets. A PHP project generally runs using PHP-FPM behind a webserver communicating through FastCGI.
Doing websockets in PHP requires changing this setup. This is what ReactPHP does for instance.

But IMO, this does not fit in Symfony (you can still rely on Symfony components in your code though of course).

I think this is best kept as a separate PHP project (ReactPHP or one of the other alternatives whihc exist already) rather than creating a new Symfony component doing it (which would have to duplicate existing libraries). I don't think we would benefit from going the NIH way here

**Comment by dunglas** [comment]
Agree with @stof. However a cookbook entry explaining how to use React or [Ratchet](https://github.com/ratchetphp/Ratchet) with Symfony can would be nice to highlight than you can use websockets with the Symfony ecosystem too.

**Comment by leggetter** [comment]
For the cookbook:

Some examples of integrating Symfony with real-time frameworks (includes Ratchet): https://github.com/leggetter/realtime-symfony-examples

Slides from a talk I gave at Symfony live LDN:
https://leggetter.github.io/realtime-symfony/

Video of the above talk:
https://youtu.be/LX2KoVK7mqAl

**Comment by Sander-Toonen** [comment]
This topic brings up the biggest issue I have with Symfony (or to be fair, with PHP).

I love Symfony and I always try to use it when starting a new project. However, more and more, clients are looking for the 'real-time' experience. PHP is just not cut out for that at the moment. It lacks asynchronous/non-blocking features and although there is ReactJS, it just isn't good enough. It is possible to create two web stacks. One with Symfony and another for the websocket connections and then have them communicate using a message queue. However, this is way to complicated and in most of those cases I end up using only Node (or nowadays Meteor.js).

I agree with @dupuchba and think that this will definitely be a "must have" in the future and I am very keen on hearing the opinion of the core developers on this matter.

**Comment by tgabi333** [comment]
I think the question is: If i have a symfony application and a want to implement some real-time feature, how could i do it?

Long-poll ajax? Come on, nineties are gone.

Anyway we must change the webserver configuration for using websockets. No matter if we use nodejs or php.

In our symfony app we have everything we need for real-time: orm, services, response classes. I definetly want to use them with websockets either. 

But not in a separate project. Without keeping the application in one project, without sharing the the same container for http and websocket,  what argument do we have against socketio?

Building up another stack for serving websocket requests would push the developers to make better structured symfony applications.

**Comment by bitgandtter** [comment]
I agree with @stof the main issue is how this two tech are used and certainly there is no good on introduce any websocket implementation into base SF when it does not fit into the apache or fpm/fast-cgi delivery system. In the other hand ReactPHP does provide non-blocking func event driven approach and Ratchet to provide websocket integration. At the end you can easily integrate Ratchet/ReactPHP with SF and use the framework benefits.

**Comment by yellow1912** [comment]
I don't think PHP at the moment is fit to run well with websocket, PHP is not (yet) working well in this type of environment. In our system we fallback to nodejs (and now GO) for this when we need it :)

**Comment by J7mbo** [comment]
@tgabi333 The problem with shoving websockets into the framework core is that many of the things you provided as an example are blocking. Doctrine ORM, awesome (but slow) and blocking. Any HTTP calls you make have to be coded non-blocking and asynchronously.

As soon as you add something like that to the core, all the extra libraries the user chooses need to support that to avoid blocking the event loop.

**Comment by stof** [comment]
@Sander-Toonen I ended up using pusher.com to handle the websocket stuff (and the fallback for IE)

**Comment by harikt** [comment]
I have played with https://github.com/hoaproject/Websocket which is a nice library. So if people need, they still can use and integrate. If there is something better, yes, everyone can push that also.

**Comment by stof** [comment]
To be complete, here is the website of the Websocket library based on ReactPHP: http://socketo.me/

Regarding the hoa library, it looks like it is a synchronous server though. Am I right ?

**Comment by Sander-Toonen** [comment]
Before we get a listing of each and every library or service; The point is that these require people to build two separate web stacks. And then one might as well choose a technology that doesn't block in every possible way.

Some daydreaming: Wouldn't it be neat if we could somehow create a performant server in PHP that could asynchronously handle connections and io. This server could then even bootstrap Symfony and Symfony could then handle requests without the need to boot the kernel for each request. Doesn't that make much more sense from an architectural perspective?

**Comment by stof** [comment]
@Sander-Toonen this does not solve the issue. You still need a server listening on 1 port for HTTP and another server listener on the other port for websocket.
They probably cannot run on the same port as they talk a different protocol. And PHP-FPM is not only the issue. You would not have to reimplement CGI, but HTTP (replacing NGinx).

and anyway, this is a huge paradigm shift if you run a CGI or HTTP server in PHP, as it means you run a single long-running process handling all requests. In such case, you should better be running asynchronously (which is what ReactPHP does).

> Some daydreaming: Wouldn't it be neat if we could somehow create a performant server in PHP that could asynchronously handle connections and io? This server could then even bootstrap Symfony and Symfony could then handle requests without the need to boot the kernel for each request. Doesn't that make much more sense from an architectural perspective?

If you don't boot the kernel on each request, we would still have to reset many service between requests. The session, the security context and the database connection cannot be shared among all incoming requests, and so any service depending on them cannot either (which eliminates a huge part of the container actually). And a bunch of other services also rely on state being isolated per request (any Symfony profiler collector for instance, or the monolog buffering handlers).
So we would still have to create a separate container for each request (which is almost all work being done in the kernel booting, and we cannot have a single kernel with multiple containers).

There have been experiment about doing this (avoiding at least the need to reload class definitions for each requests). I don't remember the links though.

And regarding your idea of a server handling asynchronous IO too, this would not help much: as soon as you call the Symfony kernel to handle the request, you are in a synchronous world (the Symfony HttpKernel API is synchronous), which means that you cannot handle other requests while waiting for your database IO to complete (as you cannot go outside the kernel at that point to enter into it again at the end of the query).
Running asynchronously requires to expose an asynchronous API from the start. A synchronous API can be called inside an asynchronous API, even though it will kill the benefits of the async in case IO is performed, as it will be blocking IO; but an asynchronous API cannot be called from a synchronous one (well, you can embed a codebase written in an asynchronous way, but only if you block your synchronous API until the embedded async logic completes entirely and exits, which means it is still blocking IO in regards to the outside of your synchronous API, meaning your webserver still see a blocking API). And Symfony cannot become an asynchonous framework. It would require a non backward compatible rewrite of the whole project, which would actually make it a totally different project (and this is why there are already other frameworks for that use case, for instance ReactPHP)

**Comment by ProPheT777** [comment]
I work since a long time on [WebsocketBundle](https://github.com/GeniusesOfSymfony/WebSocketBundle) with reactphp and ratchet. 

some point back to my experience from websocket bundle : 

* Ratchet is a no go because he is outdated (Since php5.5 brings generator), doesn't support 100% of websocket protocol (no binary, no heartbeat) and no new development since long time :(
* As pointed out @stof, we will need a side application as server with an IO loop. (It work by running the same application, I currently do it, but it's not good - we should have a specific kernel for it)
* We will need to handle authentication between your application and the websocket (because everybody will asking for it)
* We will need to open the door for developper to handle sub-protocol (because it's very common)
* We will need a wire protocol between symfony application and websocket server in order to push messages from your app to the websocket. (For example I support AMQP, ZMQ and WS client) other way : HTTP, RAW SOCKET ?? 
* Also, do we need to bring a simple websocket or with overlay/sub-protocol (like PUB/SUB) because it fit with 90% of real time application instead of I -> O
* Should we support multi threading (pthread) ? 
* Since websocket run in a loop where symfony is running (and never shutdown) you will extra stuff (like ping SGBD to prevent disconnect, and probably more ...) 
* we can't natively handle wss from server side, php is not fast enough (require to proxy wss with stunnel).

Symfony is web centric (I mean Request / Response deal via PHP-FPM), so it's another paradigm which symfony is not designed for. 

Create a gateway to only push on websocket (pusher, pubnub, socketio) :question: 
Create a new Symfony brother, a new concurrency framework to build websocket application (Bring a lot of value IMO for all kind of server / worker app) :racehorse:
Keep Symfony as he is and integrate websocket support (like many bundles do it today) :x: 
Do nothing :question:

**Comment by leggetter** [comment]
Some really good points above. A few additional relevant points that are worth looking at:

## How does Laravel approach this?

Laravel provides an abstractions for [Event Broadcasting](http://laravel.com/docs/5.1/events#broadcasting-events) where the underlying broadcaster implementation is decoupled. Right now it has [three implementations](https://github.com/laravel/framework/tree/5.2/src/Illuminate/Broadcasting/Broadcasters); Pusher, Redis and to Logs (the gateway approach that @ProPheT777 mentioned?).

The pros of this are the loose coupling and that it works well for a common broadcasting use case. The cons is that it is restrictive: you have to use HTTP requests for client -> server communication, how do you achieve authentication? What about framework specific functionality e.g. Pusher Private channels that require custom authentication)

Creating abstractions in symfony for all the potential communication patterns ([simple messaging, pub sub, evented pub sub, RPC/RMI and Data Sync](https://leggetter.github.io/realtime-symfony/#50)) may be nice additions to the framework (*personally I'd go with evented pubsub).

## For the majority of production applications you are going to require HTTP fallback

WebSocket has been designed to offer the type of real-time communication that we require in modern applications. But older runtime environments and troublesome network infrastructure can still get in the way. At Pusher (where I work) we tend to have between 93 and 97% of connections via WebSocket and the rest use a fallback. So the solution will need an HTTP option to serve 100% of clients. 

// @cboden - any thoughts?

## Appendix

*Symfony + Redis (+ Ratchet)*

![Symfony + Redis](https://leggetter.github.io/realtime-symfony/img/realtime-web-stack-integration-self-hosted-symfony-ratchet.png)

*Symfony + Hosted service*

![Symfony + Pusher](https://leggetter.github.io/realtime-symfony/img/realtime-web-stack-integration-hosted-symfony-pusher.png)

**Comment by cboden** [comment]
@ProPheT777 
> Ratchet is a no go because he is outdated (Since php5.5 brings generator), doesn't support 100% of websocket protocol (no binary, no heartbeat) and no new feature since long time :(

0.4 is almost complete with binary messaging and heartbeat check. Generators are nice but not needed. Otherwise, Ratchet's job is to do WebSocket I/O...adding more features such as authentication are a job for another package on top of Ratchet, not the library itself. 

@leggetter Awesome! I agree, having a loosely coupled spec for Symfony is the way to go. Let the user choose their async implementation with the framework providing a protocol on how to communicate between it. Redis is a great bridge between the two stacks that they both can read/write to ([Predis Async](https://github.com/nrk/predis-async), [Redis React](https://github.com/clue/php-redis-react)).

**Comment by harikt** [comment]
> Regarding the hoa library, it looks like it is a synchronous server though. Am I right ?

Sorry, I don't know more about it. I would like @Hywan to look into the issue if he is interested in it.

**Comment by ProPheT777** [comment]
@cboden Glad to hear that ! (Sorry if I seemed rude against ratchet, if it was not my intention. I just realized it while reading myself ... :kissing:). 

I'm also in favor to offer a gateway and let user choose his implementation and not be coupled to symfony framewok. Also I don't think popularized redis as transport is a good thing, I mean lot of protocol / software are very well at this job (TCP, AMQP, STOMP, ZMQ, Redis, Nats,  NSQ, blabla ...).

**Comment by Hywan** [comment]
@stof @harikt `Hoa\Websocket` is not synchronous. It relies on `stream_select`, which is asynchronous. It is better to add quotes around “asynchronous” here because `stream_select` allows async stuffs but not ones as we usually mean.

**Comment by devekko** [comment]
could this C websockets low level library go upstream to PHP? 
https://github.com/warmcat/libwebsockets

on the other end of the spectrum

there is an Apache websockets module
https://github.com/disconnect/apache-websocket

**Comment by fesor** [comment]
@devekko, i'll prefer to have some abstraction layer which can use several backends (like this libwebsockets extension or amphp based solutions with message queue).

**Comment by davidwdan** [comment]
For anyone that's interested, we've built a realtime bundle for symfony that uses WAMP (Web Application Messaging Protocol).  We've made some pretty cool applications with it.

https://github.com/voryx/ThruwayBundle

**Comment by SoboLAN** [comment]
@davidwdan At this moment is it stable enough to be used in production ?

**Comment by davidwdan** [comment]
@SoboLAN I would consider it beta right now.  We've been using it in production, but it still needs some work, especially around debugging.

**Comment by javiereguiluz** [comment]
Closing this issue because it fulfilled its purpose: to initiate the discussion about Symfony + real-time apps. Now it's time for more specific discussions and for that we'll need new issues. Thank you all for your comments.

**Comment by Maxim-Mazurok** [comment]
@javiereguiluz so, is there any progress on WebSockets in Symphony? I'm using enqueue for amqp and they use Symphony async loop. And I want to use both enqueue and websockets in one async event loop. Currently, I can't do it because most WebSocket solutions rely on React's async event loop. And I'm not sure that it's possible to have two async event loops in one script.

**Comment by dunglas** [comment]
Now we have MercureBundle for that: https://symfony.com/doc/current/mercure.html

**Comment by Pierstoval** [comment]
My 2cents:

WebSockets are not compatible with HTTP/2. 

In order to bring "real-time capabilities" in the modern era, we must use protocols that can evolve. Hence [Mercure](https://symfony.com/doc/current/mercure.html) and Server Sent Events, which are compatible.

And if at one moment you complain because WebSockets are two-way (server->client & client->server), and SSE are one-way (server->client), just remember how you've been making "client->server" interactions in the past 25 years 😉

**Comment by Maxim-Mazurok** [comment]
> My 2cents:
> 
> WebSockets are not compatible with HTTP/2.
> 
> In order to bring "real-time capabilities" in the modern era, we must use protocols that can evolve. Hence [Mercure](https://symfony.com/doc/current/mercure.html) and Server Sent Events, which are compatible.
> 
> And if at one moment you complain because WebSockets are two-way (server->client & client->server), and SSE are one-way (server->client), just remember how you've been making "client->server" interactions in the past 25 years

While your answer is right and using HTTP/2 over WebSockets is somewhat reasonable, it still doesn't make me feel good.
My hosting of choice for prototyping purposes - Heroku [doesn't support HTTP/2 yet](https://help.heroku.com/JAOCNZ25/does-heroku-have-plans-to-support-http-2).
My implementation is based on WebSockets, uses two-way communication and I'm not feeling like reimplementing the whole thing, because our startup is still in the early stage.
So, I would be much happier if I could get WebSockets lib that works in the Symphony's async loop, or to get any clue on how to "friend" Symphony's async loop and React async loop.

**Comment by stof** [comment]
well, websocket needs a long-running connection so it cannot be implemented in a Symfony kernel directly (the same is true for SSE, but this is why we don't have a SSE component but a Mercure one, where the mercure hub is not written in PHP). In my own project (implemented way before Mercure became a thing), I'm using pusher.com to fulfill this role of a websocket hub (and I'm using it only as a server->client communication, so I could implement that with mercure if I was doing that from scratch).
Also, there is no such thing like a Symfony async loop at all.

On a side note, this is the issue tracker of the Symfony project, not of the Symphony one (which is a [XSLT-powered CMS](https://www.getsymphony.com/)).

**Comment by stof** [comment]
And regarding Heroku not supporting HTTP/2, not that SSE does not require HTTP/2. But it can *benefit* from it (unlike websocket), because it is built on top of HTTP.
Also note that in the case of using Mercure, you need HTTP/2 support on the mercure hub server, not on your Symfony app (as that's where the SSE will happen).

**Comment by Maxim-Mazurok** [comment]
> well, websocket needs a long-running connection so it cannot be implemented in a Symfony kernel directly (the same is true for SSE, but this is why we don't have a SSE component but a Mercure one, where the mercure hub is not written in PHP). In my own project (implemented way before Mercure became a thing), I'm using pusher.com to fulfill this role of a websocket hub (and I'm using it only as a server->client communication, so I could implement that with mercure if I was doing that from scratch).
> Also, there is no such thing like a Symfony async loop at all.
> 
> On a side note, this is the issue tracker of the Symfony project, not of the Symphony one (which is a [XSLT-powered CMS](https://www.getsymphony.com/)).

Sorry, it was a typo. I mean Symfony, of course :)

Yeah, you're right about async loop also... It seems like the [EventDispatcher extension](https://github.com/php-enqueue/async-event-dispatcher) being used. So I guess there's no hope to find a lib that uses it for WebSockets.

> And regarding Heroku not supporting HTTP/2, not that SSE does not require HTTP/2. But it can _benefit_ from it (unlike websocket), because it is built on top of HTTP.
> Also note that in the case of using Mercure, you need HTTP/2 support on the mercure hub server, not on your Symfony app (as that's where the SSE will happen).

Ok, so maybe I can actually run it on Heroku. I still won't get HTTP/2 benefits because all http traffic is going through their router. Anyway, thanks for the explanation.
