### ISSUE TITLE
$container->get('request_stack')->getCurrentRequest() === null in service created from factory

### ISSUE THREAD

**Issue by llewellynthomas** [symfony/symfony#17122]
I can wondering if there is any new changes with the request_stack service that it does not contain a request when you're trying to create a service using a factory method:

```
 <service id="service" class="%service.class%" >
     <argument type="service" id="service_container"/>
     <factory service="service" method="getBuildSettingsFromRequest"/
 </service>
```

On first page load we have this problem on second page load problem goes away, but if I delete cache (rm -rf app/cache/*) the problem re-appears

In symfony 2.5.5 we don't have this problem. I've change over to using the request_stack, as I was having similar problems with the request service.

**Comment by stof** [comment]
it depends *when* your service is created (and this was always the case). If you retrieve the service very early, the Request might not be in the container yet.

If this happens only when the cache is built, this may be because you retrieve this service in a cache warmer, which will indeed run before the handling of the request.

In any case, retrieving the request in the constructor of your service is a idea. It simply means that you are doing the same than a request-scoped service, except that the container cannot detect your mistake and block you from doing it. You cannot have a container-scoped service which has a configured based on the request, which has a shorter life than the container.

**Comment by iltar** [comment]
@stof I think you mean '_a bad idea_'?

My tip: only get the request from the stack when you need it.

**Comment by llewellynthomas** [comment]
@stof & @iltar, thanks for you're help, the class was written for symfony 2.0 and things have changed since then, I'll refactor it and inject the request object with a listener, probably saver.
