### ISSUE TITLE
InlineFragmentRenderer should create subrequest based on input request

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#17123]
In our project we have created our own `Request` object. This works great except when we are doing fragment renders in twig:

``` twig
{{ render(controller("AppBundle:Homepage:events")) }}
```

But now

``` php
public function eventsAction(My\Custom\Request $request)
```

fails because it is given a `Symfony\Component\HttpFoundation\Request`.

I found out that the problem is in https://github.com/symfony/symfony/blob/161f12ce0246c34a264e8bf0b8ce832fe31f861d/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php#L133

If I change

``` php
$subRequest = Request::create($uri, 'get', array(), $cookies, array(), $server);
```

to

``` php
$subRequest = $request::create($uri, 'get', array(), $cookies, array(), $server);
```

It works :)

Is this by design or can I submit a PR to fix this?

**Comment by iltar** [comment]
You have the object so you should be able to call it as `$request->create()` in this case.

_I think the underlying problem is, that we need a RequestFactory of some sort and not have the request being responsible for this. This way the Request is nothing more than an implementation such as the PSR variant._

**Comment by ruudk** [comment]
Yep but `create` is static. That's why I call it static.

**Comment by iltar** [comment]
As far as I know it's perfectly legit to call a static method from an object PoV.
