### ISSUE TITLE
[Filesystem] dumpFile() ignores umask settings

### ISSUE THREAD

**Issue by hboomsma** [symfony/symfony#17303]
`dumpFile()` will always create a file with `0666` permissions if the file system supports these file permissions.

Analog to the behavior of `file_put_contents` and other file handling functions, one would expect that the umask setting will be taken into account.

**Comment by DemonTPx** [comment]
I've run into the same problem.

`dumpFile` uses the `tempnam` method to generate a temporary filename, which always creates files using mode `0600`. See: http://php.net/manual/en/function.tempnam.php

In symfony/filesystem <3.0, this was not a problem, since a `$mode` parameter was present with the default value of `0666`.

**Comment by DemonTPx** [comment]
Oh, wait a minute... I see that my problem has already been fixed in master (not in 3.0.1). Thanks for that! :+1:

**Comment by xabbuh** [comment]
@DemonTPx Indeed, this was fixed in #17063 which will be included in 3.0.2.
