### ISSUE TITLE
[Validator] CacheInterface uses concrete implementation instead of abstraction

### ISSUE THREAD

**Issue by mvhirsch** [symfony/symfony#17312]
Hi,

I just realized (while writing unit-tests in my own code) that the [CacheInterface](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Mapping/Cache/CacheInterface.php#L44) does depend on the concrete implementation instead of the interface ClassMetadataInterface.

I think this is a bug, is it?
I could easily provide a patch (exchanging ClassMetadata with ClassMetadataInterface) if you agree.

**Comment by stof** [comment]
Changing the signature of the interface is not an easy patch: it is a BC break and so can only be done in major versions.

**Comment by aivus** [comment]
@stof I think we can expand signature without any issues.

**Comment by Ener-Getick** [comment]
@mvhirsch @stof I think we can at least add a ``@todo`` annotation to not forget it in 4.0. What do you think?

**Comment by robfrawley** [comment]
@stof Obviously this is minor, but it peeked my interest as a means to learn more about the policies Symfony uses to govern BC breaks and manage issues in general.

I noticed this was marked as an enhancement, which was surprising to me, as it registers as a bug in my mind - no different from someone accidentally committing a misspelled or otherwise completely invalid type hint (aside from the obvious distinction that this didn't render Symfony's usage broken and bring down everyone's kernel, as a completely misspelled type hint could).

Assuming the choice wasn't intentional (on quick glance I don't see the method perform any calls against the argument not defined in the interface), this implicitly removes an implied feature: the ability to use the provided interface to write a custom metadata class (I say "implied feature" as the interface's very existence provides this president in my mind: one would not provide an interface only to explicitly ignore it and utilize it nowhere). 

Anyway, I'm simply interested in becoming more familiar with Symfony practices and contributing guidelines --- this isn't an academic exercise to annoy you guys ;-) --- and I don't directly use Symfony's cache component at all, so this doesn't impact me in any manner. Seeing this issue simply offered as a reminder that I wanted to educate myself on Symfony's practices.

Thanks for any providing any insight!

**Comment by webmozart** [comment]
Thank you for reporting this issue @mvhirsch! The reason for this is that `ClassMetadataInterface` was created much later than `CacheInterface`, which meant that we could not change that interface anymore. I'll add this to 4.0.

**Comment by mvhirsch** [comment]
@fabpot Can you please tell, why this change won't be done in 4.0?

**Comment by fabpot** [comment]
There is nothing that can be done on 4.0 without an upgrade path starting in 3.x. I removed the 4.0 milestone just because of that. But I'm not opposed to the change per se.

**Comment by xabbuh** [comment]
I am closing here for the same reason as I closed #20542. It seems that no-one cares enough about this to create a PR providing an upgrade path for the existing implementation.
