### ISSUE TITLE
[Symfony 3] Form and OneToOne relation

### ISSUE THREAD

**Issue by gazouweb** [symfony/symfony#17496]
Hi everybody,

I have a Contact entity and a Media entity. In the Contact entity, I have a OneToOne relation with my Media entity.

```php
/**
 * @ORM\OneToOne(targetEntity="EvolBundle\Entity\Media", cascade={"persist", "remove"}, orphanRemoval=true)
 * @ORM\JoinColumn(nullable=true)
 * @Assert\Valid()
 */
private $photo;
```
So far, so good, then in my ContactType.php for the form I have this:

```php
->add('photo', MediaType::class,  array(
      'required' => false,
      'attr' => array(
            'class' => 'well'
      )
))
```
my MediaType.php 

```php
class MediaType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('alt', TextType::class, array(
                'required' => false
            ))
            ->add('file', FileType::class, array(
                'required' => false,
                'media_alt' => 'Alt',
                'media_url' => 'webPath'
            ))
        ;
    }
 
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefined(array(
            'data_class' => 'MonBundle\Entity\Media',
            'required' => false
        ));
    }
}
```
Here again all is well, when I displayed my form I have all my fields, when I submit form that the media fields are filled or not because I set required to FALSE, I have the following error:

```
Catchable Fatal Error: Argument 1 passed to MonBundle\Entity\Contact::setPhoto() must be an instance of MonBundle\Entity\Media, array given, called in /var/www/monprojet/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php on line 556 and defined
500 Internal Server Error - ContextErrorException
```

For information, this my function of controller : 

```php
public function addAction(Request $request)
    {
        $contact        = new Contact();
        $em             = $this->getDoctrine()->getManager();
        $translator     = $this->get('translator');
 
        $form = $this->createForm(ContactType::class, $contact);
 
        if ($form->handleRequest($request)->isValid()) {
            $em->persist($contact);
            $em->flush();
            $nextAction = $form->get('saveAndAdd')->isClicked() ? 'monproject_contacts_admin_add' : 'monproject_contacts_admin';
            $request->getSession()->getFlashBag()->add('success', $translator->trans('contacts.add.action.success') );
            return $this->redirect($this->generateUrl($nextAction));
        }
 
        return $this->render('MonBundle:Contacts:form.html.twig', array(
            'task' => 'add',
            'form' => $form->createView()
        ));
    }
```

Help please, if you want more information it's possible.
Thanks for advance

**Comment by xabbuh** [comment]
Please fork the Symfony Standard Edition and make the necessary changes that make it possible to reproduce your issue if you think the behaviour you experience is a bug or use [one of the support channels](http://symfony.com/support) if you just need some help for a problem your are trying to solve.

**Comment by gazouweb** [comment]
Sorry, I don't understand what you want me to do

**Comment by dkisselev** [comment]
It looks like your issue is more of a user support issue, Github issues are intended as a place to post specific bugs where Symfony itself is broken (or could beimproved). xubbah's asking you to start a new Symfony project and apply the minimal changes that break something to show what's broken.

I believe your issue might have to do with configureOptions in your MediaType, it calls the setDefined function, but the [documentation specifies that you need to call setDefaults](http://symfony.com/doc/current/book/forms.html#book-forms-data-class). The error message you're getting looks like the MediaType has returned an array of the form fields instead of a MediaType object, but you would need to use a debugger or do something like a var_dump to confirm that.

Give that a shot. It sounds like you might intend to use setDefined because of your required/not required configuration, but that's a support question, not a bug with Symfony, please ask your question in IRC or on Stackoverflow, and close this issue if it's not a symfony bug.

**Comment by gazouweb** [comment]
Sorry, it's true, I will not have the post here, thank you for the information I will look at it more closely and posting elsewhere if necessary.

**Comment by gazouweb** [comment]
Hi,
For information, I replaced setDefined by setDefaults and everything works.
Thanks.
