### ISSUE TITLE
Windows 10 console seems to now provide ANSI support without ANSICON.

### ISSUE THREAD

**Issue by rquadling** [symfony/symfony#17499]
`\Symfony\Component\Console\Output\StreamOutput::hasColorSupport()` will probably need updating as Windows 10 ConHost+CMD now seems to provide ANSI support without the need to use ANSICON.

Whilst doing that is/should be easy enough, I don't know how to get the terminal dimensions for `\Symfony\Component\Console\Application::getTerminalDimensions`.

**Comment by iltar** [comment]
Windows + gitbash for example isn't working as nice either (or powershell for that matter).

**Comment by foglcz** [comment]
Just noticed this thanks to composer, and it does not play nice at all. See below screenshot:

![w10console](https://cloud.githubusercontent.com/assets/767839/15277868/03649bb6-1b07-11e6-9437-7585519bc1ef.PNG)

It seems as if the escape sequence is not interpreted, maybe there's a windows-flavored-ansi?
Like \r\n vs \n ? :smile:

**Comment by Seldaek** [comment]
This has been fixed in https://github.com/symfony/symfony/pull/18385 but the fix doesn't really seem to work as per https://github.com/composer/composer/issues/5323

**Comment by rquadling** [comment]
I am running Insider Preview, so sorry for jumping the gun on this one.

**Comment by cirdog** [comment]
If this hasn't been mentioned before, the global workaround for Windows is:

```
C:\ProgramData\ComposerSetup\bin\composer.bat
(edit its content)
php "%~dp0composer.phar" %* --no-ansi
```

Adding the "--no-ansi" flag at the launch script of composer eliminates the need to flag it for every command.

**Comment by mlocati** [comment]
I'm posting here since it's the only open issue regarding color support on Windows.

A short history:
- On Windows 10 build 10586 Microsoft added support to ANSI colors, enabled by default
- With #18385, Symfony assumed that builds equals or greater that 10586 had color enabled
- Microsoft released Windows 10 build 14393: ANSI colors are still supported, but every executable must explicitly enable it
- So, with #19660, Symfony has disabled color support for builds different that 10586

I've managed to find some time to suggest the PHP core team a new function to enable ANSI colors under Windows: see https://github.com/php/php-src/pull/2103.
It's still under discussion, but the final implementation should be quite near.

When everything will be ready, I'll create a new PR to add color support for Symfony under newer builds of Windows.

**Comment by fabpot** [comment]
Closing as this is fixed now.

**Comment by kelunik** [comment]
Seems like the implementation is incomplete.

https://github.com/symfony/symfony/blob/5cf0a2ea8f32e86e6636c409ce92cf53ea098cb1/src/Symfony/Component/Console/Output/StreamOutput.php#L96

That makes an equality check, but I guess it's supposed to be `version_compare`?

**Comment by mlocati** [comment]
> That makes an equality check, but I guess it's supposed to be version_compare?

@kelunik Nope.
Microsoft added support to colored terminals in Windows 10.0.10586.
This feature was initially enabled by default; BTW, [next Windows versions disabled it](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/15617610--re-enable-enable-virtual-terminal-processing-by), and PHP have to enable it explicitly.
For PHP versions <7.2, we don't have control of that feature.

[Starting from PHP 7.2](https://github.com/php/php-src/pull/2103), PHP enables this feature on startup, and we have the `sapi_windows_vt100_support` function to check if it's enabled.
