### ISSUE TITLE
translate The CSRF token is invalid. Please try to resubmit the form

### ISSUE THREAD

**Issue by fyher** [symfony/symfony#17523]
hi, i havre the problem. In my form the text : The CSRF token is invalid. Please try to resubmit the form is not translate. I have the file translations/validator.fr.yml and i havre this in :The CSRF token is invalid. Please try to resubmit the form.

**Comment by paradajozsef** [comment]
Could you describe the steps, how to reproduce it? Which version you use, how did you setup? Or you could fork the symfony standard edition as the documentation suggests:
http://symfony.com/doc/current/contributing/code/bugs.html

**Comment by fyher** [comment]
symfony 2.7 
in the file validators.fr.yml i have : 
The CSRF token is invalid. Please try to resubmit the form.: 'Actualisez le formulaire svp'
csrf_message: 'Actualisez le formulaire svp'

**Comment by paradajozsef** [comment]
Sorry I don't see, that you just found a bug, or there is a problem with you configuration. To me it looks like just a configuration problem.

If you think this is a bug in symfony, please provide more information.

Otherwise, just go for the [symfony support](http://symfony.com/support), github used for reporting bugs. Thanks!

**Comment by fyher** [comment]
ok thanks i go to stack thanks
