### ISSUE TITLE
Improve the overriding of bundle templates

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#17557]
This feature has been asked by lots and lots of users in #15755, #17054 and #17407.
### Problem

1) You have installed `MyBundle` which contains this template:

``` twig
{# MyBundle/Resources/views/base.html.twig #}
{% block title '...' %}

{% block content %}
    {# a lot of contents here #}
{% endblock %}
```

2) You override that template in your app by creating `app/Resources/MyBundle/views/base.html.twig`.

3) In your own template, you want to override just the `title` block and reuse the original `content` block.

``` twig
{# app/Resources/MyBundle/views/base.html.twig #}
{% extends 'MyBundle::base.html.twig' %}

{% block title 'New title' %}
```

**This won't work and Symfony will show a _"reached nested level"_ error.** The only current solution is to copy+paste the entire original template (and keep it in sync forever if the bundle changes it).
### Solution

People asking for this feature suggest to add a new notation to tell Twig/Symfony that you want to override the original template, not your copy:

``` twig
{# app/Resources/MyBundle/views/base.html.twig #}
{% extends '!MyBundle::base.html.twig' %}

{% block title 'New title' %}
```

Some people (e.g. @jakzal) don't like the new notation. The problem is that `!` always mean "not", so it can be read as _"don't extend ..."_.

Since Twig prefers expressive syntax, maybe we could use a word to enable the special `extends` behavior?

``` twig
{# app/Resources/MyBundle/views/base.html.twig #}
{% extends original 'MyBundle::base.html.twig' %}

{% block title 'New title' %}
```

Comments? Thoughts? Better ideas? Thanks!

**Comment by xavierleune** [comment]
@javiereguiluz When I opened #17054 I digged into symfony internals to check if this was easy to do. Actually I think that a convention in the path is easier to implement and maintain. On the other hand, your proposal is easier to understand.
It seems that extends is an original tag from twig, so modify it's behaviour only in symfony can be misleading in some case. So I would prefer a convention in Symfony, but it can be anything else than "!".

**Comment by iltar** [comment]
My opinion will remain that bundles shouldn't provide full templates, especially not base templates as they belong in your application. If for some reason you do have re-usable templates, you can always use embed or include.

Given that people still seem to want this, I suggest a whole new tag as it's pretty much a new feature.

```twig
{% replace 'MyBundle::base.html.twig' %}

{% block title 'New title' %}
```

Because with the current setup, it would mean you can hack your way around A extending A.

**Comment by xavierleune** [comment]
@iltar actually "replace" is a wrong term. We really want to "extend" it. But we just want to bypass the bundle inheritance mechanism. So it can be a new tag but we need a better name (like "extends_original" or something like this).

**Comment by iltar** [comment]
So it's actually a flag to ignore overwriting when extending if the target template is the one you're overriding? It looks like the [extends tag is defined inside twig itself](https://github.com/twigphp/Twig/blob/93ec90b857460c1e8c43b5d218ca072d0441856c/lib/Twig/TokenParser/Extends.php) so that would mean a change in the twig core. If I understand the code correctly (first time I've looked this up), the [TemplateFinder](https://github.com/symfony/symfony/blob/582f4753a343f230fbe18b4e9a0747d48351ddfb/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/TemplateFinder.php#L62) loads the app templates last and overwrites anything from the bundles (please correct me if I'm wrong!). It means that at this point, the templates would have to be pre-parsed which would slow down the cache warmer in certain cases.

It looks like quite something complex to solve. Either you'd have to build overriding support into twig, or find a workable solution within symfony. I'm sure I missed something so if you have any other ideas, feel free to shout it out.

**Comment by xavierleune** [comment]
Last time I check (but perhaps I missed something) the method "HttpKernel\Kernel::locateResource" is called to find the template to extends (and any resource twig needs to access). That's where the bundle inheritance and template overriding logic is made. So a convention is very easy to implement here.

**Comment by hason** [comment]
I prefer solve this problem after upgrade to the [Puli](http://docs.puli.io). What about to add a new function into the [Puli Twig extension](https://github.com/puli/twig-extension/blob/master/src/PuliExtension.php#L104)? @webmozart 
```twig
{% extends resource_versions('/my-bundle/views/base.html.twig').first %}
```

**Comment by fabpot** [comment]
Symfony does not use Puli, so that does not help.

**Comment by Guite** [comment]
> actually "replace" is a wrong term. We really want to "extend" it

How about `extend_partial`?

**Comment by xavierleune** [comment]
@Guite It shouldn't have any mention of "partial", "replacement" or anything like that. This is an extends, we just don't want to use the automagic overriding system from symfony in this case.

**Comment by dunglas** [comment]
Can be `%` `+`, or anything else... I personally like `!` because it means "imperative" (like in YAML http://yaml.org/type/binary.html) but it can be confusing.

**Comment by patrick-mcdougle** [comment]
IIRC, maximum nesting level is a result of the xdebug extension, not of PHP. I think maybe all you have to do is increase the `xdebug.max_nesting_level = {int}` in your php.ini.

See [this stackoverflow answer](http://stackoverflow.com/questions/4293775/increasing-nesting-functions-calls-limit) for more details.

**Comment by xavierleune** [comment]
So so so... Any new idea to feed the debate ?

**Comment by fsevestre** [comment]
We're actually in this case in our current project.

From the Twig documentation (http://twig.sensiolabs.org/doc/tags/extends.html): "The extends tag can be used to extend a template from another one."
In theory, extending the twin template from the parent bundle or any other template should be the same.

For me, the `extends` tag should manage this use case nativelly.


But since it might not be that simple to change this behavior, like @dunglas I like `!`.

My only concern about that is adding a new notation only for this one use case :/
What happens if we use this notation to extend another template other than his twin from the parent bundle ? (e.g. layout.html.twig extending the base.html.twig)

--
We are using temporarily the workaround from @jockri (https://github.com/symfony/symfony/issues/17407#issuecomment-173923144) which is working fine except when using the `javascripts` tag which throw an exception: `An exception has been thrown during the compilation of a template ("You must add !PfdFrontBundle to the assetic.bundle config to use the {% javascripts %} tag in !PfdFrontBundle::layout.html.twig.`

**Comment by stof** [comment]
@fsevestre bypassing the overwrites has nothing to do with the extends tag actually. It is something related to the loading of templates. The extends tag cannot bypass the overwriting as it is not implementing it either.

**Comment by kisprof** [comment]
Other solution could be if we would register not only the **{bundleName}** namespace automagically in TwigBundle, but also **{bundleName}Original** but without the app/resources path, so we could use:
` {% extends '@{bundleName}Original/base.html.twig' %} `
` {% extends '@AcmeOriginal/base.html.twig' %} `

This would be similar to: http://twig.sensiolabs.org/doc/recipes.html#overriding-a-template-that-also-extends-itself

**Comment by xabbuh** [comment]
> Other solution could be if we would register not only the **{bundleName}** namespace automagically in TwigBundle, but also **{bundleName}Original** but without the app/resources path, so we could use:
`{% extends '@{bundleName}Original/base.html.twig' %}`
`{% extends '@AcmeOriginal/base.html.twig' %}`

A real solution will be more complex as bundle inheritance is not restricted to simple parent/child relations, but you can have actual inheritance chains like ParentBundle <- ChildBundle <- GrandChildBundle <- GrandGrandChildBundle and so on.

**Comment by yceruto** [comment]
Both the child and parent bundle templates have the same "logical" name (`@My/base.html.twig`) causing an infinite loop when the parent is loaded... 

In the meanwhile, this could be solved by **registering your own namespace for parent bundle** to avoid names collision :collision: e.g.:

```yaml
# app/config/config.yml
twig:
    # ...
    paths:
        '%kernel.project_dir%/vendor/acme/MyBundle/Resources/views': MyParentBundle
```
And then, extends from `@MyParent/base.html.twig` instead of `@My/base.html.twig` to make it work like a charm:
```twig
{# app/Resources/MyBundle/views/base.html.twig #}
{% extends '@MyParent/base.html.twig' %}

{% block title 'New title' %}
```
:muscle: :satisfied: :v:

**Comment by Pierstoval** [comment]
@yceruto Your solution is really nice, we could even add a feature to create aliases for bundles, like this:

```yml
twig:
    bundle_aliases:
        AcmeMyBundle: MyParentBundle
```
This would register two paths for the same templates, allowing a syntax like yours without having to deal with long paths.

This may also help almost all third-party bundles to have a really clean template inheritance system (like [javiereguiluz/EasyAdminBundle](/javiereguiluz/EasyAdminBundle) for example 😉 )

**Comment by xavierleune** [comment]
@yceruto nice workaround ! Thanks for sharing it !

**Comment by evelync23** [comment]
@yceruto very nice!! I have many and many templates with duplicated code from parent templates, maybe this should be documented as well?

**Comment by yceruto** [comment]
The good news! after removing bundles inheritance https://github.com/symfony/symfony/pull/24161 [the blocker](https://github.com/symfony/symfony/issues/17557#issuecomment-282576918) is out, so a solution would be possible soon, like define an exclusive namespace only for bundle `views` path (apart from the current one):
```yaml
twig:
    paths:
        # adding paths behind the scene into TwigExtension
        templates/bundles/FooBundle: Foo # added override path if it exists
        vendor/acme/foo-bundle/Resources/views: Foo
        vendor/acme/foo-bundle/Resources/views: FooConventionSuffix # exclusive
```
thus, one can decide when use the exclusive namespace to avoid this issue. Later, we could say use `@FooConventionSuffix` namespace (could be a preffix instead) to extend from the original templates and override just part of it using blocks.

**Comment by Tobion** [comment]
@yceruto proposal makes sense and I'm 👍 to do something like that.

**Comment by yceruto** [comment]
See https://github.com/symfony/symfony/pull/24264 for a built-in solution.
