### ISSUE TITLE
CRUD generator doesn't use FQCN in FormType

### ISSUE THREAD

**Issue by klein0r** [symfony/symfony#17692]
Example:

'datetime' field created the following form builder:

```
$builder->add('publishedAt', 'datetime')
```

Correct Version:

```
$builder->add('publishedAt', DatetimeType::class)
```

**Comment by javiereguiluz** [comment]
@klein0r thanks for reporting this issue. However, the CRUD generator is provided to Symfony by a bundle called SensioGeneratorBundle. Therefore, this issue should be reported to the repository of that bundle: https://github.com/sensiolabs/SensioGeneratorBundle/issues  As you can see, there are already some issues about this error.

That's why I'm closing this issue to keep the discussion in the other repository. Thanks!

**Comment by klein0r** [comment]
@javiereguiluz Thank you for the fast response and the explanation :+1: 
Sorry for opening the issue in the wrong repository - I'm very new to the Symfony universe :smirk:

**Comment by javiereguiluz** [comment]
@klein0r no worries, I did this mistake myself lots of times in the past. And welcome to the Symfony *universe*!
