### ISSUE TITLE
improve StringUtil::singularify or CollectionType

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#17764]
I have words like "subjectData" .. or "clientData"
and it's making "subjectDaton", "subjectDatum" ...

or improve CollectionType for custom add/remove methods

**Comment by javiereguiluz** [comment]
I'm afraid that Symfony considers that a feature instead of a bug. The singularify method "correctly" transforms `data` (plural) into `datum` (singular). Some people are against this "feature" but most Symfony developers seem happy with it or they just don't care. That's why I'm closing this issue as "won't fix". Thanks for understanding it.
