### ISSUE TITLE
[Monolog Bridge] Dependency issue

### ISSUE THREAD

**Issue by kleijnweb** [symfony/symfony#17808]
```
PHP Fatal error:  Interface 'Symfony\Component\HttpKernel\Log\LoggerInterface' not found in 
/home/jkleijn/Projects/php/kleijnweb/swagger-bundle/vendor/symfony/monolog-
bridge/Symfony/Bridge/Monolog/Logger.php 
```

This happens when I run composer update --prefer-lowest with symfony/http-kernel: ^3.0 symfony/monolog-bundle: ^2.8. monolog-bridge then claims v2.4.0 to be compatible, which is untrue because it depends on before-mentioned interface which was removed from symfony/http-kernel 3.0.

Adding symfony/monolog-bridge: ^3.0 resolves this issue. Not sure what can be done about it, but thought I'd report it anyway, if only to share.

**Comment by javiereguiluz** [comment]
@xabbuh you excel at spotting issues with dependency versions, so could you please check if this issue is legit? Thanks!

**Comment by xabbuh** [comment]
We could add conflict rules in all maintained branches of the MonologBridge in 2.x to conflict with HttpKernel >= 3.0. However, this will not solve the issue as Composer then would still install MonologBridge 2.4 which wouldn't get updated due to our update policy. Probably the best we can do is add conflict rules to all maintained branches and then wait until Symfony 2.3 reaches the end of support to bump the minimum required version of the MonologBridge in MonologBundle to 2.7.

**Comment by javiereguiluz** [comment]
@xabbuh [Symfony 2.3 ended its support on May 2017](https://symfony.com/roadmap?version=2.3#checker) so maybe we can now do the change you proposed here? Thanks!

**Comment by xabbuh** [comment]
I think we can close here. The HttpKernel is a requirement of the bridge since #19113.
