### ISSUE TITLE
Fresh installation of Symfony 3.0.2 project with no changes takes 300 ms avg to load -- too slow

### ISSUE THREAD

**Issue by rparsi** [symfony/symfony#17848]
My env (virtual machine):

CentOS 7, x64
8 GB memory
40+ GB
php 5.6

It takes on avg 300 ms for the app_dev.php page to load, which is quite slow.  How to speed this up?

**Comment by javiereguiluz** [comment]
@rparsi virtual machines are usually much slower than running native software. My question is: What was the average time before upgrading to 3.0.2?

  * If it was much slower, this can be a bug in the new Symfony version and we'll investigate it.
  * If it was similar, then you'll need to ask for support to the Symfony Community. These are the channels to do that: http://symfony.com/support

**Comment by dupuchba** [comment]
@rparsi does your host is on Mac OS X, there are usefully small issues with the NFS

**Comment by rparsi** [comment]
@javiereguiluz @dupuchba 
My vm is on a local server in the office.
Xeon E5-2450v2 @ 2.5Ghz x2 (dual cpu, 16 threads per cpu) 192GB RAM DDR3

The vm server itself has only a handful of vms (my dev team is small) and overall cpu/memory usage is low according to our devOps guy.

With Symfony 2.6, 2.7 the average load time of a new project (fresh install -- no changes by me) was 100 to 150 ms.  Starting with 2.8 it went up to 300 ms (average).  I was originally going to create new 2.8 based project but the bundles I'm interested got full 3.0 support (by now) so decided to just use latest symfony.

It's not a huge problem for now as my project will be an api with barely any ui, so majority of controller actions will be using JsonResponse, but it is concerning.

I will also ask in the irc channel.
So what's the average app_dev.php load time for you guys on a bare symfony3 project?

**Comment by javiereguiluz** [comment]
@rparsi thanks for providing more insights. Since you are going to ask in the support channels and since this error didn't appear on 3.0.2 but at least from Symfony 2.8, I'm going to close this issue. If we have some information proving that this is a Symfony problem, we can reopen this issue or create a new one.

---

You also ask about average load time for `app_dev.php`. My computer is very old (and I'm using PHP 5.6), but I get decent numbers both for simple pages:

![simple_pages](https://cloud.githubusercontent.com/assets/73419/13179265/68214ff4-d723-11e5-837b-8e3add4c0886.png)

and for complex pages with lots of queries and complex Twig logic:

![complex_pages](https://cloud.githubusercontent.com/assets/73419/13179267/6b8fad34-d723-11e5-9109-59fe305e7f03.png)
