### ISSUE TITLE
[web debug toolbar] Get toolbar height

### ISSUE THREAD

**Issue by vitek-rostislav** [symfony/symfony#17851]
I need to know height of web debug toobar to adjust my layout when toolbar is in two lines. Problem is, that the toolbar is emtpy on document.ready() and its height is 0 at that moment.

I would really appreciate some "toolbar content loaded" event in toolbar_js.html.twig template. 

Or any other suggestion?

**Comment by javiereguiluz** [comment]
@vitek-rostislav to be honest, my recommendation would be: "don't care about this".

In Symfony 2.7, the version you mentioned, the toolbar displayed two rows "frequently". In Symfony 2.8 and newer versions, the toolbar is optimized and rarely overflows to two rows.

Besides, I can't understand the need of adjusting the layout because of the toolbar. This toolbar is only displayed in the dev environment and if the toolbar hides something in your page, you can temporarily hide the toolbar itself.

**Comment by vitek-rostislav** [comment]
@javiereguiluz thanks for your reply. Seems that the best solution would be use the 2.8 toolbar :)

**Comment by xabbuh** [comment]
I agree that we shouldn't do anything here. And by the way, even if the toolbar looks really great, end the it still is just a developer tool. :)

**Comment by javiereguiluz** [comment]
Closing it for the reasons explained above.
