### ISSUE TITLE
[2.8] PHP 7.0 Support?

### ISSUE THREAD

**Issue by pculka** [symfony/symfony#17879]
The Component/Validator/Constraints/True.php is deprecated, though are there any possibilities this code will be parsed from within Symfony2 core? In case of a bundle which uses this constraint, I'll just dump the Bundle, but ...

**is it SAFE to assume that 2.8.x is PHP7.0 Ready?**

**Comment by javiereguiluz** [comment]
As far as I know we don't use those deprecated features in the core. If you find some usage of these deprecations, please open a new issue with their specific information. Thanks!

In [this blog post](http://symfony.com/blog/symfony-achieves-100-php7-compatibility) you have more information about Symfony + PHP 7 and in Travis CI logs you can see that even Symfony versions earlier than 2.8 are compatible with PHP 7 ([example](https://travis-ci.org/symfony/symfony/jobs/110777199)).

**Comment by pculka** [comment]
Thanks, are there plans to remove the conflicting files (for example like abovementioned class) from the branch?

**Comment by javiereguiluz** [comment]
@pculka due to our [Backwards Compatibility Promise](http://symfony.com/doc/current/contributing/code/bc.html) we can't remove those files in 2.x branches.

The good news is that those files were removed in 3.x and master branches. See for example: https://github.com/symfony/symfony/tree/3.0/src/Symfony/Component/Validator/Constraints  `True.php` is gone and you only have `IsTrue.php`.
