### ISSUE TITLE
[PropertyAccess] Issue with findAdderAndRemover()

### ISSUE THREAD

**Issue by tobske** [symfony/symfony#17907]
If you have an entity A with a one-to-many collection to entity B and you use a form for entity A with the option `allow_add` for the collection you can have the following issue:
If entity A only contains a methods `addB()` but doesn't contain `removeB()` the `PropertyAccessor` doesn't return any method in `findAdderAndRemover()` and then throws a `NoSuchPropertyException` in  `writeProperty()`.

**Comment by xabbuh** [comment]
Can you provide a concrete example please? Not sure I understand what you mean.

**Comment by paradajozsef** [comment]
You can reproduce it with a single entity. If it has addX() method, but doesn't have removeX(), then you will get this exception when trying setValue() with an array.

It's because finAdderAndRemover() searches for both addX and removeX. You have to ipmlement both of them.

If the decision is that this is not a bug, then at least we should mention this in the propertyaccessor documentation. Actually I can't find anything about adders and removers in the docs:
http://symfony.com/doc/current/components/property_access/introduction.html

**Comment by Simperfit** [comment]
@paradajozsef I was trying to look into this in order to fix it. It does not return an exception in master, I've tried with a Test class, it does return NULL when I have addX but not removeX.

If the property of the class does not exist or is not the same, it does Throw an exception in `getWriteAccessInfo`.

It is specific to a Symfony version ?

ping @xabbuh.

**Comment by xabbuh** [comment]
@Simperfit In your example, is the property accessible through some other method (a setter) or is it public?

**Comment by xabbuh** [comment]
ping @webmozart What do you think about this? Should we treat it as a documentation issue and improve the docs or is this to be considered a real issue (looking at the comments [here](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L591-L594) I tend to treat the current behaviour as intended)?

**Comment by Simperfit** [comment]
@xabbuh It was public, i've been trying to add a phpunit test for thatn but it passed. Then I've done it with 2 dummy entity and I couldn't reproduce it.

I've tester in master, not in 2.3

**Comment by xabbuh** [comment]
@Simperfit If the property is public, the property accessor will always fall back to access it directly. Looking at the code it doesn't seem that it changed between `2.3` and `master`.

**Comment by Simperfit** [comment]
Oh, sorry @xabbuh didn't understand that like that.

Now that it is private I've the exception. 
`Neither the property "test" nor one of the methods "addTest()"/"removeTest()", "setTest()", "test()", "__set()" or "__call()" exist and have public access in class "Symfony\Component\PropertyAccess\Tests\Fixtures\TestClassWithAddWithoutRemove".`

In Master the comments you've mentioned does not exist any more and this part neither.

https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L674
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L790


The Exception is thrown by https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L717
