### ISSUE TITLE
[Form] Add a built-in form_javascript twig function

### ISSUE THREAD

**Issue by egeloen** [symfony/symfony#17935]
Hey!

While trying to fix egeloen/IvoryCKEditorBundle#212 I have added a `form_javascript` Twig functions which allows to render form javascript related code where you want in the template. 

Doing so, allow to link javascript code to a specific form type, allow to render your javascript where you want in the page (often at the bottom of the page), allow to take benefit of the form theming inheritance (for example: form -> text -> textarea) and also define a standard way of linking javascript code to a form. 

I have decided to open the issue because my implementation is not new, it has been inspired by [GenemuFormBundle](https://github.com/genemu/GenemuFormBundle) and [DatetimepickerBundle](https://github.com/stephanecollot/DatetimepickerBundle) which both rely on the exact same concept and the exact same code is duplicated along different bundles...

Now my question is does it belong to the core or to a third party library? WDYT?

**Comment by iltar** [comment]
Do you have an example of form related javascript code?

**Comment by egeloen** [comment]
CKEditor is a good example, for each ckeditor form, you have to render some javascript code... But ti also applies to a datepicker, same for a range picker same...

Let's define a datetime picker using jquery in the form theming:

``` twig
{% block datetime_javascript %}
    <script type="text/javascript">
        $("{{ id }}").datepicker();
    </script>
{% endblock %}
```

Then, this block will be used for each datetime form type:

``` twig
{# Load javascript libraries (jquery + datepicker) #}
{{ form_javascript(form) }}
```

**Comment by mvrhov** [comment]
I'm wondering how come that I'm the only one hitting #6025 when using those 3rd party bundles.

**Comment by trsteel88** [comment]
(Y)

**Comment by trsteel88** [comment]
:+1:

**Comment by webmozart** [comment]
I like the idea! :) :+1:

**Comment by Babacooll** [comment]
Could this be extended to handle form collections javascript functionalities (such as add / delete) ?

**Comment by egeloen** [comment]
It should indeed be possible by creating a `collection_javascript` block but IMO, it should not go in the core as it is something specific to each project.

**Comment by dunglas** [comment]
Should we really add that to the core?
Client-side (JS/TypeScript/whatever) and server-side (PHP) code are more and more isolated in different apps.
IMO it's not a good signal sent to developers, it encourages mixing JS and PHP.
As we refused to integrate CKEditor as part of the core (the main argument was: the server-side code should be JS-agnostic), we should not merge such things unless there is no other way to do it (but AFAIK, this already doable outside of core).

**Comment by webmozart** [comment]
@dunglas Very good points. Any other opinions?

**Comment by HeahDude** [comment]
I think it can be very useful.

If symfony deciders don't consider this consistent within the core, it should be easy to make a `Twig_Extension` in a tiny, easy to support bundle with #17963 implementation and talk about it in the docs.

**Comment by javiereguiluz** [comment]
I like @egeloen's proposal. The idea of not mixing up PHP and JS is OK, but there are some ubiquitous form fields which can't work without JavaScript (editors and date pickers).

And this could also help us fix the issue of Symfony not allowing to add new forms dynamically, and forcing the user to write their own JavaScript over and over again, as explained here: http://symfony.com/doc/current/cookbook/form/form_collections.html#allowing-new-tags-with-the-prototype

**Comment by tkleinhakisa** [comment]
i think it would be a great addition and would ease the use of modern forms (dynamic add/delete, editors, datepickers, plugins to enhance selects elements...) and any custom complex form type
It only provides the ability to add some javascript linked to a form type but does not add a single line of javascript into core. Integrating something like ckeditor would require some javascript code, so in my opinion it's not the same

**Comment by dunglas** [comment]
> I like @egeloen's proposal. The idea of not mixing up PHP and JS is OK, but there are some ubiquitous form fields which can't work without JavaScript (editors and date pickers).

I fail to understand why? You can easily add editors and date pickers without mixing PHP and JS (e.g, add a class to add fields requiring such editors, and detect it in JS).

> And this could also help us fix the issue of Symfony not allowing to add new forms dynamically, and forcing the user to write their own JavaScript over and over again, as explained here: http://symfony.com/doc/current/cookbook/form/form_collections.html#allowing-new-tags-with-the-prototype

The user will require a different JS code anyway depending of the JS stack it uses. This must not be done the same way depending if you use React, Angular or  Ember. Not even taking into account moderner alternatives to JS...
IMO it's not the responsibility of Symfony to provide defaults for JS code, nor to encourage to mix it in PHP.

It's better to use tools from the JS ecosystem like NPM, Gulp, SystemJS, Webpack and so on to manage JS code and dependencies. It's even better to not use raw JS but use moderner languages (ES6, TypeScript...).
It's why we removed Assetic from the standard edition. Making Symfony aware of how the JS is handled is a step backward.

**Comment by webmozart** [comment]
I guess @dunglas is right. The problem @javiereguiluz describes can be solved in a different way - namely by providing a standard JavaScript-kit for jQuery+Symfony. People who use jQuery could use that kit (=easier than right now). Everybody else could still write their own (=same as right now). However, the `*_javascript` block is not a prerequisite for that feature and hence it's probably better not to add it.

**Comment by fabpot** [comment]
I'm :-1: for this addition for the reasons explained by @dunglas. Symfony devs should be able to use whatever frontend tools they need. jQuery? With all the buzz around new ways to write JS, I'm not sure this is even a good idea.

**Comment by stof** [comment]
I'm -1 for this as well. Javascript should rather be written in a way where you load a single JS file and the initialization is done in this file based on a class placed on the form inputs needing this initialization rather than putting inline JS for each field. The ``datetime_javascript`` example given above is the way JS was written years ago, not the way it should be written today (CSP forbids it for instance)

**Comment by egeloen** [comment]
I'm OK to not put it in the core but I think I will go with this solution in IvoryCKEditorBundle... And so, it will be documented this way in the bundle...

**Comment by WouterJ** [comment]
I still like this issue very much, it's a problem we are facing with the CmfTreeBrowserBundle as well.

The issue seems to be very generic, while the arguments against it seems to focus on some specific things that shouldn't be part of the feature:

 * The feature **doesn't imply any front-end design technique, framework, library**, whatever. It provides a generic way for form types to define some stuff that need to be added only once (e.g. javascripts)
 * The feature does only need to be implemented on Symfony, **Symfony core doesn't have to use it**. All form types of Symfony work perfectly without JS (they have proofen this for years already). This feature would only make it easier for some third party bundles like CmfTreeBrowserBundle and IvoryCKEditorBundle
 * The feature **isn't about mixing PHP and JavaScript**. The `*_javascript` block is part of the template, which is 100% front-end already. If you use the form types to process a REST request, the template isn't used and no JavaScript is outputed either.

Currently, for form types needing JavaScript (Bundles mentioned before), there are 3 ways to do it now:

 1. Create a custom block/function and *tell the user to execute* the function in the template somewhere
 1. Include it in the `*_widget` block, resulting in *many redundant resource requests* when the type is used multiple times
 1. Don't include it at all and *tell the user to include* the resource in the head/body explicitly

(1) and (3) are both a less-good developer experience (they rely on the developer to do some action) and they make a template aware of the form type that it renders. (2) is a bad user experience, as loading the page takes longer.

**Comment by egeloen** [comment]
For the record, I will create the IvoryFormExtraBundle which will provide a `form_javascript` and `form_stylesheet` and then suggest to use it if you want to take benefit of this feature. For now, I have a working bundle but some more tests need to be added. A release is planned in the next days...

**Comment by webmozart** [comment]
@WouterJ AFAIU it should be sufficient to add one single JavaScript to all pages in questions and do the checks for different field types in that script?

**Comment by egeloen** [comment]
@webmozart The issue with such approach is that the IvoryCKEditorBundle, GenemuFormBundle, DatetimepickerBundle and CmfTreeBrowserBundle should not exist at all and the user should manage JavaScript itself without any integration...

Is it what you mean by `do the checks for different field types in that script`?

**Comment by iltar** [comment]
@webmozart You mean everything in 1 big file?
http://webpack.github.io/docs/code-splitting.html

**Comment by webmozart** [comment]
@iltar I'm no JavaScript expert, but I'm thinking about one entry point that lazily loads other required code in a way similar to what you just linked.

@egeloen If a developer using those bundles needs to explicitly take care of loading the JavaScript, that means they can also optimize how those scripts should be bundled. If bundles do that automatically, that's a bit more complicated. Users would have to overwrite the *_javascript blocks of all types to return nothing first.

**Comment by egeloen** [comment]
For those who are interrested: https://github.com/egeloen/IvoryFormExtraBundle

**Comment by Soullivaneuh** [comment]
I quite agree with @wouterj. Adding a `form_javascript` tag does not mean we manage javascript, but we let the possibility to the bundle maintainers and the devs to add some JS definition to form types options.

As you can see, many bundles are doing this with the same way and now a special bundle appear for the `form_javascript` and `form_stylesheet` functions.

IMHO, this should be re-thinked. :-)

**Comment by greg0ire** [comment]
I would be against mixing js code inside twig. Instead, I think data attributes should be used whenever js needs some data from the server. I also think there could be a service that, when given a complicated, composite form with needs for several different js to work properly, could list said js files in a deduplicated manner for use by whatever frontend tool the user want to pipe them into.

This implies that there should be some way to associate a form with a js, preferably outside the form itself so that coupling is loose. Same could be done for css, by the way. Something like this:

```
form:
   js:
       My\Form\Type:
            - a.js
            - b.js
       My\Form\OtherType:
            - a.js
            - c.js
   css:
       You\Get\The\IdeaType:
…
```

Building a form with both types and feeding it to this service would yield `[ 'a.js', 'b.js', 'c.js' ]`

**Comment by stof** [comment]
Well, solutions based on a block in the form theme were all about putting some inline JS code during the rendering of the form, which defeats all JS best practices (the first one being that it forces you to load the JS dependencies, for instance jQuery, before the body of the page, otherwise the inline code breaks). The solution of having a block renderer for each FormView is *not* suited for loading external files *once*, unless you do crazy things inside these blocks (potentially needing Twig extensions to implement these crazy things). and if you go for such crazy things, you could do them in ``form_widget`` as well potentially.

GenemuFormBundle, DatetimepickerBundle and IvoryCKEditorBundle all suffer from this (the dependencies are loaded several times), making their implementation a no-go for anyone caring about frontend performance (and also for anyone caring about CSP btw).

So I don't think this will be re-evaluated for the core.
A separate system like the one suggested by @greg0ire might be more interesting. but I don't think it needs to be implemented in Symfony itself. It could totally be built in userland, with a function receiving a FormView object and traversing it to find all types used in it, to collect the needed dependencies based on an external config. And this is clearly something which should be tried outside Symfony first to see whether it is worth it.

**Comment by javiereguiluz** [comment]
I think we're focusing too much on the problems instead of the solutions. Apparently, all the popular Symfony bundles "suffer" from this problem. OK ... but, what can do Symfony to help them fix this problem?

**Comment by stof** [comment]
@javiereguiluz the solution is simple: write unobstrusive javascript binding itself based on a class added on the field (which does not require any new feature), and ship your JS code as an external file which can be loaded a single time, by the preferred mean (bundled with other files for instance, etc...); As long as bundles want to write inline JS code, they will suffer from these issues (and then, they can just put it in ``form_widget`` today, as done by IvoryCKEditorBundle is some cases btw)

Then, a feature like the one suggested by @greg0ire could help loading the file only on necessary pages (but it may be harder to integrate it with your frontend build process then, so some cases may just want to bundle the files with other JS code instead).
And discussion about such a feature should happens elsewhere than in a closed issue asking for a different solution.
