### ISSUE TITLE
[Security] $attributes can be anything, but RoleVoter assumes strings

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony#18042]
There are no limitations on the $attributes voted on, but the RoleVoter assumes the attributes are strings. The ExpressionVoter for example expects Expression(s) as attributes. The only reason the RoleVoter does not warn on the "blind" strpos, is because Expression has a __toString method.
So currently, one cant use classes (`Permission`) as attributes that dont implement __toString.
I dont know if any other voter blindly expects string attributes -- this has to be checked.

Either the VoterInterface contract should be changed to indicate the use of "stringable" attributes or the RoleVoter needs to take non stringable attributes into account.

**Comment by WouterJ** [comment]
Given that passing objects as attributes is already used with the ExpressionVoter, I think we should add a check for string (or object implementing `__toString()`) in the RoleVoter and RoleHierarchyVoter.

**Comment by backbone87** [comment]
something else which i discovered around $attributes: the new abstract class Voter explicitly grants as soon as one attribute is granted (logical **OR**), but this behavior is nowhere mentioned neither it is dictated by the VoterInterface

**Comment by WouterJ** [comment]
@backbone87 the abstract class is for some very specific use cases (which turns out to be the most common use cases btw). For all other use cases, people can implement the interface themselves.

The behaviour is mentioned in the code: `// grant access as soon as at least one attribute returns a positive response` and in [the docs](http://symfony.com/doc/current/cookbook/security/voters.html): `Your job is simple: return true to allow access and false to deny access.`
