### ISSUE TITLE
[feature suggestion] use browser sync in the server:run command

### ISSUE THREAD

**Issue by tykayn** [symfony/symfony#18062]
it would be great if the embedded webserver could implement hot reloading like we can have it with gulp + browser-sync.
and it would be great to not have to setup more dependencies to do so.
This feature would be very welcome :)

**Comment by javiereguiluz** [comment]
@tykayn thanks for opening this issue to propose a new feature.

When you talk about "hot reloading", are you referring to application assets?

**Comment by javiereguiluz** [comment]
@tykayn please provide more details about what you'd expect from this "syncing feature". Thanks!

**Comment by jorge07** [comment]
I use to configure the live-reload via gulp/grunt. 
90% of my symfony apps doesn't have frontend anyway. 
Nodejs is the recommended tool to process assets on the symfony doc, so livereload.js is just another package to install, like uglifyjs, configure the watchers and you are done.

**Comment by jakzal** [comment]
It's really unclear what you're asking for guys.

**Comment by tykayn** [comment]
@javiereguiluz the idea is, i run the command server:run ,
my default browser opens a tab to the app_dev.php page, and when i save a change in my IDE on a php file, a twig file or a config (yml) file, the tab reloads automatically.

I use gulp with a browser-sync task and watchers on some src/ and app/ files normally for that, but a built in feature would be great.
Is it clearer this way ? :)

**Comment by dunglas** [comment]
I like the idea. But it should be implemented as a bundle (or maybe just as a Node.js package) and not in core.

**Comment by javiereguiluz** [comment]
I agree with @dunglas. I'm :-1: to include this in the Symfony core.

Besides, I'm not sure it's such a good idea. Reloading pages when styles changes makes sense. But reloading pages continuously as soon as you change any file in your Symfony application can become a bit annoying.

---

In any case, since at least two Symfony Core members are against this addition, I'm closing it as "won't fix". @tykayn this time the proposal didn't make it, but please keep sending proposals to improve Symfony so we can discuss them. Thanks!
