### ISSUE TITLE
[DX][Profiler][Doctrine] Show where the query was made

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#18235]
It is sometimes tedious to find what caused the exact query, visible in `Doctrine` panel, to be run.

It would be cool if next to `Explain query` button there was a `Show stacktrace` button. Even if it would be visible only for people with Xdebug enabled.

**Comment by PeterFour** [comment]
The only way to do this was to use Blackfire for me and it was not that much efficient time-wise (but still better than crawling all the code). Would be really usefull to debug some bad or massive queries

**Comment by MacDada** [comment]
> it was not that much efficient time-wise

@PeterFour It could be optional: only collected when a certain cookie is present.

**Comment by PeterFour** [comment]
@MacDada Well I know I was just saying that even using Blackfire it was not perfect so having a Stacktrace would be probably easier to use, especially because it's already using the Doctrine Profiler Panel

**Comment by fabpot** [comment]
I've not checked but this is part of DoctrineBundle, not Symfony, right?

**Comment by MacDada** [comment]
> I've not checked but this is part of DoctrineBundle, not Symfony, right?

@fabpot You're [probably right](https://github.com/symfony/symfony/issues/18234#issuecomment-199213153).

**Comment by MacDada** [comment]
[I recreated the issue in DoctrineBundle repository](https://github.com/doctrine/DoctrineBundle/issues/525).

**Comment by sustmi** [comment]
Just for reference, this feature is already available in Doctrine bundle: https://symfony.com/blog/new-in-doctrinebundle-1-11-0#store-backtraces-when-profiling-queries (PR: https://github.com/doctrine/DoctrineBundle/pull/954) .

You just need to enable it by setting `doctrine.dbal.profiling_collect_backtrace: true` (I set it to `'%kernel.debug%'` instead because it is the default value of `profiling` setting that this feature depends on).

Web search got me here and from this conversation it looks like it may not be available yet.
