### ISSUE TITLE
[DX][Profiler] Auto-dump Doctrine query results

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#18234]
I often want to dump Doctrine–fetched data and do that manually.

How about auto-dump feaure, so that I could see the data in the web panel?

![screen shot 2016-03-19 at 17 36 44](https://cloud.githubusercontent.com/assets/136261/13899911/cbfc55f4-edf9-11e5-84fa-d8f55710bb91.png)

**Comment by iltar** [comment]
With lots of data that would be quite heavy. I suggest to only show the entity + id, similar to how the Security logger will show you with isGranted calls.

/cc #18149

**Comment by stof** [comment]
this should be asked in DoctrineBundle, not here, as this panel is provided in DoctrineBundle (btw, I think there is already a feature request for that)

**Comment by javiereguiluz** [comment]
@MacDada thanks for proposing this feature. However, I'm closing it because of the reasons explained by @stof:

1. The Doctrine profiler panel is created by the DoctrineBundle (this is the DoctrineDataCollector class: https://github.com/doctrine/DoctrineBundle/blob/master/DataCollector/DoctrineDataCollector.php)
2. There is already a (very old) issue asking for this feature: https://github.com/doctrine/DoctrineBundle/issues/110
