### ISSUE TITLE
Form theme _self with extends from a variable

### ISSUE THREAD

**Issue by SebastienTainon** [symfony/symfony#18238]
Hello,

I'm facing a bug in Twig when I'm using `{% form_theme _self %}` in a nested template with a dynamic parent file : `{% extends extend_template %}` where `extends_template` is a variable passed from the controller.

It's pretty easy to reproduce this, I've made a symfony standard edition fork for this: https://github.com/SebastienTainon/symfony-standard/commit/ac6121a67f6d485e58edb2f266405eb183f75208

My use-case: I want to specify which is the parent template to use from the controller depending on the request (either new.html.twig or edit.html.twig for example), and I'd like also to customize the rendering of one field of the form, in any of these cases.

When the code is executed, I have this error:

```
Variable "extend_template" does not exist in AppBundle:edit.html.twig at line 1
500 Internal Server Error - Twig_Error_Runtime
```

Nevertheless, if I try:
- to put directly {% extends 'AppBundle:parent.html.twig' %}
- to change _self by an other file
- to remove the {{ form_start(form) }} and {{ form_end(form) }}
then I get no error.

Note that this issue is very similar to https://github.com/symfony/symfony/issues/5284 except that here it's about a variable passed from the controller.

Thanks for your help!

**Comment by SebastienTainon** [comment]
Any update on this?

You can checkout my symfony fork to reproduce this bug: https://github.com/SebastienTainon/symfony-standard/commit/ac6121a67f6d485e58edb2f266405eb183f75208

Thanks!

**Comment by jakzal** [comment]
I confirm this issue exists

**Comment by stof** [comment]
this is a documented limitation of using ``_self`` as form theme: it means you are using the template with 2 different contexts:
- as a rendered template with the context coming from the controller
- as a form theme with the context coming from the form rendering engine

So dynamic inheritance will indeed not work here as it will rely on variables defined only in one of these contexts.
The workaround is simple: move your form theming to a dedicated template instead of mixing responsibilities in your template

**Comment by jakzal** [comment]
Alright, closing since this is a documented limitation.

@SebastienTainon there's also another solution given in [the ticket you referenced](https://github.com/symfony/symfony/issues/5284#issuecomment-18890218).
