### ISSUE TITLE
Missing Symfony\Bridge\PhpUnit\DnsMock in stable branches

### ISSUE THREAD

**Issue by remicollet** [symfony/symfony#18319]
Some tests use this new class

    Symfony/Component/Validator/Tests/Constraints/UrlValidatorTest.php
    Symfony/Component/Validator/Tests/Constraints/EmailValidatorTest.php

Problem: this class only exists in master, not in other stable branches

**Comment by xabbuh** [comment]
You need to use our [phpunit wrapper](https://github.com/symfony/symfony/blob/2.3/phpunit) to execute the Symfony test suite which takes care of installing the right version of the PHPUnit bridge (see https://github.com/symfony/symfony/blob/2.3/phpunit#L55):

```bash
$ ./phpunit
```

see also http://symfony.com/doc/current/contributing/code/tests.html#running-the-tests

**Comment by ymc-dabe** [comment]
I just came across this, while trying to [update Debian's Symfony packaging for 2.8.4](http://anonscm.debian.org/cgit/pkg-php/symfony.git/log/?h=wip/dabe/2.8.4).

Besides the fact, that I fell it's kind of curious you can not use the version of PHPUnit Bridge that is shipped with Symfony to test Symfony, it is a real problem for the [Debian packaging of Symfony](https://tracker.debian.org/pkg/symfony): We simply can not download things during build time.

@xabbuh Do you intend to hold on this? In this case we, that take care about Symfony in Debian, have to find a way to deal with this situation.

**Comment by remicollet** [comment]
Yes, the initial report was for downstream Fedora Packaging.
Same rules ;)

**Comment by xabbuh** [comment]
So the general issue for both of you is our custom testing process which requires the installation of additional packages if I understand you correctly?

**Comment by remicollet** [comment]
Additional packages is not an issue, as soon as dependencies are clearly described (composer.json, require-dev)

Using a git snaphot of phpunit-bridge @dev-master while packaging a stable version seems just terribly strange.

**Comment by remicollet** [comment]
To summarize, how can you qualify the code, if you don't use it ?  ;)

**Comment by nicolas-grekas** [comment]
Running the tests require the custom phpunit that is shipped with Symfony.
We don't ship e.g. `\PHPUnit_Framework_TestCase` and the code is still correct.
The situation is exactly the same here.

**Comment by remicollet** [comment]
Sorry, but I don't think this is the same.

PHPUnit is just an external dependency (yes, which need to be tweaked to use current symfony version rather than bundled components)

phpunit-bridge IS part of symfony.

**Comment by nicolas-grekas** [comment]
@remicollet it's not: the phpunit bridge is excluded from the autoload map and requires an explicit composer requirement to be enabled. Truth is I made a mistake in #18272 on this very topic, to be reverted in #18389...

**Comment by ymc-dabe** [comment]
The problem for Debian comes down to two things (and I guess it's similar for Fedora)::

1. We can not trust to have network access during build time, since most buildd's simply do not have. Thus we can not use composer to download/install anything to run tests, as it now is done by Symfony's [phpunit wrapper](https://github.com/symfony/symfony/blob/2.3/phpunit#L57).

2. We can have only one version of a package for a distribution (e.g. sid) in the archive. As we build a package for each Symfony Component/Bundle/Bride out of a single source package (see: [src:symfony](https://packages.debian.org/source/sid/symfony)), we can not provide [php-symfony-phpunit-bridge](https://packages.debian.org/sid/php-symfony-phpunit-bridge) in version 2.8.4 and version 3.1@dev the same time - and thus can not use a newer version *just for testing* and ship an older one *to be used otherwise*.

To fix this in Debian itself, I can think of the following:
* Simply skip the failing tests
 - Very bad, since in past the tests prevented us from quite a lot of otherwise undetected problems with the packaging
* Patch src:symfony in Debian to contain the missing pieces
 - Hard to maintain in future
* No longer build php-symfony-phpunit-bridge form src:symfony in Debian and maintain a newer version in a separate package
 - No LTS support from Symfony beyond 2.8.x before the Debian/stretch freeze, which is expected later this year
 - Might break things in future (e.g. an updated php.symfony-phpunit-bride is needed for tests, but will not work for the rest)
 - Hard to maintain, as well (might less harder than above in the beginning, but will be most likely harder, once support for the version in Debian/stretch is no longer maintained by Symfony)
* Ship the missing pieces just to run tests inside a vendor dir within the source package and use composer to install (but not download) it.
 - No idea if this really would work.
 - No idea if something similar can be done for the [DEP-8](https://anonscm.debian.org/gitweb/?p=autopkgtest/autopkgtest.git;a=blob_plain;f=doc/README.package-tests.rst;hb=HEAD) (as-installed) testing

I don't like any of those approaches and rather would like to see the issue gone in Symfony itself.

@xabbuh The testing is not that custom, it basically is what used to be done to run tests in Symfony in past ([take a look at debian/rule lines 94 and 95](http://anonscm.debian.org/cgit/pkg-php/symfony.git/tree/debian/rules?h=debian/2.8.3%2bdfsg-1#n94)).
@nicolas-grekas Thanks for the fix, but I think it will not solve the problem for Debian.

**Comment by nicolas-grekas** [comment]
@ymc-dabe if you need to run tests, then I suggest to just skip time-sensitive and dns-sensitive groups. This way, the related tests will be excluded.
symfony/symfony does not "provide" (in the composer way) symfony/phpunit-bridge, which means you maybe should not build the bridge out of symfony/symfony yourself. Thus is you want to allow running tests, you'd need to provide symfony/phpunit-bridge 3.1 alongside with any versions of symfony/symfony 2.3 & up.

**Comment by nicolas-grekas** [comment]
#18392 should fix this on our side (above comment still applies :) )

**Comment by ymc-dabe** [comment]
@nicolas-grekas Thanks, this could work out for us. I'll discuss it within Debian's Symfony Maintainers.

**Comment by xabbuh** [comment]
@ymc-dabe I am a bit surprised that this worked for until recently. Or did you do some custom tweaks after we switched to the our custom `phpunit`?

**Comment by ymc-dabe** [comment]
@xabbuh It was not a problem up to 2.8.3 and we did not do any custom tweaks regarding it since you introduced it in August 2015.

**Comment by remicollet** [comment]
> symfony/symfony does not "provide" (in the composer way) symfony/phpunit-bridge, which means you > maybe should not build the bridge out of symfony/symfony yourself. 

So, why is it part of this git repo ?
it should probably be removed from here, and be maintained and released as a separate project.

All is about consistency

**Comment by ymc-dabe** [comment]
@remicollet I agree with you and moving symfony/phpunit-bridge out of symfony/symfony (like [it was done with symfony/security-acl](https://github.com/symfony/symfony/issues/14718)) looks like the right approach to me and it would work out for Debian. For now we decided to simply skip out the affected tests.
