### ISSUE TITLE
[RFC] Consider using safe placeholders in our codebase

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#18345]
### Problem

The recent [JavaScript debacle](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) due to a trademark dispute should be a serious warning about the dangers of using real names for naming things in our code.

It's not a widespread practice, but Symfony uses real people names, real company names and real websites in some tests.

### Solution

Wikipedia publishes a [list of safe placeholders](https://en.wikipedia.org/wiki/Placeholder_name) for any need. I propose to enforce the use of these placeholders in our codebase, to avoid any problem:

* Companies: `Acme`
* People: `John Doe` and `Jane Doe`
* Websites, domains: `example.org` and `example.com`
* Variables: `foo`, `bar`, `baz` and `qux`

**Comment by theofidry** [comment]
Is it that much of a problem? I think having names in the code base humanise the project. Unlike the JavaScript debacle you are referring to, AFAIK real names are using only as dummy values in tests and docs, if Symfony was asked to remove the usage of one of those names for whatever reason, it wouldn't be a problem right?

**Comment by javiereguiluz** [comment]
@theofidry yes, it only refers to tests like this one:

![sample_test_code](https://cloud.githubusercontent.com/assets/73419/14113703/6417a550-f5d4-11e5-9fbc-b05d492ac74b.png)

In this example, we are using personal domains (`dunglas.fr`), a company name and domain (`les-tilleuls.coop`) and another real website (I guess it's a client of the other company) (`lostinthesupermarket.fr`).

We can trust @dunglas because we know him. But what if someday he leaves that company and the new managers go crazy and sue us for "misusing" their company name? And what if @dunglas decides to change his personal website (`dunglas.fr`) and the new domain owner points to something malicious (but no one would click on that domain! Yes, except by accident, and we don't want to be associated with malicious things). I could give you more examples, but I guess you get the idea behind this RFC issue.

**Comment by theofidry** [comment]
>I could give you more examples, but I guess you get the idea behind this RFC issue.

I do, it boils down choosing between providing a little nicer experience to the developers (it's arguable, but I do prefer seeing real names that `John Doe` or `Dummy`) and being more cautions regarding the potential troubles Symfony may have by using real names.

I'm just saying I prefer the first choice in Symfony case because I do not see (at least right now) who this could be an issue: if @dunglas or his company becomes a bad guys and want to sue Symfony for misusing their company names, Symfony could agree on not using those names anymore and it won't go beyond that. Malicious links are a bit tricker, but hey, we could point to google.com and Google being hacked an replaced by a malicious website right ? :P

Obviously it's not for me to take the decision, but I just want to share my opinion as a regular Symfony user on this :)

**Comment by Tobion** [comment]
This is is non-issue as it's only about values in test cases?! If somebody feel offended, we can change it easily. No need to premature change things.

**Comment by Tobion** [comment]
But in general I agree that introducing personal information like the name or domain in tests should be avoided in the first place.

**Comment by jonny827** [comment]
I agree with @Tobion.  

1. Placeholders exist for consistency. If Symfony created default fixture data/placeholder data then tests could be run against certain data.(Country Specific, of Edge Case specific, or Package/Data Specific(GIS/Addresses/Etc)) This would this allow developers to write tests against data that is:
 a)consistent between tests so the various parts of their application will be able to share and pass the same data(One Bundle may support a field at length 25 whereas another has length 40... without consistent we lose the ability to test cross-bundle data compatibility.
b)community maintained - we get a host of developers that can contribute to our default placeholders/test fixtures whereas we can get edge case version for tough to GIS addresses, extra long names,  names with special characters, etc. The last thing we need to do as developers is close off our lessons learned to other Symfony colleagues about potentially valid submitted data(long addresses or newly introduced Areas codes, or other specific cases)
c) inline with symfony mind-set -   Symfony has countless abstraction layers to real data and best practices that cover almost every other aspect of symfony and I believe shying away from setting a precedent best practice creates two fold problems.

1) First problem, it is anti-Symfony standard to not have a best practice at this point for every major aspect of a project and tests including the data used is major aspect.
2) Not setting a standard in the Symfony project for the data allowed to be publicly released, used, combined, appended, modified and or presented in ways Symfony has no control over is only increasing the projects risk and the risk of the developers that use the Project and related tests in their own projects.  We can create  "plausible deniability" if  Symfony substantially encourages best practices for test data and all Symfony components are released under these best practices as they are with other best practices.  Then, like with any development practice, developers still have a choice to adopt those best practices or to "act on their own" and create use case data that is not inline with our stated best practices and "intended use of the application and its components".

Symfony development should be thought of like a mind-set and its consistency should be applied across all Symfony development regardless of core component or third party bundle.

**I am not an attorney, and these comments are not to be taken as legal advice.

**Comment by sstok** [comment]
Better stop using the word Acme then :smiling_imp: https://euipo.europa.eu/eSearch/#basic/1+1+1+1/50+50+50+50/Acme

Better hope I will not get in to any trouble :joy: 
https://github.com/rollerworks/search-doctrine-dbal/blob/master/tests/Functional/WhereBuilderResultsTest.php#L108-L111

I almost thought this was an Aril fools joke, the JavaScript NPM legal problem was about someone using a trade-marketed name (used for software) for another software product (which could lead to confusion and brand protection problems). _In Holland it's actually not uncommon to find multiple companies with the same name, but in different industries._

The editor complains about that NPM has to much power, and open source spirit, but this has nothing to do with that. Symfony is open source and yet the name is trade-marketed, trade-marketing protects unauthorized usage of name and brand. In short you may only "use" a brand name if it's for an informative nature ("we love Symfony (TM)" is perfectly legal, but if you imply that you are the creator/owner of Symfony (without being it) you violate the trade-market. For safety most companies have small disclaimer to prevent confusion).

Using Acme or some actually existing website/company name for testing purposes should have no negative impact, unless you use it in a way that could damage there brand. Otherwise it's only free marketing :)

**Comment by javiereguiluz** [comment]
Closing this as "won't fix" because it failed to gain support from the community.
