### ISSUE TITLE
Cannot locate view inside bundle

### ISSUE THREAD

**Issue by Loupax** [symfony/symfony#18364]
Hello everyone,

I just updated my project to the latest symfony version and it now looks for view in the wrong location.

My code is organized in two Bundles, each with it's own views located inside it's `Resources/views` directory
Replication:

```
php bin/console --version
Symfony version 3.0.3 - app/dev/debug

composer update
....
php bin/console --version 
Symfony version 3.0.4-DEV - app/dev/debug
```

This is the code inside my controller that previously worked:
```
return $this->render('AuthBundle:authentication/login.html.twig', ['form' => $form->createView()]);
```
Which in turn gives me the following error
```
Unable to find template "AuthBundle:authentication/login.html.twig" (looked into: /data/home/webapps/myapp/app/Resources/views, /data/home/webapps/myapp/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).
```

**Comment by javiereguiluz** [comment]
Shouldn't the template path be:

```
'AuthBundle::authentication/login.html.twig'
```

**Comment by Loupax** [comment]
It used to work like this. 

Now I changed the path to `AuthBundle:authentication:login.html.twig` which also currently works fine

`AuthBundle::authentication/login.html.twig` also works just need to know if this behaviour is correct or not

**Comment by stof** [comment]
``AuthBundle:authentication/login.html.twig`` never worked, as far as I can tell, unless you registered a custom loader handling it. We have 3 working notations:

- ``@Auth/authentication/login.html.twig`` (using Twig builtin loading algorithm)
- ``AuthBundle::authentication/login.html.twig`` using the Symfony-specific algorithm
- ``AuthBundle:authentication:login.html.twig`` using also the Symfony-specific algorithm

``AuthBundle:authentication/login.html.twig`` does not match syntax supported by either algorithm.

**Comment by javiereguiluz** [comment]
This shouldn't work (now or before): `AuthBundle:authentication/login.html.twig`

As @stof said, we support several notations: the traditional one contains 3 parts separated with `:` (any of the parts can be empty, but the entire template path must have 2 `:` in total).

However, I recommend you to use the new namespaced-syntax (e.g. `@Auth/authentication/login.html.twig`). It allows you to forget about the ugly `:` and it's "unique" (every template has a unique namespaced representation, whereas the traditional notation allows several representations for any given template).

In any case, I'm closing this issue because it looks like it's not a Symfony bug. Thanks.
