### ISSUE TITLE
Simplify access to CLDR/ICU data

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#18368]
At the moment, we have issues with regard to CLDR/ICU data (i.e. information about languages, currencies etc. that is collected by the CLDR project and exposed in a C API by the ICU project):
- Method calls are long: `Intl::getCurrencyBundle()->getCurrencyName(...)`
- We don't expose all information that is actually available in the CLDR data (e.g. see #11886)
- Since the bundles implement interfaces, we can't add methods to expose that data without breaking BC

To fix these problems, I suggest:
- Moving to static method calls for data access (e.g. `Currencies::getLocalizedName('EUR', 'en')`). This has been discussed before in #11887. 
  - The data is always available on the file system since we bundle it with the Intl component, hence I don't see a need to mock this information in tests and static access should be fine. 
  - Also, I don't see a need to provide value objects (`Currency`), since we expose data only. Projects that need value objects need specialized value objects most of the time and are better off if they implement their own. We didn't find a good solution in #11887, so I suggest to KISS and move forward.
  - To avoid confusion with value object classes and to underline that the class contains static methods only, I suggest to use plural names.
- Adding new methods for accessing CLDR data that is currently not being exposed.

This work was started once in #9206, but abandoned. I suggest to look at the PR for inspiration.
#### To Do
- [ ] Migrate `CurrencyBundle` to `Currencies`
- [ ] Migrate `LanguageBundle` to `Languages`
- [ ] Migrate `LocaleBundle` to `Locales`
- [ ] Migrate `RegionBundle` to `Countries`
- [ ] Add `Scripts`
- [ ] Add `Timezones` (started in #17636)
- [ ] Analyze CLDR data and add accessors for available data

:sparkles: **Who wants to work on these PRs?** :sparkles:
#### Canonicalization

We should add `canonicalize()` methods to all static classes in order to canonicalize (normalize) language/currency/etc. codes. For example, fr-FR and fr_FR are both valid language codes. Within our code, we want to use **one** specific format, however (namely fr_FR). Language codes received from other sources (browsers, request headers, ...) can be passed to `Languages::canonicalize()` in order to convert them to Symfony's preferred format.
#### Currencies API

Here is a proposed API for the `Currencies` class. I added the doc comments from #9206 where needed for clarity. See #9206 for implementation inspiration.

``` php
class Currencies
{
    /**
     * Returns all available currencies.
     *
     * @return string[] An array of ISO 4217 three-letter currency codes
     */
    public static function getCurrencyCodes();

    public static function exists($currencyCode);

    public static function canonicalize($currencyCode);

    public static function getSymbol($currencyCode);

    public static function getLocalizedName($currencyCode, $displayLocale = null);

    public static function getLocalizedNames($displayLocale = null);

    public static function getFractionDigits($currencyCode);

    public static function getRoundingIncrement($currencyCode);

    /**
     * Returns the ISO 4217 numeric code of a currency.
     *
     * For example, the numeric code of the Canadian Dollar ("CAD") is 124. If
     * no numeric code is available for a currency, 0 is returned.
     *
     * @param string $currency A canonical ISO 4217 three-letter currency code
     *                         (e.g. "EUR")
     *
     * @return integer The numeric code
     *
     * @throws InvalidArgumentException If the currency code does not exist
     */
    public static function getNumericCode($currencyCode);

    /**
     * Returns the matching ISO 4217 three-letter codes for a numeric code.
     *
     * For example, the numeric code 124 belongs to the Canadian Dollar ("CAD").
     * Some numeric codes belong to multiple currencies. For example, the
     * number 428 is assigned to both the Latvian Ruble ("LVR") and the Latvian
     * Lats ("LVL"). For this reason, this method always returns an array.
     *
     * @param integer $numericCode An ISO 4217 numeric currency code (e.g. 124)
     *
     * @return string[] The matching ISO 4217 three-letter currency codes
     *
     * @throws InvalidArgumentException If the numeric code does not exist
     */
    public static function forNumericCode($numericCode);
}
```
#### Languages API

``` php
class Languages
{
    /**
     * Returns all available languages.
     *
     * Languages are returned as lowercase ISO 639-1 two-letter language codes.
     * For languages that don't have a two-letter code, the ISO 639-2
     * three-letter code is used instead.
     *
     * A full table of ISO 639 language codes can be found here:
     * http://www-01.sil.org/iso639-3/codes.asp
     *
     * @return string[] An array of canonical ISO 639 language codes
     */
    public static function getLanguageCodes();

    public static function exists($languageCode);

    public static function canonicalize($languageCode);

    public static function getLocalizedName($languageCode, $displayLocale = null);

    public static function getLocalizedNames($displayLocale = null);

    /**
     * Returns the ISO 639-2 three-letter code of a language.
     *
     * @param string $language A canonical ISO 639 language code (e.g. "en")
     *
     * @return string The ISO 639-2 three-letter code of the language
     *
     * @throws InvalidArgumentException If the language is invalid
     * @throws MissingResourceException If the language has no
     *                                  corresponding three-letter code
     */
    public static function getAlpha3Code($languageCode)
}
```
#### Locales API

``` php
class Locales
{
    /**
     * Returns all available locales.
     *
     * @return string[] A list of ICU locale codes
     */
    public static function getLocales();

    public static function exists($locale);

    public static function canonicalize($locale);

    public static function getLocalizedName($locale, $displayLocale = null);

    public static function getLocalizedNames($displayLocale = null);
    /**
     * Returns a list of locale aliases.
     *
     * @return string[] An array with locale aliases as keys and ICU locale
     *                  codes as values
     */
    public static function getAliases();

    /**
     * Returns the fallback locale for a given locale, if any
     *
     * @param string $locale The ICU locale code to find the fallback for.
     *
     * @return string|null The ICU locale code of the fallback locale, or null
     *                     if no fallback exists
     */
    public static function getFallbackLocale($locale);
}
```
#### Countries API

``` php
class Countries
{
    public static function getCountryCodes();

    public static function exists($countryCode);

    public static function canonicalize($countryCode);

    public static function getLocalizedName($countryCode, $displayLocale = null);

    public static function getLocalizedNames($displayLocale = null);

    public static function getAlpha3Code($countryCode);

    public static function forAlpha3Code($alpha3Code);
}
```
#### Scripts API

``` php
class Scripts
{
    public static function getScriptCodes();

    public static function exists($scriptCode);

    public static function canonicalize($scriptCode);

    public static function getLocalizedName($scriptCode, $displayLocale = null);

    public static function getLocalizedNames($displayLocale = null);
}
```

**Comment by Simperfit** [comment]
@webmozart Why not reusing the work you've done in #9206 ?

**Comment by c960657** [comment]
If we are introducing a brand new API, I think we should use the opportunity to prepare the API for accessing arbitrary data from CLDR. Here are my thoughts on the proposed API:

The classes mentioned above have several different purposes:
1) Enumerate all possible currencies/countries/languages/scripts.
2) Given a country/currency/language/script and a locale, provide a locale-specific name, symbol etc.
3) Given a country/currency/language/script, provide a non-locale specific property (e.g. number of decimal places used with a specific currency).

Regarding no. 1:
What is considered a "possible" currency etc. is very context-specific. The current XxxDataGenerator classes have some hard-coded blacklists that filters out some values that are often not relevant to include. However, whether you want to include them or not really depends on the specific use-case. Currently CurrencyBundle::getCurrencyNames() returns names of currencies that are no longer legal tender, e.g. German Marks (used in Germany before the introduction of Euro) - that may sometimes be appropriate, but other times you don't want to include historic currencies. Often the list of "possible", say, currencies is definend by some external data, e.g. which currencies are supported by our exchange rate data provider.

Regarding no. 2:
The CLDR provides several display name variants, e.g. default and short region names (e.g. "Palestinian Territories" vs "Palestine"). CLDR defines fallback rules if a short variant is not specified for a given region. The current code returns a specific variant, but which variant you want depends on the use case. You could argue that the current limitation is not a big deal in practice, but on the other hand, why throw away data that the CLDR contributors have carefully compiled.

For these reasons I propose:
- The methods for enumerating all possible currencies/countries/languages/scripts should accept arguments that allow some of the most popular filtering options. The filtering should not be hard-coded into PHP but based on CLDR data (e.g. the [validity lists](http://www.unicode.org/repos/cldr/trunk/common/validity/)); the Symfony code should avoid being opinionated about data but just present whatever data is in CLDR.
- The methods for returning the localized name should accept arguments that allows the user to request any variant from CLDR (the variant/alt/draft/count XML attributes). Fallback/inheritance should be handled according to the CLDR spec.
- getLocalizedNames() should be changed to accept a mandatory list of currencies etc. to look up (this is also useful when the list of possible currencies is retrieved from some external source).


Some other thoughts:
I wonder whether it makes sense to split locale-specific and non-locale-specific methods into separate classes rather than the adding getLocalized- prefix to all methods that return locale-specific data (there is a lot of locale-specific data in CLDR).

I think we should stick to the terminology used in CLDR. This implies e.g. renaming getLocalizedName() to getDisplayName().

The entire CLDR dataset is rather large. Perhaps it was worth considering splitting into separate components so that you did not have to fetch translations for all timezones names in all locales if you only need a list of currencies in English and German.

I think the API should allow modifying the data (add new currencies/countries/languages and change existing translations) if the user is not satisfied with the data in CLDR. CLDR is rather dynamic and frequently gets error-fixes and new additions, so it is not at all unlikely that the user has some changes/additions that are not (yet) available upstream. This suggestion of making the datasets mutable may be an argument against moving to static calls (or we could make the static methods a facade that delegates calls to the "default" data bundle).

The data in the Intl component is imported and converted from ICU data that is imported and converted from CLDR. I don't know what lies behind this decision. If you are manually exploring the data, I think the CLDR XML files are much easier to read, and the documentation for each piece of data is easier to find. So I think we should consider using the CLDR XML files directly rather than the files from ICU.


Well, these were my initial thoughts. I hope you don't think I am derailing this issue or over-engineering. I think the CLDR dataset is very exciting, and I hope that we can make it more easily accessible to PHP programmers, not just the simple list of currencies/countries etc. but also features like relative dates, date intervals, metatimezones, list patterns, units of measurement and more.

**Comment by c960657** [comment]
It seems there already exist at least three PHP CLDR libraries: 
1. [punic/punic](https://github.com/punic/punic)
2. [commerceguys/intl](https://github.com/commerceguys/intl)
3. [ICanBoogie/CLDR](https://github.com/ICanBoogie/CLDR)

No. 1 is most in line with what is proposed in this issue. No. 2 and 3 on the other hand is somewhat similar to the exisitng Symfony API.

I suggest that Symfony use a third-party library rather than reimplementing its own version. Understanding and supporting CLDR is not trivial. I think Punic is a good candidate – it supports a large part of CLDR, its API is neutral/standard PHP, and it is not closely tied to a particular other framework.

I don't know if there is a reason to create a wrapper component in Symfony. The Punic API is pretty straight forward and not much different from what is proposed in this issue, so code elsewhere in Symfony could just be changed to call Punic directly. We could implement a `Intl\ResourceBundle` wrapper to maintain backwards compatibility (even though this issue is about getting rid of that part of the API) while deprecating/removing most other parts of the Intl component.

Thoughts?

**Comment by bojanz** [comment]
I agree with @webmozart's conclusions regarding the API, as well as the proposed plan.

I should add that we also need to expose number format data, which can then be used to reimplement NumberFormatter (as done by all 3 libraries referenced in the previous post).
