### ISSUE TITLE
[Form] Time Field with Different Model & View Timezones Behaves Differently During Daylight Savings Time

### ISSUE THREAD

**Issue by chrisguitarguy** [symfony/symfony#18366]
Let's say you add a time field like this:

``` php
/** @var FormBuilderInterface $builder */
$builder->add('time', TimeTime::class, [
  'model_timezone' => 'UTC',
  'view_timezone' => 'America/New_York',
]);
```

So users are entering the "time" field in their local time. Right now (2016-03-30) this happens to be during daylight savings time in (most of) the US: UTC is four hours ahead.

Saving the form with a time value of 1AM, I would expect the UTC time to be 5am. Instead it comes back as 6am because the [model transformer](https://github.com/symfony/symfony/blob/86eee064dd9953a5739adac2a4b5cbaa486c9081/src/Symfony/Component/Form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php#L183-L185) uses 1970-01-01 as the date (not during DST).

I'm not sure if this is actually a bug or not. The behavior makes sense when you look at it from the perspective of the field being time only without a frame of reference for the date -- it doesn't care about DST.

But the fact that it does conversion from one TZ to another makes it a bit weird: the conversion doesn't act as expected.

Might be useful to pass a reference date to the form that the model transformer can use and default that value to 1970-01-01?

``` php
$builder->add('time', TimeTime::class, [
  'model_timezone' => 'UTC',
  'view_timezone' => 'America/New_York',
  'current_date' => new \DateTime('now'), // default to 1970-01-01
]);
```

**Comment by mvrhov** [comment]
If you leave the input and output timezones blank, then it will use default php timzeone and there would be no time switch.

**Comment by pounard** [comment]
I have a similar problem, and I think it's related, I can be a bit more precise: when you spawn a `DateTimeType` form type, it awaits `model_timezone` and `view_timezone` arguments, which is definitely a good thing. Problem is, if you give a default date, it could itself carry a timezone (per default, in PHP, all `\DateTimeInteface` objects carry a timezone).

What happens here is tricky, I spawn a `DateTimeType` form type leaving default values for both model and view timezones arguments, the widget chooses to use the default configured. But it may happen that the default value I give to the widget is actually different from mine, let me explain:

- I'm on a server using `Europe/Paris` as default timezone,
- the default value I set on the widget is loaded from a UNIX timestamp using new `DateTime('@'.$some_integer_value)`,
- per default, when creating an instance from a UNIX timestamp, PHP does the right thing, and set the `UTC` timezone on the object (a timestamp cannot carry a timezone, so a timestamp per convention **is always UTC**),
- I spawn the `DateTimeType` widget with defaults, which fallbacks both on `Europe/Paris`,
- the `DateTimeToArrayTransformer` does this check: `if ($this->inputTimezone !== $this->outputTimezone) {` and considers there's nothing to change,
- it displays the `UTC` values because it does fetch the raw `Y`, `m`,`d` and `H` values from my date object without carrying about the timezone (as this date of year France is `UTC+2`),
- when I submit the form, it creates a new object using the previous date, which was originally `UTC` but not converted, so it has a 2 hours decal,
- in the `reverseTransform()` operation, it creates the new `\DateTime` instance by explicitely setting the `Europe/Paris` timezone, using raw values which actually were `UTC` when displayed (since not convered),
- value saved in my model then has a 2 hour decal.

If I load the form, click save without modifying, my date looses 2 hours, then I load the form, click submit without modifying values, and I loose 2 hours, etc...

My opinion is that the `model_timezone` per default should either always fallback on the given default `\DateTimeInterface` object's own timezone **or** it should not do the `if ($this->inputTimezone !== $this->outputTimezone) {` check and always call `setTimezone()` on the `\DateTime` default value object.

When you call `setTimezone()` on a `\DateTime` it converts it to the new timezone, but keeping the same `UTC` real time, so it's supposed to be safe.

But doing that, sadly, lots of program would experience bugs. But a lot of others would be fixed.

**Comment by pounard** [comment]
@mvrhov absolutely nothing, as soon as there is a parsable timezone in given time string, or when it's UNIX timestamp, PHP falls back to "UTC" no matter what timezone you try to give. And that's the right thing to do actually.

**Comment by pounard** [comment]
```
php > $ts = time();
php > echo $ts;
1523003098
php > print_r(new \DateTime('@'.$ts, new \DateTimeZone("Europe/Paris")));
DateTime Object
(
    [date] => 2018-04-06 08:24:58.000000
    [timezone_type] => 1
    [timezone] => +00:00
)
php > 
```

**Comment by mvrhov** [comment]
If that's true, then this is very very nonlogical. As the other way around works as expected.
https://3v4l.org/0qp6E

**Comment by pounard** [comment]
The result is what to expect, when you specify a timezone outside of the time value, it considers that the value is relative to the timezone, so when you convert to a unix timestamp, the timestamp it gives you is UTC, take look in the values it gave you, timestamp is not the same: Paris' timestamp as an extra 2 hours from the UTC timestamp in your example: it's working as documented.

**Comment by pounard** [comment]
```
php > $utc = new \DateTime('2018-01-01 00:00:00', new DateTimezone('UTC'));
php > $local = new \DateTime('2018-01-01 00:00:00', new DateTimezone('Europe/Paris'));
php > echo 'UTC: ' . $utc->getTimestamp() . "\n";
UTC: 1514764800
php > echo 'PARIS: ' . $local->getTimestamp() . "\n";
PARIS: 1514761200
php > 
php > echo 'UTC: ' . $utc->format(\DateTime::RFC1036) . "\n";
UTC: Mon, 01 Jan 18 00:00:00 +0000
php > echo 'PARIS: ' . $local->format(\DateTime::RFC1036) . "\n";
PARIS: Mon, 01 Jan 18 00:00:00 +0100
php > $utc = new \DateTime('@'.$utc->getTimestamp());
php > $local = new \DateTime('@'.$local->getTimestamp());
php > echo 'UTC: ' . $utc->format(\DateTime::RFC1036) . "\n";
UTC: Mon, 01 Jan 18 00:00:00 +0000
php > echo 'PARIS: ' . $local->format(\DateTime::RFC1036) . "\n";
PARIS: Sun, 31 Dec 17 23:00:00 +0000
```

If you look at the results here, when converted to timestamp, it is UTC-relative, then once converted to `\DateTime` again, time kept the right timezone, even if we didn't specified it. Paris is 00:00+0100 on the first echo, and 23:00+0000 the second time, so everything's fine, no dataloss!

**Comment by mvrhov** [comment]
AFAIK, this is your problem, you are converting from timestamp to DateTime. If you want it in different one, then you need to call setTimezone, after you create object. 
However I'd say that this is still the PHP bug, and that PHP should call the setTimezone internally if provided in constructor.

**Comment by pounard** [comment]
> this is your problem, you are converting from timestamp to DateTime

This is not a problem, the \DateTime may carry any timezone (in my case UTC, it is valid) from the form type perspective which doesn't know anything about the business/application layer, it should be honoured instead of being ignored.

> If you want it in different one, then you need to call setTimezone

I do not need to change the timezone, my input is valid, I don't care about having a different timezone since the date and time are correct. One very good point with Symfony's form type is that it does actually separate view timezone and model timezone, and converts it for display purposes: it is very, very good! But in my case, the model timezone is actually the one within the \DateTime, once again, it should be honoured per default.

> However I'd say that this is still the PHP bug, and that PHP should call the setTimezone internally if provided in constructor.

Maybe, may be not, it actually works as designed and documented, and changing this behaviour would break backward compatibility with millions of existing applications. I was not surprised by the way PHP handles this - or I should say I was pleasantly surprised when I saw how well PHP handles it correctly. Making any change on this behaviour is more a political question than an a technical one. Doc says that if first parameter is a timestamp, or carry a timezone (and per convention, a UNIX timestamp carries its own timezone: it's always UTC) then an additional timezone parameter is a duplicate and inconsistent, so it's being ignored. Valid to me.

**Comment by pounard** [comment]
I think that historically (I might be wrong but it seems a legit reasoning) that Symfony's form widget was abusively relying/tied on Doctrine's own behaviour. Doctrine documentation says: 

> By default Doctrine assumes that you are working with a default timezone

And I guess that what most people will let Doctrine do. And I think it explains why the form type assumes that the given input is always using the default timezone per default. This is where I think the problem lies.

**Comment by xabbuh** [comment]
The behaviour for the `TimeType` is expected (see also #24510). So I have reflagged the issue as a feature request.

@pounard Your issue seems to be something different. I suggest to open a new issue with an example application that allows to reproduce it.

**Comment by xabbuh** [comment]
see #32718
