### ISSUE TITLE
Dropdownlists inside an embedded form collection inside a form ignore "order by" annotation

### ISSUE THREAD

**Issue by mote0230** [symfony/symfony#18378]
Problem appears in at least 2.3 and 2.8.3. I use doctrine.
If you have 3 entities mapped to a database, each being a one to many, for example
car -> wheel -> color
And you have a form of car, embed a collection of forms of wheel, and have a dropdownlist of color of the wheel.
And in the wheel entity you have: 

```php
    /**
     * @ORM\ManyToOne(targetEntity="foo\entity\color")
     * @ORM\OrderBy({"colorname" = "ASC"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_color", referencedColumnName="id")
     * })
     */
    private $idColor
```

Then when rendering it will ignore this OrderBy annotation. You can even insert a nonexisting column name and no error will be thrown.

The dropdownlist may be a specific instance of this bug, maybe all ordering inside an embedded form collection is ignored, but I did not test this.

**Comment by xabbuh** [comment]
@mote0230 Would you be able to fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by mote0230** [comment]
I found no docs on how to get the app folder etc when starting from the github source, so i made a new install from composer.
Here it is:
https://github.com/mote0230/symfony2test
clone it, set up your db parameters (it's currently set to postgres in config.yml ) then do a  app/console doctrine:schema:update --force 
Put some stuff in the db, 1 car and 1 or 2 wheel is fine, 2 or more colors. Then go to app_dev.php/1/edit and see the color is not sorted, and if you inspect the db queries it does a select on the color table without a sort.

**Comment by dmaicher** [comment]
Well this is not a symfony bug ;)

The `@ORM\OrderBy({"colorname" = "ASC"})` annotation does not do anything in your case. That's because you have a `ToOne` relation and its only useful for `ToMany` relations:

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/tutorials/ordered-associations.html

And this would (say you have a collection that you want to order) only order the entities INSIDE the collection of the relation. The symfon2 form type cannot do anything with this information to order the possible choices.

What you can do to order the colors is define a custom querybuilder for the entity field here:

https://github.com/mote0230/symfony2test/blob/master/src/AppBundle/Form/WheelType.php#L14

As explained here:

http://symfony.com/doc/current/reference/forms/types/entity.html#using-a-custom-query-for-the-entities

Hope this helps ;)

**Comment by mote0230** [comment]
Ok thanks for the info!
