### ISSUE TITLE
[RFC][Routing] Smart routing order

### ISSUE THREAD

**Issue by unexge** [symfony/symfony#18415]
Right now, the routes registering by definition order(i'm not read the codes, but i see that in compiled matcher).

But sometimes, some routes needs more priority than others, for example;

if we had routes like that
```yml
bar:
    path: "/foo/{slug}"
    defaults:
        _controller: AppBundle:Default:bar

baz:
    path: "/foo/baz"
    defaults:
        _controller: AppBundle:Default:baz
```

the `baz` route needs more priority than `bar` route. even `bar` route defined first. because `baz` route define exact path.

**Comment by javiereguiluz** [comment]
@unexge if you are asking for Symfony to "magically" (or "smartly") reorder the application routes, I'm afraid that won't be possible because it will change the behavior of the applications without the user knowing why and that's a big BC break.

What we could do is to improve the `debug:router` command to show warning messages telling the developer that he/she is probably doing it wrong because some "catch-all" routes are defined before other specific routes. I can't estimate if that would be doable or too hard.

**Comment by unexge** [comment]
@javiereguiluz yes, that is a big BC break, but for now we can add an option and set it `false` by default for smart ordering.

**Comment by Simperfit** [comment]
I agree with @javiereguiluz, we could improve the way we help users knowing their routes may not be correctly ordered, but the user need to know what his application is doing. You may want to do things like that.. in some situation.

**Comment by backbone87** [comment]
a priority attribute could be introduced for routes, with a default value of 0.
after all routes are collected, apply a stable sort on priority (with a negative comparator, dont reverse the result).

this should hold the BC, while allowing to manually specify route order.

**Comment by fabpot** [comment]
The rule is very clear and won't change (no magic involved here): the routing tries to match routes one by one in the order of their definitions; whenever one matches, work is done. The developer is in control of that process, so it's up to the developer to re-organize routes the way they see fit.

Of course, we could develop a tool that tells developers that some routes will never match if they are shadowed by previous ones, that would certainly help debugging such situations.

**Comment by Simperfit** [comment]
I'm +1 for the tool in command or in` debug:router`

**Comment by backbone87** [comment]
> The developer is in control of that process, so it's up to the developer to re-organize routes the way they see fit.

setting the priority is still in full control of the developer. its just a proper tool when re-ordering the definition is combersome or not possible.

**Comment by unexge** [comment]
reorganizing routes can be very hard sometimes. especially importing route resources. 
giving more priority the "exact" routes, most of the times expected behaviour. and if developer still wants to reorganize routes by himself/herself, he/she always disable the "smart ordering" option.

**Comment by xabbuh** [comment]
I am :-1: on adding such a feature. It adds a lot of magic that in my opinion adds too much complexeity (increasing the risk to break existing code) for a too low benefit. But I would also be :+1: for giving developers a better support to find shadowed routes (however that could be implemented).

**Comment by iltar** [comment]
I think it could be implemented by iterating over all routes and build a tree, split on slashes.

**Comment by sstok** [comment]
Careful though, static routes are pretty easy to find but routes with parameter can get complicated.
Say you have two routes:

* Product: `shop/{slug}` with requirement `\w+`
* Category: `shop/{cat}` with requirement `[a-z]+`

Both overlap each other but they have different requirement values that are not equal!
You would have to normalize the regex patterns to determine if they are equal :scream: (That's a problem I'm actually facing in a Bundle of mine. https://github.com/park-manager/app-sectioning-bundle/issues/1 )

**Comment by HeahDude** [comment]
The `debug:router` command displays the routes in the order they are registered, and building the route map of an application is one of the first thing to do for an app.

So when the application grows you can actually see the impact on the routes order, but I agree, it should be easy to compare a dumped list to a new to see if some other routes have just been appended or let it emit a warning if the order has changed.

**Comment by HeahDude** [comment]
An "unreachable" route might be more complicated to implement, it implies to test all regex...

**Comment by unexge** [comment]
adding some info the `debug:router` command definitely help, but after detecting this, it still hard to reorganize (especially if all routes defined by annotations) IMO.

adding `priority` option as @backbone87 [said](https://github.com/symfony/symfony/issues/18415#issuecomment-204741952), would be really great for DX.

**Comment by HeahDude** [comment]
@unexge I agree but what about performances ? If one needs priorities to order its route it might be that he also needs to question his mapping ? I don't mean one would do something wrong in that case but it could help to do better instead of using a feature.

**Comment by javiereguiluz** [comment]
@unexge route priority was proposed in the past and rejected. Reordering routes is not that hard unless the app has lots of errors. In those cases, setting priorities would be a fragile patch instead of a real solution.

**Comment by fabpot** [comment]
The kind of conflicts mentioned in this issue mostly happen in the context of one file, so reorganizing one file is easy.

**Comment by backbone87** [comment]
@javiereguiluz i have searched for route priorities on the tracker, but couldnt find a discussion thats showing the "fragility" of such a feature. it is used for event listeners, too.
what you mean by fragile? that the sort algorithm shuffles up routes of equal priority? thats a well researched property of sort algrithmns and there are plenty of stable ones available, that ensure the relative order of equal valued sort key items.
i didnt run into the problem described in this ticket myself yet, but i cant follow the reasoning behind rejecting a priority feature. from my point of view, it would be very logical to provide priorities for route definitions, because it is already available in similar situations (event listeners).

**Comment by HeahDude** [comment]
@backbone87 You could compare listeners with controllers if controllers were supposed to be treated by priority for one route, simple 'class:method' ordered in an array, but routes ordering depends on optional parameters, regex, method (e.g POS, GET) and more. The algorithm would be very complex IMHO.

I don't think the needs fit here.

**Comment by backbone87** [comment]
@HeahDude i dont think we talk about the same thing? the only thing the route order is dependant on, is their definition order. nothing else. you talk about the matching process. thats not what my route priority is meant for. its about what route is tested for a match first. thats currently the one first defined, but can easily be changed to the one with the highest priority (or in case 2 routes have the same priority, then the one which was defined first). without explicitly giving a priority to a route, nothing changes within the routing process.

**Comment by HeahDude** [comment]
@backbone87 Ok got it. I just think I wouldn't use such feature, feels like it could go messy to me, I'm fine with the current way to handle things, but I guess some can find it useful to their projects :)

**Comment by fabpot** [comment]
There is a big difference between listeners and routes: people barely defines listeners (an app probably has 10 of them max), but an app can have 100s of routes, priority conflicts will happen a lot. Trying to reorder routes coming from 10s of files is going to be a nightmare. Again, the problem expressed here is very easily solvable: swap the two routes in one file, done. Without other real-world use cases where priorities would be useful, I don't think there is anything to solve here.

**Comment by unexge** [comment]
@fabpot IMO, reordering routes is already nightmare :smile:. swapping two routes is not that easy with annotations.

for example, i have 10 controller and a routing file like that;
```yml
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
```
without the shadowing situation, thats totally fine. but if one route shadows others, i need to define all controllers one by one.

also if we add `priority` option with default value `0`, it doesn't change anything. developer still can reorder routes manually. but if just one route needs to be check first, just add `-10` priority that route and done :smile:.

IMO, that kind of flexibility doesn't break anything and can be very helpful sometimes.

**Comment by twifty** [comment]
Adding a priority to the routes is not a good idea. But, due to the nature of how annotations are parsed, defining them in the correct order can be cumbersome. It has often forced me to use yaml/xml while at the same time leaving the annotations in place (as comments).

I would be in favour of adding a priority to the `@Route` annotation only. Especially on a class scope. This wouldn't be a BC issue and only involves sorting the `RouteCollection` contents before being returned.

**Comment by backbone87** [comment]
@twifty there are no BC issues with route priorities, idk why everyone is assuming that. its discussable, if the feature makes sense, but it doesnt cause BC breaks. just assume a priority feature already exists, but you can not configure the priority value currently, so it defaults to 0. there is noone change in the behavior, if you **do not** explicitly add priority values != 0.

**Comment by twifty** [comment]
@backbone87 You are proposing to add a priority to ALL routes, which would be a nightmare to maintain. Imagine a 3rd party bundle with prioritized routes, then another bundle, also using such routes, then your own code. There could be 30 or so routes all with the same priority, which one comes first?

On top of that, when creating a new controller/action, you would always have to keep in mind the priority of already defined routes. That would be impossible to do, especially when working on 3rd party code.

You think this is not a BC break. Imagine a 3rd party bundle, for example FOSRestBundle, implements prioritized routes. When you run composer update on an already developed, working and/or deployed application you would expect no changes. But, all of a sudden /user/{token} is pointing to /user/delete. It's an extreme example, but the less extreme are really hard to find bugs.

The current method of route ordering works. Simply define/import them in order. The only issue I have is pointing the annotation loader towards a directory, the files will always be scanned in alphabetical order. Adding a priority to `@Route` will change that and allow developers more control. All in the context of a single directory.

**Comment by Tobion** [comment]
> The only issue I have is pointing the annotation loader towards a directory, the files will always be scanned in alphabetical order. Adding a priority to @Route will change that and allow developers more control.

You can also just import the controllers indivdually if alphabetical order is not what you want. So this is basically the same as adding a priority.

**Comment by backbone87** [comment]
@twifty 
> There could be 30 or so routes all with the same priority, which one comes first?

Exactly the same way it is handled now, first come first serve.

> Imagine a 3rd party bundle, for example FOSRestBundle, implements prioritized routes.

If a 3rd party bundle decides to change its routing configuration, like adding route priorities different from 0 is, then its a BC break on **their** bundle, **not** Symfony. Its up to the 3rd party project to correctly tag this new bundle version as a major update and therefore BC breaks within this bundle must be respected by the integrator, if he wishes to upgrade to a new major version of said 3rd party bundle.

**Comment by ad3n** [comment]
Hi, this feature is relevan, not as a magic but we need to order the route when using annotation as route loader.

**Comment by ofbeaton** [comment]
Yay necroposts! Here to talk about how this conflict can happen super easily in any symfony app.

If you setup a login form per the advice in https://symfony.com/doc/master/security/form_login_setup.html you will have controller annotation defined `/login` routes in a `SecurityController` class.

Now if you define a annotated route like `/{hip root path route}` elsewhere then this will likely break your logins at `/login`, `/check_security` and `/logout` because of route priority since controllers are loaded alphabetically. No error message obviously, just lots of weird redirects and page reloads. `debug:routes`  will confirm your login route will come after `/{hip root path route}`

You can:
a) refactor your app to not use that hip root path but a `/uncool/{path route}`
b) add a regular expression check constraint on it to omit the 3 security paths slowing your app down
c) move the routes from SecurityController into routing.yml, similar to what is described in the 3.x docs (4.x docs have removed this): https://symfony.com/doc/3.4/security.html#logging-out
d) rename your SecurityController so it alphabetically comes before your hip root path route controller

Is this use case enough to re-open this issue? I think this is worth a guide in the docs for anyone wanting to use wildcards at the root.
