### ISSUE TITLE
[Form] ChoiceType error after upgrade to 3.0.4

### ISSUE THREAD

**Issue by walczakmac** [symfony/symfony#18461]
I just upgraded to Symfony 3.0.4 and I can't set integers as choice values in ChoiceType field. Validation gives me "This value is not valid." message for an integer value. In my case it was default value passed through "empty_data" option.

Here is example field I use to reproduce this:
```php
$builder->add('emailNotificationsEnabled', ChoiceType::class, [
    'required' => false,
    'multiple' => false,
    'choices'  => [0, 1],
    'empty_data' => 1,
]);
```

I found out that this is caused by this change: https://github.com/symfony/symfony/commit/3eac4693ad8e63283bb715375ab690999717d92b#diff-81585954baecb0c458557b7969974093L42

**Comment by HeahDude** [comment]
Hi @walczakmac, thank you for reporting this.
In fact `empty_data` of the `ChoiceType` should always be the string value of the choice.

This option stands for the submitted data (the string selected from the html form) and will be matched in the `ChoiceToValueTransformer` who needs a string to get to the right choice which in that case is an integer.

This can be a "BC break", however this is the way it is supposed to happen, as far as I understand.

If I'm wrong, please submit a PR to fix this regression.

In any case sorry for the trouble

**Comment by HeahDude** [comment]
In fact that the casting was done at this line https://github.com/symfony/symfony/commit/3eac4693ad8e63283bb715375ab690999717d92b#diff-81585954baecb0c458557b7969974093R46 and is useless with that change.

Because it should always be a string.

In contrary, to pre select the choice, the option `data` needs to be the "real" choice value, in your case an integer.

So I suggest to open a PR anyway, either to remove the useless `(string)` casting, or to revert that change.

ping @webmozart 

Would you like to handle it ?

**Comment by HeahDude** [comment]
ping @Tobion :)

**Comment by walczakmac** [comment]
@HeahDude Yes i can open a PR to fix that. I'll revert that change becase it's a BC break IMO and shouldn't be introduced in minor version.

**Comment by HeahDude** [comment]
Should be closed by https://github.com/symfony/symfony-docs/issues/6340.

**Comment by walczakmac** [comment]
As mentioned in #18462 I'm closing this.

**Comment by ameenross** [comment]
This cost me upwards of 2 hours today. Whatever was wrong with PHP type juggling I wonder... if I'd thought it to be a problem, I'd be using a strongly typed language.
