### ISSUE TITLE
Symfony Console OutputFormatter replaces "<<" with "\"

### ISSUE THREAD

**Issue by nuqqsa** [symfony/symfony#18481]
On a console command, with the standard OutputInterface instance
`$output->writeln("<<");`
actually outputs:

```
\
```

expected:

```
<<
```

The cause is the implementation of the method format in OutputFormatter, see line 177:

``` php
if (false !== strpos($output, '<<')) {
    return strtr($output, array('\\<' => '<', '<<' => '\\'));
}
```

Symfony version: 3.0.4

**Comment by javiereguiluz** [comment]
I can verify this bug:

```php
$output->writeln('Lorem << Ipsum');
$output->writeln('Lorem >> Ipsum');
$output->writeln('Lorem <<Ipsum>>');
$output->writeln('\\');
$output->writeln('<<');
$output->writeln('<');
```

Output:

```
Lorem \ Ipsum
Lorem >> Ipsum
Lorem \Ipsum>>
\
\
<
```

**Comment by chalasr** [comment]
Right now I'm not sure this should be fixed, at least I don't see any way to do it without having side effects on existing codes because as noticed this is due to the `OutputFormatter` implementation. I'll try to investigate and keep you informed.

Meanwhile, here are some quick ways to get the expected output:

- Adding a backslash immediately before `<<`:
  ```php
  $output->writeln('Lorem \<< Ipsum');
  ```

- Using `OutputFormatter::escape()` manually (will cause any `<tag></tag>` to be displayed):
  ```php
   $output->writeln(OutputFormatter::escape('Lorem << Ipsum'));
  ```

Both will give:
```
Lorem << Ipsum
```

**Comment by SpacePossum** [comment]
https://github.com/symfony/symfony/commit/44ae7850642597f8f56220bd4411d85023a64a61#diff-b79fd0c5df00b2bc5bf00f91b5939769R176

This introduced a BC break between 3.0.2 and 3.0.3.
Someone got an idea how to resolve this, i.e. if it cannot be fixed and the workarounds listed must be used than it would be good to know (to prevent to undo the workarounds if this issue is fixed later on).

**Comment by keradus** [comment]
In referred PR I see that even docs team think it's a bug

**Comment by SpacePossum** [comment]
@nicolas-grekas any news on this? I would like to move forward so any updates are welcome :)
