### ISSUE TITLE
[Console] --verbose option does not allow values

### ISSUE THREAD

**Issue by TobiasXy** [symfony/symfony#18546]
On [this page](https://symfony.com/doc/current/components/console/usage.html#global-options) we can see an example command like this:

`php application.php list --verbose=2`

But as a matter of fact, it is not possible to provide a value to the `--verbose` option.

If you try it, the result is this exception:

> [Symfony\Component\Console\Exception\RuntimeException]
  The "--verbose" option does not accept a value.

To reproduce it you can run a simple command like this:
` php bin/console router:match / --verbose=2`

I guess this could be fixed in the InputDefinition (Symfony\Component\Console\Application::getDefaultInputDefinition method), by replacing `InputOption::VALUE_NONE` with `InputOption::VALUE_OPTIONAL` for the verbose option?

**Comment by stof** [comment]
this is actually a bug in the doc (``--verbose`` is treated in a special way).

We cannot change the config of the option as you suggest, as it breaks BC badly (using ``bin/console router:match -v /`` would then pass ``/`` as the ``--verbose`` value rather than as an argument). We tried that in the past already.

Please open an issue on the doc repo to ask them to fix the doc.
