### ISSUE TITLE
[DI] Autowiring fails when TypeHinting on interfaces implemented indirectly

### ISSUE THREAD

**Issue by lemoinem** [symfony/symfony#18658]
The current implementation of autowiring seems to force unnecessary coupling and to be instable in case of change in a vendor's service implementation.

Example 1:

```
interface IA
interface IB extends IA
*service* class C implemets IB
```
I can autowire using the type hint `IB`, but not `IA`.

Example 2:
```
interface I
class CA implements I
*service* class CB extends CA
```
I cannot type hint on `I`.

This means, autowiring would break if an intermediary interface or an abstract class were added. Nothing in the documentation (http://symfony.com/doc/current/components/dependency_injection/autowiring.html) mentions this limitation and it seems highly counter-intuitive.

If you agree this should be addressed, I am ready to provide a PR to fix this.

**Comment by theofidry** [comment]
@lemoinem why can't you typehint `IB` in example 1? You just have to bind `C` to `IA` no?

**Comment by lemoinem** [comment]
@theofidry I'm not sure what you mean by "just have to bind `C` to `IA`". `C` is a service provided to me by a third party bundle, I don't have any control on it. Plus, the interface I'm actually depending on is `IA`, not `IB`.

For example:
Let's say I have a bundle A v1.0, which provides `IA` (and `C`, its implementation), I will naturally make my own service type hint for `IA`, and it will work.
But then, A v1.1 is released, which introduce a new interface `IB` extending `IA` and now, `C` implements `IB` directly (and `IA` indirectly). Anyway, `(new C) instanceof IA` still works and `C` still implements `IA`, so there are no reasons why this should be a breaking change. But the current autowiring WILL break.

Other example:
I have a Bundle A which provides `IA`, and a Bundle B which provides `IB` and `C`. I don't want to be coupled with B, because I might switch to a third bundle D which provides a class `D` implementing only `IA` and not related to `IB`. So I should type hint on `IA`, not `IB`.

In both cases, the current implementation forces me to adapt my code for a change that shouldn't be a break or to be unnecessary coupled to an additional bundled. In both cases, the goal of type hinting on an interface is to decouple myself from this interface implementation. IMO, Allowing only direct implementations of the interface reduces considerably the usefulness of the autowiring feature.

**Comment by theofidry** [comment]
I understand your examples, but I beg to differ and think this is the expected behaviour. Let's reconsider your example:

**v1.0**: you have an interface `IA` and a concrete class `C` implementing `IA`. `IA` is bound to `C`.
 
Now you introduce a new interface `IB` extending `IA`. `C` now implements `IB`. If `C` is not final, this is already a BC regardless of the bindings. Now for the sake of the example, let's assume `C` was final. So up to this point, everything is BC as expected. Let's consider the following scenarios:

- If you expect `IB` to be bound to `C`: I don't see why. You could have `CB` implementing `IB`, bound to `IB` and keep `C` bound to `IA`. In any case, this is a binding that should be declared and not guessed.
- If you bind `IB` to `C` and no longer explicitly bind `IA` to `C`, I don't see why the container should be able to guess this binding either.

In any case, I see no reason why the Container should guess anything just based on the fact that `IB` extends `IA`. So in your example, binding `C` to `IB` is fine and doable. But breaking the binding between `IA` and `C` is a BC break.

**Comment by lemoinem** [comment]
I'm sorry, but I really don't see how introducing a new intermediate interface would be a BC break...
There are absolutely no test (short of using specific reflection based tests exposing _internal implementation details_) which you could do before introducing `IB`, that would change behavior afterward...

Any method in `IA` is still implemented, `instanceof`, casting, type hinting and polymorphism still work exactly the same for both `C` and all its possible children classes. Any class extending `C` is still working just as before and no additional method (potentially required by the new `IB`) would break any of `C`'s children since they would be provided by `C` already (unless `C` is abstract and not implementing some of the new methods, but that's a different case entirely and, I agree, a BC break). Once again, since `IB` extends `IA`, `C` still implements `IA`. It would simply result as a duplicate interface implementation.

It's also a change that fits the Symfony BC promise: http://symfony.com/doc/current/contributing/code/bc.html

This kind of change has actually occured in Symfony itself to preserve backward compatibility while introducing new features, or even simply as a refactoring (non comprehensive list):
- https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Config/Resource/FileResource.php
- https://github.com/symfony/symfony/commit/1eec2d6fdafe3171d3f755569a041d903d1fd73c

In view of all this, I'm rather convinced that _this should not be considered a BC break_.

The Container is relying on reflection to determine which interfaces are implemented because this is the only way to get the information, but, IMO, the current information extraction algorithm is incomplete and flawed. Since there is a single service implementing `IA`, I expect type hinting to work regardless of the implementation details. And again, the documentation never mentions a limitation to interfaces explicitly and directly implemented.

My current, actual use case involves Doctrine. I have a single Entity Manager and no Document Manager. 
The only interface my service is relying on is `Doctrine\Common\Persistence\ObjectManager`. Why can't I type hint on it? It IS the real dependence I'm needing any way... With the current implementation, I can't use autowiring, or I have to type hint on `Doctring\ORM\EntityManagerInterface`, which is not my actual dependency.

**Comment by theofidry** [comment]
>I'm sorry, but I really don't see how introducing a new intermediate interface would be a BC break...

Because it can break a consumer code, as simple as that. Now it's an edge case and Symfony decided to not include this kind of change in their BC promise, which is not necessarily a bad thing as it would freeze a lot of things for a very small edge case.

>The Container is relying on reflection to determine which interfaces are implemented because this is the only way to get the information

Indeed it does. I though that the auto-wiring would work as it does in Laravel as it was coming from it, i.e. that even if you have only one implementation of an interface, you have to bind the interface to the concrete class still. As the choice have been made to auto-resolve it, introducing an intermediate interface shouldn't break things as they do /cc @dunglas

**Comment by dunglas** [comment]
It's weird that it fails. And IIUC what you describe, it's covered by a unit test.
Did you try to clear the cache after changing the vendors? Can you provide a failing test?

**Comment by lemoinem** [comment]
@dunglas While trying to create a reproducible error, I noticed the problem was actually caused by interactions with third party bundles... Both FOSUB and JMSDiExtra creates services equivalent to the default EM, but with new service IDs, and FOS only registers the `ObjectManager` Interface (hence the seemingly weird behavior).

I apologize for the loss of time. I did check the Autowiring Compiler Pass source code first (and didn't though `$reflClass->getInterfaces()` would return indirect interfaces... It doesn't say so in the doc either.)

Case is closed... I solved my issue by "hotwiring" the EM service (add the interfaces I need as its autowiring types in a custom compiler pass).

Do you think providing more explicit error messages for autowiring (Mentionning a list of the services implementing a type hint, or explicitly mentioning that no such service was found) could help for DX? (I think it would prevent further report like this one? I am certainly ready to go ahead and try working on a PR including this.

**Comment by xabbuh** [comment]
I am 👍 for improving the exception message if that makes it easier to spot the actual issue.

@lemoinem Can you open a pull request?

**Comment by nicolas-grekas** [comment]
Reopening until #18691 is adjusted for master (3.1) ping @lemoinem
