### ISSUE TITLE
[2.7.11] - Twig not looking for fields template in bundles when rendering form

### ISSUE THREAD

**Issue by zajca** [symfony/symfony#18653]
I'm using sonata admin bundle 2.3.10 with symofny 2.7.10
When I updated to 2.7.11 I get error when rendering form:

```
Unable to find template "AppBundle:Form/fields.html.twig" (looked into: <path>/app/Resources/views, <path>/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form, <path>/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views) in "SonataAdminBundle:CRUD:base_edit_form.html.twig".
```
It's not looking in bundle. When downgrade to 2.7.10 this is OK.

**Comment by stof** [comment]
``AppBundle:Form/fields.html.twig`` is not a valid template name when using the bundle notation. A bundle notation always contain 2 ``:``.

2.7.10 had a bug allowing invalid names in some cases, and this bug does not exist anymore due to a change in the implementation of the parsing.

**Comment by javiereguiluz** [comment]
@zajca as @stof said, the real problem is that the template which is not working now ... shouldn't have worked before either. In https://github.com/symfony/symfony-docs/issues/6468 we're discussing about improving the chapter about templates to avoid this kind of mistakes. That's why I'm closing this issue as "won't fix" because it's not considered a bug. Thanks.

**Comment by zajca** [comment]
@stof @javiereguiluz wow, I miss this. But it's more like BC for LTS version, I just quick check sonata for this syntax and double ```::``` is not even used and I guess other project will have same issues. I know It's a bug but still.
