### ISSUE TITLE
[DomCrawler] Chinese characters are not supported

### ISSUE THREAD

**Issue by CaliCastle** [symfony/symfony#18679]
I was using crawler for swapping elements, but it appeared to have some unicode issues

**Comment by javiereguiluz** [comment]
Could you please share the smallest snippet of code that produces this error? Thanks!

**Comment by CaliCastle** [comment]
In my html:
```html
<html>
...
<body>
    <h1>安装</h1>
</body>
</html>
```

And the php side:
```php
// $content is the html string of the code above.
$title = (new Crawler($content))->filter('h1');

return count($title) ? $title->text() : null;
```

And it resolved as: "å®‰è£…"

**Comment by CaliCastle** [comment]
As it turned out, I was actually compiling markdown into html:

```markdown
# 安装

## ...
```

But once I added
```markdown
<meta charset="utf-8">
```

It worked just fine, sorry for my mistakes.

**Comment by javiereguiluz** [comment]
@CaliCastle that's right. HTML and XML contents crawled with DomCrawler need to define an attribute named `charset`. Otherwise, the default charset is applied, which sadly is `ISO-8859-1` instead of `UTF-8`.

I'm glad you could fix this in a simple way and therefore, I'm closing this issue as fixed. Thanks!
