### ISSUE TITLE
[Form][2.8] performing a data transformation on a form element doesn't propagate further

### ISSUE THREAD

**Issue by er1z** [symfony/symfony#18683]
I'm struggling with a following issue: I'm working with a ``DataTransformer`` and form based on array as a form model.

Form works well, of course. And I add a view transformer

    $builder->get('field')->addViewTransformer(new MyTransformer());

If I submit a form, transformer works well:

    $form->get('field')->getViewData();

And I get the transformed data correctly. But if I want to gather view data for whole form:

    $form->getViewData();

It's synchronized with normalized data - transformed result is completely discarded. The, done some digging and found out that this code is enforcing data overwriting: https://github.com/symfony/form/blob/2.8/Form.php#L616

I'm using a stock mapper, ``PropertyPathMapper``.

Am I using something wrong or is this a bug? I'd like to get a view data for whole form, binding data transformer to a particular field. Right now, the only solution is to bind this to very whole builder.

**Comment by er1z** [comment]
Someone else came across this issue and created a test case: https://github.com/SimonHeimberg/SymfonyFormForm_DataTransformer_Demo

**Comment by er1z** [comment]
Any news?

**Comment by SimonHeimberg** [comment]
In case this is [expected behaviour](# "at least I did not expect this"), it should be mentioned in the [cookbook article about DataTransformers](http://symfony.com/doc/current/cookbook/form/data_transformers.html "How to Use Data Transformers").

**Comment by HeahDude** [comment]
Hi @er1z, I was searching another issue and I've just crossed this thread in the list (again?), and actually this is not a bug.

This is a kind of limitation because compound forms having an object or array as underlying data, don't keep their view data synchronized with their children's view data.
The model can be transformed once using a model data transformer, but only children are really transformed in view data before being mapped again in the parent on submission.

That's why there is model data transformers and view data transformers.

This is documented but not really obvious to understand, see http://symfony.com/doc/current/form/data_transformers.html, that used to confuse me.

In fact, the view data transformation only apply on values needing to be present in a field, that's not the case of the model or array data which does not need to be exposed directly in the view.

So we don't need to synchronize norm data or view data with children because this is the role of the DataMapper.

That's also one of the reason there is so many form events to access different states and step of the cycle.

To conclude I'd say we can close here as it would require it big refactoring, since using the parent view data synchronized with the model data is one of the key that makes everything work (think about the famous `empty_data`).

If one wants to get a form's children view data, well, he can just loop through them and get it :)
