### ISSUE TITLE
Finder: open compressed archives

### ISSUE THREAD

**Issue by flip111** [symfony/symfony#18811]
The Filesystem interface is very nice. It would be useful if filesystem would support archives so that they can be search easily as well. At the moment php seems to support zip, rar, bzip and gz out of the box. But with a archive-opener interface people could add their own archive formats to it.

**Comment by flip111** [comment]
Eh actually i meant the API of the Finder component, not the FileSystem one ..

**Comment by javiereguiluz** [comment]
@flip111 do you want to find files inside zip/rar/bzip/... archives? Something like this?

```php
$finder = new Finder();
$images = $finder->name('photos*')->size('< 100K')->in('images.zip');
```

**Comment by stof** [comment]
IMO, we should simply rely on stream wrappers to let PHP handle it. The Finder component is already compatible with PHP streams.

The issue with the zip is that ``new DirectoryIterator('zip://..../images.zip')`` does not work, because the zip stream wrapper fails saying ``failed to open dir: not implemented``.
Creating a custom stream wrapper able to read zip archives with the full stream wrapper API rather than only half of it would allow to use the Finder component without any change.

but from what I read from the doc, ``rar://`` (provided by ``ext-rar``) should work properly (I haven't tried it to confirm it), as long as you add a ``#`` at the end of the path (this is optional to iterate over the top-level of the archive, but not including the optional ``#`` means that iterating recursively breaks).

what you could do is to open a feature request on PHP itself to ask them to support ``opendir`` in the zip wrapper

**Comment by flip111** [comment]
stof would the streamwrapper idea make it possible to register your own archive format? which methods does the stream object need to implement to be 100% compatible with Finder?

**Comment by stof** [comment]
@flip111 it needs to be compatible with DirectoryIterator. I don't know exactly what it needs, but it at least needs ``opendir`` (which is not supported by ``zip://``). Knowing what DirectoryIterator actually needs should be asked to the PHP developers

**Comment by flip111** [comment]
https://bugs.php.net/bug.php?id=72304

This still leaves open that Finder could/should be compatible with custom stream wrappers, which it isn't at the moment (AFAIK). In other words: the API of Finder could be changed and does not depend on php-core built-in stream wrapper improvements.

**Comment by stof** [comment]
@flip111 the Finder component does not implement any filesystem iteration itself. It relies on RecursiveDirectoryIterator. And this won't change just because stream wrappers provided in some PHP extensions are incomplete.
Note that you can perfectly implement your own ``zip`` stream wrapper with the complete API and register it instead of the ext-zip one. This will make things work.

**Comment by flip111** [comment]
Ah ok so basically you are saying that Finder already takes custom stream wrapper right? That's cool !

**Comment by stof** [comment]
@flip111 yeah, it does as long as they implement the API necessary to be compatiable with directory iteration (and on a side note, reimplementing iteration in userland would probably not help us support incomplete stream wrappers)

**Comment by xabbuh** [comment]
Closing here as there is nothing we can do in Symfony about it.
