### ISSUE TITLE
[Form] RadioListMapper does not handle empty array

### ISSUE THREAD

**Issue by julienfastre** [symfony/symfony#18817]
Hi,

I do not know if this is a bug or a feature... I am still investigating this, but if you have some guidance I would appreciate.

For a reason I do not know (yet), sometimes, an empty array is passed to the method [`Symfony\Component\Form\Extension\Core\DataMapper\RadioListMapper::mapFormsToData`]( symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/RadioListMapper.php#L46 ) (a `var_dump` gives `array (size=0)
  empty`) when nothing is checked by the user (this form is not required). 

Until `2.8.5`, everything was great. But from `2.8.5`, the class [`Symfony\Component\Form\Extension\Core\DataMapper\RadioListMapper`]( symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/RadioListMapper.php ) has changed in commit ea5375c7b78ecb71790475935edfe6855c15dc7d, an and `Symfony\Component\Form\Exception\UnexpectedTypeException` is thrown.

Logically, when I change the method `mapFormsToData` to allow empty arrays, the method is processed without any error : 

```php
public function mapFormsToData($radios, &$choice)
    { 
       // the condition was if (null !== $choice && !is_string($choice))
        if (
              null !== $choice && !is_string($choice)
              AND
              !(is_array($choice) && count($choice) === 0)
        ) {
                 throw new UnexpectedTypeException($choice, 'null, string or empty array');
        }

        $choice = null;

        // as we have an empty array, this loop is not executed, the $choice remains on `null` and everything is fine...
        foreach ($radios as $radio) {
            if ($radio->getData()) {
                if ('placeholder' === $radio->getName()) {
                    return;
                }

                $choice = $radio->getConfig()->getOption('value');

                return;
            }
        }
    }
```

I do not know if we have to be so strong in the condition, or if this class should also accept empty array.

So, is this a bug or a feature ?

### Some context

As I said before, I do not know why we have an empty array. This array comes from a CustomType which produce a field "Choice with other" (the user may choose amongst different values, or pick another value and fill a text).  This _Type_ may allow multiple choices (`'multiple' => true`) or not, and is not required. When `multiple` is `true`, we do not encounter problems. When `multiple` is `false`, the `RadioListMapper` is executed and the exception is thrown. This _Type_ is attached to a _DataTransformer_ which transform the values into an array and store that as an array.

Some code : 

```
class ChoiceWithOtherType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options) 
    {
        //add an 'other' entry in choices array
        $options['choices']['_other'] = $this->otherValueLabel;
        //ChoiceWithOther must always be expanded
        $options['expanded'] = true;
        
        $builder
            ->add('_other', 'text', array('required' => false))
            ->add('_choices', 'choice', $options)
        ;    
    }
}
```

When coming out of the `DataTransformer`, the data is this : 

```
array (size=2)
  '_other' => string '' (length=0)
  '_choices' => null
```

### Something else...

Something else which might be interesting is this block in [`Form::submit` line 616-623]( symfony/src/Symfony/Component/Form/Form.php#623). 

```
                if (count($this->children) > 0) {
                    // Use InheritDataAwareIterator to process children of
                    // descendants that inherit this form's data.
                    // These descendants will not be submitted normally (see the check
                    // for $this->config->getInheritData() above)
                    $childrenIterator = new InheritDataAwareIterator($this->children);
                    $childrenIterator = new \RecursiveIteratorIterator($childrenIterator);
                    $this->config->getDataMapper()->mapFormsToData($childrenIterator, $viewData);
                }
```

When `$this->config->getDataMapper()->mapFormsToData($childrenIterator, $viewData);` is executed, `$viewData` contains an empty array, and this throw and Exception. But `var_dump($this->getViewData()))`, return `string '' (length=0)`. I wonder if the `$viewData` would have some transformation from an empty string to an empty array...

But, if I replace `$this->config->getDataMapper()->mapFormsToData($childrenIterator, $viewData)` by `$this->config->getDataMapper()->mapFormsToData($childrenIterator, $this->getViewData())`, the validation does not pass any more.

If you think this might be a bug, could you tell me how I should improve this bug report ? (I hadn't time to reproduce the bug).

**Comment by julienfastre** [comment]
Cc to @HeahDude, which commited ea5375c7b78ecb71790475935edfe6855c15dc7d

**Comment by HeahDude** [comment]
Hi @julienfastre, thanks for reporting this. I don't understand why you expect an empty array to be valid here. I think there might be something useful to know about the `DataMapper` used by your type but it is missing from the description. Could you please tell me more about it?

In the meanwhile, let me try to make clear the logic about how the `ChoiceType` handles its data:

1. you define an array of choices thanks to the `choices` option with keys which will be used as default string labels and values that can be anything (from scalars to objects) as model data.

2. choices model data need to be used as string values in the HTML form so the type uses either:

   - `choice_value` option to convert the choice data to string (if not string),

   - or a default string conversion (`false => '0', true => '1', (string) scalar),

   - or (when there is duplicates or not a scalar like `null` or objects) use incrementing integers as strings (`'0', '1', ...)

3. when you define the option `expanded` to `true`, instead of simply passing the (maybe generated) string values to html `option` tags in a select input (one input), the type has to handle a list of sub forms (many radio buttons or checkboxes inputs depending on `multiple` option).

   This implies that each data of the sub forms is a string.

What I guess might be an issue here is that when `multiple` option is `false` and `RadioListMapper` is used, the view data is handled as a single scalar value and not an array of scalar (as it should be by default when a form is compound).

One way I see you could solve your problem is by passing the `multiple` option to your mapper so it handles the default null value with something like:
```php
if (null === $viewData['_choices']) {
    $viewData['_choices'] = $this->multiple ? array() : '';
}
```

**Comment by HeahDude** [comment]
Ok it seems to me that if it worked before thanks to this [hack](https://github.com/symfony/symfony/commit/ea5375c7b78ecb71790475935edfe6855c15dc7d#diff-11ee91a32c601e8e1d509117556d53b3L142).

But the reason of this hack it that radio and checkbox list data mappers used to handle choices transformation. But then the wrong data was passed to the mappers while `Form::setData` because of the default normalization and the form failed to preselect choices.

Unless this is considered a real BC break, I think such hack should be implemented in data transformers when needed.

@stof @Tobion @xabbuh any thought on this one?

**Comment by xabbuh** [comment]
@HeahDude Would it hurt to put that event listener back into the form type if that is what is causing the issue described here?

**Comment by stof** [comment]
My question is why you would get an array being submitted in the radio field. This does not make sense.

**Comment by HeahDude** [comment]
@xabbuh It does not "hurt" as it was the way it was before, but then I suggest to deprecate this because I asked the same question as @stof, it clearly does not make sense and an event just for this has a performance impact. Some details about such use case would help.

Note that if we got an array in the first place [it was because of this line](https://github.com/symfony/symfony/commit/ea5375c7b78ecb71790475935edfe6855c15dc7d#diff-11ee91a32c601e8e1d509117556d53b3L251) which kinda normalize `empty_data`.

But setting it there for reversing it in a listener does not make sense either IMHO.

**Comment by julienfastre** [comment]
Hi,

Any new about this issue ?

I am not sure I understood everything here... I tryied to re-introduce the "hack" in `ChoiceType::buildForm`, like here : 

```
diff --git a/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php b/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php
index 3080ede..d76db84 100644
--- a/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php
+++ b/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php
@@ -133,7 +133,17 @@ class ChoiceType extends AbstractType
             });
         }
 
-        if ($options['multiple']) {
+        if (!$options['multiple']) {
+            // For radio lists, transform empty arrays to null
+            // <select> tag with "multiple" option or list of checkbox inputs
+            // This is kind of a hack necessary because the RadioListMapper
+            // is not invoked for forms without choices
+            $builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {
+                    if (array() === $event->getData()) {
+                        $event->setData(null);
+                    }
+                });
+        } elseif ($options['multiple']) {
             // <select> tag with "multiple" option or list of checkbox inputs
             $builder->addViewTransformer(new ChoicesToValuesTransformer($options['choice_list']));
         } else {
~
```

But this does not work : the `RadioListMapper::mapDataToForm` receive a `null`, but expect a `string`.

If I remove the condition, I am back on the same point: `RadioListMapper::mapFormToData` receive an array, but expect a string.

**Comment by HeahDude** [comment]
@julienfastre Could you show us some code from your `DataTransformer`?

**Comment by julienfastre** [comment]
@HeahDude 

We did further investigation this week.

Some informations about our `DataTransformer` : this is quite complicated, the data transformer execute the function here : https://framagit.org/Chill-project/Chill-CustomFields/blob/master/CustomFields/CustomFieldChoice.php#L159 (see [line  106](https://framagit.org/Chill-project/Chill-CustomFields/blob/master/CustomFields/CustomFieldChoice.php#L106) where it is added in the data transformer.

On the output, the data transformer return this : 

```php
array(
   '_other' => null,
   _choices' => null
);
```

This is logical, because our type is a `ChoiceWithOther` type, [defined here](https://framagit.org/Chill-project/Chill-CustomFields/blob/master/Form/Type/ChoiceWithOtherType.php).

We confirmed this result using `var_dump` at runtime, and [an unit test exists](https://framagit.org/Chill-project/Chill-CustomFields/blob/master/Tests/CustomFields/CustomFieldsChoiceTest.php#L183) to cover this case.

We also inspected [`Form::submit`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L496) and particularly [the lines 595-606](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L595-606) : 

```php
                // when the exception occurs, $this->getConfig()->getName() is '_choices' 
                $viewData = $this->config->getCompound() ? $this->viewData : $submittedData;
                // $viewData is `null`

                if (FormUtil::isEmpty($viewData)) {
                    $emptyData = $this->config->getEmptyData();

                    if ($emptyData instanceof \Closure) {
                        /* @var \Closure $emptyData */
                        // this part is executed : $emptyData is a \Closure
                        $emptyData = $emptyData($this, $viewData);
                        // here, $emptyData is `array()`
                    }
                    $viewData = $emptyData;
                    // and the $viewData is the wrong type => cause error !
                }
```

My colleague says that this might come from [`FormType`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/FormType.php#L141). 

Why, in this case, the `$this->getConfig()->getCompound()` return `true ` ?

If you have any help or suggestions about where to search for debugging this...

**Comment by HeahDude** [comment]
@julienfastre The form is compound in this case because it has sub forms.

Your bug might come from `empty_data` setting since this option should always be a string or an array of string when `multiple` is `true`.

So https://framagit.org/Chill-project/Chill-CustomFields/blob/master/CustomFields/CustomFieldChoice.php#L128 plus [line 137](https://framagit.org/Chill-project/Chill-CustomFields/blob/master/CustomFields/CustomFieldChoice.php#L137) and [line 145](https://framagit.org/Chill-project/Chill-CustomFields/blob/master/CustomFields/CustomFieldChoice.php#L145) should be `'empty_data' => '0'`.

**Comment by julienfastre** [comment]
@HeahDude You are right that this is another bug, which could be fixed by transforming those int to string. This is fixed in a local version. (The lines you pointed to is used on admin part to let administrator defines the custom field).

The form is build [on lines 71-117 (function `buildForm`](https://framagit.org/Chill-project/Chill-CustomFields/blob/master/CustomFields/CustomFieldChoice.php#L72). More precisely, this is done by [line 100](https://framagit.org/Chill-project/Chill-CustomFields/blob/master/CustomFields/CustomFieldChoice.php#L100) when [the option multiple is `false`](https://framagit.org/Chill-project/Chill-CustomFields/blob/master/CustomFields/CustomFieldChoice.php#L86).

**Comment by julienfastre** [comment]
@HeahDude some documentation is available here about this feature : https://framagit.org/Chill-project/Chill-CustomFields/blob/master/CustomFields/CustomFieldChoice.php#L86

**Comment by julienfastre** [comment]
@HeahDude Some documentation is available here about this feature : http://docs.chill.social/en/latest/bundles/custom-fields.html#custom-fields-concepts

**Comment by HeahDude** [comment]
Right, but I don't see any `empty_data` configuration there so why is this used as a closure in your test?

**Comment by julienfastre** [comment]
@HeahDude That's a question: why the empty data on the `_choices` (defined [here](https://framagit.org/Chill-project/Chill-CustomFields/blob/master/Form/Type/ChoiceWithOtherType.php)) is a `\Closure` (executed [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L595-606)) and where this `\Closure` comes from ?

**Comment by HeahDude** [comment]
The closure is set by default when the `data_class` option is defined, but it's explicitly set to `null` for the `ChoiceType` as you pointed. There might be a configuration issue somewhere.

**Comment by HeahDude** [comment]
Hey @julienfastre, any news here?

**Comment by julienfastre** [comment]
@HeahDude Currently not, but it makes still part of the things I have to check. Thanks.

**Comment by xabbuh** [comment]
Closing here for now. @julienfastre Please comment if you happen to be able to provide more information and we can reopen here then.

**Comment by julienfastre** [comment]
Hi. I could solve my problem by adding an empty_data value on the Choice Field (see the new line 34 at https://framagit.org/Chill-project/Chill-CustomFields/commit/affeae238c3e5f4bbadc3b2c6761a356b7e33596#2bc73e1658e8d593840b67db8b0ea0777f5486f4_33_34)

I still do not know why the default empty data does not work, but if I was the only one to observe this behaviour, I may assume everything is ok :-) 

Thanks for your help and time.

**Comment by HeahDude** [comment]
Thanks for the feedback :)
