### ISSUE TITLE
Symfony\Component\Process 127 comand not found

### ISSUE THREAD

**Issue by nmpribeiro** [symfony/symfony#18847]
Hi there,

So I am trying to use `sass`. I have it installed through local user, and If I use it try the `sass -v` command through the user apache works on, it outputs. However, through php (and process) I get the `127` output, and my error_log tells me this:

```
/usr/bin/env: ruby_executable_hooks: No such file or directory
```

Now, how can I change the paths of these? Say, my ruby_executable_hooks is here: `/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks` and `which ruby_executable_hooks`  outputs: `~/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks`

My `$path` seams to be in order... I'm clueless...

**Comment by javiereguiluz** [comment]
What do you get as a result when executing

```php
use Symfony\Component\Process\Process;

$process = new Process('echo $PATH');
$process->run();
echo $process->getOutput();
```

**Comment by nmpribeiro** [comment]
```
Echo:
/usr/local/bin:/usr/bin:/bin 
```

And... if I try to call sass on /usr/local/bin:
```
$ /usr/local/bin/sass -v
Sass 3.4.22 (Selective Steve)
```

Unless php has some block/limitation in place.. I don't get it.

**Comment by javiereguiluz** [comment]
Your PATH is `/usr/local/bin` (and others) but `sass` is trying to execute this command: `/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks`. That's why it doesn't find it. Should you add `/usr/local/rvm/` dir to your path?

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed", but if the error still persists, please reopen it. Thank you!

**Comment by ssmusoke** [comment]
I am having the same issue with MySQL in my shell script, I keep getting command not found, yet shell_exec executes the scripts properly... and they also run well on the command line 

My Environment:
- MacOS 10.13.4 - all installations done via Homebrew 
- PHP 7.2.5 (cli) (built: Apr 26 2018 12:07:32) ( NTS )
- Symfony 4.0.8 + Process 4.0.8 
- Built-in PHP server as well as Laravel Valet 

It seems that the component is using the sh instead of bash, so I am not sure how to get this changed or leveraged 

Further digging brought me to this StackOverflow post https://stackoverflow.com/questions/3428647/php-exec-path-variable-missing-elements

**Comment by ssmusoke** [comment]
By luck I run the inbuilt PHP server using the Symfony Web Server bundle, and this issue does not occur seems that these lines do the magic https://github.com/symfony/web-server-bundle/blob/0dd380dda69a180151de75f3734c418917652f3a/Command/ServerRunCommand.php#L102-L112
