### ISSUE TITLE
[YAML] Array keys disappeared when dump

### ISSUE THREAD

**Issue by flat1701** [symfony/symfony#18843]
I executed like below.

```php
$array = ['foo' => ['bar' => [1 => 2, 'baz' => 3]]];
echo Yaml::dump($array);
```
I expected

> foo:
>     bar: { 1: 2, baz: 3 }

but result is

> foo:
>     bar: [2, 3]

I edited Yaml/Inline.php like below, I got wanted result.

```diff
@@ -159,9 +159,7 @@
     {
         // array
         $keys = array_keys($value);
-        if ((1 == count($keys) && '0' == $keys[0])
-            || (count($keys) > 1 && array_reduce($keys, function ($v, $w) { return (int) $v + $w; }, 0) == count($keys) * (count($keys) - 1) / 2)
-        ) {
+        if ($keys === range(0, count($keys)-1)) {
             $output = array();
             foreach ($value as $val) {
                 $output[] = self::dump($val, $exceptionOnInvalidType, $objectSupport);

```

**Comment by xabbuh** [comment]
@flat1701 Do you want to create a pull request?

**Comment by javiereguiluz** [comment]
@flat1701 in case what @xabbuh said confused you, he acknowledges this bug and asks you if you want to try to make a pull request to solve it. If you don't have experience creating pull requests, we can guide you through the process and it doesn't matter if you make any unintentional mistakes (we all do!). Otherwise we can solve this issue ourselves. Thank you!

**Comment by flat1701** [comment]
I created this account yesterday. So I issued rather than pull request.
Who is good to do but I also want to try.

**Comment by xabbuh** [comment]
We would really appreciate that. :) You may want to start with some information you can find on http://symfony.com/doc/current/contributing/code/patches.html. But of course just ask if something is not clear to you.

**Comment by dimkir** [comment]
@flat1701 mind that your method needs adjustment, so that it works with the arrays in php created in non-sequential order. 

Because arrays internally are stored in hash-like structures, array keys would be preserving the order of insertion. 

Eg. let's say we create array backwards:

```
$bck_array = [];
for($i = 10; $i>=0; $i--){
 $bck_array[$i]  = "Value $i";
}
```

If we do `print_r`, 

```
php > print_r($bck_array);
Array
(
    [10] => Value 10
    [9] => Value 9
    [8] => Value 8
    [7] => Value 7
    [6] => Value 6
    [5] => Value 5
    [4] => Value 4
    [3] => Value 3
    [2] => Value 2
    [1] => Value 1
    [0] => Value 0
)

```
we can see that backwards order of insertion is preserved by PHP, however resulting array is **perfectly  VALID NUMERIC KEYS ONLY array with sequential KEYS IN RANGE [0,n)**, which in Yaml should be dumped as `['Value 1', 'Value 2', ... 'Value 10']` string.

Calling `array_keys($bck_array)` would also result in sequence of keys, with the order of the items preserved:

```
php > echo implode(', ',array_keys($bck_array));
10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0
```
 

However call to `range(0,10)` would return array with indices sorted in ascending order:

```
php > echo implode(', ',range(0,10));
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

```


So in this case your comparison: 
```
  if ($keys === range(0, count($keys)-1)) {
```
would yield false negative. 

The first step towards solution maybe to actually call `sort()`  on the keys, before comparing them with the range...

**Comment by dimkir** [comment]
I suggest fix along these lines:

```
  if ((1 === $keysCount && '0' == $keys[0])
            || ($keysCount > 1 && array_reduce($keys, function ($carry, $item) {
                    if ( $carry === null ) return; // null carry is error
                    if ( 'integer' !== gettype($item) ) {
                        return null;
                    }
                    return (int) $carry + $item;
                }, 0) === $keysCount * ($keysCount - 1) / 2)
        )
```
