### ISSUE TITLE
Problems with using MongoDbSessionHandler to Store Sessions in a MongoDB Database

### ISSUE THREAD

**Issue by yapro** [symfony/symfony#18853]
I use instruction http://symfony.com/doc/current/cookbook/doctrine/mongodb_session_storage.html

But, when I try to update my cache, i getting error:

```
php app/console cache:clear -v --env=prod
Clearing the cache for the prod environment with debug false
  Warming up cache



  [MongoConnectionException]  
  No candidate servers found  



Exception trace:
 () at /site/app/cache/pro_/ap_ProdProjectContainer.php:1126
 MongoClient->__construct() at /site/app/cache/pro_/ap_ProdProjectContainer.php:1126
 ap_ProdProjectContainer->getMongoClientService() at /site/app/bootstrap.php.cache:2090
 Symfony\Component\DependencyInjection\Container->get() at /site/app/cache/pro_/ap_ProdProjectContainer.php:1441
 ap_ProdProjectContainer->getSession_Handler_MongoService() at /site/app/bootstrap.php.cache:2090
 Symfony\Component\DependencyInjection\Container->get() at /site/app/cache/pro_/ap_ProdProjectContainer.php:1453
 ap_ProdProjectContainer->getSession_Storage_NativeService() at /site/app/bootstrap.php.cache:2090
 Symfony\Component\DependencyInjection\Container->get() at /site/app/cache/pro_/ap_ProdProjectContainer.php:1437
 ap_ProdProjectContainer->getSessionService() at /site/app/bootstrap.php.cache:2090
 Symfony\Component\DependencyInjection\Container->get() at /site/app/cache/pro_/ap_ProdProjectContainer.php:1327
 ap_ProdProjectContainer->getSecurity_Csrf_TokenManagerService() at /site/app/bootstrap.php.cache:2090
 Symfony\Component\DependencyInjection\Container->get() at /site/app/cache/pro_/ap_ProdProjectContainer.php:551
 ap_ProdProjectContainer->getForm_CsrfProviderService() at /site/app/bootstrap.php.cache:2090
 Symfony\Component\DependencyInjection\Container->get() at /site/app/cache/pro_/ap_ProdProjectContainer.php:1933
 ap_ProdProjectContainer->getTwigService() at /site/app/bootstrap.php.cache:2090
 Symfony\Component\DependencyInjection\Container->get() at /site/app/cache/pro_/ap_ProdProjectContainer.php:365
 ap_ProdProjectContainer->getAssetic_AssetManagerService() at /site/app/bootstrap.php.cache:2090
 Symfony\Component\DependencyInjection\Container->get() at /site/vendor/symfony/assetic-bundle/CacheWarmer/AssetManagerCacheWarmer.php:33
 Symfony\Bundle\AsseticBundle\CacheWarmer\AssetManagerCacheWarmer->warmUp() at /site/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /site/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:138
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /site/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /site/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /site/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:896
 Symfony\Component\Console\Application->doRunCommand() at /site/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /site/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /site/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /site/app/console:27


cache:clear [--no-warmup] [--no-optional-warmers]
```

I think that cache clear should not cause the connection to MongoDB.

**Comment by Tobion** [comment]
Can't you just make the MongoClient service lazy?

**Comment by csarrazi** [comment]
@yapro It's not actually the cache:clear command that triggers the connection, but the cache:warmup (as you may know, the cache:clear command actually automatically warms up the cache unless you specify `--no-warmup`).

By the way, this is a global issue, which concerns all non-file session handlers. During cache:warmup, when initialising Twig, the csrf_provider is initialised, which in turn initialises the session. Because of this, a connection to the session storage is always made, and this triggers this issue.

You'll have exactly the same problem when storing sessions using memcache, redis, mongodb, pdo, etc.

Like @Tobion said, you could try creating the service lazily.

**Comment by javiereguiluz** [comment]
@csarrazi your explanation is excellent. Thanks for that!  But don't you think this is "a bug"? To me it looks strange that compiling the templates requires to initialize the session (optionally making database connections).

**Comment by csarrazi** [comment]
@javiereguiluz The behaviour could be interpreted as a "bug". But that's actually one of the limitations of Twig, which loads all extensions eagerly. In which case, this is actually one of the only exceptions to the container injection rule, as you would need to inject the container instead of the actual classes. However, this would most likely introduce BC breaks, as well as a direct dependency on the container in the bridge, which is a no go as it is used not only for Symfony, but other projects also (Silex, etc.), which don't use Symfony DI component.

I'm not sure this can be fixed easily, without introducing a BC break, as it would mean either:

* Injecting the container in one of the classes (and thus, changing its signature)
* Making lazy services (we need to inspect that one further, in order to see whether that's possible)

If @Tobion's suggestion works, this means that we should update the documentation to make sure that it is mentioned (and for all session handlers, not only the MongoDB session handler).

**Comment by javiereguiluz** [comment]
@csarrazi Fabien started working on refactoring Twig extensions (https://github.com/twigphp/Twig/pull/1974) Let's see if he can finish it.

I've opened https://github.com/symfony/symfony-docs/issues/6621 to improve the docs about this.

**Comment by fabpot** [comment]
Closing as it should be fixed now that Twig extensions are lazy (IIUC). Feel free to reopen if that's not the case.
