### ISSUE TITLE
[LDAP] Set multiple dn_string values

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#18871]
Hi,

Using the LDAP component as a firewall, is it possible to set multiple `dn_string` values?

I would like something like: `dn_string: ["dnstring1", "dnstring2"]`

So if the user is not found in `dnstring1`, it will try to find him in `dnstring2`.

Any way to do this?

Thanks

**Comment by csarrazi** [comment]
Currently, you would need to create your own user provider in order to do this.

**Comment by iltar** [comment]
Would a chain ldap userprovider work here?

**Comment by Seb33300** [comment]
I am currently using the LDAP firewall with a database provider.

The provider checks if the user exists in the database, then LDAP firewall checks if he exists in the LDAP.
My problem is that it seems to not be possible to check multiple DN strings on the LDAP.

**Comment by Seb33300** [comment]
More details:

On the LDAP, users are stored on 2 dn strings:
`uid={username},ou=internals,ou=people,dc=company,dc=com`
and `uid={username},ou=externals,ou=people,dc=company,dc=com`

Actually we are checking only on the first string and it works fine.
But we would like to search on the other if the user was not found on the first.

How can we set a second dn string?
Or maybe a wildcard like `uid={username},ou=*,ou=people,dc=company,dc=com` to search on all `ou=people` sub folders?

**Comment by csarrazi** [comment]
Using a wildcard won't work, as `ldap_bind()` doesn't support this. Using multiple dn strings is unsupported, and can actually already be done using a special search filter like `(&({uid_key}={username})(|(ou=internals)(ou=externals))(ou=people,dc=company,dc=com)`

We could either:
* Do this in the user provider (which is currently already supported)
* Do this in the authentication provider (However, I would actually introduce a configuration option to enable this behavior, as we actually need to enable a search user in the configuration.

Either way, currently, as you are fetching you user info from the database, you may actually want to use a custom authentication provider, using either `simple_form`, `simple_preauth` or `guard`.

**Comment by Seb33300** [comment]
Thanks.

If I can do this with this search filter, it's ok for me. I will try it.

I just don't understand what is the `{uid_key}`?
Does I need to replace it with `uid`?

**Comment by csarrazi** [comment]
uid_key is actually replaced with the value of the `uid_key` configuration value. This is done in the user provider, and is actually simply a DX thing. If you're using the default filter `({uid_key}={username})` (which works with simple auth enabled), you just need to configure the `uid_key` in the user provider's options.

See https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/User/LdapUserProvider.php#L53 and https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/User/LdapUserProvider.php#L65 for more information.

By the way, after a bit of research, it seems that running an LDAP search is actually faster than multiple calls to `ldap_bind()`. In your case, I would actually do this in a custom authentication provider.

**Comment by Seb33300** [comment]
Just tried `(&(uid={username})(|(ou=internals)(ou=externals))(ou=people,dc=company,dc=com))` but it seems to not work.

LDAP Search Filters can be used on `ldap_bind()`?
Do you know if we have to activate something on the LDAP server to allow Search Filters?

Here is my security.yml:
```
security:

    providers:
        app_db:
            entity:
                class: AppBundle:User

    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: app_db
            form_login_ldap:
                service:      app.ldap
                dn_string:    "(&(uid={username})(|(ou=internals)(ou=externals))(ou=people,dc=company,dc=com))"
                check_path:               app_login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
```

**Comment by csarrazi** [comment]
Like I said earlier, you still need to create your own authentication provider. In your case, as you need to do a previous search in the authentication provider, you actually need to create your own provider, by using `simple_form` instead of `form_login_ldap`, and running the ldap search before.

The `form_login_ldap` and `http_basic_ldap` providers only work if you have a single DN string (`uid={username},ou=internals,ou=people,dc=company,dc=com`), but not with a wildcard. You actually need to implement your own authentication provider (using `simple_form` in your case, as it should be easier than `guard`, or extending the `FormLoginLdapAuthenticationProvider`). You actually mistook the `dn_string` with an LDAP filter, but they are not the same at all.

Make sure you read the documentation from http://symfony.com/doc/current/cookbook/security/custom_password_authenticator.html

**Comment by Seb33300** [comment]
OK, I misunderstood your previous answer.

Thanks!

**Comment by csarrazi** [comment]
For 3.2, we could actually try improving the current behaviour, enabling a few different scenarios:

* Binding directly using the DN string
* Searching for a user, and binding against the resulting DN

Also, we could actually make the authentication providers configurable, so they either bind against the LDAP server before or after fetching the user info.

**Comment by sfeni** [comment]
We have the same probleme here. We have many many dn_string for the different users.

- Searching for a user, and binding against the resulting DN

Would be a very nice solution because if I find the user I can use his dn and do not need to create the dn myself (with the dn_string config option).

use_ldap_result_dn_string: true (default: false)
or something like that.
