### ISSUE TITLE
routing_dev.yml required for dev cache:clear

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony#18875]
I wanted to do console commands but wanted to start with the symfony distribution and strip things out that I didn't need, as I wasn't experienced enough to know if the caching stuff helps with commands or not. I also wanted to take advantage of the `parameters.yml` and centralized `console` command.

As I was stripping things out I'm down to:
- `symfony/console` `^3.1@dev`
- `symfony/debug-bundle`
- `symfony/monolog-bundle`
- `sensio/distribution-bundle`
- `sensio/framework-extra-bundle`
- `incenteev/composer-parameter-handler`
- `sensio/generator-bundle`
- `symfony/phpunit-bridge`

I noticed something odd, when I run `php bin/console cache:clear --env=prod` everything works fine, but when I run `php bin/console cache:clear --env=dev` it complains about a missing `routing_dev.yml`.

For the record I removed both routing files. Why would routing be required for dev but not for prod? Did I miss something to strip out? Is the caching mechanism not useful for console?

**Comment by xabbuh** [comment]
Your issue is that the `config_dev.yml` file loads another routing file (`routing_dev.yml`) which in turn loads the main `routing.yml` routing config to add additional routes that are only needed during development.

However, I am closing here as we use GitHub only for managing Symfony's development. For support questions, please use one of [our support channels](http://symfony.com/support). Thank you for understanding.

**Comment by ofbeaton** [comment]
You are indeed correct, apologies, and thank you. I thought I had removed the references because the import was gone, but it was in the `framework/router/resource` part of the file.
