### ISSUE TITLE
[HttpFoundation] Enable StreamedReponse API for async usage

### ISSUE THREAD

**Issue by andig** [symfony/symfony#18892]
I hope asking here is the right place and my question if not entirely stupid. Working on https://github.com/php-pm/php-pm-httpkernel/issues/36 I've found that- while `StreamedReponse` allows to produce the response lazily- there is no way to consume it like that. 

Why? Once the `callback()` is called, all output is produced at once. A wrapping application like a middleware stack can only rely on `ob_get_clean` to obtain the entire blob- and might run into memory and performance problems. 

I'm wondering if it made sense to extend the `StreamedReponse` API by providing an `echo()` or `emit()` method that well-behaved clients could use and wrapping applications modify that would allow to digest the streamed response in chunks.

**Comment by stof** [comment]
StreamedResponse expects the callback to echo the content. This cannot be changed as it would be a big BC break.
Thus, having to use a dedicated method to echo instead of using the PHP ``echo`` feature would forbid using any library using echo (for instance ``$twig->display()`` is very handy in streamed responses).
So I don't expect this to happen.

Regarding the memory issue, you may want to use an output callback for ``ob_start`` receiving the buffer in chunks and writing it into the ReactPHP Response and returning an empty string to avoid filling the buffer (not tested). I'm not sure this will allow to avoid the memory limit if there is no ``flush`` code regularly inside the StreamedReponse callback though.

**Comment by andig** [comment]
> you may want to use an output callback for ob_start receiving the buffer in chunks

Much appreciated. I wasn't even aware of that parameter! It seems funny that PHP would interrupt its own program flow but thankfully it does. If somebody else wants to try this, according to my tests on Windows:

  - `flush()` doesn't influence the behaviour- so it doesn't matter if producer calls it or not
  - `$chunk_size` is needed to provoke any callbacks

**Comment by stof** [comment]
> $chunk_size is needed to provoke any callbacks

not really, but the callback is called only when flushing the ob buffer when it is ``0`` (which is the default).

**Comment by andig** [comment]
>> $chunk_size is needed to provoke any callbacks

> not really, but the callback is called only when flushing the ob buffer when it is 0 (which is the default).

I'm confused- using this code I don't get callback inspite of the `flush()`?

	<?php

	$block = 1;

	ob_start(function($buffer) use (&$block) {
		file_put_contents("out.txt", $block++ . PHP_EOL, FILE_APPEND);
		return '';
	// }, 4096);
	});

	for ($i = 1; $i++;) {
		echo str_repeat("$i ", 1024);
		flush();
	}

	ob_end_clean();

I do however get the callback when I specifiy the chunk size regardless if I use `flush()` or not.

**Comment by stof** [comment]
@andig ``flush`` is not the same thing than ``ob_flush``. see http://php.net/manual/fr/function.ob-start.php#refsect1-function.ob-start-parameters

**Comment by andig** [comment]
Got it. Since I can't rely on application calling `ob_flush()` either I'd still suggest using `$chunk_size` as well. 

Anyway as far as this ticket goes I'm entirely happy- much appreciated! I hope this can be of help to others looking for async usage of `StreamedResponse`.

**Comment by jakzal** [comment]
@andig so can we close this or is there anything to do here? :)
