### ISSUE TITLE
[Symfony 2.6] Retrieving user details from FOSUserBundle and displaying in twig error templates (prod environment)

### ISSUE THREAD

**Issue by bwenstar** [symfony/symfony#18912]
Hello,

I have various error templates in my /app/Resources/TwigBundle/views/Exception/ directory.  They are working fine but I want to pass through the user's details to the error page. 

I have read this link: http://symfony.com/doc/2.6/cookbook/controller/error_pages.html#avoiding-exceptions-when-using-security-functions-in-error-templates 

I understand that the routing is generated before security but is there anyway to do this? or can I switch the priority of the listeners?

I'm just looking to pass through {{ app.user.name }} or {{ app.user.email }} to my twig templates.  I have an error template that is the child(?) (extending my main.twig) which contains the details I wish to use there.  

Thank you

**Comment by iltar** [comment]
For support, please use one of the support channels: http://symfony.com/support

You're also viewing an out-of-date docs version, you might want to check a newer version

**Comment by javiereguiluz** [comment]
@bwenstar sadly I need to close this issue because in the GitHub repository we only discuss about Symfony bugs and new features. For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

By the way, @iltar is right: Symfony 2.6 is unsupported since long ago. Updating to 2.7 shouldn't be hard and it will give you years of support.
