### ISSUE TITLE
[console] OutputFormatter performance issues

### ISSUE THREAD

**Issue by aik099** [symfony/symfony#18976]
The `OutputFormatter` class is without doubt most powerful tool, when it comes to displaying nice looking texts in the CLI application. It is made with best OOP practices in mind, but that on the other side results in lot of method calls to perform really simple things. This in turn makes application slow when it needs to display a lot of data.

The #18957 issue clearly demonstrates, that reducing usage of `OutputFormatter` class have massively improved overall application speed.

To approach this from the right angle I'm recommending to refactor `OutputFormatter` itself to be fast instead of just using it less frequently.

**Comment by javiereguiluz** [comment]
I'm closing this issue because it's not actionable (it only suggests to refactor OutputFormatter class) and because @aik099 already improved A LOT the performance of OutputFormatter (see #18957). So, this is "fixed" by now ... but in the future, if someone faces more performance issues, we can open a new issue with specific problems and details. Thanks!
