### ISSUE TITLE
/app/console doctrine:schema:validate with no Entities defined

### ISSUE THREAD

**Issue by rogerwalt** [symfony/symfony#18997]
Shows mapping OK and database in sync, but there is nothing to compare or sync. It's correct in a mathematical sense but very impractical to say it's OK and in sync when there's nothing to compare or sync. If you can point me to the corresponding code I'd be happy to write a patch.

**Comment by javiereguiluz** [comment]
@rogerwalt yes, maybe it's better to display a message saying that there are no entities, so nothing is validated. If you want to send a pull request for this, you must do it in the DoctrineBundle repository. Specifically, this command is defined in this file: https://github.com/doctrine/DoctrineBundle/blob/master/Command/Proxy/ValidateSchemaCommand.php

Therefore, I'm closing this issue because we can't fix this from Symfony ... but you can create a new issue at https://github.com/doctrine/DoctrineBundle  Thanks!

**Comment by rogerwalt** [comment]
Thanks @javiereguiluz. [https://github.com/doctrine/doctrine2/pull/5872](url)
