### ISSUE TITLE
[Security][Guard] Per authenticator configuration via security factory

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#19175]
This is first a question, since there is no real documentation for this component yet.

In Guard, the end user can use several authenticators per firewall, that is something nice.
The problem is that we can't define any extra configuration per authenticator.
I mean that we don't have any alternative to the classic SecurityListenerFactor but per authenticator.

Does providing this feature (extra configuration per authenticator) can be envisaged?
If it is, I can work on. 
Otherwise, is there any alternative?

For a real use case, please see https://github.com/lexik/LexikJWTAuthenticationBundle/pull/184#issuecomment-228466149 and the (very light) code that comes with.

ping @weaverryan What do you think?

**Comment by chalasr** [comment]
Our better alternative for now is to move the whole (actual) per-firewall configuration into the bundle config, and document how to create a custom authenticator service based on ours, letting the possibility to override the configuration through the service arguments.

The idea of having end users forced to create one service per firewall sounds weird IMO. Any idea?

**Comment by chalasr** [comment]
ATM it seems the only available way is to make our service overridable as easy as possible, so users can override arguments by creating child services, as needed.

Closing because of the lack of comments

**Comment by weaverryan** [comment]
@chalasr for the record, I agree :). Security is difficult, due to firewalls. But in general, the purpose of most bundles is to provide services, and the bundle configuration is the way that the user is able to control how those services are instantiated/configured. Why should services for security be any different? Use the bundle configuration to configure the service, then use the service as your guard authenticator.

Life does get a *bit* more difficult if you want your user to be able to create *multiple* authenticator services (each with their own configuration). This can be solved either like Doctrine solves it (e.g. with their connections or em's) or by making it easy to configure 1 service, and making the user do more manual work to configure multiple services, since that will be an edge-case.

Cheers!
