### ISSUE TITLE
[CS] [Proposal] Replace calls to `0 === count(array())` with `!array()`

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#19182]
Since [empty arrays always evaluates to `false`](http://php.net/manual/en/types.comparisons.php), these checks can be simplified.
An example from [`Symfony\Component\Routing\Annotation\Route::setRequirements()`](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Annotation/Route.php#L110):
```php
// current check
if (0 === count($this->methods)) {
    // ...
}

// proposed check
if (!$this->methods) {
    // ...
}
```

NOTE: I've found 54 exact matches for `0 === count(` at `2.7` branch.

**Comment by nicolas-grekas** [comment]
Dont forget countable objects

**Comment by Simperfit** [comment]
I agree when these are pur array since it can be faster.

**Comment by phansys** [comment]
Thanks for pointing that @nicolas-grekas. Are we widely using this notation to allow (now or later) either an `array` or an instance of `Countable` for these checked collections, or we can apply this change making the distinction in each replacement?

**Comment by nicolas-grekas** [comment]
I don't think we use countables much, still, when count is used, we must be
sure to not break BC, which means this should be thought on a case by case
basis. Not sure it's worth doing now...

**Comment by phansys** [comment]
I'll await for more feedback then, but I don't know if this change should be against `2.7` or `master`.

**Comment by nicolas-grekas** [comment]
2.7 if any

**Comment by Tobion** [comment]
Is there a performaance difference considering counting is not necessary?

**Comment by phansys** [comment]
I haven't any benchmark @Tobion, but I can do something about that.

**Comment by phansys** [comment]
The results shows that the proposed syntax is much faster than the original: https://3v4l.org/GETTr

**Comment by javiereguiluz** [comment]
I like this proposal and @phansys showed that it's 4 or 5 times faster than the existing code. But at the same time I don't like this proposal because the code is way harder to read.

---

If I see this:

```php
if (0 === count($this->methods)) {    }
```

I instantly understand it as *"if the array has no elements"*.

---

But if I see this:

```php
if (!$this->methods) {    }
```

I understand it as *"if this is null"*, *"if this doesn't exist"*, *"if this is false"*, etc. And *"if this has no elements"* comes much later.

---

So, if understanding the code as *"this has no elements"* is important, this change shouldn't be made.

**Comment by ro0NL** [comment]
Im very :+1: on this, basicly we can write faster. @javiereguiluz with a good object domain and understanding of it this should be not so much a problem, ie i read;

_"If the object has no methods available"_. (With `methods` being a bad example perhaps, but you get the point).

**Comment by jvasseur** [comment]
Maybe we could use `if ([] === $this->methods)` instead, it is faster than the count method (https://3v4l.org/m9CNV) and still convey the meaning "this array is empty".

**Comment by ro0NL** [comment]
It's still boilerplate code, but definitely better than `count` imo.

**Comment by WouterJ** [comment]
👎:

 * The time saved is nearly nothing. I mean even after 10.000 calls, the count one still takes just 0.004 seconds.
 * I agree with @javiereguiluz here. Using count is way more readable and clear. (for instance, I thought `!array(null)` would be true as well)
 * As illustrated by @nicolas-grekas, this fix wouldn't be as trival as just running PHP CS fixer, as we have to take care of not breaking BC. Also, this means inconsistency is introduced, people will start submitting PRs to change other count usages as well, which we then have to close because of BC breaks, etc. I don't think it's worth it, let's focus on some parts of the app that can reduce way more response time instead :)

**Comment by ro0NL** [comment]
Reconsidered this. I think using `count` is good in a way; it will probably break the code whenever the type changes (due refactoring whatever). Only if this were the case ;-) `count($whatever)` is still unpredictable for simple types.

Besides that this could lead to counts in loops, and what if the tested array is actually not empty: https://3v4l.org/1sCIf Im not a performance expert, but the gain for the 5.5/5.6 seems significant.

So im :+1: for either `array() === $var` or `!$var`. Where the first is perhaps more strict.

**Comment by phansys** [comment]
@WouterJ, please note that my proposal isn't about a rule for `php-cs-fixer`, as the matching cases require attention to decide. What I'm proposing here is to aim developers to avoid a call to a function which isn't really required in order to achieve the expected goal, regardless the semantic perspective as @javiereguiluz pointed.
This means we should be able to write a new item at coding standards docs stating something like "Checks against empty arrays MUST be done using logical not ( ! ) operator".

**Comment by WouterJ** [comment]
> What I'm proposing here is to aim developers to avoid a call to a function which isn't really required in order to achieve the expected goal, regardless the semantic perspective as @javiereguiluz pointed.

At this is exactly what I don't agree on. I mentioned the PHP CS Fixer to illustrate that this isn't a quick and trival change.

**Comment by iltar** [comment]
Considering [this][1], I would say stick with `count()` for the sake of consistency. Notice that generators give a different value in count due to a generator object being returned (which might be a php bug?)

[1]:https://3v4l.org/iR82P

**Comment by fabpot** [comment]
As the new code is less readable and as the current code does not have a huge performance impact, I'm 👎 as well for this change.

On a more general note, when thinking about making similar changes, we should also always think about this bigger impact on Symfony: what value does it bring (value is not just about features, it's also of course about maintainability, consistency, ...)? Is it worth discussing? Is it worth taking the time to do the change, discuss it, merge it, document it, enforce it, ...
