### ISSUE TITLE
Deprecate Container::set() for non-synthetic services

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#19192]
See discussion here:
- https://github.com/symfony/symfony/pull/19146#discussion_r68385379
- https://github.com/symfony/symfony/pull/18728#discussion_r62531184

**Comment by stof** [comment]
Copying my comment from #19146 so that people looking at this issue know about the case preventing to deprecate it blindly:

``set('doctrine.orm.entity_manager', null)`` is used by the Doctrine manager registry (in the bridge) to reset the entity manager service (due to the fact that the entity manager becomes unusable after an exception during a flush, because the unit of work is know to be in a broken state).
So we should still at least support this use case.
Allowing to reset an existing instance of the ORM cannot happen without a major change in the ORM (which I will ask to be done in Doctrine 3, but this is not planned to happen soon), so we need to be able to reset the service, to be able to use the ORM in long running scripts like a RabbitMQ consumer (if we cannot reset the service, the only solution would be to kill the process)

**Comment by nicolas-grekas** [comment]
@stof looking at `resetManager()` in doctrine bundle, it's up to the user to call it, and one must ensure to always get the entity manager through the container (vs injecting it directly) so that resetting works. It looks like a hack to me :) Yet it works and we have to provide an alternative.
If Doctrine can't manage to provide a resettable manager before Symfony 4.0 is out, we might also make it resettable but using a resettable lazy proxy from ProxyManager (if possible).

**Comment by stof** [comment]
@nicolas-grekas or to get it from the registry, which is how things are done.
And yes, I agree that it is hacky. A resettable entity manager would be the clean solution, but all doctrine O*M projects are suffering from the same limitation (as they are all based on the architecture of the ORM) and changing it would take time (while the Doctrine team is lacking developer resources currently). Thus, if it happens only in a new major version, we could have to keep supporting the 2.x branch for some time due to adoption rates.

Regarding using a proxy object to make it resettable, this might be an option, but it would force us to have a hard dependency on the proxy manager in all doctrine bundles (which may be considered fine though), and it may have a performance impact (which needs to be investigated)

**Comment by stof** [comment]
@Ocramius does ProxyManager supports something like what we describe here to wrap the EntityManager in a resettable object ? This would allow us to know what our options are.

**Comment by Ocramius** [comment]
Yes, a proxy object can do that eventually. Not sure about exception handling tho...

**Comment by nicolas-grekas** [comment]
Done & tested in #19203, so that we're now sure to not break anything and move on safely.

**Comment by nicolas-grekas** [comment]
ping @ro0NL since you're in the DI business these days, any chance you could look at implementing this one? :)

**Comment by ro0NL** [comment]
@nicolas-grekas can you explain a bit (im not really familiar with proxy managers on a low-level). But reading

> Deprecate Container::set() for non-synthetic services

im not really sure how we would even do that.. the [contract](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/ContainerInterface.php#L34) is clear on this right?

**Comment by nicolas-grekas** [comment]
**Overwriting** a non synthetic service should be deprecated.

**Comment by ro0NL** [comment]
At the first looks of it, [this](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Container.php#L177) needs to be deprecated.

However.. it's getting late. Im lost.. it's probably their for some reason. I wasnt really aware of this to be honest. Ill have a look tomorrow (lets see what tests are gonna fail :))
