### ISSUE TITLE
use hungarian notation

### ISSUE THREAD

**Issue by sliecer** [symfony/symfony#19219]
Use the hungarian notation for the Framework. Debugging of web applications would be much easier for developers. (https://en.wikibooks.org/wiki/PHP_Programming/Alternative_Hungarian_Notation)

**Comment by stof** [comment]
This does not make things much easier IMO. I find this notation quite unreadable.

**Comment by pasdeloup** [comment]
Seems to be a troll: he created a github accound just to post the same issue on Symfony, CakePHP and Zend Framework

**Comment by javiereguiluz** [comment]
@pasdeloup opening the same issue in several repos doesn't turn him/here into a troll :)

@sliecer thanks for opening this issue to propose some changes for Symfony's code. Sadly, I'm afraid it will be "impossible" to take it into account. This proposal would imply thousands of changes in our variable names. In turn, that would introduce hundreds of conflicts in our codebase (because we maintain  5 different branches at the same time and we merge lower branches into higher ones).

Thankfully we document the type of the properties/variables with PHPdoc, so we almost get the same advantages of this proposal but without its disadvantages.

Therefore, I'm going to close this issue as "won't fix". Thanks for understanding it.

**Comment by lin4you** [comment]
Thank you for your detaild and constructive feedback.

**Comment by irufus** [comment]
I think I know who this troll is.
