### ISSUE TITLE
[LDAP] Retrive additional fields into a user

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony#19329]
I was using https://github.com/BorisMorel/LdapBundle before Symfony 2.8, but now with Symfony 3.1 I am using the built-in LDAP mechanism.

One of the things I miss is the ability to pull in custom user fields from LDAP. For example I was pulling in email and fullname.

Is there a way to do this with Symfony's LDAP component already? I looked at the documentation:
http://symfony.com/blog/new-in-symfony-2-8-ldap-component
http://symfony.com/components/Ldap (this is blank!!! linked to from the above)
http://symfony.com/doc/current/cookbook/security/ldap.html

and couldn't find either an easy way to do it, or a guide on how to implement this myself if that is the desired way to do it.

I propose two things:
a) that the ldap component provide an easy way to configure additional fields to pull in
b) that the documentation reflect this, or a cookbook is made on how to do it ourselves

Thanks!

**Comment by iltar** [comment]
Regarding the documentation, you can check if there's already a similar issue and if not, create one: https://github.com/symfony/symfony-docs

**Comment by csarrazi** [comment]
Hi @ofbeaton! This is something which is currently being considered, and I've been thinking a lot about adding support for associating user groups to LDAP attributes or entries. While I cannot provide you an ETA, this is something I have been working on since a few months, slowly but surely.

Currently, there is no support for pulling in custom user fields. If you want to do this, you will need to override the LDAP user provider (or re-implement a LDAP-based user provider) with your own logic.

**Comment by Simperfit** [comment]
isn't that a dupplicate of https://github.com/symfony/symfony/issues/28873 covered by #31532  ?

**Comment by ofbeaton** [comment]
Yes #28873 is a duplicate of this issue (this issue is 2 years earlier). The other difference is that the issue you mentioned proposes what the configuration would look like.

I'm excited to hear someone is working on a PR for this though! When it merges this should be closed. It seems to cover this use case from what I can tell.
