### ISSUE TITLE
Fixtures/DoctrineBridge: ContainerAwareLoader uses removed ContainerAwareInterface

### ISSUE THREAD

**Issue by hobbysoldat** [symfony/symfony#19335]
Using Doctrine Fixtures Bundle and the Doctrine Datafixtures package, the container is not injected into fixtures anymore when using Symfony 3, because the ContainerAwareLoader only checks for the presence of the (removed in Symfony 3) ContainerAwareInterface.

Expected Behaviour: The Container should be injected into fixture classes even when they only use the new ContainerAwareTrait, because there is no way to implement a removed Interface.

**Comment by ogizanagi** [comment]
The [ContainerAwareInterface](https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/DependencyInjection/ContainerAwareInterface.php) still exists in sf > 3.0. Only the [ContainerAware](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/DependencyInjection/ContainerAware.php) abstract class has been deprecated in 2.8 and removed in 3.0.

You should use the trait + the interface in order to have the container being injected in your class.

**Comment by hobbysoldat** [comment]
How could I miss that! I was sure my IDE marked the Interface as missing. So I have to use the ContainerAwareTrait and implement the ContainerAwareInterface. Thanks for your Help.
