### ISSUE TITLE
[Security] Move Required PHP version to 5.6.x

### ISSUE THREAD

**Issue by ErichHartmann** [symfony/symfony#19349]
PHP version 5.5 ended (EOL) on 10 July for security patches. Recommend the required PHP version be moved to PHP version 5.6.x. Support for this last 5.x version will continue until 31 Dec 2018.

http://php.net/supported-versions.php

**Comment by Tobion** [comment]
Symfony 4 will only require a new PHP version.

**Comment by javiereguiluz** [comment]
@ErichHartmann thanks for proposing this change. Indeed PHP 5.6 and up are the only safe choices for PHP developers. However, we can't change the minimum PHP version required by Symfony because that would break some applications that rely on the fact that Symfony 3.x requires PHP 5.5.

In any case, the minimum PHP version is just a reference for us when adding new code. People can run Symfony apps with higher versions and most of them do that (even running PHP 7).
