### ISSUE TITLE
[3.1][HttpKernel] ArgumentResolver not used as ParamConverter bails out

### ISSUE THREAD

**Issue by havvg** [symfony/symfony#19354]
I'm on removing a custom system with the same goal as the `ArgumentResolver`. However, when converting one into a `ArgumentValueResolver`, the system is not capable of resolving, as a `ParamConverter` bails out by throwing an `\Exception`.

My use-case: The resolver resolves a doctrine entity, which is not related to the request. Therefore the `ParamConverter` throws `Unable to guess how to get a Doctrine instance from the request information.`.

My expectation: The `ArgumentValueResolver` will be asked, too (which would yield the correct entity).

**Comment by iltar** [comment]
@havvg The parameter converter listens to [`kernel.controller`][pc listener] and puts the resolved value in the request attributes (or throws an exception). Eventually one of the value resolvers will fetch that value from the attributes. It will never reach the value resolvers because they are called [after the `kernel.controller` has finished][http kernel].

If you wish to make it "fall back" to the value resolvers, try adding `= null` to your argument. This way the PC won't throw an exception.

[pc listener]: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/EventListener/ParamConverterListener.php#L52
[http kernel]: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpKernel.php#L136-L150

**Comment by havvg** [comment]
@iltar Thanks for your explanation.

However I don't consider making the parameter optional a valid solution. The parameter is not optional.

Is this considered expected behavior? 
Then I have to abort switching to this feature in favor of the already existing custom solution (which also listens on `kernel.controller` with higher priority as the `ParamConverterListener`).

**Comment by iltar** [comment]
The argument value resolver is not (yet) a 1:1 replacement for the parameter converter, especially not as fallback. The "problem" you face is that the existing implementation (parameter converter) throws an exception. If you can get around that, you should be safe.

One way could be by decorating the listener and catching the exception, but this would break your other cases where you don't want a fallback. @stof had the idea to move the PC to a value resolver as well, but ideally I'd simply make it possible to request the controller configuration (which can be an annotation, or even yaml/xml/php). Sadly I'm not sure if I will even get to finish this before 3.2 as this change is quite complex. See: #19338

So regarding your question, this is "expected" behavior. _I'd call the doctrine PC a bit greedy and verbose._

**Comment by havvg** [comment]
I opted for the decorator, too. Just in case someone is looking for an example (may be incomplete for different use-cases): https://gist.github.com/havvg/54ba33fc11316485887add8aa030f11d

**Comment by iltar** [comment]
:+1: Looks good

**Comment by xabbuh** [comment]
Is there anything we can actually do in the core about this issue (the pan converters are part of the SensioFrameworkExtraBundle)?

@HeahDude Maybe something you want to consider?

**Comment by iltar** [comment]
@xabbuh see https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/436

Fabien was working on something, but I don't know if he had the time to finish this

**Comment by xabbuh** [comment]
@iltar Yeah, but can we do anything more in the core (I actually doubt so)?

**Comment by iltar** [comment]
No, this is something that the sensio framework extra bundle has to solve, like disabling the doctrine PC (which I would actually use as feature)
