### ISSUE TITLE
Dynamically added on submit field default view data missing

### ISSUE THREAD

**Issue by marfillaster** [symfony/symfony#19370]
Obviously we can set the default value of date in-form. But the intent is to demonstrate the form's behavior wherein instead of defaulting to next day as value(since form[date] has not been posted yet), the dynamically added date field will be empty. 

```
class Schedule
{
   public $postponed;
   public $date;
}

$sched = new Schedule
$sched->date = new \DateTime('+1 day');

$builder->add(
   $builder->create('postposed', CheckboxType::CLASS)
	   ->addEventListener(FormEvents::POST_SUBMIT, function(FormEvent $event) {
			if ($event->getForm()->getData()) {
				$event->getParent()->add('date', DateType::CLASS);
			}
	   })
);
```

Workaround:

```
$event->getParent()->add($factory->createNamedBuilder('date', DateType::CLASS, null, array(
         'auto_initialize' => false,
    ))
    ->addEventListener(FormEvents::PRE_SUBMIT, function(FormEvent $event) use($sched) {
			if (null  === $event->getData()) {
                                //  pre-populate when data is null. check is unreliable for some cases
                                // Perhaps implement FormInterface::isMissingFromRequest ?
                                $event->setData($sched->date->format('Y-m-d));
			}
     })
    ->getForm()
);
```
The above workaround quickly gets ugly on compound types.

I was hoping if there is a utility to get view data quickly. I'm currently using this for complex form graph.

```
$recursiveFormViewData = function($form, $choice = false) use(&$recursiveFormViewData)
    {
        if (!$choice && ($children = $form->all())) {
            $viewData = array();

            foreach ($children as $name => $childForm) {
                $viewData[$name] = $recursiveFormViewData($childForm, $childForm->getConfig()->getType()->getName() === 'choice');
            }

            return $viewData;
        }

        return $form->getViewData();
    };
```

**Comment by dmaicher** [comment]
Not sure I understand what you want to do. So if the user does not enter any date you want it to not be set to `null` on your model but keep `\DateTime('+1 day')`?

Also in `POST_SUBMIT` you should not add/remove any form fields: http://symfony.com/doc/current/form/events.html#c-the-formevents-post-submit-event

**Comment by marfillaster** [comment]
@dmaicher `POST_SUBMIT` is the only way to add fields based on submitted value of existing field. 

The example posted allows an optional future date when checkbox postponed is ticked. The problem is when the form is submitted, the default value( new day) is replaced with an empty value. Aside from interepting the request data on `PRE_SUBMIT`, another workaround is to add the field during setup and just skip form render. This however makes it unwieldy when we're adding many dynamic fields.

**Comment by HeahDude** [comment]
>POST_SUBMIT is the only way to add fields based on submitted value of existing field.

As said @dmaicher you should use `PRE_SUBMIT` event to handle dynamic field base on to-be submitted data otherwise it won't have any effect. `POST_SUBMIT` let you access the model data modified by submission but won't change the form and this is expected, so I don't see any issue here.

**Comment by HeahDude** [comment]
Hey @marfillaster any news?

**Comment by backbone87** [comment]
Using POST_SUBMIT here is fine, because its attached to a child that is manipulating the parent (root in this case).

The problem is within the clearMissing flag. I guess that there isnt even a value submitted for date, so it gets set to `null` because of the clearMissing flag. see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L561

Skipping the rendering of the field isnt the correct way either, because you need the initial field data to be POSTed, so you render the field and set it `display:none;` as long as `postponed` isnt checked. you can abstract this into a commen JS helper that is trigger via data-attributes set on the checkbox and/or the field to be hidden.

Also setting the empty_data might help:
```php
class Schedule
{
   public $postponed;
   public $date;
}

$sched = new Schedule
$sched->date = new \DateTime('+1 day');

$listener = function(FormEvent $event) {
  if ($event->getForm()->getData()) {
    $event->getForm()->getParent()->add('date', DateType::CLASS, [
      'empty_data' => $event->getForm()->getParent()->getData()->date;
    ]);
  }
};
$builder->add('postponed', CheckboxType::class);
$builder->get('postponed')->addEventListener(FormEvents::POST_SUBMIT, $listener);
``´

**Comment by HeahDude** [comment]
@backbone87 If the field is not added at `PRE_SUBMIT` you won't be able to submit the data in it, transformations in `POST_SUBMIT` only impacts the view.

**Comment by backbone87** [comment]
@HeahDude But he attached the listener to the child and adds a field to the parent. This does work, but could be unintented API-wise

You are correct, if he attaches the listener to the POST_SUBMIT of the parent, because at that point, the parent is already completely submitted and you cant even add a field anymore:
- Submitted gets set to true: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L648
- POST_SUBMIT is called: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L655
- Adding of fields throws exception, because submitted is true:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L803

**Comment by marfillaster** [comment]
@backbone87 I like your approach where you made the dependent field `schedule` available on form build and then removed based on the submitted value of `postponed`. This has a nice side effect of maintaining the default value.

**Comment by HeahDude** [comment]
@backbone87 I like that, thanks! Let's close here then :)
