### ISSUE TITLE
[Routing] Add naming strategy configuration

### ISSUE THREAD

**Issue by azatyan** [symfony/symfony#19421]
Hi

What you tink about adding naming strategy config here?

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php#L200

**Comment by iltar** [comment]
I think you should always give a route a name manually.

**Comment by azatyan** [comment]
@iltar  it can save too much time on large projects and this is not a mandatory. we only need 2-3 nice strategies to implement.

**Comment by iltar** [comment]
@azatyan I know all about large projects, being verbose in those large projects is extremely important. If you let one of the strategies define the name, you will have to guess the name if you want to link to that action or use the `debug:container` command all the time.

**Comment by jakzal** [comment]
👎 I also prefer do be explicit. Relying on automatically generated route names might look like a time-saver, but what it really does is it couples your route names to controller/action/path names. As a result it makes refactoring harder. Route name is there to decouple from those, so you can change one without changing the other.

**Comment by azatyan** [comment]
It's a developer's choice like human rights.  If you prefer manually you can write manually.

**Comment by iltar** [comment]
Consider it a recommendation of experienced developers to write them out manually. For RAD development I think the current strategy is fine, mainly because refactoring is costly.

**Comment by azatyan** [comment]
it can be  

"{class}_{action}"   - 1 main bundle
"{prefix}_{action}"  - App name - action
"{bundle}_{class}" - Rest (no action name required)

**Comment by azatyan** [comment]
Also this can be bundle-level configuration

**Comment by iltar** [comment]
How would you configure this per bundle?

**Comment by azatyan** [comment]
there is many ways, maybe in Bundle Class, with some pattern setting

**Comment by ogizanagi** [comment]
@azatyan If you don't bother about naming your routes yourself, that means to me that you don't bother about their names in the application. 
So why would you need having different strategies ?

**Comment by javiereguiluz** [comment]
@azatyan I'm afraid that relying on "auto-magic" route names is a very bad practice because even the slightest change in your controllers will break the application entirely.

We added this feature because sometimes a controller doesn't have to be mapped to a route (e.g. when the controller is always used inside `render(controller('...'))` calls). You can think of this as an "anonymous route" ... but in Symfony every route must have a name ... so we assign them a name generated automatically.

In any case, any non-trivial application should never use this feature ... and that's why I agree with previous comments and my vote is 👎 . I hope you understand it. Thanks!

**Comment by azatyan** [comment]
@ogizanagi  to have choice, for example one dev loves some scheme, other, other...

**Comment by azatyan** [comment]
@javiereguiluz  if we create right model, it can be usable for example, auto route name,  like   "shop_view", "shop_edit",  "app_index" "app_about" .

About automation - it should be fully controllable

**Comment by javiereguiluz** [comment]
I'm closing this issue as "won't fix" because it received some `-1` votes from Symfony Core members and they provided technical reasons.

@azatyan it's sad when a proposal doesn't make it ... but please keep sending them because technical discussions about anything are always a good thing! Thank you.
