### ISSUE TITLE
Clearing the cache fails because the cache is outdated

### ISSUE THREAD

**Issue by UlrichEckhardt** [symfony/symfony#19429]
There is a cyclic dependency between the `cache:clear` command and the cached service container itself, causing it to sometimes fail when the services are adjusted.

In order to reproduce this, consider these steps:
1. Create a normal Symfony setup.
2. Create a command using dependency injection (i.e. `services.yml` or similar).
3. Run that command. This will cause the cached service container to be created.
4. Adjust the command added in step 2 so that it takes an additional parameter, e.g. the logger.
5. Run `app/console cache:clear`.

At this point, you get a `ContextErrorException` which is caused by loading the cached service container and retrieving the command defined in step 2. Since the cache is outdated, it doesn't provide the new parameter added in step 4. At this point, you are basically SOL with builtin tools, you have to manually delete the cache folders.

A variation of this is when extending `setContainer()` in a container-aware command to retrieve the dependencies. The idea is to override `setContainer()`, call the baseclass first and then retrieve your own dependencies. Similar to the variant using dependency injection, this fails when `setContainer()` is called based on an outdated service container cache.

I have tried to hack around this and was able to at least get the `setContainer()`-based approach running:
- In class `Symfony\Bundle\FrameworkBundle\Console\Application`, I removed the loop calling `setContainer()` on the commands. Instead, I only called `$this->registerCommands()` in that place. 
- In the baseclass `Symfony\Component\Console\Application`, I called `$command->setContainer($this->getKernel()->getContainer())` on the invoked command. Of course this doesn't work reliably, because I'm simply assuming that the derived class has a kernel with a container, it's just a proof-of-concept hack.

Some more notes:
- Why are unused commands retrieved from the service container at all? A much better approach would seem to just locate the one command that is called, so that issues with other commands don't cause complete failure. Loading an initializing all other commands seems like a waste of CPU to me.
- Another approach would be to log and ignore failure to register commands. This could allow commands to veto their registration. It would also cause the variant using dependency-injection to not fail fatally when just one dependency is temporarily broken.
- I'm using Symfony 2.8 on Debian.

**Comment by iltar** [comment]
I've never seen this before to be honest, it's correct that you get an exception because 1 argument is missing. If you would've changed the service definition, the container has to be rebuild either way and in dev will be done automatically.

> Why are unused commands retrieved from the service container at all? A much better approach would seem to just locate the one command that is called, so that issues with other commands don't cause complete failure. Loading an initializing all other commands seems like a waste of CPU to me.

I agree. They are loaded because the instance is required to return the name of the command. There are alternative ways to do so (tagging, static functions for container aware, annotations etc.), but would require a big change.

**Comment by stof** [comment]
@iltar this is the common issue about using the console to clear the cache: in a non-debug environment, this requires to boot the kernel in the new codebase, but with the old cache (as it does not check for freshness).
This is impossible to fix as long as we want to keep ``app/console cache:clear`` instead of using a standalone script to clear the cache (independent from the kernel being booted to start executing the command)

**Comment by stof** [comment]
btw, there are a bunch of other changes which can cause similar issues. So only catching exceptions during the registration of commands will not help

**Comment by iltar** [comment]
I have to admit that I simply use `rm -rf var/cache/*`.

I guess this simply emphasizes the need of metadata about commands.

**Comment by javiereguiluz** [comment]
@UlrichEckhardt thanks for reporting this, but I must close it now as "can't fix" because there are some well-known and unsolvable edge-cases when clearing the cache.

Luckily, in the next Symfony 4 version all this will be solved because the cache clear is not executed via the Symfony application itself but via a Makefile task.
