### ISSUE TITLE
Missing PhpDocs for object fields

### ISSUE THREAD

**Issue by MacDada** [symfony/symfony#19500]
Example: https://github.com/symfony/symfony/blob/v3.1.3/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L33

Could be like:

    /**
     * @var AuthenticationProviderInterface[]
     */
    private $providers;

Or at least:

    /**
     * @var array
     */
    private $providers;

Adding PhpDocs would ease up reading the code, as one could just see the type of data stored in a field, instead of reading all the class' code, to reason what it contains. And of course, it would make IDE autocompletion better supported.

I volunteer to add them and submit a PR.

**Comment by iltar** [comment]
Your IDE can already determine the type based on the constructor argument provided actually. In your example that would be: https://github.com/symfony/symfony/blob/v3.1.3/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L40

Imo docblocks should only be added if they add something. This could be scalar types, collection/generic type (`Foo[]`) or types otherwise not supported by default in the language or that version (which is often the former 2).

Inside symfony itself you won't have to worry about property types anyway, they are not part of the public API.

**Comment by robfrawley** [comment]
@iltar I agree with the first point in your post, but I take issue with

>Inside symfony itself you won't have to worry about property types anyway, they are not part of the public API.

Assuming the symfony teams wants open source collaboration, pull requests, etc (which I'm sure they do) they need to make sure their code is easy to understand, and this absolutely includes property types.

**Comment by nicolas-grekas** [comment]
The policy about phpdoc blocks is: only when it adds value. Since "adding value" is a subjective thing, we deal wth it on a case by case basis. E.g. when some docblock duplicates some obvious signature method, we prefer not adding it. etc.

Closing as this issue is too broad for this reason.

@MacDada if you find some comments that are missing and add clear value, please open PRs. But experience, these trigger a lot of comments (because hey, "value" is subjective here), so be prepared to deal with them.

**Comment by MacDada** [comment]
> Your IDE can already determine the type based on the constructor argument provided actually.

@iltar Not always. [EventDispatcher](https://github.com/symfony/symfony/blob/v3.1.3/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L35) is not constructor–injected but [setter–injected](https://github.com/symfony/symfony/blob/v3.1.3/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L61). Good luck with IDE guessing.

Anyway, the main reason I opened this issue was:

> Adding PhpDocs would ease up reading the code, as one could just see the type of data stored in a field, instead of reading all the class' code, to reason what it contains.

IDEs I mentioned laters, as less important.

> Imo docblocks should only be added if they add something.

@iltar For field definitions they do. They are **for people reading the code**.

You don't need to declare fields in PHP. And IDEs could be smart enough to type hint fields with values set in the constructor, although the fields were not declared.

But we still declare the fields. We do that, so one can immediately see what the object consists of. Without the need to read all class' code.

> Inside symfony itself you won't have to worry about property types anyway, they are not part of the public API.

@iltar But I still read the code. Sometimes I event modify it (to make a PR) or override it (with my custom code, similar to the Symfony's code). But mostly I read it. On GitHub as well, where u have no IDE magic ;-)

The code should be obvious, good, clean, readable without IDE magic. In this case it can. By simply adding the docblocks.

I'm not suggesting to add docblocks [for methods that have a PHP–built–in typehinting support](https://github.com/symfony/symfony/blob/v3.1.3/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L61). That actually doesn't add any value, as both for humans and the machines the situation is obvious.

But for fields, there is no such mechanism. Docblocks cannot help machines, but do help humans.

> please open PRs

@nicolas-grekas Will do.

**Comment by iltar** [comment]
Whether or not setter injection is good, is definitely debatable
