### ISSUE TITLE
Running vi with Process

### ISSUE THREAD

**Issue by denisvmedia** [symfony/symfony#19528]
Is that anyhow possible? I can run that with passthru(), but not with Symfony/Process.

Here is what I do:
```
        $process = new Process('vi');

        try {
            $process->setPty(true);
            $process->mustRun(function ($type, $buffer) {
                echo $buffer;
            });
            //echo $process->getOutput();
        } catch (ProcessFailedException $e) {
            echo $e->getMessage();
        }
```

Here is what I get:
```
The command "vi" failed.

Exit Code: 1(General error)

Working directory: [path]

Output:
================
Vim: Error reading input, exiting...
Vim: Finished.


Error Output:
================
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
```

**Comment by sstok** [comment]
It depends on what you are trying to do, are you using vi(m) to pass commands using php or do you want to open it for external editing?

**Comment by sstok** [comment]
OK, that should work. We are using it in Gush (any editor as configured with $EDITOR), but it will only work when it's opened as an external program (GUI). When you open vim in the background it will not work as there no interaction possible (or there is, how these things work always amazes me).

Maybe you need to use `setTty` instead of `setPty` but I'm not sure.

It's best to ask this in one of the support channels: http://symfony.com/support the issue tracker is only used for reporting bugs and discussing new features.

**Comment by denisvmedia** [comment]
@sstok magically setTty() works! Thank you!

**Comment by gggeek** [comment]
Sorry to bring back an old thread ;-) Here is my question:
- I seem to be able to use Process::setTty() to start an interactive process from php! Whee!!!
- However, if my main php script is executing a Symfony Console Application and Command, what I get is:
    - I can see the output of the interactive process
    - but I can not seem to be able to capture user input to pass it on to the interactive process :-(

Any tips ?

**Comment by gggeek** [comment]
Weird enough: I switched to Conso0le 2.8 (was using 3.1), and this seems to work out of the box :-)
