### ISSUE TITLE
deprecated LazyChoiceList

### ISSUE THREAD

**Issue by arno14** [symfony/symfony#19575]
Since I upgraded to SF 3.1.3 I have multiples warning when I run phpunit
```
Caching the choice list in Symfony\Component\Form\ChoiceList\LazyChoiceList is deprecated since 3.1 and will not happen in 4.0. Cache the list in the Symfony\Component\Form\ChoiceList\Loader\ChoiceLoaderInterface instead: 13x
```
I did not have them in SF 3.1.1 and I use the "choice_loader" options in multiple forms.

This is related to commits 98621f4355c65b6f8a8a63c80f9168fa639d7459 (and fix deb12ae1b5f27b1a276ba6f215261de945d2e622) by @tgalopin

As the construction of LazyChoiceList is hardcoded in DefaultChoiceListFactory I don't see how I could avoid theses warning.
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/Factory/DefaultChoiceListFactory.php#L40

**Comment by tgalopin** [comment]
That's indeed an issue, I should have check for usages of this deprecated class in Symfony core. I'll work on a PR to fix that.

**Comment by HeahDude** [comment]
Since the same choice list is returned from the default choice loader and this is tested (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Tests/ChoiceList/LazyChoiceListTest.php#L60), I don't understand why you get those warnings.

Are you using the `choice_loader` option somewhere?

**Comment by arno14** [comment]
As said in my first message I do use the "choice_loader" option.
The method used is then "Symfony\Component\Form\ChoiceList\Factory\DefaultChoiceListFactory::createListFromLoader" which return a LazyChoiceList.
When using the "choices" option, the "Symfony\Component\Form\ChoiceList\Factory\DefaultChoiceListFactory::createListFromChoices" method is used and this one return an ArrayChoiceList.

To be coherent with the deprecated message saying that the cache logical should be in the ChoiceLoader, this method should simply return the ChoiceList created by the Choice Loader

see https://github.com/symfony/symfony/pull/19591
(this pull request is not coherent with the DefaultChoiceListFactoryTest::testCreateFromLoader and 
DefaultChoiceListFactoryTest::testCreateFromLoaderWithValues)


I'm not very confortable with the syntax of theses test, but it seems that what is tested is the return value of the getChoices method.

As a LazyChoiceList is initialized in the setUp method, I suppose that a deprecated warning is also triggered when running Symfony/Component/Form test (  with 3.1.3 there are 8  Legacy deprecation notices and in 3.1.1 only 7)

**Comment by HeahDude** [comment]
There is nothing wrong with tests. If you use a custom choice loader, it has the responsibility to return a `ChoiceListInterface`, and before this choice list was stored in the lazy choice list instance which is now deprecated.

So your loader should now cache the list to return the same instance in order to get rid of the deprecations warning.

**Comment by arno14** [comment]
You are right.
When returning always the same instance in ChoiceLoaderInterface::loadChoiceList, no warning are displayed.

thanks
