### ISSUE TITLE
[Workflow] Digging in to the workflow component

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony#19605]
I just started to dig in to the workflow component in order to add some documentation. I noticed some strange behaviors and I would like to ask @lyrixx (or someone else) about these. 

The workflow has the concept of "places" which I first intrepid as "states". The main issue is that you can be on two places at once. 

``` php
// +---+     +----+     +---+     +----+     +----+     +----+     +----+
// | a | --> | t1 | --> | b | --> | t2 | --> | c  | --> | t4 | --> | f  |
// +---+     +----+     +---+     +----+     +----+     +----+     +----+
//             |                                          ^
//             |                                          |
//             |                                          |
//             v        +---+     +----+     +----+       |
//             -------> | d | --> | t3 | --> | e  | ------
//                      +---+     +----+     +----+
```

When preforming **t1** I will be in both place 'b' and 'd'. There is no way for me to fetch all subjects in state 'b'. Which, sure, that could be fine in some applications. But why do I need to separate 'b' and 'd'? 

But as a consequence of this, we run into other issues. Say that I'm writing a blog and want a workflow for the blog post. One could imagine the following states: init, draft, review, published, trash, rejected. 

You could also imagine the following translations: 
- init => draft
- draft => review
- trash => review
- rejected => review
- draft => trash
- rejected => trash
- review => published

Since a transaction can have multiple "froms" and "tos" it makes sense to create `Transactions` like: 

``` php
$definition = new Definition();
$definition->addPlaces(['init', 'draft', 'review', 'published', 'trash', 'rejected']);
$definition->addTransition(new Transition('to_draft', 'init', 'draft'));
$definition->addTransition(new Transition('to_review', ['draft', 'trash', 'rejected'], 'review'));
$definition->addTransition(new Transition('to_trash', ['draft', 'rejected'], 'trash'));
$definition->addTransition(new Transition('to_publish', 'review', 'publish'));
```

So whenever you have a `BlogPost` you could check if it is possible to put this in the "review" place. 

This is however not possible because the "to_review" transaction expects you to be in **all** "from" places ('draft', 'trash', 'rejected'). ([See source](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/Workflow.php#L180-L184))

With the current implementation you need to define transactions like:

``` php
$definition->addTransition(new Transition('to_review_from_draft', 'draft', 'review'));
$definition->addTransition(new Transition('to_review_from_trash', 'trash', 'review'));
$definition->addTransition(new Transition('to_review_from_rejected', 'rejected', 'review'));
```

Is this really the intention?

I suggest we should behave more like state machines and do not allow one to be in two places/states at the same time. I suggest to removing the possibility for a transaction to have multiple "to". A transaction should be something that takes you from one or more places to a defined place. This would make my initial graph look like this: 

``` php
// +---+     +----+     +---+     +----+     +----+     +----+     +----+
// | a | --> | t1 | --> | b | --> | t2 | --> | c  | --> | t4 | --> | f  |
// +---+     +----+     +---+     +----+     +----+     +----+     +----+
//                        |                               ^
//                        |                               |
//                        |                               |
//                        v       +----+     +----+       |
//                        ------> | t3 | --> | e  | ------
//                                +----+     +----+
```

**Comment by Nyholm** [comment]
I added a test for this issue in: https://github.com/symfony/symfony/pull/19607

**Comment by lyrixx** [comment]
Hello @Nyholm 

> When preforming t1 I will be in both place 'b' and 'd'. There is no way for me to fetch all subjects in state 'b'. Which, sure, that could be fine in some applications. 

Yes you can. But indeed with the default configuration it might be not so easy as the data is stored in a json. But you can use one of the following solution:

* PostgresSQL (and maybe more RDBMS) has a native support for JSON, so it's easy to query it.
* update the DomainObject::setMarking(array $marking) to store each places as single Boolean properties
* update the DomainObject::setMarking(array $marking) to store each places as a bit field in the property
* if your net will always be "simple" (ie there are never 2 or more destinations for one transitions) you can use the `ScalarMarkingStore`. Like that a simple string will be stored in your database.
* You can use your own MarkingStore and store in a new table the current marking. The table could look like Table ('object_id', 'init', 'draft', 'review', 'published', 'trash', 'rejected').

> But why do I need to separate 'b' and 'd'?

It really depends of you application. Sometimes you want to be in two places at the same time. It means you can paralyze actions. You can [see it in action](http://symfony-workflow-demo.herokuapp.com/show/420?_switch_user=admin).

> Is this really the intention?

Yes, indeed. It's a workflow net and not a state machine. That's why you need to declare more transition for what you try to do. 

BTW, I want to add a new property to a transition `title` to be able to share the same title (`review` in your case). Like that, the "long & accurate" name will be used internally, and a simple name could be exposed to the end user.

> I suggest we should behave more like state machines

State machines are too simple and does not cover many cases, that's why we implemented a workflow net.

**Comment by Nyholm** [comment]
> Yes you can. But indeed with the default configuration it might be not so easy as the data is stored in a json.

Okey, fair. I guess I need to include that in the documentation. 

> It really depends of you application. Sometimes you want to be in two places at the same time. It means you can paralyze actions. You can see it in action.

Cool. Thank you. It really does makes sense in your use case. I guess my mind has been too much on state machines. 

>> Is this really the intention?

> Yes, indeed. It's a workflow net and not a state machine. That's why you need to declare more transition for what you try to do.

> BTW, I want to add a new property to a transition title to be able to share the same title (review in your case). Like that, the "long & accurate" name will be used internally, and a simple name could be exposed to the end user.

I think that is a good idea. Correct me if Im wrong but I would like to consider a state machine as a special case of a workflow. With a transaction title one could use the workflow as a state machine, it is just a matter of configuration, right?

Do you want me to make a PR for the transaction title?

**Comment by ogizanagi** [comment]
The "transition title" looks like an intention. What do you think about naming it `intent` instead of `title` ? 
Unless there is another appropriated naming convention for this in the Petri net standard definition.

**Comment by Nyholm** [comment]
I solved this issue by adding a new interface and a new marking class. See #19629
