### ISSUE TITLE
[Form] children builder should have data

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#19642]
example:

Controller:

    $form = $this->createForm(AtricleFormType::class, $article);

AtricleFormType:

    function buildForm($builder, $options) {

        // $builder->getData() = $article;

        $builde->add('tags', CollectionType, [
           'entry_type' => TagFormType::Class,
            ...
            without setting data ... 
            ...
        ]);
    }

TagFormType:

    function buildForm($builder, $options) {
        // $builder->getData() = null;
    }

as you can see in TagFormType there are null data
I think item of type CollectionType, should have data in builder

**Comment by HeahDude** [comment]
Hi @poolerMF, I don't think we should allow that, since it's not the builder responsibility to set data to children forms from the data passed as argument by some `create*Form` method.

DataMappers do that.

If you need to build forms dynamically depending on data values you should use listeners instead.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" per @HeahDude's comments. If anyone thinks this feature should be implemented, please comment and we'll reopen this issue. Thanks!
