### ISSUE TITLE
[Console] Add a RepeatedQuestion

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#19678]
Actually when I want to ask several times the same question with `SymfonyStyle` i have a very verbose output:

``` console
What do you want? [default]:
> foo

What do you want? [default]:
> bar

What do you want? [default]:
>

```

I propose to introduce a `RepeatedQuestion`. It could be implemented like that:

``` php
class RepeatedQuestion extends Question
{
    private $generator;

    public function __construct($question, \Generator $generator)
    {
        parent::__construct($question);
        $this->generator = $generator;
    }

    public function addAnswer($answer)
    {
         $this->generator->send($answer);
    }

    public function shouldContinue(): bool
    {
        return $this->generator->valid();
    }

    public function getDefault()
    {
        return $this->generator->current();
    }
}
```

It would be used like that:

``` php
$question = new RepeatedQuestion(call_user_func(function() use ($default) {
    do {
        $answer = yield $default;
    } while ($answer !== $default);
}));
foreach ($helper->askQuestion($question) as $answer) {
    // do what you want
}
```

And the command output would be:

``` console
What do you want?
[default] > foo
[default] > bar
[default] >
```

WDYT?

**Comment by iltar** [comment]
Looks like a valid case to me

**Comment by Ener-Getick** [comment]
BTW it could also be used for things like multiline answer. Maybe we should choose a name showing this use case as well ?

**Comment by jameshalsall** [comment]
This can easily be implemented in user land with `Question`

**Comment by Ener-Getick** [comment]
@jameshalsall how would you do that ? That's not that easy and would probably need some hacks.
Anyway even if that's doable in userland i don't understand why it wouldn't be supported by the core to make it easier to use.

**Comment by sstok** [comment]
Depending on there relationship this is not as easy as it seems, in https://github.com/rollerworks/SkeletonDancer I started with a collection of questions, but then I wanted to add support for conditional questions (only ask when x) and then it become complicated.

So Instead of adding all to a collection, each question is asked by a Questioner that keeps track of all questions, but instead of using the Symfony Console Question directly it uses a wrapper that creates the Question at a later state so that the default can be passed https://github.com/rollerworks/SkeletonDancer/blob/master/src/Question.php

**Comment by jameshalsall** [comment]
@Ener-Getick at a simple level off the top of my head...

```
$answers = [];
$question = new Question('What is foo?', 'bar');
do {
    $answers[] = $questionHelper->ask($input, $output, $question);
} while ($answer !== 'bar');
$output->writeln('You answered with ' , implode(', ', $answers);
```

**Comment by Ener-Getick** [comment]
@jameshalsall yes but as i said that's very verbose.

**Comment by jameshalsall** [comment]
it's no more verbose than your suggested implementation, imo

**Comment by Ener-Getick** [comment]
@jameshalsall the output in the console is verbose, not the call to `ask`  :P

**Comment by sstok** [comment]
@jameshalsall Good point, that's actually something I want to do in the long run :) but that will take some time.

**Comment by javiereguiluz** [comment]
I'm 👎 for this proposed feature:

1) Having a repeated question in a command is not that common (unlike forms, where you always have a repeated password field, for example).
2) The output is "verbose" ... because the command showed an example is verbose in the first place. You are asking 3 or 4 times the same thing, so it's a verbose command originally.
3) It can be solved with existing features. E.g. 

```
What do you want? (separate the values with a comma):
> foo, bar, baz
```

**Comment by Ener-Getick** [comment]
@javiereguiluz i want to use this in my [QuickInstallBundle](https://github.com/EXSyst/QuickInstallBundle) to reconfigure an app.
It is very common in `Configuration` to have array nodes and everytime to configure one of them it is verbose (see [this example](https://github.com/EXSyst/QuickInstallBundle/blob/master/Configurator/Bundle/DunglasActionConfigurator.php#L36-L50)). When you don't have a default and you use small values you can of course use `,` but you have to explain it.

BTW I think it would also be useful for multiline input (emails, comments, ...).

**Comment by javiereguiluz** [comment]
Closing it because the related issue (#19699) was closed as "won't fix".
