### ISSUE TITLE
Dumper does not output file/line

### ISSUE THREAD

**Issue by pies** [symfony/symfony#19706]
When I use dump() I'd like to be able to tell where was it called at. 

It's not difficult to add to output and I'd like to contribute it if approved by community.

**Comment by stof** [comment]
The issue is not to add it to the output, but to determine these file and line. The only way (AFAIK) is to use ``debug_backtrace`` and then to extract a meaningful location from it (which is not easy, as the meaningful layer is often not the first one, due to the ``dump()`` function wrapper or the Twig integration layer)

**Comment by wouterj** [comment]
Please note that this information is shown when dumping to the web dev toolbar.

**Comment by pies** [comment]
@stof That's correct, I intended to use `debug_backtrace()` for this task.
@wouterj I use dumper with Silex and without a debug bar.
