### ISSUE TITLE
cache:clear --env=prod problem

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony#19911]
Symfony 3.1

1. I have a console command defined as a service.
2. I decide to remove it
3. Remove the class file
4. Remove the defintion in services.yml
5. Run cache:clear --env=prod
6. Get `ClassNotFoundException` at `appProdProjectContainer.php`
7. `rm -rf var/cache/prod/` helps

Tested with other services types (not commands) - no exceptions.
`cache:clear --env=dev` also works good.
First got this error when updating the production server after `git pull`, then tested locally.

**Comment by mvrhov** [comment]
This is a known issue it has been debated here many times, but it's impossible to fix. The problem is that to run a cache clear command the app has to be run with currently built up container. However you just removed the class that was referenced in old container.
The best way to avoid this is to deploy the app into the new directory and just warm up a cache.

**Comment by vudaltsov** [comment]
@mvrhov , thank you for clarifications. I still have one question. How `cache:clear --env=dev` is different and why it works without exceptions?
