### ISSUE TITLE
[Console] SymfonyStyle line length limit cannot be customized

### ISSUE THREAD

**Issue by OndraM** [symfony/symfony#19918]
Hi,
I understand purpose of SymfonyStyle is mainly to unify output of Symfony commands. However, I use the output style also in my own commands, as I want them to have same feel as the builtin commands.

Considering that, it would be handy for me to have the possibility to adjust their output a bit, without the need of implementing my own OutputStyle from scratch (there is lot of already implemented logic in the SymfonyStyle I want to keep using - especially the `createBlock()` method). 

The main case - there is no way how to  change the 120 characters MAX_LINE_LENGTH limit (it is constant, the constructor use it as `self::` not `static::`, and the class property is private). 

So. what is your opinion on these possible solutions how to allow changing the max. line length limit?
- make the `lineLength` property protected ie. overridable in custom constructor
- use `static::` in the constructor, so it could be set just using constant
- make max length optional constructor param
- anything else?
- nothing

Thanks for your considerations!

**Comment by javiereguiluz** [comment]
I'd like to ask you some details about this. Which is the problem that introduces the `120` limit in your case?

The Symfony style behaves like this:

* Use the console window width as the max line length.
* If the window is wider than 120 chars, then use 120 (otherwise, the lines are ridiculously long)

So, do you want to use lines longer than 120?

**Comment by OndraM** [comment]
Yes, exactly. I put some verbose information in the output in some of my commands, and the 120 characters are quite limiting.

**Comment by fabpot** [comment]
As you said, the main goal of the default Symfony Styles is to unify the output. So, I'm against making them configurable, that would defeat the initial purpose.

**Comment by javiereguiluz** [comment]
@OndraM I'm afraid I need to close as "won't fix" because of the reasons given by Fabien. Besides, the 120 limit is a defining feature of the Symfony Style, so we "cannot" modify it.

In any case, your "verbose information" will be output in several 120-chars lines, so the user still can read it comfortably.
