### ISSUE TITLE
Extending bundles from the outside in Symfony / Doctrine 2?

### ISSUE THREAD

**Issue by betaglop** [symfony/symfony#19999]
As far as I know, if you want to extend a bundle from another bundle, without creating a dependency between them or using any OO concept of inheritance, it is not yet possible w/ Symfony & Doctrine2. This confirmed my first idea :

"Due to the way Doctrine works, it is not possible to override entity mapping of a bundle." (source: http://symfony.com/doc/current/bundles/override.html#entities-entity-mapping)

The only existing way did not give me satisfaction : using SuperMappedClasses...
What I want is, for instance:
- having Contacts in a standalone bundle in one hand (CRMBundle)
- having EmailMessages in an other standalone bundle in the other (EmailBundle)
- adding "magically" the Contact::$emailMessages property + getter/setter + twig template in the ShowMapper (if I'm using Sonata, which is not mandatory) + fields in the DatagridMapper/FormMapper... when the EmailBundle is present in the App at the same time than the Contact/CRMBundle.
- the same thing on the reverse side (Email)

For the moment, as the official Symfony doc says, it does not seem possible. Anyone can confirm the "state of the art" on this point ? BTW, we are working on this here, and I think we are about to touch something new and interesting for everyone on that point... but I don't want us to work on this issue without the necessity for (Are there some interested people here?).

Thanks in advance,

**Comment by sstok** [comment]
Doctrine provides something that allows for a base bundle, called a MappedSuperClass.
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html

But there are some known limitations (see the docs).

When it comes to functional bundles (not integration bundles like TwigBundle, SecurityBundle, etc), I don't tent to think of how they relate but how they are packaged (Composer package). 
For example I have a Invoice package that provides three bundles (Infrastructure, Web, and Api), Web and Api depend on Infrastructure, but the "package" doesn't depend on other functional packages (like Customer).

Instead of coupling these packages together the Invoice package provides an gateway interface and a local Model of a "debtor". Then to allow to link an Invoice to a Customer there is a bridge package `customer-to-invoice` that provides an implementation of the DeptorGateway that fetches a Customer and converts it to a Deptor Model for the Invoice.

The Customer can easily change without affecting the Invoice package, the Invoice package can communicate with the customer-to-invoice bridge package or a third-party API (like an external CRM). No coupling, easy to change/replace, and no epic object graphs.

For this to work properly it's important both Debtor and Customer are identified with the same unique id (UUID). Using a UUID ensures you always get the correct model instance instead, no mater which system you are using.

This technique is known as Domain Driven Design, which is a really big topic (to big to explain here). And are highly recommended for big systems (not a CMS) where you must prevent coupling between components (Bounded contexts).

There are couple (no pun) of books I can highly recommend:

https://leanpub.com/ddd-in-php
https://leanpub.com/principles-of-package-design
https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215 
https://amzn.com/0321834577 - Implementing Domain-Driven Design 1st Edition (Domain design patterns)
https://amzn.com/0132350882 - Clean Code

**Comment by betaglop** [comment]
I'm not sure to understand correctly the Domain Driven Design, but I've got the idea. I think "Domain" Driven cannot fit our needs as we are looking for a way to design our components as that they can adapt to various domains. We'd like to abstract Domains instead of being shaped by them.

You are creating a bridge that "shapes" the external entity (Customer) in a way that it fits the internal entity (Debtor) requirements. That's not what we are looking for. What we need is a way to extend Debtor features from outside so that it can be compatible with the Customer entity needs.

I think we have something, creating the links between functional bundles within the AppBundle (so "on demand") and extending the foreign entities in the exact way needed by the extra-bundle. Would it be interesting for the community to publish them?

**Comment by jakzal** [comment]
It doesn't look like the problem you have is Symfony related but it's purely about Doctrine. Which by the way, already provides a way to dynamically change the mapping with [the ClassMetadata event](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#load-classmetadata-event).

**Comment by betaglop** [comment]
Yes, Doctrine has what's needed with the ClassMetaData event... but we cannot, AFAIK, add properties, for instance, to an Entity from the outside... and this is THE limitation that we want to overcome.

For instance, a Stock has to be extended in its properties to be able to be used by different kind of stuff (liquids/gaz, material products, event tickets, etc.). And at that point, Doctrine needs an access to the Entity properties with the \ReflexionProperty tool, which requires real properties... and this cannot be provided by the ClassMetaData event... and it is not "nice" to prepare generic properties (with a limitated number of properties, of course) which aim to be reused by external bundles and their ClassMetaData event...

By the way, I understand that we need to be able to point very precisely the subject of our investigation in the future.

**Comment by jakzal** [comment]
> but we cannot, AFAIK, add properties, for instance, to an Entity from the outside

I don't see how would this work without extending the original class, or generating it perhaps. Either way this is not a problem Symfony will solve for you.

**Comment by betaglop** [comment]
So we have to create something new if we want to design fully-standalone and fully-really-extendable symfony bundles... Do you think it would be interesting for the community if we make it generic, formalized and reusable ?... Because as far as I can understand, this is an issue never answered in the way we need.

Thx in advance for your attention,

**Comment by jakzal** [comment]
As mentioned earlier, problems you're trying to solve are doctrine related. In my opinion there's nothing we should do in Symfony. I might be wrong though, so if you have any concrete suggestions of what we could add to Symfony to make your life easier, we will consider them. Otherwise I think we can close this issue.

**Comment by betaglop** [comment]
Let's wait a week (until sept. 30th), if you agree... I'll ring a bell on the Doctrine project too, and we'll work on our idea, formalizing it before any publication.
Or you can close it and we will reopen it waiting for our solution.

**Comment by Padam87** [comment]
I usually "solve" these kinds of problems with traits, embeddables and interfaces. The reusable bundle has all the services and utility classes, but I define my entities on a per application basis, using the traits etc provided by the bundle... 90% works out of the box, just have to wire it up.

I would rather have it this way than having to deal with an over-configured mess.

**Comment by betaglop** [comment]
Yeah Padam87... Our progression in this direction is about to be confirmed. I am about to be able to write the specification of a new "design pattern" in this direction... with concrete examples with Doctrine & Symfony. It gonna be so easy to use, implement and reuse!

The proof of concept in 90% done, and the rest is just formality.
Then I'll have to write things down on the paper to be able to publish something.
Maybe it will be something awesome... except if I'm totally out of the path, and this 100% reusable/extendable approach is much more common that I feel/know...

**Comment by Richtermeister** [comment]
I'm late to this party, but take a look at https://github.com/Sylius/Sylius and how they are extending bundle entities in higher-level bundles. Your case of adding properties to bundle entities is addressed there and overall things work very well in their approach. However, your base bundles need to be written with this in mind and only instantiate new entities via factories, so your top-level app can configure which actual entity class will be used.

**Comment by javiereguiluz** [comment]
Closing this because of the explanations made by @jakzal and the solution recommended by @Richtermeister. Thanks!
