### ISSUE TITLE
Collection validation does not stop after first violation

### ISSUE THREAD

**Issue by pfcloutier-druide** [symfony/symfony#20017]
PHP 7
Using Symfony\Component\Validator\Constraints\Collection;

I'm using Symfony 3.1 and I hope I'm not doing something wrong. When I validate a field, it doesn't stop after the first violation. Example : 

```
$errors = $val->validate(
    $info,
    new \Symfony\Component\Validator\Constraints\Collection([
        'fields' => array(
            'specialKey' => array(
                new NotBlank(),
                new Length(['min' => 8,'max' => 20]),
                new Regex(['value' => "/^[A-Za-z]*$/"]),
            )
        ),
        'allowExtraFields' => true,
    ])
);
```

I'm getting : 

```
'This value is too short. It should have 8 characters or more.'
'This value is not valid.'
```

I found a walk-around for those who are interested : 

```
$errors = $val->validate(
    $info,
    new \Symfony\Component\Validator\Constraints\Collection([
        'fields' => array(
            'specialKey' => array(
                new NotBlank(['groups' => 'groupe1']),
                new Length(['min' => 8,'max' => 20,'groups' => 'groupe2']),
                new Regex(['value' => "/^[A-Za-z]*$/",'groups' => 'groupe3']),
            )
        ),
        'allowExtraFields' => true,
    ]),
    new GroupSequence(array('Default','groupe1','groupe2','groupe3'))
);
```

**Comment by Jean85** [comment]
Why it should stop? If there are multiple errors, the users should be made aware of all of them! Otherwise it could get frustrating for him, getting a different error for 2-3 submission in a row

**Comment by iltar** [comment]
If you want to show a different message for an empty field than an invalid field, you now get both. It would be a nice feature to be able to stop validation propagation

**Comment by Jean85** [comment]
@iltar, I think that that kind of use case is normally already covered by the use of `'required' => true`..

**Comment by iltar** [comment]
@Jean85 that's just an option passed to your form-type, not validation related.

**Comment by Jean85** [comment]
@iltar I know, but since the issue that you raised is UI related, that is helpful, since it stops the user even before submitting the form, requiring the field to be filled.

**Comment by ro0NL** [comment]
Im not sure we need a "break chain on failure" feature, however if we can group multiple constraints bound to a single message that would be convenient.. im not sure this is easily possible now?

**Comment by pfcloutier** [comment]
@Jean85 You have a solid point here! I got the case where both constraints have the same message with all the needed information like : "The password must be between 8 and 20 characters and a combination of letters and numbers.” I don't want to send repetitive information like :
"The password must be between 8 and 20 characters."
"The password must be between a combination of letters and numbers."

**Comment by Jean85** [comment]
The best way to address this IMHO would be a way to create a custom
validator which is a compound of basic validators...maybe this is the best
way to go.

Something like the All constraint:
https://symfony.com/doc/current/reference/constraints/All.html but applied
to a single field. Or does it already work in this way?

Il gio 22 set 2016, 21:31 pfcloutier <notifications@github.com> ha scritto:

**Comment by pfcloutier** [comment]
The All constraint is also not stopping after the first violation. Maybe like you said the best way for now is to create a custom constraint with all the needed validations.

**Comment by xabbuh** [comment]
This doesn't look like a bug to me, but as the way it was intended to work. Furthermore, we can not really change the current behaviour as that would break code relying on the current behaviour which to seems totally valid.

Since there are already ways to implement the desired behaviour with custom code I suggest to close here.

@symfony/deciders What do you think?

**Comment by javiereguiluz** [comment]
@xabbuh I agree with you.

@pfcloutier if you only want to display one error per field, instead of creating a custom constraint, you may create a very simple form theme extending from the Symfony's theme and then override the form_error to display just the first message.

**Comment by pfcloutier** [comment]
@xabbuh : I don't want to change the current behaviour, but it could be a nice feature to add a property 'stopOnFailure' in the collection validator. 

I don't think it should be marked as a bug.

**Comment by xabbuh** [comment]
@pfcloutier I tagged this as a feature request.

**Comment by jaikdean** [comment]
+1 for a "stopOnFailure" type option.

Our use case is using validators to check the format of user input from a JSON request body. Say we've decoded the JSON and want a PIN field to be a string of 4 numeric digits (not an integer in case it starts with a 0):

```php
$constraints = [
    new Type('string'),
    new Regex('^\d{4}$'),
];

$validator->validate($pin, $constraints);
```

This all appears to work correctly, until the user starts messing around and sends an array for the value of this field. In this case, the `Type` constraint causes a violation as expected, but the `Regex` constraint throws an uncaught `UnexpectedTypeException`.

We're currently calling `validate()` for each constraint individually and stopping when we get a violation, to work around this.

**Comment by Jean85** [comment]
@jaikdean you should write a custom validator for your case.

**Comment by jkobus** [comment]
I agree with @jaikdean.
If I want to check a property for non-empty string and then second validator checks it in the database, the query will be executed anyway, even if the first validator will fail, and that's not cool.

**Comment by xabbuh** [comment]
> If I want to check a property for non-empty string and then second validator checks it in the database, the query will be executed anyway, even if the first validator will fail, and that's not cool.

For that use case there is the concept of [group sequence providers](http://symfony.com/doc/current/validation/sequence_provider.html) where subsequent validation groups are only checked if the previous ones did not error.

**Comment by ogizanagi** [comment]
I agree with @xabbuh here, and group sequences already are a solution to this.
But, throwing a raw idea: could a `Sequence` constraint be helpful? It'll be a composite constraint and accept a collection of constraints as argument (like the `@All` constraint for instance), and proceed to the next constraint validation only if there is no violation yet. Looks like it could help solving some simple cases straightforwardly to me (but not as powerful as group sequences).

**Comment by iltar** [comment]
I'm looking for pretty much what you describe @ogizanagi so yes, that sounds like a good idea to me.

**Comment by BonBonSlick** [comment]
in my case, i want to display  all error, but current default behavior stops validation on first violation...

**Comment by mcatirau-avantajprim** [comment]
As @jkobus pointed, this can make a security issue if second validator make a request in database

**Comment by rijnhard** [comment]
From my perspective this is a UX issue.
Context:
We have a custom validator that can only operate on an array,
So we use `@Assert\Type(type=array,message='...')` to control the UX of the error,
then we have our custom constraint `@Assert\Custom(...)` that follows the [Symfony guidelines](https://symfony.com/doc/current/validation/custom_constraint.html#creating-the-validator-itself) and throws an `UnexpectedValueException` just in case someone forgot to use the `@Assert\Type` constraint. 

Now we have two errors for it not being an array, one of which is our error message, the second of which is the default error message which we can simply not change, and that breaks our UX. 

Can you see the problem?

**Comment by rjcnitsche** [comment]
How to Sequentially Apply Validation Groups

https://symfony.com/doc/3.4/validation/sequence_provider.html

works for me.

**Comment by fbastien** [comment]
I see many people around suggesting like @xabbuh and @ogizanagi using group sequences, but this may not always be a good workaround as a violation in one group would skip validation of constraints in subsequent groups on _all other fields_ as well, even if those fields comply with first groups constraints but violate some constraints in subsequent groups.

Although I understand @Jean85's POV and the need to show all **independent** constraint violations at once (like password length and charset), some constraints may still be dependent on previous ones being valid.

I think that's especially true about data type constraints, as @jaikdean and @rijnhard pointed out, since trying to validate constraints on a value of the wrong type makes no sense to me (e.g. why raising an error about a date field not being in an expected period of time if the input is not a date in the first place?), and this may even lead to raising exceptions/errors if subsequent validation rely on code that assumes that values have the expected type.
I'm facing a similar issue validating a field which is expected to be a float value (so having a `Type` constraint on it) and also having `Expression` constraints using some arithmetics with the value. If the input is not numeric, then the evaluation of these expressions raises an `ErrorException` up to the `validate()` method invocation thus the constraint violation list of the whole entity is lost and subsequent fields aren't validated either! If I want to avoid it, I can still duplicate type checking in every subsequent constraint (using ternary operator around `value` occurrences in my case) but this is dirty IMO, this clutters the code and makes less clear what the actual constraint is.

As an API user, I think we should have an easy way to set a `Type` constraint and use it as a safe guard before further validation, without having to write a custom validator or such.
Moreover, I feel this is inconsistent with how validators deal with `null` values. As @webmozart said in  [#10221 comment](https://github.com/symfony/symfony/issues/10221#issuecomment-34769066):

> The reason why most of the validators silently allow `null` values is that (a) whether a value is set or not and (b) which constraints this value has to satisfy, _if_ it is set, are usually orthogonal concepts.

Then why not silently allowing incoherent data types as well? I feel like (a) whether a value's type is coherent/safe and (b) which constraints this value has to satisfy, _if_ it is coherent/safe type-wise, are also orthogonal concepts. And this may be why some (many?) of us don't expect Symfony to raise further violations when type constraint is violated.

+1 for a `@Sequence` compound constraint (although it may make constraint inference more difficult for other annotation-scanning components?)
+1 as well for a "stopOnFailure" (or "orSkipNext") option, at least on `Type` constraint but maybe even a base inherited option, defaulted to no-skip to preserve BC. Something like:
```php
/**
 * @Assert\Type("float", orSkipNext=true)
 * @Assert\Expression(...)
 */
```
(Apologies for being beyond OP scope about Collection validation of independent constraints, I didn't want to create a new issue...)

**Comment by ogizanagi** [comment]
I opened https://github.com/symfony/symfony/pull/34456 about the sequence constraint
