### ISSUE TITLE
[RFC] Making services private by default in Symfony 4?

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#20048]
Just wondering, how about making services private by default in Symfony 4?
That would give us more private services optimizations by default, thus lighter containers.
The path could be as "simple" as deprecating the "public" attribute and replacing it by a "private" one.
Worth pursuing?

**Comment by Ener-Getick** [comment]
:+1: but for that imo we have to allow using private services with any tag (event listeners, etc.; eg. the tag manager can make the service public or create an alias).

**Comment by iltar** [comment]
I'd be very happy to see this, but it would be a big issue for people extending the Controller. Imo Controller as a Service is the way to go but not everyone agrees with me.

**Comment by Ener-Getick** [comment]
@iltar imo symfony should create its own public aliases when it needs to, instead of forcing the user to make his services public... but i'm not sure everyone agrees.

**Comment by iltar** [comment]
@Ener-Getick the problem is that Symfony can't guess the service you're going to need if you use a Service Locator.

**Comment by Ener-Getick** [comment]
An alternative would be to encourage using [DunglasActionBundle](https://github.com/dunglas/DunglasActionBundle) but again not everyone agrees...
A limitation of the problem would be to allow making public an entire set of services (during their import or as a header of the file).

**Comment by iltar** [comment]
You'd have to do static code analysis of the file and try to determine all locator calls. This works up to a point where calls become dynamic.

**Comment by Ener-Getick** [comment]
@iltar i meant as a header of the config files 😉

**Comment by iltar** [comment]
Ah, well then I would rather recommend making everything private by default and recommending controller as a service instead.

**Comment by hhamon** [comment]
I would vote for but that's a major BC break and it will probably prevent people from upgrading to Symfony 4. I don't know if we can make this behavior globally configurable (enable or disable).

**Comment by Ener-Getick** [comment]
@hhamon that's why we use bc layers and deprecations. For apps respecting best practices, it shouldn't be that hard to upgrade.

But i'm wondering if it wouldn't make services even harder to understand for newcomers. I'm :+1: for making this globally configurable and l would make services public by default in the standard edition and private by default to ensure bundles tests are always against the worst scenario.

**Comment by hhamon** [comment]
Yes it will be harder for newcomers to understand this concept. When I do training sessions, including advanced ones, it's often rare that people know the differences between private and public services. And the consequences private service definitions have on the container compilation. So IMO, we have to be careful with this. If we decide to switch to private services by default, it has to be very very well documented. But again, I would prefer having a global configuration setting to enable or disable this behavior.

**Comment by Ener-Getick** [comment]
@hhamon for me, we should promote autowiring for newcomers (or at worst methods hiding the calls to the container such as the base `Controller`). It is more magic but it reduces the learning path and would allow us more easily to do this change.

**Comment by nicolas-grekas** [comment]
It can't be a global flag: definitions can't rely on some outside context! But it could be changed locally for a whole file for sure. Having everything private by default would prevent using the dic as a service locator, which is too easy for newcomers today. They'd better learn very soon that if they do this, they must optin to the not-the-best practice.

**Comment by nicolas-grekas** [comment]
Oh btw, we already planned to prevent fetching private services from the container in 4.0, so we already have the right explanation point for newcomers: the exception message they'll get then.

**Comment by Ener-Getick** [comment]
@nicolas-grekas even with bad practices, the framework is hard to understand at first. The exception thrown when using private services at runtime will of course be useful but only if the user understands services.
The best would be to take a look at other frameworks and see how they make it easy for newcomers to get how they work.

**Comment by theofidry** [comment]
What about libraries? If an application the issue is scoped to service locators, in libraries it's much more complex: you definitely don't want a service as private by default.

What about a switch to trigger private by default instead (that would apply to application local services as well as an library services)? If the goal is performance here, I don't think it's right to break the BC promise for it, but we should still able to make it possible for people looking for it.

**Comment by iltar** [comment]
@theofidry Usually when 3rd party bundles need services, they are being configured via the configuration/extension/compiler pass (in this sequence). At the last 2 points, you can fetch the service and make it public if needed, works well in combination with tagged services.

**Comment by theofidry** [comment]
@iltar as actually private services are accessible as before even if they come from a third-party bundle it's not a problem, sorry for the confusion. The only place (to my understanding) where it would be a problem are service locators, but it's a concern you already shared.

**Comment by sh4ka** [comment]
Would love to see this feature.

**Comment by xabbuh** [comment]
Well, if we made that steps, we would have to treat controllers that use the DI container as a service locator a bad practice. So effectively you will have to register your controllers as services (or you have to turn services into public ones again). Is that something we can agree on (in the docs we recently made the shift the other way around, i.e. not propagating controllers as services)?

**Comment by sh4ka** [comment]
I guess private services by default do not enforce that behavior, and mark public services as such.

**Comment by iltar** [comment]
@xabbuh currently it's recommend to extend the `Controller` and use `$this->render()` for example. As a BC layer for this,  https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php#L61-L67 should also call the setContainer. This means the Controller as a Service can still work for the default methods. Just have to throw a bunch of errors/warnings.

Additionally for 4.0, a bunch of controller helpers (or make the Controller a ControllerHelper with public methods instead) should be created to "ease" Controller as a Service for people. With Autowiring in place, this could still be relatively easy for people to start with.

**Comment by fabpot** [comment]
@xabbuh I'm still a firm believer that controller as a service is not at all something people should do by default. Too much added complexity for little gain. We need to support the controller as a service pattern for people who like this approach and to make controllers independent of the full-stack framework (to be able to share them with other libs/frameworks built on top of the Symfony components).

**Comment by theofidry** [comment]
@nicolas-grekas could this be configured via a parameter?

**Comment by dunglas** [comment]
👍 to make services private by default.

@fabpot We can also import ActionBundle in core (or in the standard edition symfony/symfony-standard#960). It's about 200 LOC and it allows to create and use controllers as a service as easily as the standard Symfony controller while promoting better practices regarding dependency injection: https://github.com/dunglas/DunglasActionBundle#usage

IMO it's even more easy for newcomers than the current controller system because it doesn't require to register services using an XML or YAML.

I added this bundle in the standard edition of API Platform 2 (https://github.com/api-platform/docs/blob/master/core/operations.md#creating-custom-operations-and-controllers), and I got only positive feedback from users for now.

**Comment by iltar** [comment]
While I find the configuration for the ActionBundle a bit confusing, I really like the concept of the bundle. Maybe it cold indeed be integrated into Symfony?

**Comment by dunglas** [comment]
@iltar can you open an issue about the config? What looks confusing to you? It can probably be improved.

**Comment by sstok** [comment]
> The best would be to take a look at other frameworks and see how they make it easy for newcomers to get how they work.

Silex (Pimple) used to mark services as private by default, but changed this for performance reasons.

Marking services as private by default seems like a good idea, when you mark them as public it's not a bad-practice perse, it simply means you want to make them accessible elsewhere (private/internal vs public API). But most services should not be accessible by default (like 'form.registry').

Sorry for the off topic, but is it better to mark a service as lazy rather then marking them as public and use the Container for loading them??

**Comment by stof** [comment]
> Silex (Pimple) used to mark services as private by default, but changed this for performance reasons.

It never did this. Pimple does not even have a concept of private services (as it does not have a compilation step to apply optimizations).
You are confusing things with the switched from non-shared to shared by default.

The performance reasons made Pimple change the way shared services are stored internally. And this change made it possible to share by default (the old way required sharing to be done on top of non-shared services, and so could not be the default). The change of default behavior was done because 99% of services are actually shared (and Symfony DI always made them shared by default)
