### ISSUE TITLE
Twig extension is not enabled - twig 1.26.0

### ISSUE THREAD

**Issue by caciobanu** [symfony/symfony#20136]
After updating to twig 1.26.0, extensions registered as laxy services in the container and that implement the method getName() and return a random string will not work.

For the extension below when the function **test_test** is used in a twig template it will say that the extension is not enabled:

```php
class TestExtension  extends \Twig_Extension
{
    public function getFunctions()
    {
        return [
            new \Twig_SimpleFunction(
                'test_test',
                [$this, 'testTest']
            ),
        ];
    }

    public function testTest()
    {
    }

    public function getName()
    {
        return 'test_extension';
    }
}
```

```xml
<service id="test.twig.extension" class="AppBundle\Twig\TestExtension" lazy="true">
     <tag name="twig.extension"/>
</service>
```

PS: In order for this case to be reproduced the **ocramius/proxy-manager** package is needed.

**Comment by stof** [comment]
hmm, the usage of the class name as identifier might indeed cause issues for lazy services, as they are wrapped in a proxy.

However, there is 0 benefit at making an extension lazy, and there is a perf drawback (due to the proxy forwarding overhead), as they way Twig uses the extension would force the proxy to be initialized as soon as they extension is registered in Twig.

**Comment by waplet** [comment]
Agree , whether:
1. update composer.json
2. release tag with latest master version.

**Comment by fabpot** [comment]
Closing, everything will be "fixes" with new Symfony releases.
