### ISSUE TITLE
Console BC break 2.8.12?

### ISSUE THREAD

**Issue by dominikzogg** [symfony/symfony#20194]
Within Symfony 2.8.11 a space between option and its value wasn't a problem.
```{.sh}
$ ./app/console --version
Symfony version 2.8.11 - app/dev/debug

$ app/console my:command:name --option= 8
```

Within Symfony 2.8.12 a space between option and is a problem.

```{.sh}
$ ./app/console --version
Symfony version 2.8.12 - app/dev/debug

$ app/console my:command:name --option= 8

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command".
```

**Comment by xabbuh** [comment]
The fact that this worked before does not look right to me, but this shouldbe considered as a bug that now has been fixed.

**Comment by dominikzogg** [comment]
@xabbuh you've right, but "fixing" bugs that aren't security relevant which worked since long time (never saw this break in past) isn't very gently to the users. There was not need to "fix" this.

**Comment by xabbuh** [comment]
Well, if we went this way, we would never be able to fix any bugs as there will always be some users who relied on the wrong behaviour. By the way, the PR that changed this behaviour is #19946.

**Comment by dominikzogg** [comment]
@xabbuh in this case a single (unwished) whitespace (in a shell variable) worked until the last update.
I understand that you doesn't care cause it was not documented, but for me this means its dangerous to install bugfix releases.

**Comment by javiereguiluz** [comment]
@dominikzogg I can understand how you feel about breaking the app just by upgrading to a bugfix release. But please, take into account that this was a Symfony bug and that's why we needed to fix it. It's true that it worked before ... but just by pure luck, because this was always "borken".

Regarding the bugfix releases, please don't be afraid to upgrade in the future. Thanks to our [Backwards Compatibility Promise](http://symfony.com/doc/current/contributing/code/bc.html) you can be sure that we won't change Symfony's features behavior or add new features in these minor releases.

Considering all this, I'm closing this issue as "won't fix" then. Thank you.
