### ISSUE TITLE
adding getFlashBag to SessionInterface in later 3.1.x, or 3.2.x ?

### ISSUE THREAD

**Issue by pculka** [symfony/symfony#20258]
This has been well discussed already in many threads, did something change in the opinions since 3.0 deprecated/changed some BC stuff? Oradding this to the SessionInterface will be planned due in 4.0? It's just only a tiny bit annoying.

**Comment by stof** [comment]
adding a method in an interface cannot be done in any minor release

**Comment by xabbuh** [comment]
Even adding a new method to an existing interface in the next major version will probably not happen as there is no clean upgrade path that we can provide. The only viable upgrade path would be the introduction of a new interface, and optionally deprecating the existing one.

**Comment by stof** [comment]
@xabbuh there is a way to handle it without using a new interface name in the future in case the existing name is the best one, but it involves 2 generations of deprecation. There is such an example in Twig for the Twig_LoaderInterface:

- 1.11 introduced a ``Twig_ExistsLoaderInterface`` with a new ``exists`` method, and triggered deprecation warning when using a Twig_LoaderInterface which does not implement the new interface as well (actually, deprecations were added in 1.12 only, but this is irrelevant for this story)
- 2.0 adds the method in Twig_LoaderInterface itself (fine as Twig already warned you if you don't have it in your implementation, if you used it) and turns ``Twig_ExistsLoaderInterface`` into an empty interface (kept for BC to let loaders support both 1.x and 2.x by implementing it). 2.0 now has the future-proof API of the loader
- 2.1 deprecated ``Twig_ExistsLoaderInterface`` as it is useless now (if you want to support 2.1 without deprecation, you have to drop support for running on 1.x without deprecation, but this is considered fine, as people had time to migrate)
- 3.0 drops the empty deprecated ``Twig_ExistsLoaderInterface``

And this is easier than replacing the interface by a whole new one, because consumers of the interface don't have to change their typehint to support new names (which is hard, as you can either have code with the new typehint supporting both interface, or code with any interface passing old typehints, but not both). Renaming interfaces is a pain

**Comment by iltar** [comment]
Whenever I need the flash bag, I simply inject it: `@session.flash_bag`. However, it's only used for messages and stuff so I wrote an application specific wrapper around it so that I won't have to inject it all the time and I just do something like:

```php
$this->message_store->addSuccess('username.changed');
$this->message_store->addSuccess(new TranslatableMessage(
    'form.email.change_password_success',
    ['%mailbox%' => $this->email->getAddress()]
));
// also got addWarning and addError, but as I mentioned, it's for my application specific.
```

**Comment by pculka** [comment]
well sure, one can always use a wrapper, but I really do believe a solid framework like Symfony should have the interfaces set properly.
I mean ... it works like it is atm anyway, it's just that hinting in IDE which resolves the services tells me that "the method getFlashBag is not found in Interface". Really not a big deal, it just can be a bit annoying , when you try to code with nice green checks.

**Comment by iltar** [comment]
As you've already mentioned, it's been discussed a number of times already and it all came to the conclusion that `getFlashBag` doesn't belong to the `SessionInterface`. Just inject the the `session.flash_bag` service and you got your flash bag

**Comment by stof** [comment]
@iltar except that inject the service directly can do weird things, because if you don't initialize the session before working with this bag, it will not be initialized. The ``session.flash_bag`` is not meant to be accessed directly currently. It is there as a way to configure the dependency of the Session object.

**Comment by iltar** [comment]
@stof I once recommended to make the FlashBag use the container factory functionality: https://github.com/symfony/symfony/pull/11957/files

I could always re-make this PR for 3.2. In our codebase (all applications), I currently find this variable to be injected 54 times. I took out about 20 when I refactored to the example I gave in one of our applications.

**Comment by fabpot** [comment]
Closing as it's not going to happen as discussed already.
