### ISSUE TITLE
Deprecate DbalSessionHandler?

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#20501]
As per the discussion in symfony/symfony#20288, I'd like to deprecate DbalSessionHandler for the following reasons:

* Why not just use `PdoSessionHandler` instead as `DbalSessionHandler` is "slower";
* As everything is abstracted, `DbalSessionHandler` is not more "convenient" than `PdoSessionHandler`;
* `DbalSessionHandler` is more "complex" to configure than `PdoSessionHandler` as you should ensure that it uses a different connection than the one used by the ORM;
* `DbalSessionHandler` is not really configurable easily in terms of column names (not that this is really something anyone should do) as there is a schema that helps creating the table (which is by the way the only "advantage" of this handler).

WDYT?

**Comment by fabpot** [comment]
I think that the most important reason for deprecating it is the fact that most developers won't use a different connection between the session handler and the ORM.

**Comment by stof** [comment]
If we want to deprecate it, while keeping the schema useful (for people using the same DB for the session even though it is a separate connection), we should make the schema support the field customization supported by the PDO handler, so that we can keep hooking the schema in DBAL when using DBAL migrations (so that generated migrations don't try to delete the session table)

And there is another advantage of using DBAL: it supports being configured with a DB URL, which is the way credentials are given on most PaaS. Parsing the URL early to generate a DSN is not easy if we want to keep reading the env var at runtime (and DB credentials are precisely a case where you want that, to be compatible with the PaaS switching your DB to a failover). So I suggest adding support for configuring the PDO handler through a URL *before* deprecating the DBAL handler.
