### ISSUE TITLE
[Symfony 2.8] Form data transformers always occurred before validators

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony#20526]
why cannot customize about this.

**Comment by xabbuh** [comment]
What is your use case for validating anything else than your model data?

**Comment by zacharyzh** [comment]
I want to validate all 'categories' before transform them to 'Category' objects (Product entity has a property named 'categories').

    $builder->add('categories', CollectionType::class, array(
        'allow_add' => true,
        'entry_type' => TextType::class,
        'constraints' => array(
            ...
            new CategoriesConstraints(),
        ),
    ));

    $builder->get('categories')->addModelTransformer(new ProductCategoriesTransformer());

**Comment by xabbuh** [comment]
That does not answer my question. Why do you need to do that before the data is transformed?

**Comment by HeahDude** [comment]
You should use your `Category` model to validate the values by cascade when validating the owner.

**Comment by HeahDude** [comment]
This works:
```php
class Product
{
    // ...
    /**
     * @Assert\Valid
    private $categories;
// ...
```

**Comment by zacharyzh** [comment]
@HeahDude 

But I don't know how many category ids was entered (5 ids were entered and only 1 was valid).

**Comment by zacharyzh** [comment]
@xabbuh 

I want to know how many ids were entered and how many of them were invalid.

**Comment by HeahDude** [comment]
You can already put that kind of logic in a `POST_SUBMIT` event. You can then loop through forms and use `$form->addError(new FormError(...))` on the field you want to map the error to.

**Comment by HeahDude** [comment]
If you want to it before the transformation use `SUBMIT` event.

**Comment by zacharyzh** [comment]
I just found this on stack overflow. it's resolved my problem. but I still think it's better to be done by validators.

http://stackoverflow.com/questions/19754436/how-to-customize-datatransformer-error-message-in-symfony

**Comment by zacharyzh** [comment]
@HeahDude 

thanks :)
But form event is hard to maintains.

**Comment by zacharyzh** [comment]
Form field will be set to empty if transformer fails. It's not the best way to resolve problem. 

I think that validators should always access very original data user entered. They can transforms data by using transformers if they want to.

**Comment by HeahDude** [comment]
If the view transformer fails the value is not safe to be mapped, this is a no go IMHO.

**Comment by zacharyzh** [comment]
@HeahDude 

To be empty is logical if transformer fails.

But validators must always access **very original data** if you want to know the data user entered is valid or not (transformers makes that invisible).

**Comment by HeahDude** [comment]
>But validators must always access very original data if you want to know the data user entered is valid or not

The validation is processed on the model holding a new set of data, only if one was submitted. What the point of having the old issue (since it should already be valid before).

The transformer is just about changing the representation of the value, not validating its model. I don't get your point. Could you please describe a little more your use case?

**Comment by zacharyzh** [comment]
😢

It's so hard to describe with my poor English. I will introduce my code later.

**Comment by zacharyzh** [comment]
@HeahDude 

> The validation is processed on the model holding a new set of data, only if one was submitted. What the point of having the old data (since it should already be valid before).

Did you mean the model validation will be done before data transformation?

PS:
I never used the php comments as the "annotation". That's could be lost after the code compression.

**Comment by HeahDude** [comment]
@zacharyzh In fact, the validation format (e.g annotations, xml...) does not change what's happening in the form validation process.

You attached a model transformer and the constraint on the collection field. 

But when the collection is submitted:

 1. it is first transformed from view data to norm data (both arrays in this case)
 2. it submits all of its children, each of them are then transformed twice (view and model)
 3. children are mapped back as an array to the collection
 4. the collection is transformed using your model transformer.
 5. the collection will be validated (surely after the product which is the root) using your constraint.

Your code fails at step 4, so data does not reach the validation step 5.

>thanks :)
>But form event is hard to maintains.

Maybe you could try to rely on a unique listener instead of using a `CategoriesConstraints`and a  `ProductCategoriesTransformer`, so one file to maintain instead of two ;).

It could hold all the logic (I only presume based on your example):

```php
class ProductCategoriesFormListener implements EventSubscriberInterface
{
    private $categoryRepository;

    public function __construct(...) // inject you stuff and make it a service
    // ...

    public function onPostSubmit(FormEvent $event)
    {
        // the form is the collection so its parent is the product
        $product = $event->getForm()->getParent()->getData();
        $ids = $event->getData(); // an array of Ids

        $categories = array()
        foreach ($categories as $key => $id) {
            if ($category = $this-> categoryRepository->find($id)) {
                $categories[] = $category;
            } else {
                // Map an error to the field you want:
                $form->get($key)->addError(new FormError('this field as a wrong id');
                // or 
                $form->addError(new FormError('this collection as a wrong category '.$id);
            }
        }

        if ($form->isValid()) {
            $product->setCategories($categories);
        }
    }
    // implements the interface to subscribe to FormEvents::POST_SUBMIT
    // ...

class ProductType extends AbstractType
{
    private $categoriesListener;

    public function __construct(ProductCategoriesFormListener $listener) // inject it as well
    // ...

    public function buildForm(...)
    {
        $builder
            // ...
            ->add(
                $builder->create('categories', CollectionType::class, array(
                    'allow_add' => true,
                    'entry_type' => TextType::class,
                    'constraints' => array(
                        // other constraints will be applied on transformed Category objects
                    ),
                ))->addEventListener($this->categoriesListener)
        )
        // ...
```

Hope that helps.

And while I'm at it here's how you could reuse it all easily:
```php
class ProductCategoryCollectionType extends AbstractType
{
    private $categoryListener;

    // inject it as above

    public function buildForm(...)
    {
        $builder->addeventListener($this->eventListener);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'allow_add' => true,
            'entry_type' => TextType::class,
            'constraints' => array(
                ...
           ),
        );
    }

    public function getParent()
    {
        return CollectionType::class;
    }
}
```

And in any types, just use:
```php
$builder->add('categories', ProductCategoryCollectionType::class);
```

Cheers!

**Comment by zacharyzh** [comment]
@HeahDude 

That's looks pretty good! I need to learn more about the FormType extending.

Thank you very much. That's what I need. 😄

**Comment by HeahDude** [comment]
So I suggest to close here since there is already enough hooks IMHO to validate data in a form.

The Form component provides `Form::addError` to play with the validation process, and by extension this is delegated to the Validator component thanks to a `ValidationListener` from the core component, configured in the full stack, and based on models.

From there, two possibilities: build custom constraints that fit the default hook to validate a model (but also independently from the form), or use a custom hooks to add errors (e.g using listeners, data mappers, request handlers, controllers, services, ...) when something is wrong in the form mechanism.

**Comment by javiereguiluz** [comment]
Closing it because of the reasons explained by @HeahDude.
