### ISSUE TITLE
\Symfony\Component\Serializer\Exception\UnexpectedValueException provides insufficient semantics

### ISSUE THREAD

**Issue by wimleers** [symfony/symfony#20534]
Drupal 8's normalizers' `denormalize()` implementations throw `UnexpectedValueException` to indicate unexpected values in the received data, which cannot be denormalized to corresponding PHP objects. Such exceptions should result in a 422 response: `\Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException`.

Sadly, the same exception is used in Symfony's encoders/decoders — it is thrown by:

- `\Symfony\Component\Serializer\Encoder\JsonDecode::decode()`
- `\Symfony\Component\Serializer\Encoder\JsonEncode::encode()`
- `\Symfony\Component\Serializer\Encoder\XmlEncoder::buildXml()`
- `\Symfony\Component\Serializer\Encoder\XmlEncoder::decode()`

… yet encoding/decoding problems should result in a 400 response: `\Symfony\Component\HttpKernel\Exception\BadRequestHttpException`.

The official docs don't mention 422 responses or (de)normalization failures either: http://symfony.com/doc/current/components/serializer.html + http://symfony.com/doc/current/serializer.html.

**Comment by dunglas** [comment]
422 exceptions are a Drupal specificity. Symfony doesn't have any builtin mechanism to transform Serializer's exceptions in HTTP errors.

You should report this problem on the Drupal bug tracker instead of here.

**Comment by catch56** [comment]
This issue was opened as a spin-off from a Drupal issue, see the discussion in https://www.drupal.org/node/2827084 which led to it being opened. We have a workaround for Drupal, but the lack of specificity in Symfony's exceptions precluded a less intrusive approach that was suggested, hence this issue.

**Comment by xabbuh** [comment]
@dunglas More specific exceptions would allow to base the response status code on the exception being thrown instead of having to parse the exception message. See #21239 for a suggestion to improve the situation for Drupal.

@wimleers @catch56 Can you confirm that such a change would ease Drupal's situation?
