### ISSUE TITLE
[BUG] [Symfony 3.0] [PHP 7] Cannot declare class Locale, because the name is already in use

### ISSUE THREAD

**Issue by RubenHarms** [symfony/symfony#20532]
I got the following error in the console, when using a translation within a twig file (not sure if it's only in twig):

```
Cannot declare class Locale, because the name is already in use.

Exception trace:
 () at /var/www/domains/rsaleads/vendor/symfony/symfony/src/Symfony/Component/Intl/Resources/stubs/Locale.php:23

```

Info about environment:

PHP 7.0.13-1+deb.sury.org~xenial+1 (cli) ( NTS )
Symfony 3.0.1

**Comment by xabbuh** [comment]
This looks weird. Can you explain which step you performed that ended up here? Did you switch PHP versions, but did not clear the cache?

**Comment by RubenHarms** [comment]
First I upgraded to 3.0.1, after a succes upgrade, i switched to PHP 7.0.  I can confirm this issue is not a cache issue. I forced cleared the cache  by removing the folder cache content (rm ./var/cache/prod/*; rm ./var/cache/dev/*), but that does not solve anything.

**Comment by RubenHarms** [comment]
The following rule causes the error:
``` $c = \Symfony\Component\Locale\Locale::getDisplayCountries('nl'); ```

I replaced the code with the following code:
```$c =  Intl::getRegionBundle()->getCountryNames('nl');```

But this strange (Declare) error should not may appear!

**Comment by thi3rry** [comment]
Same here with Symfony 3.2, PHP 7.0.14-2+deb.sury.org~xenial+1
but with Response class

`Cannot declare class Symfony\Component\HttpFoundation\Response, because the name is already in use in /var/www/var/cache/prod/classes.php on line 4479`

In prod environment it seems to appear when using the when using the HttpCache with AppCache().

**Comment by thi3rry** [comment]
Well, I found this issue with the use of FOSHttpCacheBundle https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/276

I use this gist https://gist.github.com/pestaa/d544870c8bf7c9ecdc1cb999ac918cbb to solve the problem.

**Comment by mvrhov** [comment]
afair this is because of zendoptimizer try completely disabling it

**Comment by nicolas-grekas** [comment]
@thi3rry your issue is different and should be solved by #21184
@RubenHarms can we close this issue then?

**Comment by jakzal** [comment]
Closing due to no response.

@RubenHarms feel free to come back with more details and we'll re-open.

**Comment by krazygit** [comment]
I got the same issue with Symfony\Component\Config\ConfigCacheInterface


> PHP Fatal error: Cannot declare interface Symfony\Component\Config\ConfigCacheInterface, because the name is already in use in /home/Myproject/var/cache/web/prod/classes.php

Env:
SF 3.2.8 + php7.1.5

When I run cache clear the prod/classes.php generated cause this strange error.
But when I just delete the cache directory and run the App every thing ok...

**Comment by Pei116** [comment]
I have problem

**Comment by sstok** [comment]
@krazygit try upgrading to Symfony 3.3, and remove this line https://github.com/symfony/symfony-standard/blob/3.3/web/app.php#L12

**Comment by NicoHaase** [comment]
@sstok: if he is using PHP >= 7.0.0, as he states, line 12 should never be called

**Comment by xabbuh** [comment]
@NicoHaase Old versions of the Symfony Standard Edition didn't have this condition. So you need to make that change manually if you bootstrapped your project before the change was done in the repository.

**Comment by Bubelbub** [comment]
I still have this issue with Symfony 3.4 LTS.

**Comment by jakzal** [comment]
@Bubelbub can you provide a full stack trace to show where's the error coming from?

**Comment by nicolas-grekas** [comment]
I would close here: this is the same as #25484, where I stated:

**Comment by nicolas-grekas** [comment]
This issue is generally due to this: conflicting inlining strategies between boostrap.cache.php, classes.php and now maybe the inlined "include" in the container. Fortunately, we deprecated the two former, so this will die soon. Just don't use them and done.

**Comment by jakzal** [comment]
Ok. @Bubelbub please try Nicolas' suggestion and come back if it didn't make your issue go away.

**Comment by helmidridi** [comment]
I  have this issue with Symfony 3.4.

**Comment by clementtalleu** [comment]
I still have this problem with sf 3.4. I try to fix it by modify my app_dev but it's not effective

**Comment by mendonca89dalton** [comment]
It gave me a similar problem and in the end I used php version 7.0.13 and symfony 3.1

**Comment by NicoHaase** [comment]
> It gave me a similar problem and in the end I used php version 7.0.13 and symfony 3.1

Have you tried updating both PHP and Symfony? Using completely outdated and no longer supported versions does not sound good

**Comment by kumar2112** [comment]
Hi all i am trying to create a new bundle in symfony 5 . so created and folder Core in src  folder 
mention namspace for in composer json file  also  register my bundle in  bundles in bundle config .but when i try to run the app its shows me 

`Compile Error: Cannot declare class PortableAdmin\UserBundle\PortableAdminUserBundle, because the name is already in use`


Please help me why its happening.

**Comment by xabbuh** [comment]
@kumar2112 For support, please refer to one of the [support channels](https://symfony.com/support).

**Comment by Skiwa** [comment]
This might help : 

In my case, I simply changed  `Locale::getDisplayRegion($cc, 'fr'));` to `\Locale::getDisplayRegion($cc, 'fr'));`

**Comment by isaqov1700** [comment]
PHP Fatal error:  Cannot declare class CreateRatingsTable, because the name is already in use in /home/abdurahmon/Documents/GitHub/Olx.uz/database/migrations/2023_03_23_082629_create_ratings_table.php on line 7

   Symfony\Component\ErrorHandler\Error\FatalError 

  Cannot declare class CreateRatingsTable, because the name is already in use

  at database/migrations/2023_03_23_082629_create_ratings_table.php:7
      3▕ use Illuminate\Database\Migrations\Migration;
      4▕ use Illuminate\Database\Schema\Blueprint;
      5▕ use Illuminate\Support\Facades\Schema;
      6▕ 
  ➜   7▕ class CreateRatingsTable extends Migration
      8▕ {
      9▕     /**
     10▕      * Run the migrations.
     11▕      */


   Whoops\Exception\ErrorException 

  Cannot declare class CreateRatingsTable, because the name is already in use

  at database/migrations/2023_03_23_082629_create_ratings_table.php:7
      3▕ use Illuminate\Database\Migrations\Migration;
      4▕ use Illuminate\Database\Schema\Blueprint;
      5▕ use Illuminate\Support\Facades\Schema;
      6▕ 
  ➜   7▕ class CreateRatingsTable extends Migration
      8▕ {
      9▕     /**
     10▕      * Run the migrations.
     11▕      */

      +1 vendor frames 

  2   [internal]:0
      Whoops\Run::handleShutdown()
