### ISSUE TITLE
Using the dot notation on an instance of Twig_Template is deprecated since version 1.28 and won't be supported anymore in 2.0

### ISSUE THREAD

**Issue by garak** [symfony/symfony#20568]
I'm getting such deprecation message in tests, since I upgraded Twig a couple of days ago.
I'm on Symfony 2.8.13 with Twig 1.28.1
I tried to dig into Twig source to understand the reason of such deprecation, but I couldn't understand. Moreover, I couldn't find a mention of such deprecation in Twig files (e.g. in deprecated.rst)
The stranger thing is that I'm not getting any logged deprecation in dev environment, the debug toolbar is not showing any deprecation message in logs. It happens only when I run tests (with phpunit-bridge, of course).

**Comment by fabpot** [comment]
The deprecation (for which the message is indeed not very clear) is when you are trying to call a method on a template instance with the dot notation in a template. For instance, `template.renderBock('foo')`. That's deprecated now, and you should use `block('foo', template)` instead. Of course, it can also comes from a third-party bundle or the Symfony web profiler if it is not updated to the latest version (read dev version for now).

Regarding the deprecation message in the logs, be sure to upgrade to the latest version of MonologBundle as 3.0.0 has a bug.

I'm going to tweak the Twig error message to make it clearer.

**Comment by garak** [comment]
Indeed, I'm using monologbundle 3.0.1. I also tried to upgrade from symfony 2.8.13 to 2.8.14-DEV, but I still don't see deprecations in debug toolbar.
About `block`/`renderBlock`, trying a `grep -lr renderBlock vendor/` is resulting in files from `vendor/symfony` and `vendor/twig` dirs only, so there's no third-party bundle involved

**Comment by fabpot** [comment]
see twigphp/Twig#2270

**Comment by fabpot** [comment]
Sorry, 3.0.1 has the bug, try with 3.0.0 which does NOT have the bug.

**Comment by kunsttorsten** [comment]
Importing a bundle of macros by using {% import "..." as varname %} also throws exception "Using the dot notation on an instance of Twig_Template is deprecated" now. How to use it now?

**Comment by karlbuckland** [comment]
I'm getting the same when trying to set up a recursive macro, eg:
`{% import _self as twigdebug %}`
`{{ twigdebug.recursiveTree() }}`

Then within the macro twigdebug:
`{{ _self.recursiveTree() }}`

Is there an equivalent of block() for calling a macro?

**Comment by RenaudParis** [comment]
I am only using Twig (not Symfony) and I have the same issue here when using macros.

```
Fatal error: Uncaught exception 'ErrorException' with message 'Calling "gettrBegin" on template "email/_macros.twig" from template "email/validation/accepted.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0.' in D:\wamp\www\my_project\lib\vendor\twig\twig\lib\Twig\Template.php on line 222
```

The faulty line is:
```
{% import 'email/_macros.twig' as macros %}
{{ macros.trBegin }} {# <== throw exception here #}
```

This is not very kind to throw an exception for a deprecated feature. A mere notice is more suited.

I'm going to rollback to 1.27 because the exception throwing is not described in the changelog and there is no described alternative for macros.

**Comment by stof** [comment]
@RenaudParis can you provide us a reproducing test case ? Because macros are meant to work without triggering this deprecation (and they do in the testsuite)

**Comment by RenaudParis** [comment]
Hi @stof mmmh ok I'll try to create a minimalist template and copy/paste it here. FWIW my template is extending a layout, and the import is in the layout. brb.

**Comment by stof** [comment]
well, this is your issue then: you need to import macros in the template using them, not in the parent. (We have to improve the deprecation warning for this case)

**Comment by RenaudParis** [comment]
It always worked. Why wouldn't it anymore? I don't see anything about that in the changelog.

Am I now also forbidden to create variables in the layout too? Because I'm making heavy use of this as well :)

In any case I rollbacked to 1.27 and I no longer plan on upgrading versions. Too risky. But I'd be glad to help you anyway!

Here are my test templates if necessary:

```
/// layout.twig
{% import '_macros.twig' as macros %}

{% block body '' %}
```

```
/// test.twig
{% extends 'layout.twig' %}

{% block body %}
	{{ macros.heroic('toto') }}
{% endblock %}
```

```
/// macros.twig
{% macro heroic(text) %}
	<span style="font-weight: bold; font-size: 22px;">{{ text }}</span>
{% endmacro %}
```

**Comment by stof** [comment]
@RenaudParis it was never *meant* to work. I worked only thanks to an implementation detail (we were not even aware it was working until we made a change breaking it and had to delay it until 2.0 instead).
Your `macros.heroic('toto')` call is not compiled as a macro call here, but as an attribute access to the template (which is slower than compiling it as a macro call btw). This works only thanks to the way macro are compiled in the template, making them appear like getters. But this also created other issues (some macro names are forbidden because of that for instance, and it created some security issue in the past). Twig 2.x changes the way macro are compiled, making them inaccessible as getters (and so things won't work if the macro call is not recognized as a macro call).

and Twig does not throw exceptions for deprecations. It triggers a **silenced** ``E_USER_DEPRECATED``. The only way to get an exception is to use a broken error handler (error handlers have the power to ignore the ``@`` operator if they are not careful about it, but doing it when triggering exceptions is plain wrong).

**Comment by RenaudParis** [comment]
@stof well then I'm glad that this "bug" existed until 1.28 :) because it allows me to import my macros only once in the layout and use them freely in any template extending this layout. Also I don't care about compilation speed because in production I am using cached templates obviously :)

In Template.php:222 (the line that you can see in my error log) I see this: "throw new Twig_Error_Runtime()". But indeed I tested again and I think you are catching it later and generating a notice instead, and my error handler is transforming it into an exception. Because when I removed my error handler then it worked fine. However, I like to throw exceptions on notices, in order to have the cleanest code possible (undefined variables or whatever), so I'll stay with Twig 1.27, so that I can keep my error handler and also not have to modify all my templates.

Thanks for the detailed explanation anyway, it's always good to know the inner workings!

**Comment by stof** [comment]
@RenaudParis I'm not talking about the compilation speed. I'm talking about the runtime speed of the compiled code (the compile code is not the same for a macro call or for an attribute access).

It is fine to turn notices into exception in an error handler (Symfony does it to in dev) as long as you take care to respect the error reporting level in the error handler, to avoid breaking the ``@`` operator. And your error handler does not respect it.

**Comment by RenaudParis** [comment]
@stof isn't the `@` handled by php internally? I'll have a look at my error
handler to see if I can improve it somehow, but I have already been using
it for quite some time with no problem.

In any case, isn't `@` supposed to be a bad practice as a general rule?

Le jeu. 24 nov. 2016 12:23, Christophe Coevoet <notifications@github.com> a
écrit :

**Comment by stof** [comment]
@RenaudParis error handlers are still called for silenced errors (allowing to log them for instance). But ``error_reporting()`` would report ``0`` in the error handler for this case.
``@`` does not disable the error handler. It changes the error reporting level temporarily.

**Comment by mvrhov** [comment]
> well, this is your issue then: you need to import macros in the template using them, not in the parent. (We have to improve the deprecation warning for this case)

@stof if this is true than this is very very bad BC break. 
We also utilize this heavily as macros that are used in most templates are only imported in a top most parent. Importing 3-4 macros in each template it troublesome.

**Comment by stof** [comment]
@mvrhov relying on macros being accessible as object attribute access forces to do several weird things in Twig, and prevents doing performance optimization for macros (it even created security issues in the past, requiring more weird things to fix the security issue without breaking BC for cases not being insecure).
What kind of macros are used in almost all your templates ?
Btw, you could look into providing the feature in a function defined by an extension instead depending on the use case.

**Comment by mvrhov** [comment]
Mostly form ones they are theme specific e.g semantic-ui, bootstrap...

```jinja
{% macro action(type,caption,params,iconName) %} table actions
{% macro cancel() %} adds cancel button if neccessary
{% macro remove(uri, panelCaption,  panelText, captionAction, icon = '') %} full confirm before deletion dialog
{% macro action_bar(form, params) %} form buttons inside an action bar
..
```

**Comment by RenaudParis** [comment]
@stof as far as I'm concerned, I primarily/only use macros in emails. And
they are used in every email: tr/td creation with inline style, a-href
creation with inline style, buttons, you name it. I could use includes
instead, but I decided to use macros at the beginning because I found the
markup to be easier/lighter.

Le ven. 25 nov. 2016 14:51, Christophe Coevoet <notifications@github.com> a
écrit :

**Comment by mtnorthrop** [comment]
@karlbuckland,

I ran into the same problem as you did with recursive macros, and the solution was to not use ```_self.macroname()``` inside the macro, but instead import ```_self``` at the beginning of the macro.

For example, the code you provided should look something like this:

```
{% import _self as twigdebug %}

{% macro recursiveTree() %}
    {% import _self as twigdebug %}

    {{ twigdebug.recursiveTree() }}
{% endmacro %}

{{ twigdebug.recursiveTree() }}
```

I'm not sure this is the 100% correct way of doing things, but it fixed the deprecation notices for me.

**Comment by fabpot** [comment]
@mtnorthrop Looks good to me.
