### ISSUE TITLE
[TwigBridge] AppVariable doesn't know HTTP host in forwarded requests

### ISSUE THREAD

**Issue by Wirone** [symfony/symfony#20596]
I found this issue after migrating to Silex 2.0. I have app under VHost `http://custom.loc` and home route `/` which invokes `DefaultController::indexAction()`:

```php
public function indexAction(HttpFoundation\Request $request, Application $app)
{
    // Use different route as home route, but without browser redirect
    return $app->handle(
        HttpFoundation\Request::create(
            $app['url_generator']->generate('my_custom_route'),
            'GET'
        ),
        HttpKernelInterface::SUB_REQUEST
    );
}
```

In Twig's default layout I have:

```
<script type="text/javascript">
    APP = {
        baseUrl: "{{ global.request.getSchemeAndHttpHost() }}"
    };
</script>
```

Which produces `APP.baseUrl = 'http://localhost'` ONLY in that forwarded route, everywhere else `APP.baseUrl` is generated properly. It produces errors when accessing some API/ajax resources because of cross-origin policy.

**Solutions:**

- Generate base URL as `app['request_stack'].getMasterRequest().getSchemeAndHttpHost()`
- Use `UrlGeneratorInterface::ABSOLUTE_URL` when generating forward URL

**However** maybe `AppVariable` should have `getMasterRequest()` method, so it would be possible to use `global.masterRequest.getSchemeAndHttpHost()`?

PS. `AppVariable` throws exceptions that `app.request`, `app.user`, `app.session`, `app.debug` and `app.environment` variables are missing, but in Silex these variables are under `global` namespace. I didn't know if I should submit it as another issue and if it should be here or in `silex/silex`.

**Comment by Wirone** [comment]
@fabpot I would like to make PR, but before that I would like to know what do you think about it - if it's something to fix, or it should be done on app's side (like example solutions above).

**Comment by stof** [comment]
This is because the new request is created without inheriting the current info for SERVER into, and is not using a full URL either (as you don't generate it as absolute).

So there is no issue in AppVariable. There is only an issue in the Request object you created (which is a localhost one). When forwarding requests to a different controller, Symfony takes care of building the request properly: https://github.com/symfony/symfony/blob/a4edafbd7d82ccea983f04ade3dc220e72f340e2/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php#L60 (but which does not forward based on a URL) or https://github.com/symfony/symfony/blob/a4edafbd7d82ccea983f04ade3dc220e72f340e2/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php#L113 (which does a few extra work as it is about fragment rendering here)

**Comment by Wirone** [comment]
@stof I am aware of that what you wrote, solutions above address it. Maybe issue name is misleading, I was thinking about extending `AppVariable` with something that would make accessing master request possible. It could be new proxy method `getMasterRequest()` or argument in `getRequest()` (with current request as default return value).

**Comment by stof** [comment]
IIRc, we explicitly rejected adding ``getMasterRequest`` in the past. In most cases, accessing the master request is a bad idea, because it breaks the encapsulation of the request handling.
The only use case we received for adding this method until now was the same one than the one you gave here: working around badly constructed sub requests. And the right solution for this is not to access the master request, but to fix the code building the sub request.

**Comment by Wirone** [comment]
@stof OK, I understand. 

PS. What about those exceptions? It does not correspond to Silex 2.0, should I submit it in `silex/silex`?

**Comment by stof** [comment]
@Wirone http://silex.sensiolabs.org/doc/master/cookbook/sub_requests.html gives the right info to build the subrequest without loosing important info from the master request (see the second code block)

**Comment by Wirone** [comment]
@stof yeah, I read it already and now I'm forwarding like this:

```php
public function indexAction(HttpFoundation\Request $request, Application $app)
{
    return $app->handle(
        HttpFoundation\Request::create(
            $app['url_generator']->generate('my_custom_route', [], UrlGeneratorInterface::ABSOLUTE_URL),
            'GET',
            $request->query->all(),
            $request->cookies->all(),
            array(),
            $request->server->all()
        ),
        HttpKernelInterface::SUB_REQUEST
    );
}
```
