### ISSUE TITLE
[DI] Replace container injection by explicit service locators

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#20658]
In some cases, there is no better way than injecting the container itself and use it as a service locator.
The issue then is that one can access *any* public service, thus it is almost impossible to track service dependencies for such code.

I'd like to propose a first class service locator concept, with mandatory and explicit dependencies declaration. Such code would have first to explicitly declare the list of services they need to get them, through a dedicated container (service locator really) that would have access to them and only them.

We could then maybe deprecate injecting the main container directly, and replace that by the possibility for such a service locator to return the "service_container" when required (though that would be a discouraged practice, but could be required for e.g container inspecting logics).

**Comment by mvrhov** [comment]
You mean this: https://github.com/liip/LiipContainerWrapperBundle ?

**Comment by nicolas-grekas** [comment]
@mvrhov not far from this! Except that I'd move the configuration responsibility to the user land side, adding a dedicated interface to do that (return the list of required services, and optionally their type so that autowiring could use that info to do its job).

**Comment by stof** [comment]
@nicolas-grekas the service container should still be injectable in these service locators services. Otherwise, it breaks the main use case for injecting the container: keeping the instantiation lazy until this service is retrieved from the service locator.
You don't want to instantiate all your controllers and all their dependencies just to instantiate the controller resolver for instance, as each request will use only 1 controller.

**Comment by nicolas-grekas** [comment]
As I see these service locators, they should just call $container->get internally, after checking if the service name is allowed. This mean lazy instantiation would work out of the box the same as today.

**Comment by javiereguiluz** [comment]
I'm not sure about the need for this feature:

1) If you inject `service_container` in your own service, it's probably because of some rare edge-case or because you have lots and lots of dependencies (this is probably an architecture error in your app that you'll fix when you have time for that).
2) If Symfony forces you to inject `service_container` somewhere (I'm not sure we have that case), then that's a Symfony bug.

**Comment by stof** [comment]
@javiereguiluz the third case being the case of service locators wanting lazyness (event dispatcher and controller resolver are such cases in the core, but the core is not special for this and other parts may have similar needs)

**Comment by theofidry** [comment]
Like @javiereguiluz, I'm not sure this should be added to the core, but maybe it's something that could be pushed into third-party bundle ([LiipContainerWrapperBundle](https://github.com/liip/LiipContainerWrapperBundle)?) and promoted in the doc rather.

**Comment by nicolas-grekas** [comment]
@javiereguiluz this is also targeting all classes that use `ContainerAwareTrait`. To me this has two major drawbacks:
- too broad access to existing services;
- no prior knowledge about which services are actually used, which makes it impossible to to verify/match the actually existing services and the actually used one in such code.

The goal of this RFC is to fix these two issues with their exact solution:
- explicit beforehand dependency declaration;
- restricted access to listed services only.

**Comment by nicolas-grekas** [comment]
Note also that if everything goes well with #20657, it *might* very well have the potential to remove the need for any container injection. Which means we should first work on #20657 then revisit this one.

**Comment by nicolas-grekas** [comment]
Sharing my recent thought on this:

it *could* be a good idea to allow classes/objects to declare a set of services they need (in a way that the FIG/a PSR could define).
This could be as simple as making them able to declare a map of "id" => "type" that the object needs.
Eg:

'logger' => 'Psr\Log\LoggerInterface'

this meaning: please, someone, give me a container that has a service called 'logger' service, that implements LoggerInterface. This container could just have the current PSR11 interface and things would work.

There are of course two things missing: a way for classes/object to declare this list, and a standard way to inject the container into such compliant objects.

This would allow "autowiring" of deps - by leveraging the return type to know which service from the existing main container should be cherry-picked into a smaller dedicated container that fits the declaration.

There are remaining cases unclear for now, like what should be the behavior when a service is required but no such thing exists in the main container - or when an ambiguity exists (which eg if two LoggerInterface exists in the main logger). etc.

But this is something a FIG working group could solve I guess if the goal looks interesting enough.

ping @mnapoli @moufmouf

**Comment by mnapoli** [comment]
@nicolas-grekas I'm not sure I understand. `ContainerInterface` (aka injecting and using the container as a service locator) has proven to be useful in cases where *you don't know what you are going to `get()`*.

For example, in Zend Expressive or Slim, the router (or the dispatcher) `get()` the controller to call. The router cannot declare beforehand what entries it needs, because it's resolved at runtime based on the URL of the request.

Other example: Behat uses `ContainerInterface` to resolve dependencies of feature contexts: contexts are configured by users, so Behat doesn't know the list in advance (so there's no point in generating a custom service-locator on the fly just to use it afterwards).

So all those scenarios are `get($someId)` where `$someId` is dynamic (unknown at compile time).

It seems to me all other scenarios would be better solved by direct dependency injection? (though I agree it's sometimes easier said than done, for ex. if you consider `ContainerAwareTrait`)

**Comment by nicolas-grekas** [comment]
Would be great to post an excerpt of these concrete examples on the fig list, with actual code samples of how each work in the email !

**Comment by mnapoli** [comment]
@nicolas-grekas good idea it seems it could help, I'll try to find time to do that this week-end.

But to be concrete that's exactly the same thing that's done here in Symfony's router: https://github.com/symfony/symfony/blob/5129c4cf7e294b1a5ea30d6fec6e89b75396dcd2/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php#L65 (and that's just one example) I.e. in `routing.yml` you map a route to a controller as a service (`app.usercontroller:subscribe`) and the router resolves `app.usercontroller` by calling `Container::get()`.

Currently Symfony decouples the router from the framework through the FrameworkBundle. With PSR-11 *maybe* the router could have native dependency injection support and be compatible with all DI containers. That would allow Symfony's router to be usable out-of-the-box with all containers?

**Comment by unkind** [comment]
@mnapoli in general, I'm not sure if it makes sense to couple such services with DI-container concept (like PSR-11). See this example: https://github.com/symfony/symfony/issues/20875#issuecomment-266801911. It may be simple callable:
```php
final class CallableCommandBus implements CommandBus
{
    public function __construct(callable $handlerMap)
    {
        // ...
    }

    public function handle(Command $command)
    {
        // Note that the key here is not service id.
        if ($handler = $this->handlerMap(get_class($command))) {
            $handler->handle($command);
        }

        throw ...
    }
}
```

**Comment by chalasr** [comment]
> Note also that if everything goes well with #20657, it might very well have the potential to remove the need for any container injection

The [SecurityBundle's FirewallMap](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/Security/FirewallMap.php) is also a concrete use case where this would be useful and that is not (stop me if I'm wrong) solvable through getter injection, as it matches a given request with a given service id, then load it from the container.

**Comment by chalasr** [comment]
See #21553
