### ISSUE TITLE
[DI] Support generating interface-bound proxies

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#20656]
May it be useful to make the container able to generate interface-bound proxies?

I see 3 benefits to do so:
- hiding the concrete class to the consumer, to create a safeguard and enforce talking to its dependency only through the interface-defined contract;
- these kind of proxies could also be able to instantiate their concrete implementation lazily, in a much simpler way than the generic lazy-proxies generated by https://github.com/Ocramius/ProxyManager;
- as a side effect, it would allow creating lazy proxies for final classes, thus fix #20392.

There are two places where this could be enabled, depending on who should have this responsibility:

## in the proxyfied-service definition

Assuming `Ns\FooClass implements Ns\FooInterface`, this could be eg. in XML:
```xml
<service id="foo" class="Ns\FooClass" proxy="true" />
```
so that:
```php
$container->get('foo') instanceof Ns\FooInterface; //==> true
$container->get('foo') instanceof Ns\FooClass; //==> false
```
lazyness could be activated when the "lazy" attribute is enabled, or be always enabled.
"proxy" attribute being true, all interfaces implemented by the service class would be proxyfied.
We could also imagine a `proxy` tag that explicitly tells which interfaces should be proxyfied amongst all the implemented one.

## in the dependency injecting definition

In XML, this could be eg.:
```xml
<service id="foo" class="Ns\FooClass" />
<service id="bar" class="Ns\BarClass">
<argument type="service" proxy="Ns\FooInterface">foo</argument>
</service>
```
so that *inside bar*:
```php
$this->foo instanceof Ns\FooInterface; //==> true
$this->foo instanceof Ns\FooClass; //==> false
```
lazyness could be activated when a "lazy" attribute is enabled, or be always enabled.
In that case, I don't think we should allow proxying several interface at once.

WDYT? (ping @theofidry, maybe you'd like to give it a try?)

**Comment by xabbuh** [comment]
To me this is sounds like a good idea. :+1:

**Comment by pamil** [comment]
I'd love to see it 👍 

Btw. shouldn't `<argument type="service" proxy="Ns\FooInterface">foo</argument>` be `<argument type="service" proxy="Ns\FooInterface" id="foo" />`?

**Comment by stof** [comment]
This should not be in the argument configuration, as this would mean that injecting the same service in 2 different places would inject different objects (depending on whether they are proxied or no), which can creates nasty behaviors (as the DIC currently enforces that getting a shared service always return the same instance).

Regarding the implementation, I'm not sure we should get rid of ProxyManager. There are a bunch of nasty cases regarding proxy generation (handling code generation, handling all features of method signatures, etc) and I don't see any benefit reimplementing many part of the library while it is well-tested.

**Comment by pamil** [comment]
@stof totally agreed, on both points made.

**Comment by theofidry** [comment]
@nicolas-grekas sorry I couldn't check properly the issue, I've got a few question regarding it but it might be better to ask in person at the SfCon ;)

**Comment by theofidry** [comment]
I think proxy generation, interface bound or not, are far from trivial so I would prefer to keep everything in ProxyManager instead. This IMO is a missing feature from ProxyManager, not Symfony itself (although Symfony will need to change a bit its integration for this new feature).

Regarding where to enable it, I'm more tempted by the second approach for several reasons:

- I find it more flexible
- I hardly see the change of the first approach without causing any BC of any kind

The case I'm thinking of is the following:

- Your class may not have any interface
- Your class may have additional methods that that are not in the interface and you depend on it (i.e. you are actually not making use of the interface in some cases but depend on a concrete implementation instead)
- Your class implements several interfaces

Having the second approach, you could keep the current behaviour by having `proxy="true"` and give the possibility of the user to choose to proxy against an specific interface instead when he wants to (e.g. `proxy="App\FooInterface"`).

Maybe having a proxy for two interfaces is doable, I'm not sure to see why it wouldn't, but we can always revisit how to integrate this feature once it lands in ProxyManager.

**Comment by theofidry** [comment]
As discussed at the SymfonyCon, it is true that an interface bound proxy is way simpler (approximate code):

```php
namespace Ns;

interface FooInterface
{
  public function foo(): string;
}

class FooProxyClass implements FooInterface
{
  private $container;
  private $serviceId;
  private $service;

  public function foo(): string
  {
    if (null === $this->service) {
      $this->service = $this->container->get($this->serviceId);
    }

    return $this->service->foo();
  }
}

class FooProxyClass implements FooInterface
{
  private $container;
  private $serviceId;
  private $service;

  public function foo(): string
  {
    if (null === $this->service) {
      $this->service = $this->container->get($this->serviceId);
    }

    return $this->service->foo();
  }
}

$proxy = Closure::bind(
    function (ContainerInterface $container, string $serviceId) {
        $this->container = $container;
        $this->serviceId = $serviceId;
        
        return $this;
    },
    new FooProxyClass(),
    'FooProxyClass'
)($container, $serviceId);

```

It might still be easier to have a dependency on Zend/Code to generate the proxy though.

I'm still less convinced about the argument proxy and would prefer to split this RFC in two to treat them separately, but I'm +1 for the first one.

There is also the question of if this could be handled in ProxyManager and be more generic (not coupled to Symfony DIC) via PSR-11.

**Comment by nicolas-grekas** [comment]
Because we decided to *not* have a hard requirement on ProxyManager (and I'm really fine with this), lazy services are second zone citizen.
I forgot to mention it: this RFC is also targeted at making them first class citizen, by seeking for a way to make them so with simpler logic, which I believe this RFC allows (as you spotted).
This means interface-proxy generation should be done in the component itself, by PhpDumper I'd say.
We should KISS, the need for interop (being PSR11 or separated package for code gen) does *not* exist IMHO. And if it were, it might be done in a later PR.

About your example proxy, it looks nice :)
I just didn't expect the `$service` property and thought we should always call the container. This allows resetting the service transparently in some case where it could be needed (e.g. Doctrine EM). This shouldn't impact perf much.

There is one missing case, which is fluid interfaces.
So we should check the return value like this:
```php
$service = $this->container->get($id);
$result = $service->foo();
return $result === $this ? $this : $result;
```

**Comment by nicolas-grekas** [comment]
Of course, we should also deal with references (as arg and as return values).
But I think we don't have to deal with PHP5-style variadics (that use func_get_args()).

**Comment by nicolas-grekas** [comment]
I guess this should also allow generating proxies based on abstract classes?

**Comment by theofidry** [comment]
Possibly, but I would add the support for it in a second iteration.

**Comment by TheCelavi** [comment]
I would like to support third comment/feature by @pamil. This feature can be desirable, at this moment, this feature would help us with our current project.

Namely, we are using Go! Aop for handling cross cutting concerns (mainly as implementation of decorator). Now, Aop bundle allows us to inject symfony services in aspects, which makes it very powerful tool. 

However, we have noticed that service injected in aspect can not be, nor it can depend on, a service which class has been weaved with Aop engine. Not to get into too much explaining, it goes something like -> first service container is initialized, then aspect container, then aspects as services, then other services. If aspect requires service, that service is initialized prior to aspect, where we get into a cyclic dependency issue.

There are two approaches now with which we can handle this situation:
1. Service locator, we can inject container, or service locator - we dont like that approach, we dont like idea of service locator at all
2. Mark injected service into aspect as "lazy" (injecting proxy). 

We are using approach nb. 2. However, we are not found of that approach either, because, for vendor's services we have to do extra work in order to make that service lazy.

We use a lot of aspects, they are registered and initialized with the application, but majority is not used during Request-Response lifecycle.

Therefore, in terms of execution optimization, but mostly having in mind developer experience, ability to specify that injection of specific service should be lazy would increase our productivity.

For us, solving cyclic dependency issue would be as simply as modifying from:

    <argument type="service">foo</argument> 

to:

    <argument type="service" proxy="Ns\FooInterface">foo</argument>

and that would make our developer experience smooth. We do not have any objection to sacrifice some performances or arguable "good, by the book, practice" on account of our productivity and achieved developer experience.

Thank you.

**Comment by stof** [comment]
Well, marking a service as proxy at the level of the injection breaks a rule of the current system: the injection of `<argument type="service" id="translator" />` always injects the same instance for shared services. If we start doing injection-level proxies, this may not be true anymore (and becomes even worse if we generate multiple proxy instances)

**Comment by TheCelavi** [comment]
@stof Proxy is just a wrapper around of same service instance for shared service right? Each proxy would use same service instance - it would not be a same proxy, but underlying service would be the same, or I have misinterpreted proposed idea?

**Comment by TheCelavi** [comment]
On top of that, if the rule is: "if there is a shared service A that can be lazy loaded with proxy AA, there can be only one instance of service A and only one instance of its proxy AA" -> I don't think that that can be classified as hard problem to solve. As service container manages shared services, it can manage shared proxies, right?

**Comment by stof** [comment]
Well, the issue proposes 2 implementations. What I'm saying is that the first proposal fits well in the existing system (it is actually just a different way of implementing the existing proxy, by proxying only an interface rather than the whole class). The second one requires changing one of the invariants we have in the component (and requires adding complexity in the component for that)

**Comment by backbone87** [comment]
Just a DX note: it must be possible to disable proxying on the argument side. imagine a service user like this:
```php
class Builder {
  private $service;
  public function __construct(ServiceInterface $service) {
    $this->service = $service;
  }
  public function method() {
    if($this->service instanceof SomeConcreteImplementationThatAllowsUsageOptimizations) {
      // efficient solution using special methods of conrete impl
      return;
    }
    // the long way
  }
}
```

if the injected service is defined by a 3rd party, you must override the whole definition, which in the worst case requires a custom compiler pass (because the service is dynamically created).
Therefore `<argument type="service" id="conrete_service" proxy="false" />` should be possible

**Comment by theofidry** [comment]
Not really a big fan of that @backbone87 tbh. If you don't want the service to be proxied it's simpler to either override the service definition or alter it via a Compiler pass. If it's just for that specific case, then maybe we could indeed provide a `Proxy` interface which would have a `getProxiedInstance()` method or something which every proxy would implement.

**Comment by popy-dev** [comment]
I'm probably a bit naïve there, I've just red this, and came with one idea which allows to "opt out" the proxy, avoid name collision (the proxy having the same name than the service), and would work nicely with autowiring :

Assuming ```Ns\FooClass``` implements ```Ns\FooInterface```

```
<service id="foo" class="Ns\FooClass" />
<service id="Ns\FooInterface" proxy="foo" />
```

Also, the service Ns\FooInterface could either implement ONLY Ns\FooInterface, or every interface of the Ns\FooClass. 

One other way of configuring this kind of behaviour would be that ```<service id="foo" class="Ns\FooClass" proxy="true" />``` would create one proxy service named after each Interface implemented by ```Ns\FooClass``` (but I guess it could be confusing seing services coming out of nowhere)

**Comment by nicolas-grekas** [comment]
See #27697 for an implementation (not everything discussed/proposed, but still the main idea.)
