### ISSUE TITLE
Suspicious HTTP redirect with redirectToRoute and DELETE method

### ISSUE THREAD

**Issue by kubawerlos** [symfony/symfony#20672]
I have request call with DELETE method and try to redirect to action with GET and getting this problem:

Having controller:
```php
<?php
class DefaultController extends Controller
{
    /**
     * @Method("get")
     * @Route("/homepage", name="homepage")
     */
    public function indexAction()
    {
        return new Response('hello');
    }

    /**
     * @Method("delete")
     * @Route("/delete", name="delete")
     */
    public function deleteAction()
    {
        return $this->redirectToRoute('homepage');
    }
}
```

For request 
```
"DELETE /delete"
```

I'm getting:
```
No route found for "DELETE /homepage": Method Not Allowed (Allow: GET, HEAD)
```

Is that suppose to happen? If so, why?

**Comment by stof** [comment]
which kind of client is doing the request ? Is it a browser or another tool ? And which one ?

**Comment by kubawerlos** [comment]
It's Postman

**Comment by stof** [comment]
I suspect that postman implements 302 redirects as described in the initial HTTP spec (keeping the original method) rather than as being implemented by all browsers out there (i.e. changing the method to GET).
The HTTP spec recognized that the Internet relies on the existing browser behavior since a long time, and standardized 307 as being a redirection keeping the same method.

I suggest you to open an issue on Postman asking them to switch to a behavior being more useful today. I'm not sure they would accept it (I have no link with the Postman team), but it would probably be the best resolution of the issue.
In the meantime, if you want to be compatible with Postman, you could use a 303 redirect (which is the original status code meant to represent what 302 became de facto). But be careful that you may loose support for old browsers by doing that, as I think some old browsers don't like 303 for redirections.
