### ISSUE TITLE
how to add a xml node to a symfony Crawler()

### ISSUE THREAD

**Issue by jul6art** [symfony/symfony#20686]
I need to manage xml documents in symfony.

I've got no problem to get the xml into a Crawler() instance, modify existing node and after it, put the xml into a file.

But i can't add new node.

When i try to add a new node with appendChild method to the parent, i've got:

   

>  wrong document error

And when i try the add method to the crawler, i've got:

    

> impossible to add two differents sources to the crawler?

What can i do to add a simple node to an existing crawler?

Thanks for any response

**Comment by javiereguiluz** [comment]
@jul6art I'm really sorry but I need to close your issue. The reason is that in the GitHub repository we only discuss about reported Symfony bugs and proposed new features.

For this kind of questions about using Symfony, please use any of the support alternatives shown in http://symfony.com/support Thanks!

**Comment by stof** [comment]
the Crawler component is not about modifying the underlying DOM document

**Comment by jul6art** [comment]
Thank you for your response :-)
