### ISSUE TITLE
[DI] Add "lazy collection" type

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#20875]
I was looking at #12521 then #20039. Both deal with lazyness in the event dispatcher.
The issue is having event listeners/dispatchers be instantiated only when actually needed.
`ContainerAwareEventDispatcher` partially works around the issue, but in a non generic way (bound to Symfony's DI  container and not compatible with private services).

But let's imagine we add a new lazy collection type to our lovely DI component, usable this way:
```xml
<service id="foo" class="Foo">
    <argument type="iterator">
        <argument type="service" id="bar" />
        <argument type="service" id="buz" />
        <argument key="key" type="service" id="zob" />
    </argument>
</service>
```

Generating this code when compiled (simplified example):
```php
protected function getFooService()
{
    return new Foo((function () {
        yield $this->get('bar');
        yield $this->get('buz');
        yield 'key' => $this->get('zob');
    })());
}
```

Then the referenced services would be instantiated only when the generator reaches the corresponding yield statement. This would allow building e.g. a generic lazy event dispatcher.

**Comment by enumag** [comment]
How does this solve the issue with LazyEventDispatcher? I don't see it.

**Comment by nicolas-grekas** [comment]
Because it would replace the ContainerAwareEventDispatcher completely with a more generic approach to laziness.

**Comment by enumag** [comment]
I don't understand. In EventDispatcher you don't want to lazily iterate over all listeners like you would with a generator - that way you would still instantiate all of them. You only need to instantiate those for the event that is dispatched at the moment.

Or do you mean that for each event the EventDispatcher should have a lazy collection like this? But then again not everything in the dispatcher is always lazy so that doesn't make much sense either.

**Comment by nicolas-grekas** [comment]
> for each event the EventDispatcher should have a lazy collection

yes

> not every listener needs to be lazy

it's not the job of listeners do know about that, so they shouldn't care

**Comment by unkind** [comment]
I'm not sure if I see the whole picture with event dispatcher example.

You have N lazy-collections for each of N events, right?
So you need something like
```php
interface ListenerProvider
{
    /**
     * @return callable[] <- this thing can be lazy-collection
     */
    public function getListenersFor(Event $event);
}
```
with `ContainerListenerProvider` implementation which is basically more or less same thing as existing one, isn't it?

Otherwise, if you want to inject all lazy-collections at once (like hash map `eventName => lazyCollectionInstance`), I have 2 questions:
* do I understand right that the first service would be instantiated every time in every lazy-collection of event handlers?
* would it be faster than #12521 which you referred to (the only point of that PR is performance AFAIK)?

**Comment by sstok** [comment]
I think I get it, you provide all the listeners/subscribers in the constructor (but because of the yield it will not actually load them yet). 

You can pass the EventDispatcher to any service, but once you start dispatching that's when all lazy services are initialized 😵 when this works, it's amazing 🙀

**Comment by tgalopin** [comment]
What I like about this approach is how it is generic: it decouples the EventDispatcher from the Container as the service resolution is now done inside the lazy-collection (inside the container definition).

@sstok You understand it right.

@unkind 
> do I understand right that the first service would be instantiated every time in every lazy-collection of event handlers?
Why would that be? The service would be instanciated only when the event is dispatched, isn't it? And even if I'm wrong on this, I don't think that's much of a problem.

> would it be faster than #12521 which you referred to (the only point of that PR is performance AFAIK)?
I'm not sure it would be, we have to benchmark, but in any case it's much more generic, so I personnally prefer it.

**Comment by unkind** [comment]
> Why would that be? The service would be instanciated only when the event is dispatched, isn't it? 

When you inject lazy-collection, it is already has `Generator` instance; it means first `yield` has occurred. First `yield` triggers first service from example above.

**Comment by nicolas-grekas** [comment]
> When you inject lazy-collection, it is already has Generator instance; it means first yield has occurred.

You made me doubt, but fortunately that's not the case, see https://3v4l.org/bMUn8

**Comment by julienfalque** [comment]
@unkind No, you would have to iterate over the injected `Generator` to reach all `yield` statements.

**Comment by unkind** [comment]
By the way, in practice, I need container-aware map way more often rather than lazy-collection. Probably, it makes sense to introduce `lazy-map` as well. The advantage is similar: you can make all services `private`.

**Comment by tgalopin** [comment]
Given the positive feedbacks, I'm going to work on this if it's okay for everyone :) .

**Comment by fabpot** [comment]
Thanks @tgalopin :)

**Comment by nicolas-grekas** [comment]
@unkind example updated to showcase keyed values. Also, "lazy-collection" renamed to "lazy".

**Comment by unkind** [comment]
> @unkind example updated to showcase keyed values. Also, "lazy-collection" renamed to "lazy".

Not sure if it is what I mean.
I don't want to iterate the map (well, in general).
I want to get service by some key (it might be serviceId, might be not).
Real-life example: command bus, each command has one (and only one) command handler:

```php
final class MappedCommandBus
{
    public function handle(Command $command): void
    {
        Assertion::true(isset($this->commandHandlerMap[get_class($command)]));
        $this->commandHandlerMap[get_class($command)]->handle($command);
    }
}
```

I'd expect something like 
```php
protected function getCommandHandlerMapService()
{
    return new CommandHandlerMap(function ($key) {
        static $map = [
            'Acme\Foo\Commands\RegisterFoo' => 'register_foo_handler',
            'Acme\Foo\Commands\PayBar' => 'pay_bar_handler',
        ];

        if (isset($map[$key])) {
            return $this->get($map[$key]);
        }

        return null;
    });
}
```

**Comment by nicolas-grekas** [comment]
@unkind you're asking for #20658 (but please don't hijack this thread)

**Comment by Federkun** [comment]
> Also, "lazy-collection" renamed to "lazy".

I'd like " generator" better.

**Comment by Koc** [comment]
@nicolas-grekas am I right that constructor's typehints must be changed from `array` to `iterable`?

**Comment by nicolas-grekas** [comment]
@Koc in order to leverage this new data structure yes

**Comment by nicolas-grekas** [comment]
@Federkun "generator" is an implementation detail for what is really an "iterator". Which makes we think now that this vocabulary could be better! Example updated to use type="iterator" instead of type="lazy".

**Comment by vasi** [comment]
This looks interesting!

* In addition to the lazy instantiation, there's another reason Drupal uses its own EventDispatcher: it's apparently much faster to store an array of service information in the container, rather than calling `addEventSubscriber()` for each subscriber after initializing the dispatcher. [Some benchmarks](https://www.drupal.org/node/1972300#comment-9216069). Is that intended to be resolved by #20953?
* We're not going to actually use generators for this, right? I don't think generators are rewind-able, so if an event is issued multiple times we'd have trouble. A LazyServiceCollection class that implements Iterator, including rewind, would be necessary.
* To bikeshed a little, I prefer "lazy" to "iterator". "Iterator" doesn't necessarily indicate laziness.

**Comment by tgalopin** [comment]
@vasi 

> We're not going to actually use generators for this, right? I don't think generators are rewind-able, so if an event is issued multiple times we'd have trouble. A LazyServiceCollection class that implements Iterator, including rewind, would be necessary.

We did implement a RewindableGenerator class in this PR. However you are probably right about the fact that we won't use this PR in the EventDispatcher in favor of a more suited approach.

> To bikeshed a little, I prefer "lazy" to "iterator". "Iterator" doesn't necessarily indicate laziness.

The lazyness is actually not really the core concept of this PR, it's more the fact that it gives the possibility to easily create a generator from your configuration, meaning you get lazyness but also better memory management.

**Comment by nicolas-grekas** [comment]
@vase thanks for the input! #20907 is now implementing this RFC. As you'll see, it embeds a solution for the rewindability issue. About the name, I think we're going to stick to "iterator", sorry it's not your preference :)

> it's apparently much faster to store an array of service information in the container, rather than calling addEventSubscriber()

#20953 should be solving this yes, but not via constructor injection. I think most of the perf gain you observed comes from what `addEventSubscriber` does (autoloading the class + iterating over array of events to register). Doing this job at compile time instead turns it into calls to `addEventListener`, which by looking at the source, is a trivial array insertion.

Doing the injection in one operation via the constructor might be faster, but I doubt it would be substantial. The big benefit is that it doesn't require any change to the existing EventDispatcher class. Did your benchmark experiment with this situation?

**Comment by unkind** [comment]
> The big benefit is that it doesn't require any change to the existing EventDispatcher class

Can you explain the reason behind it? If it is about BC, how it breaks it?

**Comment by tgalopin** [comment]
@unkind From what I remember, I think the problem was about the possibility in the EventDispatcherInterface to remove listeners, which can be a problem in some cases.
