### ISSUE TITLE
[BC BREAK] Symfony's dev-dependency depends on PHP 7.1.

### ISSUE THREAD

**Issue by naroga** [symfony/symfony#20942]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.1

Symfony 3.2 requires in its `require-dev` section in `composer.json` the library `ocramius/proxy-manager`. It constrains the versions to `"~0.4|~1.0|~2.0"`, which makes `2.1` an acceptable (and currently the selected) version. However, version 2.4 only works with PHP 7.1, which breaks CI servers everywhere for people running apps that use Symfony 3.2 with php:7.0 containers.

Just remembering that one is supposed to install `dev` dependencies on a CI server, in order to run phpcs/phpunit/etc.

**Comment by naroga** [comment]
The error:

```$ php composer.phar install --no-scripts
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ocramius/proxy-manager 2.1.0 -> satisfiable by ocramius/proxy-manager[2.1.0].
    - ocramius/proxy-manager 2.1.0 requires php ^7.1.0 -> your PHP version (7.0.14) does not satisfy that requirement.

ERROR: Build failed: exit code 1```

**Comment by stof** [comment]
@naroga it makes 2.4 an acceptable version **if** it is also acceptable for other constraints. And these other constraints will include the PHP one.

If you run ``composer update`` on PHP 7.0, the 2.4 version of the package will **not** be installed by Composer.

Running composer on PHP 7.1 will not make your lock file compatible with PHP 7.0 by default. If you want to be compatible with a different version than the current PHP version, you have to use ``config.platform`` to configure composer.

Thus, the dev requirements of Symfony have **no** influence on your own CI setup, because dev requirements are a root-only settings, and so they are only meaningful when working on symfony itself.

So there is no BC break at all. you just need to learn about how composer works (and yes, if you use ``--ignore-platform-reqs``, you will get packages which may not be compatible with your PHP platforms, but you asked composer about it)
