### ISSUE TITLE
choice_attr doesn't set id attribute

### ISSUE THREAD

**Issue by alvinbunk** [symfony/symfony#20965]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.7

I've already posted [this question](http://stackoverflow.com/questions/41174777/any-reason-why-the-choice-attr-in-symfony3-choicetype-cant-set-the-id-attribute) on stackoverflow asking for help.

The issue is for a Field Type of ChoiceType, [documentation says that choice_attr](https://symfony.com/doc/current/reference/forms/types/choice.html#choice-attr) can be used to set an id attribute in a callable function, but it doesn't work for 'id' but instead works for 'class' and 'data-id'; but I really need it to work as documented, and that means any attribute.

At least if the 'choice_attr' is known not to work with 'id', it should be documented.

Example code to reproduce the problem is shown below:

```php
->add('deg_certs', ChoiceType::class, array(
        'mapped' => false,
        'expanded' => true,
        'multiple' => true,
        'label' => 'Degrees/Certificates received:',
        'choices' => array(
                'BA/BS' => 'ba_bs',
                'AA/AS' => 'aa_as',
                'Voc. Cert.' => 'voc_cert',
                'Other' => 'other',
        ),
        'choice_attr' => function($val){
            return ['id' => $val];
        },
))
```

But setting to 'data-id' works:

```
'choice_attr' => function($val){
    return ['data-id' => $val];
},
```

**Comment by stof** [comment]
This is because Symfony generates ids for form types it renders, so trying to set an id explicitly will indeed not work

**Comment by alvinbunk** [comment]
And is it possible to change that functionality? If so, what files might I look into?

**Comment by HeahDude** [comment]
@alvinbunk You can override the `$view->vars['id']` of your form using the methods `buildView()` or `finishView()` of its type since this is where it is generated https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/BaseType.php#L86, or you can override a form template and compute the id there.

But as said @stof this is expected and unlikely to change in the core as that would also be a huge BC break to not generate it anymore.

Hence this is expected with the `attr` option too. I've commented [this issue] so we don't forget to add a note in the docs about that.

I think we can close here.

**Comment by ogizanagi** [comment]
But is there anything preventing us to replace the generated id if `$options['attr']['id']` is provided?

**Comment by HeahDude** [comment]
@ogizanagi Nothing, but because of the issue I've linked, it is safer IMHO to implement one of the solutions I've suggested instead of defining attributes using the `attr` option as defining one can override some others (think of `attr` option defined both in a type and in a controller). Btw, it would not be enough to allow it with `choice_attr`.

I think we should encourage acting at the view level for this.

**Comment by ogizanagi** [comment]
Agreed.

(Psst: I think you missed the link when trying to actually link the issue 😅)

**Comment by jakzal** [comment]
Shall we close this and #24044, since most of us agree it's too risky to change and workarounds exist?

**Comment by HeahDude** [comment]
:+1: for closing.
