### ISSUE TITLE
[RFC] Simple form mapping via data objects

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#20976]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.0

This RFC consists of two parts, mapping forms from a data object, and the part that's required to do so; metadata that holds the information.

### Simple Form Mapping
The most common 'complaint' that I hear, is that Symfony Forms are kinda complex and overkill for the smaller and more simple forms (next to "they change every version; *1.0~1.4* 😉). I've been thinking about a way to make it easier and less overhead, but that's really hard to do if you have to write a form type.

I personally _always_ use DTOs for forms for many reasons, but one of the most important ones, is that it contains validation rules and the fact that it's not an array *(yay!)*. I would like to propose instead of omitting the data object and use an array, the ability to map forms from a data object. While this would be useless for the more complex cases, pretty much all static forms can be written this way.

When using this method, you would have your validation + form mapping in 1 place rather than validation spread between the Type and data object.

Here's an example of what I've been brainfarting about *(public just for display purposes here)*:
```php
<?php
namespace App\Form;

use Symfony\Component\Form\Mapping as Form;
use Symfony\Component\Validator\Constraints as Assert;

final class PosterData
{
    /**
     * @Form\Type()
     *
     * @Assert\Valid()
     *
     * @var AuthorData
     */
    public $author;

    /**
     * @Form\DateTimeType({"invalid_message": "Invalid datetime given."})
     *
     * @Assert\DateTime()
     *
     * @var \DateTime
     */
    public $publishAt;
}

```
```php
<?php
namespace App\Form;

use Symfony\Component\Form\Mapping as Form;
use Symfony\Component\Validator\Constraints as Assert;

final class AuthorData
{
    /**
     * @Form\TextType()
     *
     * @Assert\Regex("/[a-z]+/")
     *
     * @var string
     */
    public $name;

    /**
     * @Form\EmailType()
     *
     * @Assert\Email()
     *
     * @var string
     */
    public $email;
}
```
This annotation based API would provide 2 things:
 - An annotation class to extend (`Form\Type`)
 - An implemented version for each type in the Core.

### Form\Type
This class acts as guesser in case nothing is passed along. The first argument would be optional and could be the FQCN of the form type to be used. This class can also be extended to provide a ready-to-use shortcut.
```php
/**
 * Guesses the type based on the data object received, only works for data
 * without type. This data should be compiled or cached away to save run-time
 * performance.
 *
 * @Form\Type() 
 */

/**
 * Pretty much equivalent to $builder->add('current_prop', CustomType::class, [])
 *
 * @Form\Type("App\Form\CustomType", options={})
 */

/**
 * A custom annotation implementation, this would allow easy configuration of the type.
 *
 * @Form\DateTimeType({"invalid_message": "Invalid datetime given."})
 */
```

Creating a form should be simple:
```php
// form factory
$formFactory->create(MappedType::class, $dataObject, $options = []);
$formFactory->createMapped($dataObject, $options = []);

// base controller
$this->createMappedForm($dataObject, $options = []);
```

### Storing This Information
A caching system could be created where the metadata of this form is stored, the forms would still have to be build after all. This caching system should make it possible to create by either reading config files or annotations from the data objects. While this can be created after the actual feature, it provides something else: Database/Yaml forms. This would provide an extension point for CMS systems to generate forms based on what is configured from (e.g.) an interface.

What do you think?

**Comment by HeahDude** [comment]
First, thank you for sharing your thought on this :)

I think this idea is good, but one problem I have with annotations it that there is too much of them in my entities... We use them for so many things already: doctrine (and extra doctrine stuff), validation, serialization, and some bundles also provide more of them.

Also annotations for forms as you suggest could become noisy really fast, and this does not easily cover the need for resolving options, the view or listeners, that means we would need to let the object implements some specific methods to support this (as we do for validation where this can make more sense IMHO).

So this adds a lot of complexity to the domain object (not only entities, even VO which I consider as domain object and use with validation annotations) and this also adds a lot of complexity and code in the core, not even talking about the caching logic, all to avoid creating a form type :(.
_____
⚠️  **Spoilers Alert** ⚠️
But this remind me an email I wrote to Fabien in September when he started working on FrameworkExtraBundle 4.0, and I did on the GeneratorBundle 4.0. I've not shared these things for now, so here's some parts of it.

What I was thinking is to use some annotations in controllers to add some metadata given to an argument resolver that handles a `Form` instance, something like:
```php
// src/Controller/PostController.php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Form;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

// ...

/**
 * @Route("/post/create", name="post_create")
 * @Form(type="AppBundle\Form\Type\PostType")
 */
public function createPost(Form $form)
{
    // handling request is done by the resolver
    if ($form->isSubmitted() && $form->isValid()) {
        // An instance is returned thanks to the option "data_class" defined in the type
        $post = $form->getData();

        $em = $this->getDoctrine()->getManagerForClass(Post::class);
        $em->persist($post);
        $em->flush($post)

        return $this->redirectToRoute('post_index');
    }

    return $this->render('@App/Post/create.html.twig', array(
        'form' => $form->createView(),
    ));
}
```
We could even handle the persistence part with a `flush` option, a `data` option to match an argument, and why not a `redirect` option that takes a route name.

We could also use a form type guesser and a default `FormType` as root with an option `data-class` passed in the annotation.

This could look like:
```php
/**
 * @Route("/post/{id}/edit", name="post_edit", requirements={"id": )
 * @Form(type="App\Form\Type\PostType", data="post")
 */
public function createPost(Form $form, Post $post)
{
    if ($form->isSubmitted()) {
        if ($form->isValid()) {
            $this->addFlash('success', 'The post has been updated');

            return $this->redirectToRoute('post_index');
        }

        // Custom handling of some error(s)
        // see https://github.com/symfony/symfony/pull/19496
    }

    return $this->render('@App/Post/edit.html.twig', array(
        'form' => $form->createView(),
    ));
}
```

To go even further the last return could be replaced by a `@Template` notation, and an option like `view-var` as `form` by default.

An `options` option could be used to tag services:
`@Form(type="App/Form/Type/MyEntityType", options={"factory": "@my_entity_factory"})`.

A `submit` option defaulted to `true` could be turned off to keep adding fields (i.e some specific buttons, even if I think this should happen in templates) in the controller before handling the request.

I'd really like to remove some logic used again and again in controllers, rather than adding more metadata to my entities to generate some form types.

I know one could argue that what I've said above about annotations in entity could also be true for controllers, but in most cases default options should do it and the simple fact to type hint `Form` in the controller action can do the job.

Although, what I've just shared is just a thought I had about something concerning the FrameworkExtra, not the core, the next version of `generate:form` should also be cool enough to generate form types even more quickly and easily and that's an old WIP coming really soon ;).

_____
My answer to the RFC is more about a 👎 for now, but if others support it I would be opened (and curious) about any PR trying to implement that :)

**Comment by iltar** [comment]
I understand your points, but would like to comment on them

> I think this idea is good, but one problem I have with annotations it that there is too much of them in my entities

I don't have more than `@ORM\*` and [`@AG\Generate`](https://packagist.org/packages/hostnet/accessor-generator-plugin-lib). [I believe you should _never ever_ bind entities to forms](stovepipe.systems/post/avoiding-entities-in-forms), the data transfer objects (_not_ value objects) are the ones in an invalid state, hence the validation annotations.

The only task these objects have is to get the information from the request to the point where you use them (often enough enters a command bus).

> We use them for so many things already: doctrine (and extra doctrine stuff), validation, serialization, and some bundles also provide more of them.

Annotations are multi-purpose, but the responsibility of this object is not. I don't think you should be putting serialization annotations on the DTOs for forms, the form already uses its own (un)serializer.

```php
/**
 * @Form(type="App\Form\Type\PostType", data="post")
 */
```
Something like this is a nice idea, but I'm using [FormHandlers](https://github.com/hostnet/form-handler-bundle), so I will not use it like this. My proposed solution will work for the form component as stand alone.

> I'd really like to remove some logic used again and again in controllers, rather than adding more metadata to my entities to generate some form types.

I'm all for thin controllers, which is why we created the form handler package (though not perfect). It's not metadata in entities if you use data objects so this should not be a problem for people using entities.  This solution would not work either way because people bind their entities to multiple forms (which causes complex validation group issues).

**Comment by HeahDude** [comment]
I agree that my proposition is totally off topic here, but was just another suggestion about annotations and forms.

But your examples are about defining types for properties which is already solved by guessers. The three properties could have the same treatment with `$form->add('name', null, $options)`.

And custom guessers are a really powerful way to handle specific resolution of types and options depending on the underlying entity.

**Comment by iltar** [comment]
But they will not work for nested types as I understood. Also, I would rather not guess basic types to form types, I do want to explicitly declare them

*Your proposition is interesting though ;)*

**Comment by HeahDude** [comment]
>But they will not work for nested types as I understood

What do you mean? The guessers registered by default in full stack do not know about custom types and that's where custom guessers are also useful.

**Comment by iltar** [comment]
@HeahDude mainly talking about this `PosterData::$author`, which is an instance of `AuthorData`. The Guess doesn't know what to do with this by default afaik. Besides of that, I don't want to rely on this kind of guessing, because if this logic changes or is bugged, I might end up with another form without knowing that. As long as resolving is pretty much like "oh that data object should get that form type!", I'm good.

**Comment by HeahDude** [comment]
>The Guess doesn't know what to do with this by default afaik. Besides of that, I don't want to rely on this kind of guessing, because if this logic changes or is bugged, I might end up with another form without knowing that. As long as resolving is pretty much like "oh that data object should get that form type!", I'm good.

This is exactly what the guesser is about, you would have to implement:
```php
public function guessType($class, $property)
```

Where `PosterData::class  === $class` and `'author' === $property`, and if the logic change that's also a problem for generated cache from annotations.

**Comment by stof** [comment]
@HeahDude @iltar I think you should start an experiment about this outside the core. This feature can totally be implemented in a third-party bundle. This would allow gathering real feedback on it before including it in the core (and so before having to maintain it for years even if it ends up being a bad idea).
This is what @weaverryan did with the Guard system for instance.

**Comment by iltar** [comment]
I think that's a good idea actually

**Comment by iltar** [comment]
Closing this as I won't have time in the near future to work on this.
