### ISSUE TITLE
[DI][Proposal] Support anonymous classes in service definition

### ISSUE THREAD

**Issue by skafandri** [symfony/symfony#20997]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | master

I don't know if this actually makes sense as a way to make defining services easier. The idea is to be able to define a service **only** in a config. Without the need to define a class.

Example in yml:
````yml
var_dump_logger: >
        new class extends \Psr\Log\AbstractLogger {
        
            public function log($level, $message, array $context = array())
            {
                var_dump(['level' => $level, 'message' => $message, 'context' => $context]);
            }
        };
````

I don't think is a good way to define services, rather a quick way to *play around* with the DI component.

**Comment by javiereguiluz** [comment]
@skafandri I'm afraid this won't happen. In the past, we allowed to execute PHP code inside YAML files. But then we deprecated it and in it's no longer possible to do that. This proposal is similar because it mixes PHP code and YAML markup, so it's not something desired. Because of this, I'm 👎 for this proposal.

**Comment by ro0NL** [comment]
@skafandri see #20973.. it's basically happening.. sort of :)

**Comment by skafandri** [comment]
I knew is not a good idea :)
