### ISSUE TITLE
[CssSelector] Constructions like "//*[name() = 'div']" not working in Firefox

### ISSUE THREAD

**Issue by BR0kEN-** [symfony/symfony#21004]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

Firefox on `macOS` up to latest (`51` for now) version does not support expressions like `//*[name() = 'div']`. I've faced this using Selenium 2 WebDriver.

![firefox-xpath](https://cloud.githubusercontent.com/assets/2760616/21378537/841bc698-c760-11e6-9950-7c3f2297bcd1.png)

Which was the reason to use `//*[name() = 'div']` instead of `//div`?

**Comment by BR0kEN-** [comment]
For instance, `//*[local-name() = 'div']` will be working.

**Comment by tomgibson** [comment]
Running FF 50.0.2 and Ubuntu 16.10.
`//*[name() = 'div']` does not seem to be supported.

![screenshot from 2016-12-21 17-03-32](https://cloud.githubusercontent.com/assets/12995237/21379138/b5bcf502-c79f-11e6-8dc3-5e439c14ad3a.png)

**Comment by BR0kEN-** [comment]
Also, this material could be helpful: http://stackoverflow.com/a/2464906

**Comment by BR0kEN-** [comment]
So, the difference between `name()` and `local-name()` XPath functions breaks workability in Firefox.

My final questions are:

- Why used `//*[name() = 'div']` instead of `//div`?
- Can we replace `name()` by `local-name()` as I did in PR?

**Comment by PavelLoparev** [comment]
FF 37, ubuntu 15.04. Looks like `//*[name() = 'div']` is not supported.
http://screencloud.net/v/wJ82

**Comment by fabpot** [comment]
Closing as there is nothing we can do on our side.

**Comment by phil-s** [comment]
@fabpot: Can this be re-evaluated?

I can see from https://github.com/symfony/symfony/pull/21011 that switching to `local-name()` was rejected because dropping the name-space was not acceptable.

It seems to me that changing from `//*[name() = 'foo']` to `//foo` would resolve the problem, however?

E.g. When selecting a table row, I find that Chromium only matches `//*[name() = 'tr']` and Firefox only matches `//*[name() = 'TR']`, but both browsers match both  `//tr` *and* `//TR`.  So the latter syntax does not appear to be case-sensitive, which seems to circumvent the problem.

**Comment by phil-s** [comment]
Or, simpler, change `name()` to:  
`translate(name(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')`  
in order to obtain a lower-case value.

That only supports the basic ascii letters, but it seems that `lower-case()` is not a thing in XPath 1, and this approach would presumably be a good improvement over the current support.  I can see something similar going on in `translateLang()` in `css-selector/XPath/Extension/HtmlExtension.php`, so maybe this character set limitation is already accepted.

**Comment by stof** [comment]
Please open a new issue instead of commenting on an issue closed since 2018 (which won't be seen by people not reading all notifications for the repo)
