### ISSUE TITLE
How to resolve ICU version requirements in Symfony 3 on CentOs? 

### ISSUE THREAD

**Issue by samayo** [symfony/symfony#21049]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.0.0

I have installed Symfony version 3, which requires ICU version 57.1 However, my CentOs 7.3 machine does not come with ICU by default. But, `yum install libicu` provides only version 50.1 

This means, I either need to compile new ICU release from binary, or somehow downgrade Symfony3 requirements for ICU. I tried the first, which did not work.. I am hopping if I can downgrade S3 requirements by any means.

**Comment by mvrhov** [comment]
It seems that most linux distributions manage the ICU as another library which is clearly wrong. The data in ICU is dynamic and changes over the course of time. IMO, the most distributions should begin to manage the ICU like they manage timezone data.

**Comment by javiereguiluz** [comment]
I see that you asked the same in the CentOS forums and you didn't get a clear answer: https://www.centos.org/forums/viewtopic.php?t=60684

In any case, please keep in mind that this is just a recommendation, so you can run Symfony apps without any problems even if you have an outdated ICU library. Moreover, my guess is that if your app uses a common language, you probably won't get any significant difference between those versions.

Let's close this for now as "won't fix" because we can't downgrade Symfony requirements and hopefully you'll upgrade the ICU library in your server somehow. Thanks for understanding it.
