### ISSUE TITLE
[TwigBridge] String concatenation and trans filter

### ISSUE THREAD

**Issue by jacoz** [symfony/symfony#21229]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7.22

Hi,
having something like `{{ "my.message." ~ someVar|trans }}` or `{{ ("my.message." ~ someVar)|trans }}` the translation fails because the engine doesn't seem to be able to parse the concatenation.

**Comment by stof** [comment]
> because the engine doesn't seem to be able to parse the concatenation.

I don't understand what you mean here

**Comment by jacoz** [comment]
@stof having this scenario:
```
{% set myVar = "foo" %}
{{ "my.message." ~ someVar|trans }}
```

I'm expecting that the `trans` filter would have as first argument the evaluated string: `my.message.foo`, but it doesn't, it actually is `my.message.someVar`

**Comment by stof** [comment]
OK, is it your real code ? If no, please paste the extract of your real code, to let us spot silly typos in it. There is no reason to get ``my.message.someVar`` in your case here

**Comment by fancyweb** [comment]
@jacoz I don't think this is a bug.
You either have to use the `format` filter ``{{ 'my.message.%s'|format(someVar)|trans }}` or brackets `{{ ('my.message' ~ someVar)|trans }}`

**Comment by behram** [comment]
probably you can use twig `attribute` function.

Related link;
 - http://twig.sensiolabs.org/doc/2.x/functions/attribute.html

**Comment by xabbuh** [comment]
@jacoz Can you please provide the information @stof asked for? Otherwise we cannot really help you.

**Comment by jakzal** [comment]
This is an expected behaviour. See twig's operator precedence: http://twig.sensiolabs.org/doc/2.x/templates.html#expressions

`{{ "my.message." ~ someVar|trans }}` will translate someVar and append it to "my.message."

`{{ ("my.message." ~ someVar)|trans }}` will concatenate "my.message." with someVar and translate the result.

I just confirmed this behaviour. If I misunderstood your problem, please provide code that would reproduce the issue (i.e. a fork of the Symfony standard edition).
