### ISSUE TITLE
Any chance to separate the Symfony Debug Bar as a component?

### ISSUE THREAD

**Issue by reypm** [symfony/symfony#21236]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | N/A

I have been working with Symfony for a while and I should say is the best PHP framework I have ever tried. This days there are a few more out there: Laravel, Zend Framework, Yii and of course vanilla PHP applications - yes they exists nowadays. 

The Symfony Debug Bar is one of my best friends during development and it helps a lot since you don't need to go to logs or use dumping functions in order to know what's happening with your application.

I did know there is some small attempts out there like [PHP Debug Bar][1] and Laravel has it's own (I believe so) so my question would be: is there any chance where Symfony team release Debug Bar as a separate standalone component so it can be used anywhere? 

  [1]: http://phpdebugbar.com/

**Comment by stof** [comment]
the Symfony Profiler is currently strongly coupled to HttpFoundation (and requires a bunch of manual work if you don't use HttpKernel, to reintegrate it with a different kernel system). So it is not usable for any project using another library for HTTP requests and responses.
changing this requires rewriting the component entirely (and would probably be a migration nightmare due to the current architecture).

However, if you already use HttpFoundation and HttpKernel, the system is totally usable (Silex uses it for instance). WebProfilerBundle (which provides the UI for the profiler) does not depend on the framework, only on some components.

**Comment by reypm** [comment]
@stof currently I am using ZF1 (yes EOL and so on but is what the company I work for use so ....) and I don't have a clue to use such components on top of it I don't even if it's possible since ZF1 seems to be lazy in some aspects.

**Comment by javiereguiluz** [comment]
@reypm I'm not sure this will happen anytime soon. This component can only work well with a Symfony-based project (Symfony or Silex) because every panel is tightly integrated with Symfony features. For your specific case, you should consider using [Z-Ray](http://www.zend.com/en/products/server/z-ray) instead.

**Comment by reypm** [comment]
thx @javiereguiluz I will give this a try (tried before but couldn't get it to work properly will try again though) I am not sure to leave this issue open looking for other answers, what do you think, should I close it or keep it open for a while?

**Comment by stof** [comment]
ZF1 is definitely not based on the Symfony 2+ components (which were written years *after* ZF1). So you cannot get the Symfony Profiler system for now.

@reypm I'm closing this issue, because we already have another issue about decoupling the profiler from HttpFoundation (and splitting the component is not worth the effort before that IMO. No need to rename classes twice)
