### ISSUE TITLE
Swiftmailer CVE-2016-10074

### ISSUE THREAD

**Issue by javsalgar** [symfony/symfony#21252]
On 25.12.2016 a security issue (CVE-2016-10074) was found in the Swiftmailer component for versions lower than 5.4.5. Is symfony affected by this issue?

More info: http://pwnscriptum.com/

**Comment by stof** [comment]
Symfony is not affected, because it does not contain the swiftmailer source code, and does not use swiftmailer.

Projects using both Symfony and Swiftmailer may be affected. But the fix is simple: they should upgrade the swiftmailer version they use (and the ``security:check`` command already knows about this CVE to warn them)

**Comment by sstok** [comment]
If you want to be sure to never accidentally install a vulnerable version you can install the
https://github.com/Roave/SecurityAdvisories composer meta-package which uses the security-advisories database.

Note in the case of Swiftmailer it may actually break Composer depending on the constraints of defined dependencies, that actually indicates a much bigger problem for those packages.
