### ISSUE TITLE
BUG: KNP Menu: Unable to find template "knp_menu.html.twig"

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony#21281]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | 2.8.16

The error appeared after upgrading composer that upgraded Symfony to version 2.8.16.
Falling back to Symfony 2.8.15 "solves" the error.

What have I to do?

[I opened this same issue on the KNP Menu repository, too.](https://github.com/KnpLabs/KnpMenu/issues/252)

**Comment by xabbuh** [comment]
Can you fork the Symfony Standard Edition and make the changes that are necessary to reproduce your issue?

**Comment by umulmrum** [comment]
I can confirm the problem for Symfony 3.2.2 - "solved" after downgrading symfony/symfony to 3.2.1

**Comment by xabbuh** [comment]
@umulmrum Can you describe which steps we need to do to reproduce your issue?

**Comment by umulmrum** [comment]
@xabbuh I haven't managed yet to reproduce the issue with a fork of the standard edition. 
What's a bit strange is the error message:

"Unable to find template "knp_menu.html.twig" (looked into: [my document root]/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form) in AppBundle::menu.html.twig at line 1."

Looks like only the form directory is considered, but I have no clue why. Possibly this problem is related to https://github.com/symfony/symfony/pull/19586

**Comment by umulmrum** [comment]
@xabbbuh OK, it was actually quite easy to reproduce.

Just follow the instructions in the KnpMenuBundle docs to add a menu in the most simple way, and additionally set another menu template in config.yml. But what is important: The error only occurs if the KnpMenuBundle is registered AFTER the TwigBundle in AppKernel. I tend to sort things alphabetically instead of appending at the end, but didn't do this first when trying to reproduce.

I pushed the failing app state to https://github.com/umulmrum/symfony-standard/tree/3.2

**Comment by xabbuh** [comment]
@umulmrum Thank you for your great effort to provide the failing example. It helped me a lot to reproduce your issue and work on a fix.

@Aerendir @umulmrum Could you both please check if #21285 fixes your issue?

**Comment by umulmrum** [comment]
@xabbuh I merged 2.7 into 3.2 locally and the problem is gone. Thanks for the really quick fix!
