### ISSUE TITLE
[TwigBundle] [Form] Problem with twig warmer and form templates

### ISSUE THREAD

**Issue by twoleds** [symfony/symfony#21322]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.*

Twig warmer doesn't warm up templates for the form component. We use read-only file system on production and we have problem with the missing templates.

The form templates are in non-standard path: `src/Symfony/Bridge/Twig/Resources/views/Form`
```
bootstrap_3_horizontal_layout.html.twig
bootstrap_3_layout.html.twig
form_div_layout.html.twig
form_table_layout.html.twig
foundation_5_layout.html.twig
```

I try fix it somehow but I need some code review or discussion about it: https://github.com/symfony/symfony/compare/master...twoleds:twig-form-warming

**Comment by xabbuh** [comment]
Couldn't we do that [in the extension](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L92)? And shouldn't we also add the paths discovered from other bundles here too?

**Comment by twoleds** [comment]
I tried to do that in the extension and it works, but I want to keep warming the templates only if the `form.extension` is enabled and I cannot check it in the extension because the service isn't available there. But if it isn't big problem with warming the templates when the extension is disabled, we can do it in the extension.

**Comment by yceruto** [comment]
After compilation absolutely all template paths are defined in `Twig\Loader\FilesystemLoader::$paths` through `twig.loader.native_filesystem` service, including bundle paths, form theme paths, default project paths, custom project paths, etc.

My point is, shouldn't it be better iterate over the Twig loader paths instead of hardcoding again all possible paths here? (see https://github.com/symfony/symfony/pull/27764 where the new default path has been forgotten)
https://github.com/symfony/symfony/blob/ea0b508c8ee448acdd95d6ae6e261c8b0f292913/src/Symfony/Bundle/TwigBundle/TemplateIterator.php#L50-L66

Specifically, this is what I'm talking about:
```php
// ...

$loader = $this->twig->getLoader();
if (!$loader instanceof FilesystemLoader) {
    return;
}

foreach ($loader->getNamespaces() as $namespace) {
    foreach ($loader->getPaths($namespace) as $paths) {
        foreach ($paths as $path) {
            $this->templates = array_merge($this->templates, $this->findTemplatesInDirectory($path));
        }
    }
}

// ...
```
so we don't have to keep this dependency (`$paths`) updated everywhere:
https://github.com/symfony/symfony/blob/ea0b508c8ee448acdd95d6ae6e261c8b0f292913/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L87-L88
https://github.com/symfony/symfony/blob/cccb66f4c6aef7f5a08d622df4277f7c884b667f/src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/ExtensionPass.php#L50-L53

WDYT?

**Comment by twoleds** [comment]
@yceruto I forgot about this issue, thanks for reminding me. I think refactoring is not subject of this bug issue. You should create a new one. 
@yceruto The issue with the form templates is they aren't part of any bundle, they are in bridge package for twig and the iterator doesn't include these paths. The second issue is the templates are part of bridge package for twig and the templates use functions & filters from the form component of symfony. The form component is optional and if the component is not installed then compilation of the templates will fail. The templates should be compiled only in case if the form component is installed & enabled.

**Comment by twoleds** [comment]
I check this bug again and @weaverryan fixed it in the commit https://github.com/symfony/symfony/commit/2ef619f9bb4a38394b5e3716b3febec9499c6425, thanks for fix
