### ISSUE TITLE
Non-blocking external processes using Process Component

### ISSUE THREAD

**Issue by undercloud** [symfony/symfony#21340]
Hi! Just little question:)
Can I create non-blocking process  using https://symfony.com/doc/current/components/process.html
I need something like this
http://stackoverflow.com/questions/1019867/is-there-a-way-to-use-shell-exec-without-waiting-for-the-command-to-complete
Or I need to specify options for  each platform e.g ``` /dev/null 2>/dev/null & ```?

**Comment by stof** [comment]
You can start a process without blocking the main process using ``$process->start()``. But you cannot make the process outlive the PHP process (unless maybe using ``/dev/null 2>/dev/null &`` but I'm not sure it works fine).

When pcntl is available (which is never the case on windows), there is a trick to do this by forking the PHP process, so that the main PHP process can stop, and the forked process can keep the Process object alive. See the implementation of ``server:start`` for instance.

**Comment by stof** [comment]
btw, forking the process with pcntl as done in server:start is probably a very bad idea in non-CLI processes.

**Comment by undercloud** [comment]
In my case, I use CLI
