### ISSUE TITLE
[FrameworkBundle] Execute the PhpDocExtractor earlier

### ISSUE THREAD

**Issue by GuilhemN** [symfony/symfony#21367]
| Q                | A
| ---------------- | -----
| Bug report?      | yes, kind of
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8 -> master

I wonder if this is logical to execute [the `PhpDocExtractor` after the `ReflectionExtractor`](https://github.com/symfony/symfony/blob/c2a6ddc0ea13cecc1d6b3ea2c167c199b7fdcd48/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1287): when you use phpdocs it's because they are more precise than php type hints.
This causes an issue in [NelmioApiDocBundle](https://github.com/nelmio/NelmioApiDocBundle/issues/950), for example you can't use `int[]` with a setter as the type `mixed[]` will be returned instead of `int[]`.

Would you accept bumping its priority to `-999`?

cc @dunglas

**Comment by ogizanagi** [comment]
👍 I agree it's more logical and the order I personally rely on in my own projects. This is also the order described on the documentation page: http://symfony.com/doc/current/components/property_info.html

**Comment by GuilhemN** [comment]
Apparently the `DoctrineExtractor` already has a priority of `-999`, so I'd say it's safer to change the priority of the `ReflectionExtractor` to `-1002` or lower.

**Comment by dunglas** [comment]
It was done on purpose because parsing PHPDoc is extremely slow. On the other hand using reflection is fast.
But we can reconsider it.

**Comment by GuilhemN** [comment]
see https://github.com/symfony/symfony/pull/21370

**Comment by magarzon** [comment]
And if you could choose the priority/order and/or enable/disable each extractor in the FrameworkBundle configuration, it'd be a blast.

My use case: I make calls to an API and deserialize the response into model objects using the Serializer (and PropertyInfo component). So I don't need DoctrineExtractor at all, but it's instantiated and added as first option anyway.

Second issue: I have a class with a boolean field "active" and its accesor "isActive", but the response from the API is 0 or 1. The ReflectionExtractor only try to get the type using ReflectionMethod::getReturnType if you use PHP 7.x, but I'm using PHP 5.7, so it fallbacks to check if the accesor starts with "is" to decide that it's a boolean, and I get and exception (because is_bool(1) returns false). With the PhpDocExtractor I could use int|bool as expected types.

Yes, I can change the name of the accesor to getActive, but I'd prefer if I could decide which extractors use

**Comment by GuilhemN** [comment]
@magarzon you can remove the extractors you don't need using `$container->removeDefinition('the_extractor_i_dont_want')`.

**Comment by teohhanhui** [comment]
This has caused BC break in my app. :disappointed:

**Comment by xabbuh** [comment]
@teohhanhui Please open a new issue describing the BC break you experience. Here your comment will likely get lost.

**Comment by faizanakram99** [comment]
> [@magarzon](https://github.com/magarzon) you can remove the extractors you don't need using `$container->removeDefinition('the_extractor_i_dont_want')`.

it doesn't work, without doctrine extractor, property info breaks, it somehow still references it.
