### ISSUE TITLE
[WebServerBundle] Potential BC break as FrameworkBundle doesn't register this bundle?

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony#21373]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3-dev

As of https://github.com/symfony/symfony/pull/21039 , the `server:*` commands are moved to a new bundle. This is all nice and such, but it also is kind of a BC break: All applications updating to Symfony 3.3 will have to make sure they register `WebServerBundle` as well in order to use the server commands. This broke some CMF test jobs against dev versions, as the `server:*` command was no longer available.

Is this considered a BC break?

**Comment by chalasr** [comment]
#21039 clearly states that it contains BC breaks so I guess it has been accepted.
I think the upgrade file should mention it though

**Comment by sh4ka** [comment]
What about an 'easypick' for the docs?

**Comment by javiereguiluz** [comment]
The docs would be a solution ... but most people don't read docs, so they'll execute the same command as before ... and now they'll get an exception.

Just asking: instead of creating a full BC layer, etc. what if we add a simple listener for `ConsoleEvents::EXCEPTION` and we check if the user executed a `server:*` command and then we display a clear error message:

*"Starting from Symfony 3.3, these command has been moved to a new bundle called WebServerBundle. Register that bundle in your AppKernel file to be able to execute the command again"*.

**Comment by chalasr** [comment]
@javiereguiluz I had the exact same idea but finally thought it wasn't worth it, maybe it is.
The approach was to add a simple check here https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Application.php#L486. Since the whole namespace doesn't exist anymore, we can throw a generic error abut `server:*` commands if the undefined command contains `server`.

**Comment by chalasr** [comment]
See #22094
