### ISSUE TITLE
All or Collection Constraint validates embedded objects

### ISSUE THREAD

**Issue by courtney-miles** [symfony/symfony#21398]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.1.5

When using the `All` constraint on an objects embedded as a property, each object is also validated.

For example, take the following configuration:

    <property name="favoriteColours">
        <constraint name="All">
            <option name="constraints">
                <constraint name="NotBlank"/>
                <constraint name="Type">
                    <option name="type">\Colour</option>
                </constraint>
            </option>
        </constraint>
    </property>

In this case, I'm finding that validation configuration for `\Colour` are also being triggered, where I would expect it to only be validated if I were also using the `Valid` constraint.

**Comment by HeahDude** [comment]
Hello @courtney-miles, this is not a bug as it seems to be the expected behavior of the Validator component.

There are two concepts:
 - cascading (validating nested entities of objects)
 - traversing (validating nested values by iterating over the data with `foreach`)

So for objects:
 - cascading is disabled by default, in other words, all properties are validated (arrays implicitly traversed), BUT nested objects are NOT unless using `Valid` constraint explicitly on each.
 - traversing is enabled implicitly by default when implementing `\Traversable` unless using the `Traverse` constraint on the class to enable/disable it. Unlike validating properties, it will validate values by iterating over the object with a `foreach`.

And for arrays:
 - cascading has no meaning for arrays, since they don't declare properties, they only need to be traversed to get all values.
 - traversing an array is always implicit (as for objects when iterable). But can be controlled if the using groups on collection constraints.

Considering the given example of this issue, `favoriteColours` is an array property of an object, so as an array, it is always implicitly traversed, then each entries are validated.

If the property `favoriteColours` was an object if would not be validated because of the cascading strategy unless using the `Valid` constraint. This can be done the other way around by using `@Assert\Valid(traverse=false)` but with a traversable object (like a doctrine collection), arrays are always traversed as explained here https://symfony.com/doc/current/reference/constraints/Valid.html#traverse.

You can work around the issue by using groups on nested constraints to only validated them when needed.

I don't think there is something to fix in the component as we have everything needed for this use case. Maybe improve the docs on that topic? Don't hesitate to open an issue in the docs repo or review the last PR with the validator label there. Thanks

**Comment by HeahDude** [comment]
The tests added in #36352 confirm we can close here.
