### ISSUE TITLE
[Intl] IntlDateFormatter polyfill behavior differs from a native one

### ISSUE THREAD

**Issue by issei-m** [symfony/symfony#21428]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | All of maintained version (maybe)

Please see following snippet - the POC of my problem:

```php
date_default_timezone_set('Asia/Tokyo'); // My local timezone.

$pattern = 'yyyy-MM-dd';

$nativeIntlDf = new \IntlDateFormatter(
    'en',
    \IntlDateFormatter::FULL,
    \IntlDateFormatter::FULL,
    'UTC',
    \IntlDateFormatter::GREGORIAN,
    $pattern
);

$polyfillIntlDf = new \Symfony\Component\Intl\DateFormatter\IntlDateFormatter(
    'en',
    \IntlDateFormatter::FULL,
    \IntlDateFormatter::FULL,
    'UTC',
    \IntlDateFormatter::GREGORIAN,
    $pattern
);

var_dump(
    $nativeIntlDf->parse('2017-01-01'),  // 1483228800
    $polyfillIntlDf->parse('2017-01-01') // 1483196400
);
```

The native one is care about a timezone well - `1483228800` is `2017-01-01 00:00:00 +0000`,
meanwhile polyfill is NOT - `1483196400` is `2016-12-31 15:00:00 +0000`, seems to be influenced by the current timezone because this time equals to `2017-01-01 00:00:00 +0900`.

As the result, [DateTimeToLocalizedStringTransformer ignoring time during reverse transform between timezones#20806](https://github.com/symfony/symfony/issues/20806) happens IMHO.
(this issue doesn't happen if you installed `php-intl` extension)

Thanks.

**Comment by Jean85** [comment]
Since I partecipated in previous issues about this, I would like to remark this: while fixing this issue, we must be careful in not breaking one important thing, **the DateType field**.

In certain timezones, midnight of some dates is not valid, due to poor choices about DST changes. So, if you want to input that particular date, is considered not valid by the form, due to the transformation. Is it possible to write a test about this? I think that the previous one (`DateTimeToLocalizedStringTransformerTest::testReverseTransformWithNoConstructorParameters`) relies too much on the polyfill we are discussing here, and may not be enough to catch this eventual regression.

**Comment by issei-m** [comment]
I'm closing this because I can no longer see the bug (ended up I do still not know what was wrong, though)
