### ISSUE TITLE
Process component points to wrong PHP version when installing composer.

### ISSUE THREAD

**Issue by stephan-v** [symfony/symfony#21591]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

I am trying to run `composer install` with the Symfony process component like this:

```php
    if ($process->isSuccessful()) {
        $process = new Process("cd {$directory} && composer install");
    
        $process->run(function ($type, $buffer) {
            if (Process::ERR === $type) {
                Log::info($buffer);
            } else {
                Log::info($buffer);
            }
        });
    }
```

It points to a PHP version of 5.6.25 which looks really strange because I am 100% certain I am using PHP 7. Running a phpinfo() inside Laravel gives me:

> PHP Version 7.0.13

Running `php -v` from my terminal gives me:

> PHP 7.0.13 (cli) (built: Nov 15 2016 23:52:36) ( NTS ) Copyright (c)
> 1997-2016 The PHP Group Zend Engine v3.0.0, Copyright (c) 1998-2016
> Zend Technologies

This is the output that I am tailing from my log file which the Symfony process component is writing to:

    Problem 1
        - Installation request for phpunit/php-code-coverage 5.0.0 -> satisfiable by phpunit/php-code-coverage[5.0.0].
        - phpunit/php-code-coverage 5.0.0 requires php ^7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
      Problem 2
        - Installation request for phpunit/phpunit 6.0.6 -> satisfiable by phpunit/phpunit[6.0.6].
        - phpunit/phpunit 6.0.6 requires php ^7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
      Problem 3
        - Installation request for phpunit/phpunit-mock-objects 4.0.0 -> satisfiable by phpunit/phpunit-mock-objects[4.0.0].
        - phpunit/phpunit-mock-objects 4.0.0 requires php ^7.0 -> your PHP version (5.6.25) does not satisfy that requirement.

Does anybody know why it points to a PHP version I am not using? I am running this on macOS and have installed php with homebrew.

The strangest thing is that even if I use `php -v` in the Symfony process it shows the right PHP version, so it seems composer links to a wrong PHP version? I was able to install it locally though with composer by simply requiring it through my own terminal.

If anybody needs more information I am more than willing to try some things. Let me know.

**Comment by javiereguiluz** [comment]
Do you have some PHP version configured in `composer.json` -> `config` -> `platform` -> `php` ?

**Comment by stephan-v** [comment]
@javiereguiluz No I have no PHP version specified there. If that was the case if would also provide an error when I would manually install it from my terminal which is not the case. I am still puzzled.

**Comment by javiereguiluz** [comment]
If you do a `which php` to get the full path to the PHP binary and add it to Composer's command like this, does it work?

```
$process = new Process("cd {$directory} && /usr/local/php7/bin/php composer install");
```

**Comment by stephan-v** [comment]
@javiereguiluz  I just tried it by simply specifying the full composer path and it seems to work like that. I still have no clue why is picks up the default installed PHP version of macOS though since I have completely swapped over to PHP 7 in all other scenarios.

I used:

```PHP
$process = new Process("cd {$directory} && php /usr/local/bin/composer install");
```

and:


```PHP
$process = new Process("cd {$directory} && /usr/local/bin/php /usr/local/bin/composer install");
```

They both seem to work perfectly fine.

I am still baffled by this behavior. Thanks for the temporary workaround though.

I think I might stick with a local composer download to be on the safe side since I want this to work on production. I still would love to know the answer to this, to understand how this works.

**Comment by stephan-v** [comment]
I have also tried running phpunit like so:

```PHP
$process = new Process("cd {$directory} && vendor/bin/phpunit");
```

Which gives me the following message: 

>[2017-02-13 00:23:13] local.INFO: This version of PHPUnit is supported on PHP 7.0 and PHP 7.1.
You are using PHP 5.6.25 ().

Meaning this is not just a composer issue but rather something going on with the symfony component since I know for certain I installed PHP 7.0. Although via homebrew my CLI and phpinfo() still provide the proper 7.0 information.

**Comment by robfrawley** [comment]
@stephan-v When executing a command via the CLI, you will likely have your environment inherited by the Symfony process component, but this becomes more complex when PHP is running from a different SAPI, such as FTM or Apache.

In the latter situations, _your_ custom `$PATH` (from your system user) won't be inherited, because the process isn't running as *you* but as a *different user*, and therefore your `$PATH` will be different from what you might expect. Likely, it picks up the default installation of PHP (instead of the intended version of `7.x`) because your `$PATH` environment variable isn't properly configured to use `/usr/local/bin` *before* `/usr/bin`, __or__ `/usr/local/bin` doesn't even exist in the `$PATH` being used.

You can check the value of your `$PATH` environment variable by running.

```php
$p = new Process('echo $PATH');
$p->run();
var_dump($p->getEnv(), $p->getOutput());
```

If you want to specify a custom `$PATH` then pass it as an associative array to the `env()` method.

```php
$p = new Process('echo $PATH');
$p->setEnv(array(
  'PATH' => '/usr/local/bin',
));
$p->run();
var_dump($p->getEnv(), $p->getOutput());
```

The above would result in your process using the PHP binary you want to use, the `/usr/local/bin/php` binary. You can learn all about the `$PATH` variable at http://www.linfo.org/path_env_var.html, but here are a few pointers:

- Paths are separated by a colon (`:`)
- Order paths by their "priority"
- Paths should not have a trailing slash

For example, this `$PATH` would see both versions of PHP, but load your custom on first.

```bash
PATH="/usr/local/bin:/usr/bin"
```

Furthermore, while when you execute `php` the `/usr/local/bin/php` one will be used, you can always see which paths are available (and in the order they are found) by calling `which` with the `-a` flag. For example, the following would result in something similar.

```bash
$ which -a php
/usr/local/bin/php
/usr/bin/php
```

Lastly, you may very well need the other path directories to exist for your command to work properly. If this is the case, instead of overwriting the `PATH` environment variable (as in my first example), you may want to concatenate the path you want to add to the existing `PATH` like so.


```php
$p = new Process('echo $PATH');
$p->setEnv(array(
  'PATH' => sprintf('/usr/local/bin:%s', getenv('PATH')),
));
$p->run();
var_dump($p->getEnv(), $p->getOutput());
```

**Comment by robfrawley** [comment]
Also note, that you may need to add `/usr/local/bin` to your PATH for `composer` to be found without calling it via an absolute path.

**Comment by robfrawley** [comment]
Also note, that you may need to add `/usr/local/bin` to your `$PATH` for `composer` to be found without calling it via an absolute path.

**Comment by stephan-v** [comment]
@robfrawley I have it set in my path. I am perfectly able to call it from my commandline. Or would I also still have to set it in PHP? Does it not pick up on the systems `$PATH`?

Thanks for the help though but I am still curious to what is causing this. Since I tried this with PHPUnit and go the same results it seems something is going on with the combination of homebrew(package helper for macOS) and Symfony Process component. 

I will research some more tonight, in the meanwhile all suggestions are welcome.

**Comment by nicolas-grekas** [comment]
do you inherit env vars? if not, try doing so

**Comment by stephan-v** [comment]
After having reviewed all the information from @robfrawley and others it indeed runs are another user. 

I am sorry for having to create an issue about this, but I would seem the fastest way to solve this. I am inexperienced with running commands from PHP in this fashion.

I do feel like this is a pitfall many more novice users could fall into and maybe the documentation could state a warning or some kind of message to notify users about this process running as another user. I feel like this might be a valuable addition but to a lot of users it might also be common sense. So it will be it to others I guess.

Either way, thanks for everyone's help here. I appreciate it a lot that everybody is willing to help out instead of simply replying with 'go to stackoverflow'.

Thanks guys.

**Comment by javiereguiluz** [comment]
@stephan-v I'm glad this is fixed now!  As you said, we try our best to help people ... but we only use this repository for bug reports and feature requests, so we often tell people *"go to StackOverflow"* 😄  This time it was different because maybe this was a real Process bug.

I've created an issue in the Symfony Docs repository (https://github.com/symfony/symfony-docs/issues/7505) to think how we could improve this doc. Thanks!

**Comment by stof** [comment]
> Paths are separated by a colon (:)

if you want to make your code portable, use ``PATH_SEPARATOR`` instead. Windows uses ``;`` as PATH separator (as ``:`` is used in paths)
