### ISSUE TITLE
[WebServerBundle] Add config option for default router

### ISSUE THREAD

**Issue by andrerom** [symfony/symfony#21614]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

As the Web Server is being cleaned up it would be great if a long standing limitation of this feature is fixed, namely being able to configure the default router. Which would be useful for symfony distros without having to force users to always specify router argument, diverging from standard symfony doc.

Currently this is hard code in [WebServerConfig.php#L39](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php#L39):
```php
        $this->router = $router ?: __DIR__.'/Resources/router.php';
```

**Comment by javiereguiluz** [comment]
@andrerom I can't truly understand the issue here. The web server commands already define an option to set a custom router script:

```php
            ->setDefinition(array(
                // ...
                new InputOption('router', 'r', InputOption::VALUE_REQUIRED, 'Path to custom router script'),
            ))
```

If you are creating your own customized Symfony distro, you probably have a custom command to start/stop the server, so you can pass a value to this option, right?

Otherwise, can't you use the `ConsoleEvents::COMMAND` event to make some changes if needed before running these commands?

**Comment by andrerom** [comment]
I would not want to redefine the console command for this, and while I could add custom logic to change the meaning of undefined router argument, the cleaner way would be if the default router can be injected / configured / extended.

**Comment by nicolas-grekas** [comment]
@andrerom I guess you can submit a PR if you want that to happen :)

**Comment by andrerom** [comment]
We currently don't have a strong need for this, otherwise I would have :)

So closing, but feel free to reopen if someone wants to improve on this.
