### ISSUE TITLE
[Security] : Voter class '$subject' variable and @Security annotation 'user' object cause problem

### ISSUE THREAD

**Issue by wess1984** [symfony/symfony#21657]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.2

The parameter user is overritten in the UserVoter class.

**Normal scenario :**
  The $subject variable in the Voter class must return the user object passed in parameter in the controller action by the @Security annotation.

Take a look at this screenshots to have further idea.

**User controller edit action**
![image](https://cloud.githubusercontent.com/assets/1428846/23092489/87fc6570-f5cc-11e6-9992-63f5ea4e13f0.png)

**UserVoter Class**

![image](https://cloud.githubusercontent.com/assets/1428846/23092501/e482ccd0-f5cc-11e6-831e-d404e47ed99d.png)

**Dump Result**: The 2 variables $subject and $user show the same connected user

![image](https://cloud.githubusercontent.com/assets/1428846/23092605/a759e7ce-f5ce-11e6-8638-3ac4483593cb.png)
![image](https://cloud.githubusercontent.com/assets/1428846/23092607/b53dd6ca-f5ce-11e6-928c-db5cbdf8b4b8.png)

**Comment by dmaicher** [comment]
Is related to this `FrameworkExtraBundle` issue https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/411.

So `user` currently is a predefined variable as stated here http://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/annotations/security.html#usage.

For now you could rename your variable to `$userEntity` or similar.

**Comment by javiereguiluz** [comment]
@wess1984 thanks for reporting this issue. @dmaicher has confirmed that it's real ... but I'm closing it because we're already working on it in the specific code repository where this should be fixed: https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/411

(Sometimes it's tricky to know where to report issues, so it's OK to report them in the main Symfony repo and we'll move them elsewhere if needed. Thanks!)
