### ISSUE TITLE
You have requested a non-existent service "imdevadminbundle"

### ISSUE THREAD

**Issue by WaltherUA** [symfony/symfony#21672]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.*

Got this error after creating a bundle, but i dont create any service. Please help i checked everything to fix it

**Comment by javiereguiluz** [comment]
The problem is probably that somewhere in your code you used `$this->get('imdevadminbundle')` or `$container->get('imdevadminbundle')` ... or somewhere in your services configuration you put `@imdevadminbundle` in the arguments option of some other service.

In any case, for this kind of problems is better to use the Symfony support channels (https://symfony.com/support) because we use the GitHub repository only to repost bugs caused by Symfony or request new features. Thanks!
