### ISSUE TITLE
[DX] [Form] Use constants for form options

### ISSUE THREAD

**Issue by pimolo** [symfony/symfony#21727]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.7

## Currently

In Symfony Forms, the form type options keys are defined as strings, like `'data_class'`, `'required'`, `'choices'`, etc. (depending of the type of course).

## Proposal

Let's defining a constant for each one of these options!

A few examples:
- `'data_class'` -> `FormOptions::DATA_CLASS`
- `'required'` -> `FormOptions::REQUIRED`
- ...

A benefit could be making sure you don't make typos when you write the options in a field/form.
We could also consider defining these constants directly in the form types (not like in my example above which uses a dedicated class), that could give more consistency to options in my opinion.
Example : `ChoiceType::CHOICES`, `FormType::REQUIRED`...

Note that it won't create any BC break.

Thoughts? Pros / cons?

**Comment by lyrixx** [comment]
> A benefit could be making sure you don't make typos when you write the options in a field/form.

There is already a validation. Not sure it worth it.

**Comment by iltar** [comment]
This means that I have a few list of constants spread around my application and vendor packages. Either that, or I have a partial string, partial constant list. I don't like this idea.

**Comment by felipsmartins** [comment]
I like this idea. However, even though you made a typo while writing any form option OptionsResolver validator will throw an exception.
Of course, your proposal is more comprehensive.

**Comment by yceruto** [comment]
Some IDE are able to autocomplete these options and otherwise the config component validates if each of them is defined, so not worth it (IMHO).

**Comment by paulandrieux** [comment]
The mix strings/constants could be a lack of consistency. 
However, I think it would be a great benefit to use autocompletion from a ChoiceType to discover all the options available through the inheritances.

**Comment by lyrixx** [comment]
@paulandrieux You will find only some options not all. First because you can define options from any form type, form extension. Then because as the proposal state:
>We could also consider defining these constants directly in the form types

**Comment by HeahDude** [comment]
>use autocompletion from a ChoiceType to discover all the options available through the inheritances

Impossible, because types inheritance has nothing to do with PHP inheritance.
The `FormType` itself is inheriting some options and this time through PHP inheritance by extending `BaseType`. However, as said @lyrixx, options can be defined in any class (i.e. child type calling `getParent()` or extension calling `getExtendedType()`) this argument does not suit.

There are too many classes defining options, using only one like `FormOptions`as stated in the proposal is not even possible is the core or it wouldn't make any sense, some options are defined in the Doctrine bridge (in both abstract and concrete types).

Thanks for your proposal @pimolo but I'm 👎 on this, also because I agree with arguments given above considering the `OptionResolver` validation and IDE plug-ins autocompletion.

**Comment by sstok** [comment]
👎  The OptionsResolver already errors when unsupported options are provided and gives suggestions which option you meant instead. Considering the flexibility of Form types this will never work as expected.

Also the options are not that hard to remember (read the manual a few time, use it a few times and it becomes natural), using constants for HTTP status codes is usable because not everyone remembers what 401 means, using constants for flags instead of having to remember bit positions (which can be actually change at any time) is is good use-case.

But for this situation it feels like heavy overkill, also `FormOptions::DATA_CLASS` is much longer to type then `'data_class'` and will not encourage anyone to actually use them.

**Comment by pimolo** [comment]
Clearely there was a lot of points I didn't have in mind.
As this change would break consistency and DX, I'm going to close this RFC.

Thank you all for your feedback! :kissing_heart:
