### ISSUE TITLE
Add a `dump:container` command

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21724]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Symfony version  | 3.x

Related to #21365, @ogizanagi wondered if we could provide a `dump:container` command to dump the Symfony container into several formats: PHP, XML, YAML, GraphViz. The last one could be really useful.

**Comment by stof** [comment]
I don't see why we should have a command dumping it in PHP. The kernel is already doing it during boot. I don't see a benefit for dumping it manually.

regarding Graphviz, https://github.com/schmittjoh/JMSDebuggingBundle used to have a feature building a graph centered around a service with a limited depth, but the bundle looks unmaintained.
Dumping the whole container with Graphviz may not be usable due to the size of the graph. But as we already have the dumper and the info, it should not be hard to add a command.

**Comment by stof** [comment]
And the compiled container cannot be dumped in YAML (our YAML format cannot represent inlined services, even though we could add a feature for it now that we have custom tags)

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" because of the reasons explained by Christophe. Thanks!
