### ISSUE TITLE
Don't add the @Framework Twig namespace when not needed

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21758]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.3

Inspecting the production container of a Symfony app, I saw the following call in the Twig service:

```php
$instance->addPath(($this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/views'), 'Framework');
```

The `@Framework` Twig namespace is created for the FrameworkBundle. However, if you look at the actual contents of that directory, you'll see that it only contains PHP templates related to forms: https://github.com/symfony/symfony/tree/master/src/Symfony/Bundle/FrameworkBundle/Resources/views.

In my app I only have Twig engine enabled (and moreover, I have disabled forms entirely), so should we remove this namespace when `php` is not one of the enabled templating engines? Thanks!

**Comment by stof** [comment]
Well, this has no performance impact on the template resolution (and the only impact on instantiation is the ``addPath`` call).

I'm not sure making the code registering paths in the loader more complex (to check that the folder has at least 1 template in it) is worth it.
Thus, doing this requires tracking changes inside the folder too instead of just checking its existence to invalidate the cached container (otherwise, adding a first template would not register the folder until you clear the cache manually), which would add some overhead in debug mode.

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" because it's not worth it. @stof thanks for the explanation!
