### ISSUE TITLE
Form support can't be disabled entirely?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#21759]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Symfony version  | 3.x

In a Symfony app I have disabled form support (and CSRF, validation, etc.)

```yaml
framework:
    #form:            ~
    #csrf_protection: ~
    #validation:      { enable_annotations: true }
    # ...
```

However, in the production container I see some form-related things:

**3 services**

```php
'form.type.entity' => 'getForm_Type_EntityService',
'form.type_guesser.doctrine' => 'getForm_TypeGuesser_DoctrineService',
'twig.form.renderer' => 'getTwig_Form_RendererService',
```

**2 parameters**

```php
'twig.form.resources' => array(
    0 => 'form_div_layout.html.twig',
),

'form.type_guesser.doctrine.class' => 'Symfony\\Bridge\\Doctrine\\Form\\DoctrineOrmTypeGuesser',
```

And the `twig` service has the following: 

```php
$instance->addRuntimeLoader(new \Symfony\Bundle\TwigBundle\ContainerAwareRuntimeLoader(
    $this, array(
        // ...,
        'Symfony\\Bridge\\Twig\\Form\\TwigRenderer' => 'twig.form.renderer'
    ), ...);
```

Should we remove all this when needed? Thanks!

**Comment by fabpot** [comment]
I've just checked on a project using Flex (not using Form), and I only have the `twig.form.resources` parameter.

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" because I've just verified the same that Fabien said. Thanks!

**Comment by stof** [comment]
I think the difference is that the first project was using DoctrineBundle. The guesser and the form type listed above are the one registered in FrameworkBundle.

I will check whether we have an easy way to mark these services as private when using Symfony 3.3+ (they were required to be public before due to lazy-loading), which would cause them to be removed from the container automatically when Form is not enabled.
