### ISSUE TITLE
UserLoaderInterface removed ability to define custom refreshUser 

### ISSUE THREAD

**Issue by ptrm04** [symfony/symfony#21938]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3

So with the `UserLoaderInterface` replacing `UserProviderInterface`, the ability to declare a custom `refreshUser` method has been taken away. The user still gets refreshed on each request.

- How can we define a custom method that will refresh the user? i.e. you might want to join the query on roles tables if you intend to refresh roles on each request
- How can we stop the user being refreshed / reloaded **completely** on each request? With the custom `refreshUser` method it was an opportunity to suppres reloading from db for apps that don't need / care about this.

**Comment by ptrm04** [comment]
Also:

- On the docs page at http://symfony.com/doc/current/security/entity_provider.html it suggests to use `UserLoaderInterface` and later in this section http://symfony.com/doc/current/security/entity_provider.html#understanding-serialize-and-how-a-user-is-saved-in-the-session on **the same page**  it talks about `refreshUser`
- Many things are not correct in the section about "understanding serialize" - including misleading facts that if the username or password get changed the user will be logged out, as covered in other issues

- Should there be a configurable parameter to decide if you want the user to be reloaded or not?
- In the current state, unless you are relying on multiple roles, reloading the user has no benefits but an additional SQL hit as it does nothing really except when you rely on multiple roles (beyond the scope for many apps) that it will:
**a)** reload the roles if any properties change and you have an `is_granted` call that will trigger role reload
**b)** if the `isEnabled` returns false (i.e. user property changed) **and** you have an `is_granted` call / access control role restriction

**Comment by stof** [comment]
@ptrm04 if you want a special handling of refreshUser, implement the UserProviderInterface yourselves instead of relying on the EntityUserProvider implementation. The UserProviderInterface is not gone. And there is no benefit using the EntityUserProvider if you want to implement the UserProviderInterface fully (and there is no reason to put this implementation in your EntityRepository itself).

And not hitting the DB has another effect: the User instance in the Token will not be the entity managed by Doctrine, which requires carefully writing the code (you cannot get the current user from the Token to allow editing it, or to assign it in a relation of another entity, for instance, as this would save a *new* instance of User in the DB)

**Comment by xabbuh** [comment]
Closing for the reasons given by @stof.
