### ISSUE TITLE
escape trans tag

### ISSUE THREAD

**Issue by Gemorroj** [symfony/symfony#21945]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.5

example:

```twig
<script>{% autoescape 'js' %}
    myTranslatedFunctionValue = '{% trans %}some value{% endtrans %}';
{% endautoescape %}</script>
```

```xml
<trans-unit id="some value" resname="some value">
    <source>some value</source>
    <target>quote - ' - quote</target>
</trans-unit>
```

result:
```js
myTranslatedFunctionValue = 'quote - ' - quote'; // <- syntax error
```

but:
```twig
<script>{% autoescape 'js' %}
    myTranslatedFunctionValue = '{{ 'some value'|trans }}';
{% endautoescape %}</script>
```
correctly escaped variable.
It seems to fit the documentation (https://symfony.com/doc/current/translation.html#translation-filters see note).
But I think there is a problem.
I guess I could use the bundle https://github.com/arthens/safe-translations
But first I would like to hear the opinion of developers.

**Comment by xabbuh** [comment]
> But I think there is a problem.

What actual problem do you mean? The behaviour you describe here is exactly what is described in the documentation.

**Comment by stof** [comment]
And changing this would be a huge BC break

**Comment by Gemorroj** [comment]
> What actual problem do you mean?

The problem is non-obvious behavior.
To me, it seemed that by default, all should be escaped. No matter tag or filter.
It turns out that the `|trans` and `{%trans %}` doing a few different things.

Why do I need to transfer the executable code?
For example, the `{% trans %}<h3>foo</h3>{% endtrans %}` as stated in the documentation.
In real life most likely would have been `<h3>{% trans %}foo{% endtrans %}</h3>`.

**Comment by stof** [comment]
@Gemorroj autoescaping is applied by Twig in display nodes, which come from the ``{{ ... }}`` syntax. Twig does not apply auto-escaping on custom tags (it would be a huge nightmare, as it is not in charge of doing the display, the node is).
If you want escaping, use a Twig expression using the filter.

**Comment by Gemorroj** [comment]
> Twig does not apply auto-escaping on custom tags.
Can add new tags, for example `{% transsafe %}`.
Enabled by default escaping.

**Comment by stof** [comment]
Tags don't change the strategy of escaping. The autoescaping of Twig is about escaping displayed expressions.
Tags in Twig are not about displaying things, but are structuring the template. If they output something by themselves (rather than just delegating their body), they do so internally, not through Twig mechanisms. So auto-escaping cannot know about it.
And in the Twig architecture, the right way to integrate the translation component is the filter, not the tag. This is precisely why we added a filter in Symfony too.

I would be totally against adding another new tag for the translation integration which would apply escaping. Use the filter for that. I would rather deprecate the tag in favor of the filter.
Btw, migrating your whole codebase to use the a new tag would be a similar amount of work than migrating to the filter.

**Comment by Gemorroj** [comment]
Thanks @stof, I understand now.
