### ISSUE TITLE
[Autowire] unable to override automatically autowried services

### ISSUE THREAD

**Issue by mvrhov** [symfony/symfony#21955]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | master

It seems that you cannot override the services that get registered via resources aka psr4 section.
I've prepared a [testcase](https://github.com/mvrhov/symfony-standard/tree/autowireOverride)

**Comment by nicolas-grekas** [comment]
I checked out your fork. The reason is ordering of definitions:
in your bundles extension, you define the `AppBundle\Action\Foo\GetAction`
service,
then in app/config/services.yml, you redefine it as part of the
`AppBundle\` psr4 loading.

files in app/config/* are always loaded last, meaning they overwrite any
definitions set by bundles.

If you want to setup a convention for your bundle (the psr4 mapping), put
it in your bundle's config, not in your app's. Mixing like here can't work
for the "precedence" reason.

"Not a bug" :)

**Comment by mvrhov** [comment]
Yeah, the examples were all fro services.yml. I was blindly following them.

**Comment by nicolas-grekas** [comment]
Just for reference as explained on Slack, the proper config should start with the convention written as:
`<prototype namespace="AppBundle\Action\" resource="../../Action" />`
in the bundle's services.xml

**Comment by bendavies** [comment]
@nicolas-grekas can you explain this `precedence` argument? 
I've just come acropper when migrating a large app to autowiring, and this was the cause.

Why is it that autowiring overwrite definitions? Surely that is not "expected behaviour", at least to me.

thanks!

**Comment by nicolas-grekas** [comment]
@bendavies this is the rule since always: the lastly defined service overwrite any predefined one with the same name.
