### ISSUE TITLE
Downloadable .htaccess File Problem

### ISSUE THREAD

**Issue by aligoren** [symfony/symfony#21992]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | current

Hello there. I've run into a bug in websites that use the Symfony project. This error makes it possible to download htaccess files.

I tried some websites for these web sites:

```
http://symfony.com/.htaccess
https://sonata-project.org/.htaccess
https://connect.sensiolabs.com/.htaccess
http://www.webtekno.com/.htaccess
http://sulu.io/.htaccess
```

**Comment by iltar** [comment]
I don't think this is a direct Symfony issue. This repository doesn't do anything with `.htaccess` files. I've tried it sites I work on and I get an access denied there.

**Comment by theofidry** [comment]
`.htaccess` files don't work with nginx, but it would be better if the access to them was denied:

```nginx
location ~ /\. {
    deny all;
}
```

**Comment by javiereguiluz** [comment]
@aligoren thanks for reporting this!

In practice this is probably *not* a security issue because:

1. The default .htaccess provided by Smyfony doesn't contain any sensitive info
2. If the .htaccess contains sensitive info, it's because the developer added that info ... and that's because they are using Apache ... and Apache blocks by default any attempt to access to the contents of .htaccess
3. If you use Nginx and it's not properly configured ... you can access to the contents of that file ... but you are using Nginx, so that file can't contain anything relevant or sensitive

In any case, we'll improve the docs about this: https://github.com/symfony/symfony-docs/issues/7625

**Comment by aligoren** [comment]
Firstly, thank you all for your answers.

I do not know the security principles very well. I tought this could be problem. I guess it's okay. Thanks :)

I closed this issue
