### ISSUE TITLE
Generate URL without baseUrl

### ISSUE THREAD

**Issue by Hecke29** [symfony/symfony#22013]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.17

The frontend of my Symfony-API is using a proxy. Given that the frontend is reachable at `http://example.com` all backend calls go to `http://example.com/api/` which is a proxy to `http://api.example.net/backend/myapp/web/app.php/`.

There's one use-case (`GET http://example.com/api/product/{id}/details`) where the backend has to tell a URL to the frontend where it is able to get an image. Let's say that the image-endpoint of the API is `/image/{id}/small`. So for the frontend it would be `http://example.com/api/image/4711/small` which would lead to a API-call to `http://api.example.net/backend/myapp/web/app.php/image/4711/small`.

I used the UrlGenerator for this task in different ways:

```
$this->router->generate('myapp_product_image', ['id' => 4711, 'format' => 'small'], $referenceType);
```
where `$referenceType` is:

* `UrlGeneratorInterface::ABSOLUTE_URL`
I get `http://api.example.net/backend/myapp/web/app.php/image/4711/small`
* `UrlGeneratorInterface::ABSOLUTE_PATH)` (default)
I get `/backend/myapp/web/app.php/image/4711/small`
* `UrlGeneratorInterface::RELATIVE_PATH`
I get `../../image/4711/small`
* `UrlGeneratorInterface::NETWORK_PATH` (just to mention it)
I get `//api.example.net/backend/myapp/web/app.php/image/4711/small`

Since the frontend knows that the backend is reachable with `/api/` I want the backend to just return the route. So just `/image/4711/small` would be sufficient.

I thought about implementing a new constant (maybe something like `UrlGeneratorInterface::PATH_ONLY`) that would just return the route like mentioned.

What are your thoughts on this?

**Comment by jakzal** [comment]
Are these two separate applications?

I'm not sure if there's anything we should do in Symfony. Looks like you need to get your concept right.

**Comment by dmaicher** [comment]
Is the backend application somehow aware that its behind the proxy?

Imho Symfony behaves correctly here when generating the absolute path. I would say you need to decorate the router/url generator for your special case and strip out everything that is not needed for the "proxied" version of the path?

**Comment by Nek-** [comment]
@Hecke29 any suggestion of what Symfony could do for your case? Maybe a `UrlGeneratorInterface::APP_PATH`?

**Comment by Hecke29** [comment]
@Nek- That would be awesome.

@dmaicher No, it's not.

@jakzal They are two seperate applications. Just think of a reverse-proxy setup: 
![symfony rproxy-setup](https://cloud.githubusercontent.com/assets/737401/24097560/ab9d96b4-0d66-11e7-982a-72cc30bdf1b0.png)
Since the servers don't have their application in the "root" directory but are in a subdir and there's nothing like `X-Forwarded-Path` the generated URLs are wrong. So my intention is to only generate the `APP_PATH` (in this example `image/4711/small` like mentioned by @Nek-

And yes, this is kind of a workaround for a missing `X-Forwarded-Path`-Header.

Hope I could describe my problem.

**Comment by dmaicher** [comment]
Thanks @Hecke29. Now its a lot more clear :blush: 
In this case having `UrlGeneratorInterface::APP_PATH` would indeed make sense and solve the problem.

Out of interest: How are you currently handling generating other urls? I mean all endpoints should be without the  `/backend/myapp/` prefix then for the frontend?

Thinking if it might be possible to adjust the webserver (nginx?) config so the backend app actually thinks its reachable on `https://x.example.com/` without `/backend/myapp/`. As technically all generated urls should be without the prefix? Or is the backend also reachable without the proxy?

**Comment by nicolas-grekas** [comment]
Anyone willing to digg into the topic here? Otherwise let's close, isn't it?

**Comment by Tobion** [comment]
👎 to add such a feature to the core as it's an edge case. You can do this very easily yourself. Just create a wrapper service that calls Symfonys UrlGenerator and then replaces your base path (backend/myapp/web/app.php/). That's like 5 lines of code.

**Comment by Pictor13** [comment]
Hi, forgive me for resurrecting an old issue, but I believe that the circumstances changed.

Nowadays, that the previous extensibility points have been removed (router `generator_class`), it is harder to customize the behavior.  
Because of that, those 5 lines would rather fit easier into the Symfony `CompiledUrlGenerator`.  

-----
-----

This could be implemented with a `APP_RELATIVE_PATH` as new possible `$referenceType`.  

* Although, I don't _yet_ have an idea how to pass it into the Twig render though without causing breaking changes (the convenience of passing a `bool` to Twig `path`/`url` functions limits us to only 2 values).
An alternative to the `$referenceType` param there could be a `router.generate_relative_to_app_path: true` flag to enable the behaviour.  
Or to have an `app_path()` Twig Function.

------

The pattern is quite more common nowadays.  
It would cover well the cases where a static `<base href="/subpath/">` is used (e.g. sub-applications; or offline use, like @fabpot thought initially in #6631  ; or when behind reverse-proxies and wanting links to be clear & agnostic from the deployment).
HTML source code would also be more readable (no `../` links).
Things can feel a bit astonishing, when using `RELATIVE_PATH` starts to interact with `<base href>` on browser side. While an `APP_RELATIVE_PATH` generation would make things more predictable.

Devs would benefit by sparing themselves headaches with CompilerPasses + CustomCompiledUrlGenerator + config, profiting from a more straightforward approach and less maintenance burden.
It would also provide them more flexibility and interoperability with the increasingly mainstream SPAs, reverse-proxies, subpaths; allowing to choose the route-gen model that fits their use case the best.

-----

A draft for changing CompiledUrlGenerator:
```
const APP_RELATIVE_PATH = 4

public function generate(string $name, array $parameters = [], int $referenceType = self::ABSOLUTE_PATH): string
    {
        # ....

        $referenceAppBase = $referenceType === self::APP_RELATIVE_PATH;
        $referenceType = $referenceAppBase ? self::ABSOLUTE_PATH : $referenceType;
        $url = $this->doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, $hostTokens, $requiredSchemes);
        if ($referenceAppBase) {     # strip prefix; fallback to doc-root if empty, to keep URL valid
            $url = ltrim(str_replace($this->getContext()->getBaseUrl(), '', $url), '/')  ?: '/';
        }
        return $url;
    }
```

Would it be reasonable enough to consider re-opening the issue, given the evolutions from the past?
