### ISSUE TITLE
Typo in Exception in Symfony\Component\Form\Form

### ISSUE THREAD

**Issue by desmax** [symfony/symfony#22103]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | master

File https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php

`throw new RuntimeException('A cycle was detected. Listeners to the PRE_SET_DATA event must not call setData(). You should call setData() on the FormEvent object instead.');`

I believe here is a typo, in first case there should be `getData` instead of setData.

**Comment by fancyweb** [comment]
This is not a mistake, cf the doc of form events (http://symfony.com/doc/current/form/events.html) and especially this warning : 

> During FormEvents::PRE_SET_DATA, Form::setData() is locked and will throw an exception if used. If you wish to modify data, you should use FormEvent::setData() instead.

**Comment by desmax** [comment]
Ok, makes sense. but maybe it should be clarified which setData is meant in the first place.

P.S. I got this when I called `$event->getForm()->getData();`

**Comment by fancyweb** [comment]
Ok I see exactly the problem and you are right, the message is not logic for the DX.

That happens when no data was set when the form is built, and then you use `$event->getForm()->getData();` in a `FormEvents::PRE_SET_DATA` event. I think the right way is to use `$event->getData()` in this event but there is no message about this.

When you try to get the data directly from the form, as it was not set, it tries to set the default data with a `Form::setData()` call that will dispatch the `FormEvents::PRE_SET_DATA` event once again and end up in a cycle...

**Comment by fancyweb** [comment]
That also mean that if no data was already set for the form, in a `FormEvents::PRE_SET_DATA` event, we cannot have access to the `Form::getNormData()` and `Form::getViewData()` methods as they also call the `FormEvent::setData()` and will throw the same misleading exception.

**Comment by stof** [comment]
well, getting the data from the form before it is set in it does not make any sense anyway. It is not there yet.

**Comment by fancyweb** [comment]
I agree but the problem is that if you try to do it, you get a misleading / unrelated message.

**Comment by javiereguiluz** [comment]
We are always in favor of improving error messages, so would @desmax or @fancyweb be interested in contributing a pull request to improve this error message a little? Thanks!

**Comment by fancyweb** [comment]
@javiereguiluz I will work on improving this.
