### ISSUE TITLE
PHPUnit\Framework\TestCase not found

### ISSUE THREAD

**Issue by vyk12** [symfony/symfony#22206]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.18

For a couple of days, the `PHPUnit\Framework\TestCase` cannot be found anymore. I have tests that extend `Symfony\Bundle\FrameworkBundle\Test\KernelTestCase`, which extends `PHPUnit\Framework\TestCase`, that cause my tests to fail because the class cannot be found.

**Comment by Tobion** [comment]
Just update phpunit which also provides those new classes as forward compatibility in its new patch versions.

**Comment by GromNaN** [comment]
You can also run [vendor/bin/simple-phpunit](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit)

**Comment by vyk12** [comment]
I have updated both my composer and systems packages (my dev server runs on Ubuntu 16.04, my staging server on Debian 8), the problem is still there. I don't understand, why does it crash now? Isn't it a backward compatibility issue?

@GromNaN This file is not available in Symfony 2.8

**Comment by stof** [comment]
@vyk12 the symfony/phpunit-bridge package must always be required explicitly when you want to use it (as a dev dependency as you don't need it at runtime). Then the file will be available (and this bridge is designed to allow using the 3.x version of the bridge alongside Symfony 2.8).

Regarding the BC break, PHPUnit provides the namespaced classes since years (it was added in 5.4, with the proper casing in 5.4.3+), and they even have been backported to the latest 4.8 release.
So the only way to get this issue is to use a version of PHPunit unmaintained since years. Use an uptodate version of PHPUnit (there are lots of releases available matching the condition of being 4.8.35 or 5.4.3+)

**Comment by vyk12** [comment]
@stof Thank you for clarifying the situation. This was indeed the issue, the Ubuntu and Debian repositories have the version 5.1. Installing it as PHAR as it is explained in the documentation did the trick.

Thanks to all of you!
