### ISSUE TITLE
How to create multiple sessions in symfony 2.3

### ISSUE THREAD

**Issue by spjoshis** [symfony/symfony#22289]
I have implemented two login forms [one for Admin side and one for Front side] using `FOSUserBundle` in Symfony2.3. When i login from admin side [As Admin] and front end [As User] (Both) in the same browser with different users than Sessions variables created from front end conflicts with session variables of admin side.

Eg.
When user has logged in from front side at that time it stores session if. Now, I am going to login from admin side as Admin user here what the issue is as soon as admin logins, it replaces session Id of Front side with new session id.

Here is my firewall settings

```
firewalls:
    admin:
        pattern:            /admin/(.*)
        form_login:
            provider:       fos_userbundle_admin
            login_path:     admin_login
            check_path:     admin_login_check
            default_target_path: admin_dashboard
            success_handler: login_success_handler
        logout:
            path:           admin_logout
            target:         admin_login
            success_handler: logout_listener
            invalidate_session: false
        anonymous:          true
        context:            admin
    main:
        pattern: ^/
        form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
            default_target_path: /home
            success_handler: login_f_success_handler
            failure_handler: login_f_success_handler
        logout:      
            path:           fos_user_security_logout
            target:         fos_user_security_login
            success_handler: logout_listener
            invalidate_session: false
        anonymous:    true
        remember_me:
            key: "%secret%"
            path: /
            domain: ~
        context: front
```

Is there any settings that i missed out in configuration?

**Comment by curry684** [comment]
Hey @spjoshis, thanks for your question!

The issue board here on Github is only meant for tracking bugs and other development stuff surrounding the Symfony project itself. Due to the immense scale of the project it's not feasible to provide end users with support on here. If you have a look at http://symfony.com/support you'll see it refers you to [Stack Overflow](https://stackoverflow.com/questions/tagged/symfony) where questions with a `symfony` tag are usually answered quickly and thoroughly by fellow developers.

As a sidenote, Symfony 2.3 went out of active support [nearly a year ago](http://symfony.com/roadmap?version=2.3#checker), so you should really consider upgrading to 2.8 soon, or preferably right away to the current stable 3.2. At the end of this year the new LTS 3.4 version will be released with 3 years of active support, and with 3.2 you should be nearly ready for that.

**Comment by javiereguiluz** [comment]
Closing because it looks like a support question. @spjoshis please use the https://symfony.com/support channels, as explained by @curry684. Thanks!
