### ISSUE TITLE
[WebProfiler] File links (event panel) are not resolved using the router

### ISSUE THREAD

**Issue by matt-usurp** [symfony/symfony#22290]
| Q | A
| ---------------- | -----
| Bug report? | yes
| Feature request? | no
| BC Break report? | no
| RFC? | no
| Symfony version  | ~3.2

When viewing the web-profiler event (`?panel=events`) panel the links against the class names appear to be fixed to a hard-coded route `_profile/open?file=xyz` instead of being resolved using the router. I believe this might be the case anywhere file links are rendered.

Because of this when I change my development route prefixes to be anything other than the default ones given in a standard Symfony installation these links will 404.

```yaml
_profiler:
  resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
  prefix: /~dev/profiler
```

I looked at seeing whether I could implement a fix and noticed that this looks like it might be the issue, although I don't have the confidence to make this change.

https://github.com/symfony/symfony/blob/fedbc3fbcbb5f99eab635388491cec143b36392d/src/Symfony/Bundle/WebProfilerBundle/Resources/config/profiler.xml#L57

```xml
<service id="debug.file_link_formatter" class="Symfony\Component\HttpKernel\Debug\FileLinkFormatter" public="false">
  <argument>%debug.file_link_format%</argument>
  <argument type="service" id="request_stack" on-invalid="ignore" />
  <argument>null</argument>
  <argument>/_profiler/open?file=%%f&amp;line=%%l#line%%l</argument>
</service>
```

I personally am not affected by this as I would rather view the file in my IDE, however I thought I should report this anyway. Thanks.

**Comment by curry684** [comment]
There's much more amiss here. The bug is definitely there, but that piece of config is not to blame, as it's correctly concatenated to the BaseUrl in https://github.com/symfony/symfony/blob/033c41a6b91a2520106412ba320f234ca90e6ba1/src/Symfony/Component/HttpKernel/Debug/FileLinkFormatter.php#L82:
```
    $request->getSchemeAndHttpHost().$request->getBaseUrl().$this->urlFormat,
```
The true problem there is that the Base URL is an empty string in nearly all situations, as the HttpFoundation Request::prepareBaseUrl method extracts it from `SCRIPT_URL`, therefore the front controller, which is by convention in the external root folder. This just accidentally goes right all the time because just about everyone just mounts in `/_profiler` in the root.

So either the FileLinkFormatter misunderstands the purpose of the Base URL (which would make it a HttpKernel issue) or the Request incorrectly determines the Base URL (which would make it a HttpFoundation issue). One of those two is wrong though.

Status: reviewed

**Comment by curry684** [comment]
Just noticed the exception pages also use these links in the main callstack view, which are thus all broken. Therefore this shouldn't go low priority.

**Comment by matt-usurp** [comment]
Nice investigation! 

I just want to add that because I have the prefix `/~dev/profiler` the open route that works (if I go here manually) is `/~dev/profiler/open?file=xyz` and therefore the parameter for the argument I give in my snippet would still be an issue even if the base URL was fixed. That is `/~dev/profiler/_profiler/open?file=xyz` is still wrong.

However, maybe I am missing something and it's overridden by a compiler pass.

**Comment by curry684** [comment]
Correct, I also realized that after my initial posts, but it's moot right now as that part is just a matter of fixing the config. If BaseUrl were supplied/processed correctly the service argument would have to be:
```
<argument>/open?file=%%f&amp;line=%%l#line%%l</argument>
```

**Comment by javiereguiluz** [comment]
We're trying to solve this issue in #24153. It'd be great if you could test it in your real apps. Thanks!

**Comment by matt-usurp** [comment]
I subscribed to the PR, thanks for taking a look. When I see that it is good to test with the requested changes I will check it out and try it on our apps at work.
