### ISSUE TITLE
[Crawler] Conflict with html tags

### ISSUE THREAD

**Issue by jvahldick** [symfony/symfony#22375]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8, 3.x

I am dealing with a problem when I was scraping a specific website, which the content is not created properly. So I could catch if there is any </html> written in the file, the domCrawler stops the content's creation on that point.

Should it be the correct behavior or it should identify the last html closed tag?

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head></head>
<body>
<script type="application/javascript">
    function example() {
        var newWindow = window.open('about:blank', 'ImageWindow');
        newWindow.document.write('<html><title>x</title><body><img src="imgSrc" alt=floorplan/></body></html>');
        return false;
    }
</script>
<div id="example">dom crawler example</div>
</body>
</html>
```

**Comment by Jean85** [comment]
The crawler doesn't support javascript at all, it works only on plain HTML. So your example won't work, it's not the intended functionality.

**Comment by stof** [comment]
This is a limitation of the PHP DOMDocument parser, which is based on libxml.
And btw, older browsers had the same limitation, which is why we used string concatenation during years by splitting the string between ``<`` and ``/`` for each closing tag.
Another option is to use ``<![CDATA[`` for your JS blocks, as done for the old days of XHTML (as this also avoids this issue in libxml AFAIK). See http://stackoverflow.com/questions/66837/when-is-a-cdata-section-necessary-within-a-script-tag for an example of such syntax.

Oh, and of course, the best solution is to migrate away from `document.write` (which is the main case where you have HTML inside an inline script tag).

There's nothing we can do in the DomCrawler component (we have to plan to reimplement the whole ext-dom in userland just to be able to implement a HTML parser not suffering from this limitation).

If you have no control over the content of the website, relying on the PHP DOMDocument parsing will be very hard. You would have to alter the source before giving it to the Crawler and ext-dom, and this is very error-prone.

**Comment by stof** [comment]
Note that this is the same than https://github.com/symfony/symfony/issues/21852

**Comment by javiereguiluz** [comment]
Closing it for the reasons given above. @jvahldick hopefully you can apply any of the alternatives suggested by @stof.

**Comment by jvahldick** [comment]
Hey guys, 

Thanks for the quick answer and sorry for the duplication, I was searching just for the open issues.

It's an external website, so I don't have the control of the code. Anyway, I already did some replacement to solve this.

:+1:
