### ISSUE TITLE
Can not read env()-parameter in a Compiler Pass

### ISSUE THREAD

**Issue by dbrumann** [symfony/symfony#22456]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

I encountered the following problem when writing a CompilerPass that reconfigures a services based on whether a certain parameter is checked. The CompilerPass looks something like this:

```php
<?php
namespace AppBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class SomeCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        if ($container->getParameter('env(SOME_PARAMETER)') == false) {
            return;
        }
        if ($container->hasDefinition('app.some_service')) {
            // TODO Interact with service
        }
    }
}
```
The parameter is set in my parameters.yml like this:

    env(SOME_PARAMETER): false

Checking it after the Container is compiled (e.g. in a Controller) works fine, but in the Compiler Pass instead of the expected value `false` getParameter will return something like: `env_SOME_PARAMETER_d163dacb55d3a0dfb9e6236feba2ec26`.

I have also tried setting the environment variable with the same effect. The same condition using a "regular" parameter without `env()` will return the expected value.

**Comment by nicolas-grekas** [comment]
That's the expected behavior: you should not use the values of env var at compile time. Doing so would mean that the generated container is not configurable anymore at runtime.

**Comment by javiereguiluz** [comment]
The problem here is that you are using a dynamic value (env var) to make a "static decision" (creating/enabling or not some service in the container). Two possible solutions would be: 1) replace the env var by a regular config param and keep the compiler pass; 2) keep the env var, but remove or change the logic of the compiler pass.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/issues/21420

**Comment by gipeshka** [comment]
Would it be that the situation is solved as following:
```
public function process(ContainerBuilder $container)
{
    $container->compile(true);

    $serviceDefinition =
        $container->getParameter('is_my_feature_enabled')
            ? $container->findDefinition('MyService.implementation')
            : $container->findDefinition('MyService.dummy');

    $container->setDefinition('MyService', $serviceDefinition);
}
```
?
Would it mean that the container is compiled twice? During the compiler path `process` and before we go on with controller handling the request?

**Comment by stof** [comment]
Compiling the container inside a compiler pass will create an infinite loop. Don't do it.

If you need the resolved value of the parameter (being aware that changing the value of the env variable will then require that you clear your cache for it to be taken into account as it is read at compile-time rather than runtime), you can use the following:

```php
$parameterValue = $container->resolveEnvPlaceholders(
    $container->getParameter('%env(foobar)%'),
    true // Resolve to actual values
);
```

Btw you should not be setting the definition in a new id, as this will create 2 objects. You should set an alias instead.
