### ISSUE TITLE
[Feat] DI - auto wire container params using annotation

### ISSUE THREAD

**Issue by akomm** [symfony/symfony#22467]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x.x

I would be nice if you could auto wire container params using annotation like in this example:

```php
    /**
     * @ContainerParam(name="kernelEnvironment", param="kernel.environment")
     */
    public function __construct($kernelEnvironment)
    {
    }
```

This would play nice with bundles like [DunglasActionBundle](https://github.com/dunglas/DunglasActionBundle) and with auto wire in general.

I could make a compler pass which makes the conversion, but the default AutowirePass from symfony throws when auto wire is enabled and an argument could not be resolved.

**Comment by sstok** [comment]
FYI it's autowire 😉 and this is more about annotation based DI, which has been somewhat rejected in the past because it couples your code to the framework.

Autowiring is about automatically setting-up the service configuration so you don't have to do everything manually. `@required` (phpdoc not an Annotation) is an exception here because it informs the CompilerPass to that this method can be used for autowiring (and you don't have to define method calls explicitly) but it doesn't couple your code to the framework, and is nothing then a tip.

When you use annotations inform which param should be injected, you are still explicitly wiring your service configuration. Except that it's now done with annotations.

But did you know you can actually inject parameters without having to supply the other parameters?
Can't find the documentation 🤔 let me see if I can find the pr 😛

**Comment by sstok** [comment]
Ah found it. https://github.com/symfony/symfony/pull/21383

**Comment by stof** [comment]
This PR is indeed not about autowiring at all. It is about annotation-based configuration of services.

I'm -1 on such feature (it couples the code to the container).
But note that it could be implemented outside the core: you would need to build a compiler pass reading such annotation and configuring the necessary argument. You would just have to ensure that its priority is high enough to make it run before the AutowirePass (so that necessary arguments are already defined based on annotations when reaching the autowiring validation of arguments)

**Comment by akomm** [comment]
@sstok you are right. It is basically an alternative configuration in annotation instead of yml... I had similar concerns, but was not entirely sure. I did not know about named params. Thanks!

@stof Agree. Did not know about priority option. Thanks.

**Comment by nicolas-grekas** [comment]
Closing as explained.
