### ISSUE TITLE
show last file in /src when reporting errors

### ISSUE THREAD

**Issue by hajika** [symfony/symfony#22472]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.2

For some errors, one get the error handling itself highlighted and extended, not the place where the developer has made assumedly the error. For example when a parameter is used, that has not been defined symfony will always present the file `var/cache/dev/appDevDebugProjectContainer.php at line 4072` on the error page because the stack ends there. Thats not always very exploratory.

I propose that always the last file in the `/src` and `/app` folders should be shown (means: highlighted and extended) by default. That should be configurable if you are developing in another directory.

**Comment by javiereguiluz** [comment]
In the new exception pages available in "master" and in the upcoming Symfony 3.3 (see https://symfony.com/blog/new-in-symfony-3-3-redesigned-exception-pages) we already do that. @curry684 improved those exceptions in #22344 to always expand by default your own application code instead of vendor/ or var/ code.

So, I think we can close this proposal as "fixed" and available in a few weeks (Symfony 3.3 will be released at the end of the next month). Thanks!
