### ISSUE TITLE
[Workflow] State is lost running multiple branches in parallel

### ISSUE THREAD

**Issue by marcospassos** [symfony/symfony#22521]
| Q                | A
| ---------------- | -----
| Bug report?      | Yes
| Feature request? | No
| BC Break report? | No
| RFC?             | No
| Symfony version  | 3.2.7

Consider the following workflow:

![graph](https://cloud.githubusercontent.com/assets/943036/25387479/648c4d90-29a1-11e7-97bc-600eb4ea68b2.png)

Once events can happen asynchronously, I get a new running branch for every event triggered from an action place. To achieve such outcome, I've added some recursive transitions. I have also added some guard listeners so that I can ensure that a transition will never be applied from the same place more than once:

![graph2](https://cloud.githubusercontent.com/assets/943036/25387715/3222e89a-29a2-11e7-9cce-4787aa6ebdaa.png)

Now, let's suppose I have trailed the following path:

```
(start) -> [match] -> (email-action) -> [email-send] -> (sms-action)
```

At this stage, the marking points to ` [sms-action, email-action]`.

If I apply the transition `sms-bounce`, the new place `email-action` will get merged with the existing one, resulting in the marking `[email-action]`. So now any transition applied from there will run as a single thread, and then the current state is mixed.

**Comment by lyrixx** [comment]
Hello @marcospassos 

I'm not sure to fully understand your issue / use case in the first paragraph

About the second paragraph:

> At this stage, the marking points to [sms-action, email-action].

It's normal. All places **after** a transition get a new token when you fire the transition.

> If I apply the transition sms-bounce, the new place email-action will get merged with the existing one, resulting in the marking [email-action]. So now any transition applied from there will run as a single thread, and then the current state is mixed.

You are right. The workflow component does not implement all features defined in the PetriNet specification. We do have a limitation: a place can contain only 1 token and all edges weight 1.

---

Anyway, I'm not 100% sure you need a full implementation of the PetriNet spec because I don't understand your workflow.

**Comment by lyrixx** [comment]
I'm closing this issue because there is no feedback.
