### ISSUE TITLE
ldap_free_result() expects parameter 1 to be resource, integer given. in vendor/symfony/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php at line 44 

### ISSUE THREAD

**Issue by pouyana** [symfony/symfony#22632]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

The component/ldap as a service when combined with a cache system leads to this error. It is very hard to debug. But if you need more data I would be glad to report then.  In this class  `$this->search` is 0 and that is why the error is happening.

**Comment by nicolas-grekas** [comment]
ping @csarrazi

**Comment by csarrazi** [comment]
@pouyana, can you explain more precisely how to reproduce this?

Regardless, Collection classes are not meant to be cached. If you wish to cache query results, you should rather use the CollectionInterface's `toArray()` method. Otherwise, you may end up caching the query object, which contains the connection and search resources, which can not be serialised/deserialised.

Actually, I think it would be better to throw an exception, should the search resource be something which is not a PHP resource.

**Comment by pouyana** [comment]
@csarrazi That is what I tried to do:
Cache the result of the` Query->execute()` and then use it afterward. 
You are right I could not make it work (search resource was not available). I was not aware of ` toArray()` method. You can close this bug.
