### ISSUE TITLE
Webpack asset management

### ISSUE THREAD

**Issue by jry2** [symfony/symfony#22644]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | v3.3.0-BETA1

Would it be possible to publish official recommendation regarding Symfony 3.3 and asset management based on Webpack? We are looking for something like [Laravel Mix](https://laravel.com/docs/master/mix).

Support for Less, Sass, PostCSS, Source maps for debugging, Cache busting (with [Symfony 3.3 Manifest-based asset versioning](http://symfony.com/blog/new-in-symfony-3-3-manifest-based-asset-versioning)), maybe BrowserSync.

**Comment by javiereguiluz** [comment]
@jry2 I like your proposal a lot but I must close it for two reasons:

* You are asking for documentation, so we'll add it to the Symfony Docs repo (https://github.com/symfony/symfony-docs) instead of this one.
* We are going to introduce in the coming days our own JavaScript-based tool to manage web assets. Stay tuned!

**Comment by jry2** [comment]
Great, thank you!

**Comment by yakobe** [comment]
Any news on this javascript based tool? 😊

**Comment by stof** [comment]
@yakobe this tool is being worked on by @weaverryan currently. And AFAIK, it already powers the asset pipeline of symfony.com
