### ISSUE TITLE
Bug Asset Function in Twig

### ISSUE THREAD

**Issue by florianmarical** [symfony/symfony#22722]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7.22

We have updated Symfony to version 2.7.27. Since then, we have an error on the Asset function in Twig.

We pass an object in the Asset method, and the __toString method returns the path of the image. Before there was no worry, it worked well.

Since the update, we have the following error: 
`Proxies\ _ CG _ \W360\FileBundle\Entity\File as array`

The error would come from the Symfony\Component\Asset\PathPackage.php file
`Line 62: if ($ this-> isAbsoluteUrl ($ versionedPath) || ($ versionedPath && '/' === versionedPath [0])) {`
 
$VersionedPath contains our object and it can not be used as an array.

We fixed the problem by testing if $ versionedPath was an array.
`Line 62: if ($ VersionedPath) || (is_array (versionedPath) && $ versionedPath && '/' === versionedPath [0])) {`

**Comment by dmaicher** [comment]
How exactly does the `asset(...)` call in twig look like that causes this issue? What arguments are you passing?

**Comment by dmaicher** [comment]
Ok So I guess you are using this?

```twig
{{ asset(image_object) }}
```

Ok then this diff indeed breaks it for you:
https://github.com/symfony/symfony/compare/v2.7.26...v2.7.27#diff-cfeee47d50fbac0d07f3a0c736a9fa53R62

But technically you are "violating" the interface of the `asset` method as the phpdoc indicates it expects a `string` and not an object (even if it might be casted into a string with `__toString`):

https://github.com/symfony/symfony/blob/v2.7.27/src/Symfony/Bridge/Twig/Extension/AssetExtension.php#L55

The cleanest would probably be if you extend the `asset` extension and forward the call to Symfony's version with `(string) $imageObject`.

What do you think @weaverryan? One other alternative would be to use `substr($versionedPath, 0, 1)` instead of `$versionedPath[0]` to get the first character.

**Comment by stof** [comment]
Well, we don't provide BC for cases where people don't respect the contract (implementations details may make implicit casting work for you, but providing BC for any such case would likely forbid us to make any change in existing code to ensure the same weird edge cases all keep working).
So the solution here is indeed to use `{{ asset(image_object.path) }}`.

I would not recommend overwrite the `asset` function, as this would also impact other bundles in the project, and then you might be missing new features added in later Symfony versions (new arguments for instance) which would break them.

**Comment by xabbuh** [comment]
I agree with @stof here. Thus I am closing this as as misuse of the official API that can easily be fixed when calling the `asset()` function.

**Comment by florianmarical** [comment]
ok, thank you very much for the explanations. We will do : {{ asset(image_object.path) }}
