### ISSUE TITLE
[VarDumper] Expand all

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#22856]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2

Would be nice if a HTML `dump()` has some `expand all` toggle; or persist the "open paths" in local storage maybe;

Basically i want to save 7 clicks on each refresh :)

![image](https://cloud.githubusercontent.com/assets/1047696/26307955/709bf1a6-3ef7-11e7-9fb7-df08c5cfe6c9.png)

**Comment by stof** [comment]
Ctrl+click on the array toggles all child nodes. If you want to expand everything, you can collapse the root node and reopen it with Ctrl+click instead of just a click (use Cmd+click on Mac instead).

Remembering the open paths in local storages would be weird, as successive dumps may not share the same paths at all.

**Comment by ro0NL** [comment]
Wow :)
