### ISSUE TITLE
[DependencyInjection] Create aliases of expressions

### ISSUE THREAD

**Issue by iluuu1994** [symfony/symfony#22944]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | v3.3.0-RC1

I've been injecting the current request into my services using `@=service('request_stack').getCurrentRequest()`. Now that the new DI features are here I wanted to create an alias to the current request using the following snippet so that I can autowrite it in my services:

```
Symfony\Component\HttpFoundation\Request: "@=service('request_stack').getCurrentRequest()"
```

This gives me the following error message:

> [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
> You have requested a non-existent service "=service('request_stack').getCurrentRequest()".

I guess I could just inject the `request_stack` service but that has some drawbacks:

- Creating an instance of this service elsewhere will require creating a `RequestStack` object
- The API is lying as the `RequestStack` is not actually required

I think this could be a useful feature.

**Comment by vudaltsov** [comment]
The whole idea of the request stack is providing certain request objects when they are needed and when they are relevant.

Injecting request this way (even if that was possible) makes no sense. The dependency will be evaluated and the request dependency won't switch at runtime when the actual current request switches. So you might get the wrong request in your service.

You cannot use such objects at DI compilation phase, because they don't even exist at that moment. And aliases won't help here.

**Comment by vudaltsov** [comment]
Here's a wonderful explanation of all this: [New in Symfony 2.4: The Request Stack](http://symfony.com/blog/new-in-symfony-2-4-the-request-stack)

**Comment by iluuu1994** [comment]
That makes sense. Thanks @vudaltsov for explaining. In my case I'm mostly interested in the master request which is why the `RequestStack` seems unnecessary. I can live with injecting the `RequestStack`.
