### ISSUE TITLE
[Form|Twig] customize block render twice if non-root block. 

### ISSUE THREAD

**Issue by alborq** [symfony/symfony#22941]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Symfony version  | 2.8.9, 3.* tested

Hello, 
When try to custome form field like 

```twig
{% block _form.name_row %}
    {# Some ...#}
{% endblock %}
```

If this block definition is in another block (like {% block content%}) twig thinks is a new one and render it. 

Result : _form.name_row is render twotime : 
  - on declaration
  - on usage 

In my classic case: 
feature/create.html.twig  => include form/formRender.html.twig  with form only
feature/edit.html.twig      => include form/formRender.html.twig  with form only
form/formRender.html.twig => Do some work to display form nicely 

declaration of block in form/formRender.html.twig is obliviously in block like :  

```twig
{% block content %}
        {% include 'form/formRender.html.twig' with {'form': form} only %}
{% endblock %}
```

I cant remove out of {% block content %} because include. Block is render twice. but without form context, Result some error of undefined vars.

**Comment by stof** [comment]
In a template which does not extend a parent (or inside a block overwriting a parent block), a `{% block %}` does 2 things:

- it defines a block
- it renders this block

For a form theme customization, you only want to define blocks, not to render them.

So if you need to use a custom theme for your form and your template does not have a parent, you will need to store your custom form theme blocks in a different template than the one rendering the form (and then using the name of this other template instead of `_self` in the `{% form_theme %}` tag.
Btw, I'm quite sure that the Symfony documentation has a warning about this.

**Comment by alborq** [comment]
Thanks @stof for your reply. 

Ok but, if i use form_theme to customize all of needs of forms obliviously the goal is use only form(form) render method with a good theme. But: 
-  If i want customize specific form :` _detail` i use 'customize an individual field' with name of form : `_detail_widget`=> it work. 

- When this form is nested on other form once => work with alias : 
```twig
{% use 'form.html.twig' with _detail_widget as _form_detail_widget %}
```

- When this form is nested on other form Twice or more ? => i may use  : 
```twig
{% use 'form.html.twig' with _detail_widget as _form_director_detail_widget %}
{% use 'form.html.twig' with _detail_widget as _form_subdirector_detail_widget %}
{# ... maybe more #}
```

- When this form is a collection of other form,  i may use  : `_entry `naming ? 

Complexity grow up with that.
Actually, form_theme block is not rendered on definition because twig bridge force to render them and send render on a void ? thanks to `\Symfony\Bridge\Twig\Form\TwigRendererEngine`

i dont thinks use include is done only by me, form is generally render directly on view (Ex : Two column form view)  Usecase available on Symfony Demo : https://github.com/symfony/symfony-demo/blob/master/app/Resources/views/admin/blog/edit.html.twig (usage of _form.html.twig)

Maybe we can send on void like extend view. Say to twig do not display block. Or some else ? 

I have read during all day docs about [customize](http://symfony.com/doc/2.8/form/form_customization.html) without reading anything about this case.

**Comment by stof** [comment]
I don't understand what you mean. You are talking to me about usage of the `{% use %}` tag, which was not mentioned in the discussion before.

Btw, if the rendering is for one of your own form types rather than for a Symfony builtin type, you can define theming for the type itself rather than theming the individual field (which avoids knowing where the field is.

and no, TwigRendererEngine does nothing to avoid rendering blocks on definition by sending output to void. What it does is that it **never** ask Twig to render the template used as form theme (it only asks it to render blocks when it needs it)

**Comment by alborq** [comment]
@stof sorry for `use`, it's a fail of copy paste. 

For the first point, yep, that i have sayed is stupid. i just need to create theme by Type

And thx for explain about TwigRendererEngine. 

I close.
