### ISSUE TITLE
Breaking change using array values in cookies since Symfony v3.3

### ISSUE THREAD

**Issue by thomx12** [symfony/symfony#23017]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes
| Symfony version  | 3.3.*

Please see [this issue](https://github.com/laravel/framework/issues/19443) for details and code snippets.

**Comment by stof** [comment]
Passing array values as the cookie value was **never** supported in Symfony. The contract in Symfony 3.2 and older is `string` only: https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/HttpFoundation/Cookie.php#L38

For 3.3, we actually changed it to allow `string|null`.

Btw, I don't see how this could work in 3.2 either. AFAICT, it should also be triggering a `Array to string conversion` notice, as it also casts the value to string in 3.2

**Comment by derekmd** [comment]
FYI, it would have been implicitly allowed in Laravel apps since its `EncryptCookies` middleware would transform array payload cookies to a string hash.

## Example

```php
return view('who-needs-standards')->withCookie('channel', [
    'utm_source' => 'laravel',
    'utm_campaign' => 'issueclutter',
    'utm_medium' => 'github',
]);
```

in post-middleware would call:

```php
app(Illuminate\Contracts\Encryption\Encrypter::class)->encrypt([
    'utm_source' => 'laravel',
    'utm_campaign' => 'issueclutter',
    'utm_medium' => 'github',
]);
```

to store this string in the 'channel' cookie:

"eyJpdiI6InJCRGdNSmhWSU5VeUF1c0dRRHJzWmc9PSIsInZhbHVlIjoiU1c4MWhLYzJPY29JblpBaW9zekZYanE5RlJwVkxFQXFFdzJBRFY2U2lIek5uM0tEUml6aU9lSlVaV1Y5UkJwMkxpSzZcLzNjbDZwRCsyVDA1dUJTQmRwRzBDckJ0RWZJVjIyTDU4WGlhRHV4SERiTTV4Mkozais5NDBhcENxYXp5SWtISzVweEE1ejg3YlwvQk1aUkViQ0YzS1wvNFdkajNIT0V1OTFwdmwzS1VBPSIsIm1hYyI6IjBkNGM0Nzg5YjBiNThmYzNiNjBlYjQ5YTE3NmE0YTM3NTdkZjhhY2RlNDM4NzJkMWExNzViYjk1MjEzMjVmNjcifQ=="

## Cause from Laravel's codebase

The abstractions built on top symfony/http-foundation's `Request` class don't enforce a `string` value in its interface due to `func_get_args()` magic:

https://github.com/CanadaStays/canadastays-v5/blob/master/vendor/laravel/framework/src/Illuminate/Http/ResponseTrait.php#L67

There are likely recently upgraded Laravel 5.4 apps (from 5.3 with a Symfony 3.2 dependency) now exhibiting this problem when attempting to retrieve the cookie after `EncryptCookies` middleware decrypts it. The `ParameterBag` of `Request@cookies` now holds a decrypted plain ol' PHP array that `Cookie@__toString()` won't handle.

## Solution for codebases wanting to use Symfony 3.3

To be fair, the official Laravel framework docs never mention devs can store arrays in cookies. But the programming interface allowed it.

Existing incoming cookies would have to be transitioned to JSON-encoded strings, overwriting those cookies before a 3.3 upgrade can happen. Good luck if the cookie TTL was originally set in months!

Tag: https://github.com/laravel/framework/issues/19417
