### ISSUE TITLE
Validate an array will validate it's values recursively

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#23032]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.2.9

Hi !

I have this simple code :
```php
$object = new MyObject();
// test #1
$validator->validate(['foo', $object], null, 'validationGroup');
// test #2
$validator->validate([0 => [0 => ['foo', $object]]], null, 'validationGroup');
```
This will call `validationGroup` validation on $object, for tests `#1` and `#2`.
I can understand for `#1`, although it's not what i expect : validators should validate only one level, so it must validate keys and values (type, count, etc), but not call `validationGroup` on each values.
If i want to validate each value, with `validationGroup`, i must add `Valid` validator, like we do on objects.

For `#2`, i don't understand why group `validationGroup` is validate for $object ?

Thanks !

**Comment by xelaris** [comment]
Hi, I think it's expected behaviour. Since you don't pass any constraints to the validator [the `Valid` constrained is assumed](http://api.symfony.com/3.3/Symfony/Component/Validator/Validator/RecursiveValidator.html#method_validate) and the default value for the [`traverse` option](http://symfony.com/doc/current/reference/constraints/Valid.html#traverse) of the `Valid` constraint is `true`, which means:

> If this constraint is applied to a property that holds an array of objects, then each object in that array will be validated only if this option is set to true.

Status: Works for me

**Comment by steevanb** [comment]
So, i missed something in documentation, i found nothing about this behavior.

**Comment by xabbuh** [comment]
IMO that's the expected behaviour as explained by @xelaris.

@steevanb Would you like to open an issue in the [documentation repository](https://github.com/symfony/symfony-docs) to improve that over there?
