### ISSUE TITLE
Add a way to "export" parameters, and remove all the non-exported ones

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#23133]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

When opening a dumped container file, one can see that the list of parameters can grow big, with many parameters being just useless because never used at runtime (e.g. all `*.class` params from bundles.)

I propose we add a way to "export" parameters, so that in 4.0, when a dumped `$container` is used, only exported parameters could be retrievable via `$container->getParameter()`.

This could be done via e.g. new `get/addExportedParameters(string[] $params)` methods on the base extension class. It may also be useful to be able to "export" from config files, via e.g. an `export="true"` attribute in XML (dunno for Yaml).

In 3.4, accessing (get/has) a non-exported param would throw a deprecation.
WDYT? Anyone willing to give it a try?

**Comment by javiereguiluz** [comment]
Two quick comments:

* I'm not sure this is a big problem for performance ... because the worst problem was the `*.class` params that you mentioned, but all quality bundles have removed them now. But maybe people with complex Symfony apps can share some performance stats and prove me wrong about this.
* What about dynamic parameters? Imagine a method calling `->getParameter('loader.' + $someVariable)`  You can't detect if those params are really used in run-time and "exporting" all of them would be boring.

**Comment by fabpot** [comment]
I don't think this is something we need to work on. "Best practices" say that you should not create parameters. Use cases are rare. "*.class" **must** be removed.

**Comment by nicolas-grekas** [comment]
@javiereguiluz dynamic parameters would be exported of course. Being convention based, they are very easy to make so by their providing bundle extensions.
Fact is that I opened Blackfire's dumped container, and 13% of it is a list of useless parameters, lots of `*.class` included. And we only quality bundles I promise :)
Why do we have this "best practice" in the first place? AFAIK, it's *because* parameters pollute the dumped container. While moving some 2.x apps to 3.x, one of the pain point was in fact replacing by-`*.class` specialization by full service redefinition. This feels just annoying :)

So, let's make most params compile-time only, because most are. Still unconvinced we should give it a try?

**Comment by javiereguiluz** [comment]
It's not that I'm still unconvinced, but I'd need some stats or profiles showing that this is really a problem for CPU performance, memory consumption, etc.

About the `*.class` parameters, we deprecated them more than 1 year ago. Using them is a very bad practice and those bundles should remove them as soon as possible.

**Comment by lyrixx** [comment]
I already proposed this few [years ago](https://github.com/symfony/symfony/issues/11881#issuecomment-56247459) and this was rejected.
But I did not called that "exported parameters" but "public parameters", like for the services.

Anyway, now I'm agree with @fabpot ; I don't think we need this.

**Comment by nicolas-grekas** [comment]
My point is putting the dumped compiler on a diet. Any other proposal?

**Comment by nicolas-grekas** [comment]
Note that *.class parameters are just one example amongst many other params that just sits in the dumped container for nothing. I can find a bunch of others that are used at compile time only.

**Comment by javiereguiluz** [comment]
@nicolas-grekas instead of exporting "the real params" ... we could do the opposite: add a method to remove params that are only used in compile time, so good bundles can use it to not "pollute" the container. In any case, I still can't see why this is needed.

**Comment by nicolas-grekas** [comment]
@javiereguiluz we could, but this will be far less efficient and will remain unused so won't solve anything to me. We'd better encourage people (bundle authors really) be explicit IMHO.

**Comment by fabpot** [comment]
*.class are a bad practice not because they pollute the list of parameters, but because it gives you the false impression that it makes them overridable. They were introduced as such, but that does not work in practice and we later added proper ways to override a service. So, we were able to get rid of them. If some (quality/recommended) bundles still have *.class parameters, they should be deprecated and removed.

For other ones, we should be doing the same. And we already did in the past. Scanning existing parameters and deprecate/remove the ones that do not makes sense in terms of extensibility.

**Comment by nicolas-grekas** [comment]
> Scanning existing parameters and deprecate/remove the ones that do not makes sense in terms of extensibility

The core issue is that there is no other way to convey configuration from bundle extensions to compiler passes. We can keep our bundles clean, but helping bundle authors doing so is also important. Most of the unused params I see are from bundles. We can say "their fault", but if core can help do better by default, it's its our job :)

**Comment by stof** [comment]
if a parameter is used purely to convey info to a compiler pass, the compiler pass could clean the parameter when it is done with it.
