### ISSUE TITLE
[Profiler][Translation] Stop showing Translation Errors twice?

### ISSUE THREAD

**Issue by Hanmac** [symfony/symfony#23146]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | 3.3.2

Currently as of Symfony 3.3.2 if you got a Form with labels that are not translated, and Translation is enabled, then the Profiler does show them twice,

* Translation > Missing
* Log Messages > Info. & Errors > WARNING

the second one does looks unnessary for me when i got the infomation from the Translation tab.

That thing does made my work a bit complicated when i try to port my stuff to newest PHP and Symfony versions, i thought it was showing Deprecations, but it was only Translation Warnnigs.

**Comment by stof** [comment]
Well, the solution would be to disable the logging of translation errors when you enable the profiler.

Btw, deprecation are separate from warnings in the Logs panel.

**Comment by ogizanagi** [comment]
> deprecation are separate from warnings in the Logs panel.

Indeed, but I admit it's quite annoying in the profiler toolbar, as deprecations and warnings due to missing translations make the `.sf-toolbar-block-logger` block appear with the same color:

![capture d ecran 2017-06-14 a 16 38 40](https://user-images.githubusercontent.com/2211145/27138087-fa7677cc-511f-11e7-8070-9334f211d449.png) ![capture d ecran 2017-06-14 a 16 38 47](https://user-images.githubusercontent.com/2211145/27138088-fa8f14e4-511f-11e7-9b27-a2ff3b84da21.png) ![capture d ecran 2017-06-14 a 16 39 22](https://user-images.githubusercontent.com/2211145/27138125-0d70e7a4-5120-11e7-8209-1b07270cbb3a.png)

So you can indeed miss deprecations or think there are some, while it's only missing translations.

**Comment by ogizanagi** [comment]
I forgot to mention: If you don't really care about logging missing translations and as you already have the collector, you can also disable logging for the translator:

```yml
framework:
    translator: { fallbacks: ["%locale%"], logging: false }
```

**Comment by Simperfit** [comment]
So what could we do in symfony to fix this ? @ogizanagi

**Comment by ogizanagi** [comment]
Perhaps making the `framework.translator.logging` default value `false` instead of `$this->debug`? 
Disabling it only when the profiler is enabled as suggested by @stof? 
Or simply update the translation recipe to set `framework.translator.logging` to false.
