### ISSUE TITLE
[DX] [Asset] Conditional asset referencing

### ISSUE THREAD

**Issue by scaytrase** [symfony/symfony#23163]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.x

As soon as we have a great Encore component which allows us to dynamically require resource files in a chain we should have a possibility to check, whether the resource was generated before including it to the template.

Having a function like `asset_exist` would be nice

```patch
<link rel="stylesheet" href="{{ asset('build/global.css') }}">
+ {% if asset_exist('build/app.css') %}
+   <link rel="stylesheet" href="{{ asset('build/app.css') }}">
+ {% endif %}
```

Original issue and discussion

https://github.com/symfony/webpack-encore/issues/7

**Comment by stof** [comment]
How should this be implemented ? A simple `file_exists` ? This would be incompatible with most features of the component:

- assets may be stored on a CDN rather than locally, requiring a network request to check for existence (you clearly don't want that)
- versioning can either modify the asset path or add a query string. For the query string, you need to avoid it when checking the file, but for a path change, you may need it or no (it depends whether the file is actually renamed on disk or the path-based cache-busting actually relies on webserver rewrite rules to get back the non-versioned name again)
- converting the asset path to a filesystem path (assuming it does not generate a URL pointing to a CDN) still requires to configure the web root, to know how the asset will be resolved to a file (again, can be complex if you want to account for all magic which could happen at the webserver level)

What is the actual use case for this function ? It is quite hard to implement it, based on what `asset()` can do.

**Comment by stof** [comment]
Btw, when using encore, you know exactly what the generated assets are, as you configured them all using `addEntry`, `addSharedEntry` or `addStyleEntry`

**Comment by scaytrase** [comment]
@stof Top-level entries are not a problem. Problem is when chaining with dynamic, especially third-party modules. 

I.e in our practice we have shared front-end package for several sites, and it would be sad to know one day that we've updated the package but forgot to include the generated chained asset.

> How should this be implemented ?

Good question, indeed. Can we check the `manifest` to ensure that asset was generated on compile time? Or can we use some log-like report to know which files were generated? I know this not covers all the cases, but we can use it as the start point.

At this point I like Assetic too much since I can control which files **should be** generated from the source code, not from the external tool

**Comment by stof** [comment]
@scaytrase checking the manifest would work only when using the manifest strategy.





> Problem is when chaining with dynamic, especially third-party modules.
> 
> I.e in our practice we have shared front-end package for several sites, and it would be sad to know one day that we've updated the package but forgot to include the generated chained asset.

what do you mean with `generated chained asset` ?

**Comment by scaytrase** [comment]
@stof You can have a JS asset that requires other JS asset, etc, which requires 3rd-party (or shared) JS asset finally requires SCSS (for example) asset. The fact of compiled CSS file presence depends on fact of requiring SCSS by 3rd-party JS asset, so it can change in the future unattended

**Comment by fabpot** [comment]
I'm closing this issue for the reason explained by @stof.
