### ISSUE TITLE
Error with phpunit

### ISSUE THREAD

**Issue by dorcyv** [symfony/symfony#23183]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

When I lanch phpunit with an empty symfony project (downloaded by symfony installer), I have this error:
```
PHP Fatal error:  Class 'Doctrine\Tests\Common\Cache\CacheTest' not found in /tmp/test/vendor/doctrine/cache/tests/Doctrine/Tests/Common/Cache/ApcCacheTest.php on line 10
PHP Stack trace:
PHP   1. {main}() /home/kipik/bin/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /home/kipik/bin/phpunit:546
PHP   3. PHPUnit\TextUI\Command->run() phar:///home/kipik/bin/phpunit/phpunit/TextUI/Command.php:141
PHP   4. PHPUnit\TextUI\TestRunner->getTest() phar:///home/kipik/bin/phpunit/phpunit/TextUI/Command.php:162
PHP   5. PHPUnit\Framework\TestSuite->addTestFiles() phar:///home/kipik/bin/phpunit/phpunit/Runner/BaseTestRunner.php:65
PHP   6. PHPUnit\Framework\TestSuite->addTestFile() phar:///home/kipik/bin/phpunit/phpunit/Framework/TestSuite.php:394
PHP   7. PHPUnit\Util\Fileloader::checkAndLoad() phar:///home/kipik/bin/phpunit/phpunit/Framework/TestSuite.php:322
PHP   8. PHPUnit\Util\Fileloader::load() phar:///home/kipik/bin/phpunit/phpunit/Util/Fileloader.php:45
PHP   9. include_once() phar:///home/kipik/bin/phpunit/phpunit/Util/Fileloader.php:61
```

**Comment by xabbuh** [comment]
This looks weird. How did you run PHPUnit? Can you provide some steps to reproduce your issue?

**Comment by skalpa** [comment]
You're trying to run the `doctrine/cache` test suite. 

You can't run the tests of composer packages from your project as the `require-dev` and `autoload-dev` sections of their `composer.json` file are not processed when they are used as dependencies (which means in your case that the classes of the `Doctrine\Tests` namespace aren't available).

The `phpunit.xml.dist` configuration file that is supposed to be in your project root folder should tell phpunit to only scan the `tests` folder for tests and not the `vendor` folder as long as you run phpunit correctly by:

making sure phpunit is run from your root folder:
```bash
$ cd /path/to/project
$ phpunit
```

or by specifying the path to the config file when you invoke phpunit:
```bash
$ phpunit -c /path/to/project/phpunit.xml.dist
```

**Comment by dorcyv** [comment]
Okay, my bad.

I just run theses commands: `symfony new test && cd test && phpunit .`

**Comment by nicolas-grekas** [comment]
all is fine to me, at least when running with `./vendor/bin/simple-phpunit`

**Comment by jakzal** [comment]
@dorcyv you should've run ` symfony new test && cd test && phpunit`

Notice there's no dot at the end. By giving the path you're overriding settings from `phpunit.xml.dist`. Passing a dot makes that phpunit will run ALL the tests it can find in the current directory, including vendors.  Since vendors are installed with no dev dependencies their tests might fail like you observed with some Doctrine tests.

If you want to run vendor tests you'll need to clone their repos in an isolated place and install dependencies before running tests.

Otherwise run phpunit in either of the following ways:

```
phpunit
phpunit tests
```

More about tests in Symfony projects can be found in the docs: https://symfony.com/doc/current/testing.html
