### ISSUE TITLE
ResourceNotFound exception is not being handled by onKernelException listener.

### ISSUE THREAD

**Issue by edinchev** [symfony/symfony#23203]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.2

When I go to a route that doesn't exist, a ResourceNotFoundException is thrown but the onKernelException listener I have setup does not handle the exception.

If I `throw new ResourceNotFoundException('test');` in a valid route for testing purposes, the onKernelException listener does get called.

**services.yml**
`    app.exception_listener:
        class: AppBundle\EventListeners\ExceptionListener
        arguments: ['@logger', '@router', '%kernel.environment%', '@ras_flash_alert.alert_reporter', '@twig.controller.exception', '@twig']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }`

**Stack Trace:**
![image](https://user-images.githubusercontent.com/15091453/27196657-5e0c2f5c-51d9-11e7-9657-89a951a28860.png)

**Comment by xabbuh** [comment]
I am not sure if I correctly understand your issue. Where do you throw the exception that is not handled properly? Can you give a reproducing example project?

**Comment by xabbuh** [comment]
Closing due to the lack of feedback. Please leave a comment with more information and we can consider to reopen.

**Comment by NicoHaase** [comment]
@xabbuh / @edinchev: probably, I have the same problem using Symfony 2.8.x. When running my application with PHP 5.6.x, the sf error.log shows the following lines:

`[2017-07-24 15:58:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "WARNING: No route found for "GET /v1/login555"" at /home/niha/projects/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): WARNING: No route found for \"GET /v1/login555\" at /home/niha/projects/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /home/niha/projects/project/app/cache/prod/appProdProjectContainerUrlMatcher.php:370)"} []
[2017-07-24 15:58:17] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Routing\Exception\ResourceNotFoundException:  at /home/niha/projects/project/app/cache/prod/appProdProjectContainerUrlMatcher.php line 370) {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /home/niha/projects/project/app/cache/prod/appProdProjectContainerUrlMatcher.php:370)"} []`

The browser shows a blank page, the network tab shows the error code 500.

Using PHP 7.1.0, the same messages are written to the log, but instead of throwing error code 500 and a blank page, markup is rendered with result code 200 and an error message is printed out indicating:
`( ! ) Fatal error: Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in /home/niha/projects/project/app/cache/prod/appProdProjectContainerUrlMatcher.php on line 370`

**Comment by xabbuh** [comment]
@NicoHaase Would you be able to create small example project that allows to reproduce your issue?

**Comment by NicoHaase** [comment]
@xabbuh: I'd love to, but I can't reproduce it a day later.... strange.... :(
