### ISSUE TITLE
YAML file extension in Symfony4 (Flex)

### ISSUE THREAD

**Issue by jlagneau** [symfony/symfony#23205]
| Q                | A
| ---------------- | -----
| Bug report?      | probably
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.x-dev

With the recent changes regarding the YAML extension in Symfony4 (https://medium.com/@fabpot/symfony-4-best-practices-b4bbd6a9c994), every files in the configurations folder (now `etc`) changed from `.yml` to `.yaml`. When I tinkered a bit with the new version, it appear that it currently suffer of consistency and you need a mix of `.yaml` and `.yml` files depending on their uses. Should that new change apply only in files in `etc` or everywhere (such as the `translations` directory)?

**Comment by stof** [comment]
Don't change it for YAML translations yet, because we haven't yet updated FrameworkBundle to allow the `.yaml` extension for translation files (this will be done before the 4.0 release).

But yeah, the idea is that you will be able to use `.yaml` everywhere supporting YAML file at the end (`.yml` will remain supported).

**Comment by ogizanagi** [comment]
I'd suggest to support it everywhere as a feature in 3.4: #23207

**Comment by stof** [comment]
Yeah, when I said we will do it before 4.0, it would be done in 3.4, as all new features go in 3.4, not only in 4.0
