### ISSUE TITLE
Symfony 3, populating token and refreshing user

### ISSUE THREAD

**Issue by aLkRicha** [symfony/symfony#23215]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.*

I have created small project for describing and reproducing an issue [**symfony-token-issue**](https://github.com/aLkRicha/symfony-token-issue)

**Comment by iltar** [comment]
Okay so if I understand the issue correctly, you change the email of the currently authenticated user and this causes an error because the username is not found which triggers a logout. 

This makes sense though:
 - [In this Controller](https://github.com/aLkRicha/symfony-token-issue/blob/master/src/AppBundle/Controller/DefaultController.php#L45) you bind the currently logged in user to your form. This user, is fetched from the Token.
 - In [the ContextListener](https://github.com/symfony/symfony/blob/7bba83d3d7071605fd36bff083a0ba2f97530364/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L134) Symfony serializes the token back into the session, which contains the same user object as you've bound to your form, which got the values from your post request.

You should probably [avoid binding any objects to forms](https://stovepipe.systems/post/avoiding-entities-in-forms) that are used elsewhere. It's also [a good idea to not store the entity in the security token](https://stovepipe.systems/post/decoupling-your-security-user), to avoid this issue.

This is not a bug but a violation of SRP.

**Comment by xabbuh** [comment]
Indeed, this is not an error as explained by @iltar.
