### ISSUE TITLE
[RFC] Why RegisterListenersPass does not complain when the EventDispatcher is missing?

### ISSUE THREAD

**Issue by Jean85** [symfony/symfony#23265]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | all

Today I struggled a lot with a stupid bug, because I was using the `RegisterListenersPass`, and I was passing the wrong service name for the `EventDispatcher`. If the container complainer with a `ServiceNotFoundException` I would have catched that issue days ago! There's a reason behind this? Could we make this change?

```diff
// Symfony\Component\EventDispatcher\DependencyInjection\RegisterListenersPass

    public function process(ContainerBuilder $container)
    {
        if (!$container->hasDefinition($this->dispatcherService) && !$container->hasAlias($this->dispatcherService)) {
-            return;
+           throw new ServiceNotFoundException($this->dispatcherService);
    }
```

Obviously we can think of a more convoluted solution, but still this issue remains, IMHO. And 4.x is coming, so a BC wouldn't be an issue here.

**Comment by jakzal** [comment]
This is a common approach to make compiler passes optional. If the dispatcher is not present, the compiler pass won't be run. Most of compiler passes follow this approach. 

Historically, the `RegisterListenersPass` compiler pass has been a part of the HttpKernel component, but was later moved to EventDispatcher (see #9792). Perhaps this check doesn't make sense anymore.

**Comment by stof** [comment]
Well, for the event dispatcher, FrameworkBundle does not register the service conditionally. So we might change it. But most compiler passes need to keep the silent skipping, due to features being optional (and so the compiler pass must not fail if the DI extension has not registered the service).
starting to make 1 or 2 passes fail loudly in this case opens the door to broken contributions changing other compiler passes while they should not be changed (most features in FrameworkBundle are optional)

**Comment by nicolas-grekas** [comment]
Same reasoning as @stof: I'd vote to close as "won't fix" personally.

**Comment by xabbuh** [comment]
agreed too, closing here
