### ISSUE TITLE
Console: Infinity and NaN not shown as default value

### ISSUE THREAD

**Issue by jkufner** [symfony/symfony#23267]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | v3.1.5

Code in SomeCommand::configure():

`````
$this->addOption('limit', null, InputOption::VALUE_REQUIRED, 'Max number of items', INF)
`````

Then  --help shows following line:

`````
      --limit=LIMIT              Max number of items [default: ]
`````

Notice the missing default value. I would expect `[default: INF]` or `[default: ∞]`.

The same situation is with NAN.

**Comment by ogizanagi** [comment]
Makes sense to me (at least for `INF`, I don't see use cases for `NAN` as a default value actually). The text and json descriptors are affected by this issue due to the use of `json_encode`, as there is no equivalent in json for those values. Xml and markdown ones should be fine, as they use `var_export`.

Note this is only my opinion, not a decider's one. But it might be worth for you trying to submit a PR.

**Comment by xabbuh** [comment]
Creating a fix for `INF` looks reasonable to me.

**Comment by xabbuh** [comment]
see #23345
