### ISSUE TITLE
[Symfony 2.8] The log handler "rotating_file" has an unusual behavior

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony#23298]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8.7

Here is my configuration about monolog

    monolog:
        log_a:
            type: rotating_file
            path: /path/to/a.log
            level: debug
            channels: ['channel_a']
            max_files: 30
        log_b:
            type: rotating_file
            path: /path/to/b.log
            level: debug
            channels: ['channel_b']
            max_files: 15

Normally, there should be up to 45 log files. But the 31st log file will be created repeatedly when there are 30 log files. And never creates the 32nd log file.

Sorry for my bad english.

**Comment by jakzal** [comment]
@zacharyzh your English is perfectly fine, no need to apologise.

The MonologBundle merely [configures monolog services](https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/MonologExtension.php#L308), so if you think the [rotating file handler](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RotatingFileHandler.php#L124) misbehaves I think it should rather be reported to [monolog](https://github.com/Seldaek/monolog).

However, I just tested it and it seems to be behaving as expected (keeps configured max files per handler). Perhaps the bug was already fixed. Note that the handler will rotate file once a day.
