### ISSUE TITLE
Autowire: Try with variable name in case of doubt

### ISSUE THREAD

**Issue by ScreamingDev** [symfony/symfony#23346]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3.z

I am having this class and want to autowire it:

```


use SimpleBus\Message\Bus\MessageBus;

class AddressController
{
    /**
     * AddressController constructor.
     *
     * @param MessageBus        $commandBus Bla bla (e.g. simple_bus.command_bus)
     */
    public function __construct(MessageBus $commandBus)
    {
        // ...
    }
}
```

But it errors with:

>  argument "$commandBus" of method "__construct()" references interface "SimpleBus\Message\Bus\MessageBus" but no such service exists. You should maybe alias this interface to one of these existing services: "simple_bus.command_bus", "simple_bus.event_bus".

I understand this and like to add a feature request.

Put in some additional strategy to autowire services like:

- Variable name can be found in the service name (e.g. `$commandBus` in "simple_bus.command_bus").
- DocComment tells which service to use (e.g. `Bla bla (e.g. simple_bus.command_bus)` ).
- or `@see simple_bus.command_bus`

I guess there is some more or better to look up.

**Comment by weaverryan** [comment]
>* Variable name can be found in the service name (e.g. $commandBus in "simple_bus.command_bus").

This is too magic and unpredictable, so we definitely cannot do it
>* DocComment tells which service to use (e.g. Bla bla (e.g. simple_bus.command_bus) ).
>* or @see simple_bus.command_bus

I proposed the ability to wire via annotations awhile ago, but it wasn't widely liked: https://github.com/symfony/symfony/pull/21376

@ScreamingDev Is there a reason why you don't want to add the alias to `services.yml` so that this works?

```yml
services:
    # ...

    SimpleBus\Message\Bus\MessageBus\MessageBus: '@simple_bus.command_bus'
```

**Comment by ScreamingDev** [comment]
Example:

```
services:

  AddressController: ~
  SomeWhatController: ~
```

While `AddressController` needs `@simple_bus.command_bus` as `SimpleBus\Message\Bus\MessageBus\MessageBus`
and `SomeWhatController` wants `@simple_bus.event_bus` for some reason.

On bigger scale with more services implementing one interface this alias would fail.
Writing one YML per implementation would be a solution but this is as much effort as not using autowiring at all.

My sum up would be now: autowiring gives me some shortcuts but when an app becomes more complex it's completely lost.

**Comment by nicolas-grekas** [comment]
:-1:, autowiring should not do any guess. All current guessing logic is deprecated.

**Comment by theofidry** [comment]
@ScreamingDev the you just have to manually wire that argument, simple and clear

**Comment by javiereguiluz** [comment]
I'm 👎  too. @ScreamingDev at first I liked your idea ... but the promise we made with the autowiring feature is to only provide "automation", not "magic". Unfortunately this feature feels like magic and can lead to hard-to-debug issues when the guessing mechanism doesn't work as expected.

I'm closing as "won't fix" because of the downvotes.
