### ISSUE TITLE
User Deprecated: The "Twig_Profiler_Dumper_Text" class is considered final. It may change without further notice as of its next major version.

### ISSUE THREAD

**Issue by Korikulum** [symfony/symfony#23383]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.x

The twig profiler panel (`/_profiler/{id}?panel=twig`) logs the following deprecation notice:
```
User Deprecated: The "Twig_Profiler_Dumper_Text" class is considered final.
It may change without further notice as of its next major version.
You should not extend it from "Twig_Profiler_Dumper_Html". at
/var/www/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php:177
```

**Comment by stof** [comment]
This is an issue in Twig itself, which has already been fixed by https://github.com/twigphp/Twig/pull/2513, but not yet released (see https://github.com/twigphp/Twig/issues/2521 asking for it).

I'm closing this issue as there is nothing to do in Symfony about this (both impacted classes are part of Twig)
