### ISSUE TITLE
framework.cache.pools and namespaces

### ISSUE THREAD

**Issue by thewilkybarkid** [symfony/symfony#23438]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | next

`framework.cache.pools` seems to allow for configuring everything that using the `cache.pool` tag does except for `namespace`. It'd be useful to use an expression too.

(My use case is https://github.com/elifesciences/journal/pull/652, where I'm adding a compiler pass to set the namespace.)

Related, I'd quite like to extend the values used to seed a generated namespace, rather than setting the namespace explicitly (I don't care what the namespace is; I'm adding package versions to the namespace to invalid the cache whenever they update). So it would be useful to have an option pass in an array of strings instead.

This could lead to something like:

```yaml
cache.guzzle:
    adapter: cache.app
    clearer: ~
    default_lifetime: 31536000 # 1 year
    namespace_seed:
      - '@=package_version("guzzlehttp/psr7")'
      - '@=package_version("kevinrob/guzzle-cache-middleware")'
    public: true
```

**Comment by nicolas-grekas** [comment]
did you look at the `prefix_seed` config option? it's "global", but is it good enough for your use case?

**Comment by nicolas-grekas** [comment]
note that if not, PR is welcomed :)

**Comment by thewilkybarkid** [comment]
Will open a PR for the first part.

Looking at using expressions here, seem like using them in this way was rejected? https://github.com/symfony/symfony/issues/9658

**Comment by nicolas-grekas** [comment]
Not sure we should do anything here: the simple approach of exposing the namespace to config is just asking people to find *two* names for their pools (the name of the pool, and its service), which looks just annoying, and the more advanced case of seeding the namespace is perfectly possible with a compiler pass as your demonstrated.

Thus, we may close this one?

**Comment by johnecon** [comment]
This would help with applications migrating to Symfony.
We could use the same cache keys if only we were able to configure namespaces.

**Comment by flaushi** [comment]
Oh, I am facing a similar problem, just described at [SO](https://stackoverflow.com/questions/55271509/symfony-redisadapter-has-different-internal-cache-keys-depending-on-app-environm)
I would be very grateful if somebody could help me :)

**Comment by d-ph** [comment]
@nicolas-grekas 

Hi,

Apologies for reviving a discussion from 2017 but I've just came across a similar use case where it would be helpful (and intuitive) to be able to configure a complete cache namespace on a cache.pool config level.

It appears that nowadays it's possible to create a manualy-namespaced cache pool by using the following service definition:
```yaml
services:
    my_app.cache.adapter.redis:
        parent: 'cache.adapter.redis'
        tags:
            - { name: 'cache.pool', namespace: 'my_custom_namespace' }
```
However it pales in comparison to just being able configure a cache pool's namespace manually in the ordinary cache pools part of the config:
```yaml
framework:
  cache:
    pools:
      my_cache:
        namespace: 'my_custom_namespace'
```
The added bonus of being able to do this on the cache pool config level, is that the usual cache pool autowiring based on a cache pool's name JustWorksTM.

You mentioned that having a namespace config item on a cache pool level would confuse/annoy devs, as they would need to come up with two names for their caches. I personally am not fully able follow that argument because:

1. Devs would not customarily use the "namespace" config item. They would discover it only once they actually realise that they want to opt out of the default namespace hashing mechanism offered by the Cache Symfony component. So at the time they discover that config item, they would not be burdened/annoyed -- on the contrary: they would rejoice that there is a simple way to resolve their simple problem.
2. It could be clearly emphasised in the Symfony docs that the "namespace" config item makes a cache pool fully opt-out of the default namespacing mechanism, and that it should likely be used only when the mechanism is not fit for one's particular need/purpose.
3. For auto-documenting purposes, the "namespace" config key could instead be called "namespace_override", or "manual_namespace".

---

On top of the above, I second what the OP said that it would also be very useful to add an additional "prefix_seed" on cache pool config level that would apply to a particular cache pool only, not globally. This in fact would reduce the number of cases where a dev would need to resort to a complete "namespace override". It could also be made in the configuration "compilation" that having both "prefix_seed" and "namespace" config items on a single cache pool is disallowed.

---

For completeness: my particular use case is that I wish to have a few cache pools that are namespaced with the timestamp of the webapp deployment, so that the cache pools are guaranteed not to share cached data between deployments. At present I resorted to defining cache pools the hard way as "services:", but it took me _a lot_ of time to find this solution and fully understand how it compares to cache pools defined under framework.cache.pools. I found this process to be very "in my way", instead of "working with me".

Thank you.
