### ISSUE TITLE
In windows 10, displays error after generating new bundle from command line

### ISSUE THREAD

**Issue by pdeekerongi** [symfony/symfony#23504]
ClassNotFoundExceptionAttempted to load class "TestBundle" from namespace "TestBundle".Did you forget a "use" statement for "Symfony\Bundle\FrameworkBundle\Tests\Functional\Bundle\TestBundle\TestBundle"?

in AppKernel.php (line 19)

**Comment by Noa83** [comment]
got exactly the same problem...

**Comment by Noa83** [comment]
@pdeekerongi , I had the same problem. I found the answer [on this link](https://openclassrooms.com/forum/sujet/probleme-de-namespace-symfony-3). Go to the maels1991's answer, it's the good way and it worked for me.

**Comment by javiereguiluz** [comment]
@pdeekerongi thanks for reporting this issue and @Noa83 thanks for providing a solution for this. 

I've moved this issue to https://github.com/sensiolabs/SensioGeneratorBundle/issues/563 because that's repository where we develop the tool that generates things like bundles. Hopefully this will be fixed soon. Thanks!

**Comment by pdeekerongi** [comment]
@Noa83
Thank you for the solution!
