### ISSUE TITLE
[RFC] Remove ConstraintViolationList

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#23531]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

Another proposal to simplify things originated in the [Symfony Slack](https://symfony.com/support). I reproduce the relevant conversation:

| user | message
| --- | ---
| **ostrolucky** |  I would remove ConstraintViolationList. It just replicates array functionality. And does it poorly. This unneeded abstraction worsens DX.
| **sstok** | I don't agree as it does more then that, like string casting, it ensures you always get list of Violations. and `findByCodes()`. <br><br> Not to mention that with an array you need to use pass-by references to allow adding without return.
| **ostrolucky** | String casting violates the interface. <br><br> `findBycodes()` is a sign of limitations of `ConstraintViolationList` (can't easily use array_ functions) <br><br> Ensuring you get list of Violation is done by `ExecutionContext` anyway <br><br> Adding without return - how useful is that instead of calling `ExecutionContext->addViolation()` and isn't current trend to limit mutability?

**Comment by ro0NL** [comment]
I dont like the interface actually :P `ConstraintViolationListInterface`.

If we remove that `ConstraintViolationList` gets more value. Also not sure about need for `\ArrayAccess`, `get()` and such.

**Comment by ostrolucky** [comment]
Related: https://github.com/symfony/symfony/issues/11939

If ConstraintViolationList was removed, we could then do:
```php
if (!$validator->validate('', [new NotBlank()]) {
    // handle invalid state
}
```

Removing IMO wouldn't even break most applications, since most common usage is just iterating over it and using `count()`.

Additional advantages:
- immutability, passing list of violations all over application will no longer allow modifying them inside object which stores this list
- Easy checking if violation list contains violations without having to iterate over it/counting/accessing getIterator->valid()
- Direct usage of `array_` functions instead of wrapping list of violations in `iterator_to_array`
- More transparent API (getting ConstraintViolationList is currently hidden behind `getViolations`, more transparent would be `getConstraintViolationList`)
- Eliminating "slippery slope" we got into when `findByCodes` was introduced. Since this was introduced, users will expect to accept even more filtration methods.

Lost features:
1. Removed `__toString()` This method is marked as for development only and doesn't respect interface anyway. Solution is to advice users to replace it with `join(',', $validator->getViolations())` which is better solution all around
1. Removed `findByCodes` This method currently creates slight inconsistency, because since it's immutable, adding constraintViolations into the returned object does not add these violations to validator, as compared to ConstraintViolationList's got in any other way. Replacement: `array_filter($violations, function($violation) use ($codes) { return in_array($violation->getCode(), $codes); });`

___
But hey, good enough would be just removing pretty useless `\ArrayAccess` interface, implementing `hasViolations()` and `toString()` and making getters for violationList immutable

**Comment by ogizanagi** [comment]
No strong opinion about this right now, but note it'll complicate things for https://github.com/symfony/symfony/pull/22150. I'm sure there are similar use-cases in the wild so I'm not sure it's worth it.

**Comment by ostrolucky** [comment]
Yeah... I think even I no longer want to completely remove it

**Comment by javiereguiluz** [comment]
Closing it because even the original user proposing this idea no longer thinks it's the best thing to do. Thanks!
