### ISSUE TITLE
Debug toolbar error more than one subcontroller

### ISSUE THREAD

**Issue by Kleinast** [symfony/symfony#23543]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Hi,

I have one main controller, rendering a view, in this view I render(controller()) 2 times, not the same controller. In simpliffy, I have something like:

   ``` twig
 <div class="generic-content contrat">
        {{ render(controller('AppBundle:Contrat:blockEcontrat')) }}
    </div>

    <div class="generic-content contrat">
        {{ render(controller('AppBundle:Contrat:blockAmountsReceived')) }}
    </div>
```
My subcontroller only return empty template or empty Response (I tried whith both)

In this case, the debug toolbar crash, show message "An error occurred while loading the web debug toolbar. Open the web profiler." and when I click on it, I get Token not found.
Wird things is when I comment one of render, the toolbar work fine. It only happen when there is more than one render(controller()) on my template.

**Comment by javiereguiluz** [comment]
@Kleinast thanks for reporting this.

The reason of the error can't be the use of two or more `render(controller())` because I use that in several Symfony apps and it works (for example, some pages of `symfony.com` make more than 2 `render(controller())` class in the same page).

This is probably a fatal error or exception in any of the rendered controllers. Try to remove one of them alternatively and see if it works. I'd also recommend to do some `dump()` in the controller code to find where the error happens.

**Comment by Kleinast** [comment]
I already try, if I comment one of the render (one or the other) it work, so It really not seem to be error from my controller content (plus they only html twig empty template).
I tried to move this simple code to new fresh install and seem work, maybe be one bundle cause that fail.

I will dig this clue, thanks for the track @javiereguiluz

**Comment by Kleinast** [comment]
It seem update symfony to 3.3.5 resolve my problem.

Thx for your time and your help.
