### ISSUE TITLE
[DI] Use variadics for autowiring tagged services

### ISSUE THREAD

**Issue by wjbLabs** [symfony/symfony#23608]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | not sure
| RFC?             | yes
| Symfony version  | 3.3.5

Although a [documentation ](https://symfony.com/doc/current/service_container/tags.html)doesn't describe it, tagged services can be injected via
```php
$definition->replaceArgument(1, $arrayOfTransportDefinitions);
```

In all of cases I worked, a service would ever accept only one type of tagged services. Can this be used to have services autowired like this:
```php
class TransportChain
{
    public function __construct(LoggerInterface $logger, TransportInterface ...$transports)
    {
        // ....
    }
````

This way user would not have to write compiler pass, giving better experience. The con is lack of injecting multiple tagged services but I don't think users do it anyway.

**Comment by ro0NL** [comment]
See #22200

What about an additional !variadic / VariadicArgument. In the same spirit as !iterator / IteratorArgument.

With tagged services it would look something like;

```yaml
'$arg': !variadic !tagged-services tag
```

**Comment by wjbLabs** [comment]
I was thinking about having injected tagged services without any extra code in ``services.yml`` (as long as autowire=true) or extra compiler pass.

**Comment by nicolas-grekas** [comment]
That implies that we're able to compute a collection of `TransportInterface`.
But that's impossible, we don't do that anytime (and if autowiring does some sort of reflection, that's a deprecated feature, because it's a too fragile behavior).
Let's say we are able to create a list of such services, how would you compute it? The only algo I can think of is: do reflection on all defined services and create the list of all services that implement that interface.
That is extremely fragile also, and forbids any fine tuned behavior. There are many cases where that criteria (the interface some class implement) is not enough to be turned into a collection.
#22200 is a much more tailored solution, one that requires an explicit opt-in into such a behavior. A requirement to me.

**Comment by ro0NL** [comment]
Agree; to me the bare minimum is having extra config in services.yml, i dont see how it relates to autowiring at first.

The only "auto" thing i can think of is some typehint sniffing, ie technically we could this;

```php
public function __construct(array $a, iterable $b, ...$c) { }
```

```yaml
'$a': [1,2,3]
'$b': [4,5,6]
'$c': [7,8,9]
```

I think that's intuitive, though magic-ish. I believe this conflicts with @nicolas-grekas concern;

> one that requires an explicit opt-in into such a behavior. A requirement to me.

But how i see it is; you configure a sequence; you ask for a sequence. Enough for DI to process :)

**Comment by GuilhemN** [comment]
Just as a side note, if I remember well, chaining tags (in `'$arg': !variadic !tagged-services tag`) is not allowed.

**Comment by nicolas-grekas** [comment]
as explained, I'm :-1:
