### ISSUE TITLE
Missing docs for symfony/web-link component - Unknown "preload" function

### ISSUE THREAD

**Issue by insekticid** [symfony/symfony#23643]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Missing docs page for https://github.com/symfony/web-link component (https://symfony.com/doc/current/components/weblink/introduction.html)

I am trying Symfony Flex with templating enabled.
I would like to use `preload` twig function but I have got exception 
Twig_Error_Syntax HTTP 500 Internal Server Error Unknown "preload" function.

I had to looked into https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L61

and found, that I have not installed `web-link` component 

Simple fixed via 'compose req symfony/web-link' - create simple docs for this feature

http://symfony.com/blog/new-in-symfony-3-3-asset-preloading-with-http-2-push

**Comment by javiereguiluz** [comment]
@insekticid thanks for reporting this. I see here two different problems:

* WebLink component is not documented (we're taking care of that here: https://github.com/symfony/symfony-docs/issues/7515)
* When using Flex, nothing is installed by default and you must execute "composer req ..." whenever you use a new feature. We'll take care of that when updating the entire Symfony Docs. But it will take us some time.

In any case, I'm closing this issue because it's mostly related to Symfony Docs and we already have other issues for it. Thanks!
