### ISSUE TITLE
[Routing] Add to defaults dynamic variables

### ISSUE THREAD

**Issue by EneasVVA** [symfony/symfony#23691]
Eventually programmers need use dynamic variables in yaml routing descriptors, should be something like this:

back.api.detail:
    path: /api/{category}/{file}.{format}
    defaults: { _controller: 'topics.v1.controller:topicsDetailAction', section: '/api/{category}' }

| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

**Comment by sstok** [comment]
Can you explain what your problem is, and what you propose to solve this because your current description isn't very helpful. Also please use Markdown for your code examples (see GitHub help) to ensure correct display.

If you are talking about a route's defaults that can have dynamic values (eg. an expression) I would vote yes for this. As it would make defaults for a host requirement much easier `defaults: { tld: '@request.attributes.get("tld", 'nl')' }`. But there is properly some limitation that I'm not considering 🤔.

**Comment by EneasVVA** [comment]
Yes, I'm talking about defaults dynamic values like you did.

**Comment by nicolas-grekas** [comment]
I think this is not something that the router should deal with, but the controller.
Adding this to the controller is going to add a new level of complexity we'd better not add IMHO.

**Comment by Tobion** [comment]
I agree with @nicolas-grekas
