### ISSUE TITLE
[RFC][Cache] RedisTrait

### ISSUE THREAD

**Issue by arnaspet** [symfony/symfony#23702]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | ?

RedisTrait has private property `$redis` as well as method `pipeline`, so changing `doSave` or do `doFetch` methods becomes pain as you need to override constructor & copy-paste pipiline to extended class. My suggestion is as simple as it gets to make them `protected`. Willing to do a PR

**Comment by nicolas-grekas** [comment]
Since this is a trait, can't you just use it to create a new adapter if you need to?

**Comment by arnaspet** [comment]
well i would still need to copy-paste pipeline method, right?

**Comment by nicolas-grekas** [comment]
Why? the trait is automated copy/paste, isn't it? you can rename it while doing the use for the trait, and re-implement the pipeline method if that's what you want.
See http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict
Not that the trait is internal, so that's not a BC guaranteed way. But it'll work for the foreseeable future.

**Comment by arnaspet** [comment]
oh, Sorry never actually used traits in real life scenarios, can you explain why you chose traits for this exact problem?

**Comment by nicolas-grekas** [comment]
I don't know what "this exact problem" references to :)
But I can tell that a trait is used here because that exact same implementation is required for both RedisAdapter and RedisCache classes, and traits where created exactly for this problem, "behavior reuse".
See https://wiki.php.net/rfc/horizontalreuse for some background.

**Comment by nicolas-grekas** [comment]
Closing as there doesn't seem to be anything left to do here.
