### ISSUE TITLE
Question about Lock component

### ISSUE THREAD

**Issue by AyrtonRicardo** [symfony/symfony#23764]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

I was trying to use the symfony lock component, but I didn't found any stable version. What's the reason for this? 

Exists any alternative to use this component without `minimum-stability = dev` tag in `composer.json`?

**Comment by gharlan** [comment]
It will be released with 3.4: https://github.com/symfony/symfony/issues/22580

**Comment by chalasr** [comment]
@gharlan is right. 
So the answer is no, if you want to use `symfony/lock` right now you have to require it in its `3.4.x-dev` version. 
Note that it has been postponed to 3.4 for having time to make the package itself and its framework integration stable so, as for any non stable requirement, you are on your own when using it since we could very well break things until 3.4 gets stable.
