### ISSUE TITLE
[RFC] Add static method + interface to get command names at compile time

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#23796]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.4

With PSR-4-based service definitions, we can declare command as services. But this doesn't provide laziness for them, because we don't know their name at compile time.

To enhance that, what about adding a new static method + related interface to commands, ?
Eg.
```
public static function getDefaultName()
{
    return 'foo:bar';
}
```

That would also enable auto-configuration of commands. The method would be called to fill in the "name" attribute of the "console.command" tag when none is set.

ping @chalasr

**Comment by javiereguiluz** [comment]
Instead of just defining the name, we could define the entire command signature ([like Laravel does](https://laravel.com/docs/5.4/artisan#defining-input-expectations)). This would save us all the verbosity required to define a command.

**Comment by nicolas-grekas** [comment]
@javiereguiluz, creating a DSL for command configuration is something else, that's for another RFC :)

**Comment by ro0NL** [comment]
why the new interface? we can simply add this to Command no?

**Comment by chalasr** [comment]
This has been suggested by @weaverryan and briefly discussed in #22734.  
from https://github.com/symfony/symfony/pull/22734#issuecomment-303354763:
> @chalasr please don't make things static. This is even worse for configurability, as you cannot make the name configurable anymore in commands (while it is currently), except by using some global static state (which is very bad), and only if you don't register the same command class multiple times with different names (and different instances of your deps, which is the use case for registering multiple times)
[...]
Thus, it will be almost impossible to write a good migration path for this: you cannot make the default implementation of the static method call the existing code, as static cannot call non-static code; so it means you still have to allow commands not implementing this static-based interface everywhere in the code.

The idea is not to replace the tag nor to make Application aware of this method but just to fill the tag attribute by calling it from the pass.
Commands relying on this interface could not be used for more than 1 service. Given this is all about auto discovered/configured commands, I think it's not an issue. Explicit configuration would always win so that If one wants to reuse a command for another service, then one has to fill the tag attribute for this service.

👍  as it makes laziness accessible to autoconfigured commands.

**Comment by ro0NL** [comment]
> Explicit configuration would always win

But  `getName` doesnt always win from `getDefaultName`, which may be confusing. I think that's a documentation issue =/

> Commands relying on this interface

:S wouldnt `getName()` be something like `return $this->name ?? static::getDefaultName()`?

**Comment by nicolas-grekas** [comment]
@chalasr thanks for the link. There is no pb to me to make this static method if it is really an easilly overrideable default, which is what I'm suggesting to do. You can think of it like an annotation that is parseable by PHP itself.

**Comment by chalasr** [comment]
Going to pick this one. 
Not sure I can expect anything but... any hint on how could this interface be named would be nice :)

**Comment by nicolas-grekas** [comment]
DefaultNameProviderInterface
