### ISSUE TITLE
[VarDumper][DX] Selectively disabling control characters alternatives / allowing to copy real code

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony#23921]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Currently VarDumper (specifically `\Symfony\Component\VarDumper\Dumper\CliDumper`) replaces common control characters with their visible representation. There's however a problem with this approach - copied result is unusable without manual modification.

![default_dump](https://user-images.githubusercontent.com/1227834/29419625-3170952c-8335-11e7-93d7-a31708801c0a.png)

I was thinking about solving the problem. For new lines solution will be bare simple - giving some control over `\Symfony\Component\VarDumper\Dumper\CliDumper::$controlCharsMap`, which easily let's the developer to create print like the one below:

![copy_dump](https://user-images.githubusercontent.com/1227834/29419685-589db26a-8335-11e7-9325-450649c0534f.png)

This solution however is slightly hacky in my opinion, since in order to achieve such result I had to create such definition:

```php
    protected static $controlCharsMap = array(
        "\t" => '\t',
        "\n" => "",
        "\v" => '\v',
        "\f" => '\f',
        "\r" => '\r',
        "\033" => '\e',
    );
```

Maybe there's a way to make just copying usable? In HTML we can offer option to copy raw string, without any enhancements like control characters replacement. For CLI there's no such way unfortunately...

Do you have any ideas how to improve DX of this functionality?

**Comment by nicolas-grekas** [comment]
this is difficult because there are conflicting expectations: displaying control chars is done for DX also, to help see invisible chars - which shouldn't be invisible when debugging.

> giving some control over CliDumper::$controlCharsMap

you already have control over it since the property is protected, but that requires you to extend the dumper class and use it instead. Might be enough, or not, depending on your use case.

in HTML, what about using adding `user-select: none` to `.cchr`?
Maybe that's enough to fix this "issue"? That would leave CLI out - but again, displaying invisible chars is an important  feature to me so that "selection" maybe not enough a reason to not display them - even conditionally.
