### ISSUE TITLE
[Forms] EntityType not updated to null

### ISSUE THREAD

**Issue by JurajMlich** [symfony/symfony#23961]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes
| Symfony version  | 3.3.6

Got a problem with the EntityType form class, specifically with the null value. My configuration of the field looks like this:

`->add('parent', EntityType::class, [
                'class' => SupportSection::class,
                'choice_label' => 'name',
                'required' => false,
            ])`

I use it with an entity from the database that has already some parent set (not null). **When I only change the parent to null in the form (by selecting the empty value) without changing some other fields, the parent is left with its original value** (the form gets submitted and is valid), parent does not get set to null. When I want to set the parent to null, I have to change some other property as well. Setting to non-null value works fine.

The request post data:
![screen shot 2017-08-23 at 13 45 49](https://user-images.githubusercontent.com/6961904/29614161-7160b4fe-8809-11e7-98eb-88f6358bb27a.png)

And the generated select:
![screen shot 2017-08-23 at 13 46 46](https://user-images.githubusercontent.com/6961904/29614189-8a88168e-8809-11e7-8fc6-bd61ae935c8a.png)

I think that it really is a bug. Thank you for having a look :-)

**Comment by JurajMlich** [comment]
I tracked it down. The correct null value is set, however in Form:667, dispatcher is called invoking ValidationListener which calls $this->validator->validate($form) on line 55 that changes the parent back to the original value.

**Comment by JurajMlich** [comment]
The problem appears to be in UniqueEntityValidator, method validate. I have a unique constraint on the slug field. After that method, the parent is restored. Going to track where exactly it is restored during the execution in the method.

**Comment by JurajMlich** [comment]
OK, the problem is in UniqueEntityValidator:145. It tries to load an entity that has the same slug as my original entity but appereantly it just finds itself and therefore the parent value is refreshed. 

Any way to prevent that? I really need to get this working today.

**Comment by JurajMlich** [comment]
OK and the very last piece of information, it happens only if the property (used in EntityFiled) is set as EAGER, not being lazy loaded :(

**Comment by xabbuh** [comment]
@JurajMlich Would you be able to create a small example project that allows to reproduce your issue?

**Comment by JurajMlich** [comment]
Sure, give me few minutes.

**Comment by JurajMlich** [comment]
https://github.com/JurajMlich/symfony-bug 

Set up:
1. Generate MySQL database scheme (php bin/console doctrine:schema:update --force)
2. add two rows:

![screen shot 2017-08-24 at 10 58 39](https://user-images.githubusercontent.com/6961904/29658465-36ef7208-88bb-11e7-920e-3226100316db.png)
3. DefaultController:23 - change id to the row with parrent
4. open web, you should see something like:

![screen shot 2017-08-24 at 11 00 26](https://user-images.githubusercontent.com/6961904/29658530-78f04998-88bb-11e7-95f5-5f704f990f0a.png)

6. set select element to empty and save
7. as you'll see, it prints the old id, the field is not set to null (in form correct value remains, but after redirect it'd have been lost, since the row in the database is not changed to null)
8. change slug as well and save - you'll see, that now the parent field gets changed

In case of any questions, feel free to contact me. I'll as much as I can .-)

**Comment by JurajMlich** [comment]
Any updates?

**Comment by liweiyi88** [comment]
I tried to debug a little bit and find the "issue" (personally, I don't think it is a real issue and it actually has nothing to do with Symfony Form) reported by @JurajMlich is caused by one line of code of UniqueEntityValidator, see [the line](https://github.com/symfony/symfony/blob/67a58c9c3e24907c4d2e21f7d0ec6149354c7161/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L142). You can play with the demo provided by @JurajMlich and use dump() function to see the differences before and after this line by 
```
dump($entity);
$result = $repository->{$constraint->repositoryMethod}($criteria);
dump($entity);
die;
```
Then you will see the $entity object has been "reset". 
`$repository->{$constraint->repositoryMethod}($criteria);` is simply to call the `findBy` method of EntityRepository but the thing we need to understand here is why the `findBy` method of doctrine repository class can change the state of an object. Personally, I guess it is because the $entity has already been loaded in the UnitOfWork at this stage, then calling `findBy` method again with`EAGER` mode will let UnitOfWork reload the $entity object (as it is `EAGER` mode, the findBy('slug' => 'YOUR_NUMBER') will also fetch the parent before any update).

Can any doctrine expert give us any more details?
BTW,  someone had the similar problem before and he suggested to not use `EAGER` [post](http://jayroman.com/blog/be-careful-with-doctrine-magic-and-symfony2)

**Comment by JurajMlich** [comment]
Exactly as I have written :P

**Comment by xabbuh** [comment]
I am going to close here as this is something that is related to how Doctrine behaves when you make use of eager loading. Either disable eager loading for your associations or create a custom repository method that you use in your unique constraint that does not use eager loading.
