### ISSUE TITLE
multiline @Route annotation requires asterisk and/or whitespace prefix

### ISSUE THREAD

**Issue by hlb-schmidt** [symfony/symfony#24019]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | maybe boils down to
| BC Break report? | a what now?
| RFC?             | no thank you
| Symfony version  | 3.3.6

these do not work, but (imo) should:

```
/**
@Route("/foo")
*/
```
```
/**
	@Route("/foo")
*/
```
> one tab character

these do work:

```
/**
* @Route("/foo")
*/
```

```
/**
*@Route("/foo")
*/
```

```
/**
 @Route("/foo")
*/
```
> one whitespace character

**Comment by iltar** [comment]
Annotation parsing is not a Symfony library though. When used, it's done by https://github.com/doctrine/annotations

**Comment by javiereguiluz** [comment]
@hlb-schmidt I'm afraid that @iltar is right. The logic to parse annotations is out of the reach of Symfony because we use an external library. Please report your issue in https://github.com/doctrine/annotations/issues

By the way, in theory the `@` character may be preceded by `*` or a white space or a tab. See https://github.com/doctrine/annotations/blob/2497b1f9db56278d3ad2248f9e4bdbbbaa271c3e/lib/Doctrine/Common/Annotations/DocParser.php#L372
