### ISSUE TITLE
[DX] A simpler way to define custom error pages

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24049]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

[How to Customize Error Pages](https://symfony.com/doc/current/controller/error_pages.html) in Symfony apps has bugged me since day one. In the past we could understand why it worked that way. But now that [Twig is a first class citizen](https://symfony.com/blog/new-in-symfony-2-7-twig-as-a-first-class-citizen), in-app bundles are gone and [bundle inheritance is in question](https://github.com/symfony/symfony/issues/24048) we could reconsider this.

### The Proposal

Make Symfony/Twig/TwigBundle look for in the `templates/error/` directory for custom error pages, and keep using the same logic to pick the template (`error500.json.twig`, `error.xml.twig`, etc.)

This change could be made for Symfony 4.0, which introduces the new `templates/` directory at project root, but we may need to deprecate or change something in Symfony 3.4 in preparation for that.

**Comment by Pierstoval** [comment]
If the `templates/error/` directory is customizable via an option in the TwigBundle, I'm totally ok 👍

**Comment by yceruto** [comment]
I think it should be a general convention, I mean, not only for TwigBundle's errors templates. Although each bundle is free to add its own custom Twig's path.

There is an open PR https://github.com/symfony/symfony/pull/23339 proposing to move them to `templates/bundles/Twig/Exception/*.html.twig` by convention.

**Comment by javiereguiluz** [comment]
@yceruto I agree with what you say, but considering that 100% of real projects need to customize the error pages, why not making that simpler? If the only way to customize is `templates/bundles/Twig/Exception/*.html` then I need to learn that errors are in fact exceptions, that they are handled by "a thing" called TwigBundle, I need to learn what a bundle is, I need to learn how to override the templates of a bundle, etc.

This proposal could be compatible with your proposal too. Want to customize error pages fast? Create `templates/error/...` Do you prefer a more strict approach? Use the native Symfony mechanism to override templates: `templates/bundles/Twig/Exception/*.html`

That way we could solve @Pierstoval issue too: you can either use the simple and fast path (`templates/error/`) or you can use the standard overriding mechanims (but no other option is provided).

**Comment by Pierstoval** [comment]
There is something really important too:

Even if `templates/error` becomes customizable (and maybe configured by default in TwigBundle's recipe for DX), you will be able to load the "parent" template or blocks, which you cannot do when using Symfony's inheritance system (because then `@Twig/Exception/error.html.twig` is resolved as `app/Resources/TwigBundle/views/Exception/error.html.twig`).

Proposing a customizable extension point with a simple configuration option is to me the BEST possible solution for templates overrides.

[EasyAdminBundle](https://github.com/javiereguiluz/EasyAdminBundle) uses something similar: auto-discovery in `app/Resources/easy_admin`, and configuration-based template sources. Each of them allow extending base EasyAdmin templates, which standard override does not allow.

**Comment by Pierstoval** [comment]
Just as a reminder, people tend to use bundle templates inheritance systems, while it should be much better to use [twig paths](https://symfony.com/doc/current/templating/namespaced_paths.html).

IMO this practice should be encouraged, and maybe a new syntax could be used to resolve a bundle view directory just to create a new namespace for it and allow better overriding systems:

**Before:**

```yaml
# app/config/config.yml
twig:
    paths:
        '%kernel.project_dir%/vendor/symfony/twig-bundle/Resources/views/Exception': Error
        '%kernel.project_dir%/vendor/friendsofsymfony/user-bundle/Resources/views': FOS
```

**After:**
```yaml
# app/config/config.yml
twig:
    paths:
        '@TwigBundle/Exception': Error
        '@FOSUserBundle': User
```

**Comment by yceruto** [comment]
@javiereguiluz I see your point and I'm in favor of simplest way to do this and I think there is some way to reach it if what we want is this `templates/error/*.twig` without do anything more to be able to override 
 `TwigBundle/Resources/views/Exception/*.twig` templates.

 1. We need move all `TwigBundle/Resources/views/Exception/*.twig` templates to the `views` root `TwigBundle/Resources/views/*.twig` otherwise we wouldn't omit `Exception` directory in `templates/error/`.
 2. Update all references from `@Twig\Exception\*.twig` to `@Twig\*.twig`.
 3. Add a new Twig's path in TwigBundle to register (before the parent one) the new convention:
    ```php
    if (file_exists($dir = $container->getParameter('kernel.project_dir').'/templates/error')) {
        $twigFilesystemLoaderDefinition->addMethodCall('addPath', array($dir, 'Twig'));
    }
    $container->addResource(new FileExistenceResource($dir));
    ```
In this way when a `@Twig\error.html.twig` template is called you can override it in `templates/error/error.html.twig`.

It's just an idea, something might be missing and of course, I did ignored BC breaks.

**Comment by yceruto** [comment]
Also it could be confused, since it puts the overridden bundle templates in a location that can conflict with the app templates inside the main `templates/` directory.

**Comment by ricknox** [comment]
@Pierstoval gave the correct purpose imo.

```yaml
# app/config/config.yml
twig:
    paths:
        '@TwigBundle/Exception': Error
        '@FOSUserBundle': User
```

Are we sticking with that solution or is the solution from @javiereguiluz the way to go? Or are both solutions possible?

**Comment by yceruto** [comment]
IMHO @Pierstoval's proposal doesn't help to solve this issue :/ because the `TwigBundle/Resources/views/Exception/*` templates are referenced as `@Twig/Exception/*` internally:

https://github.com/symfony/symfony/blob/c3d1262208783fa103e7bb9fe5b3cddb1096dcfd/src/Symfony/Bundle/WebProfilerBundle/Controller/ExceptionController.php#L109-L112

https://github.com/symfony/symfony/blob/59094b406af49eec2cd8d2758235232f4159458a/src/Symfony/Bundle/TwigBundle/Controller/ExceptionController.php#L102-L127

and this proposal `'@TwigBundle/Exception': Error` only would create a new namespace `@Error` for a new path `vendor/symfony/twig-bundle/Resources/views/Exception` that would allow to load TwigBundle templates as `@Error\error.html.twig` **in userland**. It seems more related to another issue https://github.com/symfony/symfony/issues/17557.

For now, the approved convention for 3.4 is `<default_path>/bundles/<BundleName>` (https://github.com/symfony/symfony/pull/24179).

**Comment by javiereguiluz** [comment]
Let's close because thanks to @yceruto overriding bundles templates is now much simpler. Also, even the error pages path is a bit weird, it's the standard way of doing things in Symfony, so it's better to not introduce yet another way of doing this. Thanks!
