### ISSUE TITLE
[RFC] Deprecate bundle inheritance

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24048]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | yes
| Symfony version  | 3.4

After having upgraded several apps to Symfony Flex (both small and complex apps) the worst thing to me was the overriding of third-party elements. Templates for example where in `app/Resources/AcmeBundle/views/` and now should be in `src/Resources/AcmeBundle/views/...`, etc.

I asked around in the [Symfony Slack chat](https://symfony.com/support) and the first responses confirmed that bundle inheritance is rarely used, except to customize some templates:

> Do you use that in your real projects? Do you override controllers, templates, etc. from third-party bundles?
>
> -> Rarely, but it has happened
> -> I've seen that in ApiPlatform, people override the swagger html twig file
> -> Apart error pages from twig, I almost never override resources from third-party bundle
> -> I overrode ~70% of FosUserBundle, but without bundle inheritance
> -> Only the error pages from twig.
> -> Me too, only error pages (on real projects)
> -> I used it along time ago for RollerworksMultiUserBundle. but that project is EOL (for good!)
> -> I only override templates and assets within `app/Resources/`. Never did any overriding using an inheriting bundle.

Deprecating this feature in 3.4 and removing it in 4.0 is our last chance in several years to do that.

If you agree, we should provide simple alternatives to override all that is listed in this article: [How to Override any Part of a Bundle](https://symfony.com/doc/current/bundles/override.html)

* templates
* routing
* controllers
* services
* configuration
* entities
* forms
* validation
* translation

**Comment by stof** [comment]
Thus, if you want to override bundle templates in a project, you don't need to use bundle inheritance (as there is a kernel-level folder allowing this).
I would not remove the ability to override bundle templates at project-level (which is just about using the Twig built-in feature of registering multiple paths for the same namespace).

I'm all in favor of deprecating this feature. Overriding bundle controllers or imported bundle resources created WTF debugging times anytime I used them (and I stopped doing it at least 5 years ago due to that).

**Comment by Pierstoval** [comment]
Same for me. Everytime I saw bundle inheritance OR service/controller/whatever override, it was a PITA to debug or maintain. Templates that are copy-pasted in `app/Resources`, when the parent bundle is updated, all logic is lost because copy/paste has to re-happen again, and plenty other problems when overriding stuff.

I'm 👍 for deprecating this feature, but not sure it's possible to remove it Symfony 4, as feature freeze is next month and we're very close (3-4 months) from SF4 release, I'm afraid too many people / OSS maintainers won't be able to follow this big upgrade, especially for bundles like FOSUserBundle which is still the most used.

**Comment by xabbuh** [comment]
:+1: for me too

**Comment by chalasr** [comment]
:+1:

**Comment by sstok** [comment]
Controllers and Form types can be overwritten by registering them services 😛 services take precedence over initialization by FQCN.

**Comment by ro0NL** [comment]
For 3.4 we would simply check if you defined `getParent` in a bundle, if so, trigger a deprecation. Right?

I wondered.. where will that happen. From the kernel?

**Comment by Pierstoval** [comment]
@ro0NL yep, this can be done in [`Kernel::initializeBundles()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L411)

**Comment by NicoHaase** [comment]
Just recently, I used the `getParent` logic to override a bundled template in another bundle which we use in multiple projects. Will there be any alternative? Even if you determine that you do not use it anymore and debugging is hard, I'd love to see good arguments for removing this and not just leaving it as it is and adding huge warnings that using this is a really bad idea, but you *can* use it if you take all risks

**Comment by Pierstoval** [comment]
> Just recently, I used the `getParent` logic to override a bundled template in another bundle which we use in multiple projects.

You actually don't need to use `getParent()` for this. Just create the `app/Resources/{ExternalBundleName}/views/{path to your view}.twig`  and you're set.

**Comment by NicoHaase** [comment]
@Pierstoval: I know about that. But as I use the bundle which overwrites some core template in *multiple projects*, I explicitly don't want to override these templates in app/Resources in each of these projects, but do it centralized in the very bundle that each of these projects uses

**Comment by xabbuh** [comment]
You can explicitly register your bundle's template path as a path for the namespace of the parent bundle (that's what happens in the background when using bundle inheritance).

**Comment by stof** [comment]
To be exact, the solution given by @xabbuh works when using the `@Foo/baz.html.twig` notation. When using the `FooBundle::baz.html.twig` notation, only bundle inheritance can allow a bundle to provide template overrides. But this syntax should not be used anymore (in Symfony 4, it won't be available by default, as this requires the templating component, which won't be included by default anymore)

**Comment by NicoHaase** [comment]
@xabbuh: can you give an example about how to do this? It would be nice to include this to the upgrade notes if you finally decide to remove bundle inheritance :)

**Comment by javiereguiluz** [comment]
@NicoHaase this is a real example in a Symfony app:

```yaml
twig:
    debug:            '%kernel.debug%'
    form_themes:      ['bootstrap_3_layout.html.twig', '_form_theme.html.twig']
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/templates/error': Twig
```

Now I can create `templates/error/Exception/error.html.twig` to override the error pages from TwigBundle.

The `paths` config expects an array of dir paths and optionally one Twig namespace for each of them. In the case of bundles, the namespace is the name of the bundle without `Bundle` suffix: `Twig` = TwigBundle, `FOSUser` = FOSUserBundle, etc.

**Comment by yceruto** [comment]
The @javiereguiluz's example should be the right solution regarding to project-level (App-to-Bundle), BUT inside a bundle that needs to override templates from another one (@NicoHaase's case, Bundle-to-Bundle) I might need implement [`PrependExtensionInterface` in your DI extension][1] to be able to add the new path before the current one in the same namespace:
```php
class AcmeHelloExtension extends Extension implements PrependExtensionInterface
{
    public function prepend(ContainerBuilder $container)
    {
        $bundlesMetadata = $container->getParameter('kernel.bundles_metadata');

        $container->prependExtensionConfig('twig', array(
            'paths' => array(
                $bundlesMetadata['AcmeHelloBundle']['path'].'/Resources/views' => 'Twig',
            ),
        ));
    }
}
```
Now I can create `AcmeHelloBundle/Resources/views/Exception/error.html.twig` to override the error pages from TwigBundle.

Btw, the `%kernel.project_dir%` parameter can be omitted from `path` value [since it is already the default root path][2] for each relative path.

 [1]: http://symfony.com/doc/current/bundles/prepend_extension.html
 [2]: https://github.com/symfony/symfony/blob/05beadd36d173edaf180e5480f37f3e899176ab5/src/Symfony/Bundle/TwigBundle/Resources/config/templating.xml#L12

**Comment by stof** [comment]
you probably don't need to use `$bundlesMetadata['AcmeHelloBundle']['path']`, as the path to the root of your own bundle is just `__DIR__.'/..'`

**Comment by yceruto** [comment]
@stof yes I know (unrelated) but `__DIR__` constant is considered a bugrisk for [SensioLabsInsight](https://insight.sensiolabs.com/what-we-analyse) so whenever I can, I try not to use it ;)

**Comment by lyrixx** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
So, who would like to try a PR for this? Feat. freeze is coming.

**Comment by fabpot** [comment]
I will submit a PR soon.

**Comment by stof** [comment]
@yceruto SensioLabsInsight considers it a bugrisk because it might break the possibility to override through bundle inheritance in some cases. This rule should disappear from Insight (even in 2.x or 3.x, this rule is bad because it is applied to lots of places where bundle inheritance does not play any role)

**Comment by MustaphaGhlissi** [comment]
Hi every body , 

I got started recently a new project using Symfony 4 

I have a problem , 

I am using FOSUserBundle works fine but I need to override the FOS SecurityController 
Previously we use getParent() function but  this feature was deprecated and which alternative solution can use in my case ?? 

Regards

**Comment by Pierstoval** [comment]
You have to create your own controller and recreate the route you want to override, I think it's the only way.

**Comment by javiereguiluz** [comment]
@MustaphaGhlissi the solution is what @Pierstoval said and it's explained here: https://symfony.com/doc/current/bundles/override.html

**Comment by MustaphaGhlissi** [comment]
Thanks guys,
