### ISSUE TITLE
Malformed UTF-8 characters JsonResponse - Microsoft SQL Server database

### ISSUE THREAD

**Issue by PGBastien** [symfony/symfony#24089]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

I have an error when i get data with specials chars (ex : spécial caractères).
I use LswDoctrinePdoDblib (https://github.com/LeaseWeb/LswDoctrinePdoDblib) / Microsoft Sql Server 2008R2 and 2014.

Error message :

> Malformed UTF-8 characters, possibly incorrectly encoded
> JsonResponse->__construct(array('data' => array('articles' => array(array('CODE' => '334731', 'DESIGNATION' => 'sp**�**cial caract**�**res')))), 200, array('Access-Control-Allow-Origin' => '*', 'Access-Control-Allow-Headers' => 'Content-Type'))

I tried to modify (config.yml) option charset (utf-8,iso-8859-1)in my mssql doctrine connection but it don't work !

**Comment by PGBastien** [comment]
For your information, it works on windows environment with microsoft PHP drivers for MSSQL 👍 
https://www.microsoft.com/en-us/download/details.aspx?id=20098

I will test this drivers https://github.com/Microsoft/msphpsql on linux environment

**Comment by jrysig** [comment]
Could you reproduce this problem?

Maybe it's a different bug, but I've seen the same malformed UTF-8 output in Symfony 3.4.0-DEV when running on my dev machine (Linux Mint, PHP internal server, postgresql 9.6). It is always displayed instead of character with accent as two ��. When I refresh page several times, it is displayed only in some cases, but always on the same position. This text comes directly from the twig template. When I edit twig, the problem moves to another word on the page. Unfortunately I'm not able to reproduce it right now.

**Comment by PGBastien** [comment]
I use Symfony current stable version 3.3.8 and my problem occurs during **JsonResponse on API GraphQL**.
It's a different problem
