### ISSUE TITLE
Policy on PHP-Extensions listed as required in composer.json

### ISSUE THREAD

**Issue by xelan** [symfony/symfony#24168]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 2.7+

What is the policy on PHP extensions listed in the symfony components' `composer.json`? For example, many components of the framework use the `ctype` extension, which is not included by default in some PHP installations. e.g. on Alpine Linux. 

In [PR 22676](https://github.com/symfony/symfony/pull/22676#issuecomment-300434331), @xabbuh mentioned that  PHP standard extensions were not listed as ext-requirements in the past. 

The Symfony Default Distribution's [requirements checker](https://github.com/symfony/symfony-standard/blob/3.3/var/SymfonyRequirements.php) lists some extensions which must be available to run the full-stack framework, however e.g. the session extension should not be necessary for CLI-only apps.

Which extensions are considered standard and must therefore be included in a custom minimalistic PHP installation?

Thank you very much!

**Comment by nicolas-grekas** [comment]
I think nobody has the answer to your question.
If you want to submit a PR adding more ext-* requirements based on your research, please do.

**Comment by BackEndTea** [comment]
I'm not sure if this is still an issue, but i wrote a small ctype-polyfill/compatability package: https://github.com/BackEndTea/ctype-compat. Which, if used, would mean that there is no need to add ctype as an explicit dependency. Although it could be added as a suggestion, since ctype itself would be slightly faster than this version.

**Comment by nicolas-grekas** [comment]
@BackEndTea interesting. Do you think you'd be OK to submit your polyfill for merging it with https://github.com/symfony/polyfill? I can help if yes.

**Comment by BackEndTea** [comment]
I see no problem in adding it to symfony/polyfill.
If you could help me out that'd be great, you can DM me on twitter if you want https://twitter.com/BackEndTea

**Comment by javiereguiluz** [comment]
I'm closing this as "can't fix". See #31305 for the full discussion. The summary is: *"we want to do this, but we can't , because some PHP extensions are required only for optional features ... so those PHP extensions aren't really required unless you explicitly use the optional features ... which we cannot detect beforehand"*.

Instead of this, we display nice error messages when you want to use something that requires some class/function not available because some extension si not installed. A nice example is the Mime component ... which requires "openssl" ... but only if you sign messages. So: https://github.com/symfony/symfony/blob/4045a134df3cfd2356b0b5a9fae7e91ec16d5f7d/src/Symfony/Component/Mime/Crypto/SMimeSigner.php#L41
