### ISSUE TITLE
Doctrine Bundle 1.7 breaks Symfony 3.4

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#24245]
I'm using a provocative title to trigger some reactions.
Doctrine Bundle 1.7 requires PHP 7.1.
But the upcoming Symfony 3.4 still supports 5.5
This effectively prevents non-7.1 users from benefiting from new 3.4 features/optimizations that the bundle could/will/does leverage.

See https://github.com/doctrine/DoctrineBundle/pull/697

**Comment by javiereguiluz** [comment]
There's no solution possible because Doctrine maintainers believe it's OK to increase the PHP requirement in a minor version and Symfony thinks the opposite. If you use Symfony 3.4, you are forced to use the old Doctrine thing; if you want to use the new Doctrine thing, you are forced to upgrade to 4.0.

**Comment by nicolas-grekas** [comment]
We're just talking about the bundle here. I'm happy another set of skilled ppl maintain Doctrine itself with th policy that fits them. But for the bundle, we're not talking about leveraging Doctrine features, but Symfony ones. So the policy for the bundle can/needs to take both sides into account.
The very fact that the maintainers of the bundle has ppl from both sides illustrate this and makes the discussion possible to me.

**Comment by alcaeus** [comment]
> if you want to use the new Doctrine thing, you are forced to upgrade to 4.0

How is that? The "new Doctrine thing" requires PHP 7.1, which Symfony 3.4 would support as well, or am I mistaken about that?

**Comment by javiereguiluz** [comment]
@alcaeus in my previous comment I was assuming that you want/need to use PHP 5.x for some reason. Symfony 3.4 works with PHP 5.x, but the new Doctrine bundle requires PHP 7.x.

**Comment by alcaeus** [comment]
Then i must’ve misread “forced to upgrade to 4.0”. Still, if you are using 7.1, there’s no problem using Symfony 3.4 and DoctrineBundle 1.7. If you are not using 7.1, you’ll have to stick with 1.5.x, which will get bug fixes as necessary.

**Comment by Nyholm** [comment]
You are correct, the following combination does not work: 
- PHP7.0
- Symfony:3.4
- DoctrineBundle: 1.7 

I do not really see the issue. SymfonyStandard does require DoctrineBundle:1.6 and 1.6 does support PHP 5.5.

**Comment by alcaeus** [comment]
@Nyholm DoctrineBundle 1.7.0 requires PHP 7.1. Relaxing the requirement to `^1.6.8` should fix it.

**Comment by Nyholm** [comment]
Yeah, the current requirement is `^1.6`.

**Comment by nicolas-grekas** [comment]
> I do not really see the issue

in the mobile world, they call that issue "market fragmentation": users are split in groups that have different experiences - subtle ones sometimes.

**Comment by nicolas-grekas** [comment]
With market fragmentation, our maintenance burden is increased, because well, we have to handle a more diverse set of combinations. And for users, it means they wil have a hard time figuring out the why they diverge from the canonical setup that they'll learn about in workshops or trainings or etc.

**Comment by stof** [comment]
@Nyholm the issue is that DoctrineBundle 1.6 will trigger a bunch of deprecation warnings when using Symfony 3.4 (it will keep working thanks to BC layers). But then, it means that any project needing to keep compat with PHP 7.0 (due to deploying on Ubuntu and using the distro package for instance, but there might be other reasons) will not be able to go deprecation-free.
And adding usage of new Symfony 3.4 features to improve the developer experience of using the bundle would then be available only to people using PHP 7.1+ (as they won't be accepted in 1.6 as they are not bugfixes). This means that we would then need different documentation depending on which version they use, etc...
This increases the maintenance (and probably on the Symfony side, as people having an issue when using DoctrineBundle are regularly reporting it to Symfony rather than Doctrine...)

**Comment by Nyholm** [comment]
I understand. Thank you for the clarification.

**Comment by mvrhov** [comment]
Well the ones whining about 7.0 in xenial should install the packages for 7.1 from the official maintainer, or wait for 18.04, or stop whining.

**Comment by fabpot** [comment]
@mvrhov That's not how Symfony works :)

**Comment by mvrhov** [comment]
I know, but I also know, that there is to much I won't upgrade just because reasons.

**Comment by alcaeus** [comment]
> DoctrineBundle 1.6 will trigger a bunch of deprecation warnings when using Symfony 3.4

And rightly so, but that's nothing bad, right? It will tell people to update to a newer version of DoctrineBundle.

> But then, it means that any project needing to keep compat with PHP 7.0 [...] will not be able to go deprecation-free.

You make deprecation warnings sound like a bad thing. A project doesn't need to be deprecation-free all the time - it needs to be deprecation-free when people want to upgrade. People can run `composer outdated` followed by `composer why-not doctrine/doctrine-bundle 1.7` to figure out what's going on and realize that they need PHP 7.1 to run the new version.

> And adding usage of new Symfony 3.4 features to improve the developer experience of using the bundle would then be available only to people using PHP 7.1+ (as they won't be accepted in 1.6 as they are not bugfixes). This means that we would then need different documentation depending on which version they use, etc...

I feel like we've had this conversation before, but what I'm understanding from this is: 
1. "every PHP version supported by Symfony needs to be supported by every bundle"
2. "any LTS Symfony version needs to be supported by every bundle".
That is quite the maintenance burden you're putting on other projects, and all of that because you're assuming that people will run a LTS version of Ubuntu (or worse, Debian oldstable with 5.x) with the shiniest, newest version of Symfony and all its bundles. Sorry, but as has been mentioned elsewhere, people using old LTS releases of their operating system shouldn't expect to be running the newest package versions.

**Comment by nicolas-grekas** [comment]
@alcaeus having *some* coordination from *some* core bundles would be great yes, that's the point. Of course, not all of them. But the increased maintenance burden is a myth to me: by experience, the policy we have prevents using some nice to have for sure and we impose ourselves waiting a few more years before using the shiny news language features. But seriously, PHP was already a quite capable in v5 so the burden is very low.

**Comment by nicolas-grekas** [comment]
> tell people to update to a newer version of DoctrineBundle.

If only they could, that's the point also.

> You make deprecation warnings sound like a bad thing. 

Again, it's a matter of openess and possibilities: I know many teams that have a policy to fix all deprecation when moving to the next version of any Symfony release. That's really wise because it allows them to smooth the migration cost to the next major over time. Yet, here, they are *required* to also move to 7.1, which should be a totally different story. That's the issue again.

**Comment by Tobion** [comment]
As DoctrineBundle 1.7 does not provide much more value than 1.6, I don't think there is a problem requiring PHP 7.1. There is no feature in 1.7 that people must or should need, so it doesn't really matter if 1.6 or 1.7 is used.

**Comment by ostrolucky** [comment]
> That is quite the maintenance burden you're putting on other projects, and all of that because you're assuming that people will run a LTS version of Ubuntu (or worse, Debian oldstable with 5.x) with the shiniest, newest version of Symfony and all its bundles. Sorry, but as has been mentioned elsewhere, people using old LTS releases of their operating system shouldn't expect to be running the newest package versions.

This isn't about LTS versions of Ubuntu. Currently there doesn't exist Linux distribution fit for servers which ships PHP 7.1. Everybody is forced to compile it from source, or use non-official package with bus factor 1. I believe people doing it in a serious project are asking for trouble.

**Comment by mvrhov** [comment]
@ostrolucky: The whole packaging system for php for Ubuntu has a bus factor of 1. Please don't spread the FUD.

**Comment by nicolas-grekas** [comment]
Fixed by https://github.com/doctrine/DoctrineBundle/pull/705, thank you @fabpot
