### ISSUE TITLE
[security-csrf] 

### ISSUE THREAD

**Issue by ahundiak** [symfony/symfony#24259]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.9

Apologies in advance if this is just operator error but I don't think the security.csrf.token_generator service is being defined.  It used to be defined in the Framework bundle and I don't think it got moved to the Security bundle during the recent cleanup.

    composer create-project "symfony/skeleton:^3.3" sec339
    cd sec339
    composer require console
    composer require security-bundle
    bin/console debug:container --show-private security # No csrf services
 
I think it is just a question of moving the security_csrf.xml from the old FrameworkBundle to the new SecurityBundle.

**Comment by chalasr** [comment]
In fact I think this file should have been added in SecurityBundle instead of FrameworkBundle at time it to introduce it (https://github.com/symfony/symfony/pull/6554). 

If we want to move it now (I think we should) we have to keep BC for people using FrameworkBundle but not SecurityBundle. 
We could  detect that `SecurityBundle` is not enabled and register+flag as deprecated all the services this file actually provides. If `SecurityBundle` is enabled, it means that the file has been loaded (once moved) so it's fine.

**Comment by chalasr** [comment]
That's more subtle: if `framework.csrf` config is enabled, `framework.form.csrf` is default enabled and related services are registered. We need to keep the same behavior while moving `framework.csrf` config key as `security.csrf`. I'm on it.

**Comment by fabpot** [comment]
@chalasr No, it should be part of FrameworkBundle as it is now... for the reasons you give in the second comment.

**Comment by chalasr** [comment]
@fabpot Yea, realized that while reading code... I think it's a pity to not be able to use these services with SecurityBundle only. Could we add the same config node triggering a compiler pass itself registering these services if they do not exist?

**Comment by fabpot** [comment]
I don't see why this is a problem.

**Comment by ahundiak** [comment]
Okay.  It was indeed operator error.  I had to enable csrf protection in framework.yaml and then all was well.  Just like the documents indicate.
