### ISSUE TITLE
Possible BC Break: Unable to Autowire ConsoleOutput Symfony 3.3.9

### ISSUE THREAD

**Issue by m453h** [symfony/symfony#24279]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes
| RFC?             | yes/no
| Symfony version  | 3.3.9

Autowiring ConsoleOutput fails in this version, but used to work in previous versions, is there an alternative for passing this Class to a service in version 3.3.9?

![screenshot from 2017-09-21 16-45-25](https://user-images.githubusercontent.com/6837271/30699090-70c42608-9eec-11e7-8a27-acc0567a712f.png)

**Comment by stof** [comment]
In which version was it working ?

**Comment by stof** [comment]
Note that the input and output used by the console application are not available as services (this would create lots of issues, just like defining a `request` service was)

**Comment by m453h** [comment]
It was working for version 3.2.x, specifically I was using version 3.2.7 and made the jump to 3.3.9 and that is where i noticed the break. 

So far I have deviated form injecting it as a service and just instantiated the object, and got my service working.

![screenshot from 2017-09-21 17-51-16](https://user-images.githubusercontent.com/6837271/30702467-b4898d66-9ef5-11e7-8253-85761f541ee5.png)

**Comment by stof** [comment]
@m453h this will still hurt you, because this service will write to a different output that the CLI one (even though both would send their content to STDOUT). So if the CLI passes the `--no-ansi` option to force disabling colors for instance, your own output may still have them enabled.
The output is not meant to be registered as a service precisely because it would use a different output, not known by the CLI.

Btw, if you really want to be able to inject a ConsoleOutput in your service through autowiring, you could still create a ConsoleOutput service yourselves. But it will still be a bad idea.

Symfony 3.3 restricts the automatic registration of additional services during autowiring to classes of the same top-level namespace than the one of autowired service. This is precisely meant to avoid cases like this one where autowiring was creating a service for an external class, which was not meant to be treated as a service (and so was not registered as a service by the corresponding bundle)

**Comment by chalasr** [comment]
The buggy thing was to auto register such class as a service, such door should never have been opened and has been closed in 3.3. 
Sadly, you were relying on that wrong behavior and I fear we can't do anything more than telling you to instantiate the output locally rather than via dependency injection. 
Given 3.3 is stable for a while and nobody else experienced the same, I think we can close.
