### ISSUE TITLE
Following the WSSE Docs results in a error from Symfony 3 base install

### ISSUE THREAD

**Issue by jakenoble** [symfony/symfony#24288]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no
| Symfony version  | 3.3

The docs from http://symfony.com/doc/current/security/custom_authentication_provider.html do not work it seems. Following them to the letter results in an error

> Service "security.authentication.provider.wsse.wsse_secured": Cannot replace arguments if none have been configured yet.

A base install of Symfony3 + implementing these docs result in this error, see this repo to replicate the issue https://github.com/jakenoble/wsse_test

**Comment by xabbuh** [comment]
Your problem is that your [custom services](https://github.com/jakenoble/wsse_test/blob/master/app/config/services.yml#L8-LL15)  are defined before the [PSR-4 based service registration](https://github.com/jakenoble/wsse_test/blob/master/app/config/services.yml#L27-L33). Thus, your service definitions are overridden.
