### ISSUE TITLE
RFC: Require PHP 7.2 for Symfony 4.1 to be able to add type declarations

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#24283]
With https://wiki.php.net/rfc/parameter-no-type-variance coming with PHP 7.2, it makes it possible to add type declarations to methods without breaking BC of users that overwrite the methods.

That would be a huge benefit for symfony. What I'd like to see is that symfony 4.1 would increase the PHP requirement to PHP 7.2 (from 7.1) and thus we can add type declarations in Symfony core. 

I know we usually don't increase php requirement in minor versions. But the only alternatives would be:
- to wait another 2 years for Symfony 5
- require PHP 7.2 for Symfony 4.0 from the beginning which is probably too tight (as PHP 7.2 is supposed to be released in the same month and we don't have much development time anymore to add type declarations)

**Comment by iltar** [comment]
I see no reason to not be able to require newer php versions in minor versions when it comes to the health of the codebase. I know that Symfony tries to be as compatible as possible, but upgrades between php7 versions is something that has been simplified a lot. Besides of that, Symfony 4.0 is practically 3.4, which means that they are not willing to upgrade to 7.2 or 4.1 and need bug fixes, they can simply require 3.4 and their code will still work.

**Comment by kaznovac** [comment]
Symfony 4.x branch should be future oriented/proof.
IMO PHP 7.2 should be introduced as early as possible regardless type declarations in code, declarations can be introduced in future Symfony 4.[1-4].
Otherwise Symfony 4.3 (release 03/2019) and 4.4 (release 09/2019) projects will be stuck on un-mantained PHP 7.1 [PHP: Supported Versions](http://php.net/supported-versions.php) (support until 1 Dec 2018, security support until 1 Dec 2019)

**Comment by NicoHaase** [comment]
@kaznovac: that's a false conclusion. Symfony is not stuck at a single version - the only question is whether Symfony should support PHP 7.1 for the next two years or not. And as Debian 9 just arrived with PHP 7.0, there will be tons of servers running on this version for a long time.

Real servers should be run on LTS branches, and they will keep the support for such versions for longer time than the PHP guys itself do

**Comment by theofidry** [comment]
7.2 would be too much and hurt the adoption rate. A lot of people won't be able to deploy anywhere. Waiting another 2 years for it is no big deal IMO.

**Comment by iltar** [comment]
@theofidry Symfony is not made for shared hosting platforms, so if you choose a hosting solution, this often implies you have full control over what you install. 

People that want to stay behind and use the LTS version, they can do that. 3.4 will be supported for quite a while and means that they can even run 5.6 if they want to. People that want to keep moving forward, should be able to, including people that want to improve Symfony. The framework should not be kept behind by the small group of people unwilling to move forward at the same pace as development.

Symfony LTS will be supported long enough for people to make the jump to 4.4 and the new PHP version in their own pace (more or less). If it's decided to keep the php requirement as low as possible, we might as well drop the LTS concept, because people seem to be upgrading regardless.

Imo you either strive for improvement and "cutting edge" features, which means you have to accept that the framework does not stand still and increases the requirements, or you strive for the LTS concept and "stay behind", knowing you can safely upgrade to _every single 3.4.x release without problems_. Doing both will imo hurt the flexibility Symfony components have.

**Comment by theofidry** [comment]
@iltar I was not peculiarly talking of shared hosted platforms. There is a lot of people that take time to upgrade without being on a shard hosted platform.

I agree with your argument overall, but there is a big gap between being cutting edge and being on the _bleeding_ cutting edge. PHP 7.2 is still not out and will be barely a few months old when 4.1 will be released.

It is nice to be on the edge, but not every one has the time to upgrade everything all the time. A minimal platform requirement is no small requirement, it's a pretty big deal, and I don't find the new features in 7.2 appealing enough to make such a move. Look at the number of libraries still on PHP 5.6...

That said the main argument is about maintenance and I'm far from being a regular maintainer of the Symfony codebase, maybe they have an different point of view regarding that :)

**Comment by nicolas-grekas** [comment]
I'm :-1: as I adding more type hints is not worth the adoption penalty this will create.

**Comment by fabpot** [comment]
I agree with @nicolas-grekas. We went back and worth on this one, and the last decision (for Flex) was to still support 7.0.
