### ISSUE TITLE
ErrorHandler in YamlFileLoader.php 

### ISSUE THREAD

**Issue by FanchTheSystem** [symfony/symfony#24459]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Is $context missing ? In this commit :
https://github.com/symfony/symfony/commit/cf0355203376ed9fe4a0e41446a003602dc02e66

May it be something like :

```
    $prevErrorHandler = set_error_handler(function ($level, $message, $script, $line, $context) use ($file, &$prevErrorHandler) {
            $message = E_USER_DEPRECATED === $level ? preg_replace('/ on line \d+/', ' in "'.$file.'"$0', $message) : $message;

            return $prevErrorHandler ? $prevErrorHandler($level, $message, $script, $line, $context) : false;
        });
```

As in : https://github.com/symfony/symfony/blob/v3.3.10/src/Symfony/Component/Config/ResourceCheckerConfigCache.php

@xabbuh ;)

**Comment by xabbuh** [comment]
The `$context` argument of an error handler is optional and is deprecated as of PHP 7.2. Thus, we decided not to add it. If you are running in issues when using this together with the PhpUnitBridge, you need to update the bridge too as we had an issue in it (it did not allow to not pass the `$context` argument) which was fixed in #24192.

**Comment by FanchTheSystem** [comment]
Ok, thank you @xabbuh

**Comment by xabbuh** [comment]
@FanchTheSystem Can we close here then or do you still experience any issues?

**Comment by FanchTheSystem** [comment]
Please close it ;)
