### ISSUE TITLE
[DI] 3.4 BC Break - all my services made private

### ISSUE THREAD

**Issue by Strate** [symfony/symfony#24465]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.x-dev

I tried to upgrade from 3.3 to 3.4.x-dev to test compatibility and found that all of my services made private by default. It happes from `Symfony\Component\DependencyInjection\Compiler\ResolveChildDefinitionsPass::process` method:

```php
foreach ($container->getDefinitions() as $definition) {
    if ($definition->isPrivate()) {
        $definition->setPublic(false);
        $definition->setPrivate(true);
    }
}
```

`->isPrivate()` method returns `true` for all services by default, because `\Symfony\Component\DependencyInjection\Definition::$private` set as `true` by default.

/cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
What the behavior you have? Any error message?

**Comment by Strate** [comment]
I have my custom CompilerPass which checks for `isPublic` and fails if it is falsy (this need for custom services collection by tags)

**Comment by stof** [comment]
@Strate 4.0 will make services private by default. If you don't specify the visibility of services, 3.4 will indeed make them semi-private in this case: it will treat them as private, but ensure that they cannot be removed or inlined, so that they are still accessible in `Container::get()` thanks to the BC layer.
Note that in most cases, new Symfony DI 3.3 features (especially IteratorArgument and ServiceLocator) make it possible to avoid the need to use public services for lazy references.

@nicolas-grekas should we do this change on `setPublic` at a lower priority than at the beginning of priority 0 compiler passes ? It is common for bundles to check for `isPublic` in their compiler passes, and this would indeed not work well here when relying on the BC layer.

**Comment by Strate** [comment]
@stof thank you, I've got a reason why it was done. I will definitely refactor my code for sf4

**Comment by nicolas-grekas** [comment]
@Strate maybe you should run your pass BEFORE_OPTIMIZATION? It's strange to run a check at OPTIMIZATION step, isn't it?
@stof did you mean something like https://github.com/symfony/symfony/pull/24468?

**Comment by Strate** [comment]
> It's strange to run a check at OPTIMIZATION step, isn't it?

Yes, I think so too, but there is a reason to run it there: my compiler pass should run after ResolveDefinitionTemplates pass, and long time ago (when symfony was at version 2) I decided to just move my compiler pass to `OPTIMIZATION` step.

**Comment by Strate** [comment]
@nicolas-grekas there is even such compiler ass in Symfony core: 20116
