### ISSUE TITLE
Upgrade to 3.4-BETA problem 

### ISSUE THREAD

**Issue by atailouloute** [symfony/symfony#24616]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.0-BETA1

Hello,

I am using Symfony 3.3 on a project in which I am using `TwigRendererInterface` as a dependency for a service, and the injected service is `@twig.form.engine`, it works great since the service implements the mentioned interface.

But when I upgraded the project to the 3.4 version, I got an exception because the service `@twig.form.engine` does not implement the interface `TwigRendererInterface` anymore (changes made in commit https://github.com/symfony/symfony/commit/6ea71cb2ccc205294798d809e2ee295cfd9a0b5f#diff-5eb0532c96734f6e23428e921225b2f0) , for me the solution is simple, I had just to change the type-hint, but I am thinking if this would be a BC break? 

Best regards,

**Comment by Tobion** [comment]
The only solution I see is to deprecate the service twig.form.renderer and introduce a new one with the correct class. But that requires all people to change their DI. TwigRendererInterface is already deprecated since 3.2 so still relying on it seems like an edge case. So not sure who to optimize for.

**Comment by nicolas-grekas** [comment]
I'd suggest to not do anything here...
