### ISSUE TITLE
[Form] PRE_SUBMIT constant and value mismatch

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#24615]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

In [this tweet](https://twitter.com/deguif/status/920936122406113280) @deguif asked:

> `PRE_SUBMIT => 'form.pre_bind'` in Symfony 4, is there any reason why the event name value didn't change?

Should we update the value of the constant?

**Comment by iltar** [comment]
We could add a second constant and deprecate the old one in 4.1 (or 3.4 if that's still allowed)

**Comment by stof** [comment]
The `PRE_SUBMIT` constant cannot be deprecated. This is the name of the event we want (`PRE_BIND` was the old name in early 2.x).

**Comment by yceruto** [comment]
The constant name was already changed in 3.0 (with previous deprecation since 2.3) but not its value, not sure why :/ . Most ppl rely on the const name to listen, so maybe we can/should fix its value directly?

**Comment by stof** [comment]
Yeah, I think we could change this in 4.0 without a big impact (btw, I think our BC policy even allows it for this case).

There is one case where people will use the event name rather than the constant: the `kernel.event_listener` tag (and recent versions can even use the constant in YAML files). But this won't be the case for this event, as form events are not dispatched in the main dispatcher anyway.

**Comment by yceruto** [comment]
See https://github.com/symfony/symfony/pull/24631
