### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by allfreelancers** [symfony/symfony#24645]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.10

Error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 17179869216 bytes)

(1/1) OutOfMemoryExceptionError: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 17179869216 bytes)

--

in DebugClassLoader.php (line 238)

**Comment by javiereguiluz** [comment]
@allfreelancers you'll need to provide more information about this error:

* Does it happen when running tests or when loading some page?
* Did it happened before or it happened when upgrading the Symfony version?

**Comment by sstok** [comment]
A friend of mine had the same problem (on Windows), it seems it's related to the big amount of deprecations detected. He "fixed" it by disabling the Debug component 😅

**Comment by xabbuh** [comment]
So this is basically the same as #24625 (just that the latter one did not run into the `OutOfMemoryException`)?

**Comment by allfreelancers** [comment]
@javiereguiluz I'm use windows 7 and its happen on load page (this happens often)

Did it happened before or it happened when upgrading the Symfony version?
this occurs before and after the update

**Comment by xabbuh** [comment]
If it happened before updating I'd say it's rather not related to Symfony as we did not receive any other reports related to such a problem, but caused by your own code or some other package that you are using. Thus, I am going to close here, but we can of course reopen here if we have more information which indicate that Symfony seems to cause the error.
