### ISSUE TITLE
Symfony 3.3 documentation is incomplete 

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony#24654]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| Symfony version  | 3.3.10

i come from basic PHP programming and never worked with OOP until now ( to my shame )
although i now SQL is very hard for me to understand some things
also working with forms is not easy

For example i want to insert some content in a database based on the logged in user ( user_id )
i was only able to do that after paying for tutorials because symfony documentation is incomplete !

i also found that symfony does integrate forms with bootstrap template ( which is awesome !!! )
( http://symfony.com/doc/current/form/form_themes.html )
however, that i didn't found on documentation ... also paid for this !

Don't get me wrong, Symfony is awesome ! It has a lot of potential, but not very documented if not at all

This may not be a bug, but it should be definitely treated like one ...

I'm trying to open a debate here ( not a fight ! )

**Comment by javiereguiluz** [comment]
You are right that Symfony documentation is incomplete ... but the same happens with the docs of every other software project.

About your other comments, I think they are not true. You said for example that you don't know how to use a Bootstrap theme for Symfony Forms without paying. If you Google that, the first two results are free doc resources explaining Forms and Bootstrap:

![symfoy-form-bootstrap](https://user-images.githubusercontent.com/73419/31861278-b0d71362-b72a-11e7-9490-bc1c5936a75c.png)

About the other topic you were looking for:

* Here you can find all the basic info you need to know about security, users, etc. https://symfony.com/doc/current/security.html
* Here you can find the basic info about using databases: https://symfony.com/doc/current/doctrine.html

In any case, we appreciate your comments because a fresh view on our docs/code/ideas is something that we always need. So, I propose that you try to use Symfony Docs a bit more and when you find any problem, or lacking docs or bad explanations/examples, please report them opening new issues in the Symfony Docs repo: https://github.com/symfony/symfony-docs

Thanks!

**Comment by cybernet** [comment]
why have you close this ? does it looks fixed to you ?

for me to search on google symfony bootstrap form, first i had to get to templating, right now i'm at getting stuff from database and put them in the first place ( with Symfony, not phpmyadmin ... )

so awesome doctrine documentation show me how to insert a row in a table ... but a simple thing like inserting the current user that is using the form ... how ?

for instance it took me a few hours just to figure out how to pass an argument to a form ( not even [stackoverflow](https://stackoverflow.com/questions/46870572/passing-data-to-buildform-in-symfony-3-3) didn't help ... ) finally i decided to search for a demo app and i find your [blog](https://github.com/symfony/demo/blob/master/src/Controller/BlogController.php#L92) 

now i'm searching again on how to get 2 values in one query from 2 table ( without DQL ) because ... we have entities...

also symfony doesn't have a default Slug component
it's not like symfony is used for websites that publish stuff ... and well they need urls
i found a [Slug bundle](https://github.com/cocur/slugify) but i have to figure out a way to make unique urls ... and many more.. i started a week ago with symfony, if i wasn't using phpstorm i would smash my laptop with a fire extinguisher ( it's nearby )

i know that making a good documentation takes time, but at least publish the basic and more examples on github, like a forum, using Users and registration and stuff ( these are the basic stuff that any n00b needs when learning new stuff )

my login and registration part i got it from [auth0](https://auth0.com/blog/creating-your-first-symfony-app-and-adding-authentication/) ...

it's the small things that matter

and once again, this issue should be reopened ...

**Comment by javiereguiluz** [comment]
@cybernet my reasoning for closing this issue was: we take note about your comments (and appreciate them!) but I close this issue because here we are in the repository which holds the Symfony code. We have a dedicated repository for Symfony Docs (https://github.com/symfony/symfony-docs) which is where we should discuss these things. I see you've created an issue there, so let's continue the discussion in that repository. Thanks!

**Comment by curry684** [comment]
@cybernet first of all my compliments on choosing the best and most powerful PHP framework around to continue your development journey. As the saying goes however, *"with great power comes great responsibility"*. Symfony is incredibly powerful, but not a starter framework. I've had several team members, with lots of PHP experience, learn Symfony themselves using online resources, and they have never complained about the docs being "thoroughly incomplete". They had more prior knowledge from using or even writing other frameworks.

The misconception is that the Symfony docs are not trying to teach you OOP or SQL, but assume you to have all the basic knowledge in place so they can teach you on the more complex subjects that separate Symfony from the rest. I therefore do not think your comments are currently really valid, as they are based on a wrong premise.

Why the word "currently" in that previous sentence? Because I think new developments in the world of Symfony, specifically Flex, may very well warrant a separate documentation section specifically giving less experienced developers a speed course as it makes the framework more accessible to newcomers. Most of the existing documentation however is right now very well usable by experienced developers, and as a reference, exactly *because* it assumes much prior knowledge.

So it's not so much a matter of the docs being fundamentally incomplete, as of not having a section that helps those with a less thorough background up to speed. That's worth looking into    😄
