### ISSUE TITLE
upgrade 2.8 to 3.3 break

### ISSUE THREAD

**Issue by symio** [symfony/symfony#24718]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.3.10

I just passed few hours trying to migrate my sf 2.8(.28) application to 3.3(.10) following both guides :

- http://symfony.com/doc/current/setup/upgrade_major.html
- http://symfony.com/doc/current/setup/upgrade_minor.html (trying to first move to 3.1 with preceding link as 3.0 is already out ; who had almost worked and then upgrade to 3.3 and there encounter the break)

console commands server:* are lost, console is still in app directory not in bin, cache is still in app/cache no var/* directory has been created.

Comparing with a fresh 3.3.10 install do not come with an approaching file structure.
I, also, tried disabling all "specials" bundles needed in the project (fosuser, fosjsrouting, gedmo and stof doctrine-extensions, guzzle) but i always get the same result.

Also i remark that the "extra" section in composer.json is not updated like in a fresh install (no symfony-bin-dir as example).

Thanks for help and at least for reading

**Comment by kejwmen** [comment]
Hi @symio,
I will try to explain what's going on.

> console commands server:* are lost

This is 3.3 related - http://symfony.com/blog/new-in-symfony-3-3-webserverbundle and not considered as BC Break. Requires configuration change (you need additional dependency), but don't change any of existing behaviors, so it's fine - `UPGRADE` files (like [this for 3.3](https://github.com/symfony/symfony/blob/master/UPGRADE-3.3.md)) include a list of changes that could be important for migration process..

> console is still in app directory not in bin, cache is still in app/cache no var/* directory has been created.

Because new structure is just a new default - it cannot be migrated automatically, that's why manual changes are required.

I am responsible of migrating quite large symfony app since 2.4 (we're using 3.3 now) and experience is nice. Remember about `UPGRADE` in case of any problems.

And flex will bring many DX improvements, so stay tuned ;)

**Comment by chalasr** [comment]
Going from 2.8 to 3.3 is a huge upgrade, you should have a look at UPGRADE-3.0 to UPGRADE-3.3 files, they are in the root directory of this repository.

About the directory structure, updating your dependencies cannot make update it, that's up to you to keep it in sync with best practices.

For `server:*` commands, see the corresponding [upgrade note](https://github.com/symfony/symfony/blob/master/UPGRADE-3.3.md#frameworkbundle):

> The server:run, server:start, server:stop and server:status console commands have been moved to a dedicated bundle. Require symfony/web-server-bundle in your composer.json and register Symfony\Bundle\WebServerBundle\WebServerBundle in your AppKernel to use them.

**Comment by xabbuh** [comment]
I am going to close here as there is nothing we can actually change. But of course if you think that some of the upgrade instructions could be improved/clarified, please let us know.
