### ISSUE TITLE
[Form] Can not apply ViewTransformer to IntegerType form field

### ISSUE THREAD

**Issue by Snake-Tn** [symfony/symfony#24734]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

Creating a `viewTransformer` for an `IntegerType` in order to transform it to an entity Object throw an exception. 
It's because 'IntegerType'  per default has its own `viewTransformer` called `IntegerToLocalizedStringTransformer`

viewToNorm step is plugging the output of my custom transformer (entity)  to the input of `IntegerToLocalizedStringTransformer` which expects a string as input.
therefor , an exception is thrown  `TransformationFailedException('Expected a string.')`

In the example given in the official docs : http://symfony.com/doc/current/form/data_transformers.html
it uses `TextType` which doesn't come with any "View Transformer" per default.

Example who throws an exception:
```php
<?php
  public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('my_int_field', IntegerType::class);
        $builder->get('my_int_field')
            ->addViewTransformer(new CallbackTransformer(
                    function ($myEntity) {
                       ...
                    },
                    function ($number) {
                        $myEntity = new MyEntity();
                        $myEntity->setNumberAttr($number);
                        return $myEntity;
                    })
            );
    }
```

**Comment by fancyweb** [comment]
You can use the `resetViewTransformers` method before adding yours to get rid of the existing one.

I think you can also "force prepend" your transformer (by setting the second argument of the `addViewTransformer` to `true`) so your transformer is actually executed after the existing one (for the view to norm transformation).

**Comment by xabbuh** [comment]
I am closing here as there is no bug in Symfony.

**Comment by stof** [comment]
I think you should be using a model transformer in this case. your model type is your entity, but and the view type a string. But the normalized type of the IntegerType is an integer, and you should keep it this way for your custom child type (and so doing the entity conversion between modal and norm, not between norm and view).
This would solve your issue, as the default ordering for transformers is precisely meant to preserve the type semantic of the parent form (i.e. decorating the parent transformation logic rather than injecting in the middle).
But putting your logic in the view transformers, you force yourselves to change this ordering to apply the logic in the expected order, which is much more fragile (forcing the transformer to be added in a different place is a sign of using the wrong type of transformer in 90% of cases)
