### ISSUE TITLE
Kindle .mobi upload and mimetype detection

### ISSUE THREAD

**Issue by archistico** [symfony/symfony#24862]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.0.0

Not exist this mimetype? is application/octet-stream?

**Comment by timonf** [comment]
I think @archistico wants to have a new entry into [MimeTypeExtensionGuesser](/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/MimeType/MimeTypeExtensionGuesser.php).

I just read through some articles. It's hard to find a mimetype for `.mobi` files, because Amazon uses the `.azw` extension (already part of the MimeTypeExtensionGuesser).

After some further research I found an old [Drupal patch](https://www.drupal.org/node/1443070). According to this patch the following entry is missing in the list:

```php
        'application/x-mobipocket-ebook' => 'mobi',
```

Regards,
Timon

**Comment by javiereguiluz** [comment]
Closing as "fixed" because the most recent MimeTypes class contains this:

https://github.com/symfony/symfony/blob/91c5b14d8b6e9016c31d46ad8576ecf0ce836221/src/Symfony/Component/Mime/MimeTypes.php#L901
