### ISSUE TITLE
Deprecation when using @ParamConverter and Type Hints since Symfony 3.4

### ISSUE THREAD

**Issue by iluuu1994** [symfony/symfony#24891]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0-BETA3

I get the following deprecation message:

> Relying on service auto-registration for type "MyEntity" is deprecated since version 3.4 and won't be supported in 4.0. Create a service named "MyEntity" instead.

This is my action:

```php
/**
 * @Route("/my-entity/{id}")
 * @ParamConverter("myEntity", options={"id"="id"})
 */
public function editMyEntityAction(Request $request, MyEntity $myEntity)
{
    // ...
}
```

The deprecation goes away as soon as I remove the `MyEntity` type hint. It looks like Symfony thinks I'm trying to inject a `MyEntity` service. Is this a bug or am I doing something wrong?

Thanks!

**Comment by ogizanagi** [comment]
Hi @iluuu1994. 
This is bad pre-sf 3.3 autowiring happening. Try setting the `container.autowiring.strict_mode` parameter to `true` in your application in order to disable the BC layer.

Some refs about this:

- https://github.com/symfony/symfony/pull/24671
- https://github.com/symfony/recipes/pull/221
- https://github.com/symfony/symfony-standard/pull/1114

**Comment by iluuu1994** [comment]
@ogizanagi And sure enough, the deprecations are gone!

Sorry, I wasn't aware of that. Thank you!

**Comment by Taluu** [comment]
This is still a bug IMO...

**Comment by ogizanagi** [comment]
@Taluu : Not really to me. It's an incompatibility between the old autowiring system and the ServiceValueResolver introduced in 3.3, which is only opt-in by using the `controller.service_arguments` tag on the controller, while the first one is deprecated and opt-out thanks to the mentioned param.

**Comment by kironet** [comment]
Ok, what will happen if you upgrade to 4.0? 
It will broke a project right? Because this parameter is useless on 4.0(as I read somewhere)..?

**Comment by iluuu1994** [comment]
@kironet No. This flag disables the compatibility mode which is not present in Symfony 4.0. Thus this error will not occur in Symfony 4.0 projects.

**Comment by givihuda** [comment]
Not quite sure I'm understanding... you say "this error will not occur in Symfony 4.0 projects", as in that deprecation warning? I think we already know that because deprecation warnings from Symfony 3.4 go away in 4.0 because they're literally removed. What will happen if we don't fix the deprecation warnings is that Symfony 4.0 will break but with a new error (or maybe no error)... so I think what kironet is asking is if setting `container.autowiring.strict_mode` parameter to `true` simply hides a warning that will become a problem in 4.0, and I can't tell if you're saying that that's not true.
