### ISSUE TITLE
[Form] Why is symfony/intl required?

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#24966]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.7

Seems this is the only component which requires symfony/intl. As consequence with the intl extension installed I get  an useless dependency and my IDE complains I have two `\Locale` classes. Could we just move it into `suggest` section?

**Comment by kix** [comment]
@MatTheCat, the reason is that the extension is required by types that fetch data from ICU: 
* `CountryType`
* `CurrencyType`
* `LanguageType`
* `LocaleType`
* `DateTimeType`/`DateType`
If we move `intl` to `suggest`, then these types just won't work out of the box. One way Symfony could go here is move the types to a separate package but that would just make things complicated IMO.

**Comment by MatTheCat** [comment]
Any of these types can be implemented with PHP intl extension so I find it sad to force a dependency which will only support english.

**Comment by stof** [comment]
no, the intl extension does not give access to the ICU data. It only gives access to the formatters.
In the list above, only DateTimeType / DateType are using features of ext-intl.

**Comment by stof** [comment]
And the symfony/intl component is not about supporting only English. There are 2 parts in this component:

- the ext-intl polyfill for formatters, which indeed supports only English formatter rules. This code is not used at all in case the intl extension is available on your system (as it is a polyfill), unless you write your code using the stub classes directly (which is not the case of the Form component)
- the `\Symfony\Component\Intl\Intl` API exposing ICU data

On a side note, the policy of symfony component regarding polyfills is to always require them, instead of forcing users to require the polyfill themselves (for instance, `symfony/console` requires `symfony/polyfill-mbstring`). This way, components work by default (even though performance will be better if you install the appropriate extension rather than relying on the polyfill layer).

**Comment by MatTheCat** [comment]
Thanks for all the explanations!

**Comment by mmarton** [comment]
Reviveing this zombie issue:
wouldn't it be possible to create a form-pack metapackage that requires form and intl components?
That way you keep the "working out of the box" and give the possibility to install the component without intl.
