### ISSUE TITLE
Wrong symfony/http-kernel checksum on packagist

### ISSUE THREAD

**Issue by pureugong** [symfony/symfony#25006]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | v2.5.11

@fabian 
I just found this issue by chance while migrating legacy source code.

I wonder why [symfony/http-kernel checksum check sum key on packagist](https://packagist.org/packages/symfony/http-kernel#v2.5.11
) is **045a1741a8f1d4feb190d6e296998b2356cc762a**, not **7b1632cf2bdbc69c59a44942b70d5aae91034304**

It looks like that it has one commit missed, which is version up on Kernel.php
https://github.com/symfony/http-kernel/commit/7b1632cf2bdbc69c59a44942b70d5aae91034304

**Comment by nicolas-grekas** [comment]
ping @fabpot

**Comment by xabbuh** [comment]
symfony/http-kernel@045a1741a8f1d4feb190d6e296998b2356cc762a is the commit where the [v2.5.11 tag](https://github.com/symfony/http-kernel/releases/tag/v2.5.11) was made with. That's why it is show on packagist.org (and it will be the commit you end up with locally when installing `symfony/http-kernel` in version 2.5.11). I am closing here as there is nothing to do.

**Comment by pureugong** [comment]
@xabbuh
Thx! Of course I know it was where v2.5.11 tag was made with, so... which means forgot to vension up before creating v2.5.11 tag. 

Anyway I totally agree with you that there is nothing to do since it is very tiny minor issue. (Just not a good example for code consistency.)

**Comment by pureugong** [comment]
ping @javiereguiluz
