### ISSUE TITLE
[Security] Incorrect logic in GuardAuthenticationListener

### ISSUE THREAD

**Issue by vasilevrv** [symfony/symfony#25007]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 2.8-last

Hi, I have problems with Symfony\Component\Security\Guard\Firewall\GuardAuthenticationListener

I'm using two authenticators for the stateless API (by JWT token or by IP address).

Authentication process:

```
        foreach ($this->guardAuthenticators as $key => $guardAuthenticator) {
            // get a key that's unique to *this* guard authenticator
            // this MUST be the same as GuardAuthenticationProvider
            $uniqueGuardKey = $this->providerKey.'_'.$key;

            $this->executeGuardAuthenticator($uniqueGuardKey, $guardAuthenticator, $event);

            if ($event->hasResponse()) {
                if (null !== $this->logger) {
                    $this->logger->debug(sprintf('The "%s" authenticator set the response. Any later authenticator will not be called', get_class($guardAuthenticator)));
                }

                break;
            }
        }
```

In case if the first authenticator passed success, the second will also be called.

Stateless API should not return success response. 

Thanks in advance :)

**Comment by weaverryan** [comment]
Unfortunately, this IS the correct logic, but I can totally see why it doesn't work nicely in your case :). On a low-level, the security system is setup so that all authentication listeners are called - i.e. they don't stop once one is successful. 

This is typically not a problem because each authenticator (in its `supports()` method) should be looking for some specific authentication info in the request, and 2 authenticators (normally) won't both "see" authentication info on the same request. For example, if you had a JWT authenticator and a form login authenticator, only 1 authenticator would ever return `true` from supports(), because you would never have a JWT on a request AND submitted username/password data.

Your situation, where the second authenticator uses the IP, is definitely an exception to that rule. The way to handle it is to check (in the second authenticator) if the user is already authenticated, and return `false` from supports() if this is the situation. You could also check to see if a JWT header is on the request, and return `false` in that case - that would probably be even better (don't ever try to authenticate a user via IP if they are sending a JWT). If you want to check to see if the user is authenticated, see: https://symfony.com/doc/current/security/guard_authentication.html#avoid-authenticating-the-browser-on-every-request

Cheers!

**Comment by vasilevrv** [comment]
Thanks for your response!

Why this logic is correct? Why call anything if one has already success?

**Comment by weaverryan** [comment]
I actually don’t know - the security system (which was ported from Spring) was originally made to work like this. I suppose one reason would be if you auth all users automatically with one listener to give everyone basic access. Then, you have another auth listener that actually looks for credentials and auths them at a higher level. In that case, you wouldn’t want the second auth listener to NOT be called because the first technically auth’ed the user. Both ways probably have edge cases :)
