### ISSUE TITLE
submited form not containing all fields

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony#25081]
Hello

when my entity contains required fields:
1. I remove HTML fields
2. I submit form (input was required=>true)
3. there will be error "Type error: Argument 1 passed to setSomething() must be an instance of Something, null given, called in ..."

something = other entity for example

how to avoid it ?
DataMapper Should not set null values if not sended from form ? (becouse on that field I set required => true)

or this should be checked in validation ?

**Comment by iltar** [comment]
You should be checking this in the validation. I think that having the `required` option is extremely confusing, perhaps we should deprecate this option in favor of something else in 4.1? I've seen people hit this issue very often.

**Comment by poolerMF** [comment]
finally, I see that it doesn't matter if there is required
error occured before validation (it's becouse of variable type in set method)
![test](https://user-images.githubusercontent.com/4276289/33097756-7070da30-cf0b-11e7-9134-fdf70b5807cb.png)
in error example I removed date from form .. so date was not submitted

I want to keep "\DateTime" or another types in set methods

**Comment by xabbuh** [comment]
This is a known limitation of the Form component. The data mapper does not care about the actual data type but just maps the submitted form based on the form/property names. So when using type hints you always risk to run into type errors.

You *could* implement your own data mapper which works around this limitation. But probably [using DTOs instead of entities](https://stovepipe.systems/post/avoiding-entities-in-forms) in your forms is the easier way to go.

Anyway, I am going to close here as this is not a bug. Thank you for understanding.
