### ISSUE TITLE
accessing cache pool from service container

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony#25342]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.0

After clean install, I can't get access to public cache pools _app and system_, either to my custom cache pool. 
Strange things, they are all registered in container and displayed using 
`bin/console debug:container` command and they are both _public_, but when I try to get them through 
`$this->get("cache.app\|cache.system\|cache.custom")` I get 
_ServiceNotFoundException_. 

What I am doing wrong? Any ideas?

**Comment by curry684** [comment]
I can reproduce this in 4.0.1, services are marked public:
```
Information for Service "cache.app"
===================================

 ---------------- -------------------------------------------------- 
  Option           Value                                             
 ---------------- -------------------------------------------------- 
  Service ID       cache.app                                         
  Class            Symfony\Component\Cache\Adapter\TraceableAdapter  
  Tags             cache.pool                                        
  Public           yes                                               
  Synthetic        no                                                
  Lazy             no                                                
  Shared           yes                                               
  Abstract         no                                                
  Autowired        no                                                
  Autoconfigured   no                                                
 ---------------- -------------------------------------------------- 
```
Yet indeed fetching them from the container yields the exception. I half expected `composer req cache` to fix it but it doesn't.

**Comment by xabbuh** [comment]
Where do you make these calls to `get()`? It inside a controller, how does its code look like? If anywhere else, how do you get access to the container?

**Comment by curry684** [comment]
@wtorsi I expect you're deriving your controller class from `AbstractController`? If so, the behavior is expected, albeit imho downright confusing and unintuitive right now - that base class does not get the entire service container injected, just a small set of whitelisted services in a ServiceLocator. The cache classes are not in the whitelist.

If you change the base class to `Symfony\Bundle\FrameworkBundle\Controller\Controller` you *will* get the full container and it'll work as expected.

Must say this is a pretty terrible piece of DX here, and the debug output just makes it more confusing.

**Comment by weaverryan** [comment]
@nicolas-grekas this looks like the issue we we’re chatting about. What do you think about patching in a better error message in 3.3? This feels like a clear usability bug (and easy fix).

**Comment by wtorsi** [comment]
@curry684 thank you, you are right. Extending from `Controller` makes full container available. 
Never thought about this.

**Comment by curry684** [comment]
@nicolas-grekas let's have a separate discussion here from your PR, which I think is a good idea in general to improve DX when using ServiceLocators, but doesn't solve the issue at hand here in this issue.

The true issue is that the bit of documentation I mentioned above currently is downright **wrong** but *should* be right. It *should* be impossible to access services directly via `$this->get()` or `$this->container->get()`. And looking at the code, it should be trivial to make it so.

Right now all "controller behavior" is implemented in `ControllerTrait`, which does not make any assumptions about the visibility of `$this->container`. All functions in that trait already use `$this->container->get()` instead of `$this->get()`, so it doesn't need the `has` and `get` functions itself. So, if we make `$container` private in `AbstractController`, and move `has` and `get` from the trait to `Controller`, the documentation is suddenly *right* and @wtorsi would've gotten an unknown method PHP error, and no IDE autocomplete hinting it should work.

Even if we consider this a BC break if we change it now, we could stub `has` and `get` in `AbstractController` to issue a deprecation warning if the ServiceLocator does have the service, and throw an explicit `You should not use get() or has() when deriving from AbstractController, use Dependency Injection instead` for perfect DX until 5.0 arrives.

**Comment by nicolas-grekas** [comment]
Providing a locator to users is actually a feature of AbstractController. I already use it to benefit from the laziness it provides for my own services. So I'm not sure about that plan at all...

**Comment by curry684** [comment]
We wouldn't have to hide the locator itself. The confusion arises mainly from using `$this->get` which for the past 5 years has allowed blanket access to the container. The locator provides a different role.

**Comment by weaverryan** [comment]
I agree with @curry684: it’s confusing to continue offering get(), but where it is suddenly this partial container (most users don’t know about the locator or how it’s setup). I wrote the incorrect docs because that’s how I (incorrectly) assumed AbstractController worked. The current behavior is surprising.

I do definitely still want the shortcuts (and laziness those shortcuts give me), just not the user-accessible get() method and container. Wdyt?

**Comment by weaverryan** [comment]
... or, as we discusssed, a service not found error when using get() on AbstractController needs a very special error message to explain what’s going on :)

**Comment by curry684** [comment]
If we agree on the direction I'll gladly pick up the work on it. We can then review the implementation for details on when to throw and how.
