### ISSUE TITLE
[DomCrawler] Can't override createSubCrawler()

### ISSUE THREAD

**Issue by TonyBogdanov** [symfony/symfony#25540]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | -
| Symfony version  | dev

As seen in the following code, one cannot override the private method `createSubCrawler()`:

https://github.com/symfony/symfony/blob/5f72ecff1534b9a677a3b2016dc2ddd0bfda5b21/src/Symfony/Component/DomCrawler/Crawler.php#L1145-L1147

What is the reason behind the decision to make this method private? Also, if it *absolutely* has to be private, then why use `new static(...` instead of `new self(...`, e.g. why invoke the constructor of the final class, if the call cannot be changed?

As of right now it is impossible to have a class extend the crawler and define a different constructor, or override the `createSubCrawler()` to internally pass on it's context to the new instance keeping the original constructor.

Can the method be switched to `protected`, so extenders may inject context?

**Comment by stof** [comment]
the decision to make it private is because we **always** make things private, unless we explicitly decide to make it a supported inheritance-based extension point. And we don't do it without a clear use case where we decide that such extension point is indeed the right solution (inheritance-based extension have a *huge* cost regarding our BC policy)

**Comment by TonyBogdanov** [comment]
I understand your point.

However, if this is the case then, why not make the class `final`, it surely won't break any BC if it was never meant to be extended, but would properly convey the *you should not extend this* message to developers.
Or perhaps you only meant it for the sub-crawler feature?

Can you think of a use-case where one would want to extend the crawler with additional functionality, but not sub-crawlers? IMHO using `new static` explicitly conveys intention to allow for sub-crawler inheritance.

P.S. Thank you for the quick response!

**Comment by stof** [comment]
Well, `new static` was used in the code *before* the introduction of the private method (where initialization code was not copying the private properties but only calling the constructor).
I'm not sure inheritance-based extension of the crawler ever worked fine for some use cases. But the introduction of a private `createSubCrawler` did not made anything worse (it stayed exactly the same).

Here, you are asking us to turn this method into a supported extension point. So we need use cases where this extension point is necessary, not vague arguments saying "I don't see when it would not be necessary"). If we cannot understand why it is necessary to have it, we won't pay the cost of maintaining it (this cost is on us, not on the guy opening the PR to change the visibility).

All cases I saw in the past about extending the Crawler class were about adding extra methods in it (which is not covered by our BC policy btw, as it would otherwise forbid us to add any new method), and these were not involving copying extra state when creating sub-crawlers.

**Comment by TonyBogdanov** [comment]
I guess the only real use case would be if one wants to associate some kind of data with a node, but that can easily be achieved with something like `SplObjectStorage` and generally shouldn't be of the crawler's concern.

Like you said, less extension points, less things to worry about, so I suppose it is OK as it is right now.

Should I close this?

**Comment by xabbuh** [comment]
Let's close then.
