### ISSUE TITLE
[TwigBundle] TemplateCacheWarmer may pass objects into loadTemplate

### ISSUE THREAD

**Issue by zlikavac32** [symfony/symfony#25712]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

`TemplateCacheWarmer` passes `TemplateReference` into `loadTemplate` which can cause error if for certain reason `Twig_Environment` is to be extended, `declare(strict_types=1)` is used in the extending class and `$name` is passed into a method that has `string` type hint.

```php
private function doSomething(string $template): void
{
    //do something
}
```

Method  `loadTemplate` defines `$name` as `string`.

Since `__toString` method exists, cast to `string` would solve the issue.

It's not anything urgent, it's easy to bypass that, but I think this will certainly pop up sooner or later, when strict types are added to the `TemplateCacheWarmer` itself, so why not mention it here :)

I can submit PR as well.

**Comment by m-vo** [comment]
@fabpot Why was this closed? This is still an issue in 4.4.

**Comment by fabpot** [comment]
If it's still an issue, can you submit a PR so that we can review the change that would be needed?

**Comment by m-vo** [comment]
If I see this correctly, the `TemplateCacheCacheWarmer` calls `Environment#load()` with `TemplateReference` objects:

https://github.com/symfony/symfony/blob/6ccc63ff69f4a37439120665d109c13a42f5bf76/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheCacheWarmer.php#L70-L81

In Twig 2 there are no strict type hints, so the object gets passed on and ends up in the calls made to the loader (`LoaderInterface`). The interface clearly states that names can only be strings and from Twig 3 this is enforced by a type hint. That's why our own loader that fulfils the interface breaks with Symfony 4.4 code. 

I'm not sure I'm fully aware of the history of that code (or the transition to Twig native components). Can we safely add a string cast to this usage?
