### ISSUE TITLE
Question about Norsk language support

### ISSUE THREAD

**Issue by vulkodava** [symfony/symfony#25792]
Hello, this is not a bug just a question.

Can I ask why from 2.2 to 2.8 versions, and beyond, language support for Norsk changes from NO to NB and back to NO (the two variations)? And is it possible to actually have support for the both?

Thank you in advance for your time :)

**Comment by xabbuh** [comment]
Can you explain which component's translations your are talking about?

**Comment by vulkodava** [comment]
Yes, I am sorry :) Basically, this question includes all the translatable components of Symfony, but the particular issue I've stumbled on was with validator's messages in the Form component.

**Comment by derrabus** [comment]
Since Symfony does not offer two Norwegian translations (which would be NB and NN, if Wikipedia did not lie to me), using the more generic NO seems like the correct choice to me.

So, your suggestion would be creating a NB language file with an exact copy of the NO file? What problem would that solve?

**Comment by vulkodava** [comment]
Hello, well, my question was if Symfony could support both Norwegian locales, but if not, of course, we could extend them in our app :) But since it was core Symfony functionality I thought it might have been a good idea to not override and mask it. :) And it was just a question :)

**Comment by derrabus** [comment]
My previous statement was wrong, Symfony actually offers two Norwegian language files: NO and NN. Sorry, I shot too early.

> And it was just a question :)

And I was only asking questions as well. I was just trying to find out what you want to change and how that would help you. I don't know enough about Norwegian to form an opinion so I'm asking questions to understand your motivation. I'm just curious, that's all. 😃 

The change you were talking about has been made with #17785 by @valisj. Maybe he could give you more insights. He actually suggested that an NB language file could be created as an exact copy of the NO file to make the NB locale usable.

So if your application needs to support both variants of the Norwegian language, you could use NO instead of NB as a locale if you want to refer to Bokmål and NB if you want to refer to Nynorsk. Would that be an option for you?

**Comment by vulkodava** [comment]
Thank you :) Haha, it is awesome to be curious :D I am as well :) Didn't mean to sound harsh, sorry about that :). 
But, yes I do need both language variations. The interesting thing is that I cannot find the validatiors.nn.xlf file in both 2.8 and 3.4 versions, just the one validators.no.xlf. So for those two versions we will just add the needed file in our codebase, not in the lib :)

Thank you a lot, though :)

**Comment by vulkodava** [comment]
Hmm, but `nn` actually works :) Will have to investigate this a bit more :) Thanks again

**Comment by vulkodava** [comment]
Well, this was all misleading. I wrote Form component, but the problem lies also in the Validator component as well. Which looks a bit weird to me, though is that Validator component has both `no` and `nn` files and Form component has only `no` file.

**Comment by xabbuh** [comment]
So duplicating the NO file in the Form component for NN would be a solution?

**Comment by vulkodava** [comment]
Well, as I am not Norwegian I also cannot say if in this particular case this would be enough, since the two variations NO and NN do have a lot of differences but I am not sure about the strings in Symfony's components. I will fix our cases by coping all the Symfony's components' translations and extend them in our code base and will give them to our Norwegian colleagues to do the actual translation.

Otherwise, if one is not particularly interested in the differences between the two variations, yes, copy&paste would do the trick.

**Comment by xabbuh** [comment]
Maybe @valisj as the creator of #17785 can help us here.

**Comment by xabbuh** [comment]
@andrerom maybe has some good input for us too :)

**Comment by valisj** [comment]
Hi @vulkodava! To answer the first question -- I can't really comment on what happened with the Norwegian translations before my PR (#17785), but as far as I can see from what I did 2 years ago, this is what happened:
- I renamed the `src/Symfony/Component/Validator/Resources/translations/validators.no.xlf` to `src/Symfony/Component/Validator/Resources/translations/validators.nn.xlf`, because the translations in the original `validators.no.xlf` were in nynorsk (`nn`), not bokmål (`nb`). I then decided to keep the `no` locale for bokmål.
- I renamed `src/Symfony/Component/Validator/Resources/translations/validators.nb.xlf` to `src/Symfony/Component/Validator/Resources/translations/validators.no.xlf`, so that those already using `no` locale would still be getting translations. 

Only the Validator form had the nynorsk (`nn`) translation.

As for the second question -- having support for the two written standards (`nb`/`no` and `nn`) is totally doable. You would just have to create `*.nn.xlf` files for all of the components you are interested in having the additional standard.

Some thoughts regarding choice of locales -- Choosing `no` as the locale for bokmål was probably not the best choice, since `no` is not recognized as a valid language code by any of the ISO standards (please, correct me on this). The reason I did keep the `no` code was simply because the rest of the translations also used `no` for bokmål.

Hope this clarifies a bit!

**Comment by andrerom** [comment]
On first look the changes seems fine, at least I can see we have been mapping `nor_NO, aka Norwegian (Bokmål)`, the main one, to `no` for [5 years already](https://github.com/ezsystems/ezpublish-kernel/blame/7584fd58f1246e469566cc32d1dc2449f10ca348/eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml#L33-L34).

However searching around to double check locales it seems this is not that clear, these refer to `nb` being the right one:
- https://github.com/TakahikoKawasaki/nv-i18n/issues/9
  - Referring further to http://i18n.skolelinux.no/localekoder.txt (in Norwegian)
  - Newer version of that: http://people.skolelinux.org/pere/blog/Spr_kkoder_for_POSIX_locale_i_Norge.html (in Norwegian)
    - Further referring to among others:
    - http://www.loc.gov/standards/iso639-2/php/code_list.php
- Apparently the locale list on iOS: https://gist.github.com/jacobbubu/1836273
- https://en.wikipedia.org/wiki/Norwegian_language
- Several locale lists: https://stackoverflow.com/questions/3191664/list-of-all-locales-and-their-short-codes
  - On my own mac `/usr/share/locale/` contains `nb` and `no, no_NO, no_NO.ISO8859-1, no_NO.ISO8859-15, no_NO.UTF-8`

But there are also plenty of places referring to `no_NO` as the right one:
- https://bugs.openjdk.java.net/browse/JDK-4093415
- https://gcc.gnu.org/onlinedocs/libstdc++/manual/localization.html
- https://docs.moodle.org/dev/Table_of_locales

Maybe our no translator @glye has something to add to this.

But to sum up the thread, usage of `no` might be wrong but changing it will be another break, and `nn` translation is missing in some places?

**Comment by glye** [comment]
Officially, Norwegian is _one_ language, with _two_ written forms, of equal official status. In practice, nearly 90% use bokmål. (Don't ask, it's a long story, and wars have been fought over less. See the wiki page @andrerom linked to.)

I agree with @andrerom that `nb` for bokmål is the most correct, and `no` refers to both (inclusive). Using `no` for bokmål may offend the more vocal part of the `nn` minority. In practice it's not a big deal, people don't care that much about a label that's not visible in daily end-user usage. It's more a nice thing to do.
(Disclaimer: We're both in the bokmål majority...)

**Comment by valisj** [comment]
> @valisj do you remember some references on usage of no over nb?

@andrerom Some translation files used `no`, some `nb`, some had bokmål in `nn`. So, it was kind of a mess to begin with.

As for the `nb` vs. `no` discussion, I agree that `nb` would be more suitable if the `nn` standard is also present.

**Comment by andrerom** [comment]
@xabbuh unsure if this cleared up things for you? It's at least clear to me why the changes where made, so unless you want to cleanup the inconsistency in a non breaking way I guess only issue here is lack of `nn`, and as a starting point they can be created by using `no` but we should probably try to find someone who can contribute to it so it's fixed up.

**Comment by xabbuh** [comment]
:+1: so if one of you wants to create the PR, that would be great

**Comment by derrabus** [comment]
Does any of you know Nynorsk well enough to update/correct the NN files?

**Comment by andrerom** [comment]
> Does any of you know Nynorsk well enough to update/correct the NN files?

In my case no, as @glye said we are both in the `nb` region.

**Comment by valisj** [comment]
> Does any of you know Nynorsk well enough to update/correct the NN files?

My case is the same as @andrerom's.

@vulkodava You mentioned that you had Norwegian colleagues. Maybe they could help out if they know nynorsk?

**Comment by glye** [comment]
> where most avoid nn like the plague

Speak for yourself ;) I am `nn` by birth if not environment. I know it well enough for a semi-decent translation and have done it for eZ in the past. But what's the size of the job? @andrerom may not appreciate me spending days/weeks on this.

**Comment by andrerom** [comment]
Someone able to setup initial PR so we see how many strings we need to deal with?

**Comment by glye** [comment]
Judging from https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=filename%3Ano.xlf&type= it's not much at all, just 3 small files. I could do that.

**Comment by andrerom** [comment]
So can anyone confirm that is all affected files? If so 👍 

(also assuming the one nn file is relevant here for course: https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=filename%3Ann.xlf&type=)

**Comment by vulkodava** [comment]
Nice, I would like to thank all of you, guys for the time and the extra effort. I saw @glye would take care of the `nn` translations so I guess it is not needed for me to seek my Norwegian colleagues :)

Thank you, @glye, for that :)

**Comment by glye** [comment]
YW. Is it agreed that we rename all `no` to `nb`, then copy to `nn` and translate?

**Comment by derrabus** [comment]
> that we rename all `no` to `nb`

Shouldn't we rather we keep the `no` files as exact copies of the `nb` ones, so that developers may use either locale? Also, I don't want to break applications that already rely on the `no` locale being available.

**Comment by stof** [comment]
we indeed cannot remove support for `no` as it would be a BC break.

What we can do is having both of them with the same content. If this is the case, please add a unit test in the corresponding component ensuring that the no and nb files stay in sync (this is easy to automate, and very hard to remember to enforce manually otherwise).

**Comment by glye** [comment]
Anyone who wants to share the job? 😉 I can start on `nn` translation since that is independent of the bokmål copy & test.

**Comment by derrabus** [comment]
Copying files and creating unit tests? That sounds like I don't need to speak Norwegian for this task. I'll do it.

**Comment by glye** [comment]
`nn` PR: https://github.com/symfony/symfony/pull/25809

**Comment by andrerom** [comment]
@derrabus Maybe deprecate `no` then in 4.x and add a explicit note in all involved files that changes to strings should be reflected across both `no` and `nb` until `no` is removed in 5.0.

Or someone add some kind of alias feature to translation system so we can setup `no` as alias for `nb` :P

**Comment by derrabus** [comment]
> Maybe deprecate `no` then in 4.x and add a explicit note in all involved files that changes to strings should be reflected across both `no` and `nb`, until `no` is removed in 5.0.

I'm not sure about this. I could imagine two scenarios:

1. Multilingual application: I have an application that has been translated into 20 languages and Norwegian is one of them. I most likely won't ever support a second Norwegian locale. Using `nb` instead of `no` here would probably confuse developers and users alike although it would be the more precise language code.

2. An application that targets Norwegians from different regions: I develop an application that needs to distinguish between the two variants of the language. If I used the generic `no` alongside the more specific `nn`, that would look pretty odd, I guess.

So, from my point of view, if it does not create too much extra maintenance overhead, I would keep `nb` and `no`. After all, the name of the locale could be part of your public interface, for instance if you're building routes like `/{_locale}/some/page` as [described here](https://symfony.com/doc/4.0/translation/locale.html#the-locale-and-the-url). So it's not a 100% internal representation.

> Or someone add some kind of alias feature to translation system so we can setup `no` as alias for `nb` :P

That sounds like a reasonable idea. 😃

**Comment by derrabus** [comment]
See #25812 for the new `NB` locale.
