### ISSUE TITLE
Symfony4 is not returning exceptions as JSON, even with _format: json explicitly defined.

### ISSUE THREAD

**Issue by naroga** [symfony/symfony#25905]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | ?
| Symfony version  | 4.0.3

I have the following snippet defining a route:

```channel_create:
    path: /channel
    controller: App\Controller\ChannelController::create
    methods: [POST]
    defaults:
        _format: json
```

On Symfony3-, any exception thrown inside `ChannelController::create` would generate a JSON response. However, the current version seems to be ignoring the `_format` directive (even though the docs are still telling me to do exactly like this).

**Comment by Simperfit** [comment]
Are you using flex ?
What did you change ?

Because as far as I try to reproduce, it seems to work when twig-bundle is installed and not when twig-bundle is not installed.

see https://github.com/Simperfit/symfony-router-error/commits/master
Status: Reviewed

**Comment by naroga** [comment]
@Simperfit oh, I didn't know I had to have twig-bundle installed.

Should I close this, then?

**Comment by derrabus** [comment]
The fact that you need TwigBundle to have proper error handling will keep confusing people. Especially for API-only applications, this is really unexpected.

I think we should do something about that.

**Comment by fabpot** [comment]
I agree with @derrabus, that's something we need to work on for 4.1.

**Comment by Simperfit** [comment]
@naroga I don't think either this should be closed but we should add a new feature that is not twig-dependent in 4.1 to be able to have a proper json error.

@fabpot Do you have something in mind that we could do to fix this ? I can work on a fix.

**Comment by Simperfit** [comment]
So, Are you ready for a long explanation message ? :p 

I'm looking into this, what I wanted to do is to add a format in the `\Symfony\Component\Debug\ExceptionHandler` in order to be able to switch from html to json and have a special method  just like the `getHtml` method.

But, I cannot do this since the `_format` parameter is no more part of the `RequestStack` because it has been poped in the `finishRequest` method so when I get in the  `DebugHandlersListener` the request is a new one and the `_format` does not exist anymore.

```
//\Symfony\Component\HttpKernel\HttpKernel::handleException :

  // a listener might have replaced the exception
        $e = $event->getException();
        if (!$event->hasResponse()) {
            $this->finishRequest($request, $type);

            throw $e;
        }
```

What I want to achieve is to pass the _format in the new request, but as the time of writting I still don't know how to do that and if it's the good way to do it.

cc @stof @fabpot @nicolas-grekas if you have an idea or a better way to do it, i'm full in.

Thanks!

**Comment by naroga** [comment]
@Simperfit any news on this implementation?

**Comment by Simperfit** [comment]
I'm still not sure that this is the way @naroga so no for the moment, if we know this is the right way to fix it, I can work on a fix.

**Comment by yceruto** [comment]
@Simperfit I looked at this code and I think I found a way to solve it, I need to do some test first but I'm already preparing the PR.

**Comment by yceruto** [comment]
PR sent https://github.com/symfony/symfony/pull/30851

**Comment by Simperfit** [comment]
Thanks @yceruto !!
