### ISSUE TITLE
No possibility to pass parameters in constructor of bundles in SF4

### ISSUE THREAD

**Issue by gregurco** [symfony/symfony#25913]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0.0

In SF4 disappeared possibility to pass any parameters in constructor of bundles. For example, we used this possibility in eightpoints/guzzle-bundle for the plugin system:
```php
new EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle([
    new Gregurco\Bundle\GuzzleBundleWssePlugin\GuzzleBundleWssePlugin(),
])
```
This plugin system was proposed by Matthias Noback and described in https://github.com/matthiasnoback/symfony-bundle-plugins.

The problem is that in SF4 bundles are instantiated in another way: https://github.com/symfony/demo/blob/master/src/Kernel.php#L41
As you can see, there are no parameters passes to constructor.
Was it done specifically or symfony team thought that nobody use constructor?

I discussed this problem with Matthias and proposed workaround: https://github.com/matthiasnoback/symfony-bundle-plugins/issues/17#issuecomment-359380333
but in this way we should ask user to modify **src/Kernel.php**:
```diff
- yield new $class();
+ yield new $class(...$envs['constructorParameters'] ?? []);
```
and then to add parameters in **config/bundles.php**:
```php

return [
    ...
    EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle::class => [
        'all' => true,
        'constructorParameters' => [[
            Gregurco\Bundle\GuzzleBundleWssePlugin\GuzzleBundleWssePlugin::class,
        ]]
    ],
];
```

As write Matthias, it's not elegant solution and I agree with him.
Do you have any ideas or suggestions? How to keep this possibility to use plugin system? Should some changes appear in symfony or proposed workaround is ok?
Thanks :sweet_potato:

**Comment by derrabus** [comment]
Well, tbh I don't see what problem this plugin bundle system solves. Your plugin could very well be a bundle instead.

Apart from that, the `Kernel` is part of your project code. You can add your complex bundle initialization to the `registerBundles` method, like you would have done in Symfony before Flex.

**Comment by stof** [comment]
I don't see the need for this plugin system:

- registering services can be done by normal bundles directly
- doing work during `build()` (for instance registering compiler passes
- doing work on boot can be done by normal bundles directly (and this should be avoided anyway)
- registering a plugin extending a DI extension class can already be done from other bundles (with a different API of course). The SecurityBundle does it.

So the question is how common this use case is.

Thus, plugins won't come from the same bundle than the original bundle (otherwise you don't need to use plugins), so you would loose any benefit of the Flex auto-registration of bundles if you use a *different* plugin system rather than hooking into a bundle from another bundle (which can both be auto-registered).
So I don't think such plugin system makes sense in a Flex world.

Note that Symfony 4 does not forbid passing constructor arguments to bundles. This is Flex not supporting it. Someone using SF 4 without Flex is not affected by this, and someone using Flex with Symfony 3.4 has this issue.

**Comment by stof** [comment]
and indeed, you can still register this bundle in `registerBundles` directly instead of putting the class name in `config/bundles.php` (meaning, registering this bundle in the non-Flex way) if the API stays the same (just be careful that the Flex kernel uses a generator rather than returning an array, so you will need to `yield` your bundle instead rather than adding it in an array of bundles).

**Comment by xabbuh** [comment]
I am going to close here as there is nothing that could be fixed and as @stof explained you are still able to instantiate bundles manually if required.
