### ISSUE TITLE
[Session] Please do not deprecate MemcacheSessionHandler

### ISSUE THREAD

**Issue by klandaika** [symfony/symfony#25931]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4+

PR #24443 deprecated memcache in favor of memcache**d**. Memcached extension is not available for Windows. So essentially memcached server session mechanism will be unusable on any windows servers. 

The reasoning given for PR was that pecl repository does not have a memcache version compatible with php 7, however there is a popular repository which has made it compatible: https://github.com/websupport-sk/pecl-memcache

Our whole infrastructure around 60 servers are all dependent on that session mechanism and we compile memcache extension from source mentioned above without issues (for php 7.0 - 7.2). 
If this deprecation is not reverted we, (and any other windows platform that relies on memcache for sessions) will be forced to maintain our own copy of `MemcacheSessionHandler` which won't be marked as deprecated.

**Comment by Tobion** [comment]
From https://github.com/websupport-sk/pecl-memcache

> New API in 3.0: Version 3 introduces a new class "MemcachePool" which implements the new API, the 
 old class "Memcache" is still retained (but is deprecated) with the same interface 
 for backwards compatibility.

So the API used by the MemcacheSessionHandler is deprecated as well. What's the point in keeping it then? If there is a need for memcache, it should use the new memcache API. But as long as that extension is not the official successor, I doubt it should be included in symfony.

**Comment by mvrhov** [comment]
Also the memcache is a BAD bad choice for session storage. Unless you really like WTF moments when the memcache will decide that it doesn't have enough memory and will start removing the active sessions.

**Comment by nicolas-grekas** [comment]
I'm closing this issue because I think we are not going to reconsider this decision for the given reasons.
BUT @klandaika that doesn't mean you cannot copy/paste the class and use it in your own code if you need it! The license allows that. The only thing you won't get is maintenance for free from the community - because we cannot just not afford it for just you (and a few others maybe, still a small minority.)
If you want to make it a separate open-source package you'd like to maintain, that's also possible if you decide to.
