### ISSUE TITLE
Cannot create header without a date

### ISSUE THREAD

**Issue by garak** [symfony/symfony#25934]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

Commit https://github.com/symfony/http-foundation/commit/28209d9e670787ad473ef424ae00ffab442bd51d introduced a mandatory date header for Response, quoting "RFC2616 - 14.18 says all Responses need to have a Date".
Anyway, [RFC](https://tools.ietf.org/html/rfc2616#section-14.18) states three exceptions for such rule.

**Comment by derrabus** [comment]
First of all, if a php application does not set a date header, then the webserver that sits in front of it most likely will issue one automatically.

Side note: We should probably change the reference to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-7.1.1.2), since RFC 2616 is obsolete. 😉 

Anyway, let's have a look at the exceptions:

> An origin server MUST NOT send a Date header field if it does not have a clock capable of providing a reasonable approximation of the current instance in Coordinated Universal Time.

I think, we can safely ignore this case – unless you have an example of a device that runs php but does not have a hardware clock.

> An origin server MAY send a Date header field if the response is in the 1xx (Informational) or 5xx (Server Error) class of status codes.

Okay, here the header is not mandatory. The reason behind the exclusion for the 5xx class is that the device issuing the response could be in a state that does not allow to retrieve the current time. If our server was that broken, it doubt that the request would even hit our application.

In order to keep things simple, I would advise to not change this behavior. What would be your motivation to change it?

**Comment by giorgiosironi** [comment]
I originally encountered this problem [during tests](https://github.com/elifesciences/api-problem-php/pull/3):
```
       $response = $handler->handle($apiProblem);
       $this->assertSame([
           'cache-control' => ['no-cache, private'],
           'content-type' => ['application/problem+json'],
       ], $response->headers->all()); // fails, and assertion can't be made without removing the header first
```
In general:
```
        $actual = new ResponseHeaderBag(['Content-Type' => 'application/json']);
        ...
        $expected = new ResponseHeaderBag(['Content-Type' => 'application/json']);
        $this->assertEquals($expected, $actual); // may or may not fail depending on how long the test takes
```
So my concern was not really about not having a `Date` header (headers can be added transparently, at will, by proxies and other middleware), but about a Value Object that may randomly fail equality comparisons. The more so if webservers would be able to set it automatically anyway.

**Comment by nicolas-grekas** [comment]
I don't think we should change the behavior here. This is legitimate per HTTP.
You should adapt your tests. One way is to use ClockMock (there might be more)
see https://symfony.com/blog/new-in-symfony-2-8-clock-mocking-and-time-sensitive-tests
