### ISSUE TITLE
Twig absolute_url function doesn't always take base url into account

### ISSUE THREAD

**Issue by Korikulum** [symfony/symfony#25993]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4

The twig `absolute_url` function doesn't take the base url into account in some cases:

- in web context with url `http://test.loc/app_test.php/`
```twig
{{ absolute_url('?test=1') }}
```
Expected result:
```html
http://test.loc/app_test.php/?test=1
```
Actual result:
```html
http://test.loc/?test=1
```

- in cli context with `router.request_context.base_url` set to `app_test.php`
```twig
{{ absolute_url('#test') }}
{{ absolute_url('?test=1') }}
```
Expected result:
```html
http://test.loc/app_test.php/#test
http://test.loc/app_test.php/?test=1
```
Actual result:
```html
http://test.loc/#test
http://test.loc/?test=1
```

**Comment by stof** [comment]
`absolute_url` does not force the usage of the `/app_dev.php` part, because it would then be unusable for assets (which are the main use case, as the route is already able to generate absolute URLs on its own).
I'm not sure we want to change it.

Btw, generating an absolute URL for just `?test=1` or `#test` is ambiguous, as the target of such link depends on what the current URL is in a browser. So in a CLI context, we cannot have it fully, as we don't have a current URI (and for now, it is at least consistent).

**Comment by fabpot** [comment]
Closing for the reasons given by @stof
