### ISSUE TITLE
[web-link] Documentation links not working

### ISSUE THREAD

**Issue by Tasiobg** [symfony/symfony#26054]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | x.y.z

Here https://github.com/symfony/web-link
There are some broken links:
https://symfony.com/web-link
https://symfony.com/doc/current/components/weblink/introduction.html

**Comment by javiereguiluz** [comment]
@Tasiobg thanks for reporting these errors. The `symfony.com` redirection is pending on some changes in the private repo that contains the code of that website.

The other 404 is because the doc for WebLink is not ready yet. We're taking care of that in https://github.com/symfony/symfony-docs/issues/7515, which is the repo where we deal with doc issues.

I'm closing this because we have issues for it the other mentioned repos, but thanks again for reporting these issues!
