### ISSUE TITLE
Why store .env parameters in environment variables ?

### ISSUE THREAD

**Issue by ningollan** [symfony/symfony#26154]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.4

I don't understand why in production we should use environment variables.

I'd like to know why you did that ? Instead of keeping one .env file per env like before.
This causes differences between dev and prod env and then you're completely dependent of the server of your application.

Here is my source : 
https://diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/

Thanks in advance for the answer.

**Comment by javiereguiluz** [comment]
We recommend to use env vars for some config params because that's the best practice recommended in the industry (and used by lots of other comparable projects). But this is not mandatory at all. You can remove the `DotEnv` component and only use regular config params as in older Symfony versions. I do that in some small personal apps where env vars don't provide anything useful to me and they just complicate things.

**Comment by theofidry** [comment]
>I don't understand why in production we should use environment variables.

Nobody said you _should_, but you _can_. Environment variables support has been added for allowing dynamic variables on some platforms like heroku among other things. It doesn't mean you should make all your parameters dynamic. Instead, you can use the good old `parameters.yml`. It's not going anywhere.

Also your source is only partially right as there is less issues with containers and you can also use tools like [Terraform](https://www.hashicorp.com/products/terraform).

That said your comments hints that there is a part of the doc or something suggesting otherwise, could you point us to it? This should be changed

**Comment by ningollan** [comment]
Thanks for your answers, it helps me !

In the doc, nothing suggest to use the old way to use env parameters, i was just curious to know why it was like this now.

I will close this issue because you answered correcly to my question :)

**Comment by ningollan** [comment]
I'm sorry to reopen it, but i have one more question : 
What are the consequences to not use environment variables ?
All the Symfony components will work anyway ?

**Comment by iltar** [comment]
The biggest difference is that without environment variables, you'll have to rebuild the container and thus usually redeploy your application. With environment variables, you can build and configure your application independently.

It will work just fine without .env vars

**Comment by ningollan** [comment]
Ok thank you, i just have some updates to do in the public index.php, to not call $_SERVER variables.
