### ISSUE TITLE
[ Security ][ Firewall ] Bug in the last version with SimpleFormAuthentication

### ISSUE THREAD

**Issue by luismatesanz** [symfony/symfony#26172]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | 
| RFC?             | 
| Symfony version  | Since version 2.7

In the last version im detected a bug in component SimpleFormAuthentication when check if only accept method POST. If configuration security form set "post_only: false" the variable $requestBag get a Object Request and try getParameterBagValue with object wrong.

path:symfony/symfony/src/Symfony/Component/Security/Http/Firewall/SimpleFormAuthenticationListener.php
namespace Symfony\Component\Security\Http\Firewall;
method: protected function attemptAuthentication(Request $request)
line: 102

```php
        $requestBag = $this->options['post_only'] ? $request->request : $request;
        $username = ParameterBagUtils::getParameterBagValue($requestBag, $this->options['username_parameter']);
        $password = ParameterBagUtils::getParameterBagValue($requestBag, $this->options['password_parameter']);
```

For fix the problem i need downgrade version.

**Comment by iltar** [comment]
In 2.7 that class did not exist yet, but as of 2.8 it does. The method signature is:

```php
public static function getParameterBagValue(ParameterBag $parameters, $path)
```
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Http/ParameterBagUtils.php#L39

In 2.7 this was using `->get()` directly on either the request or parameter bag, which works due to ducktyping: 

```php
$requestBag = $this->options['post_only'] ? $request->request : $request;
$username = $requestBag->get($this->options['username_parameter'], null, true);
$password = $requestBag->get($this->options['password_parameter'], null, true);
```

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Security/Http/Firewall/SimpleFormAuthenticationListener.php#L111-L113

I can confirm this is a bug in 2.8+.

Status: reviewed

**Comment by chalasr** [comment]
👍 The form_login listener has been fixed in https://github.com/symfony/symfony/pull/26111, same patch needed

**Comment by xabbuh** [comment]
see #26173
