### ISSUE TITLE
Cache does not get rebuild when running bin/phpunit

### ISSUE THREAD

**Issue by Nijusan** [symfony/symfony#26189]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.0.4

So at first, i am not sure about this behavior, but it did cost me some time to understand what was happening.

for better understanding what is happening for me: https://github.com/Nijusan/alice-phpunit-fixtures

i was working on a new application and setting up alice bundle for loading fixtures for phpunit tests. i created first test with a fixture file loading correctly and all was fine. i then added a new custom faker provider in my source, included it in my fixture and ran phpunit again, but this time failing the provider i created is missing.

wondering why, at least i found out, that in the corresponding cache file the new class was missing, so calling explicit `bin/console cache:clear --env=test`solved the problem.

feels like not beeing a wished behavior ?

**Comment by Nijusan** [comment]
another example while migrating an legacy application, i got for a functional test the error `Failed to start the session because headers have already been sent...` so i activated in the framework config for env test the session.storage.mock_file, but still got the error... ah ok, `bin/console cache:clear --env=test` and its fine... so every change in the application that is written into the cache needs an explicit clear? 

am i the only one running into this problems? maybe its not a problem at all because clearing cache takes time and one would say that the configuration shouldn't change that often while developing your test and business logic?

**Comment by mccullagh** [comment]
Hi Nijusan,

The project mentioned above uses this code `static::createClient(['debug' => false]);`on https://github.com/Nijusan/alice-phpunit-fixtures/blob/master/tests/WebTestCase.php#L33 , this `debug` value is used for booting the kernel instead of the configuration from the `phpunit.xml.dist`. So far i know symfony uses this value to check if the cache is fresh here https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/Config/ConfigCache.php#L56 

I can't test it by my own right now.

**Comment by Nijusan** [comment]
@mccullagh thank you very much!! my fault i did not see this happening :/ !
