### ISSUE TITLE
[RFC] Make using the Filesystem component (a bit) simpler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#26357]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

I've always wondered why the Filesystem component doesn't define static methods, given that it doesn't define a constructor and doesn't store any state. My use case is that I'm tired of doing this:

```php
$fs = new Filesystem();
$fs->copy('...' , '...');
```

or

```php
(new Filesystem())->copy('...' , '...');
```

I'd prefer to have this in my code:

```php
Filesystem::copy('...' , '...');
```

If you agree with this, it would be possible to make this change and be backward compatible. Make all methods static and define a `__call()` method that allows to execute the non-static methods and displays the deprecation notice.

**Comment by Simperfit** [comment]
I guess it could be a little bit easier to use it, but is it really worth the work on the component to make everything static ?

**Comment by ro0NL** [comment]
from testing perspective im not to sure about static =/

also how would `__call` work? I dont think it does: https://3v4l.org/Cs8SG
'
we can only detect static calls with the current API, triggering a PHP deprecation: https://3v4l.org/tPXYB

**Comment by theofidry** [comment]
@ro0NL about testing I don't think this is an issue. You could do like done in Laravel where you can inject the instance used by the static Proxy. So I think we could do the other way around: keep stuff non static and do magic with `__callStatic`. Auto-completion could still be provided via `@method` annotations on the class.

I'm really 👍 for that change. From a usage perspective, keeping an instance of `FileSystem` doesn't make sense unless you do want to abstract your IO interactions which is far from always being the case..

**Comment by ro0NL** [comment]
> So I think we could do the other way around

nope :) https://3v4l.org/iieNH

**Comment by theofidry** [comment]
🤔 what about having a static proxy then? This way we have to change anything in the FS component

**Comment by ro0NL** [comment]
moreover, what about a plain function API...

```php
use function Symfony\Component\Filesystem\{fs_rename, fs_copy};
```

using a static proxy :P

**Comment by theofidry** [comment]
I actually use functions in [Box](https://github.com/humbug/box/tree/master/src/FileSystem) as I find it more convenient. I'm still missing the static proxy behind it though. Not an issue in practice for that project as I don't need to mock the FS, but that would be a requirement for Symfony.

**Comment by ostrolucky** [comment]
Here's how to do it https://3v4l.org/Za4KP Key is making current functions protected, so they are no longer visible from outside when making static call.

**Comment by Simperfit** [comment]
And this adds no overhead when using the component ?

**Comment by javiereguiluz** [comment]
@Simperfit I guess it does ... but any operation on the filesystem, even if you are using SSD disks, is orders of magnitude slower than your code, so it shouldn't matter.

**Comment by nicolas-grekas** [comment]
I'm :-1:, OOP is here for a good reason, going through global state to test is not enhancing anything, quite the contrary. @javiereguiluz just inject the Filesystem service and done.

**Comment by javiereguiluz** [comment]
I'm closing ... but I disagree 😃  Also, I don't think this is "a service", it's just a single utility class with a bunch of (static) methods. However, this could change in the future if this component could turn into a full featured component such as Flysystem (https://flysystem.thephpleague.com/).

**Comment by nicolas-grekas** [comment]
> I don't think this is "a service", it's just a single utility class with a bunch of (static) methods

fact is, this sentence is not correct, so you'd just need to change your mind here ;)

**Comment by frankdejonge** [comment]
Just to add a little nuance to this. I think there are 2 concerns at play here, but there's only one solution. It's not strange for the other concern not to be satisfied by the solution. As @nicolas-grekas mentioned, the global state if very important. This is true in places where this context provides the necessary import to complete the operation. Many of symfony/filesystem's use-cases require such context. However, there are many of them that don't. In these cases requiring an object is overkill, it feels like you're doing more stuff than needed. In those cases I'd actually not use the abstraction at all.

For the local filesystem PHP is the language which is probably the most pragmatic when it comes to filesystem operations. In this particular case, you can simply use the `copy` function, no need for any form of abstraction whatsoever. I think in general people should be ok with not using any abstraction, maybe this is especially good advice for Symfony users because most of what they use is abstracted or is interacted with through an abstraction. In general when you use an abstraction, it's always to ask "why" and see if there's an abstraction required for it and if so, does the abstraction's goal match your use-case?

**Comment by theofidry** [comment]
If you need an abstraction sure the current FS is the way to go. But in the
other case, I.e. dealing with PHP quirks, instantiating an object is
overkill.

Also note that if you really want an abstraction for FS, you are also
probably missing a lot of stuff from webmozart/path-util
