### ISSUE TITLE
Profiler makes requests slower

### ISSUE THREAD

**Issue by rjmr97** [symfony/symfony#26383]
Symfony version: 4.0.5

I created a new project using flex and it was working as usual (<1s response times). I started adding more bundles like annotations, twig, etc. and it kept working until I added the profiler bundle.

Now my requests take something between 3s-6s. The content loads fast (~1s) but after that the connection is kept open and ends after ~4s.

Is this the expected behavior? Is there something I can do?

Below is an example request before/after

![image](https://user-images.githubusercontent.com/30321188/36924277-e9a8956a-1e65-11e8-879a-b2859be96590.png)

![image](https://user-images.githubusercontent.com/30321188/36924087-4486f4b4-1e65-11e8-89e0-ca5871405040.png)

**Comment by nicolas-grekas** [comment]
You can profile using https://blackfire.io/ to discover what happens there.

**Comment by rjmr97** [comment]
Sorry but that's too complex for the situation, I'm just starting a new project and noticed that this happened (not a big deal, but the loading icon on the tab is a bit annoying).
Signing up to some service just to know what causes it is not really an option for me right now.

I did try to analyze it using webgrind but nothing showed up. The code runs really fast (~250ms).
There's seems to be something running (async?) after `$kernel->terminate($request, $response);` in `index.php` that may to be causing the delay in the request (saving profiling data?)

**Comment by iltar** [comment]
Generally speaking when you have an exiting application and _lots_ of deprecations (primarily from the container), it tends to cause large profiles, slowing down both the pages (due to profiler data processing) and reading in the web developer toolbar. It shouldn't be the case for a new application though. As nicolas said, if you want to find out _why_ this is slow, blackfire is a great tool to discover what part is being very slow.

**Comment by xabbuh** [comment]
I suggest we close here then if noone else is experiencing this behaviour.
