### ISSUE TITLE
symfony/debug ErrorHandler - infinite loop (?)

### ISSUE THREAD

**Issue by alcohol** [symfony/symfony#26438]
| Q                | A
| ---------------- | -----
| Bug report?      | yes (?)
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.5

We have run into a peculiar issue that only occurs under certain conditions, but due to the nature of a closed-source third party extension, we are not entirely sure what these conditions are. We can only see it happening (from time to time).

We use Sentry to track errors in our application (`sentry/sentry@1.8.3` & `sentry/sentry-symfony@1.0.0`). We also have a new relic extension installed (monitoring agent). Both of these register exception handlers. Most of the time, all is well, the sentry handler handles an exception and reports it to their API. End of process.

But sometimes, we end up in a loop where we see the new relic exception handler appear in the call stack (closed source unfortunately), and at this point we end up with some odd/peculiar circular reference where the sentry handler will see the symfony debug errorhandler as the prev handler, which in turn somehow ends up calling the sentry handler again, and this then repeats infinitely.

![screen shot 2018-03-06 at 17 51 20](https://user-images.githubusercontent.com/21414/37084601-415e260e-21f3-11e8-96dc-7e60b97eeebe.png)

Normally the callstack/timeline would end at the 1.25s marker. But in this screenshot you can see the loop start after this marker.

Not quite sure what to do with this, or how to provide more useful details 🤔 

Original error/exception that gets reported once (in _healthy/good_ flow):

```
Argument 2 passed to Foo::bar() must be an instance of X, null given, called in Y
```

Error being logged infinitely (until process is killed, in _unhealthy/bad_ flow):

```
Error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Foo::bar() must be an instance of X, null given, called in Y
```

**Comment by alcohol** [comment]
Just checked, `3.4.5` unfortunately :-(

**Comment by julia-morg** [comment]
I have the same issue with symfony 4 and sentry-symfony bundle.
First, symfony adds its ErrorHandler at Symfony\Bundle\FrameworkBundle\FrameworkBundle:boot()
Then Sentry-symfony adds its errorHandler (Raven_ErrorHandler)  and stores previous ErrorHandler
When the Fatal Error occures, Raven_ErrorHandler handles it, and calls the methods of previous errorHandler
But \Symfony\Component\Debug\ErrorHandler::handleFatalError contains instructions, which stores current error handler (e g raven errorhandler) as previous errorHandler of \Symfony\Component\Debug\ErrorHandler
So, \Symfony\Component\Debug\ErrorHandler handles error, then calls Raven_ErrorHanler. 
And Raven_ErrorHanler handles error and then calls \Symfony\Component\Debug\ErrorHandler
Infinite loop  : (

**Comment by Epskampie** [comment]
We faced a similar issue, but only during updating the php files. Infinite loop, causing thousands of errors to come in. :-) 

Shouldn't this bug be reported on https://github.com/getsentry/sentry-symfony instead?
Unfortunately it was hard to reproduce for us, but @julia-morg , you seem to have the best explantion and reproducible case, maybe it's best if you report it?

**Comment by Jean85** [comment]
Hi, Sentry SDK mantainer here. I'm currently trying to understand this bug, originally reported in https://github.com/getsentry/sentry-php/issues/552.

@alcohol which version of the NewRelic extension are you using? They just released v8, I don't know if that changes anything... I'm also struggling to reproduce the issue locally.

**Comment by alcohol** [comment]
Our servers just updated to 8.0.0.204-1 yesterday, before that they were running 7.7.0.203-1. Unfortunately, today, we actually just stopped using `sentry/sentry-symfony` and switched to using the Raven client as a Monolog handler instead.

**Comment by Jean85** [comment]
Thanks @alcohol for reporting back. Mind that the Monolog handler will not catch fatals BTW...

**Comment by alcohol** [comment]
Yeah, we are aware of that.

**Comment by alcohol** [comment]
I'm attempting to recreate our Docker container with the v8 extension and see if I can reproduce the problem again.

**Comment by alcohol** [comment]
Can confirm it still occurs with v8 of the new relic extension.

**Comment by Jean85** [comment]
@alcohol are you able to share a minimum reproducible case of your container?

**Comment by alcohol** [comment]
Yeah I'm pondering that really hard right now. Not sure how I will do this. It's my clients project. And the new relic extension requires a license and such.

**Comment by Jean85** [comment]
NewRelic license can be put as a build argument in the Dockerfile, you can use an env variable in the .ini to pass it through.

BTW I just confirmed that disabling the NewRelic extensions solves the issue! I was able to reproduce this only in production don't know why, but I re-deployed the container without the NewRelic ext and it stopped looping over the fatal error.

My setup:
 * PHP 7.2.3
 * Symfony 3.4.6
 * Sentry client 1.8.3
 * Sentry bundle 2.0.2
 * NewRelic ext 8 (when used)

**Comment by istepaniuk** [comment]
For anybody banging their heads against this, the loop can be there **OR NOT** for each request. 

Our guess is NewRelic's sampling makes the loop come and go.

**Comment by alcohol** [comment]
I dunno. It seems odd, because the extension should always be loaded and error collection should always be on I believe. Not sure that part is sampled.

**Comment by Jean85** [comment]
I've reported (like @alcohol) the issue to the NewRelic forum: https://discuss.newrelic.com/t/how-to-disable-newrelic-set-exception-handler/35544/23

Let's see what happens...

**Comment by alcohol** [comment]
Managed to reproduce it consistently with a very minimal setup. Will polish it tomorrow morning and throw it in a public Github repo.

Perhaps interesting to note: the first request to a freshly spun up container never fails and handles the flow normally. Every subsequent request runs into the infinite loop. It almost seems as if some state from the previous request carries over to subsequent requests within the same fpm child/thread?

**Comment by julia-morg** [comment]
We dont use newrelic, just symfony + sentry-symfony
And require 'any_missing_file' causes infinite loop
Besides i think that the reason is not on sentry side: Symfony Error Handler  attempts to set system error handler to the field  as a previous error handler when FatalError occures. You can see it in \Symfony\Component\Debug\ErrorHandler::handleFatalError
`
if ($handler !== $h) {
            $handler[0]->setExceptionHandler($h);
        }
`
Thin is the moment when the problem starts: Raven_ErrorHandler is $h,  $handler[0] is Symfony ErrorHandler. And Raven_ErrorHandler already contains the Symfony ErrorHandler as a previous ErrorHandler.
I made a fork of symfony/debug for my  project to stop this inifinite loop - just remove this instruction and problem is gone
Im not sure what this code had to do but i cant find any other way to stop thousands of errors in sentry

**Comment by alcohol** [comment]
I think this should help repro the issue. If not, please leave an issue on said repo with details: https://github.com/alcohol/repro-infinite-loop

**Comment by maximecolin** [comment]
We are having the same bug with Sentry. Some errors are reported thousands of times of the same occurence.

All errors being reported multiple times seems to be `Symfony\Component\Debug\Exception\FatalErrorException`. It could be a lead.

**Comment by Jean85** [comment]
@alcohol I had some small issues with file permissions, but in the end your repo reproduces the issue, thanks a lot!

@maximecolin yes the problem it's only on fatals with PHP 7+ due to the `\Throwable` interface, this issue and https://github.com/getsentry/sentry-php/issues/552 already investigated on this. The root cause seems to be the NewRelic extension messing with the error handlers order, which creates a loop between Symfony's and Sentry's (or any other one that correctly attempts to restore the previous error handler, I think).

**Comment by alcohol** [comment]
Yeah I'm on mac, and docker for mac does a lot of magic with permissions out of the box. I figured it would probably complain about some permission issues on Linux, but haven't had time to grab a Linux env myself yet to double check.

**Comment by alcohol** [comment]
Updated my repo to make it a bit easier on Linux out of the box (I think/hope).

**Comment by Jean85** [comment]
I can confirm that the Linux workaround works, thanks a lot!
Since my company is having big issues with this, I'll be opening a support ticket at NewRelic to ask for a solution.

**Comment by istepaniuk** [comment]
I can reproduce what @julia-morg describes, I removed newrelic entirely from my fork and I also get an infinite loop. This might not be related to newrelic entirely.

https://github.com/istepaniuk/symfony-error-handler-infinite-loop-bug

**Comment by Jean85** [comment]
@istepaniuk I'm not able to reproduce the issue correctly with your fork. The `/` route hangs like before, but no events are sent to Sentry... It hangs even if I replace the error with a correct `return new Response(200);`; in this case no logs are produced, except a HTTP 499 response in the nginx logs when I press ESC on the browser.

**Comment by Jean85** [comment]
Ok, I may have found the issue here; this is the scenario that I see:

### setup
 * Symfony installs its error handler
 * The Sentry bundle kicks in
 * Sentry installs its **breadcrumb** error handler ([source](https://github.com/getsentry/sentry-php/blob/512661046e403dc5eb5ae192d5a6cda10e068a95/lib/Raven/Breadcrumbs/ErrorHandler.php#L40-L44)) and it gets Symfony's error handler as the previous one to be called later
 * Sentry installs its **base** error & exception handler ([source](https://github.com/getsentry/sentry-php/blob/512661046e403dc5eb5ae192d5a6cda10e068a95/lib/Raven/Breadcrumbs/ErrorHandler.php#L40-L44)); it gets the **breadcrumb** error handler as the previous one, and Symfony's for the exception handler

### error handling
 * A fatal is generated
 * Sentry's error handler kicks in, and checks if there is a previous error handler to be called; it finds its **breadcrumb** error handler and invokes it ([source](https://github.com/getsentry/sentry-php/blob/512661046e403dc5eb5ae192d5a6cda10e068a95/lib/Raven/ErrorHandler.php#L107-L120))
 * Sentry's **breadcrumb** error handler does its job, and afterward calls the previous error handler, Symfony's ([source](https://github.com/getsentry/sentry-php/blob/512661046e403dc5eb5ae192d5a6cda10e068a95/lib/Raven/Breadcrumbs/ErrorHandler.php#L33-L37))
 * Symfony's error handler gets called and returns false [here](https://github.com/symfony/symfony/blob/874d4d659774d7bab90538072c83ed532dd17dc5/src/Symfony/Component/Debug/ErrorHandler.php#L393)

### fatal handling
At this point the error handler's job is done, but we have an unrecoverable error, and the shutdown functions kicks in:

 * shutdown functions are called in the same order as they where registered, so the first one that gets called is Symfony's, which inspects previous exceptions handlers
 * it does something that I currently don't understand fully [here](https://github.com/symfony/symfony/blob/874d4d659774d7bab90538072c83ed532dd17dc5/src/Symfony/Component/Debug/ErrorHandler.php#L616-L635)...
 * ...but I've seen that basically it calls `$handler->setExceptionHandler($h)`, where `$handler` is Symfony's error handlers and `$h` is Sentry's error handler [at this line](https://github.com/symfony/symfony/blob/874d4d659774d7bab90538072c83ed532dd17dc5/src/Symfony/Component/Debug/ErrorHandler.php#L640)
 * it goes on, [calling `$handler->handleException(...)`](https://github.com/symfony/symfony/blob/874d4d659774d7bab90538072c83ed532dd17dc5/src/Symfony/Component/Debug/ErrorHandler.php#L674)
 * it transforms the error into a `FatalThrowableError` [here](https://github.com/symfony/symfony/blob/874d4d659774d7bab90538072c83ed532dd17dc5/src/Symfony/Component/Debug/ErrorHandler.php#L544)
 * since he just set it, it calls Sentry's exception handler, starting the loop ([here](https://github.com/symfony/symfony/blob/874d4d659774d7bab90538072c83ed532dd17dc5/src/Symfony/Component/Debug/ErrorHandler.php#L583-L585))

### conclusions
IMHO the issue is caused by the confusion due to the changes with the `\Throwable` interface; Symfony's error handler calls the exception handlers, creating a loop between Symfony's fatal handler and the exception handlers. I still have to understand how this could be fixed....

**Comment by alcohol** [comment]
> it does something that I currently don't understand fully here...

To me it looks like it is trying to find itself in the stack of exception handlers that may or may not have been registered. It does this by restoring previous error handlers, and looking at what gets restored. Once it finds itself (or there simply arent any), it "restores" the stack of error handlers by reassigning them in order, and proceeds to the setExceptionHandler step. 

But I could be mistaken.. it is kind of non-descriptive in its implementation.

**Comment by Jean85** [comment]
I think you're probably right. This implementation has an issue then: Sentry's exception handler is registered **after** Symfony's, so in this way he's creating a loop, because it's setting himself out of the stack of handlers as the top/last one, but Sentry remembers Symfony's exception handler as the previous one.

**Comment by Jean85** [comment]
Upon further analysys, I've come out with 3 possible solutions:

1. Put a fix inside Sentry's client
Very ugly fix that would have to rely on some (hidden) global state, and it would probably work only if the previous handler saved inside Sentry's handler is Symfony's; if any other handler is in the middle, it would probably not work.
1. register Sentry's handler before Symfony's
This could prove pretty hard, since Symfony's handler is registered in the `FrameworkBundle::boot()` method; to come ahead of that we would have to do the same with the Sentry bundle AND add it before the FrameworkBundle
1. fix the [piece of code inside the ErrorHandler](https://github.com/symfony/symfony/blob/874d4d659774d7bab90538072c83ed532dd17dc5/src/Symfony/Component/Debug/ErrorHandler.php#L616-L635) in a way that avoids creating the loop.

Solutions 1 and 2 are ugly and would patch only Sentry, any other third party error handler would fail in the same way. Solution 3 would be better, but it requires a deeper understanding on why that piece of code alters the sequence of handlers. Can we have input from someone that can help us on that, or from the core team?

Status: reviewed

**Comment by alcohol** [comment]
@stof do you know who is more intimately familiar with the error/exception handler part of the debug component?

**Comment by nicolas-grekas** [comment]
Could you please report if #26568 fixes the issue for you?

**Comment by Jean85** [comment]
I cherry-picked your commit on my fork and used it over the 3.4.6 tag. Apart some issues with Composer to use the fork, I can confirm that this fixes the issue! Thanks @nicolas-grekas
