### ISSUE TITLE
Form validation errors rendered inside label tag in bootstrap4 layout

### ISSUE THREAD

**Issue by mmarton** [symfony/symfony#26461]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4

Hi!

I'm not sure if it is a bug or intentional, but in bootstrap4 form layout the validation errors are rendered inside the label tag see:
https://github.com/symfony/twig-bridge/blob/master/Resources/views/Form/bootstrap_4_layout.html.twig#L206

It's not exactly how bootstrap recommends it.
https://getbootstrap.com/docs/4.0/components/forms/#validation

Regards,
Marton

**Comment by jasonkrot** [comment]
I also have the same problem. In my case i feel extremely hard to move the error block out of the label, after the form_widget.
The other problem is more like logical, since the error is not a label, so it shouldn't be part of the form_label.

**Comment by jean-gui** [comment]
I think this was introduced by https://github.com/symfony/symfony/commit/a0b40f5c4a5d46a2df789d223b46b91e08b339f8. The commit message says it is a requirement for WCAG2.
An issue is that if you use the horizontal layout, the label may be very narrow thus making error messages display on many lines.
Another more serious issue, is that error messages are rendered in a <ul> but AFAIK having a <ul> in a <label> is not valid HTML5

**Comment by javiereguiluz** [comment]
@Nyholm can you think of a possible solution to the issue of the new error message spanning into multiple lines because the `<label>` element is narrow in lots of form designs? Thanks!

**Comment by Nyholm** [comment]
Yeah, have a look here: #26408

**Comment by ostrolucky** [comment]
Yes, this is intended. Compliance with WCAG2 was chosen over bootstrap guidelines, since those guidelines are not WCAG2 compliant. You can read more here https://github.com/symfony/symfony/pull/25715#issuecomment-363679953. Unless someone wants to suggest solution which will conform to both WCAG2 and bootstrap guidelines, I would close this.

**Comment by jean-gui** [comment]
@ostrolucky It's not just about bootstrap guidelines but HTML5 compliance: labels only accept phrasing content which div and ul aren't. And compliance with WCAG2 doesn't require that errors be put in labels. https://www.w3.org/WAI/tutorials/forms/notifications/#after-submit shows that you can put error messages outside of them, and https://www.w3.org/WAI/tutorials/forms/instructions/#providing-instructions-outside-labels explains a little more how.

**Comment by Nyholm** [comment]
I'll have a look at HTML5 compliance this weekend.

**Comment by ostrolucky** [comment]
Any news? More issues for this incoming

**Comment by Nyholm** [comment]
Just starting now. Expect a PR later today

**Comment by Nyholm** [comment]
I've submitted a PR now. 

Thank you @jean-gui for your links. I am not a WCAG expert, so I cannot make any arguments what is better or worse. However, I do not that screen readers and WCAG compliance are two different things. Ie, just because your HTML follows WCAG and HTML standards, it does not mean that it works well in screen readers.
