### ISSUE TITLE
Error on ThrowableError message

### ISSUE THREAD

**Issue by epixilog** [symfony/symfony#26527]
Hello, 

I noticed that there is a little problem (that can lead to some missunderstanding) on ThrowableError message. 

When you use an argument with a "wrong" class Symfony will tell you:

> error: Argument 1 passed to App\EventListener\...() must be an instance of A, instance of B given

On the message, I think Classes A and B should be inverted

Thanks

**Comment by derrabus** [comment]
I would expect this message to be emitted by the php interpreter. Symfony just displays it.

**Comment by xabbuh** [comment]
Can you provide a reproducable example that leads to a wrong error?

**Comment by epixilog** [comment]
Let's take the example of a controller event listener for example:
`
public static function getSubscribedEvents(){
        return [ KernelEvents::CONTROLLER => 'onKernelController'];
}
`
If I add a wrong argument on my function. Let's say I put:
`public function onKernelController(FilterUserResponseEvent $event) {`

Inspite of:
`public function onKernelController(FilterControllerEvent $event) {`

In that case the error code is:

> Type error: Argument 1 passed to App\EventListener\AccessControllerSubscriber::onKernelController() must be an instance of FOS\UserBundle\Event\FilterUserResponseEvent, instance of Symfony\Component\HttpKernel\Event\FilterControllerEvent given

Regards,
Epixilog

**Comment by xabbuh** [comment]
This looks expected to me because your method argument is type hint with `FilterUserResponseEvent`, but the kernel passes a `FilterControllerEvent` instance. That's just how PHP works.

**Comment by derrabus** [comment]
Okay, so this is what happens.

You specify a function that should be called on a specific event, so the event dispatcher does exactly that. The error you read here is correct because the **php runtime** complains that the type-hint does not match the given event object.

Of course, the actual error that was made here is that you've set the wrong type hint. So, if you would want a different error message here, the event dispatcher would need to check via reflection if the signature of the method is compatible before actually calling it. The dispatcher could do that, but it would mean taking a performance penalty in a core component that's supposed to be as fast as possible.

**Comment by epixilog** [comment]
What I just tried to explain is that the right error message should be:

> Type error: Argument 1 passed to App\EventListener\AccessControllerSubscriber::onKernelController() must be an instance of Symfony\Component\HttpKernel\Event\FilterControllerEvent, instance of FOS\UserBundle\Event\FilterUserResponseEvent given

Classes are inverted in the error message.
That's all :)

**Comment by derrabus** [comment]
> Classes are inverted in the error message.

They are not. The method is called with an instance of `FilterControllerEvent` as the php error message says!
