### ISSUE TITLE
[Form] With a CheckboxType, form_label is empty and form_widget renders form_row

### ISSUE THREAD

**Issue by LucileDT** [symfony/symfony#26540]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | maybe
| RFC?             | no
| Symfony version  | 3.4.6

When rendering a CheckboxType form input in a view, instead of separating label, errors and widget, Symfony renders the whole row of the input.

### TestType.php
```php
/**
 * {@inheritdoc}
 */
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
        ->add('email', EmailType::class, [
            'label' => 'Email',
            'required' => true,
        ])
        ->add('emailIsPublic', CheckboxType::class, [
            'label' => 'Make e-mail public (can be seen by everyone)',
            'required' => false,
            'attr' => [
                'class' => 'switch',
            ]
        ])
        ->add('submit', SubmitType::class, [
            'label' => 'Save changes',
            'attr' => [
                'class' => 'btn btn-outline-primary float-right',
            ]
        ]);
}
```

### test-view.html.twig

```twig
{{ form_start(edit_form) }}
    <div>
        {{ form_label(edit_form.emailIsPublic) }}
    </div>
    <div>
        {{ form_errors(edit_form.emailIsPublic) }}
    </div>
    <div>
        {{ form_widget(edit_form.emailIsPublic) }}
    </div>
{{ form_end(edit_form, {'render_rest': false}) }}
```

### Generated HTML

```html
<form name="appbundle_my" method="post">
    <div></div>
    <div></div>
    <div>
        <div class="form-check">
            <label class="form-check-label">
                <input id="appbundle_my_emailIsPublic" name="appbundle_my[emailIsPublic]" class="switch form-check-input" value="1" type="checkbox"> Make e-mail public (can be seen by everyone)
            </label>
        </div>
    </div>
</form>
```

As we can see in the generated HTML, `form_label` is empty and `form_widget` renders what `form_row` should render.

I can't find if it's an expected behaviour.

**Comment by xabbuh** [comment]
Which form theme do you use?

**Comment by LucileDT** [comment]
Hi!

My `config.yml`, the section about twig:

```yaml
# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - "bootstrap_4_layout.html.twig"
```

**Comment by LucileDT** [comment]
In addition, I tried to create a custom template for this field using the example at: https://symfony.com/doc/3.4/form/create_custom_field_type.html without success, I have the exact same problem with a hand made `SwitchType` when its parent is a `CheckboxType`:

```php
public function getParent()
{
    return CheckboxType::class;
}
```

**Comment by xabbuh** [comment]
That's specific to the Bootstrap 4 theme and it seems to be related to the changes made in #26591.

/cc @Nyholm

**Comment by DarckCrystale** [comment]
This problem still exists. How can I solve this? (except to not use Bootstrap 4 theme)

**Comment by Nyholm** [comment]
Hm. `form_widget` looks alright. `form_errors` should also be empty as it does not contain any errors by default. But `form_label` should render something...

**Comment by DarckCrystale** [comment]
For me, `form_widget` should render only the `<input type="checkbox" id="my-input" value="value"/>` and the `form_label` should render the `label for="my-input">Label</label>`.

But currently, `form_widget` renders the two of them.

**Comment by ptrm04** [comment]
There is a special mention of the label for checkbox types at https://symfony.com/doc/current/form/form_customization.html#what-are-form-themes

_When you use the Bootstrap form themes and render the fields manually, calling `form_label()` for a checkbox/radio field doesn't show anything. Due to Bootstrap internals, the label is already shown by `form_widget()`._

So in terms of `form_label()` this could be as expected, however there shouldn't even be an empty `div` as per the output above. `form_errors()` might follow this behaviour

**Comment by ptrm04** [comment]
@LucileDT, your output shows the input element within the label element, this was true in bootstrap 3, this is no longer the behaviour of bootstrap 4: https://getbootstrap.com/docs/4.1/components/forms/#default-stacked

Input and label sit at the same level.

Are you sure you were using bootstrap 4 to generate the output in your first post above?

**Comment by LucileDT** [comment]
I am using the Bootstrap 4 twig theme when I encounter this problem, yes.

So you mean by https://github.com/symfony/symfony/issues/26540#issuecomment-429277433 that if we want custom checkboxes, it's not possible to edit them in the twig templates?

**Comment by ptrm04** [comment]
- @LucileDT Thanks for confirming you are using Bootstrap 4 - that's interesting as your output in https://github.com/symfony/symfony/issues/26540#issue-305550079 appears to be the rendering from Bootstrap 3, the input is **within** the label in your example, in Bootstrap 4, both the label and input are siblings: https://getbootstrap.com/docs/4.1/migration/#forms
- Due to the above migration change, it looks like the caution "Due to Bootstrap internals, the label is already shown by `form_widget()`." at https://symfony.com/doc/current/form/form_customization.html#what-are-form-themes as well as the twig internals need updating as this no longer needs a special treatment, they follow suit any other input type rendering
- Finally, to answer your question at https://github.com/symfony/symfony/issues/26540#issuecomment-429489852 @LucileDT, unfortunately, it does not seem possible to edit checkboxes in templates, not even by overriding related blocks such as `*_label`, I've submitted a bug for this: Modifying bootstrap 4 label for checkbox removes the actual input element #28823

/cc @Nyholm @xabbuh

**Comment by xabbuh** [comment]
If you don't overwrite blocks that are responsible for rendering the checkbox/radio labels, you will still see that `form_label()` does not produce any output with the Bootstrap 4 theme.

I am going to close here as this is indeed the expected behaviour. Thank you for understanding.

**Comment by LucileDT** [comment]
Thank you very much!

**Comment by parap** [comment]
If it is right place to put solution for compound forms that do not show checkbox label in headers - inclusion to forms to solve it https://gist.github.com/parap/0d16012a45c233e7fdf2c2a4e90850e2

**Comment by Seb33300** [comment]
A workaround:

```twig
{{ form_row(form.checkbox) | striptags('<input>') | raw }}
```
