### ISSUE TITLE
Use new way to get a fully qualified name

### ISSUE THREAD

**Issue by zzenmate** [symfony/symfony#26571]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

In PHP 5.5 we got a new way to get a fully qualified name.
http://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name
Why not rename __NAMESPACE__.'\SomeClass' to SomeClass::class in the whole project?
What do you think about it?

**Comment by zzenmate** [comment]
I started from [Validator component](https://github.com/symfony/symfony/pull/26572).

**Comment by Taluu** [comment]
I think it's like scalar typehints. Even though 4.0+ uses php 7.1, there are still maintained versions that uses 5.3 (2.7, 2.8). So, `::class` (and scalar typehints, short array notation, ... and so on) are not used because it would be a mess when porting fixes from 2.7+ to 4.0+.

New features already uses scalar typehints and `::class` though.

**Comment by curry684** [comment]
Indeed, we cannot do changes like these until 2.8 is out of active support, which will be November 2019. 

https://symfony.com/roadmap?version=2.8#checker

**Comment by javiereguiluz** [comment]
@zzenmate even if you are 100% right about this ... I'm afraid we can't make this change because of how Symfony maintenance works. It's explained a bit here: https://github.com/symfony/symfony/pull/26530#issuecomment-373058166 and you can see rejected pull requests like this in #26530, #25416, etc. That's why we're sorry but we must close this proposal.
