### ISSUE TITLE
Cannot inject Templating on Symfony 4 Service

### ISSUE THREAD

**Issue by jcfrane** [symfony/symfony#26585]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0

Hi this is my first time creating an issue,

Really don't know if this is a bug or what, cause i've been searching the net for solutions and to no luck.

I posted on stackoverflow for answers:

[Cannot inject Templating on Symfony 4 Service](https://stackoverflow.com/questions/49344753/cannot-inject-templating-on-symfony-4-service)

Thanks!

**Comment by ismail1432** [comment]
Hi 👋,
This is not an issue and you just ask the question on Stack since 44 min only...
Please wait for answers and if there is a real issue open it.
But IMHO you should close this one.
Have a nice Sunday

**Comment by fabienlem** [comment]
Hello,

I ran into the same issue.

In order to inject twig, it's necessary to require symfony/templating and to add the following lines to the framework.yaml file:

```
framework:
    ...
    templating:
        engines: ['twig']
```

And then you can use:

```
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
...
public function __construct(EngineInterface $templating)
```

I think there is a problem as TwigEngine implements the EngineInterface of "symfony/templating", but requiring twig does not install "symfony/templating".

Moreover, the configuration step I described previously seems not documented. I found it in a Symfony 3.x project.

What do you think?

Regards,

Fabien

**Comment by jcfrane** [comment]
i was not able to use EngineInterface myself, i ended up using Twig_Environment.

**Comment by stof** [comment]
@fabienlem the `twig` service is *not* the TwigEngine class. It is perfectly fine to use Twig directly without using the wrapper implementing the `symfony/templating` abstraction (and this is what is done by default in a Symfony 4 project)

**Comment by fabienlem** [comment]
@stof Ok thank you for your feedback!
