### ISSUE TITLE
[Simple-phpunit] Composer.phar require to be in the path

### ISSUE THREAD

**Issue by FroggDev** [symfony/symfony#26637]
[Simple-phpunit] Composer.phar require to be in the path

| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.0

(On windows) if composer.phar is not in the path as composer.bat the "php bin/phpunit" command will make an error.
in /vendor/symfony/phpunit-bridge/bin/simple-phpunit line 46 where.exe composer.phar

For example:
c:\dev\path\composer.bat content:
@php "C:\dev\composer\composer.phar" %*

composer.bat is in the path & composer.phar is in composer folder which is not in the path.

In this case the php bin/phpunit will trigger an error.

Maybe it is possible to set an error message to the user to explain this. Or maybe work with composer.bat instead of composer.phar.

**Comment by nicolas-grekas** [comment]
I'm not 100% sure to understand the issue, but if you want to submit a PR, please do :)

**Comment by FroggDev** [comment]
i am currently busy with an end of training project on symfony, but once i'am done (around 3weeks from now) i will try a PR !

**Comment by xabbuh** [comment]
@FroggyDev Did you create the `composer.bat` file yourself or is it created by the Composer installer?

**Comment by FroggDev** [comment]
To figure this out i create a composer.bat with a link to composer.phar in it, as it is in path "composer" command work but composer.phar isnt in the same folder (like that i can separate tool from path which is a better practice for security).

Anyway I am thinking just about a minor  PR warning users that did like me to put composer.phar in same path as composer.bat.

Even if i think it would be better to rely on "composer" command rather than composer.phar.

**Comment by graste** [comment]
Same happens with linux etc. Running `bin/phpunit` or `vendor/bin/simple-phgunit` without `composer` in PATH results in:
```
sh: 1: composer: not found
sh: 1: composer: not found
sh: 1: composer: not found
sh: 1: composer: not found
```
The `simple-phpunit` script falls back to "composer" when "composer.phar" is not in the correct folder and then fails when "composer" is not in the PATH somewhere. Maybe a warning message, that the script falls back to "composer" or expects "composer.phar" in a certain directory might help. Additionally a hint, that one should set PATH or make "composer" available otherwise might help. As composer doesn't have a COMPOSER_PHAR or similar ENV variable IMHO, maybe symfony could introduce and check a APP_COMPOSER_BINARY environment variable?

**Comment by Simperfit** [comment]
@nicolas-grekas what do you think of such a warning ? @FroggDev do you still want to create the PR ?

**Comment by FroggDev** [comment]
@Simperfit Hi sorry for the late answer, you can take it, i am really busy nowadays
