### ISSUE TITLE
[Finder] Ignore paths from .gitignore

### ISSUE THREAD

**Issue by hkdobrev** [symfony/symfony#26714]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 4.1

`Finder::ignoreVCS()` is great at ignoring file patterns for the files created by popular VCS systems.

However, it would be great to be able to instruct `Finder` to actually exclude the paths excluded by `.gitignore`.

So if we have `.gitignore`:
```ini
vendor/
cache/
```

```php
Finder::create()
	->files()
    ->ignoreVCS(true) // <--- Ignores `.git`
	->ignoreVCSIgnored(true); // <--- Ignores vendor/ and cache/
```

I think this would simplify a lot of Finder configurations which currently manually exclude the git-ignored paths or manually include everything else.

**Comment by fabpot** [comment]
That's a great idea.

**Comment by Simperfit** [comment]
Do you want to do it @hkdobrev ?

**Comment by hkdobrev** [comment]
👋 @naderman @Seldaek 
 Following up from https://github.com/composer/composer/pull/1567 and the latest implementation in https://github.com/composer/composer/blob/c2fbbe3b86788eb507a0f4f45f9fdc623ca579c4/src/Composer/Package/Archiver/ArchivableFilesFinder.php I think it would be great to extract all Finder-related code out of Composer in a package or in the Finder component itself for this feature without reinventing the wheel.

I like how this turned out https://github.com/composer/xdebug-handler recently with everything starting from https://github.com/composer/composer/issues/6802 and https://github.com/phpstan/phpstan/pull/605.

I'm keen to help on extracting that code out of Composer. A small bit of refactoring would be needed to be usable with an existing finder or to incorporate it into `Finder` itself.

Please let me know if this is something you'd accept help with! Thanks!

Approaches:

1️⃣ Extract Composer filters and finder-related code to a `composer/vcs-finder` repo. Require the repo in `symfony/finder` for that feature. This would introduce the first dependency to `symfony/finder` though.
2️⃣ Incorporate the Composer filters in `symfony/finder` itself and Composer can use them as a simple configuration to their archive finder as `composer/composer` already depends on `symfony/finder`. However, this feature would be probably in `4.1` or `4.2` while Composer still supports older versions of `symfony/finder`.
3️⃣ Same as 2️⃣, but don't actually change Composer code until it moves to `symfony/finder:^4.1` or above as a dependency.

**Comment by Seldaek** [comment]
@hkdobrev The main problem is we can't upgrade to latest Symfony releases, so this is not really that interesting to me, but if you like to duplicate the code in symfony I'd say why not, one day we can use it and drop it from composer.. I'd say option 3 is the best.

**Comment by hkdobrev** [comment]
@Seldaek Thanks for the input! I'll try it out.

**Comment by naderman** [comment]
There are also some problems with the current implementation https://github.com/composer/composer/issues/5681

And there's an argument to be made that composer should only really care about gitattributes export options and not the ignore file at all, since that's for adding files and not exporting them.

**Comment by hkdobrev** [comment]
I have good understanding of the structure in Composer, the latest Finder code and their differences. I've started implementing it with separate filters where people could choose which files to use. When I have something presentable I'll open a PR to request comments on the external API.

@naderman Thank you for your input, I'll take these into consideration!

**Comment by ntzm** [comment]
Any updates on this @hkdobrev?

**Comment by inmarelibero** [comment]
Hi all, I'm currently working on https://packagist.org/packages/inmarelibero/gitignore-checker

can I try to propose an implementation of this issue?

**Comment by amaabdou** [comment]
Hi @inmarelibero 
I worked on implementation for this feature couple of days ago when I saw @nicolas-grekas tweet about help needed issues 
but did not submit it because I can not find a place that have git-ignore to regex in any language checker to port to php, so I was trying to write as many tests as possible 
when I saw your comment I got excited and pushed the code created MR maybe you have more info about this

**Comment by inmarelibero** [comment]
@amaabdou ah great

I decided to implement a stand alone library (also due to the comment of @SpacePossum https://github.com/symfony/symfony/issues/26714#issuecomment-408604768) in order to be reusable everywhere and not too tied with Symfony

hint: unfortunately rules cannot be synthetized only with regex, as `.gitignore` does not follow straight regexes

we could split the work btw: you could work on the PR and I could work on the library? what do you think of it? and if possible of course helping each other ;)

I would hear what some mantainer would say about this, as developing things without anyone knowing is a bad practice

**Comment by inmarelibero** [comment]
maybe @Simperfit ?

**Comment by amaabdou** [comment]
Sorry @inmarelibero for not replying quickly to you, I was spending my holiday :D 

Honestly I was looking forward to using regex, it is a little complicated and annoying I know and I was pulling my hair while doing it but seems more convenient for this case but I could be wrong

Anyway I submitted the PR with as many cases I could for now, lets see how the review will go, if it went okay then cool,  if not we can use the library you created
