### ISSUE TITLE
Issue while downloading http-foundation by composer

### ISSUE THREAD

**Issue by chittta** [symfony/symfony#26837]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.0

![image](https://user-images.githubusercontent.com/11360545/38425135-a59e54e6-39d0-11e8-8deb-e7f65e100c76.png)

I need help. What is the point of having that .empty file under Tests/File/Fixtures/directory ? And also it is an empty file. In windows while creating the .empty file permission issue occurs. I guess that filename is a reserved one.

Thank you

**Comment by javiereguiluz** [comment]
The `http-foundation` package has more than 80,000 daily downloads and we haven't received other reports like this, so this is probably a temporary error, which could be caused by Packagist.org or GitHub.com or your network, etc.

Have you solved it? Are you using the latest Composer version (run `composer self-update` to be sure)?

**Comment by nicolas-grekas** [comment]
Does anyone else experience the issue? It's the first time I see this behavior, looks strange. (I *can* create a `.empty` folder on my side.)

**Comment by chittta** [comment]
Hi Nicolas,

I found that the issue was with my network admin setup in my office computer. They had it configured not to allow a .empty file to be created in my machine. Later I used my personal computer to download this and everything is working properly.

Thank you for your cooperation.
