### ISSUE TITLE
Unable to have choices with same value

### ISSUE THREAD

**Issue by fmagnan** [symfony/symfony#26836]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.8

Hello,

I'm trying to display radio buttons with different labels but same values. In my FormType, I'm using this code:

```
$builder->add('answers', ChoiceType::class, [
            'choices' => ['yes' => 'y', 'ok' => 'y', 'no' => 'n', 'ko' => 'n'],
            'expanded' => true,
            'multiple' => false,
        ]);
```
The result is radio buttons but values are 0, 1, 2, 3 instead of y, y, n, n.
Is it possible to have radio buttons with identical values?

**Comment by xabbuh** [comment]
That's intended. How would the `ChoiceType` otherwise be able to select the user's choice if the submitted value is ambiguous? You can of course render HTML on your own that contains an additional radio button, but that's not the component's responsibility. I am going to close here as there is no bug.
