### ISSUE TITLE
GuardAuthenticationProvider::authenticate does not follow interface specification

### ISSUE THREAD

**Issue by biomedia-thomas** [symfony/symfony#26942]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             |  no
| Symfony version  | 4.0.8

If the authenticate method in GuardAuthenticationProvider does not find a GuardAuthenticator for the token passed to the function it falls through to the end of the function:
```php
    public function authenticate(TokenInterface $token)
    {
        ....

        // no matching authenticator found - but there will be multiple GuardAuthenticationProvider
        // instances that will be checked if you have multiple firewalls.
    }
```
There is no return statement so implicitly null is returned. However, the AuthenticationManagerInterface that is implemented by this class states the return value should be "An authenticated TokenInterface instance, **never null**"
```php
  /**
     * Attempts to authenticate a TokenInterface object.
     *
     * @param TokenInterface $token The TokenInterface instance to authenticate
     *
     * @return TokenInterface An authenticated TokenInterface instance, never null
     *
     * @throws AuthenticationException if the authentication fails
     */
    public function authenticate(TokenInterface $token);
```

I ran into this when using the scheb/two-factor-bundle that uses this interface and assumes null is never returned.

**Comment by wouterj** [comment]
Hi @biomedia-thomas! Thanks for filling in this detailed issue!

We're in a bit complex situation here. The guard authentication provider can not do much else than returning `null`. To see that, let's take a look at the authentication manager:

https://github.com/symfony/symfony/blob/2ed0c67375d7636c5a4cbda04f7d17098577675e/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php#L75-L87

The first thing I noticed: It already takes care of handling returning `null`.

And then, if the guard authenticator throws an exception instead of returning null, it would mean that it would be shown as "last exception". This makes sense for all other auth providers: They first explicitly notice they can support this token, so anything that prevents them from returning a user is obviously an error. However, in the case of the guard provider, it only knows it supports a guard token. Whether it can return a user depends on whether the guard authenticator can handle the guard token.

So I think there are two solutions here;

1. Fix the interface specs to allow returning `null`, Symfony core already supports this.
1. Change `GuardAuthenticationProvider#supports()` to, besides checking if the token is a guard token, also iterate over the guard authenticators and check if the guard provider key matches:

  
 https://github.com/symfony/symfony/blob/2ed0c67375d7636c5a4cbda04f7d17098577675e/src/Symfony/Component/Security/Guard/Provider/GuardAuthenticationProvider.php#L91-L95

**Comment by biomedia-thomas** [comment]
Hi @wouterj, thanks for replying, I understand the problem. Allowing null would be a breaking change but it's inconsistent now anyway. What would be the downside of checking it in support? I guess performance? Or are there other issues with this solution?

**Comment by wouterj** [comment]
Yeah, I also think performance. But the check is very heavy and it only is a problem when you have many guard authenticators. I think the common applications have between 1 and 3 authenticators.

So I think moving the check to `support()` might be the best solution here. Are you willing to open a pull request with this change? That makes it easier for the core team to analyse on the impact (both in functionality and performance).

**Comment by iltar** [comment]
I also just ran into this issue, see scheb/two-factor-bundle#127 for a fix on their side for now, in case it gets merged.
