### ISSUE TITLE
cannot extend LDAP component

### ISSUE THREAD

**Issue by therik** [symfony/symfony#27039]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | >=3.4

Hello,
I'm trying to run ldap_modify_batch() to let users change their passwords in Active Directory, but the LDAP component won't let me get the $resource for it, all the fields and getters are private. I can't see any easy way to extend this or even just get the resource so I can call the function directly.

Is there a way to extend it that I'm missing, or a way to get the resource out?

**Comment by mablae** [comment]
@xabbuh How to implement this? 

Having a `ManipulationInterface` with concrete implementations for Remove/Update/Add and `ManipulationCollectionInterface` and a new method "executeBatch" on `EntryManagerInterface` ?

**Comment by heiglandreas** [comment]
Without having deep knowledge in Symfony I'D test this:

Instead of invoking `LDAP::create()` I'd create the LDAP-Instance by calling `new LDAP($adapter)` where `$adapter = new Symfony\Component\Ldap\Adapter\ExtLdap\Adapter($config)`. This adapter contains the method `Adapter::getConnection()` which should return a connection-object that itself has a `getResource`-method.

So the complete code might look something like this:

```php
$adapter = new  Symfony\Component\Ldap\Adapter\ExtLdap\Adapter($config)
$ldap = new Ldap($adapter);
$ldap->bind();
$resource = $adapter->getConnection()->getResource();
```

Then you can use `$resource` for the ext-ldap calls.

I'm not sure whether the middle two lines are needed at all…

But as I said, I have no deep symfony experience, so perhaps someone else might want to chime in here to tell you the "proper" way to do it 😉
