### ISSUE TITLE
[Form] New form BooleanType class

### ISSUE THREAD

**Issue by emulienfou** [symfony/symfony#27185]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | Next for branches 3.x and 4.x

I think it would be great/easier to have a form **BooleanType**, instead of using the *ChoiceType* with yes/no values!

What do you think?
> I found this useful Gist: https://gist.github.com/fsevestre/abfefe0b66e5f5b24c60

**Comment by fsevestre** [comment]
Hi, thanks for finding the Gist useful :)
For your information, I published a library: https://github.com/fsevestre/BooleanFormType

About the request, I don't think it should be added into core because the current implementation is limited to API only and is not intended to be displayed on a browser.

For me, FOSRestBundle (issue : https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1224 / PR : https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1312) is the best place to have this form type (my library is a temporary solution until the PR on FOSRestBundle is finished)

But, to quote webmozart (https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1312#issuecomment-187174645):
> The problem about null/false is that the Form component was never designed to be used in API requests. That's what usually a serializer is for. The Form component is designed against the CGI protocol, where each value is a string or not set.
> I understand however that the Form component offers functionality that serializers are missing. The problem is that we can't change the Form component to pass false as false (instead of null) without breaking BC

**Comment by ostrolucky** [comment]
I think what OP suggests is to have just new form type which is just preconfigured choicetype with yes/no choices. Such form type is really common in projects. We use following and it works fine, even in non-API context.

```php
class YesNoRadioType extends AbstractType
{
    const CHOICES = ['YES' => true, 'NO' => false];

    public function getParent()
    {
        return ChoiceType::class;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'expanded' => true,
            'choices' => self::CHOICES,
        ]);
    }
}
```

**Comment by Aerendir** [comment]
Yes, I agree with @ostrolucky and find useful the @emolienfou’s proposal.

**Comment by xabbuh** [comment]
Does anyone of you want to work on a PR implementing this type?

**Comment by alamirault** [comment]
Would it be better if BooleanType parent is ChoiceType ?

**Comment by xabbuh** [comment]
In the solution proposed in https://github.com/symfony/symfony/issues/27185#issuecomment-387350490 the parent type is `ChoiceType`.

**Comment by ostrolucky** [comment]
Btw my opinion on the matter is this issue cannot be satisfied in generic, non-opinionated way. Some people will want it to be checkbox instead of radios, some dropdown, other people something else than yes/no labels. Having own type for this is few lines of codes and guarantees it's the way user wants. Trying to customize such booleanType that would be shipped officially doesn't save much. So in the end letting user create whatever choicetype child as is the case now might be better.

**Comment by xabbuh** [comment]
@ostrolucky I don't think that really is an issue. This can be customised through the options inherited from the `ChoiceType`.

**Comment by ostrolucky** [comment]
So can ChoiceType. User isn't saving much.

**Comment by yceruto** [comment]
I've the same opinion as @ostrolucky about this proposal, this custom type is very simple to be created by anyone.

Also extending it from `ChoiceType` will require validating the `multiple` option and maybe others that don't apply.

**Comment by fabpot** [comment]
Let's close then.
