### ISSUE TITLE
[PropertyAccessor] What is the return value of getValue method if index does not exists ?

### ISSUE THREAD

**Issue by nicolaspetitjean** [symfony/symfony#27187]
So my first topic was closed so fast, don't know why ?

| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.8

According to [symfony doc](https://symfony.com/doc/current/components/property_access.html) : 
> As you can see, the method will return null if the index does not exists.

According to [api doc](https://api.symfony.com/master/Symfony/Component/PropertyAccess/PropertyAccessor.html):
> AccessException | If a property/index does not exist or is not public

WHere is the truth ?

**Comment by iltar** [comment]
I think your first issue was closed by accident, because usually if @fabpot closes something, he adds a comment as of why it was closed.

The signature according to the code:
```php
    /**
     * @return mixed The value at the end of the property path
     *
     * @throws Exception\InvalidArgumentException If the property path is invalid
     * @throws Exception\AccessException          If a property/index does not exist or is not public
     * @throws Exception\UnexpectedTypeException  If a value within the path is neither object
     *                                            nor array
     */
    public function getValue($objectOrArray, $propertyPath);
```

In the end, it's how you configure it. The exception _can_ be thrown, doesn't mean it _will_ be thrown unless it's configured to do so. Both are right in this case. See: `PropertyAccessorBuilder::enableExceptionOnInvalidIndex()` and `PropertyAccessorBuilder::disableExceptionOnInvalidIndex()`. By default, this is false. The docs you've linked, are for the component, which didn't pre-configure it.

If the docs are unclear, you can open an issue in https://github.com/symfony/symfony-docs. The docs could receive a mention that this behavior is configurable.

**Comment by nicolaspetitjean** [comment]
Thanks you

**Comment by javiereguiluz** [comment]
Let's close this in favor of the new issue reported at Symfony Docs. Thanks @nicolaspetitjean!
