### ISSUE TITLE
the route , doctrine param converter error

### ISSUE THREAD

**Issue by imsheng** [symfony/symfony#27460]
**Symfony version(s) affected**: 3.4.11

**Description**  

When the incoming goodsSpec is null, the parse is not null
`
    url : /xxxxxx/11/goods/1615/qr
    @Route("/xxxxxx/{deliveryLog}/goods/{goods}/qr/{goodsSpec}",name="xxxxxxx",defaults={"goodsSpec"=null})

    public function qrAction(Request $request, QrDeliveryLog $deliveryLog, Goods $goods, GoodsSpec $goodsSpec = null)
`

**How to reproduce**  

**Possible Solution**  

**Additional context**  
![1527824295 1](https://user-images.githubusercontent.com/10435075/40820069-f1d3f1a4-6590-11e8-8eca-f3d478e0feb0.jpg)

**Comment by nicolas-grekas** [comment]
I suppose you need to exclude the GooSpec class from being loaded as a service class in your services.yaml config file?

**Comment by imsheng** [comment]
@nicolas-grekas no ，GooSpec is entity
I already know the solution
* @ParamConverter("goodsSpec", class="KuaidingGoodsBundle:GoodsSpec",options={"id" = "goodsSpec"})

But I still don't understand why this happens.

**Comment by jvasseur** [comment]
It's because of this code: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/Request/ParamConverter/DoctrineParamConverter.php#L156-L159. Basically if not configured and no corresponding id is in the request the `ParamConverter` will try to find an object with properties that match the request params.

**Comment by xabbuh** [comment]
As pointed out that is indeed the expected behaviour. So I am going to close here.
