### ISSUE TITLE
Form redirecting

### ISSUE THREAD

**Issue by RisteDimitrievski** [symfony/symfony#27466]
**Symfony version(s) affected**: 4.1* and 4.0*

**Description**  

If you move public directory to the root of the project, you will experience errors in form actions. You will be redirected to the invalid path of the site. Ex. If my project is in /forum/ and i've updated my composer.json public-path to the root document of the project after submiting the login or another form it will be redirect to outside of /forum/ directory.

**How to reproduce**  

**Possible Solution**  

Removing the automatically parsing the slash in the form actions should fix this issue.

**Additional context**  

Screenshoots:
http://prntscr.com/jpi5b5 - Main project index.
-- > after i submit the form:  http://prntscr.com/jpi5oy
--> My template for action method --- > http://prntscr.com/jpi6k5
--> Controller for handling the form ---> http://prntscr.com/jpi7ec

**Comment by xabbuh** [comment]
From the screenshot I can see that you are manually setting the URL to which the form should be submitted. If you change the base path of your project, you will need to update your code there too so that it generates the right URL. That not something that we can fix in the Symfony code, but that you will need to fix in your application.

**Comment by RisteDimitrievski** [comment]
I updated the composer too with the base path of the public dir.

Or i need to edit something else too ?
