### ISSUE TITLE
[Guard] [3.4] Implementing the AuthenticatorInterface still throws a deprecation message

### ISSUE THREAD

**Issue by MetalArend** [symfony/symfony#27474]
**Symfony version(s) affected**: 3.4

**Description**  
*Implementing the AuthenticatorInterface instead of extending AbstractGuardAuthenticator still throws deprecated message*

I wrote a class `FormAuthenticator` that extended the Guard `AbstractGuardAuthenticator`. After upgrading from 3.3 to 3.4 (as an LTS version), I ran Psalm, which told me that this class was deprecated. It tells me to not extend from Guard `AbstractGuardAuthenticator`, but instead to implement Guard `AuthenticatorInterface`. However, the `AuthenticatorInterface` extends from the `GuardAuthenticatorInterface`, which is also deprecated.

**How to reproduce**  
Try to implement a Guard implementing the recommended Interface for Symfony 3.4, by using https://github.com/symfony/symfony/blob/143bdfc0731fa0db9f9014503c05b960daf7a1c4/src/Symfony/Component/Security/Guard/AuthenticatorInterface.php#L26

**Possible Solution**  
Duplicate the code from the Interface, instead of extending the replacement from the deprecated interface.

**Comment by chalasr** [comment]
Before 3.4 some parts of the  guard component's public api typehint against the deprecated `GuardAuthenticatorInterface` (see e.g. https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Guard/GuardAuthenticatorHandler.php#L97) and we can't remove/change them because of our BC promise, so the change you're suggesting cannot be done.
Also our deprecation mechanism is smart enough to not trigger irrelevant deprecation notices in such cases (when you don't implement the deprecated interface directly, but a child one) so that once your code has been updated according to the recommended upgrade path, you should not get deprecation notices when running it.
Unfortunately your static analysis tool doesn't know about symfony's BC layers, and there's nothing we can do for that.
