### ISSUE TITLE
[Console][4.1][BC Break] Writing 'null' using SymfonyStyle

### ISSUE THREAD

**Issue by WFrancois** [symfony/symfony#27536]
**Symfony version(s) affected**: 4.1.0

**Description**  
Hi, when using SymfonyStyle, we can't pass `null` as a value anymore, as it will return a Fatal Error.

**How to reproduce**  
```php
$input = new \Symfony\Component\Console\Input\ArgvInput();
$output = new \Symfony\Component\Console\Output\ConsoleOutput();
$io = new \Symfony\Component\Console\Style\SymfonyStyle($input, $output);

$io->writeln(null);
```

Result in `4.0` : ` `
Result in `4.1` : `PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Style\SymfonyStyle::writeBuffer() must be of the type string, null given,`

**Possible Solution**  
To fix this, we would need to remove the type hinting in `SymfonyStyle:writeBuffer` on the `message`.

**Comment by stof** [comment]
Passing `null` was never supported, as the contract of the signature was always documented as `@param string`. Contract violations are not covered by our BC policy (they might even break in patch versions sometimes).
The only way to keep BC on invalid usages of our APIs working by luck due to the internal implementation would be to never change the implementation (which would make not be acceptable).

**Comment by WFrancois** [comment]
Oh, ok ! :/

Thanks for the quick reply.
