### ISSUE TITLE
Strange "if" in the RedirectResponse

### ISSUE THREAD

**Issue by ncou** [symfony/symfony#27574]
Hi,

There is a strange "if" in the RedirectResponse class.
https://github.com/symfony/http-foundation/blob/master/RedirectResponse.php#L45

`if (301 == $status && !array_key_exists('cache-control', $headers)) {
    $this->headers->remove('cache-control');
}`

The "not" array_key_exists" seems wrong, because why try to remove the header if the header is not present...

Am i missing something ?

**Comment by curry684** [comment]
That line of code could use an extra comment to clarify intent but it seems correct to me. It intends to achieve that if no cache control was explicitly requested by the user (via `$headers`) it shouldn't be inferred automatically (in `$this->headers`. Specifically, calling `remove` for `cache-control` is [a kind of magic](https://github.com/symfony/http-foundation/blob/master/HeaderBag.php#L199).

The cache header handling in HTTP Foundation contains a lot of magic to copy/duplicate/automate a lot of headers to please all possible UA implementations that exist out there expecting and respecting different caching mechanisms. This line of code trashes all of them for permanent redirects unless explicitly instructed otherwise. [It is even properly tested to do so](https://github.com/symfony/http-foundation/commit/be9633c63364dcc722719d5c33e0e8a73ec8866c).

**Comment by ro0NL** [comment]
However.. it assumes normalized format (lowercase) which, AFAIK, is not the case per-se for user-defined `$headers` :thinking:

**Comment by curry684** [comment]
It's dodgy code for sure that could use some comments and improvements.... but still mostly working as intended hehe.

**Comment by ncou** [comment]
Thank you for your explanations.
