### ISSUE TITLE
Performance improvement in ResourceCheckerConfigCacheFactory

### ISSUE THREAD

**Issue by DKurilo** [symfony/symfony#27615]
Here:
https://github.com/symfony/symfony/blob/3ccbec3497d277b1ffd4f3d0646a2b870f79a09a/src/Symfony/Component/Config/ResourceCheckerConfigCacheFactory.php#L42
is line:
`if (!$cache->isFresh()) {`
So each time when Symfony calling twig functions like url() or looking for translation it's calling isFresh(). isFresh i very expensive function(especially when you have slow storage). And it's better to avoid it.
I don't know if it can impact some other part of framework, but can we change ResourceCheckerConfigCacheFactory in this way:
1. to add private variable `private $cacheIsNotFresh = true;`
2. to change line I wrote above to `if ($this->cacheIsNotFresh && $this->cacheIsNotFresh = !$cache->isFresh()) {`
?

**Comment by stof** [comment]
Each cache is loaded only once AFAICT. And in prod, resources are not checked at all if you don't register the checkers (which is what is done in the core in non-debug mode), making the check very cheap.

This boolean would not help much, because the cache would be recreated before the next call (and all requests would start with the boolean forcing the check anyway).
