### ISSUE TITLE
Always load Doctrine listeners lazily

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#27661]
**Description**  
Currently, Doctrine event listeners are instantiated in order to create the Doctrine event manager. You can fix this by adding a `lazy=true` option to your service (this feature was added 6+ years ago). Could we just *always* make this lazy? This would solve issues during cache building, where all of the listeners are instantiated.

Relevant code: https://github.com/symfony/symfony/blob/8123bb102b2ad13f2b3f9f364f732f5590d42046/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L97-L99

Especially if we refactored the [ContainerAwareEventManager](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php) to accept a service locator (instead of the entire container), this would be an easy win: we wouldn't even need to make the original definitions public anymore (which is the only downside).

**Comment by HKandulla** [comment]
Hi,

we just ran into some major problems upgrading to DoctineBridge 4.2. due to this change.

Removing EventListeners using by using `$this->em->getEventManager()->removeEventListener([$event], $listener);` and passing the listener-object as the second argument will not remove the listener anymore (and not through an exception/error).
After upgrading to DoctrineBridge 4.2. you need to pass the FQCN of the listener. 
Maybe this should be mentioned?

Best, Hannes
