### ISSUE TITLE
Interface for Command class

### ISSUE THREAD

**Issue by HeathNaylor** [symfony/symfony#27665]
**Description**  
Add an interface for the `Symfony\Component\Console\Command\Command` class

**Comment by GromNaN** [comment]
This interface need to define the following methods that are used by the `Application` class:
```php
public function isEnabled()
public function setApplication(Application $application = null)
public function getAliases()
public function getDefinition()
public function getName()
public function getHelperSet()
public function mergeApplicationDefinition($mergeArgs = true)
public function run(InputInterface $input, OutputInterface $output)
```

Other public methods of the `Command` class might be used elsewhere:
```php
public function __construct(string $name = null)
public function ignoreValidationErrors()
public function setHelperSet(HelperSet $helperSet)
public function getApplication()
public function setCode(callable $code)
public function setDefinition($definition)
public function getNativeDefinition()
public function addArgument($name, $mode = null, $description = '', $default = null)
public function addOption($name, $shortcut = null, $mode = null, $description = '', $default = null)
public function setName($name)
public function setProcessTitle($title)
public function setHidden($hidden)
public function isHidden()
public function setDescription($description)
public function getDescription()
public function setHelp($help)
public function getHelp()
public function getProcessedHelp()
public function setAliases($aliases)
public function getSynopsis($short = false)
public function addUsage($usage)
public function getUsages()
public function getHelper($name)
public static function getDefaultName()
```

**Comment by GromNaN** [comment]
What is your use-case ?

**Comment by HeathNaylor** [comment]
Hey, interface for 2.7 is here: https://github.com/symfony/symfony/pull/27666

**Comment by ro0NL** [comment]
> we code to interfaces whenever possible

but now you're just adding interfaces to do so ... what's the point? Are you aiming for a different implementation? What's wrong with the base one?

> could not type hint an interface or even abstract class, just the concrete base class

In practice nothing wrong with that :)

**Comment by iltar** [comment]
I would love to see the ability to implement a very small subset via an interface, instead of extending the base Command. You could then move the configuration to either a static method, yaml, xml, php (friendly syntax) or some other configuration format. The current command then decorates your implementation and executes it.

**Comment by ro0NL** [comment]
you can configure a generic `Command` as a service today already, using e.g. another invokable service to call `setCode()` with.

**Comment by iltar** [comment]
It doesn't feel clean to me, to implement a Symfony command. This primarily due to inheritance. Especially when writing a simple test for it, I already mess up due to wanting to test `execute`, which obviously fails because I need to run `run`. It's also very hard to get a grip on _what_ you should extend and what you have to do to change behavior. There's so much in the API of the Command class that it's hard to get a good overview of its feature set. 

 - Where do I validate my input?
 - Do I have to override `run` or `execute`?
 - Do I have to configure it in the constructor?
 - Or in the configure method?
 - But the configure method is called in the constructor 🤔 
 - So do I also set the name there, or do I pass it as constructor argument?
 - Do I call `setApplication`?
 - I can configure everything, but I have to override `isEnabled` if I want to disable?
 - `interact`? `initialize`? Didn't know they existed until recently
 - `setCode`? I thought I could return a number instead?

It's just too big, too confusing and it hinders DX imo. There are too many things to think about when writing a command. If we can make the API more intuitive, I think that would be a quick win for _all_ tools and applications using the console component (because it's used quite some! 🎉 )

**Comment by ro0NL** [comment]
What about a base `AbstractCommand` (which the current `Command` extends), that way we can define the methods abstract.

**Comment by iltar** [comment]
That doesn't reduce the super set of (public/protected) methods in the command you're implementing though 😢

**Comment by stof** [comment]
I don't see how defining an interface would make the Command class more intuitive. Reimplementing everything without using the base class will require you to do *more* things.

**Comment by iltar** [comment]
It would interface only the methods you would have to implement already, but it lets you forget about any base classes. It will still exist, but uses composition instead of inheritance, cleaning up the public API you see as developer.

**Comment by stof** [comment]
@iltar but a bunch of them are optional to implement, because they are extension points inside the logic for advanced use cases (`interact` for instance). I'm not sure this would actually be simpler.

**Comment by Simperfit** [comment]
Do we want to go forward with this feature ? @stof @linaori

**Comment by nicolas-grekas** [comment]
Nope on my side.

**Comment by fabpot** [comment]
That's a no-go for me as well, closing.
