### ISSUE TITLE
Add WinCache Cache Adapter.

### ISSUE THREAD

**Issue by Auvipev** [symfony/symfony#27859]
I would like to see the wincache cache adapter.

- https://www.iis.net/downloads/microsoft/wincache-extension
- https://secure.php.net/manual/en/book.wincache.php

**Comment by nicolas-grekas** [comment]
Reading WinCache doc, I feel like most of its feature set is outdated on PHP7, since OPcache is native now. What is WinCache useful for nowadays? Do you have any pointer that could explain why one should use WinCache over APCu on Windows also? If the usefulness is confirmed, PR welcome.

**Comment by ikorisabi** [comment]
Hi i am another WinCache user and i have been using it since 5.6 was released. I have never really used APCu so i could not tell you which is better or where APCu has its strong points and weaknesses. The performance on my web applications are amazing. WinCache has been supported on php 7 in general according to the Microsoft website. The latest release for WinCache would have to be 2018-07-06 which was built for php 7.2. WinCache can do file cache, resolve file path cache, user cache, and has a session handler. I am not sure what APCu can do. Hopefully some could shed some light.

**Comment by nicolas-grekas** [comment]
Anyone willing to answer my questions above?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
