### ISSUE TITLE
Proposing improvement of debug:form command to give extra info regarding field types

### ISSUE THREAD

**Issue by pribeirojtm** [symfony/symfony#27875]
**Description**  
I'm proposing (what I think useful) a development of an improvement of `debug:form` command so it also gives information of form fields and their types that are in a given form Type to this command.

**Example**  
`php bin/console debug:form MyFormType --list-fields`
```
id » HiddenType
quantity » IntegerType
name » TextType
...
```

Or even more detailed for each field type. What do you think?

Thanks.

**Comment by yceruto** [comment]
:+1: I think we could show the children config (name and type) for the given form type at the end of the current output on `debug:form MyFormType` (without extra option `--list-fields`). Wdyt?

Would you like to create a PR that implements this feature? As the creator of the command I can help you do that.

**Comment by yceruto** [comment]
However, I can't garuantee that this feature is viable, because it'll require to build the form passing the resolved options to get the children configuration and:
 * we can't provide the resolved options (required options, type validation, etc) in CLI context.
 * also some fields are added dynamically through listeners or conditionally through the resolved options, so we'll miss some fields anyway.

The idea is good but I'm not sure if we can implement it. Right now, the command is able only to show static information.

**Comment by pribeirojtm** [comment]
@yceruto , unfortunately I don't have sufficient know-how on how to implement this feature, or even if it is possible, so I've created this ticket to discuss this possibility.

**Comment by flip111** [comment]
@yceruto would it be possible to run the form code and construct the form to finalize all it's child fields?

**Comment by yceruto** [comment]
@flip111 I don't think so, because the reason I explained above https://github.com/symfony/symfony/issues/27875#issuecomment-403025007

For example: Imagine you have a form type that requires an option `car` (instance of the class `Car`) to build some additional fields or change their options. How can we build this form type? i.e. we know that `car` is a required option and must be an instance of `Car`, but how to initialize it correctly from our side? Maybe it requires some dependencies to work well, we don't know. That's part of the userland world how to do that correctly, hence we can't guess.

IMHO, if we can't show the children in all cases, it's not worth it.

**Comment by flip111** [comment]
Maybe there can be a best effort (a guess) how to construct this form (some
forms don't need configuration so it's ok anyway). For other forms it can
depend on user input and thus the request. For this group of forms it might
be possible to construct them when you have the request code as captured by
the logger

**Comment by sstok** [comment]
I personally believe this is much of an edge case, the `form:debug` command lists all the form types and there options as these are very stable and not to dependent on runtime. Many Form types are actually very dynamic and don't have the same children for each configuration.

The Webprofiler already provides a good solution to show information about the used forms, on the current page.

**Comment by xabbuh** [comment]
closing as explained
