### ISSUE TITLE
[Doctrine-Bridge] : Sanitize SQL requests

### ISSUE THREAD

**Issue by QuentinCurtet** [symfony/symfony#27901]
**Symfony version(s) affected**: 4.1.1 and prior (i think)

**Description**  
I think this actually could be a feature too.
Got an error when i'm trying to serialize a Doctrine Query Builder in debug mode (with the web profiler) : 

Uncaught Exception: You cannot serialize or unserialize PDO instances {"exception":"[object] (PDOException(code: 0): You cannot serialize or unserialize PDO instances at /vendor/symfony/http-kernel/DataCollector/DataCollector.php:39)"}

**How to reproduce**  
Make sure you are using the web profiler.
Create a connection of type Doctrine DBAL Connection and the use the function execUpdate() by passing an argument of type QueryBuilder.
When you will try to use it, it will say that it's not possible to serialize or unserialize PDO instances.

**Possible Solution**  
In the file Symfony\Bridge\Doctrine\DataCollector\DoctrineDataCollector and in the method sanitizeQuery on line 158, add the following line : 
$query['sql'] = (string) $query['sql'];

**Comment by weaverryan** [comment]
Hey there!

Thanks for opening this! I just checked out the code: the `Doctrine\DBAL\Connection::executeUpdate()` function actually expects a *string* first argument, not a QueryBuilder - https://github.com/doctrine/dbal/blob/66daecd0084118ec04c54288915a8eb9bac7511d/lib/Doctrine/DBAL/Connection.php#L1060

So, I think this isn't a bug, but actually, you just can't pass a QueryBuilder to this argument. We *could* indeed fix this inside `DoctrineDataCollector`, but I think the use-case overall isn't valid, because Doctrine is always expecting a string.

Cheers!

**Comment by elfxby** [comment]
use $qb->getSQL() !!

$qb = $conn->createQueryBuilder()->update('users', 'u')->set('u.last_login', 'NOW()')->where('u.id = 1');
$this->conn->executeUpdate($qb->getSQL());
