### ISSUE TITLE
[PhpDumper] Problem with cache rebuild when project is symlinked

### ISSUE THREAD

**Issue by polukes** [symfony/symfony#27909]
**Symfony version(s) affected**: 4.1.1

**Description**  
We have real path eg `/data/www/html` and symlink `/var/www/html`. The reason of this is not important in this bug. When we in symlink path (`/var/www/html`) we expect that cache will rebuild with this path.
Unfortunately the path in many cache files is always `/data/www/html`.
I found problem with used `__DIR__` in PhpDumper that not respect symlink properly.

**How to reproduce**  
Rebuild cache from symlinked directory.

**Possible Solution**  
Not use `__DIR__` and `__FILE__`.

**Comment by nicolas-grekas** [comment]
I'm not sure I understand the description. Using `__DIR__` is on purpose, since that makes the generated file independent from the actual location where the container is dumped. On the contrary, not using `__DIR__` would mean generating hardcoded paths in the dumped container, which is exactly what is undesired.

If you could provide a reproducer we could run locally, that could help understand what you mean precisely. Thanks.

**Comment by polukes** [comment]
To reproduce please rebuild cache from symlinked directory (not from original directory) and check generated paths in cache files.

**Comment by yawa20** [comment]
@polukes 
php __DIR__ read real directory instdead of symlink
In my opinion is right way, because symlink is just a link, not a real path, 
and directory /var/www/html does not exists

To get few paths for the same directory try to mount directory instead of symlink
in linux systems you can call 

```
$ mkdir /var/www/html
$ mount --bind /data/www/html  /var/www/html
```

**Comment by nicolas-grekas** [comment]
I think we shouldn't change anything here. Using `__DIR__` is on purpose and provides location immutability. If this means that you can't use symlinks, that's fine to me. Maybe overriding kernel's getCacheDir et al. would allow you to customize the paths you'reusing. But for having working on it in so many iterations, I'm pretty sure we don't want to change what works well right now for almost everyone.
Of course, feel free to submit a PR if you think otherwise.

**Comment by inri13666** [comment]
Hello all :)
Possibility to use symlink was broken here https://github.com/symfony/symfony/commit/a14153a4fd6d3379d60a85af882dc8aefea08c7d
and then the possibility to use symlinks for the cache was finally broken here
https://github.com/symfony/symfony/commit/599dbca3cde76e729deab6b0750a81eab32143e4
because __DIR__ for file within symlinked folder will return realpath

**Comment by inri13666** [comment]
P/S : https://bugs.php.net/bug.php?id=77639
