### ISSUE TITLE
[DX] Flaws in the way environment variable are used ? 

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#27962]
Hello,

After a discussion on Symfony Slack about environment variables and CLI around my question:
> I’m interested into how the community solves the *environnement variable and the CLI*.

It seems that nothing solid came out out of this discussion.

The documentation states that environment variables [should be added on the webserver level on production](https://symfony.com/doc/current/configuration/external_parameters.html#environment-variables).

Nothing is said reguarding the `CLI`, so a lot of people (like me) will end up spending time looking for why a crontab entries is not executed.

To me, prefixing the executed commands by the environment variables is *not a good solution*. I mean, it would involve: 
- *variable duplication* (so bad maintenance, "oops forgot to add this variable in this place"), 
- and very *bad lisibility* (prefix with 20+ environment variables 🤔?)

Regarding of this, why push in favor of environement variable if the only way of achieving this is to use a *not recommended way* (`.env` file).

One alternate solution would be to create a file on the system in `/etc/environment` that contains those environment variable, BUT again, *what happens if your server hosts multiple projects* and you want one app X to be `APP_ENV=prod` and the other Y `APP_ENV=dev`, then you have a variable collusion with the name unless you change the `APP_ENV` variable name in all project to include a vendor prefix ? (I don't even know if it's feasible).

Not all of us use containers to run in production (or doesn't even want to).

PS: I open this here instead of the documentation repository because it reveals more questions than just "how to deal with that in doc is missing".

**Comment by dkarlovi** [comment]
If you have your env vars in `~/.bashrc`, `~/.profile` or similar, you'll notice cron will not read them. That's because cron doesn't start your [Bash as an interactive login shell](http://manpages.ubuntu.com/manpages/precise/en/man1/bash.1.html#contenttoc6).

To fix it, you either have a wrapper which does, or, more simply, [source `~/.profile`](https://unix.stackexchange.com/a/27291/100787). This makes your env vars available to cron too and it works exactly as you'd expect.

**Comment by tristanbes** [comment]
I don’t have my environement in a `.bashrc` or `.profile` or `/etc/environement` yet. I said that processing them this way on a server that host multiple APP is not doable because of variable name collision I mentionned in my original message.

**Comment by Saphyel** [comment]
I think you are trying to find a good solution for a bad practice, your actual project should be isolated from others projects. Also I think you should avoid to use env. vars in that scenario because you have the risk of write dev data into prod or otherwise.

The solutions that I think you can take is...

1. Hardcode values like the ol' times in a `parameters.yml` and use that file as source of data rather than use %ENV()%.
2. Use DotEnv.
3. Even if the console.php is provided by symfony is in your git source code so you can update it to enforce to use the .env that you want or hardcode values or whatever you want.

**Comment by Kocal** [comment]
I totally agree. 

For me, it's really hard to handle env vars at so many places:
- `.env.dist` (and `.env` for local development)
- Inside a web context (nginx/Apache) in production
- Inside a CLI context in production, because I don't want to create global env vars for a specific project. I already have 2/3 Symfony app on the same server, and I don't wan't to learn, use, masterize Docker for that :slightly_frowning_face: ...
- A special `.env.test` for Travis (not mandatory, but still helpful!)

At the moment, I followed those steps to make my life easier:  
- During deployment, automatically copy a production-ready `.env` (resolve CLI context)
- In production, **NEVER** create `APP_ENV`, so Symfony will load `.env` (resolve Web context)

I'm feeling dirty, but it works, and that's easier to maintain/use for me.

---

Personally, I found paremeters so much useful and easier...
Yes, OFC they are less flexible, but they are so much easier to maintain/use:
- Copy `parameters.yml.dist` => `parameters.yml` for local development and Travis builds
- Use a `parameters.yml` for web and CLI production contexts

and that's works!

**Comment by stof** [comment]
@Kocal and you can still use a parameters.yml file. My own approach is actually a mix of both. As I'm deploying on Heroku, I'm using `%env()` to read credentials for various services (allowing updates to be taken into account without requiring a cache clearing), but most of my config is still handled in a parameters.yml file (part of it is not supported as runtime config anyway and requires to be known at compile time)

**Comment by Kocal** [comment]
Oh, that's interesting, I wasn't aware about that.

I will try to find some time for using `parameters.yml`, that would be very interesting.

**Comment by curry684** [comment]
> I don't want to learn nor masterize Docker for something that should be so simple to manage.

It also solves 2000 other problems...

Not to derail the discussion or anything but treating Docker as a solution for this issue you're having is like saying the best thing about a car is that you're dry inside.

Docker solves nearly every deployment and testing issue. Elegantly and reliably.

**Comment by tristanbes** [comment]
> It also solves 2000 other problems...
and creates 3000 others problems. Please let's focus on this issue, I doubt that Symfony will adopt Docker as the official way now to deploy applications. Until then, let's have solution that works for all ! :p

**Comment by dkarlovi** [comment]
I don't think introducing Docker into this conversation solves anything.

>  I said that processing them this way on a server that host multiple APP is not doable because of variable name collision 

"server that hosts multiple apps" doesn't imply "server that hosts multiple apps **using the same account**", that makes a significant difference. Doing so is hardly recommended.

Having said that, I understand there are various situations in which you'd want to to that, when you might not have the choice to do it better.

The question is all about understanding how env vars inheritance works and scoping:

- placing them in `/etc/environment` means they're globally scoped (just like `global` keyword in PHP), you can do this **only if your whole server is dedicated to a single app** (but you can still chose the following approaches)
- placing them in `$HOME/.profile` means they're scoped to the user to which that `$HOME` belongs to, you can do this **only if your whole user is dedicated to a single app** (but you can still choose the following approach) - this is what the approach I would recommend
- placing them in `<approot>/.env` means they're scoped to the folder, but, since "a folder" is not a first-class citizen for scoping processes, you need to do it yourself.

You can handle it yourself

1. by sourcing the env file as linked: `source .env; bin/console foo:bar` (again, recommended if you must use the non-recommended deployment procedure)
2. by changing the RC file when invoking Bash `bash --rcfile .env -c "bin/console foo:bar"`
3. by just using `DotEnv` for CLI, even in production

If you're using Ansible as you've noted before, setting this up and distributing the env vars everywhere should be very simple to do.

**Comment by apfelbox** [comment]
Somehow related / my take on this: https://github.com/symfony/flex/issues/287

Please note that the biggest issue with using a `parameters.yaml` in Symfony 4 was that due to [an issue](https://github.com/symfony/flex/pull/377) in flex something like the the [incenteev parameters handler](https://github.com/Incenteev/ParameterHandler) wasn't able to work properly. This issue has since been resolved, so you might be able to replicate the same workflow as in Symfony <= 3.

My workflow is using `APP_ENV` as env var and everything else in a `parameters.yaml`.

**Comment by Kocal** [comment]
Issue https://github.com/symfony/flex/issues/251 is related to this one BTW.

**Comment by xabbuh** [comment]
IMO we need to improve the documentation to make it more clear when there is actual value to use environment variables and when you should rather stick with well-known container parameters. Right now we lack to make clear that there is nothing wrong in still using them, but we seems to confuse (too) many developers right now. From what I have seen in different projects and on Slack is that people overcomplicate their setup and deployment process by using environment variables when plain old container parameters would have solved their problems way easier.

**Comment by Kocal** [comment]
@xabbuh If I understand well, we should not use env vars (in `.env`) when their values will be always identical between local dev/tests/production? 

Well, it seems logical just by writing it... and it's even written in the [doc](http://symfony.com/doc/current/configuration.html#the-env-file-environment-variables): 
> The .env file is special, because it defines the values that usually change on each server

Also, if we really need to defines env vars but without a `.env`, we must use this, right?
```yml
parameters:
  env(FOO): value
```

**Comment by rufinus** [comment]
> what happens if your server hosts multiple projects and you want one app X to be APP_ENV=prod and the other Y APP_ENV=dev

Don't you use FPM with different pools? (Which also seperates the user processes) You can (and should) define the ENV vars directly in the pool config.

Like:
```
[mypoolname]
user = nologinwebuser
env[APP_ENV] = prod
```

**Comment by chalasr** [comment]
I personally load projects env vars via `~/.bashrc` for the CLI (`~/.zshenv` to be exact) and configure cron so that it uses the right shell.

**Comment by Kocal** [comment]
@chalasr so you have one user per project?

**Comment by chalasr** [comment]
@Kocal yes, one project per host and one `app` user per host able to run the project.
If an host (EC2) serves more than 1 project, all projects share the same env in CLI (project1 has project2's env when it runs via cron, env vars names are prefixed to avoid collisions).
In dev, I use Dotenv.

**Comment by Kocal** [comment]
And how do you handle env vars through web server? You still have to duplicate them right?
AFAIK you can't tell nginx/apache to source `~/.bashrc` for each app right?

**Comment by chalasr** [comment]
Indeed, an additional env file per FPM pool. Env vars are managed in a vault (single place) and dumped for both CLI and FPM on deploy (via Ansible)

**Comment by rufinus** [comment]
@chalasr why dont you include a own file in your fpm pool?

```
[www]
.... static pool config
include = /srv/www/website/fpm.conf
```

fpm.conf looks llike:
```
env[APP_ENV] = prod
env[DATABASE_URI] = ""
```
This file can be deployed via ansible, you need to restart the fpm - but you should anyway after deployment to reset the op cache.

**Comment by nicolas-grekas** [comment]
Closing as this improved a lot recently, with https://github.com/symfony/recipes/pull/501 as the last step.

**Comment by CedrickOka** [comment]
One solution for docker in entry point
printenv | sed 's/^\([^_]|[^=]*\)\=\(.*\)$/\1\="\2"/g' | sed 's/^\(_\)\=\(.*\)$//g' > /app/.env.prod.local
