### ISSUE TITLE
Issue with render_hinclude() when PHP templating engine is enabled

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#28001]
**Symfony version(s) affected**: all

**Description**  
If you put the following in a Twig template:

```twig
{{ render_hinclude(controller('...'), {'default': 'Loading...'}) }}
```

The `Loading...` text is used as a fallback content (as explained in https://symfony.com/doc/3.4/templating/hinclude.html). However, if you enable the PHP engine in the app:

```yaml
framework.templating.engines: ['twig', 'php']
```

Then, the Twig template no longer works and instead you see this error:

```
An exception has been thrown during the rendering of a template
("Template name "Loading..." contains invalid characters.").
```

**Additional context**  
Originally reported by @liviubalan as a doc issue: https://github.com/symfony/symfony-docs/issues/9790

**Comment by yceruto** [comment]
IMHO the `default` option shouldn't be used for that purpose, because both engines expected a valid template name (on parsing or normalization of the template name) before verify if it exists or not.

A similar error can happen if something like this is passed by default:
```twig
{{ render_hinclude(controller('...'), {'default': '@copyright 2018'}) }}
```
For this case, it is the `TwigEngine` who throws the error:
```
Malformed namespaced template name "@copyright 2018" (expecting "@namespace/template_name").
```

If you want a default plain text, you can use the Twig `default` filter instead:
```twig
{{ render_hinclude(controller('...')) | default('Loading...') }}
```

**Comment by yceruto** [comment]
Fixing in https://github.com/symfony/symfony/pull/28005

**Comment by yceruto** [comment]
And fixing the Twig part in https://github.com/twigphp/Twig/pull/2721
