### ISSUE TITLE
Doctrines event subscriber out of memory.

### ISSUE THREAD

**Issue by ln-e** [symfony/symfony#28010]
**Symfony version(s) affected**: 4.*

**Description**  
1. Create Doctrine's EventSubscriber.
2. Inject into in some service.
3. Inject into that service EntityManagerInterface

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in var/cache/dev/ContainerLFEgQjr/getDoctrine_Dbal_DefaultConnectionService.php on line 1

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in var/cache/dev/ContainerLFEgQjr/getDoctrine_Dbal_DefaultConnectionService.php on line 1
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1
```

It worked in symfony 3.3 but it didn't work after update to symfony 4.1

**How to reproduce**  
https://github.com/ln-e/symfony_out_of_memory

**Possible Solution**  

**Additional context**

**Comment by dmaicher** [comment]
Can confirm the issue. Until its resolved you could temporarily mark your EventSubscriber `lazy`:

```diff
diff --git a/composer.json b/composer.json
index 49746b5..4dd4ca4 100644
--- a/composer.json
+++ b/composer.json
@@ -15,6 +15,7 @@
         "symfony/monolog-bundle": "^3.1",
         "symfony/orm-pack": "*",
         "symfony/process": "^4.1",
+        "symfony/proxy-manager-bridge": "^4.1",
         "symfony/security-bundle": "^4.1",
         "symfony/serializer-pack": "*",
         "symfony/swiftmailer-bundle": "^3.1",
diff --git a/config/services.yaml b/config/services.yaml
index f98bd4e..2075d09 100644
--- a/config/services.yaml
+++ b/config/services.yaml
@@ -33,3 +33,6 @@ services:
 
     # add more service definitions when explicit configuration is needed
     # please note that last definitions always *replace* previous ones
+
+    App\Event\EntitySubscriber:
+        lazy: true

**Comment by nicolas-grekas** [comment]
Thanks for the reproducer.

The cause of the issue is a circular reference when proxy-manager-bridge is not installed: on 3.3, this is detected at runtime and leads to `  [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException] Circular reference detected for service "doctrine.orm.default_entity_manager", path: "doctrine.orm.default_entity_manager -> doctrine.dbal.default_connection".` (thus, not sure what you meant by "It worked in symfony 3.3": it doesn't "work" - but it fails properly yes :))

On 3.4 & up, this circular reference is undetected and turns to an infinite loop.

**Comment by ln-e** [comment]
Oh, I see. In my 3.3 project I have an installed `doctrine/doctrine-migrations-bundle`. And It is somehow solve my problem just like `symfony/proxy-manager-bridge` do it for 4.1 version. 

I have try on new install sf3.3. If there is migrations-bundle - no error, otherwise `Circular reference detected`.

Anyway installing `symfony/proxy-manager-bridge` solves problem in 4.1, thanks.

**Comment by stof** [comment]
that's because `doctrine/doctrine-migrations-bundle` requires the `ocramius/proxy-manager` library so this one got installed, and your 3.3 project was probably using `symfony/symfony` rather than component packages, so the code of the bridge was also available. So this leads to a situation where you have the proxy manager bridge able to handle lazy services.
