### ISSUE TITLE
Unable to get rid of SaveSessionListener deprecation

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#28022]
**Symfony version(s) affected**: 4.1.1

**Description**  
Getting:

```
The "Symfony\Component\HttpKernel\EventListener\SaveSessionListener" class is deprecated since Symfony 4.1, use AbstractSessionListener instead.
```

First of all, it's not documented in https://github.com/symfony/symfony/blob/master/UPGRADE-4.1.md

And second, I can't get rid of this deprecation error.

**How to reproduce**  
Upgrade from 4.0 to 4.1

**Comment by nicolas-grekas** [comment]
could you provide a reproducer please?

**Comment by nicolas-grekas** [comment]
Closing due to lack of feedback (and also because nobody else complained)
Feel free to provide more details of course if you think there is a bug.

**Comment by frostieDE** [comment]
I was having the same issue. Turned out, I had `symfony/framework-bundle` version 4.0.14 installed (even though I was using Symfony 4.1.4). 

`composer update symfony/framework-bundle` did the trick after modifying some of my bundles which required the `symfony/lts` package (which locked `framework-bundle` to version 4.0.x).
