### ISSUE TITLE
CSRF token is invalid

### ISSUE THREAD

**Issue by shobekhan** [symfony/symfony#28064]
**Symfony version(s) affected**: Symfony 3.4.9

**Description**  
I have a strange problem with Symfony form csrf token validation (**dev environment**).

If I change the token manually using firebug and the CSRF token is invalid. I get an error "The CSRF token is invalid. Please try to resubmit the form." which is good and it should be doing that.

The problem is that after this happens, the form never gets submitted I always keep on getting the error  "The CSRF token is invalid. Please try to resubmit the form." 

It gets into an infinate loop

This problem is also reported by other users on stackoverflow https://stackoverflow.com/questions/35208299/symfony-3-0-1-csrf-token-present-but-invalid

**How to reproduce**  
https://imagebin.ca/v/4A0LttVtZDkP valid csrf token data in xdebug
https://imagebin.ca/v/4A0Lkq94niK9 invalid csrf token data in  xdebug

**Possible Solution**  

**Additional context**

**Comment by javiereguiluz** [comment]
I'm closing this one because, as you can see in https://stackoverflow.com/questions/35208299/symfony-3-0-1-csrf-token-present-but-invalid, it's (probably) not a Symfony bug but a configuration issue (session dir is not writable, cookies are using HTTPS but in local environment you are using HTTP, etc.)

If you can reproduce this in a Symfony app without any of those config issues, please share the reproducer so we can confirm the bug and fix it. Thanks!

**Comment by latheva** [comment]
I had the same problem on env=dev but not on preprod (symfony 4.4)

--Solution--
There was missing `sessions` dir in the root
I have created one then the problem solved.

cheers
