### ISSUE TITLE
In Production, all errors become out of memory exceptions

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony#28197]
**Symfony version(s) affected**: 4.1.1

**Description**  
When running in environment `prod` with display errors off, I'm seeing in my `/var/log/nginx/error.log` lots of `out of memory exception`. I'm having to resort to running in dev environment to see that the error (in this instance) is because a directory isn't writeable.

Why is an out of memory exception being reported in the logs, instead of something more sensible?

**How to reproduce**  
Switch to prod mode, and try to write to a non-writeable directory, and you should see the out of memory exception error in the server log.

**Comment by dkarlovi** [comment]
If this is indeed a memory issue, what are the runtime's memory constraints?

For example:

- what's the `memory_limit` set to?
- is the PHP process running out of memory on the server itself (so, it stays within `memory_limit`, but the kernel refuses to allocate more memory because of system-level memory issues)?

Do you have any more details which would help pinpoint the issue? Maybe a stacktrace? Can you create a reproducer?

**Comment by xabbuh** [comment]
@ChangePlaces Do you have any more information that help us to reproduce the issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by GreenLeewayDesignCastle** [comment]
I think I have the same problem, can we open this again ?

**Comment by xabbuh** [comment]
Do you have some more information that allow us to reproduce it?

**Comment by ricktg** [comment]
I had the same issue using version 4.2.4

The problem was **var/log folder permissions**.

Doing a chmod -R 777 var/log solved it.

**Comment by biji** [comment]
Same here 4.3
