### ISSUE TITLE
[PHPUnitBridge] Clock Mock may not work as expected

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony#28259]
**Symfony version(s) affected**: 4.1

**Description**  
The clock mock feature of the PHPUnit bridge is very nice. But it uses a trick with function namespace resolution to override and mock time related functions.

And because of this PHP bug since 5.4 : https://bugs.php.net/bug.php?id=64346 it may not work as expected. You may experience the bug here: https://3v4l.org/IMmoO

If the mocked function is used within the same namespace before the clock mock is registered (https://github.com/symfony/phpunit-bridge/blob/master/ClockMock.php#L82), then the mock is not used which make the test fail.

It may leads to tricky debug as run alone a test passes but it fails if run with other tests.

**Possible Solution**  
- a warning in the documentation
- register mocked functions at the very beginning of the test suite execution

**Comment by nicolas-grekas** [comment]
You're right. That's not a PHP bug but the side effect of an optimization we really want to have.
You can also manually register the namespaces where the mock should be created, like done in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/phpunit.xml.dist

I'm closing here since there is nothing to fix on the implementation side.
PR welcome on https://github.com/symfony/symfony-docs/ if you figure out how to improve this of course!
Thanks for the report.

**Comment by sylfabre** [comment]
@nicolas-grekas ok. I wasn't sure you were aware of this bug. I'll try to work on a PR then.

**Comment by sylfabre** [comment]
I'm putting here the this article https://sylfabre.hashnode.dev/troubleshoot-a-symfony-clockmock-test
 I published for the dev team at https://www.assoconnect.com in case it helps anyone 🤞
