### ISSUE TITLE
Doctrine command make absolutely nothing :(

### ISSUE THREAD

**Issue by GothShoot** [symfony/symfony#28484]
**Symfony version(s) affected**: 4.1.2

**Description**  
Hey everyone,
I have a very strange problem with my project, i want to create my database with doctrine:create:database.
But nothing run (cmd.exe use only 16Mb of RAM, no CPU and no disk) MySQL not have request and after a lot's of hours, yes hours .. only nothing ..
I have verified my database config, clear cache with remove var/cache directory, checked php config, but nothing work ..

Any idea ?

Thank's 

**How to reproduce**  
 Code is open in: https://github.com/NitroxLab/valvoja

**Comment by iltar** [comment]
Please check the symfony slack for support (either #doctrine or #support channel). Slack can be found here:  https://symfony.com/community. Otherwise the [doctrine bundle repository would](https://github.com/doctrine/DoctrineBundle/) be the place to report a bug or issue.

If it turns out that there's a bug somewhere in the Symfony command, you can open an issue for that specific issue (or update this one if it's not being closed). If it's a bug specifically in the doctrine command, check the repository I've just linked.

**Comment by xabbuh** [comment]
I am going to close here for now. But we will of course reopen, if it turns out that there is a real bug to fix.
