### ISSUE TITLE
[Serializer] Impossible to decorate the serializer

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#28544]
**Symfony version(s) affected**: 4.1.1 (at least)

**Description**  
I tried to decorate the serializer, but it's not possible; I get an exception:

>   Circular reference detected for service "App\Serializer", path: "App\Serializer -> App\Serializer.inner -> App\Serializer".  

**How to reproduce**  

With a fresh website skeleton, add this commit: https://github.com/lyrixx/test/commit/f6e27f55d6ee946451e002f9a6938652ed56220b

I tried to decorate the Router, in order to ensure the decoration system works as expected, and it works well. So I think there is something special with the serializer, but I don't know what :/

Note: Actually, I don't need this at all, I found that while trying to help someone

**Comment by lyrixx** [comment]
I'm already on the latest release. Should I try master ?

**Comment by nicolas-grekas** [comment]
4.1-dev yes please

**Comment by ogizanagi** [comment]
I guess that's because of autoconfiguration. You decorator implements `ContextAwareNormalizerInterface`, hence `NormalizerAwareInterface`, thus is tagged as a normalizer and injected into the `Serializer`.

Note: decorating the Serializer is a bit flawed anyway depending on what you're trying to achieve, as it injects itself (hence not the decorator) into `(De)NormalizerAwareInterface` and `SerializerAwareInterface`.

**Comment by nicolas-grekas** [comment]
I confirm: disabling autoconfiguration removes the circular ref.

**Comment by nicolas-grekas** [comment]
This is similar to #27211, #25840 and #27696, except that these 3 duplicates involve `!tagged` instead of autoconfiguration.
I think it should be possible to either skip the tag or throw a meaningful error message in `SerializerPass` (the logic should be unrelated to autoconfiguration since this situation can also happen by writing bad config manually, although a lot less likely.)
Would you like to give it a try?

**Comment by lyrixx** [comment]
> Note: decorating the Serializer is a bit flawed anyway depending on what you're trying to achieve, as it injects itself (hence not the decorator) into `(De)NormalizerAwareInterface` and `SerializerAwareInterface`.

indeed, this was just a test ;) 

> Would you like to give it a try?

Sorry, I'm a bit busy ATM :(

**Comment by nicolas-grekas** [comment]
OK no pb. I'm closing then, since everything works as expected (even if we can always wonder about improving, but then the list of issues would grow up to infinity ;) )
