### ISSUE TITLE
[HttpFoundation] PHP7.2 session migration error

### ISSUE THREAD

**Issue by Flofr** [symfony/symfony#28577]
Hello,

I upgrade my PHP version from PHP 5.6.36 to PHP 7.2, but I have a problem when I want to use the migrate function of Session component. 

My simple line of code :
`$this->request->getSession()->migrate(true, $newLifetime);`

The error returned :
`Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time `

I have already a session opened before by my login page, but I want to change the session life time on login.
My Symfony version 2.8.44
Thanks for your help

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by Flofr** [comment]
Thank for your help.
I do this soon as possible

**Comment by Flofr** [comment]
This is the repo with the sample : https://github.com/Flofr/Bug-session-php7.2-sf2.8

You have to go on the login page /login with the login "test" and pwd "test"
The listener AuthenticationHandler change the session lifetime and throw the exception on PHP7.2

**Comment by Flofr** [comment]
For help you, the test in Symfony code is not complete.
This test is only for session migrate without parameter, but the bug is when you migrate with new lifetime.
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Tests/Session/SessionTest.php

**Comment by xabbuh** [comment]
I am not sure what we can do here. Maybe deprecate being able to pass a lifetime here?

**Comment by Simperfit** [comment]
@xabbuh is this still a bug ?

**Comment by xabbuh** [comment]
I think so.

**Comment by joeyhub** [comment]
What's wrong with using session_set_cookie_params? https://www.php.net/manual/en/function.session-set-cookie-params.php

**Comment by joeyhub** [comment]
Note that the manual might give the wrong impression that it's just a wrapper for ini_set, TIAS.

**Comment by joeyhub** [comment]
You're probably going to just have to session destroy then recreate or something.

```
$old = $_SESSION;

if ($destroy) {
 session_destroy();
} else {
 if ($howDoesRegenWork) {
  session_abort();
 } else {
  session_write_close();
 }
}

session_set_cookie_params($timeout);
session_start();
$_SESSION = $old;
```

Set what that does, otherwise may just have to look at the PHP source. Hopefully nothing unpleasant would be needed such as session_encode/session_decode, etc. Might want some other hacks for other places like session_id to set, etc.

Personally I usually end up just not using the PHP handler for sessions as it has been causing me headaches since 2008. You don't get any proper locking, etc. Don't know why you would make a framework only to fallback to a flawed by design session API. It's only good for prototyping, mockups and simple use cases.

**Comment by Guite** [comment]
We had a quite hard fight with this one (https://github.com/zikula/core/issues/3898, https://github.com/zikula/core/issues/3986, https://github.com/zikula/core/issues/4078), but now I think this is solved.

> You're probably going to just have to session destroy then recreate or something.

Yes. I finally found a fix that seems to work.

Background of the problem:

First, the `NativeSessionStorage::regenerate` method returns if there is no active session (see [here](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L204-L207). Afterwards it tries to set a given custom lifetime using `ini_set` (see [here](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L213-L215)) which causes the original problem (`Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time`).

So what I did is this: https://github.com/zikula/core/compare/e3b9d426b5cc1ae102b4f392c3e0cdb1c120d1d4...feffebea4246a8898f966d92c8819a3ab068a414

It looks a bit confusing because I had to duplicate some code of the class in my child class (due to #35460).

The actual fix (it looks so simple) is replacing:
```php
ini_set('session.cookie_lifetime', $lifetime);
```
by:
```php
session_destroy();
ini_set('session.cookie_lifetime', $lifetime);
session_start();
```
