### ISSUE TITLE
Symfony4 Security - Url parameter after login and redirect

### ISSUE THREAD

**Issue by etshy** [symfony/symfony#28605]
I have a problem with login redirection URL parameter (after we've been disconnected > redirect to login > login > redirect to previous page).

I'm not sure if this problem is related to Symfony directly or with FoSUserBundle

I did a SO Post and an isuse on FosUserBundle but both didn't answered with a fix to my problem.

See [this SO thread](https://stackoverflow.com/questions/52347746/symfony4-security-url-parameter-after-login-and-redirect)

See [this github Issue](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2789)

It happened to me again today, I ended up with this url `http://X.X.X.X/project/public/admin/users/edit/5aaec5ddde7534147c004f02?_url=%2Fadmin%2Fusers%2Fedit%2F5aaec5ddde7534147c004f02`

As you can see, I don't have my app at the root of my server, but I can't think about a reason that could cause this parameter.

Sorry for this issue, but as my questions were not answered, I'm trying here.

**Comment by javiereguiluz** [comment]
The problem is that the URL is added a `_url` query string parameter with the previous URL ... and that's repeated over and over again, with more and more `_url` query string params until the URL is incredibly long?

If that's the problem, I'd say it's an issue of FOSUserBundle, or maybe some misconfiguration in the app?

**Comment by etshy** [comment]
That's exactly the problem, yes.

I'll try to ask again in the FosUser github, then.

Thanks.
