### ISSUE TITLE
[LDAP] Add error codes to exceptions

### ISSUE THREAD

**Issue by shanept** [symfony/symfony#28677]
**Description**  
Upon LDAP errors, the PHP ldap extension may also return an error code. Using this code may provide a friendlier way to determine the root cause of an issue than to interpret the error message - consider how the following example may be achieved currently, with the LDAP component.

**Example**  
```php
$ldap = Ldap::create('ext_ldap', [...]);

try {
    $ldap->bind('invalid_user', 'invalid_password');
} catch (ConnectionException $ex) {
    switch ($ex->getCode()) {
        case INVALID_CREDENTIALS:
            $message = 'Invalid Username or Password.';
            break;
        case CONNECTION_TIMEOUT:
            $message = 'Unable to connect to server.';
            break;
        ...
    }
}
```

**Comment by scaytrase** [comment]
I'd better suggest throw proper exception with given messages

**Comment by dontub** [comment]
I think this is not only relevant for the bind operation, but also for other operations e.g. query. For example I want to catch LDAP_NO_SUCH_OBJECT (error code 32). Currently I'd have to parse the message to do this. So I suggest to reopen this issue.

**Comment by fabpot** [comment]
@dontub Would you will to submit a pull request for that?

**Comment by dontub** [comment]
I just had a deeper look at it. I'm currently thinking about an exception factory like this
```php
final class ExceptionFactory
{
    public static function createLdapException($messageFormat, $connection)
    {
        $errorCode = ldap_errno($connection);
        $errorMsg = ldap_err2str($errorCode);
        $message = strtr($messageFormat, [
            '%errorCode%' => $errorCode,
            '%errorMsg%'  => $errorMsg,
        ]);

        return new LdapException($message, $errorCode);
    }
}
```
instead of adding a call to `ldap_errno()` everywhere.

I also found four places where an `LdapException` is thrown without a call of an LDAP operation:
* https://github.com/symfony/symfony/blob/3498259b12ff66604e960db9b313268a0b69d8de/src/Symfony/Component/Ldap/Adapter/ExtLdap/Adapter.php#L29
* https://github.com/symfony/symfony/blob/3498259b12ff66604e960db9b313268a0b69d8de/src/Symfony/Component/Ldap/Adapter/ExtLdap/ConnectionOptions.php#L86
* https://github.com/symfony/symfony/blob/3498259b12ff66604e960db9b313268a0b69d8de/src/Symfony/Component/Ldap/Adapter/ExtLdap/EntryManager.php#L162
* https://github.com/symfony/symfony/blob/3498259b12ff66604e960db9b313268a0b69d8de/src/Symfony/Component/Ldap/Adapter/ExtLdap/Query.php#L83

Is the last one necessary as the `OptionsResolver` would already prevent this?
Should the `LdapException` be limited to errors of real LDAP operations? If yes, what would be an appropriate replacement for the exceptions above? The class comment of `LdapException` (`LdapException is thrown if php ldap module is not loaded.`) needs to be updated in any case. (The same holds true for `DriverNotFoundException` which has exactly the same comment.)

WDYT?

In case of the exception factory: Should PHP type hints be used there?
