### ISSUE TITLE
RedisStore does not follow the StoreInterface for waitAndSave

### ISSUE THREAD

**Issue by nesl247** [symfony/symfony#28694]
**Symfony version(s) affected**: 4.1.*

**Description**  
`RedisStore` does not properly follow `StoreInterface`'s docblock.

**Possible Solution**  
Instead of throwing `InvalidArgumentException` it should throw `NotSupportedException

**Additional context**  
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Lock/StoreInterface.php#L37
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Lock/Store/RedisStore.php#L77

**Comment by chalasr** [comment]
Same for all other methods actually, they all rely on `RedisStore::evaluate()` without catching the `InvalidArgumentException` it throws.

**Comment by jderusse** [comment]
@nesl247 good catch, it's a mistake. Would you mind to open a PullRequest?

@chalasr should we wrap every external call in a try/catch in order to return an expection `Symfony\Component\Lock\Exception\ExceptionInterface` instead of the raw original exception? (same goes for evey stores (DBAL, Memcahced, ...)

**Comment by nesl247** [comment]
I'd be happy to open a PR for it. I'll add it to my todo.

**Comment by Simperfit** [comment]
@fabpot this can be closed
