### ISSUE TITLE
[Lock] ZookeeperStore:putOffEpiration throws exception

### ISSUE THREAD

**Issue by jderusse** [symfony/symfony#28696]
**Symfony version(s) affected**: master

**Description**  
The ZookeeperStore:putOffEpiration` method throws an exception (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Lock/Store/ZookeeperStore.php#L94) whereas Zookeeper locks forever.
The purpose of `putOffEpiration` is to extends the lifetime of a lock, by locking forever, the ZookeeperStore support the feature. 

**Possible Solution**  
 Instead of throwing an exception the store should do nothing like other stores (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Lock/Store/FlockStore.php#L111)

ping @GaneshChandrasekaran

**Comment by GaneshChandrasekaran** [comment]
Thank you raising this issue. I did initially have the implementation like you suggested. However, I revisited this when @nicolas-grekas had left feedback here:
https://github.com/symfony/symfony/pull/27920#discussion_r218733368

I checked the documentation of the `StoreInterface` and it expected this exception if the store didn't support it.
https://github.com/symfony/symfony/blame/master/src/Symfony/Component/Lock/StoreInterface.php#L44-L54

To me, this makes sense as well, that, if a store doesn't support a feature it should be marked as `NotSupported` instead of a `noop`.

The only place where this exception can be thrown from what I have seen is when you instantiate the lock with a `ttl`. And for this store, any client should leave the `ttl` as `null` anyway.

Another benefit of leaving this exception as is, is that, if in case, someone accidentally thinks that this store supports a `ttl` they will know due to this exception that a `ttl` value should not be set as it is not supported. 

I know this is not consistent with `FlockStore` and `SemaphoreStore`. If this reason works for you, we can probably fix those places for consistency. 

Let me know what you think!

**Comment by jderusse** [comment]
You're right.. this interface is confusing. 

Issue with throwing a `NotSupportedException` is that we don't know what is exactly not supported? 
- Does the store throws an exception because it does not supports defining an Expiration? 
- Or it does not supports extending an initial expiration?

By defining the interface, I was thinking about the second case. In my opinion, expiring lock is not a feature, it's a drawback, we don't care whether the store support putting expiration. What we care is: "is the store able to extends the expiration date". That's why other stores does not throws any exception.

For consistency, I suggest to:
- add a new NotExpirableStoreException (or a better name :-) )
- change the interface of putOffExpiration to documentate both exception
- catch and ignore NotExpirableException in Lock:refresh (and in CombinedStore::putOfExpiration too)

What do you think?

**Comment by GaneshChandrasekaran** [comment]
I like this idea. However, I have one question about your last point

- catch and ignore NotExpirableException in Lock:refresh (and in CombinedStore::putOfExpiration too)

Does `CombinedStore` support different types of `Stores` to store the lock? For example a `RedisStore` and a `PDOStore` at the same time? Because if not, then I would like to not handle `NotExpirableStoreException` as I would like the client to instantiate a lock correctly without a `ttl` and to avoid any misleading confusion.

**Comment by jderusse** [comment]
It's not usual, but yes it could be. 

For instance, if you have very heavy concurrency workers, you could imagine to combine a `SemaphoreStore` + a `RedisStore` with an `UnanimousStrategy`

The first store will avoid concurrency on the local host to reduce the load on Redis.


If none of the stores supports expirable lock, the CombinedStore could re-throw the exception

**Comment by GaneshChandrasekaran** [comment]
Great, thank you for the feedback. I will put up a PR soon for this then.

**Comment by Simperfit** [comment]
@jderusse I think this one can be closed
