### ISSUE TITLE
Option to disable the automatic 301 redirection without trailing slash

### ISSUE THREAD

**Issue by arneee** [symfony/symfony#29011]
**Description**  

> The automatic 301 redirection from /foo/ to /foo was introduced in Symfony 4.1. In previous Symfony versions this results in a 404 response.

This is a "magic" behaviour which can be unwanted in certain cases. For example it can [break AJAX calls via HTTPS](https://stackoverflow.com/questions/13556772/jquery-ajax-wont-make-https-requests).

There should be an option to disable this behaviour and enforcing strict URL matching on the route, without any magic redirects behind.

**Comment by nicolas-grekas** [comment]
I'm not sure the linked SO entry applies: the router doesn't redirect from https to http. And the top reply is right: you should fix your calls to send them to the correct URL. I'm not sure we should make the component more complex to support this option (I'm pretty sure we shouldn't actually ;) )

**Comment by arneee** [comment]
> I'm not sure the linked SO entry applies: the router doesn't redirect from https to http. 

In my case it did, since the smyfony app was called from a reverse proxy via HTTP, but the connection to the client was HTTPS.

> And the top reply is right: you should fix your calls to send them to the correct URL. I'm not sure we should make the component more complex to support this option (I'm pretty sure we shouldn't actually ;) )

The reason I don't like it is the "magic" behaviour. If you don't randomly see the part of the documentation, there is no reason to expect this. Since the redirect is not logged anywhere, you might only realize if it breaks suddenly for whatever reason (AJAX calls, API clients which don't support a redirect, etc).

**Comment by arneee** [comment]
Personally I don't like unexpected "magic" functions at all, in any case. For now I have used a compiler pass to revert to the "classic" UrlMatcher, but this is an ungly workaround.

`    public function process(ContainerBuilder $container)
    {
        $router = $container->getDefinition("router.default");
        $options = $router->getArgument(2);
        $options["matcher_class"] = 'Symfony\\Component\\Routing\\Matcher\\UrlMatcher';
        $options["matcher_base_class"] = 'Symfony\\Component\\Routing\\Matcher\\UrlMatcher';
        $router->setArgument(2, $options);
     }`

**Comment by xabbuh** [comment]
> In my case it did, since the smyfony app was called from a reverse proxy via HTTP, but the connection to the client was HTTPS.

Still, the request should be treated as secure by the application. Are you sure you properly configured the trusted hosts?

**Comment by arneee** [comment]
> > In my case it did, since the smyfony app was called from a reverse proxy via HTTP, but the connection to the client was HTTPS.
> 
> Still, the request should be treated as secure by the application. Are you sure you properly configured the trusted hosts?

Maybe I need to do some additional configuration on the Symfony side, but since the conenction from reverse proxy to symfony was "http", Symfony created a 301 redirect to "http://" which was not trusted by the client anymore.

**Comment by xabbuh** [comment]
And that's why it's important to properly tell Symfony about the reverse proxy as the proxy will send a special header telling the application about the secure connection allowing Symfony to treat the request as if it was actually encrypted.

**Comment by nicolas-grekas** [comment]
I would personally be OK to consider deprecating the redirection when the `Accept` header is present but doesn't contain `html`. I would keep the current behavior when the header is missing or when html is accepted. And I would not like to add an option to control this. More options mean more complexity, not worth it here IMHO.

**Comment by Nek-** [comment]
Just to add some more insights for this issue. Here is another use case: we want to hide some part of the application using a reverse proxy. This means we proxy `http://some.domain/` to `http://another.domain/custom/reserved/path`.

Depending on the proxy you use (basically: works with nginx, fails with haproxy) you may experiment redirection issue, because (and it's pretty logical) it transform `http://some.domain/` to `http://another.domain/custom/reserved/path/`, which leads to `http://some.domain/custom/reserved/path` (and 404 error, of course).

**Comment by B-Galati** [comment]
IMHO, no real issue here as it is all infrastructure related problems.

But it would be cool if one could opt-out from the trailing slash redirection for any reasons.
For example twitter support both URL without redirection; but the one without trailing slash is the canonical.

**Comment by arechsteiner** [comment]
I'm experiencing exactly what @Nek- described. My Symfony application returns a fully qualified redirect for the trailing slash and thus leads the user onto the origin server. The same happens for `redirectToRoute()` so I've opened a new issue: #29456 

The problem might just be the fact that Symfony insists on fully qualifying the redirect which makes the whole thing a lot less flexible for this kind of scenario.

**Comment by kgkg** [comment]
Can anyone explain me, why in my app there is FORCED to redirection from 127.0.0.1/foo to 127.0.0.1/foo/?
That makes running my middleware twice (before and after redirection). It's very annoing. There should be option to disable this behaviour, because simply many users DON'T WANT IT.

**Comment by COil** [comment]
Also notices this as it broke some tests. But they was redirections tests, so it's wasn't a problem. As the final destination URL was correct.

**Comment by enrico69** [comment]
Adding an optional parameter in the configuration would really add complexity? It would kind of keep the backward compatibility with some existing projects.

**Comment by nicolas-grekas** [comment]
I completely lost here: automatic redirection as described in the original description is expected and exists since early versions of the router component (before 2.3).
A deeper issue found early in the discussion was a mix of misconfigured trusted proxies.
Now, some of you report newly broken tests, which is unrelated to the original issue.
I think this issue has been hijacked to a point where it doesn't describe anything.
Closing as such. Please open specific issues if you want any follow up.
Before doing so, please check #29575 and #29673 which look similar.

**Comment by iquito** [comment]
As an addition to the <a href="#issuecomment-434035441">CompilerPass solution by @arneee</a> , which I used - for Symfony 4.3 it does not work anymore because of changes to the Routing component, so it needs to be modified to use `Symfony\Component\Routing\Matcher\CompiledUrlMatcher` (and setting `matcher_base_class` has no effect anymore, so it should be removed):

```php
public function process(ContainerBuilder $container): void
{
    $router = $container->getDefinition("router.default");
    $options = $router->getArgument(2);
    $options['matcher_class'] = CompiledUrlMatcher::class;
    $router->setArgument(2, $options);
}
```

Maybe that helps others to avoid my headaches of finding a solution ;-)

**Comment by sela** [comment]
> And that's why it's important to properly tell Symfony about the reverse proxy as the proxy will send a special header telling the application about the secure connection allowing Symfony to treat the request as if it was actually encrypted.

I also have the issue that I get 301 redirect from **https** to **http** did anyone manage to sort it out?
