### ISSUE TITLE
cache:clear fails after uninstalling monolog

### ISSUE THREAD

**Issue by ShariJoosten** [symfony/symfony#29025]
**Description**  
After uninstalling monolog with composer, composer tries to empty the cache. This will fail. Manually clearing the cache doesn't work either. It mentions the following as error:

```
[K0]
Script cache:clear returned with error code 255
[WARNING] Some commands could not be registered:

In srcProdProjectContainer.php line 693:
Class 'Symfony\Bridge\Monolog\Logger' not found
```

**How to reproduce**  
```
composer remove symfony/monolog-bundle
php bin/console cache:clear
```
It will then crash and mention it can not find monolog. 

**Possible Solution**  
Manually removing the entire cache directory with `rm -rf var/cache` works as a workaround.

**Comment by xabbuh** [comment]
I am afraid that this is one of the chiggen egg problems we cannot really solve. When the `cache:clear` command is executed, the old container is booted which still references the `Logger` class from the Monolog bridge which is no longer present. And since logging is an essential part of the application Symfony will soon try to use the `logger` service which cannot be built as the required class is missing.

**Comment by ShariJoosten** [comment]
Well, I guess in that case this topic can be closed. At least programmers who run across the same issue can now atleast quickly find a possible solution
