### ISSUE TITLE
[Form] Guesser/DataMapper: problem with nullable property on non-entity

### ISSUE THREAD

**Issue by ckrack** [symfony/symfony#29029]
**Symfony version(s) affected**: 4.1.6

**Description**  
When using a non-entity class as a forms ``data_class``, which contains a private ``DateTime`` property with nullable setter/getter (both typehints and default value for the setter), the field options are not correctly guessed.

**How to reproduce**  
Not really complex, but contains some files:
https://github.com/ckrack/symfony-form-datetime-guesser-bug

Browse to the index of the server to see the form.
The fields are correctly guessed as `DateTimeType` and displayed without populated date values in the text fields.
When submitting, the `TaskData::setDueDate()` method is throwing an `InvalidArgumentException ` because an empty string is passed.
This should be null.

It appears that the guesser is correct but the `DataMapper` does not know about the expected type.

**Possible Solution**  
I can fix the problem by changing the options manually and specifying the Type as `DateTimeType`

```diff
    // src/Form/TaskType.php

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
-           ->add('dueDate')
+           ->add('dueDate', DateTimeType::class, [
+                'required' => false,
            ])
        ;
    }
```

When using an Entity with Doctrine annotations instead of a DTO, and I have the following annotation:

`* @ORM\Column(type="datetime", nullable=true)`

The behaviour is also correct.
I don't know about the internals, but either there is a problem with the Guesser or with the connection between `Guesser` and `DataMapper`.

**Comment by yceruto** [comment]
Yeah, there is an inconsistency between `ValidatorTypeGuesser` and `DoctrineOrmTypeGuesser` for datetime field:

https://github.com/symfony/symfony/blob/f5939a83366e6839f48d4b281543d589fa46df52/src/Symfony/Component/Form/Extension/Validator/ValidatorTypeGuesser.php#L118

vs

https://github.com/symfony/symfony/blob/524bc4b039c32b3fa8c8276fb99aec2ec38eb30d/src/Symfony/Bridge/Doctrine/Form/DoctrineOrmTypeGuesser.php#L63

Possible solution: Remove the `input` option in `ValidatorTypeGuesser` and rely on the default value (currently `datetime`).

That is the cause of the error since the final data is transformed into a string when you expect `\ DateTime` or` null`.

**Comment by yceruto** [comment]
Another is when you use `@Assert\Type("\DateTime")`, it define a `DateType` field instead of `DateTimeType`:
https://github.com/symfony/symfony/blob/f5939a83366e6839f48d4b281543d589fa46df52/src/Symfony/Component/Form/Extension/Validator/ValidatorTypeGuesser.php#L100-L101

IMO both `@Assert\DateTime()` and `@Assert\Type("\DateTime")` should define the same form `DateTimeType` field, and `@Assert\Date()` for `DateType` fields.

**Comment by xabbuh** [comment]
I would remove the `DateTime` constraint. It's only useful when you want to check if a string is in a valid date and time format (and using it with `DateTimeInterface` instances will be deprecated in Symfony 4.2 anyway).

**Comment by ckrack** [comment]
> I would remove the `DateTime` constraint. It's only useful when you want to check if a string is in a valid date and time format (and using it with `DateTimeInterface` instances will be deprecated in Symfony 4.2 anyway).

That's true, however we should fix both the bugs mentioned by @yceruto, too.
These should be BC breaks, so maybe we can get this in a release along with #12018

**Comment by xabbuh** [comment]
IMO making this change now will be a BC break. We can do that in Symfony 5 where the `DateTime` constraint cannot be used with `DateTimeInterface` instances anymore.

**Comment by xabbuh** [comment]
Since the `ValidatorTypeGuesser` guesses the `input` option things will work differently. So it doesn't seem like there is anything to fix anymore and I am going to close here.

If you still think there is something to fix, please provide a small example application that allows to reproduce. Thank you for understanding.
