### ISSUE TITLE
[4.2] kernel getRootDir deprecation

### ISSUE THREAD

**Issue by COil** [symfony/symfony#29110]
**Symfony version(s) affected**: 4.2 beta 1

**Description**  
In 4.2 `$kernel->getRootDir()` is deprecated in favor of `$kernel->getProjectDir();` however they don't return the same path. In 4.1 I have to use `dirname` to get to the `composer.json` directory. In 4.2 the path is already correct.

**How to reproduce**  
//$rootDir = \dirname($kernel->getRootDir()); // <   Symfony 4.1
$rootDir = $kernel->getProjectDir();          // >=  Symfony 4.2

Please close this issue if it is the intended behavior. 

See you. COil

**Comment by stof** [comment]
this is indeed the intended behavior. `getProjectDir` is the root of the project (the place where you have your composer.json, which is likely to be the root of the git repo too). `getRootDir` was returning the directory containing the kernel source code, which means it was not a folder containing your source code (especially in the 3.x  structure where the kernel was in `app`)

Note that `getProjectDir` already exists since 3.3.

**Comment by COil** [comment]
Thanks @stof . Just wanted to be sure. Please close. ;)
