### ISSUE TITLE
[Workflow] Composer is complaining about dependencies regarding workflow and symfony

### ISSUE THREAD

**Issue by marioprudhomme** [symfony/symfony#29112]
**Symfony version(s) affected**: 3.2.9

**Description**  
Composer is complaining during install (not update) about dependencies between symfony and workflow, despite the fact that the same unchanged composer.lock file worked previously (2 days ago). 

**How to reproduce**  
Running `composer install` using this composer.lock file https://github.com/DigitalState/Cases/blob/83b65a06e458c8a9c5f16b4228f98eaa418b77c1/composer.lock

Gives this error https://travis-ci.org/DigitalState/Cases/builds/448045756#L1740

The following lists our builds results https://github.com/DigitalState/Cases/commits/master . The list was all green. Restarting any build in this list now gives an X, despite running the same composer install/code.

**Possible Solution**  
Not sure.

**Comment by xabbuh** [comment]
You cannot install `symfony/symfony` and `symfony/workflow` at the same time. This was a bug in Composer that mistakenly did not prevent the installation from succeeding and has been fixed in Composer 1.7.3 (see composer/composer#3754, composer/composer#7454 and composer/composer#7764 for more information about this).

**Comment by marioprudhomme** [comment]
All makes sense now. Thanks for quick response.
