### ISSUE TITLE
[Workflow] The workflow is un-deterministic when there a many transition with the same name

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#29140]
When many transitions have the same same, the workflow because un-deterministic. This is not cool.
It's impossible to build something really strong. How could the workflow guess what the dev intent?

I propose to update the interface:

```diff
- can(object $subject, string $transitionName)
+can(object $subject, Transition $transition)
- apply(object $subject, string $transitionName)
+apply(object $subject, Transition $transition)
```

I will add some helper to get the best transition for a transition name.

This will fix : 

* #28429
* #28432
* #28493
* #29137
* #28018
* https://github.com/symfony/symfony/pull/28007#issuecomment-40652420

**Comment by lyrixx** [comment]
Or another fix could be to forbid the use of the same transition name. 
I order to address the use case:

 > For example I regularly use an `update` transition for almost all states which does not change the state at all. If the same name must not exist mutliple times I would need to name them `updatewaiting`, `updateapproved`, etc. which seems clumsy

User could easilly leverage metadata

What do you think ?

Note: I think I prefer the last option because it's much more simple, the BC layer will be much more easier to achieve, and there will be less code

**Comment by stof** [comment]
Well, for a full-featured workflow, I think we already enforce transition name uniqueness.
For a state machine, we enforce uniqueness of transition names among transitions with the same starting point. Given the constraints put on state machines (the marking contains a single state, and transition have a single starting and ending state), this should not lead to any non-determinism.

If there are issues currently, they are not due to inherent non-determinism, but to implementation bugs (as the initial implementation had unique transition names, we may still have some code relying on this gone assumption)

**Comment by lyrixx** [comment]
> Well, for a full-featured workflow, I think we already enforce transition name uniqueness.

nope

> For a state machine, we enforce uniqueness of transition names among transitions with the same starting point.

yes.

> If there are issues currently, they are not due to inherent non-determinism, but to implementation bugs

Yes, may be ;) I'm trying to solve them ATM ;)

**Comment by lyrixx** [comment]
Closing this issue are @stof is right.
