### ISSUE TITLE
EntryManagerInterface is missing new functions

### ISSUE THREAD

**Issue by grahl** [symfony/symfony#29433]
**Symfony version(s) affected**: 4.2.0

**Description**  
The new functions add/removeAttributeValues from #21856 are not included in EntryManagerInterface, so they are not visible in auto-completion without a hint to EntryManager.

**Possible Solution**  
PR follows

**Comment by ro0NL** [comment]
Maybe we can leverage `@method` on the interface for these :)

see also  #28902

**Comment by mablae** [comment]
When I remember correctly @csarrazi  asked me to not include Interface methods on https://github.com/symfony/symfony/pull/27069 since the implementations were not final and completly stable. 

There's also some explanations in the PR that maybe still relevant? https://github.com/symfony/symfony/pull/27069#issuecomment-385371978

**Comment by csarrazi** [comment]
As mentioned in the other thread, the current methods are specific to PHP's `ldap` extension, and leak implementation details.
Though there have been little changes to the code since then, my view on the component has not changed. So if anyone wants to implement the suggested changes, that would be great.

Unfortunately, while I still perform code reviews occasionally, I no longer have time to contribute code to the Symfony project.

**Comment by nicolas-grekas** [comment]
Closing as advised by @csarrazi here and at https://github.com/symfony/symfony/pull/30043#issuecomment-461401299
PR welcome if you want to move this forward by implementing or discussing the suggestions he made.
