### ISSUE TITLE
[Framework-Bundle] Old template path usage

### ISSUE THREAD

**Issue by luxemate** [symfony/symfony#29466]
**Symfony version(s) affected**: symfony/framework-bundle@^4.0

**Description**
While fixing our assetic fork, I encountered that assetic doesn't see templates in %kernel.project_dir%/templates, which is recommended template location in 4.x. While debugging I ran into those files referenced below. And fixing them to use the correct path fixed our assetic fork, as it uses plain templating.locator and file_locator services. I'm aware that nobody cares about assetic today, because of encore, but I just want to make sure it's not a bug or something that was forgotten.

So, is there a reason, why in Symfony 4.2 these lines are still referencing the old template location directory (app/Resources/views)?

https://github.com/symfony/symfony/blob/c7fe1b6bcbb90874bcce78763e98584de9fc8238/src/Symfony/Bundle/FrameworkBundle/Resources/config/templating.xml#L26-L30

https://github.com/symfony/symfony/blob/c7fe1b6bcbb90874bcce78763e98584de9fc8238/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/TemplateFinder.php#L61

https://github.com/symfony/symfony/blob/c7fe1b6bcbb90874bcce78763e98584de9fc8238/src/Symfony/Bundle/FrameworkBundle/Templating/TemplateReference.php#L47

https://github.com/symfony/symfony/blob/c7fe1b6bcbb90874bcce78763e98584de9fc8238/src/Symfony/Bundle/FrameworkBundle/Resources/config/services.xml#L49-L55

**Comment by yceruto** [comment]
Actually those aren't old templates paths, but the paths that belong to the PHP templating layer, as well as the `TemplateFinder` class/service, hence these paths refer only to `%kernel.root_dir%/Resources/views`.

In the other hand, if you've installed/enabled the `TwigBundle` it's another history, the [`TemplateIterator`](https://github.com/symfony/symfony/blob/46fff8b4d71d4dfdf8c5cebc9611499c74cd58b3/src/Symfony/Bundle/TwigBundle/TemplateIterator.php#L22) [service](https://github.com/symfony/symfony/blob/0970b097962b3e0ceffc239454e20b11d2001cbd/src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml#L40-L45) is activated to find templates in all Twig paths (`templates/`, etc), which is expected if you've this config:
```yaml
framework:
    templating:
        engines: ['twig'] # add 'php' if you work with PHP templates
```
For Twig, this path `%kernel.root_dir%/Resources/views` has been deprecated since 4.2, but for PHP templates it's fine.

Currently, it's confusing have to deal with two templating engine in the same app. So I'd suggest remove the Templating component if you don't use PHP templates and also if any dependency of the app doesn't requires this component.

**Comment by luxemate** [comment]
@yceruto, thanks for detailed explanation. Of course, I forgot about PHP templating capability. Never used it, so didn't even think in that direction. Now it's clear that assetic used the framework bundle's locator as there was unified path previously.

I guess, there's nothing that could be fixed, so I'll close the issue.
