### ISSUE TITLE
[DependencyInjection] Error with Inline Services for ServiceLocator

### ISSUE THREAD

**Issue by ragboyjr** [symfony/symfony#29545]
**Symfony version(s) affected**: 4.2.0

**Description**  

Using the new php service configuration type, when I define an inline service for a ServiceLocator, I get an error when trying to access that service from the service locator.

Here's some code to show what I mean.

```php
$container->set('main_service', MainService::class)
    ->arg(0, ref('main_service.service_locator'));
// vs 
$container->set('main_service', MainService::class)
    ->arg(0, inline(ServiceLocator::class)->arg(0, [
        'key' => ref('sub_service')
    ]));

$container->set('main_service.service_locator', ServiceLocator::class)
    ->arg(0, [
        'key' => ref('sub_service')
    ]);
$container->set('sub_service', SubService::class);

// MainService
final class MainService {
    public function __construct(ContainerInterface $container) {
        $this->container = $container;
    }

    public function __invoke() {
        $subService = $container->get('key');
        $subService(new SomeMessage(1,2,3));
    }
}

// SubService

final class SubService {
    public function __construct(/* args */) {

    }

    public function __invoke(SomeMessage $message) {

    }
}
```

When using the inline service definition, when I access the $container->get('key') in the MainService

```php
$subService = $container->get('key');
```

The service locator will try to invoke the `SubService` definition with itself as the first argument. So instead of returning the configured sub service, I get an error message like:

```
Argument 1 passed to SubService::__invoke() must be an instance of SomeMessage, instance of Symfony\Component\DependencyInjection\ServiceLocator given, called in /var/www/html/api/vendor/symfony/contracts/Service/ServiceLocatorTrait.php on line 63
```

From what I can tell, the ServiceTrait class thinks the SubService service is a factory instead of an actual service. The error goes away if I don't use an inline service definition at all.

**Comment by nicolas-grekas** [comment]
This is not supposed to work: your root `main_service.service_locator` is correctly wired correctly because you must be using autoconfiguration. That means the `container.service_locator` is added to it automatically. Nested inline services cannot be autoconfigured - ie setting the tag is your responsibility. Right now, this inline definition is just a regular service definition: a ServiceLocator instance is created with an array of services as argument. But that's not what this class expects as argument (it should be a collection of callables.)

Two options to fix your config:
- add the tag to the inline service
- use the new `service_locator()` helper instead of `inline()`

**Comment by ragboyjr** [comment]
@nicolas-grekas Oh sweet, didn't see that service_locator helper, is that documented anywhere? I couldn't see it. If not, I can submit a docs pr for that.

Will try that out today and let you know how it goes.

**Comment by nicolas-grekas** [comment]
I'm not sure it's properly documented, your help would be welcomed!
