### ISSUE TITLE
Composer update don't limit version to expected one

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#29581]
**Symfony version(s) affected**: 4.0, 4.1 and 4.2

**Description**  
I want to create a project with 4.1.* Symfony version, and don't use any 4.2 package.
Same bug when i want to create a project with 4.0.* Symfony version.
This problem will be the same for 4.2, when 4.3 will be released.

**How to reproduce**  
```bash
composer create-project symfony/skeleton sf-4-1-9 4.1.9.1
```
(I have removed some dependencies to make output more readable)
```bash
Installing symfony/skeleton (v4.1.9.1)
  - Installing symfony/skeleton (v4.1.9.1): Downloading (100%)         
Created project in sf-4-1-9
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 20 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.1.8): Loading from cache

Prefetching 11 packages 🎶 💨
  - Downloading (100%)

  - Installing symfony/console (v4.1.9): Loading from cache
  - Installing symfony/dotenv (v4.1.9): Loading from cache
  - Installing symfony/routing (v4.1.9): Loading from cache
  - Installing symfony/http-foundation (v4.1.9): Loading from cache
  - Installing symfony/event-dispatcher (v4.1.9): Loading from cache
  - Installing symfony/debug (v4.1.9): Loading from cache
  - Installing symfony/http-kernel (v4.1.9): Loading from cache
  - Installing symfony/finder (v4.1.9): Loading from cache
  - Installing symfony/filesystem (v4.1.9): Loading from cache
  - Installing symfony/dependency-injection (v4.1.9): Loading from cache
  - Installing symfony/config (v4.1.9): Loading from cache
  - Installing symfony/cache (v4.1.9): Loading from cache
  - Installing symfony/framework-bundle (v4.1.9): Loading from cache
  - Installing symfony/yaml (v4.1.9): Loading from cache
```
4.1.9 is installed, with it's dependencies as 4.1.9 too.
But if i do this :
```bash
rm -rf vendor && composer up
```
Dependencies i don't have in my composer.json will be installed as latest version (4.2.1 today):
```bash
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 22 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.1.8): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.10.0): Loading from cache
  - Installing symfony/console (v4.1.9): Loading from cache
  - Installing symfony/dotenv (v4.1.9): Loading from cache
  - Installing symfony/routing (v4.2.1): Loading from cache
  - Installing symfony/http-foundation (v4.2.1): Loading from cache
  - Installing symfony/contracts (v1.0.2): Loading from cache
  - Installing symfony/event-dispatcher (v4.2.1): Loading from cache
  - Installing symfony/debug (v4.2.1): Loading from cache
  - Installing symfony/http-kernel (v4.2.1): Loading from cache
  - Installing symfony/finder (v4.2.1): Loading from cache
  - Installing symfony/filesystem (v4.2.1): Loading from cache
  - Installing symfony/dependency-injection (v4.2.1): Loading from cache
  - Installing symfony/config (v4.2.1): Loading from cache
  - Installing symfony/var-exporter (v4.2.1): Loading from cache
  - Installing symfony/cache (v4.2.1): Loading from cache
  - Installing symfony/framework-bundle (v4.1.9): Loading from cache
  - Installing symfony/yaml (v4.1.9): Loading from cache
```
I've tried to use `extra.symfony.require`, but it didn't change anything.

**Comment by stof** [comment]
`extra.symfony.require` is a feature implemented by `symfony/flex`. Running composer without having the Flex plugin installed will not apply the features of the plugin.

**Comment by stof** [comment]
There is 2 solutions here:

- install `symfony/flex` as a global plugin, so that it is always available when you run composer
- avoid removing the `vendor/symfony/flex` plugin if you need to clean part of the vendor folder.

Btw, you don't need to remove the vendor folder before running a `composer up`

**Comment by BoShurik** [comment]
You can run `composer install` before `update` to install `flex`
`rm -rf vendor && composer install && composer update`

**Comment by steevanb** [comment]
@stof I know I don't need to remove vendor dir before composer up / install. But for example, when i clone a project, and call composer update (and not install first), i have the problem.

Install Flex as global plugin is a good idea, but will not always work: you can't use official docker composer image for example.

@BoShurik Yes i can do that, but that's not "official": composer allow to update before install. If we can't do that anymore with Symfony ^4.0, i think you should add it to the installation documentation.

**Comment by stof** [comment]
Well, I don't see any other way. There is simply no way for Flex to customize the dependency resolution if Flex is not installed in your composer setup (as Composer could not know about Flex).

**Comment by steevanb** [comment]
I understand, but to me it's a problem, and it should be notified somewhere.

**Comment by nicolas-grekas** [comment]
This *might* be solvable at flex level but it's going to be tricky:

- Flex would need to detect when it has been just installed but didn't yet enforce `extra.symfony.require`. This should be "relatively simple" in a `POST_PACKAGE_INSTALL` hook.
- When this situation occurs, flex could disable all pending operations by calling:
`$composer->getInstallationManager()->addInstaller(new NoopInstaller());` which would terminate the current installation immediately in a proper way.
- Then, flex should hook into `POST_UPDATE_CMD`|`POST_INSTALL_CMD` to restart composer and do a "composer update" internally.

I'm closing this issue as this is a https://github.com/symfony/flex topic - and also because all has been said here.
Please reopen on that repo if you want this to be implemented (copy/pasting + linking this issue).

Since that's quite a challenge to implement (writing a composer plugin is always a challenge), I don't expect this to be fixed in the near future. Please prove me wrong ;)

**Comment by steevanb** [comment]
Ok, let's give it a try on Flex ( https://github.com/symfony/flex/issues/450 ) !
