### ISSUE TITLE
duplicated cache-control

### ISSUE THREAD

**Issue by tinect** [symfony/symfony#29595]
**Symfony version(s) affected**: 3.4.20

**Description**  
Due to session_cache_limiter, header "cache-control" is reported two times.

**Possible Solution** 
check with headers_list() if there is a cache-control-header at this point and replace it:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php#L125

**Additional context**  
![image](https://user-images.githubusercontent.com/135993/49951161-941c6200-fef9-11e8-81a0-3cd3df7c8d9c.png)

**Comment by nicolas-grekas** [comment]
That's not really an issue as it legal per the RFC, right?
Merging the headers before sending them might be difficult.
I'm closing therefore, please comment if you think this is really a bug.

**Comment by ilyachase** [comment]
Hi @nicolas-grekas while setting multiple `cache-control` headers if fine, it's only because its value is a list. From the [HTTP RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2):
> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)].

So it's more of an exception than a rule. Now the problem is that some Nginx versions (e.g. AWS ingress) complain about duplicate `Expires` headers (rightfully so, because its value is not a list). but Symfony does not take into account that the `session` module already set `Expires` header when setting it in `\Symfony\Component\HttpKernel\EventListener\AbstractSessionListener::onKernelResponse`:
```
$response
  ->setExpires(new \DateTimeImmutable('+'.$maxAge.' seconds'))
  ->setPrivate()
  ->setMaxAge($maxAge)
  ->headers->addCacheControlDirective('must-revalidate')
```

Because of the above, I think the `setExpires` must check if the header is already set (and remove it) using native PHP functions when setting a new value, otherwise, it violates the HTTP RFC. WDYT?

**Comment by nicolas-grekas** [comment]
We'd need a reproducer + a fix ideally. A dedicated issue if you cannot prepare a PR before ;)

**Comment by ilyachase** [comment]
Just a note for the future, probably a good place to dedup a header is here: https://github.com/symfony/symfony/blob/b28e597474cae687d4a0eb052a4c50819f1d65fc/src/Symfony/Component/HttpFoundation/Response.php#L338

**Comment by ilyachase** [comment]
So, while writing a reproducer I dug deeper and realized there's no issue (at least on the newest version and using native session), because:
* `cache_limiter` set to `0` at https://github.com/symfony/symfony/blob/f4666ceef4d59f384c31c9f452e95ef3520ec975/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1258
* Then it's applied using `ini_set` at https://github.com/symfony/symfony/blob/f4666ceef4d59f384c31c9f452e95ef3520ec975/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L341
* Which tells PHP not to set cache-related headers when starting the session
* So when Symfony sends response, there are no duplicate headers
