### ISSUE TITLE
Private service not injected anywhere is not found in test

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#29603]
**Symfony version(s) affected**: >=4.1

**Description**  
Symfony 4.1 [introduces a new container used in tests](https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing). It allows you to retrieve a private service. This is a really nice improvement. But it's in conflict with another feature: private services that are not injected are removed from the container.

In case you test a service using the new test container, it may result in "service not found exception". This case happens a lot in TDD development.

It may be understandable and an acceptable behavior (after all, that's what happen in your real application, the same behavior is expected when you get the container) but when you try to get the service in `debug:container` command, everything works without telling you the service will be removed! This is leading to a misunderstanding of what is happening and naturally, headache.

**How to reproduce**  

```php
// not used anywhere
class AwesomeService {}
```

```php
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
class AwesomeServiceTest extends KernelTestCase
{
    public testSomething()
    {
        self::bootKernel();
        $awesomeService = self::$container->get(AwesomeService::class);
    }
}
```

Result in:

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "AwesomeService" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

**Possible Solution**  

When I do `bin/console debug:container AwesomeService`, I should see in the table: `warning: this service is not injected and will be remove before runtime` or something like that.

**Comment by nicolas-grekas** [comment]
Definitely :+1: to update the command and make it clear the service has been removed.
We could even - by default - *not* list removed services and make `--show-hidden` display them with a notice?
PR welcome.

**Comment by Korbeil** [comment]
Could also think about some kind of configuration to not remove not injected services in dev/test ?

Actually we have a `config/packages/test/services.yml` that contains all classes we want to test on our project but I'm sure we can find a better work-around :wink:

**Comment by DonCallisto** [comment]
I'm willing to open a PR for this but I need some clarification.

https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php#L54-L64

Listed above we have all cases were we should (I think) apply this kind of modification (apart from `describeContainerParameter`).

What I don't understand is why, in every single case, `$builder->isCompiled()` returns `false` so as long as container isn't compiled, we can't retrieve inlined or removed services (feel free to correct me if I'm making wrong assumpion).

 So, my main question is: isn't builder compiled for perfomance issue (eg.: more reactive output as there's no reason to compile the container) or because is wrong to do so?
If we don't compile container we're not be able to retrieve this kind of info.

WDYT?

**Comment by nicolas-grekas** [comment]
The container has a method called `getRemovedIds()` that should allow building this. PR welcome.

**Comment by DonCallisto** [comment]
@nicolas-grekas I didn’t checked again the code but I’m pretty sure that if container is not compiled, and is not (see my last comment), there will no way to retrieve those informations.

**Comment by nicolas-grekas** [comment]
These commands deal with a local container created for the command itself and loaded from an XML description of services. This is the one you may be looking at. There is also the real container that can be accessed using DI. This one should contain the missing info.

**Comment by chalasr** [comment]
> We could even - by default - not list removed services and make --show-hidden display them with a notice?

The local container compiles without removing passes on purpose (for having removed/inlined definitions and aliases listed, https://github.com/symfony/symfony/pull/22385) which is useful for service discovery. Not sure about hidding them by default :)

**Comment by lyrixx** [comment]
Even is the service is injected somewhere, it's not possible to access it from the test env.
[Here is a simple reproducer](https://github.com/lyrixx/test/commit/3b240bc2a3f99bb51194cc9bd7476a9d2296d4ce)

I'm :+1: with this issue too. It very useful to access a service in test env to simplify the code.

**Comment by DonCallisto** [comment]
@lyrixx I'm not sure this issue is about accesing them from `test` env.
It's about list those services when they're stripped off the container.

**Comment by DonCallisto** [comment]
@nicolas-grekas 

> These commands deal with a local container created for the command itself and loaded from an XML description of services. This is the one you may be looking at. There is also the real container that can be accessed using DI. This one should contain the missing info.

https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/ContainerDebugCommand.php#L209-L213

I'm not sure I can access it from nowere. One solution could have been to check if `container` is compiled. If not, retrieve container in the same way we do in the linked snippet and pass the `removedIds` directly to the options. However this not seem to be a fitting solution because removed ids are not real options.

Maybe I'm missing something though

**Comment by chalasr** [comment]
See #31525
