### ISSUE TITLE
[Form] UrlType should be text when default_protocol is set

### ISSUE THREAD

**Issue by MatTheCat** [symfony/symfony#29690]
**Symfony version(s) affected**: all

**Description**

https://html.spec.whatwg.org/multipage/input.html#url-state-(type=url)

> The `input` element [represents](https://html.spec.whatwg.org/multipage/dom.html#represents) a control for editing a single [absolute URL](https://url.spec.whatwg.org/#syntax-url-absolute) given in the element's [value](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-value).

That means `default_protocol` is useless because its purpose concerns invalid values.

**How to reproduce**  

Display a `UrlType` field.

**Possible Solution**  

input type should be `text` when `default_protocol` is not `null` and `url` `inputmode` should be added.

**Comment by lmlsna** [comment]
Okay so:

#29926 = [Form] Changed UrlType input type to text when default_protocol is not null, and
#3879 = Force default_protocol to generate an url input

So now we are forcing a default protocol and then changing the type to text if there's a default protocol (which there always is because we force it). So this element never renders as a `type="url"` now. And because it writes to the $view var "type", we have no way to override that.

It doesn't make much sense to change a UrlType to a TextType, and the inputmode attribute was obsoleted in the WC5.2. If you just remove that bit, it works like all the other extended text types. Can I just send a PR that does this?
