### ISSUE TITLE
Transient tests hunting II

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony#29760]
Let's link travis/appveyor failures to this issue, and fix tests volatility.

**Comment by greg0ire** [comment]
About `ProcessTest::waitUntil()`:
- weird output assertion failure: https://ci.appveyor.com/project/fabpot/symfony/builds/21344209
- weirder output assertion failure: https://ci.appveyor.com/project/fabpot/symfony/builds/21344789#L1190
- process not even running: https://ci.appveyor.com/project/fabpot/symfony/builds/21344543

**Comment by greg0ire** [comment]
I suppose so, but good catch!

**Comment by greg0ire** [comment]
A Travis one, this time: https://travis-ci.org/symfony/symfony/jobs/474903064#L3987

<details>

```
Symfony\Component\Process\Tests\ProcessTest::testUpdateStatus
Failed asserting that 0 is greater than 0.
/home/travis/build/symfony/symfony/src/Symfony/Component/Process/Tests/ProcessTest.php:588
```

</details>

**Comment by stof** [comment]
> Even weirder output assertion failure: https://ci.appveyor.com/project/fabpot/symfony/builds/21344789#L1190

is this a transient one, or always failing ? If it is always failing, it might be related to newline chars

**Comment by stof** [comment]
> Another one about PHPUnit: https://ci.appveyor.com/project/fabpot/symfony/builds/21322425

that one is a bug in the phpunit-bridge due to the refactoring to `composer create-project`.
In some cases, the bridge decides to reinstall PHPUnit even though it is already there (I think it is when the bridge script itself is edited). But it does not remove the existing version. The old code was fine with it. The new code is not (composer refuses to override existing content when creating a project).

**Comment by greg0ire** [comment]
The weirder output is super transient, I saw it once and that's it

**Comment by javiereguiluz** [comment]
I'm closing this one as "fixed" because lately tests are green again on all branches. Thanks!
