### ISSUE TITLE
Error in PostAuthenticationGuardToken::serialize because of bug in PHP 7.3

### ISSUE THREAD

**Issue by toooni** [symfony/symfony#29951]
**Symfony version(s) affected**: 2.8.0-4.2.2 (ONLY with PHP 7.3+)

**Description**  
A bug in PHP7.3 (https://bugs.php.net/bug.php?id=77302) which was also discussed in https://github.com/symfony/symfony/issues/29459 creates an issue where an object (sometimes?) cannot be serialized twice.
This is what happens in `PostAuthenticationGuardToken::serialize` / `PostAuthenticationGuardToken::unserialize`:
```
    public function serialize()
    {
        $serialized = serialize(array($this->providerKey, parent::serialize()));

        return $serialized;
    }

    public function unserialize($serialized)
    {
        list($this->providerKey, $parentStr) = unserialize($serialized);

        parent::unserialize($parentStr);
    }
```

Which results in an error `Notice: unserialize(): Error at offset x of y bytes` when using symfony guard.

**How to reproduce**  
See https://bugs.php.net/bug.php?id=77302

**Possible solution**
I don't know how to fix this without a BC break. Since it's basically a PHP bug only affecting some users I also don't know how to proceed.

**Comment by nicolas-grekas** [comment]
I'm not sure we can do anything in Symfony itself, this is a PHP 7.3 bug.
Ping @nikic we might need your help here,  https://bugs.php.net/bug.php?id=77302 is affecting many apps...

**Comment by nicolas-grekas** [comment]
Another reason to deprecated `Serializable` btw. See https://gist.github.com/nicolas-grekas/34e2b51c1998456d38d0d192ef30d2c6

**Comment by nikic** [comment]
I don't believe we can do anything on the PHP side either, short of introducing a new serialization mechanism. I believe that the only change here in PHP 7.3 is that it has some stricter validation, which makes unserialization fail rather than silently returning bogus data.

If you use the Serialization interface, you need to write your code in a way that invokes serialization / unserialization in the same order. That generally means that `parent::serialize()` is a no-go. If you can rewrite this code without using `parent::serialize()`, that should "resolve" this issue.

**Comment by nicolas-grekas** [comment]
Thanks for the details, let's see what we can do then. That's highly unexpected but I understand there are valid technical reasons.
Can we get serious about deprecating Serializable and introducing `__serialize(): array / __unserialize(array $data): void` instead?
I know you already suggested this, and I tried building some draft proposal on top.
PHP 7.4 need that better design so that PHP 8 can drop `Serializable` altogether...
We'd need your help here :)

**Comment by toooni** [comment]
An easy solution would be to make the properties in `Symfony\Component\Security\Core\Authentication\Token\AbstractToken` protected instead of private and use them in `PostAuthenticationGuardToken` to serialize/unserialize only once.
But a BC break seems inevitable. `serialized`, stored tokens would always have to be regenerated in php <7.3 with the new solution before being able to migrate to php >=7.3.

**Comment by nikic** [comment]
@nicolas-grekas Okay, I'll try to create an implementation and RFC for a new serialization mechanism sometime soon.

**Comment by nicolas-grekas** [comment]
@nikic awesome thanks, keep me posted if you want any feedback!

**Comment by nicolas-grekas** [comment]
After some history, this bug is "known" since 2013, but hidden in #9806

**Comment by nikic** [comment]
As another possibility for working around this:

```php
    public function serialize()
    {
        $s1 = serialize($this->providerKey);
        $s2 = serialize(parent::serialize());
        return bin2hex($s1) . ',' . bin2hex($s2);
    }

    public function unserialize($serialized)
    {
        list($s1, $s2) = explode(',', $serialized);
        $this->providerKey = unserialize($s1);
        parent::unserialize($s2);
    }
```

This avoids the nested serialization and allows the serialize and unserialize calls to happen in the same order.

**Comment by nicolas-grekas** [comment]
I've just prototyped a working patch based on an optional argument "bool $isCalledFromOverridingMethod Must be set to true when called from an overriding method".

When set, the serialize method return an array.
When not provided, $isCalledFromOverridingMethod is computed from the backtrace.

"unserialize" then just checks with `is_array` whether it should call "unserialize" on its argument or not.

Works like a charm. PR coming soon.

**Comment by nicolas-grekas** [comment]
Here is the PR implementing the strategy I mentioned: #30006
For master, we should seek for a better design and deprecate extending serialize/unserialize (eg making them `@final` in 4.3 and really final in 5.0), but for branches in maintainance-only mode, that should do it.
