### ISSUE TITLE
[Twig][Bootstrap 4 Theme]: Displaying errors like in official docs

### ISSUE THREAD

**Issue by FlashBlack** [symfony/symfony#29986]
**Symfony version(s) affected**: 4.2.2

**Description**  

As for me, error displaying is much prettier with official bootstrap v4 [component/forms](https://getbootstrap.com/docs/4.2/components/forms/#supported-elements).

**How to reproduce**  
1. config/packages/twig.yaml in "form_themes" put bootstrap_4_(horizontal)_layout.html.twig
2. Create a form, cause a validation error

**Possible Solution**  
MR: https://github.com/symfony/symfony/pull/29987

**Additional context**  

_Currect views:_
![2](https://user-images.githubusercontent.com/915531/51765580-34fd6000-20e9-11e9-953e-2a59ba08d487.jpg)
Horizontal: ![2_hor](https://user-images.githubusercontent.com/915531/51765581-34fd6000-20e9-11e9-8a9b-0c0b8445fb62.jpg)

_Proposed:_
![1](https://user-images.githubusercontent.com/915531/51765587-39297d80-20e9-11e9-9497-459b821c32db.jpg)
Horizontal: ![1_hor](https://user-images.githubusercontent.com/915531/51765588-39297d80-20e9-11e9-89f3-4b3fa5323e02.jpg)

**Comment by stof** [comment]
Rendering the errors as part of the label was done in an effort to improve accessibility (the `ERROR` prefix was also part of that).
This indeed does not play well with the horizontal variant.

And putting the error in the place where Bootstrap expects it to be also makes sense from a compatibility point of view (we have no guarantee that our "hacked" usage of Bootstrap will keep working fine in future updates)

@Nyholm as you were the one doing that change in https://github.com/symfony/symfony/pull/24435 (and the related PR is essentially a revert of that one), could you participate here ?

**Comment by mmarton** [comment]
I've already tried and failed with this. :( I hope you will have better luck
**https://github.com/symfony/symfony/issues/26461**

**Comment by vudaltsov** [comment]
I experienced troubles with errors in labels too. First of all because all of a sudden `{{ form_widget() }}` and `{{ form_label() }}` started working differently around some `3.4.x` patch release which was kind of a BC break to be honest (see https://github.com/symfony/symfony/pull/24435/files). Second because my form layout became worse in places where invalid forms' labels were not supposed to expand occasionally. Finally I just created my own layout which I reuse in all projects using Bootstrap.

While I am certainly thumbs up for accessibility in general, I am not sure that Symfony should change how Bootstrap is designed. If I choose Bootstrap as a front-end library and use Symfony's BS form templates, I expect everything to work according to the BS documentation. It means that I accept how BS approaches layout and accessibility and other problems. That's my choice. If I want to make my forms more accessible, I should replace some twig blocks or choose another front-end framework or create an issue in https://github.com/twbs/bootstrap. By default I want to see everything working according to BS docs and defaults because Symfony is supposed to provide a Twig**Bridge** for Bootstrap, not an opinionated modified version.

**Comment by javiereguiluz** [comment]
@vudaltsov I fully agree with you. Moreover, anyone that reads Bootstrap docs can see that they care about accessibility a lot ... so their current approach it's probably pretty (or fully) accessible and we don't need to change it.

**Comment by mmarton** [comment]
I don't have a problem with symfony having it's own opinionated layout. Just don't name it bootstrap3/4 layout.

**Comment by xabbuh** [comment]
I am closing here as we already have #28086 which is the same.
