### ISSUE TITLE
[RFC] [DI] Functional Service Support

### ISSUE THREAD

**Issue by ragboyjr** [symfony/symfony#29997]
A somewhat common pattern seen among the PHP community is making final classes with one method `__invoke` like so:

```php
final class DoSomething {
  public function __constructor(/* args */) {
     // set args
  }
  public function __invoke(): void {
    // do something
  }
}
```

Semantically, this is equivalent to the following done with functions and closures:

```php
function doSomething(/* args */) {
  return function() use (/* args */): void {
    // do something
  };
}
```

I'd like to discuss ways in which we could make the latter (functional service) easier to use in a symfony application.

The former pattern I think emerged in PHP rather than the latter due to PSR-4 composer autoloading defaults and the fact that most autowired di frameworks (like SF DI) use the class name to wire dependencies.

However, using the function/closure definition is much more terse, and allows you to easily include multiple related services into one file.

## Example

With SF's new php fluent container configuration, i've been able to make use of functional services relatively pain free with the help of a few helper functions and abusing the php lexer.

```php
// src/services.php

namespace App;

const serviceA = serviceA::class;
function serviceA(callable $serviceB) { // $serviceB is autowired
   return function() use ($serviceB) {}; // does stuff
}

const serviceB = serviceB::class;
function serviceB(Psr\Log\LoggerInterface $logger) {
     return function(): int {}; // does stuff
}
```

```php
// src/util.php

namespace App;

/**
 * Registers a service that is a function which returns a closure. If a suffix is applied, the function name is suffixed with `.{suffix}`
 */
function fnService(AbstractServiceConfigurator $container, string $fnName, ?string $suffix = null, ?string $bindName = null): ServiceConfigurator {
    $serviceId = $fnName . ($suffix === null ? '' : '.' .$suffix)
    $container->set($serviceId, 'Closure')->factory($fnName);
    if (!$bindName) {
        $parts = explode('\\', $fnName);
        $bindName = end($parts);
    }

    $container->bind($bindName, ref($serviceId);
}
```

```php
// config/services.php

use App;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use function App\fnService;
use function Symfony\Component\DependencyInjection\Loader\Configurator\ref;

return function($configurator) {
  $container = $configurator->services()
    ->defaults()->autowire()->autoconfigure()->private();

  fnService($container, App\serviceA);
  fnService($container, App\serviceB);
};
```

## Desired Outcomes

I'd be real stoked to see if we could do something like `$container->fn()` which is basically my implementation of `fnService`.

I'm also very open to ideas of how we could possible make this even more robust.

As far as dealing with the pain of having to register non-psr4 files into the `files` section of the composer.json, that can be mitigated with a composer plugin like: https://github.com/krakphp/php-inc.

**Comment by xabbuh** [comment]
Same as #28992?

**Comment by stof** [comment]
The main drawback of using functions rather than classes is that you cannot autoload them. Anything you put in the `files` section of composer (or that you add in this `php-inc` plugin, as it works the same) is always loaded at the beginning of the request (see the drawback section of the plugin). Loading unused code (even optimized by OPCache) has a performance cost (this is why the compiled container now generates separate files for the instantiation of most services instead of generating a single huge file).

Thus, I don't even think that a named function returning a closure having access to the dependencies passed to it is actually more readable than an invokable class (and it still does not prevent you from finding a name for your factory function).

**Comment by stof** [comment]
@xabbuh no, not the same. In this request, the service itself is an anonymous callable, created by a named factory. #28992 is requested the support of anonymous functions as factory for services.

**Comment by ragboyjr** [comment]
@stof Understood, your points are valid, this feature might make more sense if php had the ability to autoload functions.  Wanted to bring it up in case this made sense to others as well, or if possibly there were better ideas to support such a thing.

**Comment by ProtonScott** [comment]
What one could do however is have a macorable class that lets you easily bind differ untitled functions together and have some sort of invocation hook. Laravel has a dead simple implementation of it here: 

[Laravel Macorable Trait](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Support/Traits/Macroable.php)

You could extend this idea a number of ways: for instance:

Parsing out macros from a macro.yaml file using expression-language. You might get some good caching out of this (unsure if that would be supported )

Simply require a functions.php at runtime (this you can do and functions can be namespaced to avoid collisions) like when one loads bundles but just part of the kernel process (don’t see how this would be an issue per day)

I’m interested in something like this for passing utitlies without having to go through and get a ton of classes created for the purpose

**Comment by jkufner** [comment]
It is possible to use autoloader with functions. The trick is to use a class :)

`````php
class DoSomething {
    public static function createFactory(/* args */) {
        return function() use (/* args */): void {
            // do something
        };
    }
}
`````

However, I'm not sure if it is a good idea. Passing callables around is problematic because PHP cannot type-hint them properly (it is not possible to specify arguments in the type hints). I think that the little bit of verbosity is not that bad regarding readability and understandability of the code. While the factory may look more compact, code using such a factory is likely to be more difficult to understand.

**Comment by ragboyjr** [comment]
@ProtonScott I'm not 100% sure how your example would work, can you give some specific examples?

**Comment by ProtonScott** [comment]
@ragboyjr Absolutely I'd be happy to.

As a side note: [Composer Can Autoload Functions](https://getcomposer.org/doc/04-schema.md#files) so I'm not sure if that makes any difference here. There's no real reason we could not state in the documentation that to use a function as a service (FAAS!) that you must include it in the composer.json,

I think from there it would be much more simple to work with.

Anyways, as a discreet alternative, using the Macroable class (and I'm assuming, for the sake of argument, the Macroable class would be included in symfony/framework-bundle) you could have a functions.php that looks like this:

```php
$funcs = [
  'callback' => function (string $echo) {
    echo $echo;
  },
];

return Symfony\Component\Macroable\Macroable::addFuncs($funcs);
```

Now, you have an array of functions that are defined (the name of the function being the key),

So that can be handled, more or less like it is [here](https://github.com/laravel/framework/blob/master/src/Illuminate/Support/Traits/Macroable.php#L73)

Now thanks to something like this being a class that handles the registered functions at runtime (not unlike how the Kernel handles bundles), you could do something like this:

```yaml
services:
  App\Functions\UsefulFunc:
     # ...
     calls:
       - method: callback
       - arguments: 'Hello World'
```


This is a very basic example of what I was thinking (it could use a little more fleshing out, but I hope you get the basic idea of what I am going for here)

Effectively you just create a function registry.

**Comment by ragboyjr** [comment]
Ah, ok, i think I understand what you're talking about. App\Functions\UsefulFunc would be a faux class that is handled via the Macroable class which resolves to the `callback` closure defined in the `$funcs` array.

Is my understanding correct?

**Comment by ProtonScott** [comment]
@ragboyjr Yup (an alias basically), an alternative of course would be to just call it directly against the Macro class like so:

```yaml
services:
  app.some.service:
     # ...
     calls:
       - method: Symfony\Component\Macroable\Macroable::callback
       - arguments: 'Hello World'
````

or you could use an interface to define it (for contracts)

```yaml
services:
 App\Contract\CallBackInterface:
     # ...
     calls:
       - method: Symfony\Component\Macroable\Macroable::callback
       - arguments: 'Hello World'
````

I would of course be curious if there is anything preventing the autoload via composer from calling in directly as I linked to before. That would certainly simplify this whole affair even further.
