### ISSUE TITLE
Check that we are not using features deprecated in PHP 8

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#30036]
**Description**  
PHP 8 won't be released anytime soon, but it has already removed a lot of features, functions, settings, etc. that were deprecated in PHP 7.2 and 7.3.

We probably don't use many (any?) of these, but to make our code future-proof we should check this comprehensive list: https://github.com/php/php-src/pull/3770

**Comment by stof** [comment]
Well, if they haven't messed up with triggering `E_USER_DEPRECATED`, we should already be fine, as any `E_USER_DEPRECATED` would be detected by our testsuite (and by the profiler in dev).

**Comment by javiereguiluz** [comment]
Not sure about that. For example, in our Yaml component code we have code like this: `... & (int) ini_get('mbstring.func_overload')`  but `mbstring.func_overload` no longer exists in PHP 8.0.

**Comment by stof** [comment]
Well, our YAML component does not rely on `mbstring.func_overload`. It makes sure to keep working when you use that feature.

AFAICT, `ini_get` does not break for unknown settings (otherwise, the YAML component would already be broken if mbstring is not loaded), and so this code would simply never enter inside the code running only when the `mbstring.func_overload` feature is used.
Deleting that code will only be possible when PHP 8 is our min version (so that our code cannot run on a runtime having `mbstring.func_overload` enabled).

**Comment by nicolas-grekas** [comment]
I'm closing as PHP8 is a remote and moving target. Test suite will tell us where we'll need to update, as done for previous versions.
