### ISSUE TITLE
Show stack trace of Doctrine query

### ISSUE THREAD

**Issue by iluuu1994** [symfony/symfony#30040]
**Description**  

When a page executes too many queries it would be extremely useful to know where these queries are executed. Since these queries are generated by Doctrine it is very non-obvious where they are coming from.

**Example**  

![image](https://user-images.githubusercontent.com/1752683/51982533-92e9c900-2496-11e9-92c1-fc0e824ee39c.png)

I would add another toggle "Show stack trace" that shows you exactly where the query was executed in your code.

**Comment by javiereguiluz** [comment]
@iluuu1994 I agree that this would be great. However, it seems that Doctrine DBAL is not ready for this. Check https://github.com/doctrine/DoctrineBundle/issues/722 (and duplicated issues like https://github.com/doctrine/DoctrineBundle/issues/800).

So, I must close this and I hope that one day this is fixed in Doctrine and leveraged in DoctrineBundle. Thanks.

**Comment by iluuu1994** [comment]
@javiereguiluz Thanks for investigating!

> [DBAL already has a DebugStack logger doing this](https://github.com/doctrine/DoctrineBundle/issues/800#issuecomment-380903730)

Is this not an option?

**Comment by javiereguiluz** [comment]
Sadly that's not an option. The Doctrine data collector used in DoctrineBridge is already using it. However, as you can see in its code (https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Logging/DebugStack.php) it doesn't log who/where the query was executed. That's why we don't have that info in the data collected by Symfony:

![symfony-demo-doctrine-collector](https://user-images.githubusercontent.com/73419/52062268-7de16880-2570-11e9-8b16-e97db870bf87.png)

**Comment by iluuu1994** [comment]
Bummer. Anyway, thanks @javiereguiluz!

**Comment by alcaeus** [comment]
Just to follow up, this was added in https://github.com/doctrine/DoctrineBundle/pull/954 and will be released in version 1.11.0 of the Doctrine Bundle 👍

**Comment by iluuu1994** [comment]
*Hype!* Thanks @ottaviano and @alcaeus!

**Comment by mayro** [comment]
Hello @alcaeus,
I'm using doctrine 1.11.2 and i haven't this profiling, i have only the query...

**Comment by stof** [comment]
@mayro due to the performance impact (it increases memory usages of the collected queries), you need to opt-in in your DoctrineBundle config (see `profiling_collect_backtrace`). It is turned off by default.

**Comment by mayro** [comment]
Thanks @stof  i enable the profilning_collect_backtrace, I can now trace the steps but anyway it doesn't log where the query was executed...

**Comment by stof** [comment]
"in which connection of the Master/Slave" is not the same question than "where in the project", which is what a debug backtrace provides.

**Comment by mayro** [comment]
@stof  Thank you for clarifying that. so is there any way to know in which connection (Master or slave) the query was executed please ?
