### ISSUE TITLE
How to correctly use probabilistic early expiration in Redis

### ISSUE THREAD

**Issue by wangbourne** [symfony/symfony#30066]
I tried to use following approach

1
```
        $callback = function ($returnedValue) {
            return $returnedValue;
        };


        $cache = new RedisCache(RedisAdapter::createConnection('redis://localhost:6379'));

        $cache->set('stats.products_count',"xbox");
        $productsCount = $cache->get('stats.products_count', $callback, INF);

```

2
 ```
$callback = function ($returnedValue) {
            return $returnedValue;
        };

        $redis = RedisCache::createConnection(
            'redis://localhost:6379'
        );


        $redis->set('stats.products_count',"xbox123");
        $productsCount = $redis->get('stats.products_count', $callback, INF);
```

But both are NOT right. Appreciate if somebody could provide some example

I'm using: 
Symfony CLI version 4.2.8

**Comment by dmaicher** [comment]
Seems passing `INF` will force immediate expiration?

https://symfony.com/blog/new-in-symfony-4-2-cache-stampede-protection

**Comment by wangbourne** [comment]
For the second case, it comes following error, which indicate get method does accept multiple parameters.  It seems RedisCache does not probabilistic early expiration yet.

![image](https://user-images.githubusercontent.com/2090084/52176563-36710b80-2800-11e9-943a-abbd10c551a2.png)

**Comment by nicolas-grekas** [comment]
To use early expiration, you must not call set().
You must also fix your callback: it should return the computed value.
And you should not pass INF as this forces immediate expiration, which means never using the cache.
Without more details, that's all we can say here.
Does that help?

**Comment by wangbourne** [comment]
@nicolas-grekas 
I'm following the page to create a controller: https://symfony.com/doc/current/page_creation.html .
Below is the complete code for this new controller.

```
<?php
// src/Controller/LuckyController.php
namespace App\Controller;

use Symfony\Component\Cache\Simple\RedisCache;
use Symfony\Component\HttpFoundation\Response;

class LuckyController
{
    public function number()
    {
        $callback = function ($returnedValue) {
            return $returnedValue;
        };

        $redis = RedisCache::createConnection(
            'redis://localhost:6379'
        );

        $productsCount = $redis->get('stats.products_count', $callback);


        return new Response(
            '<html><body>Redis get key: '.$productsCount.'</body></html>'
        );
    }
}

```

Run `php bin/console server:run` and hit the page of `http://localhost:8000/lucky/number`, then i got above error.

My key point is:  seem `$redis->get` does not accepts above way.

**Comment by nicolas-grekas** [comment]
Sorry there is a mix of misunderstandings here, due to lack of doc I suppose (that's on my list...)
`RedisCache` doesn't support early expiration - actually *no* driver in the `Simple` namespace support them.
But *all* adapters in the `Adapter` namespace support it, eg `RedisAdapter`.
Then: `RedisAdapter::createConnection()` returns a Redis ... *connection* - ie *not* a cache adapter.
Which means you might be looking for `new RedisAdapter(RedisAdapter::createConnection(...));`

Then the callback really needs to *compute* `$returnedValue` - ie it cannot take it as argument.
See https://github.com/symfony/symfony/blob/master/src/Symfony/Contracts/Cache/CallbackInterface.php for some details about the signature of the callback.

I'm closing this issue since this tracker is for bug reports only.
I invite you to go to https://symfony.com/support to ask for help to the community.
