### ISSUE TITLE
HttpKernel *HttpException should depend on HttpResponse constants

### ISSUE THREAD

**Issue by Geolim4** [symfony/symfony#30072]
**Symfony version(s) affected**: 3,4

**Description**  
Currently HttpKernel *HttpException are hardcoding statusCode in child constructor.

**How to reproduce**  
Not reproducible as it's part of the current code

**Possible Solution**  
As httpKernel depends on HttpFoundation, those statusCode should refer directly to HttpFoundation/Response class constants.

**Additional context**  
N/A

**Comment by javiereguiluz** [comment]
@Geolim4 thank you for your proposal! Sadly, I'm afraid this has been proposed in the past (see for example https://github.com/symfony/symfony/pull/22023) and rejected because of the reason given in https://github.com/symfony/symfony/pull/22023#issuecomment-287073577

So, we must close this as "won't fix". I'm sorry.
