### ISSUE TITLE
Undescore in property name cannot be normalized

### ISSUE THREAD

**Issue by degregar** [symfony/symfony#30082]
**Symfony version(s) affected**: 4.2.2

**Description**  
I've added property with underscore in the name and after normalization the property was not there. 

**How to reproduce**  
make:entity
add new property with underscore, for example: "sender_collapse"
try to normalize it

**Possible Solution**  
I've found, that in vendor\symfony\property-info\Extractor\ReflectionExtractor.php method getAccessorMethod checks if there is method in entity class that is called as property name with underscore (for example getSender_collapse()) which I didn't have, because make:entity command generates methods without underscores.

Of course symfony recommends to use camelCase for variables, functions, methods, but I haven't found to written explicitly I had to use camelCase for entity properties as well.

I've changed my entity properties to camelCase and it worked.

I think there should be either warning while trying to add property with underscore make:entity or generating scheme with doctrine or a fix for generating proper property names for ReflectionExtractor class.

**Additional context**

**Comment by ktherage** [comment]
@degregar 
IMO it is not needed, doing this change will lead people to introduce bad practices into their code and, if we do this, some may ask for properties with dashes others with dots and we'll never end it.

Moreover, as you say :
> Of course symfony recommends to use camelCase for [...] **methods**

And so, if you define proper "camelCased" getters, setters, issers or hassers then this will work as expected.
Here is an exemple : 
```php
<?php
require 'vendor/autoload.php';

use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class Test {
    private $property_with_many_underscores = "test";

    public function getPropertyWithManyUnderscores()
    {
        return $this->property_with_many_underscores;
    }

    public function setPropertyWithManyUnderscores($property_with_many_underscores)
    {
        return $this->property_with_many_underscores = $property_with_many_underscores;
    }
}

$normalizers = [new ObjectNormalizer()];
$serializers = new Serializer($normalizers);

$normalized = $serializers->normalize(new Test);
dump($normalized);
// prints :
// array:1 [
//   "propertyWithManyUnderscores" => "test"
// ]

$denormalized = $serializers->denormalize($normalized, Test::class);
dump($denormalized);
// prints :
// Test^ {#124
//   -property_with_many_underscores: "test"
// }
```

The unique difference in this case is that you have `propertyWithManyUnderscores` after normalization instead of `property_with_many_underscores` and even in this case you can configure it (https://symfony.com/doc/master/components/serializer.html#configure-name-conversion-using-metadata).

**Comment by jewome62** [comment]
You say
> symfony recommends to use camelCase for variables, functions, methods, 

But is not Symfony but into [PSR-1: Basic Coding Standard](https://www.php-fig.org/psr/psr-1/)

**Comment by xabbuh** [comment]
I am closing here as I don't think that we will add support for this as explained. Thank you for understanding.
