### ISSUE TITLE
[Security] Add an ability to detach user from TokenStorage

### ISSUE THREAD

**Issue by sam0delkin** [symfony/symfony#30141]
**Description**  
The main issue that caused was described in https://github.com/stof/StofDoctrineExtensionsBundle/issues/373 , but after some thinking, I decided that the best & universal solution would be to allow TokenStorage be marked as unmanaged/detached (maybe, via EventDispatcher). So, this way any Component/Code may listen to this event and update Token data if it becomes detached somehow.

**Example**  
Example from the original issue, which uses Doctrine2, FOSUserBundle and StofDoctrineExtensionsBundle:
Assume i have an entity:
```php
namespace Some\Bundle\Entity\Post;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Some\Bundle\Entity\User;

/**
 * Post
 *
 * @ORM\Table(name="post")
 */
class Post
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    // ...

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="Some\Bundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     *
     * @Gedmo\Blameable(on="create")
     */
    protected $user;
```

and somehwere in code:
```php
// here i have an IS_AUTHENTICATED_FULLY role.
$post1 = new Post();
$em->persist($post1);
$em->flush(); // <-- here post will be created successfully, and user relation will be set
$em->clear(); // user in token storage and in blameable listener becomes unmanaged
$post2 = new Post();
$em->persist($post2);
$em->flush(); // <-- here would be an exception listed below
```
Exception:
```
A new entity was found through the relationship 'Some\Bundle\Entity\Post#user' that was not configured to cascade persist operations for entity: Some User. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})
```

**Comment by fancyweb** [comment]
I think it is your responsability to merge the detached `User` entity back in the UoW, and to set the new managed instance in the `TokenStorage`. 

Moreover, the `TokenStorage` or the token itself cannot be marked as unmanaged/detached because it is a Doctrine concept, and the token does not have to be a Doctrine entity.

**Comment by linaori** [comment]
The problem here is that you store an entity in the Token instead of a Data Transfer Object, see: https://stovepipe.systems/post/decoupling-your-security-user

In the "near" future I'd like to work out a system that completely removes the `UserInterface` from the Token, where it would only be used during the authentication process, but this will probably get some resistance.

**Comment by sam0delkin** [comment]
But even in Doctrine Bridge user is just loading via simple Doctrine repository [call](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php#L51). Maybe i addressed issue wrong (so, possible should be addressed into Doctrine Bridge)? and @linaori +1 for a DTO. But even in FOSUserBundle official doc, they saying that Doctrine user should extend their UserModel (which implements UserInterface), see [this](https://symfony.com/doc/current/bundles/FOSUserBundle/index.html#a-doctrine-orm-user-class), which is, of course is not DTO anymore...

**Comment by linaori** [comment]
FOSUserBundle is discouraged by a lot of people these days, I can't remember ever recommending to use it myself. https://jolicode.com/blog/do-not-use-fosuserbundle

**Comment by linaori** [comment]
`If Symfony provides me functionality to load a user from Doctrine ORM`

It doesn't, Symfony allows you to implement a `UserInterface`. There's nothing that exposes this to be an entity.

**Comment by sam0delkin** [comment]
but then why this code is needed: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php#L51 ?

**Comment by linaori** [comment]
That's how this particular user provider looks for the user. You're using the `UserInterface` implementation as entity in your code, but Symfony doesn't expose this as such. This entity isn't managed by doctrine because it comes from the session. Making this entity known to doctrine isn't a good idea because it's a second "truth", it might be out of sync with what's in the database. If you need your Entity, fetch it from the database. 

Using the security user as entity and then trying to persist it, won't work. Changing the TokenStorage to work around the limitation is not a good idea as it's more of a hack to get this particular (ab)use case to work.

**Comment by chalasr** [comment]
Closing as explained.
