### ISSUE TITLE
[Validator] Improve URL validator pattern

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony#30222]
1. The current pattern used in URL validation constraint allows invalid URLs.
Pattern `([\pL\pN\pS\-\.])+(\.?([\pL\pN]|xn\-\-[\pL\pN-]+)+\.?)` for domain allows to pass domains like 
`-a.com` which are invalid according to [RFC 1035](https://tools.ietf.org/html/rfc1035) domains can't start and end with the hyphen. 

2. `\p{M}` is allowed and should be added to pattern.  `à.com` will be transformed to `xn--0ca.com`

3. Also, what do you think about adding TLD pattern check?

**Comment by kiler129** [comment]
rel. 3:
I don't think it's sensible. New TLDs are added pretty frequently nowadays. I cannot count how many times I wasn't able to register with my e-mail in `.pro` domain and how many mail servers are simply rejecting e-mails because of an invalid TLD.

Today you have `.google` and `.ovh`, tomorrow we may have 10 different companies registering TLDs. I'm :-1: for TLDs validation.

**Comment by wtorsi** [comment]
@kiler129  Sure, confirm it.
Actually I'm working on pattern based on RFC 5892 mixed with other RFCs for labels right now, so can provider a PR in the nearest future.
