### ISSUE TITLE
workflow_all_transitions() twig function to list all transition not just enabled

### ISSUE THREAD

**Issue by danaki** [symfony/symfony#30288]
I want to show all transitions available for an object, but some of them make disabled and not clickable. `workflow_transitions()` returns the list of only available transitions. I don't want to hardcode the list of any transitions nor in my twig templates nor in forms, iterate over the list taken from workflow definition is just fine. Is it possible to add `workflow_all_transitions()` to achieve this purpose?

Thanks.

**Comment by lyrixx** [comment]
hello @danaki 

Could you explain a bit more your use case ?
Displaying non-enabled transition is a bit useless because there are not enabled :) 

I did [that ](https://github.com/lyrixx/SFLive-Paris2016-Workflow/blob/1b0e5350e6fdfeedbb04fe5bfe18f340a20f0a72/src/Twig/WorkflowExtension.php#L24-L31) in the demo, but as I said, it's a "hack". I'm very reluctant to add it to Symfony. But you can easily copy / paste this code to your projet.

**Comment by danaki** [comment]
I want to see all transitions as buttons, some of them disabled.

**Comment by lyrixx** [comment]
Ok. So you can use the code that is in the demo :)
