### ISSUE TITLE
Add CardScheme "MIR"

### ISSUE THREAD

**Issue by LeoWyatt666** [symfony/symfony#30376]
**Description**  
Add CardScheme ["MIR"](https://en.wikipedia.org/wiki/Mir_(payment_system))

**Comment by fabpot** [comment]
Can you create a pull request? Nobody will do it otherwise.

**Comment by antonch1989** [comment]
@LeoWyatt666, @fabpot  I've created the pull request. Sorry if I did this too fast, next time I'll notify an issue creator before starting working on it

**Comment by fox-hellraiser** [comment]
@fapbot, @xabbuh, @javiereguiluz supporting MIR is the same as supporting world terrorism and help to avoiding sanctions imposed by the governments of EU and USA to Russia Federation. Citate from Wikipedia:

> The system was devised in 2014 as a way to overcome potential blocks of electronic payments, after several Russian banks were denied services by US-based Visa and MasterCard because of the sanctions regime against them.

> Cette nouvelle carte de crédit a été créée pour pallier le risque de blocage électronique des paiements, suite à plusieurs blocages de banque russe d'accès aux services des systèmes américains VISA et MasterCard lors des sanctions internationales liées à la crise ukrainienne

There is no place for politics, so just google WHY these sanctions were imposed.

**Comment by javiereguiluz** [comment]
@fox-hellraiser we don't talk about politics in this repo, so I'm not going to reply to this message. Sorry.

Also, I propose to lock this conversation because it's easy for this kind of discussions to end up in heated debates. We don't want to bring in politics to this tech project. Sorry again.

Note: we respect your freedom of speech so, if you want, you can continue this debate about "politics/ethics and tech" in Symfony's Slack (https://symfony.com/slack). Thanks.
