### ISSUE TITLE
[Validator] Get good values

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony#30404]
**Description**  
When validate an array with the `All Constraints`  There is no native way to get good values. I propose to add a method to get them  

**Example**  
```php
$uuids = [
'a4f24386-ba58-41d6-a439-565866a52155', //good
'a4f24386-ba58', //wrong
'z4f12345-ba58-41d6-a439-565866a09876' //good
];

 $uuidViolations = $validator->validate($uuids, [new All(new Uuid())]);

 $goodUuid = $validator->saneValue(); 

$goodUuid contains [
'a4f24386-ba58-41d6-a439-565866a52155', 
'z4f12345-ba58-41d6-a439-565866a09876'
]; 
or Object like ConstraintViolation but ConstraintValid or something like this...
````

WDYT ?

**Comment by ro0NL** [comment]
im not sure this belongs to the scope of a validator.

You can infer the good values from the bad ones thru `$uuidViolations` already.

**Comment by kix** [comment]
Why can't you just map/filter the values through the validator, without using the `All` constraint?

```php
$validUuids = array_filter($uuids, function ($el) use ($validator) {
    $violations = $validator->validate($el, new Uuid());

    return $violations->count() === 0;
});

// $validUuids === array(1) {
//    [0]=> string(36) "a4f24386-ba58-41d6-a439-565866a52155"
//  }
```

The `All` constraint's intention is to be used against composite values, as I understand the concept. It shouldn't really be used to pick specific valid values.

Also note that
- adding a `saneValue` method to the validator makes it stateful, which is a no-go. 
- `z4f12345-ba58-41d6-a439-565866a09876` is not a valid UUID actually, since UUIDs are `base16` :)

**Comment by fabpot** [comment]
Closing as there is no more activity here.
