### ISSUE TITLE
[Routing][ServiceRouterLoader] Use a private service

### ISSUE THREAD

**Issue by fancyweb** [symfony/symfony#30402]
When using a service router loader (`type: service`), the service has to be `public`. It would be nice if it was not mandatory (to follow Symfony good practices).

The implementation I thought of would be to tag custom router loader services with a new tag, to be able to inject them in the `ServiceRouterLoader` service in a second "private" service locator. Creating another loader for private services would be bad for DX.

The proposed implementation might be bad for DX actually since it forces developers to add a tag. However, that would works great if there was a concrete interface to implement for service router loader because it could be autoconfigured.

I also thought that we could parse all routes config files before compilation to get the referenced services, but I think that would involve a lot of code and probably be overkill.

Is the whole thing overkill ? Does anyone have a better / easier implementation idea ? @Tobion @nicolas-grekas @stof

**Comment by chalasr** [comment]
👍 for the intend. IIUC the steps needed are:
- Add the tag (+ autoconfiguration interface perhaps)
- Update ServiceRouteLoader so that it takes a ServiceLocator as 2nd constructor arg (the locator contains only tagged route loaders)
- Update `getServiceObject` to make it trigger a deprecation notice in case the new locator doesn't know about the given `$id` + use the DIC as fallback
- Stop using the DIC in 5.0 (removing it from the constructor)

@symfony/deciders any blocker?

**Comment by nicolas-grekas** [comment]
Looks good to me, let's remove the container.

**Comment by fancyweb** [comment]
Alright I'm gonna work on it this week-end!
