### ISSUE TITLE
The LogicException in WebTestCase.php is not correct.

### ISSUE THREAD

**Issue by mehlichmeyer** [symfony/symfony#30420]
**Symfony version(s) affected**: 4.2

**Description**  
In the WebTestCase class there is an error with the LogicException that is being thrown. The message is hardcoded to "You cannot create the client used in functional tests if the BrowserKit component is not available. Try running "composer require symfony/browser-kit".". 
This error can however also occur if the browser-kit is installed. 

**How to reproduce**  
Go to vendor/symfony/framework-bundle/Test/WebTestCase.php and look at the try catch in the createClient() function.

**Possible Solution**  
Change the message

**Additional context**  
For me this error occured when I didn't have my phpunit configured in phpstorm.

**Comment by ro0NL** [comment]
Can you explain how the `test.client` service definition is related to _phpunit configuration in phpstorm_? What exactly did you had to do besides installing browser-kit?

**Comment by xabbuh** [comment]
I think the error can also occur when the test client isn't enabled in the framework bundle config.

**Comment by SerkanYildiz** [comment]
Had this issue too, when I ran the command: `composer dump-env test` it was fixed.
When framework.test is not `true`, the `test.client` service gets removed from the container.

**Comment by xabbuh** [comment]
Does someone want to create a PR also including the `framework.test` config option in the error message?

**Comment by SerkanYildiz** [comment]
@mehlichmeyer do you want to fix it as your first PR to Symfony?

**Comment by SerkanYildiz** [comment]
Ok, couldn't reproduce this on a clean install anymore but went back to our original project.
I understand totally what happens.. 

Our application runs in a docker container where we have set up environment variables on machine base, and because it is on machine base the `DotEnv` component did not overwrite it with the value of phpunit.xml.dist

Because now our application is running under `dev` environment, the `FrameworkExtension` did not load the test.xml which contains the service definition of test.xml.

Do we want to throw another exception that tests should be ran under `APP_ENV=test` or just add that framework.test should be set on true? Wdyt @xabbuh

**Comment by stof** [comment]
the message should talk about the `framework.test` config setting. The fact that there is an environment named `test` where this setting is set is a convention of the Flex skeleton (and of symfony-standard before that), but it is not a requirement of Symfony at all (you could name it however you want)

**Comment by stof** [comment]
btw, we can even check *which* message should be used, as we can check whether browser-kit is installed (using `class_exists(Client::class)` on the browserkit client)

**Comment by mehlichmeyer** [comment]
@SerkanYildiz if I can I would gladly contribute in any way I can! If you'll allow me I'd gladly work ona  fix for this and create a merge request. 
You assumption regarding Docker could be correct, we are using Docker indeed.

**Comment by SerkanYildiz** [comment]
Hi @mehlichmeyer,

I already created a PR (#30479) to fix this issue.

**Comment by k00ni** [comment]
_I would like to add a small hint for others who might also come here after getting this error, because it was not clear what the real problem was at the beginning._ 

I get this message after I upgraded my project from Symfony 4.4 to 5.2. In case you use `phpunit/phpunit` (with `symfony/browser-kit` and `symfony/css-selector`) as well as rely on `APP_ENV` in `.env` and `phpunit.xml`, for instance:

```xml
<env name="APP_ENV" value="test"/>
```
Running PHPUnit with tests using `static::createClient` triggers the error message (`You cannot create the client used in functional tests if the "framework.test" config is not set to true.`), because it still thinks you are using `APP_ENV=dev` (or whatever your default is). Also `framework.test` was `true` in (`config/packages/test/framework.yml`).

### Solution

You have to force `APP_ENV` to be set to `test`, e.g. by using the following in your `phpunit.xml`:

```xml
<env name="APP_ENV" value="testing" force="true"/>
```
**Source:** https://stackoverflow.com/a/53832084/5301527

Be aware of the order PHPUnit checks environment variables! Just because you used `<env name="APP_ENV" value="APP_ENV" force="true"/>` doesn't mean it is used. If it was set outside properly PHPUnit just uses that instead of the one inside the `phpunit.xml`.

Here is the order I assume PHPUnit (at least v12) uses:
1. "Real" environment variable (e.g. set outside the script or inside `.env.test`)
2. `<env name="APP_ENV" value="testing" force="true"/>` from `phpunit.xml`

**Comment by yapro** [comment]
If you want a prod env, you need to config/packages/framework.yaml add:
```yaml
when@prod:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

```
and into phpunit.xml.dist add APP_ENV = prod:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/bin/.phpunit/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="tests/bootstrap.php"
         convertDeprecationsToExceptions="false"
>
    <php>
        <server name="APP_ENV" value="prod" force="true" />
        ...
    </php>
```
