### ISSUE TITLE
[DependencyInjection] Anonymous services are not removed along with the parent service 

### ISSUE THREAD

**Issue by marcospassos** [symfony/symfony#30428]
**Description**  
When a definition is removed, I expect nested anonymous services to be removed as well:

**How to reproduce**  
```xml
<service id="foo_service" class="Foo">
    <argument type="service">
        <service class="Bar">
            <argument>%bar.parameter%</argument>
        </service>
    </argument>
</service>
```

Extension:
```php
if (!isset($config['option'])) {
    $container->removeDefinition('foo_service');

    return;
}

$container->setParameter('bar.parameter', $config['option']);
```

Compiling the container without `option` results in:

```
The service ".3_Bar~hJYmG7r" has a dependency on a non-existent parameter "bar.parameter".
```

**Comment by sstok** [comment]
Due to the way services are parsed by the https://github.com/symfony/symfony/blob/101bfd79bfc9853e7935f2c87411516eda0a8b2f/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php#L417 (and Yaml also) Anonymous services are registered as regular services but with a unique id to reference them, so they are not embedded in the actual service that uses them.

I don't think this something that can be fixed, or it would be rather difficult to do so 😅

**Comment by marcospassos** [comment]
In fact, the nested services will be removed as part of the optimization step. My point is that warning about a missing parameter is side effect, and completely unexpected.

**Comment by nicolas-grekas** [comment]
In a similar situation (AutowiringPass if I'm not wrong), we use `Definition::setError()` to solve this case. It should work here also if someone wants to have a look.
