### ISSUE TITLE
[TwigBridge][DebugCommand] Attempted to call an undefined method named "getNamespaces" of class "Twig_Loader_Chain".

### ISSUE THREAD

**Issue by diepm** [symfony/symfony#30426]
**Symfony version(s) affected**: 4.1 and 4.2 (have not tried with other versions).

**Description**  

This happens when I use multiple Twig loaders and run `./bin/console debug:twig`. The error message is

    In DebugCommand.php line 249:
   
       Attempted to call an undefined method named "getNamespaces" of class "Twig_Loader_Chain".

**How to reproduce**  

* Start a new Symfony project `composer create-project symfony/website-skeleton test`
* Add a new Twig loader to `services.yaml`, under `services:` section, as `extra_twig_loader: { class: Twig\Loader\FilesystemLoader }`
* Run `./bin/console debug:twig`

I might have been missing something when adding a new Twig loader, but for now, it's the error I get. Looking at `DebugCommand.php` code, the Twig loader instance for multiple Twig loaders is `ChainLoader` instead of `FilesystemLoader`. This `ChainLoader` doesn't have `getNamespaces()` method.

**Comment by yceruto** [comment]
This bug can be solved if we ignore the information related to the loader when this is an instance of `ChainLoader`, but it would be better if we could iterate over the contained loaders (which is not possible now) and show the information of all `Twig\Loader\FilesystemLoader` registered. For this, we would need to do `ChainLoader` iterable or add a new `getLoaders()` method inside it.

Another alternative would be to pass all `Twig\Loader\FilesystemLoader` to the command constructor and play with them, but this one seems more a new feature rather than a bugfix.

Friendly ping @fabpot, @stof, what would be the strongest solution in your opinion?

Status: Reviewed

**Comment by fabpot** [comment]
In one of my project, I have something like this where I need to get the first filesystem loader:

```php
    private function findFirstFilesystemLoader(LoaderInterface $loader): ?FilesystemLoader
    {
        if ($loader instanceof FilesystemLoader) {
            return $loader;
        }

        if ($loader instanceof ChainLoader) {
            $p = new \ReflectionProperty($loader, 'loaders');
            foreach ($p->getValue() as $l) {
                return $this->findFirstFilesystemLoader($l);
            }
        }

        return null;
    }
```

I think it would make sense to expose the loaders from a Chain loader. I'm going to create a PR on Twig for that.

**Comment by fabpot** [comment]
see twigphp/Twig#2858

**Comment by diepm** [comment]
I expect the `getLoaders()` method as well. Thanks!

**Comment by yceruto** [comment]
Draft PR in progress - waiting for the new Twig release https://github.com/symfony/symfony/pull/30440
