### ISSUE TITLE
[DX] Is DX is focused on IDE autocompletion ?

### ISSUE THREAD

**Issue by arnaud-lb** [symfony/symfony#30452]
It's awesome to see Symfony having a goal of improving developer experience (DX). However, as seen on the communication around the new HttpClient and on the related [PR](https://github.com/symfony/symfony/pull/30413), it appears that this effort is mainly focused on making IDEs auto-completion nicer by reducing the number of symbols exposed to the user.

In order to support this effort, it appears that compromises are being made on the design and the behavior of the component.

Example of design compromise: Building a HTTP client with multiple backends is a natural fit for an adapter pattern. Instead, it has been chosen to re-implement the full client for each backend, and to use a trait for code re-use between them. Given rationale: Using an adapter pattern would introduce a new interface (e.g. HttpClientAdapterInterface), which would pollute the type space [and IDEs auto-completion]. An adapter pattern would have been better, IMO: Clearer extension points defined by the adapter interface, thus easier implementation of backends including by third parties, and easier evolution / backwards compatibility management. In contrast, a trait, whose methods and properties are inherently accessible by using classes, is impossible to evolve safely (especially if third parties use it).

Example of behavior compromise: In order to support batching, the HTTP client exposes lazy responses instead: The request() method immediately returns a response that will be truly executed upon first access. The result of this choice is that error behavior is less intuitive, less obvious. It is unclear when and how exceptions can be thrown. Some getters, once called, change the behavior of other getters. An alternative approach would have been to return request objects, and to allow to execute the requests in batch. The non-lazy appraoch has apparently not been taken because of DX reason as well.

Symfony 2 was once a model of clean code, clean design, least-surprise, non-magic, explicit code for me, which made for a the best developer experience I ever had with any web framework before. I feel that some of these values are being abandoned for the sake of IDE auto-completion conciseness.

Here are my questions:

 - Is it worth it ?
 - Is it really improving the developer experience, beyond auto-completion ?
 - Can Symfony cooperate with IDEs to improve the experience while reducing the compromises made on Symfony side ? (e.g. introducing an annotation that's mid-way between "every day APIs" and "internal")

**Comment by stof** [comment]
I don't see how the fact that both the native client and the curl clients are implementations of the HttpClientInterface rather than of another HttpClientAdapterInterface makes any difference here.
the implementation of the public API of HttpClientInterface is precisely what changes between implementations. Having an HttpClientInterface implementation delegating everything to an HttpClientAdapterInterface interface with the same API does not make any sense.

The HttpClientTrait only provides some internal helpers needed by both implementation inside their processing. The alternate design would have been to provide a `HttpClientUtil` class with public helpers instead of using private helpers in a trait.

Regarding the lazyness, the goal was precisely to design a system where calling code does not have to handle all batching on its own.
and for `getStatusCode` changing what happens when you get the content, that was done to make it easy to handle failures: either you access the status code to deal with such cases yourselves, or we automatically report failures as exception. That avoids the common mistake of forgetting to handle failures, or the hassle of having to catch exception to handle them differently in case the http client decided to throw exceptions in such case.

this was *not* designed with IDE  autocompletion as the first requirement. Older drafts of it were even totally bad for IDE autocomplemention (they were returning some mixed array, not a Response object) when this smart error handling and this lazyness was not yet part of it.

**Comment by stof** [comment]
See https://github.com/symfony/symfony/pull/30413#issuecomment-468905424 for the explanation about the error reporting behavior.

**Comment by arnaud-lb** [comment]
Thanks for your comments @stof.

> Having an HttpClientInterface implementation delegating everything to an HttpClientAdapterInterface interface with the same API does not make any sense.

This is not the idea :) The idea is to implement only adapter-specific methods in adapters, and user-facing APIs in the client class. This way, the client has the opportunity to execute common code before calling the adapter (like preparing the request).

> The HttpClientTrait only provides some internal helpers needed by both implementation inside their processing

To be precise, the trait provides primarily one helper: `HttpClientTrait::prepareRequest()`. Calling this helper is the first thing that's done by both implementations. In an adapter design, this helper would be a private method of `HttpClient`, called by `HttpClient`, and it would return a request object. The request object would then be passed to the adapters.

The only two other trait methods that are called by implementations are `parseUrl()` and `resolveUrl()`, two methods that could be methods of a request object, for example.

The 7 remaining methods are internal methods of the trait. However, they are accessible directly by the implementations. I believe that Symfony uses private visibility by default on base classes, to avoid having to maintain them. In a trait, it's impossible (privates can be accessed by using classes).

> Regarding the lazyness, the goal was precisely to design a system where calling code does not have to handle all batching on its own.

It is possible to implement batching with a very similar API, without lazyness: If `HttpClientInterface::stream()` accepted an array of requests, we wouldn't need lazyness. Creating request objects can be annoying, so a `HttpClientInterface::prepare($method, $url, $options)` could handle that for us (an hypothetical method with the same signature as `::request()`). 

> and for getStatusCode changing what happens when you get the content, that was done to make it easy to handle failures: either you access the status code to deal with such cases yourselves, or we automatically report failures as exception

This is the result of chosing lazyness. Without lazyness, `stream()` or `request()` can directly throw an exception when an error occurs. The exception can contain the `ResponseInterface`, which can be used to access any detail about the errored response.

When not batching, only `getContent()` needs to be lazy, and in case of a read error it makes sense to throw an exception from `getContent()`.

> That avoids the common mistake of forgetting to handle failures

This problem exists only because of lazyness

> See #30413 (comment) for the explanation about the error reporting behavior.

I'm all ok about throwing exception on 3xx 4xx 5xx status codes. What I'm complaining about where and how the exceptions are thrown.

**Comment by arnaud-lb** [comment]
Note: While the issue uses the HTTP client as an example, I hoped that it wouldn't turn in a debate around the HTTP client particularly. My primary goal here is to raise questions around the way DX seems to be achieved currently, and the way it affects the components.

**Comment by nicolas-grekas** [comment]
Symfony is not one brain and is not a living body. Things exist by their contributors. If you feel like Symfony - the code - should be different, denigrating the work that others did isn't very helpful. What I invite you to do instead is to contribute your code, which will embed your style. I'm sorry for that abrupt response but please read your initial description again, that's what it is: denigrating the work of many.

> Is it really improving the developer experience, beyond auto-completion ?

Autocompletion is provided by type completeness. i.e. if all types are crystal clear at reading-time (the reader being the human looking at them or the IDE or a static analyzer, etc.), then everyone can understand the code much better, tools or reviewers.

So, if your question is: does Symfony optimize for IDEs, the answer is no. But is the code I submit as explicit as I can possibly make it about types? the answer is yes. Is it worth it? To my eyes yes. Nice side effect: IDEs like that.

> Can Symfony cooperate with IDEs to improve the experience while reducing the compromises made on Symfony side ? (e.g. introducing an annotation that's mid-way between "every day APIs" and "internal")

See https://youtrack.jetbrains.com/issue/WI-37750

I won't comment specifically on the HttpClient PR since you explained that's not the topic you want to raise.

So, what about traits in the generic case?

From a maintainer POV, every private methods in a trait add the exact same burden as a protected method in a class. That means we cannot use "private" on a trait to mean "internal". This means that when we add a trait with private methods, we must be as careful as if we were to add a protected method. I think everyone in the core team knows about that, so we're good: that's not an argument against using traits. About your example in HttpClientTrait, my indent *is* to expose all the methods to userland - not only the 3 of them you spotted: they can be all useful to future authors of decorators and they are pure functions, which means they're very easy to maintain.

Traits are awesome reusability units because they don't bind behavior to a type. They provide tools without forcing one to also inherit a type while doing so. Using HttpClient as an example again, HttpClientTrait is used also in #30414, in a class that needs the exact same logic internally but doesn't expose the same types at all.

Would this be better achieved by injecting helper objects? Helper objects mean adding an interface for them, an injection point, etc. all the classical dance we need when composing objects. *That* dance is adding maintenance overhead to us, the maintainer. Traits free us from that by being reusability units of pure behaviors.

About the other part in your rant, I can't answer in any generic term. I've been exploring so many dead ends while working on HttpClient before settling on the current API. If you think you have a better API, please ship some code, I'd be happy to review it, borrow ideas, replace everything, etc. while keeping the core features that I managed to bundle together.

**Comment by stof** [comment]
> This is not the idea :) The idea is to implement only adapter-specific methods in adapters, and user-facing APIs in the client class. This way, the client has the opportunity to execute common code before calling the adapter (like preparing the request).

but that's the whole thing here: there is no common logic between the native client and the curl client for the user-facing API, as they perform HTTP request differently.

> This problem exists only because of lazyness

Please read the discussion on the PR. @nicolas-grekas already answered this concern here. He considers that this lazyness is a core feature of the component. As soon as you have more than 1 HTTP request involved, lazyness is very good for performance.
This lazyness is not only useful when using `stream`. It also helps when starting 2 requests and then consuming their response, as the HTTP request will still happen concurrently:

```php
$firstResponse = $client->request('GET', $url1);
$secondResponse = $client->request('GET', $url2);

// Both HTTP requests are running concurrently here

// this line blocks until the first response is available
$firstResponse->getContent();

// this line blocks until the second response is available.
// There is a good chance that it already is, as it started before waiting for the first response.
$secondResponse->getContent();

```


the equivalent JS code would look like that:

```
const firstResponsePromise = fetch(...);
const secondResponsePromise = fetch(...);

// Wait only after starting both requests.
const firstResponse = await firstResponsePromise;
const secondResponse = await secondResponsePromise;
```

**Comment by arnaud-lb** [comment]
All my apologizes if you feel that I'm denigrating someone's work: This is not my intent at all. What you are doing is awesome, and you deserve only love for this.

The only goal of this issue is to discuss.

When I say "it appears that this effort is mainly focused on making IDEs auto-completion nicer by reducing the number of symbols exposed to the user", it's because this is how it appears from the outside, when looking at the communication around the HTTP client, and from PR comments, for example. If that's not the case, this makes me very happy, however from the communication it appears to be a very important metric in the DX effort.

> >     Can Symfony cooperate with IDEs to improve the experience while reducing the compromises made on Symfony side ? (e.g. introducing an annotation that's mid-way between "every day APIs" and "internal")

> See https://youtrack.jetbrains.com/issue/WI-37750

This is exactly the kind of cooperation I was referring to, this is awesome. From a [previous comment](https://github.com/symfony/symfony/pull/30413#issuecomment-468923096) of yours, it appeared to me that introducing a `HttpClientAdapterInterface` would pollute the type system (which I understood as _pollute the auto-completion_, please let me know if I'm wrong). In this issue, I'm asking whether solutions less radical than avoiding new interface could arise from a cooperations like this.

> Traits are awesome reusability units because they don't bind behavior to a type
> [...]
> [Helper objects are] adding maintenance overhead to us, the maintainer

I think that there is a world between traits and full-fledged dependency injection. If a trait is being used today, it means that all the benefits of dependency injection are not a requirement (such as accepting an abstraction, not an implementation). If these requirements are absent, there is no need for interfaces, injection points, and all the overhead you are referring to. There would still be some benefits, though, such as isolation/encapsulation, clear APIs, etc. and (I believe) better maintainability.

> If you think you have a better API, please ship some code, I'd be happy to review it, borrow ideas, replace everything, etc. while keeping the core features that I managed to bundle together of course.

Will try !

**Comment by arnaud-lb** [comment]
@stof:

> >    This is not the idea :) The idea is to implement only adapter-specific methods in adapters, and user-facing APIs in the client class. This way, the client has the opportunity to execute common code before calling the adapter (like preparing the request).

> but that's the whole thing here: there is no common logic between the native client and the curl client for the user-facing API, as they perform HTTP request differently.

There is: They both need to prepare the request, parse the options, parse the URL, for example.

> >     This problem exists only because of lazyness

> Please read the discussion on the PR. @nicolas-grekas already answered this concern here. He considers that this lazyness is a core feature of the component. As soon as you have more than 1 HTTP request involved, lazyness is very good for performance.

My point was that _I think_ that we can achieve this without lazyness

>  This lazyness is not only useful when using stream. It also helps when starting 2 requests and then consuming their response, as the HTTP request will still happen concurrently:

This was not apparent in the features. This changes some things :)

**Comment by nicolas-grekas** [comment]
> All my apologizes if you feel that I'm denigrating someone's work: This is not my intent at all. What you are doing is awesome, and you deserve only love for this.

Thanks for your kind words. Usually, I ignore the form and focus on the content of comments. But too many of them carry some sort of emotional load... I'm trying a different style because the form has its importance, e.g. for diversity... Slippery rope for me... Nothing personal!

> If that's not the case, this makes me very happy, however from the communication it appears to be a very important metric in the DX effort.

Thanks for the warning, that's a miscommunication then. `HttpOptions` *is* for IDEs, but it's really an experiment. All the rest is really rooted in being SOLID before anything.

> See https://youtrack.jetbrains.com/issue/WI-37750
> This is exactly the kind of cooperation I was referring to, this is awesome.

Too bad JetBrains forgot about it... Anyone reading, please comment/vote on the issue if that can help. Or each a JetBrains dev.

> From a previous comment of yours, it appeared to me that introducing a HttpClientAdapterInterface would pollute the type system (which I understood as pollute the auto-completion, please let me know if I'm wrong).

I really meant from a maintainer pov: the broader the API surface, the harder to maintain.

> I think that there is a world between traits and full-fledged dependency injection. If a trait is being used today, it means that all the benefits of dependency injection are not a requirement (such as accepting an abstraction, not an implementation).

Yes, exactly: providing DI composition here means creating a local framework in the framework. Something that is hard to get right and thus adds significant maintaince burden - because we *will* deprecate some parts of it in the future, for sure.

Traits are muc more lighweight reusability unit: we provide the behavior, you compose them. You want to build composition via DI on top? No issue, just do it. Does Symfony *have* to provide it for you? That's a real challenge at this genericity level, better focus on one abstractio, the main one.
That's my reasoning at least.

> If you think you have a better API, please ship some code, I'd be happy to review it, borrow ideas, replace everything, etc. while keeping the core features that I managed to bundle together of course.
> Will try !

Thanks! That can be only snippet at the begining of course. I'd suggest doing after merge, that will make it easier for everyone. I'll all up for a better API if we can find one!

**Comment by nicolas-grekas** [comment]
@arnaud-lb makes sense?

**Comment by DanieleGBX** [comment]
> > See https://youtrack.jetbrains.com/issue/WI-37750
> > This is exactly the kind of cooperation I was referring to, this is awesome.
> 
> Too bad JetBrains forgot about it... Anyone reading, please comment/vote on the issue if that can help. Or reach a JetBrains dev.

According to a JetBrains dev response, this is supposedly already implemented.

**Comment by arnaud-lb** [comment]
@nicolas-grekas : Makes sense ! It reassures me that DX in Symfony is not only about optimizing auto-completion, so I guess I can close this issue now. Again, all my apologizes if the issue came as denigration, this was not the goal. Online communication is hard, I need to improve on that.
