### ISSUE TITLE
Suggest packages on missing autowiring aliases

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#30521]
When I use a type-hint for an interface that is not installed, autowiring fails with a generic message, e.g.: `Cannot autowire argument $client of "App\Controller\HelloController::index()": argument "$responseFactory" of method "Symfony\Component\HttpClient\Psr18Client::__construct()" has type "Psr\Http\Message\ResponseFactoryInterface" but this class was not found.`

But in this example, we could suggest a solution: `compose require nyholm/psr7` will install recipes for the interface. Maybe we could display this as a suggestion when we detect that flex is installed? We would do this for packages with official recipes only to reduce the scope.

Another example is ` Cannot determine controller argument for "App\Controller\HelloController::index()": the $client argument is type-hinted with the non-existent class or interface: "Psr\Http\Client\ClientInterface".` when `psr/http-client` is missing.

**Comment by moynzzz** [comment]
I would like to work on this issue @nicolas-grekas how do you suggest implementing the desired in terms of which packages interfaces should be auggested. Should we extract all possible interfaces from the packages that exist in the symfony recipes repository or some more robust way of doing that?

**Comment by nicolas-grekas** [comment]
From what I read, these two messages are found:
1. in `AutowirePass::createTypeNotFoundMessage()`
2. in `RegisterControllerArgumentLocatorsPass::process()`

I think we could add a static class in the DI component that would hard-code a few packages - let's start with only the ones mentionned in the description and see later if/how to grow the list?

**Comment by moynzzz** [comment]
Okay I'm working on a PR for this feature.

**Comment by moynzzz** [comment]
I have a qustion about how to check if flex is installed in a symfony application. I tried to check if flex class exists (`Symfony\Flex\Flex`) but it depends on `Composer\Plugin\PluginInterface` which is not autoloaded (because composer autoloader doesn't add it to the list of loaded classes which is expected we don't need it in our applications) and so the check will fail. A solution will be to check for a class that exists in the flex source like `Symfony\Flex\Lock` but I don't think this is the best one.

Does anybody have an idea how this can be solved?

**Comment by nicolas-grekas** [comment]
> A solution will be to check for a class that exists in the flex source like Symfony\Flex\Lock

I think that's the best solution actually :)

**Comment by Simperfit** [comment]
@moynzzz Are you still working on it ?

**Comment by moynzzz** [comment]
@Simperfit Yes, I am. Sorry for the delay I was a little busy last month.
