### ISSUE TITLE
Automatic packager for easy installer for a project

### ISSUE THREAD

**Issue by MicWit** [symfony/symfony#30531]
I have used Symfony in the past (I am a web developer), and use bamboo to deploy it with a script I wrote. I am now looking at making an opensource webapp, but I want it to be easy for a user to download and install my webapp. This means not touching composer for anything, rather just running a simple install script. I think the user would still need to install mysql (or whatever database they want to use, I would include instructions on how to do that), but would be nice if on Windows they could just run an exe, and similar on linux and mac, and the installer would ask what port they want to run on as well as database details etc. Maybe even have a version that would install MySQL as part of the installer. Then maybe a second option for if they are running it on a web host running Apache that could be as simple as the user extracting a zip and running an installer.php.

I am looking at making a wiki that is simple to use (so far when it comes to adding data to a wiki, Confluence is the only one that is simple and functional to add pages etc), but I would want it to be easy to install as well, and if I use Symfony it would not be too easy to install on a computer. I would imagine if you could get the packager working properly, this could make Symfony a way better choice for opensource webapps.

Btw, this should have a label of feature request, but not sure how to add a label, could be because I am on my phone.

**Comment by javiereguiluz** [comment]
About the labels ... they can only be set by admins, that's why you couldn't label this as a feature. I did it for you.

About the feature request, it looks like you are looking for something similar to [Golang's compile commnand](https://golang.org/cmd/compile/) which generates an executable binary with all the dependencies included in it, so you can install the app anywhere. It's amazing ... but PHP doesn't have anything like that ... yet ... see https://github.com/ircmaxell/php-compiler

It's not possible for us to implement this without PHP helping us with the compiling phase, so I'm afraid we can't implement your feature request and that's why I'm closing your issue. Thanks for understanding!

In any case, this lacking feature doesn't prevent all the important PHP projects (except WordPress) to use Symfony, See https://symfony.com/projects  So, you don't need this to distribute open source apps.

Finally, you said that you are developing a *"simple to use wiki"* ... so maybe you could simplify your requirements to make the app easier to distribute. Taking the Symfony Demo app as an example (https://github.com/symfony/demo) you could use SQLite instead of MySQL or distribute the web assets compiled instead of their sources.

**Comment by nicolas-grekas** [comment]
See also https://github.com/humbug/box

**Comment by MicWit** [comment]
@javiereguiluz 
> It's amazing ... but PHP doesn't have anything like that ... yet ... see https://github.com/ircmaxell/php-compiler

This looks interesting, I will keep an eye on this, thanks.

> Taking the Symfony Demo app as an example (https://github.com/symfony/demo) you could use SQLite instead of MySQL or distribute the web assets compiled instead of their sources.

Yes, I fully intend to do both these things, but have an option to change to your own database if required. One of the things I REALLY want to avoid is the need to install composer and node.js. I guess doing this will mean installing PHP and it should just run.

@nicolas-grekas 
> See also https://github.com/humbug/box

This project looks cool, and I think I will use it for some things/services. In this case I really want the ability for the user to plug into a mysql database, but it may be an option to package a version with an SQLite database built in, so that the user can just install PHP and run a command (and maybe have an installer that will set it up as a service.


When it comes to using the built in server (in Symfony), I have seen in the past that this should only be used for testing purposes. Has this changed at all or could I now just get the user to install PHP, extract the project with web assets ready to go and run the built in server (to save an Apache install)? Of course this would need to be let through the firewall etc.

I was also thinking that a basic install.php that is run with options etc could be good, and it could set up the env variables etc and check for any php modules etc this particular project requires (rather than use composer).
