### ISSUE TITLE
Introduce custom attributes for Responses

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#30578]
**Description**  
The request object have attributes property where application can save custom informations. This possibility is missing on responses. (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L74)

I am migrating currently a project that uses ZF1 Request and Response object. The Response object has a method to set exceptions to this Response. Since I want to replace only the Request and Response object I have to support that also as Response object from the HttpFoundation.

So my idea was to add that property also to the Response object

I would also create a PR for that :)

**Example**  
```
$response= new Response();
$response->attributes->set('something', true);
```

**Comment by stof** [comment]
What would be the use case for that ?

**Comment by shyim** [comment]
To store custom informations like exceptions occurred in this request response cycle (Who don't use the complete Symfony Framework)

**Comment by ro0NL** [comment]
Do you really need to use Symfony Response for that? I'm not sure it's valid just because Zend Response does it.

> The Response object has a method to set exceptions to this Response. 

ZF will handle it as such i assume? Symfony has no such concept, so i'm not sure what you're expecting?

If it's just to transfer attribtues/anything, i don't think you need the Response object for that per se. Or at least i dont think core should provide something for that.

**Comment by fabpot** [comment]
The Response is probably not the right class to store additional information.
