### ISSUE TITLE
[Validator] UrlValidator doesn't accept brackets in query string

### ISSUE THREAD

**Issue by finwe** [symfony/symfony#30603]
**Symfony version(s) affected**: at least since 3.2.14 up to current master

**Description**  
The preg validating URLs doesn't validate URLs containing `[]` characters generally used for denoting array query parameters.

**How to reproduce**  
Try to validate url (generated by FB, altered and shortened) `https://www.facebook.com/genericfbpage/?__tn__=kC-R&fref=nf&__xts__[0]=68.ARDlO2VS` - validation fails

**Possible Solution**  
Alter UrlValidator PATTERN regex constant to match brackets.

**Comment by ro0NL** [comment]
There's a lot of discussion around square brackets in URIs :)

Per https://stackoverflow.com/questions/11490326/is-array-syntax-using-square-brackets-in-url-query-strings-valid

> If a reserved character is found in a URI component and
   no delimiting role is known for that character, then it must be
   interpreted as representing the data octet corresponding to that
   character's encoding in US-ASCII.

I'm :+1: ok to allow both, escp. since it works in PHP. Alternatively we could a a new option `extraAllowedChars` maybe.

**Comment by cybernet** [comment]
maybe url can be stripped after “?” ...
[] in urls are a rarely a thing from what i’ve noticed ( excepting websites in perl )

**Comment by finwe** [comment]
> [] in urls are rarely a thing from what i’ve noticed ( excepting websites in perl )

Is this just an assumption or can you support this with some evidence?

GET forms with dynamic number of elements will almost definitely use this.

**Comment by cybernet** [comment]
@finwe just an assumption
