### ISSUE TITLE
config custom dir of `Datafixtures`

### ISSUE THREAD

**Issue by lichnow** [symfony/symfony#30705]
can change the dir of `Datafixtures` now? because,when use `api platform`，app will has many dir like `dto`,`dataprovider`...,I want to move that all to `src/Data` path.have any configure to `DataFixtureBundle`?

**Comment by javiereguiluz** [comment]
@lichnow I'm afraid I must close this issue because it looks like a support question (we only use this repository to discuss about bugs and new features; for support, you can check https://symfony.com/support).

In any case, take a look at the recently added `--group` option (https://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html#fixture-groups-only-executing-some-fixtures) and report any issues in this repository: https://github.com/doctrine/DoctrineFixturesBundle
