### ISSUE TITLE
[RFC][Form] Data transformer as a service

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#30747]
I like to propose the idea of using a Form `DataTransformerInterface` as a service. This would ease a vendor to ship some (complex) data transformers and let the user decide to use it yes/no in some specific form type.

Before

```php
$builder->get('some')->addModelTransformer(new Vendor\SomeTransformer(
  $all, $the, $deps, $needed, $here
));
```

After

```php
$builder->add('some', SomeType::class, ['model_transformers' => [
  'vendor.some_transformer',
  ClassNamedService::class,
  new MyTransformer(),
]]);
```

conceptually it applies to view transformers & event listeners as well.

**Comment by kunicmarko20** [comment]
The name is a bit confusing since you can already use them as a service, right?

**Comment by yceruto** [comment]
Did you mean a new option to configure data transformers?

**Comment by yceruto** [comment]
Can't you inject your data transformer service and add it as usual?
```php
$builder->get('some')->addModelTransformer($this->vendorModelTranformer);
```

**Comment by ro0NL** [comment]
> Can't you inject your data transformer service and add it as usual?

yes, this is my current approach :) but ideally i dont want to fed up the user with service injection.

> Did you mean a new option to configure data transformers?

i guess :)

**Comment by ro0NL** [comment]
We should probably hook in via `addModelTransformer('service_id')` to not leak this detail outside by default. But that's a bigger step.

My use case is any form with an `EmailType` which can optionally be transformed to its corresponding entity yes/no, depending on the context of the form.

Now i switched to a specific form option (provided by extension) to configure a mapping from source field (e.g. `email`) to target field (e.g. `user`), where both fields end up in the final form data array. I actually like it because i keep both values at hand :) but it's a bit less generic.

**Comment by sstok** [comment]
Something like this can be done using a TypeExtension without making it a default feature of the `FormType`, given that `model_transformers` is passed you append the transformers to the existing transformers list. Or prepend (as this will properly require another option, and another one to whether or not clear existing transformers).

My only concern, how likely is it that you use this extensively (with multiple transformers?), introducing a new FormType with extra options is rather cheap and keeps the logic in the form type that performs this rather than doing this in the parent form-builder, not to mention that any type extension can modify the behavior of the child type and break your one-off transformer configuring.

Not saying this is a bad idea, but is it something that should be part of the Form component itself?

**Comment by ro0NL** [comment]
I think you're right. Using rich form options, in my case, works fine. Closing as such.. let's see if the use case pops up in different form.

For reference, here's how i solved it: https://github.com/msgphp/user/blob/17281e23589c108fe41ca2c72ebb6821530391b8/Infrastructure/Form/Extension/UserExtension.php#L45
