### ISSUE TITLE
[Routing] UrlGenerator could benefit from cache support

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#30751]
UrlGenerator could benefit from cache support. When generating thousands routes (eg for sitemap), time it takes for this call creeps up (for about 200000 calls this is responsible for more than 4 seconds). I believe this is good candidate for caching, because it's rare that route definiton + input ever yields different output.

**Comment by javiereguiluz** [comment]
With the given data, I'd say it's not worth it. 200,000 calls in 4 seconds is OK for something as unusual as generating the sitemap of a big web site or web app.

Moreover, it's common (I'd say mandatory!) to cache the entire generated sitemap XML file, so this routing cache wouldn't be used at all.

**Comment by ostrolucky** [comment]
Total time is 20 seconds. 10 seconds takes XML generation, but algorithm for that in bundle we use is poor. 5 seconds is taken by route generation. I would say this is significant.

It's not mandatory to cache sitemap, because it's for robots only. Robots don't care when webpage takes couple seconds more to load. Furthermore, even when you cache it, you need to eventually invalidate it and warm this cache again.

**Comment by javiereguiluz** [comment]
Introducing a cache may make routing slower for most apps: you need to hash the route name and the entire input to generate the cache key. In lots of cases that could be slower that actually generating the URL.

Also, I still think that the given use case is not enough. I've never seen a non-trivial app that doesn't generate the XML sitemaps statically, so they wouldn't use this routing cache because they cache the entire XML file.

**Comment by ostrolucky** [comment]
If generating cache key is slower than re-generating value, then obviously caching here is no-go, but that is speculation that needs to be measured. If it's even slightly faster then it's worth it in majority cases, because it's rare this gets invalidated. Also, this caching can be optional.

> they wouldn't use this routing cache because they cache the entire XML file.


> even when you cache it, you need to eventually invalidate it and warm this cache again.

**Comment by stof** [comment]
Is your sitemap calling the url generator 200000 times with the same argument, or 200000 times for different ouput each time.
The use case of a sitemap would be to generate all possible URLs, not many times the same one AFAICT. So memoizing the URL generation would only add overhead as it would always end up doing cache misses.

**Comment by ostrolucky** [comment]
You somehow count with temporary array cache, I'm proposing here proper psr cache support. Such cache can be stored and don't really get stale.

**Comment by stof** [comment]
but then, you want to replace 200000 calls to the generation logic with 200000 calls to a Redis server, involving network IO. With the numbers above, each call takes 20µs. You won't be able to get the answer from Redis and process it in that time.

**Comment by stof** [comment]
note that the url generator does not parse the routing files each time you call it. We already generate an optimized generator in the cache to be as fast as we can.

**Comment by ostrolucky** [comment]
Now you count with redis cache. What about APCu and OPCache?

**Comment by k0d3r1s** [comment]
what do you want to cache exactly if in sitemap you should be generationg 200k of unique urls?

**Comment by ostrolucky** [comment]
result of $route, $routeParameters => $uri, so it does not need to be calculated again once it happened already in past. I need to play with it a little to see what's the gain

**Comment by k0d3r1s** [comment]
you want to cache that within that sitemap generation (which is strange since you shouldn't have even two identical links inside of sitemap) or you want it generated link to be cached for reuse beyond sitemap?  
i don't see any gain in performance either way tho. if the generation takes such a long time, just cache response for some time to not do generation again for some time.

friend of mine made this library to cache full responses in redis, you can check that out, maybe it works for you: phpsed/cache

**Comment by ostrolucky** [comment]
> you want to cache that within that sitemap generation (which is strange since you shouldn't have even two identical links inside of sitemap) or you want it generated link to be cached for reuse beyond sitemap?

This is about caching result of url generation. Speed up this will result in will benefit everywhere, let's not talk in whole thread only about given example use case.

> just cache response for some time to not do generation again for some time.

> cache the entire generated sitemap XML file

> they wouldn't use this routing cache because they cache the entire XML file.

↓

> even when you cache it, you need to eventually invalidate it and warm this cache again.

**Comment by rpkamp** [comment]
I agree that the added code complexity and overhead won't make caching worth it, especially not for smaller applications where it will probably make URL generation slower due to added layers.

That being said, if URL generation is considered slow, maybe we should be profiling it to make it faster, instead of directly jumping to caching?

**Comment by rpkamp** [comment]
> friend of mine made this library to cache full responses in redis, you can check that out, maybe it works for you: phpsed/cache

Symfony has the [HttpCache](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/HttpCache/HttpCache.php) class to cache kernel responses. No need for additional depencies :slightly_smiling_face:

**Comment by ostrolucky** [comment]
Ok I'm convinced, you are right guys. Caching has higher overhead than urlgenerator. Thank you all for feedback!

After inspection, I see see some possible theoretical urlgenerator micro optims in future though:

- avoid doing array_flip inside UrlGenerator, store it flipped in compiled UrlGenerator
- avoid doing isset check by ensuring compiler fills in every slot of array (concretely I'm talking about `$token[5] ?? false`)
- avoid doing two strtr calls in a row by having `/..` and `/.` segments included in $decodedChars
- check if $defaults is non-empty before calling `array_udiff_assoc`

cc @nicolas-grekas
