### ISSUE TITLE
[Twig] Access master request in twig

### ISSUE THREAD

**Issue by antonch1989** [symfony/symfony#30822]
I propose to make `master request` available in AppVariable class in purpose to be accessible in a template without having it as a controller argument.

**Comment by stof** [comment]
What is your use case ?

**Comment by yceruto** [comment]
I'm not sure that it's a common case to access the master request from templates, but we could expose this feature as `app.master_request`.

Meanwhile, you can create your global service that also has access to the master request. https://symfony.com/doc/current/templating/global_variables.html

**Comment by fabpot** [comment]
I'm 👎 for adding this in core. It's easy enough to add if you need to (as explained by @yceruto), the use cases should be rare enough, and we are trying to not leak the master/sub-requests information in the view.

**Comment by nuryagdym** [comment]
I also faced this issue.

My use case is, I have a dynamic menu which I am loading in the twig in the following way:

```
{% block submenu %}
    {{ render(controller('App\\Controller\\HeaderMenuController::bankOperations', {'bank': bank})) }}
{% endblock %}
```

what **bankOperations** renders:
```
<nav class="navbar" id="sub-navbar">
    <ul class="nav navbar-nav">
        {% for op in operations %}
            <li class="nav-item {{ app.request.uri == path(op.path, {'bank' : bank}    ) ? "active" : '' }}"><a href="{{ path(op.path, {'bank' : bank}) }}">{{ op.label }}</a></li>
        {% endfor %}
    </ul>
</nav>
```
**bankOperations** It will render sub menu according to the selected bank.

I am using this block almost on all pages.

Problem is, while loading submenu I can't determine the active URL in the menu when rendering, since it is a sub request

basically this part is not working: 
```
{{ app.request.uri == path(op.path, {'bank' : bank} ) ? "active" : '' }}
```
