### ISSUE TITLE
[Mailer] Set ESMTP Socket Stream Timeout

### ISSUE THREAD

**Issue by liberpater** [symfony/symfony#30868]
**Description**  
There isn't a way--that I could see--to set the SocketStream's timeout when using the ESMTP Transport.  Some mail servers have delays for spam prevention purposes and one of my clients Exchange servers requires a 30 second delay for any emails to an external address.  This causes it to timeout every time.

**Comment by fabpot** [comment]
Use `$mailer->getStream()->setTimeout()`

**Comment by appnator** [comment]
Symfony\Component\Mailer\MailerInterface doesn't have getStream() method

**Comment by abbul** [comment]
> Symfony\Component\Mailer\MailerInterface doesn't have getStream() method

Hi @appnator , I have the same issue. Could you solve it?

**Comment by leonelvsc** [comment]
Same here

**Comment by webiator-gmbh** [comment]
use Symfony\Component\Mailer\Transport\TransportInterface; instead of MailerInterface in order to be able to change the timeout. 

**Note that TransportInterface cannot send mail asynchronously.** So it is recommended to use MailerInterface. Wrap your send logic with try/catch in order to handle the 500 timeout error.

**Comment by karser** [comment]
I solved it for v4.4 by setting timeout in the decorated EsmtpTransportFactory::create method. I [blogged](https://karser.dev/symfony-mailer-increase-socketstream-timeout/) about it.
