### ISSUE TITLE
default_locale not passed to UrlGenerator

### ISSUE THREAD

**Issue by HypeMC** [symfony/symfony#30996]
**Symfony version(s) affected**: >=4.1

**Description**  
Symfony 4.1 introduced [Internationalized routing](https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing).
After defining a route with multiple locale I tried to generate a url with a command and got the following error:

```
Unable to generate a URL for the named route "locale" as such route does not exist.
```

The route:

```php
    /**
     * @Route({
     *    "en": "/locale",
     *    "hr": "/lokalno"
     * }, name="locale")
     */
```

The code that generates the url:

```php
$this->router->generate('locale');
```

After some playing around I realized that I need to explicitly set the locale in order for the url to be generated, which was strange since I had the `framework.default_locale` set to `hr`.

```php
// This works
$this->router->generate('locale.hr');
```

I did a little digging and noticed that the [UrlGenerator](https://github.com/symfony/routing/blob/4.2/Generator/UrlGenerator.php#L70) class has a `$defaultLocale` parameter and [the following code](https://github.com/symfony/routing/blob/4.2/Generator/UrlGenerator.php#L116):

```php
$locale = $parameters['_locale']
    ?? $this->context->getParameter('_locale')
    ?: $this->defaultLocale;
```

The problem is that the `$defaultLocale` parameter is [never set](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Router.php#L348) when the class is instantiated. I would expect the `framework.default_locale` parameter to be passed here.

**How to reproduce**  

```yaml
# framework.yaml
framework:
    default_locale: hr
```

```php
// Controller
class LocaleController extends AbstractController
{
    /**
     * @Route({
     *    "en": "/locale",
     *    "hr": "/lokalno"
     * }, name="locale")
     */
    public function index()
    {
        // ...
    }
}
```

```php
// Command
class LocaleCommand extends Command
{
    protected static $defaultName = 'app:locale';

    // ...

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln($this->router->generate('locale'));
    }
}
```

**Possible Solution**  

A possible solution would be to override the way the `UrlGenerator` class is instantiated in the [FrameworkBundle Router](https://github.com/symfony/framework-bundle/blob/4.2/Routing/Router.php) class and pass the `framework.default_locale` as the `$defaultLocale` parameter.

**Comment by fancyweb** [comment]
IIRC, it is possible to have an i18n route "my_route" (so its names are technically my_route.en, my_route.hr, etc.) and an unrelated route with the name "my_route".

Passing the default locale to the UrlGenerator would be a BC break because it would generate another route than currently with the default value.

I think we need to deprecate having a route with the same name than an i18n route so we can actually do something about this in Symfony 5.0.

**Comment by HypeMC** [comment]
Not sure it would be a BC break since the problem is that there's inconsistent behavior between the web and cli contexts. The route exists when generated in a web request cause it gets the locale from the request context (`$this->context->getParameter('_locale')`):

```php
class LocaleController extends AbstractController
{
    /**
     * @Route({
     *    "en": "/locale",
     *    "hr": "/lokalno"
     * }, name="locale")
     */
    public function index()
    {
        // This works
        return new Response($this->generateUrl('locale'));
    }
}
```

**Comment by X-Coder264** [comment]
Currently the same route generation call behaves differently depending on the context it's being run in (WEB or CLI). In a WEB context the above route would be generated just fine, while in CLI it'd throw an exception. The system does not behave consistently and I don't see how this can be treated as anything but a bug.

Another solution which would avoid this "breaking change" and allow us to make the behavior consistent no matter the context is adding another parameter (let's call it `router.request_context.defaut_locale` for example) which would work the same as all other similar parameteres as described in https://symfony.com/doc/current/console/request_context.html

Since that parameter doesn't exist yet it would always default to null unless explicitly set so the current behavior remains the same while it allows developers to override/customize it.

**Comment by stof** [comment]
Adding this new parameter looks good to me.

**Comment by HypeMC** [comment]
@stof Hm, but would we then have two different parameters/configuration options for the same thing, `framework.default_locale` & `router.request_context.defaut_locale`?

**Comment by stof** [comment]
We don't have `framework.default_locale`. We have `framework.translator.default_locale`, which will not exist at all if you don't enable the translator. So we cannot make it a hard dependency.

**Comment by HypeMC** [comment]
@stof Not sure what you mean, I was referring to the [FrameworkBundle configuration](https://symfony.com/doc/current/reference/configuration/framework.html#default-locale), which is set as [kernel.default_locale](https://github.com/symfony/framework-bundle/blob/4.2/DependencyInjection/FrameworkExtension.php#L180).

**Comment by stof** [comment]
hmm indeed. I confused things. Using the `kernel.default_locale` would indeed make sense then.

**Comment by xabbuh** [comment]
this looks related to #30010
