### ISSUE TITLE
[Twig\Debug] {{ dump() }} on any entity exhausting memory

### ISSUE THREAD

**Issue by fmonts** [symfony/symfony#31077]
**Symfony version(s) affected**:
4.2.5, but the issue started many versions ago

**Description**  
When using dump() on a Twig template to dump an instance of some entity, it fails for memory exhaustion (ex.: `PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 268451840 bytes`)

**How to reproduce**  
Controller:
```
public function someAction()
{
        return $this->render('template.html.twig', [
            'myItem' => $this-getDoctrine()->getRepository(Item::class)->find($id)
        ];
}
```
Twig:
    `{{ dump(myItem) }}`

If I use `dd($myItem)` in the controller, it works.

**Comment by ro0NL** [comment]
Could you share a reproducer app? I wasnt able to reproduce it using one of my own entities.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by fmonts** [comment]
I tried but unfortunately I've not been able to reproduce the issue in a new application. 

There is some loop happening on \vendor\twig\twig\src\Extension\DebugExtension.php on line 61, and it doesn't happen if I remove linked entities ($item->setUser(null), where User is a ManyToOne relationship.

I'll try again when I have more time

**Comment by kavalanche** [comment]
I have the same issue. Twig debug extension uses var_dump instead of dump and it runs out of memory. There is a dump extension, but I don't know why it's not used (debug extension is used instead).

symfony/twig-bridge                 v5.0.1
symfony/twig-bundle                 v5.0.1
twig/twig                           v3.0.0
symfony/var-dumper                  v5.0.1

**Comment by stof** [comment]
Instead `symfony/debug-bundle` and then it will be used. DebugBundle is the one responsible for wiring the var-dumper stuff.

**Comment by kavalanche** [comment]
Isn't it deprecated?

**Comment by kavalanche** [comment]
Documentation is misleading. `symfony/debug-bundle` is in fact working! This is the solution to this issue.

**Comment by stof** [comment]
`symfony/debug` is deprecated, due to replacing it with a better error handler component (as our error handling has been improved to be suitable for production too over time btw).

`symfony/debug-bundle` is *not* deprecated (and it is more about the `symfony/var-dumper` component than about the `symfony/debug` one btw).

**Comment by kavalanche** [comment]
Thanks for clarification.
