### ISSUE TITLE
[Request] Request::hasPreviousSession() inits session driver

### ISSUE THREAD

**Issue by Imunhatep** [symfony/symfony#31113]
**Symfony version(s) affected**: 4.2.x/master

**Description**  
Connection to session storage (e.g. redis) initialized by calling Request::hasPreviousSession() method.

**How to reproduce**  
Misconfigure session handler with incorrect endpoint, make a request and check previous session

**Possible Solution**  
Check if session name cookie is in request and it's value is not empty, do not touch Session instance.

**Comment by nicolas-grekas** [comment]
I just had a look at the code: checking that the session cookie requires getting its name first, which is something that the session gives.
The real issue is that creating the session should not trigger a connection to the backend.
This means that to me laziness is missing on the Redis connection side. Please have a look in this area.
`RedisSessionHandler` manages instances of `RedisProxy` for this reason.
I don't know how easy it is to configure. Could you please have a look?

**Comment by Imunhatep** [comment]
Im pretty sure this workaround will work with RedisProxy, but what to do with other session handlers like Memcached, Mongo, Pdo, e.t.c.?  And it's not very intuitive from Session docs, that states: 

> a session will actually start on demand, that is, if any session request is made to read/write session data

Here Request::hasPreviousSession() is called and for "some" reason Session handler initialized (

**Comment by nicolas-grekas** [comment]
"some" reason in readable in the code: to get the name of the session cookie.
The issue is not on the Session class but on the storage/handler side, which should be (made) lazy.

**Comment by Imunhatep** [comment]
From my point of view - it looks as a defense of current implementation rather than following logic, i.e. read COOKIE != connect to STORAGE.

If it feels as "by design" - may close the issue.

**Comment by nicolas-grekas** [comment]
Defense of current implementation is the most pragmatic argument :) Since there are other ways that require changing nothing, planning for potentially invasive changing might not be worth the invested time. But of course, my argument is easily defeated and I'd be happy to be proved wrong: someone should "just do it" ;)

**Comment by Simperfit** [comment]
Someone would like to take this ? I don't see how we can fix it in the Session class.
