### ISSUE TITLE
Built-in password hash migrations

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#31139]
#30955 is proposing adding a new event to hook into the password verification process and allow listeners to deal with clear text passwords. Thinking a bit about this approach, I have a different one to propose here.

The most important drawback of #30955 is that it's still up to the application to implement some custom code to run a "needs rehash" logic then a "persist new encoded password" one. The 2nd drawback is that this gives a trivial way to hook into the process to leak clear text passwords (inadvertently or not).

The boilerplate of a listener shouldn't be needed: security should be first class by default, and this means progressive migration of passwords should be built in and the default behavior.

Instead of adding this hook, I'd suggest adding two new interfaces (names/etc are draft):
```php
interface UpgradablePasswordInterface
{
    public function upgradePassword(string $encoded): void;
}

interface RehashAwarePasswordEncoderInterface extends PasswordEncoderInterface
{
    public function needsRehash(string $encoded): bool;
}
```

Then, a `UserPasswordEncoder` could call both methods when applicable inside its `isPasswordValid` method, and done.

WDYT?

**Comment by aschempp** [comment]
Would the `UpgradablePasswordInterface` be implemented by the user object? I think that could be problematic because the user object is not a service, so it possibly does not have access to the database. Maybe it should be on the `UserProvider` and get the user object in the method signature?

**Comment by teohhanhui** [comment]
`upgradePassword` needs the plaintext password to do its job.

**Comment by teohhanhui** [comment]
Calling `isPasswordValid` should not produce side effects. The caller should be in charge.

**Comment by dkarlovi** [comment]
How do you deal with several "generations" of users, some of which have their password in `algo1` (they haven't logged in since the upgrade to `algo2`), some in `algo2` (they have) and now you're moving to `algo3`.

Also, a comment I agree with here https://github.com/symfony/symfony-docs/issues/9356#issuecomment-369172755 points out you wish to rehash passwords (hashes) ASAP. This means passwords could be in several current states.

What we all agree with is that passwords should be kept as secure as possible at all times, so upgrading them to the latest / best currently available algorithm is definitely the end goal.

**Comment by teohhanhui** [comment]
> How do you deal with several "generations" of users, some of which have their password in algo1 (they haven't logged in since the upgrade to algo2), some in algo2 (they have) and now you're moving to algo3.

See https://github.com/symfony/symfony/issues/30914#issuecomment-482525127

**Comment by nicolas-grekas** [comment]
> How do you deal with several "generations" of users, some of which have their password in algo1 (they haven't logged in since the upgrade to algo2), some in algo2 (they have) and now you're moving to algo3.

there is nothing to do for passwords encoded/verified with`password_hash()` and `libsodium` as these strategies already know about many algos. Then, a chain encoder would provide migration from message-digest/pbkdf2/etc to them.

**Comment by aschempp** [comment]
@teohhanhui rehasing several algorithms is not a problem. Whenever the user logs in, you **already** have the clear text password. 

We have currently implemented such a solution in Contao (https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/User.php#L498-L510), as this already existed before we integrated Symfony. We have successfully migrated from SHA1 to SHA256 to bcrypt (using PHPs `crypt` method) and finally to the PHP `password_` methods that automatically know about password algorithms and rehashing. Whenever the default PHP encoding changes (e.g. to argon2), it would automatically re-hash it on the next login.

The *bad* part about this implementation is that we have to hardcode on the request parameters, because there is no way to retrieve the credentials from the security service. If one would implement a different security listener (e.g. http auth instead of form login), the migration would not work. That's what we try to solve here.

**Comment by stof** [comment]
I don't think that should be implemented in an interface extending PasswordEncoderInterface. The common way to switch algo for older users is to switch the PasswordEncoder selected by the factory (thanks to the EncoderAwareInterface on the User, which is precisely meant for that). In that case, the encoder cannot implement that interface. Doing that in a PasswordEncoder would actually require duplicating the logic of the EncoderFactory in that PasswordEncoder.

And upgrading the password of a user requires access to the raw password in some place (the place calling the newer PasswordEncoder) but also having access to the User to store the new hash and persist the change.

> there is nothing to do for passwords encoded/verified with`password_hash()` and `libsodium` as these strategies already know about many algos. Then, a chain encoder would provide migration from message-digest/pbkdf2/etc to them.

That answer is wrong. The whole point of having `password_needs_rehash` in the password API of PHP is precisely that you may want to handle the case of users having a hash using an older algo. Next time they login (and so give you the raw password), you may want to re-hash with the new stronger hash.

**Comment by nicolas-grekas** [comment]
I don't think my answer is wrong, so maybe I was not clear enough. Anyway, I'll make it work and that should settle what's possible or not ;)

**Comment by tgalopin** [comment]
> That answer is wrong

@stof I think you're saying the same thing.

**Comment by stof** [comment]
@nicolas-grekas you said there is nothing to do for these password hashes. I'm precisely saying that **there is** something to do for them. If the API tells us the password needs to be rehashed with the newer algo, we do need to handle it.

**Comment by crayner** [comment]
Hi Nicolas, 
This is what I have done with a bundle already.  Bundle will attempt to write the highest password encryption back to the storage, regardless of starting point.  I did not include plain password, but easy to add.
