### ISSUE TITLE
which version should i use if my php version < 7.1 and i need overload ?

### ISSUE THREAD

**Issue by Guojunzhou-git** [symfony/symfony#31141]
I need to use overload method to overwrite vars from .env file instead vars in OS env;
so I upgrade symfony/dotenv from ^3.4 to ^4.2;
then I deployed to test env, but our php version is 7.0.30 in test env;
```php
Fatal error: Uncaught TypeError: Return value of Symfony\Component\Dotenv\Dotenv::populate() must be an instance of Symfony\Component\Dotenv\void, none returned in /var/deploy/oem-sdk/vendor/symfony/dotenv/Dotenv.php:145 
```
then I found Type Void is supported in php 7.1;

so is upgrade my php the only way to sovle this? or do we have a version supported overload with php version lt php7.1?

**Comment by dmaicher** [comment]
So first of all I would suggest you to use the same php version locally on testing and also on production :blush: Otherwise there can always be interesting surprises like the error you mentioned above.

And yes, Symfony 4.2 requires php >= 7.1.3

https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Dotenv/composer.json#L19

So you need to downgrade the symfony packages or upgrade your php version.

**Comment by xabbuh** [comment]
You either need to upgrade to PHP +7.1.3 (which I'd highly recommend) or implement the method in your own code. I am going to close here as there is nothing to change on our side. Thank you for understanding.

**Comment by Guojunzhou-git** [comment]
> So first of all I would suggest you to use the same php version locally on testing and also on production 😊 Otherwise there can always be interesting surprises like the error you mentioned above.
> 
> And yes, Symfony 4.2 requires php >= 7.1.3
> 
> https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Dotenv/composer.json#L19
> 
> So you need to downgrade the symfony packages or upgrade your php version.

Thanks for your advice. Finally, I upgrade my php version on testing same to my local.
