### ISSUE TITLE
Validation cache warmer doesn't work for classes without constraints

### ISSUE THREAD

**Issue by jaikdean** [symfony/symfony#31214]
**Symfony version(s) affected**: 4.2.7

**Description**  
Warming the validation cache doesn't work for classes with no constraints, as no record is created for them. When an object of class `Foo`, with no constraints configured, is passed into the validator, the `LazyLoadingMetadataFactory` will try to parse the metadata for `Foo` as it finds nothing in the cache for it.

**How to reproduce**

https://github.com/jaikdean/symfony-validator-cache-warmup-bug-reproducer

Warm up the cache with `php bin/console cache:warmup`, then make a `GET` request to `/foo`. The cache will be written to, despite having already been warmed.

**Comment by fancyweb** [comment]
Status: Works for me 

The cache is never populated in the first place since `Foo` does not have any constraint. It works as expected. We obviously don't add all the project classes to the cache but only the ones that are mapped to an actual loader.

**Comment by jaikdean** [comment]
However, since Symfony finds no cache entry for the class, it tries to parse the validation constraints again. If the cache is warmed, this shouldn't really happen.

**Comment by fancyweb** [comment]
It doesn't parse the validation constraints **again**. The `ValidatorCacheWarmer` only warm classes that have at least one constraint. The class `Foo` has no constraint. So the cache is not warmed for this class.

**Comment by jaikdean** [comment]
I understand the reasons why, but thanks for clarifying and cleaning up the terminology. My point is that if I warm the cache, it shouldn't then have more written to it on the first request.

I'm aware Symfony doesn't support read-only filesystems for the cache directory, but in practice it's entirely possible, and very useful when hosting on cloud/containerised/serverless platforms. This issue is the last thing we're trying to resolve, as it pollutes our logs with warnings.

**Comment by nicolas-grekas** [comment]
Can you try enabling apcu if that's not already the case?
When enable, writes should happen only once, and not after, which should remove most warnings (only the first attempts would generate one instead of all requests)

**Comment by jaikdean** [comment]
In our case APCu wouldn't help as we're running in AWS Lambda, so we effectively don't have shared memory, and are on a read-only filesystem. We use Redis as a shared cache for some aspects, but warming the file-based cache completely during deployment is ideal.

**Comment by nicolas-grekas** [comment]
Can you please check #33413?

**Comment by nicolas-grekas** [comment]
#33413 doesn't work, because we cannot know all classes that might be validated at compile time.
The only option I see is on your side: turning the `cache.validator` service into a `NullAdapter`. Same for `cache.annotations` and `cache.serializer` as they are similar in this regard.

This will remove the warning.

```yaml
cache.serializer:
    class: Symfony\Component\Cache\Adapter\NullAdapter
```

I'm closing because there is no alternative (I might be wrong, but I don't see how I could be :) )

**Comment by Nyholm** [comment]
I faced this issue too. I dont have a perfect solution but I do got some workarounds and info that might be helpful. 

If you use annotations to specify serializer config or validation contraints, these will not be put in cache in `bin/console cache:warmup`. That is only for Yaml and Xml. That is because the `AnnotationLoader` dost not have `getMappedClasses()` (Give all classes with annotation). 

I've created a small bundle that make sure that annotation config will be in cache: https://github.com/Happyr/annotation-warmer
(It also includes an annotation linter). 

-------------

AWS Lambda is a read only filesystem. I do see a lot of error messages like: 

> file_put_contents(/var/task/var/cache/prod/pools/WmAtw511rM/5dc47665b21492.54451012): failed to open stream: Read-only file system

These could happen because we read metadata from a file that is not in cache, so Symfony is trying to save it back to cache. 

One solution is to create a read only cache adapter with a constructor like: 

```
use Symfony\Component\Cache\Adapter\AdapterInterface;
class ReadOnlyAdapter implements AdapterInterface
{
    private $pool;
    private $readOnly;

    public function __construct(AdapterInterface $pool, bool $readOnly)
    {
        $this->pool = $pool;
        $this->readOnly = $readOnly;
    }

   // ...
}
```

This cannot be dependent on the environment (`prod`/`dev`) because we need to warm the cache in `prod`. There should be an other env variable parameter that defines the value of `$readOnly`.

However, an alternative that works on AWS Lambda is to define another path to the cache folder. Because AWS Lambda is not 100% read only. You can write to the `/tmp/` directory. 

```php
final class Kernel extends BaseKernel
{
    use MicroKernelTrait;
    // ...

   public function getCacheDir()
    {
        // When on the lambda only /tmp is writeable
        if (false !== \getenv('LAMBDA_TASK_ROOT')) {
            return '/tmp/cache/'.$this->environment;
        }

        return parent::getCacheDir();
    }
}
```
