### ISSUE TITLE
[Workflow] Support for getting a workflow from registry using a class instead of an instance 

### ISSUE THREAD

**Issue by asimonf** [symfony/symfony#31506]
**Description**  
Right now, the only way to obtain the corresponding workflow from the registry is by passing an object of the object that the workflow supports. This feature would allow for obtaining the workflow without the object, but rather, with the class.

**Example**  

```
    $workflow = $this->workflowRegistry->get(Object::class);

    foreach ($objects as $object) {
        $workflow->apply($object, 'to_next');
    }
```

**Comment by lyrixx** [comment]
hello @asimonf 

Acutally, the workflow strategy use a https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/Registry.php#L38-L41 of [`WorkflowSupportStrategyInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/SupportStrategy/WorkflowSupportStrategyInterface.php#L19-L22)

And this interface works only with a subject (an object).

So this will not be possible.

But could I know your use case about this need? 

Note: If your are using the full stack framework, you can get it via the cointainer

**Comment by asimonf** [comment]
Hey, there, thanks for the answer. Why would it not be possible? Wouldn't implementing a `WorkflowSupportStrategyInterface` that takes a class name as a subject be enough? I don't see it as semantically incompatible with the contract proposed by the interface.

**Comment by lyrixx** [comment]
What is your use case ?

**Comment by Steveb-p** [comment]
@lyrixx I believe asimonf was trying to get a `Workflow` instance based on Workflow name specified in configuration.

It seems Workflow documentation will need a little update to indicate that new Controllers (with `ServiceSubscriberInterface`) have to access Workflow instances via their Registry (I've only realized that Registry exists by looking through issues and then checking my container for workflow related services).

**Comment by lyrixx** [comment]
> @lyrixx I believe asimonf was trying to get a Workflow instance based on Workflow name specified in configuration.

Yes, I understood this part, but I would like to know why he want to do that.

> It seems Workflow documentation will need a little update to indicate that new Controllers (with ServiceSubscriberInterface) have to access Workflow instances via their Registry (I've only realized that Registry exists by looking through issues and then checking my container for workflow related services).

The registry is not used when injecting a workflow somewhere. It's here only to get to a shortcut in twig template. That's why I don't understand.

In pure PHP (controller, service), it's better to inject the workflow directly (with autowiring if you have only only one workflow, or with configuration if you have many)

So again, I would like to know the real use case here, to help you to use the componant.

**Comment by Steveb-p** [comment]
> In pure PHP (controller, service), it's better to inject the workflow directly (with autowiring if you have only only one workflow, or with configuration if you have many)

In my app's case a particular workflow is used when an object being created is configured in a specific way - thus causing automatic creation and activation (via workflow) of another related entity. `Registry` handles this just fine for me, since it's not always used.

```php
    /**
     * @return array
     */
    public static function getSubscribedServices()
    {
        return array_merge(parent::getSubscribedServices(), [
            __CLASS__ . '::googleTagManager' => GoogleTagManager::class,
            __CLASS__ . '::dispatcher' => EventDispatcherInterface::class,
            __CLASS__ . '::getPathWorkflow' => WorkflowRegistry::class,
        ]);
    }

    public function getPathWorkflow(Path $path): Workflow
    {
        return $this->container->get(__METHOD__)->get($path);
    }
```

I might have gone with creating an event and dispatching it, and expecting a service to handle this specific case (you can consider this a violation of single responsibility principle) but it was easier to keep that code near the operation that it relates to (which from my perspective is easier to read, so it follows "keep it simple").

Is `Registry` not supposed to be used in userland code? Will workflow instances become private services in the future (I believe they are always public in 4.2)?

How can I lazy load Workflow in this case?

**Comment by lyrixx** [comment]
> Is `Registry` not supposed to be used in userland code?

You can use it, but, IMHO, this is useless when you already know what workflow instance you want to get. The registry is here only to get a workflow dynamically according to a subject.

> Will workflow instances become private services in the future (I believe they are always public in 4.2)?

Right know workflow service are public, they might become private at some point, but this does not change anything to this use case.

> How can I lazy load Workflow in this case?

Like you do, with a service subscriber:

```php
    public static function getSubscribedServices()
    {
        return [
                'workflow' => 'workflow.my_workflow',
                // or
                'workflow' => WorkflowInterface::class, // This work is you have only one workflow, and have aliased WorkflowInterface on the service workflow.XXXXXX
        ];
    }

    public function getPathWorkflow(Path $path): WorkflowInterface
    {
        return $this->container->get('workflow');
    }
```

**Comment by Steveb-p** [comment]
When using `getSubscribedServices()` with a service name instead of class, it results in an exception:
```php
    /**
     * @return array
     */
    public static function getSubscribedServices()
    {
        return array_merge(parent::getSubscribedServices(), [
            __CLASS__ . '::googleTagManager' => GoogleTagManager::class,
            __CLASS__ . '::dispatcher' => EventDispatcherInterface::class,
            __CLASS__ . '::getPathWorkflow' => 'state_machine.path',
        ]);
    }
```

```shell
In RegisterServiceSubscribersPass.php line 71:
                                                                                                                                                                                                                                                                      
  "AppBundle\Controller\Services\PageController::getSubscribedServices()" must return valid PHP types for service "AppBundle\Controller\Services\PageController" key "AppBundle\Controller\Services\PageController::getPathWorkflow", "state_machine.path" returned.  
```

I've checked the current master and it wasn't changed since version 4.2 that I'm using.

**Comment by lyrixx** [comment]
ping @nicolas-grekas

**Comment by lyrixx** [comment]
The initial issue was about retrieving a workflow according to the FQCN of a subject.
This is not supported and this could not be supported because it defeat the purpose of the registry.

Then this issue goes on another topic about service subscriber.
As I would like to not mix issue, I'm going to close this one. 

Feel free to re-open an issue about Service Subscriber is something is really wrong.

Thanks for reporting and have a nice day
