### ISSUE TITLE
[FrameworkBundle] Set only desired locales

### ISSUE THREAD

**Issue by proArtex** [symfony/symfony#31563]
**Description**  
There is no option to set locales that will be used in an app. FrameworkExtension is currently collect all the locales from different bundles (registerTranslatorConfiguration) and then it goes to Translator cache warmer. So I have many extra translations warmed up, but I want to use just a few. They are basically useless and take warmup time.

**Example**  
So `translation.yaml` might contain `available_locales` directive:
```
framework:
    available_locales: ['en', 'fr']
```
and registerTranslatorConfiguration() function might restrict Finder to that locales.

**Comment by javiereguiluz** [comment]
I think we should explore this idea. It's only a guess ... but the performance improvement should be noticeable because Symfony would track/parse fewer files and would created fewer catalog files.

**Comment by Pictor13** [comment]
I am having the same necessity.
There should be a way to define the locales available for the application.

Is there any progress on this?

**What would be a *workaround*, for the moment, in order to limit the list of available locales?**
Do we really need to uninstall the locales from the system, in order to hide them?
Or dunno if there's some *intl* build option  to specify it 😕

**Comment by Pictor13** [comment]
For the moment I solved with a custom LanguageType/ChoiceType that gets the whole list of locales and filters them with a list of languages enabled on the app.
But I am curious if any native solution is on the way.
