### ISSUE TITLE
[Form] Choice type empty value

### ISSUE THREAD

**Issue by ghostika** [symfony/symfony#31572]
**Symfony version(s) affected**: 4.2

**Description**  
Given a form type for a department with a field for the leader (UserType with data_class `User`). The UserType has a field, salutation with the type `ChoiceType Radio` with the given configuration:

```
->add(
      'salutation',
      ChoiceType::class,
      [
          'choices' => [
               'male' => 0,
               'female' => 1,
          ],
      'expanded' => true,
      'empty_data' => null,
      'required' => false,
      'placeholder' => null,
]
```
The leader person is set to `required => false`.

*Expectation*
If the form is sent, without filling in the leader, then the value should be `null`

*Happens*
The leader is created with `data_class` and everything is set to null.

In case, the salutation is removed from the types, it works as expected.
After digging in a little bit, I've found in Symfony FormType.phpL136 -> if data_class is set and the form field is not required and is empty, then the value is `null`. Problem is, the `isEmpty` check is always false, for the ChoiceType. The Request doesn't contain any value for the choice `salutation`. 
The root of the problem is at `isEmpty` in `Form.php`L724 `FormUtil::isEmpty($this->modelData)` as the model data for the radio buttons are `false`.

The only solution I've found so far is a `modelTransformer` for the choices:
```
            $builder
                ->get('salutation')
                ->get(0)
                ->addModelTransformer(new CallbackTransformer(
                    function ($value) {
                        return $value;
                    },
                    function ($value) {
                        return false === $value ? null : $value;
                    }
                ));
            $builder
                ->get('salutation')
                ->get(1)
                ->addModelTransformer(new CallbackTransformer(
                    function ($value) {
                        return $value;
                    },
                    function ($value) {
                        return false === $value ? null : $value;
                    }
                ));

```

**Comment by xabbuh** [comment]
I am not sure I understand the issue. Can you create a small example application that allows to reproduce it?

**Comment by ghostika** [comment]
I've created the example:
https://github.com/ghostika/symfony_choice_type_bug
Open `/test` and only fill in the first name. 
Width the 2nd dump, you will see that a `Boss` class is created, but everything is null.
After that, comment out the `salutation` in the `BossType` and now the 2nd dump will show `null` for Boss.

**Comment by fancyweb** [comment]
Status: reviewed

I analysed the reproducer because of https://github.com/symfony/symfony/issues/31927.

Yes there is a non logical behavior : unchecked checkboxes / radio buttons (subforms of `ChoiceType`) are never considered empty. When they are not checked, their norm data is `null`. This norm data is reverse transformed to `false` by the `BooleanToStringTransformer` that is added by the `CheckboxType`. `false` is not an empty value for `FormUtil::isEmpty()`.

Considering `false` as an empty value would be a BC break. However, all tests passes with this change.

How to resolve this behavior?

The model data of a `CheckboxType` being a boolean is right. We must not change it. Our problem is that in this particular case we want false to be considered as empty.

On 3.4, we can resolve this with an attribute that we would set in the `ChoiceType` and then add the `false === $this->modelData && $this->config->getAttribute('false_is_empty', false)` in the `Form->isEmpty()` method. Kind of ugly but it works with no BC break.

On 4.4, we could do a better fix by adding a new method to the `FormConfigInterface` interface `isEmpty($modelData): callable`. Each form type could declare its own method to decide if the passed model data is empty or not. `Form->isEmpty()` would just call `($this->config->isEmpty)($this->modelData)`. The current code in this method would be the default callable and would be added in the `FormConfigBuilder`.

WDYT @xabbuh?

**Comment by nicolas-grekas** [comment]
Reopening as there is something to consider for 3.4.
