### ISSUE TITLE
[DotEnv] loading priority and overriding

### ISSUE THREAD

**Issue by Preclowski** [symfony/symfony#31579]
**Symfony version(s) affected**: 4.2.8

**Description**  
I'm not sure is this feature or bug, but override priority of environment variables are little confusing. System variables always take precedence over dotenv files.

**How to reproduce**  
1. Export system environment eg. `DATABASE_URL=test1`
2. Add `DATABASE_URL=test2` to `.env`
3. Add `DATABASE_URL=test3` to `.env.local`
4. Add `DATABASE_URL=test4` to `.env.test`
5. Set `APP_URL=test`

Now check result in application.
`%env(DATABASE_URL)%` is equal to `test1`. In this particular environment I would expect it would be equal to `test4`. In docs there is no word about handling system environment variables. Now I'm not sure is this feature or bug.

It works perfect when `composer dump-env test`. I mean - when `composer dump-env test` `DATABASE_URL` is equal to `test4`. It's not only about behavior, but also about consistency. It also works well when system environment variable in system is not set.

**Possible Solution**  
Describe expected behavior of DotEnv component or fix if this is a bug.

**Comment by nicolas-grekas** [comment]
That a feature, not a bug. This is how `.env` files work in all technologies. Real env vars always have the highest precedence. Doc PR welcome if this is not clear enough.

**Comment by Preclowski** [comment]
And what you think about inconsistency in `composer dump-env test`. It doesn't include system envs.

**Comment by nicolas-grekas** [comment]
Where is the inconsistency? This behaves exactly the same as loading `.env` files.
dump-env is and should be real-env-insensitive, because it only provides default values,
the real env is used and has greater precedence.

**Comment by michalhalas** [comment]
So what I understand from it, is that (given .env exists and is loaded first), that in order for a variable to be loaded from .env.local, this variable must not exists in .env file (becuase we are not overriding those values once they are loaded), which is different to what's written in this manifesto https://symfony.com/doc/current/configuration/dot-env-changes.html.

There exists a function overload() that is used nowhere and would solve the issue if we used it instead of load() here https://github.com/symfony/dotenv/blob/master/Dotenv.php#L95 and all subsequent load()'s.

**Comment by nicolas-grekas** [comment]
https://symfony.com/doc/current/configuration/dot-env-changes.html is misleading if not wrong: real env vars are never overridden, but fake env vars are so that .env.local wins over .env only for those vars it defines.

This is accurate: https://github.com/symfony/recipes/blob/master/symfony/flex/1.0/.env

/cc @weaverryan

**Comment by nicolas-grekas** [comment]
Closing as there is no bug. Doc should be updated instead.

**Comment by kwisatz** [comment]
@nicolas-grekas I have a case where the `.env` takes precedence over a `.env.$APP_ENV.local` file created from decrypted secrets after `dump-env`.

It does definitely not correspond to what is stated in https://github.com/symfony/recipes/blob/master/symfony/flex/1.0/.env

Do I create a new ticket with `debug:dotenv` output? 
Also, can you please link to the docs in question, the link above 404s.

**Comment by nicolas-grekas** [comment]
Dunno the link anymore, but if you found a bug, please submit a new report with a simple reproducer. :pray:

**Comment by kwisatz** [comment]
> Dunno the link anymore, but if you found a bug, please submit a new report with a simple reproducer. 🙏

I just rubber-duck-resolved the issue by trying to write up a simple and concise reproducer. :duck:
