### ISSUE TITLE
[Config] Negative value for boolean-based parameter

### ISSUE THREAD

**Issue by pierredup** [symfony/symfony#31580]
**Description**  

While debugging an issue with the Webpack Encore config (symfony/recipes#591), I realised it's not possible to convert a boolean parameter to a negative value.

In this example, there is a config parameter to enable caching. Caching should not be turned on when debug is set to true, so for the option, you need to get the inverse value of the `kernel.debug` parameter. As far as I know, this is not currently possible, but I would expect to be able to use something like `cache: '!%kernel.debug%'` to convert the `kernel.debug` value (I.E set the config value to `false` if `kernel.debug` is true).

If this is something that will be considered, I'd like to open a PR but just need some guidance on where the best place would be to handle this (in the DI parameter bag, when resolving config values etc).

**Comment by javiereguiluz** [comment]
I don't think we should implement this. Symfony itself "needs" this in lots of places, but doesn't miss it. It's just a matter of reversing the code logic.

Instead of having a method called `enableCache()` which expects the negative value of `%kernel.debug%` ... create a `disableCache()` method which expects `%kernel.debug%`.

However, I'd recommend to pass the `%kernel.debug%` "as is" and store it in a `$debug` (or `$debugMode`, etc.) constructor argument and then make decisions in your own logic based on this parameter. Otherwise you are "changing" the purpose of "kernel.debug". This param tell you if the app is in debug mode or not, so it's not related to enable/disable cache, etc. It's related indirectly (if debug is on, disable cache, etc.). I hope you understand what I try to say 🙏 

So, I'm closing this proposal as "won't fix" for now for the reasons given above. Thanks.

**Comment by pierredup** [comment]
> It's just a matter of reversing the code logic

I don't think the code/config needs to change just to accommodate this parameter. In some cases, it makes more sense to have an `enableCache` method rather than `disableCache`.
E.G in the encore-bundle, the cache is disabled by default, and it makes sense there to only enable it when it's needed. It would be weird to change the config to `disable_cache` in that specific scenario. just to accommodate the `kernel.debug` parameter.

Also, the issue was about negating boolean parameters in general. The `kernel.debug` and cache issue was just an example that I came across which triggered the idea. I think there are other valid use cases as well. But I'll re-open the discussion if there are other use-cases that can be discussed which might be useful, so this can stay closed for now.
