### ISSUE TITLE
[DoctrineBridge] Embeddables are not read properly while introspecting validator's `PropertyMetadata`

### ISSUE THREAD

**Issue by phansys** [symfony/symfony#31743]
**Symfony version(s) affected**: 4.3.0

**Description**  
Doctrine's embeddables are not read properly while introspecting validator's `PropertyMetadata`:
```In PropertyMetadata.php line 40:
                                                                                             
  [Symfony\Component\Validator\Exception\ValidatorException]                                 
  Property "embeded_class.some_property" does not exist in class "App\Entity\MyEntity"  
                                                                                             
```

**How to reproduce**  

Update symfony/doctrine-bridge (v4.2.9 => v4.3.0)

**Comment by avramcosmin** [comment]
Having the same error here.

After updating Symfony to 4.3.0 [JWTRefreshTokenBundle](https://github.com/gesdinet/JWTRefreshTokenBundle) stopped working. I maintain an `Entity` class which is extending their `AbstractRefreshToken` class (just because I want a different table name for the refresh tokens).

**Comment by phansys** [comment]
As a workaround, you can update `composer.json` in order to conflict with this update:
```json
"conflict": {
    "symfony/doctrine-bridge": ">4.2.9"
}
```
I'll try to check where the issue came from: https://github.com/symfony/doctrine-bridge/compare/v4.2.9..v4.3.0
