### ISSUE TITLE
Updated from 4.2 to 4.3 and got deprecation

### ISSUE THREAD

**Issue by manu-sparheld** [symfony/symfony#31896]
Hi
I did run `composer update` 3 times. And symfony updated from 4.2 to 4.3. But I am getting below deprecation errors in logs:
```
 php.INFO: User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Calling the \"Symfony\\Component\\EventDispatcher\\EventDispatcherInterface::dispatch()\" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead. at /home/manu/sparheld/alpaka-core/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:148)"} []
```

**Comment by xabbuh** [comment]
This looks expected to me. New minor releases add deprecations for code that will be removed in the next major version. That's too help you prepare your application for the next major release which would otherwise break your application then if you'd still depend on the deprecated features.

Thus you will need to check where your application (or one of your dependencies) uses these deprecated feature and update accordingly.

I am closing here as there is nothing to fix. Thank you for understanding.
