### ISSUE TITLE
[Messenger] Plan delivery time of messages

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#32033]
Currently we're using a Redis based bus with the possibility to dispatch events with a planned delivery time in the future (scheduling, e.g. 3 days from now).

I believe SF messenger currently doesnt support it. In practice this could be done using eg. `dispatch($message, [new PlanDeliveryStamp('now +3 days')])`

Thoughts?

**Comment by alexander-schranz** [comment]
@ro0NL What is the difference to the `DelayStamp`? For redis its not yet implemented but we are working on it here: #31977

**Comment by ro0NL** [comment]
Hi @alexander-schranz , i wasnt sure "delaying" could serve the "scheduling" purpose. I thought it was meant to allow for an increasing delay between e.g. retries.

However, now looking at your PR this looks similar to what we are using; `ZADD` + `ZRANGEBYSCORE`. I should interpret "delay" as "time-to-live" correct?

**Comment by alexander-schranz** [comment]
@ro0NL the message can live longer. Delayed means the consumer will not get the message before this time so if the delay is 2hours, the consumer will get the message after 2 hours but if the consumer don't read messages the message will still be available in 3 hours or later so its not a timeto live of a message. The redis implementation the sorted set (zadd) ist just use to delay the messages before they are pushed to the stream because redis has no native support for delayed messages.

**Comment by ro0NL** [comment]
Thanks for explaining, i think this is what we're looking for yes. Subscribed to the PR.
