### ISSUE TITLE
Access Abstained with Voter

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony#32058]
**Symfony version(s) affected**: 4.2.9

**Description**  
Access Abstained with Voter

**How to reproduce**  
I have a basic voter and trying to check if current user can comment ( basic boolean )

I will include only the necessary code blocks

**UserVoter**
`case 'BLOG_USER_CC':
                if ( $user->getCanComment() ) {
                    return true;
                }
                return false;
                break;`

**User Entity**
`/**
     * @ORM\Column(type="boolean")
     */
    private $canComment;`

**Twig template**

`{% set perm = is_granted('BLOG_USER_CC') %}
{{ dump(perm) }}`

**returns false.**

`{% set uperm = app.user.CanComment %}
{{ dump(uperm) }}`

**returns true.**

**Possible Solution**  
Use **uperm** instead of Voter

Am I doing something wrong ?

**Comment by xabbuh** [comment]
Can you please create a small example application that allows to reproduce?

**Comment by cybernet** [comment]
https://github.com/cybernet/symfony-32058

**Comment by xabbuh** [comment]
Thank you for the example. Your issue is inside the voter itself. `return in_array($attribute, ['BLOG_USER_CC']) && $subject instanceof User;` inside the `supports()` method will always be `false` as `$subject` is `null`. Change it to `return in_array($attribute, ['BLOG_USER_CC']);` and your voter should work as expected. Closing here as there is no bug.
