### ISSUE TITLE
TokenStorageInterface no longer retrieving user after symfony update to 4.3

### ISSUE THREAD

**Issue by ChoppyThing** [symfony/symfony#32184]
**Symfony version(s) affected**: 4.3

**Description**  
I'm getting an issue when updating symfony version from 4.2 to 4.3. The problem arises when using TokenStorageInterface, i wonder if others have had the same problem. Has there been a breaking change that i missed ?

Using $tokenStorage->getToken()->getUser(); notably in a constructor no longer works as it was working in symfony 4.2.

**How to reproduce**

```
public function __construct(TokenStorageInterface $tokenStorage)
{
    try {
        if ($tokenStorage->getToken()) {
            $this->user = $tokenStorage->getToken()->getUser();
            if ($this->user instanceof User) {
                $this->score();
            }
        } 
    } catch (\Exception $e) {}
}
```
I wonder if the problem comes from using this in a constructor as it was working before.
Thanks for your help.

**Comment by linaori** [comment]
The problem is that you get the token in the constructor, this is error prone because at the moment of initialization of the service, the token might not be set yet. This all depends on when this particular service is initiated. Set the token storage in a property and retrieve the token when you need it.

**Comment by xabbuh** [comment]
I am closing here as this indeed is not a bug as explained by @linaori. Thank you for understanding.
