### ISSUE TITLE
[Messenger] Messages retried on failure transport lose exception metadata

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#32311]
**Symfony version(s) affected**: 4.3.*

**How to reproduce**  
* Try to handle a messenger message that fails... and allow it to fail until it goes to the failure transport
* Once on the failure transport, use `messenger:failed:retry` to retry the message. But, make sure it fails *again*.
* Try to view the specific information about the message - e.g. `messenger:failed:show <id>`. It will lose details about its exception. I think they are probably still there... but not being read correctly.

Message on failure transport before retrying:
![before](https://user-images.githubusercontent.com/121003/60448213-30d2f280-9bf3-11e9-9405-665b8bc001bd.png)

Message on failure transport after retrying:
![after](https://user-images.githubusercontent.com/121003/60448227-34ff1000-9bf3-11e9-92ba-229c82144083.png)

**Possible Solution**  
We need to figure out if the exception information is being lost on redelivery (and if that's the case, make it not lost) or if it is present, but not being read correctly.

**Comment by TimoBakx** [comment]
From what I can see, this happens because the message is sent to the failure bus with 0 retries listed in the `SendFailedMessageToFailureTransportListener`. Then, when running `bin/console messenger:failed:retry [id]`, the message is only retried once. Because the retry count is reset, the `SendFailedMessageToFailureTransportListener` is not triggered again, so only the `RedeliveryStamp` of the first try is added (in `Worker`, line 152) without any exceptions.

We could, in `Worker`, check previous `RedeliveryStamp`s to check if there are any exceptions in those, and then add them in the next one.

I've done this bit in #32341. Please let me know if I'm on the right track with this and I'll try to create unit tests for it.
