### ISSUE TITLE
[Messenger] no possibility to prevent retrying at this moment | UnrecoverableMessageHandlingException not working 

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony#32325]
v4.3.2

When using async transport, `UnrecoverableMessageHandlingException` business logic does not work at this moment at all.  
`Symfony\Component\Messenger\Middleware\HandleMessageMiddleware:82` wraps all `\Throwable`  (not only `UnrecoverableExceptionInterface` exceptions) occurred in handlers in `Symfony\Component\Messenger\Exception\HandlerFailedException`, when `Symfony\Component\Messenger\Worker:194` wants only `UnrecoverableExceptionInterface`.
At this moment the only possible solution to prevent retrying is disable totally retrying strategy.

To reproduce, just throw `UnrecoverableExceptionInterface` in any kind of async handlers (i did not test on sync handlers, but think that situation is the same). 

As a solution, it's be better to check payload of `HandlerFailedException` in `Worker`.

**Comment by Tobion** [comment]
Confirmed, see https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Messenger/Worker.php#L132-L136
Suggestion as bug-fix:
- When there is only one nested exception, use that to check for UnrecoverableExceptionInterface (most common situation with a single handler)
- When there are more than one nested exception, always retry (like now) because we can't really decide

Suggestion as new feature:
- Pass the exception to the RetryStrategyInterface. This way custom retry strategies can change the logic based on the exception and for example make a better decision when there are more than one nested exceptions in several handlers.

**Comment by weaverryan** [comment]
> Suggestion as bug-fix:
>  * When there is only one nested exception, use that to check for UnrecoverableExceptionInterface (most common situation with a single handler)

+1
> * When there is more than one nested exception, always retry (like now) because we can't really decide

Yes, certainly for 4.3. But also, we could (in `HandleMessageMiddlware`) attach the `HandledStamp` for that handler to effectively make it "look handled". A retry would only retry the *other* handlers. This could get a bit tricky, so I think it's ok to make a first bug fix PR without this, then tackle this later.

> Suggestion as new feature:
> * Pass the exception to the RetryStrategyInterface. This way custom retry strategies can change the logic based on the exception and for example make a better decision when there are more than one nested exceptions in several handlers.

That is certainly very sensible.
