### ISSUE TITLE
[HttpClient] Ability to add middlewares  

### ISSUE THREAD

**Issue by flaver12** [symfony/symfony#32367]
It would be nice to have the ability to add middlewares to the request.
I came up with this because I had the case that I use an API to get projects.
The API has a request limit, after that, it sends back a 429. In this case, it would be nice to have the ability to add a middleware that can react to that. 
Or in other cases where if you have a certain header to do something with it before it comes to the actual logic.

```php
<?php
$middlewares = Middlewares::create();
$middlewares->push($instanceOfMyMiddleware);
$this->client->request('GET', 'https://my-example-api.com/endpoint', ['middlewares' => $middlewares]);
```

**Comment by jsamouh** [comment]
@flack something like the PR ?

**Comment by ostrolucky** [comment]
I don't think approach in https://github.com/symfony/symfony/pull/32751 was right, but decorators are not a good substitute to good middleware system:

Decorator approach breaks laziness. If I need middleware which needs to read the response, doing it in decorator will trigger fetch as soon as calling `$httpclient->request(...)`, instead of normal Symfony httpclient behaviour - doing it when calling `$response->getStatusCode()` or `$response->getContent()` etc. Unless there is response resolve hook inside symfony httpclient, only workaround on my mind to do this would be necessity to have decorator not just for client, but for response and ResponseStreamInterface too.

Second problem. If I need to send another request from inside my decorator, it does not have access to outermost httpclient. Let's say I have `CredentialsRenewalDecorator` and `RetryDecorator`. Decorating `CredentialsRenewalDecorator` with `RetryDecorator` will cause requests triggered by `CredentialsRenewalDecorator` not being retried. Decorating `LoggingDecorator` with `RetryDecorator` will cause requests with expired credentials causing 401 responses triggered via `RetryDecorator` not being renewed.

**Comment by nicolas-grekas** [comment]
@ostrolucky :100:, that's exactly my point in https://github.com/symfony/symfony/pull/32751#issuecomment-515702398

**Comment by nicolas-grekas** [comment]
Additional requirement for extensibility: being able to add more "info" to the reponse (e.g. to allow `$response->getInfo('blackfire.profile_id')`)

**Comment by er1z** [comment]
Is this issue on any roadmap?

**Comment by brentybh** [comment]
So how to implement retrying 429 currently??

**Comment by flaver12** [comment]
Well I used the HTTPlug Lib to implement it.

**Comment by nicolas-grekas** [comment]
This issue is going to be fixed by #36779. I'm super happy about the design and the capabilities it gives :)

**Comment by Amunak** [comment]
Can I just say that using decorators is the absolute worst way to configure the client? There is very little control over when they get registered and because of the fuckery where we have a default HttpClient that then gets re-used under Scoped clients (while they're all tagged as http clients) it's a nightmare to register properly and you can easily end up in a situation where you either register something "too high" and it doesn't receive configuration from Scoped clients or it registers multiple times so your "middleware" is now called twice because you registered it on all http clients (which includes the reused inner one, too).

It would probably be beneficial if Scoped clients always used their own, separate HTTP Client that's not tagged. Or IDK. *Something* to allow for easier configuration.

Additionally there's like no documentation on how to do it properly; basically if the default configuration / clients aren't enough one has to write their own decorator, understand how to register it, etc. and all without any help. :c

**Comment by DaanBiesterbos** [comment]
I would like a neat way to, let's say, fetch a short lived token. It's just too complex right now. That said, you can decorate the http client to implement a customized solution to "add" middleware. So the real question is, should Symfony provide middleware out of the box.

I would like it. But I did implement something myself before that works well, but it might not always work. Considering http2/async etc. 
Symfony would have to implement something that works perfect under all circumstances. And if you need something custom it should be relatively easy. And the decorator approach does avoid restrictions or other complexities. It is very easy to decorate the client. However, in the real world people don't understand how to do it, or instantiate http client's themselves etc. Being able to "wire" your client, including handling authentication would, I think, avoid people doing whatever and wherever.

It would therefore be nice to have little bit more control over the static clients.
Perhaps a decorator that triggers events, or a way to register a header factory per scoped client that's executed every time we send a request with that client. I think this would solve my issue 9 out of 10 times.
