### ISSUE TITLE
Cleanup the new ErrorHandler component

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#32605]
Right now, this component is a copy/paste from Debug, but it can and should diverge now.

Here are things that should be done, to be confirmed by trying:
- [x] remove ExceptionHandler: we don't need anymore to recover from failed userland rendering (https://github.com/symfony/symfony/pull/32637)
- [x] remove the FatalErrorException class and namespace: this doesn't apply anymore since PHP7, right? (https://github.com/symfony/symfony/pull/33053)
- [x] add type declarations (https://github.com/symfony/symfony/pull/32812)
- [x] support Throwable directly (https://github.com/symfony/symfony/pull/33038)
- [x] decouple from the ErrorRenderer component (https://github.com/symfony/symfony/pull/32637)

/cc @fancyweb @yceruto as you like this part of the code base :)

**Comment by yceruto** [comment]
Yes, I'll take a look soon :+1:

**Comment by fancyweb** [comment]
> remove the FatalErrorException class and namespace: this doesn't apply anymore since PHP7, right?

@yceruto Looking at this.

@nicolas-grekas I have several questions.

Al of our own fatal error handlers are indeed useless since PHP 7. However, the `ErrorHandler::getFatalErrorHandlers` is an extension point that allow userland to define their own handlers. Removing it is removing a feature. So should we just remove our own useless handlers and keep the behavior or remove our handlers + deprecate the method to remove it later with all the associated behavior or just remove everything since it's a new component?

Also, should we clean the Debug component as well or we just let it die with unneeded classes?

**Comment by Tobion** [comment]
Debug component is deprecated. No point in changing that.

**Comment by vudaltsov** [comment]
It seems that `E_STRICT` can be dropped, because it's not used anymore in PHP 7. See https://wiki.php.net/rfc/reclassify_e_strict

**Comment by fancyweb** [comment]
For information, I'm working on handling \Throwable directly in ErrorHandler::handleException() too. 

@vudaltsov Are you able to take care of the `E_STRICT` removal?

**Comment by vudaltsov** [comment]
@fancyweb , yes, I am. Will look at it tomorrow.

**Comment by derrabus** [comment]
I like where this is going. May I reopen #26514?

**Comment by fancyweb** [comment]
About the `E_STRICT` removal: I think we need to keep it. The constant was not removed from PHP so users can still trigger with this level.

**Comment by vudaltsov** [comment]
@fancyweb , that's a nice point, fully agree. But then we can add a deprecation there, so that devs stop triggering `E_STRICT`.

Earlier I promised to help with this. But I got a new job and don't have much time at the moment.

**Comment by yceruto** [comment]
All tasks completed so far, thank you to everyone involved!
