### ISSUE TITLE
[PropertyInfo] Property case depends on the second character's case

### ISSUE THREAD

**Issue by jdsaphir** [symfony/symfony#32656]
**Symfony version(s) affected**: 4.3.2

**Description**  
Using camelCase, with an attribute `$aFooBar`, naming the getter/setter `getAFooBar()`/`setAFooBar()` returns the property name as `AFooBar` instead of `aFooBar`.

I'm not sure if this is a bug or intended behavior, but it seems weird that the second character's case dictates the first character case, as:
- `getAFooBar` returns the property name as `AFooBar` (1&2 uppercase => 1&2 uppercase)
- `getAfooBar` returns the property name as `afooBar` (1 uppercase & 2 lowercase => 1&2 lowercase)

Found it out the hard way through api-platform/core#2941

Generating the getter with `make:entity` from the attribute `$aFooBar` generates `getAFooBar()` which in turn gives the property name `AFooBar`.

**How to reproduce** 
Create an entity such as the one below and get its properties.
```PHP
// ./src/Entity/UDemandeur.php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\UDemandeurRepository")
 * @ORM\Table(name="U_DEMANDEUR")
 */
class UDemandeur {
    /**
     * @ApiProperty(identifier=true)
     * @ORM\Id()
     * @ORM\Column(type="string", name="U_DEMANDEURID", unique=true, length=255)
     */
    private $uDemandeurId;

    public function getUDemandeurId(): ?string
    {
        return $this->uDemandeurId;
    }
}
```

**Comment by s1k3s** [comment]
This can be reproduced on 3.4. @xabbuh This issue concerns PropertyInfo, not PropertyAccess and it's caused by this condition here:

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php#L122

Basically in this case the first letter is not lowercased because it passes the regex test. I'm not sure what the fix should be, but I tend to agree with the comments in the api-platform issue that we should probably define a list of rules based on which we perform the extraction and document it somewhere.

You could update the condition to something like this:

```
if (!$reflectionClass->hasProperty($propertyName) &&
       (!preg_match('/^[A-Z]{2,}/', $propertyName) || preg_match('/^[A-Z]{2}/', $propertyName)))
```
but then it would break other cases such as:
```
class MyClass
{
    public function getDOB()
    {
    }
}

// would return dOB
```

**Comment by jdsaphir** [comment]
Would it be enough to check if the property is in full caps maybe?
