### ISSUE TITLE
Export format in Encoder

### ISSUE THREAD

**Issue by CvekCoding** [symfony/symfony#32727]
I found in my project that it will be helpful if `EncoderInterface`  will have third method `getFormat()`.

Example where it will be helpful:
```
abstract class AbstractExporter
{
    abstract protected function getEncoder(): EncoderInterface;

    /**
     * @return string
     */
    public function export(): string
    {
        $object = $this->getObject();

        return (new Serializer([new ObjectNormalizer()], [$this->getEncoder()]))
            ->serialize($object, $this->getEncoder()->getFormat());
    }
}
```
In my example child has to implement only 1 method. But with a current `EncoderInterface` it's impossible and I have to implement additional method like `abstract protected function getExportFormat(): string` which is redundant I believe, because format is already hardcoded in `Encoder` and I simply duplicate this info.

@dunglas WDYT?

**Comment by stof** [comment]
There is nothing preventing a given Encoder to support multiple formats today.

Adding this third method in the interface would then reduce the possibilities of the interface.

Also, the common usage of the Serializer would be to configure the instance with all support encoders (and inject it with DI rather than instantiating it inline), and so your exporter would need only `getFormat`, but not `getEncoder`.

**Comment by CvekCoding** [comment]
@stof , thanks for explanation, agree.
I'm closing this issue.
