### ISSUE TITLE
[Symfony/intl] French DOM/TOM into the country list

### ISSUE THREAD

**Issue by Prometee** [symfony/symfony#32744]
**Symfony version(s) affected**: all

**Description**  
Getting the list of countries to use it into Sylius, I was surprise to found [DOM/TOM](https://fr.wikipedia.org/wiki/France_d%27outre-mer) into the list and I'm wondering if other non real countries are listed into `Countries::getNames()`.
They have ISO 3166-2 codes but they are not countries.
Here is the complete list :

| ISO 3166-2 | French label |
|-|-|
| BL | St. Barthélemy |
| GP | Guadeloupe |
| MF | St. Martin |
| MQ | Martinique |
| NC | New Caledonia |
| PF | French Polynesia |
| PM | St. Pierre & Miquelon |
| RE | Réunion |
| TF | French Southern Territories |
| WF | Wallis & Futuna |

**How to reproduce**  
https://symfony.com/doc/current/components/intl.html#country-names

**Comment by Prometee** [comment]
The complete list of non countries codes can be found here I guess :
https://en.wikipedia.org/wiki/ISO_3166-2#Subdivisions_included_in_ISO_3166-1

**Comment by ro0NL** [comment]
> There is no hard and fast definition of what regions are countries and which are not. (https://en.m.wikipedia.org/wiki/Country)

From https://en.wikipedia.org/wiki/ISO_3166-2#Subdivisions_included_in_ISO_3166-1 it starts already with

> For the following countries

:thinking:

**Comment by nicolas-grekas** [comment]
Not on our side, that's how international standards do it.

**Comment by Prometee** [comment]
@nicolas-grekas and @ro0NL according to the ISO website : https://www.iso.org/iso-3166-country-codes.html

    The purpose of ISO 3166 is to define internationally recognized codes of letters and/or
    numbers that we can use when we refer to countries and subdivisions.

So, if we expect a list of countries with: `Country :: getNames()` and this list mixes countries and subdivisions, this detail should be at least mentioned or explained somewhere.

An intermediate solution could be creating a second class allowing us to get those specials subdivisions like for exemple : `CountrySubdivisions::getNames(string $baseCountryCode=null)`
or to create a method : `Countries::getSubdivisions(string $baseCountryCode=null)`

**Comment by ro0NL** [comment]
> Country Codes - ISO 3166
> The International Standard for country codes and codes for their subdivisions.

The way i see it "county codes" is the common denominator ... to label things.

Ultimately ISO provides us the "list of country codes", and it includes subdivisisions ... not sure we need to do anything about it (or put different; we shouldnt deviate from the international standards)

I think the more practical reasoning is: can we send postal mail to it? If so; it's a country IMHO.

**Comment by javiereguiluz** [comment]
@Prometee I agree with you. I tried to explain why here https://github.com/symfony/symfony/pull/31350#issuecomment-489568341  but I couldn't convince others 

@ro0NL this is where the error lies I think -> *"The way I see it "country codes" is the common denominator ... to label things."*. The list contains "countries" + "other things" ... that's why "countries" cannot be the common denominator.

Also, ISO standard says this:

![image](https://user-images.githubusercontent.com/73419/62188782-b7ebc580-b36d-11e9-9495-b1a2ca674e00.png)

And the original source of information, the United Nations, says this:

![image](https://user-images.githubusercontent.com/73419/62188795-c20dc400-b36d-11e9-9465-fe6ef074ec06.png)

So, even the source of the information says that these are "regions" (countries + areas + cities + territories) and that they don't dare to say that these are only countries.

We should probably keep things like they are on our side because it's too late to change ... but sadly we should expect to receive more issues in the future about this.

**Comment by nicolas-grekas** [comment]
Geopolitics is not our business.
We use an official source and we stick to it.
That's the only way to deal with this.

**Comment by Prometee** [comment]
> I think the more practical reasoning is: can we send postal mail to it? If so; it's a country IMHO.
> (it should be available in the country selector)

@ro0NL if I want to send a postal mail to somebody in `Martinique (MQ)` and I put Martinique instead of France for country it will be delayed because Martinique is not a country but it's a subdivision of France.

Other exemple I want to use `Symfony\Component\Form\Extension\Core\Type\CountryType` as a country field for an e-commerce billing form. If somebody select Martinique instead of France and I don't know Martinique is an available country **because I trust symfony tools**, maybe some auto process like computing VAT or else will be wrong because of those non-country codes. I'm sure other critical exemples can be found.

@nicolas-grekas the list is a source of data and you are already filtering it so why avoiding us to filter it again ?

**Comment by ro0NL** [comment]
VAT numbers start with  ISO 3166-1 alpha-2 country codes, thus `MQ` should be valid as such

> if I want to send a postal mail to somebody in Martinique (MQ) and I put Martinique instead of France for country it will be delayed because Martinique is not a country but it's a subdivision of France.

what do you mean with "delayed", is it technically incorrect to select `MQ` instead of `FR`, if you actually intend it as such?

ultimately Symfony doesnt provide a address type, only a ISO 3166-1 alpha-2 list of "country codes", so it's more or less up to the application how to interpret that list.

**Comment by Prometee** [comment]
A VAT number of a company from Martinique will start with `FR`

> what do you mean with "delayed", is it technically incorrect to select MQ instead of FR, if you actually intend it as such?

`delayed` because postal services are auto processed and if an address is not recognized a human manual check can be required at the end delaying your postal mail.

> ultimately Symfony doesnt provide a address type, only a ISO 3166-1 alpha-2 list of "country codes", so it's more or less up to the application how to interpret that list.

"country codes" is different from "countries and subdivisions" at least it has to mention somewhere, isn't it ?

**Comment by ro0NL** [comment]
i figured the "country" is determined based on postal code
 https://www.grcdi.nl/gsb/martinique.html#H00D7F69F12785BD324517C9F11E876C5DA47CA5D048A2AA2AMartiniqueA20A2DA20A5BA5BAddressesA7CAddressA20formatsA5DA5DA2AA2A00100401101401701A01D02903303D040043046
 https://www.grcdi.nl/gsb/france.html#H85366ACFB2D528ADAAC46564CEB84F59E801344D030A5BA5BAdministrativeA20districtsA20graphicA5DA5D00100401502102B02E

> "country codes" is different from "countries and subdivisions" at least it has to mention somewhere, isn't it ?

yes and no :) 

https://en.wikipedia.org/wiki/ISO_3166

> defines codes for the names of countries, dependent territories, special areas of geographical interest, and their principal subdivisions (e.g., provinces or states). The official name of the standard is Codes for the representation of names of countries and their subdivisions.

so maybe we're a  bit wrong, however we don't have this much of detail, only the "list of codes" and we call it countries.

After all maybe sticking with `Regions` was a better call :(, yet i still tend to believe "country codes" is a common enought reference for "ISO 3166-1 alpha-2"

so eventually this is a naming concern at most, not an implementation one per se.

**Comment by ro0NL** [comment]
btw if we have a reliable source of such a mapping, we can surely implement e.g. `Countries::isSubdivision/getSubdivisionFor()` to support building your business logic. But more data/sources is more complex, so we need to be sure

**Comment by VincentLanglet** [comment]
Just encountered a bug because someone selected `Martinique` in the CountryType instead of `France`

In the list of country of the wikipedia article, 
https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
there is a `Sovereignity` column.
So there is a clear difference between `UN member state` or a related to another country.

The word `Country` is really misleading.
You can say that it's follow the IsoCodes, but for the `CountryType` the description is 

> The CountryType is a subset of the ChoiceType that displays countries of the world.

And this is not real countries.
