### ISSUE TITLE
FORM allow nulls

### ISSUE THREAD

**Issue by bitgandtter** [symfony/symfony#32804]
**Description**  
Forms allow empty data but do not differentiate empty values from null. Suppose we have a REST API with a PUT endpoint to edit some resources. If we send '' empty string form will recognize it as empty data and if we don't send the value at all it will also recognize it as empty data.

The form should be able to differentiate between empty data sent or not sent. 

In current behavior:

- if data is not sent and empty_data is set to '' (empty string) then it will replace with empty_data
- if data is not sent and empty_data is not set then it set null
- if data is sent as '' (empty string) and empty_data is set to '' (empty string) then it will replace with empty_data
- if data is sent as '' (empty string) and empty_data is not set then it set null

there we miss an option to allow a combination of above so if we take option 4 and we want the empty string sent we will get a null 

**Example**  
I have created this mini-project https://github.com/bitgandtter/sf_form where current behavior can be tested.

**Comment by linaori** [comment]
In my opinion forms are not suitable to act as API, you're better off using something like Api Platform or perhaps FOSRestBundle. The form component is specifically built around how HTML forms work.

I also disagree with the idea behind `empty_data` in Symfony, you're better off setting default values through the data binding when creating forms as default data is part of your dataset and not template.

> The form should be able to differentiate between empty data sent or not sent.

The form expects a value to be somewhere when it's mapped, because that's what the rendered form is supposed to send.
