### ISSUE TITLE
[BC break] Exception thrown when "session save path is ignored without a handler service"

### ISSUE THREAD

**Issue by luispabon** [symfony/symfony#32837]
**Symfony version(s) affected**: 3.4.30

**Description**  
Upon update from 3.4.29 to 3.4.30 a new exception is being thrown by framework bundle when save_path is used at framework.session when handler is set to null. This breaks previously working config (site doesn't use sessions).

It was introduced here: #31620

**How to reproduce**  
https://github.com/phpdocker-io/phpdocker.io/blob/master/app/config/config.yml#L30

That was IIRC default config. Site doesn't use sessions.

**Possible Solution**  
Remove the LogicException and instead throw a deprecation warning.

**Comment by gnat42** [comment]
Definitely related - I'm not sure what the best course of action is.

**Comment by gnat42** [comment]
So when I submitted the PR, I did mention that I wasn't sure if it was considered a BC, but that the default setting has two problems.

* When the session handler is null the save_path is ignored. This may be fine and still work however
* When php is run as a non-standard user like can be done in an php-fpm, session files can't be stored and everything silently stops working.

Thus, it is a BC but no one addressed that part of my PR/question and then it got merged. The solution to me is to fix the default to either remove the save_path or change the handler_id. Obviously now that this is in there it may some issues. Like just reported. I hit the same because my dev and prod weren't 100% identical.

I'm willing to help with fixing it but would need some guidance on what should be done I wasn't evern 100% sure what the proper solution was as you could see in my messages in #31620. Totally open to ideas or clarification on what should have happened there.

**Comment by luispabon** [comment]
As a user I totally get where that change's coming from.

So I would recommend reverting (at least the `LogicException` part) from 3.4 & 4.2+ but not master (5.0) and issuing a deprecation warning on 4.4.

**Comment by javiereguiluz** [comment]
I can confirm this BC break too when updating from Symfony 4.3.0 to 4.3.3:

![image](https://user-images.githubusercontent.com/73419/62834410-178a8080-bc4c-11e9-842d-89e0e8c2acc9.png)

**Comment by nicolas-grekas** [comment]
I like @luispabon's proposal - anyone up for doing the PRs?

**Comment by luispabon** [comment]
I can do it.

**Comment by luispabon** [comment]
What would be the procedure to do this? Open separate PRs per branch? Please bear with me as my contribs to symfony can be counted in the 1s

**Comment by nicolas-grekas** [comment]
One PR for 3.4 for the revert, one for 4.4 for the deprecation. The one for master after they're both merged.

**Comment by luispabon** [comment]
Thank you. There would be no PR for master wouldn't it? We're keeping the current behaviour as is for 5.0+

**Comment by nicolas-grekas** [comment]
Offending commit revert in 1d7114957b
