### ISSUE TITLE
[DX] RouteCollection::all and descriptors are not always consistent

### ISSUE THREAD

**Issue by kix** [symfony/symfony#32880]
**Symfony version(s) affected**: all versions probably, `master` and `4.4` certainly

**Description**  
Whenever running `bin/console debug:router`, I expect the return result to be sorted in the same way to make text debug output comparisons possible.

**How to reproduce**  
For example, I'm migrating several routes in my app from annotations to YAML (or the other way around). I've migrated the routes in a feature branch, ran `debug:router --show-controllers` and compared the output to what I had before the migration. The comparison rendered not really helpful since the routes do not have a guaranteed sort order.

This in turn leads to that the resulting `RouteCollection` is populated with routes in a different order. After that, the console `TextDescriptor::describeRouteCollection` simply calls `RouteCollection::all`, which also does not guarantee a sort order.

**Possible Solution**  
I see several solutions here:

- Add a `ksort()` call to `RouteCollection::all()`, so that `RouteCollection` always appears to be in the same sorted state.
- Add a `ksort()` to be called each time when a route is added to the collection (could affect performance though)
- Add a `ksort()` call to all of the descriptors' `describeRouteCollection` methods

**Comment by kix** [comment]
I see that expectations for `RouteCollection` have been specified in 0a1cfcdb5f0f75ad8c69506879eb5b8c38436d35 by @Tobion. That's where the test was added to check that `->addCollection() imports routes of another collection, overrides if necessary and adds them at the end`. What's the reason behind this? I could explore the changes possible in `RouteCollection` If I knew.

**Comment by Tobion** [comment]
Route order is very important because it defines which routes match first. So we can't just sort them as suggested. Also the debug:router list routes exactly in the order they are defined which is what we want. If you migrate your routes, you want them to stay in the same order by importing them the right way. If the order of routes does not matter in your case, you can simply sort the output of debug:router yourself I would suggest. Closing for the reasons given.
