### ISSUE TITLE
Allow voter without attribute

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#32950]
**Description**  
In Symfony 4, I used sometimes Voter who only checks the subject.
```
    public function supports($attribute, $subject)
    {
        if (!$subject instanceof Contract) {
            return false;
        }

        return true;
    }
```
With the following annotation
```
@IsGranted(subject="contract")
``` 
This was useful when we wanted to do the check every time, no matter the attribute.

With the previous annotation, it seems that attribute was `null` in the voter.

Now, with the typehint of the Voter
```
    /**
     * Determines if the attribute and subject are supported by this voter.
     *
     * @param string $attribute An attribute
     * @param mixed  $subject   The subject to secure, e.g. an object the user wants to access or any other PHP type
     *
     * @return bool True if the attribute and subject are supported, false otherwise
     */
    abstract protected function supports(string $attribute, $subject);

    /**
     * Perform a single access check operation on a given attribute, subject and token.
     * It is safe to assume that $attribute and $subject already passed the "supports()" method check.
     *
     * @param string         $attribute
     * @param mixed          $subject
     * @param TokenInterface $token
     *
     * @return bool
     */
    abstract protected function voteOnAttribute(string $attribute, $subject, TokenInterface $token);
```
It's not possible anymore.

Would it be a bad idea to typehint `?string` instead ?

**Comment by VincentLanglet** [comment]
Hi @derrabus. I saw you're the one who added the typehint in this file.
This may interest you.

**Comment by derrabus** [comment]
Having `null` as an attribute looks odd to me. I'm unsure if that was really an intended execution path of that component.

I mean, you can basically fix this on your side annotating `@IsGranted("some_dummy_attribute", subject="contract")`, right? Your voter can still choose to ignore the attribute in that case.

**Comment by VincentLanglet** [comment]
> I mean, you can basically fix this on your side annotating `@IsGranted("some_dummy_attribute", subject="contract")`, right? Your voter can still choose to ignore the attribute in that case.

Indeed, I can even fix this with
```
@IsGranted("", subject="contract")
```
But i'm kinda not happy with the solution of giving this default value everytime.
 
Instead of allowing a null value, do you think it is a better idea to make the default value of the attributes in the `@IsGranted` to "" ?

**Comment by xabbuh** [comment]
Why don't you pass the contract as the attribute instead?

**Comment by derrabus** [comment]
@xabbuh Same problem: the contract might not be a string.

**Comment by derrabus** [comment]
The authorization checker is designed around the concept of string attributes that you can vote on. To me it feels wrong to attach semantics to `null` or the empty string. Also, the DX of this isn't really nice, as the web profiler will tell you that a vote has been cast on `null`. On top of that, voters that ignore the attribute name will break as soon as you decide that you want to introduce a second permission on the same subject, (e.g. differ between read and write access).

I'd really recommend to use a meaningful attribute name when checking permissions. Something like `@IsGranted("read_access", subject="contract")`. If that is too verbose for you because it's always the same attribute that you decide on, you might consider to create your own annotation that presets the attribute name.

So far, voting on `null` attributes looks like an execution path that has worked by accident and I'm not really convinced that it should be restored or advertised.

**Comment by VincentLanglet** [comment]
Thanks for your explanation.

Can you just develop the following point ?

> On top of that, voters that ignore the attribute name will break as soon as you decide that you want to introduce a second permission on the same subject, (e.g. differ between read and write access).

I add on purpose this in my `security.yaml` in order to avoid break with many permission.
```
access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false
```

When the voter is specific, I use an attribute.
When the voter is not specific and should be use everytime we want to check the subject, I don't use attribute.
