### ISSUE TITLE
[Mailer] Send batch message

### ISSUE THREAD

**Issue by romaricdrigon** [symfony/symfony#32991]
Hello,

A common use case is to send a "batch" emails, meaning sending an identical message to many users, without having all the recipients seeing each other addresses.
Most email transport providers offer the option, as [Postmark](https://postmarkapp.com/developer/api/email-api), [Mandrill](https://mandrillapp.com/api/docs/messages.JSON.html), [Mailgun](https://documentation.mailgun.com/en/latest/user_manual.html#batch-sending), etc. 
The benefit is to have only one network per e-mail call instead of one per recipient, it is a substantial difference when doing mass mailing.

It would be great to expose such a possibility to the developer in the Mailer component.
Ultimately, it is up to the Transport to either send the e-mails as a batch (if the provider offers such an API) either to loop over each recipient (for instance, for SMTP).

Regarding implementation, I thought of different possible ways:
 - decorate `Email`, as in `BatchEmail `. A `BatchEmail` would receive an array of recipients in `BatchEmail::to()`. It would override some (internal) logic which is not valid anymore. The issue is that `Email` is already decorated with `TemplatedEmail`, so eventually we would end up with `BatchTemplatedEmail`.
 - keep `Email` as it is, but add a `BatchAddress`. I didn't quite explore the code there, I think `Email` class will have to be modified to handle that. So it will add some complexity there.
 - add a flag in `Email` class like `$enableBatch`, which would make multiple recipients in `To` field receive each one a separate e-mail. That's how some providers (Mandrill, Mailgun) work. I don't find it extremely clear.

I realized this feature missed as I was working on a project - I could try to get some code done, but I wanted to RFC before working on something :)

**Comment by xabbuh** [comment]
Doesn't it work if you use `addBcc()`/`bcc()`?

**Comment by fabpot** [comment]
The Symfony Mailer component is for transactional emails, so this feature is not supported and should not be (it was removed a very long time ago in Swiftmailer for that reason as well).

**Comment by romaricdrigon** [comment]
Well, that solves it then. Transactional multiple recipients e-mail is a use case (cf. Mandrill, they provide an API for that), but I guess it is minor (and uncommon).

**Comment by fabpot** [comment]
Note that you can send the same email to several recipients by adding more `To`s. That's supported. That should cover your use case, right?

**Comment by fabpot** [comment]
Or you can use `Bcc`s (with no `To`), that's supported as well.

**Comment by romaricdrigon** [comment]
`Bcc` can be considered "good enough", yes. It feels a little bit like a workaround (because Postmark / Mandrill offer hiding `To` from each other, when using their transactional batch API), but it can work, yes.

**Comment by fabpot** [comment]
So that I understand correctly, your feature request would be to be able to have n `To`s but instead of sending on email, it would send n emails with 1 `To`, right?

**Comment by romaricdrigon** [comment]
Yes, exactly!

**Comment by fabpot** [comment]
Let's see if we can add an "option" to make it work. It that's not too complex, why not. Would you like to give it a try?

**Comment by romaricdrigon** [comment]
Sure, thanks for reopening.
Regarding implementation, what sounds like the best option to you?

**Comment by fabpot** [comment]
Not sure, we should investigate which object should have this responsibility. It cannot be on the Transport IMHO, so probably on the email or the envelope perhaps?

**Comment by fabpot** [comment]
Closing as there is no more feedback.

**Comment by nicodemuz** [comment]
@fabpot I have a usecase where I need to send a newsletter with an embedded unsubscribe link to the users. As such, I need to send a slightly different email to each subscriber. It would be great if the Symfony mailer could support batch/bulk/templated sending to multiple users in one single call.

Many of the email service providers seem to have API end-points for this purpose:

https://postmarkapp.com/developer/api/email-api#send-batch-emails
https://mailchimp.com/developer/transactional/api/messages/send-using-message-template/
https://documentation.mailgun.com/en/latest/user_manual.html#batch-sending-1
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendBulkEmail.html

**Comment by Jean-Gian** [comment]
@nicodemuz I have the same usecase and so I agree: it would be great if Symfony could support that

**Comment by stof** [comment]
Supporting the template syntax of providers to allow sending bulk emails with substitution (or recipient variables, or whatever other name they use for that) is impossible (or very very hard) to abstract across providers as they have no standard for the way these substitutions work. Previous proposals for that topic were forcing devs to write their emails using the specific syntax of the provider they are using, which is breaking the symfony/mailer abstraction (switching transport would break if you don't also change all your content to use a different syntax), which is why we dediced to keep it out of scope of the mailer component.

**Comment by Jean-Gian** [comment]
Your point @stof makes perfect sense

**Comment by kieranmetcalfe** [comment]
Hi,

I'm hitting this issue as well. I've been round the houses with mailgun support, and the key seems to be that it's down to the fact that (they say) the recipients should be sent as TO fields in the cURL request, rather than To headers in the mail/mime message:

```
curl -s --user 'api:YOUR_API_KEY' \
    https://api.mailgun.net/v3/YOUR_DOMAIN_NAME/messages \
    -F from='Excited User <mailgun@YOUR_DOMAIN_NAME>' \
    -F to=YOU@YOUR_DOMAIN_NAME \
    -F to=bar@example.com \
    -F recipient-variables='{"YOU@YOUR_DOMAIN_NAME": {"first":"Bob", "id":1}, "bar@example.com": {"first":"Frank", "id":1}}' \
    -F subject='Hey, %recipient.first%' \
    -F text='If you wish to unsubscribe, click https://mailgun/unsubscribe/%recipient.id%'
```


Similarly, if using the SMTP transport, they say that the recipients should all be sent in the RCPT TO of the SMTP connection, rather than the To header in the mime message. The "To" SMTP header, they say, should be `%recipient%` which then gets replaced by MailGun with the actual recipient email address. 

This is all pretty much counter to their own documentation, but they're adamant they're correct... even though this isn't standards compliant on the To header as far as I can see.

What's the best way to go about implementing a new transport to allow this formatting, probably on the API/HTTP transport to use cURL fields in that way?
