### ISSUE TITLE
[4.3.3] The IntegerType empty_data option always cause the form validation to fail.

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony#33322]
**Symfony version(s) affected**: 4.3.3

**Description**  

EDIT:

The default value defined by the empty_data option of IntegerType always causes form validation to fail.

The example application here: [https://github.com/zacharyzh/sf-int-type-demo](https://github.com/zacharyzh/sf-int-type-demo)

Thanks.

**Comment by xabbuh** [comment]
I am not sure I understand the problem. Can you be a bit more specific of what happens and what you expected instead. The best would be if you could create a small example application that allows to reproduce it.

**Comment by zacharyzh** [comment]
@xabbuh 

Sorry for my broken english, here is a example: 

[https://github.com/zacharyzh/sf-int-type-demo](url)

**Comment by xabbuh** [comment]
Thank you for the application. Actually, the issue here is the configured value for `empty_data`. The value given here is expected to be in the view format. This means it has to be a `string` in this case. If you change your `DemoFormType` like in the following example, everything will work as expected:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('number', IntegerType::class, [
        'required' => true,
        'empty_data' => '1',
    ]);
}
```

I am going to close here as there is nothing to fix. Thank you for understanding.

**Comment by zacharyzh** [comment]
Thanks for your explanation.
