### ISSUE TITLE
[Cache] The cache does not work with a NFS filesystem 

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony#33392]
**Symfony version(s) affected**: 4.2.10

**Description**  
The cache component desn't work with a NFS filesystem because of the [`flock()`](https://www.php.net/manual/fr/function.flock.php) function calls done by the LockRegistry :

https://github.com/symfony/symfony/blob/9ea05b1601632fb9fe3f8972d6ee7d9430d8acd8/src/Symfony/Component/Cache/LockRegistry.php#L93

Indeed, the `flock()` function itself is not reliable with a such filesystem.

**How to reproduce**  

```
php -r "var_dump(flock(fopen('/file-on-nfs-filesystem', 'r+'), LOCK_EX | LOCK_NB));"
// always returns bool(false)
```

**Possible Solution**  

We could bypass the locking mechanism if we know we are on a NFS filesystem.

**Additional context**

I tried to use the cache component into a vagrant with NFS synchronised files but I can't.

**Comment by maidmaid** [comment]
Relates to #27730

**Comment by nicolas-grekas** [comment]
Maybe this is for the best? A cache pool should really not be stored on a NFS...

**Comment by maidmaid** [comment]
Certainly in production but while the development, some people are still using a web app through a vagrant with NFS as a filesystem for instance.

**Comment by oliverde8** [comment]
We tend to mount those directories inside the vagrant with symbolic links. With some of our project(not symfony) that does a lot of writes into the cache directories the nfs was to way slow anyway. The drawback is you can't access the generated files from the host machine.

**Comment by nicolas-grekas** [comment]
Alternatively, can we detect the situation and skip the lock, using a combination of the return value and the $wouldblock argument maybe? Any with the issue willing to give it a try?

**Comment by vakafonic** [comment]
@maidmaid Hello!

Today I was in a situation, where GCP deployment of code with the usage of Symfony cache component costs some downtime for us.

Originally, this problem could be found in the logs with PHP max method execution time exceeded

`E_ERROR: Maximum execution time of XX seconds exceeded`

and files like `vendor/symfony/cache/Traits/ContractsTrait`

I was digging through the solution and found some info about LockRegistry usage in cache component, so I was forced to hack a solution by adding the next line somewhere in the bootstrap of your app before cache usage.

`\Symfony\Component\Cache\LockRegistry::setFiles([]);
`
Then the problem was solved.
