### ISSUE TITLE
Dynamic database connection

### ISSUE THREAD

**Issue by Dev1lDragon** [symfony/symfony#33406]
Its will be good if in symfony will be posible to conect to database dinamicaly, i mean i have 1 database master and n database customer, where n is increment when new user create, and for this will be good if symfony got something like EntityManger::create(/*customet entity manager*/'customer', /*variables to change*/['db'=>'customerN']), and its create new entity manager on instance.

**Comment by javiereguiluz** [comment]
From time to time we receive similar questions for this feature. If I'm right, Symfony/Doctrine don't want to add this to the core Symfony/DoctrineBundle. However, you can probably do this yourself adding the username/userID as part of the URL and then getting that value very early in an event listener or subscriber. With the user ID you can get the right entity manager for them and set it somehow in your app.

Or you may create your own entity manager wrapper service ... and inject the RequestStack service to get the user ID from the URL of the current request.

See this talk for more details: https://skillsmatter.com/skillscasts/9604-multi-tenant-database-architecture-with-symfony-and-doctrine

You can also ask on Symfony's Slack (https://symfony.com/slack) because people may give you advices and recommendations based on their own experiences.
