### ISSUE TITLE
[WebProfiler] Deprecate `intercept_redirects` in 4.4, remove it in 5.0

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#33467]
The `intercept_redirects` option is not needed anymore as the toolbar for the redirected resource now contains a link to the redirect response profile. For this reason, this option is set to `false` by default.

I think that this feature is not needed anymore and should be deprecated in 4.4 so that we can remove it in 5.0.

**Comment by stof** [comment]
I totally agree with this. I have this option disabled since years, as intercepting redirects is something I always considered more annoying that useful (there are many cases when I want to follow the redirection and I don't care about the profiler). And the fact that redirected responses are linked now makes it even less useful.

**Comment by dorumd** [comment]
@fabpot @stof I would like to work on it, is it still not taken?

**Comment by fabpot** [comment]
I'm not aware of anyone working on it, so feel free to take it.

**Comment by lyrixx** [comment]
Oh, I missed this issue and so I'm late on it.
Actually, I disagree with this change. 
Let me explain it. I'm working on a booking website were we display only search results.
When the user wants to books a travel we build a "deeplink" to an external website.
It's something like https://booking.example.com/?travelID=XXXX&foo=bar&......
When we develop (and without this feature), It will add lot of extra clicks to ensure the deeplink is good:

1. click in the fist tab on "book"
1. in another tab, where the profiler is opened, click on "see last 10"
1. find the good request / response
1. open it
1. ensure the redirection is the right one

instead of just one "ensure the redirection is the right one"

I have also another exemple:
We build dynamic redirection to generated picture. We know serving picture after a redirection is not perfect since it adds an extra round-trip but we had no choice. More over, https://connect.symfony.com does the same thing to serve avatar picture. For exemple on the Symfony blog, avatar URL are something like `https://connect.symfony.com/api/images/17170f22-52c0-4adf-a75d-29cb01d53176.png?format=80x80`

So again, this feature is very useful here.

I understand that removing an option is nice and reduce the codebase, but this feature exists for age, is very stable and quite simple.

Could we consider reopening this issue and/or reverting the PR?

**Comment by Pierstoval** [comment]
I'm also highly reusing it when I have to test my forms and their redirections.

Like, I have a page displaying a form based on `symfony/form` and I can have several redirections or operations in the same action, and instead of manually remove the `return new RedirectResponse($url)`  in the end, I often prefer to just keep the codebase as-is and use `intercept_redirects: true` in order to re-submit the same values and check the output of it, when for instance I'm debugging form handlers (which can involve tons of calls) or different kinds of redirections.

On one of my projects it's even defaulted to `true` in `dev` env to not have to think about it in the first place (and it's disabled in `test` env)

**Comment by lyrixx** [comment]
I asked [on twitter](https://twitter.com/lyrixx/status/1174237481425936384), and many people are using this option.

That's why I will re-open this issue.

Feel free to close it again if you think we should really remove this option.

**Comment by drupol** [comment]
Just for the sake of it, I have to say that this option is actually very useful when developing a bundle related to authentication having redirections.
I'm working on a bundle for the CAS authentication on a custom CAS server (_based on the CAS protocol, but with some variants_) and the `intercept_redirect` option is definitely useful, I'm glad it came back.

**Comment by fabpot** [comment]
@drupol This has been reverted in the meantime.

**Comment by drupol** [comment]
Yes yes I saw it thanks for it, I just wanted to share my experience and why it was useful for us :-)

**Comment by Addvilz** [comment]
Just to pitch in, indeed use cases for this are not many, yet I do have some too, specifically when working with external redirects etc, where I love the option of actually not having to follow redirects.
