### ISSUE TITLE
[Security] RememberMeAuthenticationProvider is broken

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#33472]
**Symfony version(s) affected**: `4.2 - 4.4`

**Description**  
Similar to https://github.com/symfony/symfony/issues/26775, In https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Authentication/Provider/RememberMeAuthenticationProvider.php#L50-L52.
[`TokenInterface::getUser()`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Authentication/Token/TokenInterface.php#L61) returns `string|object`, [`UserCheckerInterface::checkPreAuth()`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/UserCheckerInterface.php#L31) allows a `UserInterface` instance only.

I get `Argument 1 passed to checkPreAuth() must implement interface Symfony\Component\Security\Core\User\UserInterface, null given`, and can't reproduce it, but the code looks wrong.

**Comment by rbaarsma** [comment]
I see your objection, but if you look at line 65 (https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Authentication/Provider/RememberMeAuthenticationProvider.php#L65), triggered by line 43, you will see this authenticator only works with a `RememberMeToken`

If you look in the constructor of the `RememberMeToken`, you will see that a `UserInterface` is mandatory as the first argument (https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Authentication/Token/RememberMeToken.php#L31)

Therefore it seems impossible for this bug to be triggered by the `RememberMeAuthenticationProvider`.

It's unfortunate you haven't copied the full exception, because I would've been curious if the exception was really raised by the `RememberMeAuthenticationProvider.php` from Symfony, but I'm assuming that this is the case. 

I've done a few quick tests, but have been unable to reproduce this issue.

Tested on symfony/security 4.3.4

**Comment by umpirsky** [comment]
Here is the trace:

```
TypeError: Argument 1 passed to My\User\UserChecker::checkPreAuth() must implement interface Symfony\Component\Security\Core\User\UserInterface, null given, called in vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/RememberMeAuthenticationProvider.php on line 52
src/My/Security/User/UserChecker.php(12): checkPreAuth
vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/RememberMeAuthenticationProvider.php(52): authenticate
vendor/scheb/two-factor-bundle/Security/Authentication/Provider/AuthenticationProviderDecorator.php(63): authenticate
vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php(76): authenticate
vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authorization/AuthorizationChecker.php(53): isGranted
vendor/stof/doctrine-extensions-bundle/EventListener/LoggerListener.php(46): onKernelRequest
vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): doDispatch
vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): dispatch
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(125): handleRaw
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(66): handle
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(188): handle
```

Looks like `scheb/two-factor-bundle/Security/Authentication/Provider/AuthenticationProviderDecorator.php` is triggering it. But the class design should not allow this kind of behavior.

**Comment by umpirsky** [comment]
I should probably report this to https://github.com/scheb/two-factor-bundle, but we should improve error handling here. Agree?

**Comment by chalasr** [comment]
@umpirski Returning false from `RememberMeAuthenticationProvider::supports()` in case the token's user is not a `UserInterface` instance should fix the bad error handling, sounds good as a bugifx to me.
Are you willing to submit the PR?

> If you look in the constructor of the RememberMeToken, you will see that a UserInterface is mandatory as the first argument

The issue might be that `RememberToken` extends `AbstractToken` which exposes a `setUser()` method that supports a wider type range. 
We could override the setter in `RememberMeToken` to make it support only `UserInterface` (deprecation notice on 4.4, exception in 5.0). 

Also yes, scheb/two-factor-bundle probably needs a patch

**Comment by umpirsky** [comment]
> Are you willing to submit the PR?

I can try, but not soon. Thank!

**Comment by umpirsky** [comment]
`scheb/two-factor-bundle` just forwards the call and result of `supports()`, so it's neutral in this case, and without it, we would have the same issue.

**Comment by chalasr** [comment]
no, 4.2 is not maintained anymore (security fixes only)
