### ISSUE TITLE
[DomCrawler] Crawler parses page incorrectly

### ISSUE THREAD

**Issue by interlab** [symfony/symfony#33493]
**Symfony version(s) affected**: "symfony/dom-crawler": "^4.3"
PHP 7.2.6 (cli) (built: May 23 2018 20:29:41)

**Description**  
Crawler parses html page incorrectly (see attachment)

**How to reproduce**  
```php
use Symfony\Component\DomCrawler\Crawler;

require_once __DIR__ . '/vendor/autoload.php';

$data = file_get_contents(__DIR__.'/t.txt');
$crawler = new Crawler($data);
dump($crawler->html());
```

**Possible Solution**  

**Additional context**  

[t.txt](https://github.com/symfony/symfony/files/3584221/t.txt)

**Comment by stof** [comment]
Please give more details about what is incorrect. It will make it much easier to help you

**Comment by interlab** [comment]
domcrawler sees only <head>, should see and <body>

**Comment by stof** [comment]
Are you sure that it is not just `dump()` truncating the string because it is too long ? Your `<head>` is huge.

**Comment by stof** [comment]
OK, found it. Even your `head` is not complete. And this seems to be because of the `</html>` appearing inside the huge JS script you have.
This is related to the usage of libxml to parse the DOM in PHP's dom extension.

You have 2 solutions here:

- install the `masterminds/html5` optional dependency, which will make dom-crawler use it to parse your HTML (as you use the HTML5 doctype)
- wrap the content of your script in a `CDATA` section to make it parseable by the XML-based parser of libxml

For anyone reading this issue, not that using `masterminds/html5` as the HTML5 parser is supported only as of 4.3. Older versions cannot do it.

**Comment by interlab** [comment]
Thanks for the help, I will try later.

**Comment by interlab** [comment]
added masterminds/html5 to composer.json, updated libraries via "composer update" and now works.
