### ISSUE TITLE
[Validator] Allow to ignore a Violation for a Constraint

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#33555]
**Description**  
For our project, we are using the `@Assert\File` but, for some reason, we would like to allow the submission of our form if the file is not found.

The constraint add a violation with the code `File::NOT_FOUND_ERROR` if the file is not found. It would be great if we could use the annotation this way
```
@Assert\File(ignore={"errorCode"})
```

**Comment by stof** [comment]
I don't think adding an `ignore` option to all our constraints is something we want. I don't see a use case justifying to add that complexity in core for everyone.

If you use the validator component directly, it is easy to decide to ignore some of the returned violations (as the validator does not more than returning this list).
If you use the form component with its validator integration, what you could do is adding an event listener on the `POST_SUBMIT` even on your form (with a negative priority so that it runs after the ValidatorListener), inspect the Form tree to find errors you want to ignore and remove them (this actually implies clearing errors for the particular Form object in the tree and then re-adding all the other errors, as we don't have an API to remove individual errors).

**Comment by VincentLanglet** [comment]
@stof I used the `@Assert\File annotation` in my class, and since I have OneToMany/OneToOne relation with `@Assert\Valid` I had a lot of form with this error. In my case the listener should listen every POST_SUBMIT from every form. Since I never used listener, I don't know if it's possible and how to do it. 

Actually, what I did was creating a `class FileOrNotFound extends File` and a `class FileOrNotFoundValidator extends FileValidator` with an early return if path is not found.
Now I use my custom constraint FileOrNotFound instead of Assert\File.

I understand the option is not accepted, this was just a proposition.

**Comment by stof** [comment]
well, if this is about forms where you don't include the file field, the right solution is not to ignore the violation, but to ignore the constraint, which we already support. This is what validation groups are for.

Btw, the existing validator already return early when the value is `null` or the empty string. For a `File::NOT_FOUND_ERROR` violation to be reported, you actually need to provide a value corresponding to a wrong path.
If your class can have both a file path and something else in the same property, this is either a code smell that should be fixed, a good use case for validation groups again or a use for a custom constraint which would delegate to the File constraint when necessary (note that I suggested delegation, not inheritance, which also allows to filter out the delegated violations depending on how this gets done).

**Comment by VincentLanglet** [comment]
@stof I don't consider my use case as a code smell. But I can agree it's kinda tricky.

The files in production are stored in the production server, and the files in our pre-production or our local are stored in a test server. When we download the production database for debugging, we get value for the path, but can't load the file since we're not using the prod server. 

What do you mean by delegation instead of inheritance ? Do you have a short example ?

**Comment by VincentLanglet** [comment]
Hi @stof, what did you mean by delegation instead of inheritance ?
Do you have a short example of how you would you do it ?

Thanks
