### ISSUE TITLE
class_alias for autowiring only working once on empty cache

### ISSUE THREAD

**Issue by hcomnetworkers** [symfony/symfony#33695]
**Symfony version(s) affected**: 3.4.22

**Description**  
Because autowiring/autoconfiguring is so nice, I wanted to autowire a specific monolog channel.
This construct is what I came up with to achieve it:

services.yml
```yml
services:
  MyApp\Logger\SecurityLogger: '@monolog.logger.security'
```
MyApp\Logger\SecurityLogger.php
```php
<?php
class_alias(Psr\Log\LoggerInterface::class, 'MyApp\\Logger\\SecurityLogger');
```

And this works great for autoconfigured injection into a controller action, every time, multiple calls.

However, when I try using this for autowiring in services (constructor), it only works once with an empty cache. After the cache is built, all consecutive executions result in:

> Type error: Argument x passed to XXX::__construct() must be an instance of MyApp\Logger\SecurityLogger, instance of Symfony\Bridge\Monolog\Logger given

My SecurityLogger is supposed to be a LoggerInterface, which is supposed to match the Monolog\Logger. This error makes no sense.

I've tried adding the `class_alias()` call in the front controller to see if that aliasing was not happening, but this had no effect.

Is this a bug in the container cache? Can this be fixed?

**Comment by nicolas-grekas** [comment]
The reason is that the alias is not loaded in the case that fails. It *is* loaded when a controller is used because the argument resolver inspect arguments of your actions, and loads the alias as a side-effect of that inspection process. Yet, adding this inspection step to the instantiation of every single service is of course out of question.

See https://github.com/symfony/monolog-bundle/pull/254 for a proper solution on the topic.
I'm closing as there is no bug here.

**Comment by nicolas-grekas** [comment]
I meant https://github.com/symfony/monolog-bundle/pull/315 sorry for the bad link.
