### ISSUE TITLE
[Messenger] Memory consumption is too high when using Redis

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#33715]
**Symfony version(s) affected**: all

**Description**  
On Symfony Slack some people were discussing about Messenger and other alternatives. A person said:

> [I had] bad experience using redis transport in production (on 2 different projects): memory consumption was (way) too high. Couldn’t figure out what was the root cause of this, but it was faster to migrate [to a Messenger alternative].

And another added that:

> I run a redis docker image with 500 MB memory, and it will stop working if memory is full

**How to reproduce**  
No specific details were given about how to reproduce, so I guess you only need to use Messenger + Redis to see the excessive memory consumption.

**Comment by flaushi** [comment]
One of the cited comments was by me. My proposition is to use `XDEL` after `XREAD` such that consumed messages are deleted at the redis side...

**Comment by xavismeh** [comment]
I'm the original author of the other quote, and already mentionned more or less that problem in https://github.com/symfony/symfony-docs/pull/11869. Since I only have a (very) few informations of what happened, let me share it with you:
## context
- production environment
- intensive use of the lib: regularly having 200K messages to process in queue

## setup
- messenger component using redis transport, latest dev version (at time speaking)
- large amount of consumers per queue — 50 on average — which lead to my original comments in symfonydoc's PR

## (non expected) behaviors
1. each consumers were processing the same messages despite advices provided in https://github.com/symfony/symfony-docs/pull/11869
2. memory limit was frequently reached per consumer, when, using a single consumer wiped this problem away. It used to take several minutes for a single message to be processed when the "alternative lib" used to run the exact same process (same input, same output) within seconds

*Side notes:*
I was not able to determine what was the root cause of this because of possible delays. However, IIRC, the tests I had at this time were tending to make me think that the main problem was not redis transport specific: I think the problem comes from the lib itself (messages management?), and for some reasons, the redis transport made it more visible.

Of course, I would more than happy to give a hand if necessary/possible.

**Comment by javiereguiluz** [comment]
Thanks for your detailed insights! They will be very useful to try to improve this.

**Comment by sroze** [comment]
@alexander-schranz @soyuka do you have any time to look at this? 🙏

**Comment by alexander-schranz** [comment]
@sroze without doing any benchmarks I can say that redis loads a lot into the memory. You can work around the memory problem by keeping your stream small. The easiest way is what @Toflar implemented in #31825 the auto_trim feature.

Sadly I think its hard to define a default value for trimming. It depends how fast you consume the messages as you don't want that the a streamed message get trimmed before you consumed it.

**Comment by alexander-schranz** [comment]
And the suggestion above removing the message manually when on XACK/XREAD can not be done. Or when we do this it should be an optional option as the Redis Stream Transport is build that you have multiple ConsumerGroups and that will not work if the message gets deleted after the first one ack its consumption and del the message.

There is currently only one way to remove all consumed messages and it would require phpredis extension of ^5.0 (current requirement is ^4.2) . First use the `xinfo` to get all groups and get from all groups then the `last-delivered-id` filter out which one is the oldest and then use xrange and xdel to remove this consumed messages. This is an heavy process it should not be done in every `get` call of the consumer. Maybe doing it by a random factor when we implement this type of logic.

But maybe the effected people can check if they have multiple consumers they use also multiple consumer names as written in symfony/symfony-docs#11869 and if the max_trim feature #31825 (needs symfony ^4.4) does it work for them.

@Toflar @soyuka what do you think?

**Comment by soyuka** [comment]
> See here what XACK does

> Once a consumer succesfully processes a message, it should call XACK so that such message does not get processed again, and as a side effect, the PEL entry about this message is also purged, releasing memory from the Redis server.

Are you sure that we manually have to do the message removal? It seems that redis should purge them at one point (mb clean with [MEMORY_PURGE](https://redis.io/commands/memory-purge)?). The trim option looks definitely on point, I think we need to investigate this further.

**Comment by sneakyvv** [comment]
> Are you sure that we manually have to do the message removal? It seems that redis should purge them at one point (mb clean with MEMORY_PURGE?). The trim option looks definitely on point, I think we need to investigate this further.

@soyuka XACK will only delete PEL entries, the stream would always just grow larger.

> But maybe the effected people can check if they have multiple consumers they use also multiple consumer names as written in symfony/symfony-docs#11869 and if the max_trim feature #31825 (needs symfony ^4.4) does it work for them.

@alexander-schranz the problem is that the XTRIM approach is still unreliable. If you cannot foresee XADD peaks, which might exceed the `stream_max_entries`, and/or if consumers are not processing messages fast enough, unconsumed messages might be removed. 

So, I actually prefer your approach which works with the `last-delivered-id`. However, if I'm correct the last-delivered-id is not the same as last ACK'ed id. If you have 5 items pending the last delivered-id would be the last pending id, and we actually need the oldest pending one. In theory a consumer could need to XCLAIM another consumer's pending items if it crashes. Therefore, I think it would be better to use XPENDING, and use the oldest id from _all_ pending messages. And of course then you need to XRANGE/XDEL everything _older_ than that.

**Comment by ljay79** [comment]
Hi guys i came across this thread while researching for an issue i learned the hard way on production.

As im a basic user of symfony, redis etc and this project is my first one implementing the messenger methodlogy, im not fully understanding the unterlying fundamentals.

So my general question is basically, if my below issue is exactly what would be solved buy this PR or if im exiriencing an different maybe just a missconfiguration problem.

Im using:
- snc/redis-bundle ^3.2
- symfony/framework-bundle 4.4.*
- symfony/messenger 4.4.*
- php ^7.2.24
- Redis 5.0.6 (non-cluster mode)

Yesterday i noticed an issue with the app tracing it down to problem; the redis memory was simply full. (1.5GB).
Checking deeping, i noticed that the messenger stream in redis is never truncated, it was apparently never deleting any messages in the stream and therefor constantly growing in the memory.

And this, as long as i can say, all messages are processes successfully or handled correctly with a failed message handler.
For my understanding, with a basic default setup, any the stream should never grow to such high memory.
I was under the impression, any processed message would get removed from the stream afterwards.

I was able to reproduce this consistanly.

Your PR, i have applied manually (hacked) into my source atm and it solved the issue right away.
Now even under peak load, the stream is not growing over 50 MB and shrinks down right away synchrony with processing messages.

As this lets me believe, that *every* setup with redis as a stream transport would experience the exact same behavior i can not imagine, this is expected?

a) is there an important part in the doc missing, that instructs a developer to take care of an own implementation of message truncation after processing?
b) do i experience an unexpected bug?
c) can i (safly) apply this PR to my 4.4.x symfony?

**Comment by Toflar** [comment]
That's just how Redis streams work. They are never automatically truncated.
In Symfony 4.4 you can use the `stream_max_entries` configuration to make sure you don't have memory leaks.
The best option would be to just update to 5.1 and have Symfony handle cleanup automatically for you.

**Comment by ljay79** [comment]
Thx understood.
Its just strange, that the symfony adapters are deleting failed messages from stream but not successful.
As this ismplies, it is actually mandatory to implement some kind of handling for this (even for perfect implementations) i would really like to have such highlighted warning in the documentation.

Successfull and good messenger implementation leads to memory leak but at least to depleting any size of redis server memory (just a matter of time) is nothing any level user shall expect when implementing a "service" in symfony core.

Thx anyway, i have learned it the hard way now and applied the related changes as apatch to my symfony 4.4. core.

**Comment by Toflar** [comment]
Please, make a PR to the docs then :)

**Comment by ljay79** [comment]
Im not sure, i can describe the cause for the warning properly as im myself not 100% understanding the underlying dependencies or reasons it might be designed on prupose like this...

**Comment by PhilETaylor** [comment]
So today I deployed messenger into production (with Redis) as a replacement for Resque-php

With 300 messenger:consume Im hitting 16Gb RAM and crashing the server. Resque-php ran on average 300 workers for 8Gb RAM.

This is not about stream size in Redis, but this is the only thread I could find with others using large numbers of workers... 

My worker app is tiny, basically makes a few db calls, then a HTTP POST to a remote site, gets a json response and processes it back to the db. 

300 consumers just sitting there with nothing in the queue is taking 15-16Gb RAM consistently 

Any ideas where I can start to look?

**Comment by alexander-schranz** [comment]
@PhilETaylor when using multiple parallels running consumers you need to make sure that every consumer has its own consumer name. Else you can get into trouble, as I see you already seems to know that because of your comment here: https://github.com/symfony/symfony/issues/35358#issuecomment-1026184663.

Then redis consumers and group should only be created once. So if your container setup is generating new consumers everytime the container is build/restarted/... and not reuse the consumers. Redis will be bloated with consumer and consumer group data and so that can make problems. So consumer name need to be unique per parallel process but should not create new consumer names everytime a new process is started. Its tricky but thats the requirement when using redis. So check that you only have 1 group and 300 consumers and not that the consumers are growing and growing again. You can use xinfo to get a list of your consumers: https://redis.io/commands/xinfo

If you are not using groups / multiple groups so multiple system receiving the same message you should set `delete_after_ack=true` in your DNS see also: https://symfony.com/doc/current/messenger.html#redis-transport. So old messages are not longer stored in the redis database. When having multiple groups you need a manual cleanup task for your stream. Example using xrange to get all message older then a specific timerange and then delete them.

At the end best way to debug redis is to have a look at what is stored in redis and what does take the the 16GB memory. I prefer using [Redis Insight](https://redis.com/de/redis-enterprise/redis-insight/) for this. Redis Docs with its commands is also helpful: https://redis.io/commands#stream

Still I never used redis with 300 consumers, not know which effects 300 consumers has on redis itself has.

**Comment by PhilETaylor** [comment]
I think you misinterpret my post :) I DONT have the issue in this thread where my Redis-server is running out of memory due to a large volume of stored messages in the stream. 

The problem I thought I had was that each message:consume process - even if the stream was empty - was taking a large amount of memory - but on debugging Im going to just assume this is the way it is. Each process is taking 0.4% of the 16Gb RAM available.  300 processes all using x 0.4% of the RAM = 120% of the available RAM - gulp. 

It seems resque-php did not spawn the php processes until needed, so this is why its initial RAM requirement was much lower. 

> you need to make sure that every consumer has its own consumer name

Yup done that as per the documentation.

> Then redis consumers and group should only be created once. So if your container setup is generating new consumers everytime the container is build/restarted/... and not reuse the consumers. Redis will be bloated with consumer and consumer group data and so that can make problems. 

I noticed that, and wrote an Event Listener that unregisters consumers on messenger:stop-workers command - see https://github.com/symfony/symfony/issues/45267

Like I said, my current issue is not about a bloated Redis server, but the RAM used by each messenger:consume process, even at idle. 

> So consumer name need to be unique per parallel process but should not create new consumer names everytime a new process is started

I create new consumer names on each container deployment, but I unregister the old consumer names first. 

> If you are not using groups / multiple groups so multiple system receiving the same message you should set delete_after_ack=true

Yup already have that config. As per the docs. 

> At the end best way to debug redis is to have a look at what is stored in redis

Like I said, this is not the problem I was reporting/talking about. Nothing in stored in Redis at the point 300 consumers use 16Gb of RAM. The consumers are idle. There are no messages yet in the queue. 

> Still I never used redis with 300 consumers, not know which effects 300 consumers has on redis itself has.

Our default is 300 workers - on a release day (Joomla or WordPress release) we can scale up to 3000 workers. Redis never event breaks a sweat with this - it handles everything we have ever thrown at it.

Im guessing that we will just have to horizontally scale 16Gb RAM servers, each running < 300 consumers. Unless I can profile and work out why an idle messenger:command process is using 0.4% of 16 Gb (64 megabytes) per process even when doing nothing. 
 
Thanks for listening as I talk this through myself.

**Comment by alexander-schranz** [comment]
@PhilETaylor Sure 300 consumers will create 300 processes running waiting for getting a message. There is nothing implemented in symfony to like a consumer manager which will start or stop child processes like what you seem to have before. 

As I understand your setup before there was 1 consumer which did read the message and which then did start an async child process handling that.

You still could wrap your message into a:

```php
$message = new AsyncMessage($originalMessage);
```

and then having a `AsyncMessageHandler` which will manage the child proccess via a Semaphore you could limit the numbers of it: https://symfony.com/doc/current/components/semaphore.html Sure it is a lot of more work and sure not you wanted the hear here.

So at all I think what you are searching for is a new feature, because something like this is not yet implemented in messenger. I think it is worth to create a feature request to split read the message and process the message (via async child proccesses).

If you want to debug why a messenger:consume requires 64 megabytes of RAM I would recommend creating a [blackfire profile](https://blackfire.io/docs/up-and-running/installation) with when one message is in queue and you run `blackfire run php bin/console messenger:consume --limit=1`. You could also try if it is redis specific or does also appear when you use example for testing now the doctrine transport.

**Comment by PhilETaylor** [comment]
> I would recommend creating a [blackfire profile](https://blackfire.io/docs/up-and-running/installation) with when one message is in queue

Great minds think alike... this is what's currently on my screen right now ;-) 

> So at all I think what you are searching for is a new feature, because something like this is not yet implemented in messenger. I think it is worth to create a feature request to split read the message and process the message (via async child proccesses).

Agree. Im not going to have time for that this weekend... but maybe in the near feature. Need to complete the migration to the MessageBus from Resque-php first, and then I can circle back to contribute improvements.
