### ISSUE TITLE
[Workflow] Access MarkingStore property value

### ISSUE THREAD

**Issue by sapiet** [symfony/symfony#33802]
**Description**  
I am trying to listen entity updates and check if any updated values are concerned by a workflow to ensure that the matching transition can be applied. When iterating the state machines, i cannot access to the property name, because $property is private and the class don't provide a getter. https://github.com/symfony/workflow/blob/master/MarkingStore/MethodMarkingStore.php#L33

**Example**  
$property = $stateMachine->getMarkingStore()->getProperty();

**Comment by xabbuh** [comment]
Can you be a bit more precise about the problem that you need to solve? Maybe there is another way we can show you.

**Comment by sapiet** [comment]
Sure, let's have, for example, an entity BlogPost.
A Workflow is defined with three places (draft, to_review, published) and two transitions (review, publish).
A BlogPost entity is created with default status "draft".
Then, someone writes this code:
`$blogPost->setStatus('toto')`or `$blogPost->setStatus('published')`
As Doctrine and Workflow do not communicate with each other, this will not throw any error and the status will be updated in the database after a flush.
My wish is, with Doctrine listeners and Worflows definitions, to check if this updates are allowed.
For that i need to compare every Workflows with each updated properties on the entity.
This works fine, except for retrieving the property concerned by the Workflow definition, which make comparison possible.

**Comment by lyrixx** [comment]
When a subject (eg an entity) is managed by the workflow component, no-one should use `$blogPost->setStatus('published')`. I understand you want to automate this this but IMHO, it should not be done at runtime. It should be done during a code-review, or with tools like phpstan.

Anyway, If you really want to do that, since you choose the property name `status`, you can simply hardcode `status` in your listener. And if you don't want to hardcode anything, you can use a constant for that.

Finally, I'm against adding `MarkingStoreInterface::getProperty()` since there is coupling between the MarkingStore storage and the subject. For exemple, the marking store may store the marking in another table with the current_user_id for audit

**Comment by sapiet** [comment]
In case we use API Platform we have to do this code review on client side applications, as this is not the server itself which make requests, which may be painfull. I'll take a look at phpstan.
I finally ended to hardcode something like `const MAPPING = ['blog_publishing' => 'status'];`

**Comment by bpolaszek** [comment]
@lyrixx In the case of a santardized CRUD application (with Api-Platform or anything else), it would indeed be a nice feature to _automatically_ prevent updating a property which is behind a state machine. 

Defining a workflow for `BlogPost::status` currently doesn't prevent you from doing `PUT /blog-post {"status": "anything"}`. Of course we could define this property as read-only and use a custom operation to update it using the workflow; but the desired behavior is more a rule like "if trying to update a property of any object covered by a state machine, throw an error". This indeed requires the knowledge of every object/property covered by the workflow component.

**Comment by lyrixx** [comment]
With API platform, you can ignore this property. In order to do that, you must not add a group on the property, and so it will be ignored

ATM, I don't see how we can automate this kind of check.

**Comment by bpolaszek** [comment]
It's not about automating things in the component itself, the point is about allowing the developer to automate that with its own code. But this could be done at the only condition that `MethodMarkingStore::$property` is exposed.

@sapiet Otherwise, this should do the trick:
```php
$reflectedClass = new \ReflectionClass($markingStore);
$reflectedProperty = $reflectedClass->getProperty('property');
$reflectedProperty->setAccessible(true);
$property = $reflectedProperty->getValue($markingStore);
```

 😁

**Comment by lyrixx** [comment]
As I said, this is not possible, since there is no coupling between the the Marking store and the property.
I explained different way to achieve that in a previous [comment](https://github.com/symfony/symfony/issues/33802#issuecomment-537553602) 

We could also think of another solution: create your own marking store where you expose this property.

As everything has been explained, I gonna close this issue.
If you think something is missing, don't hesitate to comment / re-open this issue :)
