### ISSUE TITLE
[Mailer] Mailtrap mailer transport

### ISSUE THREAD

**Issue by lsv** [symfony/symfony#33847]
**Description**  

It would be lovely, if a [mailtrap.io](https://mailtrap.io) mailer provider was included.

It is awesome to test mail with, as you can inside mailtrap forward the mail to another mail, and therefor testing it with different browsers/mail clients/mailtests etc.

And as mailtrap is sending all mails to a single mailbox regarding the TO address, its great to testing.

**Example**  

Only username and password should be provided by `.env` it should be fairly simple to include.

**Comment by stof** [comment]
AFAICT, mailtrap.io exposes a SMTP server. So this is already supported by the generic SMTP transport available in the component.

**Comment by fabpot** [comment]
Indeed, let's close

**Comment by PapyDanone** [comment]
@fabpot @stof, I would be very interested in such a feature for the following reasons:

1. Mailtrap is very popular during development, and recommended often by @weaverryan in his SymfonyCasts
2. Configuring Mailtrap with the `MAILER_DSN` only is not enough for it to work properly, because of the cumbersome rate limiting they impose (2 emails every 10 seconds), which results very often in `too many emails per seconds` exceptions
3. Is it currently difficult with Mailer to call `setRestartThreshold` or `setMaxPerSecond` without resorting to the use of compiler passes or by decorating the SMTP factory, which a lot of users may be unfamiliar with or reluctant to implement.

I think a dedicated transport could take care of these pain points. 

I'd be happy to work on a PR if you guys can reconsider, in light of what I mentioned above.

**Comment by javiereguiluz** [comment]
Indeed, Mailtrap is pretty popular ... and the problems explained by @PapyDanone make it hard to use it with Symfony Mailer. @stof would you consider reopening this or do you still think it's better to not add this new transport? Thanks!

**Comment by weaverryan** [comment]
The max per second stuff is for the free account. I really like Mailtrap, but I don’t think we can add a transport that would - effectively - make it easier for people to work around the free service limitations. 

However, if setting some options - like max per second - is too difficult in general, then maybe we could think of a way to make that easier :). I *do* like the focus of this issue to try to make tasks easier.

**Comment by fabpot** [comment]
And there are many free mail catcher projects to choose from.

**Comment by chrisVdd** [comment]
@fabpot can you be more specific about mail catcher projects, or give some advice ?
I face the same kind of issues, during my dev phase of building a new CMS and indeed, creating the "email" part of this project. Thanks a lot ;)
