### ISSUE TITLE
[Messenger][RFC] Multiply message buses should be hidden detail of configuration

### ISSUE THREAD

**Issue by dvc** [symfony/symfony#33949]
**Description**  
MessageBus - is abstraction of plug'n'play message dispatching. Multiply MessageBuses leads to leak of abstraction. I need to know about concrete message bus in my code. I need to replace my code then i change single bus to multiply buses.

**Variant 1: Transport first**

Message always should dispatched to transport, not bus. My code should inject some `TransportInterface $internalTransport`. Transport has to route message to bus or send to 3-rd party server.

**Pros**: same workflow for internal and external messages
**Cons**: total refactoring

**Variant 2: Single MessageBus as dispatching entrypoint (Facade)**

It's like Exchange in RabbitMQ. 
- must be only one for app
- HasNoHandlers middleware. Only routing.
- like Exchange in RabbitMQ can acts as direct, fanout, topic, etc...
- MessageBusResolver depends on mapping between collections of MessageBuses, Handlers and Transports
- not requires Enveloping messages, but can do it for concrete message buses.
- can apply common middlewares

**Pros**: no extra abstractions, minor refactoring
**Cons**: some difference between 3-rd party and self workflows

**Comment by stof** [comment]
> It's like Exchange in RabbitMQ.

this comparison is bad. RabbitMQ supports defining multiple exchanges.

**Comment by dvc** [comment]
Agree, this aspect differs :)

But RabbitMQ Exchange can route message to/between multiply queues. 

RabbitMQ Exchange ~ Symfony MessageBusFacade
RabbitMQ Queue ~ Symfony Concrete MessageBus

Messenger can support simplified variant with only one "exchange" or implement multiply "exchanges". Not the point. 

Point is: i should have ability to replace single bus to multiply buses and vice versa transparently for app. Because it is details of configuration.

**Comment by dvc** [comment]
**Simple case: one bus**

```
// some controller 
// inject concrete message bus
public function __constructor(MessageBusInterface $bus)
...
public function __invoke(Request $request)
{
...
$this->bus->dispatch(new MyCommand());
$this->bus->dispatch(new MyEvent());
}
```

**Complex case: one bus facade**

```
// some controller 
// inject facade message bus
public function __constructor(MessageBusInterface $bus)
...
public function __invoke(Request $request)
{
...
$this->bus->dispatch(new MyCommand()); // to CommandBus
$this->bus->dispatch(new MyEvent()); // to EventBus (or may be Symfony EventDispatcher :))
}
...

```

**Comment by dvc** [comment]
see also #33627 

Main question for me: what is more abstract (and should encapsulate others) - message bus or transport? Or it depends..?

**Comment by Tobion** [comment]
What are you trying to solve? I don't see a problem description.

Variant 1 does not work because you can also use messenger for syncronous messages in which case you don't want to send messages to a transport at all.
I don't see what Variant 2 does esp. since it's not clear what problem it's meant to solve.

**Comment by dvc** [comment]
Hello @Tobion 

> What are you trying to solve? I don't see a problem description.

Problem is abstraction leak. My controller will just works without knowledge about details of request domain, path, etc.  It will works for single routing rule and multiply routes too (/path1 - controller1, /path2 - controller1).

Why should i know about message routing details? I have enough info in configuration.

> Variant 1 does not work because you can also use messenger for synchronous messages in which case you don't want to send messages to a transport at all.

Why not? Transport is just some layer abstraction. Why not some SyncTransport? I don't care. I want to inject single TransportInterface. And change my routing and mapping by config. Every message will send via transports - single workflow for all of them. It is simplification for my mind.

Or single MessageBusIntrface. Only single, not multiply in my code.

> I don't see what Variant 2 does esp. since it's not clear what problem it's meant to solve.

see above. **I want to simplify user code dependencies.** I am not sure about the best way for it. MessageBusFacade is just the clearest way for me. No more abstractions required.

For example, i inject logger in my code as abstract interface. And i can change some details without changing in code.  I can send my log message to single or multiply targets too. I is realized via "channels".

**Comment by Tobion** [comment]
> Problem is abstraction leak.

I don't see where you are going. Could you be more specific with concrete examples?

**Comment by dvc** [comment]
Hello, @Tobion 

I need some time to prepare... I'll be back :)

**Comment by dvc** [comment]
[RefactoringFromSingleBusToMultiplyBuses.pdf](https://github.com/symfony/symfony/files/3862393/RefactoringFromSingleBusToMultiplyBuses.pdf)

Hello, everybody. I have create some slides for my ideas. As i wrote, main idea for me: avoid editing usercode on editing message buses map.

Page 1: current way. Single dependency should be replaced by multiply dependencies.

Page 2: hide routing by message bus facade. Example of configuration may be not good. Facade bus routing may be part of special middleware config.

Page 3: replace usercode dependency from MessageBusInterface to TransportInterface. So, any Message will always routes to Transport and optionally (if local) to MessageBus.

Consuming messages will be similar to Page 3. Consumer -> RemoteTransport -> MessageBus -> Handler. I can draw it too if will be asked.

**Comment by Nyholm** [comment]
Thank you for the details. 
I dont see a problem here either. Your controller expects a `MessageBusInterface`, it does not care about routing etc. It just knows that it should put a message on a bus. 

If you have multiple busses to the same controller one **could** argue that the controller has to be smart and to know what bus to put what message. You can solve that in your application by providing an class that wraps the message bus, eg a `CommandBus` and then add an interface `CommandBusInterface`. 

I vote for closing this issue.

**Comment by jwillp** [comment]
Hello @dvc!

Not sure If I understand this correctly, but here's my understanding:

You think that using multiple buses is an infrastructure (configuration as you called it) concern.
Your code's API should be able to dispatch messages to a single bus only, regardless of the configuration.
This is in order to be able to reconfigure the messenger as per your needs to send to different buses.

Meaning that your code would look like the following:
```php
$this->bus->distpach($message) // Where $message can be a command or an event.
```

Behind the scenes, there would be a way to route the messages to the right bus.

There are many ways to solve your problem, using what is already in the messenger component.

1 - As you said, an option would be to configure your message routing using transports.
But you don't have to change your code, for this, you should be able to do this using the transport configurations.
But, imposing a TransportInterface, would not work as @Tobion said, since synchronous messages don't rely on a transport at all.


2 - For the facade, you could do it this way, with DIC bindings:

```php
class MessageBusFacade {
    
    public function __construct(MessageBusInterface $commandBus, MessageBusInterface $eventBus) 
    {
        $this->commandBus = $commandBus;
        $this->eventBus = $eventBus;
    }

    public function dispatch($message) 
    {
        if($message instanceof EventInterface) {
            $this->eventBus->dispatch($message);
        }

        if($message instanceof CommandInterface) {
            $this->commandBus->dispatch($message)
        }
    }
}

```

Then in your DIC config, you could bind the command bus and event bus arguments to the respective buses. When you want to only use a single bus, you could remove those bindings, and would receive
the same value for both arguments -> one bus.

This would be in your case, the way to go, for abstracting messaging implementation from your controllers.
You could even go further and define a DVCMessageBusInterface which MessageBusFacade could implement.
That way your controllers would not know about any specific implementation. Now, your real implementation
would be using the Message Bus facade, relying on composition with the Messenger Component.


If I may, however, I think that in code having two different buses actually makes more sense.
A Command and an Event are actually two very different things with different intentions.
If your code uses a single Message Bus for both and even a single method for both, 
that would, in essence, indicate that the Commands and Events are actually the same thing, or work in a similar way. Which, to me, breaks SRP.
What if you ever need to add even more buses (query bus, notification bus). They all have very specific responsibilities. You could, in this case, implement an interface for each, and simply provide the right implementation using the DIC. (InMemoryCommandBus, RedisCommandBus, AQMPCommandbus, DatabaseCommandBus etc..). Now the way it is implemented, if they all rely on different communication transports or not, or if they rely on a single bus, would be abstracted by your configuration.

In all these cases, I don't think this is the messenger's responsibility to provide
facades of itself for such use cases. The messenger component's responsibility is to send messages.
Which messages you decide to send, why and where is your responsibility.

So, to answer your question:
> Main question for me: what is more abstract (and should encapsulate others) - message bus or transport? Or it depends..?

I would say the message bus. It is no wonder it is an interface: it can be configured using DIC. You can decide if you need to send those messages to transports or not.
Just like with a LoggerInterface, you can have your own implementation of a MessageBus to work the way you want.
(Supporting Transports or not, or even using a completely custom system)

Note: Although Symfony provides powerful configurations for its components, doing everything with it is not always the best way to go, nothing prevents you from using pure PHP design patterns (as shown above) to solve your problems.

Did that clarify things a bit?

**Comment by dvc** [comment]
@Tobion , @jwillp thanks a lot for detailed comments. It is more clear for me now.

Custom facade class is good decision for this use case. 
Smart controller has some semantic benefits too.
Simple configuration DSL is big advantage for component.
