### ISSUE TITLE
[Proccess] Keep process running in background even though the script is finished

### ISSUE THREAD

**Issue by erlangp** [symfony/symfony#33947]
**Description**  
Keep process running in background even though the script is finished

**Example**  
```php
echo 'A';
$process = new Process(['/usr/bin/php', 'slow-starting-server.php']);
$process->startAndKeepRunning();
echo 'B';
exit();
```

**Comment by stof** [comment]
This cannot be implemented, because of the way child processes work: a child process is killed when its parent dies.

The `server:start` command works around this restriction by forking the PHP process (requires `pcntl` so not cross-platform), setting the forked process as a session leader (so that it is not a child process of the main one anymore to avoid being killed) and uses the Process component (to run a child process with the command) in this forked process to start the process (with a loop keeping this PHP process alive as long as the process is running and the PHP process was not asked to stop it). This way, the command can exit without killing the forked process.
This requires a dedicated architecture being careful about the fact that multiple processes will be involved. It is not something we can embed in the Process class (the Process object interacts with the resource of the child process running the command, but only one of the 2 PHP processes will have access to that resource).

**Comment by xabbuh** [comment]
I am closing here for the reasons given by @stof. Thank you for proposing @erlangp.
