### ISSUE TITLE
[Messenger] Use Doctrine middleware by default

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#34073]
**Description**  
After #34066, the Doctrine middleware should now work nicely.

In fact, I think that the "clear entity manager" and "ping connection" middleware should ALWAYS be used (assuming Doctrine is installed). Both of these are very sensible things to do to make sure the database connection is alive and that data in the entity manager isn't "stale" because it's being stored in an identity map that was added to via a message handled 10 minutes ago.

There are 2 tricky parts to this:

1) The services for those middleware are added via DoctrineBundle... but the default middleware need to be added in FrameworkExtension.

2) Would we do it for *all* entity managers? I think that could (in https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Doctrine/Messenger/DoctrinePingConnectionMiddleware.php) cause connections to be made to *all* connections, even if a connection wasn't previously open (though, that could be fixed by only pinging a connection `if $connection->isConnected()`).

**Comment by Tobion** [comment]
If your handlers don't use the database, you do not want to have those middlewares enabled. So I don't see how always enabling the doctrine middlewares is a good thing. Just because doctrine is installed, does not mean every handler uses doctrine. So this must be a developers choice on case-by-case basis to me.

**Comment by weaverryan** [comment]
What about simply doing: `$em->clear()` on all EM's. I'm guessing this would have no effect on an EM that didn't have an established connection (would need to double-check this of course). I saw yet another user this week get "bit" by worker data becoming outdated because the old data was stuck in the identity map.

**Comment by guilliamxavier** [comment]
After #34156 the "clear entity manager" is always used, but what about "ping connection"? Is it necessary (in 4.4) to add this to the config?
```diff
 framework:
     messenger:
         failure_transport: failed
         transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
             failed: 'doctrine://default?queue_name=failed'
             # sync: 'sync://'
         routing:
             'App\Message\AsyncMessageInterface': async
+        buses:
+            messenger.bus.default:
+                middleware:
+                    - doctrine_ping_connection
```
And is it sufficient? Should I also add `- doctrine_close_connection`? And is the order important?

**Comment by guilliamxavier** [comment]
Answering my own questions, after trying different things: Yes, it is necessary. And sufficient. Also adding `doctrine_close_connection` seems useful to avoid letting a dangling connection that ends up being aborted by the MySQL server after `@@wait_timeout` seconds (in my case). And their relative order doesn't seem important: [DoctrinePingConnectionMiddleware](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Doctrine/Messenger/DoctrinePingConnectionMiddleware.php) pings [and resets] the connection _before_ the message is handled, whereas [DoctrineCloseConnectionMiddleware](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Doctrine/Messenger/DoctrineCloseConnectionMiddleware.php) closes the connection _after_ the message has been handled.

Actually, with `doctrine_close_connection`, I don't need `doctrine_ping_connection` anymore, because the first query on a closed (Doctrine) connection will open a new (PDO/MySQL) connection. Besides, the ping middleware always opens a connection at the start of each message handling, but all handlers won't necessarily always need a connection (it might depend on the message type, or even on the message's contents).

Please correct me if I'm wrong.
