### ISSUE TITLE
[doctrine-bridge] `MergeDoctrineCollectionListener` why we need it? 

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony#34120]
4.3.

Actually, this listener `MergeDoctrineCollectionListener` only calls `clear` on collection when it is empty, before calling `MergeCollectionListener` which one itself checks data to be merged and to be removed. 
But, this kind of behaviour in `MergeDoctrineCollectionListener` can cause a bug.
The `clear` method on `PersistentCollection`  calls `takeSnapshot` as the last action, which makes collection `not changed`, and as the result nothing will be persisted, and collection will be unchanged.

I'll try to show the bug in test project. 

I think, there is no need in `MergeDoctrineCollectionListener ` and it can be deleted.

**Comment by xabbuh** [comment]
Please provide a small example application that allows to reproduce the bug you are talking about.

**Comment by wtorsi** [comment]
Sure, here it is https://github.com/wtorsi/symfony-34120

**Comment by alcaeus** [comment]
@wtorsi the listener does not care about whether you have a `PersistentCollection` or any other collection implementation. What matters is the contract, which states that `clear` empties the collection, and thus is an alternative to iterating over it and removing every element.

As for the ORM `PersistentCollection` implementation calling `takeSnapshot` at the end and marking it "not changed", this is because two lines before taking the snapshot, it schedules a collection deletion in the UnitOfWork, which will be applied right at the start of the `flush` process. Any subsequent operation on the collection (e.g. adding a new element) will mark the collection as dirty and schedule the necessary update operations in the next `flush`.

**Comment by xabbuh** [comment]
@alcaeus Does that mean we can close here as there is no bug?

**Comment by alcaeus** [comment]
Yes, I would say so.
