### ISSUE TITLE
Runnable query not runnable in DoctrineDataCollector

### ISSUE THREAD

**Issue by garak** [symfony/symfony#34234]
**Symfony version(s) affected**: 4.3 and 4.4.X

**Description**  
This is a reopening of issue #24782, that was closed with merged code. I'm not sure if merged code was working and then at some point was regressed, or if instead it never worked

**How to reproduce** 
Just like old issue: run a query with an object identifier (like Ramsey\Uuid) and inspect query in profiler, clicking "View runnable query".

Example of viewed query:

```sql
SELECT e0_.name AS name_0, e0_.id AS id_2 FROM element e0_ WHERE e0_.id = '/* Object(Ramsey\\Uuid\\Uuid): */\"919a1f66-6e93-412d-909e-6a851b3f1ec8\"' LIMIT 1;
```

Query should be instead:
```sql
SELECT e0_.name AS name_0, e0_.id AS id_2 FROM element e0_ WHERE e0_.id = /* Object(Ramsey\\Uuid\\Uuid): */ '919a1f66-6e93-412d-909e-6a851b3f1ec8' LIMIT 1;
```

**Comment by fancyweb** [comment]
Status: reviewed

The bug exists. I analyzed it. I doubt we can do something on 3.4 and 4.3 because collected data is "raw" and`DoctrineBundle` add simple quotes and add slashes when outputting them (https://github.com/doctrine/DoctrineBundle/blob/755847de53877f30432dab7f16c5a9df13eb1300/Twig/DoctrineExtension.php#L231). Strings will always be wrapped by `'`. Objects could use `__toString()` but simple quotes will be escaped by `addslashes`...

However, on 4.4, we can do something because params are now cloned with the var dumper (https://github.com/symfony/symfony/blob/81588eb835f4501d943e9bb64d2bd9f31671a430/src/Symfony/Bridge/Doctrine/DataCollector/DoctrineDataCollector.php#L171). I opened a PR that uses this opportunity.
