### ISSUE TITLE
symfony/notifier 4.4.x-dev - shouldn't notifier be usable with 4.4?

### ISSUE THREAD

**Issue by c33s** [symfony/symfony#34417]
**Symfony version(s) affected**: 4.4.0-dev

**Description**  
according to the composer file `symfony/notifier` conflicts with a `symfony/http-kernel` smaller than `4.4`. so it looks like to be compatible with `4.4`.

as far as i know x.4 should be compatible with y.0 (4.4 with 5.0) only the deprecations are removed. so the notifier component should be working with 4.4 but i get the error:
```
 Unrecognized option "notifier" under "framework". Available options are
```

if you compare the two versions you see the notifier config is missing:

https://github.com/symfony/symfony/blob/v4.4.0-BETA2/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php

vs

https://github.com/symfony/symfony/blob/v5.0.0-BETA2/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php

is there a special reason why notifier is not included in 4.4? please bring it to 4.4 as the notifier component is awesome to wait until 5.4 to use.

**Comment by fabpot** [comment]
The Notiifer Component is only available in 5.0. Why? Because the component is marked as experimental and we cannot have experimental components in an LTS version.

If you are using LTS versions, it means that you only want to use stable features, and indeed you will need to wait for 5.4.

If not, then use 5.0 instead of 4.4.
