### ISSUE TITLE
[cache] Make cache item expiry accessible

### ISSUE THREAD

**Issue by drzraf** [symfony/symfony#34487]
**Description**  
I would like read-only access to [CacheItem->expiry](https://github.com/symfony/cache/blob/master/CacheItem.php#L29), eg via a `getExpiry()` method.

**Example**  
I use cache as a kind of locally-stored-expiring-lock in order to avoid reissuing a (temporary) failed HTTP request during a given time.
When checking for the cacheItem I would like to access the expiry.
My use-case is that I can issue a request short *before* cache actually expire and progressively increase its expiration time (like 1 hour, 3 hours, 6 hours, ...).

Reference:
https://stackoverflow.com/questions/58527540/how-to-get-expiration-datetime-of-items-using-symfonys-cache-component

**Comment by mcsky** [comment]
Expiry is accessible with 

```php
/** @var ItemInterface */
$metadata = $item->getMetadata();
$expiry = $metadata[ItemInterface::METADATA_EXPIRY];
```

**Comment by mcsky** [comment]
Maybe the method `Symfony\Component\Cache\CacheItem::expiresAt(...)` should set the metadata[ItemInterface::METADATA_EXPIRY] attribute ?

**Comment by nicolas-grekas** [comment]
The expiry is stored only if you use the `CacheInterface` from symfony/cache-contracts.
@mcsky gave the call to get it.
When using PSR-6/PSR-16, the expiry cannot be made accessible, because that would generate bigger storage needs for everyone, while reading the info is usually not needed.
If you cannot use `CacheInterface`, you'd need to store the expiry on your own as a sidekick of the cached value. (e.g. `->set([$value, $expiry])`)
Closing therefor.
