### ISSUE TITLE
[PHPUnitBridge] fail only for "new" deprecations / "baseline" feature

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#34496]
**Description**  
On a big work project (that started with Symfony 2.1 and is now on 4.3) we recently introduced the PHPUnitBridge to keep track of deprecations.

Unfortunately it currently reports a variety (> 2000) of deprecations trigged in our own code-base. We are slowly fixing those but this will take some time.

While we are still fixing those deprecations unfortunately whenever new code is merged it might introduce more/new deprecations again :cry: 

I was thinking it would be really nice to be able to make our CI build fail **only** for new deprecations reported by the bridge.

This is similar to the phpstan baseline feature maybe: https://medium.com/@ondrejmirtes/phpstans-baseline-feature-lets-you-hold-new-code-to-a-higher-standard-e77d815a5dff

WDYT? Is this something that might be interesting and not too complex to implement?

**Comment by nicolas-grekas** [comment]
Generating a baseline could be a nice idea - setting some option in the SYMFONY_DEPRECATIONS_HELPER to record it, and use it later.
PR welcome.

**Comment by ruudk** [comment]
I really like how PHPStan does this. Especially since it will error again if you ignore an error that is not triggered, urging you to update your ignored error list.

This is something I really mis right now. In my project I have one external dependency that triggers a `A tree builder without a root node is deprecated` message. If I can just tell PHPUnitBridge that this one is fine, I can prevent future deprecations immediately.
