### ISSUE TITLE
[Notifier][RFC] Do we need the distinction between Chatters and Texters?

### ISSUE THREAD

**Issue by magnusnordlander** [symfony/symfony#34544]
I was trying to understand the notifier component in order to write documentation for it, and I'm confused by Chatters and Texters. 
 
I don't understand the need for the distinction. From what I understand Texters are supposed to be for SMS messages, and Chatters are supposed to be for all other chat style messages, but the implementations in Chatter and Texter is exactly the same. Furthermore, I don't think the distinction is particularly clear cut. SMS:es are clearly Texts, but what about MMS:es? What about iMessages?

There is already a distinction in that we have both SmsMessage and ChatMessage classes. I propose we should replace Chatter and Texter by a single concept, and that we should simplify configuration by just having a single `transports` section instead of `chatter_transports` and `texter_transports`. I would be happy to work on a PR for this, but I would like some feedback on the idea first.

#SymfonyHackday

**Comment by fabpot** [comment]
To be honest, I went back and forth on this one. At some point, I removed the distinction, but introduced it again later one in the development process. I'd like to see how adding other notifiers that are not SMSes or chat would work before making a decision.

**Comment by wouterj** [comment]
After some testing in a demo application, I can see how there is a difference between Texters and Chatters.

Texters all implement the same protocol: SMS. Chatters are bridges between your app and some third party notification provider (slack, push notifications, iMessages, etc). MMS is a tricky one, as it would also be a protocol instead of some provider.

So whereas just any enabled texter transport would be fine (they all result in the same thing: an SMS being send to a specific phonenumber), it does matter which chatter transport has send your notification (Slack is something different from Telegram, WhatsApp or push notifications).

---

While writing this, I feel like texters are just the failover variant of chatters:

```yaml
framework:
  notifier:
    texter_transports:
      twilio: '%env(TWILIO_DSN)%'
      nexmo: '%env(NEXMO_DSN)%'

# is effectively equal to
framework:
  notifier:
    chatter_transports:
      sms: '%env(TWILIO_DSN)% || %env(NEXMO_DSN)%'
```

So that would be in favor of merging both concepts and having only a `transports` setting.

**Comment by fabpot** [comment]
I've done an updated version of my London's talk about the Notifier today. Having a Texter abstraction means that you can only use that to send SMSes without anything else from the Notifier component. That's a big plus to me. And having looked at the code again, I'm pretty sure that we do need to keep the two channels (Texter and Chatter). We might even add more with push messages, ...
