### ISSUE TITLE
[4.4] Tests slow after updating to 4.4

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#34567]
**Symfony version(s) affected**: 4.4

Somehow our testsuite became extremely slow after updating to 4.4. It's a regular API platform setup, using hautelook fixtures. So DB is reloaded on every test.

In the `var/cache/test` it seems to boot/cache a compiled container container *per testcase*. If i abort after first testcase, and then restart the testsuite it seems to pick up the existing container.

Moreover, the behavior is exposed using:

```
# FAST
rm -rf var/cache/test
bin/phpunit

# SLOW
rm -rf var/cache/test
bin/console c:c -e test
bin/phpunit

# ALSO SLOW
rm -rf var/cache/test
bin/console c:c --no-warmup -e test
bin/phpunit
```

Im not sure where to look for now, hints welcome :) i've updated all recipes etc. so everything is "latest 4.4".

**Comment by nicolas-grekas** [comment]
Check Blackfire.io for hints ;)

**Comment by ro0NL** [comment]
@nicolas-grekas it's caused by https://github.com/symfony/http-kernel/commit/354bcae4

**Comment by nicolas-grekas** [comment]
If you want me to help, I'd need a reproducer. A blackfire comparison would be a good start in any case.

**Comment by acasademont** [comment]
We're seeing our tests also being far slower in 4.4. Hopefully I can provide some Blackfire profiles tomorrow :)

**Comment by Kocal** [comment]
Since Symfony 4.4 update, our PHPUnit tests now take ~9 minutes instead of ~15 seconds to run 586 tests and 610 assertions (we use `KernelTestCase` literally everywhere because we need to access the container). 

Here some blackfire traces for only one file (running blackfire on every files make it crash):

- before: https://blackfire.io/profiles/268eb1ef-70cc-4c0a-a870-273681af6f09/graph
- after: https://blackfire.io/profiles/ae3dc62f-d47f-43af-9907-02afe1867513/graph
- comparaison: https://blackfire.io/profiles/compare/60a8dd23-f525-4f59-bb1d-965b8fc1fcc4/graph

```bash
rm -rf var/cache/test && bin/console c:c -e test
blackfire run bin/simple-phpunit tests/phpunit/Security/Voter/SectorVoterTest.php # slow
blackfire run bin/simple-phpunit tests/phpunit/Security/Voter/SectorVoterTest.php # fast

```

Thanks!

**Comment by acasademont** [comment]
Feels like the container is built a gazillion times

**Comment by nicolas-grekas** [comment]
Thanks for the hints. Can anyone please confirm #34580 fixes the issue?

**Comment by acasademont** [comment]
@nicolas-grekas yes! test speeds are back to normal :D

**Comment by acasademont** [comment]
I'd say tests are even faster now, amazing!

**Comment by stof** [comment]
@acasademont sure they are. The initial change was meant to speed them up. But that's only true when the optimizing logic is not buggy.
