### ISSUE TITLE
twig-bundle dependencies missing to include inky_to_html-filter, resulting in error when updating translations

### ISSUE THREAD

**Issue by Knallcharge** [symfony/symfony#34586]
**Symfony version(s) affected**: 4.4.0

**Description**  
After updating from Symfony 4.3 to 4.4 (changing composer.json manually and using composer update), I'm faced with the error message "In body.html.twig line 1: Unknown "inky_to_html" filter." when trying to update my translations (bin/console tran:up <locale>).

**How to reproduce**  
Migrate Symfony to 4.4 by changing composer.json & calling composer update
Execute php bin/console tran:up <locale>

**Possible Solution**  
When in the project directory, adding the dir to the command is a workaround:
php bin/console tran:up <locale> .

**Additional context**  
https://stackoverflow.com/questions/59029924/symfony-4-4-unknown-inky-to-html-filter also has my composer.json (as I can't attach it here)

**Comment by abdounikarim** [comment]
Hello,

Did you add the library with : 
`composer require twig/inky-extra` ?

Cheers 😉

**Comment by Knallcharge** [comment]
That's what the bug is all about: shouldn't the requirement be added automatically?

**Comment by abdounikarim** [comment]
i think... no. Because you can use twig without this.

**Comment by Knallcharge** [comment]
Symfony 4.4 requires symfony/twig-bridge and that requires twig/inky-extra, but is not included when using composer update. Please check the stackoverflow-link.

**Comment by stof** [comment]
@fabpot weren't we ignoring Twig templates producing a syntax error when extracting translations, instead of failing the whole extraction ?
That's what is happening here. The new zurb email templates depend on `twig/inky-extra`, but that is an optional dependency of the twig-bridge, as it is not needed for all other features of the bridge.

**Comment by jbdelhommeau** [comment]
I have the same error. I don't want to install `twig/inky-extra` because I don't need it.
I'm willing to do an MR.

**Comment by fabpot** [comment]
@stof No, we weren't ignoring errors. See #34711 for a fix.

**Comment by burned42** [comment]
I see this is supposed to be fixed, but I just started using translations and got the same error message complaining about missing `inky_to_html` and `markdown_to_html` when calling `lint:twig` (after seeing that `translation:update` would remove all my translations, because it says they're unused).

To get rid of the error message and to get `lint:twig` "green" again, I had to install `twig/extra-bundle`, `twig/inky-extra`, `twig/markdown-extra` and because after I installed those, it started to complain about missing `inline_css` filter, I also had to install `twig/cssinliner-extra`. Note that I'm not using any of those filters in my code/templates.

Am I supposed to install all those packages manually, or is there maybe a problem that brought this issue back?
