### ISSUE TITLE
[Debug] Preview errors in debug does not work anymore

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#34602]
**Symfony version(s) affected**: 5.0.0 (at least)

**Description**  
the following URL https://127.0.0.1:8001/_error/404 does not preview the error anymore. It display a regular error in debug mode

**How to reproduce**  
```
>/tmp symfony new sf-5.0 --full
* Creating a new Symfony project with Composer
  (running /usr/local/bin/composer create-project symfony/website-skeleton sf-5.0)

* Setting up the project under Git version control
  (running git init sf-5.0)

                                                                                                                        
 [OK] Your project is now ready in /tmp/sf-5.0                                                                          
                                                                                                                        

>/tmp cd /tmp/sf-5.0
>/tmp/sf-5.0(master) symfony serve -d 
                                                                                                                        
 [OK] Web server listening on https://127.0.0.1:8001 (PHP FPM 7.4.0)                                                    
```                 

Then open this URL https://127.0.0.1:8001/_error/404
and see this exception                                                                                                        
![image](https://user-images.githubusercontent.com/408368/69556499-1ab03f00-0fa5-11ea-8813-6f13951d8f39.png)

**Comment by fancyweb** [comment]
Actually it looks like the full error templating is gone on 5.0. TwigBundle preview and exception controllers are gone there, as well as the "find template" in the TwigBundle logic. https://symfony.com/doc/current/controller/error_pages.html was not updated.
Don't we need a preview error renderer on 5.0 that will look for those templates again ?

**Comment by ogizanagi** [comment]
It seems the [TwigBundle/Resources/views/Exception/error.html.twig](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/TwigBundle/Resources/views/Exception/error.html.twig) file was removed in 5.0. I'm not sure this is expected as https://github.com/symfony/symfony/pull/31398 mentions only non-html templates are deprecated and it is still referenced in https://github.com/symfony/symfony/blob/7719fc709e6d5f5d44d15417b0ff132c4ee39a3f/src/Symfony/Bridge/Twig/ErrorRenderer/TwigErrorRenderer.php#L83 without any fallback if you don't have override this template yourself in your app.

**Comment by yceruto** [comment]
The preview mode feature was moved to the FrameworkBundle (see ErrorController), as well as the default HTML error page is now hosted into ErrorHandler component (pure PHP page).

The TwigErrorRenderer will work in preview and non-debug mode only if you have a custom Twig-based error page here:
 * `templates/bundles/TwigBundle/Exception/error404.html.twig`
 * `templates/bundles/TwigBundle/Exception/error.html.twig`
otherwise it fall back to HTMLErrorRenderer, which does not supports the preview mode. @lyrixx can you confirm that this is the case?

I think what we lacked here was the preview mode support for HTMLErrorRenderer and SerializerErrorRenderer (for consistency). I'll try tonight, in the meantime, PR welcome.

Doc PR in progress https://github.com/symfony/symfony-docs/pull/12687

**Comment by yceruto** [comment]
See https://github.com/symfony/symfony/pull/34619
