### ISSUE TITLE
Make .env files optional in production?

### ISSUE THREAD

**Issue by mnapoli** [symfony/symfony#34660]
**Description**  

The [config/bootstrap.php](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/config/bootstrap.php) file requires either a `.env` or `.env.local.php` file to exist.

Those files are useful to load environment variables. However, if you setup your production to populate real environment variables, `.env` is unnecessary. Yet you get an exception in production, forcing you to deploy empty files.

What about removing the requirement for those files in production?

That would have the side benefit of encouraging users to use actual environment variables.

**Example**  

Maybe a change like this in `bootstrap.php`:

```diff
if (is_array($env = @include dirname(__DIR__).'/.env.local.php') && ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? $env['APP_ENV']) === $env['APP_ENV']) {
    foreach ($env as $k => $v) {
        $_ENV[$k] = $_ENV[$k] ?? (isset($_SERVER[$k]) && 0 !== strpos($k, 'HTTP_') ? $_SERVER[$k] : $v);
    }
} elseif (!class_exists(Dotenv::class)) {
    throw new RuntimeException('Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.');
- } else {
+ } elseif (($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV']) !== 'prod') {
    // load all the .env files
    (new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env');
}
```

**Comment by mnapoli** [comment]
Sorry, my code example is completely wrong 😅  Anyway hopefully you get the idea: if `.env` is here we load it, if not we throw an error only if we are not in production.

**Comment by TheGarious** [comment]
You need a .env for your configuration

**Comment by TheGarious** [comment]
You don't have a configuration from your project ?

**Comment by mnapoli** [comment]
@TheGarious in production, the configuration is done via real environment variables (in some projects). The `.env` files are not necessary.

**Comment by TheGarious** [comment]
This .env is like a parameter.yml.dist from Symfony < 3.3 

It's a versionning file

**Comment by nicolas-grekas** [comment]
Loading `.env` files is on purpose. We want ppl to be able to use the most convenient way to define env, prod included. Use real env vars for dynamic values or if it's convenient enough for you, use .env files if they are more convenient and you don't need dynamic values.

There is no downside to loading .env files in prod - but there are benefits (the just mentionned ones).

Don't miss using `composer dump-env prod` after running `composer install -o --no-dev`.

I'm closing because this has been discussed several times and we stabilized on the current situation after many iterations - this is really the best behavior for everyone. (as you spotted you can patch the file if you don't want this behavior).

**Comment by mnapoli** [comment]
I feel like I failed to explain the problem clearly.

> Use real env vars for dynamic values if it's convenient enough for you, use .env files if they are more convenient and you don't need dynamic values.

I do use env vars. The thing is that this doesn't work with Symfony.

If I use env vars to configure my app in production, then the app will crash in production.

In other words, Symfony is forcing to create a `.env` file, even if you don't use it. Does that make more sense?

Is that intended behavior? Because if that's the case, that means that Symfony is not configurable via env vars only. Which sounds weird because `.env` files are a way to emulate environment variables in scenarios where it's not practical to define them (e.g. locally). But it turns out that "polyfill" has become a replacement of actual env vars.

**Comment by jelen07** [comment]
Requiring `.env` file as mandatory has more disadvantages. Since apps running in containers, there is no need to loads .env files and you still get the benefits when you want the `.env` just use it.

It would be more container & DevOps friendly to not force devs to have empty `.env` file as well as running extra command (`composer dump-env prod`).

The intention is to have an application minimal as possible - from the size perspective and also complexity.

And there is also the security issue - versioning ENVs where sensitive data may be is not a good habit at all.
