### ISSUE TITLE
config:dump-reference does not see my own tree anymore

### ISSUE THREAD

**Issue by jpauli** [symfony/symfony#34756]
**Symfony version(s) affected**: 4.4.1

**Description**  
If I create a config tree not in a bundle, f.e in my Kernel, then the config:dump-reference command does not see it. It used to see it in Symfony 4.3 and before, with "bundle name" simply not set

**How to reproduce**  
Create a Kernel that is an Extension and a Configuration.
Implement the methods

```php
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\DependencyInjection\Extension\ExtensionInterface;

class Kernel extends BaseKernel implements ExtensionInterface, ConfigurationInterface
{
       public function load(array $configs, ContainerBuilder $container)
	{
		$processor = new Processor();
		$config    = $processor->processConfiguration($this, $configs);
	}

	public function getNamespace()
	{
		return '';
	}

	public function getXsdValidationBasePath()
	{
		return false;
	}

	public function getAlias()
	{
		return 'foobar';
	}

	public function getConfigTreeBuilder()
	{
		$tree = new TreeBuilder($this->getAlias());
                // do something
                return $tree;
        }
}
```

**Possible Solution**  

**Additional context**

**Comment by ogizanagi** [comment]
Are you sure this was working before 4.4? 
While defining an extension from the kernel like you did was always possible to me, I think the command always only listed the bundles, not all extensions.

**Comment by jpauli** [comment]
I remember it working. Not sure about the version though, SF 3 or SF 4

**Comment by stof** [comment]
Please provide a reproducer of it working on older versions. I don't understand how that is possible.

**Comment by nicolas-grekas** [comment]
No need for a reproducer - let consider it as a feature request. It'd be nice to have this tree displayed too :)

**Comment by raffaelecarelle** [comment]
What about to have a function inside "Kernel" called getExtension() which retuns an instance of AppExtension (for example). AppExtension class should extends Symfony\Component\DependencyInjection\Extension\Extension and then override getConfiguration method, that returns AppConfiguration instance that implements ConfigurationInterface and so, it defines the getConfigTreeBuilder method. 

Finally we can change the execute method in ConfigDumpReferenceCommand (from line 82 to 92):
```
$name = $input->getArgument('name');
$kernel = $this->getApplication()->getKernel();
if (null === $name || 'app' === $input->getArgument('name')) {
    if (method_exists($kernel, 'getAppExtension')) {
        $extension = $kernel->getAppExtension();
    } else {
        $this->listBundles($errorIo);
        $errorIo->comment(['Provide the name of a bundle as the first argument of this command to 
            dump its default configuration. (e.g. <comment>config:dump-reference 
            FrameworkBundle</comment>)',
            'For dumping a specific option, add its path as the second argument of this command. (e.g. 
            <comment>config:dump-reference FrameworkBundle profiler.matcher</comment> to 
            dump the <comment>framework.profiler.matcher</comment> configuration)',
        ]);
        return 0;
    }
} else {
    $extension = $this->findExtension($name);
}
```

As you can see, I add a check of input. If user types 'app' as first input the command shows only app configuration. Thats becouse the command can take two arguments (first for bundle and second for config node). Like so the user can specify the input for app and a node inside the app configuration. Otherwise if user doesn't type any argument, by default the command will show the configuration app.

Waiting feedback.

Cheers! :)
