### ISSUE TITLE
Console choice forces answers as strings

### ISSUE THREAD

**Issue by LordZardeck** [symfony/symfony#34789]
**Symfony version(s) affected**: 4.3

**Description**  
When using `choice`, selected answers are forced into strings, preventing us from using complex values such as a class with a custom `__toString`. This is a problem, as I need the ability to present the user with a list of display strings to choose from, but need the ID associated with that display string in order to do anything useful. 

**How to reproduce**  
```php
class UserRoleOption
{

    public $id;
    public $name;

    public function __construct($id, $name)
    {
        $this->id = $id;
        $this->name = $name;
    }

    public function __toString()
    {
        return $this->name;
    }
}

foreach ($rolesQuery as $role) {
    $roles[] = new UserRoleOption($role->id, $role->name);
}

var_dump($this->choice('Select roles to assign', $roles));
```

**Possible Solution**  
Remove the cast to string on this line: https://github.com/symfony/console/blob/master/Question/ChoiceQuestion.php#L172

**Comment by dsentker** [comment]
I do not quite understand the problem. The (string) cast does the same thing as the manual call to __toString(). If you need name and ID, why not use the __toString() magic?

```php
public function __toString()
{
    return sprintf('%s (#%d)', $this->name, $this->id);
}
```

**Comment by flip111** [comment]
@dsentker i think he does not want to present the id to the user because it's for internal use of the application.

When looking in the docs https://symfony.com/doc/current/components/console/helpers/questionhelper.html#let-the-user-choose-from-a-list-of-answers one can let the user choose between a bunch of strings `['red', 'blue', 'yellow']`

However instead of strings now objects have been passed which will be casted implicitely by https://github.com/symfony/console/blob/master/Question/ChoiceQuestion.php#L156

It's a matter of ergonomics in the application wether to build the choice with objects to get the right choice back as an object.

Or to have some kind of lookup table (assosiative array?) that maps strings back to class names which can then be constructed. This assumes that the id's (in the object) can also be known AFTER the user makes the choices.

I think the original (string) cast https://github.com/symfony/console/blob/master/Question/ChoiceQuestion.php#L172 was there to emulate what the user has typed in the console himself. But i see no reason to not just return an object instead of one of the choices.

Looks like a good change to me to remove `(string)` cast

**Comment by dsentker** [comment]
OK, thanks for the explanation. The `QuestionHelper` is not suitable for entities. I could well imagine that a new helper (e.g., `EntityChoiceQuestion`) is offered, which extends the `QuestionHelper`.

The answer options for the new `EntityChoiceQuestion` Helper could then be filled with entities. The helper just needs to make sure each entity includes the getId() method to ensure that the user input is mapped back to the entity.

**Comment by flip111** [comment]
`Entity` is a concept specific to Doctrine. Don't really see the point of adding another class and more code for just this feature when removing string cast will do. Using `getId` is not even necessary because you already have objects, in other words ... there is nothing to "map". Mapping is only necessary with the current situation without the feature of keeping the object as is.

**Comment by rbaaboud** [comment]
Hi,

I'm facing the same issue.
I explain it with my words.

If i have Roles :
```php
$roles = [
    12 => 'admin',
    45 => 'moderator'
];
```

I would like to have : 

```php
$role = $this->choice('Which role?', $roles);
// if selected role is admin : $role = 12
```

But now, `$role = 'admin'`

Thanks a lot.
