### ISSUE TITLE
[PropertyInfo] Rename Type::getBuiltinType() to Type::getPhpType() ?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#34964]
**Description**  
I find the `Type::getBuiltinType()` method name confusing because of "built-in": where's the data type built-in? In PHP? In Symfony? In Doctrine DBAL?

I think that `getPhpType()` would avoid that confusion.

In any case, "renaming + deprecations" are always annoying for end-users ... so let's think if this is really worth it. Thanks!

**Comment by webnet-fr** [comment]
[PHP documentation](https://www.php.net/manual/en/language.types.intro.php) refers to `array`, `bool`, `callable`, `float`, `int`, `iterable`, `null`, `object`, `resource` or `string` as **primitive types**. "Build-in type" term is kind of vague because `stdClass` and SPL classes can also be considered as such. So I'd rather suggest `Type::getPrimitiveType()`.

BTW, if we deside to rename the method `Type::getPhpType()` we will also need to rename constants `Type::BUILTIN_TYPE_INT`, etc.

**Comment by nicolas-grekas** [comment]
The name comes from this: https://www.php.net/manual/en/reflectiontype.isbuiltin.php
I don't think we should create our own vocabularies.

**Comment by Seb33300** [comment]
So, `getPhpBuiltInType`?

**Comment by javiereguiluz** [comment]
Let's close this because it's too minor and not worth it. Thanks.
