### ISSUE TITLE
 Uncaught Error: Class 'Symfony\Component\Debug\Debug' not found in index.php:12 Stack trace: #0 {main} thrown in

### ISSUE THREAD

**Issue by kasali** [symfony/symfony#34992]
We use GitHub issues only to discuss about Symfony bugs and new features. For
this kind of questions about using Symfony or third-party bundles, please use
any of the support alternatives shown in https://symfony.com/support

Thanks!
After upgrading 4.4.1 to symfony 5.0 i have this error!

**Comment by javiereguiluz** [comment]
@kasali as shown in https://symfony.com/support, we don't provide support on GitHub either. You should use StackOverflow or Slack.

In any case, this issue is caused because Debug component has been replaced by ErrorHandler component in Symfony 4.4 (see https://symfony.com/blog/new-in-symfony-4-4-errorhandler-component).

Your `public/index.php` controller probably still refers to `Debug`. Check if that file looks like this one, which uses ErrorHandler instead of Debug: https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.4/public/index.php
