### ISSUE TITLE
The class GmailSmtpTransport always use 465 port for StartTLS

### ISSUE THREAD

**Issue by lamzin-andrey** [symfony/symfony#35174]
**Symfony version(s) affected**: 5.0.2

**Description**  
In the code GmailSmtpTransport.php always set 465 port.
(parent::__construct('smtp.gmail.com', 465, true, $dispatcher, $logger);)

I think, gmail.com use 587 port for StartTLS

**Comment by azjezz** [comment]
:+1: Gmail uses port `587` for TLS/STARTTLS as documented here : https://support.google.com/mail/answer/7104828?hl=en&visit_id=637136505340573721-3114450189&rd=3

**Comment by fancyweb** [comment]
Status: reviewed.

@lamzin-andrey Are you able to send a pull request that fixes the issue (as a bug fix on 4.3)? Thanks.

**Comment by lamzin-andrey** [comment]
> Status: reviewed.
> 
> @lamzin-andrey Are you able to send a pull request that fixes the issue (as a bug fix on 4.3)? Thanks.

Now I do not understand, how I can do it.

**Comment by fancyweb** [comment]
You can read https://symfony.com/doc/current/contributing/code/pull_requests.html.

**Comment by lamzin-andrey** [comment]
I will try do it, but I do not understand, how many time it take.

**Comment by fabpot** [comment]
Both work (I've just tested on Symfony 5.0).
465 SSL or 587 STARTTLS.
So, in 4.4/5.0/5.1, we can use `465, true` or `587, false`.
`465, true` means that we use SSL for the connection
`587, false` means that we use a regular connection and use STARTTLS to upgrade.

So, before changing anything, I'd like to understand the issue you have.

**Comment by fabpot** [comment]
Closing as there is no feedback.

**Comment by edgargalvezr** [comment]
When using the GmailSmtpTransport class in development, you can access Gmail and send the email but when uploading to the production server it gives the following error:

Connection could not be established with host "ssl: //smtp.gmail.com: 465": stream_socket_client (): unable to connect to ssl: //smtp.gmail.com: 465 (Network is unreachable)

To solve this I have modified the GmailSmtpTransport class, changing the port to 587 and tls to false.
`parent :: __ construct ('smtp.gmail.com', 587, false, $ dispatcher, $ logger);`
Having done this is not correct, so I suggest giving yourself options when configuring the GmailSmtpTransport so that you can change the post and the tls.
