### ISSUE TITLE
[Doctrine] Provide a MongoDB pack

### ISSUE THREAD

**Issue by emulienfou** [symfony/symfony#35196]
**Description**  
This feature is aim to provide a Symfony Pack for Doctrine ODM (MongoDB), based on the same idea of the [Symfony Pack for Doctrine ORM](https://github.com/symfony/orm-pack).

The idea here is to provide for developers who are using Doctrine MongoDB instead of ORM a pack which is a Composer meta-package that include several dependencies to work easily with Doctrine MongoDB and Symfony.

This Pack will be able to support MongoDB ODM **1.x** has well has **2.x**.

> This feature will create the new composer package: `symfony/mongodb-pack`

**Providing**
This Symfony Pack, will provide the next dependencies for ODM **1.x**:
* `"alcaeus/mongo-php-adapter": "^1.1"`
* `"doctrine/mongodb-odm-bundle": "^3.4"`
* `"doesntmattr/mongodb-migrations-bundle": "^2.0"`
> Note: in this case, a user will need to execute the next command: `composer config "platform.ext-mongo" "1.6.16"` because `ext-mongo` is not available on PHP 7!
> See: [README.md](https://github.com/emulienfou/mongodb-pack/blob/v1.0.0/README.md)

And will provide the next dependencies for ODM **2.x**:
* `"doctrine/mongodb-odm": "^2.0"`
* `"doctrine/mongodb-odm-bundle": "^4.0"`
> Note: package **doesntmattr/mongodb-migrations-bundle** is currently not compatible with ODM 2.x, see issue: https://github.com/doesntmattr/mongodb-migrations-bundle/issues/27

**Example**  
Let's see how to use this Symfony pack!   
The only think a developer who will need is to require the symfony pack like:
```
 composer require symfony/mongodb-pack
```

**Testing**
This feature is already available on a package I create months ago.   
To test it with ODM **1.x** you should use: `composer require emulienfou/mongodb-pack:v1.0.0`   
For ODM **2.x** you should use: `composer require emulienfou/mongodb-pack:v2.0.0`

**Sources**
Sources of this feature are available on this repository: https://github.com/emulienfou/mongodb-pack

**Providing virtual packages**
One other thing would be really great to implement in this Symfony Pack would be to provide some virtual packages.   
Currently the package I made implement 2 virtual packages:
* `doctrine/implementation`
* `doctrine/mongodb-implementation`

This virtual packages could be used to require a Doctrine database support.   
The package `doctrine/implementation` is used to require a doctrine implementation (ORM or ODM), whereas `doctrine/mongodb-implementation` is used to require a Doctrine MongoDB implementation.

By using the virtual packages, a bundle could be decoupled from Doctrine ORM or ODM in the `require` key of a `composer.json` file.

**Comment by derrabus** [comment]
cc @alcaeus

**Comment by alcaeus** [comment]
Just a quick comment before going into detail: please don’t add support for ODM 1.x. Running it on PHP 7 requires a very performance-heavy adapter due to the legacy driver not being available. The pack is also only useful (at least in my opinion) for people starting a new project, not people already having a project with ODM in use. In that situation, there is literally no reason to use ODM 1.x (unless you require PHP < 7.2, in which case you should bite the bullet and get ODM 1.x running yourself).

**Comment by fabpot** [comment]
As I'm not using ODM, I won't provide such a pack. IMHO, it should probably be provided by Doctrine.

**Comment by emulienfou** [comment]
@fabpot completly understand your concern!   
In that case, I think it should be better to have both ORM and ODM packs provided by Doctrine.

So we should have:
* `doctrine/orm-pack`
* `doctrine/mongodb-pack` or `doctrine/odm-pack`

What people think about that?

**Comment by alcaeus** [comment]
Thinking about this some more, I'm not sure about the need for a pack at all. The ORM pack works fine as is and is part of the Symfony Core experience, so it makes sense that Symfony controls that - especially since `symfony/orm-pack` could theoretically introduce an ORM that is different from Doctrine (for whatever reason).

As for MongoDB ODM, with 2.0 there's a single dependency that is necessary: `doctrine/mongodb-odm-bundle`. The `mongo-php-adapter` library is only necessary when using ODM 1.x (which I wouldn't recommend for new projects), while the concept of migrations is something that should not be introduced to a MongoDB database the way it is handled in SQL. MongoDB schema is way more flexible than your typical RDBMS table, which also allows you to not have to worry about adding fields to all documents in a collection. There are much better ways to deal with such changes in MongoDB. I would absolutely be against recommending such a library to be used.

With that in mind, there is no difference to `composer require doctrine/mongodb-odm-pack` over `composer require doctrine/mongodb-odm-bundle`.

**Comment by xabbuh** [comment]
Let's close then. Thank you for the feedback @alcaeus.
