### ISSUE TITLE
[Workflow] ANNOUNCE event should be optional

### ISSUE THREAD

**Issue by Harry-Dunne** [symfony/symfony#35286]
Q | A
-- | --
Bug report? | no
Feature request? | yes
BC Break report? | no
RFC? | no
Symfony version | 4.4.2

The workflow.announce event has a side effect : it fires guard events for all accessible transitions from the subject's place, even if there is no subscriber registered for this event. AFAIK it's the only event of the workflow component with this behavior.

Code in guard event, usually business rules, can be costly to execute. This cost is useless if the announce event is not leveraged, so the dispatching of this event should be optional.

**Comment by xabbuh** [comment]
Can you be a bit more precise what you mean? Reading the code I do not see any difference in how we dispatch the different events.

**Comment by Harry-Dunne** [comment]
https://github.com/symfony/symfony/blob/ddc016988ec6728adf4ead6de6adeb7510865029/src/Symfony/Component/Workflow/Workflow.php#L402

When workflow.announce event is dispatched, Workflow::getEnabledTransitions() method is called, and thus all guard events are dispatched for each possible transition from the subject's place.

Others events (except guard events themselves, obviously) don't fire guard events and are less expensive.

**Comment by lyrixx** [comment]
@Harry-Dunne How would you configure this behavior? (from the end developer perspective) Thanks

**Comment by Harry-Dunne** [comment]
The simplest way I can figure is adding an optional boolean argument to Workflow::apply() method.

```php
public function apply(object $subject, string $transitionName, array $context = [], bool $dispatchAnnounceEvent=true)
{
        [...]
        if ($dispatchAnnounceEvent) {
            $this->announce($subject, $transition, $marking);
        }
        [...]
```

This argument is set to true as default for BC.

**Comment by lyrixx** [comment]
I usually don't like to add flag to methods because we may end with 
```php
public function apply(object $subject, string $transitionName, array $context = [], bool $dispatchAnnounceEvent=true, $flag2, $flag3, ...)
```
And when we use it, it's not really undestandable if you don't know the API:

```php
$this->workflow->apply($subject, 'confirm', [], true);
```

I propose 4 things here:

1. Use a bitfield argument (more flexible on the long term)
2. Use an array argument  (more flexible on the long term)
3. Add a new method applyWithoutAnnonce 
4. Leverage the context 

My preference goes to option 4/

```php
$this->workflow->apply($subject, 'confirm', ['disable_annonce_event' => true]);
```

**Comment by noniagriconomie** [comment]
Hi @Harry-Dunne

> Code in guard event, usually business rules, can be costly to execute

I agree with this, but what about keeping the component generic, and use specific project code to "avoid" this?
Can you like "memory cache" the result of a first call to your business rules guard logics, so that the n times the workflow needs it, the result is already here?

The `apply()` IMO must/should remains "simple"/"basic"

@lyrixx +1 for context, maybe with a symfony prefix so that is does not overlap with dev business context keys :)

**Comment by Harry-Dunne** [comment]
Hi @noniagriconomie 

> Can you like "memory cache" the result of a first call to your business rules guard logics, so that the n times the workflow needs it, the result is already here?

I don't think it's possible in this case... Guard events dispatched by announce event correspond to transitions not yet applied, preemptively. Conditions in code listening these events may be different from those of the currently applied transition.

@lyrixx +1 for the context
