### ISSUE TITLE
[Secrets] Secret is not working as environment variable

### ISSUE THREAD

**Issue by Myrkky** [symfony/symfony#35348]
**Symfony version(s) affected**: tested with 5.0.2 and 4.4.2

**Description**  
Tried to use secrets to store JWT_PASSPHRASE, but symfony wont pass it to environment variable.

**How to reproduce**  
1. symfony new test-jwt-secret
2. bin/console secrets:generate-keys
3. composer require jwt
4. -- remove JWT_PASSPHRASE from .env
5. bin/console secrets:set JWT_PASSPHRASE
6. bin/console -> Environment variable not found: "JWT_PASSPHRASE".

**Additional context**  
<img width="888" alt="Screenshot 2020-01-15 at 9 54 27" src="https://user-images.githubusercontent.com/8601755/72424515-d19f8e80-378e-11ea-9426-e09441922b64.png">

**Comment by jderusse** [comment]
note: The reason is a ParameterCircularReferenceException in envLoader when the first Env Variable tried to be loaded is `default::SYMFONY_DECRYPTION_SECRET`

- call to getenv('default::SYMFONY_DECRYPTION_SECRET')
- call to getenv('SYMFONY_DECRYPTION_SECRET')
- the env variable does not exists
- iterate over loaders
- tryied to load SodiumVault envLoader
- triggers a ParameterCircularReferenceException (because the loaded requires SYMFONY_DECRYPTION_SECRET)
- the iterrator `loaders` stay in an invalid state
- EnvVarProcessor fallback to default null => OK

- next variable to be loaded (ie. JWT_PASSPHRASE)
- the env variable does not exists
- iterate over loaders
- the iterrator `loaders` is in an invalid state <= issue
