### ISSUE TITLE
[Console] Define constants for main exit codes.

### ISSUE THREAD

**Issue by Chi-teck** [symfony/symfony#35431]
**Description**  
Console commands must return exit code. I propose we define constants for most used exit statuses like it is done in C programming language.
https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html
That would make code a bit more clear.

**Example**  
Before:
`return 0;`
After:
`return self::EXIT_SUCCESS;`

**Comment by ro0NL** [comment]
you can define such consts in your application for your commands, i dont think it's much of value for core commands, nor implying everyone should use this. Personally im fine with ints :)

IMHO it's the same topic as http status codes => https://github.com/symfony/symfony/pull/22023

**Comment by javiereguiluz** [comment]
@ro0NL this is indeed a similar situation to the constants for the HTTP Status Codes. We rejected to use those in Symfony's own code ... but we defined those constants in case developers want to use them in their apps (I do for example 😊).

My opinion: **I'd love to have these constants for command exit codes**. Not for all the codes defined here: https://github.com/symfony/symfony/blob/e0c1f4da32883844cc80d29ccbebd4eb035c734d/src/Symfony/Component/Process/Process.php#L88 but for the most common.

Why? Because I always have problems remembering if "success exit" is `0` or `1` ... and when I remember that "success == 0" ... it's confusing because this is PHP, so 0 = false = error and 1 = true = success 😕  Now that Symfony forces you to define the exit code, these constants would make things more DX-friendly.

**Comment by Chi-teck** [comment]
@javiereguiluz do you know any real use cases where a command returns status greater than `1`?
I think having just two constants like _glibc_ would probably be sufficient.

**Comment by ro0NL** [comment]
i was a bit skeptical about consts for just int(0) or int(1), having more defined exit codes is more valueable :+1: 

personally i dont think of `return 0/1;` as a potential implicit boolean value.

im also curious if it belongs to Process or Console component :D

**Comment by javiereguiluz** [comment]
@Chi-teck although it's hard to find a standard list of exit codes ... most Linux-flavored OS use these codes: https://github.molgen.mpg.de/git-mirror/glibc/blob/master/misc/sysexits.h

Some of them are useful to us: `EX_DATAERR (65)` when the user input is wrong for any reason, `EX_IOERR  (74)` when some I/O operation failed on some file, `EX_NOPERM (77)` when the user does not have permission to run the command, etc.

**Comment by alister** [comment]
I've returned specific exit codes from a (php) script before so specific actions can happen in the calling (shell) script, @Chi-teck. 

A [blogpost](https://phpscaling.com/2009/06/23/doing-the-work-elsewhere-sidebar-running-the-worker/), one of a series I wrote about using queues, described how you could potentially slow things down, or exit the whole thing, using the return values.

**Comment by TomasVotruba** [comment]
Great move! I'd got with success/failure only for a start.

I use similar approach for ~ 2 years:

https://github.com/symplify/symplify/blob/4a935cec78c26929ea90cb15e0af4031f2dea236/packages/package-builder/src/Console/ShellCode.php#L7-L17

Inspired by @cakephp

https://github.com/cakephp/cakephp/blob/94435ab211196ce92014a83ec7bab4e385bf8ba3/src/Console/Shell.php#L50-L62

**Comment by Chi-teck** [comment]
I would start with only two constants for the following reasons.
1. The vast majority of console applications probably use only two status codes (0/1).
2. Exit codes are not standardized across different platforms.
3. If we have a good reason it's never too late to introduce constants for other exit codes.

**Comment by fabpot** [comment]
I agree that we should only have constants for 0 and 1.
