### ISSUE TITLE
Licensing under a "do not harm" type of license

### ISSUE THREAD

**Issue by EmilCataranciuc** [symfony/symfony#35490]
Many open source software libraries or even software packages end up being used in systems or by organizations which don't have the interest of human well being at heart.

It might be a good idea to license nest under a "do not harm" type of license. So far I am aware of this license: https://firstdonoharm.dev But it doesn't include many specifics regarding distribution and so on (compared to GPL or MIT). Maybe a dual license would fit.

**Comment by javiereguiluz** [comment]
I'm afraid that relicensing (or multi-licensing) Symfony would be a too difficult thing to do right now (you need the express agreement of each and every person who has ever contributed code to Symfony!)

Besides, this would create legal uncertainty among developers and companies.

Lastly, the kind of licenses you are proposing are often confusing. For example, some people think that airlines are one of the best things in the world because they connect people, create business opportunities, etc. But some people think they are evil companies which are polluting and destroying the world. So, who decides if these companies are good or bad?

**Comment by EmilCataranciuc** [comment]
Well, we can create a more specific license. Compatible with the current one. Dual licensing should be possible as long as licenses are compatible. I think.

**Comment by fabpot** [comment]
The biggest issue is that this new license won't be labelled as Open-Source. That's a no-go IMHO.

**Comment by EmilCataranciuc** [comment]
Well, I have no legal background so I won't insist. But I think we (together with a lawyer) could cook-up something compatible. The main idea is to prevent organizations to use the software for political persecution (tracking etc.) and other related actions.

**Comment by Nyholm** [comment]
I really like this idea. I don’t want anybody do bad things with code I’ve been contributing to. 

However, I’m closing this issue for multiple reasons:
- the difficulty changing a license
- it won’t be an open source license 
- it is hard to actually verify that some bad people (or criminals) are this software in a way that is not according to the license. 

Thank you for the suggestion.
