### ISSUE TITLE
[Intl][Validator] Language::exists fail for es_419

### ISSUE THREAD

**Issue by jkobus** [symfony/symfony#35513]
**Symfony version(s) affected**: 4.4

**Description**  
`Languages::exists('es_419')` is not working in intl 4.4 where the same code worked with 4.3.

**How to reproduce**  
- Checkout intl repo, latest version
- Add assertion in `\Symfony\Component\Intl\Tests\LanguagesTest::testExists`:
`$this->assertTrue(Languages::exists('es_419'));`
- run the test: `phpunit --group intl-data --filter testExists`
- tests will fail

Repeat the same steps with 4.3 and the test will be green.

**Possible Solution**  
I tried to dig in the code but with no luck so far.

**Additional context**  
The language validator in symfony 4.4 will also fail due to this bug.

**Comment by ro0NL** [comment]
that's an intended bug fix, see #33148

**Comment by jkobus** [comment]
Thanks, closing then :)

**Comment by jkobus** [comment]
@ro0NL, would you be so kind and tell me, what alternatives we have now for the language validator? 

We used it to validate user input; we have content in various languages and dialects, also es_419. I followed the related tickets, but there is no straightforward information. I assume, there is now no validator that can accept `es_419` as input?

**Comment by ro0NL** [comment]
Locales::exists should still work

**Comment by jkobus** [comment]
Tested, and:

`var_dump(\Symfony\Component\Intl\Locales::exists('es_419'));`

returns `false` with intl 4.4.3.

**Comment by ro0NL** [comment]
hm, that's a bug maybe.

first, `es_419` is a valid locale: https://github.com/symfony/symfony/blob/7ecb5aad8e81a6146c86f0f449fcf754dcec0c14/src/Symfony/Component/Intl/Resources/data/locales/meta.json#L209

yet, there's no translation for `es_419` in e.g. the `en.json` file (assuming this is the default locale being used): https://github.com/symfony/symfony/blob/7ecb5aad8e81a6146c86f0f449fcf754dcec0c14/src/Symfony/Component/Intl/Resources/data/locales/en.json#L200-L225

Given the current implementation:

https://github.com/symfony/symfony/blob/7ecb5aad8e81a6146c86f0f449fcf754dcec0c14/src/Symfony/Component/Intl/Locales.php#L40-L49

it returns `false` because it's unavailable under `Names` in `en.json`. I tend to believe the better implementation is like:

```
return \in_array($locale, self::getLocales(), true) ||
  \in_array($locale, self::getAliases(), true);
```

with a side node exist() may return true, whereas getName for the same locale would throw. But that's expected IMHO.

Can you submit a PR?

**Comment by ro0NL** [comment]
We should also investigate if we dont skip this locale during generation, due 

https://github.com/symfony/symfony/blob/7ecb5aad8e81a6146c86f0f449fcf754dcec0c14/src/Symfony/Component/Intl/Data/Generator/LocaleDataGenerator.php#L166-L169

im not sure why ive added this check, we should try to translate anything returned from `Locale::getRegion`, which should always be a valid country code already.
