### ISSUE TITLE
[Messenger] Poor performance according php-service-bus/performance-comparison

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#35547]
According benchmark at https://github.com/php-service-bus/performance-comparison between pure php, symfony/messenger, golang and php-service-bus/service-bus; symfony/messenger is far worst.	I don't really have suggestions how to improve it, but I think this issue should be here as placeholder for anybody willing to take a look. Please excuse me if such topic already exists somewhere here.

Pure php (Time spent: ~ 4m20s)
symfony/messenger (Time spent: ~ 7m25s)
php-service-bus/service-bus (Time spent: ~ 1m)	
Golang (Time spent: ~ 0m 22s)

**Comment by Tobion** [comment]
Symfony messenger uses amqp `get()` which is known to much slower than amqp `consume()`. That is the main difference to the pure php implementation. php-service-bus seems to use installed php extensions. Otherwise I wouldn't know how it can be faster than pure php.

Also there seem to be sub-optimal implementation like preparing sql statement for each message inside `__invoke`: https://github.com/php-service-bus/performance-comparison/blob/da16ff4584d97cff4cf2f8c9ea2855bfa65356b7/symfony-messenger/src/StoreCustomerHandler.php#L41-L47
There is no point in using a prepared statement like this. The preparation need to be done outside the loop.

**Comment by Tobion** [comment]
Also php-service-bus uses non persistent messages (https://github.com/php-service-bus/performance-comparison/blob/da16ff4584d97cff4cf2f8c9ea2855bfa65356b7/php-service-bus/src/TestService.php#L36) while Symfony uses persistent by default now (#34956)

**Comment by Tobion** [comment]
In general the comparison setup looks quite good. I wonder what transport mechanism for rabbitmq php-service-bus uses under the hood?

**Comment by JustBlackBird** [comment]
php-service-bus uses [phpinacle/ride](https://github.com/phpinnacle/ridge) as transport. It's faster because all the framework built around [AMP](https://amphp.org/) which does IO (like interacting with message brokers) in true async way.

**Comment by yethee** [comment]
Related issue #29713

**Comment by mmasiukevich** [comment]
I updated the results, as well as added persistent messages (I did not know that in the Messenger it were made this by default)

By the way, Messenger slightly accelerated message processing

**Comment by nicolas-grekas** [comment]
I'm not sure how actionable this issue is. We're comparing :apple: and :pear: here...
I'm closing therefor. Please send patches if you find ways to improve perf of course.

**Comment by ostrolucky** [comment]
Well obvious action here would be to make messenger non blocking.

**Comment by nicolas-grekas** [comment]
It may be obvious, but not trivial, nor possible without BC breaks :)
But please send PRs if you're up to give it a try!
