### ISSUE TITLE
Validator incompatibility with ProxyManager

### ISSUE THREAD

**Issue by alekitto** [symfony/symfony#35544]
**Symfony version(s) affected**: 5.0.4

**Description**  
When trying to validate a value holder proxy generated with ocramius/proxy-manager, all the public properties will be unset at construction.
This results in `ReflectionProperty::isInitialized()` returning false as clearly documented [here](https://www.php.net/manual/en/reflectionproperty.isinitialized.php).
PR #35532 introduced check on `isInitialized` returning null instead of firing an `__get` call.

**Possible Solution**  
Check if `__get` method exists before blindly returning null, as per rfc "reads from uninitialized properties will generate a TypeError unless __get() is defined".

**Comment by nicolas-grekas** [comment]
Would you mind sending a PR please?

**Comment by greedyivan** [comment]
I want to clarify how this bug differs from #35454

Originally, there was an object
```php
class Foo
{
     /**
     * @Assert\NotBlank()
     */
    public int $bar;
}
```

If a property is accessed in this initial uninitialized state, PHP throws an error:
```
Typed property Foo::$bar must not be accessed before initialization
```

Thus, when the validator tried to check the value and called `ReflectionProperty::getValue()` an error was triggered. #35532 fixed it.

But that fix broke one special case. If there is an object
```php
class Foo
{
     /**
     * @Assert\NotBlank()
     */
    public int $bar;
    
    public function __construct()
    {
        unset($this->bar);
    }
    
    public function __get($name)
    {
        return 42;
    }
}
```

And a property is accessed in that _`unsetted`_ but with `__get` method state, no error is triggered. Magic method will be called and `42` will be returned.

This issue is about that.

But there is one special case related with PHP 7.4.0 and 7.4.1+.
```php
class Foo
{
     /**
     * @Assert\NotBlank()
     */
    public int $bar;
        
    public function __get($name)
    {
        return 42;
    }
}
```
This code will trigger error in 7.4.1+, but not in 7.4.0 (`42` will be returned).

Therefore, a full implementation should only consider the latest version of PHP. There is no reason to implement a behavior that was found to be erroneous and fixed in future versions.

**Recap**
An unfixed validator implementation will fail with the second - _`unsetted`_ with `__get` method - properties, considering them null.
