### ISSUE TITLE
Unable to customize error page on json format

### ISSUE THREAD

**Issue by fernandofdzcode** [symfony/symfony#35665]
**Symfony version(s) affected**: 4.4.*

**Description**  
Symfony is unable to return custom error page on json format.

**How to reproduce**  

1. Following the tutorial: https://symfony.com/doc/4.4/controller/error_pages.html
2. Placing a "error404.json.twig" under "templates/bundles/TwigBundle/Exception/".
3. GET request on: "localhost/index.php/_error/404.json"

It outputs:
`{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","status":404,"detail":"Not Found"}`

**Additional context**  
If i place a "error404.html.json", symfony overrides the actual html with the one that i placed.

**Comment by javiereguiluz** [comment]
This changed with the introduction of the ErrorHandler component ... but the docs have been updated properly. For example, in the page you referenced (https://symfony.com/doc/4.4/controller/error_pages.html) we no longer mention that you can create a `error404.json.twig` because that's not possible anymore.

To customize non-HTML error pages, you must follow these new instructions: https://symfony.com/doc/4.4/controller/error_pages.html#overriding-error-output-for-non-html-formats
