### ISSUE TITLE
Undocumented change: Symfony 4.3 and earlier always returns a content type of text/html by default, but Symfony 4.4 and later can return a content type of text/xml if the requester says they'd prefer it

### ISSUE THREAD

**Issue by paulcdejean** [symfony/symfony#35694]
After doing: `composer create-project symfony/website-skeleton project 4.3.99`

A curl request like this: `curl -v -H "Accept: application/xml,application/xhtml+xml,text/html" http://localhost 2>&1 >/dev/null | grep 'Content'`

Returns a content type of text/html.

However in a newer version of Symfony: `composer create-project symfony/website-skeleton project 4.4.99`

A curl request like this: `curl -v -H "Accept: application/xml,application/xhtml+xml,text/html" http://localhost 2>&1 >/dev/null | grep 'Content'`

Returns a content type of text/xml!

This was causing big problems for us as our responses are not valid XML, but due to the content/type some things were expecting them to be.

Where is this change documented and how can we revert to the old behavior of always returning text/html? I can't find any mention of this in the changelog.

**Comment by paulcdejean** [comment]
da_wunder in irc mentioned that this PR could be related: https://github.com/symfony/symfony/pull/34921

**Comment by ostrolucky** [comment]
I tried this in symfony-demo with 4.4.4 deps and can confirm it's reproducable there.

**Comment by adamk33n3r** [comment]
I'd like to add that this update has also affected our application. We are using AngularJS and the accept header for all requests is `application/json, text/plain, */*`. When making a request to an endpoint that returns a plain string of text the response is setting the content-type header to be `application/json` since it is the first one in the list. I don't think this should be the logic. The response is not JSON. Therefore the AngularJS http client breaks because it tries to parse it as if it were JSON. Previously it would have been `text/html` and work fine.

**Comment by alexander-schranz** [comment]
@nicolas-grekas if I interpret the changelog of 4.4.7 and 5.0.7 correctly this can be closed now?

**Comment by nicolas-grekas** [comment]
Correct!

**Comment by alexander-schranz** [comment]
Thx for fixing this 👍
