### ISSUE TITLE
Get a wrong dom tree when dom-crawler meet \0  character

### ISSUE THREAD

**Issue by RiedSpencer** [symfony/symfony#35798]
link:  http://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=%CF%C2%D4%D8&un=&rn=10&pn=0&sd=&ed=&sm=1&only_thread=1

eg: `return $crawler->filterXPath('//div[@class="s_post"]')->html()`

hope: get the dom tree

reality：get the empty node

**Comment by stof** [comment]
That's because of PHP's DOM parsing itself, so we cannot fix it.

Note that the dom-crawler component will use the [`masterminds/html5`](https://packagist.org/packages/masterminds/html5) parser automatically when the library is installed and the page has the HTML5 doctype (which is the case on your link). I think that this library handles NUL bytes properly.
