### ISSUE TITLE
Idea: Automatically register all repositories as Twig extensions (custom functions)

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#35965]
When I need lots of data in my template, my controllers used to look like this:

```php
return $this->render('foo.html.twig', [
    'activeUsers'   => $userRepository->countActiveUsers(),
    'inactiveUsers' => $userRepository->countInactiveUsers(),
    'premiumUsers'  => $userRepository->countPremiumUsers(),
    // still more...
]);
```
Many lines of dumb boilerplate code, just fetching something from the repository, and passing it to the template.

I started to simplify things by passing the repository to the template:
```php
return $this->render('foo.html.twig', [
    'userRepository' => $userRepository
]);
```
...and in the template:
```twig
{{ userRepository.countActiveUsers() }}
{{ userRepository.countInactiveUsers() }}
{{ userRepository.countPremiumUsers() }}
```
What about doing this in Twig's `AppExtension`? Injecting the repositories into all templates globally?

And taking this approach one step further, the idea is: Why not inject them *automatically*? Similar to registering everything as a service (Symfony 3.3), auto-injecting all repositories into all templates?

Would this destroy performance?

**Comment by xabbuh** [comment]
Exposing all Doctrine repositories to Twig templates automatically will give template designer too powerful tools IMO. The reason is that them using your repositories can easily increase the number of database queries being executed without being able to control this in the application itself. While carefully choosing which variables you want to expose to the template you have full control about the number and type of database queries being executed.

That being said I am 👎 on adding a feature that makes it too easy to shoot yourself in the foot.

**Comment by noniagriconomie** [comment]
> Would this destroy performance?

maybe more "dangerous", "less control" for a core feature IMO, better in an a devland codebase as you do with retrisction on specific repo method, etc

----

also, maybe if you send to much twig vars, you can refactor from controller side instead of injecting the repo in front

```php
return $this->render('foo.html.twig', [
    'user_stat' => $statManager()->computeUserStat() // for exemple
]);
```

```twig
{{ user_stat being a simple DTO computed in the statManager }}
{{ user_stat.countActive }}
{{ user_stat.countInactive }}
{{ user_stat.countPremium }}
{{ user_stat.countXYZ }}
```

**Comment by fabpot** [comment]
I don't think that this is something that should be part of core. You can always do that in your own app if it helps.
