### ISSUE TITLE
[PropertyInfo][DoctrineBridge] wrong type for doctrine json column

### ISSUE THREAD

**Issue by norkunas** [symfony/symfony#35968]
**Symfony version(s) affected**: >=4.4

**Description**  

#35851 introduced a BC break with json columns. Previously when using `@var mixed` and `@ORM\Column(type="json")` property info returned `null` for type so serializer accepted any value for this, but currently it always returns `Type` as builtin array and it doesn't accept anymore mixed values.

**How to reproduce**  

will write if needed

**Possible Solution**  

Return `null` for json type column, while leaving `json_array` column intact.

**Additional context**

**Comment by fancyweb** [comment]
Status: reviewed.

This is normal since now the `json` type is supported. `json` is the new name of `json_array`.

However I agree with you that this type can be used with mixed data, ie it doesn't have to be array. I reported it in another PR (see https://github.com/symfony/symfony/pull/35794#discussion_r381581757). But it has always been like this (on the `json_array` type), this is why I applied the same treatment for `json`. Both have to be consistent I guess. IMO, we should return null for both since we can't guess but that would break compatibility too.

**Comment by norkunas** [comment]
> json is the new name of json_array
I disagree. In json_array doctrine was converting null or empty value to array, but json type doesn't do that. In my opinion property info is to strict to always set this as array while doctrine can store any value for json
