### ISSUE TITLE
[dom-crawler] promote private methods to protected

### ISSUE THREAD

**Issue by IAndreaGiuseppe** [symfony/symfony#35979]
**Description**  
Hi,
I'm building an expanded version of an htm5crawler class based on symfony dom-crawler but some of the private methods on the crawler class are blocking our new features.

Is there any valid reason of using private scope on those methods?

The most important is:
```
private function createSubCrawler($nodes): object
// and
private function parseHtml5(string $htmlContent, string $charset = 'UTF-8'): \DOMDocument
```

The private scope prevents our child class to mantain the same logic as yours during the parsing of a document. Any chances to see a review to permit a better class extension?

Thanks

**Comment by Tobion** [comment]
Unlikely as we avoid protected methods to allow changes in the class without breaking BC.

**Comment by stof** [comment]
The reason we use private visibility is that anything has to be covered by our backward compatibility promise. And inheritance-based extension points are the worst ones when trying to write a BC layer (especially if everything is opened to inheritance rather than only a few well-defined extension points).

The Crawler class is not meant to be extended. Why do you need a child class ?

**Comment by IAndreaGiuseppe** [comment]
> 
> The Crawler class is not meant to be extended. Why do you need a child class ?

I see the point about not breaking compatibility.

I'm working on a project that use extensively, crawlers (not only html crawler) than I decide to conform all the classes to a custom predefined interface.

Many method maps well to those defined on my interface but others dont.

1. Suppose I have something like:

```
use Symfony\Component\DomCrawler\Crawler;

class Html5Crawler extends Crawler implements CrawlerInterface
{
    public function select()
    public function find()
    public function findAll()
    // ...
```

2. what if I need DOM traversing functionality over the entire three? a `reduceRecursive()` for example like `reduce()` but spread over the entire children. Or `each()` -> `eachRecursive()`..

```
public function reduceRecursive(Closure $closure)
{
    $nodes = [];
    // ... iterate over children

    return $this->createSubCrawler($nodes); // I can't..
}
```

**Comment by stof** [comment]
Well, you could make your own class a wrapper around the Symfony Crawler rather than a child class.

Btw, see https://symfony.com/doc/current/contributing/code/bc.html#using-our-classes. If you add new methods in a child class, you go out of our BC promise (and it means that your code can become broken by any update of Symfony, including patch releases)

**Comment by nicolas-grekas** [comment]
Closing as explained by @stof and @tobion. This would require extra maintenance efforts, while there are alternatives.
