### ISSUE TITLE
[Form] Allow strict typehint in object mapped to form ?

### ISSUE THREAD

**Issue by cedricdo** [symfony/symfony#36022]
Hi,

Currently, the form component cannot handle strict type hinting in object mapped to form because in certains conditions it will try to call the setter with null or will use the getter in the case of a new entity, typicaly in a POST scenario.

In my opinion, the current behavior of the Form component doesn't fit the path PHP is following with more and more strictness (type hint for function/method parameters, return type hint, property type hint, rfc for generics, ...). The examples provided in [the form documentation](https://symfony.com/doc/current/forms.html#usage) let the users thinks it's a good - or maybe worse, a best - practice to not use typehint.

A common way of avoiding this pitfall [is to use DTO](https://stackoverflow.com/a/43962930). However, i've the feeling we are just moving the problem into the DTO itself wich cannot have strict typehint. Also, some people are reluctants to write more code for a "limited benefits". I think DTO can have several good usage, but they should not be used **only** to overcome the current form component limitation with strict typehint.

I saw recently a project which use the Form type without DTO and with strict type hinting in entity:
* https://github.com/strictify/coding-challenge
* https://github.com/strictify/form-mapper-bundle

It leverages the type error exception throwed by PHP when calling the setter/getter and also allows to correctly initialize an entity with [all mandatories properties in the constructor](https://github.com/strictify/coding-challenge/blob/symfony-4/src/Entity/Product.php#L74).

Is there any plan to improve the form component to allow a strict typehinting of mapped object?

**Comment by xabbuh** [comment]
Me and @chr-hertel have a project that we first presented at SymfonyCon Lisbon over a year ago which tackles most of the issues you describe here: https://github.com/sensiolabs-de/rich-model-forms-bundle

While maybe some of its features could be moved into the Form component I don't expect every bit of it to be implemented in the core. Working with user input implies that there will be invalid state which contradicts with strict typing and self-validating classes. Handling all the edge cases coming from that is probably not something we want to maintain here.

**Comment by zmitic** [comment]
@cedricdo I am the creator of mapper bundle but correct URL is https://github.com/hitechcoding/strict-form-mapper-bundle 

The one you posted is not working nor is documented; it will have same API but work in different way. Basically, instead of relying on TypeError exception, I will use Reflection. 

Thanks for posting it, I would also prefer to have something like this in core as I don't have enough skills to make everything I want.

**Comment by xabbuh** [comment]
@zmitic Do you think it would make sense to merge your bundle and RichModelFormsBundle? I just had a quick look at your bundle and I believe it could be a good idea not to have to duplicate features in both. Feel free to open an issue or a PR if you agree or contact me on Slack.

**Comment by zmitic** [comment]
@xabbuh 
>Do you think it would make sense to merge your bundle and RichModelFormsBundle

Absolutely **yes**, my skills goes as far as this and could really use a help! Unfortunately I am 100% occupied for next 2 months (the only reason I don't work on rewrite) but if you are interested after that, I am open.

Question: can you download [test repository](https://github.com/strictify/coding-challenge) and tell me if you like the idea? I am forcing users to write accessor closures; some people don't like it but I do because of static analysis (one can say I am obsessed with it).

**Comment by xabbuh** [comment]
With Symfony 5.2 you will be able to configure your own callbacks that can perform a more elaborated data mapping for selected fields (see https://symfony.com/blog/new-in-symfony-5-2-form-mapping-callbacks). That's a huge improvement related to this issue. So I am going to close here. If you still feel that there is room for improvement, please feel free to open a new issue with concrete suggestions of what you would like to see being implemented.
