### ISSUE TITLE
Problem with send multipart form data in method PUT

### ISSUE THREAD

**Issue by kamil-nawrotkiewicz** [symfony/symfony#36146]
**Symfony version(s) affected**: 4.4.5

**Description**  
Hi, I'm using symfony 4 versions and I have a problem with requests in the PUT multipart form data method. Unfortunately, the Request object is empty. $reques->request->all(). 

**Possible Solution**  
At the moment I have changed the method from PUT to POST that works.

**Comment by Nyholm** [comment]
Hey. 
Could you show some example code?

**Comment by derrabus** [comment]
This is not a bug.

`$request->request` leverages a php feature, the superglobal `$_POST` variable to be precise. If php receives form data via POST, the request body is parsed and the `$_POST` variable is populated automatically. However, this is not the case for PUT requests.

Now, Symfony could emulate that functionality, but I don't think that this is a good idea because it'll introduce a performance penalty to a very central framework component.

**Comment by xabbuh** [comment]
Let's close then as explained.

**Comment by malantb** [comment]
Duplicate of #9226.
