### ISSUE TITLE
[RFC] static analysis tools

### ISSUE THREAD

**Issue by vladyslavstartsev** [symfony/symfony#36164]
Add phpstan and psalm to the project.
This will add internal code and public api strictness.
Since they (SA tools) support baselines (the file with all of old errors) it will be easy to start with them and fix issues along the way of future development.

**Comment by fabpot** [comment]
Look for similar issues, this has been discussed in the past.

**Comment by JeroenVanOort** [comment]
@vladyslavstartsev Did you find the relevant issues? I couldn't really. I'm wanted to open a similar RFC for another framework and I'm looking for reasons people do and don't include SA in their projects.

**Comment by wouterj** [comment]
See e.g. https://github.com/symfony/symfony/issues/25459

**Comment by JeroenVanOort** [comment]
Thanks so much for the reference!

If I understand correctly, this was all discussed when PHPStan didn't yet have the baseline feature. So, at that time all existing reported problems would need to be fixed before PHPStan could be used in CI. This is no longer necessary. It could be done more gradually and manageable now.

Also, the world hasn't stood still. Because supported for older PHP versions has been dropped, there's a lot less risk of changes breaking BC.

And regarding the argument 'the current code is fine': if that is the case, it wouldn't be a problem to assert that, right?
