### ISSUE TITLE
Dev bundles break project after `composer install --no-dev`

### ISSUE THREAD

**Issue by GinoPane** [symfony/symfony#36219]
**Symfony version(s) affected**: 5.0.5

**Description**  
When you install and register bundles they are registered in the bundles.php file. They are registered per environment, but the file is single for all environments. 

**How to reproduce**  
For example, we have:
![image](https://user-images.githubusercontent.com/3897579/77636219-a930cf00-6f4b-11ea-8382-1404eb666fb4.png)

These extensions are installed via composer as required for development. And the problem occurs when you try to make `composer install --no-dev`. Dependencies are being removed from the `vendor` directory but class references are still in the `bundles.php` and therefore the project does not work. 

**Possible Solution**  
Any removed bundles must be reflected in `bundles.php` automatically. Or `bundles.php` must be split per environment.

**Comment by stloyd** [comment]
If any this is symfony/flex issue not symfony per se.

**Comment by linaori** [comment]
Composer dev and Symfony dev are 2 separate concepts. If you need the code in your application, it should not be in require-dev, regardless of which mode Symfony is running in.

**Comment by Nek-** [comment]
@GinoPane since the bundles listed are only started in "dev" and "test" environment, running your application in "prod" environment with `composer install --no-dev` should not be an issue.

Maybe you're complaining because you tried `bin/console` in dev env (which will fail because it's calling non-existing classes). Try `APP_ENV=prod bin/console` or `bin/console --env=prod`.

**Comment by GinoPane** [comment]
@Nek- yep, true, with `prod` env it worked.
So it might be not an issue at all (but a design consideration) and can be closed.
