### ISSUE TITLE
[Fixtures] Order or actions when loading

### ISSUE THREAD

**Issue by Nayte91** [symfony/symfony#36276]
Hi there,

1 picture >> long explanations : php bin/console doctrine:fixtures:load

>![image](https://user-images.githubusercontent.com/36332481/77952579-30739f00-72cc-11ea-8a4f-a34130e593b7.png)
> We see that the db is purged, then the load method is called and (because I'm bad) it fails.

It's probably nothing, but I feel like having his db purged and no new datas injected (the time you fix your fixtures) can create some "checkmate" situations.

Is there some good reasons why the database purge is going before the fixtures loading is tested ?

If not, may I suggest that the load is tried, and if it succeed THEN ask for purging DB and replace data ?

Nothing really important here, just some developper experience improvement by reducing stress :)

Sorry by advance if this isn't up to you,

Nayte

**Comment by javiereguiluz** [comment]
You can use the `--purge-with-truncate` option so the command deletes the data but not the table structure (columns, indexes, etc.)

Depending on your case, you could even use the `--append` option to not delete anything and just add new data.

In any case, since these are fixtures for tests, "it doesn't matter" if the entire database is deleted. You can quickly rerun the command again when the problem is solved and that's it.

If you have any other question about using this command, please use the support channels described at https://symfony.com/support Thanks!
