### ISSUE TITLE
translation:update command not generating/updating ICU variant

### ISSUE THREAD

**Issue by timosmit** [symfony/symfony#36459]
**Symfony version(s) affected**: 5.0.3 - 5.0.7

**Description**  
As per my comment on #34713:

Even though I have the PHP intl extension installed, the command refuses to output the messages in the ICU format.

**How to reproduce**  
Using the tools listed below, start a project and add translation keys (e.g. in a form or directly in a template) and run the `translation:update` command.

**Additional context**  
Here's what I'm currently using:
* Windows 10
* PHP 7.4.2
* symfony/intl 5.0.7
* symfony/translation 5.0.7

**Comment by artemoliynyk** [comment]
Hi!
I have similar issue on Symfony 5.0.7.

Command `translation:update` generates file with `+intl-icu` on new locale, but won't update existing location.
Instead of updating existing `+intl-icu` file - command create new file, without `+intl-icu` suffix.

@timosmit can you please confirm same behaviour?

My versions:
- PHP 7.2 (mac)
- symfony/intl 5.0.7
- symfony/translation 5.0.7

**Comment by timosmit** [comment]
@artemoliynyk I can confirm this.

**Comment by artemoliynyk** [comment]
Proposed fix https://github.com/symfony/symfony/pull/36505
