### ISSUE TITLE
HttpClient: fetch only the first bytes of the response

### ISSUE THREAD

**Issue by va5ja** [symfony/symfony#36529]
I was wondering how I can read only the first few bytes of the response. The documentation states:

> To abort a request (e.g. because it didn't complete in due time, or you want to fetch only the first bytes of the response, etc.), you can either use the cancel() method of ResponseInterface or throw an exception from a progress callback.

That already sounds promising so what I'm doing is like in the example:
```
$response = $client->request('GET', 'https://...', [
    'on_progress' => function (int $dlNow, int $dlSize, array $info): void {
        if ($dlNow > 600) {
            throw new DownloadSizeException();
        }
    },
]);
```

> The exception will be wrapped in an instance of TransportExceptionInterface and will abort the request.

Ok great, I'm catching the exception but how do I still get to the content though, to those 600 bytes?

**Comment by nicolas-grekas** [comment]
You need to use the `stream()` method, as explained in the doc:
https://symfony.com/doc/current/components/http_client.html#streaming-responses

I'm closing because we use this repository only for the development of Symfony.
Please use [a support channel](symfony.com/support) if you need further help.
