### ISSUE TITLE
Missing debug logs from profiler panel if monolog handler level > debug

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#36534]
**Symfony version(s) affected**: 4.4/5.0

**Description**  
In development, if your `main` monolog handler has it's level set to `info`, debug logs are missing from the web profiler panel. If all handlers are removed entirely, debug logs show as expected. 

I'm not sure if this is a bug in Symfony or MonologBundle or both.

**How to reproduce**  
1. Create a new website-skeleton app
2. Create a route/controller, inject `LoggerInterface` into the controller and log a debug message
3. Visit the route and notice the debug message in the log panel of the profiler
4. In `config/packages/dev/monolog.yaml`, set `monolog.handlers.main.level` to `info`
5. Visit the route again and notice the debug message missing from the log panel

**Comment by fancyweb** [comment]
Status: works for me

The minimum level for the stream handler is info. The debug level being lower than the info level, the log entry is not supported by any handler and therefore is not collected and does not appear in the profiler.

If you remove all handlers, we implicitly push a NullHandler with min level debug (see FixEmptyLoggerPass in the MonologBundle). Since it can handle the message, the process of logging continue and hit the DebugProcessor that start the "collecting" of the record.

**Comment by kbond** [comment]
Thanks for the explanation @fancyweb. Makes sense but I feel like the NullHandler should always be added in dev to avoid my problem (maybe this creates other problems). Regardless, this isn't a symfony/symfony issue. Closing.
