### ISSUE TITLE
When decorated, a controller cannot use ContainerAwareTrait

### ISSUE THREAD

**Issue by matks** [symfony/symfony#36567]
**Symfony version(s) affected**: 3.4.39

**Description**  
If a controller A decorates a controller B and controller A uses ContainerAwareTrait (for example, if it extends `Symfony\Bundle\FrameworkBundle\Controller\Controller`) then container is not injected into controller A anymore. Being decorated prevents the system in charge to inject the container.

**How to reproduce**  
Fresh 3.4.39 Symfony installation, with a basic LuckyController that extends `Symfony\Bundle\FrameworkBundle\Controller\Controller`
```php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class LuckyController extends Controller
{
    public function number()
    {
    	$container = $this->container;
    	if (null !== $this->container) {
    		return new Response('Container is injected');
    	} else {
    		return new Response('Container is not injected');
    	}
    }
}
```

If I use it like this, it works perfectly. I receive "Container is injected" response.

Now I decorate it:
```
// services.yaml
    custom_controller:
        class: App\Controller\CustomController
        decorates: App\Controller\LuckyController
        arguments: ['@custom_controller.inner']
```

The decorating controller is just passing the request to decorated controller.
```php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class CustomController extends Controller
{
    private $decoratedController;

    public function __construct(LuckyController $decoratedController)
    {
        $this->decoratedController = $decoratedController;
    }

    public function number()
    {
    	$decoratedControllerResponse = $this->decoratedController->number();
    	return $decoratedControllerResponse;
    }
}
```
If I use it, I receive "Container is not injected" response because LuckyController `setContainer()` was not called.

**Possible Solution**  
Be able, when decorating a controller, to keep Dependency Injection behaviors such as the ones being applied by a CompilerPass to the `@XXX.inner` instance. Decoration should not modify a controller behavior.

I did not check with a service, but it might do the same.

**Comment by stof** [comment]
there is a special case in the ControllerResolver to inject the container in controllers implementing ContainerAwareInterface if they don't already have it. This means that this injection is often **not** handled by the DI component. And that's why the inner service does not get it if your decorator does not forward the call.
Things will work seamlessly if the injection of the container is managed by the DI component itself (which is the case when extending the AbsractController class in which a service location is injected due to implementing ServiceSubscriberInterface).

**Comment by stof** [comment]
Note that if you still extend the old Controller base class, you can solve this issue by injecting the container at the DI level already, by adding a call to the `setContainer` method passing `@service_container` as argument.

**Comment by matks** [comment]
> Note that if you still extend the old Controller base class, you can solve this issue by injecting the container at the DI level already, by adding a call to the `setContainer` method passing `@service_container` as argument.


Thanks, I did that. I use a CompilerPass and inject container in all my controllers. So ControllerResolve will not have to do it.

**Comment by jolelievre** [comment]
Hello @stof 
So if I understand correctly it's the `ControllerResolver` which injects the container via `setContainer` not the DI, but then when I look at https://github.com/symfony/framework-bundle/blob/264208f210c2b51f3859315c69271e09e696589f/Controller/ControllerResolver.php#L60

It seems to be able to manage both `AbstractController` class and `ContainerAwareInterface` So since `Controller` implements the interface it should work fine right?

Anyway you think if the base class of the controller was an `AbstractController` the resolver should inject it correctly even without a custom ComplierPass?

**Comment by stof** [comment]
@jolelievre the difference is that AbstractController gets its container injected at the DI level *first*.
The code dealing with AbstractController in the ControllerResolver is just a fallback when DI was not in use (which is also why it restores the previous container if it was already set.

And when decorating, the issue you have is that the ControllerResolver does not know about the inner object, only about the decorator. So if the decorator does not forward the container to the inner object, nothing will set it.
On the other hand, if the DI layer is configured to inject the container, that will be done *before* decorating the inner object.

**Comment by jolelievre** [comment]
Ok thanks for the precisions, so to sum it up:
- `Controller` -> container injected via `ControllerResolver`
- `AbstractController` -> container injected via DI and `ControllerResolver` as fallback

But since the decorated inner service is managed by the DI we should use `AbstractController` as our base class, this way we don't have to inject the container manually

The idea for us is to make it simple for module developer to decorate our core controller, so we want to keep the decoration definition as simple as possible

**Comment by stof** [comment]
@jolelievre you should definitely migrate to `AbstractController`. The `Controller` base class is deprecated in Symfony 4.2+ and gone in 5.0.

**Comment by xabbuh** [comment]
I am closing here as it doesn't seem to be that there is anything to be fixed.
