### ISSUE TITLE
[Mailer][PostmarkApiTransport] Enable the send of templated email

### ISSUE THREAD

**Issue by Orkin** [symfony/symfony#36693]
Hi,

in reference of this issue #35329 I have the same issue.

I completely understand your point to get an agnostic email system but maybe it's possible to go further and find a way to support both without the need to break the actual purpose.

If we would like to use the mailer component with a third party integration. The way to send email must stay agnostic but we could find a workaround. For me there is three way to do that :

- the first one is to add a new property on Email object to allow to define template like textBody or htmlBody with this it could be really easy to implement external template feature without breaking anything and without hard dependencies. It's stay agnostic but I'm not sure that the Email object had to manage that purpose
- the second one is to play with headers like @Metalrex100 say. We can use headers to set if we would like to use template maybe with header name like with-template and we use the properties textBody and/or htmlBody to provide template name/id/alias. With this the Email object don't need to be modified and headers stay abstract and are only used by the provider integration. This is not the most elegant solution but it can be a way to go further and find something that can match to the most case. I try this one here if you would like to see the idea https://github.com/passions-app/postmark-mailer it probably need some improvement but it's works
- the last one could be to create a new Email object like `ExternalTemplatedEmail` or `TemplatedEmail` to provide this kind of feature and avoid some tricky case. In fact when we create an `Email` object we already know if we have to provide an html body or text body, one of them or both, it's already a case when we know which kind of email we would like to send.

The main motivation behind the usage of external template is that templated email can be managed by other team that don't need to know how the application works (technically). The product team know which variables that are available for a specific template and can work on design on their side. The other point is in case of API development. We don't need the usage of twig or templating library and if we would like to send templated email without the usage of external templates we are forced to use twig to render those emails.

What do you think about that ? Do you think it can be possible to discuss about that to find the best way to do it. I think it can be a really good feature to support that. This is a common usage and it could be harm to have to do without this component for this reason.
I can understand the choice to not use the sdk of third party in integration package and to not support all of really specific features like campaign email, template management, admin features etc ... but template is really common

Thanks for ready and sorry for my bad english 😉

**Comment by Orkin** [comment]
Any news on that ? @fabpot @nicolas-grekas

**Comment by fabpot** [comment]
I'm not a big fan of supporting this in core. If we can find a "simple" abstraction that could support "many" existing providers, we might consider adding it in core. If not, implement it outside of core is probably possible anyway.

**Comment by emmanuel-nz** [comment]
Sorry to bring the subject up again, but I really think it could be a nice addition to support templated emails.

Templated email is quite a common feature for email providers: among the 19 third-party providers supported by the Symfony Mailer, only 7 of them don't (fully) support templated email.

I feel like it's kind of a shame to refrain to implement a common feature, just for a few providers.
It forces the people who want to use templated emails to use direct SDKs instead of the Symfony mailer, and lose its benefits.

There is already a `TemplatedEmail` class for twig templates.
I do understand that transports are just differents ways to send the same content, while `TemplatedEmail` is currently a different way to "build" the content.

But if templated emails were implemented in the Symfony Mailer, we could even keep the same "api" as the `TemplatedEmail` class.
At the end of the day, all we need is always a template id (or a path in the case of twig file) and an array of variables to interpolate.

```php
$email = (new TemplatedEmail())
    ->from('fabien@example.com')
    ->to(new Address('ryan@example.com'))
    ->subject('Thanks for signing up!')

    // here a template id instead of a twig template path
    ->htmlTemplate('template-id')

    // pass variables (name => value) to the template
    ->context([
        'expiration_date' => new \DateTime('+7 days'),
        'username' => 'foo',
    ])
```

With some yaml configuration, one could choose to either use the "native" (third-party provider) implementation, or the twig one.
For the built-in transports (smtp, simple send), and the providers that don't have "native" support, it would automatically fallback to the twig implementation.

Just like for tags/headers, in the documentation we could mention that some third-party providers don't support "native" templated email, and in this case it will fallback to twig templates. One should check out its provider's documentation to know if it is supported or not.

Here is the list of third-party providers with links to their documentation when supported:
AhaSend - **PARTIAL SUPPORT** (raw html must be provided) https://ahasend.com/docs/cli/templates#template-system
Amazon - SES https://docs.aws.amazon.com/ses/latest/dg/send-personalized-email-api.html
Azure - **NOT SUPPORTED**
Brevo - https://developers.brevo.com/docs/send-a-transactional-email#send-the-transactional-email
Infobip - https://www.infobip.com/docs/api/channels/email/email-message-sending/send-fully-featured-email
Mailgun - https://documentation.mailgun.com/docs/mailgun/user-manual/sending-messages/send-templates#sending-messages-with-templates
Mailjet - https://dev.mailjet.com/email/guides/template-api/#use-templates-with-send-api
Mailomat - **NOT SUPPORTED**
MailPace - **NOT SUPPORTED**
MailerSend - https://www.mailersend.com/help/how-to-use-personalization
Mailtrap - https://docs.mailtrap.io/developers/email-sending/transactional
Mandrill - https://mailchimp.com/developer/transactional/api/messages/send-using-message-template/
Microsoft Graph - **NOT SUPPORTED**
Postal - **NOT SUPPORTED**
Postmark - https://postmarkapp.com/developer/api/templates-api
Resend - https://resend.com/docs/api-reference/emails/send-email#param-template
Scaleway - **NOT SUPPORTED**
SendGrid - https://www.twilio.com/docs/sendgrid/ui/sending-email/how-to-send-an-email-with-dynamic-templates
Sweego - https://learn.sweego.io/docs/sweego/send-send-post

What do you think?

**Comment by Orkin** [comment]
You can read some more information context here #63196 and #63223

**Comment by emmanuel-nz** [comment]
Thanks for the input 👍 
While I do get the reluctance to implement templated email support only for one provider, what I'm proposing here is a "universal" solution.
A dedicated `TemplatedEmail` class which will leverage the third-party provider template implementation if supported, otherwise falls back to the twig implementation.

Just this feature, no advanced/specific provider feature.
If we stop here I don't think it will turn the symfony mailer into an advanced SDK.
