### ISSUE TITLE
[Messenger] Do not require doctrine/messenger

### ISSUE THREAD

**Issue by tyx** [symfony/symfony#36740]
**Symfony version(s) affected**: 5.1.0@beta

**Description**  

Since https://github.com/symfony/symfony/pull/35422 we split transport in dedicated package. Nice addition ! But we require doctrine/messenger by default ... and this one will install doctrine dbal. 

I have not dbal installed for now and here are the new package installed:
![Screenshot from 2020-05-07 14-31-22](https://user-images.githubusercontent.com/245494/81294699-8aa41480-906f-11ea-8d65-325b94bc642f.png)

I guess we made this change to keep BC. But it is very annoying. Before this change I had only doctrine messenger part, now I have all doctrine stuff.

**How to reproduce**  

Install symfony/messenger without doctrine pack.

I should admit I have no idea how fix this issue.

**Comment by shouze** [comment]
@tyx this is because prior to https://github.com/symfony/symfony/pull/35422 `symfony/messenger` was only requiring `doctrine/dbal` [as you can see](https://github.com/symfony/symfony/blame/9f93a38fffd2d57595b2732a3eadeb12d0af0892/src/Symfony/Component/Messenger/composer.json#L23).

Since that it requires `symfony/doctrine-messenger` that requires a lot more of doctrine dependencies. @Nyholm don't we have a better option regarding dependencies splitting? :thinking:

**Comment by tyx** [comment]
dbal was a dev requirement before !  As doctrine transport was embedded but not mandatory.

The problem really came when we splitted transport in different package and add doctrine one as requirement of messenger.

**Comment by Nyholm** [comment]
Thank you for this issue. That is something I did miss before. 

To make it work as it did in 5.0, I think we should move the `doctrine/persistence` and `doctrine/dbal` to the `require-dev` section. This will treat `symfony/doctrine-messenger` as a special package until 6.0. But that is fine.

**Comment by tyx** [comment]
Hi @Nyholm can I make the PR to help ? Or do you prefer make it on your own ?

**Comment by Nyholm** [comment]
No no no. Please make a PR :)
