### ISSUE TITLE
Symfony String Inflector - add rules for these words: congress, status

### ISSUE THREAD

**Issue by 6562680** [symfony/symfony#36849]
I removed old Inflector, tried laravel inflector, tried to copy Symfony/Component/String/EnglishInflector manually, and even CakePhp inflector, or my own inflector...

There's no inflector who returns
singular('Congress') -> "Congress" | Actual result is "Congres"
singular('Status') -> "Status" | Actual result is "Statu"

Of course i wrapped with "irregular words"...
Maybe there's not a bug, because word is already singularized when passed to inflector.

Then there's expected something like "isSingular()" or "isPlural()" when function is not idempotent...

**Comment by derrabus** [comment]
IIRC, the method does not claim to be idempotent. So regarding the "congress" example, I wouldn't classify this issue as bug because you're passing a singular form to a function that expects a plural.

Regarding "status" however, it's a different story because "status" is in fact a valid plural form of "status". So in that case, "status" would be the expected result.

**Comment by 6562680** [comment]
How do you provide if i pass from console arguments the "word", i dont know is it a plural or singular. I think i able to pass it to plural or singular function.

**Comment by xabbuh** [comment]
This doesn't look like a bug to me. `singularize()` expects a plural, `pluralize()` expects a singular (I am not even sure we can reliably determine if a word is singular or plural).

**Comment by derrabus** [comment]
> This doesn't look like a bug to me. `singularize()` expects a plural, `pluralize()` expects a singular

Exactly. That's how the methods are specified. The component uses heuristics to determine singular/plural forms __under the assumption that the input is correct__.

NLP is hard and I don't think this component aims to solve NLP problems. :wink:

**Comment by xabbuh** [comment]
It doesn't look like there is actually anything to fix. So I am going to close this issue as explained before. Thank you for understanding.

**Comment by 6562680** [comment]
We show the movie how the user problem converts into *we already have best quality, dont be stupid* as a result some lalala and issue gone, noone understand, noone try. Ok no problem

**Comment by derrabus** [comment]
I'm sorry that this issue was not resolved the way you expected it to be. What you've presented might be a valid use-case, it's just not one that this component tries to solve.

That being said, I'd like to ask you to use a respectful language when commenting or filing issues on this tracker.

**Comment by 6562680** [comment]
Ohh, if we use on our project "respectful language" we never push anything.

Class theory means "expect respectful language from different class, not from your employees". Thats the quality recept... sorry me for unexpected recommendations.

If you expect respect from guys who wants to improve you - you never improve. As the fact.

**Comment by wouterj** [comment]
Please note that human language is very difficult to grasp in programming logic. Developers usually are no language experts. I think it's quite amazing that there is programming logic that is able to singularize/pluralize words.
If you think it's possible to detect if a word is singular and plural, please change the code and create a pull request. That's the greatness of open source: combining the knowledge of the every developer that is happy to share their knowledge.

At last, I want to make you aware of the [Symfony Code of Conduct](https://symfony.com/coc). That's how the Symfony community has decided to communicate with eachother (as every developer lives in very different cultures, it's important to have one standard code of conduct for the community).

**Comment by xabbuh** [comment]
I never did that before, but it seems like sometimes you'll have to do everything for the first time. If using a respectful language stops you from being productive, I am sure you will be able to create your own open source project where this is the way to progress. But I am tired of spending (a massive amount of) my free time improving software that is given for free to everyone who wants to use it and then wasting my time reading things like that. That's why I am locking the conversation here as there's nothing to add.
