### ISSUE TITLE
[Mailer] Can attachment be added via StreamedResponse

### ISSUE THREAD

**Issue by ricohumme** [symfony/symfony#36971]
Hi,
Is it possible to added an attachment which is generated via a StreamedResponse object. Currently the attachment supports a resource or a string. Or maybe convert the StreamedResponse to a resource perhaps?

**Example**  
```php
$response = new StreamedResponse();
$response->headers->set('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
$response->headers->set('Content-Disposition', "attachment; filename='Some file.xlsx'");
$response->setCallback(function() {
...
});
$email = new Email();
$email->attach($response);
...
```

**Comment by stof** [comment]
StreamedResponse is specifically meant to be used with callbacks rendering things to `php://output` (generally through using `echo` rather than using this stream directly).
Trying to reuse this in the mailer looks weird to me. It will need to use an output buffer to capture the output  (and it might be harder to avoid keeping everything in memory, even though I think some advanced `ob_*` usage should allow achieving this by copying the buffer to a resource incrementally).

What is your use case there ? Why not writing to a PHP stream ?

**Comment by ricohumme** [comment]
Hi,

Thanks for your thoughts stof.
The use case here is when a report is generated to the browser, a StreamedResponse is an excellent way to do this. I have seen memory usage drop immensely when using this. 
However, when processing the request, the report could either be streamed to the browser, or be mailed to the user. A matter of preference.
When generating the report with the StreamedResponse, I could then either return the response from the controller, or pass it to the mailer so it can be attached and be on it's way.

I hope this clarifies the reason.

**Comment by ricohumme** [comment]
Thnx, I'll have a look into this.
