### ISSUE TITLE
Symfony string component uses interface of other component without requiring it

### ISSUE THREAD

**Issue by freshp** [symfony/symfony#37060]
**Symfony version(s) affected**: 5.1.0

**Description**  
I use the symfony/string component as standalone package. After the update to version 5.1.0 the following error occured.
> Error : Interface 'Symfony\Contracts\Translation\LocaleAwareInterface' not found

**How to reproduce**  
Create a new package without any requirements and require the string component. Create a new instance of the AsciiSlugger and the error occured.

**Possible Solution**  
Maybe the package should require the [translation-contracts](https://github.com/symfony/translation-contracts).

**Comment by xabbuh** [comment]
see #37051

**Comment by lyrixx** [comment]
Hello

I'm reopening it because there is a real issue hidden by the BC break.

#37051 was closed because we said something that mean:

> This may be a BC break but since the component is experimental, we can break the BC.

https://github.com/symfony/string/blob/c70102b5e84f20821de9f31b54e5b7482888aace/Slugger/AsciiSlugger.php#L16-L21
This class depends on the Translation contract, but it does not requires it. So as soon as one use it, it explodes

**Comment by xabbuh** [comment]
Well, but the component is usable without using the slugger, right? So that's an optional dependency that you need for some features or do I miss something?

**Comment by lyrixx** [comment]
You are totally right.

But we could at least throw an exception with the procedure to follow to make it work?

Because ATM, junior developer are lost with this error :/

**Comment by Korbeil** [comment]
I don't see the point here on a component being usable "without".
Actually if I want to use the Slugger, I have no choice but to have this interface that isn't provided by current dependencies.

So how can I have a slugger without this ? And why having a feature when you can't use it "as it is" since it's optionnal ? I don't even understand why this "optionnal" thing exists, if you have a dependency just require it :/

**Comment by nicolas-grekas** [comment]
Slugger is not the only not the main feature of the component. The policy in Symfony is to not force dependencies for features that are not mandatory.

**Comment by nicolas-grekas** [comment]
Not that improving discovery is always nice, PR welcome.

**Comment by freshp** [comment]
I think if this error occurs for example in standalone usage you can find the solution to require the translation-contracts. But after your explanation I have two more questions:

> Slugger is not the only not the main feature of the component. 
How can I find out the main feature of a symfony component?

> The policy in Symfony is to not force dependencies for features that are not mandatory.
Where can I find the symfony policies?

thanks in advance.

**Comment by nicolas-grekas** [comment]
> How can I find out the main feature of a symfony component?

Not sure there is a silver bullet answer. Looking at the README/doc would help get the answer. Also looking at the class hierarchy maybe. Lastly, looking at the optional deps :)

> Where can I find the symfony policies?

I'm not sure it's documented explicitly. The PR/issue history has many consistent examples over the years, so that at least the core-team knows it should enforce the policy.
