### ISSUE TITLE
[HttpFoundation] Deprecation error null not allowed InputBag::set()

### ISSUE THREAD

**Issue by krioo** [symfony/symfony#37100]
**Symfony version(s) affected**: 5.1.0

**Description**  
Calling `InputBag::set()`with the second argument set to `null` triggers deprecation error: 
```
Since symfony/http-foundation 5.1: Passing "null" as a 2nd Argument to "Symfony\Component\HttpFoundation\InputBag::set()" is deprecated, pass a string or an array instead.
```

This behaviour causes issues when replacing JSON request body with the JSON decoded value as JSON supports null values.

**How to reproduce**  
```php
/** @var Symfony\Component\HttpFoundation\Request $request */
$request->request->set('key', null);
```

**Possible Solution**  
Allow null values by adding `is_null()`, since the currently used `is_scalar(null)` returns `false`: https://www.php.net/manual/en/function.is-scalar.php

**Comment by nicolas-grekas** [comment]
This looks a lot like #36725
Swapping the request arguments after decoding a json looks like a hack to me.
I would recommend putting the decoded JSON into a request attribute instead.
(which is what I wrote on the linked issue also.

**Comment by chilimatic** [comment]
Is it a hack? I would rather see it as an IO-Result

Either the body is a form, in this cases you're reasoning is very valid. but modern infrastructure shifts toward json bodys or other content. which are not really "parameters" since they are content type json.

if the whole body is JSON and JSON has the allowed type of null it does make sense to allow null values.

Personally I would say that's a monomorphism/transforming or a strategy/adapter pattern -> the input which can be CT1 | CT2 -> IT (content-type1, content-type2 should become input-type (input interface)). 

So as a developer I would expect it to work in a defined way. Esp since bundles implemented it in a similar way.

Maybe I am missing the real implications in the Framework that make it "bad" to use null values. Because if there are no directly affected parts one might argue it's primarily a question of taste.

I don't mean any disrespect just thinking out loud here.

**Comment by ro0NL** [comment]
What's wrong with something like

```
$request->request = new ParameterBag(json_decode($request->getContent(), true));
```

IMHO `InputBag` is designed to be bound to $_POST/$_GET.

**Comment by chilimatic** [comment]
I see the reasoning behind $_POST/$_GET. 

I still can be hacky as long as I cast it to string? or any other scalar value which would be in this union type variance? and arrays? 

The rest of possible assumptions aside. what's the purpose and how do we benefit from it not being null?

**Comment by ro0NL** [comment]
i agree there are few unclarities :) see also https://github.com/symfony/symfony/pull/34363#discussion_r357991020

I think ultimately it'll rely on implicit string casting when accessed: https://3v4l.org/IIWBt

But then we should actually cast it today manually for consistent behavior (e.g. the same behavior with or without a real return type).

The array case should probably validated/documented to be `string[]` (any no. of levels actually, but i dont think there's a notation for that).

InputBag is meant to make accessing single/multi values explict (`?k=v` vs. `?k[]=v`), as the user is free to mangle those.  I tend to agree the same case may apply to JSON decoded payloads.

So yes, given `scalar` is already allowed (not strictly string) it probably makes sense to allow null as well, esp. since it's already anticipated in the return type.

**Comment by nicolas-grekas** [comment]
The request's body is not always populated via `$_POST`.
Can't we use InputBag only when $_POST is used?
That would fix the issue, isn't it?

Anyone up for a PR?

**Comment by krixon** [comment]
I don't think that addresses the original issue. It's a pretty common pattern in projects I've worked on to replace the request parameters with decoded JSON which might contain null values. I know a request attribute could be used here instead, but that means everything has to know to examine that attribute instead of using `Request::request` which is much more natural and obvious IMO.

**Comment by nicolas-grekas** [comment]
> I don't think that addresses the original issue.

Can you explain why? Isn't my proposal compatible with extracting request values from json bodies?

**Comment by krixon** [comment]
Generally, I will have an event listener which looks something like this:

```php
public function onKernelController(ControllerEvent $event) : void
{
    $request = $event->getRequest();

    if ($request->getContentType() !== 'json' || empty($request->getContent())) {
        return;
    }

    try {
        $payload = json_decode($request->getContent(), true, 512, JSON_THROW_ON_ERROR);
    } catch (JsonException $exception) {
        throw new BadRequestHttpException('Invalid JSON body.', $exception);
    }

    $request->request->replace(is_array($payload) ? $payload : []);
```

Assuming the request method causes `$_POST` to be populated, which is the case for all of the common unsafe HTTP methods an API is likely to encounter, this code breaks with `5.1` but works fine with `<= 5.0`. I'm not sure how the restricting the use of `InputBag` to `$_POST` data addresses this problem (apologies if I have misunderstood your proposal).

BTW, I have worked around this for now by simply replacing the entire `InputBag`:

```php
$request->request = new ParameterBag(is_array($payload) ? $payload : []);
```

As a side note, the change has also caused some issues elsewhere in my APIs - for example I will often accept a list of sort keys in the query string for lists resources, and for client convenience I will accept a single string or an array of strings. This seems to be pretty much incompatible with the new `InputBag` API - I am forced to pull out all of the parameters in this situation and extract the value from that:

```php
// Previously:  $request->query->get('sort');
$status = $request->query->all()['sort'] ?? null;
```

Not a huge deal, but it's a breaking change I wouldn't expect in a minor release.

**Comment by nicolas-grekas** [comment]
> Assuming the request method causes $_POST to be populated

PHP also checks the content-type before populating `$_POST`.
This means your case is safe with my approach.

> I am forced to pull out all of the parameters in this situation and extract the value from that:

yes, that's on purpose: most ppl don't use query parameters in the way you describe - the defaults are to make them safer. Now, it also means some use cases will need to adapt. You describe one :)

**Comment by krixon** [comment]
> PHP also checks the content-type before populating $_POST.

Ah of course, `$_POST` is only set for `application/x-www-form-urlencoded` and `multipart/form-data` content types. That makes sense then and I agree this would resolve the issue.

**Comment by ro0NL** [comment]
im still generally curious why `InputBag` wouldnt fit JSON payloads :/

e.g. if a user is posting `{"key": "val"}` instead of `{"key": ["val"]}`, then `InputBag::get/all('key')` is generally helpful for throwing 400 bad request no?

> Can't we use InputBag only when $_POST is used?

it's also used for $_GET/$_COOKIE. I agree though setting null values makes less sense, but we can argue about the mutability of InputBag in the first place.

**Comment by nicolas-grekas** [comment]
The request object is mutable. Immutability is provided by cloning, that's the design.
About linking $_POST and InputBag, I only meant this for the "request" property. Cookie/query should remain as is.

**Comment by nicolas-grekas** [comment]
See #37265

**Comment by gmponos** [comment]
So I tried your changes locally at a project of mine and it seems that PHPStan is **not** complaining.

Still I am against the `InputBag`. Not sure how much constructive I can be here and how I can elaborate that DX is thrown out of the window with the InputBag. Current changes make the behavior in my PoV even further inconsistent. One time the `request` behaves X and the other behaves Y, right?

For instance, you might have listeners that are running after authentication, that are agnostic of the content-type of the request and ppl will be driven to use always the `all` function.

I changed my `Authenticator` from : 

```php
        $login = $request->request->get('login');
        return \is_array($login) && isset($login['username']) && isset($login['password']) && isset($login['_token']);
```

to:

```php
        $request = $request->request->all();
        if (!isset($request['login'])) {
            return false;
        }

        $login = $request['login'];
        return \is_array($login) && isset($login['username']) && isset($login['password']) && isset($login['_token']);
```

Trivial changes you might say.. but I don't find the benefit.. I still need to check the `login` if it is actually an `array`... The notion is that ppl were getting 500.. those ppl should just fix their code. I was aware and happy with what `request` of `sf` was offering.. A pile of mix data with No Behavior.. and I was fine with that... 

Some more:
> Not a huge deal, but seems a little more clumsy to use.

From [here](https://github.com/symfony/symfony/issues/37100#issuecomment-642655856)

> To get the raw value, thus string|array use all()['key'].

From my [issue](https://github.com/symfony/symfony/issues/37029) before.. The solution suggested there above kills the api of `get` as I already said...
