### ISSUE TITLE
Workflow initial_marking is optional and entered event on initial_marking is not dispatched

### ISSUE THREAD

**Issue by pluk77** [symfony/symfony#37421]
The 'initial_marking' option seems to be optional as the first defined place will be used as the initial marking if 'initial_marking' is not defined. It therefore only seems useful when the initial_marking differs from the first marking defined in places.

It is therefore also impossible to have a blank marking after interacting with the workflow, even if the initial_marking is not set as it will be set to the first state automatically.

On top of this, the 'entered' event is not dispatched when the object moves to its initial marking as there is no transition.

We found this out the hard way when using workflow->getMarking($object) on a newly instantiated object to set its initial place and subscribing to the 'entered' event on the initial place. 

Eventually we solved this as follows:

    appointment:
        type: state_machine
        audit_trail:
            enabled: true
        marking_store:
            type: 'method'
            property: 'marking'
        supports:
            - Appointment
        initial_marking: UNKNOWN
        places:
            - UNKNOWN
            - SCHEDULED
            - RESCHEDULED
        transitions:
            TO_SCHEDULED:
                from: UNKNOWN
                to: SCHEDULED
            TO_RESCHEDULE:
                from: 
                    - SCHEDULED
                    - RESCHEDULED
                to: RESCHEDULED

    // new object with blank state
    $appointment = new Appointment();
    $workflow = $this->workflowRegistry->get($appointment);
    // set the marking to the initial state and transition to the correct state
    $workflow->apply($appointment, 'TO_SCHEDULED');

    public static function getSubscribedEvents(): array
    {
        return [
            'workflow.patient_appointment.entered.SCHEDULED' => 'appointmentScheduled',
            'workflow.patient_appointment.entered.RESCHEDULED' => 'appointmentRescheduled'
        ];
    }

My recommendations on how to update the documentation:
- explicitly mention that 'initial_marking' is optional and that the first defined place will be used as the initial place by default.
- explicitly mention that when entering the initial place, there is no 'entered' event dispatched
- perhaps have an example of how the setup the states when the initial state should have an event.

**Comment by epitre** [comment]
Hi,
would it be better to dispatch the entered event ?

**Comment by stof** [comment]
I think at least the first 2 points are topics for https://github.com/symfony/symfony-docs/issues instead

**Comment by pluk77** [comment]
> would it be better to dispatch the entered event ?

It would definitely be the preferred solution for our application and would make logical sense. I am not sure how others handle this type of scenario or if our 'workaround' is actually the correct way of using and setting the initial place. 

It would be a shame having to explicitly set the desired default place on new objects as it means the default place is now defined in two locations, namely the workflow yaml as well as in the code that creates the new object.

From a very brief test I determined a transition can not be configured to have a blank 'from', therefore entering the initial place can not have a transition which means not all events can be dispatched. 

Perhaps a new event that is not bound to a place name could also work. Something indicating a new object entered the default place without explicitly referencing it? This would make it clearly different from the other events especially because no transitions are dispatched when entering the default place. It would also allow for changing the default place in yaml without having to change the subscribers.

 > I think at least the first 2 points are topics for https://github.com/symfony/symfony-docs/issues instead

That depends on whether this is supposed to happen. If it is the correct behavior it should be documented, if it is not intentionally then it could be considered a bug / enhancement?

**Comment by lyrixx** [comment]
Hello. you are totally right about the first part.

IHMO, as @stof said, everything could be fixed in the documentation an not in the code.

BTW, we can not fix your issue in the current code. If you don't "pass" your subject to the workflow component, in anyway it can set the initial marking.

So yes, the right way to setup everything is to call `getMarking($subject)` in your code.

Finally, the very first "entered" event [is dispatched](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/Workflow.php#L74)

So, feel free to submit a PR to the doc repository :) 

If you have any other question, don't hesitate to post them here. If you don't have, I'll close this issue.

Thanks

**Comment by pluk77** [comment]
> Finally, the very first "entered" event is dispatched

You are correct in stating the global 'workflow.%s.entered' event is dispatched, but because there is no transition , the 'workflow.%s.entered.%s' event is not dispatched. https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Workflow/Workflow.php#L375

Are you proposing I create a subscriber that listens to the global 'workflow.%s.entered' events and then add logic to determine if this is the initial place or any other place I have entered?

**Comment by lyrixx** [comment]
Maybe we can publish this event, the method is private, so we can set the "TO" in this special case. WDYT?

**Comment by epitre** [comment]
@pluk77 I think that a `else` [here](https://github.com/symfony/symfony/blob/c2e2560657744a52038cf4fd68e19bb9ca8fc69d/src/Symfony/Component/Workflow/Workflow.php#L379) would be enough.
Then, you have to go through the initial places `$this->definition->getInitialPlaces()` and then dispatch `$this->dispatcher->dispatch($event, sprintf('workflow.%s.entered.%s', $this->name, $place));`

Well, it's just a suggestion.

**Comment by pluk77** [comment]
It would be great if the event can be dispatched with a TO.

The marking has been set already in enter() so is there a reason why the places are taken from the Transaction in entered() and not from the Marking? Technically, the entered event should be dispatched based on a place entered, not on the to's of a transaction, or am I missing something?

Perhaps instead of:

```php
if ($transition) {
    foreach ($transition->getTos() as $place) {
        $this->dispatcher->dispatch($event, sprintf('workflow.%s.entered.%s', $this->name, $place));
    }
}
```

use:

```php
foreach ($marking->getPlaces() as $place => $nbToken) {
    $this->dispatcher->dispatch($event, sprintf('workflow.%s.entered.%s', $this->name, $place));
}
```

**Comment by epitre** [comment]
@lyrixx @pluk77 
I imagine that [here](https://github.com/symfony/symfony/blob/c2e2560657744a52038cf4fd68e19bb9ca8fc69d/src/Symfony/Component/Workflow/Workflow.php#L375), we could have :
`
        if ($transition) {
            foreach ($transition->getTos() as $place) {
                $this->dispatcher->dispatch($event, sprintf('workflow.%s.entered.%s', $this->name, $place));
            }
        } elseif (!empty($this->definition->getInitialPlaces())) {
            foreach ($this->definition->getInitialPlaces() as $place) {
                $this->dispatcher->dispatch($event, sprintf('workflow.%s.entered.%s', $this->name, $place));
            }
        }
`
Just out of my head. I did not try it.

**Comment by pluk77** [comment]
@epitre 
Although it works, I do no think it is safe to assume the initial place is used if there is no transition set, especially because the actual place(s) are already in the marking store.

Unless there is a valid reason not to use the marking store, I would argue it should be used instead of the transition altogether in the entered() function. 

It feel to me looking at the transition instead of the current marking store is like finding out where I currently am by looking at where I came from instead of looking at your current position? But perhaps there is a reason that i am overlooking?

**Comment by epitre** [comment]
> Unless there is a valid reason not to use the marking, I would argue it should be used instead of the transition altogether in the entered() function.

I think you're right.

**Comment by pluk77** [comment]
@epitre

My initial solution was probably not going to work as it assumed Marking only had new markings. Although that is the case for initiation, it is not the case for all 'enetered' events (i think) because workflow can have the subject in multiple places at the same time.

Hence my propose pull request to add a new 'initiated' event.

**Comment by epitre** [comment]
@pluk77 in that case, I prefer my solution solution with the else : https://github.com/symfony/symfony/issues/37421#issuecomment-652343044

For now, the only case where transition is null is when the initial marking is set : https://github.com/symfony/symfony/blob/c2e2560657744a52038cf4fd68e19bb9ca8fc69d/src/Symfony/Component/Workflow/Workflow.php#L68

Obviously, it would be very important to write unit test to make sure that this will be taking into account in future development.

I am not a big fan of having yet another event to monitor. The entered event makes perfect sense. I would prefer to focus on this one.

**Comment by pluk77** [comment]
@epitre I get your point and created a new pull request with the change you proposed.

One reason one might want to separate the 'entered.place' and 'initiated.place' events is the high likelihood that the subject has not been persisted at all when the 'initiated.place' event is dispatched. This in contrast to the current 'entered.place' event which is likely to be dispatched when a persisted subject moves to a new place.
That is, unless you set an initial marking and transition the un-persisted subject to a new place before persisting it (like in my work-around). 

It is also a way to catch the initiation / start of a work-flow without having to know or hard-code the initial place in the subscriber. This allows for changing the initial place in one location without having to update the subscriber code.

The original 'entered' (without place) event is still dispatched so the proposed new event is backwards compatible.

**Comment by epitre** [comment]
what's the difference between workflow.name.initiated.place and workflow.name.entered.place ?
https://github.com/symfony/symfony/pull/37481/files#diff-6d1e8dc0d2c0e7c4ab206d0efbb71516R417

Still, I don't think I would use this new event, but if you do, ok.

**Comment by pluk77** [comment]
Difference would be that 'initiated.place' is only dispatched upon initiation of the subject, going to the initial place without a transition whereas 'entered.place' is dispatched only if the subject enters a place as a result of a transition.

If allowed to break backward compatibility I would even argue that `entered` should not be dispatched upon initiation as the subject has not undergone a transaction, thereby ensuring the 'entered' event series is only dispatched as a result of a transaction. 

@lyrixx, @stof, @xabbuh what do you think is the best solution going forward as I don't think it is just up to me.

**Comment by lyrixx** [comment]
hello.

I don't this #37481 is what we want. I don't know where it's the best place to comment (here or there), so let's continue here.

I don't like it because the code is not deterministic: I really depends on how you are using the workflow.
For instance, some people use the following code in their mode:

```php
class Foobar
{
    public function __construct()
    {
        $this->state = 'new'
    }
}    
```
In such situation, the `initiated` event would not be dispatched. However, the developer could expect it.

More over, adding another event (again) seems overkill to me. It does not bring anything useful. It's a personal feedback. I may be wrong :) 

Instead I would fix the entered method as explained in [this comment](https://github.com/symfony/symfony/issues/37421#issuecomment-652343044). I'm not sure it works but it should. In the first place I did not implemented by using the markin, because I did not think about it ! IMHO the solution is a better one :)

**Comment by sabat24** [comment]
I'm not sure why this issue is closed, because that merge didn't solve the core problem. 

I created an entity with not null `status` property. Workflow Component is configured to use that property for `marking store`. The `initial_marking` option is set to `draft`.

My entity has always got some status, so that property can't be null. This is why when I want to create new entity I have to provide it's initial state - in this case `draft`.

According to doc

> If you initialize the marking by calling $workflow->getMarking($object);, then the workflow.[workflow_name].entered.[initial_place_name] event will be called with the default context (Workflow::DEFAULT_INITIAL_CONTEXT).

However that event isn't triggered, because entity status property was already set to `draft` during creation.

```php
class Training
{
    public function __construct(
        private string $title,
        private string $status,
    ) {}
}
```

```php
$training = new Training('title', 'draft');
$trainingStatusStateMachine->getMarking($training); // <- here `workflow.entered.draft` event should be triggered
```
But event will not be dispatched because of that [line](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Workflow/Workflow.php#L91)

The point is that `workflow.entered.draft` event isn't triggered because `$training` status was set during creation. This is why Workflow Component ignores triggering the event because subject is already in the workflow. 

To *fix* the situation I should not set the status (leave it `null`) and allow the Workflow to set initial place name. But I do not want to do it, because I do not want to allow my entity to be invalid.

Another solution is to create "fake" initial status for example `init`. During entity creation set that state to entity and right after that apply transition from `init` to `draft`.

**Comment by pluk77** [comment]
@sabat24 I also would have liked a slightly different solution, but at least there is a work-around, which I have used extensively

I would indeed create an initial place which is set in the constructor and define the first transition to only go from that initial place to draft.

After instantiating your training entity, you apply the draft transition and all is well. A small extra step that will cause little to no overhead. 

If you ensure the entity is only committed after applying the 1st transition successfully, you will never have any entity with the initial marking.

**Comment by sabat24** [comment]
@pluk77 Your flow is exactly that what I called a "fake" initial status. But in my opinion Workflow should just do it behind scenes. There should be a method named for example `initialize`. 

```
$trainingStatusStateMachine->initialize($training);
```

If my object is already in workflow with it's initial marking defined in `initial_marking` option, `entered` event should be dispatched. It's very clean and simple solution.

**Comment by lyrixx** [comment]
IMHO, there is nothing wrong here.

1. if the object does not have a marking, the component will set the marking and dispatch the event
2. if the object has a marking, the component does nothing, because nothing occurred.

And you have well summarized the situation: 

> To _fix_ the situation I should not set the status (leave it `null`) and allow the Workflow to set initial place name. But I do not want to do it, because I do not want to allow my entity to be invalid.

If you don't want to let the `null` value, there is nothing we can do.

BTW, I do think leaving `null` is the way to go. Indeed the entity will be invalid during it's lifecycle creation, but it's legit...
You need an external service to "finalize" it's creation. So the entity is not 100% functional after the new.

If you really want to go wild:

```php
class Subject
{
    public function __construct(
        private string $state,
        WorkflowInterface $w,
    ) {
        $w->getMarking($this);
    }
}
```

Or can can fire the transition yourself.

**Comment by epitre** [comment]
I agree with @lyrixx , if there is already a status, there must be a reason.

the goal here is to _initialize_ the status, not to reset it.

leaving the status property is the way to go, IMHO.

**Comment by sabat24** [comment]
> I agree with @lyrixx , if there is already a status, there must be a reason.

The only reason for already existing status is *always-valid paradigm*. 

> the goal here is to _initialize_ the status, not to reset it.

That's my goal, too. I manually initialized status in entity and this is why I wanted to find a way that Workflow was aware about that initialization to dispatch some starting events as "orchestrator".

I understand your point of view, but we can't agree with one crucial point: allowing the entity to not have a marking. For me it's not an option per se even for a while. This is why it leads me to finding other design pattern like initializing the marking outside the Workflow like it would be part of the Workflow.
For you leaving marking empty is a valid and proper solution, this is why you do not see a need to do it in other way.

All in all 

> Or can can fire the transition yourself.

suits for me best. I came up with same approach like that presented by pluk77.

Thank you all for your opinions.
