### ISSUE TITLE
[RFC] Rename master request

### ISSUE THREAD

**Issue by ghost** [symfony/symfony#37509]
`master` has become a word with undesireable connotations, so I propose to rename master request to something more acceptable, like main request, or primary request.

**Comment by yceruto** [comment]
duplicated of #37331, let's follow the discussion there, thanks!

**Comment by stof** [comment]
@yceruto this is not about the master branch.

**Comment by nicolas-grekas** [comment]
Submitter account has been ghosted, there is no argumentation about why this should be considered an issue.

**Comment by barthy-koeln** [comment]
Please excuse necroing this thread, but I haven't found any other discussion, I think the issue is relevant, and i would like to provide context and some explanation:

In an effort to remove words connected to slavery and racially suggestive terms, a lot of companies and projects have opted to rename and entirely remove several terms listed below:

`master`/`slave`
(Suggested replacements: `main`, `primary`, `secondary`, `replicant`, ...)
 
`blacklist`/`whitelist`
(Suggested replacements: `denylist`/`allowlist`)

As Filippo Valsorda put it in a ticket for the Go programming language:

> It's clear that there are people who are hurt by [these terms] and who are made to feel unwelcome by their use due not to technical reasons but to their historical and social context. That's simply enough reason to replace them.

[Source: Ticket 236857 | replace usages of whitelist/blacklist and master/slave](https://go-review.googlesource.com/c/go/+/236857/)

___

Here is a scientific paper on the general subject, released October 2018 in the "Journal of the Medical Library Association":

[“Blacklists” and “whitelists”: a salutary warning concerning the prevalence of racist language in discussions of predatory publishing](https://dx.doi.org/10.5195/jmla.2018.490)

Here are two useful casual reads more related to the tech industry:

[GitHub plans to replace racially insensitive terms like ‘master’ and ‘whitelist’](https://thenextweb.com/dd/2020/06/15/github-plans-to-replace-racially-insensitive-terms-like-master-and-whitelist/)
[Linux team approves new terminology, bans terms like 'blacklist' and 'slave'](https://www.zdnet.com/article/linux-team-approves-new-terminology-bans-terms-like-blacklist-and-slave/)

___

Specifically for the `RequestStack` class, this would mean deprecating the `getMasterRequest` method in favor of `getMainRequest`, `getRootRequest` or similar.

**Comment by derrabus** [comment]
Thank you for the explanation, @barthy-koeln. I've reopened the issue.

**Comment by derrabus** [comment]
#40536
