### ISSUE TITLE
BOOK

### ISSUE THREAD

**Issue by pculka** [symfony/symfony#37596]
**Symfony version(s) affected**: 5.0.3

**Description**  
Hi, I bought the book Fast Track and upon starting it up I get following error:

![image](https://user-images.githubusercontent.com/4672645/87677610-44a7b300-c77a-11ea-8750-30a19ac895c1.png)

**How to reproduce**  
symfony new --version=5.0-3 --book guestbook

**Possible Solution**  
no idea, I guess there should be something added like "http://localhost:8000" into webpack?

**Additional context**  
Issues in fast track book github are disabled for whatever reason, this ain't really a symfony issue. So I suggest enabling fast track issue reporting and move this issue over there...

**Comment by Nek-** [comment]
Hello, thank you for reporting this.

Somebody will take a look at it. Besides, I tried it on my side and I had another issue: Symfony starts the wrong version of PHP.

I use macOS, and installed the last version of PHP the recommended way: using brew. So I have PHP 7.4... But the default version of PHP on MacOS is PHP 7.3 and it's not uninstalled. SymfonyCLI uses PHP7.3 version (which is wrong, missing extension such as amqp, end somehow idk why broken because of blackfire missing).

All of this makes the Symfony book installation fail besides I have the most standard and recommended setup. I think you should take a look at this too.

**Comment by pculka** [comment]
Well I use PHP 7.4 on shell.
Eventually it starts and "works", but overall some knowledge is really needed to get this up and running. Certainly if I would never have been using docker or anything, I would be stuck at the beginning...

when using debug I've seen aswell the deps for blackfire in the output and that is also something that should not be there. I believe the basic profiler in Symfony should be more than enough fro beginners.

Also I'd recommend enabling and moving this issue over to the book repo

**Comment by chalasr** [comment]
This is definitely not the right place for such a report, indeed. Please consider reopening on symfony/cli if it's still relevant.
Thank you.
