### ISSUE TITLE
[Mailer] Allow passing an array to `cc()`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#37657]
**Description**  
The current syntax for multiple cc's is - see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Email.php#L202
```php
$email->cc('1@example.com', '2@example.com', '3@example.com');
```
Due to the splat operator in its declaration `public function cc(...$addresses)`, the function takes a variable number of arguments, and appends them to the `$addresses` array, which is then passed to [`setListAddressHeaderBody()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Email.php#L537).

But what if you already have the CC's in an array?? You cannot pass it to `cc()` - you'll get:

> An address can be an instance of Address or a string ("array") given).

So what's the current solution? "expand" the array somehow, only to have the splat operator reassemble it?

I'm suggesting to allow to pass an array to `cc()` as well. This could be achieved by adding an `is_array()` to [`Address::createArray()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Mime/Address.php#L111), then `array_merge()` instead of `$addrs[]`.

**Comment by ro0NL** [comment]
what about https://3v4l.org/mtrDN ?

**Comment by fabpot** [comment]
@ro0NL is correct, no need to support arrays.

**Comment by ThomasLandauer** [comment]
Yeah, sorry, just found that out too :-)

I opened a PR to improve findability in the docs: https://github.com/symfony/symfony-docs/pull/13996

Just for the records: If you pass a *string* with the three dots (`$email->cc(...'foo@example.com');`), you'll get:

 > Warning: Only arrays and Traversables can be unpacked

**Comment by stof** [comment]
that's expected, as the `...` operator does not apply on strings.

**Comment by collinkrawll** [comment]
@fabpot What about nulls? How should I handle an array that comes from my business logic when the business logic might return no addresses? You can't unpack null and adding an empty array sets the header (with a blank value). For example:

```
$cc = $myBusinessObj->getCc(); // There might not be any cc addresses.

$email = (new Email())
    ->addCc($cc)
    ...
```

I can change the above to `->addCc(...$cc)` to unpack the array but if `$cc` is null, a `TypeError: Only arrays and Traversables can be unpacked` error is thrown. I can update `$myBusinessObj->getCc()` to return `[]` instead of `null` but calling `->addCc(...[])` (with an empty array) adds an empty 'CC' header to the email. 

I've worked around the issue by breaking apart the builder and putting the `->addCC(...$cc)` part in an `if` statement, but it seems like there has to be a better way. Maybe I just haven't thought of it? With Swift, we would just pass an array or null without issue.

Thanks for your help.
