### ISSUE TITLE
[WebProfilerBundle] BC break in 4.4.11 - debug bar won't load

### ISSUE THREAD

**Issue by keksa** [symfony/symfony#37655]
**Symfony version(s) affected**: 4.4.11

**Description**  
Debug bar won't load anymore for our use case after changes introduces in https://github.com/symfony/symfony/pull/37576 because it's blocked by CORS.

We're using a setup, where we have 2 application modules accessible behind a proxy. The proxy is running at `proxy.test` and the modules are accessible at `proxy.test/foo` and `proxy.test/bar`. The modules itself are running at their own internal URLs -> `foo.test` and `bar.test`.

It worked before with the relative URL, because the `/foo/_wdt/66dc93` was loaded by browser as `proxy.test/foo/_wdt/66dc93`, but now it's loaded as `foo.test/foo/_wdt/66dc93`.

It's very much possible this can be solved by some configuration on our part, but IMO this is BC break and as such should not be released in patch version.

**Comment by stof** [comment]
Well, this means that *any* place generating absolute URLs in your project is actually broken, right ?

I suggest instead to configure your project to consider your proxy as a trusted proxy and ensure that the proxy sets the forwarded headers properly, so that Symfony knows about `proxy.test` being the public URL. This will fix *all* generation of absolute URLs in your project.

**Comment by keksa** [comment]
Hi @stof, yes, you're absolutely correct and I'll look into it, thank you for the pointer. 🙂 Since all absolute URL generation is broken in our case, I guess this issue can be closed as it's not really BC in the end. Did not think to check that, as we simply don't use it anywhere.
