### ISSUE TITLE
Symfony Validator implicitly requires symfony/mime since 4.4.9

### ISSUE THREAD

**Issue by Cladis** [symfony/symfony#37709]
**Symfony version(s) affected**: Symfony Validator 4.4.11

**Description**  

I see that for Validator between 4.4.0 and 4.4.11 Mime was used for production code https://github.com/symfony/validator/commit/ec017d56894e6613d6062400db66560d983dd499  since 4.4.9
while it was only added require-dev: https://github.com/symfony/validator/compare/v4.4.0...v4.4.11 . This means that the production code that was working fine now breaks with 
```
You cannot guess the mime type as the Mime component is not installed. Try running "composer require symfony/mime".
```
since Symfony requires Mime component under the hood.

**How to reproduce**  

Code making use of `FileValidator`

**Possible Solution**  

Add symfony/mime to `require` section instead.

**Additional context**

**Comment by stof** [comment]
Well, the `symfony/validator` has some optional dependencies used by some constraints. Adding them as required dependencies would mean that we would bring them to projects even if we don't use them.

Btw, before that commit, the mime type validation would be working only if you have `symfony/http-foundation` available (the commit changes it to support using `symfony/mime` even when `symfony/http-foundation` is not there), and the commit preserves that. The exception is triggered only when you have none of `symfony/http-foundation` and `symfony/mime`.
the only way I can see your prod code becoming broken while it was working before would be that you removed `symfony/http-foundation` from your dependencies when upgrading (otherwise, it would have been broken already before that)

**Comment by nicolas-grekas** [comment]
Closing as explained by @stof, the message says it all.

**Comment by Cladis** [comment]
I hope to investigate it later, and if I come up with example code I will poke you guys. We do have http-foundation in our project, so it should not be caused by what is described.
