### ISSUE TITLE
[Validator]

### ISSUE THREAD

**Issue by yahyaerturan** [symfony/symfony#37716]
**Symfony version(s) affected**: 5.1.*

**Description**  
`validator/Resources/translations/validators.{lang}.xlf` files are not loading as fallback when we call it from the controller with `Validation::createValidator();` if the locales are in `{lang}_{region}` format.

In translations, if locale is `de_CH`, it check for `de_CH` files first, then fallbacks to `de` then fallback to fallback locale, i.e. `en_US`. Shouldn't be the same flow for pre-built translation messages?

```php
public function anyControllerMethod(Request $request): Response
{
    $name = $request->request->get('name');
    $validator = Validation::createValidator();
    $violations = $validator->validate($name, [
        new NotBlank(),
        new Length(['min' => 4]),
    ]);

    ....  
```

Here, validation messages return in fallback locale. I think it is expected to fallback to `validators.de.xlf`?

**Comment by ro0NL** [comment]
Did you set a translator on the validator? by default it uses an identity translator;

https://github.com/symfony/symfony/blob/de39dbae8f2425f48e790c4f1b3e70f9b702554f/src/Symfony/Component/Validator/ValidatorBuilder.php#L381-L390

Do you aim to use the validator standalone? Otherwise i suggest to use the pre-defined `validator` service provided by the framework.

**Comment by yahyaerturan** [comment]
I did not define a translation. I was expecting to pick up internal `de` translation. And it does when I use pre-defined validator service as a method param. The phrase "framework" is just the key here :(  I thought it was a bug. Sorry :(
