### ISSUE TITLE
Serialization groups interfere with datetime objects

### ISSUE THREAD

**Issue by shumichenko** [symfony/symfony#37737]
I'm trying to serialize my **Article** entity and everyrthig's good, but **serialization groups** interfere with **datetime objects** and **datetime properties** are empty (In case of removing **AbstractNormalizer::GROUPS** assignment everything's OK). My output looks like: 

`[
    {
        "alias": "my-article",
        "title": "My article",
        "content": "Sample of an article here...  Sample of an article here... Sample of an article here... ",
        "created_at": [
    ],
        "updated_at": [
    ],
        "image_link": "kek",
        "author": {
        #information hidden#
        }
    }
]
`

[Article.txt](https://github.com/symfony/symfony/files/5021114/Article.txt)
[ArticleFetcher.txt](https://github.com/symfony/symfony/files/5021126/ArticleFetcher.txt)

**Comment by l-vo** [comment]
It looks like a problem between groups and callbacks (not datetime). In your `Article` you have:

```php
   /**
     * @ORM\Column(type="datetime")
     * @Groups({"admin", "user"})
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"admin", "user"})
     */
    private $updated_at;
```
And in your `ArticleFetcher`:
```php
$defaultContext = [
            AbstractNormalizer::GROUPS => ['user'],
            AbstractNormalizer::CALLBACKS => [
                'createdAt' => $dateCallback,
                'updatedAt' => $dateCallback
            ],
            //...
        ];
```

Since group annotations are on your properties, you have to use the property names:
```php
$defaultContext = [
            AbstractNormalizer::GROUPS => ['user'],
            AbstractNormalizer::CALLBACKS => [
                'created_at' => $dateCallback,
                'updated_at' => $dateCallback
            ],
            //...
        ];
```

It's a bit tricky, internally:
* If you use groups on some properties, normalizer see your private properties and use getters to retrieve their values (`PropertyAccess`) so you have to identify them by their property names (`updated_at` and `created_at`).
* If you don't use groups, names are directly extracted from your getter names so you have to use `updatedAt` and `createdAt`

**Comment by shumichenko** [comment]
@l-vo You are the best! I didn't noticed that. My gratitude.
