### ISSUE TITLE
It is possible to pass request parameters of any type to the Symfony web crawler

### ISSUE THREAD

**Issue by rgeraads** [symfony/symfony#37740]
**Symfony version(s) affected**: 5.1

**Description**  
It is possible to pass request parameters of any type to the Symfony web crawler, something that's not possible in actual requests.

**How to reproduce**  
On the sending end:
```
        $client = static::createClient();
        $client->request('POST', '/endpoint', [
            'foo' => 'bar',
            'baz' => 1.1,
            'boz' => Uuid::uuid4(),
        ]);
```
On the receiving end:
```
        var_dump($request->get('foo')); // 'bar'
        var_dump($request->get('baz')); // 1.1
        var_dump($request->get('boz')); // object(Ramsey\Uuid\Lazy\LazyUuidFromString)
```

**Possible Solution**  
Values in the request parameters should be restricted to strings. Any other type should result in an error.

**Comment by stof** [comment]
To emulate the incoming requests properly, any request or query parameters handling by BrowserKit should indeed be casted to string (I would do a string cast rather than enforcing strings only, to reduce the burden for passing numbers for instance)

**Comment by stof** [comment]
Of course, arrays should still be allowed for nested values. But their values must satisfy the requirement.

**Comment by rgeraads** [comment]
To make it even more complete, all array keys should also be cast to string.

**Comment by patrickbussmann** [comment]
This creates a new issue.

I'm using Symfony for a REST API.
And before 5.2 I'm using this PHPUnit test:

```
$this->client->request('POST', '/api/bookings', [
    'description' => 'Example',
    'notifyCustomer' => false
]);
```

This **was** successful.

Now with `5.2` the string conversion thing destroys it.
The `false` becomes an empty string and the form things the empty string is `true`.

When I'm using another request it's working.

```
$this->client->request('POST', '/api/bookings', [], [], [
    'CONTENT_TYPE' => 'application/json'
], json_encode([
    'description' => 'Example',
    'notifyCustomer' => false
]));
```

Some ideas? @stof @rgeraads

**Comment by rgeraads** [comment]
HTTP variables will always be strings. It is not possible to send boolean values over the line, they have to be converted back to boolean by the receiver. This fix exposes that. It is likely that some tests will fail, but it is to help prevent bugs.

**Comment by derrabus** [comment]
@patrickbussmann In your examples, you're mixing up a form-data and JSON payloads. Form-data does not care about types, everything is a string. JSON on the other hand knows booleans, numbers and strings.

**Comment by patrickbussmann** [comment]
Hmm ok maybe you're right @rgeraads but how to solve this case?

For example when I'm using 'false' as string or '0' the form is still true.
When I set `false_values` to `['', '0', 'false']` its working.
But I think this is not the idea of this.

Someone created a special type for it here https://github.com/fsevestre/BooleanFormType
But until now I was able to handle the CheckboxType for this cases.
And its working now, too - but only with real requests.

Only my PHPUnit tests are failing because of this change.

So whats the "best practise" for solving?
`false_values`?


My current solution was to downgrade: `"symfony/browser-kit": "5.1.*",`
With 5.2 I'll get this problems.

**Comment by xabbuh** [comment]
If you want to simulate a request in which a checkbox is not ticked, you can simply omit the parameter.

**Comment by patrickbussmann** [comment]
In theory you're right @xabbuh.
But in my case the form is submitted manually:

    $form->submit($request->request->all(), false);

So when I not submit the field because its not specified the update of the entity is failing.

Creation = Yes it works. No field = Checkbox is false
Update = No, fails. No field = No update = Checkbox is the value from before

😢
