### ISSUE TITLE
httpClient doesn't allow to change the curl_setopt options

### ISSUE THREAD

**Issue by dvdknaap** [symfony/symfony#37798]
**Description**  
It would be nice if you could change the curl_setopt option to what every like you want at the moment it's not possible to change any and it's only using the defined ones.

Could there be a function or option param that will be used to change the curl to your liking ?

**Example**  
```php
        $options = [
            'curlOptions' => [
                'CURLOPT_IPRESOLVE' => CURL_IPRESOLVE_V4,
            ],
        ];

            /** @var CurlResponse $res */
            $res = $httpClient->request(
                $method,
                $requestUrl,
                $options
            );


# Then when executing `vendor/symfony/http-client/AmpHttpClient.php` check for this option 'curlOptions' and pass it in curl_setopt_array
```

**Comment by nicolas-grekas** [comment]
The downside of doing this is that it instantly breaks portability. I'd prefer consider each option on a case by case basis before. What do you want to achieve ?

**Comment by javaDeveloperKid** [comment]
I was looking first at the documentation, then searching Google how I can set curl option when creating request and did not find any information about that. That's to bad we cannot manipulate these options and this should be explicitly mentioned in the documentation so developers know this at the very beginning. 
E.g. I need to set arbitrary TLS version to 1.2, otherwise my requests get rejected by an external server (CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1_2).
I think it's a big limitation that an instance of CurlHttpClient does not provide the same possibilities as when using curl_* functions directly.

**Comment by nicolas-grekas** [comment]
Anyone up for giving it a try? I think an option named `curl` under the special `extra` option might do it.

**Comment by pizzaminded** [comment]
@nicolas-grekas  if no one has taken this, im up as sometimes i need this kind of additional configuration.
