### ISSUE TITLE
denyAccessUnlessGranted still allows $attributes although it was deprecated since Symfony 4.4

### ISSUE THREAD

**Issue by Nijusan** [symfony/symfony#37824]
**Symfony version(s) affected**: > 5.0

**Description**  
In the AbstractController the Method Signature for `denyAccessUnlessGranted` accepts still an array of attributes as the parameter name implicates $attributes... using still an array breaks further implementations without having the deprecation notice removed lately in the `AuthorizationChecker`.
So this is not breaking the system, but resulting in a nested array with all attributes passed to the Voter->supports-Method.

**How to reproduce**  
passing an array to the `denyAccessUnlessGranted` Method -> 
`$this->denyAccessUnlessGranted(['foo', 'bar'], $bazz);`

**Comment by fancyweb** [comment]
Status: works for me

The attribute can technically be an array because it can be of any type (cf `AuthorizationCheckerInterface`). However, the deprecation is always triggered on 4.4 thus making it impossible to get rid off if you want to use an array attribute.

The migration path from 4.4 to 5.x clearly has a problem. On 4.4, `$this->denyAccessUnlessGranted(['foo', 'bar'])` will call the access decision manager with `['foo', 'bar']`. On 5.x, it will call it with `[['foo', 'bar']]` uncondtionally and it will obviously not produce the same results. 

https://github.com/symfony/symfony/pull/34074 removed the exception.

I don't see what else we can do here.

**Comment by Nijusan** [comment]
but isnt the parameter name $attributes missleading to wrong usage? minimal change to $attribute would help, wouldnt it?

**Comment by fancyweb** [comment]
I guess we can rename from $attributes to $attribute in AbstractController to help clarify (like it was done in https://github.com/symfony/symfony/pull/34074). Can you send a pull request?
