### ISSUE TITLE
[Validator] Luhn constraint message

### ISSUE THREAD

**Issue by guitoon** [symfony/symfony#37839]
**Symfony version(s) affected**: 4.4 / 5.1

**Description**  
The Luhn constraint message is limited to cart number. It's an algorithm used in other cases, like french Siren

**Possible Solution**  
A more generic message should be more accurate.

**Comment by YaFou** [comment]
For me :-1:. Many use cases use this algorithm and we can't enumerate each use case because the message will be to long. The bank card number is the most famous use case which uses this algorithm. A possible solution is that the developer edits this translation in its project or add a custom message in the annotation.

**Comment by xabbuh** [comment]
I think I agree with @YaFou
