### ISSUE TITLE
loadUserByUsername method with same signature expect different behaviour

### ISSUE THREAD

**Issue by CoalaJoe** [symfony/symfony#37885]
**Symfony version(s) affected**: 5.1

**Description**  
The `Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface` and `Symfony\Component\Security\Core\User\UserProviderInterface`  both provide the method `public function loadUserByUsername(string $username);` but seem to expect different behaviour when a user is not found.

The `UserLoaderInterface` states: "This method must return null if the user is not found."

And the `UserProviderInterface` states: "This method must throw UsernameNotFoundException if the user is not found."

Currently, I am in the unfortunate situation of having both implemented in the same class. Should I refactor this or are there plans to unify those Interfaces or differentiate the method signatures?

**Comment by wouterj** [comment]
> Currently, I am in the unfortunate situation of having both implemented in the same class.

Can you maybe share some details on why you have to implement both? I can't imagine it's needed. `UserProviderInterface` is the generic interface used by Symfony to load users. The doctrine bridge implements this in the [`EntityUserProvider`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php). This user provider allows Doctrine repositories to implement the special `UserLoaderInterface` in order to customize how the entity is loaded. So AFAICS, you either implement a completely custom user provider, or you implement custom logic in your Doctrine repository, but never both?

**Comment by CoalaJoe** [comment]
@wouterj 

I use both interfaces in UserRepository.

The `UserLoaderInterface` is implemented, to allow users do log in with either their username oder email.

The `UserProviderInterface` is implemented to add some additional data when refreshing the user.

Is this an odd choice?

**Comment by wouterj** [comment]
I would recommend to just create a custom user provider. It can do both. I'm also not sure how you plan to use the entity user provider *and* your custom user provider at the same time.

```php
class UserProvider implements UserProviderInterface
{
    // ...

    public function loadUserByUsername($username)
    {
        return $this->userRepository->findOneByEmailOrUsername($username);
        // or without custom repository method: $this->userRepository->findOneBy(['email' => $username]) || $this->userRepository->findOneBy(['username' => $username])
    }

    public function refreshUser(UserInterface $user)
    {
        // ... custom refresh logic
    }
```

**Comment by CoalaJoe** [comment]
There was a misunderstanding.

I dropped the UserProviderInterface, as it has been implemented but actually was never user. To recap.
- Use the UserLoaderInterface to extend the default EntityProvider.
- Use UserProviderInterface to allow login from not-yet supported sources.
