### ISSUE TITLE
XHR for /_wdt/* is on HTTP instead of HTTPS

### ISSUE THREAD

**Issue by skymanpl** [symfony/symfony#37980]
**Symfony version(s) affected**: 5.1.3

**Description**  
I noticed that Symfony's toolbar is not working on my website, due to mixed content on page - XHR for _/_wdt_ was on HTTP instead on HTTPS.

I though _router.request_context.scheme_ set to '_https_' would be enough, but it seems to be ignored. I've hope I'm not missing something basic.

**services.yaml**
```
parameters:
    router.request_context.host: 'mydomain.com'
    router.request_context.scheme: 'https'
    asset.request_context.secure: true
```
**How to reproduce**  
Enable HTTPS on whole site.

**Possible Solution**
I added simple workaround: replace function for url in **vendor\symfony\web-profiler-bundle\Resources\views\Profiler\base_js.html.twig** . This worked for me, but I doubt it is 'correct' solution in the end - toolbar should use user's config.

```
var request = function(url, onSuccess, onError, payload, options) {
    var xhr = window.XMLHttpRequest ? new XMLHttpRequest() : new ActiveXObject('Microsoft.XMLHTTP');
    options = options || {};
    options.maxTries = options.maxTries || 0;
    url = url.replace(/^http:\/\//i, 'https://');
```

**Comment by nicolas-grekas** [comment]
Can you please provide a simple reproducer? I use the wdt on https everyday and it works work me.

**Comment by Izopi4a** [comment]
i am not using the build in server for simfony, just a nginx with nothing special, just copy pasted from the docs

```
server {

    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html/public;


    location / {
        # try to serve file directly, fallback to index.php
        try_files $uri /index.php$is_args$args;
    }

    # optionally disable falling back to PHP script for the asset directories;
    # nginx will return a 404 error when files are not found instead of passing the
    # request to Symfony (improves performance but Symfony's 404 page is not displayed)
    # location /bundles {
    #     try_files $uri =404;
    # }

    location ~ ^/index\.php(/|$) {

        include snippets/fastcgi-php.conf;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;

        # optionally set the value of the environment variables used in the application
        # fastcgi_param APP_ENV prod;
        # fastcgi_param APP_SECRET <app-secret-id>;
        # fastcgi_param DATABASE_URL "mysql://db_user:db_pass@host:3306/db_name";

        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        # Prevents URIs that include the front controller. This will 404:
        # http://domain.tld/index.php/some-path
        # Remove the internal directive to allow URIs like this
        internal;
    }

    # return 404 for all other php files not matching the front controller
    # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
        return 404;
    }
}
```

and it is the same for me. the request is http and I get mixed content error

**Comment by nicolas-grekas** [comment]
You might be missig a fastcgi parameter to tell the app that it runs under HTTPS.
Usually, there is an `include fastcgi_params;` line that takes care of this AFAIK.

**Comment by Izopi4a** [comment]
no, the nginx is working without an ssl, it is what is in front of the nginx that serves the content on 443 and as a https request, but because the automatic http to https is not configured, I get a mixed content error.

For me this is a bug, the profiler should respect the browser scheme and perform the ajax correspondingly.

**Comment by nicolas-grekas** [comment]
> the profiler should respect the browser scheme and perform the ajax correspondingly

URLs are generated service-side: the app needs to know it is behind https to work correctly. Yes, we could maybe use JavaScript for the wdt, but that would still not work for all the other links/URLs that you app might generate.

**Comment by Izopi4a** [comment]
https://github.com/symfony/web-profiler-bundle/blob/master/Resources/views/Profiler/base_js.html.twig#L425

so for me here it is http ( instead of https ) ( the generated code in the console is http)

based on the docs here: https://symfony.com/doc/current/reference/twig_reference.html#url

```
Returns the absolute URL (with scheme and host) for the given route. If schemeRelative is enabled, it’ll create a scheme-relative URL.
```

do you think `schemeRelative` might help? i am new to symfony and I don't know where to place this config property. If you could help me I can try it

**Comment by skymanpl** [comment]
I've Apache/2.4.41 on OVH VPS with free SSL Gateway Free.

You can access site with following credentials:
[test    /    12345](https://chojnacki.link/)

P.s. The latest Firefox has [problem with a XHR authorization header and an upgrade-insecure-requests meta tag](https://bugzilla.mozilla.org/show_bug.cgi?id=1659503) if there is mixed content, so for time being you should try access the website in a different browser.

**Comment by djgxp** [comment]
Same for me, /_wdt/* patterns used to work in SF4 but in SF 5.1.5 I see mixed content errors and these patterns are in http instead of https.

**Comment by nicolas-grekas** [comment]
@djgxp could you provide us with a reproducer that works/doesn't work depending on the version of Symfony?

**Comment by skymanpl** [comment]
For anyone interested, if you use path() function instead of url() in the file **\vendor\symfony\web-profiler-bundle\Resources\views\Profiler\base_js.html.twig**, it works just fine.

```
            loadToolbar: function(token, newToken) {
                newToken = (newToken || token);
                this.load(
                    'sfwdt' + token,
                    '{{ url("_wdt", { "token": "xxxxxx" })|escape('js') }}'.replace(/xxxxxx/, newToken),
```

```
            loadToolbar: function(token, newToken) {
                newToken = (newToken || token);
                this.load(
                    'sfwdt' + token,
                    '{{ path("_wdt", { "token": "xxxxxx" })|escape('js') }}'.replace(/xxxxxx/, newToken),
```

**Comment by skymanpl** [comment]
For anyone interested:

1. If you use path() function instead of url() in the file **\vendor\symfony\web-profiler-bundle\Resources\views\Profiler\base_js.html.twig**, it works just fine.

```
            loadToolbar: function(token, newToken) {
                newToken = (newToken || token);
                this.load(
                    'sfwdt' + token,
                    '{{ url("_wdt", { "token": "xxxxxx" })|escape('js') }}'.replace(/xxxxxx/, newToken),
```

```
            loadToolbar: function(token, newToken) {
                newToken = (newToken || token);
                this.load(
                    'sfwdt' + token,
                    '{{ path("_wdt", { "token": "xxxxxx" })|escape('js') }}'.replace(/xxxxxx/, newToken),
```

2. Same with schemeRelative in url() function, suggested by Izopi4a
```
                this.load(
                    'sfwdt' + token,
                    '{{ url("_wdt", { "token": "xxxxxx" }, true)|escape('js') }}'.replace(/xxxxxx/, newToken),
                    function(xhr, el) {
```

**Comment by nicolas-grekas** [comment]
Please help us figure out the root cause of the issue.

**Comment by nicolas-grekas** [comment]
> the nginx is working without an ssl, it is what is in front of the nginx that serves the content on 443

ok, then you need to configure nginx to still send the `HTTPS: on` param to php, in order to allow the app to.

OR, better: the thing that is in front of nginx should send `X-Forwarded-*`/`Forwarded` headers, and you need to configure the IP of that thing in the list of trusted proxies.

I'm pretty these missing headers is the root cause of the issue. The webprofiler not working is only a symptom.

Closing therefor. Please provide additional details of you thing this was misdiagnosed.

**Comment by Izopi4a** [comment]
here are 2 screens that are showing what the profiler is generating as a code in mine page. The page is HTTPS, and the ajax URL is set to HTTP. 

https://ibb.co/9tTSrBT

https://ibb.co/mGBfx1Y

For me, this is the root problem. @nicolas-grekas

**Comment by nicolas-grekas** [comment]
About OVH SSL Gateway, the issue is exaclty the one I suspected this morning: missing `X-Forwarded-*` headers, see this on the OVH side: https://docs.ovh.com/fr/ssl-gateway/utiliser-le-ssl-gateway/

See this on the Symfony side: https://symfony.com/doc/current/deployment/proxies.html

**Comment by Izopi4a** [comment]
ok, I see, so this tells symfony to look for h_forwarded_for headers. It resolves the issue.

i still think this is a valid or tho https://github.com/symfony/symfony/pull/38076

I think many people will start to complain soon. Anyways, thx

**Comment by stof** [comment]
no it is not. Using a full URL allows for things to work for projects loading the toolbar for AJAX requests and having multiple hosts involved. For that to work, we need an absolute URL rather than a path.
The only projects impacted by such toolbars are the ones for which other features are already broken (`$request->isSecure()`, `$router->generate(..., UrlGeneratorInterface::ABSOLUTE_URL)`, etc...). And then, the solution is to fix all these issues at once by trusting the reverse proxy.

**Comment by Naqued** [comment]
Same problem here since an update of symfony 4.4.9 to 4.4.11 +

**Comment by nicolas-grekas** [comment]
@Naqued could you please check which version exactly introduced the change for you, and maybe which change in the source leads to this?

**Comment by Naqued** [comment]
It has been introduce since version 4.4.11 for us.

As the doc you linked specify, we added our reverse proxy ip to the TRUSTED_PROXY and it worked fine

Thanks

**Comment by BogdanMantescu** [comment]
I solved by putting in nginx.conf fastcgi_param HTTPS 'on';
it worked for me ( haproxy + nginx)

**Comment by Philosoft** [comment]
@nicolas-grekas hi there. I stumbled across the same issue, when using a little bit more complicated load balancing scheme then just nginx -> php-fpm. I use traefik -> nginx -> php-fpm for reasons that are not important right now. I think @Izopi4a ( from https://github.com/symfony/symfony/issues/37980#issuecomment-684024983 ) has somewhat similar setup.

How it works (for me and for ppl from this thread I think)

```
user -- https --> traefik (or any other balancer with http termination) -- http -> nginx -- fastcgi --> php-fpm
```

`X-Forwarded` headers are sent as expected. We (as users) expect it to be work via https. Symfony thinks that it's http, since request comes mainly with http attributes (port, scheme, etc). "Problem" lies here:

https://github.com/symfony/http-foundation/blob/5.1/Request.php#L1127-L1146

Since in default configuration there are no trusted proxies, request falling back to checking `$_SERVER['HTTPS'] === 'on'`. Sooo, basically there is no problem, since this exact situation is described in [docs](https://symfony.com/doc/current/deployment/proxies.html). Since there is a load balancing software which *terminates https* there is no reliable info about original https request for symfony by default.

Solutions are the same (for prod/stage/testing and for local development) and described in docs. I will cover them only in regard of local dev environment.

1. Option 1. Provide `HTTPS` fastcgi param with value  `on` (for nginx `fastcgi_param HTTPS on` in nginx config (as was proposed by you here https://github.com/symfony/symfony/issues/37980#issuecomment-688153771))
2. Option 2. Provide trusted proxies via software configuration (for nginx `fastcgi_param TRUSTED_PROXIES "192.168.0.0/24"`, it's also should be possible through php-fpm configuration, but it's not that convenient for my tastes)
3. Option 3. Provide trusted proxies in php code directly (`public/index.php`)

My proposal in regard of this bug: edit original post and add solution and links to docs + close comments on issue with additional warning that it's resolved and solution, explanation and links provided in the end of original post. If I stumbled upon this "bug" from google, then quite possible I'll not be the last one and it's more convenient to see that there is in fact a solution from the start. I missed the fact that bug was closed with a solution and not you asking for root cause on first read-through :sweat_smile: I'm sorry for unnecessary comment.

**Comment by lyrixx** [comment]
Hello @Philosoft 

I'm using the same setup as you (with traffic), And everything works as expected with a fresh (or not) Symfony.
I did not had to modify anything.

I'm using this [wrapper](https://github.com/jolicode/docker-starter) if you want to have a look at it

**Comment by Philosoft** [comment]
@lyrixx I have couple of big questions about approach there (repo stray too far from container(docker)-way in some regards), but that's not important. The reasons why it's working is [here](https://github.com/jolicode/docker-starter/blob/3e47912c79a547a4f73a99015f30e8459c6334ab/infrastructure/docker/services/frontend/etc/nginx/nginx.conf#L49) (`fastcgi_param HTTPS on;` - my option No. 1 from https://github.com/symfony/symfony/issues/37980#issuecomment-739675038 )

**Comment by drupol** [comment]
As complementary information and for what it worth, I had to push this [commit](https://github.com/drupol/cas-bundle-demo/commit/9e27651843f6476642eb1134e0349e2cb31980c8) in order to have the WebProfiler working properly on https://cas-bundle-demo.herokuapp.com/

The WebProfiler is purposely enabled there.

**Comment by tacman** [comment]
I am having the same problem, using the Symfony CLI, Symfony 4.4.18.

If I run symfony server:start --no-tls, it works as expected.

BUT the dev environment works correctly on another machine, with a nearly identical environment.  Otherwise, I get this error:

Access to XMLHttpRequest at 'http://127.0.0.1:8001/_wdt/695d50' from origin 'https://127.0.0.1:8001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by Flower7C3** [comment]
Add following code on the top of your **index.php** file (this one where You invoking `$kernel`):

```
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    $_SERVER['HTTPS'] = 'on';
    $_SERVER['SERVER_PORT'] = 443;
}
```

**Comment by tacman** [comment]
thanks, but that didn't work:

```text
[PHP        ] [Tue Mar  2 10:02:07 2021]
 PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /home/tac/survos/projects/master/public/index.php on line 9
```

**Comment by Flower7C3** [comment]
@tacman so You have different problem.
(I have added to my code `isset` to handle Your error).

**Comment by stof** [comment]
@Flower7C3 please **don't do that**. If your code runs behind a TLS-terminating proxy, you should configure the trusted proxies properly rather than hardcoding a custom handling of `HTTP_X_FORWARDED_PROTO` that does not include the security considerations that we have for the trusted proxies feature (if your web server is accessible without going through your own proxy server setting the `X-Forwarded-Proto` header, your own check on `HTTP_X_FORWARDED_PROTO` allows forging the header).

Btw, `symfony server:start` should be injected the `TRUSTED_PROXIES` env variable automatically to mark its own proxy as trusted, assuming that your project is using this env variable to configure the trusted proxies (which is the case in the default skeleton)

**Comment by michaelKaefer** [comment]
As others already wrote we should configure the trusted proxy in Symfony.

If you use Traefik I think you can trust all incoming requests which is documented [here](https://symfony.com/doc/current/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly):

.env
```env
TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR
```

config/packages/framework.yaml
```yaml
framework:
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
```

**Comment by p-golovin** [comment]
Have the same problem.

Configuration is nginx + php-fpm.

Trusted proxies are configured.
HTTPS headers are ok.

![image](https://user-images.githubusercontent.com/7702213/145592929-57afaf2d-37f6-4646-9da7-80903de7386e.png)

**Comment by back-2-95** [comment]
The solution by @michaelKaefer works for my Traefik 2 + Symfony Docker + Symfony 6 setup. Thank you Sir!

**Comment by BeyerJC** [comment]
The solution does not work for me. My setup is k8s with  php+caddy pod --> traefik (ingressRoute) --> nginx.

I added the trustedProxies with REMOTE_ADDR and tried to also add IP ranges for traefik and nginx. My wdt is still served via http.
Any ideas ?

Edit: My config
My framework.yaml looks like this
```
trusted_proxies: '%env(TRUSTED_PROXIES)%'
trusted_hosts: '%env(TRUSTED_HOSTS)%'
trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
```
and the used values like this
```
trustedHosts: "^127\\.0\\.0\\.1|localhost|.*\\.subdomain\\.mydomain.de$"
trustedProxies:
  - "127.0.0.1"
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"
  - "REMOTE_ADDR"
```

**Comment by back-2-95** [comment]
Dunno what happened but toolbar is again gone 'coz of mixed content.

Traefik 2 + Symfony Docker (inc. Caddy) + Symfony 6.1.7 and I have the framework config as described in https://github.com/symfony/symfony/issues/37980#issuecomment-910034522

**Comment by LauLaman** [comment]
Same problem here with Symfony 6.3 on a dev machine with traefik as a proxy

I fixed it by adding the following code to my `public/index.php` as @Flower7C3  suggested:
```php
if ($_SERVER['APP_ENV'] === 'dev') {
    if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
        $_SERVER['HTTPS'] = 'on';
        $_SERVER['SERVER_PORT'] = 443;
    }
}
```

**Comment by stof** [comment]
have you configured it as a trusted proxy ? If no, that's totally expected that Symfony does not trusted the `X-Forwarded-Proto` header

**Comment by LauLaman** [comment]
@stof yes in my framework.yaml:
```yaml
when@dev:
    framework:
        trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]
```

**Comment by stof** [comment]
this does not mark your traefik IP as a trusted proxy

**Comment by halabuda** [comment]
> As others already wrote we should configure the trusted proxy in Symfony.
> 
> If you use Traefik I think you can trust all incoming requests which is documented [here](https://symfony.com/doc/current/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly):
> 
> .env
> 
> ```dotenv
> TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR
> ```
> 
> config/packages/framework.yaml
> 
> ```yaml
> framework:
>     trusted_proxies: '%env(TRUSTED_PROXIES)%'
> ```

Thanks for this solution, @michaelKaefer. Also resolved my mixed content HTTP/HTTPS warning I was getting with Symfony 6.3.8 and Ngrok 3.4.0 which was preventing the profiler from loading.

**Comment by hubertinio** [comment]
This is my solution for haproxy + nginx + symfony 7.2 (php-fpm) in docker containers

Forward this headers into php container HTTPS + SERVER_PORT

```
/etc/nginx/default.conf

    location ~ \.php$ {
        ...
        fastcgi_param HTTP_HOST $host;
        fastcgi_param HTTPS on;
        fastcgi_param SERVER_PORT 443;
        ...
    }

```

**Comment by stof** [comment]
@hubertinio when using HAProxy, you need to configure it as a trusted proxy.

**Comment by hubertinio** [comment]
@stof  in environtment with many containers IPs are changed, so this is a bit hard update it on symfony side. 
Solution below fix this fast and easy
