### ISSUE TITLE
Use PHP8 attributes to inject tagged services

### ISSUE THREAD

**Issue by zmitic** [symfony/symfony#38314]
**Description**  
Allow simpler autowiring of tagged services by using PHP8 attributes

**Example**  
This is code from real project (removed irrelevant parts):

```php
class CompanyChecker
{
    /** @var iterable<CompanyCheckerInterface> */
    private iterable $checkers;

    /** @param iterable<CompanyCheckerInterface> $checkers  */
    public function __construct(iterable $checkers)
    {
        $this->checkers = $checkers;
   }
}
```

I have lots of classes that implement ``CompanyCheckerInterface`` and via Kernel.php, they get tagged by name of interface; not string like ``app.company_checker`` because they will not be used outside of project:

```php
 // not a real code, I have a loop for this
$container->registerForAutoconfiguration(CompanyCheckerInterface::class)->addTag(CompanyCheckerInterface::class);
```

During compilation, there is code similar to this:

```php
$definition->setArgument(0, new TaggedIteratorArgument(CompanyCheckerInterface::class)); // reused loop
```

---

With PHP8, it would be nicer if we could get autowiring like this:

```php
class CompanyChecker
{
    /** @param iterable<CompanyCheckerInterface> $checkers */
    public function __construct(#[Tagged(CompanyCheckerInterface::class)] iterable $checkers)
    { 
        $this->checkers = $checkers;
   }
}
```

**Comment by nicolas-grekas** [comment]
I would be:-1: here:

1. the indirection that tags privide is a must. `iterable<CompanyCheckerInterface>` references types, not tags, so this doesn't fit this need.

2. `#[Tagged(CompanyCheckerInterface::class)]`: this is DI configuration using annotations. We rejected this in the past because it has the potential to create a lot of confusion. E.g. ppl will expect that this annotation is honored, while someone could decide that the list of checkers is computed/configured externally.

**Comment by zmitic** [comment]
In a perfect world, we would have generics and something like this:

```php
public function __construct(iterable<CompanyCheckerInterface> $checkers)
```

I tried to read types in doc block and it very hard to do (at least for me). So I think attribute would be the least bad way; if there is simpler, I am all for that.

Anyway, thanks for reply.
