### ISSUE TITLE
[Lock] getUniqueToken broke locking

### ISSUE THREAD

**Issue by Punk-UnDeaD** [symfony/symfony#38423]
**Symfony version(s) affected**: 5.1.7

**Description**  
In all external stores exists(Key $key) will return false, because getUniqueToken return different values in different processes.
In one process getUniqueToken will return different values for different lock objects with same id too.

So i don't understand, how i can use non flock locker without custom store.

exists -- https://github.com/symfony/lock/blob/v5.1.7/Store/RedisStore.php#L115
getUniqueToken -- https://github.com/symfony/lock/blob/v5.1.7/Store/RedisStore.php#L147

**Comment by stof** [comment]
Well, `exists($key)` returns whether your key exists in the store. The Key consists of 2 things:

- the resource being locked
- the unique token identifying yourselves among the different processes wanting to lock that resource (a bit more subtile as some stores support serializing the key so that you can hand-over the lock to another process)

`exists($key)` will tell whether *you* already acquired the lock, not whether someone else already did.

**Comment by Punk-UnDeaD** [comment]
@stof when i use flock, i have acquired lock on second process without sharing private $key between process
when i use redis, i have non acquired lock on second process
also i don't understand, i use lock system for communicate between process so why i must share something additionally?

**Comment by stof** [comment]
> when i use flock, i have acquired lock on second process without sharing private $key between process

is the second process on a same server ? If yes, that's because flock is not a shared store and so locks are not preventing concurrency between servers.



> also i don't understand, i use lock system for communicate between process so why i must share something additionally?

Locking is not about communicating between services. It is about preventing concurrency.

The case of sharing the key is precisely for the case where one process will acquire the lock, then pass the key to the other process and that other process will release the lock when done (note that by default, Symfony enables the auto-releasing feature, which must be disabled for that use case). For most cases, that sharing of the key is not needed as you don't distribute the usage of an acquired lock.

> hm, my be i don't understand right all system, but how i can check if lock exist without trying lock create?

you mean, checking if someone else already acquired that lock ? You cannot. That's actually a feature of the component to avoid writing code subject to race conditions (it is not OK to first check whether the lock is free before trying to acquire it, as it might be acquired by someone else in-between).

**Comment by Punk-UnDeaD** [comment]
@stof thanks for you attention, it really not bug, it only my misunderstanding
