### ISSUE TITLE
X-Forwarded-Port is added to targetUrl for auto redirects

### ISSUE THREAD

**Issue by halukakin** [symfony/symfony#38504]
**Symfony version(s) affected**: 4.4

**Description**  
If there is a reverse proxy sending the X-Forwarded-Port then the symfony application add this information as the "httpsport" for the autoredirect feature.

**How to reproduce**  
Have a reverse proxy setting the X-Forwarded-Port 2345 and trigger the autoredirect.  
For instance have a router for "/login" but try to access "/login/".  
Symfony will try to redirect to "https://www.xyz.com:2345/login". 

**Additional context**  
![Screen Shot 2020-10-10 at 12 40 17](https://user-images.githubusercontent.com/22102099/95652505-2d1e6300-0afa-11eb-8301-d631c4f154b0.png)

**Comment by Nyholm** [comment]
I think this is the expected behavior.. isn't it?

> "The X-Forwarded-Port request header helps you identify the destination port that the client used to connect to the load balancer."

Which means that your client sent a request to `example.com:2345/login/`, if Symfony should tell the client to go somewhere else on this server, it should also include the same port (`example.com:2345/login`). 

If Symfony did add that port then the client would use port `2345` in the first request and then `80`(?) in the next, which does not make sense.

**Comment by xabbuh** [comment]
closing as explained by Tobias
