### ISSUE TITLE
[Symfony/Phpunit-bridge] Issue with phpstan

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony#38889]
**Symfony version(s) affected**: 4.4.16

**Description**  
When running
```
php -d memory_limit=-1 ./vendor/bin/phpstan --error-format=checkstyle analyse -l 5 -c phpstan.neon.dist --debug
```

I get the following issue (and [I'm not the only one](https://github.com/getsentry/sentry-symfony/issues/383#issuecomment-717299643))
```
Fatal error: Uncaught OutOfBoundsException: Package "project/project" is not installed in /app/payment/bin/.phpunit/phpunit-9-0/vendor/composer/InstalledVersions.php:451
Stack trace:
#0 /app/payment/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(254): Composer\InstalledVersions::getPrettyVersion('platform/paymen...')
#1 /app/payment/vendor/jean85/pretty-package-versions/src/PrettyVersions.php(13): PackageVersions\Versions::getVersion('platform/paymen...')
#2 /app/payment/vendor/jean85/pretty-package-versions/src/PrettyVersions.php(23): Jean85\PrettyVersions::getVersion('platform/paymen...')
#3 /app/payment/vendor/sentry/sentry-symfony/src/DependencyInjection/Configuration.php(117): Jean85\PrettyVersions::getRootPackageVersion()
#4 /app/payment/vendor/symfony/config/Definition/Processor.php(50): Sentry\SentryBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#5 /app/payment/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Proc in /app/payment/bin/.phpunit/phpunit-9-0/vendor/composer/InstalledVersions.php on line 451
```

I'm using the symfony phpunit bridge. And there is some config to load the 
```
.phpunit/phpunit-9-0/vendor/autoload.php
```
file with phpstan.

I tried to use phpunit/phpunit directly instead of the bridge and there is no errors.

I don't know if this issue is more phpstan related or phpunit-bridge related (or another repository). It's hard to find.
So I also created: https://github.com/phpstan/phpstan/issues/4022

**Comment by ossinkine** [comment]
@VincentLanglet I've also faced this issue. Did you fix it?

**Comment by VincentLanglet** [comment]
> @VincentLanglet I've also faced this issue. Did you fix it?

I fixed it by adding a conflict `composer >= 2` to my `composer.json`. 
Seems like the `.phpunit/vendor/composer` folder was different from the `vendor/composer` one.

Do you think the issue should be re-opened ?
I'm not sure it should be fixed by phpunit bridge.

Maybe by composer ? or sentry/symfony, which use https://github.com/Jean85/pretty-package-versions...

**Comment by Jean85** [comment]
IMHO this should be reopened. `jean85/pretty-package-versions` is only triggering the issue, not causing it, because it's asking for the `InstalledVersions` info; if a different version of Composer is temporarily used, you'll get dependencies and those will assume that the Composer 2 API is present, which may not, if you're still using Composer 1.

Upgrading to Composer 2 will make the issue go away for sure, but if the bridge is using a versions of composer without checking what the user has, that's not good.

**Comment by wouterj** [comment]
The PHPunit bridge uses whatever Composer is installed locally: https://github.com/symfony/symfony/blob/176f52d6308ba2c8a2c08109ecd60f05cf20ba35/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php#L156-L161

I'm not sure what the error is here and how the PhpUnitBridge is involved in all of this. You shouldn't run your static analyser for the `.phpunit` directory (you should analyse only your own code) and there should be no reason for PHPstan to load the PHPunit project build by the PhpUnitBridge afaics.

**Comment by VincentLanglet** [comment]
> I'm not sure what the error is here and how the PhpUnitBridge is involved in all of this. You shouldn't run your static analyser for the `.phpunit` directory (you should analyse only your own code) and there should be no reason for PHPstan to load the PHPunit project build by the PhpUnitBridge afaics.

Since I don't require phpunit (and only the bridge) in my vendors, Phpstan need to load the phpunit directory to not throw an error "class not found" or "function not found" (because methods are not the same depending on the phpunit version).

> The PHPunit bridge uses whatever Composer is installed locally:
> https://github.com/symfony/symfony/blob/176f52d6308ba2c8a2c08109ecd60f05cf20ba35/src/Symfony/Bridge/PhpUnit/bin/simple-phpunit.php#L156-L161

I think the issue is in the order.
- I use composer 1
- I have a dependency https://github.com/composer-unused/composer-unused/blob/main/composer.json, which require `composer` ; so in my vendor composer 2 is installed

phpunit bridge is using the composer in my vendor (version 2) instead of the one I used (version 1).

**Comment by wouterj** [comment]
Hmm, but if I understand that script correctly, it should never use the one from `vendor/`:

1. The first condition checks for `<getcwd()>/composer.phar`
2. The 2nd for a globally installed `composer.phar` that exists in the PATH variable
3. The 3rd for a globally installed `composer` that exists in the PATH variable
4. The 4th for a `composer.phar` in the root of the current git project
5. And otherwise, it defaults to simply `composer`

So the composer 1 you installed should be catched by (2) or (3), and otherwise (5). The vendor dir is never used here (if I'm not mistaken).

Isn't the fact that your having an incompatible version of Composer in your vendor causing the troubles @Jean85 described? (as that library might use classes from the vendor)

**Comment by VincentLanglet** [comment]
I don't know why but I can't reproduce the issue.
Until I find a way to reproduce it back, it will be hard to solve it then ; so I'll close this.
Anyway, there is a way to fix it (updating composer or adding a conflict)

**Comment by ossinkine** [comment]
@VincentLanglet The issue is the following:
`ocramius/proxy-manager` starts using `Composer\InstalledVersions` instead of `PackageVersions\Versions` since 2.9.0 (https://github.com/Ocramius/ProxyManager/pull/619/commits/d0cc213b3c2b5482ed47d3910be7552ebc5de5fe).
Your project contains `Composer\InstalledVersions` in two places: `vendor/composer` and `bin/.phpunit/phpunit-9.4-0/vendor/composer`, so when you add a new autoload file, it override the root `Composer\InstalledVersions` and uses PHPUnit's one, which has no information about requested versions of the root packages and throws an exception.
