### ISSUE TITLE
BinaryFileResponse::getContent() violates the Liskov Substituion Principle

### ISSUE THREAD

**Issue by tflori** [symfony/symfony#39076]
**Symfony version(s) affected**: 4.4, 5.* and probably older versions too

**Description**  
I'm not really sure if that issue raised with an upgrade of the http-foundation package or another package that is now using BinaryFileResponse. But since this upgrade we get in our tests a BinaryFileResponse instead of any other response and we don't get the content of that response anymore.

I came here because this is a clear violation of the Liskov Substitution Principle. Even if it is slower and it should not be done in production: the `Response::getContent` method is clearly defined to retrieve the content of the response. It doesn't do that in that child class.

**Possible Solution**  
Instead of returning false the method should return the content of the file.

**Additional context**  
https://github.com/symfony/http-foundation/blob/5.x/BinaryFileResponse.php#L334
https://en.wikipedia.org/wiki/Liskov_substitution_principle

**Comment by derrabus** [comment]
I'd say, Liskov is fine here. The return value is documented on the parent class.

https://github.com/symfony/http-foundation/blob/889007ae02c95bd377fd0e30440ad74122638f59/Response.php#L417

We have response classes that don't buffer and store their content but produce it when being sent. This applies to `BinaryFileResponse`, but also to `StreamedResponse`.

Can you elaborate what exact problem you're trying to solve?

**Comment by tflori** [comment]
I'm fine with a false response when we don't have content. Statuscode 204 suggest that. In all other cases (then also in StreamedResponse) it should return the content.

The substitution principle does not say: as long as you define it it the parent that it might be different in a child then it is ok. The reason for this principle is that I can exchange the Response with a specific Response that extends that Response and still get the same result. But obviously I can't: Because when I change the Response to a BinaryFileResponse I don't get the content anymore.

**Comment by derrabus** [comment]
> I'm fine with a false response when we don't have content.

All right: `BinaryFileResponse` and `StreamedResponse` never have content because it either hasn't been produced yet or has been streamed to the client already. A `Response` instance may but does not have to store the content that should be or has been sent to the client. If the doc block deserves some clarification on that contract, a PR is certainly welcome.

As much as I appreciate discussing design principles with you, I need to ask you again: Can you elaborate what exact problem you're trying to solve?

**Comment by tflori** [comment]
I have solved my problem already. But I thought better about symfony. In my concrete example one library changed the result to a BinaryFileResponse and a test if that contains the expected data failed.

The thing is that outside of your classes I should not know how to get the content. Of course there might be exceptions but the default should be to try at least to get the content.

And no: it is not that hard to get the content of that file and we can still send the content.

**Comment by derrabus** [comment]
I understand why this is confusing and maybe it would have been the better design to create an `AbstractResponse` without a `getContent()` method. But here we are now.

Anyhow, since responses don't always store their content, the only reliable way to retrieve it would be calling `sendContent()` with output buffering enabled.
