### ISSUE TITLE
TranslatableMessage not extracted

### ISSUE THREAD

**Issue by rmdefi** [symfony/symfony#39126]
**Symfony version(s) affected**: 5.2.0-RC1

**Description**  
The class TranslatableMessage (and the shorthand t() function), introduced in symfony 5.2, allows to provide translatable messages without needing the translator service.
The PhpExtractor from the translation component does extract them.
However, the translation:update (and debug:translation) command only extract from services which have the translator service injected.

**Possible Solution**  
The only solution I can think of would be to have the extraction parse all the PHP sources, but maybe as an option not enabled by default?

**Comment by rmdefi** [comment]
I found a workaround.
I added a compiler pass that is executed after TranslatorPathsPass and replace the $viewPaths arguments with my src directory.
That way, the extractors will recursivelly scan all PHP files in my src directory.
Good enough for my use case.

**Comment by stof** [comment]
hmm, given that the extractor is now able to extract from services, I think we should change the wiring of the commands so that they are not limited to PHP templates anymore.
what do you think @Nyholm ?

**Comment by Nyholm** [comment]
Yeah. That makes sense

**Comment by yceruto** [comment]
In fact, the commands are not related to PHP templates only. It works currently with non-removed services wiring the Translator services.

It's hard to detect all PHP files that require trans extraction, and some of them aren't services at the end. That's why I think we should pass this resposibility to the user through a new option in related commands to append specific directories or files where to extract.

For example:
```
bin/console translation:update en --extra-path=src/Controller --extra-path=src/Form
```
This would reduce the number of files to be parsed.

For the record: this PR https://github.com/symfony/symfony/pull/40229 was open to add the whole `src/`.
