### ISSUE TITLE
Profiler - Debug Doctrine queries with binary UUIDs

### ISSUE THREAD

**Issue by bigfoot90** [symfony/symfony#39144]
**Description**  
Not sure this is the right place.
I'm using UUIDs with a custom Doctrine Type mapping to `BINARY(16)` in MariaDB database. (All is working fine)

The throuble is when I go into the profiler to debug the queries.
**Actually** I see a strange binary string
![image](https://user-images.githubusercontent.com/4598274/99958663-140c0180-2d8a-11eb-8461-8ca7725785bf.png)

**Expected** would be a readable binary string like this
![image](https://user-images.githubusercontent.com/4598274/99958901-706f2100-2d8a-11eb-8c7c-42f94a623e14.png)

**Note** Doctrine already does this conversion automatically *(see the runnable query)*

**Comment by stof** [comment]
Well, `0x...` is not a string representation in PHP, but a number representation. So I don't find it unexpected that VarDumper does not automatically performs that conversion when dumping the value.
for the runnable query, that's outputting SQL and so the SQL rules apply (where `0x...` is a string format)

**Comment by bigfoot90** [comment]
In the SQL this is not a string parameter, so why the profiler prints it as a string?

**Comment by stof** [comment]
A binary string is a string

**Comment by jderusse** [comment]
I tried to fix the issue to provides a consistent representation of the parameter, then I realized that were not the right fix.

The issue is: Doctrine (in runnable query) and the VarDump (in parameters) does not use the same representation for the same thing (binary data).

* Doctrine converts the binary into Hex representation.
* VarDumper converts the binary in UTF-8

Both have benefits and drabacks. 

IMHO, it's fine to have the `b"..."` representation from the VarDumper, given we also ave different representation (resources, nested array, ...) 
We have a "real" representation of the value here, end people can show the `runnable query` to show the real value in q SQ context.

**Comment by nicolas-grekas** [comment]
Closing as explained. If someone figures out a way to improve the display, please submit a PR of course.

**Comment by kdambekalns** [comment]
> people can show the runnable query to show the real value

Probably just me, but using Shopware 6.4 and trying to debug a nasty error all I get is this:

<img width="1063" alt="Screenshot 2023-03-10 at 11 21 19" src="https://user-images.githubusercontent.com/95873/224291273-326cd355-2de4-4815-a176-673f4a39bcfe.png">

Makes trying to find the reason for foreign key constraint errors impossible, if all your ids are just "empty" (and no, there is data, I can see that in the application logs – but not for all the queries…)

**Comment by ghost** [comment]
I have a similar issue* where Doctrine log messages show UUID's as binary strings, which makes it harder to debug queries.

I created a custom Monolog processor which detects and converts binary string parameters into hex and adds them as `extra` information to the log message. This makes it easier to debug queries, since you can now copy/paste UUIDs into your DBMS query tool. The binary string detection isn't foolproof, as per the [discussion on Stack Overflow](https://stackoverflow.com/questions/25343508/detect-if-string-is-binary).

Copy this code into `src\Logger\DoctrineParameterProcessor.php` and auto-wiring will handle the rest:

```php
<?php

namespace App\Logger;

use Monolog\LogRecord;
use Monolog\Attribute\AsMonologProcessor;
use Monolog\Processor\ProcessorInterface;
use Doctrine\DBAL\ParameterType;

#[AsMonologProcessor(channel: 'doctrine')]
class DoctrineParameterProcessor implements ProcessorInterface
{
    public function __invoke(LogRecord $record): LogRecord
    {
        if (empty($record->context['params']) || empty($record->context['types'])) {
            return $record;
        }

        // Detect and convert binary strings to hex and store as an extra param
        foreach($record->context['params'] as $key => $value) {
            if ($record->context['types'][$key] == ParameterType::STRING && !mb_check_encoding($value, 'UTF-8')) {
                $record->extra['params'][$key] = bin2hex($value);
            }
        }

        return $record;
    }
}
```

---
*The issue is that when parameters are being bound[1][2][3], the UUID type's toBinary() method is called to convert[4] the parameter into a binary string. By the time the log debug method is called[5], the UUID parameter is just another string parameter.

[1] https://github.com/doctrine/dbal/blob/2fe737f19309b4b0aac886935e8af6d1f9123b26/src/Connection.php#L768
[2] https://github.com/doctrine/dbal/blob/2fe737f19309b4b0aac886935e8af6d1f9123b26/src/Connection.php#L1236
[3] https://github.com/doctrine/dbal/blob/2fe737f19309b4b0aac886935e8af6d1f9123b26/src/Connection.php#L1277
[4] https://github.com/symfony/doctrine-bridge/blob/9fc4bebf69f00d4ebb12ee904d808b496035e2f6/Types/AbstractUidType.php#L65
[5] https://github.com/doctrine/dbal/blob/2fe737f19309b4b0aac886935e8af6d1f9123b26/src/Logging/Statement.php#L40
