### ISSUE TITLE
Service has a dependency on a non-existent service on Windows 10, works well on Ubuntu 20.04 and macOS.

### ISSUE THREAD

**Issue by hoffic-cz** [symfony/symfony#39172]
**Symfony version(s) affected**: 4.4.16

**Description**  
A symfony application inside an alpine docker container fails when running on windows 10. On Ubuntu 20.04 and macOS it works flawlessly. This is the error:
The service "sonata.admin.object.manipulator.acl.admin" has a dependency on a non-existent service "form.factory".

**How to reproduce**  
- Use Windows 10 with Docker and Docker Compose
- Download or clone the code from https://gitlab.com/uni.hoffic.cz/csp400/web-system/-/tree/BUG-1
- `docker-compose up -d`
- `docker-compose exec app composer install`
- Observe the error during script cache:clear

**Possible Solution**  

**Additional context**

**Comment by jderusse** [comment]
Well, since you use Docker (based on alpine) it's not really an bug on Windows.
And you have a composer .lock, it's not an issue with dependency resolution and potential missing extension.

I guess the issue is related to volume mount and potential cache/permission in filesystem between Windows and Docker.

**Comment by letrunghieu** [comment]
I reproduced the issue in Windows 10 with Docker on WSL2. The problem here seems to belong to the file synchronization when mounting a folder on the Windows 10 file system to Docker.

* If the project source code is cloned to the Windows file system, we have the issue as @hoffic-cz described.
* If the project source code is cloned to the WSL2 file system, there are no issues.

For details, the form component is enabled in this line: https://github.com/symfony/framework-bundle/blob/v4.4.16/DependencyInjection/Configuration.php#L164

You can check the content of the `vendor\symfony\form` folder in the Windows file system and compare it to what is here: https://github.com/symfony/symfony/tree/v4.4.16/src/Symfony/Component/Form. On my computer, the `Form.php` file is missing, which causes the form component to be disabled in the framework bundle extension.

In the end, this is not a Symfony bug to me.

**Comment by xabbuh** [comment]
Let's close here then.

**Comment by radli** [comment]
I think that this is an error. Because I reproduce it too. Also windows 11 and docker. There are files in the container, everything is there, but for some reason the "Service has a dependency on a non-existent service"
I had to explicitly specify this in the file config/services.yaml:
```
    App\Service\:
        resource: '../src/Service/*'
```

only after that it worked
