### ISSUE TITLE
Second invocation of cache:clear removes cache folders created with first invocation

### ISSUE THREAD

**Issue by bobvandevijver** [symfony/symfony#39232]
**Symfony version(s) affected**: 5.2.0

**Description**  

A second invocation of `bin/console cache:clear` removes directories from the cache directory that have been created by the first invocation. For certain vendors (such as [JMS Serializer](https://github.com/schmittjoh/JMSSerializerBundle) and [Vich Uploader](https://github.com/dustin10/VichUploaderBundle)), this results in a full application breakdown, as they require the directory to exist.

This also means that a third invocation of the `cache:clear` results in an exception for my application, as the JMS serializer checks for the directory existence during container startup. 

The files I'm "missing" after the second invocation are:

- `annotation.php`
- `App_KernelDevDebugContainer.xml`
- `App_KernelDevDebugContainer.xml.meta`
- `doctrine`
- `jms_serializer`
- `pools`
- `serialization.php`
- `translations`
- `twig`
- `validation.php`
- `vich_uploader`
- `webpack_encore.cache.php`

**How to reproduce**  
You should be able to investigate the behavior with a standard Symfony installation with Twig, as that is also one of the removed folders. However, it won't throw an error in that scenario, as Twig just recreates the required folders.

It looks like the second invocation doesn't execute the warmup stage, but running the `cache:warmup` command doesn't help here due to the vendor missing the required folder.

**Possible Solution**  

I'm not sure whether this is something that is broken within Symfony, or that the vendors should be making adjustments to be more robust for missing cache folders/missing warmup. However, IMO this is a massive difference between 5.1 and 5.2, so I believe that if this was intentional, it should be postponed to 6.0.

**Comment by dmaicher** [comment]
I tracked this down to `symfony/http-kernel`. If I leave all other symfony packages at `5.1.9` and **only** upgrade `symfony/http-kernel` to `5.2.0` on `symfony/demo` then I get this issue.

So it must be something in this changeset causing it? https://github.com/symfony/http-kernel/compare/v5.1.9..v5.2.0

Edit:

@mnapoli it seems this changed line is causing it: https://github.com/symfony/symfony/pull/36515/files#diff-842527ea5582808ca82ff360aa1f7ceaa44584c9c4b4edd6c27381f62d834d3cL600

If I restore `kernel.cache_dir` to be `realpath($cacheDir = $this->warmupDir ?: $this->getCacheDir()) ?: $cacheDir` then for me the issue disappears. 

Any idea?

**Comment by alongosz** [comment]
Hi. I can confirm this issue affects us as well and prevents [Ibexa DXP from upgrading to Symfony 5.2](https://github.com/ezsystems/ezplatform/pull/624) because of [GraphQLBundle](https://github.com/overblog/GraphQLBundle) which generates some files in `var/cache/<env>/overblog/graphql-bundle/__definitions_` directory during cache warmup. After the warmup, files get deleted though (not sure when exactly). Restoring `kernel.cache_dir` as described in the previous comment resolved the issue.

**Comment by fd6130** [comment]
So can we use 5.2 for new project (well i'm already start using it in a fresh new project)? I hope this "cache folders" issue won't affect the whole new project either in `dev` or `prod`.

**Comment by bobvandevijver** [comment]
@fd6130 It depends on your dependencies, and their handling of the missing files/folders in the cache. But, there are some workaround available as described in the linked issues.

**Comment by jderusse** [comment]
I looked into the issue but did not find how to fix that properly:

We have 3 issues:
- the command is not idempotent
- output of cache warmer is lost
- application broken because file are missing

1. The command is not idempotent

Whether or not a previous cache is here, the command does not provides the same output.
This is because of https://github.com/symfony/symfony/blob/9d40bd80f609fba8a329d22df20226fbf908ba14/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L124 and because of the 2nd issue.

2. Output of cache warmer is lost:

We now have 2 parameters:
- kernel.build_dir: can be persisted on read-only disk
- kernel.cache_dir: files generated at runtime

The first parameter should be used to store files generated by cache warmers. 
But it appears, that many cache warmers relies on the second parameter and thus fill the wrong folder when running the `cache:clear` command.
Ie: the translator component that use the injected parameter https://github.com/symfony/symfony/blob/9d40bd80f609fba8a329d22df20226fbf908ba14/src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php#L93 instead of the file provided by the warmer

Because of this issue, the CacheWarmer is useless. Here are the files currently impacted by this in the "demo" application
```
var/cache/dev/annotations.php
var/cache/dev/validation.php
var/cache/dev/webpack_encore.cache.php
var/cache/dev/App_KernelDevDebugContainer.xml
var/cache/dev/App_KernelDevDebugContainer.xml.meta

var/cache/dev/pools/*
var/cache/dev/twig/*
var/cache/dev/translations/*
```

3. application broken because file are missing

IMHO this is a bug in the 3rd party bundle. Code should be resilient and handle case where cache does not exists.

**Comment by tristanbes** [comment]
@jderusse except symfony itself is impacted, it's not only a matter of 3rd party bundle (I guess ?), you can check out my issue where the container `App_KernelDevDebugContainer.xml` is no longer dumped after the second invocation of `cache:clear` https://github.com/symfony/symfony/issues/39240

**Comment by bobvandevijver** [comment]
@jderusse Awesome work, I just verified your fix, and it does indeed fix  it 👍
