### ISSUE TITLE
The parameter "kernel.build_dir" must be defined.

### ISSUE THREAD

**Issue by arcticlinux** [symfony/symfony#39250]
Everything looks to be configured, I can't figure out what is different on my production environment that makes it throw this error, if I change APP_ENV to prod on my dev server it works fine too.

After updating to 5.2 and testing in dev, running cache:clear on prod throws the following error:

```
Script cache:clear returned with error code 1
!!  09:56:01 ERROR     [console] Error thrown while running command "--ansi cache:clear". Message: "The parameter "kernel.build_dir" must be defined." ["exception" => Symfony\Component\DependencyInjection\Exception\InvalidArgumentException^ { …},"command" => "--ansi cache:clear","message" => "The parameter "kernel.build_dir" must be defined."]
!!  
!!  In App_KernelProdContainer.php line 885:
!!                                                       
!!    The parameter "kernel.build_dir" must be defined.  
!!                                                       
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!  
!!  
```

```
console debug:container --parameter=kernel.build_dir

 ------------------ ------------------------------------- 
  Parameter          Value                                
 ------------------ ------------------------------------- 
  kernel.build_dir   /var/www/example.com/var/cache/prod  
 ------------------ ------------------------------------- 
```

**Comment by mynameisbogdan** [comment]
Same here. I had to remove `var/cache/prod` and then run `bin/console cache:clear`.

**Comment by arcticlinux** [comment]
> Same here. I had to remove `var/cache/prod` and then run `bin/console cache:clear`.

That's interesting, I did a quick grep of the cache contents of the old cache and new one and the old one doesn't contain a value for the kernel.build_dir but the new one does:

grep build_dir var/cache/prod -r
```
var/cache/prod/ContainerIjY28Eg/App_KernelProdContainer.php:        'kernel.build_dir' => false,
var/cache/prod/ContainerIjY28Eg/App_KernelProdContainer.php:            case 'kernel.build_dir': $value = $this->targetDir.''; break;
```

**Comment by mbabker** [comment]
It's a new parameter in Symfony 5.2 from https://github.com/symfony/symfony/pull/36515

**Comment by iquito** [comment]
I ran into this issue too - some parts of my application just started failing because the cache could not be cleared. From my perspective, there should be a way to upgrade to a new Symfony version and then be able to clear the cache, without having to completely remove the cache directory manually, as this is error-prone. If the new Symfony version is completely incompatible with the "old" cache, it should just not use the existing cache. This chicken-and-egg problem with clearing the cache with an "invalid cache" has happened to me many times, and each time it was frustrating and seemed unnecessary.

In this specific case, Symfony could have made kernel.build_dir optional instead of mandatory, and the default would have been kernel.build_dir = false. But if it needed to be mandatory, then just not use the cache of an old Symfony version, as this is guaranteed to break each time, and it will always affect people where they expect it the least.
