### ISSUE TITLE
Problem with route attributes

### ISSUE THREAD

**Issue by jasiolpn** [symfony/symfony#39294]
**Symfony version(s) affected**: 5.2.0

**Description**  
Hi
I've installed a clear symfony skeleton project. I want to test routes via PHP 8 attributes. I've made new controller with public method like always. Snippet:

```php
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Service\Attribute\Required;

//.....

#[Route('/', name: 'index')]
public function testAction()
{
}

#[Required]
public function req()
{
    dump(123);
}
```
But **symfony console debug:router** gives 

```
 -------------------------- -------- -------- ------ ----------------------------------- 
  Name                       Method   Scheme   Host   Path                               
 -------------------------- -------- -------- ------ ----------------------------------- 
  _preview_error             ANY      ANY      ANY    /_error/{code}.{_format}           
  _wdt                       ANY      ANY      ANY    /_wdt/{token}                      
  _profiler_home             ANY      ANY      ANY    /_profiler/                        
  _profiler_search           ANY      ANY      ANY    /_profiler/search                  
  _profiler_search_bar       ANY      ANY      ANY    /_profiler/search_bar              
  _profiler_phpinfo          ANY      ANY      ANY    /_profiler/phpinfo                 
  _profiler_search_results   ANY      ANY      ANY    /_profiler/{token}/search/results  
  _profiler_open_file        ANY      ANY      ANY    /_profiler/open                    
  _profiler                  ANY      ANY      ANY    /_profiler/{token}                 
  _profiler_router           ANY      ANY      ANY    /_profiler/{token}/router          
  _profiler_exception        ANY      ANY      ANY    /_profiler/{token}/exception       
  _profiler_exception_css    ANY      ANY      ANY    /_profiler/{token}/exception.css   
 -------------------------- -------- -------- ------ ----------------------------------- 
```

Solution is to install **doctrine/annotations** but the Symfony docs tells us this dependency is not required.

>Your application is now using native PHP attributes and you can uninstall dependencies like doctrine/annotations if you don’t use them elsewhere

**Comment by derrabus** [comment]
Does it work if you create a `config/routes/annotations.yaml` file with this content?

https://github.com/symfony/recipes/blob/12765b0a1d67937dda8b54e4210096808d51c2b3/doctrine/annotations/1.0/config/routes/annotations.yaml#L1-L7

**Comment by jasiolpn** [comment]
I have tried this but it doesn't work. 

EDIT:
Sorry it works but I had to clear cache. Also if I remove #[Required] attribute from other method Symfony still executes it until I remove cache

**Comment by derrabus** [comment]
Can you provide a reproducer, please?

**Comment by jasiolpn** [comment]
Ok the situation is very strange.
I created ``config/routes/annotations.yaml`` file then I cleared cache and it worked. But then I removed that file and opened project in browser and then restored file. Now the console output is

```
 -------------------------- -------- -------- ------ ----------------------------------- 
  Name                       Method   Scheme   Host   Path                               
 -------------------------- -------- -------- ------ ----------------------------------- 
  _preview_error             ANY      ANY      ANY    /_error/{code}.{_format}           
  _wdt                       ANY      ANY      ANY    /_wdt/{token}                      
  _profiler_home             ANY      ANY      ANY    /_profiler/                        
  _profiler_search           ANY      ANY      ANY    /_profiler/search                  
  _profiler_search_bar       ANY      ANY      ANY    /_profiler/search_bar              
  _profiler_phpinfo          ANY      ANY      ANY    /_profiler/phpinfo                 
  _profiler_search_results   ANY      ANY      ANY    /_profiler/{token}/search/results  
  _profiler_open_file        ANY      ANY      ANY    /_profiler/open                    
  _profiler                  ANY      ANY      ANY    /_profiler/{token}                 
  _profiler_router           ANY      ANY      ANY    /_profiler/{token}/router          
  _profiler_exception        ANY      ANY      ANY    /_profiler/{token}/exception       
  _profiler_exception_css    ANY      ANY      ANY    /_profiler/{token}/exception.css   
  index                      ANY      ANY      ANY    /                                  
 -------------------------- -------- -------- ------ ----------------------------------- 
```

But I've got ``No route found`` exception

![image](https://user-images.githubusercontent.com/5113866/100946401-8952a180-3503-11eb-9d46-008d369ecb49.png)

**Comment by derrabus** [comment]
When adding/removing config files, make sure you clear the cache.

Okay, so if you add that file, attribute-based routing works. That's expected behavior so far. We then need to update the recipes to make this a bit easier without Doctrine Annotations. If you want, you can open an issue for that on the recipes repository: https://github.com/symfony/recipes/issues

Thank you for your report.

**Comment by jasiolpn** [comment]
The reproducer code is very simple. It is only clear skeleton project with ``debug`` bundle and one simple controller:

```php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Service\Attribute\Required;

class AttrRoutesTestController
{
    #[Route('/', name: 'index')]
    public function testAction()
    {
    }

    #[Required]
    public function req()
    {
        dump(123);
    }
}

```
I've compiled PHP 8 myself if it has any meanig

**Comment by TheNewHEROBRINEX** [comment]
For me creating config/routes/annotations.yaml makes the route appear in debug:router but it would still not be found if accessed without having annotations installed.

**Comment by kamilwylegala** [comment]
Can I find somewhere in documentation how to setup attributes for routing? I use yaml configuration in my project and wanted to switch to PHP8' attributes. I found helpful information only here. If there is no documentation available where should I contribute?

Thanks!

**Comment by ssi-anik** [comment]
Two days ago I started reading the routing doc and I couldn't find this "cache related issue" point there. And obviously, after two days I get to find this issue after debugging the whole codebase why it's not working. Can anyone please update the doc or point us somewhere so that we can contribute too?

**Comment by sanderlissenburg** [comment]
> For me creating config/routes/annotations.yaml makes the route appear in debug:router but it would still not be found if accessed without having annotations installed.

I got it working without requiring the doctrine/annotations package but I had to add (for example) the following to `config/routes/annotations.yaml` even though I'm using attributes.

```yaml
controllers:
  resource: ../../src/Controller/
  type: annotation

```

**Comment by fabriziofs** [comment]
> > For me creating config/routes/annotations.yaml makes the route appear in debug:router but it would still not be found if accessed without having annotations installed.
> 
> I got it working without requiring the doctrine/annotations package but I had to add (for example) the following to `config/routes/annotations.yaml` even though I'm using attributes.
> 
> ```yaml
> controllers:
>   resource: ../../src/Controller/
>   type: annotation
> ```

With a fresh project with Symfony 5.3.12 and PHP PHP 8.0.13 adding `config/routes/annotations.yaml` with the content you mention fix the problema with the attributes routes. Thanks! (After cache clear)

**Comment by webdevilopers** [comment]
> Okay, so if you add that file, attribute-based routing works. That's expected behavior so far. We then need to update the recipes to make this a bit easier without Doctrine Annotations. If you want, you can open an issue for that on the recipes repository: https://github.com/symfony/recipes/issues
> 
> Thank you for your report.

Was an issue related to the recipe opened? I still had to add the file manually when installing a fresh symfony **6.0.2** skeleton.

These seem related:

* https://github.com/symfony/recipes/issues/1030
* https://github.com/symfony/recipes/issues/1034

**Comment by AkashicSeer** [comment]
Isn't everyone glad there isn't anything in the relevant sections of the docs mentioning this. It just suggests you use annotations has a link about it and never mentions you must install some other package. I mean even right here in the docs [https://symfony.com/doc/current/routing.html#creating-routes](url) it tells you how to configure annotations with the annotations.yaml file but fails to mention you must install a loader. WTF? I have complained about the docs for years. It makes no sense why you would leave pertinent information out of the documentation constantly like it is on purpose.  Let me dig through this post and find the magic little tidbit of information WE ALL NEED in order to make this actually work. FFS

**Comment by AkashicSeer** [comment]
I decided to finally try attributes. So I tried starting a new project with symfony 6.1.* like the docs show. EPIC FAIL Nothing would work at all something about a Datetime something or other. So I tried the symfony command to use the lts version. EPIC FAIL AGAIN. Something about 127.0.0.1:53:53 couldn't be found or something. So I created an app with version 5.4. Amazement occurred as it finally worked. So now I think, hey lets try this attributes thing that has been around for a while now. EPIC FAIL AGAIN. I thought OK let me follow the docs line by line.  So I created  the attributes.yaml file with the proper settings, cleared the cache and reloaded the browser to find this beautiful Scene on the Screen. So I am guessing the whole idea of using attributes was just an idea ? Really frustrating honestly.
![symfony-attributes-fail](https://user-images.githubusercontent.com/45157506/197689980-f83e8de4-674d-40f3-b595-579b33670b31.png)

**Comment by AkashicSeer** [comment]
Anyone have any ideas on how to actually get Attributes working? I tried what the docs show with the attributes.yaml file and clearing the cache. I used 5.4 to create a skeleton project because 6.1 is a pile of barf that isn't working. I get this non helpful error screen. 
![symfony-attributes-fail](https://user-images.githubusercontent.com/45157506/197690636-4bbdda4e-04c2-4e9a-a75c-93204a523df5.png)

Anyone know if there is a attributes loader? There is nothing about it in the docs on the loader page. WTF? Why not put pertinent info like this directly in the docs where people who need it can read it? I mean is there any good reason this is still not in the dosc after this long? Do they just like to hear people complain? I guess I'll just go back to annotations until someone decides to share with us how to get this working. If you are not going to give the proper info, then remove the bullshit from the docs.
