### ISSUE TITLE
Entity type-hinting error before validation

### ISSUE THREAD

**Issue by SylvanoTombo** [symfony/symfony#39309]
Hi guys! I'm facing an issue today about form and i would like to have your point about the subject, I know the submit function triggered before and after the validator listener is called but what if my type-hiting in my setters of my entity is strict?
Imaging i have a an entity like below:

```
<?php

namespace App\Entity;

class Posts {

  /**   
  * @Assert\NotNull(groups={"sylius"})
  **/  
   private $name;

   public function getName(): string
   {
     return $this->name;
   }
   public function setName(string $name)
   {
       $this->name = $name;
   }
}
```

When Symfony map the data to the entity php rise an error like this `Expected argument of type string but null given` and the code doesn't reach the validation listener.

I tried to add into` ProductType` a `CollectionType` for `ProductVariantType` but when i created a  product and leave empty the pricing, it rise an error before reaching the validation.The error is below

![Screenshot from 2020-12-04 15-18-04](https://user-images.githubusercontent.com/40351002/101158058-8b704980-3644-11eb-8397-71bf9063d959.png)

**Comment by julienfalque** [comment]
This is because the form hydrates your underlying object **before** validating it. It will try to write `null` for empty fields, which is not accepted by the `string` type declaration in your setter. A simple fix would be to drop the type declaration but IMHO a much better solution is to use a DTO object (accepting e.g. `string|null`) with the form component instead of trying to update your entity directly, this would allow to keep strict constraints in your entity.

**Comment by SylvanoTombo** [comment]
@julienfalque , Thanks..
