### ISSUE TITLE
Console: Declarations incompatible

### ISSUE THREAD

**Issue by TiSiE** [symfony/symfony#39368]
**Symfony version(s) affected**: 5.2.0

**Description**  
PHP Fatal error:  Declaration of Symfony\Component\Console\Style\OutputStyle::write($messages, bool $newline = false, int $type = self::OUTPUT_NORMAL) must be compatible with Symfony\Component\Console\Output\OutputInterface::write($messages, $newline = false, $options = 0) 

**How to reproduce**  
Install symfony/console ^5.0 with composer and try to use the `write` method.

**Additional context**  
PHP version 7.4.12

I have found the similar issues regarding this declaration errors. They all state that the composer must be run with the dame PHP version as the application. But in my case the console component is used with a composer plugin _in the same run_ as the dependency install/updates - so it is always the same PHP version!

**Comment by stof** [comment]
the issue in a composer plugin is that your plugin runs as part of the composer process, which uses symfony/console 2.8.
Here, you probably have `Symfony\Component\Console\Style\OutputStyle` loaded from your vendor directory at 5.2.0 (because there is no such class in symfony/console 2.8) while `Symfony\Component\Console\Output\OutputInterface` is the one from the composer phar (at 2.8.x).
that's not a bug in Symfony, but a limitation of the composer plugin system (by design, they must run in the composer process and so are subject to the composer dependencies).

**Comment by TiSiE** [comment]
Thank you very much for this information. 

Now I can try to work around this.
