### ISSUE TITLE
HttpException's $statusCode and $message should be inverted

### ISSUE THREAD

**Issue by Leemonn** [symfony/symfony#39780]
**Symfony version(s) affected**: 5.2.1

**Description**  
The Exception base class uses 
`__construct ( string $message = "" , int $code = 0...`
Symfony's HttpException uses
`__construct ( int $statusCode, string $message = null...`

While I know that this change might break a lot (if not all) systems using symfony, I was wondering if this implementation was intentional.

Thanks in advance.

Edit: This is a possible problem and not a bug, I can't change the labels.

**Comment by derrabus** [comment]
This is intentional. The `$code` on PHP's `Exception` is an internal code that is meant for categorizing errors. This not the same as a HTTP status code and must not be used as such. In fact, `HttpException` has an optional `int $code` parameter as well.

When throwing an HTTP exception, the status code is a mandatory parameter whereas the message is optional. This is why the status has to be the first parameter.

Closing as this is not a bug.
