### ISSUE TITLE
RegisterEntryPointPass points to already resolved alias

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#39881]
**Symfony version(s) affected**: 5.2

**Description**  

The reference that is created here:
https://github.com/symfony/symfony/blob/294195157c3690b869ff6295713a69ff38b3039c/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/RegisterEntryPointPass.php#L74

can point to an alias, eg.:
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/f6c0d9a2816b52e759ed1ba0658b45786b58fdf7/Resources/config/token_authenticator.xml#L8

When this happens, and because `RegisterEntryPointPass` is registered "before-removing", the reference points to a private alias, which is going to be removed by another pass.

Because `RegisterEntryPointPass` runs as a "before-removing", thus after `ResolveReferencesToAliasesPass`, it should point to the resolved service id instead.

What I don't know is if this resolving logic should be implemented in `RegisterEntryPointPass`, or if the reference should *not* be created at all. I'm wondering this because in my case, the argument replaced by the pass already *is* the correct resolved reference.

/cc @wouterj maybe you know how to fix this best?

**Comment by wouterj** [comment]
Can you confirm that you've explicitly configured the `entry_point` for this firewall/guard? If that's the case, the argument is indeed already correctly set. The compiler pass is setting the entry point automatically based on the configured authenticators IIRC.

I can't recall if their is a specific reason to not make this pass "before-optimalization". Maybe it can be solved by just removing the bad position. (I often put a comment if there is a specific choice for a different position)

**Comment by fabpot** [comment]
I confirm (I'm the one with the bug) that the entry_point is configured explicitly.

**Comment by wouterj** [comment]
https://github.com/symfony/symfony/blob/294195157c3690b869ff6295713a69ff38b3039c/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Compiler/RegisterEntryPointPass.php#L57-L61

We should `continue` here if `$configuredEntryPoint` is set and not an authenticator key (it's then set to a service/alias ID).

---

However that doesn't fix the real bug here (it's still broken if you rely on the default behavior). We should resolve the alias in that case. I'm unsure how to fix it, as we need it to run "before removing" (we need child definitions to be resolved, as `$definition->getClass()` must return the FQCN). Possible things I can imagine:

* Make `ResolveReferencesToAliasesPass::getDefinitionId()` public and static, so we can reuse its logic in `RegisterEntryPointPass`
* Add a priority to `ResolveReferencesToAliasesPass` in `PassConfig` (and make sure it's different than `ResolveChildDefinitionsPass`), so we can position `RegisterEntryPointPass` in between those passes.

Do you have any favor of the solution (or know a better solution)?

**Comment by nicolas-grekas** [comment]
Can't we resolve the class in the pass? We already have some passes that do so when they need access to the class.

**Comment by wouterj** [comment]
I wasn't aware of that. Yes, that's probably also possible.
