### ISSUE TITLE
[Finder] BC: Manuelly added files are missing 

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#40022]
**Symfony version(s) affected**: 4.4.19

**Description**  
Finder lists only one manuelly added file

**How to reproduce**  
```php
$finder = new Finder();
        $finder
            ->sortByName()
            ->files()
            ->followLinks()
            ->name('*.php');

        $finder->append([__DIR__ . '/Context.php']);
        $finder->append([__DIR__ . '/Logger.phpp']);
        $finder->append([__DIR__ . '/Serializer.php']);

        foreach ($finder as $item) {
            var_dump($item->getPathname());
        }
 ````

Output: v4.4.19:
string(59) "/var/www/html/vendor/zircote/swagger-php/src/Serializer.php"

Output: v4.4.18
string(56) "/var/www/html/vendor/zircote/swagger-php/src/Context.php"
string(56) "/var/www/html/vendor/zircote/swagger-php/src/Logger.phpp"
string(59) "/var/www/html/vendor/zircote/swagger-php/src/Serializer.php"

        

**Possible Solution**  
Revert https://github.com/symfony/finder/commit/94a9b864774d7d20635607c975e3d92a7d3b1ba9

**Additional context**

**Comment by stof** [comment]
your reproducer is likely incomplete as `$directory` is not defined in it

**Comment by shyim** [comment]
Ahh That line is not needed sorry :) Just point to some files. And you will get only one

**Comment by stof** [comment]
I think I understood the issue. `SortableIterator` uses `iterator_to_array($iterator, preserve_keys: true)`. The effect of that is that it removes duplicate keys in the iterator (as arrays don't support duplicate keys).

This is not really an issue for cases providing a directory, because the full path is used as keys in such iterators. But when using `->append()` with an array, the Finder component will uses incremented keys for that array only, and so using `append` multiple times will generate duplicate keys in the final iterator. The Finder should probably also build iterators using the path as key for such case instead of using integers.

**Comment by xabbuh** [comment]
see #40023
