### ISSUE TITLE
E_WARNING:  Zend OPcache could not compile file

### ISSUE THREAD

**Issue by melnikoved** [symfony/symfony#40129]
**Symfony flex version**: v1.12.1

**Description**  
I receive 4-5 warnings per hour the warning like this:
```
E_WARNING: Zend OPcache could not compile file /var/www/backend/releases/1057/var/cache/prod/pools/+XQbTBprpD/K/S/LnuQ3UN2H-3McS8mM0hw
```
The trace is not usefull:
```
1. File "/var/www/backend/releases/1057/vendor/oxcom/symfony-rollbar-bundle/EventListener/ErrorListener.php", line 69 in SymfonyRollbarBundle\EventListener\ErrorListener::handleError

2. SymfonyRollbarBundle\EventListener\ErrorListener::handleFatalError
```

The project is run on two identical servers with a load balancer.
When I checked the file I found that the file does not exist on one of two servers (few minutes later the file is created on the second server too)

**Additional context**  
The warnings are produced by HTTP requests to NGINX and PHP-FPM. 
I use symlink deployment process but the warning appears randomly (not right after the code update).

Opcache settings are default except this three values:
```
opcache.memory_consumption=1024
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=30000
```

**Comment by nicolas-grekas** [comment]
A stack trace would be useful actually. There is nothing we can do if we don't know what is triggering this.
This might be related to a call to `opcache_compile_file()`, but without a stack trace, that's just a guess.
If my guess is right, the only call to this function is `@`-silenced, so that the warning should be ignored and you might have a configuration issue with your error handler.

Status: needs feedback.

**Comment by xabbuh** [comment]
Let's close here for now until we are able to reproduce the issue.
