### ISSUE TITLE
Is there a way to set different cookie for each defined firewall ?

### ISSUE THREAD

**Issue by fodger** [symfony/symfony#40219]
Hi,
first at all, many thanks for your work !

Here's my situation : I have different firewalls used for some specifics root URIs (front, back...).
It's a classical story, actually with a same domain, cookie is shared between front and back.

Is it possible to define in security.yaml firewalls the cookie name ? 

Thanks.

Regards,

**Comment by stof** [comment]
which cookie are you talking about ? The session cookie or the remember_me cookie ? the name of the remember_me cookie is already configurable per firewall. The session cookie is not managed by the security system and so cannot change per firewall, because the session does not depend on the firewall.

**Comment by weaverryan** [comment]
Yea, the problem as Stof said is that the session cookie is just a session cookie - it's global for your application's session, regardless of the firewall (or even if you don't have security installed).

> It's a classical story, actually with a same domain, cookie is shared between front and back

Is this causing a problem? The 2 different firewalls store their authentication in different parts of the session. So even with the same session cookie, you can be logged into the frontend and backend as different users.

Cheers!

**Comment by xabbuh** [comment]
closing as explained
