### ISSUE TITLE
Failed messages deleted after max retry reached

### ISSUE THREAD

**Issue by tmessaoudi-official** [symfony/symfony#40212]
**Symfony version(s) affected**: 4.4

**Description**  

When a message fails x times (RetryStrategy default 3 * 2 times), it gets deleted permanantly,
In my context i would want to keep in a "dead" transport like error for example for manual review,
I couldn't find a way to make this happen, i read the docs but seems like a default behavior.
Should it be the default behavior if it is ? or how can change this behavior if i want to

Thanks in advance

**How to reproduce**  

Just default config for symfony/messenger 4.4,
When a message fails and you reexecute bin/console messenger:failed:retry,
With the default retry strategy it tries it for 6 times and then on the 7th or 8th the message deleted permanantly

**Possible Solution**  

Add an option to decide what to do when a message is not retryable
**Additional context**

**Comment by monteiro** [comment]
@tmessaoudi-official By default, after 3 retries the message is discarded, because even if you have a failure-transport, they have the same behavior as the normal transports.

What you can do is to create a new **Retry Strategy**, instead of the [default](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Messenger/Retry/MultiplierRetryStrategy.php) one, implementing the [interface](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Messenger/Retry/RetryStrategyInterface.php): 

with **isRetryable()** method returning always true, without caring about the number of retries.

**Comment by tmessaoudi-official** [comment]
@monteiro Thanks for you answer, in fact what i did is a little bit similar, but instead of always returning true for retry (i don't want that), when it reachs maxRetries * 2 + 2, which means that it ran for the first time, then retried x times then failed then retried again x times (here will be deleted with the normal behavior), i move it to another transport called error for manual review, because like i said i don't want it to be retried forever neither to be deleted.
I'am closing the issue.
