### ISSUE TITLE
[RFC][DX] Add possibility to provide bundle configuration (definition) inside the bundle class

### ISSUE THREAD

**Issue by mahono** [symfony/symfony#40259]
**Description**  
With all the recent changes towrds configuring things using PHP I wonder why not providing the possibility to provide bundle configuration directly inside the bundle class. Currently developers need to create an extension class and then a Resources/services.php file to return the configuration definition.

I think it could be a great improvement to provide an empty method in Symfony\Component\HttpKernel\Bundle\Bundle that can be overridden to just return that same configuration you would return in the Resources/services.php file.

**Example**  
From developer perspective it could look like this in a bundle class:

```php
class ByAwesomeBundle extends Bundle
{
    protected function configureContainer(ContainerConfigurator $container)
    {
        // Do whatever you like to configure the container for the bundle.
    }
}
```

Or I'm not 100% sure how the system works maybe the method needs to return Closure to work with the container building system.

I just wanted to report this idea. :o)

**Comment by yceruto** [comment]
What about `Bundle::build(ContainerBuilder $container)` method? Although it's not the fancy `ContainerConfigurator` you can do whatever you want concerning DI directly.

**Comment by gggeek** [comment]
Sorry, but this could easily lead to configuration becoming more magic and less understandable, as using more php instead of declarative languages (yaml, xml) allows developers to embed more logic in the "creation of the final configuration values".
This in turns makes it hard to the developers who have to use/modify/extend those bundles to both understand what is going on and tweak it.
While it could be a nice option for 'project code', I am not sure it is a good idea for 'library code'...

**Comment by ahundiak** [comment]
Conceptually, I have always felt that AppBundle had basically been replaced with src/Kernel.php.  So besides a configureContainer method, it might be interesting to add a configureRoutes(RoutingConfigurator $routes) method as well.  You could even go crazy and allow implementing things like the CompilerPassInterface.

**Comment by Nyholm** [comment]
I might be slightly off topic, but here is an idea: 

Currently, to create a bundle, you need a `AcmeHelloBundle` class, an `Extension` and a `Configuration`. You can define your services in the `Extension::load()` or with some addition php/yaml/xml resources. 

You could however make this process a bit simpler by adding everything in the `AcmeHelloBundle` class. Working example:

```php
namespace Acme;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\Config\Definition\Processor;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Extension\ConfigurationExtensionInterface;
use Symfony\Component\DependencyInjection\Extension\ExtensionInterface;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Symfony\Component\DependencyInjection\Loader;

class AcmeHelloBundle extends Bundle implements ExtensionInterface, ConfigurationExtensionInterface, ConfigurationInterface
{
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder($this->getAlias());
        $root = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('some_option')->isRequired()->cannotBeEmpty()->end()
            ->end();

        return $treeBuilder;
    }

    public function load(array $rawConfigs, ContainerBuilder $container)
    {
        $processor = new Processor();
        $config = $processor->processConfiguration($this, $rawConfigs);
        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/config'));
        $loader->load('services.yaml');

        // Do something with $config['some_option']
        // Add service definitions
    }

    public function getConfiguration(array $config, ContainerBuilder $container)
    {
        return $this;
    }

    public function getContainerExtension()
    {
        return $this;
    }

    public function getXsdValidationBasePath()
    {
        return false;
    }

    public function getAlias()
    {
        return 'acme_hello';
    }
}
```

This is okey "light" bundles. For most bundles they can be just simple libraries + recipes and for "heavy" bundles, you probably want the `Extension` and `Configuration` in separate classes.

**Comment by jvasseur** [comment]
If I recall correctly, loading code even if not executed adds an small overhead on each requests (it might have changed with preloading) and since the bundles classes are loaded on each requests. This means that if we go this route, the configuration and building code of bundles will be loaded on every requests, even when it's not needed because the container is already built.

**Comment by Nyholm** [comment]
Excellent observation. You are correct. The `Bundle` class is loaded into memory at each request, but `Configuration` and `Extension` is only loaded when building the container. 

I have not measured the impact, but Im sure it is really neglectable. And as you mention, the time penalty will go away with with preloading. 

Also note (in case it was not obvious), the code I posted is already working with sf 5.2 and most likely with sf 4.4.

**Comment by jonny827** [comment]
@gggeek Magic is all perspective. 

The way Symfony does configuration is problematic. 

Unless I am missing something, In the bundle, I can easily configure services/parameters but not routes or configuration. 

There are several use cases that I have where it would be much better to import routes from bundles so that I can manage the route configuration at the bundle level.  This is especially helpful when using locale based route configurations like 
```
path:
        en: /about-us
        nl: /over-ons

```
Routes in bundles are also super helpful for managing host for subdomain usage for multi-tenant, api, dev, mobile version, etc.

For config, I would like to configure Twig and Doctrine, from within bundles as well. <project>/bundle/<bundle>/Resources/config/packages/Twig.yml would be appended to <project>config/packages/Twig.yml. This is similar to how templates are overwritten but in this case it is an append.

It is Symfony, I think configuration options are great including php, yaml, xml!  I would like to add a configuration provider so we could store configuration in the database and I could alter configurations using SQL.

If I happen to be missing either of these options (config and routes in bundles) and (configurations stores in DB similar to a user provider) then please. let me know!

Until then, I agree with @mahono that we need to move towards best practices, because what we have right now is not it in my opinion.

**Comment by nicolas-grekas** [comment]
> I can easily configure services/parameters but not routes or configuration.

This is by design: routes belong to the "public API" of web apps. Not to bundles. Bundles should not create routes on their own - the dev should wire the routes for a bundles. Recipes provides working routes out-of-the-box, which is the best DX to me.

> I would like to add a configuration provider so we could store configuration in the database and I could alter configurations using SQL.

Since Symfony's container is compiled, it'd mean finding a way to connect to the DB before compiling the container. Since the DB connection is defined as a service, there is a chicken-n-egg situation.
This is still possible, see Drupal. Of course, this comes with its set of compromises, which we won't do in Symfony (use Drupal if you need this).

But this is going a bit off topic :)

**Comment by gggeek** [comment]
@nicolas-grekas sorry for introducing the off-topic topic ;-) I have a tendency to do that in comments to PRs as those provide an extremely convenient, universally available way to give feedback (thanks github for that btw!).
I'd love it if there was an equivalently easy way to discuss about more high-level design decisions, such as what @jonnny827 is doing.
Alas, many projects provide little or no venue for feedback on design, and only allow it on working code / prototypes - and at that moment it feels bad to undo what has already been done :-( Heck, some developers even have a dislike of discussing stuff in abstract...

**Comment by wouterj** [comment]
@gggeek you can start new discussions (concrete & abstract) by creating new issues (https://github.com/symfony/symfony/issues/new/choose) or commenting on issues that are about the topic already. Or join the [Symfony slack](https://symfony.com/slack) if you want to have a more conversation-type discussion within the community.

Anyway, back to the topic here.

---

I think @Nyholm already showed that bundle classes are already able to provide DI configuration. Is there anything to do here?

**Comment by jonny827** [comment]
@nicolas-grekas 

> This is by design: routes belong to the "public API" of web apps. Not to bundles. Bundles should not create routes on their own - the dev should wire the routes for a bundles. Recipes provides working routes out-of-the-box, which is the best DX to me.

1. I become a developer to never do something manually again.

2. How do recipes provide working routes and config and twig namespace registration,etc. out of the box?  The version 5.x documentation for Reusuable Bundles leaves much to be desired and same with Recipes.  Would love to know how so I can keep good programming practice (separation of duties) without having to manually configure every single bundle.

> Since Symfony's container is compiled, it'd mean finding a way to connect to the DB before compiling the container. Since the DB connection is defined as a service, there is a chicken-n-egg situation.
This is still possible, see Drupal. Of course, this comes with its set of compromises, which we won't do in Symfony (use Drupal if you need this).

During container warmup / caching we could use a container provider to establish a connection with the database to acquire all of the configurations; a sort of pre-container.  You never compromise by offering a way to do this.  It is similar to doing a credential provider for user authentication.

**Comment by xabbuh** [comment]
I agree with @wouterj and @Nyholm. Let's close here.

**Comment by yceruto** [comment]
FYI with https://github.com/symfony/symfony/pull/43701 you can manage the DI extension of the bundle within the bundle class itself with all the new stuff you currently like and more:
```php
class AcmeFooBundle extends MicroBundle
{
    public function configuration(DefinitionConfigurator $definition): void
    {
        $definition->import('../config/definition.php');
    }

    public function prependExtension(ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container->import('../config/packages/cache.php');
    }

    public function loadExtension(array $config, ContainerConfigurator $container, ContainerBuilder $builder): void
    {
        $container->import('../config/services.php');
    }
}
```
Further, you can load Config definitions and extension configs from an external file, or if desired, everything can be defined in place.
