### ISSUE TITLE
Is it possible to write a RECURSION schema for configuration

### ISSUE THREAD

**Issue by divineniiquaye** [symfony/symfony#40251]
This is more like a bug than a general question I'm seeking answers to.
I'm in the process of migrating an application from [Nette](https://github.com/nette/nette) to [Symfony](https://github.com/symfony/symfony). But kind of stacked working with Symfony's Config component Schema.

## Description

I have define a configuration scheme used in an aspect of my application, this config is for setting up `CORS` in my app. First, I'll need to setup a default config, for all allowed paths which should have `CORS` support. Example of a data used:

![Data](https://user-images.githubusercontent.com/53147395/108440576-48893f80-724b-11eb-8873-6aaa7cf4ef1e.png)

### `In Nette` my scheme configuration looks like this and works just fine:

![Nette](https://user-images.githubusercontent.com/53147395/108437663-b03c8c00-7245-11eb-881d-524088220bbc.png)

### But using `Symfony's config component`, it throws a generic `PHP Error` : 

*Maximum function nesting level of '256' reached, aborting!*

![Symfony](https://user-images.githubusercontent.com/53147395/108441408-f3e6c400-724c-11eb-9857-7c806f119894.png)

## Help

After reviewing the codes in the pics illustrations above. Is it a bug of Symfony's Config component, or I'm not doing something right.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by stof** [comment]
the difference is that in your Nette example, you are not adding `allow_paths` inside your `addCorsSection` method, and so you are not triggering an infinite recursion when calling  `addCorsSection`. But in the case of your symfony-based code, your `addCorsSection` method is calling itself in an infinite recursion loop. There is no bug in symfony/config. The bug is purely in your own code.

I see 2 ways to solve that:

- moving the handling of `allow_paths` outside the `addCorsSection` method
- adding a boolean parameter in your `addCorsSection` method to control the fact of adding a recursive `allow_paths` node (and passing `false` to it when calling it for the `allow_paths` node)

**Comment by divineniiquaye** [comment]
I guess you right @stof Thanks. I'll try what you have suggested.
