### ISSUE TITLE
Messenger exception normalizer conflicts with other possible exception normalizers

### ISSUE THREAD

**Issue by goetas** [symfony/symfony#40256]
**Symfony version(s) affected**: 5.2.3

**Description**  
https://github.com/symfony/symfony/pull/32341 and https://github.com/symfony/symfony/pull/38941 started to serialize and unserialize exceptions when a message fails (using `\Symfony\Component\Messenger\Transport\Serialization\Normalizer\FlattenExceptionNormalizer`).

When there is another normalizer registered to handle exceptions (as in FOSRestBundle the `\FOS\RestBundle\Serializer\Normalizer\FlattenExceptionNormalize`), there is a conflict of normalizers.

What happens is that the FOSRestBundle serializes the exception,  but later the messenger normalizer tries to deserialize it... but since it is a different format, it fails throwing an error.

(this error can heppen any time there is a custom exception normalizer registerd) 

**How to reproduce**  
- application with symfony messenger 5.x and fos rest bundle 3.x
- throw an error while consuming a message
- when the message is re-delivered an error is thrown

```
[2021-02-19T15:07:18.242180+00:00] console.CRITICAL: Error thrown while running command "messenger:consume". Message: "Notice: Undefined index: class" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: class at /var/www/app/vendor/symfony/messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php:74)","command":"messenger:consume","message":"Notice: Undefined index: class"} []

In FlattenExceptionNormalizer.php line 74:

  Notice: Undefined index: class  
```

**Possible Solution**  

Since it is hard to have independent serializer configurations, what if the `\Symfony\Component\Messenger\Transport\Serialization\Normalizer\FlattenExceptionNormalizer` was just ignoring errors if the data are different from what is expected? 

(from my understanding the `ErrorDetailsStamp` is used just to provide a nicer error message to the user).

**Additional context**  
I've created https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2292 on the FOSRestBundle repo

**Comment by monteiro** [comment]
In this specific case, I think that FriendsOfSymfony/FOSRestBundle should handle that. Because in Symfony you have both normalizers. One for [API](https://github.com/symfony/symfony/blob/17eaad20d137b5d7918d715b76ab2ac4ae13e32c/src/Symfony/Bundle/FrameworkBundle/Resources/config/serializer.php#L103) and another one for [Messenger](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/FrameworkBundle/Resources/config/messenger.php#L70).

If messenger is installed it will install the messenger normalizer one, overriding the API normalizer one (using a bigger priority).
The interesting part here is that both are compatible, meaning that the only difference is that the Messenger one, will provide more information.

You can see this behavior has been added in [5.2](https://github.com/symfony/symfony/blob/37e1823598ecb068529acd63df8efbd90e2a58b0/src/Symfony/Component/Messenger/CHANGELOG.md) to solve a bug in Messenger: 

> Added FlattenExceptionNormalizer to give more information about the exception on Messenger background processes. The FlattenExceptionNormalizer has a higher priority than ProblemNormalizer and it is only used when the Messenger serialization context is set.

Take into account, that we can execute Messenger in a controller, using an API. So we cannot just separate that Flatten exception serializer assuming that it will be executed in the command line.

**Comment by Richard87** [comment]
Hi all, this bug hits me too:
(Symfony 5.2.1, PHP 7.4.10)

```
There are 73 messages pending in the failure transport.
[2021-02-24T09:18:42.325278+01:00] console.ERROR: Error thrown while running command "messenger:failed:show -vvv". Message: "Notice: Undefined index: message" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: message at /home/eportal/production/releases/20210223142338/vendor/symfony/messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php:71)","command":"messenger:failed:show -vvv","message":"Notice: Undefined index: message"} []
09:18:42 ERROR     [console] Error thrown while running command "messenger:failed:show -vvv". Message: "Notice: Undefined index: message"
[
  "exception" => ErrorException {
    #message: "Notice: Undefined index: message"
    #code: 0
    #file: "/home/eportal/production/releases/20210223142338/vendor/symfony/messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php"
    #line: 71
    #severity: E_NOTICE
    trace: {
      /home/eportal/production/releases/20210223142338/vendor/symfony/messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php:71 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Serializer.php:208 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:471 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:506 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php:385 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:233 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:311 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Serializer.php:208 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Normalizer/ArrayDenormalizer.php:62 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Serializer.php:208 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/serializer/Serializer.php:144 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/messenger/Transport/Serialization/Serializer.php:120 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/messenger/Transport/Serialization/Serializer.php:73 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/doctrine-messenger/Transport/DoctrineReceiver.php:160 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/doctrine-messenger/Transport/DoctrineReceiver.php:121 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/messenger/Command/FailedMessagesShowCommand.php:86 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/messenger/Command/FailedMessagesShowCommand.php:71 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/console/Command/Command.php:255 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/console/Application.php:989 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/framework-bundle/Console/Application.php:96 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/console/Application.php:290 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/framework-bundle/Console/Application.php:82 { …}
      /home/eportal/production/releases/20210223142338/vendor/symfony/console/Application.php:166 { …}
      /home/eportal/production/releases/20210223142338/bin/console:28 {
        › $application = new Application($kernel);
        › $application->run($input);
        › 
        arguments: {
          $input: Symfony\Component\Console\Input\ArgvInput {#1 …}
        }
      }
    }
  },
  "command" => "messenger:failed:show -vvv",
  "message" => "Notice: Undefined index: message"
]

```

**Comment by monteiro** [comment]
Morning @goetas !

This is the exception that should be supposed loaded on the Messenger part: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php and is replaced by the FOSRestBundle.

If you see this [line](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php#L61) Normalizer is instantiated and it's only executed if context is from Messenger
That context is set on the [Symfony Messenger Serializer](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php).

Can you provide a sample project where we are able to test this locally, in order to see if we can play with the context to fix this somehow?

**Comment by monteiro** [comment]
A potencial solution is for https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3.x/Serializer/Normalizer/FlattenExceptionNormalizer.php#L78

do the same as this [line](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Messenger/Transport/Serialization/Normalizer/FlattenExceptionNormalizer.php#L100).

If the serializer is the Messenger serializer, it sets a context, so the right flatten exception normalizer is used.
If you don't potentially want to do that change in FOSRestBundle, the other option is to change priority, so the FOSRestBundle has lower priority.

**Comment by goetas** [comment]
Closing this since fixing this in the FOS Rest bundle is easier (created https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2294)
