### ISSUE TITLE
Translating PHP classes (and their contents)

### ISSUE THREAD

**Issue by elfring** [symfony/symfony#40473]
It is occasionally needed to translate selected PHP classes (and their contents).
I am still looking for ways to improve corresponding conversions for affected data models.

:thinking: How do you think about to [add any more information for this use case](https://stackoverflow.com/questions/66636139/how-to-translate-data-models-by-the-means-of-symfony/66637793#66637793 "How to translate data models by the means of Symfony?")?

**Comment by Nyholm** [comment]
Hey. 

Have you seen [Translatable objects](https://symfony.com/doc/current/translation.html#translatable-objects)? Have a look at `Symfony\Component\Translation\TranslatableMessage` and the interface it implements. It may help you.

**Comment by elfring** [comment]
>Have you seen Translatable objects?

Yes.

:thinking: I would appreciate if selected PHP classes (and their contents) can be marked for translations (without the specification as named additions to form constructions).
Are there any more consequences to consider for [desired data processing](https://symfony.com/doc/current/translation.html#extracting-translation-contents-and-updating-catalogs-automatically "Extracting translation contents and updating catalogs automatically")?

**Comment by jkufner** [comment]
A simple question: How do you collect the strings or message IDs so that you can compose a complete dictionary for the translators?

I've seen this concept multiple times over the last two decades and it always backfired spectacularly. It seems to be a good idea at first, but significant complications come later.

In the ages of Gettext, it was a simple tokenization of the source code and looking for the `_('some string')` constructs.

**Comment by xabbuh** [comment]
Closing here as it's not clear what should be changed. Please feel free to comment with a concrete use case that you have in mind and we can consider to reopen.

**Comment by elfring** [comment]
>Please feel free to comment with a concrete use case that you have in mind

Some forms are usually constructed based on attributes from PHP classes (according to a selected data model).


>and we can consider to reopen.

Thus I am looking again for software development possibilities to integrate data sources for desired translations automatically.

**Comment by jkufner** [comment]
@elfring Every text in source code which is meant to be presented to the user, should be explicitly marked for translation, so that static analysis can collect the messages and build a dictionary for translation. If such a message is retrieved from annotations or autogenerated, then it cannot be collected for translation and everyone will suffer — users because of incomplete translations, developers because of localization overhead, and translators because of repeatin problems and missing texts.

Alternative approach is to use message IDs instead of messages in a primary language. That solves some issues with fixing grammar errors in source code, but otherwise it is the same.

So, if you want localized texts in PHP class annotations, then localize them in the annotations, not later in the forms. Sooner or later you will run into a case where you need a localized message somewhere else.
