### ISSUE TITLE
Serializer trying to denormalize object of expected type for constructor

### ISSUE THREAD

**Issue by mrsombre** [symfony/symfony#40746]
**Symfony version(s) affected**: 5.2x

**Description**

Cannot create an instance of "Bar" from serialized data because its constructor requires parameter "name" to be present.

**How to reproduce**

```
class Foo
{
    private Bar $bar;

    public function __construct(Bar $bar)
    {
        $this->bar = $bar;
    }
}

class Bar
{
    public function __construct(string $name)
    {
    }
}

$bar = new Bar('test');

$normalizers = [new \Symfony\Component\Serializer\Normalizer\ObjectNormalizer()];
$serializer = new \Symfony\Component\Serializer\Serializer($normalizers);

$foo = $serializer->denormalize(
    [
        'bar' => $bar,
    ],
    Foo::class,
);

var_dump($foo);
```

**Possible Solution**
Custom normalized like this:
```
public function supportsDenormalization($data, string $type, string $format = null, array $context = [])
{
    if (!is_object($data)) {
        return false;
    }
    return get_class($data) === $type;
}

public function denormalize($data, string $type, string $format = null, array $context = [])
{
    return $data;
}
```

**Additional context**

Am I missing something? Why serializer trying to do something with an already denormalized object? I'm using this code for test entities mapping.

**Comment by norkunas** [comment]
Maybe providing `AbstractNormalizer::DEEP_OBJECT_TO_POPULATE => true` to the context would help?

**Comment by mrsombre** [comment]
@norkunas Doesn't help. This is for the case when you denormalize into an already existing object. But in my case, I'm denormalizing into a new object, but there are existsting objects in data

**Comment by n0rbyt3** [comment]
@mrsombre I guess you are mixing two different things: You are *not* trying to denormalize into an exising object, because you are passing an array and you are *not* denormalizing an normalized array because it contains an object.

Denormalization is the process of converting normalized data (=an array of simple types) back into an object.

I guess your case is not supported by the serializer component (yet). Because ```Bar``` requires special construction, you will have to use a custom denormalizer for this class.

**Comment by mrsombre** [comment]
@n0rbyt3 yeah, thx for the explanation. I'm using a serializer for object mapping, ie populating properties without actually call setters. Custom normalizer sounds reasonable for me now.
