### ISSUE TITLE
[DependencyInjection][FrameworkBundle] `lint:container` incorrectly marks service closures as not callable

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#40773]
**Symfony version(s) affected**: 5.2.6

**Description**
Under some circumstances, the `lint:container` command incorrectly fails on service closures being passed to a parameter declared as `callable`. This caused doctrine/DoctrineMigrationsBundle#413 and currently breaks the CI of the Symfony demo app.

**How to reproduce**
https://github.com/derrabus/di-sca-reproducer

Run the `lint:container` command and you'll get the following error.

```
[ERROR] Invalid definition for service "a": argument 2 of "App\A::setDependency()" accepts "callable", "App\B" passed.
```

However, run the `test`command and you'll see that the service definition is constructed successfully.

**Comment by nicolas-grekas** [comment]
The reason for this issue is that in Yaml/XmlDumper, we have code like:
```php
        if ($value instanceof ServiceClosureArgument) {
            $value = $value->getValues()[0];
        }
```

That is: we unwrap the service.

The deeper reason for this is that we don't have a way to dump service closures as yaml nor xml.

When using the command, in dev, the xml file is loaded and :boom: 
In prod env, this works as expected because the container is loaded from source, not from xml.

For thoughts :)

**Comment by alexandre-daubois** [comment]
What I understood during my investigation is during values processing here...
https://github.com/symfony/symfony/blob/bb1e1e58aea5318e96d1c22cc8a91668ed7baaaa/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php#L86
... the value is resolved, and it returns only the `Reference`, created during services register (`Kernel.php` in @derrabus example).

The reason tests are passing seems to be because the `CheckTypeDeclarationPass` is tested alone, not with other compilation passes. Adding this code in `checkType` of `CheckTypeDeclarationPass` solves the problem:

```php
if ('callable' === $type && \is_object($value) && ($value instanceof Reference || $value instanceof Definition)) {
    return;
}
```

But the solution of @nicolas-grekas seems a better explanation!

**Comment by derrabus** [comment]
Thanks for the analysis.

> we don't have a way to dump service closures as yaml nor xml

This is something we could fix for 5.3. But that would basically mean that the linter remains broken in Symfony 4 perpetually. 😕  

> ```
> if ('callable' === $type && \is_object($value) && ($value instanceof Reference || $value instanceof Definition)) {
>     return;
> }
> ```

Yes, that would silence the error. Side note: `Closure` would also be a valid type declaration for a service closure.

But that change would basically mean that *any* reference or inlined definition would pass a `callable` type. We would fix a false positive at the cost of introducing false negatives. That would be unfortunate. 😕

**Comment by nicolas-grekas** [comment]
We could skip using the xml in 5.2. That would make the command slower :man_shrugging:

**Comment by craigh** [comment]
@nicolas-grekas :
> In prod env, this works as expected because the container is loaded from source, not from xml.

so it seems like I should then be able to do `bin/console lint:container --env=prod --no-debug` with success, but I get this error:
```cli
  In ContainerBuilder.php line 982:

  You have requested a non-existent service "debug.controller_resolver".

**Comment by stof** [comment]
@alexandre-daubois the code you linked does not replace the ServiceClosureArgument. It process the value inside it, but keeps the argument itself.

**Comment by stof** [comment]
@nicolas-grekas the other solution is to add a XML syntax to represent a ServiceClosureArgument, so that we can dump the compiled container properly

**Comment by derrabus** [comment]
This is apparently a duplicate of #39259. Let's close this one then.
