### ISSUE TITLE
[DomCrawler] issue with parsing script tags

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#40789]
**Symfony version(s) affected**: v4.4.20 + v5.2.4

**Description**
I noticed an issue with the DomCrawler when parsing script tags that contain closing html tags.

**How to reproduce**
```php
<?php

require_once 'vendor/autoload.php';

$html = <<<HTML
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>reproducer</title>
    </head>
    <body>
        <form>
            <script>
                var x = '</form>';
            </script>
        </form>
    </body>
</html>
HTML;

$crawler = new Symfony\Component\DomCrawler\Crawler($html);
echo $crawler->outerHtml();
``` 

results in 

```html
<html lang="en">
    <head>
        <title>reproducer</title>
    </head>
    <body>
        <form>
            <script>
                var x = '</script></form>';
            
        
    </body>
</html>
```

**Comment by stof** [comment]
This is actually an issue of PHP's `DOMDocument` API due to the parsing being done with `libxml`. The same kind of issues was appearing in browsers too years ago (hence the common practice to split strings as `'<' + '/form>'` in inline JS).

The DomCrawler component supports using an HTML5 parser instead when `masterminds/html5` is installed. Using the HTML5 parser is automatic based on the presence of the HTML 5 doctype in the string (which is the case in your example, so it would use it).

**Comment by dmaicher** [comment]
Indeed thanks @stof.

Just stumbled across https://bugs.php.net/bug.php?id=52012 and https://github.com/phpgt/dom/issues/39

So nothing we can really do here I guess. I will try it with `masterminds/html5`.

**Comment by VincentLanglet** [comment]
What do you think about adding documentation to https://symfony.com/doc/current/components/dom_crawler.html ?

**Comment by stof** [comment]
@VincentLanglet I suggest you open a PR on https://github.com/symfony/symfony-docs/ :smile:
