### ISSUE TITLE
Add support for $requestStack->getCurrentRequest(throwOnNull: true);

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#40948]
**Description**
I have quite often this piece of code in my service layer:
```php
$request = $this->requestStack->getCurrentRequest();
if (!$request) {
    throw new \RuntimeException('The request is mandatory.');
}
```
And it's a bit boring to write this code every time.

**Example**

What do you think about a flag (or another method) to add this feature in the core?

```php
$requestStack->getCurrentRequest(throwOnNull: true);
// or
$requestStack->getCurrentRequestOrThrow();
```

**Comment by derrabus** [comment]
PHP 8 ftw! 😉 

```php
$request = $this->requestStack->getCurrentRequest()
    ?? throw new \RuntimeException('The request is mandatory.');
```

**Comment by derrabus** [comment]
I think, this issue also applies to `getMainRequest()`.

Adding a flag would only make sense if we wanted to deprecated calling `getCurrentRequest()` on an empty stack imho. Otherwise IDEs and static analyzers would still complain because the return type has to remain nullable. We wouldn't gain much.

**Comment by dborsatto** [comment]
I've dealt with a fair share of functions that could either return null or throw an exception depending on a flag parameter, and let me tell you, it's the worst of both worlds. A function in an external class should always treated as a black box and if it says that it returns `Request|null` and can throw an exception, you must check for both regardless of what parameter you pass to it.

In my opinion the best API would have been from the start to return `Request` and have the function throw if none is available (instead of returning `null`), but at this point I'd rather keep it the way it is than having two ways of communicating failure conditions 😉

**Comment by lyrixx** [comment]
Fair point. We could add this behavior in symfony, isn't ? With the current method (and a migration path) or a ne method?
But it may not worth it. I Don't know

**Comment by lyrixx** [comment]
Let's use the solution provided by @derrabus https://github.com/symfony/symfony/issues/40948#issuecomment-826647177
