### ISSUE TITLE
[5.3 beta2][Security] Can't validate manual CSRF (test env only)

### ISSUE THREAD

**Issue by COil** [symfony/symfony#41046]
**Symfony version(s) affected**: 5.3 beta2

**Description**
A csrf token put inside a twig template with the `csrf_token()` helper can't be validated any-more. This only occurs when using the test environment (PHPUnit 7.5.20) .

**How to reproduce**

Twig :

    <input type="hidden" name="_token" value="{{ csrf_token('delete'~event.id) }}">

Controller : 

        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {

Test : 

        $csrfToken = self::getContainer()->get('security.csrf.token_manager')->getToken('delete1')->getValue();
        echo $csrfToken;
        $client->request('DELETE', '/event/delete/1', [
            '_token' => $csrfToken,
        ]);

**Possible Solution**
Seems related to the test environment as everything works correctly in dev or prod.

**Additional context**

* Everything was OK with 5.2.6.
* The problem occurs everywhere `csrf_token(` is used in a template

**Comment by javiereguiluz** [comment]
Starting from 5.3, CSRF tokens are randomized (transparently to the developer) to avoid security issues. See https://github.com/symfony/symfony/pull/39919. Maybe it's related somehow?

**Comment by jderusse** [comment]
~is it expected to have 2 différents intentions? `delete` in controller and `delete1` in test~
NVM I missed the controller logic

**Comment by COil** [comment]
Hello, I am closing this. Generating the CSRF token manually in the test wasn't really clean. I switched to a better functional test where I submit the form, and now it's OK.

    $form = $crawler->selectButton('event_delete_1')->form();
    $client->submit($form);

Thanks for the help. 🙂

**Comment by stof** [comment]
@COil what you were trying to do previously in your test was basically bypassing the CSRF protection to make a CSRF attack work :smile:

**Comment by COil** [comment]
Yes, indeed!!! 😅

**Comment by Pixelshaped** [comment]
Not sure how we should test AJAX requests. We had this implementation for our API system that doesn't work anymore:
```
protected function callAPI(string $uri, array $data, string $tokenId): ?Crawler
    {
        $apiData = [
            '__data' => $data,
            '__token' => self::getContainer()->get(CsrfTokenManagerInterface::class)->getToken($tokenId)->getValue()
        ];
        return $this->client->xmlHttpRequest('POST', $uri, [], [], ['CONTENT_TYPE' => 'application/json'],
            json_encode($apiData));
    }
```
In some way: yes we were "attacking" that endpoint, but then that's not what we were testing. What would be the preferred way?

Some detail:
```
self::getContainer()->get(CsrfTokenManagerInterface::class)->getToken($tokenId)->getValue()
```
Calling this before anything else results in the RequestStack being not initiated, which in turn triggers the `Since symfony/security-csrf 5.3: Using the "Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage" without a session has no effect and is deprecated. It will throw a "Symfony\Component\HttpFoundation\Exception\SessionNotFoundException" in Symfony 6.0` warning.

Also not too sure why a test object
`return $this->session ?? $this->session = new Session(new MockArraySessionStorage());`
has been used outside of a test context in https://github.com/symfony/security-csrf/blob/1101de5429b78325980c028c0ab9fccbce290399/TokenStorage/SessionTokenStorage.php#L137

**Comment by Pixelshaped** [comment]
Unorthodoxly solved by:

- Declaring a test route (available only in test env) that gets a token ID and returns a token
- Calling this route before making an API call lets you get the proper randomized token + side benefit of having the request stack initialized properly

Dummy POC implementation now is:
```
// config/routes/test/routes.yaml
csrf_generator:
  path: /csrf_generator
  controller: App\Controller\Application\Test\TestController::csrfGenerator
```

```
<?php
declare(strict_types=1);

namespace App\Controller\Test;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;

final class TestController extends AbstractController
{
    public function __construct(
        private CsrfTokenManagerInterface $csrfTokenManager
    ) {}

    public function csrfGenerator(Request $request): Response
    {
        return new Response($this->csrfTokenManager->getToken($request->query->get('token'))->getValue());
    }
}

```

```
protected function callAPI(string $uri, array $data, string $tokenId): ?Crawler
    {
        if ($this->client === null)
            return null;

        $this->client->request('GET', "/csrf_generator?token=$tokenId");

        $csrfToken = $this->client->getResponse()->getContent();

        $apiData = [
            '__data' => $data,
            '__token' => $csrfToken
        ];
        return $this->client->xmlHttpRequest('POST', $uri, [], [], ['CONTENT_TYPE' => 'application/json'], json_encode($apiData));
    }
```

**Comment by trickeyone** [comment]
@stof Any advice on how to better-resolve this issue? Having to do something like what @Pixelshaped suggested is not very appealing, especially for any functional tests involving XHTTP requests that need CSRF protection.

**Comment by Pixelshaped** [comment]
@trickeyone the proper way to test it would be to:

1. Visit the page A that makes the XMLHttpRequest. Usually there you'll have the button or whatever that makes the call, from which you can scrap infos like `data-token`, `data-route`, and so on, that are most certainly declared as attributes.
2. You scrap this token (and eventually the route and other infos relevant to your AJAX call).
3. You make a successful AJAX call to the route B using a proper `data-token`

Now wait a minute and reflect on what you are testing exactly:

- Is it that the token generated on page A is correctly generated? You have to do it the proper way. (but somehow you're testing Symfony's token integration instead of your code).
- Is it that the `@Security` annotations of page A match the ones of the route B so that they can both be accessed by the same user? You have to do it the proper way. This is a legitimate scenario, but you don't necessarily want to test that always.
- Is it your code, the one behind route B? Then the workaround is sufficient.

The workaround is as much an "attack" on the token generation flow as
```
$this->client = static::createClient();
$user = self::getContainer()->get(UserRepository::class)->findOneByEmail('admin@test.com')
$this->client->loginUser($user);
```
is an attack on the login flow.

See, in all your functional tests you could go through your login page, post the form, etc. but this was deemed a bit redundant: why would you test that your login page works on each test? This is quite the same here. 

Not saying the proper way to do it is wrong, it has legitimate use cases. We currently use both.

Edit: adding an example of "the proper way" for reference:
```
// Visit page A
$this->client->request('GET', '/app/account/order/'.$order->getId());

// Scrap the element that triggers the AJAX call
$elem = $this->client->getCrawler()->filter('a.dropdown-item.open-confirm-modal');
$route =  $elem->attr('data-modal-secondary-route');
$csrfToken = $elem->attr('data-modal-token');

// Using scrapped info, make your xmlHttpRequest call
$this->client->xmlHttpRequest('POST', $route, ['token' => $csrfToken]);

// Test the response and whatever you want
$this->assertRouteSame('client_order_step');
$this->assertSame('/app/order/step/cart', $this->client->getRequest()->getPathInfo());
// ...
```

**Comment by trickeyone** [comment]
@Pixelshaped The code behind the route isn't being tested. In our code, we mock the implementations and test only at the service layer. The test in question is the actual login form submission, so no user has been logged-in yet. I did end up using your example. However, having to make a test-only controller to generate the CSRF token instead of simply getting the CsrfTokenManager and generating the token from it directly in the test is a very... crude and hackish way to get the token.

I understand the reasoning for the token-storage changes and I'm not arguing against it. I'm asking for a more-elegant solution given that, even for basic form validation, I shouldn't have to execute a request to create the form to test the submission logic behind it. This is grossly bloated and simply makes testing even more complicated and brittle. I should be able to run a test to simply test whether data being submitted is valid and not have to completely render a form, populate the form data, then use the crawler to "click" the submit button. I should be able to issue the data directly to the endpoint.

**Comment by Pixelshaped** [comment]
> @Pixelshaped The code behind the route isn't being tested. In our code, we mock the implementations and test only at the service layer. The test in question is the actual login form submission, so no user has been logged-in yet. I did end up using your example. However, having to make a test-only controller to generate the CSRF token instead of simply getting the CsrfTokenManager and generating the token from it directly in the test is a very... crude and hackish way to get the token.
> 
> I understand the reasoning for the token-storage changes and I'm not arguing against it. I'm asking for a more-elegant solution given that, even for basic form validation, I shouldn't have to execute a request to create the form to test the submission logic behind it. This is grossly bloated and simply makes testing even more complicated and brittle. I should be able to run a test to simply test whether data being submitted is valid and not have to completely render a form, populate the form data, then use the crawler to "click" the submit button. I should be able to issue the data directly to the endpoint.

Oh then we do agree. I guess a shorthand like `$this->client->loginUser()` will be implemented in the long run? Something like `$this->client->fakeMeAValidCsrfTokenPlease()` :D

**Comment by trickeyone** [comment]
@Pixelshaped Pretty much, yeah. It'd be nice if having to create this test-only-controller work-around wasn't necessary. Having some kind of convenience test-only method similar to the `loginUser` method would be helpful.

**Comment by trickeyone** [comment]
@Pixelshaped I did find a _possible_ work-around. The issue with the CSRF token not being stored to the session seemed to stem from the fact that there wasn't a logged-in session. Since the Session service is being deprecated in favor of getting the RequestStack, then calling to get the Session from the RequestStack. The session from the RequestStack was simply the Session instance from the last Request object in the stack.

I will give one caveat to this, I haven't tested if this works with following redirects or multiple request inside a single test case.

I added this to my abstract `WebTestCase` that extends from Symfony's `WebTestCase`.
```php
abstract class WebTestCase extends SymfonyWebTestCase
{

    protected function getSession(): SessionInterface
    {
        try {
            return self::getContainer()->get('request_stack')->getSession();
        } catch (SessionNotFoundException $e) {
            return self::getContainer()->get('session');
        }
    }

    protected function getCsrfProvider(): CsrfTokenManagerInterface
    {
        return static::getContainer()->get(CsrfTokenManagerInterface::class);
    }

    protected function getCsrfToken(string $tokenId): string
    {
        $this->ensureSessionIsAvailable();

        return (string)$this->getCsrfProvider()->getToken($tokenId);
    }

    protected function ensureSessionIsAvailable(): void
    {
        /** @var RequestStack $requestStack */
        $requestStack = self::getContainer()->get('request_stack');
        try {
            $requestStack->getSession();
        } catch (SessionNotFoundException $e) {
            $session = $this->getSession();
            $masterRequest = new Request();
            $masterRequest->setSession($session);
            $requestStack->push($masterRequest);
            $session->start();
            $session->save();
            $cookie = new Cookie($session->getName(), $session->getId());
            self::$client->getCookieJar()->set($cookie);
        }
    }


}
```

So, when calling `$this->getCsrfToken('<token id>')` from inside a test, it checks to see if a Session is already available. If there is, all-good. If not, we push a blank request to the stack and set a session instance on it.

I can confirm that this worked for my use-case where I just needed to get a single CSRF token for the login form. Whether it would work in a more-complex scenario, I'm not sure.

**Comment by Pixelshaped** [comment]
That was one of my previous leads, thanks for posting your whole solution. Pretty sure it always throws in `ensureSessionIsAvailable()`, so you always get the session from `self::getContainer()->get('session')`. Couldn't make it work in my API Calls though, as it seems to unlog the user, but I haven't tested it thoroughly.

**Comment by trickeyone** [comment]
Yeah, the current project I'm working on is still in the early staging (hence my just working on the login atm), so I haven't gotten to test it with an authenticated user. However, if you call the `$this->client->loginUser(...)` before call ing to get the token, I think it might still work. If you test with this approach, let me know if it works or not.
