### ISSUE TITLE
[Messenger] Message attributes

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#41106]
Eg.

```php
#[Handler(Some::class)]
#[Handler(Other::class)]
#[Route('sync')]
```

As replacements/alternatives for

```yaml
        'routing' => [
            'App\Message\SmsNotification' => 'sync',
        ],
```

and `MessageHandlerInterface` :zany_face: 

Perhaps it's considerable to expose some tools in a contract package, for other bus implementors to leverage. But Messenger component will do i guess. We could even think of a interop messge bus contract.

**Comment by maxim-dovydenok** [comment]
I like the idea to configure transport using attributes. I will create a PR with the "Senders" attribute. I called it Senders instead of Route, because as I understand "routing" concept is part of the Framework bundle, and in the Messenger, there're only senders. If it's not right, then I'll change it in the pull request.

As for Handlers, I'm not sure that it's the right solution. From my point of view, Messages should not know about the Handlers, and I prefer how it's done now in the Framework bundle. I would like to hear someone's feedback, but I can work on this attribute as well.

**Comment by ro0NL** [comment]
You are right. Im not sure what `#[Handler]` would actually be conveying from the message POV :sweat: probably only creating some bidirectional relation.

What if an attribute could replace MessageHandlerInterface on the handler side, eg. to classify any handler callable. Perhaps it enables more interop value ...

**Comment by maxim-dovydenok** [comment]
> What if an attribute could replace MessageHandlerInterface on the handler side, eg. to classify any handler callable. Perhaps it enables more interop value ...

We can add `AsMessageHandler` attribute as a replacement for a marker interface `MessageHandlerInterface`. There're `AsCommand`, `AsEventListener`, [`AsController`](https://github.com/symfony/symfony/pull/40555/files) attributes already.

**Comment by ro0NL** [comment]
see #41202
