### ISSUE TITLE
[HTTP Foundation][Session] Reverting the session service deprecation and finding a better approach

### ISSUE THREAD

**Issue by dborsatto** [symfony/symfony#41120]
Hello,

yesterday a [blog post](https://symfony.com/blog/new-in-symfony-5-3-session-service-deprecation) was published announcing that the session service would be deprecated in 5.3 and removed in 6.0. While I agree that the current approach is problematic for the reasons explained in the blog post, I believe that the change introduced in #38616 does not go in the way of actually fixing the problem and simply swaps one mistake for another.

The main issues we have currently are:

1. The session is currently treated as a data object _and_ as a service which lives in the service container. As a general rule of thumb, I think we can agree that things that live in the service container should be stateless (except maybe a few very specific use cases), and a data object is definitely not stateless.
2. The session handling is part of the HTTP foundation, which is wrong because sessions are not a part of the HTTP specification. Having this code live in the HTTP foundation is a byproduct of how PHP sessions are handled, with (put simply) a request cookie used to identify the backend session.

The change in #38616 fixes none of these issues. We no longer require `SessionInterface` but we require `RequestStack`, which is also a stateful data object from the HTTP foundation. In there we have a `getSession` shortcut which takes the last request (even though from a conceptual point of view all the `RequestStack` sub-requests should share the same session, unless I'm missing something in how this is handled?) and returns the session from that. With this, we keep `Request` (and therefore the HTTP foundation) session-aware, and we also spread the "session-awareness" to `RequestStack`, too.

For this reasons I believe the current approach is less than ideal, as it introduces a deprecation which does not fix the actual issues in meaningful way, and also spreads the "session-awareness" to other points of the HTTP foundation. My suggestion would be to revert the PR before 5.3, so we avoid publishing and encouraging some behavior which will need to be changed anyway (leading to users having to change their code twice), and use this issue to start the discussion of what the read fix would be, that is, moving the session management part to a separate component (something which has been talked about in the past). Of course, because 5.3 is coming up fast, this new fix would have to be postponed to 5.4/6.0.

Needless to say, I would be super happy to help with this.

@fabpot @javiereguiluz tagging both of you as you replied to my comment on the blog post saying we should move the discussion here.

Cheers!

**Comment by jderusse** [comment]
First of all, thank you for opening this RFC!

There are 2 distinguishes topics here:
- removing the state from the Container
- removing Session out from HttpFoundation

The purpose of #38616 and #40285 was to remove stateful services from the container and address only the first topic.
I don't have a strong opinion about the second topic and won't talk about it in this comment.

I think the main frustration here is a wrong assumption: 

> The `RequestStack` is stateful data object, therefor moving session from a stateful service to another changes nothing.

I disagree on the 2 parts:

1. The `RequestStack` service is not a stateful data object, it's a service that provides you data objects (ie. the current `Request`). Of course, the service has a state to track the current request. Like an `ArrayCacheAdapter`, like `TraceableEventDispatcher`, or like `Monolog` with a finger-crossed strategy, they all store a state, but they are not data object.
The main difference is: If you inject a data object into your service (ie the session), your service will always use the same data (which is the issue when using the `session` service). While, if you inject the service that provides the data object, your service can fetch the current version of the data object.

2. Even if you disagree with the previous part, and think `RequestStack` is a stateful data object, the PR #40285 and #38616 have merged 3 stateful data object into one, which is simpler to manage..

**Comment by derrabus** [comment]
> I think we can agree that things that live in the service container should be stateless (except maybe a few very specific use cases), and a data object is definitely not stateless.

I think there are two things that we should not mix up here:

* A service that maintains a state (stateful service)
* A service that represents the state itself.

The latter is especially problematic because if the state changes, services that depend on that service cannot be updated once they're constructed. This is why the request has been removed from the container a long time ago, why the current user should never be a service and why now the session has been removed.

A stateful service is fine as long as it represents the single source of truth for the state that it maintains. If the state changes, that service will be updated with the new state. That's how the request stack works, but also SecurityBundle's token storage.

> The session handling is part of the HTTP foundation, which is wrong because sessions are not a part of the HTTP specification. Having this code live in the HTTP foundation is a byproduct of how PHP sessions are handled, with (put simply) a request cookie used to identify the backend session.

"Wrong" is a very hard word here. Cookies are also not port of the HTTP spec for instance. HttpFoundation is an attempt to provide usable tools for the interaction with HTTP. Yes, the logic could be moved into a dedicated session component, but I'm not sure if we gain much from it.

> We no longer require `SessionInterface` but we require `RequestStack`, which is also a stateful data object from the HTTP foundation.

See above: Session = state, RequestStack = stateful service.

What would be the alternative? If the request stack is not the right place for the session (maybe it isn't), then we would need a different service that fetches the current session for me. That service would probably still have a method `getSession()` that does just that. And whatever that service is, it will depend (directly or indirectly) on the request stack because the request ultimately provides the information about which session to resume.

**Comment by dborsatto** [comment]
> The RequestStack service is not a stateful data object, it's a service that provides you data objects (ie. the current Request). Of course, the service has a state to track the current request. Like an ArrayCacheAdapter, like TraceableEventDispatcher, or like Monolog with a finger-crossed strategy, they all store a state, but they are not data object.
> The main difference is: If you inject a data object into your service (ie the session), your service will always use the same data (which is the issue when using the session service). While, if you inject the service that provides the data object, your service can fetch the current version of the data object.

The difference between `RequestStack` and the other services you mention is that those are implementations details over higher level abstractions, whereas `RequestStack` (as the name says) is an implementation of a stack data structure, with a couple convenience methods added to it. `ArrayAdapter`, `TraceableEventDispatcher`, and `FingersCrossedHandler` are instances of an implementation which happens to hold internal state, but unlike `RequestStack`, this is not meaningful to the consumer of those services. As per what @derrabus said, those are perfect examples of services that hold internal state but do not represent the actual state.

> Even if you disagree with the previous part, and think RequestStack is a stateful data object, the PR #40285 and #38616 have merged 3 stateful data object into one, which is simpler to manage..

I'm not sure I'm following the _3_: session, request stack, and? Also, "simpler to manage" is always debatable and was not really a point of the issues the PR said it fixed :wink: 

---

> The latter is especially problematic because if the state changes, services that depend on that service cannot be updated once they're constructed.

How is this not the case with `RequestStack`? If a sub request is added to it, other services which had already requested it can no longer be updated. Besides, the name of the class itself is telling us that _it is_ state, it's literally a data structure (a stack that contains request objects).

> "Wrong" is a very hard word here. Cookies are also not port of the HTTP spec for instance. HttpFoundation is an attempt to provide usable tools for the interaction with HTTP. Yes, the logic could be moved into a dedicated session component, but I'm not sure if we gain much from it.

Here I was just reposting what the blog post mentioned as justification for this change. A dedicated session component is something that was proposed in the issues that the PR said was fixing (especially in #12839) but actually was not addressed at all.

> What would be the alternative? If the request stack is not the right place for the session (maybe it isn't), then we would need a different service that fetches the current session for me.

The alternative (in my opinion) would be to no longer represent an abstraction over the session itself, but rather as a way of talking to a generic "session" concept (which could be defined as "persistence of local data across different requests"). If we can shift the focus from "getting the session from the container" to "getting a service which talks to some form of local data storage" I believe we can have a cleaner model and workflow. By abstracting how we talk to the session rather than the session itself, we can break the ties with the `Request` objects and therefore with the HTTP Foundation. This would also allow to easily implement things like https://github.com/psr7-sessions/storageless.

The code in my opinion is already "kind of there", it probably just needs a bit of refinement in how the entry point would look like.

**Comment by derrabus** [comment]
> > The latter is especially problematic because if the state changes, services that depend on that service cannot be updated once they're constructed.
> 
> How is this not the case with `RequestStack`? If a sub request is added to it, other services which had already requested it can no longer be updated.

And they don't need to because even if you add requests to it or if you flush it completely and handle an entirely new main request, it's still the very same request stack.

> The alternative (in my opinion) would be to no longer represent an abstraction over the session itself, but rather as a way of talking to a generic "session" concept (which could be defined as "persistence of local data across different requests").

You lost me here, sorry.

> a service which talks to some form of local data storage

Your description fits either a cache or a database. Storing data is **not** the point of a session. A session maintains state over a stateless protocol.

> we can break the ties with the `Request` objects

We cannot because without the request we wouldn't know which session to resume. You can wrap abstraction layers around it, but eventually you need information attached to the request.

> This would also allow to easily implement things like https://github.com/psr7-sessions/storageless.

That library literally stores the session data ON the request.

Also, can you elaborate why this kind of session storage cannot be implemented with the current session system?

**Comment by pounard** [comment]
> The RequestStack service is not a stateful data object, it's a service that provides you data objects (ie. the current Request). Of course, the service has a state to track the current request. Like an ArrayCacheAdapter, like TraceableEventDispatcher, or like Monolog with a finger-crossed strategy, they all store a state, but they are not data object.

This were I strongly disagree:

-  whereas an ArrayCacheAdapter has a state, it's an application-wide state, it's not supposed to be related to current-request-only context data or state, if it's used otherwise, then I guess it should not be in the container as a service in the first place, but only exist as a service decorator somewhere that could be replaced or changed by something else at anytime,
- TraceableEventDispatcher is a debugging tool, and should probably not considered in this discussion, but it's a current-request-only-dependent data storage as well,
- RequestStack is implemented as a service, but it is a stateful data structure, by definition it holds data from the current request state, therefore it's itself tainted by this state and is stateful.

I know that maybe Session's place is not HttpFoundation, but Request::getSession() seems the most natural place for me to fetch the session.

Maybe what's missing is a component in between Symfony's framework and HttpFoundation, let's says some kind of CurrentRuntimeContext object, whose only goal is to carry current query (I'm saying "query" and not only "request", because console/cli run will need this as well, and they don't have a request) whose goal would be to tie everything whose state is directly derived/dependent from the current execution context, and not application configuration.

Using such in-between application current state object, as interface, would allow it to:

- inject it into controller arguments,
- inject it as console command services using something like a synthetic service,
- add it as a dependency on http events classes, so that listeners can access it via arguments (the event) instead of as being injected as a service,
- because it would be a simple interface without dependency in the first place, using it in other places wouldn't create a dependency hell, and it would be relatively safe to extend to add features (be future proof in some way),
- in the long term make it extendatable using some kind of plugin system (so that users can add functionality over it without the need to patch symfony) - for example to propagate security context.

That's just an arbitrary thought, but it's been a long time that those stateful services do hitch me. I'm always terrified when I inject the TokenStorage service to find the current user instead of directly finding it into the current Request object. Maybe this intermediate application runtime state interface injectable to controllers is what's missing.

**Comment by ro0NL** [comment]
>  from a conceptual point of view all the RequestStack sub-requests should share the same session

i think theoretically we could push any request onto the stack yes, hence i believe session as a service cannot work

**Comment by ro0NL** [comment]
we can think of a `ProxySession` pattern, but there's no guarantee such implementation is always wired eventually.

IMHO eg. `SessionValueResolver` is _the_ legit "in-between" glue, which is 100% bound to current request

i agree RequestStack::getSession is bit of indirection, overruled at the language level with `$stack->getCurrentRequest()?->getSession() ?? throw ...`

**Comment by pounard** [comment]
@ro0NL I agree regarding resolvers but one thing it doesn't solve is the listener services dépendency, no matter how hard we always end-up with a tainted service in container (most notable exemple being the request stack).

Hence the need, at one point or another to try conceiving another way of passing those state objects to listeners, for exemple as properties in event themselves. As pure arguments, if services were statless fonctions, stateful objects such as thé session ans request stack would be arguments.

**Comment by ro0NL** [comment]
RequestStack is an implementation detail for us, if you consider eg. `$kernel->handle(new Request())`

what i dont see yet, is how we replace RequestStack as an extension point for general purpose solutions. If we ignore its mutability, is it a bad service? Its state doesnt change within a kernel lifecycle.

of course we generally prefer the active scope if possible, eg. kernel event, controller args etc.

> Having this code live in the HTTP foundation is a byproduct of how PHP sessions are handled, with (put simply) a request cookie used to identify the backend session.

i dont see how we can make this better other than $request->getSession, i believe eg. symfony/runtime has to evolve first before this can be decoupled.

**Comment by ro0NL** [comment]
what could work is if we abstract the protocol, eg. SessionAware::getSession for stateful data, and SessionProvider::getSession at the service layer (respectively Request and RequestStack for HTTP).

Perhaps it does introduce better semantics :+1:

**Comment by nicolas-grekas** [comment]
About the initial request of reverting the new method, I'm :-1:. The new method is a pragmatic solution to the most important issue, which is about injecting a stateful object as a direct dependency of session consumers. RequestStack creates just the right indirection that allows mutating the session as needed without having to resort to so called scoped services.

The rest is theory. Please give your ideas a try as I'd be happy to find a better way, but for for now we only have ideas, no code yet.
