### ISSUE TITLE
[Security] Access Control behavior with strategy unanimous (Question/Bug)

### ISSUE THREAD

**Issue by simonberger** [symfony/symfony#41251]
Symfony version 4.4.23

We recently switched our access_decision_manager to strategy unanimous.
We need different voters to all grant access.

```yml
access_decision_manager:
    strategy: unanimous
    allow_if_all_abstain: true
```

I compare two different areas of voting (in our application).
1. the security.yml access_control entries giving access to a path with 1 .. n roles
2. annotations (IsGranted and Security) vote on a specific action

Voting on the second case works like intended. Adding an expression allowing access when one of two roles are applied (`@Security("is_granted('ROLE_1') or is_granted('ROLE_2')")`)
- Access is granted when one voter grants access to one attribute (but does not fail if it denies access to one of them)
- Access is denied if one voter denies access to all attributes

When adding multiple roles to an access_control entry in the security.yml the documentation defines this as an OR expression. Why is access denied if access to one role is denied?

I found this one year old security vulnerability which has been fixed. As far as I understood this just introduced the behavior.
https://symfony.com/blog/cve-2020-5275-all-access-control-rules-are-required-when-a-firewall-uses-the-unanimous-strategy

I might miss one important part, but from my point of view the access control voter works against the given configuration in a firewall entry and this is not what the unanimous strategy (should) mean.

**Comment by derrabus** [comment]
The documentation is a bit inaccurate here. One of the reasons might be that the `unanimous` strategy is rarely used and most applications stick to the default `affirmative` strategy.

If you present an array of attributes in the access control rules, what will happen is that all voters will be asked to cast their votes on _each_ of the attributes individually. So assuming, you vote on `['ROLE_USER', 'ROLE_ADMIN']` for a user that possesses `ROLE_USER` only, this is how the votes will look like:

* `RoleVoter` on `ROLE_USER`: granted
* All other voters on `ROLE_USER`: abstain
* `RoleVoter` on `ROLE_ADMIN`: denied
* All other voters on `ROLE_ADMIN`: abstain

So, in the end we will end up with 1 vote for "granted", 1 vote for "denied" and a lots of abstain votes. Using the `affirmative` strategy, access will be granted. But with the `unanimous` strategy, you effectively have to have both roles to be granted access.

I think, the documentation should be updated to reflect this. PR welcome. 🙂 

My recommendation to solve your issue would be to not vote on more than one attribute at a time. There are two ways to achieve this:

* Vote on permissions instead of roles. This gives you more control over how roles should be taken into account. You would implement a custom voter that queries `ROLE_1` and `ROLE_2` and grants access if one of the roles is present (or any other logic you like, really).
* Work with role hierarchies. This way, you can create a new virtual role that users will automatically be awarded if they posess either `ROLE_1` or `ROLE_2`. Checking for that new role should have the effect you want.

**Comment by simonberger** [comment]
@derrabus  Thank you for your detailed response. I debugged the current behavior as well and I think updating the documentation would be helpful.
Still I want to at least question why the behavior has been changed in that way.
To be  precise what I mean here the scenarios in more detail.

1. Vote on an action with an expression for ROLE_USER or ROLE_ADMIN
    
    **What happens?**
    - Voter1 grants access to both roles
    - Voter2  grants access to ROLE_ADMIN but denies access to ROLE_USER
Because we have an 'or' expression here access is stil granted

2. Vote on access_control entry `- { path: ^/, roles: [ ROLE_USER, ROLE_ADMIN ] }`

    **What happens?**
    - Voter1 does not support it
    - RoleVoter grants access to ROLE_ADMIN but denies access to ROLE_USER

The documentation states that those permissions are 'or'-linked. 
`unanimous` shall change how the decision of **different** voters is handled. This is also how it works in the first scenario but not how it works for the access_control. It has been changed (most likely) to fix this mentioned CVE.

Let's assume a scenario 3 which could have existed before Symfony 4.4 which would be really bug.

3. Vote on access_control entry

    **What happens?**

    - Voter1 grants support to ROLE_ADMIN -> user is authenticated
    - Voter2 would deny access to both but is not checked

I do not understand why it should be correct or is even necessary that scenario 2 works the way it does. Instead of changing voters from 'or' to and 'and' it silently changes access control roles that way.

**Comment by derrabus** [comment]
> Vote on an action with an expression for ROLE_USER or ROLE_ADMIN

The big difference is that with

```
@Security("is_granted('ROLE_1') or is_granted('ROLE_2')")
```

you trigger a vote on that expression and not directly on the roles itself. This totally bypasses the voter strategy because `ExpressionVoter` decides how the individual votes for both roles will be combined into a single atomic vote for the whole expression. By the way, if that solves your problem, you can just use expressions in your access control list:

```YAML
access_control:
    - { path: ^/some/path$, allow_if: "is_granted('ROLE_1') or is_granted('ROLE_2')" }
```

> `unanimous` shall change how the decision of **different** voters is handled.

No, that's not how it works. The strategy makes a decision based on **all** votes cast, no matter what voters they're coming from.

**Comment by derrabus** [comment]
I'm going to close this issue now because the current behavior is expected and we can hardly change it now without breaking existing applications in very harmful ways. 🙈 

Please feel free to open an issue on the symfony-docs repository. A PR to fix the documentation is also more than welcome, of course.
