### ISSUE TITLE
[TwigBridge] bootstrap_5_layout Errors does not appear

### ISSUE THREAD

**Issue by ben29** [symfony/symfony#41349]
when using bootstrap 5 layout

the error message will not appear at all.

```
{{ form_label(form.fiat) }}
{{ form_widget(form.fiat) }}
```

even doing:

` {{ form_errors(form) }}`

no errors at all.

<img width="918" alt="t" src="https://user-images.githubusercontent.com/343681/119096051-c3fdb700-ba1b-11eb-9af5-2d39e80e1101.png">

on bootstrap 4 layout there is:

https://github.com/symfony/symfony/blob/67e56facd0c0543088c652a8d530a45993053c52/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig#L260

and:

https://github.com/symfony/symfony/blob/67e56facd0c0543088c652a8d530a45993053c52/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_4_layout.html.twig#L264

which missing on bootstrap 5 layout

https://github.com/symfony/symfony/blob/67e56facd0c0543088c652a8d530a45993053c52/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_5_layout.html.twig#L257-L274

when I just did:

`form_themes: ['bootstrap_5_layout.html.twig', 'fix.html.twig']`

and put bootstrap 4 block form_label on fix.html.twig

everything is works fine

**Comment by micheh** [comment]
Which function do you use to render the field? The errors are now displayed after the widget (when using `form_row`) and are no longer included in the label.

**Comment by ben29** [comment]
@micheh 
```
{{ form_label(form.fiat) }}
{{ form_widget(form.fiat) }}
```

even doing:

` {{ form_errors(form) }}`

no errors at all.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by Martin-P** [comment]
Just ran into this issue as well when migrating from Bootstrap 4 to Bootstrap 5.
For documentation purposes: issue is as @micheh says (https://github.com/symfony/symfony/issues/41349#issuecomment-845825546). You need to render form field errors separately now.

My custom form rendering Twig code for Bootstrap 4:
```
{{ form_label(form.emailAddress) }}
{{ form_widget(form.emailAddress) }}
```
My custom form rendering Twig code for Bootstrap 5:
```
{{ form_label(form.emailAddress) }}
{{ form_widget(form.emailAddress) }}
{{ form_errors(form.emailAddress) }}
```

> even doing:
>
> {{ form_errors(form) }}
>
> no errors at all.

Correct. Had to look it up, but is mentioned in the docs: https://symfony.com/doc/current/form/form_customization.html#form-errors-form-view
```
{# render any "global" errors not associated to any form field #}
{{ form_errors(form) }}
```
Because your error _is_ associated to any form field (`form.fiat`) it will not be displayed.
