### ISSUE TITLE
[Translation] Rename translation:update command

### ISSUE THREAD

**Issue by welcoMattic** [symfony/symfony#41411]
As Translation Providers feature has been merged into 5.3, I wonder if we should rename the `translation:update` command to `translation:extract`. Indeed, as we have now `translation:pull` & `translation:push` commands, the `update` is more ambiguous than before, as `pull` command will also *update* the catalogs.

WDYT about renaming this command on `translation:extract`? It has the advantage of reflecting **exactly** what the command does.

Could the renaming be done for 5.4 or 6.0? As we have to respect de BC promise, so deprecate the `update` command, then remove it.

cc @Nyholm @nicolas-grekas

**Comment by elfring** [comment]
>It has the advantage of reflecting **exactly** what the command does.

I got doubts about the supported functionality.

**Comment by dsentker** [comment]
I also think translation:update is ambiguous.

**Comment by javiereguiluz** [comment]
The new proposed name is definitely much better and precise! I can understand that this kind of changes are a bit annoying because you need to relearn the new command name and maybe change some things in your projects ... but, at the same time, this change looks like the right thing to do.

Maybe we could rename it to `translation:extract` in 5.4, while keeping `translation:update` as an alias (and, if technically possible, trigger a deprecation notice) and then in 6.0 remove the `:update` alias.

**Comment by welcoMattic** [comment]
@javiereguiluz that's exactly what I was thinking, in matter of deprecation and alias for 5.4. But I wonder if it's possible to introduce the `:extract`, `:update` alias and deprecation notice in 5.3.x as it's not a breaking change, keep this for 5.4 and completely remove `:update` in 6.0. It will let more time to people to change their applications/infrastructures. WDTY?
