### ISSUE TITLE
It's a good idea to wipe the password from memory.

### ISSUE THREAD

**Issue by void-azure** [symfony/symfony#41489]
Here a basic example:
```php
public function hash(string $plainPassword): string
{
    if ($this->isPasswordTooLong($plainPassword)) {
        throw new InvalidPasswordException();
    }

    if (\function_exists('sodium_crypto_pwhash_str')) {
        $generatedHash = sodium_crypto_pwhash_str($plainPassword, $this->opsLimit, $this->memLimit);
        sodium_memzero($plainPassword);
        return $generatedHash;
    }

    if (\extension_loaded('libsodium')) {
        $generatedHash = \Sodium\crypto_pwhash_str($plainPassword, $this->opsLimit, $this->memLimit);
        \Sodium\memzero($plainPassword);
        return $generatedHash;
    }

    throw new LogicException('Libsodium is not available. You should either install the sodium extension or use a different password hasher.');
}
```

This is just a possible example.

- https://www.php.net/manual/en/function.sodium-memzero.php

**Comment by nicolas-grekas** [comment]
Thanks for your interest in the component.

Since you're opening issues that might have some security-sensitivity, I would like to kindly ask you to [check our security policy](https://symfony.com/doc/current/contributing/code/security.html), just in case. TLDR, security-sensitive issues should not be reported publicly.

About the issue here, using `sodium_memzero` won't help, because PHP uses copy-on-write.
I'm therefor closing.

**Comment by void-azure** [comment]
Ok
