### ISSUE TITLE
symfony/console --no-ansi option removed but present in the logic

### ISSUE THREAD

**Issue by yaroslav-spryker** [symfony/symfony#41531]
**Symfony version(s) affected**: 5.3

**Description**
In the 5.3 version of the symfony/console we do not have the declaration of `--no-ansi` parameter anymore
https://github.com/symfony/console/blob/5.3/Application.php#L1039

BUT we have the logic with the check
https://github.com/symfony/console/blob/5.3/Application.php#L885
And in several places of this file as well.
Seems to be a bug or the code needs to be cleaned up.

**How to reproduce**
Execute the code similar to below with getting this option value
`$userOptions['colors'] = $this->options['no-colors'] || $input->getOption('no-ansi') ? false : $config['settings']['colors'];`

**Possible Solution**
To return back the definition of ` --no-ansi` parameter to the 
`Application:: getDefaultInputDefinition()`

**Comment by dereuromark** [comment]
https://github.com/Codeception/Codeception/pull/6216 had the same issue it seems, and they refactored their code.
But any tag before that one, and also any library that still relies on the 5.2 way seem to break now still.
```
Codeception PHP Testing Framework v4.1.21
Powered by PHPUnit 9.5.4 by Sebastian Bergmann and contributors.
Running with seed: 
                                        
  The "no-ansi" option does not exist.  
                                        
fixtures [--no-colors] [--silent] [--steps] [-d|--debug] [--no-exit] [-s|--skip SKIP] [-g|--group GROUP] [-x|--skip-group SKIP-GROUP] [--env ENV] [--seed SEED]
```

I agree that we should get some shimming back, so that the existing and currently working --no-ansi config also works in 5.3+.
