### ISSUE TITLE
LoginFormAuthenticator supports function does not validate

### ISSUE THREAD

**Issue by glukose** [symfony/symfony#41618]
**Symfony version(s) affected**: 5.3

**Description**
Right after starting a new project, the LoginFormAuthenticator supports function does not return true.
The values for :
`$this->getLoginUrl($request)` => **/project/public/index.php/login** and
`$request->getPathInfo()` => **/login** are not matching

**How to reproduce**
`php bin/console make:auth` and choose a LoginFormAuth
I run a dev environment on an apache2/mysql ubuntu distrib

**Possible Solution**
Reverting back to the previous condition or a derivative would work
`return 'app_login' === $request->attributes->get('_route')`

I guess the change was made for a reason, just surprising to have to override what seems to be the default behavior.

Cheers

**Comment by Dannebicque** [comment]
Hello,

I confirm the problem.
In a development environment, the index.php front controller is not taken into account for the comparison. Which makes the test wrong. @glukose  's solution did not work. But if I put 

```php
    public function supports(Request $request): bool
    {
        return $request->isMethod('POST') && $this->getLoginUrl($request) === $request->getRequestUri();
    }
```
the problem seems corrected.

But maybe I'm setting something wrong too, at least before I didn't have this problem with index.php.

**Comment by xabbuh** [comment]
If I understand the issue correctly, this should be reported in the MakerBundle, right?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
