### ISSUE TITLE
HTTP Foundation - Format HTML step

### ISSUE THREAD

**Issue by Nayte91** [symfony/symfony#41645]
Hello,
Here's the 'problems' that make me thinking about this feature :
   
1. I want a **well formated HTML** when sending, with perfect line returns, whitespace, indentations. When I look at the source code of a page generated by Symfony, I don't want to see a **cacophony**, as it is **embarassing** to present some flawed html,
2. I don't want to fight with Twig too much to reach such a common and framed result, so **whitespace trimming**, **line whitespace trimming**, **spaceless** variations of my {% %} and {{ }} blocks are **low value** fights.

So I wonder how much it can take for a PHP function to format HTML - after Twig templating work and before sending response - the standardized way ? How much cost for a auto [https://webformatter.com/html](https://webformatter.com/html) handled on serv side ?

**If this is affordable** in term of milliseconds, I feel like it can be a good tradeoff; get **rid of some complexity in Twig API**, letting developers to indent the template files **the way they want**, and still provide a **perfectly formated result** if they want to. In every way it reduces the mind burden for designer and improve DX.

I guess this Feature Request can fit more on the HTTP-Foundation side. Maybe having a new config entry 'html formater' (default = false) that makes the AbstractController->render() method to format body before sending ? I feel like it's not relevant as a parameter on the method, as you either want every one of your pages well formated, or you don't care at all.

I guess this can be extended at some point to AbstractController->json().

Thank you for your time considering this,

**Comment by Nek-** [comment]
Hi! Thanks for trying to contribute to Symfony.

I'm sorry but I really think having a "nice" HTML output is an edge case that Symfony can't support. (any feature means maintenance and time from contributors, it's not possible to do something that most people will not use).

Actually, a more useful thing could be to compress significantly HTML to make it either unreadable or just faster to load, and some bundles and libraries already provide this feature. And it's done on JSON by default.

If you really want this kind of feature as well as some people, you should try to make a bundle, that's why they exist!

Sorry to disappoint, I hope you understand why it will not be possible.

**Comment by Nayte91** [comment]
Hello,
Thank you for taking time considering my idea, no matter what is the outcome. Let me try to argue with some points, as I want to be sure this is rejected for the good reasons :)

1. There is a discrepancy in philosophy if you compare what you say (not an objective, edge case, flow is actually more about minifying, ..) and the fact that exists on Twig some options like spaceless, {%~blocks %} and {{- dash }}. Either anyone, anywhere doesn't care about formating HMTL and we can save time to maintain this, or, in some case and for some people, having beautiful HTML is something worth. No matter what answer do you choose, there is an accorded move.
2. HTML_modifier: none (default), minify (yours), beautify (mine). Kind of a choice :)

I'm searching the best for DX, and the 1. bugs me; fighting with ~, - and standardized indents in twig files to produce proper html is not very 20's friendly, and http foundation can give a solution.

I'm out of arguments after those ones !

Thank you again for taking time,

**Comment by Nek-** [comment]
I really think this kind of thing cannot come directly from Symfony. If a popular bundle was about it (either minifying or beautifying) we could think about it.

I think really not many people are into formatting output because it takes CPU time while we're trying to get performance.

But if you want to do it on your bundle it's actually easy. It's just a listener you add on `kernel.response` event. A bundle should be easy to make for it.

**Comment by ro0NL** [comment]
>  it is embarassing to present some flawed html

This is just an opinion. Not sure what we are solving... given debug tools solve it for us.

**Comment by fabpot** [comment]
Regarding the ~ and - modifiers in Twig, keep in mind that Twig is NOT just for HTML. Having these modifiers in Twig is mainly to be able to control indentation in other formats like YAML where it does matter.
For HTML, there is no need to control the whitespace characters, and like already said, it is consuming CPU for something machines do not care about.
That's why the feature you want does not exist in Symfony and will never as this is probably a niche.
If you really want to do it, Symfony already has the right hook via the response event, or the controller one if you want more flexibility.
Let's close as this is out of the scope of the Symfony vision.
