### ISSUE TITLE
[EventDispatcher] Question about RemoveListenersPass configurability in 6.0

### ISSUE THREAD

**Issue by tscni** [symfony/symfony#41698]
**Symfony version(s) affected**: 5.3, 6.0

**Description**
Not specifically a Bug report but more of a question about a change.

https://github.com/symfony/symfony/pull/40468 and https://github.com/symfony/symfony/pull/41358 deprecated / remove configurability from EventDispatchers RegisterListenersPass. The default configuration is a bit specific to the FrameworkBundle though (e.g. requires the `event_dispatcher` service id) and usages outside of that might very well have to configure them differently (e.g. I use `EventDispatcher::class`).

I'd prefer if I could still configure it (service id and listener tag in my case) directly. Having to add a decorator seems a bit cumbersome.
But if all these compiler passes are meant to be tied to the FrameworkBundle, shouldn't they be moved there instead?

Also:
- I'm a bit disappointed that you didn't add an entry to the UPGRADE documents for these.
- I suspect the corresponding documentation might be forgotten:
https://github.com/symfony/symfony-docs/blame/6.0/components/event_dispatcher.rst#L257-L263

**Comment by stof** [comment]
@tscni in a world where auto-configuration is the expected DX rather than manually tagging services to register them, maintaining a separate service being an instance of the EventDispatcher is *significantly* worse than dispatching events in the `event_dispatcher` service registered by FrameworkBundle, because it requires registering listeners manually with a separate tag. That's why reusing the compiler pass with different ids has been deprecated: we don't want to encourage such practice anymore.

**Comment by tscni** [comment]
I see. Thanks for the insight!
