### ISSUE TITLE
[Security] Validating a CSRF token in the test environment doesn't work

### ISSUE THREAD

**Issue by YaFou** [symfony/symfony#41757]
**Symfony version(s) affected**: 5.3

**Description**

Generating a CSRF token in a test and check if it is valid doesn't work.
> Test
```php
$client = self::createClient();
$token = self::getContainer()->get('security.csrf.token_manager')->getToken('id')->getValue();
$client->request('POST', '/test', ['token' => $token]);
self::assertSame('valid', $client->getResponse()->getContent());
```
> Controller
```php
/**
 * @Route("/test")
 */
public function __invoke(Request $request): Response
{
    $tokenValid = $this->isCsrfTokenValid('id', $request->request->get('token'));

    return new Response($tokenValid ? 'valid' : 'invalid');
}
```

**How to reproduce**

[Reproducer](https://github.com/YaFou/symfony-csrf-test)

**Possible Solution**

I will search one and open a PR if needed

**Additional context**

Is related to #41046

**Comment by yann-eugone** [comment]
I ran into the same issue (I think).
I've found that the code responsible for the issue is : [SessionTokenStorage::getSession](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Security/Csrf/TokenStorage/SessionTokenStorage.php#L135).
The thing is that at the moment we are generating the token (beginning of a web test case) the request stack is empty.

The workaround proposed in #41046 is to let the page that generate the token do the job, but it is not always possible. 

I have a controller that allow preview of an entity enforced via a csrf token, the link to this resource might have been generated from various location, so I decided to generate it myself in the test case.

Any idea on how to fix this ?

**Comment by YaFou** [comment]
A possible solution is to inject a false request in the request stack during tests but it seems to be weird. I don't know how to fix it properly...

**Comment by yann-eugone** [comment]
Yeah, but if you inject a fake request during the test, it will become the "main request"... The test might have unexpected results.

Maybe something like 

```php
$csrf = self::getContainer()->get('security.csrf.token_manager');
$stack = self::getContainer()->get('request_stack');
$stack->push(new Request());
$token = $csrf->getToken('id')->getValue();
$stack->pop();
```

will do the trick, but this is...

-----

edit, I tried, and no this is will not be a workaround solution (csrf still invalid, even when providing request session object)
