### ISSUE TITLE
[Form] Allow hexadecimal colors with 3 characters in `ColorType`

### ISSUE THREAD

**Issue by YaFou** [symfony/symfony#41785]
**Description**

A new option was introduced in #36302 called `html` which validates if the color respects HTML rules about hexadecimal colors. This takes into account colors like `#FFFFFF` or `#06CD8E`.

---
However, it is very common to find colors formatted like the following example: `#FFF`. But this format isn't valid in the `ColorType`. Perhaps, it will be nice to have the support of this format.
Moreover, there is another format, less popular, which takes into account the alpha channel: `#FFFFFFDD` but I don't know if it is worth to support it.

**Comment by derrabus** [comment]
Does HTML5 allow any of those formats in `<input type="color">`?

**Comment by stof** [comment]
No it does not. The HTML spec only supports simple colors for this input, which is a concept defined here: https://html.spec.whatwg.org/#simple-colour

> A **simple color** consists of three 8-bit numbers in the range 0 to 255, inclusive, representing the red, green, and blue components of the color respectively, in the 'srgb' color space.
>
> A string is a **valid simple color** if it is exactly seven characters long, and the first character is a U+0023 NUMBER SIGN character (#), and the remaining six characters are all ASCII hex digits, with the first two digits representing the red component, the middle two digits representing the green component, and the last two digits representing the blue component, in hexadecimal.
>
> A string is a **valid lowercase simple color** if it is a valid simple color and doesn't use any characters in the range U+0041 LATIN CAPITAL LETTER A to U+0046 LATIN CAPITAL LETTER F.

**Comment by YaFou** [comment]
Yes I know that the specification considers that only seven characters colors are valid but I think it could be nice to support other common variants of this format.

**Comment by stof** [comment]
well, that `html` option is precisely there to allow enforcing that the value is one conforming to this HTML definition for the `<input type="color">`. If that's not what you need, don't enable that option.

**Comment by YaFou** [comment]
Do you think that adding another option to support more formats could be an interesting feature?

**Comment by stof** [comment]
What other option do you want ? If you don't turn on that option, the Form layer won't perform any validation on its own (btw, you should probably not even use a ColorType because you will want to use a `<input type="text">` to allow inputting other kind of colors in modern browsers). And then, the validation layer is all yours by using custom constraints in the Validation component.

**Comment by YaFou** [comment]
I want an option (like `soft_html`) that validates colors like `#FFF`.

**Comment by YaFou** [comment]
Yes, of course, I can use the default type and use a regex but I think using the `ColorType` is more appropriate.

**Comment by derrabus** [comment]
> I want an option (like `soft_html`) that validates colors like `#FFF`.

👎🏻 from me. If HTML5 does not support those formats, then `ColorType` shouldn't either. 

Form types should not come with built-in validation. The only reason why `ColorType` does have a built-in validation is because it implements the HTML5 standard that way. No browser on earth implements what you call `soft_html`, so you will end up with a custom form control on the client side anyway.

Different formats could be implemented by adding a new `Color` constraint to the validator component.

**Comment by stof** [comment]
> Yes, of course, I can use the default type and use a regex but I think using the `ColorType` is more appropriate.

If you don't use the TextType, browsers won't let you submit other values, because ColorType renders a `<input type=color>`. So in the form component, there is no point about other things.

**Comment by javiereguiluz** [comment]
@YaFou thanks for suggesting this proposal, but I'm afraid we must close it. In order to have full compatibility with the fields created by browsers, we need to follow the standard strictly. Thanks for understanding!

However, I understand your needs ... we even have a pending PR to add a more powerful validator for all kinds of CSS colors (see #40168) so that could help you build a custom input and validate it as a CSS color. Cheers!

**Comment by YaFou** [comment]
Thank you for the discussion and @javiereguiluz for the provided opened PR!
