### ISSUE TITLE
Duplicate interfaces UserPasswordHasherInterface and PasswordHasherInterface

### ISSUE THREAD

**Issue by crtl** [symfony/symfony#41886]
**Description**
In symfony 5.3 there are 2 interfaces for password hasher:
- [Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface](https://github.com/symfony/symfony/blob/20de32eabadde889f260caeed12a38ed02dca417/src/Symfony/Component/PasswordHasher/Hasher/UserPasswordHasherInterface.php)
- [Symfony\Component\PasswordHasher\PasswordHasherInterface](https://github.com/symfony/symfony/blob/20de32eabadde889f260caeed12a38ed02dca417/src/Symfony/Component/PasswordHasher/PasswordHasherInterface.php)

Those interfaces implement the same methods except `PasswordHasherInterface` includes the actual method signatures where as `UserPasswordHasherInterface` only defines methods in doc comments.

There is no clarification on what interface to use or if any is depreacted.

To my understanding only `PasswordHasherInterface` should be used because `UserPasswordHasherInterface` has no method definitions and is therefore unsafe to use.

**Solutions**:
- `UserPasswordHasherInterface` should be removed, or
- `UserPasswordHasherInterface` should extend `PasswordHasherInterface`

**Comment by wouterj** [comment]
`UserPasswordHasherInterface` is new and uses PHPdoc methods for backwards compatibility reasons. Implementations of this interface will have these methods (a deprecation notice is triggered otherwise). In Symfony 6, these PHPdoc methods are transformed into real method definitions.

`PasswordHasherInterface` does what it says: it hashes a string representing the password. https://symfony.com/doc/current/components/security/authentication.html#creating-a-custom-password-hasher

`UserPasswordHasherInterface` knows which hasher to use to hash/validate the password for a user (note the different is signature): See https://symfony.com/doc/current/security.html#c-hashing-passwords
