### ISSUE TITLE
Authenticator does not support the request.

### ISSUE THREAD

**Issue by fluxion8** [symfony/symfony#42044]
**Symfony version(s) affected**: 5.3

Login form is working on  "/login" route.But /admin/login route doesnt work.Just refreshing without error.Nothing happen.

Everything is working excepted.But until supports function return true.
`    public function supports(Request $request): bool
    {
        return true;
    }`
I overrided function and return true.But still same  "Authenticator does not support the request." message displaying again in logs.This message must be display only supports method return false.

**Comment by chalasr** [comment]
The information you provide do not allow us to reproduce the issue.
Please consider creating a small project with enough code to reproduce the bug (see https://symfony.com/doc/current/contributing/code/reproducer.html#reproducing-complex-bugs).

**Comment by fluxion8** [comment]
Thank you for your concern.I tried with new project. supports method override working.Could there be any other situation affecting the operation of this function?

**Comment by chalasr** [comment]
You're welcome. 

> Could there be any other situation affecting the operation of this function?

Probably yes, but we can't guess what. We definitely need to be able to reproduce the reported issue in order to consider it's a bug. 
Please do more debugging on your side an once you can reproduce, comment here so that we can consider to reopen and eventually start investigating. 
Also check our support platforms: https://symfony.com/support.
Closing meanwhile. Thanks
