### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by farshid-ahmadian** [symfony/symfony#42169]
hi ,i use laravel 8 and the last version of symfony.
when i try to use Accessor for a float value  
```
public function getAmountAttribute($val)
    {
        return number_format($val, 2);
    }
```
this error shows me:
`A non well formed numeric value encountered`
i think this error is bug in your package 🌺🌺

**Comment by javiereguiluz** [comment]
In order to help you, you'll need to provide more details about the error. In your example, `getAmountAttribute()` is a custom function and `number_format()` is a built-in PHP function, so there's no Symfony code being used.

Ideally, create a bug reproducer as explained in https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by xabbuh** [comment]
I am closing here as this does not seem to be related to Symfony. If you disagree, please create a small example application that allows to reproduce the issue and we can consider to reopen.
