### ISSUE TITLE
Expose Console/Application::$dispatcher

### ISSUE THREAD

**Issue by xepozz** [symfony/symfony#42336]
Because of https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Console/Application.php#L67 isn't final it can be extended.
It would be great to have an access to the `$dispatcher` property in child class.
[Now we need to override `setDispatcher()` method to have an access to the dispatcher.](https://github.com/yiisoft/yii-console/blob/master/src/Application.php#L29)
Also it would be great if you patched another versions too. At least 5.1 and greater.

**Comment by derrabus** [comment]
Can you elaborate why you would want to access the application's dispatcher?

**Comment by xepozz** [comment]
I want to have an access to the $dispatcher property in child class.
Now I need to override method and declare own property in child application class.
It looks a little duplicated ;)

**Comment by javiereguiluz** [comment]
@xepozz thanks for this proposal ... but I think @derrabus is asking why you need this feature because there might be already a solution for this.

*"I want to access to the $dispatcher"* is HOW are you solving the problem ... but we need to know WHAT is the problem (e.g. *"I need to generate a custom log message before running each application command"*). Thanks!

**Comment by wouterj** [comment]
Hi @xepozz.

Making properties non-private adds some maintenance overhead (i.e. we can't rename the property or change its type). This is why we always want to judge whether it's worth opening something up. For now, I'm going to close this issue as it's not clear why this might be wanted.

If you just didn't have time to answer, it's 100% OK to still comment on this issue. The reopen action is only one click away :)

Thanks!
