### ISSUE TITLE
Ability to start & stop SMTP connection when needed

### ISSUE THREAD

**Issue by phamviet** [symfony/symfony#43237]
**Description**
I am using Mailer in Messenger worker long lived process with AWS SES SMTP interface and it keep throwing error:
> Expected response code "250" but got code "451", with message "451 4.4.2 Timeout waiting for data from client.

I know i can get rid of this error by setting `ping_threshold: 0`  but it is not efficient since the transport have to ping server on every email sending out. It is better to manually stop transport connection when Messenger message get handled (with all emails are sent out) and it will auto start on next message handling. But the problem is SmtpTransport `start` & `stop` methods are private and i have no way to access them.

**Comment by dvaeversted** [comment]
Related to this missing possibility to manually stop a transport, is in long running jobs/workers where it only ever sends emails occasionally, you will end up having a constant connection open towards an SMTP server.

Not all servers like this, so in changing over from swiftmailer, we are currently debating whether we need to destroy the mailer after each iteration since the stop() method is called in the destructor.

**Comment by fabpot** [comment]
Looks like a legit use case indeed. Is anyone willing to make start/stop methods public in a PR for 6.1?

**Comment by dvaeversted** [comment]
I am willing to give it a go today :-)

**Comment by jul6art** [comment]
Hi @fabpot is there an equivalent for 5.4 symfony LTS version?

**Comment by xabbuh** [comment]
@jul6art You'll need to update the component to Symfony 6.
