### ISSUE TITLE
[DependencyInjection] CheckTypeDeclarationsPass does not validate deprecated services (in lint:container)

### ISSUE THREAD

**Issue by simonberger** [symfony/symfony#43263]
**Symfony version(s) affected**: 4.4, 5.3

In this bug report I mean the usage of the pass in the `lint:container` usage. I am not aware of other usages.
When calling `lint:container` it won't report broken services that are marked as deprecated.

If the service is deprecated it calls the parent `processValue` function and with this skips the validation.

```php
if (!$value instanceof Definition || $value->hasErrors() || $value->isDeprecated()) {
    return parent::processValue($value, $isRoot);
}
```

**Comment by simonberger** [comment]
Had been done in this PR #39861
I am not sure the described effect here had been intended with the change.

```
$container->register('broken_service', 'Not\AvailableClass')
    ->setDeprecated(true)
    ->setPublic(true);
```

This service is reported by the lint command without marked as deprecated but not when it is.

/cc @chalasr

**Comment by nicolas-grekas** [comment]
It looks like this is the intended behavior. Deprecated services are not checked on purpose since #39861

**Comment by chalasr** [comment]
This has been done to prevent autoloading of deprecated classes indeed, mainly because some Symfony core test cases use that compiler pass. The fact it avoids reporting invalid classes might be an undesirable side effect, given that a deprecated service must keep valid, thus must keep using an existing class. 

Maybe we can do better by e.g. making this opt-in, or catching deprecations when loading the class of a deprecated service. I'll have a look
