### ISSUE TITLE
@Assert\DivisibleBy(0.01) not working

### ISSUE THREAD

**Issue by CharlyPoppins** [symfony/symfony#43345]
**Symfony version(s) affected**: 5.2.12

**Description**
Float with value `10.12` fail validation when `@Assert\DivisibleBy(0.01)`

**How to reproduce**
```
git clone git@github.com:CharlyPoppins/sf-bug-with-divisible-by.git

symfony composer install

symfony server:start

POST on https://127.0.0.1:8000/test-model with JSON body
{
    "amount": 10.12
}
```

**Possible Solution**
- I need an additional config in the projet or in php.ini
- `fmod` can't handle this kind on test

**Additional context**
Problem happen in `vendor/symfony/validator/Constraints/DivisibleByValidator.php`
![Capture d’écran 2021-10-06 à 00 16 02](https://user-images.githubusercontent.com/7072633/136165121-6bef7496-357a-4fce-b2cf-f8ac5baca221.png)

**Comment by stof** [comment]
Well, divisibility rules for floats can bring quite weird results due to the floating point arithmetic itself (that's the same reason why `0.1 + 0.2 !== 0.3`): floating point numbers can represent exactly all numbers, and so you have rounding issues, for instance when implementing things like `fmod` which guarantees that `$remainder < $divisor` (and so it can return `$remainder = $divisor - 10**-16` instead of returning something like `- 10**-16` which would then be considered equal to 0 at 12 decimals).

**Comment by CharlyPoppins** [comment]
I'm not familiar with fmod... but I have already done something similar to handle float comparison.

Maybe something like this can be done ?

```
define('EPSILON', 0.00001);

if (is_float($value1) && is_float($value2)) {
    $remainder = $value1 / $value2;
    $rounded   = round($remainder);
    $delta     = abs($remainder - $rounded);
    if ($delta > EPSILON) {
        return false;
    }
}
```

**Comment by nicolas-grekas** [comment]
Would using `PHP_FLOAT_EPSILON ` work? Maybe you'd like to try a PR, using either the const of fmod() @CharlyPoppins?

**Comment by CharlyPoppins** [comment]
Hello, I'll try with `PHP_FLOAT_EPSILON ` and also propose a PR next time I'll work on this project 👍🏻
