### ISSUE TITLE
EventSubscriber - Subscribe to events with simple regex

### ISSUE THREAD

**Issue by AdrienBr** [symfony/symfony#43351]
**Description**

Hi,
I think it would be a good feature to subscribe to events either by name (like now) or by basic expressions like `foo.bar.*`, or `foo.*`

**Example**

Before : 
```
    public static function getSubscribedEvents()
    {
        return [
            OrderEvents::CREATED => ['orderHandler', 10],
            OrderEvents::PENDING => ['orderHandler', 10],
            OrderEvents::COMPLETED => ['orderHandler', 10],
            UserEvents::SIGNED_UP => ['userHandler', 10],
            UserEvents::UPDATED => ['userHandler', 10],
        ];
    }
```
After :
```
    public static function getSubscribedEvents()
    {
        return [
            'order.*' => ['orderHandler', 10],
            'user.*' => ['userHandler', 10],
        ];
    }
```

Please let me know if you find this interesting, maybe I could take some time to do it

**Comment by stof** [comment]
I fear this will have a big performance impact, because the needs of the event dispatcher is not to find the events for a given listener, but to find the sorted listeners for a given event (without knowing the full list of dispatched events in advanced, so we cannot turn a regexp into the list of matched strings eagerly).
The performance hit is not only due to the usage of a regexp during the event dispatching. It is also caused by the requirement to revert existing performance optimization that perform the sorting of listeners during the container building for all listeners registered through dependency injection (and so if you don't register new listeners dynamically for a given event, the event dispatcher does not need to perform the sorting at runtime at all as it never invalidates that sorted list).

**Comment by derrabus** [comment]
I never felt I needed something like this. And I fear that this feature would increase the component's complexity and impact its performance negatively.

I would advise against implementing it.

**Comment by AdrienBr** [comment]
Ok I understand the problem.

Thank you for your answers.

**Comment by xabbuh** [comment]
I have the same concerns as @stof and @derrabus. Given that I close here. Thank you for understanding.
