### ISSUE TITLE
Replace AppVeyor by Github Action

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#43394]
**Description**

Although I would really miss being logged as @fabpot:
<img width="413" alt="Screenshot 2021-10-11 at 15 58 31" src="https://user-images.githubusercontent.com/7502063/136802807-bbc212b8-818b-44f1-912b-44dc4b18d96a.png">

The AppVeyor build is constantly failing for some time now and AFAIK we can use GHA to achieve the same goal, hopefully with less problems.

Should we give it a try?

**Comment by nicolas-grekas** [comment]
The build is failing because the code is buggy. See #43239
Unless we have an issue with appveyor (which we don't AFAIK :) ), let's work on something that provides value :)

**Comment by wouterj** [comment]
One of the issues with Appveyor that we run into ever so often is the random job time limit causing a failure.

But I agree, there is not a real big problem. The reason it often fails is because the tests run on Appveyor have a very different nature from the other tests (windows, 32 bit, and with only minimal PHP extensions)

**Comment by stof** [comment]
and those different nature are something we want to keep (as they are tested on purpose), meaning that moving away from Appveyor won't avoid these failures.

**Comment by chalasr** [comment]
Makes sense.
