### ISSUE TITLE
[synfony/lock] v5.3.4 breaks PHP 7.x compatibility

### ISSUE THREAD

**Issue by iotch** [symfony/symfony#43409]
**Symfony version(s) affected**: not sure

**Description**
Recent `synfony/lock` release (5.3.4) breaks PHP 7.x compatibility. When using  component with the `"symfony/lock": "^5.0"` composer.json constraint, composer's autoloader complains on platform incompatibility despite on Lock's supported PHP versions from 7.2.5:

````
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.0.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.0. in D:\dev-packages\php\tolkam\application\vendor\composer\platform_check.php on line 24
````
This is caused by the following change compared to v5.3.2 - https://github.com/symfony/lock/commit/583dfedfab45c5022466eeb1fed11a786c688a25

**Possible Solution**
Refine `psr/log` version constraint required in Lock component's `composer.json`.

**Comment by stof** [comment]
This issue can only happen if you run `composer update` on PHP 8 and then run the project on PHP 7.4. That's totally the wrong usage of composer.

psr/log properly defines its PHP requirement, and symfony/lock supports all 3 major versions of psr/log. This means that if you run `composer update` on PHP 7.4 (or on PHP 7.2.5), composer will choose to install psr/log 1, because that's the compatible version.

We won't remove support for psr/log 2 and 3 just to account for projects misusing composer. That would remove benefits from projects using composer properly and preparing for upgrades to newer psr/log versions.

**Comment by iotch** [comment]
Good point, my bad, sorry!
