### ISSUE TITLE
[TwigBundle] Missing serializer service

### ISSUE THREAD

**Issue by rvanlaak** [symfony/symfony#44022]
### Symfony version(s) affected

5.3

### Description

The serializer service is no hard dependency in `TwigBundle`, but it does get mentioned in the service definitions.

### How to reproduce

* Checkout https://github.com/APY/APYBreadcrumbTrailBundle
* `$ composer install`
* `$ composer test`

### Possible Solution

Make the service definition that links `serializer` as argument conditional, like in the snippet above: https://github.com/symfony/twig-bundle/commit/44cbc0dfddd3eb4e8c20b19490d7122c6b58aaab#diff-709fe24cc6358a5694be87023a34c71ffe8378500cd0db6b45e0935db22da84fR165-R169

Or, move `symfony/serializer` from `require-dev` to `require` for the `framework-bundle`

**Comment by xabbuh** [comment]
The issue is that you make these two service definitions public in your test:

```php
$this->addCompilerPass(new PublicServicePass('|twig|'));
```

This in turn leads to the fact that they can no longer be removed by the compiler. Your tests pass once the compiler pass is being disabled.

That being said there is no issue in the Symfony code base, but you will have to adapt your test. So I am going to close here. Thank you for understanding.

**Comment by rvanlaak** [comment]
Thanks a lot @xabbuh , https://github.com/APY/APYBreadcrumbTrailBundle/pull/66 does indeed make the `master` branch green again.
