### ISSUE TITLE
[Cache] Failure with couchbase collection

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#44049]
### Symfony version(s) affected

5.4

### Description

In the CI we see a warning:
https://github.com/symfony/symfony/runs/4204456225#step:11:28

> [cb,WARN] (pcbc/pool L:37) The specified expiry duration 1668530562 is longer than 50 years. For bug-compatibility with previous versions of SDK 3.0.x, the number of seconds in the duration will be interpreted as the epoch second when the document should expire (#{effective_expiry}). Stuffing an epoch second into a Duration is deprecated and will no longer work in SDK 3.1. Consider using Time instance instead.

And a failure:
> 1) Symfony\Component\Cache\Tests\Adapter\CouchbaseCollectionAdapterTest::testExpiration
Failed asserting that true is false.
> src/Symfony/Component/Cache/Tests/Adapter/AdapterTestCase.php:169

And a warning:
> THE ERROR HANDLER HAS CHANGED!

To be investigated.

@ajcerezo since you contributed support for couchbase collection, maybe you'd like to have a look?

### How to reproduce

-

**Comment by ajcerezo** [comment]
Hi @nicolas-grekas ,

I am in charge of investigating and solving this problem.

**Comment by ajcerezo** [comment]
This problem occurs because couchbase made a change to the ttls calculation.

- SDK 2.3: Set the document expiration time in seconds. If it is greater than 30 days (606024 * 30), the server will interpret it as absolute UNIX time (seconds since 1970-01-01T00: 00: 00).
- SDK 3.0: The relative expiration time in seconds or the DateTimeInterface object for an absolute point in time.

**Comment by ajcerezo** [comment]
This problem occurs because couchbase made a change to the ttls calculation.

- SDK 2.3: Set the document expiration time in seconds. If it is greater than 30 days (606024 * 30), the server will interpret it as absolute UNIX time (seconds since 1970-01-01T00: 00: 00).
- SDK 3.0: The relative expiration time in seconds or the DateTimeInterface object for an absolute point in time.

**Comment by stof** [comment]
The solution would be that `CouchbaseCollectionAdapter::normalizeExpiry` return a DateTimeImmutable instance instead of an integer when producing an epoch.
Or maybe it should be removed entirely, as Couchbase 3.0 seems to have changed the max relative expiry to 50 years rather than 30 days.
