### ISSUE TITLE
Enable asserts when in dev mode

### ISSUE THREAD

**Issue by AurelC2G** [symfony/symfony#44118]
### Description

Since PHP 7, the behavior of the `assert()` function is determined by a couple of configuration directives, zend.assertions and assert.exception. When calling the ErrorHandler component's `Debug::enable()`, these directives get enabled, and assertions are evaluated and throw when broken (https://github.com/symfony/error-handler/blob/5.3/Debug.php#L32).

However, as far as I can't tell, symfony doesn't call `Debug::enable()`, even in debug mode. Would it make sense to enable this mode in dev by default?

**Comment by stof** [comment]
@nicolas-grekas was this lost when migrating to the runtime component ?

**Comment by nicolas-grekas** [comment]
Absolutely not. What's described in this ticket is just wrong...
Here is where the call is done in <= 5.2 app:
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.2/public/index.php

and where it's done since 5.3:
https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Runtime/Internal/BasicErrorHandler.php
(called from GenericRuntime)

I don't know what @AurelC2G means here.

**Comment by AurelC2G** [comment]
> and where it's done since 5.3: https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Runtime/Internal/BasicErrorHandler.php (called from GenericRuntime)
> 
> I don't know what @AurelC2G means here.

I wrote that `Debug::enable()` was not called (anymore) by Symfony, and that seems to be true then (and not "just wrong"). However you're right that `BasicErrorHandler::register()` does the same thing, hadn't noticed that.
The reason why asserts were not working despite that is that setting zend.assertions this way doesn't work anymore (has to be set in php.ini). Nothing we can do about that though...
