### ISSUE TITLE
[DEBUG] The method dump() is breaking layout

### ISSUE THREAD

**Issue by stiffroy** [symfony/symfony#44210]
### Symfony version(s) affected

5.3.10, 5.3.11

### Description

This is a strange issue that I am facing and can't figure out why. Whenever I am dumping a few values, it is breaking the layout of the error page and the profiler.

When scrolled down of an any page (in image it is an error page):
<img width="1790" alt="Screenshot 2021-11-23 at 00 50 28" src="https://user-images.githubusercontent.com/13282223/142952158-daa4a674-2b66-44cb-b35c-ceec4658a4ad.png">

NOTE: The pointer is not hovered over the profiler bar in the above image

And in the profiler page the `Debug` section looks like:
<img width="1791" alt="Screenshot 2021-11-23 at 00 41 44" src="https://user-images.githubusercontent.com/13282223/142952238-505910b8-51d0-413b-bc32-d32cfd6267c2.png">

Any idea why is this happening? Is it my code or the debug component that is causing this?

### How to reproduce

Not exactly sure but I hope  debugging a few things here and there in the code will show this. I have 14 dumps at the moment.

**Comment by stof** [comment]
I think this happens when your dumps are done for the HTTP requests loading the toolbar content (in ajax) and the profiler UI, for which the profiler is disabled and so the dumps are not sent to the DumpDataCollector but to the output.
This can indeed happen when you dump things in a kernel.request listener without any check to choose on which request it happens.

I don't really see what we can do here. /cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Nothing we can do here: there are places where collecting the dump cannot work, eg because it's too early or too late for the collection logic to work.
