### ISSUE TITLE
[ErrorHandler] Split class ErrorHandler functionality to independent: PhpErrorHandler, ExceptionHandler, FatalHandler

### ISSUE THREAD

**Issue by benbor** [symfony/symfony#44249]
### Description

AFAIK Symfony components are introduced as a framework agnostic reusable components. 

I really like feature of Symfony\ErrorHandler where we talk about handling PHP Engine errors. Log buffering, different level customisation, etc are very cool stuff.

But for non symfony framework project class ErrorHandler often does too many things. 
If project has it's own `exception_handler`  `ErrorHandler::register` can't be used, because it change project's exception_handler. 

### Proposal: 

Give possibility to use only one thing from ErrorHandler

### Example

```php
class ErrorHandler 
{ 
    public static function register() 
    {
           self::registerPhpErrorHandling();
           self::registerExceptionHandling();
           self::registerFatalHandling();
    }

    public static function registerPhpErrorHandling () { /* ... */}
    public static function registerExceptionHandling () { /* ... */}
    public static function registerFatalHandling () { /* ... */}
```

It is only one (imho most simple option). It may be any other implementation

**Comment by fancyweb** [comment]
Hello, thank you for your idea.

> If project has it's own exception_handler ErrorHandler::register can't be used, because it change project's exception_handler.

Yes but the project exception handler is called after Symfony's ErrorHandler exception handler, so it's not lost. Can you confirm it's working for you?

Splitting the `register` method  in order to use only one or two "handling" is not really possible because the methods are coupled. For example, `handleFatalError()` needs `ErrorHandler::handleException()` as the exception handler. `register` is a like a bootstrap method that setup everything correctly.

What is your use case exactly?

**Comment by benbor** [comment]
@fancyweb  thank you for fast answer! 

> Yes but the project exception handler is called after Symfony's ErrorHandler exception handler, so it's not lost. Can you confirm it's working for you?

I haven't check yet, but if it works, it sounds good for me. Let me close the issue. I'll reopen this again, if find something relevant
