### ISSUE TITLE
[Runtime] GenericRuntime: body data from php://input

### ISSUE THREAD

**Issue by erlangparasu** [symfony/symfony#44462]
### Description

Currently body data extracted from global variable `$_POST`,
i think will be better if `$_POST` as 'fields',
then `php://input` as 'body'
Thank you

https://github.com/symfony/symfony/blob/1d64ab2e5bbe8002a01bb044e8d9087c4db256a7/src/Symfony/Component/Runtime/GenericRuntime.php#L171

### Example

```php
return [
    'query' => $_GET,
    'fields' => $_POST, // +
    'body' => file_get_contents('php://input'), // +
    'files' => $_FILES,
    'session' => &$_SESSION,
];
```

or

```php
return [
    'query' => $_GET,
    'body' => $_POST,
    'body_raw' => file_get_contents('php://input'), // +
    'files' => $_FILES,
    'session' => &$_SESSION,
];
```

**Comment by nicolas-grekas** [comment]
Hi, thanks for the suggestion but I would advise against doing that.
The reason is that `php://input` might be arbitrary long and we'd better not buffer that stream in memory by default.
Also because I prefer to keep things as close as possible to PHP in this `$context` array.
Of course, using a value object could be a nice idea to improve the experience when dealing with inputs. This is what type-hinting for the `Request` class of `symfony/http-foundation` provides. You might want to use it instead.

**Comment by erlangparasu** [comment]
Without `php://input`, how we get JSON data? (eg. request header content-type `application/json`)

**Comment by erlangparasu** [comment]
@nicolas-grekas Any example to use type-hinting (`Request`) ?

**Comment by nicolas-grekas** [comment]
Just use `Request` as argument...
