### ISSUE TITLE
[Console] Autocomplete feature is not working when using alias

### ISSUE THREAD

**Issue by tarlepp** [symfony/symfony#44461]
### Symfony version(s) affected

5.4.0

### Description

If I use bash alias like;
```bash
echo 'alias console="/app/bin/console $@"' >> /home/dev/.bashrc
```

then autocomplete feature doesn't work when I try following;
```bash
dev@php-fpm:/app$ console ut [TAB]
```

but it works as expected when I use it like;
```bash
dev@php-fpm:/app$ ./bin/console ut [TAB]
```

### How to reproduce

See the description.

**Comment by tarlepp** [comment]
Also noticed that if I add that `/app/bin` to `PATH` env it doesn't work as expected.

**Comment by alessandro-podo** [comment]
bin/console se [TAB] works
php bin/console se [TAB] not working

**Comment by wouterj** [comment]
Hi! Thanks for the reports. Unfortunately, both of them are "can't fix" issues. As "application writers", the only thing we can do is provide a completion script to the shell. In the end, it's up to the shell's logic to run our completion script in the correct cases.

In bash, you configure the bash completion utility using the `complete` command: https://github.com/symfony/symfony/blob/d2600e8be8dcb1a1f06da4b7b9c43fe5a3b6f963/src/Symfony/Component/Console/Resources/completion.bash#L75

* `_sf_{{ COMMAND_NAME }}` is the completion function defined before it (for Symfony apps: `_sf_console`)
* `{{ COMMAND_NAME }}` is the shell program you want to bind this completion to, `console` in this case

I'm not sure why `/app/bin` in `PATH` doesn't work. As for aliases, I'm 90% sure that bash completion doesn't natively support aliases (e.g. Zsh and Fish do support it natively).

The same applies to `php bin/console`. In this case, the shell completion will try to find a completion function for the `php` program (and not the `bin/console` program - this is "just" an argument of the `php` program). As there is a lot more to the `php` program than just `bin/console`, we don't provide a completion script for it.

---

If there is someone with great bash skills that is aware of a way to make aliases work, please contribute or comment :) Otherwise, I'm afraid all I can do is close this one.

**Comment by tarlepp** [comment]
Imho - we should at least keep this open a bit more - maybe someone who has some insights for this would spot this easier.

**Comment by tarlepp** [comment]
Previously I used - https://github.com/bamarni/symfony-console-autocomplete - for this and it worked with `PATH` and `alias` solution - maybe there is something that could help with this one.

**Comment by wouterj** [comment]
That's interesting. Which install method did you use for the autocomplete functionality?

**Comment by tarlepp** [comment]
Just couple of things on my `Dockerfile_dev` - this is just for development and not used on production;

```
ENV PATH "$PATH:/home/dev/.composer/vendor/bin:/app/vendor/bin:/app/bin"

RUN composer --no-cache global require bamarni/symfony-console-autocomplete

RUN echo 'eval "$(symfony-autocomplete --shell bash)"' >> /home/dev/.bashrc
```

or did you mean how I setup  that Symfony autocomplete feature in my setup?

**Comment by mindaugasvcs** [comment]
Are you aware that autocomplete feature is provided by the shell at OS level?

**Comment by tarlepp** [comment]
> Are you aware that autocomplete feature is provided by the shell at OS level?

Yes, I know that - but when I was using that - https://github.com/bamarni/symfony-console-autocomplete - autocomplete also worked with `PATH` and `alias` use, so I think that `./bin/console completion bash` is missing something.
