### ISSUE TITLE
[HttpClient] Idle timeout reached with negative default_socket_timeout

### ISSUE THREAD

**Issue by caugner** [symfony/symfony#44477]
### Symfony version(s) affected

5.4.0

### Description

We have set PHP's configuration directive [`default_socket_timeout`](https://www.php.net/manual/en/filesystem.configuration.php#ini.default-socket-timeout) to `-1` (meaning infinite timeout), and noticed that all requests created with `symfony/http-client` failed with a "Idle timeout reached" exception.

This looked like https://github.com/symfony/symfony/issues/44198, but the issue persisted beyond upgrading from 5.3.7 to 5.4.0.

### How to reproduce

```php
ini_set('default_socket_timeout', '-1');
$response = \Symfony\Component\HttpClient\HttpClient::create()->request('GET', 'https://symfony.com');
dd($response->getStatusCode());
// Symfony\Component\HttpClient\Exception\TimeoutException with message 'Idle timeout reached for "https://symfony.com/".'
```

### Possible Solution

The `HttpClientTrait` falls back to the `default_socket_timeout` value from PHP:

https://github.com/symfony/symfony/blob/d2600e8be8dcb1a1f06da4b7b9c43fe5a3b6f963/src/Symfony/Component/HttpClient/HttpClientTrait.php#L162

However, the `TransportResponseTrait` does not seem to handle this well:

https://github.com/symfony/symfony/blob/d2600e8be8dcb1a1f06da4b7b9c43fe5a3b6f963/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L184

Consequently (I think), the following `usleep()` call is skipped:
https://github.com/symfony/symfony/blob/d2600e8be8dcb1a1f06da4b7b9c43fe5a3b6f963/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L312-L314

So curl may not have a chance to actually proceed with the request, and since no time is elapsed, `$elapsedTimeout` and `$timeoutMax` are still both `0`, causing the following `ErrorChunk`:

https://github.com/symfony/symfony/blob/d2600e8be8dcb1a1f06da4b7b9c43fe5a3b6f963/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L197-L199

### Additional Context

Originally posted here: https://github.com/meilisearch/meilisearch-php/issues/262

```
 Symfony\Component\HttpClient\Exception\TimeoutException: Idle timeout reached for "http://meilisearch:7700/indexes/projects/documents?primaryKey=id".
 
 /var/www/html/vendor/symfony/http-client/Chunk/ErrorChunk.php:62
 /var/www/html/vendor/symfony/http-client/Response/CommonResponseTrait.php:150
 /var/www/html/vendor/symfony/http-client/Response/TransportResponseTrait.php:55
 /var/www/html/vendor/symfony/http-client/Psr18Client.php:100
 (...)
```

**Comment by caugner** [comment]
Probably, the easiest solution would be to either update `HttpClientTrait` to set `$options['timeout']` to `INF` (or `null`?) if `ini_get('default_socket_timeout'))` is negative, or to update `TransportResponseTrait` to ignore negative timeout values.

**Comment by nicolas-grekas** [comment]
I never considered the timeout could be set to a negative value (I'm not sure it makes sense either to use infinite timeouts...)
I'd be fine turning them into something long enough. A (few) day(s) is already long enough IMHO, no need to use `INF` IMHO.
PR welcome.

**Comment by vyshkant** [comment]
I'm having a similar issue with this code:

```php
$response = $httpClient->request('GET', 'https://example.org');
$stream = $response->toStream();
```

the call chain is next:
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/CommonResponseTrait.php#L112
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/CommonResponseTrait.php#L116
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L67
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/CommonResponseTrait.php#L149
- https://github.com/symfony/symfony/blob/4b41d178e3c073e267f12d662d7f2536f0bf895a/src/Symfony/Component/HttpClient/Response/TransportResponseTrait.php#L193

where at the last point `$timeoutMax` equals `0`.

So in fact even though `-0.0` was passed to the last method, we still have `0` set to `$timeoutMax` at that point.

@fabpot is this an expected behavior? If no, should I create a separate issue for this?

**Comment by vyshkant** [comment]
the biggest problem is that I can't see a way to override this behavior: value `-0.0` is hardcoded, and it leads to `0` value of `$timeoutMax`

**Comment by nicolas-grekas** [comment]
Please open another issue yes, with a detailed description of what happens for you and a reproducer if possible

**Comment by stof** [comment]
to me, having `-0` being treated the same than `0` is OK.
