### ISSUE TITLE
Successful login doesn't redirect to requested page

### ISSUE THREAD

**Issue by svscherpenseel** [symfony/symfony#44508]
### Symfony version(s) affected

5.4.*

### Description

When requesting a secured page, I'm redirected to the login page as expected. However, after a successful login, I'm not being redirected to the previously requested page. I'm redirected to the homepage.

The session does seem to have the required attribute to make this work:

```
_security.main.target_path | "http://127.0.0.1:8000/some/secured/page"
```

Somehow, it looks like the referrer is being used, even though I don't use `use_referer`.

### How to reproduce

- Setup a fresh Symfony installation
- Use the built-in authentication system to create a login page and a secured page
- Go to the secured page and see how you're redirected to the login page
- Login and see how you're not being redirected to the requested page

### Additional Context

I'm using this basic security configuration:

```
security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: json-login
            form_login:
                login_path: login
                check_path: login
                default_target_path: account.index
            logout:
                path: logout

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
      - { path: /some/secured/page, roles: ROLE_USER }
```

**Comment by chalasr** [comment]
We'll need [a full reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) in order to help.

**Comment by gnito-org** [comment]
It is probably something in your Symfony config that's causing this behavior.

I'm using the vanilla built-in authenticator system of 5.4, and the redirect after login to the requested page works for me.

**Comment by emmanuelballery** [comment]
I'm using the `form_login` authenticator and I also lose my session right after I login since upgrading from `5.4.0` to `5.4.1`.

I reverted the change made in 36b466e0f2a7c4045e66ee27691721ea188afe76 and my app is now working as expected but I can't seem to reproduce this in a simple demo app - it must be related to another configuration (https://github.com/emmanuelballery/test-bug-login).

I also found out that removing the `framework.session.cookie_secure` configuration which was set to `auto` is fixing my issue (is it related to #44521 ?)

**Comment by gnito-org** [comment]
Mine works fine with 5.4.1 and 6.0.1. I've tried with and without remember me.

Could you please post the output of your ``./bin/console debug:config security`` of the app that loses the session?

**Comment by gnito-org** [comment]
@emmanuelballery Isn't [this](https://github.com/emmanuelballery/test-bug-login/blob/dab9e5a0c857ad2fd21eef5f42c6e0a72f8bbb30/config/packages/security.yaml#L25) the source of your issue? It's used to [ignore](https://symfony.com/doc/current/security/form_login.html#always-redirect-to-the-default-page) the previously requested URL.

**Comment by emmanuelballery** [comment]
Thank you, I'm aware of this option ; in my case the session is completely lost after login even though I can find its related file in my disk. I actually also used this `always_use_default_target_path` option to track the session right after a successful login and it was empty.

I'm actually curious to see if @svscherpenseel can remove his `framework.session.cookie_secure` config or locally revert the change from 36b466e0f2a7c4045e66ee27691721ea188afe76 to see if we have a common base for our issues.

**Comment by gnito-org** [comment]
If I cannot reproduce the issue, and neither can you using a small vanilla app, it probably suggests that it's something in your  app's config and/or code. Perhaps it's a carry-over from 4.4 that only now stopped working?

**Comment by emmanuelballery** [comment]
Please considere that I'm only here to see if there are common grounds between our issues. As I said, my apps are already patched, the culprit being something related to cookies and the `framework.session.cookie_secure` configuration. Reverting from `5.4.1` to `5.4.0` is fine ; removing this configuration is also working.

Feels like 36b466e0f2a7c4045e66ee27691721ea188afe76 is not something we should have allowed for a minor update since multiple issues are reported regarding this change. Another one popped up: #44541

As I'm not able to create a reproducer nor can I share my thousands of lines of code, I'm willing to spend time narrowing the possibilities. Let's wait and see if @svscherpenseel can play with `framework.session.cookie_secure`.

**Comment by verng95** [comment]
May be my problem also applies here #44546

**Comment by svscherpenseel** [comment]
Thanks for looking into this guys! I apologize for the delayed reply.

I thought I had misconfigured my firewall, but it does seem to be related to `framework.session.cookie_secure`. I had this set to `true`, while my local development environment doesn't use HTTPS. Changing this to `auto` seemed to have fixed the problem. I hope this is also the fix for the other guys.

Thanks @emmanuelballery for suggesting this!

**Comment by fritzmg** [comment]
The Contao Managed Edition already uses `framework.session.cookie_secure: auto`. While the session is still created over a secure connection, any log in attempt via `http://` for example does not create a session (and thus logins do not work for example) due to the changes in https://github.com/symfony/symfony/commit/36b466e0f2a7c4045e66ee27691721ea188afe76.

**Comment by xabbuh** [comment]
What is the state here? I have some difficulties actually rereading the issue if the problem persists and how to reproduce it if it hasn't been solved.

**Comment by emmanuelballery** [comment]
@xabbuh This issue is one in the many related to `framework.session.cookie_secure: auto` and is a duplicate of #44546 #44521 #44541

**Comment by xabbuh** [comment]
Thanks for the feedback. Let's close here then as we already have issues opened for this issue.
