### ISSUE TITLE
[Security][RFC] Manual reset of login throttle

### ISSUE THREAD

**Issue by gnito-org** [symfony/symfony#44545]
### Description

I can see a use case where login throttling is set to longer periods (e.g., 10 minutes), and you want to give support staff the ability to manually reset a fat-fingered user's login throttle instead of telling the person to make a sandwich and wait.

Perhaps something like a ``LoginThrottlingResetListener``?

**Comment by stof** [comment]
I see 2 reasons not to do it:

- it is quite hard to implement, because the way to actually reset the throttling depends on the implementation of the rate limiter (and the rate limiter component does not have any way to do that right now, and that would be hard to put in the interface too)
- from a security point of view, this is weakening your security, as the efficiency of your throttling is now tied to the resiliency of your support staff against social engineering
