### ISSUE TITLE
[Mail] Add interface to final class Transport

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#44607]
### Description

Since Symfony 5.4 the class `\Symfony\Component\Mailer\Transport` is final. We use this to build mail transports based on user configuration saved in the database. I would suggest here, that the class should have an interface, so we can archive the same method signatures.

### Example

See example decoration https://github.com/shopware/platform/blob/trunk/src/Core/Content/Mail/Service/MailerTransportFactory.php#L29-L49

**Comment by derrabus** [comment]
Can you elaborate why you need to extend the `Transport` class to implement your factory logic?

**Comment by shyim** [comment]
The problem for us is to be stay compatible to changes to the Transport class. Currently, it is called by the di config https://github.com/symfony/symfony/blob/6.1/src/Symfony/Bundle/FrameworkBundle/Resources/config/mailer.php#L36

When now a new method is added and this one is called, our code would break. Thats the reason why an interface could help here

**Comment by derrabus** [comment]
Well the idea of the `Transport` class is that it receives a list of transport factories that it iterates over to create the actual transport. For those factories, we provide an interface `TransportFactoryInterface` because that is the intended extension point.

Providing your very own implementation of the `Transport` class only makes sense if that extension point does not work for you. And in that case, that would be the problem to fix.

Can you try to work with `TransportFactoryInterface` instead and tell us why this does not work for your use-case?
