### ISSUE TITLE
Allow inheritdoc to suppress the deprecation error

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#44802]
### Description

I would like to use `inheritdoc` to suppress the error message that a return type is added in the future.  When I start adding return I need to be more explict so phpstan and psalm are compatible. So it's much easier to use inheritdoc 😅 

### Example

```
/**
     * @inheritdoc
     */
    public static function getSubscribedEvents()
    {
        return [
            EntityWrittenContainerEvent::class => [
                ['invalidate', 2000],
            ],
        ];
    }
```

**Comment by shyim** [comment]
It's pretty waste of time. 😞 for PRs like https://github.com/scssphp/scssphp/pull/525

**Comment by wouterj** [comment]
This feature was designed to explicitly not support `@inheritdoc`. See https://github.com/sebastianbergmann/php-file-iterator/pull/74#issuecomment-984546983 for some more background on this.

Also, the better suggestion is to add the real PHP type. Only if not possible (due to BC constraints in other open source packages or unsupported types in the used PHP version - like `object`) you can use the annotation to opt-out and say "I accept the risk that any upgrade of my dependencies can break this piece of code". This really is necessary, it's the only possible way to move towards a PHP ecosystem that is more typed (and thus better documented and less error-prone).
See https://wouterj.nl/2021/09/symfony-6-native-typing for a bit more information on the whole initiative (and patch tool Symfony made to make adding both real types and PHPdoc opt-outs as easy as possible).

**Comment by nicolas-grekas** [comment]
I confirm: this is by design and desired. A change like scssphp/scssphp#525 or https://github.com/composer/composer/pull/10404 is absolutely meaningful as it hints authors about changes they should plan to do.
