### ISSUE TITLE
[Form] Validation of empty entity will be ignored in CollectionType

### ISSUE THREAD

**Issue by UtechtDustin** [symfony/symfony#44871]
### Symfony version(s) affected

6.0.2

### Description

I have a Form which contains a `CollectionType` of Entities, the option `allow_add` is enabled.
If i add a new dataset in the frontend and submit the form, the new (empty) dataset will be ignored. Which means no validation happens and the method `isValid` returns `true`.
As soon i fill out atleast one input with at least one character anything works fine!

I searched in the documentation and found the option [delete_empty](https://symfony.com/doc/current/reference/forms/types/collection.html#delete-empty), which sound exactly like the behavior i have.
But i don't set this option!

I asked on slack and i discussed with @xabbuh, @DavidBadura and @benblub (Thanks for that!).
We are not sure if this is a bug or (in my opinion a strange) wanted behavior.

In my opinion the dataset should always validated, if a user add a new dataset in the frontend he does this for a reason, if he forgott to fill it out (for whatever reason), he should get a validation error as reminder.

### How to reproduce

I created a small test repository (https://github.com/UtechtDustin/collection-test) for this issue.

1. Clone the repository
2. Run the migrations
3. Open the site (path `/`)
4. Click on `Neue Kontaktdaten anlegen`
5. Click on submit
6. You see the "SAVED"-Response instead of validation messages.

### Additional Context

I tried to debug it, but i never worked with the internal symfony code so i don't found the issue.
In the Browser request and in the request class the (empty) dataset exists, after the method `handleRequest` of the `Form` the data is missing in `$form->viewData`.

A quick video what happens:

https://user-images.githubusercontent.com/13292481/147777511-6216fd3c-744c-4c06-a049-5e64ac6c1fb5.mp4

**Comment by fancyweb** [comment]
Not a bug for me. You are relying on on the default `FormType` `empty_data` callback (see https://symfony.com/doc/current/reference/forms/types/form.html#empty-data). Since the submitted entry is composed of only empty children and the entry is not required, the model data end up being null, so there is nothing to validate. You have two solutions:

1. If you want to keep the possibility to submit full empty entries, add the `empty_data => new Address()` option (either in `entry_options` in `ChildType` or directly in `AddressType`).

2. Otherwise, add `required => true` everywhere in `ChildType` (from the root options to `entry_options`).

**Comment by UtechtDustin** [comment]
Good to know, thank you for the quick answer ! :-)
