### ISSUE TITLE
Translations: incorrect domain using "t" function and named domain argument

### ISSUE THREAD

**Issue by noofaq** [symfony/symfony#44899]
### Symfony version(s) affected

5.4.2

### Description

Using `Symfony\Component\Translation\t` function and using named `domain` argument "translation:extract" and "debug:translations" use incorrect domain (default one `messages` is used).

### How to reproduce

```
class DAMFileNameTemplate extends Constraint
{
    public function getMessage()
    {
        return t('error.dam_file_name_template_evaluation', domain: 'validators');
    }
}
```

Calling `debug:translation` reports incorrect domain:
![obraz](https://user-images.githubusercontent.com/1412384/147960545-5fd73160-ae94-4323-b7bc-90b6c071eb4e.png)

Workaround:
```
class DAMFileNameTemplate extends Constraint
{
    public function getMessage()
    {
        return t('error.dam_file_name_template_evaluation', [], 'validators');
    }
}
```
Calling `debug:translation` reports correctly:
![obraz](https://user-images.githubusercontent.com/1412384/147960609-fad0902d-7bbc-4578-a434-a7732f6894cf.png)

**Comment by fancyweb** [comment]
Not a bug for me but probably an unimplemented case in the Translation PhpExtractor. Could you have a look?

**Comment by welcoMattic** [comment]
We discussed with @stof & @nicolas-grekas about adding support of named arguments in PhpExtractor. It seems to require to add a new optional dependency on https://github.com/nikic/PHP-Parser to leverage AST features and avoid to continue with tokens, especially since we will probably have to add support of some other syntax (like inline variable assignation, see https://github.com/symfony/symfony/issues/42285).
