### ISSUE TITLE
[Form] Handling entities reordering in collection type

### ISSUE THREAD

**Issue by maciej-pyszynski** [symfony/symfony#4492]
Symfony default behaviour for handling reordering in collection type is wrong.

When you reorder to items saved in database as:

id: 56, name: first, order: 0
id: 57, name: second, order: 1

After changing they positions I receive:

id: 56, name: second, order: 0
id: 57, name: first, order: 1

Instead of:

id: 56, name: first, order: 1
id: 57, name: second, order: 0

Last occurrence at version 2.0.15

**Comment by webdevilopers** [comment]
I'm not sure if my use case covers the original one by @maciej-pyszynski but I have a similar behaviour with the `choice` type:
```php
        $builder
//            ->add('item', 'entity', array(
            ->add('item', 'choice', array(
                'required' => true,
                'multiple' => true,
                'expanded' => true,
                'choices' => array(
                    1 => 'Element 1',
                    2 => 'Element 2',
                    3 => 'Element 3',
                    4 => 'Element 4',
                    5 => 'Element 5',
                    6 => 'Element 6'
                )
            ))
```

I'm using jQuery's Sortable to drag the choices into a sortable layer. My order on client side was 6, 1, 2.

When submitting the form I get the following dump - first one directly from `$_POST` with original order and the second one from `$form->getData()`:
![bildschirmfoto vom 2015-04-22 14 13 22](https://cloud.githubusercontent.com/assets/3479626/7274054/e187de94-e8f9-11e4-816b-0282505e2933.png)

I guess such a use case is handled more safely when using a hidden field to save the order on the client side using jQuery's `serialize` method.

But still I'm wondering if there is a way to keep the client order?

**Comment by danbettles** [comment]
I wanted the forms within a collection to come out in the order in which they were submitted; that's because the user is able to sort those forms.  I solved the problem by re-indexing the submitted data for the forms in the collection in a pre-submit handler registered in the form-type containing the collection.  This works just fine for me because the submitted indexes are of no consequence.

Not an ideal solution, for sure, but it might help someone coming to this issue with the same problem.

In `buildForm()` in your form-type, add something like the following.

```php
$builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
    $submittedData = $event->getData();

    if (!array_key_exists('offers', $submittedData)) {
        return;
    }

    //Re-index the array to ensure the forms stay in the submitted order.
    $submittedData['offers'] = array_values($submittedData['offers']);

    $event->setData($submittedData);
});
```

**Comment by chrisguitarguy** [comment]
@danbettles that was exactly my solution.

Maybe this isn't a issue with the from component -- there's a lot of room to go wrong with the sortable thing. Could be there just needs to be a bit of documentation on the subject that describes the solution.

**Comment by stof** [comment]
@webdevilopers a choice form does not preserve ordering.
Submitting an HTML form has no way to submit the order of selected elements. It does not even has this concept in the spec. Browsers generally add values in the order in which they appear in the DOM, but there is no requirement to do that. So if you need to save the order, you should indeed use a separate field for that.

**Comment by webdevilopers** [comment]
I was just wondering @stof because looking at the dump of my `$_POST` above the order of the client sorting will be correctly passed. In addition to that duplicates are allowed. So at least the symfony form field type does some handling on the `$_POST` submitted value.

So I guess the separate field is indeed the only solution to this use case.

**Comment by ryancastle** [comment]
@fabpot I think this can be closed? It seems that @danbettles solution or an explicit sorting field solve the issue, and I'm not sure what the Form component could do differently.

**Comment by webdevilopers** [comment]
Indeed I moved my solution to a collection which had an extra "position" field. Some Doctrine Sortable and the the everything was fine.

Any feedback on the statement I made about allowing duplicates at the end of https://github.com/symfony/symfony/issues/4492#issuecomment-95153781?

**Comment by Tobion** [comment]
@webdevilopers please do not mix different things in one ticket and rather create a new one for it.

**Comment by archy-bold** [comment]
Sorry to resurrect an old thread but was there ever a decent solution found to this? I'm using a Symfony form for an API and I'm having issues as a result of it overwriting entities if the order changes. For example, if the first element is deleted, the second element will overwrite the first.

I can't just re-index the data because I need to ensure the entity matches to an existing entity in the database. There's an ID value being sent through that I can use for this.

Thanks!

**Comment by ryancastle** [comment]
@archy-bold Not really. I think the best bet in your case is [hiding removed elements](https://github.com/symfony/symfony/issues/7468#issuecomment-64023956), instead of entirely removing the full block. Or [recording the index in a data field](https://github.com/symfony/symfony/issues/7468#issuecomment-192011499). Neither are lovely solutions, but they might get you there.

**Comment by archy-bold** [comment]
Thanks @ryancastle but that wouldn't work for me, given it's for an API I'm not actually ever creating the form, I'm just receiving the POST data.

My solution was to add an `indexBy` attribute to my `OneToMany` relationship and ensure the `allow_add` and `allow_delete` flags are set on the form collection. Then ensured that the collection is indexed by the column I specified with `indexBy` in the POST data, I ensured that column was a unique attribute that the remote service had access to. Finally you need `add[Entity]` and `remove[Entity]` functions on the entity on the left side of the relationship that remove elements from the right. Seems to work really well.

**Comment by Ziiweb** [comment]
Since @danbettles answer is working, don't you think is necessary to mention it in `CollectionType` docs? Im missing information about ordering in the `CollectionType` docs.

**Comment by gbourgeat** [comment]
@archy-bold What you use for indexBy ? Class identifier like "id" or you have add new field just for it ?

thks

**Comment by archy-bold** [comment]
@gbourgeat I used `originId`, which was an ID that was known to both sides of the API request.

**Comment by egonolieux** [comment]
The solution @danbettles proposed does not work if you have multiple nested forms. The child forms will still map to the old indexes for some reason. Even if the form data looks OK, it will still get mapped wrongly to the object. Any idea how to solve this?

**Comment by 01e9** [comment]
Because [this file](https://github.com/symfony/form/blob/836bb5edf9f8c2aef6320b39bab8cfa3981bfb3b/Extension/Core/EventListener/ResizeFormListener.php#L77-L79) is hardcoded [here](https://github.com/symfony/form/blob/836bb5edf9f8c2aef6320b39bab8cfa3981bfb3b/Extension/Core/Type/CollectionType.php#L43), the easies solution for me is to update the names via js

```js
<script>
  jQuery(function ($) {
    $('input[name], select[name], textarea[name]').each(function(i, input) {
      input.name = input.name.replace(/\[(\d+)\]/g, '[_$1]');
    });
  });
</script>
```

_The js that adds new collection items via prototype generates non-numeric names._
