### ISSUE TITLE
AnonymousToken doesn't adhere to TokenInterface

### ISSUE THREAD

**Issue by DrLuke** [symfony/symfony#44989]
### Symfony version(s) affected

5.4

### Description

In the `TokenInterface` the return type for `getUser` is [defined](https://github.com/symfony/security-core/blob/5.4/Authentication/Token/TokenInterface.php#L54) as  `UserInterface|null`, but `AnonymousToken` doesn't adhere to the interface, as it just [redefines](https://github.com/symfony/security-core/blob/5.4/Authentication/Token/AnonymousToken.php#L29) the type of `user` to  `string|\Stringable|UserInterface`, which `AbstractToken` will happily return as [it doesn't have a return type defined ](https://github.com/symfony/security-core/blob/5.4/Authentication/Token/AbstractToken.php#L93).

Now `AnonymousAuthenticationListener` goes ahead and [jams](https://github.com/symfony/security-http/blob/5.4/Firewall/AnonymousAuthenticationListener.php#L68) `'anon.'` as an user into an anonymous token.

This results in everything relying on the `TokenInterface` to fail, for example in the twig bridge:

```
Symfony\Bridge\Twig\AppVariable::getUser(): Return value must be of type ?Symfony\Component\Security\Core\User\UserInterface, string returned
```

### How to reproduce

Use `app.user` in a twig template and visit the page as an anonymous (logged out) user.

### Possible Solution

Use [new authenticator system](https://symfony.com/doc/5.1/security/experimental_authenticators.html)

**Comment by DrLuke** [comment]
AbstractToken also can not have `null` set as user, because it's prevented [here](https://github.com/symfony/security-core/blob/5.4/Authentication/Token/AbstractToken.php#L102)

**Comment by wouterj** [comment]
Hi @DrLuke!

What you're referencing are PHPdoc types. While these do document the contract, they can not produce fatal errors causing your app to break. Are you sure you're talking about errors, or are you talking about deprecations?

If it's the latter, then this is as expected. The code was changed in 5.4 to use `?UserInterface` instead of  `stringable|UserInterface`. PHPdocs always document the new API, and this automatically enables triggering deprecations when the old API is still used.
As for AnonymousToken, this class is deprecated in Symfony 5.4 so it's likely to trigger deprecations.

If it's really an error, it would be great if you can [create a reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html). My first (bold) guess would be that you somehow mix up TwigBridge 6.0 with Symfony 5.4 (as 6.0 does have the strict type definition for `AppVariable`, whereas 5.4 doesn't).

> AbstractToken also can not have null set as user, because it's prevented here

`NullToken` returns null (which is also the only use-case for null): https://github.com/symfony/symfony/blob/6b9fafb2c0ef84bfa7d17b3b37737c5da710bd0e/src/Symfony/Component/Security/Core/Authentication/Token/NullToken.php#L31-L34

**Comment by DrLuke** [comment]
Thanks for the great explanation! You are indeed correct, running `composer update` installed `symfony/twig-bridge` with version `v6.0.2`. Maybe the dependencies in the twig bridge bundle need to be adjusted then?
