### ISSUE TITLE
[Messenger] RejectRedeliveredMessageMiddleware Causes Class Not Found Errors on the Full Stack Framework

### ISSUE THREAD

**Issue by chrisguitarguy** [symfony/symfony#45003]
### Symfony version(s) affected

`>=5.1`

### Description

When one uses `"symfony/symfony": "^5.4"` in their composer.json to get the full stack framework, the `RejectRedeliveredMessageMiddleware` causes errors because it's tightly coupled to Amqp classes.

> The autoloader expected class "Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceivedStamp" to be defined in file "{redacted}". The file was found but the class was not in it, the class name or namespace probably has a typo. (500 Internal Server Error)

When requiring the messenger component directly, the amqp bridge is available: https://github.com/symfony/symfony/blob/bbe4105fe97d92f06a29f1289a6283bf2cbea67b/src/Symfony/Component/Messenger/composer.json#L21

but that requirement is not explicit in the root `composer.json`: https://github.com/symfony/symfony/blob/bbe4105fe97d92f06a29f1289a6283bf2cbea67b/composer.json#L34-L57

Feels like it should probably be there in the 5.4 release?

There is an open PR addressing the coupling issue targeting 6.1: https://github.com/symfony/symfony/pull/41749 but might be worth solving in 5.4 by making that depenency explicit for user of the full stack framework. I know that's frowned uppon now, but I suspect there's a lot of legacy apps out there with just `symfony/symfony` in their `composer.json` files.

### How to reproduce

Try to use messenger with symfony full stack >= 5.1 with messenger and without having `symfony/amqp-messenger` installed

### Possible Solution

Add `symfony/amqp-messenger` to the `symfony/symfony` `composer.json`.

**Comment by chrisguitarguy** [comment]
For anyone coming here with the same issue: work around is to `composer require symfony/amqp-messenger`

**Comment by mkilmanas** [comment]
That does not sound like a good workaround, since `symfony/amqp-messenger` in turn requires `ext-amqp`. Since I am not using any AMQP in my app, I can't see a justification for installing an extra lib and an extra php-extension just to make another lib/framework happy.

Moreover, code at [5.4](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpReceivedStamp.php) says `@deprecated since Symfony 5.1, to be removed in 6.0. Use symfony/amqp-messenger instead.` - yet it is already removed in 5.4 - what's up with that?

And why is `RejectRedeliveredMessageMiddleware` auto-enabled in the first place? How can we turn it off?

**Comment by nicolas-grekas** [comment]
That's because of a mix of 5.4 and 6.0 deps.
Use flex to precisely control indirect Symfony dependencies of your app.
Alternatively ensure symfony/amqp-messenger v5.4 is installed when using symfony/messenger v5.4. This one doesn't require ext-amqp.
This is solved in 6.0, but cannot be in 5.4 for BC reasons.
