### ISSUE TITLE
[DependencyInjection] `Target` parameter attribute does not work for controller methods

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#45021]
### Symfony version(s) affected

5.3+

### Description

When using the `Target` attribute for controller methods (on controller services tagged with `controller.service_arguments`) it is ignored.

### How to reproduce

```php
#[Route('/default', name: 'default')]
public function index(#[Target('doctrineLogger')] LoggerInterface $logger): Response
{
    // expect `$logger` to be `monolog.logger.doctrine` but it is app logger (`monolog.logger`)
}
```

**Comment by stof** [comment]
That's because injection in controller methods is not done by the autowiring itself (those methods are not called as part of the class instantiation managed by the DI component), but by the ServiceArgumentResolver, which does not magically inherit all features of the DI component.

Looking at it quicky, I think it would be fixed by using `Target::parseName($p)` instead of `$p->name` as the argument of the TypedReference on https://github.com/symfony/symfony/blob/6b9fafb2c0ef84bfa7d17b3b37737c5da710bd0e/src/Symfony/Component/HttpKernel/DependencyInjection/RegisterControllerArgumentLocatorsPass.php#L178
@nicolas-grekas can you confirm ?

**Comment by nicolas-grekas** [comment]
@kbond up to give it a try?
