### ISSUE TITLE
[Messenger] PostgreSQL: new messages are not picked up for 60 seconds

### ISSUE THREAD

**Issue by bendavies** [symfony/symfony#45056]
### Symfony version(s) affected

5.3 onwards

### Description

Hi,

There appears to be a bug in [PostgreSqlConnection](https://github.com/symfony/symfony/blob/6cdfd712b35fd129f8da6098eb0cfec5d4abe410/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/PostgreSqlConnection.php#L31) meaning that newly available messages are not picked immediately.

This is due to this line:
https://github.com/symfony/symfony/blob/6cdfd712b35fd129f8da6098eb0cfec5d4abe410/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/PostgreSqlConnection.php#L90

I really don't understand what that line is doing apart from being something to do with delayed message, but apart from that  don't understand it.

### How to reproduce

1. start your consume: `bin/console messenger:consume async -vvv`
2. queue some job via any means you like
3. this message will be consumed immediately
4. queue another message via any means you like
5. this message and all other new ones will not be picked up for 60 seconds after the message in 2. was consumed.

Simply: after the queue is emptied, new messages will not be picked up for 60 seconds because of `check_delayed_interval' => 60000`

### Possible Solution

Unsure, no idea what https://github.com/symfony/symfony/blob/6cdfd712b35fd129f8da6098eb0cfec5d4abe410/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/PostgreSqlConnection.php#L90 is meant to be doing.

### Additional Context

Found a related discussion #36990

**Comment by bendavies** [comment]
~~Secondly, and this is possibly related, but it seems to be that these default settings simply do not work and make `NOTIFY` support not work:~~
```php
'use_notify' => true,
'get_notify_timeout' => 0
```

~~since `get_notify_timeout` is zero, this line
https://github.com/symfony/symfony/blob/6cdfd712b35fd129f8da6098eb0cfec5d4abe410/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/PostgreSqlConnection.php#L85~~

~~returns immedately and never "waits" for a notification,  which seems to defeat the point of using listen/notify completely.~~

edited:
problem discovered here: https://github.com/symfony/symfony/issues/45056#issuecomment-1077584781

**Comment by Sajito** [comment]
I had the issue too, that the consumer picked up new messages only after 60 seconds. I also thought it might be due to the `get_notify_timeout` option, but it turned out having this option set to `0` works perfectly fine.
After some time I checked how the NOTIFY/LISTEN feature actually works and found that there should be a trigger on the `messenger_messages` table, which was missing for me. Have you checked if the trigger exists for you?

The 60 seconds delay is the default polling rate, when NOTIFY/LISTEN feature is not used. In my case the problem is actually sitting in this check, maybe it's the same in your case:
https://github.com/symfony/symfony/blob/acf1f713205c9cfcff2552d84a46c837f9d7bdcb/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/DoctrineTransportFactory.php#L51

I have installed the `sentry/sentry-symfony` bundle, which decorated the connection's driver, therefore the check `$driverConnection->getDriver() instanceof AbstractPostgreSQLDriver` fails and the NOTIFY feature is never actually set up.

**Comment by bendavies** [comment]
yes we have the trigger, and our problem is not sentry.

as per the OP, this line is the problem:
https://github.com/symfony/symfony/blob/6cdfd712b35fd129f8da6098eb0cfec5d4abe410/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/PostgreSqlConnection.php#L90

once the queue is emptied, new messages won't be checked for 60 seconds.

**Comment by Sajito** [comment]
That's not what that line does, because you're ignoring the first condition. The check is only delayed, if there is no notification or the notification is not related to the checked queue. Check the whole if and notice the `&&` at the end of line 88.

https://github.com/symfony/symfony/blob/6cdfd712b35fd129f8da6098eb0cfec5d4abe410/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/PostgreSqlConnection.php#L86-L91

If a notification for the queue is received, then the first part will fail and the delay-condition won't be checked.

So your issue must be caused either by the notification not being triggered, or the listen not being notified.

Edit: The method itself by default is actually called every second, which also if configurable with the `sleep` option.

**Comment by bendavies** [comment]
@Sajito thanks for your reply.

I've investigated again, and what I am finding is that the listener is being "lost".

the listener is setup here:
https://github.com/symfony/symfony/blob/6cdfd712b35fd129f8da6098eb0cfec5d4abe410/src/Symfony/Component/Messenger/Bridge/Doctrine/Transport/PostgreSqlConnection.php#L72

just above the `pgsqlGetNotify` line i have added:
```php
$listeners = $this->driverConnection->fetchAssociative('select * from pg_listening_channels();');
```
which correctly shows the listener the first time around.
on the 2nd time around, the listener is gone, and `pg_listening_channels()` returns `false.`

this appears to be why `pgsqlGetNotify` isnt' working.

now, need to figure out what's happening to the listener.

**Comment by bendavies** [comment]
and.. it's the `doctrine_close_connection` (`DoctrineCloseConnectionMiddleware`) middleware.

so the `PostgreSqlConnection` needs to detect that it is no longer listening and relisten

**Comment by dunglas** [comment]
Thanks for investigating @bendavies! Do you want to work on a patch?

**Comment by bendavies** [comment]
@dunglas yes, but...choices:

1. `PostgreSqlConnection` checks every single call to `get` if it is listening or not using `pg_listening_channels()`
2. `PostgreSqlConnection` listens on `Doctrine\DBAL\Events::postConnect` and relistens if required. there is unfortunately no event for closing the connection.
3. another way?

any preferences?

**Comment by goetas** [comment]
I have the same issue. What is the harm of querying `LISTEN xxxx` every the time in `get`? anyway is per-session and calling `LISTEN` multiple times is idempotent.

> https://www.postgresql.org/docs/current/sql-listen.html
> If the current session is already registered as a listener for this notification channel, nothing is done.

In that way it would be possible to stop keeping track of "are we listening or not" and remove the `$this->listening` prop. (eventually we can also `UNLISTEN` as soon as `pgsqlGetNotify` completes).

**Comment by bendavies** [comment]
Nice find. That sounds good

**Comment by bendavies** [comment]
I'll work on this next week

**Comment by mtomala** [comment]
@bendavies Hi. Any updates on this?

**Comment by goetas** [comment]
https://github.com/symfony/symfony/pull/47209 is the pull request implementing https://github.com/symfony/symfony/issues/45056#issuecomment-1152244259
