### ISSUE TITLE
Twig service in AbstractController

### ISSUE THREAD

**Issue by meiyasan** [symfony/symfony#45080]
### Symfony version(s) affected

6.0.2

### Description

Hello, 

I have been using Symfony\Bundle\FrameworkBundle\Controller\AbstractController for a while in my bundle. Since I updated to version 6.0.2, controllers in my bundles are returning an error message : 
```
You cannot use the "renderView" method if the Twig Bundle is not available. Try running "composer require symfony/twig-bundle".
```

I have upgraded recipes while updating to SF6 and double-checked my service declaration. Problem still here.
Might this issue be a consequence of the deprecation public state of the twig service as described here ?
https://github.com/symfony/symfony/pull/36739#

Is there an alternative I might not be aware of ? Or this is just unexpected ?

### How to reproduce

Install a bundle and inherit from AbstractController

**Comment by stof** [comment]
How are you configuring your controller service ? To me, this looks the same than what was discussed in https://github.com/symfony/symfony/discussions/44628: injecting the main container (`service_container`) in the controller instead of injecting the ServiceLocator corresponding to the ServiceSubscriberInterface.

The reason why AbstractController was introduced in Symfony 4 as a replacement of the previous `Controller` base class was precisely to make it a service subscriber instead of injecting the main container and getting public services from it. But if you wire it not as a service subscriber, it will indeed break (and btw, you should receive a deprecation warning on 5.4 when using Twig)

**Comment by meiyasan** [comment]
Sorry I forgot to add my service declaration:
```
        <service id="xKzl\MyBundle\Controller\Client\MaintenanceController">
            <tag name="controller.service_arguments" />
            <call method="setContainer"><argument type="service" id="service_container" /></call>
        </service>
```

This indeed seems to be related.. I am gonna try to fix it using previous discussion, and mark it as close if it fixes my issue

**Comment by meiyasan** [comment]
@stof 
I am trying to replace service_container by the proper service locator, but I am quite not sure how.
I am expecting to inject this guy: Symfony\Component\DependencyInjection\Argument\ServiceLocator

Are my expectations right ?

**Comment by derrabus** [comment]
Tag your controller with `container.service_subscriber`.

**Comment by stof** [comment]
As explained in the discussion I linked, tag your service as `container.service_subscriber` and inject `Psr\Container\ContainerInterface`

The compiler pass managing service subscribers will configure the ServiceLocator service corresponding to the needs of that controller and will register a binding so that injecting `Psr\Container\ContainerInterface` is resolved to that locator.

**Comment by meiyasan** [comment]
Oh sorry, I tagged controller.service_subscriber.. 
Sorry about that. Now it is detected. Thank you so much ! :)
