### ISSUE TITLE
Symfony certificate do not opened without logon

### ISSUE THREAD

**Issue by Mepcuk** [symfony/symfony#45087]
### Symfony version(s) affected

6

### Description

Hello, 
  can you please check your security.access_control- https://live.symfony.com/account/certificate/conference/P3R94HDZEXQ9XG4W
  Symfony certificate do not opened without logon anymore...

Thanks in advance

### How to reproduce

follow link https://live.symfony.com/account/certificate/conference/P3R94HDZEXQ9XG4W

**Comment by javiereguiluz** [comment]
@Mepcuk I've just checked and the code hasn't changed the access policy of this action. To download a certificate in PDF, you must be logged in as user (this has been the case since day one) ... because you can only download your own certificates, so we need to check if the requested certificate belongs to you.

If you have any other issue related to your certificates, please send a message via https://symfony.com/support and I can answer privately to you. Thanks!
