### ISSUE TITLE
Would it make sense for Role(Hierarchy)?Voter to take into account the subject if it is of UserInterface type?

### ISSUE THREAD

**Issue by jellynoone** [symfony/symfony#45207]
### Description

Today, I just noticed that I have misunderstood the security role feature.

It assumed that if you pass a `UserInterface` object to the `Security->isGranted` method as the subject the underlying `RoleVoter` / `RoleHierarchyVoter` would take its roles into account rather than the `TokenInterface`s. I came to realized this was not the case.

The change to support this is trivial, however, I wanted to gather feedback if it makes sense to you?

My use case is displaying permissions of site users or have the means to check general permissions of a user other then the logged in one. Example, trouble shooting why some user can't review.

_Note: I'm aware my use case isn't that strong. But I did almost make a vital mistake by assuming the behavior described above._

### Example

With this change you could check the permissions of other users rather than just the currently logged in one i.e.:

```php
class AppController
{
    public function display()
    {
        /** @var UserInterface $user */
        $user = \null /** fetch user having an issue with reviewing */;

        $canReview = $this->isGranted('CAPABILITY_REVIEW', $user);

        // . . .
    }
}
```

**Comment by jellynoone** [comment]
Closing as I remembered I can simply override the native voters.

**Comment by stof** [comment]
changing the voter themselves to use the roles of the subject rather than of the current user would be totally unexpected to me. It would be a very confusing API.

Btw, your use case looks more a case where you would want to call the AuthorizationCheckerInterface with a fake token containing a different user, rather than a case passing that different user as the subject for which the permission is checked (which then would also work for checking their permissions for something that requires an actual subject)

**Comment by ixillium** [comment]
@stof Thank you for the tip!

**Comment by jellynoone** [comment]
@stof Thank you for the tip! Will check out the proposed solution.
