### ISSUE TITLE
Symfony Session doesn't work if set handler_id via environment variable

### ISSUE THREAD

**Issue by linuxitux** [symfony/symfony#45202]
### Symfony version(s) affected

5.3.0/5.4.5

### Description

Symfony throws `Unsupported Connection: "session.handler.native_file"` if you set `handler_id` in `config/packages/framework.yaml` to `session.handler.native_file` via `.env` variable.

I want to have the ability to switch between different session handlers in my application, so I added a .env variable named "SESSION_HANDLER" to set `handler_id` in `framework.yaml`. I want to support several session handlers, including native_file.

If I set a Redis URL in my SESSION_HANDLER .env var, it works perfectly and uses my Redis node as the session handler. But, if I set SESSION_HANDLER to `session.handler.native_file`, I got:

```
InvalidArgumentException

Unsupported Connection: "session.handler.native_file".

In vendor/symfony/http-foundation/Session/Storage/Handler/SessionHandlerFactory.php  (line 85) .
```

### How to reproduce

Add `SESSION_HANDLER` var in `.env` and set it to `session.handler.native_file`:

`.env`:

```
SESSION_HANDLER=session.handler.native_file
```

Set handler_id via .env var in `framework.yaml`:

`config/packages/framework.yaml`:

```
framework:
    session:
        handler_id: '%env(SESSION_HANDLER)%'
```

[internal_server_error.txt](https://github.com/symfony/symfony/files/7950307/internal_server_error.txt)

**Comment by linuxitux** [comment]
Tested in 5.4.5. Same issue.

**Comment by alexander-schranz** [comment]
You can not switch the session handler based on an env variable as it can not be changed at runtime, it requires a whole cache clear. You would need to switch to a parameter instead of env var.

There are some discussion about static vs runtime env vars here: https://github.com/symfony/symfony/issues/40794

**Comment by xabbuh** [comment]
Closing here as explained by @alexander-schranz. Thank you for understanding.

**Comment by linuxitux** [comment]
@alexander-schranz thanks for your reply. The whole purpose of setting the session handler via an env var is to keep this setting variable and isolated from the version control software. If I set the session handler using a parameter in framework.yaml I would have to keep the entire file away from my control version system. I need to keep framework.yaml tracked by git with the ability to switch between session handlers without messing with deploys. Is that possible? Thanks again.

**Comment by alexander-schranz** [comment]
It is not possible as env variables are designed to be used only for configurations which do not require a cache clear. For using env variables for configs which do require a cache clear the linked issue is about it  (https://github.com/symfony/symfony/issues/40794).

You could still use the parameters.yml/parameters.yml.dist like it was in symfony 3/2: see comment here: https://github.com/symfony/symfony/issues/40794#issuecomment-818609906

See also the linked presentation here where nicolas did talk about runtime parameters and config parameters and so on: https://github.com/symfony/symfony/issues/40794#issuecomment-818722216

As you see the last comment of the linked issue is "Help wanted", so symfony is open here for a pull request to introduce a special env resolver to achieve this things e.g.: https://github.com/symfony/symfony/issues/40794

Until you need as said go with something else, a parameters.yml or some hack in your `Kernel.php` to set a kernel parameter by `$_SERVER`/`$_ENV` variable to achieve what you want. Or use the `.php` config instead of `.yml` and use `$_SERVER` or `$_ENV` to achieve what you want.

**Comment by linuxitux** [comment]
@alexander-schranz thank you very much. I will be back on this if I find a proper solution.
