### ISSUE TITLE
Support option 'placeholder' for all relevant form field types like 'TextType'

### ISSUE THREAD

**Issue by klemens-u** [symfony/symfony#45214]
### Description

It's confusing, that "ChoiceType" does support the option "placeholder", but other types like "TextType" do not.

Currently placeholder has to be given via 'attr' option.

### Example

**Currently**

```
$builder->add('location', TextType::class, [
    'attr' => ['placeholder' => 'Town or State)'],
]);
```

**Proposed:**

```
$builder->add('location', TextType::class, [
    'placeholder' => 'Town or State',
]);
```

**Comment by xabbuh** [comment]
The difference is that the `placeholder` option of the `ChoiceType` does more than setting an HTML attribute. Being able to configure the `placeholder` attribute of other types in more than one way is rather confusing (we had that in the past and precisely for this reason we removed the `max_length` and `pattern` options in 3.0). That's why I am going to close here. Thank you for understanding.
