### ISSUE TITLE
[Dotenv] Loading of env variables depends on the php parameter `variables_order`

### ISSUE THREAD

**Issue by kaznovac** [symfony/symfony#45266]
### Symfony version(s) affected

^5.4, most possibly others

### Description

Loaded env vars are not the same depending on the [`variables_order`](https://www.php.net/manual/en/ini.core.php#ini.variables-order) parameter setting.

The recommended development/production setting does *not* load the `$_ENV` superglobal. see: https://github.com/php/php-src/blob/master/php.ini-production#L636-L647

When the `$_ENV` is not loaded the actual env variables are not considered and that breaks this stance in [configuration documentation](https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local)
> Real environment variables always win over env vars created by any of the .env files.

Possible cause for the issue is this change (it removed the call to `getenv`) https://github.com/symfony/symfony/commit/f76e420e0959b52e73f1486a7b99771d6553ff01#diff-2585c97d75081932a10834cb311d918012a7e0588d28ebd5216c8591b15d15aeL73

### How to reproduce

- run any symfony project using .env file and few of those env vars in console
- try php configured with `variables_order = "GPCS"` and `variables_order = "EGPCS"`
- observe the variables in the profiler's 'server parameters'
- compare with expected (the env vars in console should take precedence)

### Possible Solution

utilize `getenv` to load the variable, investigate other solutions for the rootcause of https://github.com/symfony/symfony/issues/23502

**Comment by nicolas-grekas** [comment]
If which SAPI does this happen?
When using `php -S` this is a known issue: env vars aren't populated in `$_SERVER`. All other SAPIs do add to `$_SERVER`, so that they should not be affected.
A workaround would be to execute `$_SERVER += getenv();` before using Dotenv when `'cli-server' === PHP_SAPI`.
The better alternative is to use the [symfony binary](https://symfony.com/download) instead of `php -S`
That's not something we can fix in Dotenv.

**Comment by nicolas-grekas** [comment]
We could fix that in symfony/runtime maybe.

**Comment by kaznovac** [comment]
haven't used `php -S` built-in web server.

`PHP_SAPI` is, depending on context, either `apache2handler`, `cli`

I've built a docker image based on [official php 8.1-apache](https://hub.docker.com/layers/php/library/php/8.1-apache/images/sha256-940dbf46c39bf7afc3a0b3fa6bd815e4102513c50d63fb891376665af57101b6?context=explore)
with recommended php.ini-production configuration (i.e. `RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini`)

With the `variables_order = "GPCS"` the `$_SERVER` is loaded as expected (with the correct value for env vars), and the `$_ENV` is `[]` so in the `Dotenv::populate` the check will fail in line (`$_ENV` is empty) https://github.com/symfony/symfony/blob/43e3e71a78e4c1d33658f6a31eac9edae124c2dd/src/Symfony/Component/Dotenv/Dotenv.php#L190
and the correct env variable value will be, later in the same method, overwritten with the value read in from the `.env.local.php` at lines https://github.com/symfony/symfony/blob/43e3e71a78e4c1d33658f6a31eac9edae124c2dd/src/Symfony/Component/Dotenv/Dotenv.php#L198-L201

This is the commit that removed the `$_SERVER` check https://github.com/symfony/symfony/commit/08291b1665a96c77a6516ac52c4a100135e7061f

*edit*
The same commit also copied the vars from `$_SERVER` to `$_ENV`... so this should work :|
https://github.com/symfony/symfony/blob/08291b1665a96c77a6516ac52c4a100135e7061f/src/Symfony/Component/Dotenv/Dotenv.php#L139-L141

**Comment by nicolas-grekas** [comment]
>  The same commit also copied the vars from $_SERVER to $_ENV... so this should work :|

that's what I would say also... so it's something else I guess

**Comment by nicolas-grekas** [comment]
Closing for now, please report back when you have more info.

**Comment by annuh** [comment]
Thanks for the hint about `variables_order`.

I was having issues after enabling the [php.ini-production](https://github.com/php/php-src/blob/PHP-8.2/php.ini-production). _Real_ environment variables were not resolved correctly:

I was using the following environment variable: `MYSQL_HOST=external.host` (configured via AWS ECS) and the following configs:
```
# .env
MYSQL_HOST=localhost
```

```
# packages/doctrine.yaml
doctrine:
    dbal:
        host: '%env(resolve:MYSQL_HOST)%'
```

Our application tried to connect to `localhost`, instead of `external.host`. 
This was fixed after adding `variables_order = "EGPCS"` to our `php.ini` (which is loaded after php.ini-production)
