### ISSUE TITLE
 Redis connection "redis:///var/run/redis/redis.sock" failed: php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by wokenlex** [symfony/symfony#45277]
### Symfony version(s) affected

v4.4.37 

### Description

After update from v4.4.27 to v4.4.37 symfony cache can't connect redis through the socket.

### How to reproduce

Use socket connection to redis, use URL in redis config like this:
redis:///var/run/redis/redis.sock

**Comment by mathielen** [comment]
It's because in this commit https://github.com/symfony/symfony/commit/c0879ecd657d350a605f04989ef522bf9d061059 the default for $port has been set to 6379 instead of null. So the redis connection is using a port with a unix-socket. This throws a RedisException with `php_network_getaddresses: getaddrinfo failed: Name or service not known`
