### ISSUE TITLE
Rename `invalidate-tags` command as `clear-tags`?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#45711]
### Description

In #44692 we added a `cache:pool:invalidate-tags` command in addition to the existing `cache:pool:clear` command.

I think `invalidate` is too long and uncommon ... besides being inconsistent with the existing `clear` command.

Even in the proposed docs of this feature (https://github.com/symfony/symfony-docs/pull/16328) we use the "clear" word to explain the command:

<img width="728" alt="docs" src="https://user-images.githubusercontent.com/73419/157862390-9d6184d8-90e4-4519-9691-b4b3bf01c641.png">

So, should we rename `cache:pool:invalidate-tags` as `cache:pool:clear-tags` ?

Thanks!

**Comment by kbond** [comment]
I used "invalidate" because of the `TagAwareCacheInterface::invidateTags()` method. Note, [this doc](https://symfony.com/doc/current/components/cache/cache_invalidation.html) uses the term "invalidation" instead of "clear". Maybe https://github.com/symfony/symfony-docs/pull/16328 should use the term invalidate as well? Also, I know there has been a proposal for a specific `cache:pool:invalidate` command - to invalidate a specific key or keys.

That all being said, I don't have a strong opinion on this.

**Comment by javiereguiluz** [comment]
Thanks for your comments Kevin. I see this is more complex than it looked at first.

Technically speaking, what does the `cache:pool:invalidate` command do?

(1) Turns the tags as invalid, but items are still stored in the cache (but invalid) until they are actually cleared later.
(2) Turns the tags as invalid and immediately deletes all the items tagged with them.

To me, (1) is "invalidate" and (2) is "clear".

**Comment by kbond** [comment]
Good point, I'm not actually sure if it's 1 or 2. @nicolas-grekas could probably answer this.

> Also, I know there has been a proposal for a specific cache:pool:invalidate command - to invalidate a specific key or keys.

I think if this were added, we would call `cache:pool:delete` to match the interface method. (I was trying to find another place we'd use the term invalidate but this isn't it).

**Comment by OskarStark** [comment]
Or @Nyholm can help us here

**Comment by nicolas-grekas** [comment]
We provide both implementations 1. and 2. 
The correct term is invalidation to me. The doc should be fixed.
