### ISSUE TITLE
CLI colors are broken in Docker

### ISSUE THREAD

**Issue by mvorisek** [symfony/symfony#45917]
### Symfony version(s) affected

5.4.5

### Description

see https://github.com/composer/composer/issues/10691#issuecomment-1086616111 /w repro DockerFile

### Possible Solution

colors supported correctly

**Comment by mathela59** [comment]
In fact, colrization inside a docker depends of the shell used in docker. I'm not sure that the problem is a Symfony problem.

Moreover, if your docker is run under root user, it's normal that colorization is disabled.

In my opinion this is not an issue.

Maybe you should try ls --color to see if your shell support it .

**Comment by mvorisek** [comment]
Code to repro:

Dockerfile: https://github.com/mvorisek/image-php/blob/master/data/8.1-debian/Dockerfile#L57
CI: https://github.com/mvorisek/image-php/runs/5796737502?check_suite_focus=true#step:6:103

there is some transformation, but what supprises me is the coloring is more or less random

**Comment by fabpot** [comment]
Feel free to submit a PR if you think there is something we can improve here.

**Comment by fabpot** [comment]
Fixed by #52940
