### ISSUE TITLE
[PropertyInfo] Support array elements types through PHP native attributes

### ISSUE THREAD

**Issue by lainosantos** [symfony/symfony#46092]
### Description

Hello everyone,

I developed a package for support extract array elements types with PHP attributes. It dispense use of DocBlock for simples operations as serialize/deserialize of typed array.

Do Make It sense as part of PropertyInfo's core? If yes, i can make a PR.

https://github.com/lesphp/property-info-typed-array

**Comment by ro0NL** [comment]
the same info can already be extracted using enhanced type info isnt it?

```
@var array<int, Baz|string|null>
```

**Comment by lainosantos** [comment]
Yes, it is possible, however it depends of DockBlock annotation with type info. With PHP cuurent version, there is no way for type hint array elements. DocBlocks is PHP first-class citizen, but it isn't for type checking/enforcing. A wrong class name inside a docblock is only textual documentation for PHP, but not for developer. Then, documentations can be removed/replaced and the program behavior should be the same. Using PHP attributes can prevent errors when refactoring something, for example, because type enfircing in DocBlock is only a convention and is not fully/widely supported in IDEs or PHP parsers libraries.

**Comment by ro0NL** [comment]
> DocBlocks is PHP first-class citizen, but it isn't for type checking/enforcing

the same arguments apply to attributes

IIUC the proposal is to add runtime validation in Serializer component, using the type info from extractors

**Comment by lainosantos** [comment]
From developer perspective, PHP attributes change/configure the runtime code behavior, but DocBlock not, it is for documentation. When refactoring, for example, a DocBlock can be removed/outdated/forgotten, because IDE support or developer action, but for all PHP attributes the developer know that it change the program behavior as same the code. The DocBlock convention is good, but only while the language don't provides other way more strict native.

**Comment by lainosantos** [comment]
The proposal is to add others way for extract array elements type without use DocBlock, in this case using an attribute.

**Comment by nicolas-grekas** [comment]
Symfony's policy on the topic of type descriptions is to be a follower. Aka we don't implement experiments. Instead we wait for things to become mainstream before supporting them.

On the topic of using attributes for describing types, phpstorm supports these:
https://github.com/JetBrains/phpstorm-attributes/

Having support by phpstorm is a good step towards broader adoption. Having phpstan+psalm also support them (or similar attributes also adopted by phpstorm) would definitely make us consider supporting them.

I'm closing because I think this "solves" the issue. Aka please let us know when a set of attributes is becoming mainstream on the topic. (Personally I'm not sure attributes in the phpstorm namespace are good candidates for super broad adoption, but I might be wrong.)
