### ISSUE TITLE
[FrameworkBundle] Auto detect IDE config

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony#46339]
### Description

Just read the news about improvement made on the [`framework.ide`](https://symfony.com/doc/current/reference/configuration/framework.html#ide) config option and I am wondering if this option cannot be auto detected (when possible) instead of being set to `%env(SYMFONY_IDE)%` (`null`) by default.

Most of IDE are creating a file/folder at the root of the project to store IDE project configuration like `.idea` with PHPstorm (Jetbrains) or `.vscode` for Visual Studio Code.

So we could just check if the file/folder exists and apply the default value?

**Comment by KevinVanSonsbeek** [comment]
I have 2 thoughts/questions about this
* What do you do when multiple IDE folders are found in the root of the project? As you might have opened the project in multiple IDE's for some reason. Or for some weird reason the folders are (partially) tracked in the VCS.
* Wil there need to be a new value added to still be able to open files in the browser? As i use PHPStorm at work, but due to circumstances can't install the handler/protocol needed to open the files properly, and thus prefer to still open the files in the browser if possible. 

Edit: 
P.S. i do think it would be a nice addition, but it should be configurable to some degree. As people might not like the auto detecten.

**Comment by Seb33300** [comment]
- I will suggest to use the one with the most recent modified date by default.
- Not sure to understand your question. this is to set the default value, you still can override it in the config.

**Comment by GromNaN** [comment]
In 6.1, the default value will `%env(SYMFONY_IDE)%` (#44575). That way, you can configure your favorite IDE once on your system.

**Comment by KevinVanSonsbeek** [comment]
Right now if the option is not set or null, it should open the files in browser, if i understand correctly.

If you replace that behavior with auto detecting an IDE, you lose the option to view in browser, the moment you've opened the project with an IDE. So you'd either want an "autodetect" option, to trigger the autodetecting. Or need like a "browser" option, to keep the option to open files in browser, when you use an IDE, but don't want to actually open the files in your IDE.

**Comment by stof** [comment]
The autodetection would be hard anyway. For instance, detecting a `.idea` folder does not imply that the extra configuration necessary to register a protocol handler on your system has been done.

**Comment by KevinVanSonsbeek** [comment]
> The autodetection would be hard anyway. For instance, detecting a `.idea` folder does not imply that the extra configuration necessary to register a protocol handler on your system has been done.

In my case i use PHPStorm to develop, but due to security risks i'm not actually able to install the protocol handler required for linux. So that would break the file opening functionality. Thus needing an option to disable the auto detect, and still choose the option to open files in browser :)

**Comment by lyrixx** [comment]
More over, some people commit some files related to their IDE (yeah I know, they shouldn't). So it can detect a bad IDE. 

I'm 👎 for this feature but thanks for the proposal
