### ISSUE TITLE
[Mailer] Create a new Mailpace Bridge to replace OhMySMTP Bridge 

### ISSUE THREAD

**Issue by welcoMattic** [symfony/symfony#46340]
### Description

See at https://docs.mailpace.com/guide/moving_from_ohmysmtp/

OhMySMTP has been renamed to Mailpace, we should create a new bridge to support to new API url and header names, and deprecate the OhMySMTP one.

**Comment by stof** [comment]
We should probably create a new bridge using the new name (and then deprecate the old one)

**Comment by Holicz** [comment]
Hi, I would gladly send a PR for this. Since it would be my first contribution I have a couple of questions.

1) I would choose branch 6.1 as a target since it's not a bug fix, right?
2) The change will result in a new composer package `symfony/mailpace-mailer` and a new repo – this is handled by somebody else during the monorepo split, correct?

Thank you for the answers!

**Comment by stof** [comment]
1. This will even go to 6.2 as 6.1 is in feature freeze since more than a month now. The 6.2 branch will be created soon (for now, the focus is on finalizing the 6.1 stable release, not on working on new features for 6.2, as 6.1 is in beta)
2. yes, this is handled by the core team (well, adding the composer.json in that folder and the few other metadata should be part of the PR, but the split itself and the registration on Packagist will be handled by the core team when merging the PR)

**Comment by Holicz** [comment]
I've prepared the PR and checked the pipelines, I would say remaining failures in phpunit are not related to my changes, so it's ready for review when anybody have time for it.
