### ISSUE TITLE
cache:clear warning about /proc/mounts no such file

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#46446]
### Symfony version(s) affected

5.4.8

### Description

When you run `./bin/console cache:clear` on Mac, you always get a PHP warning.

```
12:14:21 DEBUG     [php] Warning: file(/proc/mounts): Failed to open stream: No such file or directory
[
  "exception" => Symfony\Component\ErrorHandler\Exception\SilencedErrorContext {
    +count: 1
    -severity: E_WARNING
    trace: {
      ./vendor/symfony/framework-bundle/Command/CacheClearCommand.php:211 { …}
      ./vendor/symfony/framework-bundle/Command/CacheClearCommand.php:164 { …}
    }
  }
]
```

### How to reproduce

./bin/console cache:clear

### Possible Solution

Check OS is Linux 🤔

**Comment by nicolas-grekas** [comment]
`SilencedErrorContext` means the error is `@-silenced`, this should be ignored then.

**Comment by shyim** [comment]
But it still writes it in the console on any cache clear 😅

**Comment by nicolas-grekas** [comment]
It shouldn't. I guess you have `xdebug.scream` turned on, or similar. Nothing we can do about.

**Comment by johnpancoast** [comment]
@nicolas-grekas, I'm getting this output as well but xdebug is disabled, i.e., `xdebug.mode = "off"`.

I've been out of PHP/Symfony land for awhile and only skimmed things here, but couple things:

1. [This line in CacheClearCommand](https://github.com/symfony/framework-bundle/blob/6.2/Command/CacheClearCommand.php#L203) gets called (with `@` prefix) then gets to Symfony's error handler.
2. While tracing the [ErrorHandler](https://github.com/symfony/error-handler/blob/6.2/ErrorHandler.php) for my case, I noticed that [where the log is called](https://github.com/symfony/error-handler/blob/6.2/ErrorHandler.php#L472-L473), `$level`'s value created on line 472 is equal to `LogLevel::DEBUG` for my case instead of `warning` so I'm wondering if that has something to do with it. 

Maybe another possibility is that this is related to [PHP v8 handling error reporting differently](https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting)?

> The default value is E_ALL.
>
> Prior to PHP 8.0.0, the default value was: E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED. This means diagnostics of > level E_NOTICE, E_STRICT and E_DEPRECATED were not shown.

**Comment by daslicht** [comment]
any solution for this meanwhile?
