### ISSUE TITLE
[Console] Returns wrong hinted "command" in output when called via Symfony CLI

### ISSUE THREAD

**Issue by chii0815** [symfony/symfony#46705]
### Symfony version(s) affected

>4.4 maybe lower

### Description

When running a console command via symfony cli the console returns a hint with the bin/console command.
Running `symfony console make:migration` returns an output with an hinted next command `php bin/console doctrine:migrations:migrate`. Expected would be `symfony console doctrine:migrations:migrate`.
As this happens not just on make: commands it maybe something that could be fixed on the console component.

### How to reproduce

$ symfony console make:migration

  Success!

 Next: Review the new migration "migrations/Version20220617164704.php"
 Then: Run the migration with php bin/console doctrine:migrations:migrate
 See https://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html

### Possible Solution

Make console component aware of called via symfony cli.

**Comment by magikid** [comment]
I think this only affects the symfony/maker-bundle.  I can't find any indication of `php bin/console` being specified in this repo outside of tests.  I did however find several instances of it in the MakerBundle repo.

@chii0815 if you know of any other spots besides the `make:...` commands where this can be seen, that would be useful to get this fixed.

I've opened up symfony/maker-bundle#1235 to fix it over there because it's hardcoded text.

**Comment by stof** [comment]
The reason why you don't see `bin/console` is because this is resolved dynamically based on where the console is run from. See https://github.com/symfony/symfony/blob/ac88f9a72bd0980ebff2bf4a24a11bdbc2aa6735/src/Symfony/Component/Console/Command/Command.php#L589-L608

The issue is that using `symfony console` still makes the Go binary run `php bin/console` under the hood in a subprocess. So the console component is not aware that what the user ran was actually `symfony console`

**Comment by magikid** [comment]
Ah so then there's probably no way to get the maker-bundle (or whatever else) to be aware of what the original command was.

**Comment by jrushlow** [comment]
This issue can probably be closed. It's related to `MakerBundle` and not something that we have the ability to "fix". See https://github.com/symfony/maker-bundle/issues/1235

**Comment by jrushlow** [comment]
This will now be possible in the next feature release of the Symfony Binary (5.5+) & MakerBundle (1.49+)

See https://github.com/symfony-cli/symfony-cli/pull/231 && https://github.com/symfony/maker-bundle/pull/1238
