### ISSUE TITLE
[symfony/doctrine-bridge] phpunit fails due to depreciation error

### ISSUE THREAD

**Issue by dvdknaap** [symfony/symfony#46892]
### Symfony version(s) affected

6.1

### Description

In the ci pipeline phpunit fails because of the following depreciation.

The "Symfony\Bridge\Doctrine\Logger\DbalLogger" class implements "Doctrine\DBAL\Logging\SQLLogger" that is deprecated Use {@see \Doctrine\DBAL\Logging\Middleware} or implement {@see \Doctrine\DBAL\Driver\Middleware} instead.

See: https://github.com/symfony/doctrine-bridge/blob/6.1/Logger/DbalLogger.php

### How to reproduce

Install symfony 6.1 with symfony/doctrine-bridge and symfony/phpunit-bridge then run `vendor/bin/phpunit`

**Comment by tcheymol** [comment]
Hi @dvdknaap , I think that your PHPUnit does not fails, but it triggers a deprecation. Maybee your PHPUnit config makes it fail on warning.
I would suggest you to not break your pipeline on deprecations doing something like this in your phpunit.xml,
```
<phpunit 
         convertWarningsToExceptions="false"
         failOnWarning="false">
```

**Comment by stollr** [comment]
I think the failing on deprecations happens due to [Symfony's deprecation helper](https://symfony.com/doc/current/components/phpunit_bridge.html#making-tests-fail), which is integrated in the phpunit-bridge. I had the same issue some days ago.

I added `export SYMFONY_DEPRECATIONS_HELPER="max[direct]=0&max[indirect]=999999"` to my git pre-commit hook script before executing phpunit. This prevents phpunit from failing, although the deprecations will still be shown.

**Comment by stof** [comment]
Are you using the latest version of DoctrineBundle ?

**Comment by lxregistry** [comment]
> Are you using the latest version of DoctrineBundle ?

this warning still persist with symfony/phpunit-bridge (v6.1.3), symfony/doctrine-bridge (v6.1.5) and doctrine/doctrine-bundle (2.7.0)

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
