### ISSUE TITLE
[EasyAdminBundle] setBadge method wrongly defined 

### ISSUE THREAD

**Issue by Loicyeu** [symfony/symfony#47067]
### Symfony version(s) affected

6.1.2

### Description

Easyadmin-bundle : v4.3.3

The `setBadge` method of the trait `EasyCorp\Bundle\EasyAdminBundle\Config\Menu\MenuItemTrait` have wrongly defined PHPDoc. The `$content` attribute is typed as `This` instead of no type. In the method definition, good types are provided to the argument but it's commented. The problems is for IDE linters that do not recognise good types.

![image](https://user-images.githubusercontent.com/56322238/181048578-fc67b12b-e310-49f4-a7ac-ac2c20c807b1.png)
![image](https://user-images.githubusercontent.com/56322238/181048717-f6c7f4ee-1c67-48db-8a2b-56b2a38bd662.png)

### How to reproduce

Just open the `EasyCorp\Bundle\EasyAdminBundle\Config\Menu\MenuItemTrait` to see the problem.

### Possible Solution

Uncomment the types on the method definiton or set a type on the PHPDoc.

**Comment by chalasr** [comment]
EasyAdminBundle is not part of Symfony core, please consider reopening this issue on https://github.com/EasyCorp/EasyAdminBundle.

**Comment by wouterj** [comment]
Note that this is *not* a wrongly defined PHPdoc, it's OK to not have a type and the Symfony community often avoids PHPdoc that simply duplicates information that is already present in PHP (to avoid out of sync PHPdoc).

Instead of reporting this to the upstream projects, please report this to your IDE :)
