### ISSUE TITLE
syntax error, unexpected token ")" when using version 6.0 of symfony/css-selector as part of illuminate/mail dependencies.

### ISSUE THREAD

**Issue by garethdaine** [symfony/symfony#47064]
### Symfony version(s) affected

6.0

### Description

- Laravel Version: ^8.40
- PHP Version: ^8.0
- Database Driver & Version: Serverless v1 MySQL 5.7 (Laravel Vapor)

### Description:

I've come across a bug when sending out email via AWS SES (on Laravel Vapor) when the version of **symfony/css-selector** a dependency of **tijsverkoyen/css-to-inline-styles** which is a dependency in **illuminate/mail** is version 6.0.

Essentially, any time an email is sent (notification, password reset, email verification etc), it results in a 500 error with the message syntax error, unexpected token ")".

Locking **symfony/css-selector** to version 5.4.3 fixes this issue and mail is sent fine

### How to reproduce

With all versions in description the same, simply try to send an email via AWS SES on Laravel Vapor when **symfony/css-selector** is set to version 6.0.

**Comment by stof** [comment]
Please provide the exact error message (including the location of the error).

**Comment by stof** [comment]
And please provide the exact version of the component you are using (run `composer show -i` to view the exact versions of your installed components). `6.0` is not an exact version.

**Comment by garethdaine** [comment]
Hey @stof The exact version is 6.1.0 of **symfony/css-selector**.

I've noticed that in the composer.json of the **tijsverkoyen/css-to-inline-styles** repo there is a dependency requirement for **"symfony/css-selector": "^2.7 || ^3.0 || ^4.0 || ^5.0 || ^6.0"**, and as **illuminate/mail** has **"tijsverkoyen/css-to-inline-styles": "^2.2.2"** as a requirement, if a composer update was ran, this would essentially upgrade **symfony/css-selector** to version 6.1.0.

With Laravel 8 not being compatible with version 6 of Symfony, this may well be what caused the issue.

The exact error and location details are:

**Location**: vendor/symfony/css-selector/XPath/Extension/NodeExtension.php:68
**Error**: syntax error, unexpected token ")"

**Comment by stof** [comment]
Well, if you are running your code on PHP 8.0, installing `symfony/css-selector` 6.1.0 will indeed be broken, as it requires PHP 8.1 (and uses some syntax added in PHP 8.1).

Make sure that you run `composer update` using the proper target PHP version. There is 2 ways to achieve that:
- run composer using PHP 8.0 (as the default behavior of Composer is to use your runtime version as target version)
- configure the `platform` config setting of Composer to configure the target platform explicitly instead of relying on the default version: https://getcomposer.org/doc/06-config.md#platform

Also, make sure that you don't use the `--ignore-platform-reqs` option when running `composer update`, as that disables all rules ensuring compatibility with the platform version.

There is no issue in Symfony or in `tijsverkoyen/css-to-inline-styles` as the platform requirements are configured properly and so composer will select the right version automatically.

**Comment by garethdaine** [comment]
> Well, if you are running your code on PHP 8.0, installing `symfony/css-selector` 6.1.0 will indeed be broken, as it requires PHP 8.1 (and uses some syntax added in PHP 8.1).
> 
> Make sure that you run `composer update` using the proper target PHP version. There is 2 ways to achieve that:
> 
> * run composer using PHP 8.0 (as the default behavior of Composer is to use your runtime version as target version)
> * configure the `platform` config setting of Composer to configure the target platform explicitly instead of relying on the default version: https://getcomposer.org/doc/06-config.md#platform
> 
> Also, make sure that you don't use the `--ignore-platform-reqs` option when running `composer update`, as that disables all rules ensuring compatibility with the platform version.
> 
> There is no issue in Symfony or in `tijsverkoyen/css-to-inline-styles` as the platform requirements are configured properly and so composer will select the right version automatically.

Thank you @stof That was indeed the issue and has now been sorted and solved our end.

Very much appreciated, buddy.
