### ISSUE TITLE
MonologBridge shows deprecation error with Monolog 3.2

### ISSUE THREAD

**Issue by gbirke** [symfony/symfony#47096]
### Symfony version(s) affected

6.1

### Description

Monolog 3.2 has made the `Logger` class `final` (see https://github.com/Seldaek/monolog/commit/3cba75ec0926eec177a4a2cd6c977ecddd0fc7c1 ). This might lead to deprecation notices when initializing the Symfony logger

### How to reproduce

Manually add Monolog ^3.2 to your composer dependencies
Initialize the Symfony logger in your code, e.g. a CLI command. When the logger is initalized for the first time (with a clean cache), you will get an error message that looks like this:

_User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /var/www/vendor/symfony/error-handler/DebugClassLoader.php:330)"} []_

### Possible Solution

A short-term fix would be to restrict the possible versions of Monolog to any version below 3.2 in the `composer.json` file of monolog-bridge

The long-term fix would be to change `Symfony\Bridge\Monolog\Logger` as a facade for a `Monolog\Logger` instance, possibly wrapping a logger and implementing the `Psr\Log\LoggerInterface` and `Monolog\ResettableInterface` for backwards compatibility.

**Comment by derrabus** [comment]
I think, we should deprecate `Symfony\Bridge\Monolog\Logger` in 6.2. That logic can be reimplemented easily without extending Monolog's `Logger` class.

**Comment by upyx** [comment]
> I think, we should deprecate `Symfony\Bridge\Monolog\Logger` in 6.2.

I doubt anyone is using it at all. It is used internally in profiler to collect logs and to translate the Monolog's `ResettableInterface` to Symfony's `ResetInerface`.

However, it **is** a default `monolog.logger` service, so it **must** be of `Monolog\Logger` type. But to formally keep the BC promise, the `monolog.logger` service must be of `Symfony\Bridge\Monolog\Logger` type too (it has been since 2010). Catch 22 :man_shrugging:

In 6.1, we can mark conflict with monolog 4.0 and newer, and just suppress the notice. It will work while Monolog keeps their promises.

In 6.2, it will be a lot of work :smile:

**Comment by derrabus** [comment]
> But to formally keep the BC promise, the `monolog.logger` service must be of `Symfony\Bridge\Monolog\Logger` type too (it has been since 2010). Catch 22 🤷‍♂️

Well, the MonologBundle which registers that service is not part of the Symfony monorepo, so we could tag a new major release of that bundle as we see fit.

**Comment by stof** [comment]
The profiler implementation currently expects the `logger` service to implement DebugLoggerInterface to be able to collect logs. We would need to provide an alternate configuration setup where the interface could be implemented by a separate service instead (and then, MonologBundle could inject the DebugProcessor directly in the LoggerDataCollector). As long as this is not done in FrameworkBundle, we cannot avoid using the child class provided in the bridge.

**Comment by derrabus** [comment]
> We would need to provide an alternate configuration setup where the interface could be implemented by a separate service instead

Yes. And in fact, the interface is already implemented by a separate service in addition to the bridge's logger class. All this class does is searching for that service and acting as a façade.

**Comment by stof** [comment]
@derrabus yeah, but we ned to add a feature in FrameworkBundle allowing to inject a different object than the `logger` service in LoggerDataCollector. That's the requirement to solve that issue. Currently, FrameworkBundle expects the logger to implement the interface.

**Comment by derrabus** [comment]
Exactly.

**Comment by Seldaek** [comment]
I don't know if you have a way to ignore these errors, but just FYI the reason I added the `@final` was because some people extended it and did crazy things and then got burnt.. so I thought I'd declare the intention that it should be final, but I don't necessarily think it should be `final` for real. So if you are extending with reasonable things it may be fine to keep as is. I just wanted to be clear that extending breaks the warranty and people shouldn't come complaining if things break :)

**Comment by derrabus** [comment]
Understood. Then again, I think we can and should stop extending it.

**Comment by Seldaek** [comment]
Yeah that'd be a better outcome but I also see it seems like work which isn't strictly needed so I wanted to clarify.

**Comment by joaojacome** [comment]
I've opened a PR to try and fix the deprecation. Whenever you guys are available, please take a look :)

**Comment by Evgeny1973** [comment]
Not fixed yet? I have latest v. 6.3.4 and deprecate appears.
![image](https://github.com/symfony/symfony/assets/20745667/4f74c1b5-12c0-4452-96a9-6b33feba0b1e)

**Comment by pscheit** [comment]
PR is here btw https://github.com/symfony/symfony/pull/49759

**Comment by derrabus** [comment]
I think we're done here:

* #51284
* #51289
* symfony/monolog-bundle#461
