### ISSUE TITLE
Routing transforms url

### ISSUE THREAD

**Issue by pcmanprogrammeur** [symfony/symfony#47110]
### Symfony version(s) affected

5.4

### Description

Hi all,
We have a thesaurus with german localities like :
- name : Baden-Württemberg
- url : Baden-W%C3%BCrttemberg

When we use path() function in twig, the url is again encoded `Baden-W%25C325%BCrttemberg` so i call url_decode() to keep to good url ...
When we are in the controller, `Baden-W%C3%BCrttemberg` is decoded due to : `$pathinfo = rawurldecode($pathinfo) ?: '/';` in CompiledUrlMatcherTrait.php and i don't find `Baden-Württemberg` in database ...
Why does the routing package change all my urls please ?
Adding url_decode and urlencode is bad ...

### How to reproduce

In twig : 
{{ path('my_path', {'region': 'Baden-W%C3%BCrttemberg')}) }} => my_path/Baden-W%25C3%25BCrttemberg
{{ path('my_path', {'region': url_decode('Baden-W%C3%BCrttemberg')}) }} => my_path/Baden-W%C3%BCrttemberg
I must add url_decode() to make it works properly ...

In controller :
$localilty = urlencode($locality);
// Before : `Baden-Württemberg` After : `Baden-W%C3%BCrttemberg`
$myService->getLocality($locality);
I must add urlencode() to make it works properly ...

**Comment by BaptisteContreras** [comment]
Hey,

Actually, I don't think this is a bug: 
- As URIs are (and should be) always encoded before the request is being sent, we should not care about the raw URI parameters and let the framework handle them in a safe way.
- This is also the same idea for the auto encoding when you generate a route (with the `path `helper in twig or directly with the `router`) : it's the framework duty to safely encode our route parameters and it's smoother if we don't have to think about it each time we generate an URL.

Maybe in your application you should create a DTO object and use it, instead of a string.

Here is a sample :

```
class Region {
    private $encoded; // You are free to rename this property...

    private $decoded; // And also this one :)

    public function __construct(string $decoded) {
        $this->encoded = urlencode($decoded);
        $this->decoded = $decoded;
    }

    public function getEncoded(): string {
        return $this->encoded;
    }

    public function getDecoded(): string {
        return $this->decoded;
    }
}
```
 And in a controller :
```
    /**
     * @Route(path="/{stringRegion}", name="test-region")
     */
    public function testRegion(string $stringRegion): Response
    {
        $region = new Region($stringRegion);

        $myService->doSmth($rawRegion);
        $myRepo->findByRegion($rawRegion);

        return $this->render('my_view', [
           'region' => $region
        ]);
    }
```


In your services or repository you can work with this object and in twig you can do something like that:  `{{ path('my_path', {'region': region.decoded)}) }}`

If you don't want to use a DTO like above you can try to create your own [ParamConverter](https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/converters.html#creating-a-converter), but it won't solve your problem with `path()`.

Finaly, I don't think there would be real benefits to give access to the "raw route parameters", I can't find a use case for this (maybe I've missed something) ?

Have a great day,
Regards

**Comment by pcmanprogrammeur** [comment]
Hey,

Thank you for all your detailed explanations and the useful example.

I will take a look about your solution.

Using my own ParamConverter, whereas path() will not be resolve, is not a good solution in my usecase.

Thank you again.

Have a great day too,
Regards
