### ISSUE TITLE
[3.0] [Form] DateType ignores "empty_data" option

### ISSUE THREAD

**Issue by henrikbjorn** [symfony/symfony#4715]
With the following test case. https://gist.github.com/e50f4dfb88fc38486389 DateType ignores `empty_data` in the options array.

Also tried extension `DateType` and set the `empty_data` option directly in `setDefaultOptions` with the same result.

**Comment by eved42** [comment]
Hi, it's a problem that this bug isn't solved for the moment...
But, I find a solution in case of a form build with an entity.

In this case, I set default dates when I create a new entity but I don't when this is the edit case because I want dates fields are filled with stored data.

If you don't specify the 'data' attribute of a DateType, the field will be empty.

This will replace the functionning of "empty_data". 
```
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class MyEntityType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$beginOptions = array(
			'label' 	=> false,
			'widget' 	=> 'single_text',
			'html5' 	=> false,
			'format' 	=> 'yyyy-MM-dd',
		);

		$endOptions = array(
			'label' 	=> false,
			'widget' 	=> 'single_text',
			'html5' 	=> false,
			'format' 	=> 'yyyy-MM-dd',
		);

		// Case : new entity
		if (empty($options['data']->getId())) {
			# default dates
			$beginOptions['data'] = new \DateTime('now');
			$endOptions['data'] = new \DateTime('tomorrow');
		}

		$builder
			->add('beginDate', 	DateType::class, $beginOptions)
			->add('endDate', 	DateType::class, $endOptions)

			// [...]
		;
	}

	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults(array(
			'data_class'  => 'AppBundle\Entity\MyEntity',
		));
	}
}
```

**Comment by alegout** [comment]
Hello, any news for this issue?

**Comment by HeahDude** [comment]
Hello there!

As explained above, this is not a bug, but an annoying limitation.
In both case the behavior we expect here is not right.

Usually, I'm in favor of fixing the docs and making such behavioral change in master.
But I think this case is different because what we're actually dealing with is an inconsistency in the way `empty_data` (a.k.a default view data on submission) is handled; which is not the same depending on the widget of all date related types, because basically it depends on whether the form is compound.

1/ If the form uses the `choice` or the `text` widgets, then it's compound so its empty data is an empty array no matter what. Because in a compound field, the view data is the data into which default inner fields model data should be mapped.

2/ If it uses the `single_text` widget then the empty data value is reversed transformed to a `\DateTime object` as expected (see test added in #29179). Because in a simple field, the view data is the one replacing the model data.

So if we want to fix 1, we need to cascade the configuration to inner fields to be able to set values used as default. This should not be a problem since this never worked as expected before.

I suggest we do it in 2.8, here's a proposal #29182.
