### ISSUE TITLE
[Security] login_throttling un-blocking for *one* attempt at "5 * max_attempts"

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#47282]
### Symfony version(s) affected

6.1.3

### Description

I have this in my `security.php`:
```php
$security->provider('foo_provider')->entity()->class(Foo::class)->property('token');
$mainFirewall->loginThrottling()->maxAttempts(1)->interval('1 hour');
```
`Foo::$token` is a self-created random string for magic link login.

This happens when requesting the **same** inexistent token URL (after `cache:clear`):
1. attempt => "Invalid link"
2. attempt => "You're blocked" // As expected with `->maxAttempts(1)`
3. attempt => "You're blocked"
4. attempt => "You're blocked"
5. attempt => "Invalid link" // **Why??**
6. through 20. attempt => "You're blocked"

So to me this looks like either a bug, or the documentation at https://symfony.com/doc/5.4/security.html#limiting-login-attempts is missing something:
> Login attempts are limited on `max_attempts` (default: 5) failed requests for IP address + username and 5 * max_attempts failed requests for IP address.

When changing `max_attempts` to 2, the unexptected "Invalid link" happens at the 10th attempt, so it's probably related to the "5 * max_attempts" rule.

### How to reproduce

If you're telling me that this is the expected behavior, then let's try to improve the docs. If you say that this is unexpected, I can try to investigate it further or create a reproducer.

**Comment by MatTheCat** [comment]
It seems the issue is caused by https://github.com/symfony/symfony/blob/79ee32a603fa896f2a83a13860b68dfcaac887e5/src/Symfony/Component/HttpFoundation/RateLimiter/AbstractRequestRateLimiter.php#L48-L50

On the fifth attempt the global limiter will return an accepted rate limit with zero remaining token. The local limiter will then return a “denied” one but as it also has zero remaining token (obviously) the global rate limit is kept and the request is accepted.

Maybe it would make sense to also check `RateLimit::$accepted` in the condition.
