### ISSUE TITLE
Factory is not describable

### ISSUE THREAD

**Issue by BenMorel** [symfony/symfony#47309]
### Symfony version(s) affected

5.4.11, 6.1.3

### Description

We cannot currently use `bin/console debug:container` with `--format=json` because we get this error:

> In JsonDescriptor.php line 248:
>                                
> [InvalidArgumentException]   
> Factory is not describable.  
                               
The culprit in our case is `Sentry\Client`, and because of this only service, we cannot describe our whole container.

Would it be possible, instead of throwing an exception, to just output a `null` value, an error string, or anything that wouldn't make the whole thing fail?

Same issue with `xml` and `md`.

### How to reproduce

```
composer create-project symfony/skeleton:"6.1.*" tmp
cd tmp
composer require sentry/sentry-symfony
bin/console debug:container --format=json --env=prod
```

**Comment by stof** [comment]
Looking at the code of `sentry/sentry-symfony`, it looks like the non-describable factory is a case where the bundle uses an inline service as part of the factory definition (using `[$inlineDefinition, 'getClient']` as factory).

As the DI component supports that, the descriptor should support it too.

> Would it be possible, instead of throwing an exception, to just output a `null` value

that would lie about the service definition instead of reporting that there is a bug in Symfony. This makes the situation worse IMO.
