### ISSUE TITLE
[Framework]: `base_path` for Twig's `asset()` never works for CLI *and* web

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#47773]
### Symfony version(s) affected

6.1.5

### Description

**Current Situation**

With `$framework->assets()->basePath('/public');` in `framework.php`, when using `{{ asset('assets/logo.svg') }}` in a Twig template, the outcome is *always* (i.e. via CLI and via webserver): `/public/assets/logo.svg`

**Needed Behavior**
* Since on the web server, `/public` is mapped to `/`, the final path in the template needs to be `/assets/logo.svg`.
* But in a CLI command, the final path needs to be `/public/assets/logo.svg`.

The latest(?) PR regarding this was https://github.com/symfony/symfony/pull/36681

My use case: I'm generating PDF's from the same template through web and CLI. And I think that Symfony's current approach (aligning the asset context to the routing context - as far as I understand) will never work in this case, because:

* The solution for generating **links** from CLI is to use a *full URL* (that's what [`default_uri`](https://symfony.com/doc/current/reference/configuration/framework.html#default-uri) is for).
* But this doesn't work for **assets** - you cannot use a full URL as `<img src="">`

### How to reproduce

See above.

### Possible Solution

Maybe create a setting like `cli_base_path` that only gets prefixed to `asset()` when called from CLI.

**Comment by ThomasLandauer** [comment]
Right now, I'm using this as a workaround:
```twig
<img src="{% if 'cli' is same as constant('PHP_SAPI') %}/public{% endif %}{{ asset('assets/logo.svg') }}">
```
See https://www.php.net/manual/en/reserved.constants.php#reserved.constants.core

**Comment by stof** [comment]
To me, a better solution would be to configure your PDF generation to use the public folder as the document root for assets, so that you have the same config for the CLI and the webserver. Otherwise, things will become totally weird when your CLI needs to generate a URL that will be loaded through the webserver (when using a CLI script to send emails for instance).


> * But this doesn't work for **assets** - you cannot use a full URL as `<img src="">`

why ? the `src` attribute of `<img>` supports absolute URLs too

**Comment by ThomasLandauer** [comment]
I think the generator I'm using (dompdf) does neither support a base URL, nor loading assets over the web (i.e. absolute URL). So let's wait for some more opinions...
Either way, I can live with the workaround ;-)

**Comment by stof** [comment]
This is an issue of dompdf then, not of Symfony. Not allowing you to configure what is the base for resolving relative URLs does not make sense to me.

**Comment by ThomasLandauer** [comment]
Well, the base URL is not the problem (manually prefixing *everything* with `public` is easy). The problem is that it needs to be different in CLI and webserver context. And if I were the dompdf maintainer, I'd probably say: "Just give me a URL that works ;-)"

**Comment by stof** [comment]
it needs to be different only because you want to resolve things differently in the CLI and the webserver. In your case, it looks like you want the CLI to generate URLs relative to the project root rather than to the document root. If the dompdf library does not let you configure what is the document root for relative URLs, it is an issue of that library IMO.

And symfony won't automatically change the CLI to generate asset URLs based on the project root instead, because that would break lots of use cases. It would break all cases where you use the CLI to generate some HTML that is then sent elsewhere where URLs will be loaded from the webserver (sending emails from a worker for instance, or pre-generating HTML snippets for a cache).

**Comment by ro0NL** [comment]
also, i dont think a global setting would work for the better, since IMHO this issue is context specific.

**Comment by y4roc** [comment]
Maybe the package function of assets would help you? Then you can use `{{ assets('img.png', 'cli') }}` in the templates for dompdf in twig.

Edit:
https://github.com/dompdf/dompdf/wiki/Usage#setbasepath – You can set basepath in dompdf.  😉

**Comment by xabbuh** [comment]
let's close here as it looks like there are already good enough solutions for this edge case
