### ISSUE TITLE
[Cache] DefaultMarshaller triggers deprecation when resources are serialized via igbinary

### ISSUE THREAD

**Issue by megawilddaddy** [symfony/symfony#47974]
### Symfony version(s) affected

5.4

### Description

DefaultMarshaller triggers deprecation when resources are serialized via igbinary (in our case resources are guzzle responses that we cache).

Deprecated: igbinary_serialize(): Cannot serialize resource(stream) and resources may be converted to objects that cannot be serialized in future php releases. 

\Symfony\Component\Cache\Marshaller\DefaultMarshaller::marshall

### How to reproduce

```
$marshaller = new DefaultMarshaller(true);
$failed = [];
$values = [curl_init()];
$serialized = $marshaller->marshall($values, $failed);
```

### Possible Solution

Do not use igbinary for resources serialization

**Comment by nicolas-grekas** [comment]
I'm not sure their authors will agree but to me this should reported at igbinary: the deprecation is not legit since the php engine itself doesn't trigger it.

But the root issue is cache response objects. This works "by change" - these objects are not supposed to be cacheable. You should instead extract the exact info you want to cache in a dedicated simpler structure.

I'm closing because this is not something we can do on our side.
