### ISSUE TITLE
[FrameworkBundle] Configuring framework exceptions does not work with config builders

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#48191]
### Symfony version(s) affected

6.2.0-BETA2

### Description

PHP example from https://symfony.com/doc/current/reference/configuration/framework.html#exceptions doesn't work. It fails with error
```
Symfony\Config\FrameworkConfig::exceptions(): Argument #1 ($value) must be of type array, string given, called in /vagrant/fe-bl-service/config/packages/framework.php
```

### How to reproduce

```php
<?php

declare(strict_types=1);

use Symfony\Component\Messenger\Exception\RejectRedeliveredMessageException;
use Symfony\Config\FrameworkConfig;

return static function (FrameworkConfig $frameworkConfig): void {
    $frameworkConfig->exceptions(RejectRedeliveredMessageException::class)->logLevel('debug');
}
```

**Comment by fancyweb** [comment]
Looks like a doc issue to me. Does it currently work for you with 6.1 or a previous version? :thinking:

**Comment by ostrolucky** [comment]
Happens with 6.1.7 as well

**Comment by MatTheCat** [comment]
I notice there is no call to `useAttributeAsKey` in `framework.exceptions` definition and that’s why the `FrameworkConfig` is not generated as expected.

It seems the `YamlReferenceDumper` does not care but I’m not sure about the `XmlReferenceDumper` :thinking: 

This comes from https://github.com/symfony/symfony/pull/42244; do you have an insight @lyrixx?

**Comment by MatTheCat** [comment]
Okay so the main issue is how the configuration is defined. The documentation could be updated for the XML part but it doesn't seem to be a way configuring `framework.exceptions` using the ConfigBuilder.

FTR this is how you're currently supposed to configure exceptions using XML:

```xml
<framework:exceptions>
    <framework:exception name="Symfony\Component\HttpKernel\Exception\BadRequestHttpException" log-level="info" status-code="422" />
</framework:exceptions>
```

Whereas you would expect from other configs to write

```xml
<framework:exception
    class="Symfony\Component\HttpKernel\Exception\BadRequestHttpException"
    log-level="info"
    status-code="422"
/>
```

Problem is: fixing the configuration is needed for using the ConfigBuilder, but it would be a BC break for XML format users. Though, https://symfony.com/doc/current/contributing/code/maintenance.html says if “the current buggy behavior is not widely used as a "feature"” it can be fixed in a patch version, so I'll try a pull request against `5.4`.

**Comment by ostrolucky** [comment]
I think there are more places with same issue actually, eg. `rate_limiter` configuration.

**Comment by MatTheCat** [comment]
What is the issue with `rate_limiter`?

I noticed [`framework.workflows`](https://symfony.com/doc/current/reference/configuration/framework.html#workflows) examples are also wrong but it seems to be only a documentation issue.

**Comment by ostrolucky** [comment]
rate_limiter has custom keys (like `framework.rate_limiter.foobar`) similar like exceptions, but there is no way to specify them. Who knows how many configs like this there are 🤔

**Comment by MatTheCat** [comment]
I tested [the documentation](https://symfony.com/doc/current/rate_limiter.html#configuration) samples and did not have any issue using Symfony 6.1 (you’re supposed to set the key through a `limiter`). This would be another issue anyways!
