### ISSUE TITLE
[Cache] Attempted to load class "�" from the global namespace, when using expiresAfter()

### ISSUE THREAD

**Issue by zim32** [symfony/symfony#48195]
### Symfony version(s) affected

6.1.6

### Description

When settings expires on cache item, this error happens

```
 Attempted to load class "�" from the global namespace.  
  Did you forget a "use" statement? 
```

### How to reproduce

```
<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Contracts\Cache\CacheInterface;
use Symfony\Contracts\Cache\ItemInterface;

class TestCommand extends Command
{
    public function __construct(private readonly CacheInterface $cache)
    {
        parent::__construct(null);

        $this->setName('app:test');

    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {

        $this->cache->get('test-key', function(ItemInterface $item) {
            $item->expiresAfter(3);

            return '123';
        });

        return 0;
    }

}
```

### Possible Solution

I see there is a strange code in  https://github.com/symfony/cache/blob/6.1/CacheItem.php#L186
$valueWrapper = self::VALUE_WRAPPER and then new expression is used. But  VALUE_WRAPPER is just const  "�"

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by zim32** [comment]
This is strange, but now I can not reproduce this error.

**Comment by zim32** [comment]
I will close due to lack of reproducible code

**Comment by TracKer** [comment]
I just got that issue. I didn't find what's causing it yet, but here is what's happening. There is a class called `�` in file `ValueWrapper.php` https://github.com/symfony/symfony/blob/450113c6f3c417123f74181c310c5a032ccf17e1/src/Symfony/Component/Cache/Traits/ValueWrapper.php#L19

The problem is that the class is called "\xA9", but the composer class map knows it as "\xEF". And when class loading is happening it can't find the class with such name.

**Comment by TracKer** [comment]
**For those who will have this issue in the future** - all you need to do is to drop `vendor` folder and perform `composer install` on the broken environment. The problem is there because of an unusual file name `©` in `ValueWrapper.php` file
https://github.com/symfony/symfony/blob/450113c6f3c417123f74181c310c5a032ccf17e1/src/Symfony/Component/Cache/Traits/ValueWrapper.php#L19

There is a discussion related to that file name: https://github.com/symfony/symfony/discussions/46477

Most probably your file `ValueWrapper.php` got converted into a multibyte representation, and the class name from a 1-byte character got converted into a 3-byte character. My file got converted while syncing between 2 machines using the Synthing tool.

In the file `CacheItem.php` there is a constant with hardcoded a 1-byte HEX code of a `©` character, which means if your class was renamed to a 3-byte character it would never be found by composer autoloader.
https://github.com/symfony/symfony/blob/450113c6f3c417123f74181c310c5a032ccf17e1/src/Symfony/Component/Cache/CacheItem.php#L25
Most likely it will fail over here:
https://github.com/symfony/symfony/blob/450113c6f3c417123f74181c310c5a032ccf17e1/src/Symfony/Component/Cache/CacheItem.php#L172

That is an extremely rare case that should not appear in a correct deployment process, but it can waste a couple of hours of your time...
