### ISSUE TITLE
[OptionsResolver] Support nested options

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#4833]
It is currently not possible to configure nested options. For example:

``` php
$resolver->setDefaults(array(
    'db' => array(
        'dsn' => null,
        'user' => 'root,
        'password' => '',
        'port': 3306,
    ),
));
```

It is not possible to resolve this configuration in the following way:

``` php
$resolver->resolve(array(
    'db' => array(
        'dsn' => ...
    ),
));
```

because now the other default values under "db" will be dropped. Also, it is not possible to specify allowed values or types for the nested options.

**Comment by Yoshix** [comment]
This might be overly simplistic, but wouldn't it suffice to *automatically* resolve an `OptionsResolver` that is used as a default value? E.g.:

    $nested3rdLevel = new OptionsResolver();
    $nested3rdLevel->setDefault('3rd', 1);

    $nested2ndLevel = new OptionsResolver();
    $nested2ndLevel->setDefault('2nd', $nested3rdLevel);

    $nested1stLevel = new OptionsResolver();
    $nested1stLevel->setDefault('1st', $nested2ndLevel);

    $options = $nested1stLevel->resolve([]); //  ["1st" => ["2nd" => ["3rd" => 1]]]

The only bc-break this would introduce is that an `OptionsResolver` could not be used as a default value (though this could be fixed by using some internal flag). Which seems to me, is a rare use-case anyway.

I actually have a (*seemingly*) working implementation for the above (minus access to the parent resolver), though I wanted to first ask if this approach would be acceptable at all?

**Comment by webmozart** [comment]
I will close this issue. It's been open for a while and I don't think that this is something that the OptionsResolver really should support. I also don't see a way to do this without making the implementation overly complex.

**Comment by Gummibeer** [comment]
For all interested: I've found this package [sauls/options-resolver](https://github.com/sauls/options-resolver) which does support deep options resolving by `dot.notation` in configuration.

**Comment by yceruto** [comment]
See https://github.com/symfony/symfony/pull/27291 for full implementation of the original request. Could this request be reopened, please?
