### ISSUE TITLE
`Route` attribute can not be used on `__invoke()` methods in invokable actions anymore

### ISSUE THREAD

**Issue by localheinz** [symfony/symfony#48438]
### Symfony version(s) affected

6.2.0

### Description

An automated update of https://github.com/symfony/framework-bundle/compare/v6.1.7...v6.2.0 broke all invokable actions:

![CleanShot 2022-12-02 at 11 07 35@2x](https://user-images.githubusercontent.com/605483/205268593-823eb4cc-b0f5-4daa-bab9-08be65f1289a.png)

Unless I forgot to read, this change is neither documented in release notes nor in the documentation.

What is the purpose of this obviously breaking change?

### How to reproduce

Invokable action with attribute on `__invoke():

```php
<?php

final class FooAction
{
    #[Routing\Annotation\Route(
        path: '/foo/',
        name: 'foo,
        methods: [
            HttpFoundation\Request::METHOD_GET,
        ],
    )]
    public function __invoke(): HttpFoundation\Response
    {
        // ...
    }
}
```

### Possible Solution

Move attribute to class level.

```php
#[Routing\Annotation\Route(
    path: '/foo/',
    name: 'foo',
    methods: [
        HttpFoundation\Request::METHOD_GET,
    ],
)]
final class FooAction
{
    public function __invoke(): HttpFoundation\Response
    {
        // ...
    }
}
```

**Comment by fancyweb** [comment]
Hello, could you provide a small project that reproduces the issue plz?

**Comment by stof** [comment]
this looks like a bug in PHP. That `__invoke` is a method.

And this error is triggered by PHP itself (when instantiating the attribute, PHP checks the attribute target).

**Comment by localheinz** [comment]
@stof 

The only thing that has changed is the dependency update, still using the same PHP version.

**Comment by nicolas-grekas** [comment]
This is a bug in early PHP 8.1 AFAIK.
Which version are you using? Can you try with latest 8.1 if not already the case?

**Comment by localheinz** [comment]
@nicolas-grekas 

```shell
php -v
```

yields

```
PHP 8.1.8 (cli) (built: Aug  2 2022 07:31:17) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies
```

Nothing has changed here from my side. The only thing that has changed is the dependency update, still using the same PHP version.

**Comment by stof** [comment]
Well, the code in Symfony indeed changed between 6.1 and 6.2. But the latest PHP 8.1 version is 8.1.13, not 8.1.8. Upgrading to the latest PHP version should fix that as PHP fixed that bug in the attribute target validation.

**Comment by localheinz** [comment]
@stof 

But why would I need to update the PHP version that I currently use?

Everything worked fine when using `symfony/framework-bundle:6.1.7`. The update to `symfony:framework-bundle:6.2.0` broke my app. 

Perhaps the platform requirement in [`composer.json`](https://github.com/symfony/symfony/blob/v6.2.0/composer.json#L36) needs an update?

It would be new to me that - when updating a single `composer` dependency - it is perfectly normal for everyone to also update the PHP version. If the `composer` dependency required a newer PHP version, that should be a hard requirement of said dependency in its `composer.json`, in my opinion.

**Comment by stof** [comment]
Symfony 6.2 happens to be affected by a **PHP** bug, that we reported to PHP and they fixed it upstream. Why would we have to find a way to workaround that PHP bug (which is already fixed in PHP) ? The time of the Symfony core team is better spent elsewhere.
Framework 6.1was not triggering that PHP bug for your code because it requires a specific situation (note that I think that it is still possible to trigger that bug with Symfony 6.1 with different kind of logic, it is just that the RouterListener was not reaching that code path before, but removing that code path would force to remove a feature added in 6.2)

**Comment by stof** [comment]
See https://3v4l.org/PaqQd. This is a bug introduced in PHP 8.1.6 and fixed in 8.1.10.

**Comment by ostrolucky** [comment]
Would it make sense to declare conflict with PHP 8.1.6-8.1.9?

**Comment by stof** [comment]
The bug only impacts controllers using `__invoke` as method name. So the conflict rule might be too harsh for projects not using callable classes.

Side note: we cannot add the conflict in 6.2.0, only in 6.2.1. So this would result in installing the 6.2.0 release on those PHP versions as that would be the highest version declared compatible with them, which might be even worse as result.

**Comment by localheinz** [comment]
@stof 

The matter is that - ceteris paribus - the change in https://github.com/symfony/framework-bundle/compare/v6.1.7...v6.2.0 without adjusting the PHP version requirements (see https://github.com/symfony/symfony/issues/48438#issuecomment-1335159625) is a breaking change.

**Comment by stof** [comment]
@localheinz first, this has nothing to do with changes in FrameworkBundle (the code that triggers the error is in HttpKernel).
And we are talking about a PHP regression that is already fixed in PHP since several patch versions. If you consider that being affected by an already solved bug is a BC break that we need to fix, the pre-requisite would be to have a CI setup running Symfony tests against all previous patch releases of PHP as well, not only the latest version (otherwise we are not able to make such guarantee as we would not even know that). That's quite an insane setup to me.

And again, we have no way to add the conflict rule in the 6.2.0 release (time travel would be a prerequisite for that). And adding this conflict rule in 6.2.1 would make things worse instead of better (it would not forbid you to install 6.2.0 and be affected by the PHP bug, but would forbid you from benefiting from other Symfony improvements, and it will even forbid you to workaround the bug by moving away from `__invoke` if you cannot update PHP while staying on an uptodate version of Symfony).

And last thing: if you really care about compatibility with older patch releases of PHP itself, you can still spend _your_ time to find a different implementation for the feature that does not trigger the PHP bug (while still not being able to forbid regressions on that as the CI would not run the broken PHP version). But I definitely won't dedicate *my free time* to that work.

**Comment by nicolas-grekas** [comment]
I'm closing as explained, this is not on us.

**Comment by localheinz** [comment]
@stof 

I have opened the issue because I encountered it - not because I expected anyone to fix it.

**Comment by stof** [comment]
Well, you told us you consider it as a BC break

**Comment by localheinz** [comment]
@stof 

Thank you for your feedback!
