### ISSUE TITLE
[Clock] use default timezone in `MockClock`?

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#48536]
### Description

Currently the `MockClock` [falls back to `UTC` timezone ](https://github.com/symfony/symfony/blob/v6.2.1/src/Symfony/Component/Clock/MockClock.php#L30) whenever no timezone is provided.

Question: Can we not use `date_default_timezone_get` [as done in the `NativeClock`](https://github.com/symfony/symfony/blob/v6.2.1/src/Symfony/Component/Clock/NativeClock.php#L25)?

In my app I'm using a local timezone as default and this makes it slightly annoying to work with the `MockClock` as I need to provide a DateTime instance myself and cannot rely on the default constructor as this would make it use `UTC`.

**Comment by derrabus** [comment]
> I need to provide a DateTime instance myself

No, you just need to provide a timezone.

```php
new MockClock(timezone: date_default_timezone_get());
```

I must admit, I'm pretty happy that the MockClock does not depend on any ini settings like the default timezone.

**Comment by dmaicher** [comment]
> No, you just need to provide a timezone.

Yeah ok. But I can still not rely on the default constructor.

Maybe its just me then who finds this confusing :smile: 

`(new NativeClock())->now()` vs `(new MockClock())->now()` basically have different timezones for me :confused:

**Comment by uuf6429** [comment]
Sorry to interject, but @dmaicher from my understand there is no reason why anything in those two classes should be in sync.
To me UTC is a sensible default for a mock clock, whereas the native "default" time zone...rightly belongs to the "native" class.

> Yeah ok. But I can still not rely on the default constructor.

I see what you mean and I think the problem is elsewhere and a matter of design... MockClock should not take "now" as a default time, in my opinion. It should either be user-defined or an absolute value, like the timezone.

> `(new NativeClock())->now()` vs `(new MockClock())->now()` basically have different timezones for me 😕

For me that's expected and a non-issue, in my opinion. As said above, they're 2 classes that share an interface, that's the only connection.

**Comment by nicolas-grekas** [comment]
Clock-consuming services should usually be TZ independant. The best way to ensure that something doesn't rely on a TZ is to test it with various TZ and expect results to remain the same. That's also why I think it's good to have MockClock use a different TZ than NativeClock: it asks for thinking about the TZ requirements of some piece of code.

If your service is really TZ-dependent, you can use `withTimezone()` to force a specific one in your code (and then, the TZ of MockClock will be irrelevant.)
