### ISSUE TITLE
[RFC][Routing] Automatic bundle routing registration

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony#48557]
### Description

I know this has probably already been discussed in the past, but I'd like to be sure nobody has changed his mind, and I'd also like to be sure it's not possible _to find a way_.

**TL;DR:** Adding routing directly inside a bundle would be nice. There are many possibilities to do it that may be considered.

I'm currently building a mini bundle that adds content to the `.well-known` folder. Those routes will probably never be changed. But still, the user needs to specify manually (or via flex) the routes. This seems really like something not-easy and not-logic.

If you think it outside of my little bundle, you can take API Platform, and in fact, many many bundles that use a dynamic route loader... Still need to be imported... While the user has almost no power over the routing that will be added to its application.

I think it's time to consider adding a feature inside Symfony that allows bundles to define (at least) an entry-point route (that the user may redefine to add a prefix if required). WDYT?

**Comment by stof** [comment]
This was rejected in the past, because it removes control for the routes that are the public API of the project (and sometimes, the order of routes might have an impact).
A custom route loader still gives control to the project to decide whether they import it or no (so if the project does not want those routes, it can remove the import, and it can also change the order of imports if needed).

The recommended way to handle that is to have a recipe that adds the route import by default.

**Comment by Nek-** [comment]
I'm pushing again the topic because I think this is creating an unnecessary configuration for many bundles, while it could be made simpler.

**Comment by OskarStark** [comment]
A very nice way would be to be able to ship this recipe via the repo itself, even this was discussed in the past, but I doesn't know the outcome of this discussion

**Comment by MatTheCat** [comment]
@OskarStark https://github.com/symfony/flex/issues/206

> This is not something that is going to happen.

This was three years ago though.

**Comment by nicolas-grekas** [comment]
I agree with @stof, the reasons of the current design are still sound to me. I'm :-1: sorry.
