### ISSUE TITLE
Use `block_prefix` dynamically

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony#48776]
### Description

Hi,
It would be interesting to be able to update the `block_prefix` dynamically.

### Example

```php
// in Form Type
public function getBlockPrefix(): string
{
    return 'registration-' . $this->step;
}
```

```php
// Or in controller:
$form = $this->createForm(RegistrationFormType::class, $user, [
    'block_prefix' => 'registration-' . $step,
]);
```

**Comment by xabbuh** [comment]
Can you describe a use case where this feature would be useful for you?

**Comment by stof** [comment]
There is actually a `block_prefix` option to allow injecting an additional block prefix to be used during theming (that has higher priority than the block prefix of the type being used). So your second example actually works (except for the fact that dashes are forbidden in Twig block names so you should use a different value if you actually want to use it as part of the form theming).

The first code snippet would imply that you have several instance of the form type itself, and this is not supported in the form component at all (it would require rewriting the component from scratch with a different architecture, which is a no-go). The fact that we cannot have several instances for the same type is the main reason why we change the component to use class names directly to reference types instead of having a type name (as was the case before Symfony 2.7).

**Comment by stof** [comment]
Note that if your goal is to change the root *name* of the form (which indeed defaults to the block prefix of the type being used), the `block_prefix` option will not help for that). The solution instead is to create a named form in the controller (which requires using the FormFactoryInterface directly as there is no shortcut for that in AbstractController)

**Comment by seb-jean** [comment]
> Can you describe a use case where this feature would be useful for you?

On a multi-step registration.

**Comment by stof** [comment]
@seb-jean this still does not explain how this is useful to you (at leats not with just the code snippet you shared until now).

**Comment by seb-jean** [comment]
Let's take the example of user preferences managed in a `Preference` entity with `age` and `height` as properties.

The idea is to make an inline editing system so to stay on the same page.

These 2 properties are managed in the same form `PreferenceFormType` but will not be displayed all at the same time.

The problem is that there could be several times the same form `id`, `name` on the same page. 

```php
// /src/Form/PreferenceFormType.php

public function buildForm(FormBuilderInterface $builder, array $options): void
{
    switch ($options['preference']) {
        case 'height':
            $builder->add('height');
            break;
        case 'age':
            $builder->add('age');
            break;
    }
}
```

**Comment by stof** [comment]
@seb-jean form ids and names are generated based on the name of the root form. The solution for that is to use named forms, not to change the block prefix.

**Comment by seb-jean** [comment]
Ok I see. Thanks.
