### ISSUE TITLE
[Uid] Nil and Max uuid are no more valid

### ISSUE THREAD

**Issue by bobahvas** [symfony/symfony#48800]
### Symfony version(s) affected

6.2

### Description

Breaking change after update from 6.1 to 6.2.

```
Uuid::isValid('00000000-0000-0000-0000-000000000000'); // 6.1 = true, 6.2 = false
Uuid::isValid('ffffffff-ffff-ffff-ffff-ffffffffffff'); // 6.1 = true, 6.2 = false
```

### How to reproduce

```
Uuid::isValid('00000000-0000-0000-0000-000000000000'); // 6.1 = true, 6.2 = false
Uuid::isValid('ffffffff-ffff-ffff-ffff-ffffffffffff'); // 6.1 = true, 6.2 = false
```

**Comment by alamirault** [comment]
Thanks for your description.

Validation regex was updated in this PR https://github.com/symfony/symfony/pull/47518/files#diff-322d8c9c59ef8b2e6b28ac27eee6985730eacc0f834d45e26931d904283c981cR120

Friendly ping @nicolas-grekas, can we update regex to `{^[0-9a-f]{8}(?:-[0-9a-f]{4}){2}-[89ab0f][0-9a-f]{3}-[0-9a-f]{12}$}Di` in order to allow NIL and MAX uuids (I can create PR)? Or is not the solution ?
