### ISSUE TITLE
On Windows platforms where projects are deployed on junctions/symlinks, symfony/runtime's ComposerPlugin writes bad $projectDir

### ISSUE THREAD

**Issue by nerdgod** [symfony/symfony#49041]
### Symfony version(s) affected

6.0+

### Description

On Windows platforms, if the project is placed in a junction or symlink on another drive than the directory the commands are run from, then, symfony/runtime/Internal/ComposerPlugin.php' `$this->composer->getConfig()->get('vendor-dir')` returns the junction path, but  `realpath(Factory::getComposerFile())` returns the junction target path. 

So if your project is at C:\www\fooProject ->{junction-to}-> D:\some-storage-directory\www\fooProj, the call to `$fs->makePathRelative()` tries to make relative paths across filesystems and you end up with a project directory of `C:\www\fooProject\\D:\some-storage-directory\www\fooProj` in your `vendor/autoload_runtime.php`. 

### How to reproduce

Create a project on a windows system having two separate drives.

In another directory use `mklink /D <projname> <orig_proj_path>`

e.g.: project is in Z:\Projects\foo (the 'source') but it is linked to C:\Users\fabien\Desktop\foo (the 'link')

change directory to the link. 

remove the vendor dir and re-run composer update

run any composer scripts (auto-scripts or cache:clear)

the script fails with an error because the C:\Users\fabien\Desktop\foo\vendor/autoload_runtime.php has something like

```
$runtime = new $runtime(($_SERVER['APP_RUNTIME_OPTIONS'] ?? $_ENV['APP_RUNTIME_OPTIONS'] ?? []) + [
  'project_dir' => __DIR__.'/Z:/Projects/foo/',
]);
```

### Possible Solution

Call `realpath()` when retrieving both the vendor-dir property and the the composer.json file.

**Comment by nerdgod** [comment]
see https://github.com/nerdgod/symfony-runtime/tree/nerdgod-patch-1

**Comment by xabbuh** [comment]
Are you up for sending a PR with your solution?

**Comment by nerdgod** [comment]
https://github.com/symfony/runtime/pull/3

**Comment by stof** [comment]
@nerdgod PRs should be sent in the monorepo where development happens, not in the subtree split.

**Comment by eartahhj** [comment]
For those that are struggling with this exact problem while running a Symfony < 5.4.19 (which fixed the issue), I had to try and research for 2 hours but this is the temporary solution I came up with:

(Symfony 5.4.4)

1) Create an `autoload_runtime.template` file somewhere in your app folder, could be even in the root where the composer.json file is

2) You can find the original `autoload_runtime.template` file in `vendor/symfony/runtime/internal`. Copy the contents and paste them in the new `autoload_runtime.template` file you created

3) Now in the new file, change the line for:
`$runtime = new $runtime(($_SERVER['APP_RUNTIME_OPTIONS'] ?? $_ENV['APP_RUNTIME_OPTIONS'] ?? []) + %runtime_options%);`
with:
`$runtime = new $runtime(($_SERVER['APP_RUNTIME_OPTIONS'] ?? $_ENV['APP_RUNTIME_OPTIONS'] ?? []) + [
  'project_dir' => 'C:/path/to/project',
]);'`

This is because even if I set `project_dir` or `dotenv_path` inside the composer.json file they apparently get ignored.
Of course adjust the `project_dir` path according to your needs.

4) Modify your `composer.json` file and configure the path to point at the new autoload template in the `extra` options:
`    "extra": {
        "runtime": {
            "autoload_template": "C:/path/to/the/new/file/autoload_runtime.template"
        },
    }`

I hope this helps someone, expecially myself from the future in case I encounter this problem again. And thanks for finding this issue and solving it, so at least I got confirmation that it was a bug and not just a problem in my system configuration. Took me a while to figure it all out, but anyway.
