### ISSUE TITLE
Issues with the fix for CVE-2022-24894 

### ISSUE THREAD

**Issue by Toflar** [symfony/symfony#49257]
### Symfony version(s) affected

4.4 - 6

### Description

I have some remarks regarding https://symfony.com/blog/cve-2022-24894-prevent-storing-cookie-headers-in-httpcache and its fix in https://github.com/symfony/symfony/commit/d2f6322af9444ac5cd1ef3ac6f280dbef7f9d1fb.

a) First, why remove the header but still store the response? That can cause unwanted behaviour, doesn't it? Imho what should be done is not store the response at all, if `Set-Cookie` (or any other configured header) is present. 
b) Moreover, I think it should've been fixed in `HttpCache`, not in `Store`. It's a problem that affects all the `StoreInterface` implementations, doesn't it? We already have a `private_headers` config that's similar but based on the request and (correclty) affects the behavior of the `HttpCache` no matter the used `StoreInterface` implementation. So why not introduce a new config there for headers that should cause a response not to be cached at all? Something like `uncacheable_response_headers`?

But maybe there are good reasons for the fix in `Store` which I'm missing? As it was a security fix, there is no PR and no discussion for the public where I could've possibly read the reasons for this design decision :-)

### How to reproduce

-

**Comment by nicolas-grekas** [comment]
The issue happens when explicitly opting out from cache-control using `NO_AUTO_CACHE_CONTROL_HEADER`.
This means the intend IS to store the response, even if there is a session being used.
That's why the issue is fixed at the storage level. People are responsible for enabling cache-ability.
About your second proposal - making this independent from the storage - we didn't because it was enough to patch `Store` to solve the issue in Symfony. Given that we didn't consider solving this at a more generic level, I cannot say how nor if it would be possible. If you'd like to give it a try, I'd be happy to review a PR, on 6.3 of course.

**Comment by Toflar** [comment]
I see. Here's my take: https://github.com/symfony/symfony/pull/49318
