### ISSUE TITLE
Add validation rule based on Spoofchecker::isSuspicious()

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#49268]
See https://php.net/spoofchecker.issuspicious

We could then add the annotation automatically in maker-bundle when the intl extension is available.

**Comment by MatTheCat** [comment]
I did a little digging and PHP’s `Spoofchecker` is in a sorry state:

- its name is wrong (should be `SpoofChecker`).
- `isSuspicious`’s second argument `&$errorCode` seems to always be `null` (I guess it should match ICU’s `checkResult`).
- `setRestrictionLevel` is not documented (but works).
- `setAllowedLocales` requires comma-separated locales in a single string.
- no way to set allowed characters sets (ICU provides a `setAllowedChars` method).
- `setChecks` documentation is wrong (some checks concern confusability, not spoof detection).
- `SINGLE_SCRIPT` check should be replaced by `SINGLE_SCRIPT_RESTRICTIVE` level since ICU 51.
- `ANY_CASE` check modifier does not serve any purpose since ICU 58.
- `MIXED_NUMBERS` check constant is missing (you can use its value `128` though).
- `HIDDEN_OVERLAY` check constant is missing (you can use its value `256` though).
- constants are not documented.

**Comment by nicolas-grekas** [comment]
Thanks for digging. This could be worth a bug report on php-src, WDYT?

**Comment by MatTheCat** [comment]
Yes, I think both php-src and php-doc-en need a little dusting on that matter!

**Comment by nicolas-grekas** [comment]
(please don't forget to open an issue on php-src)
