### ISSUE TITLE
Mention security fixes in release notes

### ISSUE THREAD

**Issue by janedbal** [symfony/symfony#49277]
### Description

I can see that release notes pretty often contain note "no significant changes" even when there is security vulderability fix inside. Few I spotted:

- [CVE-2022-24895](https://symfony.com/blog/cve-2022-24895-csrf-token-fixation) - fixed in [symfony-bundle 5.4.20](https://github.com/symfony/security-bundle/releases/tag/v5.4.20)
- [CVE-2022-24894](https://symfony.com/blog/cve-2022-24894-prevent-storing-cookie-headers-in-httpcache) - fixed in [http-kernel 5.4.20](https://github.com/symfony/http-kernel/releases/tag/v5.4.20)

I do not consider security fix as non-significant so I think it would be nice to add some info about that.

**Comment by DanielRuf** [comment]
This also needs clarification (so it is more clear if a project is affected or not), see https://github.com/symfony/symfony/commit/d2f6322af9444ac5cd1ef3ac6f280dbef7f9d1fb#commitcomment-102229935

**Comment by DanielRuf** [comment]
@nicolas-grekas still waiting for feedback (see my link).

**Comment by fabpot** [comment]
This is a limitation on how we are making the release notes on Github.
To make a long story short: the release notes use merge commit messages to detect features, bugs, security issues, and minor changes. That works well for the mono-repo, but now, I realize it does not work so well for the subtree splits: empty commits are removed from the splits (and most of the time, the merge commits are empty). That's why there is such a discrepancy. We will change how we generate those changelogs to avoid such an issue in future releases.

**Comment by nicolas-grekas** [comment]
Closing as the fix doesn't belong to this repo. Also because this should be good starting from the next version.
