### ISSUE TITLE
Wrong authors' GitHub accout links in release notes

### ISSUE THREAD

**Issue by upyx** [symfony/symfony#49298]
### Symfony version(s) affected

all

### Description

I've spotted that sometimes links to authors have issues. 

For example https://github.com/symfony/symfony/pull/48687 

> * bug [[HtmlSanitizer] Fix HtmlSanitizer default configuration behavior for allowed schemes #48602](https://github.com/symfony/symfony/pull/48602) [HtmlSanitizer] Fix HtmlSanitizer default configuration behavior for allowed schemes (@titouan Galopin)
> ... 
> * bug [Fix dealing with ext-redis' multi/exec returning a bool #47979](https://github.com/symfony/symfony/pull/47979) [Cache] Fix dealing with ext-redis' multi/exec returning a bool (@joão Nogueira)

Titouan Galopin account is @tgalopin and João Nogueira is @joaopbnogueira 

I haven't seen the script that produces release notes to say why it happens.

### How to reproduce

See https://github.com/symfony/symfony/pull/48687

**Comment by OskarStark** [comment]
ping @fabpot

**Comment by nicolas-grekas** [comment]
This file lists usernames from https://connect.symfony.com, not github.

**Comment by stof** [comment]
@nicolas-grekas then it should not use the `@` prefix as that makes GitHub treat them as GitHub mentions

**Comment by wouterj** [comment]
Or put a zero-width space in between the `@` and the username. @​wouterj :wink:

**Comment by OskarStark** [comment]
Isn't it possible to use the Github handle instead?

**Comment by upyx** [comment]
> This file lists usernames from https://connect.symfony.com, not github.

Well, it is the reason why release notes have wrong links. Knowing it is a good start for fixing them.

By the way, not all contributors have a Symfony Connect account.

**Comment by nicolas-grekas** [comment]
So, I checked the code, which is in [symfony/gh](https://github.com/symfony/gh/blob/main/src/PullRequest.php#L52)
 and I was wrong, this doesn't happen because of any link to SymfonyConnect, but because the committer isn't linked to their github account, as in https://api.github.com/repos/symfony/symfony/pulls/47979/commits

We have a simple heuristic in gh which is to not add the "@" prefix when the contributor contains a space. We're going to do the same in release notes. That's no 100% perfect but that's a bit better.
