### ISSUE TITLE
symfony/expo-notifier always "Unable to post the Expo message: {"error":"invalid_token","error_description":"The bearer token is invalid"}"

### ISSUE THREAD

**Issue by nmateo** [symfony/symfony#49384]
### Symfony version(s) affected

5.4

### Summary

Sending message from the symfony/expo-notifier package always return invalid_token, despite the token added:

````Unable to post the Expo message: {"error":"invalid_token","error_description":"The bearer token is invalid"}"````
Without or with token set & activated Enhanced Security for Push Notifications on expo push server.

Code is as below

````
    public function createOrderNotif(string $token, int $offerId)
    {
        $options = new ExpoOptions(self::EXPO_TOKEN,
                                    [
                                                'title' => 'Nouvelle offre',
                                                'subtitle' => 'Vous avez reçu une nouvelle offre de mission !',
                                                'data' => json_encode(['offerId' => $offerId]),
                                                'priority' => 'high',
                                                'sound' => 'default',
                                                'body' => 'Test',
                                                'to' => $token
                                    ]);
        $message = new PushMessage('Nouvelle offre', 'Test2', $options);
        $message->transport('expo');

        $this->notifier->send($message);
    }
````

### Link to the related docs page

https://docs.expo.dev/push-notifications/sending-notifications/#push-tickets

### How to reproduce

Send message using expo transport to expo API, on Symfony 5.4

**Comment by OskarStark** [comment]
Did you contact their support? To me the error message is clear 🫤

**Comment by nmateo** [comment]
> Did you contact their support? To me the error message is clear 🫤

Thanks, i'm contacting their support right now, i'll keep updated here if they tell me it's an error on the symfony/expo-notifier end

**Comment by franckranaivo** [comment]
I think it's not related to _symfony/expo-notifier_. According to your code, the first argument in `ExpoOptions` construction should be the recipient of your message (not the token linked to your account).
 
It should be in the form of `ExponentPushToken[someRandomToken]`, this token is generated when you call `Notifications.getExpoPushTokenAsync()` in your expo code. They call it token and not an identifier because it is always changed each time you run a build for your app. You even don't have to set `$to` in the $options array.

I presume `self::TOKEN` is the one you have to set in your `EXPO_DSN` in your `.env` file. It is the one which is linked to your account (see documentation https://symfony.com/doc/current/notifier.html#push-channel on how to add this token). You don't have to set this token if you choose not to enhance security

No need to specify transport as `ExpoOptions` can trigger the expo transport automatically. 

And last, It's better you set `data` directly in the third argument of `ExpoOptions` as this is the place for it. 

See example code below:
```php
$options = new ExpoOptions(
                    $token, // here you provide something like ExponentPushToken[someString]
                    [
                        'body' => $message,
                        'sound' => 'default'
                    ],
                    [
                        '{"id" : '.$foo->getId().'}'
                    ]
                );

                $msg = new PushMessage('Message title', $message, $options);
```
From documentation, I used texter as a transport to send this message. Maybe it is useful.

**Comment by planim** [comment]
I had similar problem in one of my old projects.
try set:
`EXPO_DSN=expo://default`
instead of:
`EXPO_DSN=expo://Token@default`
in your`.env`
and use:
```php
$this->notifier->send(
    new PushMessage('title', 'test', new ExpoOptions('ExponentPushToken[...]', [], ['offerId' => $offerId, 'subtitle' => '...']))
);
```
or example from @franckranaivo

**Comment by xabbuh** [comment]
I think we can close here for now given that there wasn't any more details which indicate that this is an issue in the Symfony codebase.
