### ISSUE TITLE
[Serializer] SerializedPath option not working on non-scalar types, which are serialized into scalar (eg. DateTime)

### ISSUE THREAD

**Issue by HonzaMatosik** [symfony/symfony#49494]
### Symfony version(s) affected

6.2.0

### Description

If SerializedPath is set on non-scalar types, eg. `DateTimeImmutable`:
```php
final class ObjectDummyWithContextAttributeAndSerializedPath
{
    public function __construct(
        #[Context([DateTimeNormalizer::FORMAT_KEY => 'm-d-Y'])]
        #[SerializedPath('[property][with_path]')]
        public \DateTimeImmutable $propertyWithPath,
    ) {
    }
}
```

Normalization fails with error:
```
Symfony\Component\Serializer\Exception\LogicException: The element you are trying to set is already populated: "[property][with_path]"
```

But `DateTimeImmutable` is serialized into string, so expected result is:
```php
['property' => ['with_path' => '02-22-2023']
```

### How to reproduce

I created unit test for this case, which should be sufficient for reproducing: https://github.com/HonzaMatosik/symfony/commit/51f1969ebb6beaae25b8d942d9ac45b8a6768138

**Comment by emomaliev** [comment]
Faced the same problem.

Hey @boenner. What is the logical fallacy if properties are set to values?
https://github.com/symfony/symfony/blob/1dcb0f919c7183a795e15805a34db709ce27388c/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L654-L656


Because of this construction, we get an exception when serializing an object, for example, to json.

A similar problem is described here #49225

**Comment by boenner** [comment]
The normalizer is trying to set the value multiple times because non-scalar values are pushed twice into `updateData()` in the `AbstractObjectNormalizer`. Skipping the first `updateData()` changes the order of elements in the serialized string, so I reverted that because of a possible BC break (see: https://github.com/symfony/symfony/pull/43534#discussion_r806918589). It seems like I didn't test the `SerializedPath` with non-scalar values afterwards. Sorry!

I took your tests, @HonzaMatosik, into a branch and changed the behavior: https://github.com/boenner/symfony/tree/serializer-serializedpath-with-non-scalar-types. Can you check if that fix works for you?

**Comment by emr-dev** [comment]
Yes, that solved the problem. Thanks)

**Comment by emomaliev** [comment]
Hi this works great
