### ISSUE TITLE
Make RememberMeHandlerInterface more consistent

### ISSUE THREAD

**Issue by uncaught** [symfony/symfony#49511]
### Description

The [`RememberMeHandlerInterface` ](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Security/Http/RememberMe/RememberMeHandlerInterface.php) has a weird concept:
- `consumeRememberMeCookie` gives you an already parsed version of the cookie in the form of a `RememberMeDetails` instance.
- `createRememberMeCookie` doesn't want anything in return, but expects you to fill the cookie yourself with the format that `RememberMeDetails::toString` provides.
- And finally `clearRememberMeCookie` doesn't even give you the cookie nor the details, but expects you to do something with it.

This is all very inconsistent.

1. Either give `consumeRememberMeCookie` nothing at all and let the handler read/write the cookie consistently in its own format, independent of what `RememberMeDetails` wants it to be.
2. Or expect `createRememberMeCookie` to return the `RememberMeDetails` and read/write the cookie consistently outside of the handler. And also provide the details to `clearRememberMeCookie`.

However, the latter wouldn't work if you wanted to update the cookie in `consumeRememberMeCookie`, too. Giving `RememberMeDetails` an `updateValue` method, which writes to the cookie, could fix this though.

For most freedom of a custom handler, I'd prefer the first option.

**Comment by stof** [comment]
When you look at what AbstractRememberMeHandler implements vs what it delegates to subclasses, things are less confusing as it handles all the parts dealing with the request.

One thing that could be done to make it complete in that regard is adding a protected method taking the user and returning a `RememberMeDetails` and then implementing `consumeRememberMeCookie` in the abstract class as `$this->createCookie($this->createRememberMeDetails($user));`

**Comment by uncaught** [comment]
Yes, maybe the AbstractRememberMeHandler could abstract this inconsistency better.

However, I can't use the AbstractRememberMeHandler because I need more control over what is given to the database and how the user provider is called. I need the user's id in the database among other things and don't call the provider by the user identifier, but by id. So nothing inside the RememberMeDetails except for the value are of interest to me.

It also seems that the `RememberMeDetails::value` could do with a better concept than being a string of imploded arbitrary values. Because when I used PersistentRememberMeHandler as an example for my custom handler, it was very confusing to see the value containing 2 items at one point and 4 items at another point:

```php
    public function consumeRememberMeCookie(RememberMeDetails $rememberMeDetails): UserInterface
    {
//...
        [$series, $tokenValue] = explode(':', $rememberMeDetails->getValue());
//...
    }

    public function processRememberMe(RememberMeDetails $rememberMeDetails, UserInterface $user): void
    {
        [$lastUsed, $series, $tokenValue, $class] = explode(':', $rememberMeDetails->getValue(), 4);
//...
    }
```

So actually I would prefer to be free of the RememberMeDetails in general for a fully custom handler. So the interface should drop it.

This is all just a wishful suggestion of course, nothing here is a bug or wrong - you're doing great work :smile:

**Comment by stof** [comment]
Being entirely free would force you to reimplement the whole remember me system yourselves, as the RememberMeAuthenticator relies on this RememberMeDetails object as well.

And the Symfony UserProviderInterface expects to be called with the user identifier (which can be anything you want, so it *could* be your DB identifier rather than a human-selected value, even though it would be complex to do that only for remember-me). Otherwise, it will also break some things in the RememberMeAuthenticator.

> Because when I used PersistentRememberMeHandler as an example for my custom handler, it was very confusing to see the value containing 2 items at one point and 4 items at another point:

`processRememberMe` in that one has a value with 4 delimiters only because `consumeRememberMeCookie` replaces the value with 4 segments before calling the parent method (which is the one calling `processRememberMe` which should be protected and not public according to the parent visibility). this only looks like a hacky way to pass extra details to the other method.
The *public* value of a remember me cookie for the persistent handler always has 2 segments (see that `processRememberMe` changes back the value before creating the cookie).

In any case, the structure of your value is in the control of your handler, as long as the various public methods of your handler are expecting the same format.

**Comment by uncaught** [comment]
> RememberMeAuthenticator relies on this RememberMeDetails object as well.

Yes, although it looks like it's the only place. One could argue, that the `consumeRememberMeCookie` could be made to return the PasswortInterface or UserBadge, then the authenticator would be free of the details, too.

Anyway, thank you for your input! I don't think we need to discuss this any further if I can't convince you ;) It's a niche piece of code and probably won't be seen by a developer much after the initial implementation 😄
