### ISSUE TITLE
[Messenger] Out of memory errors is ignored by retry policy

### ISSUE THREAD

**Issue by julienfastre** [symfony/symfony#49545]
### Symfony version(s) affected

5.4.19

### Description

When a Messenger's message is handled and causes a "memory exhausted" error, the retry policy is ignored.

### How to reproduce

0. configure a transport (for my own: doctrine transport)
1. send a message to that transport;
2. handle message from cli (`messenger:consume`), and create a "out of memory" error. Every time the handling fails, the command stops;
3. restart the command: the message is retried more than the maximum of retry policy, without being considered as "failed"

### Possible Solution

Maybe could we update the number of tries before handling the message ?

**Comment by benmeynell** [comment]
@julienfastre - More information, please? At a minimum, please post your entire `messenger:consume` command.

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by tsadiq** [comment]
Don't know if this has somehow been fixed in newer versions or not, but i have the same issue on my old 5.4 (yeah yeah, i know…): when a message fails because of a memory issue, the message is stuck forever in the queue as the worker crashes and, i assume, cannot mark the message as failed. 

When i check the database, the message is looking like it's being processed, but it's not - the worker taking care of it is crashed. 

All i can think of for now is adding a cron to check messages with a `delivered_at` value that's _n_ minutes old, and set it to `null` so it can be consumed again, hoping that no memory error will happen again 😬 Any input on a better way to deal with this, or to add a proper failed stamp to the message, is welcome 👌

**Comment by tsadiq** [comment]
All hail `redeliver_timeout`, and thanks for your time 😬
