### ISSUE TITLE
dotenv putenv has unclear default value

### ISSUE THREAD

**Issue by j-mahlke** [symfony/symfony#49648]
### Symfony version(s) affected

6.2

### Description

I found this in code:
https://github.com/symfony/dotenv/blob/6.2/Dotenv.php#L61

comment says that the default value has to be false, and in the next line it is set to true.

I'm sure, code and comment should be the same, but I don't know which one is correct.

### How to reproduce

This is just strange code, nothing to reproduce

**Comment by alamirault** [comment]
I dig a bit and it confuse me also :sweat_smile:

Before 5.1, this comment was on construct with default value to false. 

https://github.com/symfony/symfony/blob/2c14c5fca7182f11abf0a692e471326f14119c29/src/Symfony/Component/Dotenv/Dotenv.php#L40-L44

But after, this comment is on method and default value is on property
https://github.com/symfony/symfony/blob/ac236517cc8925110d2ec9c35cfdb682a7b82f06/src/Symfony/Component/Dotenv/Dotenv.php#L41

Se default it always false, and you can enable it by calling `usePutenv`.

I created PR #49649 in order to improve sentence, hope it can help
