### ISSUE TITLE
Missing changelog for `symphony/yaml` 6.0.0

### ISSUE THREAD

**Issue by mhsdesign** [symfony/symfony#49890]
### Symfony version(s) affected

6.0.0

### Description

We currently want to loosen the constraint from `symphony/yaml` 5.1 to 6.0 and as this major release could contain by semver definition breaking changes we are interested in finding out what we need to adjust.

But for some reason the github release only says: "no significant changes"
https://github.com/symfony/yaml/releases/tag/v6.0.0 

and the change log doesnt mention 6.0.0 https://github.com/symfony/yaml/blob/6.2/CHANGELOG.md

or is there another place where we can find details about the release?
Thanks for your help!

### How to reproduce

-

**Comment by chalasr** [comment]
I hope you're talking about `symfony/yaml` rather than `symphony/yaml` as it'd mean you have been fooled through typo squatting. The UPGRADE instructions are located at the root directory of this repository: https://github.com/symfony/symfony/blob/6.0/UPGRADE-6.0.md#yaml.
It looks like an entry is missing in the 6.0 CHANGELOG you linked though. PR welcome to fix it on the 6.2 branch.

**Comment by chalasr** [comment]
Instructions about upgrading Symfony components are documented here also: https://symfony.com/doc/current/setup/upgrade_minor.html#2-updating-your-code-to-work-with-the-new-version

**Comment by mhsdesign** [comment]
Thank you ;)
