### ISSUE TITLE
Add support for NanoID in UID component

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#49899]
### Description

It would be great to see a proper NanoID implementation in PHP that is maintained by Symfony.

Would this be something that could be added to the UID component?

### Example

https://planetscale.com/blog/why-we-chose-nanoids-for-planetscales-api
https://github.com/ai/nanoid
https://zelark.github.io/nano-id-cc/
https://github.com/hidehalo/nanoid-php

**Comment by fancyweb** [comment]
Hello, thank you for your feature request.

At first glance, NanoIDs seem to be "pure random" UIDs that bring nothing more than UUIDs v4 or ULIDs. What's your use case? Are they popular in the PHP ecosystem? :thinking: 

It looks like they can have custom alphabets and custom sizes which would probably not be fully compatible with symfony/uid AbstractUid contract because, for example, I guess that from a certain size, we wouldn't be able to return an RFC 4122 representation of the NanoID.
Moreover, custom alphabets and custom sizes would prevent consumers from getting a "trusted typesafe" NanoID, for example, if one class expects a NanoID of "type" 1 and another one a NodeID of "type" 2, which kind of defeats the purpose of having safe and validated UIDs objects? At this point, couldn't it just be a string?

**Comment by derrabus** [comment]
> they can have custom alphabets

Note that this is a pure serialization issue. You could do very much the same with a UUID if you wanted to.

**Comment by ro0NL** [comment]
> What's your use case?

for me "much more user-friendly in a URL"

there's also something called "shortuuid", which solves the same issue

apart from technicalities, it sounds Uid component is a nice fit

**Comment by nicolas-grekas** [comment]
The length argument is moot to me. The existing `toBase58()` method already allows 22-chars UIDs.
