### ISSUE TITLE
Split intl packages in smaller packages

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#49943]
### Description

Right now Symfony Intl package is 43MB, which makes all Applications really big 
![image](https://user-images.githubusercontent.com/6224096/230072574-c2121225-ba4b-4447-bbf5-6b92cf4228b1.png)

The problems for me are:

- Packaging for Bref can be a problem as AWS has a limit of 250 MB (unzipped)
- Waste of Traffic and Disk Space

### Example

My ideas so far:

- Create separate packages for the actual data emoji, locales, timezones and optin people for each feature (symfony/intl-data-emoji)
- Or complete symfony/intl-emoji like split the repository on Intl level again

**Comment by stof** [comment]
Given that the emoji data is different from the other data (it is used through a different infrastructure), it might make sense to split it in a separate package to reduce this size.

**Comment by andresayac** [comment]
I like the idea

**Comment by nicolas-grekas** [comment]
In #49970, I'm proposing to compress the data. But would it make sense to let *you* do the compression when needed? See https://github.com/symfony/symfony/pull/49970#issuecomment-1513248039

**Comment by alexisLefebvre** [comment]
How do you imagine these packages?

How I see it: let's say that my website uses only English and French, so I do `composer require symfony/language-pack-en symfony/language-pack-fr` and I only have the necessary data for my project. And compression is not needed since these packages contain only a few files.

Would it require to much work and packages to maintain for Symfony?

---

Another idea: implement something like `localepurge` (see [Ubuntu](https://manpages.ubuntu.com/manpages/xenial/man8/localepurge.8.html), [Debian](https://packages.debian.org/stretch/admin/localepurge) or [ArchLinux](https://aur.archlinux.org/packages/localepurge)) to remove all the translations that are not required by your app. It could be run after `composer install` so that less space is used on a server or the Docker image, packaged app, etc.
