### ISSUE TITLE
symfony/console does not use my style for the entire application

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [symfony/symfony#49958]
### Symfony version(s) affected

6.2.8

### Description

I set<error> style to black on yellow(for example), but symfony/console does not use my style for the entire application.

### How to reproduce

```
require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Formatter\OutputFormatterStyle;
use App\Commands\HelloworldCommand;

$output = new ConsoleOutput();
$outputStyle = new OutputFormatterStyle('black', 'bright-yellow');
$output->getFormatter()->setStyle('error', $outputStyle);

$app = new Application();
$app->setName("йфяЙФЯёЁ üÜiİöÖğĞıIəƏçÇşŞ");
$app->setVersion("0.0.001");

$app->add(new HelloworldCommand());

$app->run(null, $output);
```
<img width="932" alt="ss_2023_04_06__14_53_35" src="https://user-images.githubusercontent.com/25248634/230358631-892f099e-b9b3-43dd-a4b3-18bcf61f52a1.png">

**Comment by ghost** [comment]
Try passing formatter as 3rd argument to ConsoleOutput constructor instead of modifying default one.

The source of problem described in issue is that exceptions are rendered using StreamOutput which uses default formatter if ConsoleOutput is instantiated without passing 3rd argument. 
https://github.com/symfony/symfony/blob/v6.2.6/src/Symfony/Component/Console/Application.php#L151
https://github.com/symfony/symfony/blob/v6.2.6/src/Symfony/Component/Console/Output/ConsoleOutput.php#L46

You can also call getFormatter, modify it, call setFormatter - this will set this formatter on StreamOutput then.

**Comment by aleksandr-shevchenko** [comment]
@javaDeveloperKid, yes, it work! Thanks!

**Comment by lyrixx** [comment]
I'm closing this issue since it has been solved
