### ISSUE TITLE
[Form] CollectionType: prototype_data option creates duplicates instead of new lines

### ISSUE THREAD

**Issue by jkgroupe** [symfony/symfony#49961]
### Symfony version(s) affected

6.2.8

### Description

I'm using CollectionType to embed a collection of forms and when I'm using `prototype_data` option and there is a bug when I add new lines in my form. It creates duplicates instead of create x new lines.

FYI, i'm using DTO's to populate my entities, idk if it changes something but it was working before the package upgrade.
I don't have the issue when I removed the `prototype_data` option but i need it to initialize data in new fields

### How to reproduce

**My parent form** 

```
$builder
    ->add('name', TextType::class)
    ->add('steps', CollectionType::class, [
        'entry_type' => StepForm::class,
        'allow_add' => true,
        'allow_delete' => true,
        'by_reference' => false,
        'prototype' => true,
        'prototype_name' => '__steps__',
        'prototype_data' => new StepData()
    ]);
```

**My child form** 

```
$builder
    ->add('name', TextType::class)
    ->add('probability', ChoiceType::class, [
        'choice_loader' => new CallbackChoiceLoader(function () {
            $probabilities = [];

            for ($i = 0; $i <= 10; $i++) {
                $value = $i * 10;
                $probabilities["{$value}%"] = $value;
            }

            return $probabilities;
        }),
    ])
    ->add('position', HiddenType::class, [
        'attr' => ['class' => 'position']
    ]);
```

**My form in front** _only the last 3 lines are added and new_
![Capture d’écran 2023-04-06 à 16 20 10](https://user-images.githubusercontent.com/4007104/230406547-170d0329-64dc-4ed2-8921-fa3002b1a181.png)

**After form submission** _you can see that the last 3 lines are the same with the same id (2112)_
![Capture d’écran 2023-04-06 à 16 20 31](https://user-images.githubusercontent.com/4007104/230407616-d622433a-8e79-4552-940e-6acd83a0f893.png)

 

### Possible Solution

I have downgraded the package `symfony/form` to the version `6.2.7` to solve this issue 

### Additional Context

I created a Symfony project to reproduce the bug. You can solve it to downgrade `symfony/form` package
https://github.com/jkgroupe/symfony-bug-form

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by jkgroupe** [comment]
I created a Symfony project to reproduce the bug. You can solve it to downgrade `symfony/form` package

Here is the link :
https://github.com/jkgroupe/symfony-bug-form

**Comment by stof** [comment]
The issue here is that the prototype data is an object that is not cloned for each of the added field (which was not an issue when using it only for the prototype, as there is a single prototype).

We should probably not use `prototype_data` there, or we must make sure it is not shared between entries (and forcing to clone it might not be good if the object is not designed for that).
Thus, I'm quite sure that this change breaks compat with cases configuring `empty_data` in the `entry_options`

**Comment by drekinov** [comment]
Yeah that change at some point. I got bug report couple days ago.
Fortunately i was able to refactor form and it is working fine now with empty_data.

Passing  "prototype_data => new SomeEntityCommand($user)" worked just fine to some version. (not sure if it is 6.2.8 or older)

**Comment by iquito** [comment]
I am having the same issue with my forms using CollectionType, all new elements share the same object and therefore all new elements have the data of the last new element, leading either to surprising validation errors or to overwritten/missing data. Downgrading to 6.2.7 (from 6.2.8 before) solved it for now.

**Comment by nicolas-grekas** [comment]
This was likely caused by #49835 /cc @Thorry84

Could anyone word on a fix?

**Comment by Thorry84** [comment]
Can confirm, my change caused this issue.

In an earlier commit I had the `ResizeFormListener` being passed an array_replace of `entry_options` and `prototype_options`. But then there was some discussion about this being done inside the `ResizeFormHandler` itself. I was against that since the merging of the arrays is the way the `CollectionType` does it, but that doesn't have to be the same as the `ResizeFormHandler`.

To simplify the code and prevent a duplication of logic I decided to use the prototype options variable already available.

In the past this issue would have only shown itself when the data option would be used in the entry_options, but that's not a common use case I think.

I think unintended the way `prototype_data` worked was more like `empty_data`, to provide a default value for new fields. But since the new fields didn't have this applied, it didn't matter.

I would suggest fixing this by using the array_replace when passing to the `ResizeFormListener` instead of the existing variable. I can provide a pull request if needed.

**Comment by Thorry84** [comment]
Provided a Pull Request with the fix.

I was unable to create a unit test that reproduced the original issue as it's a bit of a complex combination. If anybody has any ideas how to reproduce in a simple unit test, I'd be happy to add it.

**Comment by iquito** [comment]
I can confirm that #50056 fixes the issues I have experienced.

**Comment by jkgroupe** [comment]
I can confirm too. Thank you
