### ISSUE TITLE
[Messenger][Security] Async authentication

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#49968]
### Description

Inspired by https://stackoverflow.com/questions/64239973/best-way-to-use-voters-permissions-on-symfony-messenger-async-message-handler

The idea is to preserve the current logged in user while handling messages.

I tend to prefer opt-out, and thus by default preserve the current logged in user.

**Comment by kbond** [comment]
https://github.com/symfony/symfony/pull/48142 should help here.

**Comment by ro0NL** [comment]
In this case it's about the current user, as we'd like to leverage current infrastructure (e.g. blameable entities) when flushing async.

So stamp while sending, login while receiving. Unless an opt-out stamp was used, or maybe a dedicated system/anonymous message bus :thinking:

**Comment by kbond** [comment]
What about a more generalized `UserAwareInterface` and a `UserSwitcher` (like we did with `LocaleSwitcher`).

**Comment by kbond** [comment]
Can you use `Security::login()` in your handler (or middleware)? (You'd have to pass the firewall name manually)

Basically a simplified version of the stack overflow answer.

**Comment by ro0NL** [comment]
Maybe the better question is should the token be preserved yes/no when working async? Or why wouldnt we?

executing on behalf of the authenticated user by default, sounds generally safe to me

**Comment by kbond** [comment]
I agree I'd find this useful.

Separate feature but making the current request available would be nice too (request added to stamp and pushed to the request stack before consuming).

**Comment by wouterj** [comment]
For audit purposes, I would very much like us to not build something that causes actions from a background job to have the same authentication as a direct user action.

However, I like the idea of adding some sort of authentication support for messenger. This would need a bit of a higher level concept of "service accounts" that can act in name of a user (instead of directly as a user). That could allow us to use the user roles in the authorization process, but still have the service account as the "user" (security principal) of the action.

**Comment by ro0NL** [comment]
my usecase is 'blameable entities' for actions caused by the current authenticated user

to me a 'service account' sounds like any other security token
or put different; any token can be used as a 'service account'

given tokens are serializable, maybe this is just matter of adding a `Messenger/SecurityTokenStamp` :thinking: which manages the token storage state async

**Comment by ro0NL** [comment]
i'll experiment with such a middleware in userland first :+1: in our case it's the default behavior.

**Comment by SherinBloemendaal** [comment]
The token is serializable, but there’s an issue when using the Doctrine user provider: the entire user entity would be serialized + third-party libraries can store arbitrary data in their tokens, which could also lead to unexpected issues.
Currently the `AbstractToken` is serialized as-is: https://github.com/symfony/symfony/blob/0461860c7be76630cf583d09e947dcca6a50e324/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L79

I was thinking of calling the user provider for the `firewallName` stored inside the token but it seems there is currently no service definition to fetch the user provider for a specific firewall (which could be intended and could become a lot more complex then it looks I guess because custom authenticators could also simply load it without any user provider).

**Comment by kbond** [comment]
> the entire user entity would be serialized + third-party libraries can store arbitrary data in their tokens, which could also lead to unexpected issues.

I feel like it would be best to just send the username along (in a `UserStamp`).

**Comment by SherinBloemendaal** [comment]
Indeed. The only challenge I foresee is that when you're using a library like `thephpleague/oauth2-server-bundle`, the identifier alone isn’t enough—you also need details such as OAuth scopes and the client identifier to make it work properly.

Edit:
Another challenge would be the `SwitchUserToken` since you might want to preserve the original token as well.
