### ISSUE TITLE
[WebProfilerBundle] Profiler is not stateless

### ISSUE THREAD

**Issue by bigfoot90** [symfony/symfony#50037]
### Symfony version(s) affected

`5.4.21` `6.2.8`

### Description

I have a SPA and I'm importing all routes in stateless mode

I'm having the error `Session was used while the request was declared stateless` beacause Profier is not stateless

### How to reproduce

Edit Kernel.php to be stateless
```php
        $routes->import($confDir.'/{routes}/*'.self::CONFIG_EXTS, 'glob')->prefix('/api/')->stateless();
        $routes->import($confDir.'/{routes}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, 'glob')->prefix('/api/')->stateless();
        $routes->import($confDir.'/{routes}'.self::CONFIG_EXTS, 'glob')->prefix('/api/')->stateless();
```

**Comment by derrabus** [comment]
Please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug.

**Comment by bigfoot90** [comment]
> reproducer

https://github.com/bigfoot90/symfony-profiler-stateless

**Comment by bigfoot90** [comment]
**UPDATE** Sf6.2 is also affected.
I've created two branches to test both versions on my reproducer

**Comment by MatTheCat** [comment]
Indeed the profiler relies on the session to store search parameters so I don’t think this is a bug as you’re not supposed to say it’s stateless.

Maybe it _could_ be but I’m not sure it should be done.

**Comment by stof** [comment]
The profiler already makes the usage of the session optional for the search (if you disable the session subsystem entirely, it will simply not remember your previous search filters for the next time you try to use the search).
We could easily had a check on `$request->attributes->get('_stateteless')` in addition to `$request->hasSession()` before deciding to use the session, so that we avoid breaking the profiler entirely if you load the profiler routes as stateless

**Comment by MatTheCat** [comment]
@stof would `$request->hasSession(true)` do the trick?

**Comment by stof** [comment]
no. this is not about checking whether the session is initialized or no. The issue is about avoiding to use the session if the route was marked as being stateless.

**Comment by alamirault** [comment]
I dig a bit, and saw `_stateless` is not in attributes of `searchBarAction`.
I think is because it's rendered by twig `{{ render(controller('web_profiler.controller.profiler::searchBarAction', query=request.query.all)) }}` and `FragmentRenderer` don't populate `_stateless` based on configuration.

I don't know where is the best place for populate this, someone has an idea ?

**Comment by MatTheCat** [comment]
I originally thought this was `FragmentUriGenerator`’s job but I believe we only want to forward `_stateless` to inline rendered fragments so I opened #50198.

**Comment by bigfoot90** [comment]
Maybe we can localstorage instead of sessions to store filter parameters?
