### ISSUE TITLE
The Intl component is required to use the Bic constraint.

### ISSUE THREAD

**Issue by Aporie** [symfony/symfony#50051]
### Symfony version(s) affected

6.2

### Description

When trying to validate a swift bank number using the Bic validator, this throws the following error:

`Symfony\Component\Validator\Exception\LogicException: The Intl component is required to use the Bic constraint. Try running "composer require symfony/intl".`

### How to reproduce

Try to validate a bank swift code against the Bic constraint:

```
use Symfony\Component\Validator\Constraints\Iban;
use Symfony\Component\Validator\Constraints\Bic;
use Symfony\Component\Validator\Validation;

$validator = Validation::createValidator();
$violations = $validator->validate($swift_code, [new Bic()]);
```

### Possible Solution

I think symfony/intl should be put as required dependency. It's actually a dev requirement in symfony/validator/composer.json.

### Additional Context

On Drupal using "symfony/validator": "^6.2"

**Comment by stof** [comment]
No, it should not be put as a required dependency. It is an optional dependency because it is only needed for a few constraint, not for all of them (many projects don't try to use the `Bic` constraint at all when using the validator component).

And that's also why we provide an error explaining exactly what is needed instead of letting PHP fail with a `Class does not exist` error.
