### ISSUE TITLE
[Yaml] [Dumper] Dumper does not use block indentation indicator when multiline value begins with newline followed by spaces.

### ISSUE THREAD

**Issue by bradtreloar** [symfony/symfony#50065]
### Symfony version(s) affected

\>=3.4.5

### Description

`\Symfony\Component\Yaml\Dumper::dump` only checks for leading spaces when deciding whether to add a block indentation indicator. If the value begins with a newline followed by spaces then the indicator isn't added.

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Yaml/Dumper.php#L76

### How to reproduce

```php
// Create dumper with 2-space indentation.
$dumper = new \Symfony\Component\Yaml\Dumper(2);

// Prepare value beginning with newline followed by four spaces.
$data = ['key' => "\n    multiline value\nwith leading newline\nfollowed by spaces"];

// Dump the value to YAML.
$dumper->dump($data2, 1, 0, \Symfony\Component\Yaml\Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK);
```

Result:
```yaml
key: |-

      multiline value
  with leading newline
  followed by spaces
```

Expected result:
```yaml
key: |2-

      multiline value
  with leading newline
  followed by spaces
```

### Possible Solution

Remove leading newlines when determining the value of ` $blockIndentationIndicator`.

**Comment by n0rbyt3** [comment]
The expected result seems wrong to me: The ```-``` indicates the block is stripped.

https://yaml.org/spec/1.2.2/#8111-block-indentation-indicator says:
> In this case, the final line break **and any trailing empty lines are excluded** from the scalar’s content.

The bug seems to be the detection of the block chombing indicator: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Yaml/Dumper.php#L78

Here only the line ending is checked, but the ```+``` indicator should also be used if the string starts with spaces or new lines.
