### ISSUE TITLE
[RFC] Replace “Try running composer…” with “run composer…”?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony#50083]
### Description

In #50078 I saw that Symfony output messages like `Try running "composer require nyholm/psr7".`.

It looks like it's the standard way to suggest to add a dependency.: https://github.com/search?q=repo%3Asymfony%2Fsymfony+%22try+running%22&type=code

I don't understand why an error suggest to **try** to do something. Can it lead to conflicts with other packages? English is not my mother tongue, I interpret it as “try to install it with composer, good luck”, but it may be a misinterpretation.

What if Symfony says `Run "composer require nyholm/psr7".` instead of `Try running "composer require nyholm/psr7".`?

### Example

`You cannot use the "Symfony\Component\HttpClient\Psr18Client" as the "psr/http-factory" package is not installed. Run "composer require nyholm/psr7".`

**Comment by nicolas-grekas** [comment]
It's for two reasons to me:
1. being nice. for the same reason, we don't say "you must do this" but "you should" in all messages.
2. because there can be many reasons why an exception is thrown, and being too assertive could prevent ppl from following their own flow of thoughts to understand what's going on.

I personally prefer the way we do messages right now.

**Comment by wouterj** [comment]
I think the uncertainty in this error message is not about the tool used to install the component, but whether installing the component fixes the issue.

E.g. you can also have an older version of the library installed that doesn't have this class, or have some autoloader cache that needs to be invalided, etc.
