### ISSUE TITLE
EnumType is final, it should not be?

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony#50169]
### Description

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Form/Extension/Core/Type/EnumType.php#L23

This class is the only `final` FormType, so we can't extends it.

Can we remove the final keyword?

### Example

`class EnumType extends AbstractType {}`

**Comment by stof** [comment]
there is no reason to extend form type classes with PHP inheritance. This will generally only create issues.

Please use the proper extension points of the Form component (making your own type a child of the EnumType in the type hierarchy through the `getParent` method is probably what you need instead).

Btw, we don't open existing closed APIs just because someone ask us to do it (as that increases the maintenance cost). We always require an explanation of the use case (which allow us to explain what the alternative solutions are, which are often less costly to maintain than opening to inheritance and might even work better)

**Comment by steevanb** [comment]
In this case, why all FormType are not `final`? Why `EnumType` is the only one who is `final`?

And why `ButtonType` extends `BaseType`, and not `AbstractType`?

**Comment by ro0NL** [comment]
because BaseType and AbstractType are both, uhm, base types. Whereas ButtonType, EnumType, et al are not.

we should probably mark those form types meant to be extended by the means of getParent() `@final`

**Comment by steevanb** [comment]
I don't understand why `EnumType` is the only one `final`?

**Comment by ro0NL** [comment]
probably because EnumType is one of the last types added, and we havent discussed the matter till now :)

**Comment by wouterj** [comment]
I think it would be good to add `@final` to all types in 6.4.

**Comment by xabbuh** [comment]
closing here as extending a form class is not the way to extend form types as explain by @stof

PR welcome to add the `@final` annotation to most form type class though :)

**Comment by stof** [comment]
BaseType and AbstractType are not form types by themselves. They are PHP abstract classes meant to be used by type classes. The form component does not know about those 2 abstract classes in its type registry.

**Comment by steevanb** [comment]
@xabbuh how can i add `@final` to all FormType? I only add it, and SF 7 will have `@final` too, or should I add `@final` for SF6 and the keyword `final` for SF7?

**Comment by stof** [comment]
The core team will decide whether `@final` classes become actually final or stay as `@final` to allow mocking them (for form types, I would say that this is a case where they would actually be final as there is no reason to mock specific type classes)

**Comment by steevanb** [comment]
Ok, so i can't help you to do this?

And finally, with all this answers, i always don't understand why EnumType do not have the same behavior as other types. I understand @ro0NL answer, EnumType is the latest created, so it's final, but if i follow @stof it should not be for the mocks?

**Comment by stof** [comment]
There is no need to mock form types. So there is no reason to use `@final` instead of a final keyword for EnumType.

`@final` can be used for 2 cases:
- as `@final since ...` to indicate that the class will receive an actual final keyword in the next major version. This variant is never used on a *new* class (for new classes, there is no BC impact about making them final from the start)
- as `@final` to indicate that extending the class is not covered by our BC policy but we still wanted to allow mocks to extend it
