### ISSUE TITLE
Harmonize ISO code for Greece

### ISSUE THREAD

**Issue by Hakihiro** [symfony/symfony#50299]
### Description

Hi team, 
Sorry in advance for my English, and thanks in advance for your time :).

In the Intl component, Greece is referenced has `el`, so each of the files is call `el.php`.

But in some case, inside files we got Greece defined under `GR` and some other `EL`

For example, in the language one it's also referenced as `EL` => https://github.com/symfony/intl/blob/6.2/Resources/data/languages/en.php

But in the country one we got `GR`
https://github.com/symfony/intl/blob/6.2/Resources/data/regions/el.php

Since the case of Greece seems to be imperfect, base on the iso definition : 
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Codes_currently_agreed_not_to_use
> The [European Commission](https://en.wikipedia.org/wiki/European_Commission) generally uses ISO 3166-1 alpha-2 codes with two exceptions: EL (not GR) is used to represent [Greece](https://en.wikipedia.org/wiki/Greece), and UK (not GB) is used to represent the [United Kingdom](https://en.wikipedia.org/wiki/United_Kingdom).[[10]](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#cite_note-10)[[11]](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#cite_note-11) This notwithstanding, the Official Journal of the European Communities specified that GR and GB be used to represent Greece and United Kingdom respectively.[[12]](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#cite_note-12) For [VAT](https://en.wikipedia.org/wiki/Value_added_tax) administration purposes, the [European Commission](https://en.wikipedia.org/wiki/European_Commission) uses [EL and GB for Greece and the United Kingdom respectively.](https://en.wikipedia.org/wiki/VAT_identification_number#European_Union_VAT_identification_numbers)

I don't know if there is a specific reason using GR for country instead of EL. But if not, we could probably harmonize files to always use `EL` instead of GR, or maybe define both ?

**Comment by stof** [comment]
For languages, we don't use country codes by language codes. They are different things. See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes for the language codes. The code for Greek is `el`

And this data comes directly from the CLDR data of the ICU project.

**Comment by Hakihiro** [comment]
The problem is mainly on the country part, the code is different from every other places (GK instead of EL).
But seems to based on the ICU project as you said, so we are not free to adapt it here.

Thanks for you response.

**Comment by stof** [comment]
In the country code, the ICU project uses `GR`  (not `GK` as said in your comment) because this is the actual ISO 3166-1 code for Greece.

The fact the the European Commission decided to use `EL` does not change the ISO standard. In the ISO standard, the code for Greece is `GR` (and btw, their ccTLD is also `.gr`, not `.el`).

So to me, there is no problem with the current data.

If you are in a project that needs to work with codes following the European Commission country codes, you will indeed need to perform a conversion for cases where they differ from ISO. But changing things in symfony/intl would break all other cases, and would not respect the documentation of the `Countries` class saying it works with ISO 3166 codes.
