### ISSUE TITLE
[Security][CSRF] Token is incorrectly re-randomized even when it exists

### ISSUE THREAD

**Issue by pkly** [symfony/symfony#50360]
### Symfony version(s) affected

5.4.x

### Description

CsrfTokenManager, the default implementation of CrsfTokenManagerInterface generates incorrect CsrfToken values when using `getToken` with the same tokenId

It appears that the value of the token is the same, but result from randomize is not.

### How to reproduce

```php
// assuming manager is loaded into $csrf
$token = $csrf->getToken('id1');
dump($token);
$token = $csrf->getToken('id1');
dump($token);
$token = $csrf->getToken('id1');
dump($token);
```

While the ids match as expected the values do not even though the identifiers are the same

### Additional Context

![image](https://github.com/symfony/symfony/assets/17160364/4e2a4656-59b4-444e-9ef1-a485a05b9da6)

**Comment by mmouih** [comment]
Thank you for reporting this issue,

However, I don't think it's a bug,
https://github.com/symfony/symfony/blob/835543948d7305b1660a451ead41507cbbbf32dc/src/Symfony/Component/Security/Csrf/CsrfTokenManagerInterface.php#L26
The phpdoc of the **getToken** method of CsrfTokenManagerInterface mentions that the method returns the **same value** if the token exists, but not the `same instance`,
That's because the token is randomized every time before returning the token (even though it's value remains the same),

In the default implementation, `**randomize**` is called before returning the instance, **whether it was found or not**.
https://github.com/symfony/symfony/blob/835543948d7305b1660a451ead41507cbbbf32dc/src/Symfony/Component/Security/Csrf/CsrfTokenManager.php#L77,

I hope this answer helps,
Best regards.

**Comment by wouterj** [comment]
Indeed, the value is the same but the return string is randomized to better protect against [BREACH attacks](https://symfony.com/blog/new-in-symfony-5-3-better-protection-against-breach-attack). This behavior is expected and `CsrfTokenManagerInterface::isTokenValid()` is able to deal with these randomized strings.

**Comment by pkly** [comment]
I guess I must've missed it in BC breaks when upgrading from 4.4 then.

One thing I'm confused about then - how am I supposed to re-validate a crsf token in such a case? I'm using them for a state check by sending the token's value along and back, we previously simply compared the value from the manager against received state.

As the token returned from the manager has a different value the second time around, am I supposed to create my own CsrfToken instance with my known id and value and then simply put that into the isTokenValid method?

**Comment by wouterj** [comment]
Yes, you create a new token instance with the configured ID and the user value and pass it to the csrf manager:

```php
$csrfToken = new CsrfToken($this->tokenId, $request->request->get('csrf_token'));
if (!$this->tokenManager->isTokenValid($csrfToken)) {
    throw new \Exception();
}
```

**Comment by pkly** [comment]
Ah, I see. Thank you for the explanation and sorry to bother.
