### ISSUE TITLE
ArgumentResolver exception has incorrect wording

### ISSUE THREAD

**Issue by garak** [symfony/symfony#50375]
### Symfony version(s) affected

6.2.x and 6.3.x

### Description

The exception in [ArgumentResolver](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver.php#L106) reads like the following:

>Controller "%s" requires that you provide a value for the "$%s" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.

The "because" is clearly superfluous, and "non optional" should be written as "non-optional".

### How to reproduce

Not so relevant, since the error is inside the code.
Anyway, I stumbled upon this problem when I tried to use the new `#MapQueryParameter` feature in Symfony 6.3-beta3 (there was a bug, fixed in the current dev but still not released).

### Possible Solution

Replace with:

>Controller "%s" requires that you provide a value for the "$%s" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or there is a non-optional argument after this one.

**Comment by ghost** [comment]
I think you spent more time writing this issue that it would have taken to fix the wording and open a PR.

**Comment by wouterj** [comment]
Sounds good to me. Anyone up for a PR? (on 6.2)

> (there was a bug, fixed in the current dev but still not released)

Just for your information: pre-releases often only serve a purpose of marketing. As bugs are constantly fixed during this stabilisation phase, the dev branch is often more stable than the latest pre-release. As a result, we often recommend people to just use `6.3.x-dev` as a dependency :)

---

@javaDeveloperKid please comment in a respectful manner and add value to a discussion, see https://symfony.com/coc for more information. There are many valid reasons for someone to write an issue instead of create a PR directly.

**Comment by ghost** [comment]
@wouterj I know that but this issue was just too much for me :smile: 
I would even say that such issues should not be allowed because it costs everyone's time (the reporter to write it and the core team to read it and comment). The PR still needs to be opened and reviewed.

**Comment by garak** [comment]
> I think you spent more time writing this issue that it would have taken to fix the wording and open a PR.

It's not fair to open a PR without an issue. There's no time saving anyway, since the time spent on validation would be equally spent in the PR.
