### ISSUE TITLE
Dynamic form and new ->createview() functionnality returns 422 error

### ISSUE THREAD

**Issue by akyoscommunication** [symfony/symfony#50542]
### Symfony version(s) affected

6.2.10

### Description

Hi,

I just tried to update a 4.4 project to 6.2, I used Rector to automatically change syntax, and now all ajax requests of dynamic forms return 422 errors with no message. No error in form, no debug informations, just  "ERROR 422 Unprocessable Content". 

After few research I noticed that Rector had change all '$form->createView()' to just '$form' in $this->render calls, as specified in new doc (https://symfony.com/doc/current/forms.html). Changing back to '$form->createView()' removes the error. 

I don't really now if it's a real bug or if I'm wrong somewhere.

Thanks

### How to reproduce

Simple form with FormEvent : 

`$builder->addEventListener(
			FormEvents::PRE_SET_DATA,
			function (FormEvent $event) {
				$data = $event->getForm()->get('isMeal')->getData();
				$this->formModifier($event->getForm(), $data);
			}
		);`

`$builder->get('isMeal')->addEventListener(
			FormEvents::POST_SUBMIT,
			function (FormEvent $event) {
				$isMeal = $event->getData();
				$this->formModifier($event->getForm()->getParent(), $isMeal);
			}
		);`

`public function formModifier(FormInterface $form, $isMeal = null): void
	{
		if ($isMeal !== null) {
			if (!$isMeal) {
				$form->remove('meal');
			} else {
				$form
					->add('meal', MealType::class, [
						'label' => false,
			}
		}
	}`

And simple ajax call on change : 
`$.ajax({
                url : $form.attr('action'),
                type: $form.attr('method'),
                data : data,
                success: function(html) {...});`

Returns 422 error

### Possible Solution

Reset to : 
`return $this->render('platform/layouts/crud/new.html.twig', [
	'form' => $form->createView(),
]);`

**Comment by stof** [comment]
Well, `render()` will use a 422 status code in case the Form being rendered is submitted but invalid. This is not a bug at all but a feature. It actually follows the HTTP spec (returning a 200 status code is a lie if the POST request failed because of invalid submitted data). Returning the appropriate status code is mandatory to be compatible with tools like Turbo for instance (which the Symfony UX initiative pushed in the ecosystem).
If you don't want to perform this change in your own project, disable that rule in your Rector config (Symfony made this change opt-in as it required changing what you pass to the `render()` function)

**Comment by akyoscommunication** [comment]
Thanks for your response.

Ok for that, seems right. However, as the form is not really submitted yet (it's an ajax call for a dynamic field, not a real submit) the response is 422 because the form is incomplete, but then the AJAX request never completes cause it receives a 422 error instead of the new html with modified fields. How could we get a 200 response for the AJAX call ? (I can use $form->createView() but if it's deprecated one day I'll have the same problem)

In the doc (https://symfony.com/doc/current/form/dynamic_form_modification.html#dynamic-generation-for-submitted-forms) : 
`$.ajax({
    url : $form.attr('action'),
    type: $form.attr('method'),
    data : data,
    complete: function(html) {
      // Replace current position field ...
      $('#meetup_position').replaceWith(
        // ... with the returned one from the AJAX response.
        $(html.responseText).find('#meetup_position')
      );
      // Position field now displays the appropriate positions.
    }
  });` 

When we send 'data[$sport.attr('name')] = $sport.val();' in the POST request the form is invalid because it receive only 1 field value, and that's ok because we don't really wan't to submit, we only wan't the form to refresh with dynamic fields, but if the request returns an error the dynamic field doesn't work. Or maybe I'm wrong in the use of dynamic form..

**Comment by stof** [comment]
when using `jQuery.ajax`, I don't remember how to access the response for 4xx status code. I've been using `fetch()` since years, and `fetch` does not convert such status codes to exceptions automatically.

> When we send 'data[$sport.attr('name')] = $sport.val();' in the POST request the form is invalid because it receive only 1 field value, and that's ok because we don't really wan't to submit, we only wan't the form to refresh with dynamic fields, but if the request returns an error the dynamic field doesn't work. Or maybe I'm wrong in the use of dynamic form..

this looks like a special use case. For that case, maybe you should indeed not return a 422 status code. Either keep passing a FormView to `render()` to opt-out of the Symfony feature, or override the response status code before returning the response in your controller to set it back to 200.

**Comment by wouterj** [comment]
I think we can close here, given this is precisely the expected behavior when changing from `$this->render(..., ['form' => $form->createView()]);` to `$this->render(..., ['form' => $form])`.

If you need more help with getting your specific scenario working, please continue in one of the [support channels](https://symfony.com/support) (e.g. GitHub discussion).
