### ISSUE TITLE
Symfony\Component\Mime\Address breaks The Open Closed Principle

### ISSUE THREAD

**Issue by nathandaly** [symfony/symfony#50688]
### Symfony version(s) affected

5.4.24

### Description

You should be able to extend the address class and any other similar classes due to the Open–closed principle: 

> In object-oriented programming, the open–closed principle states "software entities should be open for extension, but closed for modification.

### How to reproduce

```php
use Symfony\Component\Mime\Address as SymfonyAddress;

class Address extends SymfonyAddress
{
}
```

You cannot extend `Symfony\Component\Mime\Address` due to it being a `final` class.

### Possible Solution

Remove the `final` keyword from `Symfony\Component\Mime\Address as SymfonyAddress`.

### Additional Context

[Image Context](https://i.imgur.com/cu4FFYE.jpg)

**Comment by derrabus** [comment]
Thank you for opening this issue. Instead of giving us lectures on software engineering principles, please state your use-case for extending that particular class.

**Comment by javiereguiluz** [comment]
I didn't understand this as "lecturing". Some people (I guess, many in the Symfony community) already know this, but giving some context to issues and PRs is always great to make them accessible to everybody.

In any case, Alexander is right to ask about your use case: if your need is common enough, we might add it to `Address` instead of removing the `final` declaration. Please note that we declare all classes as `final` by default but we're open to change that in some specific cases if there's a strong reasoning behind the change.

Thanks!

**Comment by wouterj** [comment]
The open/close principle and final keyword do not contradict. A class can be open for extension without being open for inheritance (in [his paper on this principle](https://web.archive.org/web/20150415215806/http://www.objectmentor.com/resources/articles/ocp.pdf), Robert C. Martin doesn't mention or show inheritance a single time). We favor keeping classes final, as this gives us some breathing room to add features or refactor it within the rules of our [BC promise](https://symfony/bc).

While software theory is great, it is not a good argument when maintaining a framework like Symfony, as costs (cost of maintenance, cost of change, etc. for both community and us maintainers) is very important (afterall, we are all volunteers so the costs must be kept to a minimum).

Without practical use-cases, we cannot estimate whether this is worth the extra cost. And I also think that we might want to add other extension points in the class based on the use-cases, instead of making it open for inheritance.

---

Finally, I think this issue is started based on https://twitter.com/freekmurze/status/1669321224080556032 . Two important tweets in that thread from Freek are:

> I think there is zero chance that they’ll remove that final keyword. And of course, that’s fine!



> > May I ask what you wanted to do?
>
> Just add a couple of convenience methods

Unless you see other use-cases in your applications when using the `Address` class, I'm -1 based on these arguments (as Freek himself is also -1).

**Comment by ro0NL** [comment]
probably related to #50592

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
