### ISSUE TITLE
Doctrine like Inflector enhacment.

### ISSUE THREAD

**Issue by cs-akash-jarad** [symfony/symfony#50805]
### Description

Function to extend the EnglishInflector like Doctrine.
https://www.doctrine-project.org/projects/doctrine-inflector/en/2.0/index.html#custom-setup

Issue with Symfony/Component/String/EnglishInflector . Since we are using the following words in our project, the latest release is breaking the changes.
singular('Congress') -> "Congress" | Actual result is "Congres"
singular('Status') -> "Status" | Actual result is "Statu"

**Comment by evertharmeling** [comment]
See related PR, where I fixed it for the word `status`. However it looks like `congress` is already handled correctly in the `symfony/string` component. And it looks like you should submit an issue in the [`doctrine/inflector`](https://github.com/doctrine/inflector) library.

Otherwise please submit a code example / reproducer.

**Comment by cs-akash-jarad** [comment]
thanks for the PR @evertharmeling .
