### ISSUE TITLE
MapQueryString & MapRequestPayload empty when type missmatch

### ISSUE THREAD

**Issue by Grafikart** [symfony/symfony#50904]
### Symfony version(s) affected

6.3.1

### Description

When there is a type missmatch on an objet with the attribute `MapQueryString` or `MapRequestPayload` an empty instance is created.

For instance if I use `MapQueryString` expecting a name (string) and age (int) but the user send a "John" and "foo", I end up with an empty object.

### How to reproduce

1. Create a simple DTO (I deliberately omitted NotBlank)

```php
final readonly class PayloadDTO
{

    public function __construct(
        #[Assert\Length(min: 3)]
        public string $name,

        #[Assert\Positive]
        public int    $age
    )
    {
    }

}
``` 

2. Map this DTO in a controller

```php
class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(
        #[MapQueryString] PayloadDTO $payload,
    ): Response
    {
        dd($payload); // I expect the dto to be valid (with an age / name property)
    }

}
```

3. Try to access the page using an "age" that is not a number. `http://localhost:8000/?name=John&age=foo`, you'll end up with an empty `PayloadDTO` (which will cause bugs further down the application).

### Possible Solution

I tracked down the issue to the `AbstractNormalizer` that ends up instantiating the object without using the constructor (using the reflectionClass)  since there is a `not_normalizable_value_exceptions` in the context. https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L424-L428

A solution would be to check the context for "collect_denormalization_errors" before skipping the exception or to collect the exception when it happens.

```php
            try {
                return $reflectionClass->newInstanceArgs($params);
            } catch (\TypeError $e) {
                if (!isset($context['not_normalizable_value_exceptions'])) {
                    throw $e;
                }

                $context['not_normalizable_value_exceptions'][] = NotNormalizableValueException::createForUnexpectedDataType(/* Find which parameters to give */);

                return $reflectionClass->newInstanceWithoutConstructor();
            }
```

**Comment by BafS** [comment]
Same issue for us. I asked the question on slack without success.

The workaround I did is to not use the constructor:

```php
final class PayloadDTO
{
    #[Assert\Length(min: 3)]
    public ?string $name = null;

    #[Assert\Positive]
    public ?int $age = null;
}
```

Like that you can never have an empty object.

**Comment by lukasojd** [comment]
+1

**Comment by saxap** [comment]
same issue

**Comment by rlandgrebe** [comment]
I have the same issue when using the `MapRequestPayload` annotation. The problem seems to happen in this check:
https://github.com/symfony/symfony/blob/0b788970ad2f087fa0e24b39204e98029666bec0/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L593-L597
where `$context[self::DISABLE_TYPE_ENFORCEMENT]` evaluates to `true` and therefore the data is returned. If this would have evaluated to `false` a `NotNormalizableValueException` would have been thrown.

Checking where this context variable is set to `true` I found the context settings where type enforcement is disabled:
https://github.com/symfony/symfony/blob/0b788970ad2f087fa0e24b39204e98029666bec0/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L46-L49

The fix would therefore be easy, but I'm not sure if this is the intended behaviour because enabling type enforcement would also mean that an integer given as a string (e.g. `"123"`) is not automatically converted to an `int`. It's a question of strictness.

**Comment by rlandgrebe** [comment]
New findings from my side: This only happens when the following code is executed: https://github.com/symfony/symfony/blob/0b788970ad2f087fa0e24b39204e98029666bec0/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L177-L179

Otherwise https://github.com/symfony/symfony/blob/0b788970ad2f087fa0e24b39204e98029666bec0/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L190 is called and everything runs fine.

So I found another component in our code that automatically converted the request data to an array. In this case, only denormalization takes place and an empty instance is created. The conversion snippet is this one here: https://medium.com/@peter.lafferty/converting-a-json-post-in-symfony-13a24c98fc0e

**Comment by jurchiks** [comment]
I have just now stumbled upon a very similar, if not the same bug. I was trying to implement generic interfaces for some of my requests:
```
interface GetListRequest
{
    public function getFilters(): ?ListFilters;
    // I have more getters, pruned for brevity.
}

interface ListFilters {}

readonly class SpecificListFilters
{
  public function __construct(
    // any fields, doesn't matter for this example
    public ?string $foo = null
  ) {
  }
}

readonly class GetSpecificListRequest implements GetListRequest
{
    public function __construct(
        #[Assert\Valid]
        public ?SpecificListFilters $filters,
    ) {
    }

    public function getFilters(): ?ListFilters <- GetSpecificListRequest is empty
    public function getFilters(): ?SpecificListFilters <- GetSpecificListRequest is populated
    {
        return $this->filters;
    }
}

public function index(#[MapQueryString] GetSpecificListRequest $request) ...
```

This makes it annoying to use generic interfaces for these mapped DTOs, I cannot DRY my DTOs by using a generic trait for the getters:
```
trait GetListRequestImpl
{
    public function getFilters(): ?ListFilters
    {
        return $this->filters;
    }
}
```
Which forces me to copy-paste the same identical getters into every DTO and change the return types from interface to implementation, even though interface absolutely should work.

**Comment by Wolg** [comment]
Same issue here! Any chance [this PR](https://github.com/symfony/symfony/pull/51003) can be prioritized for the next release? Otherwise `MapQueryString`/`MapRequestPayload` are not very usable.
When validating promoted property and passing the wrong type serializer ends up with an empty DTO. For the same scenario, but when the property is defined with traditional syntax, the type context misbehaves and results in `This value should be of type unknown`.

**Comment by KevsRepos** [comment]
I have the same issue but its "fixed" when I remove the `readonly` flag from all properties. Symfony then responds with `422` but somehow cant resolve the type anymore, as the error message is "This value should be of type unknown.".

**Comment by rlandgrebe** [comment]
I'm again debugging this problem and decided to go a little bit deeper. It's seems to be a combination of two factors:

First: Disabling the type enforcement in the RequestPayloadValueResolver:
https://github.com/symfony/symfony/blob/ad68f738d00388d2a8c691b92d43704fa4fcec91/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php#L53

This is normally good behavior, because if you have a "123" (string) this will be automatically converted to 123 (int). This is useful for query strings where each parameter is given as a string.

Second: Insufficient validation of data in the AbstractObjectNormalizer:
https://github.com/symfony/symfony/blob/ad68f738d00388d2a8c691b92d43704fa4fcec91/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L625

This method validates and denormalizes the data, but if I try to map a string "hello" to an integer type, no check in this method will catch the error. In the end it will reach this part:
https://github.com/symfony/symfony/blob/ad68f738d00388d2a8c691b92d43704fa4fcec91/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L610-L612

And that is the main problem, because `RequestPayloadValueResolver` disables type enforcement. This is good and needed. But in my opinion it has no sense to disable type enforcement completely, because there's no way to convert "hello" to an integer. I think the best way is to check if the type is coercible, e.g. "123" (string) -> 123 (integer) is okay, but "hello" is not okay to convert to an integer. Therefore it has to throw a `NotNormalizableValueException`, even if type enforcement is disabled. Type enforcement, though, is still useful for being strict about those "123" -> 123 coercions.

Funny thing is that types are checked this way for the XML and CSV format, e.g.:
https://github.com/symfony/symfony/blob/ad68f738d00388d2a8c691b92d43704fa4fcec91/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L683-L689

**Comment by dwgebler** [comment]
You can write `#[MapRequestPayload(serializationContext: ['disable_type_enforcement' => false])]` to override the context for denormalization. I had this issue because I have an early request listener which automatically overwrites `$request->request` with decoded JSON payload for JSON requests.

**Comment by ovidiuenache** [comment]
This has been reported again in #59104. There's a PR attached to it with the fix and a more detailed description of the issue. The fix will make it work as expected without changing your DTOs or providing a custom context to the attribute.
