### ISSUE TITLE
[Frontend] AssetMapper: Allow disabling the ES Module Shim

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony#50912]
### Description

Right now, `{{ importmap() }}` is adding this automatically:
```html
<!-- ES Module Shims: Import maps polyfill for modules browsers without import maps support -->
<script async src="https://ga.jspm.io/npm:es-module-shims@1.7.2/dist/es-module-shims.js"></script>
```
I think there should be a way to disable loading this file.

### Example

[ImportMapRenderer](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/AssetMapper/ImportMap/ImportMapRenderer.php#L27) has a constructor argument to disable this; I just couldn't find a way to set this from [`importmap()`](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bridge/Twig/Extension/ImportMapRuntime.php#L25).

In the end, it could look something like:
```twig
{{ importmap({shim: true}) }}
```
I even suggest to *exclude* it by default for two reasons:
* Loading any external resources needs to be a *conscious decision* of the developer (security, privacy, etc.). In Germany, there's some fuss about webmasters getting sued for including Google Fonts like this!
* Over time, the shim will become less important

**Comment by stof** [comment]
The `asset_mapper` configuration of FrameworkBundle has a setting to configure that constructor argument: https://github.com/symfony/symfony/blob/6c85287f18120b6a00014eec806a6427bbb6e080/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L889

You cannot configure this from the call to `importmap` because this call has no way to alter the constructor arguments (it can only call the method)

**Comment by ThomasLandauer** [comment]
Thanks, please take a look at https://github.com/symfony/symfony-docs/pull/18537 if I got the syntax right...

**Comment by weaverryan** [comment]
Closing this in favor of the docs PR - thanks Thomas!
