### ISSUE TITLE
Update from symfony/finder v5.4.21 to v5.4.26 removes symlinks

### ISSUE THREAD

**Issue by AlexanderWillner** [symfony/symfony#51162]
### Symfony version(s) affected

5.4.26

### Description

Update from symfony/finder v5.4.21 to v5.4.26 there are no symlinks anymore in the folder `public/bundles` (Symfony application [Contao 4.13](https://github.com/contao/contao))``

### How to reproduce

% composer create-project contao/managed-edition example 4.13
% ls -l public/bundles | wc -l
1
% composer r symfony/finder:5.4.21 && { ls -l public/bundles | wc -l }
7
% composer r symfony/finder:5.4.26 && { ls -l public/bundles | wc -l }
1

### Possible Solution

Downgrade again

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by AlexanderWillner** [comment]
I admit that „composer create-project contao/managed-edition example 4.13“ isn’t a small sample application, but reproduces the issue with a single command. Does this work for you?

**Comment by derrabus** [comment]
I guess, most of the people on this issue tracker have no clue how Contao works, so a smaller reproducer would indeed help.

**Comment by kartoffelheinz** [comment]
I did a `php web/contao-manager.phar.php composer require contao/manager-bundle=4.13.28 contao/news-bundle=4.13.28 contao/calendar-bundle=4.13.28 contao/faq-bundle=4.13.28 contao/comments-bundle=4.13.28 contao/newsletter-bundle=4.13.28 contao/listing-bundle=4.13.28 symfony/finder:5.4.21 --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction`
followed by
`php web/contao-manager.phar.php composer install --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader`

**Comment by ausi** [comment]
I was able to reduce the issue to the following line:

```
Finder::create()->depth(0)->directories()->exclude(['dir1', 'dir2'])->in(__DIR__);
```

If `dir1` and `dir2` are symlinks the exclude does not work with the current version 6.3.2 but it still worked in the previous version 6.3.0.

This causes the cleanup in `assets:install` to remove all symlinks that were created just before: https://github.com/symfony/symfony/blob/f6647062e561951a1a8bf1a4bb126021c477ff8e/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php#L167-L171

**Comment by ausi** [comment]
Reverting #50885 seems to fix the issue.

**Comment by eisberg** [comment]
Yes, after upgrading  symfony/finder (v6.3.0 => v6.3.2) assets symlink installation does not work 
bin/console a:i --symlink  > empty folder

**Comment by derrabus** [comment]
> Reverting #50885 seems to fix the issue.

cc @mvorisek

**Comment by mvorisek** [comment]
see https://github.com/symfony/symfony/pull/50885 changes and description

especially with https://github.com/php/php-src/pull/11577 the performance improvement is huge, thus please provide a small steps/code to reproduce

maybe you (or Symfony Finder) needs (or does not need) `\FilesystemIterator::FOLLOW_SYMLINKS`?

---

looking into https://github.com/symfony/symfony/issues/51162#issuecomment-1657221965 repro - this is expected as symlinks are not followed by default, you need to call https://github.com/symfony/symfony/blob/v6.3.2/src/Symfony/Component/Finder/Finder.php#L599 in order to follow symlinks

as long as the `Finder::exclude()` is not documented to always follow symlinks for some reason, the current behaviour is right

**Comment by ausi** [comment]
I’m not very familiar with the `Finder` API, but I find it confusing that `->directories()` seems to follow the symlinks by default while `->exclude()` does not.

But I can confirm that changing https://github.com/symfony/symfony/blob/f6647062e561951a1a8bf1a4bb126021c477ff8e/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php#L169 to:
```php
$dirsToRemove = Finder::create()->depth(0)->directories()->exclude($validAssetDirs)->in($bundlesDir)->followLinks(); 
```
fixes the issue.

**Comment by mvorisek** [comment]
Good point. This topic is interesting, because `is_file` (and `isFile` SPL equivalent) does not follow symlink, based on the docs, it is true only if the given path is a "regular file". However, `is_dir` does returns true even if the path is a link.

[1] https://www.php.net/manual/en/function.is-file.php
[2] https://www.php.net/manual/en/function.is-dir.php

Am I right, without `->followLinks()`, that `->files()` behave the same, ie. list no files from symlinks but `->directories()` does list (empty) directories from symlinks?

If `->directories()` should always follow symlinks, the #50885 should be reverted and tests for symlinked files/dirs should be added.

**Comment by derrabus** [comment]
> the performance improvement is huge

We usually don't merge pure performance improvements to LTS branches because we want to keep them stable.

I propose to revert #50885, see #51178. If there's really performance to improve here, let's reevaluate on the 6.4 branch.

**Comment by derrabus** [comment]
Thank you for your report, @AlexanderWillner. And @ausi, thank you for your quick analysis.

@mvorisek if you're up to, please re-submit your PR for 6.4 if there's a way to implement it without introducing that regression again. Tests for the 5.4 branch are also welcome.

**Comment by wouterj** [comment]
Fyi, we just made a new release ([5.4.27](https://github.com/symfony/symfony/releases/tag/v5.4.27)) to fix this issue.

Thanks everyone for the quick report, analysis and fix.

**Comment by dbu** [comment]
ah, thanks. just ran into this, found that it affects the `assets:install` command (we worked around it by using the `--no-cleanup` flag.
