### ISSUE TITLE
[Messenger] keep stamps on `RedispatchMessage`

### ISSUE THREAD

**Issue by kbond** [symfony/symfony#51205]
### Description

When adding #51092, I made the false assumption that existing stamps were kept when using `RedispatchMessage`. They are not. I'm thinking they should be.

I'm unsure how to keep the stamps within the current architecture. Any ideas?

### Example

```php
$bus->dispatch(new RedispatchMessage(new MyMessage()), [new ThisStampIsLost()]);
```

**Comment by valtzu** [comment]
I think your example is not right, the [2nd argument of `RedispatchMessage` is `array $transportNames`](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Messenger/Message/RedispatchMessage.php#L18-L26)

So did you try with passing the whole envelope as the 1st constructor argument?

```php
$bus->dispatch(
  new RedispatchMessage(
    Envelope::wrap(new MyMessage(), [new SomeStamp()]),
    ["some_transport_name"],
  ),
);
```

Note the difference vs.

```php
$bus->dispatch(
  new RedispatchMessage(
    new MyMessage(),
    ["some_transport_name"],
  ),
  [new SomeStamp()],
);
```

I assume it is by design as you may want different stamp on the initial dispatch vs. on re-dispatch – as those can be on different transports etc.

---

If the stamps still get lost, I think it may be related to the serializer not serializing them. At least the [`PhpSerializer`](https://github.com/symfony/symfony/blob/4f806062d50604b0cb340eb6a9daa1ec67a91244/src/Symfony/Component/Messenger/Transport/Serialization/PhpSerializer.php#L59) (which is the default) should keep all but `NonSendableStamp`s

**Comment by kbond** [comment]
> I think your example is not right

You're right, I've updated my example above.

> So did you try with passing the whole envelope as the 1st constructor argument?

Yes, and that does work as expected. My issue is with messenger events adding stamps (I should have made that clear). These stamps are lost because when the `RedispatchMessageHandler` re-dispatches the message, it doesn't have access to these stamps.

> I assume it is by design as you may want different stamp on the initial dispatch vs. on re-dispatch – as those can be on different transports etc.

That may end up being the conclusion of this issue.

---

For some context, I'm working on a messenger monitor system that tracks messages through their lifecycle. The specific issue, is with tracking scheduled messages that use `RedispatchMessage`. I lose the visibility on what schedule it was part of (because the `ScheduleStamp` that contains this data is lost).

**Comment by kbond** [comment]
One idea, that specifically solves my issue, in `SchedulerTransport::get()`: check if message is an instance of `RedispatchMessage`, and re-create it with an envelope that contains the `ScheduledStamp`.
