### ISSUE TITLE
ObjectNormalizer::hasCacheableSupportsMethod()" method is deprecated, use "getSupportedTypes()" instead.

### ISSUE THREAD

**Issue by oojacoboo** [symfony/symfony#51277]
### Symfony version(s) affected

6.3

### Description

>Since symfony/serializer 6.3: The "Symfony\Component\Serializer\Normalizer\ObjectNormalizer::hasCacheableSupportsMethod()" method is deprecated, use "getSupportedTypes()" instead.

Userland code doesn't call this method.  Symfony is calling it internally, then reporting it as deprecated.  So, it's a non-resolvable error.  I get that it's deprecated.  But encouraging the disabling of deprecation notices isn't a good practice.  Am I missing something here?  I don't get why it would be put in this state.

```
Exception trace:
 trigger_error() at /srv/www/vendor/symfony/deprecation-contracts/function.php:25
 trigger_deprecation() at /srv/www/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php:63
 Symfony\Component\Serializer\Normalizer\ObjectNormalizer->hasCacheableSupportsMethod() at /srv/www/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php:55
 Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getSupportedTypes() at /srv/www/vendor/symfony/serializer/Serializer.php:290
 Symfony\Component\Serializer\Serializer->getNormalizer() at /srv/www/vendor/symfony/serializer/Serializer.php:158
 Symfony\Component\Serializer\Serializer->normalize() at /srv/www/vendor/symfony/serializer/Serializer.php:138
```

### How to reproduce

`Symfony\Component\Serializer\Serializer->serialize()`

**Comment by wouterj** [comment]
This looks like an oversight indeed, we must not trigger the deprecation when calling the method from inside `ObjectNormalizer`.

**Comment by nicolas-grekas** [comment]
The deprecation in ObjectNormalizer is called under this condition:
`__CLASS__ === static::class || $this->hasCacheableSupportsMethod()`

Which means the deprecated method is not called unless the class is extended by inheritance. Is that your case? The class is `@final` so this shouldn't happen. This means the deprecation might be legit to me. At least we need more info, the partial strack trace is not enough to decide.

**Comment by wouterj** [comment]
@nicolas-grekas the class is `@final since 6.3`. Per our BC promise, this means it is considered as final only as of 7.0.

This is reflected by the code itself as well: if the class was considered final, there was no need to call `$this->hasCacheableSupportsMethod()` as the implementation is equal to the condition before the OR (actually, it would even be enough to say `true` given `__CLASS__ === static::class` is always true for final classes). Even more, this is precisely what we do in normalizers that are already final in 6.3 (e.g. the `UidNormalizer`).

So my reasoning is that we implemented the BC layer here for good reasons, but forgot to silence the deprecation.

**Comment by nicolas-grekas** [comment]
But the deprecation is correct: the child class of ObjectNormalizer should implement getSupportedTypes(), isn't it?

**Comment by nicolas-grekas** [comment]
See #51288
