### ISSUE TITLE
Function to check if the kernel is loaded via the console or a web request.

### ISSUE THREAD

**Issue by y4roc** [symfony/symfony#51340]
### Description

I had the problem that I had to check in a service if the function is called via CLI or web.

Depending on that, I had to make different calculations. That's where my idea comes from, that you could put a function `isCLI()` or `isWeb()` into the kernel.

### Example

```php
class MyService {
  public function __constructor(
    private readonly KernelInterface $kernel
  ){}
  
  public function myFunction(): void {
    if(!$this->kernel->isCLI())
    {
      return;
    }
    // Do things in CLI without Request()
  }
}

**Comment by derrabus** [comment]
I don't think that the kernel should be injected into anything unless you want to perform subrequests. While I understand your motivation, I disagree with the proposed implementation.

**Comment by nicolas-grekas** [comment]
I also thought this could be useful. I think the can be done with an envvar (`APP_RUNTIME_MODE`?) that we define as `\in_array(\PHP_SAPI, ['cli', 'phpdbg'], true) ? 'cli' : 'web'` by default. Long running servers could advertise themselves as 'web' by setting this envvar. The env var might be defined by symfony/runtime so that all runtimes could leverage the concept.

**Comment by BaptisteContreras** [comment]
I tried to implement @nicolas-grekas idea.
