### ISSUE TITLE
[Validator] Invalid All constraint tests succeed

### ISSUE THREAD

**Issue by adrianrudnik** [symfony/symfony#51416]
### Symfony version(s) affected

6.4

### Description

While building a custom constraint similar to `All` (based on a `Composite`) for a custom DBAL type I never get the validator to actually fail in tests. I tried to get some feedback in the [discussions](https://github.com/symfony/symfony/discussions/51383), but it just looks like an issue.

Not sure if test-only PRs would be OK if they do not solve the issue, so I just did this issue.

Looking through the `AllValidatorTest` it seems that not a single `->assertNoViolation()` of this test can be trusted or procudes what I would expect, it just asserts that everything is fine, which is somehow always `true`.

There are also no additional bad-path tests for this validator. Is this expected, or am I missing something?

### How to reproduce

I've added an enhanced test in a [branch](https://github.com/adrianrudnik/symfony/tree/all-constraint-tests), with a single [commit](https://github.com/symfony/symfony/compare/6.4...adrianrudnik:symfony:all-constraint-tests) testing a `Range` constraint violation.

Tests run with

```shell
php ./phpunit src/Symfony/Component/Validator/Tests/Constraints/AllValidatorTest.php --testdox
```

### Possible Solution

Looking at the other `Composite` based validator test `AtLeastOneOfValidatorTest` there is a stark contrast in both tests and how thorough they are. I'm sadly not very proficient with `ConstraintValidatorTestCase` to fully grasp the other test to derive a better test for the `All` constraint.

Also I'm not sure if the usage without array notation for the constraints like in `testNullIsValid` and `testThrowsExceptionIfNotTraversable` is actually good practice.

**Comment by krciga22** [comment]
Hi @adrianrudnik, I've taken a look into this and it looks like these tests do indeed pass if you modify getValidArguments() to return invalid arguments. After looking into this further, I believe this is probably by design. 

The validator used by `ConstraintValidatorTestCase` has been heavily mocked, so the `validator->validate()` method calls `doValidate()` instead of doing what it normally does. The `doValidate()` method, in this specific case, always finds no violations because `expectValidateValueAt()` does not setup any violations.

I believe the intention of the `testWalkSingleConstraint` and `testWalkMultipleConstraints` tests are just to assert that for each value given, a validation result exists at the correct path in the validator's context. The actual validation result (true/false) may not matter since they are derived from other constraint classes (`new Range()` and `new NotNull()` which are not under test in `AllValidatorTest`.

**Comment by adrianrudnik** [comment]
Ok sounds sane, I'll just close this issue, thanks for looking through it!
