### ISSUE TITLE
[HttpKernel] HttpCache does not pass real request type to the kernel when no cache found

### ISSUE THREAD

**Issue by shyim** [symfony/symfony#51648]
### Symfony version(s) affected

6.3.4

### Description

I would like to cache ESI includes, that works already pretty well. Now I wanted to improve the performance by not doing some stuff on SubRequests. But the HttpCache does not pass the request type to the HttpKernel.

### How to reproduce

Wrap the HttpKernel with a HttpCache. Call the handle with a sub request, check that the HttpKernel get a sub request

### Possible Solution

As adding a new parameter to `fetch` and so in HttpCache would be a breaking change. Would maybe make sense to add it as an attribute to the request and get it back until we can break the API of that interface.

### Additional Context

It's hard-code to main request 😢 
https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L473

**Comment by stof** [comment]
This is expected. HttpCache is meant to behave as a pure PHP implementation of a reverse proxy when you cannot deploy Varnish (which has much better performance).
And if you use Varnish, requests sent from Varnish to the backend will be main requests in Symfony. That's why HttpCache also sends main requests so that the app behaves the same.
Also note that those various request will be sequential. They won't be performed during the handling of the "main" request for the page (which might not even be sent to the app kernel in case it is cached)

**Comment by shyim** [comment]
I know that Varnish calls would be always `main` requests. I would still like to "optimize" the requests done in the same PHP process and detect that this request is just an "esi" call and not a main request.

I will build me something of my own

**Comment by stof** [comment]
Well, a Symfony sub request will always happen during the handling of a main request. That's how we can skip some stuff based on the type of request because we have already done it.
For an ESI request, this assumption is not true anymore. Most optimization doable for subrequests are not doable for ESI requests. An ESI request could totally be the only request handled by your app in this process.
