### ISSUE TITLE
[Routing] Symfony falsely decodes the semicolon character in query strings

### ISSUE THREAD

**Issue by andreaskienast** [symfony/symfony#51708]
### Symfony version(s) affected

6.2.8, 6.3.3

### Description

The `UrlGenerator` builds a URL with encoded query string arguments, but decoded a subset of characters again. While this might be fine in most cases, it causes issues with the semicolon character with traefik (https://github.com/traefik/traefik/issues/9164). When the character stays encoded, everything is fine in our case. Also, the statement "reserved chars that have no special meaning for HTTP URIs" (https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L35) is wrong, as semicolons are sub-delimiters as per [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt):

```
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
            / "*" / "+" / "," / ";" / "="
```

### How to reproduce

That's a bit tricky. You need a recent ddev version which will bring traefik by default.

I've setup up a dummy project to demonstrate the issue easily: https://github.com/andreasfernandez/symfony-url-semicolon. Remember: ddev is a hard requirement to test this.

The project renders the current query string and a link containing a semicolon in the query string: `/?foo=bar;baz`. When clicking the link, the request is processed by traefik and the query string is transformed to `baz=&foo=bar`.

### Possible Solution

The low-hanging fix is to remove[ `'%3B' => ';',`](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L40).

**Comment by nicolas-grekas** [comment]
sub-delims in query strings have no special meaning indeed, RFC3936 defines them as special in other parts of an URL, isn't it?
I'm not sure about this change: why this chars, why not the others? Working around Traefik can't be the core reason on our side.

/cc @Tobion WDYT since [you introduced this decoding](https://github.com/andreasfernandez/symfony/commit/3466896acd6bbb5a8f3efe0662aef161ea470231)?

**Comment by Tobion** [comment]
Those chars have no predefined meaning in HTTP but can be have application specific meanings. The reason those are not encoded is so that people can actually use those reserved chars in Symfony. Otherwise they would always get encoded and Symfony would forbid developers to use these chars with their meaning. Also it makes URLs much more readable.

So when Traefik changes the URIs without knowing the context is a bug to me. I don't think we should solve their bug in Symfony.

**Comment by nicolas-grekas** [comment]
Decorating the generator might be the way to do this on your side.
