### ISSUE TITLE
Make Workflow using PropertyAccess

### ISSUE THREAD

**Issue by garak** [symfony/symfony#51822]
### Description

The current implementation of MethodMarkingStore is based on the opinionated assumption that an object has getters and setters.
I find it inconsistent with other Symfony components, where PropertyAccess is used.

### Example

```
<?php

class MyObject
{
    public $property;
}
```

This is an object you can't use with Workflow, since the MethodMarkingStore class is using `'get'.ucfirst($property)` and `'set'.ucfirst($property)`.

**Comment by lyrixx** [comment]
Hello. This is already solved in the 6.4 branch, isn't?

**Comment by garak** [comment]
> Hello. This is already solved in the 6.4 branch, isn't?

No, it isn't.

**Comment by mdeboer** [comment]
Wow, I'm shocked. I assumed it would use PropertyAccess because it is used in so many places (and why wouldn't you).

If there is anything I can do to help or want me to make a PR, please let me know.

**Comment by lyrixx** [comment]
There is not need here for the property access component. The marking store works with method and property. What do you need more?

For your information, when the marking store set the marking is also pass another argument: the context. And this is not possible to do that With the property access component. 

---

FTR I know 6.4 supports property - I did the PR few month ago.

**Comment by garak** [comment]
What if you access your property with a method not named "getSomething"?
About the context, it's not taken into account when you use the property, so it doesn't seem a big concern to me.

**Comment by lyrixx** [comment]
> What if you access your property with a method not named "getSomething"?

So you need to change the name in the configuration.

There is absolutely no need to use the property access component here. You want to use it for the sake of using it. It's brings only drawback `setMArking($marking, $context)` is not supported.

Again the component deals with property or method:

* https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Workflow/Tests/MarkingStore/PropertiesMarkingStoreTest.php
* https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Workflow/Tests/MarkingStore/MethodMarkingStoreTest.php

If you have custom needs, I suggest you to implements your own [marking store](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Workflow/MarkingStore/MarkingStoreInterface.php)

---

I'm going to close this issue, because everything works as expected, and your proposal about internal refactoring does not work as explained.

Thanks for the discussion
