### ISSUE TITLE
[Form] broken behavior with integer named children since 6.3.6

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#52248]
### Symfony version(s) affected

6.3.6

### Description

https://github.com/symfony/symfony/pull/52021 introduced an issue when form children are named like integers.

When handling the request values are re-indexed and loose their submitted index value.

### How to reproduce

See reproducer with failing test case https://github.com/symfony/symfony/compare/5.4...dmaicher:symfony:reproducer_form_integer_children?expand=1

Where the first child named `0` will get the submitted value for the second child named `1` :confused: 

### Possible Solution

Revert change?

**Comment by OskarStark** [comment]
So 5.4 will be affected too, after release?

**Comment by derrabus** [comment]
cc @priyadi

**Comment by priyadi** [comment]
Workaround for this issue:

https://github.com/symfony/symfony/compare/6.3...priyadi:symfony:workaround-52248?expand=1

It restores the old behavior if there are no files in the request. It is only a workaround because the same problem will still occur if there are files in the request.

To really fix this problem, Form needs to be able to recognize the difference between

```html
<input name="root[0]">
<input name="root[1]">
```

and

```html
<input name="root[]">
<input name="root[]">
```

I'm not sure if this is even possible in PHP.

**Comment by priyadi** [comment]
I'm submitting my workaround because the way I see it is that our only other alternatives are:

* Revert and restore the buggy params & files merging code.
* Don't pretend we can reliably merge params & files, and let the users handle both separately. But it probably requires an API change.
