### ISSUE TITLE
[AssetMapper] Unable to use large packages on jsDelivr (highcharts) with AssetMapper

### ISSUE THREAD

**Issue by evertharmeling** [symfony/symfony#52533]
### Description

Let me start with, sorry Ryan for messing around again 😊

When running:
`symfony console importmap:require highcharts` 

I get the following error:

![Screenshot 2023-11-10 at 09 43 01](https://github.com/symfony/symfony/assets/308513/ac2b7071-2695-4177-9672-4987e2e44b5b)

This is mainly just caused by the jsDelivr API and looking at the [package](https://www.jsdelivr.com/package/npm/highcharts?tab=files) they try to give some more info. They mention, for `highcharts` specific, to look at the `dist` ([repo](https://github.com/highcharts/highcharts-dist/)) of the package.

However the `highcharts-dist` package is not available and therefor it's (still) not possible to use the command like `symfony console importmap:require highcharts-dist` for that.

### Long story short
How should in this case `highcharts` (or any package which exceeds the limit) be used in combination with `asset-mapper`? 
- Is there a way?
  - If not, should we add support for it or explicitly don't support it as it's basically a problem caused by jsDelivr? 

Either way we should add something to the documentation about such a scenario?

### Possible approaches
- Even using the `install` jsDelivr snippet and add that in my base template gave me a `403` error. Looking at [highcharts-dist documentation](https://github.com/highcharts/highcharts-dist/#use-our-cdn) it would be possible to use their own CDN, but that's not supported in `asset-mapper` at the moment. 
  - Should we revert deprecate the `url` option in the `ImportMapConfigReader`? And somehow add support for this scenario?
  - Also using a custom 'install 'snippet would gave me errors like `An import map is added after module script load was triggered.` So we should fix this with the `importmap()` function / in the `importmap.php` file.
- Ability to add a custom `PackageResolverInterface` and have a multiple resolvers chain?

I even went rogue trying to have sort of an hybrid `asset-mapper/webpack-encore` approach and downloading the `highcharts` package with `yarn` and trying to map the assets:
```yaml
framework:
    asset_mapper:
        paths:
            assets/: ''
            node_modules/highcharts/css: 'highcharts-css'
            node_modules/highcharts/es-modules/Core/Chart: 'highstock-es'
```

But that gave me a similar error

![Screenshot 2023-11-10 at 10 36 45](https://github.com/symfony/symfony/assets/308513/e5e6b816-1ba3-468a-a97a-ddf781f5fb1b)
It may be possible if the code related to the `highcharts` implementation was completely handled with `webpack-encore` and then bundled and imported with `importmap` but didn't try that (yet). It's pretty ugly but if that's the only way...

**Comment by monteiro** [comment]
This is more an issue with jdelivr, and since Asset mapper only supports fetching from there:

<img width="531" alt="Captura de ecrã 2023-11-10, às 15 41 21" src="https://github.com/symfony/symfony/assets/74459/a665e7ba-9aab-4721-a214-28e460ab3d27">

<img width="869" alt="Captura de ecrã 2023-11-12, às 11 20 25" src="https://github.com/symfony/symfony/assets/74459/f67743c3-a746-4abe-9c88-6057df163264">


To surpass this issue, maybe use directly the import on the CDN, 
example:

```
import Chart from 'https://code.highcharts.com/es-modules/Core/Chart/Chart.js';
```

I suppose that will work, but not sure, because I have never used the package.

@weaverryan don't know if in this case if it gives for example 403 for some reason (in this case because the package is too big and the jdelivr limits, should we have a way to set a custom CDN for specific packages like a require using a custom CDN.

**Comment by weaverryan** [comment]
First time I've seen this. I agree, this is a problem with jsdelivr / highcharts. Apparently, they went over the 150mb threshold quite recently - 11.2.0 fails - https://cdn.jsdelivr.net/npm/highcharts@11.2.0 - but 11.0.0 works fine - https://cdn.jsdelivr.net/npm/highcharts@11.0.0. Locally, I see that 11.2.0 is 159MB.

I have no idea why highcharts is so gigantic - their `highcharts.d.ts` file is 23 MB and they have an identical `highcharts.src.d.ts` (well, there is a 4 character difference). I think we should hunt this down with highcharts - they may not realize that they've broken this limit and may have some simple solution. Version 11.0.0 (which is only 7 months old) was 117 MB. So they have added quite a lot of size very recently (even 11.1.0 was only 120MB). In fact, it looks like an update to their build system - https://github.com/highcharts/highcharts/pull/19941 - but that's a guess.
/ 
@evertharmeling can you open an issue on the highcharts repo? I imagine that, if possible, they will want to play nicely with jsdelivr.

> should we have a way to set a custom CDN for specific packages like a require using a custom CDN

For 7.1, we can discuss allowing people to link directly to a CDN if they want to. In that case, the files would be served from the CDN and not downloaded locally. It turns out the logic needed to downloaded files locally is highly dependent on how the CDN serves files / how the library is built. For example, we *could* just allow people to use https://code.highcharts.com/es-modules/Core/Chart/Chart.js via the CDN. But if we downloaded that file, it wouldn't work unless we also downloaded all of the files it imports... and all of the files THEY import :).

Cheers!

**Comment by evertharmeling** [comment]
[Done](https://github.com/highcharts/highcharts/issues/20124)! Thanks for investigating!

As we heavily rely on jsDelivr, it would be great to allow to use a custom CDN (to be able to bypass these sort of errors) or some other way of managing the packages.

**Comment by weaverryan** [comment]
I'm going to close this for now. The good news is that the Highcharts people seem to be aware of the problem thanks to your issue.

For the issue of allowing a different CDN backend or allowing pointing directly to CDNs, if someone needs this, please open a separate issue about it.

Cheers!
