### ISSUE TITLE
Requiring es-module-shims locally in AssetMapper causes console error

### ISSUE THREAD

**Issue by hashbanged** [symfony/symfony#52547]
### Symfony version(s) affected

6.3, 6.4-dev, 6.4.0-beta3

### Description

Using the default remotely-hosted shims works as expected. If requiring the polyfills as a local vendor asset, an error occurs:

**Javascript console**
```
es-module-shims.index-50eab39155ca286f16894eb2ba1c2740.js:7 Uncaught SyntaxError: Invalid or unexpected token (at es-module-shims.index-50eab39155ca286f16894eb2ba1c2740.js:7:12535)
```

The generated file (`assets/vendor/es-module-shims/es-module-shims.index.js`) appears to be mangled.

For projects not needing the shim support, explicitly disabling it removes the error. Including it as a CDN asset, however, means the user will need to write a server CSP allowing the remote host, which may be undesirable. In Apache2:

**security.conf**
```
Header always set Content-Security-Policy "script-src blob: https://ga.jspm.io;"
```

### How to reproduce

In a Symfony ^6.3 project using [AssetMapper](https://symfony.com/doc/6.4/frontend/asset_mapper.html#serving-assets-in-dev-vs-prod), require ES Module Shims  as a local dependency:

```
./bin/console importmap:require es-module-shims

[OK] Package "es-module-shims" added to importmap.php.                               

      Use the new package normally by importing "es-module-shims".
```

Load the project page in a browser and review the inspector console for errors:

![es-module-shims-console-error](https://github.com/symfony/symfony/assets/53536018/14889ca9-2999-4aba-b8f4-d9ae885e1085)

### Possible Solution

A workaround if IE11 support isn't needed is to just disable the polyfill:

**config/packages/asset_mapper.yaml**
```yaml
framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        importmap_polyfill: false
```

**Comment by hashbanged** [comment]
If I replace the local file contents of `es-module-shims.index.js` with the unbundled code hosted at jspm.io ([1.8.0 version](https://ga.jspm.io/npm:es-module-shims@1.8.0/dist/es-module-shims.js)), the error goes away.

**Comment by weaverryan** [comment]
Hi!

For clarification, the functionality you're describing is 6.4 and higher only. You can't replace the shim in this way in 6.3 and when you `importmap:require` files in 6.3, they are not downloaded locally.

But, your bug report is legit. I'm working on it now - it actually looks like a bug in how the sourcemap is extracted (not sure yet what's different about this file to cause an incomplete sourcemap removal when the file is downloaded).

> If I replace the local file contents of es-module-shims.index.js with the unbundled code hosted at jspm.io ([1.8.0 version](https://ga.jspm.io/npm:es-module-shims@1.8.0/dist/es-module-shims.js)), the error goes away.

@hashbanged could you do more a favor? Do you happen to have access to IE 11? If so, could you try replacing `es-module-shims.index.js` with the content from https://cdn.jsdelivr.net/npm/es-module-shims@1.8.2/+esm ?

There are 2 things going on:

A) Currently, the sourcemap extraction is failing for this - that should be easy to fix
B) This file, after loading the polyfill, actually uses `export`. That should fine, since the previous code polyfilled `export`, but I'd like to verify on a browser that doesn't have polyfill support to be sure. We could change to use the non-ESM version of that file (which is more correct), but it'd require some code in Symfony specific to this ONE module. And I'd love to avoid that if it's unnecessary.

If you don't have access to IE 11, let me know and I'm sure we can find someone :)

**Comment by hashbanged** [comment]
@weaverryan -- I replaced that file's content using the 1.8.2 CDN code directly, and IE11 reports this:

![ie11-shimmed-1 8 2](https://github.com/symfony/symfony/assets/53536018/8d60ef9c-6499-4544-8c37-451798d8ef0e)

I'm guessing it's the arrow function at that position. I get a similar error using the remote URL, rather than the locally downloaded package in importmap.

BUT: in modern browsers, your patch fixes the truncation. Now it doesn't like the `export`. :|

Being so close to release, I completely wrestled with submitting this in the first place, being really less concerned with IE support and more with clearing errors in good browsers. I wonder if the shim should be opt-in by default (or removed?) Actually, if this issue disappeared in a dark alley...
