### ISSUE TITLE
pregmatch() error with Symfony in Drupal 10 // PHP 8.1.25

### ISSUE THREAD

**Issue by ParadiesDigital** [symfony/symfony#52556]
### Symfony version(s) affected

6.3

### Description

Hi,
i keep getting the following error in a fresh Drupal 10(.1.5) installation running on PHP 8.1.25.

preg_match(): Compilation failed: \k is not followed by a braced, angle-bracketed, or quoted name at offset 6 in Symfony\Component\HttpFoundation\Request->getHost() (line 1160 of (...)/symfony/http-foundation/Request.php).

I searched the web for solutions, but couldn't find anything specific to fix this.
It occurs when i try to add any module. Installations process is being stopped by this. Module is added and available afterwards in the module section, but has to be installed manually in a second step. Knowing this i can work with it, but i am not the only user on that installation and i won't be the admin forever.

Any help appreciated!
Thanks and best

### How to reproduce

Adding a module on a fresh Drupal 10(.1.5) installation running on PHP 8.1.25.
Lower Dupal 10 versions as well as lower PHP 8 versions produced the same error.

**Comment by wouterj** [comment]
Hi! This is an issue with the regex provided in the `trusted_host_patterns` setting of Drupal. This is not a bug in Symfony.

I'm not familar with Drupal code, but it seems like this is something that you configured during the setup. You might want to check the `settings.php` and make sure the regexes used there are valid. Otherwise, I hope someone in Drupal's community is able to help you solve this issue!

**Comment by ParadiesDigital** [comment]
Thank you wouterj, that wasn't obvious to me. I'll look into it and will hopefully fix it in Drupal!
