### ISSUE TITLE
[RFC][Security] SwitchUserToken inherit roles of OriginalToken

### ISSUE THREAD

**Issue by oleg-andreyev** [symfony/symfony#52571]
### Description

In case when User A impersonates another User B, original token is wrapped with `SwitchUserToken` and its roles contains only roles from User B, thus making checks is a bit frustrating because you need to check both roles:

```twig
{% if is_granted('ROLE_ADMIN') or is_granted('IS_IMPERSONATOR') %}
```

It would be great if `SwitchUserToken` could return original user roles too.

Based on the codebase it does not looks hard:

```php
// SwitchUserToken
    public function getRoleNames(): array
    {
        return array_unique(array_merge(parent::getRoleNames(), $this->originalToken->getRoleNames()));
    }
```

by adding override for `getRoleNames` we could eliminate needs to check `IS_IMPERSONATOR`.

Any drawbacks?

**Comment by maxbeckers** [comment]
I don't think that's a good idea. The switch user is there so that you can pretend to be the user and see what the user can do, what he can see in order to provide better support. Or whatever you use this function for in your system. You want to see what the user can see and not necessarily just everything like an admin. Of course, you have to use this a little in certain places, such as the switch back button. But I would only see the distinction here. That's why I think that the roles should not be passed through.

**Comment by wouterj** [comment]
Hi!

I agree with @maxbeckers. What is proposed in this issue is not what impersonation should be. The only cases I would use `IS_IMPERSONATOR` is to show the "exit impersonation" button or to hide personal information of the user.
From the request, I get the feeling that you might understand the function of roles wrongly. Maybe this article can help you a bit: http://wouterj.nl/2020/01/grant-on-permissions-not-roles

Besides all this, it would be a big backwards compatibility break if a security tokens suddenly receives elevated roles that it didn't in older versions.

**Comment by oleg-andreyev** [comment]
@wouterj I've been reading your blogpost about roles and yes, I probably agree that when you need a custom logic for your voter, write it.

So we could create own voter that will vote on ROLE_ADMIN and if SwitchUserToken we can access original one.

**Comment by stof** [comment]
You should be voting on your own permission name though, not on `ROLE_ADMIN`, to avoid confusion with the role voter (otherwise, it will be a nightmare when another dev reads this code and expects role permissions to map only to user roles in the voters)
