### ISSUE TITLE
[HttpClient] RetryableHttpClient messes timeout exception

### ISSUE THREAD

**Issue by rmikalkenas** [symfony/symfony#52587]
### Symfony version(s) affected

6.3.8

### Description

Looks like Symfony's RetryableHttpClient messes up exceptions in case of a timeout.
As showed at the reproducer if request is sent using "GET" method, client throws TimeoutException - which is correct.
But as soon as you change "GET" with "POST", exception class changes to TransportException, even though both exceptions messages are same.
If such behaviour is expected - then how to correctly identify a timeout without weirdly parsing and matching exception message?

Reproduced with php 8.2 and symfony 6.3.8

cc @jderusse maybe you will have some insights, since retryable client is written by you

### How to reproduce

```php
$client = new RetryableHttpClient(HttpClient::create());

try {
    dump('GET');
    $client->request('GET', 'https://httpbin.org/delay/5', ['timeout' => 1.0]);
} catch (\Symfony\Contracts\HttpClient\Exception\ExceptionInterface $e) {
    dump($e::class . '::' . $e->getMessage());
}

// GET
// Symfony\Component\HttpClient\Exception\TimeoutException::Idle timeout reached for "https://httpbin.org/delay/5".

try {
    dump('POST');
    $client->request('POST', 'https://httpbin.org/delay/5', ['timeout' => 1.0]);
} catch (\Symfony\Contracts\HttpClient\Exception\ExceptionInterface $e) {
    dump($e::class . '::' . $e->getMessage());
}

// POST
// Symfony\Component\HttpClient\Exception\TransportException::Idle timeout reached for "https://httpbin.org/delay/5".
```

**Comment by nicolas-grekas** [comment]
I'm reopening, but in the light of #53889, I must say that this might be the expected behavior: timeouts thrown while requesting the status code or headers are not regular timeouts. They're unrecoverable transport errors. Semantically, timeout exceptions are meant to signal a recoverable transport error (one might just need to be more patient to get some activity back and thus recover from the timeout).

About GET vs POST behavior, this might also be the desired behavior: when a timeout is thrown, the remote server might still have processed the request, so that retrying might not be safe.

Of course, if the timeout happens before we sent the headers on our side, then we can safely retry, but we don't have this level of accuracy in the client. Maybe we could detect the situation by leveraging some "info" returned by curl and leverage this in RetryableHttpClient.

If that'd help, AsyncResponse could add the TimeoutException as the "previous" exception of TransportException.

For thoughts.
