### ISSUE TITLE
[Forms] Allow modifications of choices in Form Events

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony#52709]
### Description

Hey,
I'm trying to integrate https://symfony.com/doc/current/form/dynamic_form_modification.html into EasyAdminBundle but honestly it's a bit frustrating.

The code itself works well enough BUT since you have to recreate the choice field every time it seems to loose its attributes set by EasyAdmin.

What would be A LOT! easier would be the ability to overwrite just the choices using the Form events, so the elements keep the rest of their configuration.

### Example

Could be as simple as something like that:

```php
$event->getForm()->get('someChoice')->replaceChoices([
  "new choice" => "nice"
])
```

**Comment by yceruto** [comment]
Well, sadly it's not possible to implement this due to the Form component design being immutable after being built. Even if you can add a new form field (if the parent form is not marked as submitted yet), once it's created with certain options, those options cannot be changed. This is done on purpose for stability and predictability.

But life is richer than that, and it still seems like a valid use case for dynamic form building. Yes, you'll lose the form attributes by using the `$form->add()` method (as documented).

However, thanks to the choice loader option of the ChoiceType, it shouldn't be hard to achieve this without modifying the form field instance.

I don't know which choice type you're using to address this issue, but here is a simple example for the native `ChoiceType`:
```php
namespace App\Form\Choice\Loader;

use Symfony\Component\Form\ChoiceList\ArrayChoiceList;
use Symfony\Component\Form\ChoiceList\ChoiceListInterface;
use Symfony\Component\Form\ChoiceList\Loader\ChoiceLoaderInterface;

class MutableChoiceLoader implements ChoiceLoaderInterface
{
    public function __construct(private iterable $choices)
    {
    }

    public function loadChoiceList(callable $value = null): ChoiceListInterface
    {
        return new ArrayChoiceList($this->choices, $value);
    }

    public function loadChoicesForValues(array $values, callable $value = null): array
    {
        return $this->loadChoiceList($value)->getChoicesForValues($values);
    }

    public function loadValuesForChoices(array $choices, callable $value = null): array
    {
        return $this->loadChoiceList()->getValuesForChoices($choices);
    }

    public function changeChoices(iterable $choices): void
    {
        $this->choices = $choices;
    }
}
```
This loader will allow you to load an initial choices value, which you can modify at any moment by using the `changeChoices()` method:
```php
$builder->add('someChoice', ChoiceType::class, [
    'choice_loader' => $choiceLoader = new MutableChoiceLoader([
        // all choices
    ]),
]);

$builder->get('someChoice')->addEventListener(
    FormEvents::POST_SUBMIT,
    function (FormEvent $event) use ($choiceLoader) {
         // ...

        $choiceLoader->changeChoices([
            // new choices subset
        ]);
    },
);
```
If you don't like the lexical variable scoping, you can always get the choice loader instance in this way:
```php
$choiceLoader = $event->getForm()->getConfig()->getOption('choice_loader');
```

**Comment by yceruto** [comment]
I'm closing this here, as the proposal doesn't align with the Form component design. Thank you anyway for the proposal.

**Comment by KDederichs** [comment]
Thanks for the detailed explaination, I'll see what I can do with that :)
