### ISSUE TITLE
Allow prepending extension config in DI Loader (XML/YAML)

### ISSUE THREAD

**Issue by solverat** [symfony/symfony#52789]
### Description

Given: A Bundle extension with an implemented `PrependExtensionInterface`

```php
public function prepend(ContainerBuilder $container): void
{
    $loader = new YamlFileLoader($container, new FileLocator(__DIR__ . '/../../config'));
 
    if ($specialConditionTriggers) {
        $loader->load('my_config_and_services.yaml');
    }
}
```

The Problem: The Loader (in this example, I'm using the YAML file loader) calls `loadFromExtension`, and so the configuration part gets appended:

https://github.com/symfony/symfony/blob/d04ef91ba2ab25b5b4decb3bc6a75a13c45d935f/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L952-L954

Adding a new argument to the loader methods `load()` is probably not the best solution regarding BC, but maybe we could add a second load method? For example:

```php
public function prependLoad(mixed $resource, string $type = null) {}
```

For now, I need to split up those configuration / service files, then I also have to parse the configuration manually to finally use `prependExtensionConfig` in my extension. This feels a bit odd because there is a service that could actually do it for me. :)

**Comment by yceruto** [comment]
Thanks Nicolas for the ping.

Indeed, adding a new argument to existing `load()` methods is complex because the value must travel across different strategies/processes before reaching the place to load/prepend that config, so the impact would be too high.

I was struggling recently with this topic while I was adding this related improvement in 7.1 https://github.com/symfony/symfony/pull/52636 and couldn't find a fancy way to prepend config from an external file.

Perhaps a new method, as you suggested, @solverat, could be a solution to setting up the prepending strategy for the entire loading operation.

This feature definitely got my attention, so I will continue researching it.

**Comment by yceruto** [comment]
Here we go https://github.com/symfony/symfony/pull/52843
