### ISSUE TITLE
[HttpFoundation] Use `base64url` in the `UriSigner` service

### ISSUE THREAD

**Issue by aprat84** [symfony/symfony#52822]
### Description

As the signature will be part of the URL, it would be nice to have 100% url-safe characters in it.

It could be done so it could keep backward compatibility with existing standard base64 signed URLs, I think.

**Comment by nicolas-grekas** [comment]
Would you like to submit a PR doing so?

**Comment by aprat84** [comment]
I can try!

As for the base64url encode/decode functions, would you:
- rely on third party package (ie: `paragonie/constant_time_encoding`)
- create a reusable class inside an existing component (`http-foundation`?)
- just create private methods inside `UriSigner`

As for the implementation, paragonie's is done "by hand" (not relying on PHP's `base64_*` functions), but I've used some simpler implementations like so:

```php
class Base64Url
{
    public function encode(string $data): string
    {
        return rtrim(strtr(base64_encode($data), '+/', '-_'), '=');
    }

    public function decode(string $data): string|false
    {
        return base64_decode(str_pad(strtr($data, '-_', '+/'), strlen($data) % 4, '=', STR_PAD_RIGHT), true);
    }
}
```

**Comment by damienalexandre** [comment]
This would be nice I can confirm. They have this in the Python world: https://docs.python.org/3/library/base64.html#base64.urlsafe_b64encode

I'm using https://github.com/SymfonyCasts/verify-email-bundle now and the URL is signed: guess what, some email clients are messing up the URL because it contains some `=` in the value of parameters (resulting in the link not being usable). 

Signed URL should make sure they are safe and Base64 not that good in URL (see also: https://stackoverflow.com/questions/1374753/passing-base64-encoded-strings-in-url).

**Comment by welcoMattic** [comment]
As a private method already exists [here](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Notifier/Bridge/Vonage/Webhook/VonageRequestParser.php#L91), I think we should provide a service that allow other components (like Webhook, Mailer, Notifier, etc) to use such methods to encode/decode base64url.

However, there are other usages [here](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Security/Core/Signature/SignatureHasher.php#L126) and [here](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php#L44) with another set of substitution characters. 

Other implementations of such a substitution exist, but not necessarily related to URL 
- https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Security/Http/RememberMe/PersistentRememberMeHandler.php#L52
- https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Translation/Dumper/XliffFileDumper.php#L96

**Comment by stof** [comment]
to me, the VonageRequestParser private method should stay as is: this case is required to use the same set of substitution characters than the Vonage server.

The UriSafeTokenGenerator technically uses the same substitution than VonageRequestParser with a different implementation, because `base64_encode` only produces `=` at the end of the string (it is the padding character).

However, I don't think this simple utility warrants a standalone component on its own or a cross-component dependency just for it.

**Comment by DaanBiesterbos** [comment]
I would love a symfony/base64 package with some utility methods. This issue with base 64 encoding is so old and common. I would not complain to see str_replace statements disappear.

**Comment by aprat84** [comment]
@DaanBiesterbos There's [`paragonie/constant_time_encoding`](https://github.com/paragonie/constant_time_encoding).

**Comment by stof** [comment]
And there's also [`spomky-labs/base64url`](https://packagist.org/packages/spomky-labs/base64url) if you only care about the url-safe base64 encoding without caring about constant-time encoding

**Comment by infomaniac50** [comment]
I used the sodium extension in my custom copy of this class. Sodium has been bundled with PHP since 7.2. So it should be available everywhere unless your PHP was compiled without it.

```php
    private function computeHash(string $uri): string
    {
           return sodium_bin2base64(hash_hmac('sha256', $uri, $this->secret, true), SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);
    }
```

See Also:
- https://www.php.net/manual/en/sodium.installation.php
- https://www.php.net/manual/en/function.sodium-bin2base64.php

**Comment by stof** [comment]
@infomaniac50 an extension being bundled with PHP does not mean that it is enabled by default. That's not the same thing.
