### ISSUE TITLE
AssetMapper block page refresh with Firefox

### ISSUE THREAD

**Issue by sblondeau** [symfony/symfony#52830]
### Symfony version(s) affected

7.0.0

### Description

Weird bug with page loading on Firefox; after installing assetmapper 
(seems to work well on Chromium)

### How to reproduce

- start a new Symfony 7.0 project with --webapp
- composer require assetmapper
- create a HomeController 
- remore generated style in home/index.html.twig 
- open /home (with Firefox)
=> page is loading with default light blue background from assets/app.css
- change background color and reload
=> firefox is trying to load the page without success
It works when i refresh using ctrl+shift+R (empty cache).
 

### Additional Context

Linux / Ubuntu
Firefox 119
Asset mapper 7.0
When I uninstall assetmapper, page reload works again.

**Comment by xabbuh** [comment]
Can you create a small example application that allows to reproduce your issue?

**Comment by codingfogey** [comment]
I can confirm the same issue on MacOS with PHP 8.2 and Symfony 6.4. when using the Symfony local web server.

It seems to be connected to preloading. When I remove the `symfony/web-link` component the issue no longer exists even with the `symfony/asset-mapper`still present. It also does not happen in Safari which AFAIK does not support the link header.

**Comment by smnandre** [comment]
It's something between Firefox, macOS, and maybe the symfony local server?

My investigations here: https://github.com/symfony-cli/symfony-cli/issues/382

You can disable in dev the weblink.. or help find a solution (i'm stuck on it for a couple of weeks and i find no solutions).


```
# config/packages/framework.yaml

when@dev
    framework:
        web_link: false
```

When the links are absolute and note relative it works, but that is not the expected behaviour, and relative ones work 
- for the other browsers
- in production with firefox

**Comment by Chris53897** [comment]
Thanks @smnandre That does fix it for me.

**Comment by sblondeau** [comment]
@smnandre this works for me too ! Not a perfect solution but it helps :-) Thanks !
By the way, it is not only a macOs issue, I am on Linux Ubuntu :-)

**Comment by codingfogey** [comment]
Thank you, @smnandre. Best workaround so far.

**Comment by radiz13** [comment]
Same problem on Windows 10 : firefox (more stable with Chrome, but happens when page is open in Firefox)
"web_link: false" doesn't work for firefox.
Only way to fix on firefox, comment the {{ importmap('app') }}

**Comment by smnandre** [comment]
On Firefox, you may have to stop / start the local server to get a normal situation again.

Do you all (@Chris53897 @sblondeau  @radiz13 and anyone seeing this message and having the same problem) use:
- firefox ?
- symfony-cli ? 
- asset mapper ? 

* What happens if you remove your CSS file from the main app.js  ? 
* What happens if you try to access directly the CSS file (or the file wich is not loading) ?

Those answers are the most important to me... but if you have more time, if you could do the following test that could help me

### Local test / reproducer

In a dedicated folder: 

<details>
<summary>
Create a file index.php with the following content ⏬ 
</summary>

```
<?php 
header('Link: </foo.css>; rel=preload; as=style; type=text/css');
 ?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="/foo.css" type="text/css">
		<title>Test</title>
	</head>
	<body>
		<h1>Test preload header</h1>
	</body>
</html>	
```

</details>

<details>
<summary>Create a file foo.css with the following content ⏬ </summary>

```css
@charset "utf-8";
h1 {
	color: green;
}
```

</details>

From this directory, start the server:

```
symfony local:server:start -vvv
 ```
 
 And tell me if that work (ie: the test is green, the page is fully loaded --no spinning indicator anywhere--, ...)
 - once 
 - after one refresh
 - after quick refreshes
 
 Thank you :)

**Comment by radiz13** [comment]
Hi !
- Windows 10
- Firefox 120.0.1
- last symfony-cli dowloaded with scoop
- "symfony/asset-mapper": "7.0.*", (7.0.0)

- What happens if you remove your CSS file from the main app.js ?
Same, infinite loading
- What happens if you try to access directly the CSS file (or the file wich is not loading) ?
put `<link rel="stylesheet" href="{{ asset('myCss.min.css') }}">` in the head and no problem after many refreshes.
(with `{# {{ importmap('app') }} #}`)

**Your test :** 
the test is green, the page is fully loaded, no spinning indicator anywhere **once**
after first refresh : infinite spinning... same problem than assetMapper... without assetMapper...

**Comment by smnandre** [comment]
It's either 100% Firefox bug, or a bit of symfony-cli and Firefox. 

There probably are missing headers, or trouble during internal redirections.. but Firefox should not freeze like that :/

**Comment by ghost** [comment]
Hi there,

I'm kind of experiencing same problem, but with chrome too. I've been trying to switch to assetMapper, then come back to original webpack. I've even remove my project and clone it again, I've tried to remove the docker images etc... It keeps loading forever on redirection...

- Not using Symfony CLI
- Not using Firefox (Chrome)
- Not using Macos (Ubuntu)

- Using Docker (Kévin's template)

**Comment by smnandre** [comment]
Thanks for your feedback!
Do you use or used a local proxy ? What version of Chrome do you use ? And above all.. does this happen with localhost, 127001, or "external" domains ?

**Comment by ghost** [comment]
@smnandre , 

I'm using Chrome Version 119.0.6045.159 and this happens with localhost. Hope it can help

**Comment by codingfogey** [comment]
OS: Mac
Firefox: 120.0.1
PHP: 8.2
Symfony: 6.4
Symfony CLI: yes
Local proxy: yes (also happens with localhost/127.0.0.1)

Removing only the main `app.css` from `app.js` does not change anything. Removing all `*.css` files does.

It is possible, to access any asset file directly even while the page reload ist blocking. 

I also recognised that on reloading (and blocking) the local web server does not even log the request. It seems as if Firefox never sent it.

I conducted your test, @smnandre. My results are:

- once (or full reload): works
- reload: does not work
- quick reloads: do not work

Log on first load says (there are no more log entries after that):

```
[Web Server ] Dec  4 09:01:13 |INFO   | SERVER GET  (200) / preloaded_resources=["/foo.css"]
[Web Server ] Dec  4 09:01:13 |ERROR  | SERVER unable to preload links: http2: recursive push not allowed 
[Web Server ] Dec  4 09:01:13 |INFO   | SERVER GET  (200) /foo.css ip="127.0.0.1"
```

**Comment by fnash** [comment]
Hello @smnandre 

Below my config:
- Symfony 6.4
- Symfony CLI 5.7.2
- Firefox 120.0.1.
- php 8.3.1 
- Ubuntu 20.04

I reproduced the bug with your index.php and foo.css

In Firefox, only the first display works perfectly.
From the 2nd refresh, it does not work. Infinite spinner.
Only Ctrl+shift+R works.
![Capture d’écran de 2023-12-24 22-49-15](https://github.com/symfony/symfony/assets/3097006/cb69576d-d889-47d5-a2b8-9eb815fd9c23)

In Chrome it works!
![Capture d’écran de 2023-12-24 22-50-07](https://github.com/symfony/symfony/assets/3097006/4157b4cb-9dda-428f-944d-b509aa71bd06)

**Comment by fnash** [comment]
updated Symfony CLI to 5.7.6
It works! 
Fixed with https://github.com/symfony-cli/symfony-cli/pull/391

**Comment by radiz13** [comment]
Yessss, it's fixed.
