### ISSUE TITLE
[Scheduler] Cannot have multiple #[AsPeriodicTask] on the same method with the same frequency

### ISSUE THREAD

**Issue by alex-dev** [symfony/symfony#52853]
### Symfony version(s) affected

6.4

### How to reproduce
Wire a class containing the following into a framework app with scheduler. 

```php	
#[AsPeriodicTask('PT30M', arguments: ['arg_1'])]
#[AsPeriodicTask('PT30M', arguments: ['arg_2']')]
public function method(string $arg): void {}
```

### Description
Fails to instantiate a `Schedule` with `Duplicated schedule message.`
Visibly, they are different tasks, but `ServiceCallMessage::__toString()` does not consider arguments.

### Possible Solution
Serialize args, potentially crc32 them too, into `ServiceCallMessage::__toString()`

**Comment by valtzu** [comment]
I did not intentionally add arguments to `ServiceCallMessage::__toString` because arguments may be long strings and that would make `debug:schedule` output clumsy – but yeah sure that would be the easiest solution here.

---

Btw, what should happen if I have the exact same definition twice?

```php
#[AsPeriodicTask('PT30M', arguments: ['arg_1'])]
#[AsPeriodicTask('PT30M', arguments: ['arg_1'])]
public function method(string $arg): void {}
```

I would expect it to execute 2 times or to throw an error during container build – right now the 2nd one is silently ignored. I think instead of using hash-based ids, better would be to just use array index in the StaticMessageProvider to define the uniqueness.

I think it may be wrong in general to consider a recurring message with all the same params the same – duplication may be intentional. I think the message id should come from the provider and not from the message content, maybe just the keys from `MessageProviderInterface::getMessages`

**Comment by alex-dev** [comment]
I think exact same message should be an error. One can always adjust the schedule to cover both messages.

**Comment by valtzu** [comment]
> One can always adjust the schedule to cover both messages.

But the issue is not related to the attribute / tag, same error happens with all the messages which don't include all things in `__toString` of the message, whether configured with attributes or from a schedule provider class.

---

> I think exact same message should be an error. 

Not sure where this should happen – the message provider is not executed during container build so it would mean either

1. Doing the check runtime, like the current `Duplicated schedule message` `LogicException`
2. Doing the check in compiler pass – this would then only cover autoconfigured schedule and duplicates from a `ScheduleProvider` would still be silently ignored.

Probably 1 because messages may come from db nowadays, thus not be available build-time anyway. But I consider this a separate issue.

---


Anyway, I added the arguments to `ServiceCallMessage::__toString` in https://github.com/symfony/symfony/pull/52874

**Comment by alex-dev** [comment]
Since `RedispatchMessage` is also `Stringable`, it fails the same way. I guess every scheduling message will present the same issue.
