### ISSUE TITLE
[Routing] Allow extending Route attribute

### ISSUE THREAD

**Issue by tjveldhuizen** [symfony/symfony#53467]
### Description

In our project, we are using [invokable controllers](https://symfony.com/doc/current/controller/service.html#invokable-controllers). Because we have multiple 'environments' (pages for clubs, for individual members and for admins) served on sub domains, we have currently extended the Route annotation with a ClubRoute, PersonRoute and AdminRoute, containing the default hostname, a prefix for the routes and some defaults and requirements for the parameters in this route.

Since the Route attribute is final, extending of the attribute is not possible. Therefore we have to repeat this configuration in a lot of controllers. I understand the choice to make the Route final, but hope for a way to allow us using the preset routes. An alternative for removing the final status would be an option to register custom Route attributes for the routing system, but I haven't found a good extension point to do this.

**Comment by mbabker** [comment]
Another use case where the added `@final` annotation creates noise.

FOSRestBundle has an [extended `Route` attribute](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3.x/Controller/Annotations/Route.php) that allows defining routes supporting a single HTTP method with an attribute that is a bit easier to consume (instead of `#[Route('/api/v1/posts', methods: ['GET'])]` you can use `#[Get('/api/v1/posts')]` and get the same configuration).

I know I've seen the argument that attributes can't be extended to add functionality as the loaders wouldn't know what to do with it so they should be treated as final, but the `@final` annotations also effectively make adding extended attributes for repeated configurations like the OP has or for DX shortcuts like FOSRestBundle's pointless as it adds noise to the deprecation logs.

**Comment by nicolas-grekas** [comment]
PR welcome on my side. We need to be sure the AttributeLoader takes inheritance into account.
