### ISSUE TITLE
[DI] Getting the wrong error message ("no such service exists, did you create a class that implements this interface?" when class exists but its constructor is private)

### ISSUE THREAD

**Issue by gnutix** [symfony/symfony#53651]
### Symfony version(s) affected

6.3.7

### Description

Hello there!

I created an interface and a class implementing it and injected it in another's class constructor. But I made a mistake, and created the implementation with a private constructor instead of a public one.

The framework failed with the following error message : 

> Cannot autowire service "App\Domain\X": argument "$y" of method "__construct()" references interface "App\Domain\YInterface" but no such service exists. Did you create a class that implements this interface?

Therefore, I started to triple-check that the class name, namespace, filename were all correct, tried commenting a bunch of dependencies, rebuilt composer's autoloader, restarted my Docker env... Nothing did the trick.

Then I thought to try to register the service by hand in `config/services.php`, and then the error changed to : 

> Invalid service "App\Domain\YInterface": constructor of class "App\Domain\Y" must be public.

That was it! Changed the constructor from private to public, and it was fixed. It would have been great if I didn't lost half an hour because the error wasn't the correct one though. :)

Hope it could be fixed in the future, though I understand it's low priority.

Have a nice day!
gnutix

### How to reproduce

Inject a class with a private constructor in another one.

### Possible Solution

Display the proper error message.

**Comment by ghost** [comment]
> though I understand it's low priority.

I wouldn't say it's a low priority. The debugging you have to went through and the time you spent on this should never happen. It's a tragic DX just because of a bad exception message.

**Comment by nicolas-grekas** [comment]
This could be improved by checking if the class exists just before throwing exception I suppose. Anyone up for a PR?

**Comment by maxbeckers** [comment]
It's not that easy @nicolas-grekas, we do have here only the Interface in the `$type` and `null` in `$value`...
https://github.com/symfony/symfony/blob/0102e1e875852e8112f55419b533a6598da49241/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L287-L296
And then the exception is thrown because the value is expected to be not null. The reason is that it would be loaded dynamically and not explicit as @gnutix then did by adding the class into the config file.
So we can't just say "constructor of class "App\Domain\Y" must be public." because we don't have enough details here to decide it.

**Comment by mikocevar** [comment]
After 3 days of vigorous debugging I found the issue! The problem lies in the `findClasses` method of the FileLoader class in the symfony/dependency-injection package.

Here: https://github.com/symfony/dependency-injection/blob/7.0/Loader/FileLoader.php#L295-L297

The if statement results to FALSE because the class in fact is not instantiable and as a result it is skipped. Not having the class in the `$definitions` array of the ContainerBuilder.php makes the misleading error pop-up, because there is no attempt to instantiate the class.

Improving the if statement with

```
if ($r->isInstantiable() || $r->isInterface() || !is_null($r->getConstructor())) {
	$classes[$class] = null;
}
```
includes the the class and later on throws the problem the developer needs to know:

> Cannot resolve argument $testService of "App\Controller\TestController::indexAction()": Invalid service "App\Services\TestableService": its constructor must be public.

I would LOVE to make the PR for this, since I already put this much time in it. The fact that I'm writing a comment is to make sure that I'm going in the right direction with the fix. I would appreciate a comment @nicolas-grekas

**Comment by xabbuh** [comment]
Your findings and conclusions look good to me. But we need to carefully check if making the suggested change makes sure that the new definitions that are added with this change are later cleaned up properly (for cases where the `AutowirePass` or any other compiler doesn't error anyway).

**Comment by mikocevar** [comment]
I cloned the https://github.com/symfony/dependency-injection.git repository and ran all the tests with the updated statement and all pass (with some risky and skipped test which are present even without the change).

I also want to add a new test covering this issue, but the way I did it now, broke some other tests that would need to get updated because of the newly added stubs. I do need to consider if there is a better way to cover this.

@xabbuh Can you point me to the cleanup that you are mentioning, so I can check what is happening there?

There is also another solution which might be better. Since the import is currently skipping classes that are not instantiable and also throwing some errors:

```
if (!$r) {
	throw new InvalidArgumentException(sprintf('Expected to find class "%s" in file "%s" while importing services from resource "%s", but it was not found! Check the namespace prefix used with the resource.', $class, $path, $pattern));
}
```

We could just throw another error and stop the execution right there, like this:

```
if (!$r->isInstantiable() && !is_null($r->getConstructor())) {
	throw new InvalidArgumentException(sprintf('Invalid service "%s": constructor of class "%s" must be public.', $path, $class));
}
```

All tests still pass with this change and the developer is notified right from the start.

The whole error then looks like this:

> Invalid service "/var/www/html/src/Services/TestableService.php": constructor of class "App\Services\TestableService" must be public in /var/www/html/config/services.yaml (which is being imported from "/var/www/html/src/Kernel.php").

Correct me if I'm wrong but I do not see why a service should be included for autowiring if its constructor is private. I am aware of Singletons but those are not meant to be autowired anyway. Now since manually registering a service with a private constructor already throws a meaningful error, this covers for cases with wildcard imports. This solution also comes closer to what Nicolas suggested.

**Comment by xabbuh** [comment]
@mikocevar Can you open a PR with the changes that you have in mind? It's probably easier to discuss potential issues with real code in mind.

**Comment by HMRDevil** [comment]
@gnutix @nicolas-grekas @xabbuh @maxbeckers
This applies to the 5.4 branch too.
A possible alternative and simplest solution is to add a notification to the exception message that the constructor of the class implementing the interface should not be private. Something like this:

> In DefinitionErrorExceptionPass.php line 49:
Cannot autowire service "App\Controller\IndexController": argument "$goodLuck" of method "__construct()" references interface "App\Contracts\SomekindInterface" but no such service exists. Did you create a class that implements this interface?
NOTICE: Class constructor implementing this interface should not be "private".

What do you think about this?
