### ISSUE TITLE
[Console] Listen to SIGHUP

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony#53965]
### Description

Hi,

Im wondering should https://github.com/symfony/symfony/blob/b167190e9085692a99312a4fd371df235961790c/src/Symfony/Component/Console/Application.php#L100C56-L100C63 include [`SIGHUP`](https://en.wikipedia.org/wiki/SIGHUP)?

Im beginng to suspect this is the signal we receive during deployment, and since we dont listen to it, our locked cronjobs are not released if they were running.

cc @lyrixx

**Comment by lyrixx** [comment]
I'm not sure. Listening signals imply overriding PHP default mechanism. Now, our implementation is quite good but... We never know 😅. So I'm a bit reluctant to add more signals.

Then, your use case is not super strong, since you are not sure. Sorry :/

But

1. You can extends this list in userland. see https://github.com/symfony/symfony/blob/b167190e9085692a99312a4fd371df235961790c/src/Symfony/Component/Console/Application.php#L126C21-L126C46
2. But if you deploy system is super mainstream, and you are 100% sure your app got SIGHUP, we may add it. 

---

Side note: this only dispatch event for a signal, you can listen any signals (those in this list or not per command!)

**Comment by ro0NL** [comment]
That's fair! I was hoping you'd know :angel: 

I will do some more testing soonish.

From a theoretical/architectural POV the signal would fit here right? `SIGHUP == Hang up == ConsoleTerminateEvent`

**Comment by lyrixx** [comment]
> From a theoretical/architectural POV the signal would fit here right? `SIGHUP == Hang up == ConsoleTerminateEvent`

I'm not sure, it would mean the command stop, and it's not the case... It's up to the developer to take such decission.

**Comment by jvasseur** [comment]
The problem with SIGUP is that programs often respond differently depending of if they are simple commands or long running process: for simple commands it means the terminal was closed and so the program should stop, but for long running process the SIGUP signal is often used as a "reload config" signal (it's how the `service {name} reload` is implemented for most services on linux).

**Comment by lyrixx** [comment]
thanks @jvasseur. So it confirm we should not add this signal to the default ones, right?

**Comment by ro0NL** [comment]
> applications that did not require a controlling terminal, such as [daemons](https://en.wikipedia.org/wiki/Daemon_(computing)), would re-purpose SIGHUP as a signal to re-read [configuration files](https://en.wikipedia.org/wiki/Configuration_file), or reinitialize. This convention survives to this day in packages such as [Apache](https://en.wikipedia.org/wiki/Apache_HTTP_Server) and [Sendmail](https://en.wikipedia.org/wiki/Sendmail).

ugh :(

**Comment by ro0NL** [comment]
actually ConsoleTerminateEvent is only dispatched when exit code is set

by default we'd only dispatch ConsoleSignalEvent

which currenly we can't simply listen for :(
