### ISSUE TITLE
[AssetMapper] JavaScriptImportPathCompiler::compile(): returns null in some cases

### ISSUE THREAD

**Issue by tacman** [symfony/symfony#54096]
### Symfony version(s) affected

7.0.4

### Description

Something changed between 6.4.3 and 6.4.4 (and 7.0.3 and 7.0.4).

In the example below, assetmapper is locked to 7.0.3, but updating causes the problem.

### How to reproduce

```bash
git clone git@github.com:survos-sites/dt-demo && cd dt-demo
composer install
symfony server:start -d 
symfony open:local
```

All is well.  Update to 

```bash
composer require symfony/asset-mapper:^7.0.4
bin/console importmap:update
# failure!
symfony open:local
bin/console importmap:install
bin/console importmap:update
symfony open:local
```

**Comment by tacman** [comment]
I can't tell if it's related to the underlying datatables.net libraries being updated, I've opened an issue there as well:

https://datatables.net/forums/discussion/78313/2-0-error-with-importmaps#latest

You'll see that error with the importmap:update command, it fails right away.

**Comment by tacman** [comment]
It appears that a file  in importmap is not longer available.  From the library author:

datatables.net-dt/css/jquery.dataTables.min.css

This part at least is wrong (it resolves to a 404 later in the message that you quote.

The correct file is now named datatables.net-dt/css/dataTables.dataTables.min.css. Same file, different name.

**Comment by fpucci-git** [comment]
Since upgrading to Symfony 7.0.4, our dev site no longer loads css and js

If I try to put the js path present in the dev HTML, the error is as follows

Symfony\Component\AssetMapper\Compiler\JavaScriptImportPathCompiler::compile(): Return value must be of type string, null returned

in[ vendor/symfony/asset-mapper/Compiler/JavaScriptImportPathCompiler.php ](file:///srv/ticket/dev1/vendor/symfony/asset-mapper/Compiler/JavaScriptImportPathCompiler.php#L119)(line 119)
in[ vendor/symfony/asset-mapper/AssetMapperCompiler.php ](file:///srv/ticket/dev1/vendor/symfony/asset-mapper/AssetMapperCompiler.php#L40)-> compile (line 40)
in[ vendor/symfony/asset-mapper/Factory/MappedAssetFactory.php ](file:///srv/ticket/dev1/vendor/symfony/asset-mapper/Factory/MappedAssetFactory.php#L108)-> compile (line 108)
in[ vendor/symfony/asset-mapper/Factory/MappedAssetFactory.php ](file:///srv/ticket/dev1/vendor/symfony/asset-mapper/Factory/MappedAssetFactory.php#L49)-> compileContent (line 49)
in[ vendor/symfony/asset-mapper/Factory/CachedMappedAssetFactory.php ](file:///srv/ticket/dev1/vendor/symfony/asset-mapper/Factory/CachedMappedAssetFactory.php#L42)-> createMappedAsset (line 42)
in[ vendor/symfony/asset-mapper/AssetMapper.php ](file:///srv/ticket/dev1/vendor/symfony/asset-mapper/AssetMapper.php#L41)-> createMappedAsset (line 41)
in[ vendor/symfony/asset-mapper/AssetMapper.php ](file:///srv/ticket/dev1/vendor/symfony/asset-mapper/AssetMapper.php#L47)-> getAsset (line 47)
in[ vendor/symfony/asset-mapper/AssetMapperDevServerSubscriber.php ](file:///srv/ticket/dev1/vendor/symfony/asset-mapper/AssetMapperDevServerSubscriber.php#L193)-> allAssets (line 193)
in[ vendor/symfony/asset-mapper/AssetMapperDevServerSubscriber.php ](file:///srv/ticket/dev1/vendor/symfony/asset-mapper/AssetMapperDevServerSubscriber.php#L127)-> findAssetFromCache (line 127)
in[ vendor/symfony/event-dispatcher/Debug/WrappedListener.php ](file:///srv/ticket/dev1/vendor/symfony/event-dispatcher/Debug/WrappedListener.php#L116)-> onKernelRequest (line 116)
in[ vendor/symfony/event-dispatcher/EventDispatcher.php ](file:///srv/ticket/dev1/vendor/symfony/event-dispatcher/EventDispatcher.php#L206)-> __invoke (line 206)
in[ vendor/symfony/event-dispatcher/EventDispatcher.php ](file:///srv/ticket/dev1/vendor/symfony/event-dispatcher/EventDispatcher.php#L56)-> callListeners (line 56)
in[ vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php ](file:///srv/ticket/dev1/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php#L127)-> dispatch (line 127)
in[ vendor/symfony/http-kernel/HttpKernel.php ](file:///srv/ticket/dev1/vendor/symfony/http-kernel/HttpKernel.php#L154)-> dispatch (line 154)
in[ vendor/symfony/http-kernel/HttpKernel.php ](file:///srv/ticket/dev1/vendor/symfony/http-kernel/HttpKernel.php#L76)-> handleRaw (line 76)
in[ vendor/symfony/http-kernel/Kernel.php ](file:///srv/ticket/dev1/vendor/symfony/http-kernel/Kernel.php#L185)-> handle (line 185)
in[ vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php ](file:///srv/ticket/dev1/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php#L35)-> handle (line 35)
in[ vendor/autoload_runtime.php ](file:///srv/ticket/dev1/vendor/autoload_runtime.php#L29)-> run (line 29)
require_once('/srv/ticket/dev1/vendor/autoload_runtime.php') in[ public/index.php ](file:///srv/ticket/dev1/public/index.php#L5)(line 5)

    <?php
    use App\Kernel;
    require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
    return function (array $context) {
        return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
    };

**Comment by fracsi** [comment]
Possible duplicate of #54078

**Comment by tacman** [comment]
Closed in favor of https://github.com/symfony/symfony/issues/54078
