### ISSUE TITLE
Adding dump twig filter [TwigBridge]

### ISSUE THREAD

**Issue by connorhu** [symfony/symfony#54174]
### Description

If I need to dump 1 existing variable, it would be easier to just write `|dump` instead of writing a function call around it. I suggest adding new twig filter which would be a DX change.
I will do the PR later today if you don't mind this feature.

```php

    public function getFilters(): array
    {
        return [
            new TwigFilter('dump', $this->dump(...), ['is_safe' => ['html'], 'needs_context' => true, 'needs_environment' => true]),
        ];
    }

```

https://github.com/symfony/symfony/blob/12468903d7e2b9aa03fc273c8645e41bd2b86a1a/src/Symfony/Bridge/Twig/Extension/DumpExtension.php#L38-L49

### Example

```twig
{{ variable|dump }}
```

**Comment by stof** [comment]
how is `variable|dump` much simpler than `dump(variable)` ?

Note that when using VarDumper, the recommended usage is to use the `{% dump %}` tag instead (so `{% dump variable %}` which will dump the variable into the web profiler instead of returning the dump inline (which generally breaks the page entirely)

**Comment by connorhu** [comment]
For me it's more handy if I just write after than before and two more brackets. Only one side needs editing. In the case of a longer phrase, the full length should be edited. But I accept it if it's just me.

For dumping more complex stuff, I use the tag of course.
