### ISSUE TITLE
[doctrine-messenger] Error Oracle database lastInsertId() returned false

### ISSUE THREAD

**Issue by javiercno** [symfony/symfony#54193]
### Symfony version(s) affected

6.4.4

### Description

When insert symfony messenger message using doctrine-messenger in Oracle database, return lastInsertId() returned false, no id was returned.

https://github.com/symfony/doctrine-messenger/compare/v6.4.3...v6.4.4#diff-dae291a1786531ebfa80b163d0f9e13e88f49ddf2a70d7f2b15335302e645684R453

### How to reproduce

Install symfony messenger 6.4.4, config doctrine messenger transport and store new message.

This error already existed in previous versions. Oracle does not return lastInsertId, but PHP was passing 'false' to an empty string ''.

Now it's being handled in the if statement, so it throws an exception.

### Possible Solution

No solution :(
doctrine dbal no support lastInsertId with oci8

https://github.com/doctrine/dbal/blob/3.8.x/src/Driver/OCI8/Connection.php#L118
https://github.com/doctrine/dbal/blob/4.0.x/src/Driver/OCI8/Connection.php#L88

**Comment by rjd22** [comment]
This indeed confirmed and forcing Oracle users between a rock and a hard place. The problem is the following.

- There is no way in Oracle to get the latest insert id without knowing the exact sequence name
- using `DECLARE ... BEGIN '$sql' RETURNING id INTO v_id; END;` does not allow us to return the id in the query result as far as I have researched

At this moment I don't see a way to fix this properly but it's a big regression for the Oracle users that is caused by a bugfix. If someone more knowledgeable about Oracle knows a fix that would be great. But AFAIU there is none that would be proper. The only thing I can think of is doing something scary like `select max(id) from ' . $this->configuration['table_name']`

@xabbuh what would be the way forward in this case?

**Comment by derrabus** [comment]
The proper way for Oracle would be to use either a sequence or UUIDs generated on the client.

**Comment by rjd22** [comment]
> The proper way for Oracle would be to use either a sequence or UUIDs generated on the client.

With the sequence there is no way to get the ID without knowing the sequence name. Everything is possible of course but it would cause the Oracle implementation within messenger to move far away from the default implementation.

**Comment by derrabus** [comment]
> Everything is possible of course but it would cause the Oracle implementation within messenger to move far away from the default implementation.

Yes.

**Comment by celsoandrade** [comment]
Any update on this?

I using 6.4.7 and still have this problem.

thank you

**Comment by rjd22** [comment]
When I have some more time and energy I might continue work on this. For now I'm not working on it.

**Comment by celsoandrade** [comment]
do you think a custom transport will solve the problem for now?

**Comment by joshpme** [comment]
I am currently using Oracle + Symfony Messenger on Symfony 5.4 (LTS), but are unable to upgrade to Symfony 6.4 (LTS) due to this limitation. 

Should we upgrading to a fixed v6.4.3?

**Comment by javiercno** [comment]
v6.4.3 is the latest version lts where don't error :(

**Comment by rjd22** [comment]
For the people interested there is a fix for this in https://github.com/symfony/symfony/pull/54566 . If you're willing it would be great to have some more testing. It needs a bit of manual intervention on the table that is written in the comments to add a sequence to the table and link it as a default.
