### ISSUE TITLE
RedirectResponse is sent with invalid content-type when route has non-html default format

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony#54434]
### Symfony version(s) affected

5.x.x, probably even earlier

### Description

When a route has a default format set to smth else than html, and a redirect happens, the response format gets set on the redirect response incorrectly (because RedirectResponse [always has html as content](https://github.com/symfony/symfony/blob/f3403517d8f5c61bd19c5b057ee4ac22f538b2c2/src/Symfony/Component/HttpFoundation/RedirectResponse.php#L73-L88))

This isn't a huge problem in practice as the browser typically does not render this intermediate page's content, but it is nonetheless incorrect.

### How to reproduce

```php
#[Route('/test', name: 'test', defaults: ['_format' => 'json'])]
public function testAction()
{
        return $this->redirect('/test2');
}
```

Load /test, check the response headers of the 302:

```
HTTP/1.1 302 Found
Content-Type: application/json
Location: /test2
[...]
```

If the `_format=>json` is removed from the Route, then it uses the correct default:

```
Content-Type: text/html; charset=UTF-8
```

### Possible Solution

Perhaps the _format response listener should not mess with RedirectResponse instances?

**Comment by smnandre** [comment]
Wonder if the content-type should be kept here.. Same debate took place in fetch repo some time ago : https://github.com/whatwg/fetch/issues/609

**Comment by Seldaek** [comment]
There is a response body so IMO there should be a content type set with it.

**Comment by smnandre** [comment]
This seems to be due to the [Response::prepare()](https://github.com/symfony/symfony/blob/4b659cbe4c140e5fb73961397e18964bc8e48b2e/src/Symfony/Component/HttpFoundation/Response.php#L253) method.

So maybe the RedirectResponse should [set its content-type](https://github.com/symfony/symfony/blob/4b659cbe4c140e5fb73961397e18964bc8e48b2e/src/Symfony/Component/HttpFoundation/RedirectResponse.php#L87) to text/html everytime it sets the response body ?

**Comment by Seldaek** [comment]
Yes that sounds like a reasonable fix.
