### ISSUE TITLE
Unable to send an email: to parameter is missing (code 400).

### ISSUE THREAD

**Issue by paulheijmans** [symfony/symfony#54491]
### Symfony version(s) affected

v6.4.4

### Description

Sending emails no longer works without any adjustments. I retrieve the error Unable to send an email: to parameter is missing (code 400). Other having this problem?

### How to reproduce

Sending e-mails via Laravel:

`Mail::to('test@example.com')
->send(new OrderCreated($order));`

**Comment by xabbuh** [comment]
This is not enough information to reproduce your issue. Please create a small example application that allows to reproduce.

**Comment by michaelhue** [comment]
I noticed a similar issue starting yesterday (April 4th) around 17:00 CEST in all my [Craft CMS](https://github.com/craftcms/cms/) installations that use the [Mailgun adapter](https://github.com/craftcms/mailgun/issues) (which uses symfony mailer).

However, I'm getting a slightly different error:
```Unable to send an email: from parameter is missing (code 400).```

No changes had been made to the affected systems.
I'm still investigating this, but I suspect that Mailgun is the culprit.

**Comment by eswinfen** [comment]
I have seen the same issue wirh error message "mail: to parameter is missing (code 400)" returned. This behaviour began after moving to latest php minor release 8.2.17 on the 8.2 branch. 

After some investigation it looks like the problem is in Symfony\Component\Mime\Part\AbstractMultipartPart::bodyToIterable() method which is now returning an empty array even when supplied with valid data. The bodyToString() method returns the expected message data so I think perhaps the issue is with the Generator function yield in bodyToIterable() method? I am however, not familiar with PHP Generator functions so I may be wrong.

I will try to run a comparison with code running on php 8.2.16 and post the results when I have time.

**Comment by khizarnaeemdev** [comment]
I am also having the same error "Unable to send an email: to a parameter is missing (code 400).". I am using Laravel 10 and sending EmailNotification

Error Happen:

`
 public function sendEmailVerificationNotification()
  {
       
        $this->notify(new VerifyNotification());
  }
`

`
class User extends Authenticatable  implements MustVerifyEmail 
{

    use Notifiable;

    protected $table = HC::TBL_USER;
    protected $primaryKey = HC::PK_USER;
    protected $guarded = [];

  
    public function sendPasswordResetNotification($token) {
        $this->notify(new UserResetPassword($token));
    }

    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyNotification());
    }

    public function sendPasswordChangedNotification() {
        $this->notify(new PasswordChange($this));
    }
}

    $user = User::query()->first();
    $user->sendEmailVerificationNotification();
`

**Comment by michaelhue** [comment]
@eswinfen I don't think the `bodyToIterable()` method is the problem. It returns a generator that you can use like this:
```php
foreach ($body->bodyToIterable() as $value) {
    print($value);
}
```

I replicated the Mailgun API request by copying the headers and body created by `MailgunApiTransport` to Insonmia and the request was successful. So the issue seems to be somewhere in the networking layer.

I'm using PHP `8.3.4` btw.

**Comment by sixgweb** [comment]
Same issue here (to parameter is missing) starting April 4th.  Sending locally works fine for same software and php version (8.2.11) so has to be something with the hosting network or libraries.

Switched to SMTP method as a temporary workaround.

**Comment by michaelhue** [comment]
Turns out I was wrong and @eswinfen was onto something with the `bodyToIterable()` method. The request body sent to Mailgun seems to be empty.

https://github.com/symfony/symfony/blob/524c7038065b65b91cce043e7eff31df901b71c8/src/Symfony/Component/Mailer/Bridge/Mailgun/Transport/MailgunApiTransport.php#L66 

Replacing `$body->bodyToIterable()` with `$body->bodyToString()` resolves the issue and might be a temporary workaround. Just note that this will write the whole mail body to memory (including attachments!).

---

So further debugging revealed that Symfony does create a valid looking request with all required headers and a chunked body. I wonder if the chunked transfer encoding might be borked, either on the client or server side.

**Comment by khizarnaeemdev** [comment]
@michaelhue $body->bodyToString() is working.

**Comment by paulheijmans** [comment]
@michaelhue  Yes it's working!

**Comment by michaelhue** [comment]
I created a small example application to help debug this issue:
https://github.com/michaelhue/mailer-mailgun-issue

However you need to supply your own Mailgun credentials in order to use this.

**Comment by xabbuh** [comment]
Thank you @michaelhue for the application. Someone with Mailgun credentials will need to debug what happened that the communication with Mailgun suddenly fails.

**Comment by RoliJ** [comment]
Same issue here. Started from April, 4th.

**Comment by dev4ndy** [comment]
I have been experiencing this problem since yesterday. But I'm not sure why it happened, if we haven't updated dependencies and PHP version.

**Comment by mfedak-tqgg** [comment]
Having this problem also since Thursday. I also did not change any code or update any dependencies. 

@michaelhue replacing $body->bodyToIterable() with $body->bodyToString() is working for me too. Thanks so much.

**Comment by michaelhue** [comment]
I found a better workaround that does not disable mail body streaming:

https://github.com/symfony/symfony/blob/524c7038065b65b91cce043e7eff31df901b71c8/src/Symfony/Component/Mailer/Bridge/Mailgun/Transport/MailgunApiTransport.php#L63-L67

Set the HTTP version to `1.1` by adding the following option:

```php
$response = $this->client->request('POST', 'https://' . $endpoint, [
	'auth_basic' => 'api:' . $this->key,
	'headers' => $headers,
	'body' => $body->bodyToIterable(),
	'http_version' => 1.1,
]);
```

So it seems the issue only occurs when the request is made with HTTP2.

**Comment by michaelhue** [comment]
I created a local HTTP/2 server with Deno to debug the request further. My findings:

- HTTP/2 does not support chunked transfer encoding.
- `curl` seems to ignore the `Transfer-Encoding: chunked` header in HTTP/2 mode.
- However the request body is still encoded in chunks when using `$body->bodyToIterable()`.
- Thus the request body cannot be read by the HTTP/2 server.

This is the debug output from the HTTP/2 server. Note how the form data is mangled and missing the first entry (`from`), resulting in the `Unable to send an email: from parameter is missing (code 400)` error.

```js
Request {
  method: "POST",
  url: "https://localhost:8000/",
  headers: Headers {
    "accept": "*/*",
    "accept-encoding": "gzip",
    "authorization": "Basic XXXXXX",
    "content-type": "multipart/form-data; boundary=TliGs4Sa",
    "user-agent": "Symfony HttpClient (Curl)"
  }
}
FormData {
  to: "2\r\n\r\n\r\n14\r\nrecipient@example.org\r\n2\r\n\r\n\r\nc",
  subject: "2\r\n\r\n\r\n18\r\nMailgunApiTransport test\r\n2\r\n\r\n\r\nc",
  text: "2\r\n\r\n\r\n20\r\nThis is your plain text message.\r\n2\r\n\r\n\r\nc",
  html: "2\r\n\r\n\r\n1d\r\n<p>This is your HTML message.\r\n2\r\n\r\n\r\nc",
  "h:Sender": "2\r\n\r\n\r\n1e\r\nsender@example.org\r\n2\r\n\r\n\r\ne"
}
```

Why did this issue arise suddenly? My guess would be that Mailgun just enabled HTTP/2 for their API endpoints. But I have no way to verify that.

So, the short-term solution would be forcing HTTP/1.1 requests for `MailgunApiTransport`.
The long-term solution means looking into the way that Symfony uses content streaming for HTTP/2 requests via `CurlHttpClient`, which unfortunately is above my paygrade.

---

I won't be able to create a pull request today due to time constraints, but I'll open one tomorrow if necessary.

**Comment by nicolas-grekas** [comment]
Fixed by #54517, thanks @michaelhue 
Note that this issue happens with recent versions of curl and the next version of it should also provide a fix.

**Comment by hdimitrov1** [comment]
Anyone looking for a Laravel workaround, you can add this to your mailgun config

```php
		'mailgun' => [
			'transport' => 'mailgun',
			'client' => [ // this bit here
				'http_version' => '1.1',
			],
		],
```

**Comment by fakeheal** [comment]
> Anyone looking for a Laravel workaround, you can add this to your mailgun config
> 
> ```
> 		'mailgun' => [
> 			'transport' => 'mailgun',
> 			'client' => [ // this bit here
> 				'http_version' => '1.1',
> 			],
> 		],
> ```

Does this also "fixes" emails with attachments, too?

**Comment by asmshaon** [comment]
> Anyone looking for a Laravel workaround, you can add this to your mailgun config
> 
> ```
> 		'mailgun' => [
> 			'transport' => 'mailgun',
> 			'client' => [ // this bit here
> 				'http_version' => '1.1',
> 			],
> 		],
> ```

Thank you, it works really well.

**Comment by ok200paul** [comment]
In a follow-up to @hdimitrov1 for Laravel users - if you've got an app that's been upgraded from earlier versions of laravel, pop the `client` key onto the base array of config/mail.php:

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Mail Driver
    |--------------------------------------------------------------------------
    |
    */
    
    // ..
    
    'client' => [
        'http_version' => '1.1',
    ],

];
```

**Comment by gauthiermarchand** [comment]
Hi ! 

I have the same issue with the parameter from : `Unable to send an email: from parameter is missing (code 400).`

I read this issue and as @nicolas-grekas said it seems to be fixed. Maybe there is something I did not understand in the fix.

I encountered this issue in 
- Symfony `v 6.4.6`
- php 8.3.6
- curl 8.7.1

Thanks in advance

**Comment by michaelhue** [comment]
> I read this issue and as @nicolas-grekas said it seems to be fixed. Maybe there is something I did not understand in the fix.

The fix should appear in the next official release. For now you can either use one of the workarounds or configure [`preferred-install`](https://getcomposer.org/doc/06-config.md#preferred-install) in your project.

**Comment by gauthiermarchand** [comment]
Thank @michaelhue for your answer 🙏

**Comment by marufdevops** [comment]
Anyone else facing this issue recently? Today, I am facing this in my laravel app! 

Using Laravel 9.

Already tried the above workaround on mail/config.php, not working for me!

**Comment by devon-seitz** [comment]
Curl was the issue for me, updating to 8.8 resolved

**Comment by marufdevops** [comment]
> Curl was the issue for me, updating to 8.8 resolved

@devon-seitz what did you update? can you please elaborate. My app is hosted on lambda through vapor.

**Comment by devon-seitz** [comment]
> > Curl was the issue for me, updating to 8.8 resolved
> 
> @devon-seitz what did you update? can you please elaborate. My app is hosted on lambda through vapor.

For me, my infrastructure was running Curl 8.7. You can check by running something similar to `curl --version`. By updating to 8.8 this was resolved. 

Here is the issue in curl 8.7 https://github.com/curl/curl/issues/13229
