### ISSUE TITLE
debug:dotenv command doesn't show environment variables

### ISSUE THREAD

**Issue by CViniciusSDias** [symfony/symfony#54640]
### Symfony version(s) affected

7.0.6

### Description

If you have an environment variable set, the `debug:dotenv` command doesn't display it. It doesn't even display the values set in the `.env` files.

### How to reproduce

On any symfony application, define a value in `.env` file. Let's use `TEST` as example:
```
TEST=value
```

Run `php bin/console debug:dotenv` and see that it's correctly displayed.

Now run `TEST=other php bin/console debug:dotenv` and see that it's not there anymore.

### Additional Context

The command only shows what's in `'SYMFONY_DOTENV_VARS'`. Since the value is now an env var, on `Dotenv.php:192` it will skip the iteration and it will never be defined in `$loadedVars` nor in `$_SERVER['SYMFONY_DOTENV_VARS']`.

**Comment by ghost** [comment]
Please create a reproducer.

**Comment by CViniciusSDias** [comment]
> Please create a reproducer.

As it's stated in the "steps to reproduce", it happens in any Symfony application and there is no code needed.
So I don't see much value in creating a repo with an empty Symfony project. 😅

**Comment by ghost** [comment]
> 😅

Please keep this kind of emojis for yourself. It's not a place to emphasize your personal feelings about other people comments. Let's focus on the problem.

Indeed the env var declared in .env file is missing from `debug:dotenv` when the same env var passed when executing script

![image](https://github.com/symfony/symfony/assets/25783196/d9ead689-e498-479a-9236-b4631d46ff69)

However I'm not sure this is wrong. With `debug:dotenv` command you list env vars in use that were declared in .env files. TEST was declared in .env but was not used as the real env var is used.

`--help` is ambiguous about what a user should expect.
Description says: `List all dotenv files with variables and values` what can be interpreted as list all variables (with corresponding values) declared in all dotenv files.
However Help says `The bin/console debug:dotenv command displays all the environment variables configured by dotenv` what can be interpreted as it displays only variables **configured by** dotenv - TEST is not configured by dotenv because it already exists.

Let's wait what other contributors or Core Team members will say.

**Comment by nicolas-grekas** [comment]
I think this behavior is WTF.
It'd be nice to be able to list all dotenv vars, even overridden ones. Ideally we would show both the overridden and dotenv values.

**Comment by HMRDevil** [comment]
I'm sorry for my English.
A small comment. This behavior is also present in the 5.4 branch.
@nicolas-grekas Do you think it would look better this way?

![image](https://github.com/symfony/symfony/assets/13382415/b266f1d6-2137-4430-a79c-42e9723ee87a)
