### ISSUE TITLE
[AssetMapper] Fallback URIs for jsdelivr CDN

### ISSUE THREAD

**Issue by kira0269** [symfony/symfony#54936]
### Description

The 2nd of May was a hard day for all asset-mapper component lovers: the certificate of cdn.jsveliver.net had expired.

Because of that, the command importmap:install failed and deployment couldn't be done.

I found that there was a solution: calling another endpoint from the ones below:
- fastly.jsdelivr.net
- gcore.jsdelivr.net

Today, two files in the symfony sources contain the string "cdn.jsdelivr.net" (one from the asset-mapper component and one from the mime component). They are hardcoded and the only way to override those is to apply a composer patch for example.

**Proposed solution**

- Add the other endpoints as fallbacks
- Add the possibility to the developer to override/add endpoints via config file

OR

- Use HttpClient instance to call jsdelivr CDN ?

**Comment by smnandre** [comment]
The one in the Mime component is in a dev script to update the list of mimes so no problem here. 

Regarding AssetMapper what happened to jsdeliver was an extremely unusual incident and they have added a lot of safeguards since. So I dont think it’s worth it. 

When Github is down (and this is way more frequent relatively) your CI does not work.. 

To me this incident does not justify the time required to dev/test/document/maintain some fallback system.

**Comment by alexisLefebvre** [comment]
The relevant line: https://github.com/symfony/symfony/blob/c58c599b9e6cd61c8866271fbe1453cb39fa34b5/src/Symfony/Component/Mime/Resources/bin/update_mime_types.php#L17

Another external dependency: https://github.com/symfony/symfony/blob/c58c599b9e6cd61c8866271fbe1453cb39fa34b5/src/Symfony/Component/Mime/Resources/bin/update_mime_types.php#L26

I suggest another possible solution:
- skip these update steps if for some reason the file can't be fetched, so that asset-mapper works even if there is a network issue

**Comment by kira0269** [comment]
> I suggest another possible solution:
> 
>     * skip these update steps if for some reason the file can't be fetched, so that asset-mapper works even if there is a network issue

The command importmap:install is used to "build" the app. Downloaded files are not supposed to be committed into git repo, like composer vendors. It's not just an "update".

**Comment by kira0269** [comment]
> The one in the Mime component is in a dev script to update the list of mimes so no problem here.
> 
> Regarding AssetMapper what happened to jsdeliver was an extremely unusual incident and they have added a lot of safeguards since. So I dont think it’s worth it.
> 
> When Github is down (and this is way more frequent relatively) your CI does not work..
> 
> To me this incident does not justify the time required to dev/test/document/maintain some fallback system.

I totally agree on this point. But still: using an HttpClient object instead of simple "file_get_contents" with no control over the request made. If your app is behind a proxy for example, it could be useful to specify it for the call.

**Comment by smnandre** [comment]
> The relevant line:
> 
> I suggest another possible solution:
> 
>     * skip these update steps if for some reason the file can't be fetched, so that asset-mapper works even if there is a network issue

As i said, for Mime those files are scripts only used by the maintainers to update the data / regenerate the classes. They are neither available or ... used by anyone else. So let's forget Mime for this topic :)

**Comment by smnandre** [comment]
> instead of simple "file_get_contents" with no control over the request made

Can you show me where `file_get_contents` is called in AssetMapper to fetch content from jsdeliver ?

**Comment by kira0269** [comment]
oh !
My bad, I completely mixed up. The AssetMapper already fetch the files via an HttpClient ^^"""""".
So it's already doable to configure the http client in order to handle the cases I described.

I guess this is acceptable. I'll close this issue then.

Thanks for your help 😄
