### ISSUE TITLE
Configure validation groups dynamically when using `MapRequestPayload`

### ISSUE THREAD

**Issue by asispts** [symfony/symfony#57333]
### Description

In the Form component, we can choose validation group dynamically as explained in these articles:
- https://symfony.com/doc/current/form/validation_group_service_resolver.html
- https://symfony.com/doc/current/form/data_based_validation.html

I don't think that `MapRequestPayload` has this feature yet. Currently, I do the validation manually based on the payload content.

**Comment by yceruto** [comment]
If the validation groups depend on the state of the underlying object you can use `#[Assert\GroupSequenceProvider]` and determine the groups dynamically.

Doc and references:
https://symfony.com/doc/current/validation/sequence_provider.html#group-sequence-providers
https://symfony.com/doc/current/validation/sequence_provider.html#advanced-validation-group-provider
https://github.com/symfony/symfony/discussions/51012

Closing as it's already supported since 6.4
