### ISSUE TITLE
Support substitutions in SendgridApiTransport  

### ISSUE THREAD

**Issue by galion96** [symfony/symfony#57373]
### Description

Is it possible to add a support for substitutions / personalization  like in [substitutions](https://www.twilio.com/docs/sendgrid/for-developers/sending-email/personalizations#sending-a-single-email-to-a-single-recipient-with-substitutions) for multiple users .

I assume it can be done somewhere https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/Mailer/Bridge/Sendgrid/Transport/SendgridApiTransport.php#L128-L137

### Example

Eg payload would be
```
 [
    "from" => [
        "name" => "myname",
        "email" => "foo@bar.com"
    ],
    "personalizations" => [
        [
            "to" => [
                [
                    "email" => "foo.bar@bar.com"
                ]
            ],
            "substitutions" => [
                "-name-" => "Alice"
            ]
        ],
        [
            "to" => [
                [
                    "email" => "foo.bar@foo.com"
                ]
            ],
            "substitutions" => [
                "-name-" => "Bob"
            ]
        ]
    ],
    "subject" => "New mail",
    "content" => [
        [
            "type" => "text/plain",
            "value" => "Hi -name-, lorem ipsum"
        ]
    ]
];
```

**Comment by stof** [comment]
SendgridApiTransport is not meant to be a SDK for the Sendgrid API. It is an implementation of the Mailer abstraction using the Sendgrid API.

Substitutions don't fit the Mailer abstraction because each vendor has its own syntax for them, so the content would not be portable between transport. This is why the Mailer component does not have such feature in its abstraction.
If we wanted to add support for a feature like substitutions in symfony/mailer, it would require defining a syntax for them in symfony/mailer (and an API for providing values for them, but this part is easier) and then having each transport processing that syntax to convert it to the substitution syntax of the vendor. This is quite complex and may not be worth it.

**Comment by galion96** [comment]
> SendgridApiTransport is not meant to be a SDK for the Sendgrid API. It is an implementation of the Mailer abstraction using the Sendgrid API.
> 
> Substitutions don't fit the Mailer abstraction because each vendor has its own syntax for them, so the content would not be portable between transport. This is why the Mailer component does not have such feature in its abstraction. If we wanted to add support for a feature like substitutions in symfony/mailer, it would require defining a syntax for them in symfony/mailer (and an API for providing values for them, but this part is easier) and then having each transport processing that syntax to convert it to the substitution syntax of the vendor. This is quite complex and may not be worth it.

Thanks. I ended up creating a custom transporter and adjusted the getPayload method to look like this:


```
$headers = json_decode($email->getHeaders()->get('x-smtpapi')->getBody(), true);
   foreach($headers['sub'] as $key => $header){
            $personalization[] = array_merge([
                'to' =>[[ 'email' => $key]]
            ],['substitutions' =>$header]);
        }
```
 I guess it's very specific to my usecase
