### ISSUE TITLE
Disable csrf_protection on a certain host or firewall

### ISSUE THREAD

**Issue by Methraen** [symfony/symfony#57400]
### Description

On application that has both a BO and an API (and even some times a FO), it can be pretty tiring to set on every API controller `createForm` the `"csrf_protection" => false`... I already tried to implement the FOSRestBundle workaround (`DisableCSRFExtension.php`) but it seems not to work on sf7 (it does goes through but if I dont set my form directly instead of FormType it does not have impact)...

So it would be really practical to enable/disable csrf_protection based on the host/firewall matched on the request !

### Example

The following does not work ATM for me

```
<?php

namespace App\Common\Form\Extension;

use App\Domain\User\Form\Type\ResetPasswordRequestFormType;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormTypeInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

class DisableCSRFExtension extends AbstractTypeExtension
{
    public function __construct(
        private readonly TokenStorageInterface $tokenStorage,
        private readonly AuthorizationCheckerInterface $authorizationChecker,
    ) {
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        if (!$this->tokenStorage->getToken()) {
            return;
        }

        if (!$this->authorizationChecker->isGranted("ROLE_COLLABORATOR")) {
            return;
        }

        $resolver->setDefault('csrf_protection', false);
    }

    public static function getExtendedTypes(): iterable
    {
        return [FormType::class];
    }
}
```

**Comment by xabbuh** [comment]
This use case doesn't look common enough for me to justify a core feature for it. Using a form in an API is not something that we want to promote. The Form component is built around requests originating from classic HTML forms. That's why I am going to close here. Thank you for understanding.

Please use one of the [support channels](https://symfony.com/support) if you need help getting your `DisableCSRFExtension` to work.

**Comment by Methraen** [comment]
No need to re-open the request then but how would you validate received data in an API without passing it to a form then ?
Usually I personnally do so like this:

```
    public function create(Request $request): JsonResponse
    {
        $form = $this->createForm(UserType::class, $user = new User(), [
            'csrf_protection' => false,
        ])->submit($request->request->all());

        if (!$form->isValid()) {
            throw new FormErrorException($form, Response::HTTP_BAD_REQUEST);
        }

        $this->userManager->add($user);

        $contextBuilder = (new ObjectNormalizerContextBuilder())
            ->withGroups([User::SERIALIZATION_GROUP]);

        return $this->json($user, context: $contextBuilder->toArray());
    }
```

**Comment by xabbuh** [comment]
You would deserialize the incoming data using the Symfony Serializer component and then validate the data using the validator service directly instead of relying on it being used implicitly by the form system.

**Comment by Methraen** [comment]
How about data transformation and error mapping ?

Sometimes I need to transform the data I receive and to do so I use DataTransformers or FormEvents I dont think I can do so with deserialization, or can I ?

Also to map the validation errors client-side, I had a custom ProblemNormalizer to easily map errors directly onto the form, it returns validation errors like so:

```
{
    "type": "https://tools.ietf.org/html/rfc2616#section-10",
    "title": "An error occurred",
    "status": 400,
    "detail": "Bad Request",
    "extended_message": {
        "global_errors": [],
        "property_errors": {
            "plain_password-first": [
                "Les valeurs ne correspondent pas."
            ],
            "old_plain_password": [
                "Cette valeur doit être le mot de passe actuel de l'utilisateur."
            ]
        }
    }
}
```

But with validator validate I receive a ConstraintViolationListInterface that has no form fields context...

Anyway TY for the response I'll think on how to implement the symfony way to validate data in API

**Comment by siganushka** [comment]
@xabbuh 

I also encountered the same problem. Even @Methraen's demo code is the same as mine, After practicing in multiple projects, I think that form components are completely suitable for API. From the perspective of the server, there is no difference between traditional html form and JSON API except for the different data formats (just that API no longer needs the view part of the form). The Events , Data Transformer, and Data validation of form components are still important for API services. I have tried manual serialization or using methods such as Request Mapper to process API data, but I finally returned to form components because they lack event support and data transmission.

Does Symfony have any suggestions for this?
