### ISSUE TITLE
Ban `uniqid()` from codebase

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#57588]
### Description

Following #57542, I'd like to review our usages of the `uniqid()` function. It is currently considered for [deprecation and removal](https://wiki.php.net/rfc/deprecations_php_8_4#deprecate_uniqid).

I'm not sure if this the RFC for the deprecation will actually pass, but I agree with the motives behind that proposal. We should stop using that function.

We have quite a few usages in our codebase that can be clustered by the following concerns:

#### Generate a collision-free temporary file.

https://github.com/symfony/symfony/blob/435f1946e11185ea375ecb4611c4b01879080df0/src/Symfony/Bridge/PsrHttpMessage/Factory/HttpFoundationFactory.php#L110

The `tempnam()` function should be good enough for this purpose. And if it's not, maybe we can add a safer replacement to the Filesystem component?

#### Generate a collision-free random value for tests

https://github.com/symfony/symfony/blob/6115ab07511f7ffeaaa5cedc9adfd52cbb2102ec/src/Symfony/Bridge/PsrHttpMessage/Tests/Factory/HttpFoundationFactoryTest.php#L175

It might be even better to work with a constant value in such situations.

#### Salt for a random string

https://github.com/symfony/symfony/blob/6ce530c5e90397d88e3a76a56db266c74d651584/src/Symfony/Bridge/Twig/NodeVisitor/TranslationDefaultDomainNodeVisitor.php#L117

We might as well just use `random_bytes()` in such situations.

#### Generate a collision-free identifier

https://github.com/symfony/symfony/blob/6ce530c5e90397d88e3a76a56db266c74d651584/src/Symfony/Component/Messenger/Bridge/Redis/Transport/Connection.php#L524

A UUIDv7 would probably be better suited in these cases. That would mean that we would need to pull `symfony/uid` as a dependency in several packages, but that seems reasonable to me.

**Comment by GromNaN** [comment]
> Salt for a random string
> We might as well just use `random_bytes()` in such situations.

For predictability and performance, it is better to use a simple sequence of ints. This is what we ended up implementing [in the Twig compiler](https://github.com/twigphp/Twig/blob/045f5adec773f6430676fdda078b2fa393391938/src/Compiler.php#L247).

**Comment by TimWolla** [comment]
> It is currently considered for [deprecation and removal](https://wiki.php.net/rfc/deprecations_php_8_4#deprecate_uniqid).

Correction: It is considered for “deprecation”. The RFC *very intentionally* proposes an _indefinite_ deprecation period, with the removal - _should_ that ever be desired - left for a future vote for a major PHP version that is at least 5 years in the future and has a version number of at least 10.

> The `tempnam()` function should be good enough for this purpose. And if it's not, maybe we can add a safer replacement to the Filesystem component?

`tempnam()` guarantees creating a unique file by means of locking and assistance by the operating system. If you also require the generated filenames to be hard to guess, then PHP 8.4 has you covered. In that case you probably should also ensure you set an appropriate `umask()` before creating the file.

> We might as well just use `random_bytes()` in such situations.

If the counter, as suggested by Jerome, works for you then I would recommend using a counter.

If you need the values to be unpredictable for a given request only, then you could combine the counter with a secure prefix generated with `random_bytes()`: Without knowing the secure prefix you don't know the generated identifiers, but the generation of each identifier super cheap.

If for some reason you require each identifier to be unpredictable on its own (e.g. to not leak the amount of identifiers generated within the request), but don't need cryptographically secure randomness (e.g. because the identifiers are regenerated for each request), then you could use `Random\Engine\Xoshiro256StarStar` + `Random\Randomizer::getBytesFromString()`. The Xoshiro256** engine is the fastest engine available.

-------------

Let me know if I can give any further recommendations or advice for specific situations. Really happy about this issue cleaning up the use of `uniqid()` independent of the RFC results.

**Comment by derrabus** [comment]
> For predictability and performance, it is better to use a simple sequence of ints. This is what we ended up implementing [in the compiler](https://github.com/twigphp/Twig/blob/045f5adec773f6430676fdda078b2fa393391938/src/Compiler.php#L247).

In a compiler especially, randomness is even harmful. A compiler should be deterministic because its results should be reproducible. Yes, a simple monotonic sequence is the better strategy in this case. Thank you for this remark.

---

> Correction: It is considered for “deprecation”. The RFC _very intentionally_ proposes an _indefinite_ deprecation period, with the removal - _should_ that ever be desired - left for a future vote for a major PHP version that is at least 5 years in the future and has a version number of at least 10.

Thank you for clarifying this. From my POV, it doesn't really matter when the function is removed. The motivation for the deprecation is absolutely valid and we should not use that function anymore.

Also, thank you for all your input, @TimWolla. It's certainly helpful for everyone working on this ticket.

**Comment by TimWolla** [comment]
> Thank you for clarifying this. From my POV, it doesn't really matter when the function is removed. The motivation for the deprecation is absolutely valid and we should not use that function anymore.

The last time I attempted to deprecate a widely-used function for similar reasons, there were reactions that this would be too large of an impact on the ecosystem, ultimately resulting in the vote being declined and the function not being deprecated.

That's why I find it important to clarify that the RFC proposes to mark the function as deprecated to indicated that it is unsafe and should no longer be used in newly written new / greenfield projects, but not change anything else / not to remove it to give users the time they need to migrate to a better alternative. Not every project is as organized and foresighted as Symfony is.
