### ISSUE TITLE
[Html Sanitizer] Sanitization remove single < (less than) char which is not part of any tag

### ISSUE THREAD

**Issue by touhidurabir** [symfony/symfony#57597]
### Symfony version(s) affected

6.2.2

### Description

Html Sanitizer remove any use of `<` (less than) char which is not even a part of any tags . It does preserver the `>` (greater than) character without any issue . 

For example, sanitizing string `<img src="invalid-url" onerror="alert('XSS Attack prefix')" /> 2 > 1 & 3 < 5` will result in `2 &gt; 1 &amp; 3 5` . Notice that last part where `3 < 5` becomes `3 5` and results in missing the single `<` (less than) character which was not part of any tag. 

### How to reproduce

```php
<?php

use Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig;
use Symfony\Component\HtmlSanitizer\HtmlSanitizer;

$config = (new HtmlSanitizerConfig())
    ->allowSafeElements();

$sanitizer = new HtmlSanitizer($config);
$input = '<img src="invalid-url" onerror="alert(\'XSS Attack prefix\')" /> 2 > 1 & 3 < 5';

// this results in `<img /> 2 &gt; 1 &amp; 3  5` but expected `<img /> 2 &gt; 1 &amp; 3 &lt; 5`
echo $sanitizer->sanitize($input);

```

### Additional Context

The use of single `<` char is very normal and should be considered when not part of any tags . One big example is the scientific journal articles where a journal article title,sub title or abstract may contains some simple mathematical expression or simple logical comparison that included both the `<` and `>` character .

**Comment by ChadSikorra** [comment]
I was bored this morning so decided to see what causes this.

This actually happens as part of the mastermind HTML5 parser which sees that as an illegal tag opening and omits it:

https://github.com/Masterminds/html5-php/blob/master/src/HTML5/Parser/Tokenizer.php#L145-L148

I'm not sure what the expected behavior is in regards to the HTML5 spec for parsing / tokenization (doesn't seem clear to me, and I'm not really familiar with it). However, it is a detectable error after parsing in general.

**Comment by ndossche** [comment]
According to the HTML5 spec the text should indeed serialize back to ` 2 &gt; 1 &amp; 3 &lt; 5`, so the omission of the `<` symbol seems like a parser bug.

**Comment by nicolas-grekas** [comment]
thanks for digging - not for symfony :)
