### ISSUE TITLE
Kernel broken in 6.4.9 (and possibly in latest 7.1.* too)

### ISSUE THREAD

**Issue by garak** [symfony/symfony#57662]
### Symfony version(s) affected

6.4.9

### Description

This kernel class https://github.com/dustin10/VichUploaderBundle/blob/master/tests/Kernel/SimpleAppKernel.php works in the bundle (e.g. the tests on it pass) until Symfony 6.4.8
Since 6.4.9, the test fails with this error as soon as the test tries to boot the kernel:
> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: Service "kernel" not found: the container inside "Symfony\Component\DependencyInjection\Argument\ServiceLocator" is a smaller service locator that is empty...

### How to reproduce

Run the VichUploaderBundle tests with Symfony 6.4.9 (I did it by altering the composer.json file), you'll get the error.
Do the same with Symfony 6.4.8, the tests will pass.

It should be the same with Symfony 7, but I didn't try (I'm only sure that it fails with the latest and it didn't fail a few days ago, so I suppose it applies to Symfony 7 too):

**Comment by yceruto** [comment]
It seems to be related to these changes: https://github.com/symfony/symfony/pull/57553/files and the enabling of optional warmers when the cache/build dirs are different.

By default, the build dir is the same as the cache dir unless you configure it otherwise, so I suspect they don't match here because the `$cacheDir` is the canonicalized absolute pathname from `kernel.cache_dir` parameter, while the `$buildDir` is the raw path from `getBuildDir()` directly.

/cc @nicolas-grekas

**Comment by yceruto** [comment]
Massimiliano, you can temporarily fix the issue on your own by caching the real cache path in memory, thus returning the real path in the `getBuildDir()` method as well, `tests/Kernel/AppKernelTrait.php`:

```php
trait AppKernelTrait
{
    private string $cacheDir;

    public function getCacheDir(): string
    {
        return $this->cacheDir ??= realpath($this->createTmpDir('cache'));
    }

    // ...
}
```

**Comment by nicolas-grekas** [comment]
Thanks for investigating @yceruto 
Then this is solved already by https://github.com/symfony/symfony/pull/57593
