### ISSUE TITLE
[Messenger] Add option to set custom delay on RecoverableMessageHandlingException

### ISSUE THREAD

**Issue by jannes-io** [symfony/symfony#57756]
### Description

Add an optional argument to the `RecoverableMessageHandlingException` that allows messenger to delay the retry for longer than the configured retry if the developer already knows that it'll take longer, but should be retried.

Useful in many scenarios, the code example uses the Retry-After header that is often accompanied by a 503. Some APIs with rate limits will also include headers when a rate limit is hit for when it can be retried.
Or simply to delay the retry of this 1 message, while all other messages should adhere to the configured retry timeouts.

### Example

Before:
```php
#[AsMessageHandler]
class ExampleMessageHandler
{
    public function __invoke(ExampleMessage $message): void
    {
        try {
            (new Client())->get('http://someapi');
        } catch (ServerException $ex) {
            $retryAfter = $this->parseResponseRetryAfter($ex->getResponse());
            $this->messageBus->dispatch(new ExampleMessage(), [new DelayStamp($retryAfter)]);
        } 
    }
}
```
Message is interpreted as a new message, previous retries, stamps,... are discarded.

After:
```php
#[AsMessageHandler]
class ExampleMessageHandler
{
    public function __invoke(ExampleMessage $message): void
    {
        try {
            (new Client())->get('http://someapi');
        } catch (ServerException $ex) {
            $retryAfter = $this->parseResponseRetryAfter($ex->getResponse());
            throw new RecoverableMessageHandlingException(retryAfter: $retryAfter);
        }
    }
}
```
Message retains all of its previous stamps etc, but a delay stamp is added when the message can be retried again that may be larger (or smaller) than the default retry time.

**Comment by PawelPodkalicki** [comment]
I was trying to achieve the same goal. I think that I found a workaround. Instead of throwing an exception I dispatch a new messasge with stamps: `DelayStamp` and `RedeliveryStamp`. I get retry count for `RedeliveryStamp` from additional arguments (https://symfony.com/doc/current/messenger.html#additional-handler-arguments).

```
public function resolveAdditionalArgument(Envelope $envelope): array
{
    return ['retryCount' => RedeliveryStamp::getRetryCountFromEnvelope($envelope)];
}
```

Also maximal number of retries **must be checked** during exception handling. If exceeded, `UnrecoverableMessageHandlingException` should be thrown.

Redispatch (https://symfony.com/doc/current/messenger.html#redispatching-a-message) did not work because RedispatchMessageHandler does not pass stamps.

If anyone has better approach, please comment.
