### ISSUE TITLE
Configuration and enumNode not working with environmental variables

### ISSUE THREAD

**Issue by BigOHenry** [symfony/symfony#57958]
### Symfony version(s) affected

7.1

### Description

I have bundle configuration with enumNode, but it is not working: `The value "" is not allowed for path "cache.mode". Permissible values: "apcu", "file"`. But if i use scalarNode instead, everything is working without error and getting correct values from .env file

### How to reproduce

```
// Configuration.php
// this not working
$rootNode = $treeBuilder->getRootNode();
        $rootNode
            ->children()
                ->booleanNode('enabled')->isRequired()->end()
                ->enumNode('mode')->values(['apcu', 'file'])->isRequired()->end()
            ->end();
```

```
// .env.dev.local
EVO_CACHE_ENABLED=false
EVO_CACHE_MODE=file
```

```
// Configuration.php
// this works
$rootNode = $treeBuilder->getRootNode();
        $rootNode
            ->children()
                ->booleanNode('enabled')->isRequired()->end()
                ->scalarNode('mode')->isRequired()->end()
            ->end();
```

**Comment by stof** [comment]
This is because the value of an env placeholder is not known at the time the configuration is processed and validated (as the whole point is to keep it a placeholder to resolve it at runtime).
If you want to validate the allowed value while allowing it to be resolved at runtime, you need to perform that validation at runtime as well instead of using a build-time validation like the enum node.

**Comment by xabbuh** [comment]
closing as explained
