### ISSUE TITLE
[Form] Support dependent fields

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#5807]
We long have the problem of creating fields that depend on the value of other fields now. See also:
- #3767
- #3768
- #4548

I want to propose a solution that seems feasible from my current point of view.

Currently, I can think of two different APIs:
##### API 1

``` php
<?php

$builder->addIf(function (FormInterface $form) {
    return $form->get('field1')->getData() >= 1 
        && !$form->get('field2')->getData();
}, 'myfield', 'text');

$builder->addUnless(function (FormInterface $form) {
    return $form->get('field1')->getData() < 1 
        || $form->get('field2')->getData();
}, 'myfield', 'text');
```
##### API 2

``` php
<?php

$builder
    ->_if(function (FormInterface $form) {
        return $form->get('field1')->getData() >= 1 
            && !$form->get('field2')->getData();
    })
        ->add('myfield', 'text')
        ->add('myotherfield', 'text')
    ->_endif()
;

$builder
    ->_switch(function (FormInterface $form) {
        return $form->get('field1')->getData();
    })
    ->_case('foo')
    ->_case('bar')
        ->add('myfield', 'text', array('foo' => 'bar'))
        ->add('myotherfield', 'text')
    ->_case('baz')
        ->add('myfield', 'text', array('foo' => 'baz'))
    ->_default()
        ->add('myfield', 'text')
    ->_endswitch()
;
```

The second API obviously is a lot more expressive, but also a bit more complicated than the first one.

Please give me your opinions on what API you prefer or whether you can think of further limitations in these APIs.
##### Implementation

The issue of creating dependencies between fields can be solved by a lazy dependency resolution graph like in the OptionsResolver.

During form prepopulation, the conditions are invoked with a `FormPrepopulator` object implementing `FormInterface`. When `FormPrepopulator::get('field')` is called, "field" is prepopulated. If "field" is also dependent on some condition, that condition will be evaluated now in order to construct "field". After evaluating the condition, fields are added or removed accordingly.

During form binding, the conditions are invoked with a `FormBinder` object, that also implements `FormInterface`. This object works like `FormPrepopulator`, only that it binds the fields instead of filling them with default data.

In both cases, circular dependencies can be detected and reported.

**Comment by afurculita** [comment]
@webmozart What is the status of this issue?

**Comment by Tobion** [comment]
Just read the ticket and you can see yourself what the status is.

**Comment by Glideh** [comment]
+1 for the API 2
Dependent fields are still a pain in the ass today.

**Comment by CyrilleGuimezanes** [comment]
+1 for the API 2 
Still blocked by dependent field....

**Comment by DavidBadura** [comment]
What do we need this API for? Dynamic forms can be done with events. I solved complex Forms (Multi-Step-Forms etc.) with events simply.

**Comment by CyrilleGuimezanes** [comment]
@DavidBadura An other solution can be a good tutorial/documentation adapted to Sonata Admin.

It's possible to find some article that do it with classic Symfony Forms but I didn't found any article for doing it inside a Admin Class/CRUDController.

Two articles:
https://www.adayinthelifeof.nl/2014/03/19/dynamic-form-modification-in-symfony2/
http://devlog.rolandow.com/2014/11/symfony-forms-dependent-selectboxes/

**Comment by Glideh** [comment]
Well, events allow powerful things to be done indeed.
But this dependent fields (lists most of the time) feature is a common need and would deserve some shortcut.
However the event subscriber still requires at least 50 lines of code for each dependent list:
Each time we have to implement at least the 3 `postSetData`, `preSetData`, `preSubmit` events with the `preSubmit` parameters "convertion"
And since we can't modify a field from the subscriber, it have to be configured entirely in the subscriber, which is not very readable from the related form definition (I mean if the field config is not repeated there).
This is without speaking about the usual ajax needed.

**Comment by psyray** [comment]
You coud try the ``choice_loader`` option
https://symfony.com/doc/current/reference/forms/types/choice.html#choice-loader

```
use Symfony\Component\Form\ChoiceList\Loader\CallbackChoiceLoader;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
// ...

$builder->add('constants', ChoiceType::class, array(
    'choice_loader' => new CallbackChoiceLoader(function() {
        return StaticClass::getConstants();
    }),
));
```

**Comment by vudaltsov** [comment]
@xabbuh , @stof , @HeahDude , this could be closed, I guess?
It's too late to implement. Otherwise one can do a PR on this.

**Comment by AdamReece-WebBox** [comment]
The event listener approach does not work when you have a chain of field dependency.

Example chain: (Entity)Project --(1-M)--> (Entity)ProjectManager --(Property)--> (array)GroupNames

In the form the user must pick a project first. They must then pick a project manager within that project. Thirdly they must pick a group name for that project manager. (If the project manager has no group names a text input is to be used instead.)

The [dynamic generation for submitted forms](https://symfony.com/doc/3.4/form/dynamic_form_modification.html#dynamic-generation-for-submitted-forms) guide works great for populating the "ProjectManager" entity field based in the "Project" entity, but the "groupName" choice field based on `$projectManager->getGroupNames()` never populates because apparently the "projectManager" field is null. (Even though the value for it is present in the HTTP POST data.)

This appears to happen because when the form modifier for the "project" field runs it replaces the "projectManager" field, thus the "POST_SUBMIT" event listener you had bound to it is lost. That will then mean the "POST_SUBMIT" for "projectManager" never runs to handle the "groupName" choice field.

I did try re-binding this event listener during the "PRE_SET_DATA" stage right after  (involves exposing the `FormBuilderInterface` to the callable) but this has no impact. I also tried adding the TBD fields (projectManager, groupName) as `HiddenType` before the modifiers happen, but obviously they're overwritten so that won't matter.

--

Here's an example snippet of attaching my modifiers at the end of the `buildForm()` function.
(`$this->modifiers` is an array of field keys containing an array of callable form modifier functions.)

```
// << Attach event listeners for registered form modifiers
if (is_array($formModifiers = $this->modifiers) && count($formModifiers) >= 1) {
   // var_dump(sprintf("Adding PRE_SET_DATA event for form."));
   $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($builder, $formModifiers) {

       foreach ($formModifiers as $field => $formModifiersForField) {
           if (!$field = trim($field)) {
               throw new \Exception("Field not specified.");
           }

           if (!is_array($formModifiersForField) || count($formModifiersForField) < 1) {
               throw new \Exception("Form modifiers not an array or empty.");
           }

           $getField = sprintf("get%s", ucfirst($field));

           foreach ($formModifiersForField as $formModifier) {
               if (!is_callable($formModifier)) {
                   throw new \Exception("Form modifier not callable.");
               }

               // var_dump(sprintf("Running PRE_SET_DATA event for \"%s\".", $field));
               $formModifier($event->getForm(), $event->getData()->$getField());

               if (!$builder->has($field)) {
                   $builder->add($field, HiddenType::class, [
                       "required"      => false,
                       "label"         => false,
                   ]);
               }

               // Tried re-binding the POST_SUBMIT per-field here, did not work.
               /*
               // var_dump(sprintf("Adding POST_SUBMIT event for \"%s\".", $field));
               $builder->get($field)->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) use ($field, $formModifier) {
                   // var_dump(sprintf("Running POST_SUBMIT event for \"%s\".", $field));
                   $formModifier($event->getForm()->getRoot(), $event->getForm()->getData());
               });
                */
           }
       }

   });

   foreach ($formModifiers as $field => $formModifiersForField) {
       if (!$field = trim($field)) {
           throw new \Exception("Field not specified.");
       }

       if (!is_array($formModifiersForField) || count($formModifiersForField) < 1) {
           throw new \Exception("Form modifiers not an array or empty.");
       }

       foreach ($formModifiersForField as $formModifier) {
           if (!is_callable($formModifier)) {
               throw new \Exception("Form modifier not callable.");
           }

           // Tried calling the form modifier for the entire form instead of per-field, did not work.
           // $formModifier($event->getForm(), $event->getForm()->getData());

           if (!$builder->has($field)) {
               $builder->add($field, HiddenType::class, [
                   "required"      => false,
                   "label"         => false,
               ]);
           }

           // var_dump(sprintf("Adding POST_SUBMIT event for \"%s\".", $field));
           $builder->get($field)->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) use ($field, $formModifier) {
               // var_dump(sprintf("Running POST_SUBMIT event for \"%s\".", $field));
               $formModifier($event->getForm()->getRoot(), $event->getForm()->getData());
           });
       }
   }

   /* Tried POST_SUBMIT per-field, did not work.
   // var_dump(sprintf("Adding POST_SUBMIT event for form."));
   $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) use ($builder, $formModifiers) {

       foreach ($formModifiers as $field => $formModifiersForField) {
           if (!$field = trim($field)) {
               throw new \Exception("Field not specified.");
           }

           if (!is_array($formModifiersForField) || count($formModifiersForField) < 1) {
               throw new \Exception("Form modifiers not an array or empty.");
           }

           $getField = sprintf("get%s", ucfirst($field));

           foreach ($formModifiersForField as $formModifier) {
               if (!is_callable($formModifier)) {
                   throw new \Exception("Form modifier not callable.");
               }

               // var_dump(sprintf("Running PRE_SET_DATA event for \"%s\".", $field));
               $formModifier($event->getForm(), $event->getData()->$getField());
           }
       }

   });
    */
}
// >> Attach event listeners for registered form modifiers
```

If I were to uncomment line `// var_dump(sprintf("Running POST_SUBMIT event for \"%s\".", $field));` I would see `"Running POST_SUBMIT event for "project"."` twice, but never for "projectManager".

**Comment by xabbuh** [comment]
I am closing here as I don't see this happening anytime unless someone comes up with a PR implementing this feature.
