### ISSUE TITLE
[DependencyInjection] Add support for autowiring parent contructor

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#58384]
It's common to have class that extends another:

```php
class Foobar
{
    public function __construct(
        private RouterInterface $router,
        private RequestStack $requestStack,
    ) {
    }
}

class Baz extends Foobar
{
    public function __construct(
        private EntityManagerInterface $em,
        RouterInterface $router,
        RequestStack $requestStack,
    ) {
        parent::__construct($router, $requestStack)
    }
}
```

But it's a bit boring to explicitly require in `Baz` all Foobar's arguments, and to feed them to `parent::__construct()` call.

So I propose something that could help us to reduce the boilerplate:

```php
class Baz extends Foobar
{
    public function __construct(
        private EntityManagerInterface $em,
        #[AutowireParentArguments]
        ...$randomVarName,
    ) {
        parent::__construct(...$randomVarName)
    }
}
```

https://3v4l.org/fLin8

When Symfony discovers an argument with the attribute `#[AutowireParentArguments]`, It'll search and re-use all arguments set in the parent constructor.

>[!WARNING]
> it has nothing to do with [abstract/parent service ](https://symfony.com/doc/current/service_container/parent_services.html)

>[!NOTE]
> I asked on [X](https://x.com/lyrixx/status/1838621969270608077) and people seems to like this idea

**Comment by alexandre-daubois** [comment]
I saw your post on X and I have to say I like it very much! It would be super nice to have this feature.

Should the word `Constructor` appear in the name of the attribute? Like `#[AutowireParentConstructorArgs]`, to be explicit. Maybe this is bikeshedding, I'm also comfortable with the current name. `AutowireParentArguments` _could_ suggest this can be used on any overriding method.

**Comment by GromNaN** [comment]
That's a nice alternative to [setter injection](https://symfony.com/doc/current/service_container/calls.html) for additional dependencies.

What you don't show is that the code duplication is more than the constructor argument names and types, it's also all the autowiring attributes that may be used in the parent class.

This should cascade if there is a 3rd level of inheritance, but would not work you call explicitly the constructor of a class which is not the parent class.

**Comment by gquemener** [comment]
Thanks for your proposal.

Allow me to raise the [Composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) card, as I see that move as a "risk" to promote inheritance, by simplifying its usage.

**Comment by lyrixx** [comment]
> Allow me to raise the [Composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) card, as I see that move as a "risk" to promote inheritance, by simplifying its usage.

Of course, I agree with you. but sometime, inheritance already exists in the project, and we have to deal with. And some other time, inheritance is also useful.

**Comment by derrabus** [comment]
I have migrated a few legacy projects to use DI and this feature would've been a game changer. Fat constructors and deep inheritance chains are indeed antipatterns, but sometimes supporting antipatterns can be part of a migration path towards a better architecture.

I would support this feature if it comes with a warning sign in our documentation.

**Comment by wouterj** [comment]
I like it from a "less characters to read/type" point of view.

But I have one reservation with this proposal: it'll create objects that only work nicely in a DI container. The constructor signature has very little information, which makes initializing the objects very difficult when doing it manually (aside from missing any form of static analysis).
I'm not sure we want to encourage creating PHP classes that must be used with the Symfony DI container to be initialized correctly (this is imho a major drawback of our existing setter/`@required` feature).

**Comment by alexander-schranz** [comment]
I see this kind of "extend" services a lot when doing project reviews @sulu and because people don't always follow "[Composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance)". We try to teach that service decoration should be used instead but extends is mostly more handy for them as they already has then all service from the parent in them.

What I see that there may are usecases where NOT all `Parent Services` are autowireable (because coming from a configuration) and I want to get them from a already defined service definition e.g.:

```php
        #[AutowireParentArguments('sulu_media.storage')]
        ...$randomVarName,
```

Not sure if the name `AutowireParentArguments` then longer make sense or just `#[AutowireArgumentsFromService('sulu_media.storage')]` or `TargetArguments` attribute name as it may not based longeron autowire feature.

In the most cases I did see such code the new service did overwrite the existing one.

So in most cases it would may be something like this:

```php
#[AsAlias('sulu_media.storage')] // overwrites existing service
class CustomStorage extends LocalStorage {
    public function __construct(
        private EntityManagerInterface $em,
        #[AutowireArgumentsFromService(service: 'sulu_media.storage')] // want parent defined args
        ...$randomVarName,
    ) {
        parent::__construct(...$randomVarName)
    }
}
```

Here we run now into the problem I want to overwrite `'sulu_media.storage'` but get all arguments from the parent / previous `'sulu_media.storage'` definition, so that may the tricky part with `AutowireArgumentsFromService` or whatever call them. 🤔

Just want to put my thoughts about this into here. That most services which I did seen being overwritten weren't even autowireable services instead third party services.

**Comment by alexander-schranz** [comment]
Maybe also something like the following make more sense in my case:

```php
#[Overwrite('sulu_media.storage')]
class CustomStorage extends LocalStorage {
    public function __construct(
        private EntityManagerInterface $em,
        #[OverwriteArguments()] 
        ...$randomVarName,
    ) {
        parent::__construct(...$randomVarName)
    }
}
```

---

**Update (edit to not spam)**:

I know you did write nothing todo with parent services but maybe parent services could be extended to support where the arguments should be placed via a new `ParentArguments` Attribute:

```php
#[AsAlias('sulu_media.storage')]
#[Parent('sulu_media.storage')]
class CustomStorage extends LocalStorage {
    public function __construct(
        private EntityManagerInterface $em,
        #[ParentArguments()] 
        ...$randomVarName,
    ) {
        parent::__construct(...$randomVarName)
    }
}
```

**Comment by faizanakram99** [comment]
The idea is good but probably at language level, not framework level. For one, it isn't type safe and would hurt testing. One would need to look up class hierarchies to instantiate a class in a test case.

**Comment by mmauksch** [comment]
Strongly disagree with this proposal. 
Here are my reasons:

- The parameters of the parent class are hard dependencies
- Hard dependencies must be filled by classes that depend on that parent (being a child of that class is also some kind of dependency)
- Which in turns leads to your class not only inheriting the parents functionality but also its dependencies.
- Having something like varargs for the parent dependencies HIDES these hard dependencies
- Going in the the perspective of a class depending on the child class with varags: How do I know which dependencies I need to provide? I would be forced to lookup the whole inheritance chain to find the proper dependencies to provide
- The same problems applies to a DI-Container like the one from symfony. This way it is not: Ok constructor requires these classes, let me get them for it. But it turns into: Ok let me check that class and all its parents.

Reducing the amount of boilerplate code (just passing on arguments to the parent constructor) might sound like a good idea in the first moment but I would strongly argue that in that case explicit definitions are clearer and therefor easier to reason about.

**Comment by stof** [comment]
I also vote -1 on this feature.

This kind of magic signature creates a not documented signature for your class (even worse if this is not an internal class, as this magic undocumented signature is now part of your public API covered by semver...).
And this makes code that works only through the DI container supporting that attribute (which is even more restricted than @wouterj's comment mentioning "a service container"). And it also makes that class incompatible with all static analysis tools out there.

side note, the suggested `#[AutowireArgumentsFromService(service: 'sulu_media.storage')] // want parent defined args` would not work as in your case, `sulu_media.storage` is an alias of your own service due to the `AsAlias` attribute, so you would be autowiring from yourselves. At the time autowiring and autoconfiguration runs, the original service definition does not exist anymore in the ContainerBuilder as it has been overriden.

**Comment by lyrixx** [comment]
Okay, let's close it. I agree this idea what a bit wild :)
