### ISSUE TITLE
[Config] FileLocator does not work in a phar

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#58708]
### Symfony version(s) affected

6.4.13

### Description

The code does not work anymore. This is due to https://github.com/symfony/symfony/commit/1866ba298942e835ac1f8214f2ee4d036a9f57b7#diff-d08f24bd2c3ea5b2215dc3e17072095e89f6f7b05ce634022e5ced0c8d648ac0L87

### How to reproduce

In symfony/symfony, on commit 1866ba298942e835ac1f8214f2ee4d036a9f57b7 and its parent e39f6a9622, add an `index.php`:

```php
#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Config\FileLocator;

$locator = new FileLocator();

$x = $locator->locate(__DIR__ . '/index.php');
dump($x);
```

execute it: ✅ 

now, use [box](https://github.com/box-project/box) to make a phar `box compile`, then execute it :x::

```
PHP Fatal error:  Uncaught Symfony\Component\Config\Exception\FileLocatorFileNotFoundException: The file "index.php" does not exist (in: "phar:///home/gregoire/dev/github.com/lyrixx/symfony/index.phar"). in phar:///home/gregoire/dev/github.com/lyrixx/symfony/index.phar/src/Symfony/Component/Config/FileLocator.php:71
Stack trace:
#0 phar:///home/gregoire/dev/github.com/lyrixx/symfony/index.phar/index.php(10): Symfony\Component\Config\FileLocator->locate()
#1 /home/gregoire/dev/github.com/lyrixx/symfony/index.phar(14): require('...')
#2 {main}
  thrown in phar:///home/gregoire/dev/github.com/lyrixx/symfony/index.phar/src/Symfony/Component/Config/FileLocator.php on line 71
```

**Comment by alexandre-daubois** [comment]
I'm not able to reproduce. Am I missing a step? Here's what I did:

```
$ symfony new phar --version=6.4
$ vim index.php # put your code snippet
$ box compile
$ php index.phar
^ "phar:///Users/.../phar/index.phar/index.php"
```

Using PHP 8.3.13 on macOS, in caser that matters.

**Comment by joelwurtz** [comment]
It should be 

```php
#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Config\FileLocator;

$locator = new FileLocator();

$x = $locator->locate(__DIR__ . '/index.php');
dump($x);
```

**Comment by lyrixx** [comment]
I edited my initial issue. thanks

**Comment by michalananapps** [comment]
When invoking `index.phar`, the file path is represented as `phar:///Users/user/symfony/phar/index.phar/index.php`.
In the case of `index.php`, it appears as `/Users/user/symfony/phar/index.php`.

Previously, the `parse_url` result within `\Symfony\Component\Config\FileLocator::isAbsolutePath` for paths inside a phar archive evaluated to false. After a change, the parse_url result is compared with null, causing the path `phar:///Users/user/symfony/phar/index.phar/index.php` to no longer be treated as an absolute path, and the locate method continues further.

`phar:///...` is probably considered as seriously malformed URL by `parse_url` due to triple slash.

**Comment by alexandre-daubois** [comment]
I'm having a look for the fix
