### ISSUE TITLE
32310ff is an API breaking change

### ISSUE THREAD

**Issue by chx** [symfony/symfony#59003]
### Symfony version(s) affected

v7.1.8 v7.1.7 v6.4.15 v6.4.14 v5.4.46

### Description

https://github.com/symfony/http-foundation/commit/32310ff3aa8126ede47168fc9d9ae4a33b09c3a2 is an API breaking change and as such it should not be in any released branches.

### How to reproduce

There's not much to reproduce, is there? The code is working... it just doesn't belong where it was committed.

As an example, https://web.archive.org/web/20241127071118/https://www.smartsheet.com/customers/stegh if you search for Learn more online then you will find a URL in the real world which was entered with a space at the end and you can observe how browsers are fine with it. 

Once again, the question is not whether the commit does the right thing, the problem is it broke systems depending on the previous behavior. 

### Possible Solution

Roll it back from released branches.

**Comment by nicolas-grekas** [comment]
The previous behavior could be abused and led to https://symfony.com/blog/cve-2024-50345-open-redirect-via-browser-sanitized-urls
I understand this is a BC break, but we allow them when it's to fix a security issue, and that's the case here.
Sorry this broke something for you.

**Comment by chx** [comment]
@nicolas-grekas 

https://semver.org/

> Major version X (X.y.z | X > 0) MUST be incremented if any backward incompatible changes are introduced to the public API. It MAY also include minor and patch level changes. Patch and minor versions MUST be reset to 0 when major version is incremented.

it does not say security is a get out of jail free card.

The way this should have been handled is to add a flag to `Request::createFromGlobals()` to run the security fixes and then in next major the flag can be dropped.

**Comment by nicolas-grekas** [comment]
The BC policy we stick to is documented here:
https://symfony.com/doc/current/contributing/code/bc.html

Adding a flag, the security issue would have remained open.

**Comment by chx** [comment]
Alright, I read it.

Here's how it starts:

>  That's why we promise you backward compatibility (BC) for all minor Symfony releases

It still does not say "all but security".

The security issue was with browsers. 

You still should have solved this in RequestFromGlobals and not the rest.

**Comment by xabbuh** [comment]
Our BC promise also states:

> Also note that backward compatibility breaks are tolerated if they are required to fix a security issue.

**Comment by wouterj** [comment]
We are very careful about backwards compatibility, which is why we have this very detailed backwards compatibility document clearly defining what we consider BC. Every bug fix changes behavior of code, which means it can be argued to be a backwards compatibility break.

We are also very careful with security issues, taking quite a bit of time in determining if something is a security issue (must be fixed in all supported versions) or security hardening (must follow normal deprecation/feature path).

In a very limited set of cases, we come to the conclusion that a security issue is important enough to be considered more than hardening and might come with an edge-case behavioral change. As shown by @xabbuh, we explicitly take care of this situation occurring in our BC promise.

---

Besides this, the `Request` class is not meant for request parsing. It is meant as an abstraction of the incoming HTTP request to a PHP application. As you've already proved, browsers handle incorrect URLs gracefully and strip the trailing whitespace. The PHP application will then receive a valid URL.

If you require URL parsing, we recommend using a dedicated URL parser like https://uri.thephpleague.com/ . If I remember correctly, that library also allows you to choose between URI standards, allowing you to choose a standard that doesn't consider whitespace invalid.
