### ISSUE TITLE
[HttpClient] HEAD request turns into PUT request since 7.2.0

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#59043]
### Symfony version(s) affected

7.2.0

### Description

Just upgraded one project to Symfony 7.2.0 and noticed an error with a `Psr18Client` wrapping a `CurlHttpClient`

The `HEAD` request actually turns into a `PUT` request.

### How to reproduce

```php
$response = (new Psr18Client(new CurlHttpClient()))
    ->sendRequest(new Request('HEAD', 'https://www.postb.in/1732890887317-...'));
``` 

![image](https://github.com/user-attachments/assets/a52c22f0-c8c5-4691-bb1d-8ce62874a8c8)

### Additional Context

This seems to be caused by https://github.com/symfony/symfony/pull/58856

Now the `CurlHttpClient` is sending a body as it seems: https://github.com/symfony/symfony/blob/4ed9d032c7b61ae49d526565bbc8fdbcf76d74c3/src/Symfony/Component/HttpClient/CurlHttpClient.php#L239

cc @KurtThiemann

**Comment by KurtThiemann** [comment]
After some initial testing, it seems like this happens if `CURLOPT_UPLOAD` is set to `true` after `CURLOPT_NOBODY` is set, without also setting `CURLOPT_CUSTOMREQUEST` to head. This is something I believe would have always happened when using the `CurlHttpClient` with an empty stream as body to send a `HEAD` request, but nobody ever noticed because why would you do that.

Would there be anything wrong with just always explicitly setting `CURLOPT_CUSTOMREQUEST` instead of only relying on things like `CURLOPT_UPLOAD` or `CURLOPT_NOBODY`?

**Comment by KurtThiemann** [comment]
(cc @nicolas-grekas )
Actually, no idea who's in charge here, but since you reviewed my original pr maybe you have some insight into how we should proceed to fix the issue.

I was able to verify that the issue can also occur when using the `CurlHttpClient` directly without the PSR-18 wrapper:
```php
$client = \Symfony\Component\HttpClient\HttpClient::create();

//This sends a PUT request
$client->request("HEAD", "http://localhost/", [
    "body" => function ($chunkSize) {
        return "";
    }
]);
```
While this is not something anyone would normally write, I don't think it should send a PUT request.
