### ISSUE TITLE
[3.0] [Form] Setting "empty_data" to "" still results in NULL

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#5906]
When setting the "empty_data" option of a text field to `""`, the submitted value is still converted to `null`.

```php
$form = $formFactory->createBuilder()
    ->add('task', 'text', array(
        'required' => false,
        'empty_data' => '',
    ))
    ->getForm();

if (isset($_POST[$form->getName()])) {
    $form->bind($_POST[$form->getName()]);

    var_dump($form->getData());
    die;
}
```

Actual result:

```
array (size=1)
  'task' => null
```

Expected result:

```
array (size=1)
  'task' => ""
```

**Comment by yannickl88** [comment]
I've also ran into this issue, what is the status of this?

**Comment by CRTX** [comment]
I've been running into this issue for quite a while, I just now found this bug ticket.

Is it really difficult implement a fix? It's seems like an important issue to have open for over two years.

**Comment by Galaxy** [comment]
May be U have a code in entity like this?

    * @Assert\NotNull()

**Comment by bobalazek** [comment]
+1

**Comment by nenadalm** [comment]
:+1:

**Comment by abguy** [comment]
+1

**Comment by craigh** [comment]
I would also like to see a solution to this. :+1:

**Comment by ewgRa** [comment]
#14955 cover this case without BC, but when '' returned from empty_data that is Closure, still will be null returned.

Case with closure can be covered by adding new param to options like 'empty_data_is_norm', I think it is not so often used case and can be documented at http://symfony.com/doc/current/cookbook/form/use_empty_data.html

**Comment by webmozart** [comment]
I don't think this can be solved reasonably in the current version of the Form component. Tagged for a future version.

**Comment by DancZer** [comment]
After 3 hours debugging here is the issue:

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Form.php#L1187

private function viewToNorm($value)
{
     $transformers = $this->config->getViewTransformers();

     if (!$transformers) {
         return '' === $value ? null : $value;
     }
     ....
}

The "text" and "textarea" form types don't have transformers, therefore when the $value is empty string the viewToNorm return null instead of ''. I'm not sure what is the best way to fix it, but default transformer for text fields should help.

**Comment by madmis** [comment]
Guys, any comments about this? Why?
```
if (!$transformers) {
     return '' === $value ? null : $value;
 }
```

**Comment by mkilmanas** [comment]
symfony/symfony 3.0 -> symfony/form 3.0 - still an issue :disappointed:

**Comment by fsevestre** [comment]
I'm in the exact same situation as @mkilmanas, using SF 3.0.2 and PHP7 with strict_types.

**Comment by JorisH** [comment]
+1

**Comment by webmozart** [comment]
For the record, this problem can be worked around with a custom type extension for TextType:

~~~php
class TextTypeEmptyDataExtension extends AbstractTypeExtension implements DataTransformerInterface
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ('' === $options['empty_data']) {
            $builder->addModelTransformer($this);
        }
    }
    
    public function getExtendedType()
    {
        return TextType::class;
    }
    
    public function transform($data)
    {
        return $data;
    }
    
    public function reverseTransform($data)
    {
        return empty($data) ? '' : $data;
    }
}
~~~

Register that class in the DIC with the tag `form.type_extension`. [Here's the documentation about that](http://symfony.com/doc/current/cookbook/form/create_form_type_extension.html).

**Comment by mickaelandrieu** [comment]
@webmozart thanks for the workaround. Any chance to see your suggest merged in Form component ? 
I mean, it's real bug: what the point if everyone have to create his own "TextareaType" extension to reflect common behavior needed by customers ?

**Comment by webmozart** [comment]
@mickaelandrieu Let's do this. The simplest and most efficient solution seems to be to let `TextType` implement `DataTransformerInterface` with the methods like above.

ping @HeahDude

**Comment by HeahDude** [comment]
Sounds good :)

**Comment by HeahDude** [comment]
@webmozart May be a BC break for any one extending `TextType` as it would require to implement the `DataMapperInterface` too, right ?

We  should probably do it in an extension until 3.4 though :/

Or maybe we could create a `StringType` implementing it and let the `TextType` call `getParent` on its class.

We could then trigger a deprecation in `TextType` if its parent is not implementing the interface suggesting to use `getParent` instead of extending the class, to be able to rename `StringType` to `TextType` in 4.0.

What do you think ?

**Comment by backbone87** [comment]
you already provide implementations for the interface, so extenders dont need to do it themselfes. the only BC breaks would be accidental overrides, if someone is using the same method names as DataTransformerInterface, but for another purpose.

**Comment by HeahDude** [comment]
@backbone87 of courses :) I believe I've spent to much time reading on this repository and now I've developed a BC break paranoia :fearful: so I forget about the fundamentals... thanks for taking the time to remind me it!

**Comment by HeahDude** [comment]
See #18357.

**Comment by seggen-ibuildings** [comment]
For people still on 2.8... It seems that `Form` implements some sort of default view transformer:
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Form.php#L1173

The simplest solution would be to write an `IdentityTransformer` (which just returns `$value`) and add it as a view transformer (`$builder->get('task')->addViewTransformer(new IdentityTransformer());`).

**Comment by HeahDude** [comment]
@seggen-ibuildings you're right (ref https://github.com/symfony/symfony/pull/18357#discussion_r57880321). But this looks more like an `AntiTransformer` :)

**Comment by seggen-ibuildings** [comment]
@HeahDude I have nothing personal against [Transformers](https://en.wikipedia.org/wiki/Transformers), so I am not Anti :P

The way I see it, `Form::viewToNorm()` is not the default transformer, but _contains_ the default transformer. That means that the identity transformation is not the default. Adding an identity transformer means overriding the default, which ensured that no transformation is performed. Does that make sense?

**Comment by HeahDude** [comment]
Absolutely! We're saying the same thing differently, but you're right this method defines the default transformer and uses it only when none is provided.

**Comment by Raffaello** [comment]
what is the purpose to transform an empty string to null?
  
**for my PoV is better delete that transformation with ternary operator that convert blank string to null
 and rely on `'empty_data'` option strictly.**

This one have to be fixed, possibly in an elegant way, 
otherwise php7.x type hints are not supported for form mappings. 
Especially when the attribute is not nullable. make no sense to have a setter to allow set an attribute to null when it will never be accepted by the DB schema. 

well anyway, 
workaround exists but are workaround, make over-complicated mapping a default value for a `TextType` when the string is blank and pass exactly the blank value that it is even specified in the documentation:
http://symfony.com/doc/current/reference/forms/types/text.html#empty-data

At least should be pointed out that it will be converted to `null` when the form mapping is triggered.

**Comment by Raffaello** [comment]
what is the purpose to transform an empty string to null?

for my PoV is better delete that transformation with ternary operator that convert blank string to null
and rely on 'empty_data' option strictly. Even more make no reliable at all the attribute empty_data.

So even for the types that needs null instead of blank set empty_data to null.

This one have to be fixed, possibly in an elegant way, 
otherwise php7.x type hints are not supported for form mappings. 
Especially when the attribute is not nullable. make no sense to have a setter to allow set an attribute to null when it will never be accepted by the DB schema.

well anyway, 
workaround exists but are workaround, make over-complicated mapping a default value for a TextType when the string is blank and pass exactly the blank value that it is even specified in the documentation:
http://symfony.com/doc/current/reference/forms/types/text.html#empty-data

At least should be pointed out that it will be converted to null when the form mapping is triggered.

thank you anyway

**Comment by amici** [comment]
Is this issue possibly fixed in 3.2? 
Because I don't get it with 3.2, while on 3.0.9 I do (tying a value "" to a form, sets the field to NULL, with empty_data being also set to "").

**Comment by HeahDude** [comment]
@amici indeed, this has been fixed in https://github.com/symfony/symfony/pull/18357 as of 3.1. In previous version you have to set a model transformer, better use an extension on TextType to do this globally.

**Comment by amici** [comment]
Thanks @HeahDude, I missed it in the changelog..  Until version update, I'm going with a form extension.
Thanks for fixing it as well!
