### ISSUE TITLE
`non-falsy-string` should be use over `non-empty-string` because `'0'` is considered true using the `empty()` php function

### ISSUE THREAD

**Issue by Crovitche-1623** [symfony/symfony#59132]
### Symfony version(s) affected

7.2.0

### Description

I saw that some `non-empty-string` type-hinting were added in Symfony 7.2. However, in some place, I think the `non-falsy-string` should be more appropriate because `'0'` is considered true when using the `empty()` php function.

see https://phpstan.org/writing-php-code/phpdoc-types#other-advanced-string-types

For instance the `getUserIdentifier` method: https://github.com/symfony/symfony/blob/4612ff2ce30ab0727e28613508f9e0553d40cdbb/src/Symfony/Component/Security/Core/User/UserInterface.php#L60

Maybe there are applications where `'0'` could be a valid user identifier.

### How to reproduce

Nothing to reproduce

**Comment by stof** [comment]
`non-empty-string` in phpstan means `is_string($value) && $value !== ''`. It does **not** mean that `!empty($value)` is true. And this is exactly what Symfony expects here

The comment by Ondrej in the phpstan-doctrine issue is because *your* code snippet uses `empty()` as check (and so you return a more specific type than a non-empty string).

The suggestion done in the title of the issue would precisely be the one **forbidding** to use `'0'` as a user identifier.

**Comment by Crovitche-1623** [comment]
That's right, I confused the 2 sorry

**Comment by Crovitche-1623** [comment]
@stoff However, regarding my issue in `phpstan-doctrine`, this doesn't change the fact that I needed to introduce a new custom doctrine type as doctrine ORM does not support a `minLength` parameter.

When upgrading from Symfony 7.1 to 7.2. If you use PHPStan, you must either create a custom doctrine type or add a condition to the getUserIdentifier() method:

e.g.
```php
    public function getUserIdentifier(): string
    {
        $username = $this->getUsername();

        if (null === $username || '' === $username) {
            throw new \LogicException('...');
        }

        return $username;
    }
```
