### ISSUE TITLE
symfony/phpunit-bridge: compatibility to PHPUnit > 9

### ISSUE THREAD

**Issue by jankal** [symfony/symfony#59253]
### Description

PHPUnit removed the currently used Listeners and replaced them with the new Event system - see [Release Announcement for Version 10 of PHPUnit](https://phpunit.de/announcements/phpunit-10.html).

I propose creating a new so-called [extension](https://docs.phpunit.de/en/11.5/extending-phpunit.html#extending-the-test-runner) in [`symfony/phpunit-bridge`](https://github.com/symfony/phpunit-bridge) to register event subscribers where listeners were used previously.

Additionally, I would like to propose an update of the `phpunit.xml.dist` config in `[symfony/recipes](https://github.com/symfony/recipes) to be comaptible to the new syntax.

**Comment by wouterj** [comment]
Hi! See #49069 for all discussions surrounding this.

In summary: Symfony 7.2 is compatible with PHPUnit 10+. When using any of these PHPunit features, you should not use the listener from the PhpunitBridge, but rely on PHPUnit's native handling of deprecations. Since PHPUnit 11.3, this is feature-complete with the features from the PhpunitBridge listener.

We are currently working on updating the recipes, documentation, etc about this (and updating Symfony's own testsuite to PHPUnit 11 as well). You can see a demo of the recommended set-up in my PR on the Symfony Demo: https://github.com/symfony/demo/pull/1549
