### ISSUE TITLE
Extract API from Implementation

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#6129]
Hi everyone,

We had this discussion before, but at a point when we didn't have composer yet. I would like to bring this topic up again now.
##### Problem (updated December 5, 2012)

I just had a longer discussion with @fago, who is currently integrating the Validator component into Drupal. For Drupal it is necessary to replace the translation mechanism used in the Validator component by a custom implementation. Even when implementing `Symfony\Component\Translation\TranslatorInterface` in their code, this still pulls in all of the Symfony Translation implementation (and its potential dependencies).

The same is true for any Symfony component/bundle/bridge. When someone wants to use A which relies on **B's interfaces**, and B relies on C and D, he needs to pull in A, B, C and D _and_ provide a custom implementation for B (that might depend on E and F). Lots of installed dependencies: A, B, C, D, Bcustom, E, F

```
         A
      .·´ `·.
     B     Bcustom
   .´`.     .´`.
  C    D   E    F
```
##### Proposal (updated January 7, 2013)

I would like to suggest and discuss a backwards compatible extraction of the Symfony API. In a nutshell, make it possible to use A which relies on B's interfaces but replace B with a custom implementation (i.e. only install A, Bcustom, E, F).

```
      A
      |
   Bcustom
    .´`.
   E    F
```
###### Implementation

```
api/
    Symfony/
        Component/
            Translation/
                TranslatorInterface.php
    composer.json [symfony/api]
src/
    Symfony/
        Component/
            Translation/
                Translator.php
                composer.json [symfony/translation, requires symfony/api, provides symfony/translation-implementation]
            Validator/
                composer.json [symfony/validator, requires symfony/api, suggests symfony/translation-implementation]
```
###### Example: Replacing the translator

```
Drupal/
    Translation/
        composer.json [drupal/translation, requires symfony/api, provides symfony/translation-implementation]
```

The package MUST NOT add `symfony/translation` to its "replace" section. Multiple implementations of the same interface are NOT mutually exclusive and CAN be used at the same time.
###### Example: Using the Validator with its simplistic default translator

``` json
{
    "require": {
        "symfony/validator": "2.2.*"
    }
}
```
###### Example: Using the Validator with the Symfony Translation component

``` json
{
    "require": {
        "symfony/validator": "2.2.*",
        "symfony/translation": "2.2.*"
    }
}
```
###### Example: Using the Validator with a custom implementation

``` json
{
    "require": {
        "symfony/validator": "2.2.*",
        "drupal/translation": "..."
    }
}
```

The API would comprise a _closed set_ of interfaces and classes of the components, that is:
- the top-level interface(s)
- the classes and interfaces that the top-level interface(s) refer to in type hints and `@return` tags
- the classes and interfaces that _these_ classes and interfaces refer to
- etc.

Because of composer, this change would be fully BC.
##### Benefits (updated December 5, 2012)
1. A Symfony component A can rely on interfaces of another component B without forcing the user to use B.
2. Other projects can depend on Symfony's interfaces with a lower barrier to entry.
3. The API clearly documents the stable part of the components (it is ideally guaranteed not to change)
4. The separation helps us to decouple our components more. For example, if a component A instantiates a class of another component B and thus requires "symfony/b", we can improve it to make use of DI so that it only depends on "symfony/api" instead.
##### Drawbacks (updated January 8, 2013)
1. One more composer package (symfony/api) has to be downloaded when using a Symfony component.
2. Core developers have to maintain interfaces in a separate directory.

Please let me know what you think.

**Comment by ostrolucky** [comment]
I think decoupling is one of the goals of Symfony 4.0? I think this is perfect opportunity to open discussion about this again. I welcome idea for something like `symfony/contracts`, it would help php ecosystem to implement established interfaces instead of writing their own. Ping @fabpot!

**Comment by xabbuh** [comment]
I am not sure if this is something that Symfony should do. For reusable interfaces across projects there already is the PHP FIG. This group is doing a good job in creating standards for components that need a common interface and we were always fast in implementing those interfaces.

**Comment by ostrolucky** [comment]
You are probably right, this is ideal job for php-fig, even though I'm not confident in their activity level. 

Anyway I investigated current situation and picked interfaces which might be useful for general purpose. I also found some which might seem they should belong to the list but are IMO too coupled to implementation:

~\Symfony\Component\EventDispatcher\EventDispatcherInterface~
\Symfony\Component\Lock\LockInterface
\Symfony\Component\PropertyAccess\PropertyAccessorInterface
\Symfony\Component\Serializer\SerializerInterface
\Symfony\Component\Serializer\Encoder\DecoderInterface
\Symfony\Component\Serializer\Encoder\EncoderInterface
\Symfony\Component\Serializer\Normalizer\NormalizerInterface
\Symfony\Component\Serializer\Normalizer\DenormalizerInterface
\Symfony\Component\Serializer\NameConverter\NameConverterInterface
\Symfony\Component\Templating\EngineInterface
~\Symfony\Component\Translation\TranslatorInterface~
~\Symfony\Component\Validator\Validator\ValidatorInterface~

As you see in the end there isn't many of them. It's mostly interfaces of Serializer, because they are lean enough.

Also I checked coupling of Validator to Translator and it seems it can be decoupled?

Anyway I would like to put the end to this old RFC and see official decision.

**Comment by xabbuh** [comment]
👎 for me to make this change.

@symfony/deciders What is your opinion on this topic?

**Comment by javiereguiluz** [comment]
If I'm right, this is what Laravel does in its "Contracts" package, which contains all the interfaces used in their framework: https://github.com/laravel/framework/tree/5.4/src/Illuminate/Contracts

**Comment by unkind** [comment]
@ostrolucky if one doesn't use Symfony at all, I don't see reason to use Symfony contracts. Symfony interfaces don't magically make things better. Moreover, they are designed for Symfony needs and they probably won't satisfy _your_ needs later, so you restrict yourself for no reason. Why people are so obsessed with frameworks, so they want to couple their projects with them as much as they can? What's the problem to make your own contracts? 

https://speakerdeck.com/jakzal/decoupling-from-the-framework — probably, you may find it interesting (by the way, @jakzal is Symfony maintainer).

**Comment by ostrolucky** [comment]
> Why people are so obsessed with frameworks so they want to couple their projects with them as much as they can? What's the problem to make your own contracts?

This makes me believe you don't understand point of this proposal at all? It's not coupling to a framework but opposite. Currently when you depend on Symfony interface you need to pull all components that depend on implementation. Point of not writing own interface is to allow people of your project to swap implementation with some other without writing adapter. For example Doctrine could adopt many interfaces from symfony serializer and you would be able to use implementations across these projects as you seem fit.

**Comment by nicolas-grekas** [comment]
I think there is value in having shared interfaces, as the FIG does.
In Symfony's case, some interface could be worth moving outside of their component (eg ServiceSubscriberInterface from DI)
BUT the FIG would be a better place to publish them.
I think right now, Symfony didn't embrace the mission of providing generic interfaces on their own.
Until that happens (if it does at all), I'm :-1: also because that'd mean added maintenance.

Instead, I stringly suggest people to contribute to the FIG to move useful stuff there.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because at least two core members voted against it. Thank you all for the discussion!

**Comment by unkind** [comment]
> It's not coupling to a framework but opposite
> Currently when you depend on Symfony interface you need to pull all components that depend on implementation.

We don't understand each other, because we use this term differently. I mean coupling between classes/interfaces, you talk about, in fact, composer packages. So when you start to use Symfony interfaces directly in your project you make coupling with Symfony. Symfony is a tool with its own restrictions, models, etc.

Let's say you depend on `EventDispatcherInterface` in your project. You decided to make your events immutable and exclude `setName`, `stopPropogation` from the `Event`? You can't do it. Because it's not yours contracts. So what's next? You come here and ask to change Symfony contracts, because it doesn't satisfy your needs now: #21827. So, you first couple with Symfony as much as possible and then you come to "fix" Symfony, because it doesn't meet your internal requirements.

**Comment by nicolas-grekas** [comment]
Continued in https://github.com/symfony/symfony/pull/27093
