### ISSUE TITLE
[Security] switch into a disabled user account

### ISSUE THREAD

**Issue by craue** [symfony/symfony#6306]
I'm looking for a way to disable a user account while still being able to switch into it as an admin. If that is just not possible currently, this can be considered to be a feature request.

**Comment by craue** [comment]
@saro0h, what kind of information are you thinking about?

**Comment by jaytaph** [comment]
It seems that this would mean that we should not check on the `AdvancedUserInterface` on certain conditions. And since "admin" is merely a name (ROLE_ADMIN), somehow the system should be aware of context of roles. I really like that the role-voter is based on the fact that it is absolutely not context-aware (ie: ROLE_* is whatever you want it to be in your app, and not imposed by the security component itself).

But maybe, the switchuser listener can just take the role (or roles) from the configuration. That would still leave the context up to the user. If this would be the implementation, I would like to see this feature as well.

**Comment by javiereguiluz** [comment]
Closing it as fixed sometime in the past.
