### ISSUE TITLE
[Form] Add "fieldset" type

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#6584]
I would like to add a convenience type "fieldset" which extends "form", renders as fieldset and has the "virtual" (or "inherit_data" after #6573) option set by default.

This should be implemented after #6573 is merged.

**Comment by asentner** [comment]
Happened by this post seeing if there was a plan to implement a FieldsetType. I too found https://github.com/adamquaile/AdamQuaileFieldsetBundle and also do not like the idea of a long array. 

Another way of implementing this could be with an anonymous function, that's how I chose to do it. Still thinking of other ways to implement this with what we already have available to us and curious to see what others may have come up with since this issue was created.

https://github.com/adamquaile/AdamQuaileFieldsetBundle inspired me. I had exactly what was done here but with the following changes: https://gist.github.com/asentner/c6f0e8ff8d4a38052137

**Comment by adamquaile** [comment]
@asentner That's a nice way of doing it. I don't really use this bundle much any more, but if you made that backwards-compatible with the array syntax from the bundle, it could be worth merging together.

**Comment by asentner** [comment]
@adamquaile I agree, that sounds great! I'll push a PR.

**Comment by psren** [comment]
Is this still under consideration?

**Comment by ro0NL** [comment]
@psren see https://github.com/symfony/symfony/pull/23663#issuecomment-332454382

 I tried a PR but it's rejected for now. Actually i see this issue for the first time :-) so it looks like there's a common need for it.

IMHO we should either close this issue or re-open the PR.

**Comment by xabbuh** [comment]
I agree with @ogizanagi (see https://github.com/symfony/symfony/pull/23663#issuecomment-318129478). So I am closing here.
