### ISSUE TITLE
[Routing] Generating URLs with host matching

### ISSUE THREAD

**Issue by zachbadgett** [symfony/symfony#6857]
Currently running into an issue with the new host matching when I'm trying to generate urls that requires me to pass in a host parameter.

``` ymal
InternalUserController:
    resource: "@ApiBundle/Controller/Internal/UserController.php"
    type: annotation
    host: "api.{domain}"

DashboardController:
    resource: "@DashboardBundle/Controller/DashboardController.php"
    type: annotation
    host: "{domain}"
```

The examples above work perfectly with the url matcher, but when needing to generate the url, it will require me to provide the domain parameter each time. I know this is how it's suppose to function, but it seems a bit annoying to require putting in the domain each time.

**Comment by stephanvierkant** [comment]
Still no update here?

I'm trying to use multiple domains and subdomains for one website. I think something like this should work:
```
usa:
    host: "acme.com"
    resource: "@WebsiteBundle/Controller/"
    type:     annotation
    defaults:
        country: "en"

netherlands:
    host: "acme.nl"
    resource: "@WebsiteBundle/Controller/"
    type:     annotation
    defaults:
        country: "nl"

europe:
    host: "{country}.acme.eu"
    resource: "@WebsiteBundle/Controller/"
    type:     annotation
```

**Comment by toaotc** [comment]
here's the update: https://github.com/toaotc/ToaFrameworkExtraBundle.git

your configuration:
```
toa_framework_extra:
    request:
        recycle_attributes:
            - country
```

**Comment by bonswouar** [comment]
Thanks for your little bundle @toaotc, that might be useful.

Though, there is no plan to include this kind of functionality in Symfony ?
I know this behavior is "normal" but it's not very user-friendly..

**Comment by Tetdoss** [comment]
You saved my life toatc ! Thanks for this bundle !

**Comment by alex88** [comment]
It seems also not possible, with multiple host requirements for different urls, generate a url from a domain to the other http://stackoverflow.com/questions/34687016/symfony-2-generate-route-with-domain-restrictions-from-another-domain

**Comment by toaotc** [comment]
@alex88 i assume you use the [toaotc/ToaFrameworkExtraBundle](https://github.com/toaotc/ToaFrameworkExtraBundle). the thing is that it recycles the `subdomain` from the request and so it overrides the defaults given in the route configuration. A quick win could be to use different parameter names like `subdomain0` and `subdomain1` f.e. in your route configurations to prevent the default override

**Comment by alex88** [comment]
I'm not, anyway, just figured out my issue is something different, the firewall wasn't actually being correctly matched and so it was generating the url for another domain, sorry

**Comment by conradkleinespel** [comment]
Any news on this issue ? Would you happen to know if any PRs are open for this ?

**Comment by nicolas-grekas** [comment]
About i18n use cases, #26143 should do it
We could add a special `_host` placeholder for the `api.{_host}` use case during URL generation.
If someone would like to submit a PR, please do so we could have a discussion on actual code.
Otherwise, let's close, this issue is getting old.

**Comment by noemi-salaun** [comment]
The problem is that the `Request::attributes` property contain a little bit of everything (from URL fragment to security configuration). As a result, we cannot simply transmit everything from `Request::attributes` into the context of the `UrlGenerator`. I imagine that changing the way the attributes are filled will create too much breaking changes.

The simplest would be to pass only attributes which respect a certain naming convention. A listener like the one offered by `toaotc/ToaFrameworkExtraBundle` or inspired from the `LocaleListener` whould be easy to implements.

I tried to use some special char like `api.{!domain}`  to express something like "here is my param `!domain`, I want you to keep it and forward it to the context of the request". But special char like that mess with the UrlMatcher.

```
'#^api\\.\\{\\!domain\\}$#sDi'
```

instead of

```
'#^api\\.(?P<domain>[^\\.]++)$#sDi'
```

when not using special char.

If we can find a good naming convention, I would gladly submit a PR for it

**Comment by chalasr** [comment]
Let's close as per https://github.com/symfony/symfony/issues/6857#issuecomment-368060166. PR still welcome.
