### ISSUE TITLE
[TwigBundle] Bundle inheritance is not supported for @ notation

### ISSUE THREAD

**Issue by vicb** [symfony/symfony#6919]
By looking at the [code](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L75), I am under the impression that the Bundle inheritance is not supported by the current code.

**Comment by wesleylancel** [comment]
@Tobion: sorry for duping. Is this something that might still be fixed or does it need to discussed first?

**Comment by veloxy** [comment]
Is this going to be fixed/what is the status on this? It has been open since 2013 ...

I'm running into this issue in several places, one of those places is the TwigBundle error views. I'm not able to override them with my own.

The docs [mention](https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-error-templates) I can override the error page views the same way you [override other bundle views](https://symfony.com/doc/current/templating/overriding.html). But this method only works with the "old" notation (`AcmeDemoBundle:Default:index.html.twig`), not with the @ notation. 

I can't find much about the @ notation in the docs either, it's not even mentioned in the [best practices](http://symfony.com/doc/current/best_practices/templates.html#template-locations).

Note that it works fine when the files are located in the `app/Resources/views/` directory, but not within a bundle that has `TwigBundle` as a parent.

Example:

```
src\
|_ SymfonyResources\
|__ TwigBundle\
|___ Resources\
|____ views\
|_____ Exception
|______ error.html.twig
|______ error404.html.twig
|______ ...
```

```php
<?php

namespace SymfonyResources\TwigBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class SymfonyResourcesTwigBundle extends Bundle
{
    public function getParent()
    {
        return 'TwigBundle';
    }
}
```

I believe this should work, but even non-symfony bundles are having the same issue. Nothing that uses the @ notation for templating is inheritable via another bundle.

**Comment by mvrhov** [comment]
What's more interesting is that when @ notation was introduced was said that his will be the recommended way of accessing the templates and the old one will be deprecated.
