### ISSUE TITLE
make RequestContext optional in generator and matcher

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#8705]
from #5895:

"
After discussion with @crell, we agreed that the RequestContext is a burden in reusing the routing component. That's because it only duplicates information of the Request and is not really useful without it anyway. Since we probably cannot remove it fully as it would be a big BC break, my idea is to make it optional. So the symfony generator and matcher both work with a RequestContext and a Request. I removed the RequestContextAwareInterface from the interfaces so a custom router does not need a RequestContext anymore. The default symfony generator/matcher still implements RequestContextAwareInterface but can also work with a Request. So UrlMatcher::match(Request) is now also possible. And the generator can use UrlGenerator::setRequest() instead of setContext().

I think it makes the routing more useable in symfony and more reusable for other libraries.
And it will probably make it easier to integrate content negotiation as matching a request directly with all it's metadata (like Accept header) is now possible.

One more point: symfony allowed to use matching a Request with #4363. But it's not integrated in symfony as symfonys router does not use it at all. And the important interfaces like the RouterInterface required the RequestContext anyway. So there was no way to use Request matching without RequestContext. This PR replaces the other extension point.

The only bc break is in terms of interfaces. People should be aware that RequestContextAwareInterface is not part of UrlGeneratorInterface/UrlMatcherInterface/RouterInterface anymore. And the RequestMatcherInterface was changed.
"

**Comment by fabpot** [comment]
Is it something we want to do?

**Comment by nicolas-grekas** [comment]
@fabpot I don't think so. Instead, I'd suggest to add the request's headers to the context so that people can use them in custom expressions if they want to; and others could implement a new matcher on top of Symfony's to add eg header negociation on top. The `RequestContext` provide decoupling with the actually type of request in use, that's neat.

**Comment by Tobion** [comment]
@nicolas-grekas We don't need decoupling from the request because there are defacto two existing solutions that cover everything: Symfony Request, PSR-7. The request context just makes it hard to use the routing component with eithher of them as it's something custom only relevant to the routing component. So it increases the learning curve.

**Comment by nicolas-grekas** [comment]
@Tobion we *already* have decoupling :) and we already have matchRequest(), BUT, we don't have matchPsr7Request. Instead of adding it, I'd prefer adding headers to `RequestContext` personally, that'd cover any potential need for heavy PSR7 users.

**Comment by Tobion** [comment]
Then you need to reinvent how to access headers from the context with a good API instead of using the existing standards. First of all it's not easy to get right with all the normalizations etc. Second of all, people need to learn a new API. Third, people can't use any of the existing libraries to deal with that, e.g. for content-negotiation.
