### ISSUE TITLE
[OptionResolver] Consider add the possibility of setting required fields dynamically using closures

### ISSUE THREAD

**Issue by marcospassos** [symfony/symfony#8918]
```php
$resolver->setRequired(array(
    'action',
    'resource' => function(Options $options) {
        return $options['action'] === 'replace';
    },
    'data' => function(Options $options) {
        return !isset($options['dataPath']);
    },
    'dataPath' => function(Options $options) {
        return !isset($options['data']);
    }
));
```

**Comment by HeahDude** [comment]
This is an old issue but it makes me wonder what kind of message would someone expect to read from a thrown exception with the above implementation ?

How to explicitly trace such a dynamic requirement ? It would be difficult to know when to fix it since the only information would be "The required [option] is missing". There might be a "why" which could be far more complex than in your example and/or nevertheless important to understand so you can avoid such error later on.

If the answer is as simple as "I wrote the code, I know how to fix it", then maybe you should ask yourself "Why do I need to set some options required with an `OptionsResolver` if I am the one who decides it and already know whether they should be required or not ??"

If you got through this possible mind f..., please consider that (IMHO) there are already (today) normalizers to do conditional requirements properly :
```php
use Symfony\Component\OptionsResolver\Exception\InvalidOptionsException;

$resolver->setDefaults(array(
    'resource' => null,
    'data' => null,
    'dataPath' => null,
));

$resolver->setRequired('action');
// can throw 'The required option "action" is missing', OK

$resolver->setNormalizer('resource', function (Options $options, $resource) {
    if ('replace' === $options['action'] && null === $resource) {
        throw new InvalidOptionsException('When "action" option is set to "replace", "resource" option is required');
        // you know what to do and why, OK
    }

    // you can perform some other checks before returning it normalized
    // or just return it as it is
    return $resource;
});

$dataNormalizer = function(Options $options, $data) {
    if (null === $options['dataPath'] && null === $options['data']) {
        throw new InvalidOptionsException('Either option "data" or "dataPath" needs to be set but none provided');
    }

    // may be handle some other cases, check the path...
    // instead of adding the normaliser twice as below
    return $data;
};

$resolver->setNormalizer('data', $dataNormalizer);
$resolver->setNormalizer('dataPath', $dataNormalizer);
```

Beside, in the original post example there is a mix of options as values and as keys in the array passed to `setRequired` which doesn't seem consistent.

Also missing required options are checked in `OptionsResolver::resolve()` when options are not yet resolved, which might be a problem when a requirement depends on lazy or normalized options.

The needed refactoring for this feature would be a counter performance against the actual implementation imo.

Maybe it's time to close this one, what do you think ? (ping @Tobion)

**Comment by backbone87** [comment]
I agree with @HeahDude, only the developer can throw a meaningful exception why an option is required in one case, but not in another one. Maybe his examples on how to solve this issue should be added to the symfony-docs.

But i think there is one mistake in @HeahDude example: when checking for $options['data'] and $options['dataPath'] in the last normalizer, i think there is an infinite loop.

**Comment by HeahDude** [comment]
@backbone87, thanks, I've updated the example.

**Comment by jakzal** [comment]
Closing as there's already a more powerful solution for this (as pointed out by @HeahDude).

**Comment by MichaelBrauner** [comment]
Thank you for sharing this. This really should be added to the symfony-docs. I will eventually create a PR for this.
