### ISSUE TITLE
[Form] Simplify request handling #2

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony#9032]
This is a follow-up ticket of #5493. Most of the functionality proposed there has already been implemented, except for automatic handling of requests:

``` php
$form = $this->createForm('my_form', null, array(
    'action' => $this->generateUrl('process_form'),
    'method' => 'POST',
    'request' => $request,
));

// no explicit handleRequest() or submit() anymore

if ($form->isValid()) {
    // process form
}
```

By adding an option guesser to the HttpFoundation extension, the "request" option could also be omitted.

``` php
$form = $this->createForm('my_form', null, array(
    'action' => $this->generateUrl('process_form'),
    'method' => 'POST',
));

if ($form->isValid()) {
    // process form
}
```

This behavior will **only** be active if a global "auto_submit" configuration is set to `true`. This configuration will be `false` by default (for existing applications) and `true` for new symfony-standard releases.

It will be possible to override the automatically set request by explicitly passing the "request" option as in the first code snippet.

At last, it will be possible to disable automatic request handling on a case-by-case basis by setting a "auto_submit" option to `false`:

``` php
$form = $this->createForm('my_form', null, array(
    'action' => $this->generateUrl('process_form'),
    'method' => 'POST',
    'auto_submit' => false,
));

// manually call handleRequest() or submit()

if ($form->isValid()) {
    // process form
}
```

**I need feedback:**

How should the new global configuration and the form option be named?
- auto_submit
- auto_handle_request

My opinion is that the first option is easier to understand, while the second is technically more correct.

**Comment by WouterJ** [comment]
The best practices no recommend to use `$form->isSubmitted() && $form->isValid()` in order to avoid exactly what is discussed here. So we can consider this discussion as finished.

As for the auto request binding: I think it makes sense and will improve DX.

**Comment by sstok** [comment]
It think it's important to understand what makes a form valid 🤔 can a form be valid when it's not submitted? As far as I know a Form is only validated when it's submitted.

So calling `isValid()` on a form that is not yet submitted should fail because the form is not valid.

But this may cause some unforeseen side-effects when someone only wants to check if a "has" valid data. What about adding a new option "invalid_when_unsubmitted"? Which marks a form invalid when it's not submitted, and adding a new argument to `isValid()` `$allowUnsubmitted` or adding a new method `isModelValid()` to indicate the is-valid state applies to Form model and not the form itself?

**Comment by xabbuh** [comment]
The `isValid()` method already throws an exception since Symfony 4.0. I am not convinced that we really need the auto-submission feature. I would prefer having to stay explicit here to avoid too much "magic" behaviour.

**Comment by stof** [comment]
I agree with you regarding the the auto-submission. That looks too magic.

**Comment by xabbuh** [comment]
Let's close here then. Thanks everyone for the discussion.
