### ISSUE TITLE
PUT request not responding to multipart/form-data

### ISSUE THREAD

**Issue by greatwitenorth** [symfony/symfony#9226]
In the recent build of Laravel it seems to not be responding to PUT requests that are encoded with multipart/form-data. It only works with application/x-www-form-urlencoded. I believe the http spec states that it should work no matter what you use. 

For example when sending a request using mulitpart/form-data I observe the following:

```
$d1 = file_get_contents("php://input")); // Contains the correct data
$d2 = Input::all(); // This returns an empty result
```

I tried to track it back through the code and the issue definitely seems to be the Symfony Request package and not the Laravel framework itself. The data never gets passed to the Input object in Laravel.

**Comment by shyandsy** [comment]
@fabpot 
the bug still there

**Comment by lmasforne** [comment]
@shyandsy can you confirm to me this bug still exist on Symfony 4 ?

**Comment by edwardselby** [comment]
We still can't read PUT natively in Symfony 4. Please don't force us to use FOS.

**Comment by Arkemlar** [comment]
@lmasforne 

> @shyandsy can you confirm to me this bug still exist on Symfony 4 ?

Yes it is.

**Comment by Arkemlar** [comment]
> We still can't read PUT using `multipart/form-data` in Symfony 4. `x-www` encoding works.

For me it is not an option since I need to post files combined with other data.

**Comment by Nek-** [comment]
Hello guys. I really think this will never be done directly in Symfony considering it's based on a PHP behavior that differs in case of PUT multipart/form-data. Supporting this would add a huge set of classes to make it work just like POST does. For a very edgy case.

Please consider implementing your own solution. This ticket should be close IMO as it is out of the scope of Symfony.

**Comment by Chekote** [comment]
@Nek- I agree that this should be fixed in PHP and not Symfony. But implementing support for form data decoding is not a huge amount of work. I already implemented it in #10381, but it was rejected by @fabpot because he (correctly) believes it should be fixed in PHP instead of having Symfony take on the responsibility of manually decoding form data.

**Comment by Chekote** [comment]
Here is the issue in PHP's bug tracker. It's 8 years old now. If you want it you should vote and weigh in here: https://bugs.php.net/bug.php?id=55815

**Comment by nicolas-grekas** [comment]
Closing as there is nothing to keep track of in the Symfony repo. See php bug above.

**Comment by nicolas-grekas** [comment]
ping @jpauli or @pmmaga maybe if you want to have a look at the PHP bug?

**Comment by DazDotOne** [comment]
I've been trying to figure out how to work with this issue without having to break RESTful convention and boy howdie, what a rabbit hole, let me tell you.

I'm adding this anywhere I can find in the hope that it  will help somebody out in the future.

I've just lost a day of development firstly figuring out that this was an issue, then figuring out where the issue lay.

As mentioned, this isn't a symfony (or laravel, or any other framework) issue, it's a limitation of PHP.

After trawling through a good few RFCs for php core, the core development team seem somewhat resistant to implementing anything to do with modernising the handling of HTTP requests. The issue was first reported in 2011, it doesn't look any closer to having a native  solution.

That said, I managed to find [this PECL extension](https://pecl.php.net/package/apfd). I'm not really very familiar with pecl, and couldn't seem to get it working using pear. but I'm using CentOS and Remi PHP which has a yum package.

I ran `yum install php-pecl-apfd` and it literally fixed the issue straight away (well I had to restart my docker containers but that was a given).

I believe there are other packages in various flavours of linux and I'm sure anybody with more knowledge of pear/pecl/general php extensions could get it running on windows or mac with no issue.

**Comment by rrenteria-dev** [comment]
Also lost a day of development like @DazDotOne 
Had to change the request to POST, breaking REST convention.

**Comment by DazDotOne** [comment]
@rrenteria-dev What OS are you using?

**Comment by Nek-** [comment]
@rrenteria-dev you can use `?_method=PATCH` at the end of the URL to change the method. [Learn more here](https://symfony.com/doc/4.1/reference/configuration/framework.html#configuration-framework-http-method-override)

But I also time to time lose a lot of time on this... I'm sure the PHP team would accept a fix 😬 .

**Comment by alireaza** [comment]
You can use this package:
https://github.com/alireaza/php-form-data

And this is a Laravel Service Provider for above package:
https://github.com/alireaza/laravel-form-data

**Comment by Nayte91** [comment]
> ping @jpauli or @pmmaga maybe if you want to have a look at the PHP bug?

As this issue begin to grind my gears, I would like to propose a RFC.
@nicolas-grekas or @dunglas do you have, in few seconds (I don't want to bother you), resources about the whole topic? I ofc have [the old RFC](https://bugs.php.net/bug.php?id=55815), and also [the HTTP/1.1 RFC](https://www.rfc-editor.org/rfc/rfc7231) and [its update](https://www.rfc-editor.org/rfc/rfc9110). Anything else should be known to begin? What on the PHP side?

**Comment by nicolas-grekas** [comment]
Please open a new issue if you want to discuss any idea, or send a PR if you have code of course.
My point here is that a comment on a closed issue is going to be lost.

**Comment by dimadeush** [comment]
@nicolas-grekas So it seems that currently we have only one way to change PUT request to the POST if we need, f.e., upload files, right?
Thanks in Advance

**Comment by derrabus** [comment]
Yes.

**Comment by derrabus** [comment]
I'm locking this issue to prevent further support questions.

Please read the PHP bug to learn why things are this way, use GitHub discussions if you need support or open a new issue if you have new ideas on how to tackle the problem.
