### ISSUE TITLE
[3.0] Splitting the HttpKernel component

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony#9406]
The HttpKernel component contains many classes and from time to time, someone wants to split it in several components.

It does not really brings us anything if the split components are not useable by themselves, but separating Kernel and HttpKernel is probably good to at least avoid confusing about the decoupling between bundles and the HTTP kernel itself.

Also, as things have been refactored a lot since 2.0, it's much clearer now to see where things can go in separate components. For instance, moving the Profiler/DataCollector classes to a new component is now possible as other classes do not depend on them anymore (at least in 3.0 as the TraceableEventDispatcher won't depend on the Profiler anymore).

So, here is my initial proposal for Symfony 3.0: we split the HttpKernel component into 3 separate components:

* **Kernel**:

   * Bundle/, Config/, DependencyInjection/, CacheClearer/, CacheWarmer/ directories
   * Kernel.php, KernelInterface.php

* **Profiler**:

   * Profiler/ and DataCollector/ directories
   * EventListener/ProfilerListener.php

* **HttpKernel**:

   * Controller/, Debug/, Event/, EventListener/, Exception/, Fragment/, HttpCache/, Log/ directories
   * Client.php, HttpKernel.php, HttpKernelInterface.php, TerminableInterface.php (to be merge with HttpKernelInterface in 3.0), UriSigner.php
   * rename KernelEvent to HttpKernelEvent and KernelEvents to HttpKernelEvents?

**Comment by simensen** [comment]
Are there more details about what is currently planned for Symfony 3 in how HttpKernel is going to be split out? From [the roadmap post](http://symfony.com/blog/symfony-3-0-the-roadmap) it hints that it will be split but it isn't explained in detail:

> ... (the HttpKernel is going to be split into several smaller ones -- the profiler for instance will be standalone; classes are moved from bundles to components; components are extracted from existing ones, ...)

I am still hoping that someday soon we'll be able to create Symfony Kernel applications that do not need to have any HTTP baggage implied.

If this is the direction Symfony 3 is already heading, awesome! I'd like to learn more. Is there code or ideas written down somewhere that I can take a look? I'm very much hoping that I can remove the HTTP baggage in the next major release of Sculpin.

If this isn't the direction that Symfony 3 is currently going, is it up for discussion? If not, I'll leave it be and deal with whatever. If it *is* still up for discussion, how can I get involved in that discussion? I think it would be better to get that ball rolling sooner rather than later.

---

I've let this sit for awhile as I knew I couldn't do anything in 2.x and so Sculpin was stuck with what is there currently. However, with the Symfony 3 on the horizon, I'm going to need to be updating Sculpin to use Symfony 3. Nothing would make me more happy than to be able to base Sculpin 3 around a Symfony Kernel that was *just a Kernel* and had nothing to do with HTTP at all.

Regardless of how this ultimately gets split out, I'd like to have an idea how I can prepare for working with Symfony 3's new Kernel-related components. Any and all information on the current direction would be greatly appreciated.
