### ISSUE TITLE
[Form] Allow to extend multiple form types

### ISSUE THREAD

**Issue by egeloen** [symfony/symfony#9507]
Hey!

Before Symfony 2.3, all form types use the `FormType` as base type allowing us to easily override all form types via a form type extension which uses `form` as parent extended type. Since Symfony 2.3, the button types have been introduced but they are a specific kind of types which don't use the `FormType` as base form. Because of that, we need to create two form types extension if we want to override all form types (one for the form & an other for the button).

IMO, since all types don't use the same base form (`FormType`), the form type extension should allow to override more than one type by returning a string (to maintain the BC) or an array of extended parent types. What do you think?

**Comment by webmozart** [comment]
I agree that's it a bit stupid to have to define several classes to apply a type extension to multiple types. However, the type extension mechanism is already quite a mess and I'd rather not add more functionality to it anymore. In fact, I would like type extensions to be simplified in 3.0 or 4.0.

So, since there *is* a solution that works right now (abstract type + subclasses) - even thought it's not th nicest one - I don't think this issue is critical.
