### ISSUE TITLE
[Routing] switch to RequestMatcher

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony#9781]
this will make it possible to do content type negotiation inside the Routing.
will try to implement this on todays train ride :)

/cc @couac @liuggio

**Comment by dbu** [comment]
Is this going to happen? In my opinion, it is weird to have the RouterInterface that uses the UrlMatcherInterface when we also have a RequestMatcherInterface. In places like the CMF chain router, things get complicated because of the different kind of matchers.

**Comment by Tobion** [comment]
Related to #14723

I think we can remove/deprecate the `match` method. We keep the `matchRequest` method and also provide `PsrRequestMatcherInterface::matchPsrRequest`. This should cover all cases:

- Optional PSR-7 support
- No hard dependency on HttpFoundation as people can alternatively use PSR-7
- No performance degration due to converting symfony request to psr-7, as the framework can keep using matchRequest by default

I'll work on that shortly.

**Comment by dbu** [comment]
@Tobion any chance for this to happen? we stumbled into a huge mess when trying to provide a generic router that only wants to be a request matcher - to implement RouterInterface, we must provide a match method which is not easy when your implementation needs requests. recreating the request from just a path is tricky (and breaks on paths like `//foo` as the request thinks its a url without protocol...) and risks information loss.

**Comment by Tobion** [comment]
I tried to implement my proposal. But I found no way to do so in a BC way as the matcher exposes too much internal state like protected properties. So the only way I see is the deprecate the several complete classes and provide alternatives. But changing those classes BC seems almost impossible.

**Comment by dbu** [comment]
well, my hope was that RouterInterface could stop providing UrlMatcherInterface but that would be not BC anyways. i guess we have to wait until a symfony version decides to be a bit more agressive with breaking BC to clean up old problems.

**Comment by fabpot** [comment]
Is it something we want to do?

**Comment by dbu** [comment]
I think it would make sense to simplify things here. There are currently too many different ways of matching: UrlMatcherInterface, RequestMatcherInterface and now also PsrRequestMatcherInterface. And then there is RouterInterface which unifies UrlMatcherInterface and the generator interface. I think Symfony should converge on one of those, or alternatively stop using the RouterInterface because it gives preference to the string method which is the least powerful.

I understand that there is flexibility in being able to use third party routing code with any of these input, but imho it would be better to provide adapters for those special cases and have the default way supported. As an example, the [ChainRouter](https://github.com/symfony-cmf/Routing/blob/master/src/ChainRouter.php) needs to be able to convert between string URL and Request and back to support all kind of routers. And that is without even supporting the PsrRequestMatcherInterface...

**Comment by nicolas-grekas** [comment]
It all depends on the use case. Matching against a `Request` object couples things to *that* Request type, so the current `UrlMatcherInterface` wraps the most complex and important part of an urlmatcher IMHO: matching the route tree as fast as possible. The rest is really fine by decoration, so the several interfaces make sense to me, SRP principle.
Also, someone having a string enough need for the use case need actually to make the change.
If this doesn't happen, better close IMHO.

**Comment by andig** [comment]
I'm late to the party but I think https://github.com/ratchetphp/Ratchet/issues/546 provides a use case: using routing to offer websockets and http on the same port.

**Comment by javiereguiluz** [comment]
After re-reading this discussion and the latest comment from Nicolas, I think it's better to close this as "won't fix". But don't worry! We can always reconsider this in the future if we have new use cases and feature requests. Thanks!
